{
  "abstract": [
    {
      "text": "Animations are not loaded from the scene file.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/doNotPlay"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SceneKit",
    "externalID": "c:@SCNSceneSourceAnimationImportPolicyDoNotPlay",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "doNotPlay"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SCNSceneSource",
        "text": "SCNSceneSource"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SCNSceneSourceAnimationImportPolicy",
        "text": "AnimationImportPolicy"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNSceneSourceAnimationImportPolicyDoNotPlay"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "doNotPlay"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "doNotPlay"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SCNSceneSource",
              "text": "SCNSceneSource"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SCNSceneSourceAnimationImportPolicy",
              "text": "AnimationImportPolicy"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To play animations stored in the scene file, load them manually using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/entryWithIdentifier:withClass:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/sceneTime": {
      "abstract": [
        {
          "text": "The current scene time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sceneTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/sceneTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sceneTime"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "sceneTime",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/scenetime"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource": {
      "abstract": [
        {
          "text": "An object that manages the data-reading tasks associated with loading scene contents from a file or data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSceneSource"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSource"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneSource",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy": {
      "abstract": [
        {
          "text": "Options for playing animations loaded from a scene file, used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/animationImportPolicy",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " key in options dictionaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationImportPolicy"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationImportPolicy"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneSource.AnimationImportPolicy",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/animationimportpolicy"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/doNotPlay": {
      "abstract": [
        {
          "text": "Animations are not loaded from the scene file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doNotPlay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceAnimationImportPolicy",
          "text": "AnimationImportPolicy"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/doNotPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAnimationImportPolicyDoNotPlay"
        }
      ],
      "role": "symbol",
      "title": "doNotPlay",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/animationimportpolicy/donotplay"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/play": {
      "abstract": [
        {
          "text": "Animations loaded from the scene file are immediately added to the scene and played once.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "play"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceAnimationImportPolicy",
          "text": "AnimationImportPolicy"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/play",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAnimationImportPolicyPlay"
        }
      ],
      "role": "symbol",
      "title": "play",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/animationimportpolicy/play"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playRepeatedly": {
      "abstract": [
        {
          "text": "Animations loaded from the scene file are immediately added to the scene and played repeatedly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playRepeatedly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceAnimationImportPolicy",
          "text": "AnimationImportPolicy"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playRepeatedly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAnimationImportPolicyPlayRepeatedly"
        }
      ],
      "role": "symbol",
      "title": "playRepeatedly",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/animationimportpolicy/playrepeatedly"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playUsingSceneTimeBase": {
      "abstract": [
        {
          "text": "Animations loaded from the scene file are immediately added to the scene and played according to the scene’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/sceneTime",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playUsingSceneTimeBase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceAnimationImportPolicy",
          "text": "AnimationImportPolicy"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playUsingSceneTimeBase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAnimationImportPolicyPlayUsingSceneTimeBase"
        }
      ],
      "role": "symbol",
      "title": "playUsingSceneTimeBase",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/animationimportpolicy/playusingscenetimebase"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/animationImportPolicy": {
      "abstract": [
        {
          "text": "An option for controlling the playback of animations in a scene file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animationImportPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNSceneSource",
          "text": "SCNSceneSource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNSceneSourceLoadingOption",
          "text": "LoadingOption"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/LoadingOption/animationImportPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneSourceAnimationImportPolicyKey"
        }
      ],
      "role": "symbol",
      "title": "animationImportPolicy",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/loadingoption/animationimportpolicy"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/entryWithIdentifier:withClass:": {
      "abstract": [
        {
          "text": "Loads and returns a specific object in the scene source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "entryWithIdentifier:withClass:"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/entryWithIdentifier:withClass:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "entryWithIdentifier:withClass:"
        }
      ],
      "role": "symbol",
      "title": "entryWithIdentifier:withClass:",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenesource/entrywithidentifier:withclass:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/play",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playRepeatedly",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playUsingSceneTimeBase"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNSceneSourceAnimationImportPolicyDoNotPlay"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicyDoNotPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/play",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playRepeatedly",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy/playUsingSceneTimeBase"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneSource/AnimationImportPolicy",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SCNSceneSourceAnimationImportPolicy",
                    "text": "SCNSceneSourceAnimationImportPolicy"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCNSceneSourceAnimationImportPolicyDoNotPlay"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1playRepeatedly/title",
          "value": "SCNSceneSourceAnimationImportPolicyPlayRepeatedly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1playRepeatedly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicyPlayRepeatedly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy/title",
          "value": "SCNSceneSourceAnimationImportPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1playUsingSceneTimeBase/title",
          "value": "SCNSceneSourceAnimationImportPolicyPlayUsingSceneTimeBase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1playUsingSceneTimeBase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicyPlayUsingSceneTimeBase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1play/title",
          "value": "SCNSceneSourceAnimationImportPolicyPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1play/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicyPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1sceneTime/title",
          "value": "sceneTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1sceneTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sceneTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1doNotPlay/title",
          "value": "SCNSceneSourceAnimationImportPolicyDoNotPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1AnimationImportPolicy~1doNotPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicyDoNotPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1animationImportPolicy/title",
          "value": "SCNSceneSourceAnimationImportPolicyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource~1LoadingOption~1animationImportPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSourceAnimationImportPolicyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource/title",
          "value": "SCNSceneSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneSource"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnscenesource/animationimportpolicy/donotplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnscenesource/animationimportpolicy/donotplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
