{
  "abstract": [
    {
      "text": "This notification is posted after an accessibility element gains focus. Post this notification using the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " function instead of an ",
      "type": "text"
    },
    {
      "code": "NSNotificationCenter",
      "type": "codeVoice"
    },
    {
      "text": " instance.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/focusedUIElementChanged"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSAccessibilityFocusedUIElementChangedNotification",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "focusedUIElementChanged"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@NSAccessibility",
        "text": "NSAccessibility"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
        "text": "Notification"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAccessibilityFocusedUIElementChangedNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "focusedUIElementChanged"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "focusedUIElementChanged"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@NSAccessibility",
              "text": "NSAccessibility"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
              "text": "Notification"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct": {
      "abstract": [
        {
          "text": "A namespace for accessibility symbols for AppKit apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibility"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibility"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification": {
      "abstract": [
        {
          "text": "The name of the notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Notification"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.Notification",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/announcementRequested": {
      "abstract": [
        {
          "text": "This notification is posted whenever an accessibility element needs to make an announcement to the user. This notification requires a ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary with the key ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/NotificationUserInfoKey/announcement",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and a localized string containing the announcement. To help an assistive app determine the importance of the announcement, add the appropriate ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/NotificationUserInfoKey/priority",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to the ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "announcementRequested"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/announcementRequested",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityAnnouncementRequestedNotification"
        }
      ],
      "role": "symbol",
      "title": "announcementRequested",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/announcementrequested"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationActivated": {
      "abstract": [
        {
          "text": "This notification is posted after the app has been activated. Post this notification using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead of an ",
          "type": "text"
        },
        {
          "code": "NSNotificationCenter",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationActivated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationActivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityApplicationActivatedNotification"
        }
      ],
      "role": "symbol",
      "title": "applicationActivated",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/applicationactivated"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationDeactivated": {
      "abstract": [
        {
          "text": "This notification is posted after the app has been deactivated.  Post this notification using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead of an ",
          "type": "text"
        },
        {
          "code": "NSNotificationCenter",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDeactivated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationDeactivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityApplicationDeactivatedNotification"
        }
      ],
      "role": "symbol",
      "title": "applicationDeactivated",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/applicationdeactivated"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationHidden": {
      "abstract": [
        {
          "text": "This notification is posted after the app is hidden. Post this notification using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead of an ",
          "type": "text"
        },
        {
          "code": "NSNotificationCenter",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityApplicationHiddenNotification"
        }
      ],
      "role": "symbol",
      "title": "applicationHidden",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/applicationhidden"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationShown": {
      "abstract": [
        {
          "text": "This notification is posted after the app is shown. Post this notification using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead of an ",
          "type": "text"
        },
        {
          "code": "NSNotificationCenter",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationShown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationShown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityApplicationShownNotification"
        }
      ],
      "role": "symbol",
      "title": "applicationShown",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/applicationshown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/created": {
      "abstract": [
        {
          "text": "This notification is posted after an accessibility element is created. Post this notification using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead of an ",
          "type": "text"
        },
        {
          "code": "NSNotificationCenter",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "created"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/created",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityCreatedNotification"
        }
      ],
      "role": "symbol",
      "title": "created",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/created"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/drawerCreated": {
      "abstract": [
        {
          "text": "This notification is posted after a drawer appears. Post this notification using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead of an ",
          "type": "text"
        },
        {
          "code": "NSNotificationCenter",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawerCreated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/drawerCreated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityDrawerCreatedNotification"
        }
      ],
      "role": "symbol",
      "title": "drawerCreated",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/drawercreated"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/focusedUIElementChanged": {
      "abstract": [
        {
          "text": "This notification is posted after an accessibility element gains focus. Post this notification using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead of an ",
          "type": "text"
        },
        {
          "code": "NSNotificationCenter",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusedUIElementChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/focusedUIElementChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFocusedUIElementChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "focusedUIElementChanged",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/focuseduielementchanged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/focusedWindowChanged": {
      "abstract": [
        {
          "text": "This notification is posted after the key window changes. Post this notification using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead of an ",
          "type": "text"
        },
        {
          "code": "NSNotificationCenter",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusedWindowChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/focusedWindowChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFocusedWindowChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "focusedWindowChanged",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/focusedwindowchanged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/helpTagCreated": {
      "abstract": [
        {
          "text": "This notification is posted after a help tag appears. Post this notification using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead of an ",
          "type": "text"
        },
        {
          "code": "NSNotificationCenter",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "helpTagCreated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/helpTagCreated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityHelpTagCreatedNotification"
        }
      ],
      "role": "symbol",
      "title": "helpTagCreated",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/helptagcreated"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/layoutChanged": {
      "abstract": [
        {
          "text": "This notification is posted after the UI changes in a way that requires the attention of an accessibility client. This notification should be accompanied by a ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary with the key ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/NotificationUserInfoKey/uiElements",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and an array containing the UI elements that have been added or changed. Post this notification using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead of an ",
          "type": "text"
        },
        {
          "code": "NSNotificationCenter",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/layoutChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityLayoutChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "layoutChanged",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/layoutchanged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/mainWindowChanged": {
      "abstract": [
        {
          "text": "This notification is posted after the main window changes. Post this notification using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead of an ",
          "type": "text"
        },
        {
          "code": "NSNotificationCenter",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mainWindowChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/mainWindowChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMainWindowChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "mainWindowChanged",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/mainwindowchanged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/moved": {
      "abstract": [
        {
          "text": "This notification is posted after an accessibility element moves. Post this notification using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead of an ",
          "type": "text"
        },
        {
          "code": "NSNotificationCenter",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/moved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityMovedNotification"
        }
      ],
      "role": "symbol",
      "title": "moved",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/moved"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/resized": {
      "abstract": [
        {
          "text": "This notification is posted after an accessibility element’s size changes. Post this notification using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead of an ",
          "type": "text"
        },
        {
          "code": "NSNotificationCenter",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/resized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityResizedNotification"
        }
      ],
      "role": "symbol",
      "title": "resized",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/resized"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/rowCollapsed": {
      "abstract": [
        {
          "text": "This notification is posted after a row collapses. Post this notification using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead of an ",
          "type": "text"
        },
        {
          "code": "NSNotificationCenter",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowCollapsed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/rowCollapsed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRowCollapsedNotification"
        }
      ],
      "role": "symbol",
      "title": "rowCollapsed",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/rowcollapsed"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/rowCountChanged": {
      "abstract": [
        {
          "text": "This notification is posted after a row is added or deleted. Post this notification using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function instead of an ",
          "type": "text"
        },
        {
          "code": "NSNotificationCenter",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowCountChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/rowCountChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRowCountChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "rowCountChanged",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notification/rowcountchanged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/NotificationUserInfoKey/announcement": {
      "abstract": [
        {
          "text": "The announcement as a localized string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "announcement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationUserInfoKey",
          "text": "NotificationUserInfoKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/NotificationUserInfoKey/announcement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityAnnouncementKey"
        }
      ],
      "role": "symbol",
      "title": "announcement",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notificationuserinfokey/announcement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/NotificationUserInfoKey/priority": {
      "abstract": [
        {
          "text": "A priority level that can help an assistive app determine how to handle the corresponding notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "priority"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationUserInfoKey",
          "text": "NotificationUserInfoKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/NotificationUserInfoKey/priority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityPriorityKey"
        }
      ],
      "role": "symbol",
      "title": "priority",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notificationuserinfokey/priority"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/NotificationUserInfoKey/uiElements": {
      "abstract": [
        {
          "text": "An array of elements for the notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uiElements"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationUserInfoKey",
          "text": "NotificationUserInfoKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/NotificationUserInfoKey/uiElements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUIElementsKey"
        }
      ],
      "role": "symbol",
      "title": "uiElements",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/notificationuserinfokey/uielements"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)": {
      "abstract": [
        {
          "text": "Sends a notification to any observing assistive apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "post"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "element"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "notification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityPostNotification"
        }
      ],
      "role": "symbol",
      "title": "post(element:notification:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/post(element:notification:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Notification-Names",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/announcementRequested",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationActivated",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationDeactivated",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationHidden",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationShown",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/created",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/drawerCreated",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/focusedWindowChanged",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/helpTagCreated",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/layoutChanged",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/mainWindowChanged",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/moved",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/resized",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/rowCollapsed",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/rowCountChanged"
      ],
      "title": "Notification Names"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSAccessibilityFocusedUIElementChangedNotification"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFocusedUIElementChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Notification-Names",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/announcementRequested",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationActivated",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationDeactivated",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationHidden",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/applicationShown",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/created",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/drawerCreated",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/focusedWindowChanged",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/helpTagCreated",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/layoutChanged",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/mainWindowChanged",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/moved",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/resized",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/rowCollapsed",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/rowCountChanged"
              ],
              "title": "Notification Names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSAccessibilityNotificationName",
                    "text": "NSAccessibilityNotificationName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSAccessibilityFocusedUIElementChangedNotification"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1resized/title",
          "value": "NSAccessibilityResizedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1resized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityResizedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1rowCountChanged/title",
          "value": "NSAccessibilityRowCountChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1rowCountChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRowCountChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1applicationHidden/title",
          "value": "NSAccessibilityApplicationHiddenNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1applicationHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityApplicationHiddenNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1applicationActivated/title",
          "value": "NSAccessibilityApplicationActivatedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1applicationActivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityApplicationActivatedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1post(element:notification:)/title",
          "value": "NSAccessibilityPostNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1post(element:notification:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityPostNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1NotificationUserInfoKey~1uiElements/title",
          "value": "NSAccessibilityUIElementsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1NotificationUserInfoKey~1uiElements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityUIElementsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1NotificationUserInfoKey~1priority/title",
          "value": "NSAccessibilityPriorityKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1NotificationUserInfoKey~1priority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityPriorityKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1rowCollapsed/title",
          "value": "NSAccessibilityRowCollapsedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1rowCollapsed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRowCollapsedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1applicationShown/title",
          "value": "NSAccessibilityApplicationShownNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1applicationShown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityApplicationShownNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1layoutChanged/title",
          "value": "NSAccessibilityLayoutChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1layoutChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityLayoutChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1focusedUIElementChanged/title",
          "value": "NSAccessibilityFocusedUIElementChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1focusedUIElementChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFocusedUIElementChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1drawerCreated/title",
          "value": "NSAccessibilityDrawerCreatedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1drawerCreated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityDrawerCreatedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1NotificationUserInfoKey~1announcement/title",
          "value": "NSAccessibilityAnnouncementKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1NotificationUserInfoKey~1announcement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityAnnouncementKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1created/title",
          "value": "NSAccessibilityCreatedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1created/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCreatedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1applicationDeactivated/title",
          "value": "NSAccessibilityApplicationDeactivatedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1applicationDeactivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityApplicationDeactivatedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1focusedWindowChanged/title",
          "value": "NSAccessibilityFocusedWindowChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1focusedWindowChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFocusedWindowChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1moved/title",
          "value": "NSAccessibilityMovedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1moved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityMovedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1helpTagCreated/title",
          "value": "NSAccessibilityHelpTagCreatedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1helpTagCreated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityHelpTagCreatedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification/title",
          "value": "NSAccessibilityNotificationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityNotificationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityNotificationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1announcementRequested/title",
          "value": "NSAccessibilityAnnouncementRequestedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1announcementRequested/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityAnnouncementRequestedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1mainWindowChanged/title",
          "value": "NSAccessibilityMainWindowChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1mainWindowChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityMainWindowChangedNotification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibility-swift.struct/notification/focuseduielementchanged"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsaccessibility-swift.struct/notification/focuseduielementchanged"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
