{
  "abstract": [
    {
      "text": "Constants that indicate the type of error for an ad network attribution operation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKANError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SKANError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct": {
      "abstract": [
        {
          "text": "An error that an ad network attribution operation returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKANError"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANError"
        }
      ],
      "role": "symbol",
      "title": "SKANError",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Constants that indicate the type of error for an ad network attribution operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/adNetworkIdMissing": {
      "abstract": [
        {
          "text": "The ad network identifier in the ad impression doesn’t match the value in the information property list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adNetworkIdMissing"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/adNetworkIdMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorAdNetworkIdMissing"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.adNetworkIdMissing",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/adnetworkidmissing"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionMissingRequiredValue": {
      "abstract": [
        {
          "text": "A required value is missing from a view-through ad impression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "impressionMissingRequiredValue"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionMissingRequiredValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorImpressionMissingRequiredValue"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.impressionMissingRequiredValue",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/impressionmissingrequiredvalue"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionNotFound": {
      "abstract": [
        {
          "text": "The system can’t find the ad impression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "impressionNotFound"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorImpressionNotFound"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.impressionNotFound",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/impressionnotfound"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionTooShort": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "impressionTooShort"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionTooShort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorImpressionTooShort"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.impressionTooShort",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/impressiontooshort"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidAdvertisedAppId": {
      "abstract": [
        {
          "text": "The App Store ID of the advertised app is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAdvertisedAppId"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidAdvertisedAppId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorInvalidAdvertisedAppId"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.invalidAdvertisedAppId",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/invalidadvertisedappid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidCampaignId": {
      "abstract": [
        {
          "text": "The campaign identifier that you provided is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCampaignId"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidCampaignId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorInvalidCampaignId"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.invalidCampaignId",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/invalidcampaignid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidConversionValue": {
      "abstract": [
        {
          "text": "The conversion value is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidConversionValue"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidConversionValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorInvalidConversionValue"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.invalidConversionValue",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/invalidconversionvalue"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidSourceAppId": {
      "abstract": [
        {
          "text": "The App Store ID of the app displaying the ad is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSourceAppId"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidSourceAppId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorInvalidSourceAppId"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.invalidSourceAppId",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/invalidsourceappid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidVersion": {
      "abstract": [
        {
          "text": "The SKAdNetwork version number is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVersion"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorInvalidVersion"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.invalidVersion",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/invalidversion"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/mismatchedSourceAppId": {
      "abstract": [
        {
          "text": "The source app identifier in the ad impression doesn’t match the app identifier in the source app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mismatchedSourceAppId"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/mismatchedSourceAppId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorMismatchedSourceAppId"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.mismatchedSourceAppId",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/mismatchedsourceappid"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.unknown",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/unknown"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unsupported": {
      "abstract": [
        {
          "text": "Your app attempted to use functionality that isn’t supported in the specified version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorUnsupported"
        }
      ],
      "role": "symbol",
      "title": "SKANError.Code.unsupported",
      "type": "topic",
      "url": "/documentation/storekit/skanerror-swift.struct/code/unsupported"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKANErrorDomain": {
      "abstract": [
        {
          "text": "A string that identifies the SKAdNetwork error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKANErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKANErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKANErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SKANErrorDomain",
      "type": "topic",
      "url": "/documentation/storekit/skanerrordomain"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-handling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKANErrorDomain",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct"
      ],
      "title": "Error handling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/adNetworkIdMissing",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionMissingRequiredValue",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionNotFound",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionTooShort",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidAdvertisedAppId",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidCampaignId",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidConversionValue",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidSourceAppId",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidVersion",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/mismatchedSourceAppId",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unknown",
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unsupported"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKANError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/adNetworkIdMissing",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionMissingRequiredValue",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionNotFound",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/impressionTooShort",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidAdvertisedAppId",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidCampaignId",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidConversionValue",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidSourceAppId",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/invalidVersion",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/mismatchedSourceAppId",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unknown",
                "doc://com.apple.storekit/documentation/StoreKit/SKANError-swift.struct/Code/unsupported"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-handling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKANErrorDomain"
              ],
              "title": "Error handling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKANError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code/title",
          "value": "SKANError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidConversionValue/title",
          "value": "SKANErrorInvalidConversionValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidConversionValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorInvalidConversionValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1unsupported/title",
          "value": "SKANErrorUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1unsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidSourceAppId/title",
          "value": "SKANErrorInvalidSourceAppId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidSourceAppId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorInvalidSourceAppId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1adNetworkIdMissing/title",
          "value": "SKANErrorAdNetworkIdMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1adNetworkIdMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorAdNetworkIdMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidAdvertisedAppId/title",
          "value": "SKANErrorInvalidAdvertisedAppId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidAdvertisedAppId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorInvalidAdvertisedAppId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1impressionTooShort/title",
          "value": "SKANErrorImpressionTooShort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1impressionTooShort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorImpressionTooShort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1mismatchedSourceAppId/title",
          "value": "SKANErrorMismatchedSourceAppId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1mismatchedSourceAppId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorMismatchedSourceAppId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1unknown/title",
          "value": "SKANErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1impressionNotFound/title",
          "value": "SKANErrorImpressionNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1impressionNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorImpressionNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANErrorDomain/title",
          "value": "SKANErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidCampaignId/title",
          "value": "SKANErrorInvalidCampaignId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidCampaignId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorInvalidCampaignId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidVersion/title",
          "value": "SKANErrorInvalidVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1invalidVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorInvalidVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1impressionMissingRequiredValue/title",
          "value": "SKANErrorImpressionMissingRequiredValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKANError-swift.struct~1Code~1impressionMissingRequiredValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKANErrorImpressionMissingRequiredValue"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skanerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skanerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
