{"sections":[],"identifier":{"url":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/removeAccountPolicy(_:fromCategory:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"removeAccountPolicy(_:fromCategory:)","modules":[{"name":"Open Directory"}],"externalID":"c:objc(cs)ODNode(im)removeAccountPolicy:fromCategory:error:","navigatorTitle":[{"kind":"identifier","text":"removeAccountPolicy:fromCategory:error:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeAccountPolicy","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"fromCategory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!) "},{"kind":"keyword","text":"throws"}],"role":"symbol","symbolKind":"method","platforms":[{"beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS","introducedAt":"10.10"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAccountPolicy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"policy","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s11AnyHashableV","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!, ","kind":"text"},{"text":"fromCategory","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"category","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SS","preciseIdentifier":"s:SS"},{"text":"!) ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["macOS"]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opendirectory/documentation/OpenDirectory","doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode"]]},"variants":[{"paths":["/documentation/opendirectory/odnode/removeaccountpolicy(_:fromcategory:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opendirectory/odnode/removeaccountpolicy(_:fromcategory:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"kind":"symbol","type":"topic","url":"/documentation/objectivec/bool"},"doc://com.externally.resolved.symbol/s:s11AnyHashableV":{"title":"AnyHashable","abstract":[{"text":"A type-erased hashable value.","type":"text"}],"url":"/documentation/Swift/AnyHashable","type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s11AnyHashableV","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnyHashable","kind":"identifier"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory":{"title":"Open Directory","role":"collection","abstract":[{"type":"text","text":"Authenticate users, and search for contact information in Open Directory and LDAP directories."}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory","url":"/documentation/opendirectory"},"doc://com.externally.resolved.symbol/c:objc(cs)NSDictionary":{"title":"NSDictionary","abstract":[{"text":"An object representing a static collection of key-value pairs, for use instead of a  constant in cases that require reference semantics.","type":"text"}],"url":"/documentation/foundation/nsdictionary","type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSDictionary","fragments":[{"text":"class ","kind":"text"},{"text":"NSDictionary","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","title":"Technologies","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.externally.resolved.symbol/s:SS":{"kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"title":"String","url":"/documentation/Swift/String","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"identifier":"doc://com.externally.resolved.symbol/s:SS"},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode":{"url":"/documentation/opendirectory/odnode","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode","kind":"symbol","navigatorTitle":[{"text":"ODNode","kind":"identifier"}],"abstract":[{"text":"An ","type":"text"},{"code":"ODNode","type":"codeVoice"},{"text":" object serves as a Cocoa wrapper for an Open Directory node.","type":"text"}],"type":"topic","role":"symbol","title":"ODNode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ODNode","kind":"identifier"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyCategoryType":{"kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ODPolicyCategoryType","kind":"identifier"}],"type":"topic","url":"/documentation/opendirectory/odpolicycategorytype","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyCategoryType","abstract":[],"navigatorTitle":[{"text":"ODPolicyCategoryType","kind":"identifier"}],"title":"ODPolicyCategoryType"},"doc://com.externally.resolved.symbol/c:objc(cs)NSError":{"title":"NSError","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","abstract":[{"type":"text","text":"Information about an error condition including a domain, a domain-specific error code, and application-specific information."}],"kind":"symbol","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSError"}],"type":"topic","url":"/documentation/foundation/nserror"},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/removeAccountPolicy(_:fromCategory:)":{"type":"topic","navigatorTitle":[{"text":"removeAccountPolicy:fromCategory:error:","kind":"identifier"}],"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/removeAccountPolicy(_:fromCategory:)","url":"/documentation/opendirectory/odnode/removeaccountpolicy(_:fromcategory:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeAccountPolicy","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!, ","kind":"text"},{"text":"fromCategory","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!) ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"removeAccountPolicy(_:fromCategory:)","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false},{"name":"macOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"10.10"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"value":"removeAccountPolicy:fromCategory:error:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"removeAccountPolicy:fromCategory:error:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opendirectory/documentation/OpenDirectory","doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeAccountPolicy:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"policy"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromCategory:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ODPolicyCategoryType","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyCategoryType","preciseIdentifier":"c:@T@ODPolicyCategoryType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"category"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSDictionary/abstract","value":[{"text":"A static collection of objects associated with unique keys.","type":"text"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode/title","op":"replace","value":"ODNode"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode/fragments","op":"replace","value":[{"kind":"identifier","text":"ODNode"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ODNode"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyCategoryType/title","op":"replace","value":"ODPolicyCategoryType"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyCategoryType/fragments","op":"replace","value":[{"text":"ODPolicyCategoryType","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyCategoryType/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ODPolicyCategoryType"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode~1removeAccountPolicy(_:fromCategory:)/title","op":"replace","value":"removeAccountPolicy:fromCategory:error:"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode~1removeAccountPolicy(_:fromCategory:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeAccountPolicy:fromCategory:error:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}