{"metadata":{"modules":[{"name":"Open Directory"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subnodeNames"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"externalID":"c:objc(cs)ODNode(im)subnodeNamesAndReturnError:","platforms":[{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.6","beta":false}],"title":"subnodeNames()","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"subnodeNamesAndReturnError:"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subnodeNames","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"An array of subnode names."}],"type":"paragraph"}],"kind":"content"},{"content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"In Swift, this method returns a nonoptional result and is marked with the ","type":"text"},{"type":"codeVoice","code":"throws"},{"text":" keyword to indicate that it throws an error in cases of failure.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You call this method in a "},{"code":"try","type":"codeVoice"},{"type":"text","text":" expression and handle any errors in the "},{"code":"catch","type":"codeVoice"},{"type":"text","text":" clauses of a "},{"code":"do","type":"codeVoice"},{"type":"text","text":" statement, as described in "},{"identifier":"https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html","isActive":true,"type":"reference"},{"type":"text","text":" in "},{"identifier":"https://docs.swift.org/swift-book/","isActive":true,"type":"reference"},{"type":"text","text":" and "},{"code":"About Imported Cocoa Error Parameters","type":"codeVoice"},{"type":"text","text":"."}]}],"type":"aside","name":"Handling Errors in Swift","style":"note"}],"kind":"content"}],"abstract":[{"type":"text","text":"Returns the names of subnodes for the node."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opendirectory/documentation/OpenDirectory","doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/subnodeNames()"},"sections":[],"kind":"symbol","seeAlsoSections":[{"generated":true,"anchor":"Querying-a-Node","identifiers":["doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/customCall(_:send:)","doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/nodeDetails(forKeys:)","doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/nodeName","doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/unreachableSubnodeNames()"],"title":"Querying a Node"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opendirectory/odnode/subnodenames()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opendirectory/odnode/subnodenames()"]}],"references":{"doc://com.externally.resolved.symbol/c:objc(cs)NSError":{"title":"NSError","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","abstract":[{"type":"text","text":"Information about an error condition including a domain, a domain-specific error code, and application-specific information."}],"kind":"symbol","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSError"}],"type":"topic","url":"/documentation/foundation/nserror"},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/nodeName":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nodeName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/nodeName","url":"/documentation/opendirectory/odnode/nodename","abstract":[{"text":"The node’s name.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"nodeName","kind":"identifier"}],"title":"nodeName","type":"topic"},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode":{"url":"/documentation/opendirectory/odnode","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode","kind":"symbol","navigatorTitle":[{"text":"ODNode","kind":"identifier"}],"abstract":[{"text":"An ","type":"text"},{"code":"ODNode","type":"codeVoice"},{"text":" object serves as a Cocoa wrapper for an Open Directory node.","type":"text"}],"type":"topic","role":"symbol","title":"ODNode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ODNode","kind":"identifier"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/customCall(_:send:)":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/customCall(_:send:)","navigatorTitle":[{"text":"customCall:sendData:error:","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the result of a custom call to the node."}],"title":"customCall(_:send:)","url":"/documentation/opendirectory/odnode/customcall(_:send:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customCall","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"send","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"!) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/nodeDetails(forKeys:)":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/nodeDetails(forKeys:)","navigatorTitle":[{"text":"nodeDetailsForKeys:error:","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns a dictionary containing details about a node."}],"title":"nodeDetails(forKeys:)","url":"/documentation/opendirectory/odnode/nodedetails(forkeys:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nodeDetails","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKeys"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"text":"]!) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/unreachableSubnodeNames()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unreachableSubnodeNames","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/unreachableSubnodeNames()","url":"/documentation/opendirectory/odnode/unreachablesubnodenames()","abstract":[{"text":"Returns an array of the subnodes of a given node that are currently unreachable.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"unreachableSubnodeNamesAndReturnError:"}],"title":"unreachableSubnodeNames()","type":"topic"},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/subnodeNames()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subnodeNames","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/subnodeNames()","url":"/documentation/opendirectory/odnode/subnodenames()","abstract":[{"text":"Returns the names of subnodes for the node.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"subnodeNamesAndReturnError:","kind":"identifier"}],"title":"subnodeNames()","type":"topic"},"https://docs.swift.org/swift-book/":{"url":"https://docs.swift.org/swift-book/","identifier":"https://docs.swift.org/swift-book/","titleInlineContent":[{"type":"text","text":"The Swift Programming Language"}],"type":"link","title":"The Swift Programming Language"},"https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html":{"url":"https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html","identifier":"https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html","titleInlineContent":[{"type":"text","text":"Error Handling"}],"type":"link","title":"Error Handling"},"doc://com.externally.resolved.symbol/c:objc(cs)NSArray":{"title":"NSArray","url":"/documentation/foundation/nsarray","fragments":[{"text":"class ","kind":"text"},{"kind":"identifier","text":"NSArray"}],"abstract":[{"type":"text","text":"An object representing a static ordered collection, for use instead of an  constant in cases that require reference semantics."}],"role":"symbol","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSArray","kind":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory":{"title":"Open Directory","role":"collection","abstract":[{"type":"text","text":"Authenticate users, and search for contact information in Open Directory and LDAP directories."}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory","url":"/documentation/opendirectory"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","title":"Technologies","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"role":"overview"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"unavailable":false,"introducedAt":"10.6","name":"macOS","beta":false,"deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"subnodeNamesAndReturnError:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"subnodeNamesAndReturnError:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opendirectory/documentation/OpenDirectory","doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/customCall(_:send:)","doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/nodeDetails(forKeys:)","doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/nodeName","doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode/unreachableSubnodeNames()"],"title":"Querying a Node","generated":true,"anchor":"Querying-a-Node"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSArray","preciseIdentifier":"c:objc(cs)NSArray","text":"NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"subnodeNamesAndReturnError:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"outError","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}]},"path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","op":"add","value":{"parameters":[{"name":"outError","content":[{"type":"paragraph","inlineContent":[{"text":"An error reference for error details. Can be ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}]}]}],"kind":"parameters"}},{"op":"replace","value":{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"text":"An array of subnode names.","type":"text"}],"type":"paragraph"}],"kind":"content"},"path":"/primaryContentSections/2"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode~1nodeName/title","op":"replace","value":"nodeName"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode~1nodeName/fragments","op":"replace","value":[{"kind":"identifier","text":"nodeName"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode/title","op":"replace","value":"ODNode"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode/fragments","op":"replace","value":[{"kind":"identifier","text":"ODNode"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ODNode"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode~1customCall(_:send:)/title","op":"replace","value":"customCall:sendData:error:"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode~1customCall(_:send:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"customCall:sendData:error:"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode~1nodeDetails(forKeys:)/title","op":"replace","value":"nodeDetailsForKeys:error:"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode~1nodeDetails(forKeys:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"nodeDetailsForKeys:error:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode~1unreachableSubnodeNames()/title","op":"replace","value":"unreachableSubnodeNamesAndReturnError:"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode~1unreachableSubnodeNames()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"unreachableSubnodeNamesAndReturnError:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode~1subnodeNames()/title","op":"replace","value":"subnodeNamesAndReturnError:"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode~1subnodeNames()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"subnodeNamesAndReturnError:"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSArray/abstract","op":"replace","value":[{"type":"text","text":"A static ordered collection of objects."}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}