{
  "abstract": [
    {
      "text": "Scrolls to the containing view to make the text range visible.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/scrollRangeToVisible:inDocument:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITextSearching(im)scrollRangeToVisible:inDocument:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "scrollRangeToVisible:inDocument:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "scrollRangeToVisible:inDocument:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "scrollRangeToVisible:inDocument:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "scrollRangeToVisible:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UITextRange",
              "text": "UITextRange"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "inDocument:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchDocumentIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UITextSearchDocumentIdentifier",
              "text": "UITextSearchDocumentIdentifier"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "document"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The text range to scroll to.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "range"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A string that uniquely identifies the document containing the text range. ",
                  "type": "text"
                },
                {
                  "code": "Nil",
                  "type": "codeVoice"
                },
                {
                  "text": " when searching a single document.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "document"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the seachable object supports scrolling, use this method to implement scrolling your view to make the highlighted text range visible.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextRange": {
      "abstract": [
        {
          "text": "A range of characters in a text container with a starting index and an ending index in string backing a text-entry object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextRange"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextRange"
        }
      ],
      "role": "symbol",
      "title": "UITextRange",
      "type": "topic",
      "url": "/documentation/uikit/uitextrange"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchDocumentIdentifier": {
      "abstract": [
        {
          "text": "A string that uniquely identifies a specific document when searching for matching text across multiple documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextSearchDocumentIdentifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchDocumentIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextSearchDocumentIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchdocumentidentifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq": {
      "abstract": [
        {
          "text": "The methods you use on a find session’s searchable objects to perform search operations and decorate the found text results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextSearching"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextSearching",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/clearAllDecoratedFoundText": {
      "abstract": [
        {
          "text": "Clears the style from all found and highlighted results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "clearAllDecoratedFoundText"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/clearAllDecoratedFoundText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clearAllDecoratedFoundText"
        }
      ],
      "role": "symbol",
      "title": "clearAllDecoratedFoundText",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/clearalldecoratedfoundtext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/decorateFoundTextRange:inDocument:usingStyle:": {
      "abstract": [
        {
          "text": "Applies the style to a specific text range to indicate found and highlighted results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "decorateFoundTextRange:inDocument:usingStyle:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/decorateFoundTextRange:inDocument:usingStyle:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "decorateFoundTextRange:inDocument:usingStyle:"
        }
      ],
      "role": "symbol",
      "title": "decorateFoundTextRange:inDocument:usingStyle:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/decoratefoundtextrange:indocument:usingstyle:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/scrollRangeToVisible:inDocument:": {
      "abstract": [
        {
          "text": "Scrolls to the containing view to make the text range visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "scrollRangeToVisible:inDocument:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/scrollRangeToVisible:inDocument:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollRangeToVisible:inDocument:"
        }
      ],
      "role": "symbol",
      "title": "scrollRangeToVisible:inDocument:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/scrollrangetovisible:indocument:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/willHighlightFoundTextRange:inDocument:": {
      "abstract": [
        {
          "text": "Informs the searchable object when the highlighted search result is about to change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "willHighlightFoundTextRange:inDocument:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/willHighlightFoundTextRange:inDocument:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willHighlightFoundTextRange:inDocument:"
        }
      ],
      "role": "symbol",
      "title": "willHighlightFoundTextRange:inDocument:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/willhighlightfoundtextrange:indocument:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Displaying-results",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/decorateFoundTextRange:inDocument:usingStyle:",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/clearAllDecoratedFoundText",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/willHighlightFoundTextRange:inDocument:"
      ],
      "title": "Displaying results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextRange/title",
          "value": "UITextRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextsearching-53wjq/scrollrangetovisible:indocument:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
