{
  "abstract": [
    {
      "text": "The frame in which to display the new content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction/targetFrame"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKNavigationAction(py)targetFrame",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "targetFrame"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)WKFrameInfo",
        "text": "WKFrameInfo"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "targetFrame"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "targetFrame"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@NSCopying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "targetFrame"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKFrameInfo",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WKFrameInfo",
              "text": "WKFrameInfo"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the target of the navigation is a new window, this property is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKFrameInfo": {
      "abstract": [
        {
          "text": "An object that contains information about a frame on a webpage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKFrameInfo"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKFrameInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKFrameInfo"
        }
      ],
      "role": "symbol",
      "title": "WKFrameInfo",
      "type": "topic",
      "url": "/documentation/webkit/wkframeinfo"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction": {
      "abstract": [
        {
          "text": "An object that contains information about an action that causes navigation to occur.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKNavigationAction"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKNavigationAction"
        }
      ],
      "role": "symbol",
      "title": "WKNavigationAction",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationaction"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction/request": {
      "abstract": [
        {
          "text": "The URL request object associated with the navigation action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "request"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction/request",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "request"
        }
      ],
      "role": "symbol",
      "title": "request",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationaction/request"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction/shouldPerformDownload": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the web content provided an attribute that indicates a download.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldPerformDownload"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction/shouldPerformDownload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldPerformDownload"
        }
      ],
      "role": "symbol",
      "title": "shouldPerformDownload",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationaction/shouldperformdownload"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction/sourceFrame": {
      "abstract": [
        {
          "text": "The frame that requested the navigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKFrameInfo",
          "text": "WKFrameInfo"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction/sourceFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceFrame"
        }
      ],
      "role": "symbol",
      "title": "sourceFrame",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationaction/sourceframe"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction/targetFrame": {
      "abstract": [
        {
          "text": "The frame in which to display the new content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "targetFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKFrameInfo",
          "text": "WKFrameInfo"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction/targetFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "targetFrame"
        }
      ],
      "role": "symbol",
      "title": "targetFrame",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationaction/targetframe"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-navigation-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction/request",
        "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction/sourceFrame",
        "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction/shouldPerformDownload"
      ],
      "title": "Inspecting navigation information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "targetFrame"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "targetFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit",
                "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-navigation-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction/request",
                "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction/sourceFrame",
                "doc://com.apple.webkit/documentation/WebKit/WKNavigationAction/shouldPerformDownload"
              ],
              "title": "Inspecting navigation information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.webkit/documentation/WebKit/WKFrameInfo",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)WKFrameInfo",
                    "text": "WKFrameInfo"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "targetFrame"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationAction~1shouldPerformDownload/title",
          "value": "shouldPerformDownload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationAction~1shouldPerformDownload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldPerformDownload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKFrameInfo/title",
          "value": "WKFrameInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKFrameInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKFrameInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKFrameInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKFrameInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationAction~1sourceFrame/title",
          "value": "sourceFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationAction~1sourceFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationAction/title",
          "value": "WKNavigationAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKNavigationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKNavigationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationAction~1request/title",
          "value": "request"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationAction~1request/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationAction~1targetFrame/title",
          "value": "targetFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationAction~1targetFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "targetFrame"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wknavigationaction/targetframe"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wknavigationaction/targetframe"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
