{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mReadPacketsFDF"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AudioFileFDFTable@FI@mReadPacketsFDF",
    "fragments": [
      {
        "kind": "identifier",
        "text": "mReadPacketsFDF"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mReadPacketsFDF"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "mReadPacketsFDF"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ReadPacketsFDF",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ReadPacketsFDF",
              "text": "ReadPacketsFDF"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mReadPacketsFDF"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AudioFileFDFTable"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFileFDFTable",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftable"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mReadPacketsFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "mReadPacketsFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioFileFDFTable/mReadPacketsFDF",
      "kind": "symbol",
      "role": "symbol",
      "title": "mReadPacketsFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiofilefdftable/mreadpacketsfdf"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ReadPacketsFDF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ReadPacketsFDF"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/ReadPacketsFDF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ReadPacketsFDF"
        }
      ],
      "role": "symbol",
      "title": "ReadPacketsFDF",
      "type": "topic",
      "url": "/documentation/audiotoolbox/readpacketsfdf"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ReadPacketsFDF/title",
          "value": "ReadPacketsFDF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ReadPacketsFDF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ReadPacketsFDF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1ReadPacketsFDF/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ReadPacketsFDF"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiofilefdftable/mreadpacketsfdf"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
