{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/badParameter"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false,"introducedAt":"16.0"},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"16.0"},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"16.0"},{"unavailable":false,"beta":false,"name":"macOS","deprecated":false},{"name":"visionOS","introducedAt":"1.0","deprecated":false,"beta":false,"unavailable":false}],"navigatorTitle":[{"text":"DDErrorCodeBadParameter","kind":"identifier"}],"modules":[{"name":"DeviceDiscoveryExtension"}],"roleHeading":"Case","title":"DDError.Code.badParameter","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badParameter","kind":"identifier"}],"role":"symbol","symbolKind":"case","externalID":"c:@E@DDErrorCode@DDErrorCodeBadParameter"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code"]]},"abstract":[{"type":"text","text":"An error that indicates the framework doesn’t support a parameter that the extension provides."}],"seeAlsoSections":[{"anchor":"Errors","generated":true,"title":"Errors","identifiers":["doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/success","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/unknown","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/unsupported","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/timeout","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/internal","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/missingEntitlement","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/permission","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/next"]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/devicediscoveryextension/dderror/code/badparameter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/devicediscoveryextension/dderror/code/badparameter"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"badParameter"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}]}],"references":{"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/unknown":{"url":"/documentation/devicediscoveryextension/dderror/code/unknown","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"title":"DDError.Code.unknown","navigatorTitle":[{"kind":"identifier","text":"DDErrorCodeUnknown"}],"kind":"symbol","abstract":[{"text":"An error that indicates an uncategorized problem.","type":"text"}],"type":"topic","identifier":"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/unknown"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","type":"topic","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}]},"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/next":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"next"}],"title":"DDError.Code.next","role":"symbol","identifier":"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/next","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DDErrorCodeNext"}],"url":"/documentation/devicediscoveryextension/dderror/code/next","abstract":[{"text":"An error the framework reserves for future use.","type":"text"}],"type":"topic"},"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/success":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"}],"title":"DDError.Code.success","role":"symbol","identifier":"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/success","kind":"symbol","navigatorTitle":[{"text":"DDErrorCodeSuccess","kind":"identifier"}],"url":"/documentation/devicediscoveryextension/dderror/code/success","abstract":[{"type":"text","text":"An error that indicates an operation succeeds."}],"type":"topic"},"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/missingEntitlement":{"type":"topic","identifier":"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/missingEntitlement","title":"DDError.Code.missingEntitlement","url":"/documentation/devicediscoveryextension/dderror/code/missingentitlement","abstract":[{"text":"An error that indicates that the app extension lacks a required entitlement.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingEntitlement"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DDErrorCodeMissingEntitlement"}]},"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/badParameter":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"badParameter","kind":"identifier"}],"title":"DDError.Code.badParameter","role":"symbol","identifier":"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/badParameter","kind":"symbol","navigatorTitle":[{"text":"DDErrorCodeBadParameter","kind":"identifier"}],"url":"/documentation/devicediscoveryextension/dderror/code/badparameter","abstract":[{"type":"text","text":"An error that indicates the framework doesn’t support a parameter that the extension provides."}],"type":"topic"},"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Code"}],"identifier":"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code","type":"topic","url":"/documentation/devicediscoveryextension/dderror/code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"title":"DDError.Code","abstract":[{"text":"Codes that identify errors that can occur during the framework’s use.","type":"text"}],"kind":"symbol"},"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/timeout":{"url":"/documentation/devicediscoveryextension/dderror/code/timeout","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeout","kind":"identifier"}],"title":"DDError.Code.timeout","navigatorTitle":[{"text":"DDErrorCodeTimeout","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"An error that indicates a timeout occurs."}],"type":"topic","identifier":"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/timeout"},"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/internal":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`internal`","kind":"identifier"}],"title":"DDError.Code.internal","role":"symbol","identifier":"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/internal","kind":"symbol","navigatorTitle":[{"text":"DDErrorCodeInternal","kind":"identifier"}],"url":"/documentation/devicediscoveryextension/dderror/code/internal","abstract":[{"type":"text","text":"An error that indicates a problem of internal origin."}],"type":"topic"},"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/unsupported":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsupported","kind":"identifier"}],"title":"DDError.Code.unsupported","role":"symbol","identifier":"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/unsupported","kind":"symbol","navigatorTitle":[{"text":"DDErrorCodeUnsupported","kind":"identifier"}],"url":"/documentation/devicediscoveryextension/dderror/code/unsupported","abstract":[{"text":"An error that indicates an unsupported configuration.","type":"text"}],"type":"topic"},"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension":{"title":"DeviceDiscoveryExtension","type":"topic","url":"/documentation/devicediscoveryextension","identifier":"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Stream media to a third-party device that a user selects in a system menu."}]},"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DDError"}],"identifier":"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError","type":"topic","url":"/documentation/devicediscoveryextension/dderror","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DDError"}],"title":"DDError","abstract":[{"text":"An error that the framework reports.","type":"text"}],"kind":"symbol"},"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/permission":{"type":"topic","identifier":"doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/permission","title":"DDError.Code.permission","url":"/documentation/devicediscoveryextension/dderror/code/permission","abstract":[{"text":"An error that indicates the app extension lacks necessary permissions.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"permission"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DDErrorCodePermission"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"name":"iOS","unavailable":false,"introducedAt":"16.0","deprecated":false},{"beta":false,"name":"iPadOS","unavailable":false,"introducedAt":"16.0","deprecated":false},{"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"16.0","deprecated":false},{"beta":false,"name":"macOS","unavailable":false,"deprecated":false},{"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Enumeration Case","path":"/metadata/roleHeading","op":"replace"},{"value":"DDErrorCodeBadParameter","path":"/metadata/title","op":"replace"},{"value":"case","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DDErrorCodeBadParameter"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/success","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/unknown","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/unsupported","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/timeout","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/internal","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/missingEntitlement","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/permission","doc://com.apple.devicediscoveryextension/documentation/DeviceDiscoveryExtension/DDError/Code/next"],"anchor":"Errors","generated":true,"title":"Errors"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DDErrorCodeBadParameter"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1unknown/title","value":"DDErrorCodeUnknown"},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1unknown/fragments","value":[{"kind":"identifier","text":"DDErrorCodeUnknown"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1next/title","value":"DDErrorCodeNext"},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1next/fragments","value":[{"text":"DDErrorCodeNext","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1success/title","value":"DDErrorCodeSuccess"},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1success/fragments","value":[{"kind":"identifier","text":"DDErrorCodeSuccess"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1missingEntitlement/title","value":"DDErrorCodeMissingEntitlement"},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1missingEntitlement/fragments","value":[{"kind":"identifier","text":"DDErrorCodeMissingEntitlement"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1badParameter/title","value":"DDErrorCodeBadParameter"},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1badParameter/fragments","value":[{"text":"DDErrorCodeBadParameter","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code/title","value":"DDErrorCode"},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code/fragments","value":[{"text":"DDErrorCode","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code/navigatorTitle","value":[{"kind":"identifier","text":"DDErrorCode"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1timeout/title","value":"DDErrorCodeTimeout"},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1timeout/fragments","value":[{"text":"DDErrorCodeTimeout","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1internal/title","value":"DDErrorCodeInternal"},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1internal/fragments","value":[{"kind":"identifier","text":"DDErrorCodeInternal"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1unsupported/title","value":"DDErrorCodeUnsupported"},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1unsupported/fragments","value":[{"kind":"identifier","text":"DDErrorCodeUnsupported"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1permission/title","value":"DDErrorCodePermission"},{"op":"replace","path":"/references/doc:~1~1com.apple.devicediscoveryextension~1documentation~1DeviceDiscoveryExtension~1DDError~1Code~1permission/fragments","value":[{"text":"DDErrorCodePermission","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}