{
  "abstract": [
    {
      "text": "Error codes that the watch face library returns.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ClockKit",
    "externalID": "c:@E@CLKWatchFaceLibraryErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ErrorCode"
      }
    ],
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ErrorCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CLKWatchFaceLibrary.ErrorCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ErrorCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary": {
      "abstract": [
        {
          "text": "An object for importing watch faces that the app provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKWatchFaceLibrary"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKWatchFaceLibrary"
        }
      ],
      "role": "symbol",
      "title": "CLKWatchFaceLibrary",
      "type": "topic",
      "url": "/documentation/clockkit/clkwatchfacelibrary"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode": {
      "abstract": [
        {
          "text": "Error codes that the watch face library returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ErrorCode"
        }
      ],
      "role": "symbol",
      "title": "CLKWatchFaceLibrary.ErrorCode",
      "type": "topic",
      "url": "/documentation/clockkit/clkwatchfacelibrary/errorcode"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/faceNotAvailable": {
      "abstract": [
        {
          "text": "The watch face is not available on this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/faceNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKWatchFaceLibraryErrorCodeFaceNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "CLKWatchFaceLibrary.ErrorCode.faceNotAvailable",
      "type": "topic",
      "url": "/documentation/clockkit/clkwatchfacelibrary/errorcode/facenotavailable"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkwatchfacelibrary/errorcode/init(rawvalue:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/invalidFile": {
      "abstract": [
        {
          "text": "The specified file wasn’t a valid watch face file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFile"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/invalidFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKWatchFaceLibraryErrorCodeInvalidFile"
        }
      ],
      "role": "symbol",
      "title": "CLKWatchFaceLibrary.ErrorCode.invalidFile",
      "type": "topic",
      "url": "/documentation/clockkit/clkwatchfacelibrary/errorcode/invalidfile"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/notFileURL": {
      "abstract": [
        {
          "text": "No file was found at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notFileURL"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/notFileURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKWatchFaceLibraryErrorCodeNotFileURL"
        }
      ],
      "role": "symbol",
      "title": "CLKWatchFaceLibrary.ErrorCode.notFileURL",
      "type": "topic",
      "url": "/documentation/clockkit/clkwatchfacelibrary/errorcode/notfileurl"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/permissionDenied": {
      "abstract": [
        {
          "text": "The app does not have permission to read the specified file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "permissionDenied"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/permissionDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKWatchFaceLibraryErrorCodePermissionDenied"
        }
      ],
      "role": "symbol",
      "title": "CLKWatchFaceLibrary.ErrorCode.permissionDenied",
      "type": "topic",
      "url": "/documentation/clockkit/clkwatchfacelibrary/errorcode/permissiondenied"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorDomain": {
      "abstract": [
        {
          "text": "The domain for errors while importing watch faces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKWatchFaceLibraryErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ErrorDomain",
      "type": "topic",
      "url": "/documentation/clockkit/clkwatchfacelibrary/errordomain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorDomain"
      ],
      "title": "Handling Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/notFileURL",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/invalidFile",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/permissionDenied",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/faceNotAvailable",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/notFileURL",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/invalidFile",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/permissionDenied",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/faceNotAvailable"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLKWatchFaceLibraryErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.clockkit/documentation/ClockKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/notFileURL",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/invalidFile",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/permissionDenied",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/faceNotAvailable",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/notFileURL",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/invalidFile",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/permissionDenied",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorCode/faceNotAvailable"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKWatchFaceLibrary/ErrorDomain"
              ],
              "title": "Handling Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLKWatchFaceLibraryErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode/title",
          "value": "CLKWatchFaceLibraryErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1faceNotAvailable/title",
          "value": "CLKWatchFaceLibraryErrorCodeFaceNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1faceNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorCodeFaceNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1notFileURL/title",
          "value": "CLKWatchFaceLibraryErrorCodeNotFileURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1notFileURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorCodeNotFileURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorDomain/title",
          "value": "CLKWatchFaceLibraryErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1invalidFile/title",
          "value": "CLKWatchFaceLibraryErrorCodeInvalidFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1invalidFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorCodeInvalidFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary/title",
          "value": "CLKWatchFaceLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1permissionDenied/title",
          "value": "CLKWatchFaceLibraryErrorCodePermissionDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKWatchFaceLibrary~1ErrorCode~1permissionDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKWatchFaceLibraryErrorCodePermissionDenied"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkwatchfacelibrary/errorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/clkwatchfacelibrary/errorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
