{
  "abstract": [
    {
      "text": "An array that contains the variable lengths of sequences stored in the tensor.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use Metal Performance Shaders Graph or BNNS instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/sequenceLengths-3jdab"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "MLCompute",
    "externalID": "s:So19MLCTensorDescriptorC9MLComputeE15sequenceLengthsSaySiGSgvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sequenceLengths"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "Use Metal Performance Shaders Graph or BNNS instead.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "Use Metal Performance Shaders Graph or BNNS instead.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "Use Metal Performance Shaders Graph or BNNS instead.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "11.0",
        "message": "Use Metal Performance Shaders Graph or BNNS instead.",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "14.0",
        "message": "Use Metal Performance Shaders Graph or BNNS instead.",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "sequenceLengths"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sequenceLengths"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor": {
      "abstract": [
        {
          "text": "A configuration object you use to create a tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCTensorDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCTensorDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCTensorDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/batchSizePerSequenceStep-6iz59": {
      "abstract": [
        {
          "text": "The batch size for each sequence.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "batchSizePerSequenceStep"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/batchSizePerSequenceStep-6iz59",
      "kind": "symbol",
      "role": "symbol",
      "title": "batchSizePerSequenceStep",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordescriptor/batchsizepersequencestep-6iz59"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/dataType": {
      "abstract": [
        {
          "text": "The tensor data type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCDataType",
          "text": "MLCDataType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/dataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataType"
        }
      ],
      "role": "symbol",
      "title": "dataType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordescriptor/datatype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/dimensionCount": {
      "abstract": [
        {
          "text": "The number of dimensions in the tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dimensionCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/dimensionCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dimensionCount"
        }
      ],
      "role": "symbol",
      "title": "dimensionCount",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordescriptor/dimensioncount"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/sequenceLengths-3jdab": {
      "abstract": [
        {
          "text": "An array that contains the variable lengths of sequences stored in the tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sequenceLengths"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/sequenceLengths-3jdab",
      "kind": "symbol",
      "role": "symbol",
      "title": "sequenceLengths",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordescriptor/sequencelengths-3jdab"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/shape-7i1rw": {
      "abstract": [
        {
          "text": "An array that contains the size in each dimension.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/shape-7i1rw",
      "kind": "symbol",
      "role": "symbol",
      "title": "shape",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordescriptor/shape-7i1rw"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/sortedSequences": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether you provided the sequence lengths sorted in descending order.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sortedSequences"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/sortedSequences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sortedSequences"
        }
      ],
      "role": "symbol",
      "title": "sortedSequences",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordescriptor/sortedsequences"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/stride-5mzlt": {
      "abstract": [
        {
          "text": "An array that contains the stride, in bytes, in each dimension.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stride"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/stride-5mzlt",
      "kind": "symbol",
      "role": "symbol",
      "title": "stride",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordescriptor/stride-5mzlt"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/tensorAllocationSizeInBytes": {
      "abstract": [
        {
          "text": "The allocation size, in bytes, for a tensor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tensorAllocationSizeInBytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/tensorAllocationSizeInBytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensorAllocationSizeInBytes"
        }
      ],
      "role": "symbol",
      "title": "tensorAllocationSizeInBytes",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensordescriptor/tensorallocationsizeinbytes"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Tensor-Descriptors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/dataType",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/dimensionCount",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/shape-7i1rw",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/stride-5mzlt",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/tensorAllocationSizeInBytes",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/sortedSequences",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensorDescriptor/batchSizePerSequenceStep-6iz59"
      ],
      "title": "Inspecting Tensor Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorDescriptor~1dataType/title",
          "value": "dataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorDescriptor~1dataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorDescriptor~1tensorAllocationSizeInBytes/title",
          "value": "tensorAllocationSizeInBytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorDescriptor~1tensorAllocationSizeInBytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tensorAllocationSizeInBytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorDescriptor/title",
          "value": "MLCTensorDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensorDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensorDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorDescriptor~1dimensionCount/title",
          "value": "dimensionCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorDescriptor~1dimensionCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dimensionCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorDescriptor~1sortedSequences/title",
          "value": "sortedSequences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensorDescriptor~1sortedSequences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sortedSequences"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlctensordescriptor/sequencelengths-3jdab"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
