{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/metalperformanceshadersgraph/mpsgraph/lstm(_:recurrentweight:initstate:initcell:descriptor:name:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/metalperformanceshadersgraph/mpsgraph/lstm(_:recurrentweight:initstate:initcell:descriptor:name:)"]}],"kind":"symbol","abstract":[{"type":"text","text":"Creates an LSTM operation and returns the value tensor and optionally the cell state tensor and  the training state tensor."}],"metadata":{"extendedModule":"MetalPerformanceShadersGraph","externalID":"c:objc(cs)MPSGraph(im)LSTMWithSourceTensor:recurrentWeight:initState:initCell:descriptor:name:","platforms":[{"deprecated":false,"beta":false,"name":"iOS","introducedAt":"15.4","unavailable":false},{"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"15.4","unavailable":false},{"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"15.4","unavailable":false},{"deprecated":false,"beta":false,"name":"macOS","introducedAt":"12.3","unavailable":false},{"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"15.4","unavailable":false},{"beta":false,"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false}],"symbolKind":"method","title":"LSTM(_:recurrentWeight:initState:initCell:descriptor:name:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"LSTM"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MPSGraphTensor","text":"MPSGraphTensor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recurrentWeight"},{"kind":"text","text":": "},{"text":"MPSGraphTensor","preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"initState","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPSGraphTensor","preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"initCell","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPSGraphTensor","preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"descriptor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MPSGraphLSTMDescriptor","text":"MPSGraphLSTMDescriptor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> ["},{"preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier","text":"MPSGraphTensor"},{"kind":"text","text":"]"}],"modules":[{"name":"Metal Performance Shaders Graph"}],"navigatorTitle":[{"kind":"identifier","text":"LSTMWithSourceTensor:recurrentWeight:initState:initCell:descriptor:name:"}],"roleHeading":"Instance Method","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"LSTM"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"source"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor","preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier","text":"MPSGraphTensor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recurrentWeight"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor","preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier","text":"MPSGraphTensor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"initState"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor","preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier","text":"MPSGraphTensor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"initCell"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor","preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier","text":"MPSGraphTensor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"descriptor"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphLSTMDescriptor","preciseIdentifier":"c:objc(cs)MPSGraphLSTMDescriptor","kind":"typeIdentifier","text":"MPSGraphLSTMDescriptor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:SS","preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> ["},{"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor","preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier","text":"MPSGraphTensor"},{"kind":"text","text":"]"}]}],"kind":"declarations"},{"parameters":[{"name":"source","content":[{"type":"paragraph","inlineContent":[{"text":"A tensor containing the source data ","type":"text"},{"code":"x[t]","type":"codeVoice"},{"text":"  with the data layout [T,N,I]. In case ","type":"text"},{"code":"inputWeight = nil","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"bidirectional = NO","type":"codeVoice"},{"text":" then the layout is [T,N,4H] and for ","type":"text"},{"code":"inputWeight = nil","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"bidirectional = YES","type":"codeVoice"},{"text":" the layout is [T,N,8H].","type":"text"}]}]},{"name":"recurrentWeight","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A tensor containing the recurrent weights "},{"type":"codeVoice","code":"R"},{"type":"text","text":". For "},{"type":"codeVoice","code":"bidirectional"},{"type":"text","text":" the layout is [2,4H,H] and otherwise it is [4H,H]."}]}]},{"name":"initState","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The initial internal state of the LSTM "},{"type":"codeVoice","code":"h[-1]"},{"type":"text","text":" - optional, if missing the operation assumes zeroes."},{"type":"text","text":" "},{"type":"text","text":"For "},{"type":"codeVoice","code":"bidirectional"},{"type":"text","text":" the layout is [N,2H] and otherwise it is [N,H]."}]}]},{"name":"initCell","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The initial internal cell of the LSTM "},{"type":"codeVoice","code":"h[-1]"},{"type":"text","text":" - optional, if missing the operation assumes zeroes."},{"type":"text","text":" "},{"type":"text","text":"For "},{"type":"codeVoice","code":"bidirectional"},{"type":"text","text":" the layout is [N,2H] and otherwise it is [N,H]."}]}]},{"name":"descriptor","content":[{"inlineContent":[{"type":"text","text":"A descriptor that defines the parameters for the LSTM operation."}],"type":"paragraph"}]},{"name":"name","content":[{"inlineContent":[{"text":"The name for the operation.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"A valid ","type":"text"},{"code":"MPSGraphTensor","type":"codeVoice"},{"text":" array of size 1 or 2 or 3, depending on values of ","type":"text"},{"code":"descriptor.produceCell","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"descriptor.training","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The layout of the both state and cell outputs are [T,N,H] or [T,N,2H] for bidirectional, and the layout of the trainingState output is [T,N,4H] or [T,N,8H] for bidirectional.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"This operation returns tensors ","type":"text"},{"code":"h","type":"codeVoice"},{"text":" and optionally ","type":"text"},{"code":"c","type":"codeVoice"},{"text":" and optionally ","type":"text"},{"code":"z","type":"codeVoice"},{"text":" that are defined recursively as follows:","type":"text"}]},{"syntax":"md","type":"codeListing","code":["for t = 0 to T-1","  z[t] = [i, f, z, o][t] = f( (h[t-1] m) R^T + x'[t] + p c[t-1] )","  x'[t] = x[t] W^T + b","  c[t] = f[t]c[t-1] + i[t]z[t]","  h[t] = o[t]g(c[t]), where"]},{"type":"paragraph","inlineContent":[{"code":"W","type":"codeVoice"},{"text":" is optional ","type":"text"},{"code":"inputWeight","type":"codeVoice"},{"text":", ","type":"text"},{"code":"R","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"recurrentWeight","type":"codeVoice"},{"text":", ","type":"text"},{"code":"b","type":"codeVoice"},{"text":" is optional ","type":"text"},{"code":"bias","type":"codeVoice"},{"text":", ","type":"text"},{"code":"m","type":"codeVoice"},{"text":" is optional ","type":"text"},{"code":"mask","type":"codeVoice"},{"text":",","type":"text"},{"text":" ","type":"text"},{"code":"x[t]","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"source","type":"codeVoice"},{"text":" ","type":"text"},{"code":"h[t]","type":"codeVoice"},{"text":" is the first output, ","type":"text"},{"code":"c[t]","type":"codeVoice"},{"text":" is the second output (optional),","type":"text"},{"text":" ","type":"text"},{"code":"z[t]","type":"codeVoice"},{"text":" is either the second or third output (optional), ","type":"text"},{"code":"h[-1]","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"initCell","type":"codeVoice"},{"text":".  and ","type":"text"},{"code":"h[-1]","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"initState","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"code":"p","type":"codeVoice"},{"text":" is an optional peephole vector.","type":"text"},{"text":" ","type":"text"},{"text":"See ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphLSTMDescriptor","type":"reference"},{"text":" for different ","type":"text"},{"code":"activation","type":"codeVoice"},{"text":" options for ","type":"text"},{"code":"f()","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"g()","type":"codeVoice"},{"text":".","type":"text"}]}]}],"identifier":{"url":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph/LSTM(_:recurrentWeight:initState:initCell:descriptor:name:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph"]]},"references":{"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPSGraph"}],"type":"topic","url":"/documentation/metalperformanceshadersgraph/mpsgraph","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSGraph"}],"title":"MPSGraph","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph","abstract":[{"text":"The optimized representation of a compute graph of operations and tensors.","type":"text"}]},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor":{"abstract":[{"text":"The symbolic representation of a compute data type.","type":"text"}],"url":"/documentation/metalperformanceshadersgraph/mpsgraphtensor","title":"MPSGraphTensor","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSGraphTensor"}],"navigatorTitle":[{"kind":"identifier","text":"MPSGraphTensor"}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor","type":"topic","role":"symbol"},"doc://com.externally.resolved.symbol/s:SS":{"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"kind":"symbol","title":"String","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"url":"/documentation/Swift/String","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:SS","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphLSTMDescriptor":{"role":"symbol","abstract":[{"text":"The class that defines the parameters for a long short-term memory (LSTM) operation.","type":"text"}],"title":"MPSGraphLSTMDescriptor","kind":"symbol","type":"topic","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphLSTMDescriptor","url":"/documentation/metalperformanceshadersgraph/mpsgraphlstmdescriptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSGraphLSTMDescriptor"}],"navigatorTitle":[{"kind":"identifier","text":"MPSGraphLSTMDescriptor"}]},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph":{"role":"collection","kind":"symbol","url":"/documentation/metalperformanceshadersgraph","abstract":[{"type":"text","text":"Build, compile, and execute compute graphs utilizing all the different compute devices on the platform, including GPU, CPU, and Neural Engine."}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","title":"Metal Performance Shaders Graph","type":"topic"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph/LSTM(_:recurrentWeight:initState:initCell:descriptor:name:)":{"url":"/documentation/metalperformanceshadersgraph/mpsgraph/lstm(_:recurrentweight:initstate:initcell:descriptor:name:)","role":"symbol","title":"LSTM(_:recurrentWeight:initState:initCell:descriptor:name:)","navigatorTitle":[{"kind":"identifier","text":"LSTMWithSourceTensor:recurrentWeight:initState:initCell:descriptor:name:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LSTM","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPSGraphTensor","preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"recurrentWeight","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier","text":"MPSGraphTensor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"initState"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier","text":"MPSGraphTensor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"initCell"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier","text":"MPSGraphTensor"},{"text":"?, ","kind":"text"},{"text":"descriptor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPSGraphLSTMDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MPSGraphLSTMDescriptor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> ["},{"preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier","text":"MPSGraphTensor"},{"kind":"text","text":"]"}],"abstract":[{"text":"Creates an LSTM operation and returns the value tensor and optionally the cell state tensor and  the training state tensor.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph/LSTM(_:recurrentWeight:initState:initCell:descriptor:name:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"15.4","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"introducedAt":"15.4","beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"introducedAt":"15.4","beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false},{"introducedAt":"12.3","beta":false,"unavailable":false,"name":"macOS","deprecated":false},{"beta":false,"introducedAt":"15.4","name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"LSTMWithSourceTensor:recurrentWeight:initState:initCell:descriptor:name:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"LSTMWithSourceTensor:recurrentWeight:initState:initCell:descriptor:name:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<MPSGraphTensor *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"LSTMWithSourceTensor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MPSGraphTensor","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor","text":"MPSGraphTensor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"source","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"recurrentWeight:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPSGraphTensor","preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor"},{"text":" *) ","kind":"text"},{"text":"recurrentWeight","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"initState:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MPSGraphTensor","preciseIdentifier":"c:objc(cs)MPSGraphTensor","kind":"typeIdentifier","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor"},{"text":" *) ","kind":"text"},{"text":"initState","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"initCell:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MPSGraphTensor","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor","text":"MPSGraphTensor"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"initCell"},{"kind":"text","text":" "},{"kind":"identifier","text":"descriptor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MPSGraphLSTMDescriptor","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphLSTMDescriptor","text":"MPSGraphLSTMDescriptor"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"descriptor"},{"kind":"text","text":" "},{"kind":"identifier","text":"name:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"name"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A tensor containing the source data "},{"type":"codeVoice","code":"x[t]"},{"type":"text","text":"  with the data layout [T,N,I]. In case "},{"type":"codeVoice","code":"inputWeight = nil"},{"type":"text","text":" and "},{"type":"codeVoice","code":"bidirectional = NO"},{"type":"text","text":" then the layout is [T,N,4H] and for "},{"type":"codeVoice","code":"inputWeight = nil"},{"type":"text","text":" and "},{"type":"codeVoice","code":"bidirectional = YES"},{"type":"text","text":" the layout is [T,N,8H]."}]}],"name":"source"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A tensor containing the recurrent weights "},{"code":"R","type":"codeVoice"},{"type":"text","text":". For "},{"code":"bidirectional","type":"codeVoice"},{"type":"text","text":" the layout is [2,4H,H] and otherwise it is [4H,H]."}]}],"name":"recurrentWeight"},{"content":[{"inlineContent":[{"text":"The initial internal state of the LSTM ","type":"text"},{"code":"h[-1]","type":"codeVoice"},{"text":" - optional, if missing the operation assumes zeroes.","type":"text"},{"text":" ","type":"text"},{"text":"For ","type":"text"},{"code":"bidirectional","type":"codeVoice"},{"text":" the layout is [N,2H] and otherwise it is [N,H].","type":"text"}],"type":"paragraph"}],"name":"initState"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The initial internal cell of the LSTM "},{"type":"codeVoice","code":"h[-1]"},{"type":"text","text":" - optional, if missing the operation assumes zeroes."},{"type":"text","text":" "},{"type":"text","text":"For "},{"type":"codeVoice","code":"bidirectional"},{"type":"text","text":" the layout is [N,2H] and otherwise it is [N,H]."}]}],"name":"initCell"},{"content":[{"inlineContent":[{"text":"A descriptor that defines the parameters for the LSTM operation.","type":"text"}],"type":"paragraph"}],"name":"descriptor"},{"content":[{"inlineContent":[{"type":"text","text":"The name for the operation."}],"type":"paragraph"}],"name":"name"}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"value":{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"A valid "},{"code":"MPSGraphTensor","type":"codeVoice"},{"type":"text","text":" array of size 1 or 2 or 3, depending on values of "},{"code":"descriptor.produceCell","type":"codeVoice"},{"type":"text","text":" and "},{"code":"descriptor.training","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The layout of the both state and cell outputs are [T,N,H] or [T,N,2H] for bidirectional, and the layout of the trainingState output is [T,N,4H] or [T,N,8H] for bidirectional."}],"type":"paragraph"}]},"path":"/primaryContentSections/2","op":"replace"},{"op":"replace","value":"MPSGraph","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph/title"},{"op":"replace","value":[{"kind":"identifier","text":"MPSGraph"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph/fragments"},{"op":"replace","value":[{"text":"MPSGraph","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph/navigatorTitle"},{"op":"replace","value":"MPSGraphTensor","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensor/title"},{"op":"replace","value":[{"text":"MPSGraphTensor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensor/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MPSGraphTensor"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensor/navigatorTitle"},{"op":"replace","value":"MPSGraphLSTMDescriptor","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphLSTMDescriptor/title"},{"op":"replace","value":[{"text":"MPSGraphLSTMDescriptor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphLSTMDescriptor/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MPSGraphLSTMDescriptor"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphLSTMDescriptor/navigatorTitle"},{"op":"replace","value":"LSTMWithSourceTensor:recurrentWeight:initState:initCell:descriptor:name:","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph~1LSTM(_:recurrentWeight:initState:initCell:descriptor:name:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"LSTMWithSourceTensor:recurrentWeight:initState:initCell:descriptor:name:"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph~1LSTM(_:recurrentWeight:initState:initCell:descriptor:name:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}