{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph/maxPooling2D(withSourceTensor:descriptor:name:)"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxPooling2D"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSourceTensor"},{"text":": ","kind":"text"},{"text":"MPSGraphTensor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MPSGraphTensor"},{"text":", ","kind":"text"},{"text":"descriptor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MPSGraphPooling2DOpDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MPSGraphPooling2DOpDescriptor"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"MPSGraphTensor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MPSGraphTensor"}],"roleHeading":"Instance Method","role":"symbol","title":"maxPooling2D(withSourceTensor:descriptor:name:)","platforms":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"14.0","unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"14.0","unavailable":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"14.0","unavailable":false},{"name":"macOS","beta":false,"deprecated":false,"introducedAt":"11.0","unavailable":false},{"name":"tvOS","beta":false,"deprecated":false,"introducedAt":"14.0","unavailable":false},{"unavailable":false,"beta":false,"introducedAt":"1.0","name":"visionOS","deprecated":false}],"extendedModule":"MetalPerformanceShadersGraph","externalID":"c:objc(cs)MPSGraph(im)maxPooling2DWithSourceTensor:descriptor:name:","navigatorTitle":[{"text":"maxPooling2DWithSourceTensor:descriptor:name:","kind":"identifier"}],"modules":[{"name":"Metal Performance Shaders Graph"}],"symbolKind":"method"},"sections":[],"abstract":[{"type":"text","text":"Creates a 2D max-pooling operation and returns the result tensor."}],"variants":[{"paths":["/documentation/metalperformanceshadersgraph/mpsgraph/maxpooling2d(withsourcetensor:descriptor:name:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/metalperformanceshadersgraph/mpsgraph/maxpooling2d(withsourcetensor:descriptor:name:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxPooling2D"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSourceTensor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MPSGraphTensor","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor","text":"MPSGraphTensor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"descriptor"},{"kind":"text","text":": "},{"text":"MPSGraphPooling2DOpDescriptor","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphPooling2DOpDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MPSGraphPooling2DOpDescriptor"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","identifier":"doc://com.externally.resolved.symbol/s:SS","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"MPSGraphTensor","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MPSGraphTensor"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"source","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A 2D Image source as tensor - must be of rank=4. The layout is defined by "},{"type":"codeVoice","code":"descriptor.dataLayout"},{"type":"text","text":"."}]}]},{"name":"descriptor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A pooling operation descriptor that specifies pooling window sizes, strides, dilation rates, paddings and layouts."}]}]},{"name":"name","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name for the operation."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"A valid MPSGraphTensor object"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph"]]},"references":{"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph":{"role":"collection","kind":"symbol","url":"/documentation/metalperformanceshadersgraph","abstract":[{"type":"text","text":"Build, compile, and execute compute graphs utilizing all the different compute devices on the platform, including GPU, CPU, and Neural Engine."}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","title":"Metal Performance Shaders Graph","type":"topic"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPSGraph"}],"type":"topic","url":"/documentation/metalperformanceshadersgraph/mpsgraph","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSGraph"}],"title":"MPSGraph","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph","abstract":[{"text":"The optimized representation of a compute graph of operations and tensors.","type":"text"}]},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph/maxPooling2D(withSourceTensor:descriptor:name:)":{"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph/maxPooling2D(withSourceTensor:descriptor:name:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxPooling2D"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSourceTensor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPSGraphTensor","preciseIdentifier":"c:objc(cs)MPSGraphTensor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"descriptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MPSGraphPooling2DOpDescriptor","preciseIdentifier":"c:objc(cs)MPSGraphPooling2DOpDescriptor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"MPSGraphTensor","preciseIdentifier":"c:objc(cs)MPSGraphTensor"}],"navigatorTitle":[{"kind":"identifier","text":"maxPooling2DWithSourceTensor:descriptor:name:"}],"abstract":[{"text":"Creates a 2D max-pooling operation and returns the result tensor.","type":"text"}],"kind":"symbol","role":"symbol","title":"maxPooling2D(withSourceTensor:descriptor:name:)","type":"topic","url":"/documentation/metalperformanceshadersgraph/mpsgraph/maxpooling2d(withsourcetensor:descriptor:name:)"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphPooling2DOpDescriptor":{"role":"symbol","kind":"symbol","url":"/documentation/metalperformanceshadersgraph/mpsgraphpooling2dopdescriptor","abstract":[{"text":"The class that defines the parameters for a 2D pooling operation.","type":"text"}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphPooling2DOpDescriptor","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSGraphPooling2DOpDescriptor"}],"title":"MPSGraphPooling2DOpDescriptor","navigatorTitle":[{"kind":"identifier","text":"MPSGraphPooling2DOpDescriptor"}],"type":"topic"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor":{"abstract":[{"text":"The symbolic representation of a compute data type.","type":"text"}],"url":"/documentation/metalperformanceshadersgraph/mpsgraphtensor","title":"MPSGraphTensor","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MPSGraphTensor"}],"navigatorTitle":[{"kind":"identifier","text":"MPSGraphTensor"}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor","type":"topic","role":"symbol"},"doc://com.externally.resolved.symbol/s:SS":{"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"kind":"symbol","title":"String","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"url":"/documentation/Swift/String","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:SS","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"14.0","beta":false},{"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"14.0","unavailable":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"14.0","unavailable":false},{"name":"macOS","beta":false,"deprecated":false,"introducedAt":"11.0","unavailable":false},{"name":"tvOS","beta":false,"deprecated":false,"introducedAt":"14.0","unavailable":false},{"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0","unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"maxPooling2DWithSourceTensor:descriptor:name:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"maxPooling2DWithSourceTensor:descriptor:name:","kind":"identifier"}]},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MPSGraphTensor","text":"MPSGraphTensor"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"maxPooling2DWithSourceTensor:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MPSGraphTensor","text":"MPSGraphTensor"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"source"},{"kind":"text","text":" "},{"kind":"identifier","text":"descriptor:"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphPooling2DOpDescriptor","text":"MPSGraphPooling2DOpDescriptor","preciseIdentifier":"c:objc(cs)MPSGraphPooling2DOpDescriptor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"descriptor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"name:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":{"parameters":[{"name":"source","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A 2D Image source as tensor - must be of rank=4. The layout is defined by "},{"code":"descriptor.dataLayout","type":"codeVoice"},{"type":"text","text":"."}]}]},{"name":"descriptor","content":[{"inlineContent":[{"text":"A pooling operation descriptor that specifies pooling window sizes, strides, dilation rates, paddings and layouts.","type":"text"}],"type":"paragraph"}]},{"name":"name","content":[{"inlineContent":[{"text":"The name for the operation.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A valid MPSGraphTensor object","type":"text"}]}]},"path":"/primaryContentSections/2","op":"replace"},{"op":"replace","value":"MPSGraph","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph/title"},{"op":"replace","value":[{"kind":"identifier","text":"MPSGraph"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph/fragments"},{"op":"replace","value":[{"text":"MPSGraph","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph/navigatorTitle"},{"op":"replace","value":"maxPooling2DWithSourceTensor:descriptor:name:","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph~1maxPooling2D(withSourceTensor:descriptor:name:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"maxPooling2DWithSourceTensor:descriptor:name:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph~1maxPooling2D(withSourceTensor:descriptor:name:)/fragments"},{"op":"replace","value":"MPSGraphPooling2DOpDescriptor","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphPooling2DOpDescriptor/title"},{"op":"replace","value":[{"text":"MPSGraphPooling2DOpDescriptor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphPooling2DOpDescriptor/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MPSGraphPooling2DOpDescriptor"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphPooling2DOpDescriptor/navigatorTitle"},{"op":"replace","value":"MPSGraphTensor","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensor/title"},{"op":"replace","value":[{"text":"MPSGraphTensor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensor/fragments"},{"op":"replace","value":[{"text":"MPSGraphTensor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensor/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}