{
  "abstract": [
    {
      "text": "Creates a Resize operation and returns the result tensor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph",
        "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph/resizeNearest(_:sizeTensor:scaleTensor:offsetTensor:nearestRoundingMode:name:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "MetalPerformanceShadersGraph",
    "externalID": "c:objc(cs)MPSGraph(im)resizeNearestWithTensor:sizeTensor:scaleTensor:offsetTensor:nearestRoundingMode:name:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "resizeNearest"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
        "text": "MPSGraphTensor"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "sizeTensor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
        "text": "MPSGraphTensor"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "scaleTensor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
        "text": "MPSGraphTensor"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "offsetTensor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
        "text": "MPSGraphTensor"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "nearestRoundingMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MPSGraphResizeNearestRoundingMode",
        "text": "MPSGraphResizeNearestRoundingMode"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "name"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
        "text": "MPSGraphTensor"
      }
    ],
    "modules": [
      {
        "name": "Metal Performance Shaders Graph"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "resizeNearestWithTensor:sizeTensor:scaleTensor:offsetTensor:nearestRoundingMode:name:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "resizeNearest(_:sizeTensor:scaleTensor:offsetTensor:nearestRoundingMode:name:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "resizeNearest"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "imagesTensor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
              "text": "MPSGraphTensor"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "sizeTensor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "size"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
              "text": "MPSGraphTensor"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "scaleTensor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "scale"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
              "text": "MPSGraphTensor"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "offsetTensor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "offset"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
              "text": "MPSGraphTensor"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "nearestRoundingMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MPSGraphResizeNearestRoundingMode",
              "text": "MPSGraphResizeNearestRoundingMode"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
              "text": "MPSGraphTensor"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Tensor containing input images.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "imagesTensor"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The target size of the result tensor.  1D Int32 or Int64 tensor of size equal to rank of input.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "size"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "1D float tensor of size equal to rank of input.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "scale"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "1D float tensor of size equal to rank of input.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "offset"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The rounding mode to use when using nearest resampling. Default is roundPreferCeil.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "nearestRoundingMode"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name for the operation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "name"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A valid MPSGraphTensor object",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Resamples input images to given size using the provided scale and offset and nearest neighbor sampling.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Destination indices are computed using",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "dst_indices = (src_indices * scale) + offset"
          ],
          "syntax": "md",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For most use cases passing the scale and offset directly is unnecessary, and it is",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "preferable to use the API specifying centerResult and alignCorners.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph": {
      "abstract": [
        {
          "text": "Build, compile, and execute compute graphs utilizing all the different compute devices on the platform, including GPU, CPU, and Neural Engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal Performance Shaders Graph",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph": {
      "abstract": [
        {
          "text": "The optimized representation of a compute graph of operations and tensors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPSGraph"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPSGraph"
        }
      ],
      "role": "symbol",
      "title": "MPSGraph",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph/mpsgraph"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph/resizeNearest(_:sizeTensor:scaleTensor:offsetTensor:nearestRoundingMode:name:)": {
      "abstract": [
        {
          "text": "Creates a Resize operation and returns the result tensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resizeNearest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
          "text": "MPSGraphTensor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sizeTensor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
          "text": "MPSGraphTensor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "scaleTensor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
          "text": "MPSGraphTensor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "offsetTensor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
          "text": "MPSGraphTensor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "nearestRoundingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPSGraphResizeNearestRoundingMode",
          "text": "MPSGraphResizeNearestRoundingMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
          "text": "MPSGraphTensor"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph/resizeNearest(_:sizeTensor:scaleTensor:offsetTensor:nearestRoundingMode:name:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resizeNearestWithTensor:sizeTensor:scaleTensor:offsetTensor:nearestRoundingMode:name:"
        }
      ],
      "role": "symbol",
      "title": "resizeNearest(_:sizeTensor:scaleTensor:offsetTensor:nearestRoundingMode:name:)",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph/mpsgraph/resizenearest(_:sizetensor:scaletensor:offsettensor:nearestroundingmode:name:)"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode": {
      "abstract": [
        {
          "text": "The rounding mode to use when using nearest resize mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPSGraphResizeNearestRoundingMode"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPSGraphResizeNearestRoundingMode"
        }
      ],
      "role": "symbol",
      "title": "MPSGraphResizeNearestRoundingMode",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph/mpsgraphresizenearestroundingmode"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor": {
      "abstract": [
        {
          "text": "The symbolic representation of a compute data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPSGraphTensor"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPSGraphTensor"
        }
      ],
      "role": "symbol",
      "title": "MPSGraphTensor",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph/mpsgraphtensor"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "resizeNearestWithTensor:sizeTensor:scaleTensor:offsetTensor:nearestRoundingMode:name:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resizeNearestWithTensor:sizeTensor:scaleTensor:offsetTensor:nearestRoundingMode:name:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph",
                "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
                    "text": "MPSGraphTensor"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "resizeNearestWithTensor:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
                    "text": "MPSGraphTensor"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "imagesTensor"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "sizeTensor:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
                    "text": "MPSGraphTensor"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "size"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "scaleTensor:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
                    "text": "MPSGraphTensor"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "scale"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "offsetTensor:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
                    "text": "MPSGraphTensor"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "offset"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "nearestRoundingMode:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MPSGraphResizeNearestRoundingMode",
                    "text": "MPSGraphResizeNearestRoundingMode"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "nearestRoundingMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "name:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "name"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Tensor containing input images.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "imagesTensor"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The target size of the result tensor.  1D Int32 or Int64 tensor of size equal to rank of input.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "size"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "1D float tensor of size equal to rank of input.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "scale"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "1D float tensor of size equal to rank of input.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "offset"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The rounding mode to use when using nearest resampling. Default is roundPreferCeil.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "nearestRoundingMode"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The name for the operation.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "name"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A valid MPSGraphTensor object",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph/title",
          "value": "MPSGraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensor/title",
          "value": "MPSGraphTensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraphTensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraphTensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph~1resizeNearest(_:sizeTensor:scaleTensor:offsetTensor:nearestRoundingMode:name:)/title",
          "value": "resizeNearestWithTensor:sizeTensor:scaleTensor:offsetTensor:nearestRoundingMode:name:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph~1resizeNearest(_:sizeTensor:scaleTensor:offsetTensor:nearestRoundingMode:name:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resizeNearestWithTensor:sizeTensor:scaleTensor:offsetTensor:nearestRoundingMode:name:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode/title",
          "value": "MPSGraphResizeNearestRoundingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraphResizeNearestRoundingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraphResizeNearestRoundingMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalperformanceshadersgraph/mpsgraph/resizenearest(_:sizetensor:scaletensor:offsettensor:nearestroundingmode:name:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalperformanceshadersgraph/mpsgraph/resizenearest(_:sizetensor:scaletensor:offsettensor:nearestroundingmode:name:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
