{
  "abstract": [
    {
      "text": "Runs the graph for the given feeds and returns the target tensor values in the results dictionary provided by the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph",
        "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph/run(with:feeds:targetOperations:resultsDictionary:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MPSGraph(im)runWithMTLCommandQueue:feeds:targetOperations:resultsDictionary:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "run"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)MTLCommandQueue",
        "text": "MTLCommandQueue"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "feeds"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
        "text": "MPSGraphTensor"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MPSGraphTensorData",
        "text": "MPSGraphTensorData"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "targetOperations"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MPSGraphOperation",
        "text": "MPSGraphOperation"
      },
      {
        "kind": "text",
        "text": "]?, "
      },
      {
        "kind": "externalParam",
        "text": "resultsDictionary"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
        "text": "MPSGraphTensor"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MPSGraphTensorData",
        "text": "MPSGraphTensorData"
      },
      {
        "kind": "text",
        "text": "])"
      }
    ],
    "modules": [
      {
        "name": "Metal Performance Shaders Graph"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "runWithMTLCommandQueue:feeds:targetOperations:resultsDictionary:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "run(with:feeds:targetOperations:resultsDictionary:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "run"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "commandQueue"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLCommandQueue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLCommandQueue",
              "text": "MTLCommandQueue"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "feeds"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
              "text": "MPSGraphTensor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorData",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MPSGraphTensorData",
              "text": "MPSGraphTensorData"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "targetOperations"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphOperation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MPSGraphOperation",
              "text": "MPSGraphOperation"
            },
            {
              "kind": "text",
              "text": "]?, "
            },
            {
              "kind": "externalParam",
              "text": "resultsDictionary"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
              "text": "MPSGraphTensor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorData",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MPSGraphTensorData",
              "text": "MPSGraphTensorData"
            },
            {
              "kind": "text",
              "text": "])"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "CommandQueue passed to exectute the graph on.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "commandQueue"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Feeds dictionary for the placeholder tensors.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "feeds"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Operations to be completed at the end of the run.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "targetOperations"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "MPSGraphTensors dictionary passed by user, these will be filled with graph output data.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "resultsDictionary"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "It also ensures all target operations also executed. This call blocks until execution has completed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph": {
      "abstract": [
        {
          "text": "Build, compile, and execute compute graphs utilizing all the different compute devices on the platform, including GPU, CPU, and Neural Engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal Performance Shaders Graph",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph": {
      "abstract": [
        {
          "text": "The optimized representation of a compute graph of operations and tensors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPSGraph"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPSGraph"
        }
      ],
      "role": "symbol",
      "title": "MPSGraph",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph/mpsgraph"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph/run(with:feeds:targetOperations:resultsDictionary:)": {
      "abstract": [
        {
          "text": "Runs the graph for the given feeds and returns the target tensor values in the results dictionary provided by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "run"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLCommandQueue",
          "text": "MTLCommandQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "feeds"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
          "text": "MPSGraphTensor"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPSGraphTensorData",
          "text": "MPSGraphTensorData"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "targetOperations"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPSGraphOperation",
          "text": "MPSGraphOperation"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "resultsDictionary"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPSGraphTensor",
          "text": "MPSGraphTensor"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPSGraphTensorData",
          "text": "MPSGraphTensorData"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph/run(with:feeds:targetOperations:resultsDictionary:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runWithMTLCommandQueue:feeds:targetOperations:resultsDictionary:"
        }
      ],
      "role": "symbol",
      "title": "run(with:feeds:targetOperations:resultsDictionary:)",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph/mpsgraph/run(with:feeds:targetoperations:resultsdictionary:)"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphOperation": {
      "abstract": [
        {
          "text": "A symbolic representation of a compute operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPSGraphOperation"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPSGraphOperation"
        }
      ],
      "role": "symbol",
      "title": "MPSGraphOperation",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph/mpsgraphoperation"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor": {
      "abstract": [
        {
          "text": "The symbolic representation of a compute data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPSGraphTensor"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPSGraphTensor"
        }
      ],
      "role": "symbol",
      "title": "MPSGraphTensor",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph/mpsgraphtensor"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorData": {
      "abstract": [
        {
          "text": "The representation of a compute data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPSGraphTensorData"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPSGraphTensorData"
        }
      ],
      "role": "symbol",
      "title": "MPSGraphTensorData",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph/mpsgraphtensordata"
    },
    "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorDataDictionary": {
      "abstract": [
        {
          "text": "A dictionary of tensors and corresponding tensor data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MPSGraphTensorDataDictionary"
        }
      ],
      "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorDataDictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPSGraphTensorDataDictionary",
      "type": "topic",
      "url": "/documentation/metalperformanceshadersgraph/mpsgraphtensordatadictionary"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)MTLCommandQueue": {
      "abstract": [
        {
          "text": "An instance you use to create, submit, and schedule command buffers to a specific GPU device to run the commands within those buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandQueue"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLCommandQueue",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLCommandQueue",
      "type": "topic",
      "url": "/documentation/Metal/MTLCommandQueue"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "runWithMTLCommandQueue:feeds:targetOperations:resultsDictionary:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runWithMTLCommandQueue:feeds:targetOperations:resultsDictionary:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph",
                "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraph"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "runWithMTLCommandQueue:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)MTLCommandQueue",
                    "text": "id<MTLCommandQueue>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "commandQueue"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "feeds:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorDataDictionary",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MPSGraphTensorDataDictionary",
                    "text": "MPSGraphTensorDataDictionary"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "feeds"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "targetOperations:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<MPSGraphOperation *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "targetOperations"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "resultsDictionary:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphTensorDataDictionary",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MPSGraphTensorDataDictionary",
                    "text": "MPSGraphTensorDataDictionary"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "resultsDictionary"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "CommandQueue passed to exectute the graph on.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "commandQueue"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Feeds dictionary for the placeholder tensors.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "feeds"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Operations to be completed at the end of the run.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "targetOperations"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "MPSGraphTensors dictionary passed by user, these will be filled with graph output data.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "resultsDictionary"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensorData/title",
          "value": "MPSGraphTensorData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensorData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraphTensorData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensorData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraphTensorData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph~1run(with:feeds:targetOperations:resultsDictionary:)/title",
          "value": "runWithMTLCommandQueue:feeds:targetOperations:resultsDictionary:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph~1run(with:feeds:targetOperations:resultsDictionary:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runWithMTLCommandQueue:feeds:targetOperations:resultsDictionary:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensor/title",
          "value": "MPSGraphTensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraphTensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphTensor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraphTensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphOperation/title",
          "value": "MPSGraphOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraphOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraphOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph/title",
          "value": "MPSGraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraph/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPSGraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)MTLCommandQueue/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLCommandQueue"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalperformanceshadersgraph/mpsgraph/run(with:feeds:targetoperations:resultsdictionary:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalperformanceshadersgraph/mpsgraph/run(with:feeds:targetoperations:resultsdictionary:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
