{
  "abstract": [
    {
      "text": "The end position of the range.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcodekit/documentation/XcodeKit",
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextRange"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextRange/end"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCSourceTextRange(py)end",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "end"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@XCSourceTextPosition",
        "text": "XCSourceTextPosition"
      }
    ],
    "modules": [
      {
        "name": "XcodeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "end"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "end"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "end"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextPosition",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@XCSourceTextPosition",
              "text": "XCSourceTextPosition"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit": {
      "abstract": [
        {
          "text": "Create extensions to add commands to the Xcode source editor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "XcodeKit",
      "type": "topic",
      "url": "/documentation/xcodekit"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextPosition": {
      "abstract": [
        {
          "text": "A zero-based position in a source editor, defined by a line number and column number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCSourceTextPosition"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSourceTextPosition"
        }
      ],
      "role": "symbol",
      "title": "XCSourceTextPosition",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourcetextposition"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextRange": {
      "abstract": [
        {
          "text": "A half-open range of text in a buffer you use to select text or specify the insertion point for new text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCSourceTextRange"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSourceTextRange"
        }
      ],
      "role": "symbol",
      "title": "XCSourceTextRange",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourcetextrange"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextRange/end": {
      "abstract": [
        {
          "text": "The end position of the range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "end"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@XCSourceTextPosition",
          "text": "XCSourceTextPosition"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextRange/end",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "end"
        }
      ],
      "role": "symbol",
      "title": "end",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourcetextrange/end"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextRange/start": {
      "abstract": [
        {
          "text": "The start position of the range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@XCSourceTextPosition",
          "text": "XCSourceTextPosition"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextRange/start",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "start"
        }
      ],
      "role": "symbol",
      "title": "start",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourcetextrange/start"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Bounds-of-Source-Text-Ranges",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextRange/start"
      ],
      "title": "Getting the Bounds of Source Text Ranges"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "end"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "end"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xcodekit/documentation/XcodeKit",
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextRange"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Bounds-of-Source-Text-Ranges",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextRange/start"
              ],
              "title": "Getting the Bounds of Source Text Ranges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceTextPosition",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@XCSourceTextPosition",
                    "text": "XCSourceTextPosition"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "end"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextRange~1start/title",
          "value": "start"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextRange~1start/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "start"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextRange/title",
          "value": "XCSourceTextRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceTextRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceTextRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextRange~1end/title",
          "value": "end"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextRange~1end/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "end"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextPosition/title",
          "value": "XCSourceTextPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceTextPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceTextPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceTextPosition"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcodekit/xcsourcetextrange/end"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcodekit/xcsourcetextrange/end"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
