{
  "abstract": [
    {
      "text": "An enumeration that defines possible emergency responses to a Crash Detection event.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safetykit/documentation/SafetyKit",
        "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SafetyKit",
    "externalID": "c:@E@SACrashDetectionEventResponse",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Response"
      }
    ],
    "modules": [
      {
        "name": "SafetyKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Response"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SACrashDetectionEvent.Response"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Response"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Crash Detection event response indicates whether the system attempted to dial the Emergency SOS - Call After Severe Crash provider, depending on the setting in the Settings app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit": {
      "abstract": [
        {
          "text": "Detect and respond to car crash events in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SafetyKit",
      "type": "topic",
      "url": "/documentation/safetykit"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent": {
      "abstract": [
        {
          "text": "Describes the information about a vehicular crash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SACrashDetectionEvent"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SACrashDetectionEvent"
        }
      ],
      "role": "symbol",
      "title": "SACrashDetectionEvent",
      "type": "topic",
      "url": "/documentation/safetykit/sacrashdetectionevent"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum": {
      "abstract": [
        {
          "text": "An enumeration that defines possible emergency responses to a Crash Detection event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Response"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Response"
        }
      ],
      "role": "symbol",
      "title": "SACrashDetectionEvent.Response",
      "type": "topic",
      "url": "/documentation/safetykit/sacrashdetectionevent/response-swift.enum"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/safetykit/sacrashdetectionevent/response-swift.enum/equatable-implementations"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/RawRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/RawRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RawRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/safetykit/sacrashdetectionevent/response-swift.enum/rawrepresentable-implementations"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/attempted": {
      "abstract": [
        {
          "text": "The system attempted to dial the Emergency SOS - Call After Severe Crash provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attempted"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/attempted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SACrashDetectionEventResponseAttempted"
        }
      ],
      "role": "symbol",
      "title": "SACrashDetectionEvent.Response.attempted",
      "type": "topic",
      "url": "/documentation/safetykit/sacrashdetectionevent/response-swift.enum/attempted"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/disabled": {
      "abstract": [
        {
          "text": "The system couldn’t contact the Emergency SOS - Call After Severe Crash provider because the feature is off in the Settings app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disabled"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/disabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SACrashDetectionEventResponseDisabled"
        }
      ],
      "role": "symbol",
      "title": "SACrashDetectionEvent.Response.disabled",
      "type": "topic",
      "url": "/documentation/safetykit/sacrashdetectionevent/response-swift.enum/disabled"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/safetykit/sacrashdetectionevent/response-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseDelegate": {
      "abstract": [
        {
          "text": "The interface for receiving updates about a requested emergency response action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SAEmergencyResponseDelegate"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SAEmergencyResponseDelegate"
        }
      ],
      "role": "symbol",
      "title": "SAEmergencyResponseDelegate",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsedelegate"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager": {
      "abstract": [
        {
          "text": "Provides actions in response to a Crash Detection event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SAEmergencyResponseManager"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SAEmergencyResponseManager"
        }
      ],
      "role": "symbol",
      "title": "SAEmergencyResponseManager",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-a-crash",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager",
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseDelegate"
      ],
      "title": "Responding to a crash"
    }
  ],
  "topicSections": [
    {
      "anchor": "Determining-responses",
      "identifiers": [
        "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/attempted",
        "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/disabled"
      ],
      "title": "Determining responses"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/Equatable-Implementations",
        "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/RawRepresentable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SACrashDetectionEventResponse"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionEventResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionEventResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.safetykit/documentation/SafetyKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Determining-responses",
              "identifiers": [
                "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/attempted",
                "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum/disabled"
              ],
              "title": "Determining responses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-a-crash",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager",
                "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseDelegate"
              ],
              "title": "Responding to a crash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SACrashDetectionEventResponse"
                  },
                  {
                    "kind": "text",
                    "text": ": "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SACrashDetectionEventResponse"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseDelegate/title",
          "value": "SAEmergencyResponseDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent/title",
          "value": "SACrashDetectionEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager/title",
          "value": "SAEmergencyResponseManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent~1Response-swift.enum~1attempted/title",
          "value": "SACrashDetectionEventResponseAttempted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent~1Response-swift.enum~1attempted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionEventResponseAttempted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent~1Response-swift.enum/title",
          "value": "SACrashDetectionEventResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent~1Response-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionEventResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent~1Response-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionEventResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent~1Response-swift.enum~1disabled/title",
          "value": "SACrashDetectionEventResponseDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent~1Response-swift.enum~1disabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionEventResponseDisabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safetykit/sacrashdetectionevent/response-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safetykit/sacrashdetectionevent/response-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
