{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core MIDI Data Types"
  },
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Macros",
      "type": "topic",
      "url": "/documentation/coremidi/coremidi-macros"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIDeviceID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIDeviceID"
        }
      ],
      "role": "symbol",
      "title": "MIDICIDeviceID",
      "type": "topic",
      "url": "/documentation/coremidi/midicideviceid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceManager/DictionaryKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceManager/DictionaryKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DictionaryKey"
        }
      ],
      "role": "symbol",
      "title": "MIDICIDeviceManager.DictionaryKey",
      "type": "topic",
      "url": "/documentation/coremidi/midicidevicemanager/dictionarykey"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDiscoveryResponseBlock": {
      "abstract": [
        {
          "text": "A block the system calls when a MIDI-CI node discovery request completes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIDiscoveryResponseBlock"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDiscoveryResponseBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIDiscoveryResponseBlock"
        }
      ],
      "role": "symbol",
      "title": "MIDICIDiscoveryResponseBlock",
      "type": "topic",
      "url": "/documentation/coremidi/midicidiscoveryresponseblock"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIMUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIMUID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIMUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIMUID"
        }
      ],
      "role": "symbol",
      "title": "MIDICIMUID",
      "type": "topic",
      "url": "/documentation/coremidi/midicimuid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeRequestID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIPropertyExchangeRequestID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeRequestID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIPropertyExchangeRequestID"
        }
      ],
      "role": "symbol",
      "title": "MIDICIPropertyExchangeRequestID",
      "type": "topic",
      "url": "/documentation/coremidi/midicipropertyexchangerequestid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICISessionDisconnectBlock": {
      "abstract": [
        {
          "text": "A block the system calls when a MIDI-CI session disconnects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICISessionDisconnectBlock"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICISessionDisconnectBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICISessionDisconnectBlock"
        }
      ],
      "role": "symbol",
      "title": "MIDICISessionDisconnectBlock",
      "type": "topic",
      "url": "/documentation/coremidi/midicisessiondisconnectblock"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIChannelNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIChannelNumber"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIChannelNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIChannelNumber"
        }
      ],
      "role": "symbol",
      "title": "MIDIChannelNumber",
      "type": "topic",
      "url": "/documentation/coremidi/midichannelnumber"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventVisitor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIEventVisitor"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventVisitor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIEventVisitor"
        }
      ],
      "role": "symbol",
      "title": "MIDIEventVisitor",
      "type": "topic",
      "url": "/documentation/coremidi/midieventvisitor"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRef": {
      "abstract": [
        {
          "text": "A type that represents the global state of the MIDI system, that contains lists of the devices and serial port owners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISetupRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISetupRef"
        }
      ],
      "role": "symbol",
      "title": "MIDISetupRef",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupref"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger14": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUInteger14"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger14",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUInteger14"
        }
      ],
      "role": "symbol",
      "title": "MIDIUInteger14",
      "type": "topic",
      "url": "/documentation/coremidi/midiuinteger14"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUInteger2"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUInteger2"
        }
      ],
      "role": "symbol",
      "title": "MIDIUInteger2",
      "type": "topic",
      "url": "/documentation/coremidi/midiuinteger2"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger28": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUInteger28"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger28",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUInteger28"
        }
      ],
      "role": "symbol",
      "title": "MIDIUInteger28",
      "type": "topic",
      "url": "/documentation/coremidi/midiuinteger28"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUInteger4"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUInteger4"
        }
      ],
      "role": "symbol",
      "title": "MIDIUInteger4",
      "type": "topic",
      "url": "/documentation/coremidi/midiuinteger4"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger7": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUInteger7"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUInteger7"
        }
      ],
      "role": "symbol",
      "title": "MIDIUInteger7",
      "type": "topic",
      "url": "/documentation/coremidi/midiuinteger7"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpointManager/DictionaryKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpointManager/DictionaryKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DictionaryKey"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPEndpointManager.DictionaryKey",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpendpointmanager/dictionarykey"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUMPFunctionBlockID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPFunctionBlockID"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPFunctionBlockID",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpfunctionblockid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPGroupNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUMPGroupNumber"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPGroupNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPGroupNumber"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPGroupNumber",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpgroupnumber"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Constants",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-constants"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Enumerations",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-enumerations"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Functions",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-functions"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Structures",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-structures"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions",
        "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceManager/DictionaryKey",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIMUID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeRequestID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventVisitor",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger14",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger2",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger28",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger4",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger7",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpointManager/DictionaryKey",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPGroupNumber",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDiscoveryResponseBlock",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICISessionDisconnectBlock",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIChannelNumber",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRef"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceManager/DictionaryKey",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIMUID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeRequestID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventVisitor",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger14",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger2",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger28",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger4",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger7",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpointManager/DictionaryKey",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPGroupNumber",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDiscoveryResponseBlock",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICISessionDisconnectBlock",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIChannelNumber",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRef"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions",
                "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIChannelNumber/title",
          "value": "MIDIChannelNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIChannelNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIChannelNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIChannelNumber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIChannelNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger28/title",
          "value": "MIDIUInteger28"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger28/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUInteger28"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger28/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUInteger28"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockID/title",
          "value": "MIDIUMPFunctionBlockID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPFunctionBlockID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPFunctionBlockID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISetupRef/title",
          "value": "MIDISetupRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISetupRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISetupRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISetupRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISetupRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceManager~1DictionaryKey/title",
          "value": "MIDICIDeviceManagerDictionaryKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceManager~1DictionaryKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDeviceManagerDictionaryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceManager~1DictionaryKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDeviceManagerDictionaryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPGroupNumber/title",
          "value": "MIDIUMPGroupNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPGroupNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPGroupNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPGroupNumber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPGroupNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger2/title",
          "value": "MIDIUInteger2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUInteger2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUInteger2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceID/title",
          "value": "MIDICIDeviceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDeviceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDeviceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDiscoveryResponseBlock/title",
          "value": "MIDICIDiscoveryResponseBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDiscoveryResponseBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDiscoveryResponseBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDiscoveryResponseBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDiscoveryResponseBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventVisitor/title",
          "value": "MIDIEventVisitor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventVisitor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIEventVisitor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventVisitor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIEventVisitor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIPropertyExchangeRequestID/title",
          "value": "MIDICIPropertyExchangeRequestID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIPropertyExchangeRequestID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIPropertyExchangeRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIPropertyExchangeRequestID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIPropertyExchangeRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICISessionDisconnectBlock/title",
          "value": "MIDICISessionDisconnectBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICISessionDisconnectBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICISessionDisconnectBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICISessionDisconnectBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICISessionDisconnectBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger7/title",
          "value": "MIDIUInteger7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUInteger7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger7/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUInteger7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIMUID/title",
          "value": "MIDICIMUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIMUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIMUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIMUID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIMUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPEndpointManager~1DictionaryKey/title",
          "value": "MIDIUMPEndpointManagerDictionaryKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPEndpointManager~1DictionaryKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPEndpointManagerDictionaryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPEndpointManager~1DictionaryKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPEndpointManagerDictionaryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger4/title",
          "value": "MIDIUInteger4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUInteger4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUInteger4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger14/title",
          "value": "MIDIUInteger14"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger14/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUInteger14"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger14/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUInteger14"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/core-midi-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/core-midi-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
