{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core MIDI Constants"
  },
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Macros",
      "type": "topic",
      "url": "/documentation/coremidi/coremidi-macros"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Data Types",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-data-types"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Enumerations",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-enumerations"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Functions",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-functions"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Structures",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-structures"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDI1UPMaxSysexSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDI1UPMaxSysexSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDI1UPMaxSysexSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDI1UPMaxSysexSize"
        }
      ],
      "role": "symbol",
      "title": "kMIDI1UPMaxSysexSize",
      "type": "topic",
      "url": "/documentation/coremidi/kmidi1upmaxsysexsize"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDeviceIDFunctionBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIDeviceIDFunctionBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDICIDeviceID",
          "text": "MIDICIDeviceID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDeviceIDFunctionBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIDeviceIDFunctionBlock"
        }
      ],
      "role": "symbol",
      "title": "kMIDIDeviceIDFunctionBlock",
      "type": "topic",
      "url": "/documentation/coremidi/kmidideviceidfunctionblock"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDeviceIDUMPGroup": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIDeviceIDUMPGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDICIDeviceID",
          "text": "MIDICIDeviceID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDeviceIDUMPGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIDeviceIDUMPGroup"
        }
      ],
      "role": "symbol",
      "title": "kMIDIDeviceIDUMPGroup",
      "type": "topic",
      "url": "/documentation/coremidi/kmidideviceidumpgroup"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyAssociatedEndpoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIPropertyAssociatedEndpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyAssociatedEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIPropertyAssociatedEndpoint"
        }
      ],
      "role": "symbol",
      "title": "kMIDIPropertyAssociatedEndpoint",
      "type": "topic",
      "url": "/documentation/coremidi/kmidipropertyassociatedendpoint"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyUMPActiveGroupBitmap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIPropertyUMPActiveGroupBitmap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyUMPActiveGroupBitmap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIPropertyUMPActiveGroupBitmap"
        }
      ],
      "role": "symbol",
      "title": "kMIDIPropertyUMPActiveGroupBitmap",
      "type": "topic",
      "url": "/documentation/coremidi/kmidipropertyumpactivegroupbitmap"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyUMPCanTransmitGroupless": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIPropertyUMPCanTransmitGroupless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyUMPCanTransmitGroupless",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIPropertyUMPCanTransmitGroupless"
        }
      ],
      "role": "symbol",
      "title": "kMIDIPropertyUMPCanTransmitGroupless",
      "type": "topic",
      "url": "/documentation/coremidi/kmidipropertyumpcantransmitgroupless"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger14Max": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIUInteger14Max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger14",
          "text": "MIDIUInteger14"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger14Max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIUInteger14Max"
        }
      ],
      "role": "symbol",
      "title": "kMIDIUInteger14Max",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiuinteger14max"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger28Max": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIUInteger28Max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger28",
          "text": "MIDIUInteger28"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger28Max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIUInteger28Max"
        }
      ],
      "role": "symbol",
      "title": "kMIDIUInteger28Max",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiuinteger28max"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger2Max": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIUInteger2Max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger2",
          "text": "MIDIUInteger2"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger2Max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIUInteger2Max"
        }
      ],
      "role": "symbol",
      "title": "kMIDIUInteger2Max",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiuinteger2max"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger4Max": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIUInteger4Max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger4",
          "text": "MIDIUInteger4"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger4Max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIUInteger4Max"
        }
      ],
      "role": "symbol",
      "title": "kMIDIUInteger4Max",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiuinteger4max"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger7Max": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIUInteger7Max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger7",
          "text": "MIDIUInteger7"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger7Max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIUInteger7Max"
        }
      ],
      "role": "symbol",
      "title": "kMIDIUInteger7Max",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiuinteger7max"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types",
        "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDI1UPMaxSysexSize",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDeviceIDFunctionBlock",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDeviceIDUMPGroup",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyAssociatedEndpoint",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyUMPActiveGroupBitmap",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyUMPCanTransmitGroupless",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger14Max",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger28Max",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger2Max",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger4Max",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger7Max"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDI1UPMaxSysexSize",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDeviceIDFunctionBlock",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDeviceIDUMPGroup",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyAssociatedEndpoint",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyUMPActiveGroupBitmap",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyUMPCanTransmitGroupless",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger14Max",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger28Max",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger2Max",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger4Max",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUInteger7Max"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types",
                "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUInteger2Max/title",
          "value": "kMIDIUInteger2Max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUInteger2Max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIUInteger2Max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIDeviceIDUMPGroup/title",
          "value": "kMIDIDeviceIDUMPGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIDeviceIDUMPGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIDeviceIDUMPGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUInteger4Max/title",
          "value": "kMIDIUInteger4Max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUInteger4Max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIUInteger4Max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIPropertyUMPCanTransmitGroupless/title",
          "value": "kMIDIPropertyUMPCanTransmitGroupless"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIPropertyUMPCanTransmitGroupless/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIPropertyUMPCanTransmitGroupless"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIPropertyUMPActiveGroupBitmap/title",
          "value": "kMIDIPropertyUMPActiveGroupBitmap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIPropertyUMPActiveGroupBitmap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIPropertyUMPActiveGroupBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDI1UPMaxSysexSize/title",
          "value": "kMIDI1UPMaxSysexSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDI1UPMaxSysexSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDI1UPMaxSysexSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUInteger28Max/title",
          "value": "kMIDIUInteger28Max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUInteger28Max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIUInteger28Max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUInteger14Max/title",
          "value": "kMIDIUInteger14Max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUInteger14Max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIUInteger14Max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUInteger7Max/title",
          "value": "kMIDIUInteger7Max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUInteger7Max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIUInteger7Max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIPropertyAssociatedEndpoint/title",
          "value": "kMIDIPropertyAssociatedEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIPropertyAssociatedEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIPropertyAssociatedEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIDeviceIDFunctionBlock/title",
          "value": "kMIDIDeviceIDFunctionBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIDeviceIDFunctionBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIDeviceIDFunctionBlock"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/core-midi-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/core-midi-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
