{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core MIDI Structures"
  },
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Macros",
      "type": "topic",
      "url": "/documentation/coremidi/coremidi-macros"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceManufacturer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2DeviceManufacturer"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceManufacturer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2DeviceManufacturer"
        }
      ],
      "role": "symbol",
      "title": "MIDI2DeviceManufacturer",
      "type": "topic",
      "url": "/documentation/coremidi/midi2devicemanufacturer"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceRevisionLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2DeviceRevisionLevel"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceRevisionLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2DeviceRevisionLevel"
        }
      ],
      "role": "symbol",
      "title": "MIDI2DeviceRevisionLevel",
      "type": "topic",
      "url": "/documentation/coremidi/midi2devicerevisionlevel"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProfileID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProfileID"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProfileID",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofileid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDManufacturerSpecific": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProfileIDManufacturerSpecific"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDManufacturerSpecific",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProfileIDManufacturerSpecific"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProfileIDManufacturerSpecific",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofileidmanufacturerspecific"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDStandard": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProfileIDStandard"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDStandard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProfileIDStandard"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProfileIDStandard",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofileidstandard"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUniversalMessage"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUniversalMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDIUniversalMessage",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Constants",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-constants"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Data Types",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-data-types"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Enumerations",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-enumerations"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Functions",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-functions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types",
        "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceManufacturer",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceRevisionLevel",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDManufacturerSpecific",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDStandard",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Structures",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceManufacturer",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceRevisionLevel",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDManufacturerSpecific",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDStandard",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types",
                "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileID/title",
          "value": "MIDICIProfileID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileIDStandard/title",
          "value": "MIDICIProfileIDStandard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileIDStandard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileIDStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileIDStandard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileIDStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUniversalMessage/title",
          "value": "MIDIUniversalMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUniversalMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUniversalMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUniversalMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUniversalMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2DeviceRevisionLevel/title",
          "value": "MIDI2DeviceRevisionLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2DeviceRevisionLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2DeviceRevisionLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2DeviceRevisionLevel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2DeviceRevisionLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileIDManufacturerSpecific/title",
          "value": "MIDICIProfileIDManufacturerSpecific"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileIDManufacturerSpecific/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileIDManufacturerSpecific"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileIDManufacturerSpecific/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileIDManufacturerSpecific"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2DeviceManufacturer/title",
          "value": "MIDI2DeviceManufacturer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2DeviceManufacturer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2DeviceManufacturer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2DeviceManufacturer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2DeviceManufacturer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/core-midi-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/core-midi-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
