{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core MIDI Functions"
  },
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Macros",
      "type": "topic",
      "url": "/documentation/coremidi/coremidi-macros"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPChannelPressure(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI1UPChannelPressure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIMessage_32",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPChannelPressure(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI1UPChannelPressure"
        }
      ],
      "role": "symbol",
      "title": "MIDI1UPChannelPressure(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi1upchannelpressure(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPPolyPressure(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI1UPPolyPressure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIMessage_32",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPPolyPressure(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI1UPPolyPressure"
        }
      ],
      "role": "symbol",
      "title": "MIDI1UPPolyPressure(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi1uppolypressure(_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPProgramChange(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI1UPProgramChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIMessage_32",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPProgramChange(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI1UPProgramChange"
        }
      ],
      "role": "symbol",
      "title": "MIDI1UPProgramChange(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi1upprogramchange(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPSysEx(_:_:_:_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI1UPSysEx"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPSysEx(_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI1UPSysEx"
        }
      ],
      "role": "symbol",
      "title": "MIDI1UPSysEx(_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi1upsysex(_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPSysExArray(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI1UPSysExArray"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPSysExArray(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI1UPSysExArray"
        }
      ],
      "role": "symbol",
      "title": "MIDI1UPSysExArray(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi1upsysexarray(_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndOfClipMessage()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2EndOfClipMessage"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_128",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndOfClipMessage()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2EndOfClipMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI2EndOfClipMessage()",
      "type": "topic",
      "url": "/documentation/coremidi/midi2endofclipmessage()"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointDeviceIdentityNotificationMessage(_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2EndpointDeviceIdentityNotificationMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger7",
          "text": "MIDIUInteger7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger7",
          "text": "MIDIUInteger7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger7",
          "text": "MIDIUInteger7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger14",
          "text": "MIDIUInteger14"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger14",
          "text": "MIDIUInteger14"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger28",
          "text": "MIDIUInteger28"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_128",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointDeviceIdentityNotificationMessage(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2EndpointDeviceIdentityNotificationMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI2EndpointDeviceIdentityNotificationMessage(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2endpointdeviceidentitynotificationmessage(_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointDiscoveryMessage(_:_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2EndpointDiscoveryMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_128",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointDiscoveryMessage(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2EndpointDiscoveryMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI2EndpointDiscoveryMessage(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2endpointdiscoverymessage(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointInfoNotificationMessage(_:_:_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2EndpointInfoNotificationMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_128",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointInfoNotificationMessage(_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2EndpointInfoNotificationMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI2EndpointInfoNotificationMessage(_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2endpointinfonotificationmessage(_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointNameNotificationMessage(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2EndpointNameNotificationMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UMPStreamMessageFormat",
          "text": "UMPStreamMessageFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_128",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointNameNotificationMessage(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2EndpointNameNotificationMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI2EndpointNameNotificationMessage(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2endpointnamenotificationmessage(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointProductInstanceIDNotificationMessage(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2EndpointProductInstanceIDNotificationMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UMPStreamMessageFormat",
          "text": "UMPStreamMessageFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_128",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointProductInstanceIDNotificationMessage(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2EndpointProductInstanceIDNotificationMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI2EndpointProductInstanceIDNotificationMessage(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2endpointproductinstanceidnotificationmessage(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FlexDataMessage(_:_:_:_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2FlexDataMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger4",
          "text": "MIDIUInteger4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger2",
          "text": "MIDIUInteger2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger2",
          "text": "MIDIUInteger2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger4",
          "text": "MIDIUInteger4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_128",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FlexDataMessage(_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2FlexDataMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI2FlexDataMessage(_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2flexdatamessage(_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FunctionBlockDiscoveryMessage(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2FunctionBlockDiscoveryMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_128",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FunctionBlockDiscoveryMessage(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2FunctionBlockDiscoveryMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI2FunctionBlockDiscoveryMessage(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2functionblockdiscoverymessage(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FunctionBlockInfoNotificationMessage(_:_:_:_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2FunctionBlockInfoNotificationMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger7",
          "text": "MIDIUInteger7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MIDIUMPFunctionBlockUIHint",
          "text": "MIDIUMPFunctionBlockUIHint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MIDIUMPFunctionBlockMIDI1Info",
          "text": "MIDIUMPFunctionBlockMIDI1Info"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MIDIUMPFunctionBlockDirection",
          "text": "MIDIUMPFunctionBlockDirection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_128",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FunctionBlockInfoNotificationMessage(_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2FunctionBlockInfoNotificationMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI2FunctionBlockInfoNotificationMessage(_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2functionblockinfonotificationmessage(_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FunctionBlockNameNotificationMessage(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2FunctionBlockNameNotificationMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UMPStreamMessageFormat",
          "text": "UMPStreamMessageFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_128",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FunctionBlockNameNotificationMessage(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2FunctionBlockNameNotificationMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI2FunctionBlockNameNotificationMessage(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2functionblocknamenotificationmessage(_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StartOfClipMessage()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2StartOfClipMessage"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_128",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StartOfClipMessage()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2StartOfClipMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI2StartOfClipMessage()",
      "type": "topic",
      "url": "/documentation/coremidi/midi2startofclipmessage()"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamConfigurationNotificationMessage(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2StreamConfigurationNotificationMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_128",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamConfigurationNotificationMessage(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2StreamConfigurationNotificationMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI2StreamConfigurationNotificationMessage(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2streamconfigurationnotificationmessage(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamConfigurationRequestMessage(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2StreamConfigurationRequestMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_128",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamConfigurationRequestMessage(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2StreamConfigurationRequestMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI2StreamConfigurationRequestMessage(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2streamconfigurationrequestmessage(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamMessage(_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2StreamMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UMPStreamMessageFormat",
          "text": "UMPStreamMessageFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UMPStreamMessageStatus",
          "text": "UMPStreamMessageStatus"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_128",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamMessage(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2StreamMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI2StreamMessage(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2streammessage(_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamMessageFromData(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2StreamMessageFromData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UMPStreamMessageFormat",
          "text": "UMPStreamMessageFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UMPStreamMessageStatus",
          "text": "UMPStreamMessageStatus"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_128",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamMessageFromData(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2StreamMessageFromData"
        }
      ],
      "role": "symbol",
      "title": "MIDI2StreamMessageFromData(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2streammessagefromdata(_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeltaClockstampTicksPerQuarterNoteMessage(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDeltaClockstampTicksPerQuarterNoteMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIMessage_32",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeltaClockstampTicksPerQuarterNoteMessage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDeltaClockstampTicksPerQuarterNoteMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDIDeltaClockstampTicksPerQuarterNoteMessage(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midideltaclockstampticksperquarternotemessage(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceAddEntity(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Specifies one of the entities that make up a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDeviceAddEntity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceRef",
          "text": "MIDIDeviceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEntityRef",
          "text": "MIDIEntityRef"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceAddEntity(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDeviceAddEntity"
        }
      ],
      "role": "symbol",
      "title": "MIDIDeviceAddEntity(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midideviceaddentity(_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventListForEachEvent(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIEventListForEachEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIEventList",
          "text": "MIDIEventList"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEventVisitor",
          "text": "MIDIEventVisitor"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventListForEachEvent(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIEventListForEachEvent"
        }
      ],
      "role": "symbol",
      "title": "MIDIEventListForEachEvent(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midieventlistforeachevent(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetSerialPortDrivers": {
      "abstract": [
        {
          "text": "Returns a list of installed MIDI drivers for serial port MIDI devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDIGetSerialPortDrivers"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetSerialPortDrivers",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDIGetSerialPortDrivers",
      "type": "topic",
      "url": "/documentation/coremidi/midigetserialportdrivers"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetSerialPortOwner": {
      "abstract": [
        {
          "text": "Returns the MIDI driver that owns a serial port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDIGetSerialPortOwner"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetSerialPortOwner",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDIGetSerialPortOwner",
      "type": "topic",
      "url": "/documentation/coremidi/midigetserialportowner"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIJitterReductionClockMessage(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIJitterReductionClockMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIMessage_32",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIJitterReductionClockMessage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIJitterReductionClockMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDIJitterReductionClockMessage(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midijitterreductionclockmessage(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIJitterReductionTimestampMessage(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIJitterReductionTimestampMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIMessage_32",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIJitterReductionTimestampMessage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIJitterReductionTimestampMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDIJitterReductionTimestampMessage(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midijitterreductiontimestampmessage(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINoOpMessage()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDINoOpMessage"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIMessage_32",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINoOpMessage()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDINoOpMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDINoOpMessage()",
      "type": "topic",
      "url": "/documentation/coremidi/midinoopmessage()"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetSerialPortOwner": {
      "abstract": [
        {
          "text": "Specifies the MIDI driver that owns a serial port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDISetSerialPortOwner"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetSerialPortOwner",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDISetSerialPortOwner",
      "type": "topic",
      "url": "/documentation/coremidi/midisetserialportowner"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupCreate": {
      "abstract": [
        {
          "text": "Queries drivers to discover what hardware is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDISetupCreate"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDISetupCreate",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupcreate"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupDispose": {
      "abstract": [
        {
          "text": "Disposes the specified setup object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDISetupDispose"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupDispose",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDISetupDispose",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupdispose"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupFromData": {
      "abstract": [
        {
          "text": "Creates a MIDISetup object from an XML stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDISetupFromData"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupFromData",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDISetupFromData",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupfromdata"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupGetCurrent": {
      "abstract": [
        {
          "text": "Returns the systems current MIDISetup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDISetupGetCurrent"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupGetCurrent",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDISetupGetCurrent",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupgetcurrent"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupInstall": {
      "abstract": [
        {
          "text": "Installs a MIDISetup as the systems current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDISetupInstall"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupInstall",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDISetupInstall",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupinstall"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupToData": {
      "abstract": [
        {
          "text": "Creates an XML representation of a MIDISetup object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDISetupToData"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupToData",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDISetupToData",
      "type": "topic",
      "url": "/documentation/coremidi/midisetuptodata"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITicksSinceLastEventMessage(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDITicksSinceLastEventMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIMessage_32",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITicksSinceLastEventMessage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDITicksSinceLastEventMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDITicksSinceLastEventMessage(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/miditickssincelasteventmessage(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Constants",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-constants"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Data Types",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-data-types"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Enumerations",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-enumerations"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core MIDI Structures",
      "type": "topic",
      "url": "/documentation/coremidi/core-midi-structures"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants",
        "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types",
        "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPChannelPressure(_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPPolyPressure(_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPProgramChange(_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPSysEx(_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPSysExArray(_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndOfClipMessage()",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointDeviceIdentityNotificationMessage(_:_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointDiscoveryMessage(_:_:_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointInfoNotificationMessage(_:_:_:_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointNameNotificationMessage(_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointProductInstanceIDNotificationMessage(_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FlexDataMessage(_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FunctionBlockDiscoveryMessage(_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FunctionBlockInfoNotificationMessage(_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FunctionBlockNameNotificationMessage(_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StartOfClipMessage()",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamConfigurationNotificationMessage(_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamConfigurationRequestMessage(_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamMessage(_:_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamMessageFromData(_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeltaClockstampTicksPerQuarterNoteMessage(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceAddEntity(_:_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventListForEachEvent(_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIJitterReductionClockMessage(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIJitterReductionTimestampMessage(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINoOpMessage()",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITicksSinceLastEventMessage(_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPChannelPressure(_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPPolyPressure(_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPProgramChange(_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPSysEx(_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPSysExArray(_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndOfClipMessage()",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointDeviceIdentityNotificationMessage(_:_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointDiscoveryMessage(_:_:_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointInfoNotificationMessage(_:_:_:_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointNameNotificationMessage(_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2EndpointProductInstanceIDNotificationMessage(_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FlexDataMessage(_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FunctionBlockDiscoveryMessage(_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FunctionBlockInfoNotificationMessage(_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2FunctionBlockNameNotificationMessage(_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StartOfClipMessage()",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamConfigurationNotificationMessage(_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamConfigurationRequestMessage(_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamMessage(_:_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2StreamMessageFromData(_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeltaClockstampTicksPerQuarterNoteMessage(_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceAddEntity(_:_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventListForEachEvent(_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetSerialPortDrivers",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetSerialPortOwner",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIJitterReductionClockMessage(_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIJitterReductionTimestampMessage(_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINoOpMessage()",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetSerialPortOwner",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupCreate",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupDispose",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupFromData",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupGetCurrent",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupInstall",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupToData",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITicksSinceLastEventMessage(_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-structures",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-enumerations",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-constants",
                "doc://com.apple.coremidi/documentation/CoreMIDI/core-midi-data-types",
                "doc://com.apple.coremidi/documentation/CoreMIDI/CoreMIDI-macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2FunctionBlockNameNotificationMessage(_:_:_:_:)/title",
          "value": "MIDI2FunctionBlockNameNotificationMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2FunctionBlockNameNotificationMessage(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2FunctionBlockNameNotificationMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceAddEntity(_:_:_:_:_:_:)/title",
          "value": "MIDIDeviceAddEntity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceAddEntity(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceAddEntity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2EndpointProductInstanceIDNotificationMessage(_:_:_:)/title",
          "value": "MIDI2EndpointProductInstanceIDNotificationMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2EndpointProductInstanceIDNotificationMessage(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2EndpointProductInstanceIDNotificationMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2EndpointNameNotificationMessage(_:_:_:)/title",
          "value": "MIDI2EndpointNameNotificationMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2EndpointNameNotificationMessage(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2EndpointNameNotificationMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2StreamMessage(_:_:_:_:_:_:)/title",
          "value": "MIDI2StreamMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2StreamMessage(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2StreamMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2FunctionBlockDiscoveryMessage(_:_:_:)/title",
          "value": "MIDI2FunctionBlockDiscoveryMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2FunctionBlockDiscoveryMessage(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2FunctionBlockDiscoveryMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2FunctionBlockInfoNotificationMessage(_:_:_:_:_:_:_:_:_:)/title",
          "value": "MIDI2FunctionBlockInfoNotificationMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2FunctionBlockInfoNotificationMessage(_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2FunctionBlockInfoNotificationMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINoOpMessage()/title",
          "value": "MIDINoOpMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINoOpMessage()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINoOpMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2EndpointInfoNotificationMessage(_:_:_:_:_:_:_:_:)/title",
          "value": "MIDI2EndpointInfoNotificationMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2EndpointInfoNotificationMessage(_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2EndpointInfoNotificationMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPSysEx(_:_:_:_:_:_:_:_:_:)/title",
          "value": "MIDI1UPSysEx"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPSysEx(_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI1UPSysEx"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeltaClockstampTicksPerQuarterNoteMessage(_:)/title",
          "value": "MIDIDeltaClockstampTicksPerQuarterNoteMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeltaClockstampTicksPerQuarterNoteMessage(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeltaClockstampTicksPerQuarterNoteMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2StreamMessageFromData(_:_:_:_:)/title",
          "value": "MIDI2StreamMessageFromData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2StreamMessageFromData(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2StreamMessageFromData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIJitterReductionTimestampMessage(_:)/title",
          "value": "MIDIJitterReductionTimestampMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIJitterReductionTimestampMessage(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIJitterReductionTimestampMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2StreamConfigurationNotificationMessage(_:_:_:)/title",
          "value": "MIDI2StreamConfigurationNotificationMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2StreamConfigurationNotificationMessage(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2StreamConfigurationNotificationMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPChannelPressure(_:_:_:)/title",
          "value": "MIDI1UPChannelPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPChannelPressure(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI1UPChannelPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPPolyPressure(_:_:_:_:)/title",
          "value": "MIDI1UPPolyPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPPolyPressure(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI1UPPolyPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2FlexDataMessage(_:_:_:_:_:_:_:_:_:)/title",
          "value": "MIDI2FlexDataMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2FlexDataMessage(_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2FlexDataMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2EndpointDeviceIdentityNotificationMessage(_:_:_:_:_:_:)/title",
          "value": "MIDI2EndpointDeviceIdentityNotificationMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2EndpointDeviceIdentityNotificationMessage(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2EndpointDeviceIdentityNotificationMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2StartOfClipMessage()/title",
          "value": "MIDI2StartOfClipMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2StartOfClipMessage()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2StartOfClipMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPProgramChange(_:_:_:)/title",
          "value": "MIDI1UPProgramChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPProgramChange(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI1UPProgramChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventListForEachEvent(_:_:_:)/title",
          "value": "MIDIEventListForEachEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventListForEachEvent(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIEventListForEachEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPSysExArray(_:_:_:_:)/title",
          "value": "MIDI1UPSysExArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPSysExArray(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI1UPSysExArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2EndpointDiscoveryMessage(_:_:_:_:_:_:_:)/title",
          "value": "MIDI2EndpointDiscoveryMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2EndpointDiscoveryMessage(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2EndpointDiscoveryMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2StreamConfigurationRequestMessage(_:_:_:)/title",
          "value": "MIDI2StreamConfigurationRequestMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2StreamConfigurationRequestMessage(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2StreamConfigurationRequestMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIJitterReductionClockMessage(_:)/title",
          "value": "MIDIJitterReductionClockMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIJitterReductionClockMessage(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIJitterReductionClockMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2EndOfClipMessage()/title",
          "value": "MIDI2EndOfClipMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2EndOfClipMessage()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2EndOfClipMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITicksSinceLastEventMessage(_:)/title",
          "value": "MIDITicksSinceLastEventMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITicksSinceLastEventMessage(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDITicksSinceLastEventMessage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/core-midi-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/core-midi-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
