{
  "abstract": [
    {
      "text": "Values that define the supported endpoint configurations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/endpoint-configuration"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Endpoint Configuration"
  },
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionCreate(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a MIDI thru connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIThruConnectionRef",
          "text": "MIDIThruConnectionRef"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionCreate(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionCreate"
        }
      ],
      "role": "symbol",
      "title": "MIDIThruConnectionCreate(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectioncreate(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionDispose(_:)": {
      "abstract": [
        {
          "text": "Disposes a MIDI thru connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionDispose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIThruConnectionRef",
          "text": "MIDIThruConnectionRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionDispose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionDispose"
        }
      ],
      "role": "symbol",
      "title": "MIDIThruConnectionDispose(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectiondispose(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint": {
      "abstract": [
        {
          "text": "A source or destination in a MIDI thru connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionEndpoint"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionEndpoint"
        }
      ],
      "role": "symbol",
      "title": "MIDIThruConnectionEndpoint",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionendpoint"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionRef": {
      "abstract": [
        {
          "text": "An opaque reference to a play-through connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionRef"
        }
      ],
      "role": "symbol",
      "title": "MIDIThruConnectionRef",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionref"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIThruConnection_MaxEndpoints": {
      "abstract": [
        {
          "text": "The maximum number of endpoints for this connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIThruConnection_MaxEndpoints"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIThruConnection_MaxEndpoints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIThruConnection_MaxEndpoints"
        }
      ],
      "role": "symbol",
      "title": "kMIDIThruConnection_MaxEndpoints",
      "type": "topic",
      "url": "/documentation/coremidi/kmidithruconnection_maxendpoints"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection": {
      "abstract": [
        {
          "text": "Create play-through connections between sources and destinations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Thru Connection",
      "type": "topic",
      "url": "/documentation/coremidi/midi-thru-connection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Connections",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionCreate(_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionDispose(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionRef",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint"
      ],
      "title": "Managing Connections"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuration-Constants",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIThruConnection_MaxEndpoints"
      ],
      "title": "Configuration Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuration-Constants",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIThruConnection_MaxEndpoints"
              ],
              "title": "Configuration Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Connections",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionCreate(_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionDispose(_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionRef",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint"
              ],
              "title": "Managing Connections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionDispose(_:)/title",
          "value": "MIDIThruConnectionDispose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionDispose(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionDispose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionCreate(_:_:_:)/title",
          "value": "MIDIThruConnectionCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionCreate(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIThruConnection_MaxEndpoints/title",
          "value": "kMIDIThruConnection_MaxEndpoints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIThruConnection_MaxEndpoints/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIThruConnection_MaxEndpoints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionEndpoint/title",
          "value": "MIDIThruConnectionEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionRef/title",
          "value": "MIDIThruConnectionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/endpoint-configuration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/endpoint-configuration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
