{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether the device implements the MIDI Show Control specification.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertySupportsShowControl"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kMIDIPropertySupportsShowControl",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kMIDIPropertySupportsShowControl"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMIDIPropertySupportsShowControl"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kMIDIPropertySupportsShowControl"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kMIDIPropertySupportsShowControl"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertySupportsGeneralMIDI": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device or entity implements the General MIDI specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIPropertySupportsGeneralMIDI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertySupportsGeneralMIDI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIPropertySupportsGeneralMIDI"
        }
      ],
      "role": "symbol",
      "title": "kMIDIPropertySupportsGeneralMIDI",
      "type": "topic",
      "url": "/documentation/coremidi/kmidipropertysupportsgeneralmidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertySupportsMMC": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device or entity implements the MIDI Machine Control portion of the MIDI specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIPropertySupportsMMC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertySupportsMMC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIPropertySupportsMMC"
        }
      ],
      "role": "symbol",
      "title": "kMIDIPropertySupportsMMC",
      "type": "topic",
      "url": "/documentation/coremidi/kmidipropertysupportsmmc"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertySupportsShowControl": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device implements the MIDI Show Control specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIPropertySupportsShowControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertySupportsShowControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIPropertySupportsShowControl"
        }
      ],
      "role": "symbol",
      "title": "kMIDIPropertySupportsShowControl",
      "type": "topic",
      "url": "/documentation/coremidi/kmidipropertysupportsshowcontrol"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Capabilities",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertySupportsMMC",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertySupportsGeneralMIDI"
      ],
      "title": "Capabilities"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMIDIPropertySupportsShowControl"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIPropertySupportsShowControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Capabilities",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertySupportsMMC",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertySupportsGeneralMIDI"
              ],
              "title": "Capabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kMIDIPropertySupportsShowControl"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIPropertySupportsGeneralMIDI/title",
          "value": "kMIDIPropertySupportsGeneralMIDI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIPropertySupportsGeneralMIDI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIPropertySupportsGeneralMIDI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIPropertySupportsShowControl/title",
          "value": "kMIDIPropertySupportsShowControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIPropertySupportsShowControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIPropertySupportsShowControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIPropertySupportsMMC/title",
          "value": "kMIDIPropertySupportsMMC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIPropertySupportsMMC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIPropertySupportsMMC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/kmidipropertysupportsshowcontrol"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/kmidipropertysupportsshowcontrol"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
