{
  "abstract": [
    {
      "text": "The connection you’re trying to close doesn’t exist.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoConnection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kMIDIInvalidClient@kMIDINoConnection",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kMIDINoConnection"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMIDINoConnection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kMIDINoConnection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kMIDINoConnection"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIIDNotUnique": {
      "abstract": [
        {
          "text": "The identifier you’re trying to set isn’t unique.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIIDNotUnique"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIIDNotUnique",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIIDNotUnique"
        }
      ],
      "role": "symbol",
      "title": "kMIDIIDNotUnique",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiidnotunique"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidClient": {
      "abstract": [
        {
          "text": "The client is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIInvalidClient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidClient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIInvalidClient"
        }
      ],
      "role": "symbol",
      "title": "kMIDIInvalidClient",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiinvalidclient"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidPort": {
      "abstract": [
        {
          "text": "The port is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIInvalidPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIInvalidPort"
        }
      ],
      "role": "symbol",
      "title": "kMIDIInvalidPort",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiinvalidport"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIMessageSendErr": {
      "abstract": [
        {
          "text": "The communication with the MIDI server failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIMessageSendErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIMessageSendErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMessageSendErr"
        }
      ],
      "role": "symbol",
      "title": "kMIDIMessageSendErr",
      "type": "topic",
      "url": "/documentation/coremidi/kmidimessagesenderr"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoConnection": {
      "abstract": [
        {
          "text": "The connection you’re trying to close doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDINoConnection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDINoConnection"
        }
      ],
      "role": "symbol",
      "title": "kMIDINoConnection",
      "type": "topic",
      "url": "/documentation/coremidi/kmidinoconnection"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoCurrentSetup": {
      "abstract": [
        {
          "text": "A MIDI setup object doesn’t currently exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDINoCurrentSetup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoCurrentSetup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDINoCurrentSetup"
        }
      ],
      "role": "symbol",
      "title": "kMIDINoCurrentSetup",
      "type": "topic",
      "url": "/documentation/coremidi/kmidinocurrentsetup"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINotPermitted": {
      "abstract": [
        {
          "text": "The process doesn’t have privileges for the requested operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDINotPermitted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINotPermitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDINotPermitted"
        }
      ],
      "role": "symbol",
      "title": "kMIDINotPermitted",
      "type": "topic",
      "url": "/documentation/coremidi/kmidinotpermitted"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIObjectNotFound": {
      "abstract": [
        {
          "text": "The requested object doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIObjectNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIObjectNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIObjectNotFound"
        }
      ],
      "role": "symbol",
      "title": "kMIDIObjectNotFound",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiobjectnotfound"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIServerStartErr": {
      "abstract": [
        {
          "text": "The system can’t start the MIDI server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIServerStartErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIServerStartErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIServerStartErr"
        }
      ],
      "role": "symbol",
      "title": "kMIDIServerStartErr",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiserverstarterr"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDISetupFormatErr": {
      "abstract": [
        {
          "text": "The system can’t read the saved state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDISetupFormatErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDISetupFormatErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDISetupFormatErr"
        }
      ],
      "role": "symbol",
      "title": "kMIDISetupFormatErr",
      "type": "topic",
      "url": "/documentation/coremidi/kmidisetupformaterr"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUnknownEndpoint": {
      "abstract": [
        {
          "text": "The system doesn’t recognize the endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIUnknownEndpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUnknownEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIUnknownEndpoint"
        }
      ],
      "role": "symbol",
      "title": "kMIDIUnknownEndpoint",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiunknownendpoint"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUnknownError": {
      "abstract": [
        {
          "text": "The system can’t perform the requested operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIUnknownError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUnknownError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIUnknownError"
        }
      ],
      "role": "symbol",
      "title": "kMIDIUnknownError",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiunknownerror"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUnknownProperty": {
      "abstract": [
        {
          "text": "The property you’re trying to query isn’t set on the object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIUnknownProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUnknownProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIUnknownProperty"
        }
      ],
      "role": "symbol",
      "title": "kMIDIUnknownProperty",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiunknownproperty"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIWrongEndpointType": {
      "abstract": [
        {
          "text": "A function received a source endpoint when it required a destination endpoint, or vice versa.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIWrongEndpointType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIWrongEndpointType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIWrongEndpointType"
        }
      ],
      "role": "symbol",
      "title": "kMIDIWrongEndpointType",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiwrongendpointtype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIWrongPropertyType": {
      "abstract": [
        {
          "text": "The value you assigned to the property is the wrong type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIWrongPropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIWrongPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIWrongPropertyType"
        }
      ],
      "role": "symbol",
      "title": "kMIDIWrongPropertyType",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiwrongpropertytype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIWrongThread": {
      "abstract": [
        {
          "text": "A driver is calling a non-I/O function in the server from a thread other than the server’s main thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIWrongThread"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIWrongThread",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIWrongThread"
        }
      ],
      "role": "symbol",
      "title": "kMIDIWrongThread",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiwrongthread"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidClient",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidPort",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIWrongEndpointType",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUnknownEndpoint",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUnknownProperty",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIWrongPropertyType",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoCurrentSetup",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIMessageSendErr",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIServerStartErr",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDISetupFormatErr",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIWrongThread",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIObjectNotFound",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIIDNotUnique",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINotPermitted",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUnknownError"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMIDINoConnection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDINoConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidClient",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidPort",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIWrongEndpointType",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUnknownEndpoint",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUnknownProperty",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIWrongPropertyType",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINoCurrentSetup",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIMessageSendErr",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIServerStartErr",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDISetupFormatErr",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIWrongThread",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIObjectNotFound",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIIDNotUnique",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDINotPermitted",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIUnknownError"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMIDINoConnection"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDISetupFormatErr/title",
          "value": "kMIDISetupFormatErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDISetupFormatErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDISetupFormatErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIObjectNotFound/title",
          "value": "kMIDIObjectNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIObjectNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIObjectNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUnknownError/title",
          "value": "kMIDIUnknownError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUnknownError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIUnknownError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIIDNotUnique/title",
          "value": "kMIDIIDNotUnique"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIIDNotUnique/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIIDNotUnique"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIInvalidClient/title",
          "value": "kMIDIInvalidClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIInvalidClient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIInvalidClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDINotPermitted/title",
          "value": "kMIDINotPermitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDINotPermitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDINotPermitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDINoCurrentSetup/title",
          "value": "kMIDINoCurrentSetup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDINoCurrentSetup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDINoCurrentSetup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDINoConnection/title",
          "value": "kMIDINoConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDINoConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDINoConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIWrongEndpointType/title",
          "value": "kMIDIWrongEndpointType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIWrongEndpointType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIWrongEndpointType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUnknownEndpoint/title",
          "value": "kMIDIUnknownEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUnknownEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIUnknownEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIWrongThread/title",
          "value": "kMIDIWrongThread"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIWrongThread/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIWrongThread"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIWrongPropertyType/title",
          "value": "kMIDIWrongPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIWrongPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIWrongPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIMessageSendErr/title",
          "value": "kMIDIMessageSendErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIMessageSendErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMessageSendErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUnknownProperty/title",
          "value": "kMIDIUnknownProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIUnknownProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIUnknownProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIServerStartErr/title",
          "value": "kMIDIServerStartErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIServerStartErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIServerStartErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIInvalidPort/title",
          "value": "kMIDIInvalidPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIInvalidPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIInvalidPort"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/kmidinoconnection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/kmidinoconnection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
