{
  "abstract": [
    {
      "text": "MIDI System status types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MIDISystemStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MIDISystemStatus"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MIDISystemStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MIDISystemStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MIDISystemStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus": {
      "abstract": [
        {
          "text": "MIDI status types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICVStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICVStatus"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType": {
      "abstract": [
        {
          "text": "Supported MIDI message types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessageType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessageType"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessageType",
      "type": "topic",
      "url": "/documentation/coremidi/midimessagetype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_128": {
      "abstract": [
        {
          "text": "A 128-bit MIDI message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_128",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessage_128"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessage_128",
      "type": "topic",
      "url": "/documentation/coremidi/midimessage_128"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_32": {
      "abstract": [
        {
          "text": "A 32-bit MIDI message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessage_32"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessage_32",
      "type": "topic",
      "url": "/documentation/coremidi/midimessage_32"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_64": {
      "abstract": [
        {
          "text": "A 64-bit MIDI message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessage_64"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessage_64",
      "type": "topic",
      "url": "/documentation/coremidi/midimessage_64"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_96": {
      "abstract": [
        {
          "text": "A 96-bit MIDI message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessage_96"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_96",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessage_96"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessage_96",
      "type": "topic",
      "url": "/documentation/coremidi/midimessage_96"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID": {
      "abstract": [
        {
          "text": "Specifies a MIDI protocol variant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIProtocolID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIProtocolID"
        }
      ],
      "role": "symbol",
      "title": "MIDIProtocolID",
      "type": "topic",
      "url": "/documentation/coremidi/midiprotocolid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysExStatus": {
      "abstract": [
        {
          "text": "MIDI System Exclusive (SysEx) types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISysExStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysExStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISysExStatus"
        }
      ],
      "role": "symbol",
      "title": "MIDISysExStatus",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexstatus"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus": {
      "abstract": [
        {
          "text": "MIDI System status types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISystemStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISystemStatus"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/init(rawvalue:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusActiveSending": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusActiveSending"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusActiveSending",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusActiveSending"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusActiveSending",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statusactivesending"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusActiveSensing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusActiveSensing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MIDISystemStatus",
          "text": "MIDISystemStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusActiveSensing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusActiveSensing"
        }
      ],
      "role": "symbol",
      "title": "statusActiveSensing",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statusactivesensing"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusContinue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusContinue"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusContinue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusContinue"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusContinue",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statuscontinue"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusEndOfExclusive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusEndOfExclusive"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusEndOfExclusive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusEndOfExclusive"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusEndOfExclusive",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statusendofexclusive"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusMTC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusMTC"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusMTC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusMTC"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusMTC",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statusmtc"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongPosPointer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusSongPosPointer"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongPosPointer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusSongPosPointer"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusSongPosPointer",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statussongpospointer"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongSelect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusSongSelect"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusSongSelect"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusSongSelect",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statussongselect"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusStart"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusStart"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusStart",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statusstart"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStartOfExclusive": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusStartOfExclusive"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStartOfExclusive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusStartOfExclusive"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusStartOfExclusive",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statusstartofexclusive"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusStop"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusStop"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusStop",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statusstop"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSystemReset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusSystemReset"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSystemReset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusSystemReset"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusSystemReset",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statussystemreset"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusTimingClock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusTimingClock"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusTimingClock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusTimingClock"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusTimingClock",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statustimingclock"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusTuneRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusTuneRequest"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusTuneRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIStatusTuneRequest"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus.statusTuneRequest",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus/statustunerequest"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Common",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysExStatus",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_128",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_96",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_64",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_32",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType"
      ],
      "title": "Common"
    }
  ],
  "topicSections": [
    {
      "anchor": "Status-Types",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusActiveSending",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusContinue",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusEndOfExclusive",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusMTC",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongPosPointer",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongSelect",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStart",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStartOfExclusive",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStop",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSystemReset",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusTimingClock",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusTuneRequest"
      ],
      "title": "Status Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusActiveSensing"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MIDISystemStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISystemStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISystemStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Status-Types",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusActiveSending",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusContinue",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusEndOfExclusive",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusMTC",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongPosPointer",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSongSelect",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStart",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStartOfExclusive",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusStop",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusSystemReset",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusTimingClock",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusTuneRequest"
              ],
              "title": "Status Types"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus/statusActiveSensing"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Common",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysExStatus",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_128",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_96",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_64",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_32",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType"
              ],
              "title": "Common"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MIDISystemStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:i",
                    "text": "unsigned int"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusStart/title",
          "value": "kMIDIStatusStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusMTC/title",
          "value": "kMIDIStatusMTC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusMTC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusMTC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusSongPosPointer/title",
          "value": "kMIDIStatusSongPosPointer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusSongPosPointer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusSongPosPointer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_128/title",
          "value": "MIDIMessage_128"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_128/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_128/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusStop/title",
          "value": "kMIDIStatusStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_96/title",
          "value": "MIDIMessage_96"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_96/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_96"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_96/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_96"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusContinue/title",
          "value": "kMIDIStatusContinue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusContinue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusContinue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusStartOfExclusive/title",
          "value": "kMIDIStatusStartOfExclusive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusStartOfExclusive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusStartOfExclusive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_32/title",
          "value": "MIDIMessage_32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProtocolID/title",
          "value": "MIDIProtocolID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProtocolID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIProtocolID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProtocolID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIProtocolID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus/title",
          "value": "MIDISystemStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISystemStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISystemStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_64/title",
          "value": "MIDIMessage_64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_64/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysExStatus/title",
          "value": "MIDISysExStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysExStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysExStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysExStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysExStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusActiveSensing/title",
          "value": "kMIDIStatusActiveSensing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusActiveSensing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusActiveSensing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusTuneRequest/title",
          "value": "kMIDIStatusTuneRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusTuneRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusTuneRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusSystemReset/title",
          "value": "kMIDIStatusSystemReset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusSystemReset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusSystemReset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType/title",
          "value": "MIDIMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusTimingClock/title",
          "value": "kMIDIStatusTimingClock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusTimingClock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusTimingClock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusSongSelect/title",
          "value": "kMIDIStatusSongSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusSongSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusSongSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusEndOfExclusive/title",
          "value": "kMIDIStatusEndOfExclusive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusEndOfExclusive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusEndOfExclusive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus/title",
          "value": "MIDICVStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICVStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICVStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusActiveSending/title",
          "value": "kMIDIStatusActiveSending"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus~1statusActiveSending/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIStatusActiveSending"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midisystemstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midisystemstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
