{
  "abstract": [
    {
      "text": "Supported MIDI message types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MIDIMessageType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MIDIMessageType"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MIDIMessageType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MIDIMessageType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MIDIMessageType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus": {
      "abstract": [
        {
          "text": "MIDI status types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICVStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICVStatus"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType": {
      "abstract": [
        {
          "text": "Supported MIDI message types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessageType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessageType"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessageType",
      "type": "topic",
      "url": "/documentation/coremidi/midimessagetype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/channelVoice1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelVoice1"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/channelVoice1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMessageTypeChannelVoice1"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessageType.channelVoice1",
      "type": "topic",
      "url": "/documentation/coremidi/midimessagetype/channelvoice1"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/channelVoice2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelVoice2"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/channelVoice2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMessageTypeChannelVoice2"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessageType.channelVoice2",
      "type": "topic",
      "url": "/documentation/coremidi/midimessagetype/channelvoice2"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/data128": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/data128",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMessageTypeData128"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessageType.data128",
      "type": "topic",
      "url": "/documentation/coremidi/midimessagetype/data128"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/flexData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flexData"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/flexData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMessageTypeFlexData"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessageType.flexData",
      "type": "topic",
      "url": "/documentation/coremidi/midimessagetype/flexdata"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coremidi/midimessagetype/init(rawvalue:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/invalid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMessageTypeInvalid"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessageType.invalid",
      "type": "topic",
      "url": "/documentation/coremidi/midimessagetype/invalid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/stream": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stream"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MIDIMessageType",
          "text": "MIDIMessageType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/stream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMessageTypeStream"
        }
      ],
      "role": "symbol",
      "title": "stream",
      "type": "topic",
      "url": "/documentation/coremidi/midimessagetype/stream"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/sysEx": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sysEx"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/sysEx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMessageTypeSysEx"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessageType.sysEx",
      "type": "topic",
      "url": "/documentation/coremidi/midimessagetype/sysex"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/system": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "system"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/system",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMessageTypeSystem"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessageType.system",
      "type": "topic",
      "url": "/documentation/coremidi/midimessagetype/system"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/unknownF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownF"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/unknownF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMessageTypeUnknownF"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessageType.unknownF",
      "type": "topic",
      "url": "/documentation/coremidi/midimessagetype/unknownf"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/utility": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "utility"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/utility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMessageTypeUtility"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessageType.utility",
      "type": "topic",
      "url": "/documentation/coremidi/midimessagetype/utility"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_128": {
      "abstract": [
        {
          "text": "A 128-bit MIDI message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_128",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessage_128"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessage_128",
      "type": "topic",
      "url": "/documentation/coremidi/midimessage_128"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_32": {
      "abstract": [
        {
          "text": "A 32-bit MIDI message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessage_32"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessage_32",
      "type": "topic",
      "url": "/documentation/coremidi/midimessage_32"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_64": {
      "abstract": [
        {
          "text": "A 64-bit MIDI message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessage_64"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessage_64",
      "type": "topic",
      "url": "/documentation/coremidi/midimessage_64"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_96": {
      "abstract": [
        {
          "text": "A 96-bit MIDI message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessage_96"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_96",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessage_96"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessage_96",
      "type": "topic",
      "url": "/documentation/coremidi/midimessage_96"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID": {
      "abstract": [
        {
          "text": "Specifies a MIDI protocol variant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIProtocolID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIProtocolID"
        }
      ],
      "role": "symbol",
      "title": "MIDIProtocolID",
      "type": "topic",
      "url": "/documentation/coremidi/midiprotocolid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysExStatus": {
      "abstract": [
        {
          "text": "MIDI System Exclusive (SysEx) types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISysExStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysExStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISysExStatus"
        }
      ],
      "role": "symbol",
      "title": "MIDISysExStatus",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexstatus"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus": {
      "abstract": [
        {
          "text": "MIDI System status types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISystemStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISystemStatus"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Common",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysExStatus",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_128",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_96",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_64",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_32"
      ],
      "title": "Common"
    }
  ],
  "topicSections": [
    {
      "anchor": "Message-Types",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/channelVoice1",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/channelVoice2",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/data128",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/sysEx",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/system",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/utility"
      ],
      "title": "Message Types"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/flexData",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/invalid",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/unknownF"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/stream"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MIDIMessageType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Message-Types",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/channelVoice1",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/channelVoice2",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/data128",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/sysEx",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/system",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/utility"
              ],
              "title": "Message Types"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/flexData",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/invalid",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/stream",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType/unknownF"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Common",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysExStatus",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_128",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_96",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_64",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_32"
              ],
              "title": "Common"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MIDIMessageType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:i",
                    "text": "unsigned int"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType/title",
          "value": "MIDIMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1system/title",
          "value": "kMIDIMessageTypeSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1system/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMessageTypeSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus/title",
          "value": "MIDICVStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICVStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICVStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1invalid/title",
          "value": "kMIDIMessageTypeInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMessageTypeInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1channelVoice1/title",
          "value": "kMIDIMessageTypeChannelVoice1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1channelVoice1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMessageTypeChannelVoice1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_128/title",
          "value": "MIDIMessage_128"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_128/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_128/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1sysEx/title",
          "value": "kMIDIMessageTypeSysEx"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1sysEx/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMessageTypeSysEx"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_64/title",
          "value": "MIDIMessage_64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_64/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1flexData/title",
          "value": "kMIDIMessageTypeFlexData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1flexData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMessageTypeFlexData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1data128/title",
          "value": "kMIDIMessageTypeData128"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1data128/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMessageTypeData128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1unknownF/title",
          "value": "kMIDIMessageTypeUnknownF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1unknownF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMessageTypeUnknownF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1stream/title",
          "value": "kMIDIMessageTypeStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1stream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMessageTypeStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1channelVoice2/title",
          "value": "kMIDIMessageTypeChannelVoice2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1channelVoice2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMessageTypeChannelVoice2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProtocolID/title",
          "value": "MIDIProtocolID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProtocolID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIProtocolID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProtocolID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIProtocolID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysExStatus/title",
          "value": "MIDISysExStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysExStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysExStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysExStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysExStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_96/title",
          "value": "MIDIMessage_96"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_96/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_96"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_96/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_96"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_32/title",
          "value": "MIDIMessage_32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus/title",
          "value": "MIDISystemStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISystemStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISystemStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1utility/title",
          "value": "kMIDIMessageTypeUtility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType~1utility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMessageTypeUtility"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midimessagetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midimessagetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
