{
  "abstract": [
    {
      "text": "Create and manage devices connected over a local network.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "MIDI Networking"
  },
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkConnection": {
      "abstract": [
        {
          "text": "An object that connects a session to a host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDINetworkConnection"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDINetworkConnection"
        }
      ],
      "role": "symbol",
      "title": "MIDINetworkConnection",
      "type": "topic",
      "url": "/documentation/coremidi/midinetworkconnection"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkHost": {
      "abstract": [
        {
          "text": "An object that represents the host’s network address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDINetworkHost"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkHost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDINetworkHost"
        }
      ],
      "role": "symbol",
      "title": "MIDINetworkHost",
      "type": "topic",
      "url": "/documentation/coremidi/midinetworkhost"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkSession": {
      "abstract": [
        {
          "text": "An object that represents a pairing of a source and destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDINetworkSession"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDINetworkSession"
        }
      ],
      "role": "symbol",
      "title": "MIDINetworkSession",
      "type": "topic",
      "url": "/documentation/coremidi/midinetworksession"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth": {
      "abstract": [
        {
          "text": "Connect to Bluetooth Low Energy MIDI peripherals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Bluetooth",
      "type": "topic",
      "url": "/documentation/coremidi/midi-bluetooth"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry": {
      "abstract": [
        {
          "text": "Provide support for bidirectional discovery and configuration of devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Capability Inquiry",
      "type": "topic",
      "url": "/documentation/coremidi/midi-capability-inquiry"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers": {
      "abstract": [
        {
          "text": "Create driver plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Drivers",
      "type": "topic",
      "url": "/documentation/coremidi/midi-drivers"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages": {
      "abstract": [
        {
          "text": "Create and configure messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Messages",
      "type": "topic",
      "url": "/documentation/coremidi/midi-messages"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services": {
      "abstract": [
        {
          "text": "Communicate with hardware using Universal MIDI Packets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Services",
      "type": "topic",
      "url": "/documentation/coremidi/midi-services"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup": {
      "abstract": [
        {
          "text": "Configure the global MIDI system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI System Setup",
      "type": "topic",
      "url": "/documentation/coremidi/midi-system-setup"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection": {
      "abstract": [
        {
          "text": "Create play-through connections between sources and destinations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Thru Connection",
      "type": "topic",
      "url": "/documentation/coremidi/midi-thru-connection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Services",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry"
      ],
      "title": "Services"
    }
  ],
  "topicSections": [
    {
      "anchor": "Networking",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkHost",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkConnection",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkSession"
      ],
      "title": "Networking"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Networking",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkHost",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkConnection",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkSession"
              ],
              "title": "Networking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Services",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry"
              ],
              "title": "Services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINetworkSession/title",
          "value": "MIDINetworkSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINetworkSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINetworkSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINetworkSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINetworkSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINetworkConnection/title",
          "value": "MIDINetworkConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINetworkConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINetworkConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINetworkConnection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINetworkConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINetworkHost/title",
          "value": "MIDINetworkHost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINetworkHost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINetworkHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINetworkHost/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINetworkHost"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midi-networking"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midi-networking"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
