{
  "abstract": [
    {
      "text": "Values that specify the type of MIDI transformation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MIDITransformType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MIDITransformType"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MIDITransformType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MIDITransformType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MIDITransformType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIControlTransform": {
      "abstract": [
        {
          "text": "A structure that describes the transformation of MIDI control change events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIControlTransform"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIControlTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIControlTransform"
        }
      ],
      "role": "symbol",
      "title": "MIDIControlTransform",
      "type": "topic",
      "url": "/documentation/coremidi/midicontroltransform"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransform": {
      "abstract": [
        {
          "text": "The transformation of a single type of MIDI event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDITransform"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDITransform"
        }
      ],
      "role": "symbol",
      "title": "MIDITransform",
      "type": "topic",
      "url": "/documentation/coremidi/miditransform"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType": {
      "abstract": [
        {
          "text": "A set of values that indicate how to interpret control numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDITransformControlType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDITransformControlType"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformControlType",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformcontroltype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType": {
      "abstract": [
        {
          "text": "Values that specify the type of MIDI transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDITransformType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDITransformType"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/add": {
      "abstract": [
        {
          "text": "A transform that adds a parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/add",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_Add"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.add",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/add"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/filterOut": {
      "abstract": [
        {
          "text": "A transformation that filters out an event type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filterOut"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/filterOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_FilterOut"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.filterOut",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/filterout"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/init(rawvalue:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapControl": {
      "abstract": [
        {
          "text": "A transformation that changes a specified control number to a supplied parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapControl"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_MapControl"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.mapControl",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/mapcontrol"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapValue": {
      "abstract": [
        {
          "text": "A transform that maps one value to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapValue"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_MapValue"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.mapValue",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/mapvalue"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/maxValue": {
      "abstract": [
        {
          "text": "A transform that sets the maximum value to the specified parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxValue"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/maxValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_MaxValue"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.maxValue",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/maxvalue"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/minValue": {
      "abstract": [
        {
          "text": "A transform that sets the minimum value to the specified parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minValue"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/minValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_MinValue"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.minValue",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/minvalue"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/none": {
      "abstract": [
        {
          "text": "No transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_None"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.none",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/none"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/scale": {
      "abstract": [
        {
          "text": "A transform that multiplies by the specified parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scale"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_Scale"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.scale",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/scale"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIValueMap": {
      "abstract": [
        {
          "text": "A custom lookup table to transform MIDI 7-bit values, as contained in note numbers, velocities, control values, and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIValueMap"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIValueMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIValueMap"
        }
      ],
      "role": "symbol",
      "title": "MIDIValueMap",
      "type": "topic",
      "url": "/documentation/coremidi/midivaluemap"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Transforming-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIValueMap",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIControlTransform",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransform",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType"
      ],
      "title": "Transforming Values"
    }
  ],
  "topicSections": [
    {
      "anchor": "Transform-Types",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/none",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/filterOut",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapControl",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/add",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/scale",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/minValue",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/maxValue",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapValue"
      ],
      "title": "Transform Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MIDITransformType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDITransformType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDITransformType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Transform-Types",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/none",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/filterOut",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapControl",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/add",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/scale",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/minValue",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/maxValue",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapValue"
              ],
              "title": "Transform Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Transforming-Values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIValueMap",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIControlTransform",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransform",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformControlType"
              ],
              "title": "Transforming Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MIDITransformType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt16",
                    "text": "UInt16"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1add/title",
          "value": "kMIDITransform_Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1add/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIValueMap/title",
          "value": "MIDIValueMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIValueMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIValueMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIValueMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIValueMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType/title",
          "value": "MIDITransformControlType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDITransformControlType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformControlType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDITransformControlType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1mapValue/title",
          "value": "kMIDITransform_MapValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1mapValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_MapValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1maxValue/title",
          "value": "kMIDITransform_MaxValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1maxValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_MaxValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1minValue/title",
          "value": "kMIDITransform_MinValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1minValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_MinValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1mapControl/title",
          "value": "kMIDITransform_MapControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1mapControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_MapControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIControlTransform/title",
          "value": "MIDIControlTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIControlTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIControlTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIControlTransform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIControlTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransform/title",
          "value": "MIDITransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDITransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDITransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType/title",
          "value": "MIDITransformType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDITransformType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDITransformType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1filterOut/title",
          "value": "kMIDITransform_FilterOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1filterOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_FilterOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1none/title",
          "value": "kMIDITransform_None"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_None"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1scale/title",
          "value": "kMIDITransform_Scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_Scale"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/miditransformtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/miditransformtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
