{
  "abstract": [
    {
      "text": "Returns the list of driver-created devices in the current MIDI setup.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetDriverDeviceList(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@MIDIGetDriverDeviceList",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MIDIGetDriverDeviceList"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MIDIDriverRef",
        "text": "MIDIDriverRef"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MIDIDeviceListRef",
        "text": "MIDIDeviceListRef"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MIDIGetDriverDeviceList"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "MIDIGetDriverDeviceList(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MIDIGetDriverDeviceList"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "driver"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MIDIDriverRef",
              "text": "MIDIDriverRef"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MIDIDeviceListRef",
              "text": "MIDIDeviceListRef"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The driver for which you return devices.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "driver"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The requested device list.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Dispose this list when you’re finished working with it by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListDispose(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListDispose(_:)": {
      "abstract": [
        {
          "text": "Disposes of a device list, but not its devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDeviceListDispose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceListRef",
          "text": "MIDIDeviceListRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListDispose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDeviceListDispose"
        }
      ],
      "role": "symbol",
      "title": "MIDIDeviceListDispose(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/mididevicelistdispose(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListRef": {
      "abstract": [
        {
          "text": "A list of MIDI devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDeviceListRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDeviceListRef"
        }
      ],
      "role": "symbol",
      "title": "MIDIDeviceListRef",
      "type": "topic",
      "url": "/documentation/coremidi/mididevicelistref"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverEnableMonitoring(_:_:)": {
      "abstract": [
        {
          "text": "Enables monitoring of all outgoing MIDI packets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDriverEnableMonitoring"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDriverRef",
          "text": "MIDIDriverRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverEnableMonitoring(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDriverEnableMonitoring"
        }
      ],
      "role": "symbol",
      "title": "MIDIDriverEnableMonitoring(_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/mididriverenablemonitoring(_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverInterface": {
      "abstract": [
        {
          "text": "The interface to a MIDI driver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDriverInterface"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDriverInterface"
        }
      ],
      "role": "symbol",
      "title": "MIDIDriverInterface",
      "type": "topic",
      "url": "/documentation/coremidi/mididriverinterface"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverRef": {
      "abstract": [
        {
          "text": "A MIDI driver object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDriverRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDriverRef"
        }
      ],
      "role": "symbol",
      "title": "MIDIDriverRef",
      "type": "topic",
      "url": "/documentation/coremidi/mididriverref"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetDriverDeviceList(_:)": {
      "abstract": [
        {
          "text": "Returns the list of driver-created devices in the current MIDI setup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIGetDriverDeviceList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDriverRef",
          "text": "MIDIDriverRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceListRef",
          "text": "MIDIDeviceListRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetDriverDeviceList(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIGetDriverDeviceList"
        }
      ],
      "role": "symbol",
      "title": "MIDIGetDriverDeviceList(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midigetdriverdevicelist(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetDriverIORunLoop()": {
      "abstract": [
        {
          "text": "Returns the server’s driver I/O thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIGetDriverIORunLoop"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopRef",
          "text": "CFRunLoop"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetDriverIORunLoop()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIGetDriverIORunLoop"
        }
      ],
      "role": "symbol",
      "title": "MIDIGetDriverIORunLoop()",
      "type": "topic",
      "url": "/documentation/coremidi/midigetdriveriorunloop()"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverPropertyUsesSerial": {
      "abstract": [
        {
          "text": "A value that indicates whether the driver uses serial ports and is eligible to have serial ports assigned to it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIDriverPropertyUsesSerial"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverPropertyUsesSerial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIDriverPropertyUsesSerial"
        }
      ],
      "role": "symbol",
      "title": "kMIDIDriverPropertyUsesSerial",
      "type": "topic",
      "url": "/documentation/coremidi/kmididriverpropertyusesserial"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-a-Driver",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverEnableMonitoring(_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetDriverIORunLoop()",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverPropertyUsesSerial",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverInterface",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverRef"
      ],
      "title": "Inspecting a Driver"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MIDIGetDriverDeviceList"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIGetDriverDeviceList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-a-Driver",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverEnableMonitoring(_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetDriverIORunLoop()",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverPropertyUsesSerial",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverInterface",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverRef"
              ],
              "title": "Inspecting a Driver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MIDIDeviceListRef",
                    "text": "MIDIDeviceListRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MIDIGetDriverDeviceList"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MIDIDriverRef",
                    "text": "MIDIDriverRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "driver"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The driver for which you return devices.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "driver"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The requested device list.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIGetDriverDeviceList(_:)/title",
          "value": "MIDIGetDriverDeviceList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIGetDriverDeviceList(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIGetDriverDeviceList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIGetDriverIORunLoop()/title",
          "value": "MIDIGetDriverIORunLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIGetDriverIORunLoop()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIGetDriverIORunLoop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIDriverPropertyUsesSerial/title",
          "value": "kMIDIDriverPropertyUsesSerial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIDriverPropertyUsesSerial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIDriverPropertyUsesSerial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverRef/title",
          "value": "MIDIDriverRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDriverRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDriverRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListDispose(_:)/title",
          "value": "MIDIDeviceListDispose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListDispose(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceListDispose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListRef/title",
          "value": "MIDIDeviceListRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceListRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceListRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverEnableMonitoring(_:_:)/title",
          "value": "MIDIDriverEnableMonitoring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverEnableMonitoring(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDriverEnableMonitoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverInterface/title",
          "value": "MIDIDriverInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDriverInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverInterface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDriverInterface"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midigetdriverdevicelist(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midigetdriverdevicelist(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
