{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MIDICIManagementMessageType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MIDICIManagementMessageType"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MIDICIManagementMessageType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MIDICIManagementMessageType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MIDICIManagementMessageType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICICategoryOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICICategoryOptions"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICICategoryOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICICategoryOptions"
        }
      ],
      "role": "symbol",
      "title": "MIDICICategoryOptions",
      "type": "topic",
      "url": "/documentation/coremidi/midicicategoryoptions"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIDeviceType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIDeviceType"
        }
      ],
      "role": "symbol",
      "title": "MIDICIDeviceType",
      "type": "topic",
      "url": "/documentation/coremidi/midicidevicetype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIManagementMessageType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIManagementMessageType"
        }
      ],
      "role": "symbol",
      "title": "MIDICIManagementMessageType",
      "type": "topic",
      "url": "/documentation/coremidi/midicimanagementmessagetype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/discovery": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discovery"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/discovery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICIManagementMessageTypeDiscovery"
        }
      ],
      "role": "symbol",
      "title": "MIDICIManagementMessageType.discovery",
      "type": "topic",
      "url": "/documentation/coremidi/midicimanagementmessagetype/discovery"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUInteger7",
          "text": "MIDIUInteger7"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coremidi/midicimanagementmessagetype/init(rawvalue:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/inquiryEndpointInformation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inquiryEndpointInformation"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/inquiryEndpointInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICIManagementMessageTypeInquiryEndpointInformation"
        }
      ],
      "role": "symbol",
      "title": "MIDICIManagementMessageType.inquiryEndpointInformation",
      "type": "topic",
      "url": "/documentation/coremidi/midicimanagementmessagetype/inquiryendpointinformation"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/invalidateMUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidateMUID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/invalidateMUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICIManagementMessageTypeInvalidateMUID"
        }
      ],
      "role": "symbol",
      "title": "MIDICIManagementMessageType.invalidateMUID",
      "type": "topic",
      "url": "/documentation/coremidi/midicimanagementmessagetype/invalidatemuid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/midiCIACK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "midiCIACK"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/midiCIACK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICIManagementMessageTypeMIDICIACK"
        }
      ],
      "role": "symbol",
      "title": "MIDICIManagementMessageType.midiCIACK",
      "type": "topic",
      "url": "/documentation/coremidi/midicimanagementmessagetype/midiciack"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/midiNAK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "midiNAK"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/midiNAK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICIManagementMessageTypeMIDICINAK"
        }
      ],
      "role": "symbol",
      "title": "MIDICIManagementMessageType.midiNAK",
      "type": "topic",
      "url": "/documentation/coremidi/midicimanagementmessagetype/midinak"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/replyToDiscovery": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replyToDiscovery"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/replyToDiscovery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICIManagementMessageTypeReplyToDiscovery"
        }
      ],
      "role": "symbol",
      "title": "MIDICIManagementMessageType.replyToDiscovery",
      "type": "topic",
      "url": "/documentation/coremidi/midicimanagementmessagetype/replytodiscovery"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/replyToEndpointInformation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replyToEndpointInformation"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/replyToEndpointInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICIManagementMessageTypeReplyToEndpointInformation"
        }
      ],
      "role": "symbol",
      "title": "MIDICIManagementMessageType.replyToEndpointInformation",
      "type": "topic",
      "url": "/documentation/coremidi/midicimanagementmessagetype/replytoendpointinformation"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProcessInquiryMessageType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProcessInquiryMessageType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProcessInquiryMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProcessInquiryMessageType"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProcessInquiryMessageType",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprocessinquirymessagetype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileMessageType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProfileMessageType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProfileMessageType"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProfileMessageType",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofilemessagetype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProfileType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProfileType"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProfileType",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofiletype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeMessageType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIPropertyExchangeMessageType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIPropertyExchangeMessageType"
        }
      ],
      "role": "symbol",
      "title": "MIDICIPropertyExchangeMessageType",
      "type": "topic",
      "url": "/documentation/coremidi/midicipropertyexchangemessagetype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkConnectionPolicy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDINetworkConnectionPolicy"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkConnectionPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDINetworkConnectionPolicy"
        }
      ],
      "role": "symbol",
      "title": "MIDINetworkConnectionPolicy",
      "type": "topic",
      "url": "/documentation/coremidi/midinetworkconnectionpolicy"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINoteAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDINoteAttribute"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINoteAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDINoteAttribute"
        }
      ],
      "role": "symbol",
      "title": "MIDINoteAttribute",
      "type": "topic",
      "url": "/documentation/coremidi/midinoteattribute"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPerNoteManagementOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIPerNoteManagementOptions"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPerNoteManagementOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIPerNoteManagementOptions"
        }
      ],
      "role": "symbol",
      "title": "MIDIPerNoteManagementOptions",
      "type": "topic",
      "url": "/documentation/coremidi/midipernotemanagementoptions"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProgramChangeOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIProgramChangeOptions"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProgramChangeOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIProgramChangeOptions"
        }
      ],
      "role": "symbol",
      "title": "MIDIProgramChangeOptions",
      "type": "topic",
      "url": "/documentation/coremidi/midiprogramchangeoptions"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger7": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUInteger7"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUInteger7"
        }
      ],
      "role": "symbol",
      "title": "MIDIUInteger7",
      "type": "topic",
      "url": "/documentation/coremidi/midiuinteger7"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPCIObjectBackingType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUMPCIObjectBackingType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPCIObjectBackingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPCIObjectBackingType"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPCIObjectBackingType",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpciobjectbackingtype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockDirection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUMPFunctionBlockDirection"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPFunctionBlockDirection"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPFunctionBlockDirection",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpfunctionblockdirection"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockMIDI1Info": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUMPFunctionBlockMIDI1Info"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockMIDI1Info",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPFunctionBlockMIDI1Info"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPFunctionBlockMIDI1Info",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpfunctionblockmidi1info"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockUIHint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUMPFunctionBlockUIHint"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockUIHint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPFunctionBlockUIHint"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPFunctionBlockUIHint",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpfunctionblockuihint"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidUniqueID": {
      "abstract": [
        {
          "text": "An invalid identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIInvalidUniqueID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUniqueID",
          "text": "MIDIUniqueID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidUniqueID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIInvalidUniqueID"
        }
      ],
      "role": "symbol",
      "title": "kMIDIInvalidUniqueID",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiinvaliduniqueid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidUniqueID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICICategoryOptions",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceType",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProcessInquiryMessageType",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileMessageType",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileType",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeMessageType",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkConnectionPolicy",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINoteAttribute",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPerNoteManagementOptions",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProgramChangeOptions",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPCIObjectBackingType",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockDirection",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockMIDI1Info",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockUIHint"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/discovery",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/inquiryEndpointInformation",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/invalidateMUID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/midiCIACK",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/midiNAK",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/replyToDiscovery",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/replyToEndpointInformation"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MIDICIManagementMessageType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIManagementMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIManagementMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/discovery",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/inquiryEndpointInformation",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/invalidateMUID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/midiCIACK",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/midiNAK",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/replyToDiscovery",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType/replyToEndpointInformation"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidUniqueID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICICategoryOptions",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceType",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProcessInquiryMessageType",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileMessageType",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileType",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeMessageType",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkConnectionPolicy",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINoteAttribute",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPerNoteManagementOptions",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProgramChangeOptions",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPCIObjectBackingType",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockDirection",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockMIDI1Info",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockUIHint"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MIDICIManagementMessageType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUInteger7",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MIDIUInteger7",
                    "text": "MIDIUInteger7"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProgramChangeOptions/title",
          "value": "MIDIProgramChangeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProgramChangeOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIProgramChangeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProgramChangeOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIProgramChangeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType~1invalidateMUID/title",
          "value": "kMIDICIManagementMessageTypeInvalidateMUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType~1invalidateMUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICIManagementMessageTypeInvalidateMUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINoteAttribute/title",
          "value": "MIDINoteAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINoteAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINoteAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINoteAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINoteAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockMIDI1Info/title",
          "value": "MIDIUMPFunctionBlockMIDI1Info"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockMIDI1Info/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPFunctionBlockMIDI1Info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockMIDI1Info/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPFunctionBlockMIDI1Info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICICategoryOptions/title",
          "value": "MIDICICategoryOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICICategoryOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICICategoryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICICategoryOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICICategoryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceType/title",
          "value": "MIDICIDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIPropertyExchangeMessageType/title",
          "value": "MIDICIPropertyExchangeMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIPropertyExchangeMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIPropertyExchangeMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIPropertyExchangeMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIPropertyExchangeMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIInvalidUniqueID/title",
          "value": "kMIDIInvalidUniqueID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIInvalidUniqueID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIInvalidUniqueID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileType/title",
          "value": "MIDICIProfileType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINetworkConnectionPolicy/title",
          "value": "MIDINetworkConnectionPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINetworkConnectionPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINetworkConnectionPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINetworkConnectionPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINetworkConnectionPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType~1discovery/title",
          "value": "kMIDICIManagementMessageTypeDiscovery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType~1discovery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICIManagementMessageTypeDiscovery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType~1replyToDiscovery/title",
          "value": "kMIDICIManagementMessageTypeReplyToDiscovery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType~1replyToDiscovery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICIManagementMessageTypeReplyToDiscovery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIPerNoteManagementOptions/title",
          "value": "MIDIPerNoteManagementOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIPerNoteManagementOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIPerNoteManagementOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIPerNoteManagementOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIPerNoteManagementOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType~1inquiryEndpointInformation/title",
          "value": "kMIDICIManagementMessageTypeInquiryEndpointInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType~1inquiryEndpointInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICIManagementMessageTypeInquiryEndpointInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType~1replyToEndpointInformation/title",
          "value": "kMIDICIManagementMessageTypeReplyToEndpointInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType~1replyToEndpointInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICIManagementMessageTypeReplyToEndpointInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType~1midiCIACK/title",
          "value": "kMIDICIManagementMessageTypeMIDICIACK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType~1midiCIACK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICIManagementMessageTypeMIDICIACK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileMessageType/title",
          "value": "MIDICIProfileMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPCIObjectBackingType/title",
          "value": "MIDIUMPCIObjectBackingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPCIObjectBackingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPCIObjectBackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPCIObjectBackingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPCIObjectBackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockDirection/title",
          "value": "MIDIUMPFunctionBlockDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPFunctionBlockDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPFunctionBlockDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType~1midiNAK/title",
          "value": "kMIDICIManagementMessageTypeMIDICINAK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType~1midiNAK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICIManagementMessageTypeMIDICINAK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType/title",
          "value": "MIDICIManagementMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIManagementMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIManagementMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger7/title",
          "value": "MIDIUInteger7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUInteger7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUInteger7/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUInteger7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockUIHint/title",
          "value": "MIDIUMPFunctionBlockUIHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockUIHint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPFunctionBlockUIHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockUIHint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPFunctionBlockUIHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProcessInquiryMessageType/title",
          "value": "MIDICIProcessInquiryMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProcessInquiryMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProcessInquiryMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProcessInquiryMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProcessInquiryMessageType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midicimanagementmessagetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midicimanagementmessagetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
