{
  "abstract": [
    {
      "text": "Locates a device, entity, or endpoint by its unique identifier.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectFindByUniqueID(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@MIDIObjectFindByUniqueID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MIDIObjectFindByUniqueID"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MIDIUniqueID",
        "text": "MIDIUniqueID"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MIDIObjectRef",
        "text": "MIDIObjectRef"
      },
      {
        "kind": "text",
        "text": ">?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MIDIObjectType",
        "text": "MIDIObjectType"
      },
      {
        "kind": "text",
        "text": ">?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MIDIObjectFindByUniqueID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "MIDIObjectFindByUniqueID(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MIDIObjectFindByUniqueID"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inUniqueID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniqueID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MIDIUniqueID",
              "text": "MIDIUniqueID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "outObject"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MIDIObjectRef",
              "text": "MIDIObjectRef"
            },
            {
              "kind": "text",
              "text": ">?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "outObjectType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MIDIObjectType",
              "text": "MIDIObjectType"
            },
            {
              "kind": "text",
              "text": ">?) -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The unique ID of the object to search for. You determine the unique ID by querying ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectGetIntegerProperty(_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyUniqueID",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inUniqueID"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The returned object, or 0 if the object wasn’t found or an error occurred. Cast this pointer to the appropriate type, according to type specified by the ",
                  "type": "text"
                },
                {
                  "code": "outObjectType",
                  "type": "codeVoice"
                },
                {
                  "text": " argument.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outObject"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On exit, the type of object found, or undefined if the system found no objects.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outObjectType"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "code": "OSStatus",
              "type": "codeVoice"
            },
            {
              "text": " error code, including ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIObjectNotFound",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if there is no object with this unique ID.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectFindByUniqueID(_:_:_:)": {
      "abstract": [
        {
          "text": "Locates a device, entity, or endpoint by its unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIObjectFindByUniqueID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUniqueID",
          "text": "MIDIUniqueID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIObjectRef",
          "text": "MIDIObjectRef"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MIDIObjectType",
          "text": "MIDIObjectType"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectFindByUniqueID(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIObjectFindByUniqueID"
        }
      ],
      "role": "symbol",
      "title": "MIDIObjectFindByUniqueID(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midiobjectfindbyuniqueid(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectGetIntegerProperty(_:_:_:)": {
      "abstract": [
        {
          "text": "Gets an object’s integer-type property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIObjectGetIntegerProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIObjectRef",
          "text": "MIDIObjectRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectGetIntegerProperty(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIObjectGetIntegerProperty"
        }
      ],
      "role": "symbol",
      "title": "MIDIObjectGetIntegerProperty(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midiobjectgetintegerproperty(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectRef": {
      "abstract": [
        {
          "text": "The common base class for many of the framework’s objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIObjectRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIObjectRef"
        }
      ],
      "role": "symbol",
      "title": "MIDIObjectRef",
      "type": "topic",
      "url": "/documentation/coremidi/midiobjectref"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType": {
      "abstract": [
        {
          "text": "The MIDI object types that the system supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIObjectType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIObjectType"
        }
      ],
      "role": "symbol",
      "title": "MIDIObjectType",
      "type": "topic",
      "url": "/documentation/coremidi/midiobjecttype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniqueID": {
      "abstract": [
        {
          "text": "A MIDI object’s unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUniqueID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniqueID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUniqueID"
        }
      ],
      "role": "symbol",
      "title": "MIDIUniqueID",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniqueid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidUniqueID": {
      "abstract": [
        {
          "text": "An invalid identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIInvalidUniqueID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUniqueID",
          "text": "MIDIUniqueID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidUniqueID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIInvalidUniqueID"
        }
      ],
      "role": "symbol",
      "title": "kMIDIInvalidUniqueID",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiinvaliduniqueid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIObjectNotFound": {
      "abstract": [
        {
          "text": "The requested object doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIObjectNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIObjectNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIObjectNotFound"
        }
      ],
      "role": "symbol",
      "title": "kMIDIObjectNotFound",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiobjectnotfound"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyUniqueID": {
      "abstract": [
        {
          "text": "The unique identifier of a device, entity, or, endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIPropertyUniqueID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyUniqueID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIPropertyUniqueID"
        }
      ],
      "role": "symbol",
      "title": "kMIDIPropertyUniqueID",
      "type": "topic",
      "url": "/documentation/coremidi/kmidipropertyuniqueid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-object-properties": {
      "abstract": [
        {
          "text": "Configure the properties of MIDI objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-object-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Object Properties",
      "type": "topic",
      "url": "/documentation/coremidi/midi-object-properties"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "MIDI-object-configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectRef",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-object-properties"
      ],
      "title": "MIDI object configuration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Parameter-Types",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniqueID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidUniqueID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType"
      ],
      "title": "Parameter Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MIDIObjectFindByUniqueID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIObjectFindByUniqueID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Parameter-Types",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniqueID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidUniqueID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType"
              ],
              "title": "Parameter Types"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "MIDI-object-configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectRef",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-object-properties"
              ],
              "title": "MIDI object configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MIDIObjectFindByUniqueID"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniqueID",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MIDIUniqueID",
                    "text": "MIDIUniqueID"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inUniqueID"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MIDIObjectRef",
                    "text": "MIDIObjectRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "outObject"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MIDIObjectType",
                    "text": "MIDIObjectType"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "outObjectType"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The unique ID of the object to search for. You determine the unique ID by querying ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIObjectGetIntegerProperty(_:_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIPropertyUniqueID",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " property.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inUniqueID"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The returned object, or 0 if the object wasn’t found or an error occurred. Cast this pointer to the appropriate type, according to type specified by the ",
                        "type": "text"
                      },
                      {
                        "code": "outObjectType",
                        "type": "codeVoice"
                      },
                      {
                        "text": " argument.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "outObject"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On exit, the type of object found, or undefined if the system found no objects.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "outObjectType"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An ",
                    "type": "text"
                  },
                  {
                    "code": "OSStatus",
                    "type": "codeVoice"
                  },
                  {
                    "text": " error code, including ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIObjectNotFound",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if there is no object with this unique ID.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType/title",
          "value": "MIDIObjectType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectGetIntegerProperty(_:_:_:)/title",
          "value": "MIDIObjectGetIntegerProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectGetIntegerProperty(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIObjectGetIntegerProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIPropertyUniqueID/title",
          "value": "kMIDIPropertyUniqueID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIPropertyUniqueID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIPropertyUniqueID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectRef/title",
          "value": "MIDIObjectRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIObjectRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIObjectRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectFindByUniqueID(_:_:_:)/title",
          "value": "MIDIObjectFindByUniqueID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIObjectFindByUniqueID(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIObjectFindByUniqueID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUniqueID/title",
          "value": "MIDIUniqueID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUniqueID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUniqueID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUniqueID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUniqueID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIInvalidUniqueID/title",
          "value": "kMIDIInvalidUniqueID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIInvalidUniqueID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIInvalidUniqueID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIObjectNotFound/title",
          "value": "kMIDIObjectNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIObjectNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIObjectNotFound"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midiobjectfindbyuniqueid(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midiobjectfindbyuniqueid(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
