{
  "abstract": [
    {
      "text": "An array of profile state objects that describes the profile configuration for all channels of a reachable MIDI-CI node.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileStateList"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@MIDICIProfileStateList",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MIDICIProfileStateList"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MIDICIProfileStateList"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "MIDICIProfileStateList"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<MIDICIProfileState *>"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MIDICIProfileStateList"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDiscoveryManager": {
      "abstract": [
        {
          "text": "A singleton object that performs systemwide MIDI-CI discovery.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIDiscoveryManager"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDiscoveryManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIDiscoveryManager"
        }
      ],
      "role": "symbol",
      "title": "MIDICIDiscoveryManager",
      "type": "topic",
      "url": "/documentation/coremidi/midicidiscoverymanager"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfile": {
      "abstract": [
        {
          "text": "A mapping of MIDI messages to specific sounds and synthesis behaviors, such as General MIDI, a drawbar organ, and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProfile"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProfile"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProfile",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofile"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState": {
      "abstract": [
        {
          "text": "An object that provides the enabled and disabled profiles for a MIDI channel or port on a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProfileState"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProfileState"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProfileState",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofilestate"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileStateList": {
      "abstract": [
        {
          "text": "An array of profile state objects that describes the profile configuration for all channels of a reachable MIDI-CI node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDICIProfileStateList"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileStateList",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDICIProfileStateList",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofilestatelist"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder": {
      "abstract": [
        {
          "text": "An object that responds to MIDI-CI inquiries from an initiator on behalf of a MIDI client, and handles profile and property exchange operations.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIResponder"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIResponder"
        }
      ],
      "role": "symbol",
      "title": "MIDICIResponder",
      "type": "topic",
      "url": "/documentation/coremidi/midiciresponder"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICISession": {
      "abstract": [
        {
          "text": "An object that represents a MIDI-CI session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICISession"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICISession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICISession"
        }
      ],
      "role": "symbol",
      "title": "MIDICISession",
      "type": "topic",
      "url": "/documentation/coremidi/midicisession"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Capability-Inquiry",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDiscoveryManager",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICISession",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfile",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder"
      ],
      "title": "Capability Inquiry"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICISession/title",
          "value": "MIDICISession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICISession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICISession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICISession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICISession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIResponder/title",
          "value": "MIDICIResponder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIResponder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIResponder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDiscoveryManager/title",
          "value": "MIDICIDiscoveryManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDiscoveryManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDiscoveryManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDiscoveryManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDiscoveryManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState/title",
          "value": "MIDICIProfileState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfile/title",
          "value": "MIDICIProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfile"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midiciprofilestatelist"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
