{
  "abstract": [
    {
      "text": "A request to asynchronously send a single universal MIDI packet (UMP) system-exclusive (SysEx) event to a destination.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@MIDISysexSendRequestUMP",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MIDISysexSendRequestUMP"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MIDISysexSendRequestUMP"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MIDISysexSendRequestUMP"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MIDISysexSendRequestUMP"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICompletionProcUMP": {
      "abstract": [
        {
          "text": "A function the system calls after it completely sends a UMP system-exclusive (SysEx) or SysEx 8-bit event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICompletionProcUMP"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICompletionProcUMP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICompletionProcUMP"
        }
      ],
      "role": "symbol",
      "title": "MIDICompletionProcUMP",
      "type": "topic",
      "url": "/documentation/coremidi/midicompletionprocump"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventPacketSysexBytesForGroup(_:_:_:)": {
      "abstract": [
        {
          "text": "Gets MIDI 1.0 system-exclusive (SysEx) bytes on the indicated group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIEventPacketSysexBytesForGroup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIEventPacket",
          "text": "MIDIEventPacket"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ">?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventPacketSysexBytesForGroup(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIEventPacketSysexBytesForGroup"
        }
      ],
      "role": "symbol",
      "title": "MIDIEventPacketSysexBytesForGroup(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midieventpacketsysexbytesforgroup(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIFlushOutput(_:)": {
      "abstract": [
        {
          "text": "Cancels all pending events that were previously scheduled to send.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIFlushOutput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEndpointRef",
          "text": "MIDIEndpointRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIFlushOutput(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIFlushOutput"
        }
      ],
      "role": "symbol",
      "title": "MIDIFlushOutput(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midiflushoutput(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIIOErrorNotification": {
      "abstract": [
        {
          "text": "A general I/O error notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIIOErrorNotification"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIIOErrorNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIIOErrorNotification"
        }
      ],
      "role": "symbol",
      "title": "MIDIIOErrorNotification",
      "type": "topic",
      "url": "/documentation/coremidi/midiioerrornotification"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIRestart()": {
      "abstract": [
        {
          "text": "Stops and restarts MIDI I/O.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIRestart"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIRestart()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIRestart"
        }
      ],
      "role": "symbol",
      "title": "MIDIRestart()",
      "type": "topic",
      "url": "/documentation/coremidi/midirestart()"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISendUMPSysex(_:)": {
      "abstract": [
        {
          "text": "Asynchronously sends a single universal MIDI packet (UMP) system-exclusive (SysEx) event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISendUMPSysex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDISysexSendRequestUMP",
          "text": "MIDISysexSendRequestUMP"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISendUMPSysex(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISendUMPSysex"
        }
      ],
      "role": "symbol",
      "title": "MIDISendUMPSysex(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midisendumpsysex(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISendUMPSysex8(_:)": {
      "abstract": [
        {
          "text": "Asynchronously sends a single universal MIDI packet (UMP) system-exclusive (SysEx) event with an 8-bit message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISendUMPSysex8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDISysexSendRequestUMP",
          "text": "MIDISysexSendRequestUMP"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISendUMPSysex8(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISendUMPSysex8"
        }
      ],
      "role": "symbol",
      "title": "MIDISendUMPSysex8(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midisendumpsysex8(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest": {
      "abstract": [
        {
          "text": "A request to asynchronously send a single system-exclusive (SysEx) event to a destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISysexSendRequest"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISysexSendRequest"
        }
      ],
      "role": "symbol",
      "title": "MIDISysexSendRequest",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequest"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP": {
      "abstract": [
        {
          "text": "A request to asynchronously send a single universal MIDI packet (UMP) system-exclusive (SysEx) event to a destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISysexSendRequestUMP"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISysexSendRequestUMP"
        }
      ],
      "role": "symbol",
      "title": "MIDISysexSendRequestUMP",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequestump"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/complete": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the transmission is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "complete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/complete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "complete"
        }
      ],
      "role": "symbol",
      "title": "complete",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequestump/complete"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/completionProc": {
      "abstract": [
        {
          "text": "A function that the system calls after it sends all data for the request, or after the client marks the request as complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completionProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDICompletionProcUMP",
          "text": "MIDICompletionProcUMP"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/completionProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completionProc"
        }
      ],
      "role": "symbol",
      "title": "completionProc",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequestump/completionproc"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/completionRefCon": {
      "abstract": [
        {
          "text": "Data to pass to the completion function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completionRefCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/completionRefCon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completionRefCon"
        }
      ],
      "role": "symbol",
      "title": "completionRefCon",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequestump/completionrefcon"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/destination": {
      "abstract": [
        {
          "text": "The endpoint to send the event to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEndpointRef",
          "text": "MIDIEndpointRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/destination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "destination"
        }
      ],
      "role": "symbol",
      "title": "destination",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequestump/destination"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/init(destination:words:wordsToSend:complete:completionProc:completionRefCon:)": {
      "abstract": [
        {
          "text": "Creates a new single universal MIDI packet (UMP) system-exclusive (SysEx) event request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "destination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEndpointRef",
          "text": "MIDIEndpointRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "words"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "wordsToSend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "complete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDICompletionProcUMP",
          "text": "MIDICompletionProcUMP"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionRefCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/init(destination:words:wordsToSend:complete:completionProc:completionRefCon:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(destination:words:wordsToSend:complete:completionProc:completionRefCon:)",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequestump/init(destination:words:wordstosend:complete:completionproc:completionrefcon:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/words": {
      "abstract": [
        {
          "text": "A pointer to the event to send, which the system advances as it sends the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "words"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/words",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "words"
        }
      ],
      "role": "symbol",
      "title": "words",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequestump/words"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/wordsToSend": {
      "abstract": [
        {
          "text": "A counter of the number of words to send.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wordsToSend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/wordsToSend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wordsToSend"
        }
      ],
      "role": "symbol",
      "title": "wordsToSend",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequestump/wordstosend"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "IO-management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIFlushOutput(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIRestart()",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIIOErrorNotification"
      ],
      "title": "I/O management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-request",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/init(destination:words:wordsToSend:complete:completionProc:completionRefCon:)"
      ],
      "title": "Creating a request"
    },
    {
      "anchor": "Configuring-and-inspecting-a-request",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/destination",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/words",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/wordsToSend",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/complete",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICompletionProcUMP",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/completionProc",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/completionRefCon",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventPacketSysexBytesForGroup(_:_:_:)"
      ],
      "title": "Configuring and inspecting a request"
    },
    {
      "anchor": "Sending-a-request",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISendUMPSysex(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISendUMPSysex8(_:)"
      ],
      "title": "Sending a request"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MIDISysexSendRequestUMP"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysexSendRequestUMP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysexSendRequestUMP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-and-inspecting-a-request",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/destination",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/words",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/wordsToSend",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/complete",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICompletionProcUMP",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/completionProc",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP/completionRefCon",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventPacketSysexBytesForGroup(_:_:_:)"
              ],
              "title": "Configuring and inspecting a request"
            },
            {
              "anchor": "Sending-a-request",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISendUMPSysex(_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISendUMPSysex8(_:)"
              ],
              "title": "Sending a request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "IO-management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIFlushOutput(_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIRestart()",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIIOErrorNotification"
              ],
              "title": "I/O management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MIDISysexSendRequestUMP"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP~1completionRefCon/title",
          "value": "completionRefCon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP~1completionRefCon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "completionRefCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP~1words/title",
          "value": "words"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP~1words/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "words"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest/title",
          "value": "MIDISysexSendRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysexSendRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysexSendRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP~1destination/title",
          "value": "destination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP~1destination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "destination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISendUMPSysex8(_:)/title",
          "value": "MIDISendUMPSysex8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISendUMPSysex8(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISendUMPSysex8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP/title",
          "value": "MIDISysexSendRequestUMP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysexSendRequestUMP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysexSendRequestUMP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISendUMPSysex(_:)/title",
          "value": "MIDISendUMPSysex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISendUMPSysex(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISendUMPSysex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIRestart()/title",
          "value": "MIDIRestart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIRestart()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIRestart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP~1completionProc/title",
          "value": "completionProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP~1completionProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "completionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIIOErrorNotification/title",
          "value": "MIDIIOErrorNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIIOErrorNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIIOErrorNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIIOErrorNotification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIIOErrorNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICompletionProcUMP/title",
          "value": "MIDICompletionProcUMP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICompletionProcUMP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICompletionProcUMP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICompletionProcUMP/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICompletionProcUMP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP~1complete/title",
          "value": "complete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP~1complete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "complete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventPacketSysexBytesForGroup(_:_:_:)/title",
          "value": "MIDIEventPacketSysexBytesForGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventPacketSysexBytesForGroup(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIEventPacketSysexBytesForGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIFlushOutput(_:)/title",
          "value": "MIDIFlushOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIFlushOutput(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIFlushOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP~1wordsToSend/title",
          "value": "wordsToSend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP~1wordsToSend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wordsToSend"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midisysexsendrequestump"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midisysexsendrequestump"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
