{
  "abstract": [
    {
      "text": "Create driver plug-ins.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "MIDI Drivers"
  },
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceCreate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new device object that corresponds to the available hardware.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDeviceCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDriverRef",
          "text": "MIDIDriverRef"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceRef",
          "text": "MIDIDeviceRef"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceCreate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDeviceCreate"
        }
      ],
      "role": "symbol",
      "title": "MIDIDeviceCreate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/mididevicecreate(_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceDispose(_:)": {
      "abstract": [
        {
          "text": "Disposes of a MIDI device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDeviceDispose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceRef",
          "text": "MIDIDeviceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceDispose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDeviceDispose"
        }
      ],
      "role": "symbol",
      "title": "MIDIDeviceDispose(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/mididevicedispose(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListAddDevice(_:_:)": {
      "abstract": [
        {
          "text": "Adds the specified device to the device list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDeviceListAddDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceListRef",
          "text": "MIDIDeviceListRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceRef",
          "text": "MIDIDeviceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListAddDevice(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDeviceListAddDevice"
        }
      ],
      "role": "symbol",
      "title": "MIDIDeviceListAddDevice(_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/mididevicelistadddevice(_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListDispose(_:)": {
      "abstract": [
        {
          "text": "Disposes of a device list, but not its devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDeviceListDispose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceListRef",
          "text": "MIDIDeviceListRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListDispose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDeviceListDispose"
        }
      ],
      "role": "symbol",
      "title": "MIDIDeviceListDispose(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/mididevicelistdispose(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListGetDevice(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves a MIDI device from a device list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDeviceListGetDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceListRef",
          "text": "MIDIDeviceListRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceRef",
          "text": "MIDIDeviceRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListGetDevice(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDeviceListGetDevice"
        }
      ],
      "role": "symbol",
      "title": "MIDIDeviceListGetDevice(_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/mididevicelistgetdevice(_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListGetNumberOfDevices(_:)": {
      "abstract": [
        {
          "text": "Retrieves the number of devices in a device list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDeviceListGetNumberOfDevices"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceListRef",
          "text": "MIDIDeviceListRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListGetNumberOfDevices(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDeviceListGetNumberOfDevices"
        }
      ],
      "role": "symbol",
      "title": "MIDIDeviceListGetNumberOfDevices(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/mididevicelistgetnumberofdevices(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListRef": {
      "abstract": [
        {
          "text": "A list of MIDI devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDeviceListRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDeviceListRef"
        }
      ],
      "role": "symbol",
      "title": "MIDIDeviceListRef",
      "type": "topic",
      "url": "/documentation/coremidi/mididevicelistref"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceRef": {
      "abstract": [
        {
          "text": "A MIDI device that contains entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDeviceRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDeviceRef"
        }
      ],
      "role": "symbol",
      "title": "MIDIDeviceRef",
      "type": "topic",
      "url": "/documentation/coremidi/midideviceref"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverEnableMonitoring(_:_:)": {
      "abstract": [
        {
          "text": "Enables monitoring of all outgoing MIDI packets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDriverEnableMonitoring"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDriverRef",
          "text": "MIDIDriverRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverEnableMonitoring(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDriverEnableMonitoring"
        }
      ],
      "role": "symbol",
      "title": "MIDIDriverEnableMonitoring(_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/mididriverenablemonitoring(_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverInterface": {
      "abstract": [
        {
          "text": "The interface to a MIDI driver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDriverInterface"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDriverInterface"
        }
      ],
      "role": "symbol",
      "title": "MIDIDriverInterface",
      "type": "topic",
      "url": "/documentation/coremidi/mididriverinterface"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverRef": {
      "abstract": [
        {
          "text": "A MIDI driver object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDriverRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDriverRef"
        }
      ],
      "role": "symbol",
      "title": "MIDIDriverRef",
      "type": "topic",
      "url": "/documentation/coremidi/mididriverref"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetDriverDeviceList(_:)": {
      "abstract": [
        {
          "text": "Returns the list of driver-created devices in the current MIDI setup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIGetDriverDeviceList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDriverRef",
          "text": "MIDIDriverRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceListRef",
          "text": "MIDIDeviceListRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetDriverDeviceList(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIGetDriverDeviceList"
        }
      ],
      "role": "symbol",
      "title": "MIDIGetDriverDeviceList(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midigetdriverdevicelist(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetDriverIORunLoop()": {
      "abstract": [
        {
          "text": "Returns the server’s driver I/O thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIGetDriverIORunLoop"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopRef",
          "text": "CFRunLoop"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetDriverIORunLoop()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIGetDriverIORunLoop"
        }
      ],
      "role": "symbol",
      "title": "MIDIGetDriverIORunLoop()",
      "type": "topic",
      "url": "/documentation/coremidi/midigetdriveriorunloop()"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverPropertyUsesSerial": {
      "abstract": [
        {
          "text": "A value that indicates whether the driver uses serial ports and is eligible to have serial ports assigned to it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIDriverPropertyUsesSerial"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverPropertyUsesSerial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIDriverPropertyUsesSerial"
        }
      ],
      "role": "symbol",
      "title": "kMIDIDriverPropertyUsesSerial",
      "type": "topic",
      "url": "/documentation/coremidi/kmididriverpropertyusesserial"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth": {
      "abstract": [
        {
          "text": "Connect to Bluetooth Low Energy MIDI peripherals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Bluetooth",
      "type": "topic",
      "url": "/documentation/coremidi/midi-bluetooth"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry": {
      "abstract": [
        {
          "text": "Provide support for bidirectional discovery and configuration of devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Capability Inquiry",
      "type": "topic",
      "url": "/documentation/coremidi/midi-capability-inquiry"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages": {
      "abstract": [
        {
          "text": "Create and configure messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Messages",
      "type": "topic",
      "url": "/documentation/coremidi/midi-messages"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking": {
      "abstract": [
        {
          "text": "Create and manage devices connected over a local network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Networking",
      "type": "topic",
      "url": "/documentation/coremidi/midi-networking"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services": {
      "abstract": [
        {
          "text": "Communicate with hardware using Universal MIDI Packets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Services",
      "type": "topic",
      "url": "/documentation/coremidi/midi-services"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup": {
      "abstract": [
        {
          "text": "Configure the global MIDI system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI System Setup",
      "type": "topic",
      "url": "/documentation/coremidi/midi-system-setup"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection": {
      "abstract": [
        {
          "text": "Create play-through connections between sources and destinations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Thru Connection",
      "type": "topic",
      "url": "/documentation/coremidi/midi-thru-connection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Services",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry"
      ],
      "title": "Services"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-Device-Lifecyle",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceCreate(_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceDispose(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceRef"
      ],
      "title": "Managing Device Lifecyle"
    },
    {
      "anchor": "Managing-Device-Lists",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListGetNumberOfDevices(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListGetDevice(_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListAddDevice(_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListDispose(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListRef"
      ],
      "title": "Managing Device Lists"
    },
    {
      "anchor": "Inspecting-a-Driver",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetDriverDeviceList(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverEnableMonitoring(_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetDriverIORunLoop()",
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverPropertyUsesSerial",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverInterface",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverRef"
      ],
      "title": "Inspecting a Driver"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-Device-Lifecyle",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceCreate(_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceDispose(_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceRef"
              ],
              "title": "Managing Device Lifecyle"
            },
            {
              "anchor": "Managing-Device-Lists",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListGetNumberOfDevices(_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListGetDevice(_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListAddDevice(_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListDispose(_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceListRef"
              ],
              "title": "Managing Device Lists"
            },
            {
              "anchor": "Inspecting-a-Driver",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetDriverDeviceList(_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverEnableMonitoring(_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetDriverIORunLoop()",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverPropertyUsesSerial",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverInterface",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDriverRef"
              ],
              "title": "Inspecting a Driver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Services",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry"
              ],
              "title": "Services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIGetDriverIORunLoop()/title",
          "value": "MIDIGetDriverIORunLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIGetDriverIORunLoop()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIGetDriverIORunLoop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceRef/title",
          "value": "MIDIDeviceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIDriverPropertyUsesSerial/title",
          "value": "kMIDIDriverPropertyUsesSerial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIDriverPropertyUsesSerial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIDriverPropertyUsesSerial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListAddDevice(_:_:)/title",
          "value": "MIDIDeviceListAddDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListAddDevice(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceListAddDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverEnableMonitoring(_:_:)/title",
          "value": "MIDIDriverEnableMonitoring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverEnableMonitoring(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDriverEnableMonitoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceDispose(_:)/title",
          "value": "MIDIDeviceDispose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceDispose(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceDispose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListDispose(_:)/title",
          "value": "MIDIDeviceListDispose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListDispose(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceListDispose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListGetDevice(_:_:)/title",
          "value": "MIDIDeviceListGetDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListGetDevice(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceListGetDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListRef/title",
          "value": "MIDIDeviceListRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceListRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceListRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListGetNumberOfDevices(_:)/title",
          "value": "MIDIDeviceListGetNumberOfDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceListGetNumberOfDevices(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceListGetNumberOfDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverRef/title",
          "value": "MIDIDriverRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDriverRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDriverRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceCreate(_:_:_:_:_:)/title",
          "value": "MIDIDeviceCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceCreate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIGetDriverDeviceList(_:)/title",
          "value": "MIDIGetDriverDeviceList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIGetDriverDeviceList(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIGetDriverDeviceList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverInterface/title",
          "value": "MIDIDriverInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDriverInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDriverInterface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDriverInterface"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midi-drivers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midi-drivers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
