{
  "abstract": [
    {
      "text": "Create and configure messages.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "MIDI Messages"
  },
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPChannelVoiceMessage(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI1UPChannelVoiceMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIMessage_32",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPChannelVoiceMessage(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI1UPChannelVoiceMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI1UPChannelVoiceMessage(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi1upchannelvoicemessage(_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPControlChange(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI1UPControlChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIMessage_32",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPControlChange(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI1UPControlChange"
        }
      ],
      "role": "symbol",
      "title": "MIDI1UPControlChange(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi1upcontrolchange(_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPNoteOff(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI1UPNoteOff"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIMessage_32",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPNoteOff(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI1UPNoteOff"
        }
      ],
      "role": "symbol",
      "title": "MIDI1UPNoteOff(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi1upnoteoff(_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPNoteOn(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI1UPNoteOn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIMessage_32",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPNoteOn(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI1UPNoteOn"
        }
      ],
      "role": "symbol",
      "title": "MIDI1UPNoteOn(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi1upnoteon(_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPPitchBend(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI1UPPitchBend"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIMessage_32",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPPitchBend(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI1UPPitchBend"
        }
      ],
      "role": "symbol",
      "title": "MIDI1UPPitchBend(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi1uppitchbend(_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPSystemCommon(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI1UPSystemCommon"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIMessage_32",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPSystemCommon(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI1UPSystemCommon"
        }
      ],
      "role": "symbol",
      "title": "MIDI1UPSystemCommon(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi1upsystemcommon(_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2AssignableControl(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2AssignableControl"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2AssignableControl(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2AssignableControl"
        }
      ],
      "role": "symbol",
      "title": "MIDI2AssignableControl(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2assignablecontrol(_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2AssignablePNC(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2AssignablePNC"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2AssignablePNC(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2AssignablePNC"
        }
      ],
      "role": "symbol",
      "title": "MIDI2AssignablePNC(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2assignablepnc(_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ChannelPressure(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2ChannelPressure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ChannelPressure(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2ChannelPressure"
        }
      ],
      "role": "symbol",
      "title": "MIDI2ChannelPressure(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2channelpressure(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ChannelVoiceMessage(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2ChannelVoiceMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ChannelVoiceMessage(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2ChannelVoiceMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDI2ChannelVoiceMessage(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2channelvoicemessage(_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ControlChange(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2ControlChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ControlChange(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2ControlChange"
        }
      ],
      "role": "symbol",
      "title": "MIDI2ControlChange(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2controlchange(_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2NoteOff(_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2NoteOff"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2NoteOff(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2NoteOff"
        }
      ],
      "role": "symbol",
      "title": "MIDI2NoteOff(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2noteoff(_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2NoteOn(_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2NoteOn"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2NoteOn(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2NoteOn"
        }
      ],
      "role": "symbol",
      "title": "MIDI2NoteOn(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2noteon(_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PerNoteManagment(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2PerNoteManagment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PerNoteManagment(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2PerNoteManagment"
        }
      ],
      "role": "symbol",
      "title": "MIDI2PerNoteManagment(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2pernotemanagment(_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PerNotePitchBend(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2PerNotePitchBend"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PerNotePitchBend(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2PerNotePitchBend"
        }
      ],
      "role": "symbol",
      "title": "MIDI2PerNotePitchBend(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2pernotepitchbend(_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PitchBend(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2PitchBend"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PitchBend(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2PitchBend"
        }
      ],
      "role": "symbol",
      "title": "MIDI2PitchBend(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2pitchbend(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PolyPressure(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2PolyPressure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PolyPressure(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2PolyPressure"
        }
      ],
      "role": "symbol",
      "title": "MIDI2PolyPressure(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2polypressure(_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ProgramChange(_:_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2ProgramChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ProgramChange(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2ProgramChange"
        }
      ],
      "role": "symbol",
      "title": "MIDI2ProgramChange(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2programchange(_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RegisteredControl(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2RegisteredControl"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RegisteredControl(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2RegisteredControl"
        }
      ],
      "role": "symbol",
      "title": "MIDI2RegisteredControl(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2registeredcontrol(_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RegisteredPNC(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2RegisteredPNC"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RegisteredPNC(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2RegisteredPNC"
        }
      ],
      "role": "symbol",
      "title": "MIDI2RegisteredPNC(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2registeredpnc(_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RelAssignableControl(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2RelAssignableControl"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RelAssignableControl(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2RelAssignableControl"
        }
      ],
      "role": "symbol",
      "title": "MIDI2RelAssignableControl(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2relassignablecontrol(_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RelRegisteredControl(_:_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2RelRegisteredControl"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIMessage_64",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RelRegisteredControl(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2RelRegisteredControl"
        }
      ],
      "role": "symbol",
      "title": "MIDI2RelRegisteredControl(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midi2relregisteredcontrol(_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus": {
      "abstract": [
        {
          "text": "MIDI status types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICVStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICVStatus"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType": {
      "abstract": [
        {
          "text": "Supported MIDI message types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessageType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessageType"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessageType",
      "type": "topic",
      "url": "/documentation/coremidi/midimessagetype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageTypeForUPWord(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessageTypeForUPWord"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MIDIMessageType",
          "text": "MIDIMessageType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageTypeForUPWord(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessageTypeForUPWord"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessageTypeForUPWord(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midimessagetypeforupword(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_128": {
      "abstract": [
        {
          "text": "A 128-bit MIDI message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessage_128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_128",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessage_128"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessage_128",
      "type": "topic",
      "url": "/documentation/coremidi/midimessage_128"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_32": {
      "abstract": [
        {
          "text": "A 32-bit MIDI message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessage_32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessage_32"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessage_32",
      "type": "topic",
      "url": "/documentation/coremidi/midimessage_32"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_64": {
      "abstract": [
        {
          "text": "A 64-bit MIDI message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessage_64"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessage_64"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessage_64",
      "type": "topic",
      "url": "/documentation/coremidi/midimessage_64"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_96": {
      "abstract": [
        {
          "text": "A 96-bit MIDI message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIMessage_96"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_96",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIMessage_96"
        }
      ],
      "role": "symbol",
      "title": "MIDIMessage_96",
      "type": "topic",
      "url": "/documentation/coremidi/midimessage_96"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID": {
      "abstract": [
        {
          "text": "Specifies a MIDI protocol variant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIProtocolID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIProtocolID"
        }
      ],
      "role": "symbol",
      "title": "MIDIProtocolID",
      "type": "topic",
      "url": "/documentation/coremidi/midiprotocolid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysExStatus": {
      "abstract": [
        {
          "text": "MIDI System Exclusive (SysEx) types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISysExStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysExStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISysExStatus"
        }
      ],
      "role": "symbol",
      "title": "MIDISysExStatus",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexstatus"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus": {
      "abstract": [
        {
          "text": "MIDI System status types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISystemStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISystemStatus"
        }
      ],
      "role": "symbol",
      "title": "MIDISystemStatus",
      "type": "topic",
      "url": "/documentation/coremidi/midisystemstatus"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth": {
      "abstract": [
        {
          "text": "Connect to Bluetooth Low Energy MIDI peripherals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Bluetooth",
      "type": "topic",
      "url": "/documentation/coremidi/midi-bluetooth"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry": {
      "abstract": [
        {
          "text": "Provide support for bidirectional discovery and configuration of devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Capability Inquiry",
      "type": "topic",
      "url": "/documentation/coremidi/midi-capability-inquiry"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers": {
      "abstract": [
        {
          "text": "Create driver plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Drivers",
      "type": "topic",
      "url": "/documentation/coremidi/midi-drivers"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking": {
      "abstract": [
        {
          "text": "Create and manage devices connected over a local network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Networking",
      "type": "topic",
      "url": "/documentation/coremidi/midi-networking"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services": {
      "abstract": [
        {
          "text": "Communicate with hardware using Universal MIDI Packets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Services",
      "type": "topic",
      "url": "/documentation/coremidi/midi-services"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup": {
      "abstract": [
        {
          "text": "Configure the global MIDI system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI System Setup",
      "type": "topic",
      "url": "/documentation/coremidi/midi-system-setup"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection": {
      "abstract": [
        {
          "text": "Create play-through connections between sources and destinations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Thru Connection",
      "type": "topic",
      "url": "/documentation/coremidi/midi-thru-connection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Services",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry"
      ],
      "title": "Services"
    }
  ],
  "topicSections": [
    {
      "anchor": "MIDI-10-Messages",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPNoteOn(_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPNoteOff(_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPPitchBend(_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPControlChange(_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPSystemCommon(_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPChannelVoiceMessage(_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageTypeForUPWord(_:)"
      ],
      "title": "MIDI 1.0 Messages"
    },
    {
      "anchor": "MIDI-20-Messages",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ChannelVoiceMessage(_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2NoteOn(_:_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2NoteOff(_:_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ControlChange(_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ProgramChange(_:_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PitchBend(_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PerNotePitchBend(_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ChannelPressure(_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PolyPressure(_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2AssignableControl(_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RelRegisteredControl(_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2AssignablePNC(_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RegisteredPNC(_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RelAssignableControl(_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RegisteredControl(_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PerNoteManagment(_:_:_:_:_:)"
      ],
      "title": "MIDI 2.0 Messages"
    },
    {
      "anchor": "Common",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysExStatus",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_128",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_96",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_64",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_32",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType"
      ],
      "title": "Common"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "MIDI-10-Messages",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPNoteOn(_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPNoteOff(_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPPitchBend(_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPControlChange(_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPSystemCommon(_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI1UPChannelVoiceMessage(_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageTypeForUPWord(_:)"
              ],
              "title": "MIDI 1.0 Messages"
            },
            {
              "anchor": "MIDI-20-Messages",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ChannelVoiceMessage(_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2NoteOn(_:_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2NoteOff(_:_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ControlChange(_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ProgramChange(_:_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PitchBend(_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PerNotePitchBend(_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2ChannelPressure(_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PolyPressure(_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2AssignableControl(_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RelRegisteredControl(_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2AssignablePNC(_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RegisteredPNC(_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RelAssignableControl(_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2RegisteredControl(_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2PerNoteManagment(_:_:_:_:_:)"
              ],
              "title": "MIDI 2.0 Messages"
            },
            {
              "anchor": "Common",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProtocolID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysExStatus",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISystemStatus",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_128",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_96",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_64",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessage_32",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIMessageType"
              ],
              "title": "Common"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Services",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry"
              ],
              "title": "Services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2ProgramChange(_:_:_:_:_:_:)/title",
          "value": "MIDI2ProgramChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2ProgramChange(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2ProgramChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2ChannelVoiceMessage(_:_:_:_:_:)/title",
          "value": "MIDI2ChannelVoiceMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2ChannelVoiceMessage(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2ChannelVoiceMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2AssignableControl(_:_:_:_:_:)/title",
          "value": "MIDI2AssignableControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2AssignableControl(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2AssignableControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPControlChange(_:_:_:_:)/title",
          "value": "MIDI1UPControlChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPControlChange(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI1UPControlChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2RelAssignableControl(_:_:_:_:_:)/title",
          "value": "MIDI2RelAssignableControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2RelAssignableControl(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2RelAssignableControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPChannelVoiceMessage(_:_:_:_:_:)/title",
          "value": "MIDI1UPChannelVoiceMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPChannelVoiceMessage(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI1UPChannelVoiceMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_32/title",
          "value": "MIDIMessage_32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2AssignablePNC(_:_:_:_:_:)/title",
          "value": "MIDI2AssignablePNC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2AssignablePNC(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2AssignablePNC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2RelRegisteredControl(_:_:_:_:_:)/title",
          "value": "MIDI2RelRegisteredControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2RelRegisteredControl(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2RelRegisteredControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType/title",
          "value": "MIDIMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2PolyPressure(_:_:_:_:)/title",
          "value": "MIDI2PolyPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2PolyPressure(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2PolyPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus/title",
          "value": "MIDICVStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICVStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICVStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysExStatus/title",
          "value": "MIDISysExStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysExStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysExStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysExStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysExStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_64/title",
          "value": "MIDIMessage_64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_64/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2RegisteredPNC(_:_:_:_:_:)/title",
          "value": "MIDI2RegisteredPNC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2RegisteredPNC(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2RegisteredPNC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_96/title",
          "value": "MIDIMessage_96"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_96/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_96"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_96/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_96"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2NoteOff(_:_:_:_:_:_:)/title",
          "value": "MIDI2NoteOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2NoteOff(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2NoteOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_128/title",
          "value": "MIDIMessage_128"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_128/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessage_128/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessage_128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPNoteOff(_:_:_:_:)/title",
          "value": "MIDI1UPNoteOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPNoteOff(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI1UPNoteOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageTypeForUPWord(_:)/title",
          "value": "MIDIMessageTypeForUPWord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIMessageTypeForUPWord(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIMessageTypeForUPWord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2NoteOn(_:_:_:_:_:_:)/title",
          "value": "MIDI2NoteOn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2NoteOn(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2NoteOn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPPitchBend(_:_:_:_:)/title",
          "value": "MIDI1UPPitchBend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPPitchBend(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI1UPPitchBend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPNoteOn(_:_:_:_:)/title",
          "value": "MIDI1UPNoteOn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPNoteOn(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI1UPNoteOn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProtocolID/title",
          "value": "MIDIProtocolID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProtocolID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIProtocolID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProtocolID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIProtocolID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2PerNotePitchBend(_:_:_:_:)/title",
          "value": "MIDI2PerNotePitchBend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2PerNotePitchBend(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2PerNotePitchBend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus/title",
          "value": "MIDISystemStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISystemStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISystemStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISystemStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2PerNoteManagment(_:_:_:_:_:)/title",
          "value": "MIDI2PerNoteManagment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2PerNoteManagment(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2PerNoteManagment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2ControlChange(_:_:_:_:)/title",
          "value": "MIDI2ControlChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2ControlChange(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2ControlChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPSystemCommon(_:_:_:_:)/title",
          "value": "MIDI1UPSystemCommon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI1UPSystemCommon(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI1UPSystemCommon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2ChannelPressure(_:_:_:)/title",
          "value": "MIDI2ChannelPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2ChannelPressure(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2ChannelPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2PitchBend(_:_:_:)/title",
          "value": "MIDI2PitchBend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2PitchBend(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2PitchBend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2RegisteredControl(_:_:_:_:_:)/title",
          "value": "MIDI2RegisteredControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2RegisteredControl(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2RegisteredControl"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midi-messages"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midi-messages"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
