{
  "abstract": [
    {
      "text": "Closes a previously established source-to-input port connection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortDisconnectSource(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@MIDIPortDisconnectSource",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MIDIPortDisconnectSource"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MIDIPortRef",
        "text": "MIDIPortRef"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MIDIEndpointRef",
        "text": "MIDIEndpointRef"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MIDIPortDisconnectSource"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "MIDIPortDisconnectSource(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MIDIPortDisconnectSource"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "port"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MIDIPortRef",
              "text": "MIDIPortRef"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "source"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEndpointRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MIDIEndpointRef",
              "text": "MIDIEndpointRef"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The port with the connection to close.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "port"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The source from which to close a connection to a port.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "source"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "code": "OSStatus",
              "type": "codeVoice"
            },
            {
              "text": " result code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEndpointRef": {
      "abstract": [
        {
          "text": "A MIDI source or destination an entity owns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIEndpointRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEndpointRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIEndpointRef"
        }
      ],
      "role": "symbol",
      "title": "MIDIEndpointRef",
      "type": "topic",
      "url": "/documentation/coremidi/midiendpointref"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIInputPortCreateWithProtocol(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an input port through which the client may receive incoming MIDI messages from any MIDI source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIInputPortCreateWithProtocol"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIClientRef",
          "text": "MIDIClientRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MIDIProtocolID",
          "text": "MIDIProtocolID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIPortRef",
          "text": "MIDIPortRef"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIReceiveBlock",
          "text": "MIDIReceiveBlock"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIInputPortCreateWithProtocol(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIInputPortCreateWithProtocol"
        }
      ],
      "role": "symbol",
      "title": "MIDIInputPortCreateWithProtocol(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midiinputportcreatewithprotocol(_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIOutputPortCreate(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an output port through which a client sends outgoing MIDI messages to any MIDI destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIOutputPortCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIClientRef",
          "text": "MIDIClientRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIPortRef",
          "text": "MIDIPortRef"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIOutputPortCreate(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIOutputPortCreate"
        }
      ],
      "role": "symbol",
      "title": "MIDIOutputPortCreate(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midioutputportcreate(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortConnectSource(_:_:_:)": {
      "abstract": [
        {
          "text": "Makes a connection from a source to a client input port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIPortConnectSource"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIPortRef",
          "text": "MIDIPortRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEndpointRef",
          "text": "MIDIEndpointRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortConnectSource(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIPortConnectSource"
        }
      ],
      "role": "symbol",
      "title": "MIDIPortConnectSource(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midiportconnectsource(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortDisconnectSource(_:_:)": {
      "abstract": [
        {
          "text": "Closes a previously established source-to-input port connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIPortDisconnectSource"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIPortRef",
          "text": "MIDIPortRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEndpointRef",
          "text": "MIDIEndpointRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortDisconnectSource(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIPortDisconnectSource"
        }
      ],
      "role": "symbol",
      "title": "MIDIPortDisconnectSource(_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midiportdisconnectsource(_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortDispose(_:)": {
      "abstract": [
        {
          "text": "Disposes of a MIDI port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIPortDispose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIPortRef",
          "text": "MIDIPortRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortDispose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIPortDispose"
        }
      ],
      "role": "symbol",
      "title": "MIDIPortDispose(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midiportdispose(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortRef": {
      "abstract": [
        {
          "text": "A MIDI connection that a client maintains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIPortRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIPortRef"
        }
      ],
      "role": "symbol",
      "title": "MIDIPortRef",
      "type": "topic",
      "url": "/documentation/coremidi/midiportref"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIReceiveBlock": {
      "abstract": [
        {
          "text": "A block receiving MIDI input that includes the incoming messages and a refCon to identify the source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIReceiveBlock"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIReceiveBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIReceiveBlock"
        }
      ],
      "role": "symbol",
      "title": "MIDIReceiveBlock",
      "type": "topic",
      "url": "/documentation/coremidi/midireceiveblock"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Port-management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIInputPortCreateWithProtocol(_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIOutputPortCreate(_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortDispose(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortConnectSource(_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortRef",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIReceiveBlock"
      ],
      "title": "Port management"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MIDIPortDisconnectSource"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIPortDisconnectSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Port-management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIInputPortCreateWithProtocol(_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIOutputPortCreate(_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortDispose(_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortConnectSource(_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortRef",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIReceiveBlock"
              ],
              "title": "Port management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MIDIPortDisconnectSource"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPortRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MIDIPortRef",
                    "text": "MIDIPortRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "port"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEndpointRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MIDIEndpointRef",
                    "text": "MIDIEndpointRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "source"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The port with the connection to close.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "port"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The source from which to close a connection to a port.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "source"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An ",
                    "type": "text"
                  },
                  {
                    "code": "OSStatus",
                    "type": "codeVoice"
                  },
                  {
                    "text": " result code.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEndpointRef/title",
          "value": "MIDIEndpointRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEndpointRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIEndpointRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEndpointRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIEndpointRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIOutputPortCreate(_:_:_:)/title",
          "value": "MIDIOutputPortCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIOutputPortCreate(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIOutputPortCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIPortDispose(_:)/title",
          "value": "MIDIPortDispose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIPortDispose(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIPortDispose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIInputPortCreateWithProtocol(_:_:_:_:_:)/title",
          "value": "MIDIInputPortCreateWithProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIInputPortCreateWithProtocol(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIInputPortCreateWithProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIPortRef/title",
          "value": "MIDIPortRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIPortRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIPortRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIPortRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIPortRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIPortConnectSource(_:_:_:)/title",
          "value": "MIDIPortConnectSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIPortConnectSource(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIPortConnectSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIPortDisconnectSource(_:_:)/title",
          "value": "MIDIPortDisconnectSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIPortDisconnectSource(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIPortDisconnectSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIReceiveBlock/title",
          "value": "MIDIReceiveBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIReceiveBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIReceiveBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIReceiveBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIReceiveBlock"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midiportdisconnectsource(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midiportdisconnectsource(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
