{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@MIDIUniversalMessage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MIDIUniversalMessage"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MIDIUniversalMessage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MIDIUniversalMessage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MIDIUniversalMessage"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceManufacturer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2DeviceManufacturer"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceManufacturer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2DeviceManufacturer"
        }
      ],
      "role": "symbol",
      "title": "MIDI2DeviceManufacturer",
      "type": "topic",
      "url": "/documentation/coremidi/midi2devicemanufacturer"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceRevisionLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDI2DeviceRevisionLevel"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceRevisionLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDI2DeviceRevisionLevel"
        }
      ],
      "role": "symbol",
      "title": "MIDI2DeviceRevisionLevel",
      "type": "topic",
      "url": "/documentation/coremidi/midi2devicerevisionlevel"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProfileID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProfileID"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProfileID",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofileid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDManufacturerSpecific": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProfileIDManufacturerSpecific"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDManufacturerSpecific",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProfileIDManufacturerSpecific"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProfileIDManufacturerSpecific",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofileidmanufacturerspecific"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDStandard": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProfileIDStandard"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDStandard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProfileIDStandard"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProfileIDStandard",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofileidstandard"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUniversalMessage"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUniversalMessage"
        }
      ],
      "role": "symbol",
      "title": "MIDIUniversalMessage",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/channelVoice1-20x9n": {
      "abstract": [
        {
          "text": "active when type is kMIDIMessageTypeChannelVoice1",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "channelVoice1"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/channelVoice1-20x9n",
      "kind": "symbol",
      "role": "symbol",
      "title": "channelVoice1",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/channelvoice1-20x9n"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/channelVoice1-3muv1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelVoice1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIUniversalMessage",
          "text": "MIDIUniversalMessage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_union___Anonymous_field3"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_channelVoice1"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/channelVoice1-3muv1",
      "kind": "symbol",
      "role": "symbol",
      "title": "channelVoice1",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/channelvoice1-3muv1"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/channelVoice2-20x9k": {
      "abstract": [
        {
          "text": "active when type is kMIDIMessageTypeChannelVoice2",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "channelVoice2"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/channelVoice2-20x9k",
      "kind": "symbol",
      "role": "symbol",
      "title": "channelVoice2",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/channelvoice2-20x9k"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/channelVoice2-3muv2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelVoice2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIUniversalMessage",
          "text": "MIDIUniversalMessage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_union___Anonymous_field3"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_channelVoice2"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/channelVoice2-3muv2",
      "kind": "symbol",
      "role": "symbol",
      "title": "channelVoice2",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/channelvoice2-3muv2"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/data128-3jrad": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data128"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIUniversalMessage",
          "text": "MIDIUniversalMessage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_union___Anonymous_field3"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_data128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/data128-3jrad",
      "kind": "symbol",
      "role": "symbol",
      "title": "data128",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/data128-3jrad"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/data128-43npl": {
      "abstract": [
        {
          "text": "active when type is kMIDIMessageTypeData128",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "data128"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/data128-43npl",
      "kind": "symbol",
      "role": "symbol",
      "title": "data128",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/data128-43npl"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/group": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "group"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/group",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "group"
        }
      ],
      "role": "symbol",
      "title": "group",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/group"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/init()"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reserved"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reserved"
        }
      ],
      "role": "symbol",
      "title": "reserved",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/reserved"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/sysEx-13198": {
      "abstract": [
        {
          "text": "active when type is kMIDIMessageTypeSysEx",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "sysEx"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/sysEx-13198",
      "kind": "symbol",
      "role": "symbol",
      "title": "sysEx",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/sysex-13198"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/sysEx-2jr6w": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sysEx"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIUniversalMessage",
          "text": "MIDIUniversalMessage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_union___Anonymous_field3"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_sysEx"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/sysEx-2jr6w",
      "kind": "symbol",
      "role": "symbol",
      "title": "sysEx",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/sysex-2jr6w"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/system-6vxkw": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "system"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIUniversalMessage",
          "text": "MIDIUniversalMessage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_union___Anonymous_field3"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_system"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/system-6vxkw",
      "kind": "symbol",
      "role": "symbol",
      "title": "system",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/system-6vxkw"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/system-8xb4e": {
      "abstract": [
        {
          "text": "active when type is kMIDIMessageTypeSystem",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "system"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/system-8xb4e",
      "kind": "symbol",
      "role": "symbol",
      "title": "system",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/system-8xb4e"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/type": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MIDIMessageType",
          "text": "MIDIMessageType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/type"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/unknown-2egcc": {
      "abstract": [
        {
          "text": "active when type is unkown",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/unknown-2egcc",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/unknown-2egcc"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/unknown-9rrub": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIUniversalMessage",
          "text": "MIDIUniversalMessage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_union___Anonymous_field3"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_unknown"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/unknown-9rrub",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/unknown-9rrub"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/utility-1trwz": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "utility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIUniversalMessage",
          "text": "MIDIUniversalMessage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_union___Anonymous_field3"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_utility"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/utility-1trwz",
      "kind": "symbol",
      "role": "symbol",
      "title": "utility",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/utility-1trwz"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/utility-63fq7": {
      "abstract": [
        {
          "text": "active when type is kMIDIMessageTypeUtility",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "utility"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/utility-63fq7",
      "kind": "symbol",
      "role": "symbol",
      "title": "utility",
      "type": "topic",
      "url": "/documentation/coremidi/midiuniversalmessage/utility-63fq7"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceManufacturer",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceRevisionLevel",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDManufacturerSpecific",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDStandard"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/init()"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/channelVoice1-3muv1",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/channelVoice2-3muv2",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/data128-3jrad",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/group",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/reserved",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/sysEx-2jr6w",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/system-6vxkw",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/type",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/unknown-9rrub",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/utility-1trwz"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MIDIUniversalMessage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUniversalMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUniversalMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/channelVoice1-20x9n",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/channelVoice2-20x9k",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/data128-43npl",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/group",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/reserved",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/sysEx-13198",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/system-8xb4e",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/type",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/unknown-2egcc",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUniversalMessage/utility-63fq7"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceManufacturer",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI2DeviceRevisionLevel",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDManufacturerSpecific",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileIDStandard"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MIDIUniversalMessage"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "MIDIUniversalMessage"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUniversalMessage/title",
          "value": "MIDIUniversalMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUniversalMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUniversalMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUniversalMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUniversalMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileIDManufacturerSpecific/title",
          "value": "MIDICIProfileIDManufacturerSpecific"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileIDManufacturerSpecific/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileIDManufacturerSpecific"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileIDManufacturerSpecific/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileIDManufacturerSpecific"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUniversalMessage~1reserved/title",
          "value": "reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUniversalMessage~1reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2DeviceRevisionLevel/title",
          "value": "MIDI2DeviceRevisionLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2DeviceRevisionLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2DeviceRevisionLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2DeviceRevisionLevel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2DeviceRevisionLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2DeviceManufacturer/title",
          "value": "MIDI2DeviceManufacturer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2DeviceManufacturer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2DeviceManufacturer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDI2DeviceManufacturer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDI2DeviceManufacturer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileIDStandard/title",
          "value": "MIDICIProfileIDStandard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileIDStandard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileIDStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileIDStandard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileIDStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUniversalMessage~1group/title",
          "value": "group"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUniversalMessage~1group/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "group"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUniversalMessage~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUniversalMessage~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileID/title",
          "value": "MIDICIProfileID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midiuniversalmessage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midiuniversalmessage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
