{
  "abstract": [
    {
      "text": "Configure the global MIDI system.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-system-setup"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "MIDI System Setup"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The primary clients of this API are apps that present a user interface to configure the global MIDI system, and MIDI drivers that dynamically modify the system state as users connect and disconnect hardware.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceNewEntity(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Adds a new entity to a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDeviceNewEntity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceRef",
          "text": "MIDIDeviceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MIDIProtocolID",
          "text": "MIDIProtocolID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEntityRef",
          "text": "MIDIEntityRef"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceNewEntity(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDeviceNewEntity"
        }
      ],
      "role": "symbol",
      "title": "MIDIDeviceNewEntity(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/mididevicenewentity(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceRemoveEntity(_:_:)": {
      "abstract": [
        {
          "text": "Removes an entity from a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDeviceRemoveEntity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceRef",
          "text": "MIDIDeviceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEntityRef",
          "text": "MIDIEntityRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceRemoveEntity(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDeviceRemoveEntity"
        }
      ],
      "role": "symbol",
      "title": "MIDIDeviceRemoveEntity(_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midideviceremoveentity(_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEntityAddOrRemoveEndpoints(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds or removes an entity’s endpoints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIEntityAddOrRemoveEndpoints"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEntityRef",
          "text": "MIDIEntityRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEntityAddOrRemoveEndpoints(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIEntityAddOrRemoveEndpoints"
        }
      ],
      "role": "symbol",
      "title": "MIDIEntityAddOrRemoveEndpoints(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midientityaddorremoveendpoints(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIExternalDeviceCreate(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an external MIDI device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIExternalDeviceCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceRef",
          "text": "MIDIDeviceRef"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIExternalDeviceCreate(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIExternalDeviceCreate"
        }
      ],
      "role": "symbol",
      "title": "MIDIExternalDeviceCreate(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midiexternaldevicecreate(_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupAddDevice(_:)": {
      "abstract": [
        {
          "text": "Adds a driver-owned MIDI device to the current MIDI setup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISetupAddDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceRef",
          "text": "MIDIDeviceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupAddDevice(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISetupAddDevice"
        }
      ],
      "role": "symbol",
      "title": "MIDISetupAddDevice(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupadddevice(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupAddExternalDevice(_:)": {
      "abstract": [
        {
          "text": "Adds an external MIDI device to the current MIDI setup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISetupAddExternalDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceRef",
          "text": "MIDIDeviceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupAddExternalDevice(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISetupAddExternalDevice"
        }
      ],
      "role": "symbol",
      "title": "MIDISetupAddExternalDevice(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupaddexternaldevice(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRemoveDevice(_:)": {
      "abstract": [
        {
          "text": "Removes a driver-owned MIDI device from the current MIDI setup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISetupRemoveDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceRef",
          "text": "MIDIDeviceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRemoveDevice(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISetupRemoveDevice"
        }
      ],
      "role": "symbol",
      "title": "MIDISetupRemoveDevice(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupremovedevice(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRemoveExternalDevice(_:)": {
      "abstract": [
        {
          "text": "Removes an external MIDI device from the current MIDI setup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISetupRemoveExternalDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceRef",
          "text": "MIDIDeviceRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRemoveExternalDevice(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISetupRemoveExternalDevice"
        }
      ],
      "role": "symbol",
      "title": "MIDISetupRemoveExternalDevice(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupremoveexternaldevice(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/coremidi/deprecated-symbols"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth": {
      "abstract": [
        {
          "text": "Connect to Bluetooth Low Energy MIDI peripherals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Bluetooth",
      "type": "topic",
      "url": "/documentation/coremidi/midi-bluetooth"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry": {
      "abstract": [
        {
          "text": "Provide support for bidirectional discovery and configuration of devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Capability Inquiry",
      "type": "topic",
      "url": "/documentation/coremidi/midi-capability-inquiry"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers": {
      "abstract": [
        {
          "text": "Create driver plug-ins.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Drivers",
      "type": "topic",
      "url": "/documentation/coremidi/midi-drivers"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages": {
      "abstract": [
        {
          "text": "Create and configure messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Messages",
      "type": "topic",
      "url": "/documentation/coremidi/midi-messages"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking": {
      "abstract": [
        {
          "text": "Create and manage devices connected over a local network.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Networking",
      "type": "topic",
      "url": "/documentation/coremidi/midi-networking"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services": {
      "abstract": [
        {
          "text": "Communicate with hardware using Universal MIDI Packets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Services",
      "type": "topic",
      "url": "/documentation/coremidi/midi-services"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection": {
      "abstract": [
        {
          "text": "Create play-through connections between sources and destinations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MIDI Thru Connection",
      "type": "topic",
      "url": "/documentation/coremidi/midi-thru-connection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Services",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers",
        "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry"
      ],
      "title": "Services"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-Devices",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupAddDevice(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRemoveDevice(_:)"
      ],
      "title": "Managing Devices"
    },
    {
      "anchor": "Managing-External-Devices",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIExternalDeviceCreate(_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupAddExternalDevice(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRemoveExternalDevice(_:)"
      ],
      "title": "Managing External Devices"
    },
    {
      "anchor": "Managing-Entities",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceNewEntity(_:_:_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceRemoveEntity(_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEntityAddOrRemoveEndpoints(_:_:_:)"
      ],
      "title": "Managing Entities"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/deprecated-symbols"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-Devices",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupAddDevice(_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRemoveDevice(_:)"
              ],
              "title": "Managing Devices"
            },
            {
              "anchor": "Managing-External-Devices",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIExternalDeviceCreate(_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupAddExternalDevice(_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRemoveExternalDevice(_:)"
              ],
              "title": "Managing External Devices"
            },
            {
              "anchor": "Managing-Entities",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceNewEntity(_:_:_:_:_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceRemoveEntity(_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEntityAddOrRemoveEndpoints(_:_:_:)"
              ],
              "title": "Managing Entities"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/deprecated-symbols"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Services",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-services",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-bluetooth",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-messages",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-thru-connection",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-networking",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-drivers",
                "doc://com.apple.coremidi/documentation/CoreMIDI/midi-capability-inquiry"
              ],
              "title": "Services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIExternalDeviceCreate(_:_:_:_:)/title",
          "value": "MIDIExternalDeviceCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIExternalDeviceCreate(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIExternalDeviceCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceRemoveEntity(_:_:)/title",
          "value": "MIDIDeviceRemoveEntity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceRemoveEntity(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceRemoveEntity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISetupAddExternalDevice(_:)/title",
          "value": "MIDISetupAddExternalDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISetupAddExternalDevice(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISetupAddExternalDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISetupAddDevice(_:)/title",
          "value": "MIDISetupAddDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISetupAddDevice(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISetupAddDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISetupRemoveDevice(_:)/title",
          "value": "MIDISetupRemoveDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISetupRemoveDevice(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISetupRemoveDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceNewEntity(_:_:_:_:_:_:_:)/title",
          "value": "MIDIDeviceNewEntity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceNewEntity(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceNewEntity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISetupRemoveExternalDevice(_:)/title",
          "value": "MIDISetupRemoveExternalDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISetupRemoveExternalDevice(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISetupRemoveExternalDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEntityAddOrRemoveEndpoints(_:_:_:)/title",
          "value": "MIDIEntityAddOrRemoveEndpoints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEntityAddOrRemoveEndpoints(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIEntityAddOrRemoveEndpoints"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midi-system-setup"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midi-system-setup"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
