{
  "abstract": [
    {
      "text": "An object that provides the enabled and disabled profiles for a MIDI channel or port on a device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MIDICIProfileState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MIDICIProfileState"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MIDICIProfileState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MIDICIProfileState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MIDICIProfileState"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDiscoveryManager": {
      "abstract": [
        {
          "text": "A singleton object that performs systemwide MIDI-CI discovery.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIDiscoveryManager"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDiscoveryManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIDiscoveryManager"
        }
      ],
      "role": "symbol",
      "title": "MIDICIDiscoveryManager",
      "type": "topic",
      "url": "/documentation/coremidi/midicidiscoverymanager"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfile": {
      "abstract": [
        {
          "text": "A mapping of MIDI messages to specific sounds and synthesis behaviors, such as General MIDI, a drawbar organ, and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProfile"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProfile"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProfile",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofile"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState": {
      "abstract": [
        {
          "text": "An object that provides the enabled and disabled profiles for a MIDI channel or port on a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProfileState"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProfileState"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProfileState",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofilestate"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/disabledProfiles": {
      "abstract": [
        {
          "text": "The object’s disabled profiles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disabledProfiles"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MIDICIProfile",
          "text": "MIDICIProfile"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/disabledProfiles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disabledProfiles"
        }
      ],
      "role": "symbol",
      "title": "disabledProfiles",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofilestate/disabledprofiles"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/enabledProfiles": {
      "abstract": [
        {
          "text": "The object’s enabled profiles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enabledProfiles"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MIDICIProfile",
          "text": "MIDICIProfile"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/enabledProfiles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabledProfiles"
        }
      ],
      "role": "symbol",
      "title": "enabledProfiles",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofilestate/enabledprofiles"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/init(channel:enabledProfiles:disabledProfiles:)": {
      "abstract": [
        {
          "text": "Creates a new profile state object for the specified MIDI channel and profiles.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "channel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIChannelNumber",
          "text": "MIDIChannelNumber"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "enabledProfiles"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MIDICIProfile",
          "text": "MIDICIProfile"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "disabledProfiles"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MIDICIProfile",
          "text": "MIDICIProfile"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/init(channel:enabledProfiles:disabledProfiles:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithChannel:enabledProfiles:disabledProfiles:"
        }
      ],
      "role": "symbol",
      "title": "init(channel:enabledProfiles:disabledProfiles:)",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofilestate/init(channel:enabledprofiles:disabledprofiles:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/init(enabledProfiles:disabledProfiles:)": {
      "abstract": [
        {
          "text": "Creates a new profile state object for the specified profiles.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "enabledProfiles"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MIDICIProfile",
          "text": "MIDICIProfile"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "disabledProfiles"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MIDICIProfile",
          "text": "MIDICIProfile"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/init(enabledProfiles:disabledProfiles:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEnabledProfiles:disabledProfiles:"
        }
      ],
      "role": "symbol",
      "title": "init(enabledProfiles:disabledProfiles:)",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofilestate/init(enabledprofiles:disabledprofiles:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/midiChannel": {
      "abstract": [
        {
          "text": "The MIDI channel to which this state applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "midiChannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIChannelNumber",
          "text": "MIDIChannelNumber"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/midiChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "midiChannel"
        }
      ],
      "role": "symbol",
      "title": "midiChannel",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofilestate/midichannel"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileStateList": {
      "abstract": [
        {
          "text": "An array of profile state objects that describes the profile configuration for all channels of a reachable MIDI-CI node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDICIProfileStateList"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileStateList",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDICIProfileStateList",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofilestatelist"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder": {
      "abstract": [
        {
          "text": "An object that responds to MIDI-CI inquiries from an initiator on behalf of a MIDI client, and handles profile and property exchange operations.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIResponder"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIResponder"
        }
      ],
      "role": "symbol",
      "title": "MIDICIResponder",
      "type": "topic",
      "url": "/documentation/coremidi/midiciresponder"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICISession": {
      "abstract": [
        {
          "text": "An object that represents a MIDI-CI session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICISession"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICISession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICISession"
        }
      ],
      "role": "symbol",
      "title": "MIDICISession",
      "type": "topic",
      "url": "/documentation/coremidi/midicisession"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Capability-Inquiry",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDiscoveryManager",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICISession",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfile",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder"
      ],
      "title": "Capability Inquiry"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Profile-State",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/init(channel:enabledProfiles:disabledProfiles:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/init(enabledProfiles:disabledProfiles:)"
      ],
      "title": "Creating a Profile State"
    },
    {
      "anchor": "Accessing-the-MIDI-Channel",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/midiChannel"
      ],
      "title": "Accessing the MIDI Channel"
    },
    {
      "anchor": "Accessing-Profiles",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/enabledProfiles",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/disabledProfiles"
      ],
      "title": "Accessing Profiles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MIDICIProfileState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Profile-State",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/init(channel:enabledProfiles:disabledProfiles:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/init(enabledProfiles:disabledProfiles:)"
              ],
              "title": "Creating a Profile State"
            },
            {
              "anchor": "Accessing-the-MIDI-Channel",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/midiChannel"
              ],
              "title": "Accessing the MIDI Channel"
            },
            {
              "anchor": "Accessing-Profiles",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/enabledProfiles",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileState/disabledProfiles"
              ],
              "title": "Accessing Profiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Capability-Inquiry",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDiscoveryManager",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICISession",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfile",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileStateList",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIResponder"
              ],
              "title": "Capability Inquiry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MIDICIProfileState"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICISession/title",
          "value": "MIDICISession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICISession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICISession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICISession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICISession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDiscoveryManager/title",
          "value": "MIDICIDiscoveryManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDiscoveryManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDiscoveryManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDiscoveryManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDiscoveryManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState/title",
          "value": "MIDICIProfileState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIResponder/title",
          "value": "MIDICIResponder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIResponder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIResponder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState~1init(channel:enabledProfiles:disabledProfiles:)/title",
          "value": "initWithChannel:enabledProfiles:disabledProfiles:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState~1init(channel:enabledProfiles:disabledProfiles:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithChannel:enabledProfiles:disabledProfiles:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfile/title",
          "value": "MIDICIProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState~1enabledProfiles/title",
          "value": "enabledProfiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState~1enabledProfiles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enabledProfiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState~1init(enabledProfiles:disabledProfiles:)/title",
          "value": "initWithEnabledProfiles:disabledProfiles:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState~1init(enabledProfiles:disabledProfiles:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEnabledProfiles:disabledProfiles:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState~1disabledProfiles/title",
          "value": "disabledProfiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState~1disabledProfiles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "disabledProfiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState~1midiChannel/title",
          "value": "midiChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileState~1midiChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "midiChannel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midiciprofilestate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midiciprofilestate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
