{
  "abstract": [
    {
      "text": "The types of state changes the system supports.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MIDINotificationMessageID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MIDINotificationMessageID"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MIDINotificationMessageID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MIDINotificationMessageID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MIDINotificationMessageID"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotification/messageID": {
      "abstract": [
        {
          "text": "An identifier that describes the type of state change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messageID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MIDINotificationMessageID",
          "text": "MIDINotificationMessageID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotification/messageID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "messageID"
        }
      ],
      "role": "symbol",
      "title": "messageID",
      "type": "topic",
      "url": "/documentation/coremidi/midinotification/messageid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotification/messageSize": {
      "abstract": [
        {
          "text": "The size of the message including its ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messageSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotification/messageSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "messageSize"
        }
      ],
      "role": "symbol",
      "title": "messageSize",
      "type": "topic",
      "url": "/documentation/coremidi/midinotification/messagesize"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID": {
      "abstract": [
        {
          "text": "The types of state changes the system supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDINotificationMessageID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDINotificationMessageID"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/init(rawvalue:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgIOError": {
      "abstract": [
        {
          "text": "A driver I/O error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msgIOError"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgIOError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMsgIOError"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID.msgIOError",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/msgioerror"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgInternalStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msgInternalStart"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgInternalStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMsgInternalStart"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID.msgInternalStart",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/msginternalstart"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectAdded": {
      "abstract": [
        {
          "text": "The system added a device, entity, or endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msgObjectAdded"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectAdded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMsgObjectAdded"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID.msgObjectAdded",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/msgobjectadded"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectRemoved": {
      "abstract": [
        {
          "text": "The system removed a device, entity, or endpoint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msgObjectRemoved"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectRemoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMsgObjectRemoved"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID.msgObjectRemoved",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/msgobjectremoved"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgPropertyChanged": {
      "abstract": [
        {
          "text": "An object’s property value changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msgPropertyChanged"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgPropertyChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMsgPropertyChanged"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID.msgPropertyChanged",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/msgpropertychanged"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSerialPortOwnerChanged": {
      "abstract": [
        {
          "text": "The system changed a serial port owner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msgSerialPortOwnerChanged"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSerialPortOwnerChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMsgSerialPortOwnerChanged"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID.msgSerialPortOwnerChanged",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/msgserialportownerchanged"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSetupChanged": {
      "abstract": [
        {
          "text": "Some aspect of the current MIDI setup changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msgSetupChanged"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSetupChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMsgSetupChanged"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID.msgSetupChanged",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/msgsetupchanged"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgThruConnectionsChanged": {
      "abstract": [
        {
          "text": "The system created or disposed of a persistent MIDI Thru connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "msgThruConnectionsChanged"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgThruConnectionsChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIMsgThruConnectionsChanged"
        }
      ],
      "role": "symbol",
      "title": "MIDINotificationMessageID.msgThruConnectionsChanged",
      "type": "topic",
      "url": "/documentation/coremidi/midinotificationmessageid/msgthruconnectionschanged"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-the-Notification",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotification/messageID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotification/messageSize"
      ],
      "title": "Inspecting the Notification"
    }
  ],
  "topicSections": [
    {
      "anchor": "Change-Types",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSetupChanged",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectAdded",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectRemoved",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgPropertyChanged",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgThruConnectionsChanged",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSerialPortOwnerChanged",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgIOError"
      ],
      "title": "Change Types"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgInternalStart"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MIDINotificationMessageID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINotificationMessageID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINotificationMessageID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Change-Types",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSetupChanged",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectAdded",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgObjectRemoved",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgPropertyChanged",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgThruConnectionsChanged",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgSerialPortOwnerChanged",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgIOError"
              ],
              "title": "Change Types"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotificationMessageID/msgInternalStart"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-the-Notification",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotification/messageID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINotification/messageSize"
              ],
              "title": "Inspecting the Notification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MIDINotificationMessageID"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SInt32",
                    "text": "SInt32"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgIOError/title",
          "value": "kMIDIMsgIOError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgIOError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgIOError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgInternalStart/title",
          "value": "kMIDIMsgInternalStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgInternalStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgInternalStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotification~1messageID/title",
          "value": "messageID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotification~1messageID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "messageID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgObjectAdded/title",
          "value": "kMIDIMsgObjectAdded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgObjectAdded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgObjectAdded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgPropertyChanged/title",
          "value": "kMIDIMsgPropertyChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgPropertyChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgPropertyChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotification~1messageSize/title",
          "value": "messageSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotification~1messageSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "messageSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgSetupChanged/title",
          "value": "kMIDIMsgSetupChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgSetupChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgSetupChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgThruConnectionsChanged/title",
          "value": "kMIDIMsgThruConnectionsChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgThruConnectionsChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgThruConnectionsChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgSerialPortOwnerChanged/title",
          "value": "kMIDIMsgSerialPortOwnerChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgSerialPortOwnerChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgSerialPortOwnerChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID/title",
          "value": "MIDINotificationMessageID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINotificationMessageID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINotificationMessageID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgObjectRemoved/title",
          "value": "kMIDIMsgObjectRemoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINotificationMessageID~1msgObjectRemoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIMsgObjectRemoved"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midinotificationmessageid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midinotificationmessageid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
