{
  "abstract": [
    {
      "text": "A request to asynchronously send a single system-exclusive (SysEx) event to a destination.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@MIDISysexSendRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MIDISysexSendRequest"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MIDISysexSendRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MIDISysexSendRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MIDISysexSendRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICompletionProc": {
      "abstract": [
        {
          "text": "A function the system calls after it completely sends a system-exclusive (SysEx) event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICompletionProc"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICompletionProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICompletionProc"
        }
      ],
      "role": "symbol",
      "title": "MIDICompletionProc",
      "type": "topic",
      "url": "/documentation/coremidi/midicompletionproc"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIFlushOutput(_:)": {
      "abstract": [
        {
          "text": "Cancels all pending events that were previously scheduled to send.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIFlushOutput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEndpointRef",
          "text": "MIDIEndpointRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIFlushOutput(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIFlushOutput"
        }
      ],
      "role": "symbol",
      "title": "MIDIFlushOutput(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midiflushoutput(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIIOErrorNotification": {
      "abstract": [
        {
          "text": "A general I/O error notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIIOErrorNotification"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIIOErrorNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIIOErrorNotification"
        }
      ],
      "role": "symbol",
      "title": "MIDIIOErrorNotification",
      "type": "topic",
      "url": "/documentation/coremidi/midiioerrornotification"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIRestart()": {
      "abstract": [
        {
          "text": "Stops and restarts MIDI I/O.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIRestart"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIRestart()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIRestart"
        }
      ],
      "role": "symbol",
      "title": "MIDIRestart()",
      "type": "topic",
      "url": "/documentation/coremidi/midirestart()"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISendSysex(_:)": {
      "abstract": [
        {
          "text": "Asynchronously sends a single system-exclusive (SysEx) event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISendSysex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDISysexSendRequest",
          "text": "MIDISysexSendRequest"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISendSysex(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISendSysex"
        }
      ],
      "role": "symbol",
      "title": "MIDISendSysex(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midisendsysex(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest": {
      "abstract": [
        {
          "text": "A request to asynchronously send a single system-exclusive (SysEx) event to a destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISysexSendRequest"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISysexSendRequest"
        }
      ],
      "role": "symbol",
      "title": "MIDISysexSendRequest",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequest"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/bytesToSend": {
      "abstract": [
        {
          "text": "The number of bytes to send.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bytesToSend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/bytesToSend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bytesToSend"
        }
      ],
      "role": "symbol",
      "title": "bytesToSend",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequest/bytestosend"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/complete": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the transmission is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "complete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/complete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "complete"
        }
      ],
      "role": "symbol",
      "title": "complete",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequest/complete"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/completionProc": {
      "abstract": [
        {
          "text": "A function that the system calls after it sends all bytes for the request, or after the client marks the request as complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completionProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDICompletionProc",
          "text": "MIDICompletionProc"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/completionProc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completionProc"
        }
      ],
      "role": "symbol",
      "title": "completionProc",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequest/completionproc"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/completionRefCon": {
      "abstract": [
        {
          "text": "Data to pass to the completion function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completionRefCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/completionRefCon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completionRefCon"
        }
      ],
      "role": "symbol",
      "title": "completionRefCon",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequest/completionrefcon"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/data": {
      "abstract": [
        {
          "text": "The request’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/data",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "data"
        }
      ],
      "role": "symbol",
      "title": "data",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequest/data"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/destination": {
      "abstract": [
        {
          "text": "The endpoint to send the event to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEndpointRef",
          "text": "MIDIEndpointRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/destination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "destination"
        }
      ],
      "role": "symbol",
      "title": "destination",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequest/destination"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/init(destination:data:bytesToSend:complete:reserved:completionProc:completionRefCon:)": {
      "abstract": [
        {
          "text": "Creates a new single system-exclusive (SysEx) event request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "destination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEndpointRef",
          "text": "MIDIEndpointRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "bytesToSend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "complete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reserved"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": "), "
        },
        {
          "kind": "externalParam",
          "text": "completionProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDICompletionProc",
          "text": "MIDICompletionProc"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionRefCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/init(destination:data:bytesToSend:complete:reserved:completionProc:completionRefCon:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(destination:data:bytesToSend:complete:reserved:completionProc:completionRefCon:)",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequest/init(destination:data:bytestosend:complete:reserved:completionproc:completionrefcon:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/reserved": {
      "abstract": [
        {
          "text": "A field that’s reserved for future use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reserved"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reserved"
        }
      ],
      "role": "symbol",
      "title": "reserved",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequest/reserved"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP": {
      "abstract": [
        {
          "text": "A request to asynchronously send a single universal MIDI packet (UMP) system-exclusive (SysEx) event to a destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISysexSendRequestUMP"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISysexSendRequestUMP"
        }
      ],
      "role": "symbol",
      "title": "MIDISysexSendRequestUMP",
      "type": "topic",
      "url": "/documentation/coremidi/midisysexsendrequestump"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "IO-management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIFlushOutput(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIRestart()",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIIOErrorNotification"
      ],
      "title": "I/O management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-request",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/init(destination:data:bytesToSend:complete:reserved:completionProc:completionRefCon:)"
      ],
      "title": "Creating a request"
    },
    {
      "anchor": "Configuring-a-request",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/destination",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/data",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/bytesToSend",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/complete",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICompletionProc",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/completionProc",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/completionRefCon",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/reserved"
      ],
      "title": "Configuring a request"
    },
    {
      "anchor": "Sending-a-request",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISendSysex(_:)"
      ],
      "title": "Sending a request"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MIDISysexSendRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysexSendRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysexSendRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-a-request",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/destination",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/data",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/bytesToSend",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/complete",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICompletionProc",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/completionProc",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/completionRefCon",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequest/reserved"
              ],
              "title": "Configuring a request"
            },
            {
              "anchor": "Sending-a-request",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISendSysex(_:)"
              ],
              "title": "Sending a request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "IO-management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISysexSendRequestUMP",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIFlushOutput(_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIRestart()",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIIOErrorNotification"
              ],
              "title": "I/O management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MIDISysexSendRequest"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest~1reserved/title",
          "value": "reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest~1reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP/title",
          "value": "MIDISysexSendRequestUMP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysexSendRequestUMP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequestUMP/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysexSendRequestUMP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest~1data/title",
          "value": "data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest~1data/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest~1complete/title",
          "value": "complete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest~1complete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "complete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISendSysex(_:)/title",
          "value": "MIDISendSysex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISendSysex(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISendSysex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest~1destination/title",
          "value": "destination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest~1destination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "destination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest~1completionRefCon/title",
          "value": "completionRefCon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest~1completionRefCon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "completionRefCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest~1completionProc/title",
          "value": "completionProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest~1completionProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "completionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest~1bytesToSend/title",
          "value": "bytesToSend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest~1bytesToSend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bytesToSend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIRestart()/title",
          "value": "MIDIRestart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIRestart()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIRestart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIIOErrorNotification/title",
          "value": "MIDIIOErrorNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIIOErrorNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIIOErrorNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIIOErrorNotification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIIOErrorNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIFlushOutput(_:)/title",
          "value": "MIDIFlushOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIFlushOutput(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIFlushOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest/title",
          "value": "MIDISysexSendRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysexSendRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISysexSendRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISysexSendRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICompletionProc/title",
          "value": "MIDICompletionProc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICompletionProc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICompletionProc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICompletionProc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICompletionProc"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midisysexsendrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midisysexsendrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
