{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/midi_system_setup-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceAddEntity(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Specifies one of the entities that make up a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIDeviceAddEntity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIDeviceRef",
          "text": "MIDIDeviceRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEntityRef",
          "text": "MIDIEntityRef"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceAddEntity(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIDeviceAddEntity"
        }
      ],
      "role": "symbol",
      "title": "MIDIDeviceAddEntity(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midideviceaddentity(_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetSerialPortDrivers": {
      "abstract": [
        {
          "text": "Returns a list of installed MIDI drivers for serial port MIDI devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDIGetSerialPortDrivers"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetSerialPortDrivers",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDIGetSerialPortDrivers",
      "type": "topic",
      "url": "/documentation/coremidi/midigetserialportdrivers"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetSerialPortOwner": {
      "abstract": [
        {
          "text": "Returns the MIDI driver that owns a serial port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDIGetSerialPortOwner"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetSerialPortOwner",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDIGetSerialPortOwner",
      "type": "topic",
      "url": "/documentation/coremidi/midigetserialportowner"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetSerialPortOwner": {
      "abstract": [
        {
          "text": "Specifies the MIDI driver that owns a serial port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDISetSerialPortOwner"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetSerialPortOwner",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDISetSerialPortOwner",
      "type": "topic",
      "url": "/documentation/coremidi/midisetserialportowner"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupCreate": {
      "abstract": [
        {
          "text": "Queries drivers to discover what hardware is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDISetupCreate"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDISetupCreate",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupcreate"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupDispose": {
      "abstract": [
        {
          "text": "Disposes the specified setup object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDISetupDispose"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupDispose",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDISetupDispose",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupdispose"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupFromData": {
      "abstract": [
        {
          "text": "Creates a MIDISetup object from an XML stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDISetupFromData"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupFromData",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDISetupFromData",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupfromdata"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupGetCurrent": {
      "abstract": [
        {
          "text": "Returns the system’s current MIDISetup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDISetupGetCurrent"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupGetCurrent",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDISetupGetCurrent",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupgetcurrent"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupInstall": {
      "abstract": [
        {
          "text": "Installs a MIDISetup as the system’s current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDISetupInstall"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupInstall",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDISetupInstall",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupinstall"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRef": {
      "abstract": [
        {
          "text": "A type that represents the global state of the MIDI system, that contains lists of the devices and serial port owners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISetupRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISetupRef"
        }
      ],
      "role": "symbol",
      "title": "MIDISetupRef",
      "type": "topic",
      "url": "/documentation/coremidi/midisetupref"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupToData": {
      "abstract": [
        {
          "text": "Creates an XML representation of a MIDISetup object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDISetupToData"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupToData",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDISetupToData",
      "type": "topic",
      "url": "/documentation/coremidi/midisetuptodata"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Managing-System-Setup",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRef"
      ],
      "title": "Managing System Setup"
    },
    {
      "anchor": "Managing-MIDI-Devices",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceAddEntity(_:_:_:_:_:_:)"
      ],
      "title": "Managing MIDI Devices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-System-Setup",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupCreate",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupDispose",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupFromData",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupGetCurrent",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupInstall",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupToData",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetupRef"
              ],
              "title": "Managing System Setup"
            },
            {
              "anchor": "Managing-Serial-Ports",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetSerialPortOwner",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISetSerialPortOwner",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIGetSerialPortDrivers"
              ],
              "title": "Managing Serial Ports"
            },
            {
              "anchor": "Managing-MIDI-Devices",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIDeviceAddEntity(_:_:_:_:_:_:)"
              ],
              "title": "Managing MIDI Devices"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISetupRef/title",
          "value": "MIDISetupRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISetupRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISetupRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISetupRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISetupRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceAddEntity(_:_:_:_:_:_:)/title",
          "value": "MIDIDeviceAddEntity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIDeviceAddEntity(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIDeviceAddEntity"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midi_system_setup-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midi_system_setup-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
