{
  "abstract": [
    {
      "text": "A source or destination in a MIDI thru connection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@MIDIThruConnectionEndpoint",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MIDIThruConnectionEndpoint"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MIDIThruConnectionEndpoint"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MIDIThruConnectionEndpoint"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionEndpoint"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set the endpoint’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/uniqueID",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to 0 if the endpoint exists and you’re passing its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/endpointRef",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". When retrieving a connection from Core MIDI, its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/endpointRef",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " may be ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " if it doesn’t exist, but the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/uniqueID",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is always non-zero.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionCreate(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a MIDI thru connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIThruConnectionRef",
          "text": "MIDIThruConnectionRef"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionCreate(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionCreate"
        }
      ],
      "role": "symbol",
      "title": "MIDIThruConnectionCreate(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectioncreate(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionDispose(_:)": {
      "abstract": [
        {
          "text": "Disposes a MIDI thru connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionDispose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIThruConnectionRef",
          "text": "MIDIThruConnectionRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionDispose(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionDispose"
        }
      ],
      "role": "symbol",
      "title": "MIDIThruConnectionDispose(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectiondispose(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint": {
      "abstract": [
        {
          "text": "A source or destination in a MIDI thru connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionEndpoint"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionEndpoint"
        }
      ],
      "role": "symbol",
      "title": "MIDIThruConnectionEndpoint",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionendpoint"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/endpointRef": {
      "abstract": [
        {
          "text": "The endpoint reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endpointRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEndpointRef",
          "text": "MIDIEndpointRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/endpointRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endpointRef"
        }
      ],
      "role": "symbol",
      "title": "endpointRef",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionendpoint/endpointref"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionendpoint/init()"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/init(endpointRef:uniqueID:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "endpointRef"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEndpointRef",
          "text": "MIDIEndpointRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "uniqueID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUniqueID",
          "text": "MIDIUniqueID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/init(endpointRef:uniqueID:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(endpointRef:uniqueID:)",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionendpoint/init(endpointref:uniqueid:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/uniqueID": {
      "abstract": [
        {
          "text": "The connection’s unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uniqueID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUniqueID",
          "text": "MIDIUniqueID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/uniqueID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniqueID"
        }
      ],
      "role": "symbol",
      "title": "uniqueID",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionendpoint/uniqueid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionRef": {
      "abstract": [
        {
          "text": "An opaque reference to a play-through connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionRef"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIThruConnectionRef"
        }
      ],
      "role": "symbol",
      "title": "MIDIThruConnectionRef",
      "type": "topic",
      "url": "/documentation/coremidi/midithruconnectionref"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/endpoint-configuration": {
      "abstract": [
        {
          "text": "Values that define the supported endpoint configurations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/endpoint-configuration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Endpoint Configuration",
      "type": "topic",
      "url": "/documentation/coremidi/endpoint-configuration"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Connections",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionCreate(_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionDispose(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionRef",
        "doc://com.apple.coremidi/documentation/CoreMIDI/endpoint-configuration"
      ],
      "title": "Managing Connections"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-an-Endpoint",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/uniqueID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/endpointRef"
      ],
      "title": "Configuring an Endpoint"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/init()",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/init(endpointRef:uniqueID:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MIDIThruConnectionEndpoint"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-an-Endpoint",
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/uniqueID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionEndpoint/endpointRef"
              ],
              "title": "Configuring an Endpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Connections",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionCreate(_:_:_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionDispose(_:)",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIThruConnectionRef",
                "doc://com.apple.coremidi/documentation/CoreMIDI/endpoint-configuration"
              ],
              "title": "Managing Connections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MIDIThruConnectionEndpoint"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionEndpoint~1endpointRef/title",
          "value": "endpointRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionEndpoint~1endpointRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endpointRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionCreate(_:_:_:)/title",
          "value": "MIDIThruConnectionCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionCreate(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionDispose(_:)/title",
          "value": "MIDIThruConnectionDispose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionDispose(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionDispose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionEndpoint/title",
          "value": "MIDIThruConnectionEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionEndpoint~1uniqueID/title",
          "value": "uniqueID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionEndpoint~1uniqueID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uniqueID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionRef/title",
          "value": "MIDIThruConnectionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIThruConnectionRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIThruConnectionRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midithruconnectionendpoint"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midithruconnectionendpoint"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
