{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UMPStreamMessageStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UMPStreamMessageStatus"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UMPStreamMessageStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UMPStreamMessageStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UMPStreamMessageStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICICategoryOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICICategoryOptions"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICICategoryOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICICategoryOptions"
        }
      ],
      "role": "symbol",
      "title": "MIDICICategoryOptions",
      "type": "topic",
      "url": "/documentation/coremidi/midicicategoryoptions"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIDeviceType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIDeviceType"
        }
      ],
      "role": "symbol",
      "title": "MIDICIDeviceType",
      "type": "topic",
      "url": "/documentation/coremidi/midicidevicetype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIManagementMessageType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIManagementMessageType"
        }
      ],
      "role": "symbol",
      "title": "MIDICIManagementMessageType",
      "type": "topic",
      "url": "/documentation/coremidi/midicimanagementmessagetype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProcessInquiryMessageType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProcessInquiryMessageType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProcessInquiryMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProcessInquiryMessageType"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProcessInquiryMessageType",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprocessinquirymessagetype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileMessageType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProfileMessageType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProfileMessageType"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProfileMessageType",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofilemessagetype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIProfileType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIProfileType"
        }
      ],
      "role": "symbol",
      "title": "MIDICIProfileType",
      "type": "topic",
      "url": "/documentation/coremidi/midiciprofiletype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeMessageType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIPropertyExchangeMessageType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIPropertyExchangeMessageType"
        }
      ],
      "role": "symbol",
      "title": "MIDICIPropertyExchangeMessageType",
      "type": "topic",
      "url": "/documentation/coremidi/midicipropertyexchangemessagetype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkConnectionPolicy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDINetworkConnectionPolicy"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkConnectionPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDINetworkConnectionPolicy"
        }
      ],
      "role": "symbol",
      "title": "MIDINetworkConnectionPolicy",
      "type": "topic",
      "url": "/documentation/coremidi/midinetworkconnectionpolicy"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINoteAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDINoteAttribute"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINoteAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDINoteAttribute"
        }
      ],
      "role": "symbol",
      "title": "MIDINoteAttribute",
      "type": "topic",
      "url": "/documentation/coremidi/midinoteattribute"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPerNoteManagementOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIPerNoteManagementOptions"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPerNoteManagementOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIPerNoteManagementOptions"
        }
      ],
      "role": "symbol",
      "title": "MIDIPerNoteManagementOptions",
      "type": "topic",
      "url": "/documentation/coremidi/midipernotemanagementoptions"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProgramChangeOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIProgramChangeOptions"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProgramChangeOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIProgramChangeOptions"
        }
      ],
      "role": "symbol",
      "title": "MIDIProgramChangeOptions",
      "type": "topic",
      "url": "/documentation/coremidi/midiprogramchangeoptions"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPCIObjectBackingType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUMPCIObjectBackingType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPCIObjectBackingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPCIObjectBackingType"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPCIObjectBackingType",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpciobjectbackingtype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockDirection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUMPFunctionBlockDirection"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPFunctionBlockDirection"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPFunctionBlockDirection",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpfunctionblockdirection"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockMIDI1Info": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIUMPFunctionBlockMIDI1Info"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockMIDI1Info",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPFunctionBlockMIDI1Info"
        }
      ],
      "role": "symbol",
      "title": "MIDIUMPFunctionBlockMIDI1Info",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpfunctionblockmidi1info"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UMPStreamMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UMPStreamMessageStatus"
        }
      ],
      "role": "symbol",
      "title": "UMPStreamMessageStatus",
      "type": "topic",
      "url": "/documentation/coremidi/umpstreammessagestatus"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/deviceIdentityNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceIdentityNotification"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/deviceIdentityNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUMPStreamMessageStatusDeviceIdentityNotification"
        }
      ],
      "role": "symbol",
      "title": "UMPStreamMessageStatus.deviceIdentityNotification",
      "type": "topic",
      "url": "/documentation/coremidi/umpstreammessagestatus/deviceidentitynotification"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endOfClip": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endOfClip"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endOfClip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUMPStreamMessageStatusEndOfClip"
        }
      ],
      "role": "symbol",
      "title": "UMPStreamMessageStatus.endOfClip",
      "type": "topic",
      "url": "/documentation/coremidi/umpstreammessagestatus/endofclip"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endpointDiscovery": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endpointDiscovery"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endpointDiscovery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUMPStreamMessageStatusEndpointDiscovery"
        }
      ],
      "role": "symbol",
      "title": "UMPStreamMessageStatus.endpointDiscovery",
      "type": "topic",
      "url": "/documentation/coremidi/umpstreammessagestatus/endpointdiscovery"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endpointInfoNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endpointInfoNotification"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endpointInfoNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUMPStreamMessageStatusEndpointInfoNotification"
        }
      ],
      "role": "symbol",
      "title": "UMPStreamMessageStatus.endpointInfoNotification",
      "type": "topic",
      "url": "/documentation/coremidi/umpstreammessagestatus/endpointinfonotification"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endpointNameNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endpointNameNotification"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endpointNameNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUMPStreamMessageStatusEndpointNameNotification"
        }
      ],
      "role": "symbol",
      "title": "UMPStreamMessageStatus.endpointNameNotification",
      "type": "topic",
      "url": "/documentation/coremidi/umpstreammessagestatus/endpointnamenotification"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/functionBlockDiscovery": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "functionBlockDiscovery"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/functionBlockDiscovery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUMPStreamMessageStatusFunctionBlockDiscovery"
        }
      ],
      "role": "symbol",
      "title": "UMPStreamMessageStatus.functionBlockDiscovery",
      "type": "topic",
      "url": "/documentation/coremidi/umpstreammessagestatus/functionblockdiscovery"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/functionBlockInfoNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "functionBlockInfoNotification"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/functionBlockInfoNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUMPStreamMessageStatusFunctionBlockInfoNotification"
        }
      ],
      "role": "symbol",
      "title": "UMPStreamMessageStatus.functionBlockInfoNotification",
      "type": "topic",
      "url": "/documentation/coremidi/umpstreammessagestatus/functionblockinfonotification"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/functionBlockNameNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "functionBlockNameNotification"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/functionBlockNameNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUMPStreamMessageStatusFunctionBlockNameNotification"
        }
      ],
      "role": "symbol",
      "title": "UMPStreamMessageStatus.functionBlockNameNotification",
      "type": "topic",
      "url": "/documentation/coremidi/umpstreammessagestatus/functionblocknamenotification"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coremidi/umpstreammessagestatus/init(rawvalue:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/productInstanceIDNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productInstanceIDNotification"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/productInstanceIDNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUMPStreamMessageStatusProductInstanceIDNotification"
        }
      ],
      "role": "symbol",
      "title": "UMPStreamMessageStatus.productInstanceIDNotification",
      "type": "topic",
      "url": "/documentation/coremidi/umpstreammessagestatus/productinstanceidnotification"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/startOfClip": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startOfClip"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/startOfClip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUMPStreamMessageStatusStartOfClip"
        }
      ],
      "role": "symbol",
      "title": "UMPStreamMessageStatus.startOfClip",
      "type": "topic",
      "url": "/documentation/coremidi/umpstreammessagestatus/startofclip"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/streamConfigurationNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streamConfigurationNotification"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/streamConfigurationNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUMPStreamMessageStatusStreamConfigurationNotification"
        }
      ],
      "role": "symbol",
      "title": "UMPStreamMessageStatus.streamConfigurationNotification",
      "type": "topic",
      "url": "/documentation/coremidi/umpstreammessagestatus/streamconfigurationnotification"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/streamConfigurationRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streamConfigurationRequest"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/streamConfigurationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kUMPStreamMessageStatusStreamConfigurationRequest"
        }
      ],
      "role": "symbol",
      "title": "UMPStreamMessageStatus.streamConfigurationRequest",
      "type": "topic",
      "url": "/documentation/coremidi/umpstreammessagestatus/streamconfigurationrequest"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidUniqueID": {
      "abstract": [
        {
          "text": "An invalid identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMIDIInvalidUniqueID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUniqueID",
          "text": "MIDIUniqueID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidUniqueID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDIInvalidUniqueID"
        }
      ],
      "role": "symbol",
      "title": "kMIDIInvalidUniqueID",
      "type": "topic",
      "url": "/documentation/coremidi/kmidiinvaliduniqueid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidUniqueID",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICICategoryOptions",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceType",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProcessInquiryMessageType",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileMessageType",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileType",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeMessageType",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkConnectionPolicy",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINoteAttribute",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPerNoteManagementOptions",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProgramChangeOptions",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPCIObjectBackingType",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockDirection",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockMIDI1Info"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/deviceIdentityNotification",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endOfClip",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endpointDiscovery",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endpointInfoNotification",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endpointNameNotification",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/functionBlockDiscovery",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/functionBlockInfoNotification",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/functionBlockNameNotification",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/productInstanceIDNotification",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/startOfClip",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/streamConfigurationNotification",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/streamConfigurationRequest"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UMPStreamMessageStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UMPStreamMessageStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UMPStreamMessageStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/deviceIdentityNotification",
                "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endOfClip",
                "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endpointDiscovery",
                "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endpointInfoNotification",
                "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/endpointNameNotification",
                "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/functionBlockDiscovery",
                "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/functionBlockInfoNotification",
                "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/functionBlockNameNotification",
                "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/productInstanceIDNotification",
                "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/startOfClip",
                "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/streamConfigurationNotification",
                "doc://com.apple.coremidi/documentation/CoreMIDI/UMPStreamMessageStatus/streamConfigurationRequest"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIInvalidUniqueID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICICategoryOptions",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIDeviceType",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIManagementMessageType",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProcessInquiryMessageType",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileMessageType",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIProfileType",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeMessageType",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINetworkConnectionPolicy",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINoteAttribute",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIPerNoteManagementOptions",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIProgramChangeOptions",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPCIObjectBackingType",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockDirection",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPFunctionBlockMIDI1Info"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UMPStreamMessageStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:i",
                    "text": "unsigned int"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1productInstanceIDNotification/title",
          "value": "kUMPStreamMessageStatusProductInstanceIDNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1productInstanceIDNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUMPStreamMessageStatusProductInstanceIDNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockDirection/title",
          "value": "MIDIUMPFunctionBlockDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPFunctionBlockDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPFunctionBlockDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1deviceIdentityNotification/title",
          "value": "kUMPStreamMessageStatusDeviceIdentityNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1deviceIdentityNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUMPStreamMessageStatusDeviceIdentityNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINoteAttribute/title",
          "value": "MIDINoteAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINoteAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINoteAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINoteAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINoteAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceType/title",
          "value": "MIDICIDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIDeviceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIDeviceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1endpointDiscovery/title",
          "value": "kUMPStreamMessageStatusEndpointDiscovery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1endpointDiscovery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUMPStreamMessageStatusEndpointDiscovery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1startOfClip/title",
          "value": "kUMPStreamMessageStatusStartOfClip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1startOfClip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUMPStreamMessageStatusStartOfClip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType/title",
          "value": "MIDICIManagementMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIManagementMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIManagementMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIManagementMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProgramChangeOptions/title",
          "value": "MIDIProgramChangeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProgramChangeOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIProgramChangeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIProgramChangeOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIProgramChangeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1functionBlockNameNotification/title",
          "value": "kUMPStreamMessageStatusFunctionBlockNameNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1functionBlockNameNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUMPStreamMessageStatusFunctionBlockNameNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1streamConfigurationNotification/title",
          "value": "kUMPStreamMessageStatusStreamConfigurationNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1streamConfigurationNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUMPStreamMessageStatusStreamConfigurationNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileType/title",
          "value": "MIDICIProfileType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIPerNoteManagementOptions/title",
          "value": "MIDIPerNoteManagementOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIPerNoteManagementOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIPerNoteManagementOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIPerNoteManagementOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIPerNoteManagementOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1streamConfigurationRequest/title",
          "value": "kUMPStreamMessageStatusStreamConfigurationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1streamConfigurationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUMPStreamMessageStatusStreamConfigurationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockMIDI1Info/title",
          "value": "MIDIUMPFunctionBlockMIDI1Info"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockMIDI1Info/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPFunctionBlockMIDI1Info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPFunctionBlockMIDI1Info/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPFunctionBlockMIDI1Info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1endOfClip/title",
          "value": "kUMPStreamMessageStatusEndOfClip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1endOfClip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUMPStreamMessageStatusEndOfClip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1functionBlockDiscovery/title",
          "value": "kUMPStreamMessageStatusFunctionBlockDiscovery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1functionBlockDiscovery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUMPStreamMessageStatusFunctionBlockDiscovery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIInvalidUniqueID/title",
          "value": "kMIDIInvalidUniqueID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1kMIDIInvalidUniqueID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDIInvalidUniqueID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIPropertyExchangeMessageType/title",
          "value": "MIDICIPropertyExchangeMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIPropertyExchangeMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIPropertyExchangeMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIPropertyExchangeMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIPropertyExchangeMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1functionBlockInfoNotification/title",
          "value": "kUMPStreamMessageStatusFunctionBlockInfoNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1functionBlockInfoNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUMPStreamMessageStatusFunctionBlockInfoNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus/title",
          "value": "UMPStreamMessageStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UMPStreamMessageStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UMPStreamMessageStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileMessageType/title",
          "value": "MIDICIProfileMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProfileMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProfileMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1endpointNameNotification/title",
          "value": "kUMPStreamMessageStatusEndpointNameNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1endpointNameNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUMPStreamMessageStatusEndpointNameNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICICategoryOptions/title",
          "value": "MIDICICategoryOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICICategoryOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICICategoryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICICategoryOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICICategoryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPCIObjectBackingType/title",
          "value": "MIDIUMPCIObjectBackingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPCIObjectBackingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPCIObjectBackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPCIObjectBackingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPCIObjectBackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINetworkConnectionPolicy/title",
          "value": "MIDINetworkConnectionPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINetworkConnectionPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINetworkConnectionPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDINetworkConnectionPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDINetworkConnectionPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProcessInquiryMessageType/title",
          "value": "MIDICIProcessInquiryMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProcessInquiryMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProcessInquiryMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIProcessInquiryMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIProcessInquiryMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1endpointInfoNotification/title",
          "value": "kUMPStreamMessageStatusEndpointInfoNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1UMPStreamMessageStatus~1endpointInfoNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kUMPStreamMessageStatusEndpointInfoNotification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/umpstreammessagestatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/umpstreammessagestatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
