{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:8CoreMIDI33UnsafeMutableMIDIEventListPointerV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UnsafeMutableMIDIEventListPointer"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UnsafeMutableMIDIEventListPointer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UnsafeMutableMIDIEventListPointer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UnsafeMutableMIDIEventListPointer"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventList": {
      "abstract": [
        {
          "text": "A variable-length list of MIDI event packets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIEventList"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIEventList"
        }
      ],
      "role": "symbol",
      "title": "MIDIEventList",
      "type": "topic",
      "url": "/documentation/coremidi/midieventlist"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventListAdd(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Adds an event to an event list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIEventListAdd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIEventList",
          "text": "MIDIEventList"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIEventPacket",
          "text": "MIDIEventPacket"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDITimeStamp",
          "text": "MIDITimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIEventPacket",
          "text": "MIDIEventPacket"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventListAdd(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIEventListAdd"
        }
      ],
      "role": "symbol",
      "title": "MIDIEventListAdd(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midieventlistadd(_:_:_:_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventListInit(_:_:)": {
      "abstract": [
        {
          "text": "Initializes an event list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIEventListInit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIEventList",
          "text": "MIDIEventList"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MIDIProtocolID",
          "text": "MIDIProtocolID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIEventPacket",
          "text": "MIDIEventPacket"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventListInit(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIEventListInit"
        }
      ],
      "role": "symbol",
      "title": "MIDIEventListInit(_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midieventlistinit(_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventPacket": {
      "abstract": [
        {
          "text": "A series of simultaneous MIDI events in Universal MIDI Packets (UMP) format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIEventPacket"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventPacket",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIEventPacket"
        }
      ],
      "role": "symbol",
      "title": "MIDIEventPacket",
      "type": "topic",
      "url": "/documentation/coremidi/midieventpacket"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventPacketNext(_:)": {
      "abstract": [
        {
          "text": "Advances a packet pointer to the next packet in memory, if the packet is part of an event list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIEventPacketNext"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIEventPacket",
          "text": "MIDIEventPacket"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIEventPacket",
          "text": "MIDIEventPacket"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventPacketNext(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIEventPacketNext"
        }
      ],
      "role": "symbol",
      "title": "MIDIEventPacketNext(_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midieventpacketnext(_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIReceivedEventList(_:_:)": {
      "abstract": [
        {
          "text": "Distributes incoming MIDI events from a source to its connected client input ports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDIReceivedEventList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEndpointRef",
          "text": "MIDIEndpointRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIEventList",
          "text": "MIDIEventList"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIReceivedEventList(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIReceivedEventList"
        }
      ],
      "role": "symbol",
      "title": "MIDIReceivedEventList(_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midireceivedeventlist(_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISendEventList(_:_:_:)": {
      "abstract": [
        {
          "text": "Sends MIDI events to a destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDISendEventList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIPortRef",
          "text": "MIDIPortRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIEndpointRef",
          "text": "MIDIEndpointRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIEventList",
          "text": "MIDIEventList"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISendEventList(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDISendEventList"
        }
      ],
      "role": "symbol",
      "title": "MIDISendEventList(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coremidi/midisendeventlist(_:_:_:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableMIDIEventListPointer"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UnsafeMutableMIDIEventListPointer"
        }
      ],
      "role": "symbol",
      "title": "UnsafeMutableMIDIEventListPointer",
      "type": "topic",
      "url": "/documentation/coremidi/unsafemutablemidieventlistpointer"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/append(timestamp:words:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "append"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "timestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDITimeStamp",
          "text": "MIDITimeStamp"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "words"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIEventPacket",
          "text": "MIDIEventPacket"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/append(timestamp:words:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "append(timestamp:words:)",
      "type": "topic",
      "url": "/documentation/coremidi/unsafemutablemidieventlistpointer/append(timestamp:words:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/clear()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clear"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/clear()",
      "kind": "symbol",
      "role": "symbol",
      "title": "clear()",
      "type": "topic",
      "url": "/documentation/coremidi/unsafemutablemidieventlistpointer/clear()"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/count": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/count",
      "kind": "symbol",
      "role": "symbol",
      "title": "count",
      "type": "topic",
      "url": "/documentation/coremidi/unsafemutablemidieventlistpointer/count"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/init(_:wordSize:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIEventList",
          "text": "MIDIEventList"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "wordSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/init(_:wordSize:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:wordSize:)",
      "type": "topic",
      "url": "/documentation/coremidi/unsafemutablemidieventlistpointer/init(_:wordsize:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/init(_:wordSize:inProtocol:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIEventList",
          "text": "MIDIEventList"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "wordSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inProtocol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MIDIProtocolID",
          "text": "MIDIProtocolID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/init(_:wordSize:inProtocol:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:wordSize:inProtocol:)",
      "type": "topic",
      "url": "/documentation/coremidi/unsafemutablemidieventlistpointer/init(_:wordsize:inprotocol:)"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/lastPacket": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastPacket"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@MIDIEventPacket",
          "text": "MIDIEventPacket"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/lastPacket",
      "kind": "symbol",
      "role": "symbol",
      "title": "lastPacket",
      "type": "topic",
      "url": "/documentation/coremidi/unsafemutablemidieventlistpointer/lastpacket"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/listSizeInBytes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "listSizeInBytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/listSizeInBytes",
      "kind": "symbol",
      "role": "symbol",
      "title": "listSizeInBytes",
      "type": "topic",
      "url": "/documentation/coremidi/unsafemutablemidieventlistpointer/listsizeinbytes"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/midiProtocol": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "midiProtocol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MIDIProtocolID",
          "text": "MIDIProtocolID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/midiProtocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "midiProtocol",
      "type": "topic",
      "url": "/documentation/coremidi/unsafemutablemidieventlistpointer/midiprotocol"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventPacketPointer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableMIDIEventPacketPointer"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventPacketPointer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UnsafeMutableMIDIEventPacketPointer"
        }
      ],
      "role": "symbol",
      "title": "UnsafeMutableMIDIEventPacketPointer",
      "type": "topic",
      "url": "/documentation/coremidi/unsafemutablemidieventpacketpointer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ST": {
      "abstract": [
        {
          "text": "A type that provides sequential, iterated access to its elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sequence"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ST7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ST",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sequence",
      "type": "topic",
      "url": "/documentation/Swift/Sequence"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:ST"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Event-list-management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventListInit(_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventListAdd(_:_:_:_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventPacketNext(_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDISendEventList(_:_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIReceivedEventList(_:_:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventList",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIEventPacket",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventPacketPointer"
      ],
      "title": "Event list management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/init(_:wordSize:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/init(_:wordSize:inProtocol:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/count",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/lastPacket",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/listSizeInBytes",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/midiProtocol"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/append(timestamp:words:)",
        "doc://com.apple.coremidi/documentation/CoreMIDI/UnsafeMutableMIDIEventListPointer/clear()"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventPacket/title",
          "value": "MIDIEventPacket"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventPacket/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIEventPacket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventPacket/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIEventPacket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventListAdd(_:_:_:_:_:_:)/title",
          "value": "MIDIEventListAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventListAdd(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIEventListAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventListInit(_:_:)/title",
          "value": "MIDIEventListInit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventListInit(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIEventListInit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIReceivedEventList(_:_:)/title",
          "value": "MIDIReceivedEventList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIReceivedEventList(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIReceivedEventList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventPacketNext(_:)/title",
          "value": "MIDIEventPacketNext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventPacketNext(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIEventPacketNext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISendEventList(_:_:_:)/title",
          "value": "MIDISendEventList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDISendEventList(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDISendEventList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventList/title",
          "value": "MIDIEventList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIEventList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIEventList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIEventList"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/unsafemutablemidieventlistpointer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
