{
  "abstract": [
    {
      "text": "Do not start the VPN connection, and disconnect the VPN connection if it is not currently disconnected.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/disconnect"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEOnDemandRuleAction@NEOnDemandRuleActionDisconnect",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "disconnect"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEOnDemandRuleActionDisconnect"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NEOnDemandRuleAction.disconnect"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "disconnect"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEOnDemandRuleAction"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEOnDemandRuleAction"
        }
      ],
      "role": "symbol",
      "title": "NEOnDemandRuleAction",
      "type": "topic",
      "url": "/documentation/networkextension/neondemandruleaction"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/connect": {
      "abstract": [
        {
          "text": "Start the VPN connection for every connection attempt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connect"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/connect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEOnDemandRuleActionConnect"
        }
      ],
      "role": "symbol",
      "title": "NEOnDemandRuleAction.connect",
      "type": "topic",
      "url": "/documentation/networkextension/neondemandruleaction/connect"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/disconnect": {
      "abstract": [
        {
          "text": "Do not start the VPN connection, and disconnect the VPN connection if it is not currently disconnected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disconnect"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/disconnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEOnDemandRuleActionDisconnect"
        }
      ],
      "role": "symbol",
      "title": "NEOnDemandRuleAction.disconnect",
      "type": "topic",
      "url": "/documentation/networkextension/neondemandruleaction/disconnect"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/evaluateConnection": {
      "abstract": [
        {
          "text": "Start the VPN after evaluating the destination host being accessed against the rule’s parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluateConnection"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/evaluateConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEOnDemandRuleActionEvaluateConnection"
        }
      ],
      "role": "symbol",
      "title": "NEOnDemandRuleAction.evaluateConnection",
      "type": "topic",
      "url": "/documentation/networkextension/neondemandruleaction/evaluateconnection"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/ignore": {
      "abstract": [
        {
          "text": "Do not start the VPN connection, but do not disconnect it if it is currently connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ignore"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/ignore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEOnDemandRuleActionIgnore"
        }
      ],
      "role": "symbol",
      "title": "NEOnDemandRuleAction.ignore",
      "type": "topic",
      "url": "/documentation/networkextension/neondemandruleaction/ignore"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Rule-Actions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/connect",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/evaluateConnection",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/ignore"
      ],
      "title": "Rule Actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEOnDemandRuleActionDisconnect"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEOnDemandRuleActionDisconnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Rule-Actions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/connect",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/evaluateConnection",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleAction/ignore"
              ],
              "title": "Rule Actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NEOnDemandRuleActionDisconnect"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction~1evaluateConnection/title",
          "value": "NEOnDemandRuleActionEvaluateConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction~1evaluateConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEOnDemandRuleActionEvaluateConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction~1disconnect/title",
          "value": "NEOnDemandRuleActionDisconnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction~1disconnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEOnDemandRuleActionDisconnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction~1ignore/title",
          "value": "NEOnDemandRuleActionIgnore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction~1ignore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEOnDemandRuleActionIgnore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction/title",
          "value": "NEOnDemandRuleAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEOnDemandRuleAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEOnDemandRuleAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction~1connect/title",
          "value": "NEOnDemandRuleActionConnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleAction~1connect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEOnDemandRuleActionConnect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/neondemandruleaction/disconnect"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/neondemandruleaction/disconnect"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
