{
  "abstract": [
    {
      "text": "A type of text that represents a sentence.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/sentence"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVSpeechSynthesisMarkerMark@AVSpeechSynthesisMarkerMarkSentence",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sentence"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVSpeechSynthesisMarkerMarkSentence"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVSpeechSynthesisMarker.Mark.sentence"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sentence"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker": {
      "abstract": [
        {
          "text": "An object that contains information about the synthesized audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisMarker"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisMarker"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisMarker",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesismarker"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the type of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Mark"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Mark"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisMarker.Mark",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesismarker/mark-swift.enum"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/bookmark": {
      "abstract": [
        {
          "text": "A Speech Synthesis Markup Language (SSML) mark tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bookmark"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/bookmark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisMarkerMarkBookmark"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisMarker.Mark.bookmark",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesismarker/mark-swift.enum/bookmark"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/paragraph": {
      "abstract": [
        {
          "text": "A type of text that represents a paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paragraph"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/paragraph",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisMarkerMarkParagraph"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisMarker.Mark.paragraph",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesismarker/mark-swift.enum/paragraph"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/phoneme": {
      "abstract": [
        {
          "text": "A type of text that represents a phoneme.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phoneme"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/phoneme",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisMarkerMarkPhoneme"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisMarker.Mark.phoneme",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesismarker/mark-swift.enum/phoneme"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/sentence": {
      "abstract": [
        {
          "text": "A type of text that represents a sentence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sentence"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/sentence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisMarkerMarkSentence"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisMarker.Mark.sentence",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesismarker/mark-swift.enum/sentence"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/word": {
      "abstract": [
        {
          "text": "A type of text that represents a word.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "word"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/word",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSpeechSynthesisMarkerMarkWord"
        }
      ],
      "role": "symbol",
      "title": "AVSpeechSynthesisMarker.Mark.word",
      "type": "topic",
      "url": "/documentation/avfaudio/avspeechsynthesismarker/mark-swift.enum/word"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Marks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/word",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/paragraph",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/phoneme",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/bookmark"
      ],
      "title": "Marks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVSpeechSynthesisMarkerMarkSentence"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisMarkerMarkSentence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Marks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/word",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/paragraph",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/phoneme",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVSpeechSynthesisMarker/Mark-swift.enum/bookmark"
              ],
              "title": "Marks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVSpeechSynthesisMarkerMarkSentence"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker~1Mark-swift.enum~1word/title",
          "value": "AVSpeechSynthesisMarkerMarkWord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker~1Mark-swift.enum~1word/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisMarkerMarkWord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker~1Mark-swift.enum~1paragraph/title",
          "value": "AVSpeechSynthesisMarkerMarkParagraph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker~1Mark-swift.enum~1paragraph/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisMarkerMarkParagraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker~1Mark-swift.enum~1phoneme/title",
          "value": "AVSpeechSynthesisMarkerMarkPhoneme"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker~1Mark-swift.enum~1phoneme/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisMarkerMarkPhoneme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker~1Mark-swift.enum~1bookmark/title",
          "value": "AVSpeechSynthesisMarkerMarkBookmark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker~1Mark-swift.enum~1bookmark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisMarkerMarkBookmark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker~1Mark-swift.enum/title",
          "value": "AVSpeechSynthesisMarkerMark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker~1Mark-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisMarkerMark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker~1Mark-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisMarkerMark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker/title",
          "value": "AVSpeechSynthesisMarker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisMarker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker~1Mark-swift.enum~1sentence/title",
          "value": "AVSpeechSynthesisMarkerMarkSentence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVSpeechSynthesisMarker~1Mark-swift.enum~1sentence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSpeechSynthesisMarkerMarkSentence"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avspeechsynthesismarker/mark-swift.enum/sentence"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avspeechsynthesismarker/mark-swift.enum/sentence"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
