{
  "abstract": [
    {
      "text": "An option to detect strings with the format of a flight number from an airline.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/flightNumber"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIDataDetectorTypes@UIDataDetectorTypeFlightNumber",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "flightNumber"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIDataDetectorTypes",
        "text": "UIDataDetectorTypes"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIDataDetectorTypeFlightNumber"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "flightNumber"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "flightNumber"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIDataDetectorTypes",
              "text": "UIDataDetectorTypes"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes": {
      "abstract": [
        {
          "text": "Constants that define the types of information to detect in text-based content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataDetectorTypes"
        }
      ],
      "role": "symbol",
      "title": "UIDataDetectorTypes",
      "type": "topic",
      "url": "/documentation/uikit/uidatadetectortypes"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/UIDataDetectorTypeNone": {
      "abstract": [
        {
          "text": "An option to do no data detection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIDataDetectorTypeNone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/UIDataDetectorTypeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIDataDetectorTypeNone",
      "type": "topic",
      "url": "/documentation/uikit/uidatadetectortypes/uidatadetectortypenone"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/address": {
      "abstract": [
        {
          "text": "An option to detect strings with the format of an address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "address"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDataDetectorTypes",
          "text": "UIDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/address",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataDetectorTypeAddress"
        }
      ],
      "role": "symbol",
      "title": "address",
      "type": "topic",
      "url": "/documentation/uikit/uidatadetectortypes/address"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/all": {
      "abstract": [
        {
          "text": "An option to detect all available types of data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDataDetectorTypes",
          "text": "UIDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataDetectorTypeAll"
        }
      ],
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/uikit/uidatadetectortypes/all"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/calendarEvent": {
      "abstract": [
        {
          "text": "An option to detect strings with the format of a calendar event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDataDetectorTypes",
          "text": "UIDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/calendarEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataDetectorTypeCalendarEvent"
        }
      ],
      "role": "symbol",
      "title": "calendarEvent",
      "type": "topic",
      "url": "/documentation/uikit/uidatadetectortypes/calendarevent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/flightNumber": {
      "abstract": [
        {
          "text": "An option to detect strings with the format of a flight number from an airline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flightNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDataDetectorTypes",
          "text": "UIDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/flightNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataDetectorTypeFlightNumber"
        }
      ],
      "role": "symbol",
      "title": "flightNumber",
      "type": "topic",
      "url": "/documentation/uikit/uidatadetectortypes/flightnumber"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/link": {
      "abstract": [
        {
          "text": "An option to detect strings with the format of a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "link"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDataDetectorTypes",
          "text": "UIDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/link",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataDetectorTypeLink"
        }
      ],
      "role": "symbol",
      "title": "link",
      "type": "topic",
      "url": "/documentation/uikit/uidatadetectortypes/link"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/lookupSuggestion": {
      "abstract": [
        {
          "text": "An option to detect strings with the format of information that a person might want to look up.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lookupSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDataDetectorTypes",
          "text": "UIDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/lookupSuggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataDetectorTypeLookupSuggestion"
        }
      ],
      "role": "symbol",
      "title": "lookupSuggestion",
      "type": "topic",
      "url": "/documentation/uikit/uidatadetectortypes/lookupsuggestion"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/money": {
      "abstract": [
        {
          "text": "An option to detect strings with the format of an amount of money.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "money"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDataDetectorTypes",
          "text": "UIDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/money",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataDetectorTypeMoney"
        }
      ],
      "role": "symbol",
      "title": "money",
      "type": "topic",
      "url": "/documentation/uikit/uidatadetectortypes/money"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/phoneNumber": {
      "abstract": [
        {
          "text": "An option to detect strings with the format of a phone number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phoneNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDataDetectorTypes",
          "text": "UIDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/phoneNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataDetectorTypePhoneNumber"
        }
      ],
      "role": "symbol",
      "title": "phoneNumber",
      "type": "topic",
      "url": "/documentation/uikit/uidatadetectortypes/phonenumber"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/physicalValue": {
      "abstract": [
        {
          "text": "An option to detect strings with the format of a physical value, such as length or temperature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "physicalValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDataDetectorTypes",
          "text": "UIDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/physicalValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataDetectorTypePhysicalValue"
        }
      ],
      "role": "symbol",
      "title": "physicalValue",
      "type": "topic",
      "url": "/documentation/uikit/uidatadetectortypes/physicalvalue"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/shipmentTrackingNumber": {
      "abstract": [
        {
          "text": "An option to detect strings with the format of a tracking number from a package delivery company.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shipmentTrackingNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDataDetectorTypes",
          "text": "UIDataDetectorTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/shipmentTrackingNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataDetectorTypeShipmentTrackingNumber"
        }
      ],
      "role": "symbol",
      "title": "shipmentTrackingNumber",
      "type": "topic",
      "url": "/documentation/uikit/uidatadetectortypes/shipmenttrackingnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/phoneNumber",
        "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/link",
        "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/address",
        "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/calendarEvent",
        "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/shipmentTrackingNumber",
        "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/lookupSuggestion",
        "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/money",
        "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/physicalValue",
        "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/all"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIDataDetectorTypeFlightNumber"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataDetectorTypeFlightNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/phoneNumber",
                "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/link",
                "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/address",
                "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/calendarEvent",
                "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/shipmentTrackingNumber",
                "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/lookupSuggestion",
                "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/money",
                "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/physicalValue",
                "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/UIDataDetectorTypeNone",
                "doc://com.apple.uikit/documentation/UIKit/UIDataDetectorTypes/all"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIDataDetectorTypeFlightNumber"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1phoneNumber/title",
          "value": "UIDataDetectorTypePhoneNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1phoneNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataDetectorTypePhoneNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1link/title",
          "value": "UIDataDetectorTypeLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1link/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataDetectorTypeLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1flightNumber/title",
          "value": "UIDataDetectorTypeFlightNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1flightNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataDetectorTypeFlightNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1lookupSuggestion/title",
          "value": "UIDataDetectorTypeLookupSuggestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1lookupSuggestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataDetectorTypeLookupSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes/title",
          "value": "UIDataDetectorTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataDetectorTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataDetectorTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1shipmentTrackingNumber/title",
          "value": "UIDataDetectorTypeShipmentTrackingNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1shipmentTrackingNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataDetectorTypeShipmentTrackingNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1physicalValue/title",
          "value": "UIDataDetectorTypePhysicalValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1physicalValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataDetectorTypePhysicalValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1address/title",
          "value": "UIDataDetectorTypeAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1address/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataDetectorTypeAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1all/title",
          "value": "UIDataDetectorTypeAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataDetectorTypeAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1calendarEvent/title",
          "value": "UIDataDetectorTypeCalendarEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1calendarEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataDetectorTypeCalendarEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1money/title",
          "value": "UIDataDetectorTypeMoney"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataDetectorTypes~1money/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataDetectorTypeMoney"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uidatadetectortypes/flightnumber"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uidatadetectortypes/flightnumber"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
