{
  "abstract": [
    {
      "text": "Securely authenticate users and create accounts for them in your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.signinwithapple/documentation/SigninwithApple",
        "doc://com.apple.signinwithapple/documentation/SigninwithAppleRESTAPI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "data",
    "url": "doc://com.apple.signinwithapple/documentation/sign_in_with_apple/authenticating-users-with-sign-in-with-apple"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Sign in with Apple REST API"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Authenticating users with Sign in with Apple"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Sign in with Apple lets users log in to your app across all of your platforms using their two-factor authentication Apple ID. After the user chooses to use Sign in with Apple to log in, your app receives tokens and user information that you can verify from a server.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When the user attempts to sign in using Sign in with Apple, the sequence in the following diagram begins:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3635395",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You may group apps in your developer account for Sign in with Apple so an app only requests information the first time the user logs in. A simple confirmation to continue appears even if the app bundle IDs are different across systems, such as iOS, macOS, and the web.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Authenticate-the-user-and-request-information",
          "level": 3,
          "text": "Authenticate the user and request information",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Initialize an authentication session with your app server and associate a client session with an ID token using the ",
              "type": "text"
            },
            {
              "code": "nonce",
              "type": "codeVoice"
            },
            {
              "text": " value. You can request to receive the user’s information, such as name and email address. If the user approves accessing this information, your authorization request includes the requested information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Sign in with Apple protects user accounts by using two-factor authentication. Users that log in to an Apple device can quickly sign in to your app in the following ways:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "With Face ID or Touch ID on passcode-protected devices",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "With a passcode, if Touch ID or Face ID isn’t available",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "With an Apple ID password, if the passcode isn’t set",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Native apps only allow the signed-in iCloud user to use Sign in with Apple. Web-based interactions allow logins using any Apple ID.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "On non-Apple devices, users must log in with their Apple ID, password, and two-factor authentication code.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Apple determines whether a user is a real person by combining on-device machine learning, account history, and hardware attestation using privacy-preserving mechanisms. There are three possible values when determining whether a user is a real person:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The user appears to be a real person, and you can treat this account as a valid user. You can skip any additional fraud verification checks or CAPTCHAs that your app normally uses. For more information, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASUserDetectionStatus/likelyReal",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "2",
                    "type": "codeVoice"
                  },
                  {
                    "text": " (or ",
                    "type": "text"
                  },
                  {
                    "code": "LikelyReal",
                    "type": "codeVoice"
                  },
                  {
                    "text": ")",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The system can’t determine whether the user is a real person. The server may return this value if status determination takes too long. Treat this user as any other account with limited information that requires additional verification steps. Don’t block service, because the user may be a real person. For more information, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASUserDetectionStatus/unknown",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "1",
                    "type": "codeVoice"
                  },
                  {
                    "text": " (or ",
                    "type": "text"
                  },
                  {
                    "code": "Unknown",
                    "type": "codeVoice"
                  },
                  {
                    "text": ")",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Real user status is only available in iOS 14 and later, macOS 11 and later, watchOS 7 and later, and tvOS 14 and later. Previous versions of iOS, macOS, watchOS, tvOS return ",
                        "type": "text"
                      },
                      {
                        "code": "Unsupported",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". For more information, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASUserDetectionStatus/unsupported",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "0",
                    "type": "codeVoice"
                  },
                  {
                    "text": " (or ",
                    "type": "text"
                  },
                  {
                    "code": "Unsupported",
                    "type": "codeVoice"
                  },
                  {
                    "text": ")",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "This system for detecting whether the user is real is tuned for high-precision and moderate recall time. You may also use it as a feature in your own machine-learning models for detecting account fraud.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When someone uses your app and Sign in with Apple for the first time, the identification servers return the user status. Subsequent attempts don’t return the user status.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After the user logs in to your app using Sign in with Apple on one of their devices, they can sign in on all of their devices. Deleting your app from a device doesn’t affect this capability. If the user reinstalls your app, they can continue to use Sign in with Apple on any of their devices to sign in with their existing account.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Retrieve-the-users-information-from-Apple-ID-servers",
          "level": 3,
          "text": "Retrieve the user’s information from Apple ID servers",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The information you retrieve must include the credentials required to verify the user’s identity. The server returns the credentials and user information based on the initial request. The information that returns can include user identity, full name, verified email address, and real user status.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After successfully authenticating the user, the server returns an identity token, authorization code, and user identifier to your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The identity token is a JSON Web Token (JWT) and contains the following claims:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The issuer registered claim identifies the principal that issues the identity token. Because Apple generates the token, the value is ",
                        "type": "text"
                      },
                      {
                        "code": "https://appleid.apple.com",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "iss",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The subject registered claim identifies the principal that’s the subject of the identity token. Because this token is for your app, the value is the unique identifier for the user.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "sub",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The audience registered claim identifies the recipient of the identity token. Because the token is for your app, the value is the ",
                        "type": "text"
                      },
                      {
                        "code": "client_id",
                        "type": "codeVoice"
                      },
                      {
                        "text": " from your developer account.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "aud",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The issued at registered claim indicates the time that Apple issues the identity token, in the number of seconds since the Unix epoch in UTC.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "iat",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The expiration time registered claim identifies the time that the identity token expires, in the number of seconds since the Unix epoch in UTC. The value must be greater than the current date and time when verifying the token.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "exp",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string for associating a client session with the identity token. This value mitigates replay attacks and is present only if you pass it in the authorization request.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "nonce",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A Boolean value that indicates whether the transaction is on a nonce-supported platform. If you send a nonce in the authorization request, but don’t see the nonce claim in the identity token, check this claim to determine how to proceed. If this claim returns true, treat nonce as mandatory and fail the transaction; otherwise, you can proceed treating the nonce as optional.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "nonce_supported",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string value that represents the user’s email address. The email address is either the user’s real email address or the proxy address, depending on their private email relay service. This value may be empty for Sign in with Apple at Work & School users. For example, younger students may not have an email address.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "email",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string or Boolean value that indicates whether the service verifies the email. The value can either be a string (",
                        "type": "text"
                      },
                      {
                        "code": "\"true\" or \"false\"",
                        "type": "codeVoice"
                      },
                      {
                        "text": ") or a Boolean (",
                        "type": "text"
                      },
                      {
                        "code": "true",
                        "type": "codeVoice"
                      },
                      {
                        "text": " or ",
                        "type": "text"
                      },
                      {
                        "code": "false",
                        "type": "codeVoice"
                      },
                      {
                        "text": "). The system may not verify email addresses for Sign in with Apple at Work & School users, and this claim is ",
                        "type": "text"
                      },
                      {
                        "code": "\"false\"",
                        "type": "codeVoice"
                      },
                      {
                        "text": " or ",
                        "type": "text"
                      },
                      {
                        "code": "false",
                        "type": "codeVoice"
                      },
                      {
                        "text": " for those users.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "email_verified",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string or Boolean value that indicates whether the email that the user shares is the proxy address. The value can either be a string (",
                        "type": "text"
                      },
                      {
                        "code": "\"true\"",
                        "type": "codeVoice"
                      },
                      {
                        "text": " or ",
                        "type": "text"
                      },
                      {
                        "code": "\"false\"",
                        "type": "codeVoice"
                      },
                      {
                        "text": ") or a Boolean (",
                        "type": "text"
                      },
                      {
                        "code": "true",
                        "type": "codeVoice"
                      },
                      {
                        "text": " or ",
                        "type": "text"
                      },
                      {
                        "code": "false",
                        "type": "codeVoice"
                      },
                      {
                        "text": ").",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "is_private_email",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An Integer value that indicates whether the user appears to be a real person. Use the value of this claim to mitigate fraud. The possible values are: ",
                        "type": "text"
                      },
                      {
                        "code": "0",
                        "type": "codeVoice"
                      },
                      {
                        "text": " (or ",
                        "type": "text"
                      },
                      {
                        "code": "Unsupported",
                        "type": "codeVoice"
                      },
                      {
                        "text": "), ",
                        "type": "text"
                      },
                      {
                        "code": "1",
                        "type": "codeVoice"
                      },
                      {
                        "text": " (or ",
                        "type": "text"
                      },
                      {
                        "code": "Unknown",
                        "type": "codeVoice"
                      },
                      {
                        "text": "), ",
                        "type": "text"
                      },
                      {
                        "code": "2",
                        "type": "codeVoice"
                      },
                      {
                        "text": " (or ",
                        "type": "text"
                      },
                      {
                        "code": "LikelyReal",
                        "type": "codeVoice"
                      },
                      {
                        "text": "). For more information, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASUserDetectionStatus",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". This claim is present only in iOS 14 and later, macOS 11 and later, watchOS 7 and later, tvOS 14 and later. The claim isn’t present or supported for web-based apps.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "real_user_status",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string value that represents the transfer identifier for migrating users to your team. This claim is present only during the 60-day transfer period after you transfer an app. For more information, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.signinwithapple/documentation/sign_in_with_apple/bringing-new-apps-and-users-into-your-team",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "transfer_sub",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If the user signs in with a managed Apple ID, the value of the ",
                  "type": "text"
                },
                {
                  "code": "email",
                  "type": "codeVoice"
                },
                {
                  "text": " claim is a real email address, not a proxy address. Alternatively, if the managed Apple ID is in Apple School Manager, the ",
                  "type": "text"
                },
                {
                  "code": "email",
                  "type": "codeVoice"
                },
                {
                  "text": " claim may be empty. Students, for example, often don’t have an email that the school issues.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Use the authorization code to verify the token claims with Apple servers, and exchange them for refresh tokens. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.signinwithapple/documentation/SigninwithAppleRESTAPI/Generate-and-validate-tokens",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The user identifier has the following characteristics:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Consists of a unique, stable string, and serves as the primary identifier of the user",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Uses the same identifier across all of the apps in the development team associated with your Apple Developer account",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Differs for the same user across different development teams, and can’t identify a user across development teams",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Doesn’t change if the user stops using Sign in with Apple with your app and later starts using it again",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Typically stores alongside the user’s primary key in your database",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Use the user identifier instead of an email address to identify the user. If you request the user’s full name, Sign in with Apple collects the information to pass along to your app. The name defaults to the user’s name from their Apple ID, but the user can change their name.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Apple doesn’t receive the user’s full name shared with the system UI. The raw data is passed directly to your app from the browser and is not included in the user’s identity token. To help prevent cross-site scripting attacks, validate and sanitize the user-submitted first and last name values before storing on your app servers.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "If you request the user’s verified email address, Sign in with Apple prompts the user to share it with your app. The user may choose to share their real email address or an anonymous one that uses the private email relay service. In both cases, Apple verifies that the email address works and is ready for use.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.signinwithapple/documentation/sign_in_with_apple/communicating-using-the-private-email-relay-service",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Send-information-to-app-servers-and-verify-tokens",
          "level": 3,
          "text": "Send information to app servers and verify tokens",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Ensure that your app relays the credentials and user information to your app servers. The API collects this information and shares it with your app the first time the user logs in using Sign in with Apple. If the user then uses Sign in with Apple on another device, the API doesn’t ask for the user’s name or email again. It collects the information again only if the user stops using Sign in with Apple and later reconnects to your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Although Apple provides the user’s email address in the identity token on all subsequent API responses, it doesn’t include other information about the user, such as their name. When you receive user information from the API response, immediately store it locally so your app can access it again in the event of a process or network failure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Your app servers verify the validity of the token credentials with Apple ID servers. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.signinwithapple/documentation/sign_in_with_apple/verifying-a-user",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Prevent-duplicate-accounts",
          "level": 3,
          "text": "Prevent duplicate accounts",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A user may already have an account in your system, but may attempt to use Sign in with Apple to log in to that account. Sharing the real email address that’s associated with the user’s Apple ID may not help because it may not be the same email the user uses to create the account with your system. There are a couple of ways you can mitigate this issue:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Implement the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASAuthorizationPasswordProvider",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class to detect and offer keychain credentials that the system already knows about. This works seamlessly to detect and use existing accounts, and prevents creating new accounts using Sign in with Apple.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For new accounts that use Sign in with Apple, let the user know that they’re creating a new account, and ask if they have any existing accounts to link to.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AuthenticationServices/ASAuthorizationPasswordProvider": {
      "abstract": [
        {
          "text": "A mechanism for generating requests to perform keychain credential sharing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationPasswordProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASAuthorizationPasswordProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "ASAuthorizationPasswordProvider",
      "type": "topic",
      "url": "/documentation/AuthenticationServices/ASAuthorizationPasswordProvider"
    },
    "doc://com.apple.documentation/documentation/AuthenticationServices/ASUserDetectionStatus": {
      "abstract": [
        {
          "text": "Possible values for the real user indicator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASUserDetectionStatus"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASUserDetectionStatus",
      "kind": "symbol",
      "role": "symbol",
      "title": "ASUserDetectionStatus",
      "type": "topic",
      "url": "/documentation/AuthenticationServices/ASUserDetectionStatus"
    },
    "doc://com.apple.documentation/documentation/AuthenticationServices/ASUserDetectionStatus/likelyReal": {
      "abstract": [
        {
          "text": "The user appears to be a real person.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "likelyReal"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASUserDetectionStatus/likelyReal",
      "kind": "symbol",
      "role": "symbol",
      "title": "ASUserDetectionStatus.likelyReal",
      "type": "topic",
      "url": "/documentation/AuthenticationServices/ASUserDetectionStatus/likelyReal"
    },
    "doc://com.apple.documentation/documentation/AuthenticationServices/ASUserDetectionStatus/unknown": {
      "abstract": [
        {
          "text": "The system hasn’t determined whether the user might be a real person.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASUserDetectionStatus/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "ASUserDetectionStatus.unknown",
      "type": "topic",
      "url": "/documentation/AuthenticationServices/ASUserDetectionStatus/unknown"
    },
    "doc://com.apple.documentation/documentation/AuthenticationServices/ASUserDetectionStatus/unsupported": {
      "abstract": [
        {
          "text": "The system can’t determine this user’s status as a real person.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AuthenticationServices/ASUserDetectionStatus/unsupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "ASUserDetectionStatus.unsupported",
      "type": "topic",
      "url": "/documentation/AuthenticationServices/ASUserDetectionStatus/unsupported"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.signinwithapple/documentation/SigninwithApple": {
      "abstract": [
        {
          "text": "Provide users the ability to sign in to your apps and websites using their Apple ID.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.signinwithapple/documentation/SigninwithApple",
      "kind": "article",
      "role": "collection",
      "title": "Sign in with Apple",
      "type": "topic",
      "url": "/documentation/signinwithapple"
    },
    "doc://com.apple.signinwithapple/documentation/SigninwithAppleRESTAPI": {
      "abstract": [
        {
          "text": "Communicate between your app servers and Apple’s authentication servers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.signinwithapple/documentation/SigninwithAppleRESTAPI",
      "kind": "symbol",
      "role": "collection",
      "title": "Sign in with Apple REST API",
      "type": "topic",
      "url": "/documentation/signinwithapplerestapi"
    },
    "doc://com.apple.signinwithapple/documentation/SigninwithAppleRESTAPI/Generate-and-validate-tokens": {
      "abstract": [
        {
          "text": "Validate an authorization grant code delivered to your app to obtain tokens, or validate an existing refresh token.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.signinwithapple/documentation/SigninwithAppleRESTAPI/Generate-and-validate-tokens",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Generate and validate tokens"
        }
      ],
      "role": "symbol",
      "title": "Generate and validate tokens",
      "type": "topic",
      "url": "/documentation/signinwithapplerestapi/generate-and-validate-tokens"
    },
    "doc://com.apple.signinwithapple/documentation/sign_in_with_apple/bringing-new-apps-and-users-into-your-team": {
      "abstract": [
        {
          "text": "Receive Sign in with Apple users and associated apps from another team.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.signinwithapple/documentation/sign_in_with_apple/bringing-new-apps-and-users-into-your-team",
      "kind": "article",
      "role": "article",
      "title": "Bringing new apps and users into your team",
      "type": "topic",
      "url": "/documentation/sign_in_with_apple/bringing-new-apps-and-users-into-your-team"
    },
    "doc://com.apple.signinwithapple/documentation/sign_in_with_apple/communicating-using-the-private-email-relay-service": {
      "abstract": [
        {
          "text": "Stay in touch with users who opt for an anonymous email address with Sign in with Apple.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.signinwithapple/documentation/sign_in_with_apple/communicating-using-the-private-email-relay-service",
      "kind": "article",
      "role": "article",
      "title": "Communicating using the private email relay service",
      "type": "topic",
      "url": "/documentation/sign_in_with_apple/communicating-using-the-private-email-relay-service"
    },
    "doc://com.apple.signinwithapple/documentation/sign_in_with_apple/verifying-a-user": {
      "abstract": [
        {
          "text": "Check the validity and integrity of a user’s identity token.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.signinwithapple/documentation/sign_in_with_apple/verifying-a-user",
      "kind": "article",
      "role": "article",
      "title": "Verifying a user",
      "type": "topic",
      "url": "/documentation/sign_in_with_apple/verifying-a-user"
    },
    "media-3635395": {
      "alt": "A sequence diagram that describes the steps for authenticating a user. The app creates a scoped sign-in request to the API. The API requests user information, then verifies the user and obtains the token from an Apple ID server. The server provides the user’s name and, if requested, the email address to the app.",
      "identifier": "media-3635395",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/657bda82b8abbfa187e7bef20ddbb2b4/media-3635395@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/607ccf96ad2af79e04d06a744c120a73/media-3635395~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Authentication-and-verification-of-users",
      "generated": true,
      "identifiers": [
        "doc://com.apple.signinwithapple/documentation/sign_in_with_apple/verifying-a-user"
      ],
      "title": "Authentication and verification of users"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AuthenticationServices~1ASAuthorizationPasswordProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ASAuthorizationPasswordProvider"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AuthenticationServices~1ASUserDetectionStatus~1unsupported/title",
          "value": "ASUserDetectionStatusUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AuthenticationServices~1ASUserDetectionStatus~1unsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASUserDetectionStatusUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AuthenticationServices~1ASUserDetectionStatus/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ASUserDetectionStatus"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AuthenticationServices~1ASUserDetectionStatus~1likelyReal/title",
          "value": "ASUserDetectionStatusLikelyReal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AuthenticationServices~1ASUserDetectionStatus~1likelyReal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASUserDetectionStatusLikelyReal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AuthenticationServices~1ASUserDetectionStatus~1unknown/title",
          "value": "ASUserDetectionStatusUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AuthenticationServices~1ASUserDetectionStatus~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASUserDetectionStatusUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
