{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFSelectionGranularity"]]},"kind":"symbol","identifier":{"url":"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelectionGranularity/init(rawValue:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/pdfkit/pdfselectiongranularity/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"init(rawValue:)","role":"symbol","symbolKind":"init","externalID":"s:So23PDFSelectionGranularityV8rawValueABSgSu_tcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"roleHeading":"Initializer","modules":[{"name":"PDFKit"}],"platforms":[{"introducedAt":"18.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"introducedAt":"18.0","deprecated":false,"name":"iPadOS","unavailable":false,"beta":false},{"introducedAt":"18.0","beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"introducedAt":"15.0","beta":false,"deprecated":false,"unavailable":false,"name":"macOS"},{"introducedAt":"18.0","beta":false,"deprecated":false,"unavailable":false,"name":"tvOS"},{"introducedAt":"2.0","beta":false,"deprecated":false,"unavailable":false,"name":"visionOS"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","identifier":"doc://com.externally.resolved.symbol/s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"title":"Technologies","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelectionGranularity":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"PDFSelectionGranularity"}],"title":"PDFSelectionGranularity","url":"/documentation/pdfkit/pdfselectiongranularity","kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelectionGranularity","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PDFSelectionGranularity"}]},"doc://com.apple.pdfkit/documentation/PDFKit":{"role":"collection","identifier":"doc://com.apple.pdfkit/documentation/PDFKit","type":"topic","abstract":[{"type":"text","text":"Display and manipulate PDF documents in your apps."}],"kind":"symbol","title":"PDFKit","url":"/documentation/pdfkit"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelectionGranularity/init(rawValue:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"title":"init(rawValue:)","role":"symbol","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFSelectionGranularity/init(rawValue:)","type":"topic","url":"/documentation/pdfkit/pdfselectiongranularity/init(rawvalue:)"},"doc://com.externally.resolved.symbol/s:Su":{"kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UInt","kind":"identifier"}],"abstract":[{"type":"text","text":"An unsigned integer value type."}],"title":"UInt","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Su","type":"topic","url":"/documentation/Swift/UInt"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelectionGranularity/title","value":"PDFSelectionGranularity"},{"value":[{"kind":"identifier","text":"PDFSelectionGranularity"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelectionGranularity/fragments"},{"value":[{"kind":"identifier","text":"PDFSelectionGranularity"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFSelectionGranularity/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}