{
  "abstract": [
    {
      "text": "Resizing performed by expanding or shrinking a view in the direction of the right margin.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIView",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleRightMargin"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIViewAutoresizing@UIViewAutoresizingFlexibleRightMargin",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "flexibleRightMargin"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIView",
        "text": "UIView"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIViewAutoresizing",
        "text": "AutoresizingMask"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIViewAutoresizingFlexibleRightMargin"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "flexibleRightMargin"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "flexibleRightMargin"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIViewAutoresizing",
              "text": "AutoresizingMask"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct": {
      "abstract": [
        {
          "text": "Options for automatic view resizing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AutoresizingMask"
        }
      ],
      "role": "symbol",
      "title": "UIView.AutoresizingMask",
      "type": "topic",
      "url": "/documentation/uikit/uiview/autoresizingmask-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleBottomMargin": {
      "abstract": [
        {
          "text": "Resizing performed by expanding or shrinking a view in the direction of the bottom margin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flexibleBottomMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAutoresizing",
          "text": "AutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleBottomMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAutoresizingFlexibleBottomMargin"
        }
      ],
      "role": "symbol",
      "title": "flexibleBottomMargin",
      "type": "topic",
      "url": "/documentation/uikit/uiview/autoresizingmask-swift.struct/flexiblebottommargin"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleHeight": {
      "abstract": [
        {
          "text": "Resizing performed by expanding or shrinking a view’s height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flexibleHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAutoresizing",
          "text": "AutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAutoresizingFlexibleHeight"
        }
      ],
      "role": "symbol",
      "title": "flexibleHeight",
      "type": "topic",
      "url": "/documentation/uikit/uiview/autoresizingmask-swift.struct/flexibleheight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleLeftMargin": {
      "abstract": [
        {
          "text": "Resizing performed by expanding or shrinking a view in the direction of the left margin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flexibleLeftMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAutoresizing",
          "text": "AutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleLeftMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAutoresizingFlexibleLeftMargin"
        }
      ],
      "role": "symbol",
      "title": "flexibleLeftMargin",
      "type": "topic",
      "url": "/documentation/uikit/uiview/autoresizingmask-swift.struct/flexibleleftmargin"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleRightMargin": {
      "abstract": [
        {
          "text": "Resizing performed by expanding or shrinking a view in the direction of the right margin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flexibleRightMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAutoresizing",
          "text": "AutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleRightMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAutoresizingFlexibleRightMargin"
        }
      ],
      "role": "symbol",
      "title": "flexibleRightMargin",
      "type": "topic",
      "url": "/documentation/uikit/uiview/autoresizingmask-swift.struct/flexiblerightmargin"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleTopMargin": {
      "abstract": [
        {
          "text": "Resizing performed by expanding or shrinking a view in the direction of the top margin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flexibleTopMargin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAutoresizing",
          "text": "AutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleTopMargin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAutoresizingFlexibleTopMargin"
        }
      ],
      "role": "symbol",
      "title": "flexibleTopMargin",
      "type": "topic",
      "url": "/documentation/uikit/uiview/autoresizingmask-swift.struct/flexibletopmargin"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleWidth": {
      "abstract": [
        {
          "text": "Resizing performed by expanding or shrinking a view’s width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flexibleWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAutoresizing",
          "text": "AutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAutoresizingFlexibleWidth"
        }
      ],
      "role": "symbol",
      "title": "flexibleWidth",
      "type": "topic",
      "url": "/documentation/uikit/uiview/autoresizingmask-swift.struct/flexiblewidth"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewAutoresizing/UIViewAutoresizingNone": {
      "abstract": [
        {
          "text": "The option for indicating that the view does not resize.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIViewAutoresizingNone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAutoresizing/UIViewAutoresizingNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIViewAutoresizingNone",
      "type": "topic",
      "url": "/documentation/uikit/uiviewautoresizing/uiviewautoresizingnone"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleLeftMargin",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleWidth",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleTopMargin",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleHeight",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleBottomMargin"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIViewAutoresizingFlexibleRightMargin"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAutoresizingFlexibleRightMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewAutoresizing/UIViewAutoresizingNone",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleLeftMargin",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleWidth",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleTopMargin",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleHeight",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct/flexibleBottomMargin"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIViewAutoresizingFlexibleRightMargin"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct/title",
          "value": "UIViewAutoresizing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAutoresizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAutoresizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct~1flexibleRightMargin/title",
          "value": "UIViewAutoresizingFlexibleRightMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct~1flexibleRightMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAutoresizingFlexibleRightMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct~1flexibleBottomMargin/title",
          "value": "UIViewAutoresizingFlexibleBottomMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct~1flexibleBottomMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAutoresizingFlexibleBottomMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct~1flexibleLeftMargin/title",
          "value": "UIViewAutoresizingFlexibleLeftMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct~1flexibleLeftMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAutoresizingFlexibleLeftMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct~1flexibleWidth/title",
          "value": "UIViewAutoresizingFlexibleWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct~1flexibleWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAutoresizingFlexibleWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct~1flexibleTopMargin/title",
          "value": "UIViewAutoresizingFlexibleTopMargin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct~1flexibleTopMargin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAutoresizingFlexibleTopMargin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct~1flexibleHeight/title",
          "value": "UIViewAutoresizingFlexibleHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct~1flexibleHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAutoresizingFlexibleHeight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiview/autoresizingmask-swift.struct/flexiblerightmargin"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiview/autoresizingmask-swift.struct/flexiblerightmargin"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
