{
  "abstract": [
    {
      "text": "Countries and regions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/country"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MKAddressFilterOption@MKAddressFilterOptionCountry",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "country"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MKAddressFilter",
        "text": "MKAddressFilter"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MKAddressFilterOption",
        "text": "Options"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKAddressFilterOptionCountry"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "country"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "country"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MKAddressFilter",
              "text": "MKAddressFilter"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MKAddressFilterOption",
              "text": "Options"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter": {
      "abstract": [
        {
          "text": "An object that filters which address options to include or exclude in search results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKAddressFilter"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAddressFilter"
        }
      ],
      "role": "symbol",
      "title": "MKAddressFilter",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options": {
      "abstract": [
        {
          "text": "A structure that contains options for filtering results in a search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Options"
        }
      ],
      "role": "symbol",
      "title": "MKAddressFilter.Options",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter/options"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/administrativeArea": {
      "abstract": [
        {
          "text": "The primary administrative divisions of countries or regions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "administrativeArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKAddressFilter",
          "text": "MKAddressFilter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKAddressFilterOption",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/administrativeArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAddressFilterOptionAdministrativeArea"
        }
      ],
      "role": "symbol",
      "title": "administrativeArea",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter/options/administrativearea"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/country": {
      "abstract": [
        {
          "text": "Countries and regions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "country"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKAddressFilter",
          "text": "MKAddressFilter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKAddressFilterOption",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/country",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAddressFilterOptionCountry"
        }
      ],
      "role": "symbol",
      "title": "country",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter/options/country"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/locality": {
      "abstract": [
        {
          "text": "Local administrative divisions, postal cities, and populated places.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKAddressFilter",
          "text": "MKAddressFilter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKAddressFilterOption",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/locality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAddressFilterOptionLocality"
        }
      ],
      "role": "symbol",
      "title": "locality",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter/options/locality"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/postalCode": {
      "abstract": [
        {
          "text": "An address code for mail sorting and delivery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postalCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKAddressFilter",
          "text": "MKAddressFilter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKAddressFilterOption",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/postalCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAddressFilterOptionPostalCode"
        }
      ],
      "role": "symbol",
      "title": "postalCode",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter/options/postalcode"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subAdministrativeArea": {
      "abstract": [
        {
          "text": "The secondary administrative divisions of countries or regions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subAdministrativeArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKAddressFilter",
          "text": "MKAddressFilter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKAddressFilterOption",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subAdministrativeArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAddressFilterOptionSubAdministrativeArea"
        }
      ],
      "role": "symbol",
      "title": "subAdministrativeArea",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter/options/subadministrativearea"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subLocality": {
      "abstract": [
        {
          "text": "Local administrative subdivisions, postal city subdistricts, and neighborhoods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subLocality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKAddressFilter",
          "text": "MKAddressFilter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKAddressFilterOption",
          "text": "Options"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subLocality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKAddressFilterOptionSubLocality"
        }
      ],
      "role": "symbol",
      "title": "subLocality",
      "type": "topic",
      "url": "/documentation/mapkit/mkaddressfilter/options/sublocality"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-search-filter-options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/administrativeArea",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/locality",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/postalCode",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subAdministrativeArea",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subLocality",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/administrativeArea",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/locality",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/postalCode",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subAdministrativeArea",
        "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subLocality"
      ],
      "title": "Getting search filter options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKAddressFilterOptionCountry"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOptionCountry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-search-filter-options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/administrativeArea",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/locality",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/postalCode",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subAdministrativeArea",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subLocality",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/administrativeArea",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/locality",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/postalCode",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subAdministrativeArea",
                "doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options/subLocality"
              ],
              "title": "Getting search filter options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MKAddressFilterOptionCountry"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1postalCode/title",
          "value": "MKAddressFilterOptionPostalCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1postalCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOptionPostalCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1subLocality/title",
          "value": "MKAddressFilterOptionSubLocality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1subLocality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOptionSubLocality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1locality/title",
          "value": "MKAddressFilterOptionLocality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1locality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOptionLocality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1country/title",
          "value": "MKAddressFilterOptionCountry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1country/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOptionCountry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1administrativeArea/title",
          "value": "MKAddressFilterOptionAdministrativeArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1administrativeArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOptionAdministrativeArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1subAdministrativeArea/title",
          "value": "MKAddressFilterOptionSubAdministrativeArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options~1subAdministrativeArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOptionSubAdministrativeArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options/title",
          "value": "MKAddressFilterOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilterOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter/title",
          "value": "MKAddressFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKAddressFilter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkaddressfilter/options/country"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkaddressfilter/options/country"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
