{
  "abstract": [
    {
      "text": "The time offset passed to the haptic engine is invalid.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corehaptics/documentation/CoreHaptics",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidTime"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC17CHHapticErrorCodeLeV11invalidTimeSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidTime"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
        "text": "CHHapticError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CHHapticErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Core Haptics"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "invalidTime"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidTime"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
              "text": "CHHapticError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CHHapticErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This error occurs when you pass a negative or improperly formatted time value to the haptic engine.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corehaptics/documentation/CoreHaptics": {
      "abstract": [
        {
          "text": "Compose and play haptic patterns to customize your iOS app’s haptic feedback.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Haptics",
      "type": "topic",
      "url": "/documentation/corehaptics"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError": {
      "abstract": [
        {
          "text": "A structure that represents a framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHHapticError"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticError"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code": {
      "abstract": [
        {
          "text": "Error codes for framework operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CHHapticError.Code",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/code"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/badEventEntry": {
      "abstract": [
        {
          "text": "An event is missing a required field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badEventEntry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/badEventEntry",
      "kind": "symbol",
      "role": "symbol",
      "title": "badEventEntry",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/badevententry"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/badParameterEntry": {
      "abstract": [
        {
          "text": "A parameter in an event is missing a required field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badParameterEntry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/badParameterEntry",
      "kind": "symbol",
      "role": "symbol",
      "title": "badParameterEntry",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/badparameterentry"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/engineNotRunning": {
      "abstract": [
        {
          "text": "Your app requested haptic playback when the engine wasn’t running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "engineNotRunning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/engineNotRunning",
      "kind": "symbol",
      "role": "symbol",
      "title": "engineNotRunning",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/enginenotrunning"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/engineStartTimeout": {
      "abstract": [
        {
          "text": "The haptic engine timed out while starting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "engineStartTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/engineStartTimeout",
      "kind": "symbol",
      "role": "symbol",
      "title": "engineStartTimeout",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/enginestarttimeout"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/fileNotFound": {
      "abstract": [
        {
          "text": "The system couldn’t find an audio file or haptic asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/fileNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "fileNotFound",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/filenotfound"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/insufficientPower": {
      "abstract": [
        {
          "text": "The operation failed due to power restrictions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientPower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/insufficientPower",
      "kind": "symbol",
      "role": "symbol",
      "title": "insufficientPower",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/insufficientpower"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidAudioResource": {
      "abstract": [
        {
          "text": "A pattern dictionary or an event array contain a reference to an invalid audio resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAudioResource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidAudioResource",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidAudioResource",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/invalidaudioresource"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidAudioSession": {
      "abstract": [
        {
          "text": "The system invalidated the audio session associated with the haptic engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAudioSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidAudioSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidAudioSession",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/invalidaudiosession"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidEngineParameter": {
      "abstract": [
        {
          "text": "Your app attempted to initialize the haptic engine with an invalid configuration parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidEngineParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidEngineParameter",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidEngineParameter",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/invalidengineparameter"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidEventDuration": {
      "abstract": [
        {
          "text": "An event in the dictionary has an invalid duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidEventDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidEventDuration",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidEventDuration",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/invalideventduration"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidEventTime": {
      "abstract": [
        {
          "text": "The time of an event in the dictionary is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidEventTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidEventTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidEventTime",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/invalideventtime"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidEventType": {
      "abstract": [
        {
          "text": "The type of an event in the dictionary is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidEventType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidEventType",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidEventType",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/invalideventtype"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidParameterType": {
      "abstract": [
        {
          "text": "A pattern dictionary or parameter array contains an unknown or invalid parameter type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameterType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidParameterType",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidParameterType",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/invalidparametertype"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidPatternData": {
      "abstract": [
        {
          "text": "Your app passed an invalid pattern to the haptic engine or player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPatternData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidPatternData",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidPatternData",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/invalidpatterndata"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidPatternDictionary": {
      "abstract": [
        {
          "text": "A pattern in the dictionary is missing a required field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPatternDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidPatternDictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidPatternDictionary",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/invalidpatterndictionary"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidTime": {
      "abstract": [
        {
          "text": "The time offset passed to the haptic engine is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17CHHapticErrorCodeLeV",
          "text": "CHHapticError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CHHapticErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidTime",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticerror/invalidtime"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Code-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/badEventEntry",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/badParameterEntry",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/engineNotRunning",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/engineStartTimeout",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/fileNotFound",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/insufficientPower",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidAudioResource",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidAudioSession",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidEngineParameter",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidEventDuration",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidEventTime",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidEventType",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidParameterType",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidPatternData",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticError/invalidPatternDictionary"
      ],
      "title": "Error Code Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code/title",
          "value": "CHHapticErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corehaptics/chhapticerror/invalidtime"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
