{
  "abstract": [
    {
      "text": "Advances the screen saver’s animation by a single frame.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.screensaver/documentation/ScreenSaver",
        "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/animateOneFrame()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ScreenSaverView(im)animateOneFrame",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "animateOneFrame"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "Screen Saver"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "animateOneFrame"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "animateOneFrame()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "animateOneFrame"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system calls this method each time the timer animating the screen saver fires. The time between calls to this method is always at least ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/animationTimeInterval",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The system locks focus on your view before it calls this method, so you can use this method to draw content. You can also let ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/draw(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " perform the drawing, in which case you use this method to call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSView/setNeedsDisplay(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to mark your view as dirty. The default implementation of this method does nothing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSView/setNeedsDisplay(_:)": {
      "abstract": [
        {
          "text": "Marks the region of the view within the specified rectangle as needing display, increasing the view’s existing invalid region to include it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setNeedsDisplay"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "invalidRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSView/setNeedsDisplay(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setNeedsDisplay(_:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSView/setNeedsDisplay(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.screensaver/documentation/ScreenSaver": {
      "abstract": [
        {
          "text": "Animate screen savers, and interact with the screen saver infrastructure.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver",
      "kind": "symbol",
      "role": "collection",
      "title": "Screen Saver",
      "type": "topic",
      "url": "/documentation/screensaver"
    },
    "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface for subclassers to interact with the screen saver infrastructure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScreenSaverView"
        }
      ],
      "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScreenSaverView"
        }
      ],
      "role": "symbol",
      "title": "ScreenSaverView",
      "type": "topic",
      "url": "/documentation/screensaver/screensaverview"
    },
    "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/animateOneFrame()": {
      "abstract": [
        {
          "text": "Advances the screen saver’s animation by a single frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animateOneFrame"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/animateOneFrame()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "animateOneFrame"
        }
      ],
      "role": "symbol",
      "title": "animateOneFrame()",
      "type": "topic",
      "url": "/documentation/screensaver/screensaverview/animateoneframe()"
    },
    "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/animationTimeInterval": {
      "abstract": [
        {
          "text": "The time interval between animation frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animationTimeInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/animationTimeInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "animationTimeInterval"
        }
      ],
      "role": "symbol",
      "title": "animationTimeInterval",
      "type": "topic",
      "url": "/documentation/screensaver/screensaverview/animationtimeinterval"
    },
    "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/draw(_:)": {
      "abstract": [
        {
          "text": "Draws the screen saver view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/draw(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawRect:"
        }
      ],
      "role": "symbol",
      "title": "draw(_:)",
      "type": "topic",
      "url": "/documentation/screensaver/screensaverview/draw(_:)"
    },
    "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/isAnimating": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the screen saver is animating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAnimating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/isAnimating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "animating"
        }
      ],
      "role": "symbol",
      "title": "isAnimating",
      "type": "topic",
      "url": "/documentation/screensaver/screensaverview/isanimating"
    },
    "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/startAnimation()": {
      "abstract": [
        {
          "text": "Activates the periodic timer that animates the screen saver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startAnimation"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/startAnimation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startAnimation"
        }
      ],
      "role": "symbol",
      "title": "startAnimation()",
      "type": "topic",
      "url": "/documentation/screensaver/screensaverview/startanimation()"
    },
    "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/stopAnimation()": {
      "abstract": [
        {
          "text": "Deactivates the timer that advances the animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopAnimation"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/stopAnimation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopAnimation"
        }
      ],
      "role": "symbol",
      "title": "stopAnimation()",
      "type": "topic",
      "url": "/documentation/screensaver/screensaverview/stopanimation()"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Animating-the-screen-saver",
      "generated": true,
      "identifiers": [
        "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/startAnimation()",
        "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/stopAnimation()",
        "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/isAnimating"
      ],
      "title": "Animating the screen saver"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "animateOneFrame"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "animateOneFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.screensaver/documentation/ScreenSaver",
                "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Animating-the-screen-saver",
              "generated": true,
              "identifiers": [
                "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/startAnimation()",
                "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/stopAnimation()",
                "doc://com.apple.screensaver/documentation/ScreenSaver/ScreenSaverView/isAnimating"
              ],
              "title": "Animating the screen saver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "animateOneFrame"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView/title",
          "value": "ScreenSaverView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ScreenSaverView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ScreenSaverView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView~1startAnimation()/title",
          "value": "startAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView~1startAnimation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView~1animationTimeInterval/title",
          "value": "animationTimeInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView~1animationTimeInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "animationTimeInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView~1draw(_:)/title",
          "value": "drawRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView~1draw(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSView~1setNeedsDisplay(_:)/title",
          "value": "setNeedsDisplayInRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSView~1setNeedsDisplay(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "setNeedsDisplayInRect:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "invalidRect"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView~1stopAnimation()/title",
          "value": "stopAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView~1stopAnimation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView~1isAnimating/title",
          "value": "animating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView~1isAnimating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "animating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView~1animateOneFrame()/title",
          "value": "animateOneFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screensaver~1documentation~1ScreenSaver~1ScreenSaverView~1animateOneFrame()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "animateOneFrame"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screensaver/screensaverview/animateoneframe()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/screensaver/screensaverview/animateoneframe()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
