{
  "abstract": [
    {
      "text": "The URL of the storage container of the current sample and other samples to load in the same operation as a chunk.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkStorageURL"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:objc(cs)AVSampleCursor(py)currentChunkStorageURL",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "currentChunkStorageURL"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation3URLV",
        "text": "URL"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "currentChunkStorageURL"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "currentChunkStorageURL"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "currentChunkStorageURL"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation3URLV",
              "text": "URL"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When this property is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", the storage location of the chunk is the URL of the sample cursor’s track’s asset, if it has one.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor": {
      "abstract": [
        {
          "text": "An object that provides information about the media sample at the cursor’s current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursor"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursor"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursor",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/copyCurrentSampleFormatDescription()": {
      "abstract": [
        {
          "text": "Returns the format description of the sample at the cursor’s current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyCurrentSampleFormatDescription"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/copyCurrentSampleFormatDescription()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "copyCurrentSampleFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "copyCurrentSampleFormatDescription()",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/copycurrentsampleformatdescription()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkInfo": {
      "abstract": [
        {
          "text": "A value that provides information about the chunk of samples to which the current sample belongs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentChunkInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVSampleCursorChunkInfo",
          "text": "AVSampleCursorChunkInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentChunkInfo"
        }
      ],
      "role": "symbol",
      "title": "currentChunkInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentchunkinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkStorageRange": {
      "abstract": [
        {
          "text": "The sample range in the storage container to load together with the current sample as a chunk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentChunkStorageRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVSampleCursorStorageRange",
          "text": "AVSampleCursorStorageRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkStorageRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentChunkStorageRange"
        }
      ],
      "role": "symbol",
      "title": "currentChunkStorageRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentchunkstoragerange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkStorageURL": {
      "abstract": [
        {
          "text": "The URL of the storage container of the current sample and other samples to load in the same operation as a chunk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentChunkStorageURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkStorageURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentChunkStorageURL"
        }
      ],
      "role": "symbol",
      "title": "currentChunkStorageURL",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentchunkstorageurl"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleAudioDependencyInfo": {
      "abstract": [
        {
          "text": "The independent decodability information for the audio sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleAudioDependencyInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVSampleCursorAudioDependencyInfo",
          "text": "AVSampleCursorAudioDependencyInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleAudioDependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleAudioDependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "currentSampleAudioDependencyInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentsampleaudiodependencyinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyAttachments": {
      "abstract": [
        {
          "text": "A dictionary of dependency-related sample buffer attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleDependencyAttachments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyAttachments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleDependencyAttachments"
        }
      ],
      "role": "symbol",
      "title": "currentSampleDependencyAttachments",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentsampledependencyattachments"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyInfo": {
      "abstract": [
        {
          "text": "The dependency information that describes relationships between a media sample and other media samples in the same sample sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleDependencyInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVSampleCursorDependencyInfo",
          "text": "AVSampleCursorDependencyInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleDependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "currentSampleDependencyInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentsampledependencyinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDuration": {
      "abstract": [
        {
          "text": "The decode duration of the sample at the cursor’s current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleDuration"
        }
      ],
      "role": "symbol",
      "title": "currentSampleDuration",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentsampleduration"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleIndexInChunk": {
      "abstract": [
        {
          "text": "The index of the current sample within the chunk to which it belongs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleIndexInChunk"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleIndexInChunk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleIndexInChunk"
        }
      ],
      "role": "symbol",
      "title": "currentSampleIndexInChunk",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentsampleindexinchunk"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleStorageRange": {
      "abstract": [
        {
          "text": "The offset and length of the current sample in the current chunk storage URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleStorageRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVSampleCursorStorageRange",
          "text": "AVSampleCursorStorageRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleStorageRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleStorageRange"
        }
      ],
      "role": "symbol",
      "title": "currentSampleStorageRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentsamplestoragerange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleSyncInfo": {
      "abstract": [
        {
          "text": "The synchronization information for the current sample for consideration when resynchronizing a decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleSyncInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVSampleCursorSyncInfo",
          "text": "AVSampleCursorSyncInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleSyncInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleSyncInfo"
        }
      ],
      "role": "symbol",
      "title": "currentSampleSyncInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentsamplesyncinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo": {
      "abstract": [
        {
          "text": "A value that provides information about a chunk of media samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorChunkInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorChunkInfo"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorChunkInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorchunkinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo": {
      "abstract": [
        {
          "text": "A value for describing dependencies between a media sample and other media samples in the same sample sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorDependencyInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorDependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorDependencyInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursordependencyinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange": {
      "abstract": [
        {
          "text": "A structure that indicates the offset and length of storage for a media sample or its chunk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorStorageRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorStorageRange"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorStorageRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorstoragerange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo": {
      "abstract": [
        {
          "text": "A structure that describes the attributes of media samples to consider when resynchronizing a decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorSyncInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorSyncInfo"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorSyncInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorsyncinfo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSURL": {
      "abstract": [
        {
          "text": "An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSURL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSURL",
      "type": "topic",
      "url": "/documentation/foundation/nsurl"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation3URLV": {
      "abstract": [
        {
          "text": "A value that identifies the location of a resource, such as an item on a remote server or the path to a local file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
      "kind": "symbol",
      "role": "symbol",
      "title": "URL",
      "type": "topic",
      "url": "/documentation/foundation/url"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Sample-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkStorageRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDuration",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleIndexInChunk",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleStorageRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleSyncInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/copyCurrentSampleFormatDescription()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleAudioDependencyInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyAttachments"
      ],
      "title": "Getting Sample Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "currentChunkStorageURL"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentChunkStorageURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Sample-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkStorageRange",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDuration",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleIndexInChunk",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleStorageRange",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleSyncInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/copyCurrentSampleFormatDescription()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleAudioDependencyInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyAttachments"
              ],
              "title": "Getting Sample Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSURL",
                    "text": "NSURL"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "currentChunkStorageURL"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleDependencyInfo/title",
          "value": "currentSampleDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleDependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentChunkInfo/title",
          "value": "currentChunkInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentChunkInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentChunkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentChunkStorageRange/title",
          "value": "currentChunkStorageRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentChunkStorageRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentChunkStorageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleDependencyAttachments/title",
          "value": "currentSampleDependencyAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleDependencyAttachments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleDependencyAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleSyncInfo/title",
          "value": "currentSampleSyncInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleSyncInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleSyncInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorDependencyInfo/title",
          "value": "AVSampleCursorDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorDependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorDependencyInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorChunkInfo/title",
          "value": "AVSampleCursorChunkInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorChunkInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorChunkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorChunkInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorChunkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1copyCurrentSampleFormatDescription()/title",
          "value": "copyCurrentSampleFormatDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1copyCurrentSampleFormatDescription()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "copyCurrentSampleFormatDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleDuration/title",
          "value": "currentSampleDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleStorageRange/title",
          "value": "currentSampleStorageRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleStorageRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleStorageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURL/abstract",
          "value": [
            {
              "text": "An object that represents the location of a resource, such as an item on a remote server or the path to a local file. ",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleAudioDependencyInfo/title",
          "value": "currentSampleAudioDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleAudioDependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleAudioDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentChunkStorageURL/title",
          "value": "currentChunkStorageURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentChunkStorageURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentChunkStorageURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo/title",
          "value": "AVSampleCursorSyncInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorSyncInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorSyncInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorStorageRange/title",
          "value": "AVSampleCursorStorageRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorStorageRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorStorageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorStorageRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorStorageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleIndexInChunk/title",
          "value": "currentSampleIndexInChunk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleIndexInChunk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleIndexInChunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor/title",
          "value": "AVSampleCursor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avsamplecursor/currentchunkstorageurl"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avsamplecursor/currentchunkstorageurl"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
