{
  "abstract": [
    {
      "text": "An error code that indicates the GPU device doesn’t have sufficient memory to create a counter sample buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct",
        "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code/outOfMemory"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLCounterSampleBufferError@MTLCounterSampleBufferErrorOutOfMemory",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "outOfMemory"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLCounterSampleBufferErrorOutOfMemory"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLCounterSampleBufferError.Code.outOfMemory"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "outOfMemory"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct": {
      "abstract": [
        {
          "text": "The error codes that indicate why a GPU driver can’t create a counter sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCounterSampleBufferError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterSampleBufferError"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterSampleBufferError",
      "type": "topic",
      "url": "/documentation/metal/mtlcountersamplebuffererror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code": {
      "abstract": [
        {
          "text": "The underlying error code type that indicates why a GPU driver can’t create a counter sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterSampleBufferError.Code",
      "type": "topic",
      "url": "/documentation/metal/mtlcountersamplebuffererror-swift.struct/code"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code/internal": {
      "abstract": [
        {
          "text": "An error code that indicates the Metal framework has an internal problem.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`internal`"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code/internal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterSampleBufferErrorInternal"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterSampleBufferError.Code.internal",
      "type": "topic",
      "url": "/documentation/metal/mtlcountersamplebuffererror-swift.struct/code/internal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code/invalid": {
      "abstract": [
        {
          "text": "An error code that indicates when a counter-sample buffer descriptor has at",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "least one invalid property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code/invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterSampleBufferErrorInvalid"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterSampleBufferError.Code.invalid",
      "type": "topic",
      "url": "/documentation/metal/mtlcountersamplebuffererror-swift.struct/code/invalid"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code/outOfMemory": {
      "abstract": [
        {
          "text": "An error code that indicates the GPU device doesn’t have sufficient memory to create a counter sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfMemory"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code/outOfMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterSampleBufferErrorOutOfMemory"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterSampleBufferError.Code.outOfMemory",
      "type": "topic",
      "url": "/documentation/metal/mtlcountersamplebuffererror-swift.struct/code/outofmemory"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code/invalid",
        "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code/internal",
        "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code/invalid",
        "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code/internal"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLCounterSampleBufferErrorOutOfMemory"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSampleBufferErrorOutOfMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code/invalid",
                "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code/internal",
                "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code/invalid",
                "doc://com.apple.metal/documentation/Metal/MTLCounterSampleBufferError-swift.struct/Code/internal"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLCounterSampleBufferErrorOutOfMemory"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSampleBufferError-swift.struct~1Code/title",
          "value": "MTLCounterSampleBufferError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSampleBufferError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSampleBufferError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSampleBufferError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSampleBufferError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSampleBufferError-swift.struct~1Code~1internal/title",
          "value": "MTLCounterSampleBufferErrorInternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSampleBufferError-swift.struct~1Code~1internal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSampleBufferErrorInternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSampleBufferError-swift.struct~1Code~1invalid/title",
          "value": "MTLCounterSampleBufferErrorInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSampleBufferError-swift.struct~1Code~1invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSampleBufferErrorInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSampleBufferError-swift.struct~1Code~1outOfMemory/title",
          "value": "MTLCounterSampleBufferErrorOutOfMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterSampleBufferError-swift.struct~1Code~1outOfMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterSampleBufferErrorOutOfMemory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlcountersamplebuffererror-swift.struct/code/outofmemory"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlcountersamplebuffererror-swift.struct/code/outofmemory"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
