{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC7EPErrorLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "EPError"
      }
    ],
    "modules": [
      {
        "name": "Execution Policy"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EPError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "EPError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EPError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy": {
      "abstract": [
        {
          "text": "Provide functionality so developer tools can manage execution policy exceptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy",
      "kind": "symbol",
      "role": "collection",
      "title": "Execution Policy",
      "type": "topic",
      "url": "/documentation/executionpolicy"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EPError"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EPError"
        }
      ],
      "role": "symbol",
      "title": "EPError",
      "type": "topic",
      "url": "/documentation/executionpolicy/eperror-swift.struct"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "EPError.Code",
      "type": "topic",
      "url": "/documentation/executionpolicy/eperror-swift.struct/code"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/executionpolicy/eperror-swift.struct/errordomain"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct/generic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "generic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7EPErrorLeV",
          "text": "EPError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EPError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct/generic",
      "kind": "symbol",
      "role": "symbol",
      "title": "generic",
      "type": "topic",
      "url": "/documentation/executionpolicy/eperror-swift.struct/generic"
    },
    "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct/notADeveloperTool": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notADeveloperTool"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7EPErrorLeV",
          "text": "EPError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EPError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct/notADeveloperTool",
      "kind": "symbol",
      "role": "symbol",
      "title": "notADeveloperTool",
      "type": "topic",
      "url": "/documentation/executionpolicy/eperror-swift.struct/notadevelopertool"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct/generic",
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct/notADeveloperTool",
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct/errorDomain"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.executionpolicy/documentation/ExecutionPolicy/EPError-swift.struct/Code"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPError-swift.struct~1Code/title",
          "value": "EPError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EPError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.executionpolicy~1documentation~1ExecutionPolicy~1EPError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EPError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/executionpolicy/eperror-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
