{
  "abstract": [
    {
      "text": "The user interface direction that controls the layout order of the items.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem/groupUserInterfaceLayoutDirection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSGroupTouchBarItem(py)groupUserInterfaceLayoutDirection",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "groupUserInterfaceLayoutDirection"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSUserInterfaceLayoutDirection",
        "text": "NSUserInterfaceLayoutDirection"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "groupUserInterfaceLayoutDirection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "groupUserInterfaceLayoutDirection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "groupUserInterfaceLayoutDirection"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSUserInterfaceLayoutDirection",
              "text": "NSUserInterfaceLayoutDirection"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection/leftToRight",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you want the order of the items in the group to respect the user’s preferred layout, set this property to the value of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/userInterfaceLayoutDirection",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication": {
      "abstract": [
        {
          "text": "An object that manages an app’s main event loop and resources used by all of that app’s objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSApplication"
        }
      ],
      "role": "symbol",
      "title": "NSApplication",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSApplication/userInterfaceLayoutDirection": {
      "abstract": [
        {
          "text": "The layout direction of the user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInterfaceLayoutDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUserInterfaceLayoutDirection",
          "text": "NSUserInterfaceLayoutDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSApplication/userInterfaceLayoutDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInterfaceLayoutDirection"
        }
      ],
      "role": "symbol",
      "title": "userInterfaceLayoutDirection",
      "type": "topic",
      "url": "/documentation/appkit/nsapplication/userinterfacelayoutdirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem": {
      "abstract": [
        {
          "text": "A bar item that provides a bar to contain other items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGroupTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGroupTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSGroupTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nsgrouptouchbaritem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem/groupTouchBar": {
      "abstract": [
        {
          "text": "A bar that holds this group’s items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groupTouchBar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTouchBar",
          "text": "NSTouchBar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem/groupTouchBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "groupTouchBar"
        }
      ],
      "role": "symbol",
      "title": "groupTouchBar",
      "type": "topic",
      "url": "/documentation/appkit/nsgrouptouchbaritem/grouptouchbar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem/groupUserInterfaceLayoutDirection": {
      "abstract": [
        {
          "text": "The user interface direction that controls the layout order of the items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groupUserInterfaceLayoutDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUserInterfaceLayoutDirection",
          "text": "NSUserInterfaceLayoutDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem/groupUserInterfaceLayoutDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "groupUserInterfaceLayoutDirection"
        }
      ],
      "role": "symbol",
      "title": "groupUserInterfaceLayoutDirection",
      "type": "topic",
      "url": "/documentation/appkit/nsgrouptouchbaritem/groupuserinterfacelayoutdirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection": {
      "abstract": [
        {
          "text": "Specifies the directional flow of the user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceLayoutDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceLayoutDirection"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceLayoutDirection",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfacelayoutdirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection/leftToRight": {
      "abstract": [
        {
          "text": "Layout direction is left to right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftToRight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection/leftToRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceLayoutDirectionLeftToRight"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceLayoutDirection.leftToRight",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfacelayoutdirection/lefttoright"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-groups",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem/groupTouchBar"
      ],
      "title": "Configuring groups"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "groupUserInterfaceLayoutDirection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "groupUserInterfaceLayoutDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-groups",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGroupTouchBarItem/groupTouchBar"
              ],
              "title": "Configuring groups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceLayoutDirection",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSUserInterfaceLayoutDirection",
                    "text": "NSUserInterfaceLayoutDirection"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "groupUserInterfaceLayoutDirection"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGroupTouchBarItem~1groupUserInterfaceLayoutDirection/title",
          "value": "groupUserInterfaceLayoutDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGroupTouchBarItem~1groupUserInterfaceLayoutDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "groupUserInterfaceLayoutDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1userInterfaceLayoutDirection/title",
          "value": "userInterfaceLayoutDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication~1userInterfaceLayoutDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInterfaceLayoutDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGroupTouchBarItem/title",
          "value": "NSGroupTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGroupTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGroupTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGroupTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGroupTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGroupTouchBarItem~1groupTouchBar/title",
          "value": "groupTouchBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGroupTouchBarItem~1groupTouchBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "groupTouchBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutDirection~1leftToRight/title",
          "value": "NSUserInterfaceLayoutDirectionLeftToRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutDirection~1leftToRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceLayoutDirectionLeftToRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/title",
          "value": "NSApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutDirection/title",
          "value": "NSUserInterfaceLayoutDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceLayoutDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceLayoutDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceLayoutDirection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsgrouptouchbaritem/groupuserinterfacelayoutdirection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsgrouptouchbaritem/groupuserinterfacelayoutdirection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
