{
  "abstract": [
    {
      "text": "Displays the find bar interface including the replace functionality.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinder",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/hideReplaceInterface"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTextFinderAction@NSTextFinderActionHideReplaceInterface",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "hideReplaceInterface"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextFinderActionHideReplaceInterface"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSTextFinder.Action.hideReplaceInterface"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hideReplaceInterface"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder/performTextFinderAction(_:)": {
      "abstract": [
        {
          "text": "Performs all find oriented actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performTextFinderAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/performTextFinderAction(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performTextFinderAction:"
        }
      ],
      "role": "symbol",
      "title": "performTextFinderAction(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder/performtextfinderaction(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder": {
      "abstract": [
        {
          "text": "An optional search-and-replace find interface inside a view, usually a scroll view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextFinder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinder"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action": {
      "abstract": [
        {
          "text": "These constants specify the user interface item tags that correspond find action. These constants are passed to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/performTextFinderAction(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method, the responder will call the appropriate method for the tag. That method will, in turn, determine the desired action and invoke the appropriate method in the ",
          "type": "text"
        },
        {
          "code": "NSTextFinder",
          "type": "codeVoice"
        },
        {
          "text": " object’s ",
          "type": "text"
        },
        {
          "code": "NSTextFinderClient",
          "type": "codeVoice"
        },
        {
          "text": " protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Action"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Action"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder.Action",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder/action"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/hideFindInterface": {
      "abstract": [
        {
          "text": "Hides the find bar interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hideFindInterface"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/hideFindInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinderActionHideFindInterface"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder.Action.hideFindInterface",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder/action/hidefindinterface"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/hideReplaceInterface": {
      "abstract": [
        {
          "text": "Displays the find bar interface including the replace functionality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hideReplaceInterface"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/hideReplaceInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinderActionHideReplaceInterface"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder.Action.hideReplaceInterface",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder/action/hidereplaceinterface"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/nextMatch": {
      "abstract": [
        {
          "text": "The next match, if any, is displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextMatch"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/nextMatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinderActionNextMatch"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder.Action.nextMatch",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder/action/nextmatch"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/previousMatch": {
      "abstract": [
        {
          "text": "The previous match, if any, is displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previousMatch"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/previousMatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinderActionPreviousMatch"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder.Action.previousMatch",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder/action/previousmatch"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replace": {
      "abstract": [
        {
          "text": "Replaces a single instance of the string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinderActionReplace"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder.Action.replace",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder/action/replace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replaceAll": {
      "abstract": [
        {
          "text": "All occurrences of the string are replaced.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replaceAll"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replaceAll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinderActionReplaceAll"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder.Action.replaceAll",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder/action/replaceall"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replaceAllInSelection": {
      "abstract": [
        {
          "text": "Replaces all occurrences of the string within the current selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replaceAllInSelection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replaceAllInSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinderActionReplaceAllInSelection"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder.Action.replaceAllInSelection",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder/action/replaceallinselection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replaceAndFind": {
      "abstract": [
        {
          "text": "Replaces a single instance of the string and searches for the next match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replaceAndFind"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replaceAndFind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinderActionReplaceAndFind"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder.Action.replaceAndFind",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder/action/replaceandfind"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/selectAll": {
      "abstract": [
        {
          "text": "Selects all matching search strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectAll"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/selectAll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinderActionSelectAll"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder.Action.selectAll",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder/action/selectall"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/selectAllInSelection": {
      "abstract": [
        {
          "text": "Selects all matching search strings within the current selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectAllInSelection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/selectAllInSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinderActionSelectAllInSelection"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder.Action.selectAllInSelection",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder/action/selectallinselection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/setSearchString": {
      "abstract": [
        {
          "text": "Sets the search string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setSearchString"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/setSearchString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinderActionSetSearchString"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder.Action.setSearchString",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder/action/setsearchstring"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/showFindInterface": {
      "abstract": [
        {
          "text": "The find bar interface is displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showFindInterface"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/showFindInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinderActionShowFindInterface"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder.Action.showFindInterface",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder/action/showfindinterface"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/showReplaceInterface": {
      "abstract": [
        {
          "text": "Displays the find bar interface including the replace functionality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showReplaceInterface"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/showReplaceInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextFinderActionShowReplaceInterface"
        }
      ],
      "role": "symbol",
      "title": "NSTextFinder.Action.showReplaceInterface",
      "type": "topic",
      "url": "/documentation/appkit/nstextfinder/action/showreplaceinterface"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/showFindInterface",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/nextMatch",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/previousMatch",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replaceAll",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replace",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replaceAndFind",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/setSearchString",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replaceAllInSelection",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/selectAll",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/selectAllInSelection",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/hideFindInterface",
        "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/showReplaceInterface"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextFinderActionHideReplaceInterface"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderActionHideReplaceInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/showFindInterface",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/nextMatch",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/previousMatch",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replaceAll",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replace",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replaceAndFind",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/setSearchString",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/replaceAllInSelection",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/selectAll",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/selectAllInSelection",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/hideFindInterface",
                "doc://com.apple.appkit/documentation/AppKit/NSTextFinder/Action/showReplaceInterface"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTextFinderActionHideReplaceInterface"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder/title",
          "value": "NSTextFinder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1nextMatch/title",
          "value": "NSTextFinderActionNextMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1nextMatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderActionNextMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1replaceAllInSelection/title",
          "value": "NSTextFinderActionReplaceAllInSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1replaceAllInSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderActionReplaceAllInSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1showReplaceInterface/title",
          "value": "NSTextFinderActionShowReplaceInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1showReplaceInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderActionShowReplaceInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1showFindInterface/title",
          "value": "NSTextFinderActionShowFindInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1showFindInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderActionShowFindInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1replaceAll/title",
          "value": "NSTextFinderActionReplaceAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1replaceAll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderActionReplaceAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1hideReplaceInterface/title",
          "value": "NSTextFinderActionHideReplaceInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1hideReplaceInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderActionHideReplaceInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1performTextFinderAction(_:)/title",
          "value": "performTextFinderAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1performTextFinderAction(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performTextFinderAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1selectAllInSelection/title",
          "value": "NSTextFinderActionSelectAllInSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1selectAllInSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderActionSelectAllInSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1selectAll/title",
          "value": "NSTextFinderActionSelectAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1selectAll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderActionSelectAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1setSearchString/title",
          "value": "NSTextFinderActionSetSearchString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1setSearchString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderActionSetSearchString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1replace/title",
          "value": "NSTextFinderActionReplace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1replace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderActionReplace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1hideFindInterface/title",
          "value": "NSTextFinderActionHideFindInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1hideFindInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderActionHideFindInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1previousMatch/title",
          "value": "NSTextFinderActionPreviousMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1previousMatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderActionPreviousMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1replaceAndFind/title",
          "value": "NSTextFinderActionReplaceAndFind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action~1replaceAndFind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderActionReplaceAndFind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action/title",
          "value": "NSTextFinderAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextFinder~1Action/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextFinderAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextfinder/action/hidereplaceinterface"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextfinder/action/hidereplaceinterface"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
