{
  "abstract": [
    {
      "text": "The common name for the counter that tracks the number of times a render pass calls fragment shaders.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/fragmentInvocations"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Metal",
    "externalID": "c:@MTLCommonCounterFragmentInvocations",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "fragmentInvocations"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MTLCommonCounter",
        "text": "MTLCommonCounter"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLCommonCounterFragmentInvocations"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "fragmentInvocations"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fragmentInvocations"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MTLCommonCounter",
              "text": "MTLCommonCounter"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter": {
      "abstract": [
        {
          "text": "The name of a specific counter that can appear in a GPU device’s counter sets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounter"
        }
      ],
      "role": "symbol",
      "title": "MTLCommonCounter",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/clipperInvocations": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of primitives a render pass sends to the clip stage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clipperInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/clipperInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterClipperInvocations"
        }
      ],
      "role": "symbol",
      "title": "clipperInvocations",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/clipperinvocations"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/clipperPrimitivesOut": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of primitives the clip stage produces during a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clipperPrimitivesOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/clipperPrimitivesOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterClipperPrimitivesOut"
        }
      ],
      "role": "symbol",
      "title": "clipperPrimitivesOut",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/clipperprimitivesout"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/computeKernelInvocations": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of times a pass invokes any compute kernel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "computeKernelInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/computeKernelInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterComputeKernelInvocations"
        }
      ],
      "role": "symbol",
      "title": "computeKernelInvocations",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/computekernelinvocations"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/fragmentCycles": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of cycles the GPU uses to run fragment shaders during a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fragmentCycles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/fragmentCycles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterFragmentCycles"
        }
      ],
      "role": "symbol",
      "title": "fragmentCycles",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/fragmentcycles"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/fragmentInvocations": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of times a render pass calls fragment shaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fragmentInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/fragmentInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterFragmentInvocations"
        }
      ],
      "role": "symbol",
      "title": "fragmentInvocations",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/fragmentinvocations"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/fragmentsPassed": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of fragments a render pass sends to the visibility and blend stages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fragmentsPassed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/fragmentsPassed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterFragmentsPassed"
        }
      ],
      "role": "symbol",
      "title": "fragmentsPassed",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/fragmentspassed"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/postTessellationVertexCycles": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of cycles the GPU uses to run post-tessellation vertex shaders during a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postTessellationVertexCycles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/postTessellationVertexCycles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterPostTessellationVertexCycles"
        }
      ],
      "role": "symbol",
      "title": "postTessellationVertexCycles",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/posttessellationvertexcycles"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/postTessellationVertexInvocations": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of vertices a render pass sends to a post-tessellation vertex shader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postTessellationVertexInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/postTessellationVertexInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterPostTessellationVertexInvocations"
        }
      ],
      "role": "symbol",
      "title": "postTessellationVertexInvocations",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/posttessellationvertexinvocations"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/renderTargetWriteCycles": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of cycles the GPU uses to write data to render targets during a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renderTargetWriteCycles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/renderTargetWriteCycles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterRenderTargetWriteCycles"
        }
      ],
      "role": "symbol",
      "title": "renderTargetWriteCycles",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/rendertargetwritecycles"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/tessellationCycles": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of cycles the GPU uses to run the tessellation stage during a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tessellationCycles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/tessellationCycles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterTessellationCycles"
        }
      ],
      "role": "symbol",
      "title": "tessellationCycles",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/tessellationcycles"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/tessellationInputPatches": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of tessellation patches a render pass sends to the tessellation stage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tessellationInputPatches"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/tessellationInputPatches",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterTessellationInputPatches"
        }
      ],
      "role": "symbol",
      "title": "tessellationInputPatches",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/tessellationinputpatches"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/timestamp": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the current time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/timestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterTimestamp"
        }
      ],
      "role": "symbol",
      "title": "timestamp",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/timestamp"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/totalCycles": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the total number of cycles the GPU uses to run a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalCycles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/totalCycles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterTotalCycles"
        }
      ],
      "role": "symbol",
      "title": "totalCycles",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/totalcycles"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/vertexCycles": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of cycles the GPU uses to run vertex shaders during a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertexCycles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/vertexCycles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterVertexCycles"
        }
      ],
      "role": "symbol",
      "title": "vertexCycles",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/vertexcycles"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/vertexInvocations": {
      "abstract": [
        {
          "text": "The common name for the counter that tracks the number of times a render pass calls any vertex shader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertexInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTLCommonCounter",
          "text": "MTLCommonCounter"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/vertexInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommonCounterVertexInvocations"
        }
      ],
      "role": "symbol",
      "title": "vertexInvocations",
      "type": "topic",
      "url": "/documentation/metal/mtlcommoncounter/vertexinvocations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Common-Counter-Names",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/timestamp",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/tessellationInputPatches",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/vertexInvocations",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/postTessellationVertexInvocations",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/clipperInvocations",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/clipperPrimitivesOut",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/fragmentsPassed",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/computeKernelInvocations",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/totalCycles",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/vertexCycles",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/postTessellationVertexCycles",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/fragmentCycles",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/tessellationCycles",
        "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/renderTargetWriteCycles"
      ],
      "title": "Common Counter Names"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLCommonCounterFragmentInvocations"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterFragmentInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Common-Counter-Names",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/timestamp",
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/tessellationInputPatches",
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/vertexInvocations",
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/postTessellationVertexInvocations",
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/clipperInvocations",
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/clipperPrimitivesOut",
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/fragmentsPassed",
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/computeKernelInvocations",
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/totalCycles",
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/vertexCycles",
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/postTessellationVertexCycles",
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/fragmentCycles",
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/tessellationCycles",
                "doc://com.apple.metal/documentation/Metal/MTLCommonCounter/renderTargetWriteCycles"
              ],
              "title": "Common Counter Names"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommonCounter",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MTLCommonCounter",
                    "text": "MTLCommonCounter"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLCommonCounterFragmentInvocations"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1timestamp/title",
          "value": "MTLCommonCounterTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1timestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1tessellationInputPatches/title",
          "value": "MTLCommonCounterTessellationInputPatches"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1tessellationInputPatches/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterTessellationInputPatches"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1renderTargetWriteCycles/title",
          "value": "MTLCommonCounterRenderTargetWriteCycles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1renderTargetWriteCycles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterRenderTargetWriteCycles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1computeKernelInvocations/title",
          "value": "MTLCommonCounterComputeKernelInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1computeKernelInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterComputeKernelInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1vertexCycles/title",
          "value": "MTLCommonCounterVertexCycles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1vertexCycles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterVertexCycles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1fragmentsPassed/title",
          "value": "MTLCommonCounterFragmentsPassed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1fragmentsPassed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterFragmentsPassed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1tessellationCycles/title",
          "value": "MTLCommonCounterTessellationCycles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1tessellationCycles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterTessellationCycles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter/title",
          "value": "MTLCommonCounter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1clipperPrimitivesOut/title",
          "value": "MTLCommonCounterClipperPrimitivesOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1clipperPrimitivesOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterClipperPrimitivesOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1totalCycles/title",
          "value": "MTLCommonCounterTotalCycles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1totalCycles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterTotalCycles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1postTessellationVertexCycles/title",
          "value": "MTLCommonCounterPostTessellationVertexCycles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1postTessellationVertexCycles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterPostTessellationVertexCycles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1fragmentCycles/title",
          "value": "MTLCommonCounterFragmentCycles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1fragmentCycles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterFragmentCycles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1clipperInvocations/title",
          "value": "MTLCommonCounterClipperInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1clipperInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterClipperInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1fragmentInvocations/title",
          "value": "MTLCommonCounterFragmentInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1fragmentInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterFragmentInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1vertexInvocations/title",
          "value": "MTLCommonCounterVertexInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1vertexInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterVertexInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1postTessellationVertexInvocations/title",
          "value": "MTLCommonCounterPostTessellationVertexInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommonCounter~1postTessellationVertexInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommonCounterPostTessellationVertexInvocations"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlcommoncounter/fragmentinvocations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlcommoncounter/fragmentinvocations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
