{
  "abstract": [
    {
      "text": "A mask that specifies a compressed font.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/compressedFontMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSFontTraitMask@NSCompressedFontMask",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "compressedFontMask"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSFontTraitMask",
        "text": "NSFontTraitMask"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCompressedFontMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "compressedFontMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "compressedFontMask"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSFontTraitMask",
              "text": "NSFontTraitMask"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask": {
      "abstract": [
        {
          "text": "Constants for isolating specific traits of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTraitMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontTraitMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/boldFontMask": {
      "abstract": [
        {
          "text": "A mask that specifies a bold font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boldFontMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontTraitMask",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/boldFontMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBoldFontMask"
        }
      ],
      "role": "symbol",
      "title": "boldFontMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask/boldfontmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/compressedFontMask": {
      "abstract": [
        {
          "text": "A mask that specifies a compressed font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compressedFontMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontTraitMask",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/compressedFontMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompressedFontMask"
        }
      ],
      "role": "symbol",
      "title": "compressedFontMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask/compressedfontmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/condensedFontMask": {
      "abstract": [
        {
          "text": "A mask that specifies a condensed font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "condensedFontMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontTraitMask",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/condensedFontMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCondensedFontMask"
        }
      ],
      "role": "symbol",
      "title": "condensedFontMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask/condensedfontmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/expandedFontMask": {
      "abstract": [
        {
          "text": "A mask that specifies an expanded font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expandedFontMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontTraitMask",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/expandedFontMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExpandedFontMask"
        }
      ],
      "role": "symbol",
      "title": "expandedFontMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask/expandedfontmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/fixedPitchFontMask": {
      "abstract": [
        {
          "text": "A mask that specifies a fixed pitch font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fixedPitchFontMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontTraitMask",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/fixedPitchFontMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFixedPitchFontMask"
        }
      ],
      "role": "symbol",
      "title": "fixedPitchFontMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask/fixedpitchfontmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/italicFontMask": {
      "abstract": [
        {
          "text": "A mask that specifies an italic font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "italicFontMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontTraitMask",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/italicFontMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSItalicFontMask"
        }
      ],
      "role": "symbol",
      "title": "italicFontMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask/italicfontmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/narrowFontMask": {
      "abstract": [
        {
          "text": "A mask that specifies a narrow font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "narrowFontMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontTraitMask",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/narrowFontMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNarrowFontMask"
        }
      ],
      "role": "symbol",
      "title": "narrowFontMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask/narrowfontmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/nonStandardCharacterSetFontMask": {
      "abstract": [
        {
          "text": "A mask that specifies a font containing a non-standard character set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonStandardCharacterSetFontMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontTraitMask",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/nonStandardCharacterSetFontMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNonStandardCharacterSetFontMask"
        }
      ],
      "role": "symbol",
      "title": "nonStandardCharacterSetFontMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask/nonstandardcharactersetfontmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/posterFontMask": {
      "abstract": [
        {
          "text": "A mask that specifies a poster-style font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "posterFontMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontTraitMask",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/posterFontMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPosterFontMask"
        }
      ],
      "role": "symbol",
      "title": "posterFontMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask/posterfontmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/smallCapsFontMask": {
      "abstract": [
        {
          "text": "A mask that specifies a small-caps font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smallCapsFontMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontTraitMask",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/smallCapsFontMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSmallCapsFontMask"
        }
      ],
      "role": "symbol",
      "title": "smallCapsFontMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask/smallcapsfontmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/unboldFontMask": {
      "abstract": [
        {
          "text": "A mask that specifies a font that is not bold.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unboldFontMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontTraitMask",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/unboldFontMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnboldFontMask"
        }
      ],
      "role": "symbol",
      "title": "unboldFontMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask/unboldfontmask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/unitalicFontMask": {
      "abstract": [
        {
          "text": "A mask that specifies a font that is not italic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unitalicFontMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontTraitMask",
          "text": "NSFontTraitMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/unitalicFontMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnitalicFontMask"
        }
      ],
      "role": "symbol",
      "title": "unitalicFontMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfonttraitmask/unitalicfontmask"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Trait-Masks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/boldFontMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/condensedFontMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/expandedFontMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/fixedPitchFontMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/italicFontMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/narrowFontMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/nonStandardCharacterSetFontMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/posterFontMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/smallCapsFontMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/unboldFontMask",
        "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/unitalicFontMask"
      ],
      "title": "Trait Masks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCompressedFontMask"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompressedFontMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Trait-Masks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/boldFontMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/condensedFontMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/expandedFontMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/fixedPitchFontMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/italicFontMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/narrowFontMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/nonStandardCharacterSetFontMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/posterFontMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/smallCapsFontMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/unboldFontMask",
                "doc://com.apple.appkit/documentation/AppKit/NSFontTraitMask/unitalicFontMask"
              ],
              "title": "Trait Masks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSCompressedFontMask"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1unitalicFontMask/title",
          "value": "NSUnitalicFontMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1unitalicFontMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnitalicFontMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1compressedFontMask/title",
          "value": "NSCompressedFontMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1compressedFontMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompressedFontMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1boldFontMask/title",
          "value": "NSBoldFontMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1boldFontMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBoldFontMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask/title",
          "value": "NSFontTraitMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTraitMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTraitMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1italicFontMask/title",
          "value": "NSItalicFontMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1italicFontMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSItalicFontMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1smallCapsFontMask/title",
          "value": "NSSmallCapsFontMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1smallCapsFontMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSmallCapsFontMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1condensedFontMask/title",
          "value": "NSCondensedFontMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1condensedFontMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCondensedFontMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1fixedPitchFontMask/title",
          "value": "NSFixedPitchFontMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1fixedPitchFontMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFixedPitchFontMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1expandedFontMask/title",
          "value": "NSExpandedFontMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1expandedFontMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExpandedFontMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1narrowFontMask/title",
          "value": "NSNarrowFontMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1narrowFontMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNarrowFontMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1posterFontMask/title",
          "value": "NSPosterFontMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1posterFontMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPosterFontMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1nonStandardCharacterSetFontMask/title",
          "value": "NSNonStandardCharacterSetFontMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1nonStandardCharacterSetFontMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNonStandardCharacterSetFontMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1unboldFontMask/title",
          "value": "NSUnboldFontMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontTraitMask~1unboldFontMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnboldFontMask"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfonttraitmask/compressedfontmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfonttraitmask/compressedfontmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
