{
  "abstract": [
    {
      "text": "The snapshot is out of sync due to a change of the current segment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason/currentSegmentChanged"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@AVPlayerIntegratedTimelineSnapshotsOutOfSyncReasonCurrentSegmentChanged",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "currentSegmentChanged"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason",
        "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReasonCurrentSegmentChanged"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "currentSegmentChanged"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "currentSegmentChanged"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason",
              "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason": {
      "abstract": [
        {
          "text": "Constants that represent the reason for an out-of-sync state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayerintegratedtimelinesnapshotsoutofsyncreason"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason/currentSegmentChanged": {
      "abstract": [
        {
          "text": "The snapshot is out of sync due to a change of the current segment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSegmentChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason",
          "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason/currentSegmentChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReasonCurrentSegmentChanged"
        }
      ],
      "role": "symbol",
      "title": "currentSegmentChanged",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayerintegratedtimelinesnapshotsoutofsyncreason/currentsegmentchanged"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason/loadedTimeRangesChanged": {
      "abstract": [
        {
          "text": "The snapshot is out of sync due to a change of the loaded time ranges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadedTimeRangesChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason",
          "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason/loadedTimeRangesChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReasonLoadedTimeRangesChanged"
        }
      ],
      "role": "symbol",
      "title": "loadedTimeRangesChanged",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayerintegratedtimelinesnapshotsoutofsyncreason/loadedtimerangeschanged"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason/segmentsChanged": {
      "abstract": [
        {
          "text": "The snapshot is out of sync due to a change of segments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "segmentsChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason",
          "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason/segmentsChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReasonSegmentsChanged"
        }
      ],
      "role": "symbol",
      "title": "segmentsChanged",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayerintegratedtimelinesnapshotsoutofsyncreason/segmentschanged"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-reasons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason/segmentsChanged",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason/loadedTimeRangesChanged"
      ],
      "title": "Getting the reasons"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReasonCurrentSegmentChanged"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReasonCurrentSegmentChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-reasons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason/segmentsChanged",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason/loadedTimeRangesChanged"
              ],
              "title": "Getting the reasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason",
                    "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReasonCurrentSegmentChanged"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason~1segmentsChanged/title",
          "value": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReasonSegmentsChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason~1segmentsChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReasonSegmentsChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason~1currentSegmentChanged/title",
          "value": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReasonCurrentSegmentChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason~1currentSegmentChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReasonCurrentSegmentChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason/title",
          "value": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason~1loadedTimeRangesChanged/title",
          "value": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReasonLoadedTimeRangesChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerIntegratedTimelineSnapshotsOutOfSyncReason~1loadedTimeRangesChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerIntegratedTimelineSnapshotsOutOfSyncReasonLoadedTimeRangesChanged"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avplayerintegratedtimelinesnapshotsoutofsyncreason/currentsegmentchanged"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avplayerintegratedtimelinesnapshotsoutofsyncreason/currentsegmentchanged"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
