{
  "abstract": [
    {
      "text": "An identifier for an elliptical workout.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/elliptical"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Intents",
    "externalID": "c:@INWorkoutNameIdentifierElliptical",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "elliptical"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
        "text": "INWorkoutNameIdentifier"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INWorkoutNameIdentifierElliptical"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "elliptical"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "elliptical"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
              "text": "INWorkoutNameIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier": {
      "abstract": [
        {
          "text": "Constants that indicate the type of workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutNameIdentifier",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/crosstraining": {
      "abstract": [
        {
          "text": "An identifier for a cross-training workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crosstraining"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/crosstraining",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierCrosstraining"
        }
      ],
      "role": "symbol",
      "title": "crosstraining",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/crosstraining"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/cycle": {
      "abstract": [
        {
          "text": "An identifier for a bicycling workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cycle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/cycle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierCycle"
        }
      ],
      "role": "symbol",
      "title": "cycle",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/cycle"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/dance": {
      "abstract": [
        {
          "text": "An identifier for a dance workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/dance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierDance"
        }
      ],
      "role": "symbol",
      "title": "dance",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/dance"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/elliptical": {
      "abstract": [
        {
          "text": "An identifier for an elliptical workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elliptical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/elliptical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierElliptical"
        }
      ],
      "role": "symbol",
      "title": "elliptical",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/elliptical"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/exercise": {
      "abstract": [
        {
          "text": "An identifier for a generic exercise program.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exercise"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/exercise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierExercise"
        }
      ],
      "role": "symbol",
      "title": "exercise",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/exercise"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/highIntensityIntervalTraining": {
      "abstract": [
        {
          "text": "An identifier for a high-intensity interval-training workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highIntensityIntervalTraining"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/highIntensityIntervalTraining",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierHighIntensityIntervalTraining"
        }
      ],
      "role": "symbol",
      "title": "highIntensityIntervalTraining",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/highintensityintervaltraining"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/hike": {
      "abstract": [
        {
          "text": "An identifier for a hike workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hike"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/hike",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierHike"
        }
      ],
      "role": "symbol",
      "title": "hike",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/hike"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/indoorcycle": {
      "abstract": [
        {
          "text": "An identifier for an indoor cycling workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indoorcycle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/indoorcycle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierIndoorcycle"
        }
      ],
      "role": "symbol",
      "title": "indoorcycle",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/indoorcycle"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/indoorrun": {
      "abstract": [
        {
          "text": "An identifier for an indoor running workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indoorrun"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/indoorrun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierIndoorrun"
        }
      ],
      "role": "symbol",
      "title": "indoorrun",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/indoorrun"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/indoorwalk": {
      "abstract": [
        {
          "text": "An identifier for an indoor walking workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indoorwalk"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/indoorwalk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierIndoorwalk"
        }
      ],
      "role": "symbol",
      "title": "indoorwalk",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/indoorwalk"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/move": {
      "abstract": [
        {
          "text": "An identifier for a movement-related workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "move"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/move",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierMove"
        }
      ],
      "role": "symbol",
      "title": "move",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/move"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/other": {
      "abstract": [
        {
          "text": "An identifier for a workout not specified by any other constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierOther"
        }
      ],
      "role": "symbol",
      "title": "other",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/other"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/rower": {
      "abstract": [
        {
          "text": "An identifier for a rowing workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/rower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierRower"
        }
      ],
      "role": "symbol",
      "title": "rower",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/rower"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/run": {
      "abstract": [
        {
          "text": "An identifier for an outdoor running workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "run"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/run",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierRun"
        }
      ],
      "role": "symbol",
      "title": "run",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/run"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/sit": {
      "abstract": [
        {
          "text": "An identifier for a sitting workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/sit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierSit"
        }
      ],
      "role": "symbol",
      "title": "sit",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/sit"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/stairs": {
      "abstract": [
        {
          "text": "An identifier for a stair-climbing workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stairs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
          "text": "INWorkoutNameIdentifier"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/stairs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutNameIdentifierStairs"
        }
      ],
      "role": "symbol",
      "title": "stairs",
      "type": "topic",
      "url": "/documentation/intents/inworkoutnameidentifier/stairs"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/crosstraining",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/cycle",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/dance",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/exercise",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/highIntensityIntervalTraining",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/hike",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/indoorcycle",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/indoorrun",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/indoorwalk",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/move",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/other",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/rower",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/run",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/sit",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/stairs"
      ],
      "title": "Identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INWorkoutNameIdentifierElliptical"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierElliptical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Identifiers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/crosstraining",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/cycle",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/dance",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/exercise",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/highIntensityIntervalTraining",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/hike",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/indoorcycle",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/indoorrun",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/indoorwalk",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/move",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/other",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/rower",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/run",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/sit",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier/stairs"
              ],
              "title": "Identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutNameIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@INWorkoutNameIdentifier",
                    "text": "INWorkoutNameIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INWorkoutNameIdentifierElliptical"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1exercise/title",
          "value": "INWorkoutNameIdentifierExercise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1exercise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierExercise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1cycle/title",
          "value": "INWorkoutNameIdentifierCycle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1cycle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierCycle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1highIntensityIntervalTraining/title",
          "value": "INWorkoutNameIdentifierHighIntensityIntervalTraining"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1highIntensityIntervalTraining/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierHighIntensityIntervalTraining"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1other/title",
          "value": "INWorkoutNameIdentifierOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1crosstraining/title",
          "value": "INWorkoutNameIdentifierCrosstraining"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1crosstraining/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierCrosstraining"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1move/title",
          "value": "INWorkoutNameIdentifierMove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1move/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierMove"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1dance/title",
          "value": "INWorkoutNameIdentifierDance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1dance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierDance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1sit/title",
          "value": "INWorkoutNameIdentifierSit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1sit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierSit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1indoorcycle/title",
          "value": "INWorkoutNameIdentifierIndoorcycle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1indoorcycle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierIndoorcycle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1indoorwalk/title",
          "value": "INWorkoutNameIdentifierIndoorwalk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1indoorwalk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierIndoorwalk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1stairs/title",
          "value": "INWorkoutNameIdentifierStairs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1stairs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierStairs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier/title",
          "value": "INWorkoutNameIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1indoorrun/title",
          "value": "INWorkoutNameIdentifierIndoorrun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1indoorrun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierIndoorrun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1rower/title",
          "value": "INWorkoutNameIdentifierRower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1rower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierRower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1run/title",
          "value": "INWorkoutNameIdentifierRun"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1run/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierRun"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1hike/title",
          "value": "INWorkoutNameIdentifierHike"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1hike/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierHike"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1elliptical/title",
          "value": "INWorkoutNameIdentifierElliptical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutNameIdentifier~1elliptical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutNameIdentifierElliptical"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inworkoutnameidentifier/elliptical"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inworkoutnameidentifier/elliptical"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
