{
  "abstract": [
    {
      "text": "An interface designed for an in-car experience.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/carPlay"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIUserInterfaceIdiom@UIUserInterfaceIdiomCarPlay",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "carPlay"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIUserInterfaceIdiomCarPlay"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIUserInterfaceIdiom.carPlay"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "carPlay"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom": {
      "abstract": [
        {
          "text": "Constants that indicate the interface type for the device or an object that has a trait environment, such as a view and view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiom"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/carPlay": {
      "abstract": [
        {
          "text": "An interface designed for an in-car experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "carPlay"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/carPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiomCarPlay"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.carPlay",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom/carplay"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/mac": {
      "abstract": [
        {
          "text": "An interface designed for the Mac.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mac"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/mac",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiomMac"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.mac",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom/mac"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/pad": {
      "abstract": [
        {
          "text": "An interface designed for iPad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pad"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/pad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiomPad"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.pad",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom/pad"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/phone": {
      "abstract": [
        {
          "text": "An interface designed for iPhone and iPod touch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/phone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiomPhone"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.phone",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom/phone"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/tv": {
      "abstract": [
        {
          "text": "An interface designed for tvOS and Apple TV.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tv"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/tv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiomTV"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.tv",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom/tv"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/unspecified": {
      "abstract": [
        {
          "text": "An unspecified idiom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiomUnspecified"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.unspecified",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom/unspecified"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/vision": {
      "abstract": [
        {
          "text": "An interface designed for visionOS and Apple Vision Pro.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vision"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/vision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiomVision"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.vision",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom/vision"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Idioms",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/unspecified",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/phone",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/pad",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/tv",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/mac",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/vision"
      ],
      "title": "Idioms"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIUserInterfaceIdiomCarPlay"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomCarPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Idioms",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/unspecified",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/phone",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/pad",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/tv",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/mac",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/vision"
              ],
              "title": "Idioms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIUserInterfaceIdiomCarPlay"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1carPlay/title",
          "value": "UIUserInterfaceIdiomCarPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1carPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomCarPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1mac/title",
          "value": "UIUserInterfaceIdiomMac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1mac/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomMac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1pad/title",
          "value": "UIUserInterfaceIdiomPad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1pad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomPad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1phone/title",
          "value": "UIUserInterfaceIdiomPhone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1phone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomPhone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1tv/title",
          "value": "UIUserInterfaceIdiomTV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1tv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomTV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom/title",
          "value": "UIUserInterfaceIdiom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1unspecified/title",
          "value": "UIUserInterfaceIdiomUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1vision/title",
          "value": "UIUserInterfaceIdiomVision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1vision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomVision"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiuserinterfaceidiom/carplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiuserinterfaceidiom/carplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
