{
  "abstract": [
    {
      "text": "Removes the symbol effect that matches the specified effect type, using the specified options and animation setting.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSImageView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeSymbolEffectOfType:options:animated:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSImageView(im)removeSymbolEffectOfType:options:animated:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "removeSymbolEffectOfType:options:animated:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "removeSymbolEffectOfType:options:animated:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "removeSymbolEffectOfType:options:animated:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "removeSymbolEffectOfType:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolEffect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSSymbolEffect",
              "text": "NSSymbolEffect"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "symbolEffect"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "options:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolEffectOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSSymbolEffectOptions",
              "text": "NSSymbolEffectOptions"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "animated:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "animated"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The symbol effect to match for removal.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "symbolEffect"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The options to use when removing the symbol effect.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Boolean value that indicates whether to animate the removal of a scale, appear, or disappear effect.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "animated"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageView": {
      "abstract": [
        {
          "text": "A display of image data in a frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageView"
        }
      ],
      "role": "symbol",
      "title": "NSImageView",
      "type": "topic",
      "url": "/documentation/appkit/nsimageview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageView/addSymbolEffect:": {
      "abstract": [
        {
          "text": "Adds a symbol effect to the image view with default options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageView/addSymbolEffect:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSymbolEffect:"
        }
      ],
      "role": "symbol",
      "title": "addSymbolEffect:",
      "type": "topic",
      "url": "/documentation/appkit/nsimageview/addsymboleffect:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageView/addSymbolEffect:options:": {
      "abstract": [
        {
          "text": "Adds a symbol effect to the image view with the specified options and default animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageView/addSymbolEffect:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:"
        }
      ],
      "role": "symbol",
      "title": "addSymbolEffect:options:",
      "type": "topic",
      "url": "/documentation/appkit/nsimageview/addsymboleffect:options:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageView/addSymbolEffect:options:animated:": {
      "abstract": [
        {
          "text": "Adds a symbol effect to the image view with the specified options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:animated:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageView/addSymbolEffect:options:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:animated:"
        }
      ],
      "role": "symbol",
      "title": "addSymbolEffect:options:animated:",
      "type": "topic",
      "url": "/documentation/appkit/nsimageview/addsymboleffect:options:animated:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeAllSymbolEffects": {
      "abstract": [
        {
          "text": "Removes all symbol effects from the image view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffects"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeAllSymbolEffects",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffects"
        }
      ],
      "role": "symbol",
      "title": "removeAllSymbolEffects",
      "type": "topic",
      "url": "/documentation/appkit/nsimageview/removeallsymboleffects"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeAllSymbolEffectsWithOptions:": {
      "abstract": [
        {
          "text": "Removes all symbol effects from the image view, using the specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeAllSymbolEffectsWithOptions:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:"
        }
      ],
      "role": "symbol",
      "title": "removeAllSymbolEffectsWithOptions:",
      "type": "topic",
      "url": "/documentation/appkit/nsimageview/removeallsymboleffectswithoptions:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeAllSymbolEffectsWithOptions:animated:": {
      "abstract": [
        {
          "text": "Removes all symbol effects from the image view, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:animated:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeAllSymbolEffectsWithOptions:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:animated:"
        }
      ],
      "role": "symbol",
      "title": "removeAllSymbolEffectsWithOptions:animated:",
      "type": "topic",
      "url": "/documentation/appkit/nsimageview/removeallsymboleffectswithoptions:animated:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeSymbolEffectOfType:": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified effect type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeSymbolEffectOfType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:"
        }
      ],
      "role": "symbol",
      "title": "removeSymbolEffectOfType:",
      "type": "topic",
      "url": "/documentation/appkit/nsimageview/removesymboleffectoftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeSymbolEffectOfType:options:": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified effect type, using the specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeSymbolEffectOfType:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:"
        }
      ],
      "role": "symbol",
      "title": "removeSymbolEffectOfType:options:",
      "type": "topic",
      "url": "/documentation/appkit/nsimageview/removesymboleffectoftype:options:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeSymbolEffectOfType:options:animated:": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified effect type, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:animated:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeSymbolEffectOfType:options:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:animated:"
        }
      ],
      "role": "symbol",
      "title": "removeSymbolEffectOfType:options:animated:",
      "type": "topic",
      "url": "/documentation/appkit/nsimageview/removesymboleffectoftype:options:animated:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageView/setSymbolImage:withContentTransition:": {
      "abstract": [
        {
          "text": "Sets a symbol image using the specified content-transition effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageView/setSymbolImage:withContentTransition:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:"
        }
      ],
      "role": "symbol",
      "title": "setSymbolImage:withContentTransition:",
      "type": "topic",
      "url": "/documentation/appkit/nsimageview/setsymbolimage:withcontenttransition:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageView/setSymbolImage:withContentTransition:options:": {
      "abstract": [
        {
          "text": "Sets a symbol image using the specified content-transition effect and options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:options:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageView/setSymbolImage:withContentTransition:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:options:"
        }
      ],
      "role": "symbol",
      "title": "setSymbolImage:withContentTransition:options:",
      "type": "topic",
      "url": "/documentation/appkit/nsimageview/setsymbolimage:withcontenttransition:options:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolEffect": {
      "abstract": [
        {
          "text": "An abstract base class for effects that you can apply to a symbol-based image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "@interface"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSymbolEffect"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolEffect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSymbolEffect",
      "type": "topic",
      "url": "/documentation/Symbols/NSSymbolEffect"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolEffectOptions": {
      "abstract": [
        {
          "text": "Options that configure how effects apply to symbol-based images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "@interface"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolEffectOptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSymbolEffectOptions",
      "type": "topic",
      "url": "/documentation/Symbols/NSSymbolEffectOptions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-symbol-effects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImageView/addSymbolEffect:",
        "doc://com.apple.appkit/documentation/AppKit/NSImageView/addSymbolEffect:options:",
        "doc://com.apple.appkit/documentation/AppKit/NSImageView/addSymbolEffect:options:animated:",
        "doc://com.apple.appkit/documentation/AppKit/NSImageView/setSymbolImage:withContentTransition:",
        "doc://com.apple.appkit/documentation/AppKit/NSImageView/setSymbolImage:withContentTransition:options:",
        "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeSymbolEffectOfType:",
        "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeSymbolEffectOfType:options:",
        "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeAllSymbolEffects",
        "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeAllSymbolEffectsWithOptions:",
        "doc://com.apple.appkit/documentation/AppKit/NSImageView/removeAllSymbolEffectsWithOptions:animated:"
      ],
      "title": "Configuring symbol effects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageView/title",
          "value": "NSImageView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsimageview/removesymboleffectoftype:options:animated:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
