{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy/downloadLazily"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSFileProviderContentPolicy@NSFileProviderContentPolicyDownloadLazily",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "downloadLazily"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFileProviderContentPolicyDownloadLazily"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSFileProviderContentPolicy.downloadLazily"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "downloadLazily"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderContentPolicy"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderContentPolicy"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderContentPolicy",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidercontentpolicy"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy/downloadEagerlyAndKeepDownloaded": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadEagerlyAndKeepDownloaded"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy/downloadEagerlyAndKeepDownloaded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderContentPolicyDownloadEagerlyAndKeepDownloaded"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderContentPolicy.downloadEagerlyAndKeepDownloaded",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidercontentpolicy/downloadeagerlyandkeepdownloaded"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy/downloadLazily": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadLazily"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy/downloadLazily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderContentPolicyDownloadLazily"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderContentPolicy.downloadLazily",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidercontentpolicy/downloadlazily"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy/downloadLazilyAndEvictOnRemoteUpdate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadLazilyAndEvictOnRemoteUpdate"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy/downloadLazilyAndEvictOnRemoteUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderContentPolicyDownloadLazilyAndEvictOnRemoteUpdate"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderContentPolicy.downloadLazilyAndEvictOnRemoteUpdate",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidercontentpolicy/downloadlazilyandevictonremoteupdate"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy/inherited": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inherited"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy/inherited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderContentPolicyInherited"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderContentPolicy.inherited",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidercontentpolicy/inherited"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Policies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy/downloadEagerlyAndKeepDownloaded",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy/downloadLazilyAndEvictOnRemoteUpdate",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy/inherited"
      ],
      "title": "Policies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFileProviderContentPolicyDownloadLazily"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderContentPolicyDownloadLazily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileprovider/documentation/FileProvider",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Policies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy/downloadEagerlyAndKeepDownloaded",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy/downloadLazilyAndEvictOnRemoteUpdate",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderContentPolicy/inherited"
              ],
              "title": "Policies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSFileProviderContentPolicyDownloadLazily"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderContentPolicy~1downloadLazily/title",
          "value": "NSFileProviderContentPolicyDownloadLazily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderContentPolicy~1downloadLazily/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderContentPolicyDownloadLazily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderContentPolicy~1inherited/title",
          "value": "NSFileProviderContentPolicyInherited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderContentPolicy~1inherited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderContentPolicyInherited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderContentPolicy~1downloadEagerlyAndKeepDownloaded/title",
          "value": "NSFileProviderContentPolicyDownloadEagerlyAndKeepDownloaded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderContentPolicy~1downloadEagerlyAndKeepDownloaded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderContentPolicyDownloadEagerlyAndKeepDownloaded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderContentPolicy/title",
          "value": "NSFileProviderContentPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderContentPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderContentPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderContentPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderContentPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderContentPolicy~1downloadLazilyAndEvictOnRemoteUpdate/title",
          "value": "NSFileProviderContentPolicyDownloadLazilyAndEvictOnRemoteUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderContentPolicy~1downloadLazilyAndEvictOnRemoteUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderContentPolicyDownloadLazilyAndEvictOnRemoteUpdate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidercontentpolicy/downloadlazily"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidercontentpolicy/downloadlazily"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
