{
  "abstract": [
    {
      "text": "The source color is subtracted from the destination color.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/subtract"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKBlendMode@SKBlendModeSubtract",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "subtract"
      }
    ],
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKBlendModeSubtract"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKBlendMode.subtract"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "subtract"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode": {
      "abstract": [
        {
          "text": "The modes that describe how the source and destination pixel colors are used to calculate the new destination color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKBlendMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKBlendMode"
        }
      ],
      "role": "symbol",
      "title": "SKBlendMode",
      "type": "topic",
      "url": "/documentation/spritekit/skblendmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/add": {
      "abstract": [
        {
          "text": "The source and destination colors are added together.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/add",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKBlendModeAdd"
        }
      ],
      "role": "symbol",
      "title": "SKBlendMode.add",
      "type": "topic",
      "url": "/documentation/spritekit/skblendmode/add"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/alpha": {
      "abstract": [
        {
          "text": "The source and destination colors are blended by multiplying the source alpha value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alpha"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/alpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKBlendModeAlpha"
        }
      ],
      "role": "symbol",
      "title": "SKBlendMode.alpha",
      "type": "topic",
      "url": "/documentation/spritekit/skblendmode/alpha"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/multiply": {
      "abstract": [
        {
          "text": "The source color is multiplied by the destination color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiply"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/multiply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKBlendModeMultiply"
        }
      ],
      "role": "symbol",
      "title": "SKBlendMode.multiply",
      "type": "topic",
      "url": "/documentation/spritekit/skblendmode/multiply"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/multiplyX2": {
      "abstract": [
        {
          "text": "The source color is multiplied by the destination color and then doubled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiplyX2"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/multiplyX2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKBlendModeMultiplyX2"
        }
      ],
      "role": "symbol",
      "title": "SKBlendMode.multiplyX2",
      "type": "topic",
      "url": "/documentation/spritekit/skblendmode/multiplyx2"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/replace": {
      "abstract": [
        {
          "text": "The source color replaces the destination color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replace"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/replace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKBlendModeReplace"
        }
      ],
      "role": "symbol",
      "title": "SKBlendMode.replace",
      "type": "topic",
      "url": "/documentation/spritekit/skblendmode/replace"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/screen": {
      "abstract": [
        {
          "text": "The source color is added to the destination color times the inverted source color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screen"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/screen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKBlendModeScreen"
        }
      ],
      "role": "symbol",
      "title": "SKBlendMode.screen",
      "type": "topic",
      "url": "/documentation/spritekit/skblendmode/screen"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/subtract": {
      "abstract": [
        {
          "text": "The source color is subtracted from the destination color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtract"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/subtract",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKBlendModeSubtract"
        }
      ],
      "role": "symbol",
      "title": "SKBlendMode.subtract",
      "type": "topic",
      "url": "/documentation/spritekit/skblendmode/subtract"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/alpha",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/add",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/multiply",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/multiplyX2",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/screen",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/replace"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKBlendModeSubtract"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKBlendModeSubtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.spritekit/documentation/SpriteKit",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/alpha",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/add",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/multiply",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/multiplyX2",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/screen",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKBlendMode/replace"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKBlendModeSubtract"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode~1add/title",
          "value": "SKBlendModeAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode~1add/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKBlendModeAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode~1multiply/title",
          "value": "SKBlendModeMultiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode~1multiply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKBlendModeMultiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode~1alpha/title",
          "value": "SKBlendModeAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode~1alpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKBlendModeAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode~1screen/title",
          "value": "SKBlendModeScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode~1screen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKBlendModeScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode~1replace/title",
          "value": "SKBlendModeReplace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode~1replace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKBlendModeReplace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode/title",
          "value": "SKBlendMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKBlendMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKBlendMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode~1subtract/title",
          "value": "SKBlendModeSubtract"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode~1subtract/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKBlendModeSubtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode~1multiplyX2/title",
          "value": "SKBlendModeMultiplyX2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKBlendMode~1multiplyX2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKBlendModeMultiplyX2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/skblendmode/subtract"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/skblendmode/subtract"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
