{
  "abstract": [
    {
      "text": "Return a variant icon for use on a variable background such as an animating Live Photo view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI",
        "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoBadgeOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoBadgeOptions/overContent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHLivePhotoBadgeOptions@PHLivePhotoBadgeOptionsOverContent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "overContent"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PHLivePhotoBadgeOptions",
        "text": "PHLivePhotoBadgeOptions"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHLivePhotoBadgeOptionsOverContent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "overContent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "overContent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoBadgeOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PHLivePhotoBadgeOptions",
              "text": "PHLivePhotoBadgeOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By default, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoView/livePhotoBadgeImage(options:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " returns a solid-color image suitable for use as a template image, which you can then tint for appropriate display against a specific background. If the background content is busy, animated, or unknown, add this option to instead obtain an icon (not suitable for use as a template image) that provides extra contrast for better readability.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoBadgeOptions": {
      "abstract": [
        {
          "text": "Options for the semantic use and display style of icons for badging Live Photo assets, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoView/livePhotoBadgeImage(options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoBadgeOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoBadgeOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoBadgeOptions"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoBadgeOptions",
      "type": "topic",
      "url": "/documentation/photosui/phlivephotobadgeoptions"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoBadgeOptions/liveOff": {
      "abstract": [
        {
          "text": "Return an icon for identifying assets whose additional Live Photo content is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "liveOff"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHLivePhotoBadgeOptions",
          "text": "PHLivePhotoBadgeOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoBadgeOptions/liveOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoBadgeOptionsLiveOff"
        }
      ],
      "role": "symbol",
      "title": "liveOff",
      "type": "topic",
      "url": "/documentation/photosui/phlivephotobadgeoptions/liveoff"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoBadgeOptions/overContent": {
      "abstract": [
        {
          "text": "Return a variant icon for use on a variable background such as an animating Live Photo view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHLivePhotoBadgeOptions",
          "text": "PHLivePhotoBadgeOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoBadgeOptions/overContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoBadgeOptionsOverContent"
        }
      ],
      "role": "symbol",
      "title": "overContent",
      "type": "topic",
      "url": "/documentation/photosui/phlivephotobadgeoptions/overcontent"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoView/livePhotoBadgeImage(options:)": {
      "abstract": [
        {
          "text": "Returns an icon image for the specified Live Photo semantic options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "livePhotoBadgeImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHLivePhotoBadgeOptions",
          "text": "PHLivePhotoBadgeOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoView/livePhotoBadgeImage(options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "livePhotoBadgeImageWithOptions:"
        }
      ],
      "role": "symbol",
      "title": "livePhotoBadgeImage(options:)",
      "type": "topic",
      "url": "/documentation/photosui/phlivephotoview/livephotobadgeimage(options:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoBadgeOptions/liveOff"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHLivePhotoBadgeOptionsOverContent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoBadgeOptionsOverContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/PhotosUI",
                "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoBadgeOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoBadgeOptions/liveOff"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PHLivePhotoBadgeOptionsOverContent"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHLivePhotoBadgeOptions~1overContent/title",
          "value": "PHLivePhotoBadgeOptionsOverContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHLivePhotoBadgeOptions~1overContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoBadgeOptionsOverContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHLivePhotoView~1livePhotoBadgeImage(options:)/title",
          "value": "livePhotoBadgeImageWithOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHLivePhotoView~1livePhotoBadgeImage(options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "livePhotoBadgeImageWithOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHLivePhotoBadgeOptions/title",
          "value": "PHLivePhotoBadgeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHLivePhotoBadgeOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoBadgeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHLivePhotoBadgeOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoBadgeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHLivePhotoBadgeOptions~1liveOff/title",
          "value": "PHLivePhotoBadgeOptionsLiveOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHLivePhotoBadgeOptions~1liveOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoBadgeOptionsLiveOff"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phlivephotobadgeoptions/overcontent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photosui/phlivephotobadgeoptions/overcontent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
