{
  "abstract": [
    {
      "text": "The operation is not complete",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusIncomplete"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CGImageSourceStatus@kCGImageStatusIncomplete",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "statusIncomplete"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCGImageStatusIncomplete"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CGImageSourceStatus.statusIncomplete"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "statusIncomplete"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus": {
      "abstract": [
        {
          "text": "The set of status values for images and image sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceStatus"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceStatus"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceStatus",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcestatus"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusComplete": {
      "abstract": [
        {
          "text": "The operation is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusComplete"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageStatusComplete"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceStatus.statusComplete",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcestatus/statuscomplete"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusIncomplete": {
      "abstract": [
        {
          "text": "The operation is not complete",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusIncomplete"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusIncomplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageStatusIncomplete"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceStatus.statusIncomplete",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcestatus/statusincomplete"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusInvalidData": {
      "abstract": [
        {
          "text": "The data is not valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusInvalidData"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusInvalidData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageStatusInvalidData"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceStatus.statusInvalidData",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcestatus/statusinvaliddata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusReadingHeader": {
      "abstract": [
        {
          "text": "The image source is reading the header.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusReadingHeader"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusReadingHeader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageStatusReadingHeader"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceStatus.statusReadingHeader",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcestatus/statusreadingheader"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusUnexpectedEOF": {
      "abstract": [
        {
          "text": "The end of the file occurred unexpectedly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusUnexpectedEOF"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusUnexpectedEOF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageStatusUnexpectedEOF"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceStatus.statusUnexpectedEOF",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcestatus/statusunexpectedeof"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusUnknownType": {
      "abstract": [
        {
          "text": "The image is an unknown type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusUnknownType"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusUnknownType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageStatusUnknownType"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceStatus.statusUnknownType",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcestatus/statusunknowntype"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Status-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusUnexpectedEOF",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusInvalidData",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusUnknownType",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusReadingHeader",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusComplete"
      ],
      "title": "Status Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCGImageStatusIncomplete"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageStatusIncomplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Status-Values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusUnexpectedEOF",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusInvalidData",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusUnknownType",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusReadingHeader",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus/statusComplete"
              ],
              "title": "Status Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCGImageStatusIncomplete"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus~1statusUnexpectedEOF/title",
          "value": "kCGImageStatusUnexpectedEOF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus~1statusUnexpectedEOF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageStatusUnexpectedEOF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus~1statusReadingHeader/title",
          "value": "kCGImageStatusReadingHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus~1statusReadingHeader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageStatusReadingHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus~1statusIncomplete/title",
          "value": "kCGImageStatusIncomplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus~1statusIncomplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageStatusIncomplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus~1statusComplete/title",
          "value": "kCGImageStatusComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus~1statusComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageStatusComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus/title",
          "value": "CGImageSourceStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus~1statusUnknownType/title",
          "value": "kCGImageStatusUnknownType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus~1statusUnknownType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageStatusUnknownType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus~1statusInvalidData/title",
          "value": "kCGImageStatusInvalidData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus~1statusInvalidData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageStatusInvalidData"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/cgimagesourcestatus/statusincomplete"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/cgimagesourcestatus/statusincomplete"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
