{
  "abstract": [
    {
      "text": "A property that tells the session to discover accessories within a specific Bluetooth range.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothRange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ASDiscoveryDescriptor(py)bluetoothRange",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bluetoothRange"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ASDiscoveryDescriptor",
        "text": "ASDiscoveryDescriptor"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@ASDiscoveryDescriptorRange",
        "text": "Range"
      }
    ],
    "modules": [
      {
        "name": "AccessorySetupKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "bluetoothRange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "bluetoothRange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bluetoothRange"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ASDiscoveryDescriptor",
              "text": "ASDiscoveryDescriptor"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ASDiscoveryDescriptorRange",
              "text": "Range"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/discovering-and-configuring-accessories"
      ]
    }
  ],
  "references": {
    "discovering-configuring-accessories-PageImage-card.png": {
      "alt": "An illustration that shows Bluetooth and Wi-Fi devices communicating.",
      "identifier": "discovering-configuring-accessories-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ab9450c2b7948ffea221e483d1b210d3/discovering-configuring-accessories-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/50cc817a2ebceed40a67b891238dd603/discovering-configuring-accessories-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit": {
      "abstract": [
        {
          "text": "Enable privacy-preserving discovery and configuration of accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AccessorySetupKit",
      "type": "topic",
      "url": "/documentation/accessorysetupkit"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASBluetoothCompanyIdentifier": {
      "abstract": [
        {
          "text": "The identifier of a Bluetooth accessory provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASBluetoothCompanyIdentifier"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASBluetoothCompanyIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASBluetoothCompanyIdentifier"
        }
      ],
      "role": "symbol",
      "title": "ASBluetoothCompanyIdentifier",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asbluetoothcompanyidentifier"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor": {
      "abstract": [
        {
          "text": "Descriptive traits used to discover accessories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASDiscoveryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASDiscoveryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "ASDiscoveryDescriptor",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range": {
      "abstract": [
        {
          "text": "The Bluetooth range in which to discover accessories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Range"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Range"
        }
      ],
      "role": "symbol",
      "title": "ASDiscoveryDescriptor.Range",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/range"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothCompanyIdentifier": {
      "abstract": [
        {
          "text": "The accessory’s 16-bit Bluetooth Company Identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothCompanyIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASBluetoothCompanyIdentifier",
          "text": "ASBluetoothCompanyIdentifier"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothCompanyIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothCompanyIdentifier"
        }
      ],
      "role": "symbol",
      "title": "bluetoothCompanyIdentifier",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothcompanyidentifier"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataBlob": {
      "abstract": [
        {
          "text": "A byte buffer that matches the accessory’s Bluetooth manufacturer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothManufacturerDataBlob"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataBlob",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothManufacturerDataBlob"
        }
      ],
      "role": "symbol",
      "title": "bluetoothManufacturerDataBlob",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothmanufacturerdatablob"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataMask": {
      "abstract": [
        {
          "text": "The accessory’s Bluetooth manufacturer data mask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothManufacturerDataMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothManufacturerDataMask"
        }
      ],
      "role": "symbol",
      "title": "bluetoothManufacturerDataMask",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothmanufacturerdatamask"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothNameSubstring": {
      "abstract": [
        {
          "text": "The accessory’s over-the-air Bluetooth name substring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothNameSubstring"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothNameSubstring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothNameSubstring"
        }
      ],
      "role": "symbol",
      "title": "bluetoothNameSubstring",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothnamesubstring"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothRange": {
      "abstract": [
        {
          "text": "A property that tells the session to discover accessories within a specific Bluetooth range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASDiscoveryDescriptor",
          "text": "ASDiscoveryDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ASDiscoveryDescriptorRange",
          "text": "Range"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothRange"
        }
      ],
      "role": "symbol",
      "title": "bluetoothRange",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothrange"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataBlob": {
      "abstract": [
        {
          "text": "A byte buffer that matches the accessory’s Bluetooth service data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothServiceDataBlob"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataBlob",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothServiceDataBlob"
        }
      ],
      "role": "symbol",
      "title": "bluetoothServiceDataBlob",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothservicedatablob"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataMask": {
      "abstract": [
        {
          "text": "The accessory’s Bluetooth service data mask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothServiceDataMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothServiceDataMask"
        }
      ],
      "role": "symbol",
      "title": "bluetoothServiceDataMask",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothservicedatamask"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceUUID": {
      "abstract": [
        {
          "text": "The accessory’s Bluetooth service UUID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothServiceUUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBUUID",
          "text": "CBUUID"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceUUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothServiceUUID"
        }
      ],
      "role": "symbol",
      "title": "bluetoothServiceUUID",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothserviceuuid"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/discovering-and-configuring-accessories": {
      "abstract": [
        {
          "text": "Detect nearby accessories and facilitate their setup.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/discovering-and-configuring-accessories",
      "images": [
        {
          "identifier": "discovering-configuring-accessories-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Discovering and configuring accessories",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/discovering-and-configuring-accessories"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Bluetooth-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothCompanyIdentifier",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASBluetoothCompanyIdentifier",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataBlob",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataMask",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataBlob",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataMask",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothNameSubstring",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceUUID",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range"
      ],
      "title": "Specifying Bluetooth properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "bluetoothRange"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Bluetooth-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothCompanyIdentifier",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASBluetoothCompanyIdentifier",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataBlob",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataMask",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataBlob",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataMask",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothNameSubstring",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceUUID",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range"
              ],
              "title": "Specifying Bluetooth properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@ASDiscoveryDescriptorRange",
                    "text": "ASDiscoveryDescriptorRange"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "bluetoothRange"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothManufacturerDataBlob/title",
          "value": "bluetoothManufacturerDataBlob"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothManufacturerDataBlob/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothManufacturerDataBlob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothRange/title",
          "value": "bluetoothRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothServiceUUID/title",
          "value": "bluetoothServiceUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothServiceUUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothServiceUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor/title",
          "value": "ASDiscoveryDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASDiscoveryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASDiscoveryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1Range/title",
          "value": "ASDiscoveryDescriptorRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1Range/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASDiscoveryDescriptorRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1Range/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASDiscoveryDescriptorRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothNameSubstring/title",
          "value": "bluetoothNameSubstring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothNameSubstring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothNameSubstring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothManufacturerDataMask/title",
          "value": "bluetoothManufacturerDataMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothManufacturerDataMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothManufacturerDataMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothServiceDataBlob/title",
          "value": "bluetoothServiceDataBlob"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothServiceDataBlob/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothServiceDataBlob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASBluetoothCompanyIdentifier/title",
          "value": "ASBluetoothCompanyIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASBluetoothCompanyIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASBluetoothCompanyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASBluetoothCompanyIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASBluetoothCompanyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothCompanyIdentifier/title",
          "value": "bluetoothCompanyIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothCompanyIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothCompanyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothServiceDataMask/title",
          "value": "bluetoothServiceDataMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothServiceDataMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothServiceDataMask"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothrange"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothrange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
