{
  "abstract": [
    {
      "text": "The Bluetooth range in which to discover accessories.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AccessorySetupKit",
    "externalID": "c:@E@ASDiscoveryDescriptorRange",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Range"
      }
    ],
    "modules": [
      {
        "name": "AccessorySetupKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Range"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ASDiscoveryDescriptor.Range"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Range"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit": {
      "abstract": [
        {
          "text": "Enable privacy-preserving discovery and configuration of accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AccessorySetupKit",
      "type": "topic",
      "url": "/documentation/accessorysetupkit"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASBluetoothCompanyIdentifier": {
      "abstract": [
        {
          "text": "The identifier of a Bluetooth accessory provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASBluetoothCompanyIdentifier"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASBluetoothCompanyIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASBluetoothCompanyIdentifier"
        }
      ],
      "role": "symbol",
      "title": "ASBluetoothCompanyIdentifier",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asbluetoothcompanyidentifier"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor": {
      "abstract": [
        {
          "text": "Descriptive traits used to discover accessories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASDiscoveryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASDiscoveryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "ASDiscoveryDescriptor",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range": {
      "abstract": [
        {
          "text": "The Bluetooth range in which to discover accessories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Range"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Range"
        }
      ],
      "role": "symbol",
      "title": "ASDiscoveryDescriptor.Range",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/range"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/range/equatable-implementations"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/RawRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/RawRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RawRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/range/rawrepresentable-implementations"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/default": {
      "abstract": [
        {
          "text": "The default range in which to discover accessories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASDiscoveryDescriptorRangeDefault"
        }
      ],
      "role": "symbol",
      "title": "ASDiscoveryDescriptor.Range.default",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/range/default"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/immediate": {
      "abstract": [
        {
          "text": "A range in the immediate vicinity of the device performing accessory discovery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "immediate"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/immediate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASDiscoveryDescriptorRangeImmediate"
        }
      ],
      "role": "symbol",
      "title": "ASDiscoveryDescriptor.Range.immediate",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/range/immediate"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/range/init(rawvalue:)"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothCompanyIdentifier": {
      "abstract": [
        {
          "text": "The accessory’s 16-bit Bluetooth Company Identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothCompanyIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ASBluetoothCompanyIdentifier",
          "text": "ASBluetoothCompanyIdentifier"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothCompanyIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothCompanyIdentifier"
        }
      ],
      "role": "symbol",
      "title": "bluetoothCompanyIdentifier",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothcompanyidentifier"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataBlob": {
      "abstract": [
        {
          "text": "A byte buffer that matches the accessory’s Bluetooth manufacturer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothManufacturerDataBlob"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataBlob",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothManufacturerDataBlob"
        }
      ],
      "role": "symbol",
      "title": "bluetoothManufacturerDataBlob",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothmanufacturerdatablob"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataMask": {
      "abstract": [
        {
          "text": "The accessory’s Bluetooth manufacturer data mask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothManufacturerDataMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothManufacturerDataMask"
        }
      ],
      "role": "symbol",
      "title": "bluetoothManufacturerDataMask",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothmanufacturerdatamask"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothNameSubstring": {
      "abstract": [
        {
          "text": "The accessory’s over-the-air Bluetooth name substring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothNameSubstring"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothNameSubstring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothNameSubstring"
        }
      ],
      "role": "symbol",
      "title": "bluetoothNameSubstring",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothnamesubstring"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothRange": {
      "abstract": [
        {
          "text": "A property that tells the session to discover accessories within a specific Bluetooth range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASDiscoveryDescriptor",
          "text": "ASDiscoveryDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ASDiscoveryDescriptorRange",
          "text": "Range"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothRange"
        }
      ],
      "role": "symbol",
      "title": "bluetoothRange",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothrange"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataBlob": {
      "abstract": [
        {
          "text": "A byte buffer that matches the accessory’s Bluetooth service data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothServiceDataBlob"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataBlob",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothServiceDataBlob"
        }
      ],
      "role": "symbol",
      "title": "bluetoothServiceDataBlob",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothservicedatablob"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataMask": {
      "abstract": [
        {
          "text": "The accessory’s Bluetooth service data mask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothServiceDataMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothServiceDataMask"
        }
      ],
      "role": "symbol",
      "title": "bluetoothServiceDataMask",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothservicedatamask"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceUUID": {
      "abstract": [
        {
          "text": "The accessory’s Bluetooth service UUID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothServiceUUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBUUID",
          "text": "CBUUID"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceUUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bluetoothServiceUUID"
        }
      ],
      "role": "symbol",
      "title": "bluetoothServiceUUID",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asdiscoverydescriptor/bluetoothserviceuuid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Bluetooth-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothCompanyIdentifier",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASBluetoothCompanyIdentifier",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataBlob",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataMask",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataBlob",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataMask",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothNameSubstring",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceUUID",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothRange"
      ],
      "title": "Specifying Bluetooth properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-options-instance",
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/init(rawValue:)"
      ],
      "title": "Creating an options instance"
    },
    {
      "anchor": "Bluetooth-options",
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/default",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/immediate"
      ],
      "title": "Bluetooth options"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/Equatable-Implementations",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/RawRepresentable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ASDiscoveryDescriptorRange"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASDiscoveryDescriptorRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASDiscoveryDescriptorRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Bluetooth-options",
              "identifiers": [
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/default",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/Range/immediate"
              ],
              "title": "Bluetooth options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Bluetooth-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothCompanyIdentifier",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASBluetoothCompanyIdentifier",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataBlob",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothManufacturerDataMask",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataBlob",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceDataMask",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothNameSubstring",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothServiceUUID",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASDiscoveryDescriptor/bluetoothRange"
              ],
              "title": "Specifying Bluetooth properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ASDiscoveryDescriptorRange"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothManufacturerDataBlob/title",
          "value": "bluetoothManufacturerDataBlob"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothManufacturerDataBlob/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothManufacturerDataBlob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothServiceUUID/title",
          "value": "bluetoothServiceUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothServiceUUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothServiceUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothServiceDataBlob/title",
          "value": "bluetoothServiceDataBlob"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothServiceDataBlob/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothServiceDataBlob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor/title",
          "value": "ASDiscoveryDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASDiscoveryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASDiscoveryDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1Range/title",
          "value": "ASDiscoveryDescriptorRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1Range/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASDiscoveryDescriptorRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1Range/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASDiscoveryDescriptorRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASBluetoothCompanyIdentifier/title",
          "value": "ASBluetoothCompanyIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASBluetoothCompanyIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASBluetoothCompanyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASBluetoothCompanyIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASBluetoothCompanyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1Range~1immediate/title",
          "value": "ASDiscoveryDescriptorRangeImmediate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1Range~1immediate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASDiscoveryDescriptorRangeImmediate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothNameSubstring/title",
          "value": "bluetoothNameSubstring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothNameSubstring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothNameSubstring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothCompanyIdentifier/title",
          "value": "bluetoothCompanyIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothCompanyIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothCompanyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothServiceDataMask/title",
          "value": "bluetoothServiceDataMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothServiceDataMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothServiceDataMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1Range~1default/title",
          "value": "ASDiscoveryDescriptorRangeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1Range~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASDiscoveryDescriptorRangeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothManufacturerDataMask/title",
          "value": "bluetoothManufacturerDataMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothManufacturerDataMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothManufacturerDataMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothRange/title",
          "value": "bluetoothRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASDiscoveryDescriptor~1bluetoothRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bluetoothRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessorysetupkit/asdiscoverydescriptor/range"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessorysetupkit/asdiscoverydescriptor/range"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
