{
  "abstract": [
    {
      "text": "An indicator that the app lacks access to use the framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis",
        "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalysisPolicy"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalysisPolicy/disabled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCSensitivityAnalysisPolicy@SCSensitivityAnalysisPolicyDisabled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "disabled"
      }
    ],
    "modules": [
      {
        "name": "SensitiveContentAnalysis"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCSensitivityAnalysisPolicyDisabled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SCSensitivityAnalysisPolicy.disabled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "disabled"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/detecting-nudity-in-media-and-providing-intervention-options"
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalyzer/analysisPolicy",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is this value,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the framework doesn’t detect nudity. The system disables sensitive content analysis",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "under any of the following conditions:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The app lacks the necessary ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.sensitivecontentanalysis.client",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "entitlement.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Neither the Sensitive Content Warning user preference nor the Communication Safety",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "parental control in Screen Time are active.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The user disables the Sensitive Content Warnings toggle in your app’s Settings.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis": {
      "abstract": [
        {
          "text": "Provide a safer experience in your app by detecting and alerting users to nudity",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "in images and videos before displaying them onscreen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis",
      "kind": "symbol",
      "role": "collection",
      "title": "SensitiveContentAnalysis",
      "type": "topic",
      "url": "/documentation/sensitivecontentanalysis"
    },
    "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalysisPolicy": {
      "abstract": [
        {
          "text": "Configurations that represent the way the framework checks for sensitive content",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and how the app responds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCSensitivityAnalysisPolicy"
        }
      ],
      "identifier": "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalysisPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCSensitivityAnalysisPolicy"
        }
      ],
      "role": "symbol",
      "title": "SCSensitivityAnalysisPolicy",
      "type": "topic",
      "url": "/documentation/sensitivecontentanalysis/scsensitivityanalysispolicy"
    },
    "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalysisPolicy/descriptiveInterventions": {
      "abstract": [
        {
          "text": "An indicator that user preference requests overt detection of sensitive content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptiveInterventions"
        }
      ],
      "identifier": "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalysisPolicy/descriptiveInterventions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCSensitivityAnalysisPolicyDescriptiveInterventions"
        }
      ],
      "role": "symbol",
      "title": "SCSensitivityAnalysisPolicy.descriptiveInterventions",
      "type": "topic",
      "url": "/documentation/sensitivecontentanalysis/scsensitivityanalysispolicy/descriptiveinterventions"
    },
    "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalysisPolicy/disabled": {
      "abstract": [
        {
          "text": "An indicator that the app lacks access to use the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disabled"
        }
      ],
      "identifier": "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalysisPolicy/disabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCSensitivityAnalysisPolicyDisabled"
        }
      ],
      "role": "symbol",
      "title": "SCSensitivityAnalysisPolicy.disabled",
      "type": "topic",
      "url": "/documentation/sensitivecontentanalysis/scsensitivityanalysispolicy/disabled"
    },
    "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalysisPolicy/simpleInterventions": {
      "abstract": [
        {
          "text": "An indicator that user preference requests discrete detection of sensitive content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simpleInterventions"
        }
      ],
      "identifier": "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalysisPolicy/simpleInterventions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCSensitivityAnalysisPolicySimpleInterventions"
        }
      ],
      "role": "symbol",
      "title": "SCSensitivityAnalysisPolicy.simpleInterventions",
      "type": "topic",
      "url": "/documentation/sensitivecontentanalysis/scsensitivityanalysispolicy/simpleinterventions"
    },
    "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalyzer/analysisPolicy": {
      "abstract": [
        {
          "text": "A property that determines if the app detects nudity and how the app responds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "analysisPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCSensitivityAnalysisPolicy",
          "text": "SCSensitivityAnalysisPolicy"
        }
      ],
      "identifier": "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalyzer/analysisPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "analysisPolicy"
        }
      ],
      "role": "symbol",
      "title": "analysisPolicy",
      "type": "topic",
      "url": "/documentation/sensitivecontentanalysis/scsensitivityanalyzer/analysispolicy"
    },
    "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/detecting-nudity-in-media-and-providing-intervention-options": {
      "abstract": [
        {
          "text": "Alert people before displaying images or video that might be sensitive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/detecting-nudity-in-media-and-providing-intervention-options",
      "kind": "article",
      "role": "article",
      "title": "Detecting nudity in media and providing intervention options",
      "type": "topic",
      "url": "/documentation/sensitivecontentanalysis/detecting-nudity-in-media-and-providing-intervention-options"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.sensitivecontentanalysis.client": {
      "abstract": [
        {
          "text": "A code-signing entitlement that enables an app to detect nudity in images and video.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.sensitivecontentanalysis.client",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.sensitivecontentanalysis.client",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.sensitivecontentanalysis.client"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Checking-and-intervention-strategies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalysisPolicy/simpleInterventions",
        "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalysisPolicy/descriptiveInterventions"
      ],
      "title": "Checking and intervention strategies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCSensitivityAnalysisPolicyDisabled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCSensitivityAnalysisPolicyDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis",
                "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalysisPolicy"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Checking-and-intervention-strategies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalysisPolicy/simpleInterventions",
                "doc://com.apple.SensitiveContentAnalysis/documentation/SensitiveContentAnalysis/SCSensitivityAnalysisPolicy/descriptiveInterventions"
              ],
              "title": "Checking and intervention strategies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SCSensitivityAnalysisPolicyDisabled"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.SensitiveContentAnalysis~1documentation~1SensitiveContentAnalysis~1SCSensitivityAnalyzer~1analysisPolicy/title",
          "value": "analysisPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.SensitiveContentAnalysis~1documentation~1SensitiveContentAnalysis~1SCSensitivityAnalyzer~1analysisPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "analysisPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.SensitiveContentAnalysis~1documentation~1SensitiveContentAnalysis~1SCSensitivityAnalysisPolicy~1descriptiveInterventions/title",
          "value": "SCSensitivityAnalysisPolicyDescriptiveInterventions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.SensitiveContentAnalysis~1documentation~1SensitiveContentAnalysis~1SCSensitivityAnalysisPolicy~1descriptiveInterventions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCSensitivityAnalysisPolicyDescriptiveInterventions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.SensitiveContentAnalysis~1documentation~1SensitiveContentAnalysis~1SCSensitivityAnalysisPolicy~1simpleInterventions/title",
          "value": "SCSensitivityAnalysisPolicySimpleInterventions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.SensitiveContentAnalysis~1documentation~1SensitiveContentAnalysis~1SCSensitivityAnalysisPolicy~1simpleInterventions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCSensitivityAnalysisPolicySimpleInterventions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.SensitiveContentAnalysis~1documentation~1SensitiveContentAnalysis~1SCSensitivityAnalysisPolicy~1disabled/title",
          "value": "SCSensitivityAnalysisPolicyDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.SensitiveContentAnalysis~1documentation~1SensitiveContentAnalysis~1SCSensitivityAnalysisPolicy~1disabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCSensitivityAnalysisPolicyDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.SensitiveContentAnalysis~1documentation~1SensitiveContentAnalysis~1SCSensitivityAnalysisPolicy/title",
          "value": "SCSensitivityAnalysisPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.SensitiveContentAnalysis~1documentation~1SensitiveContentAnalysis~1SCSensitivityAnalysisPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCSensitivityAnalysisPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.SensitiveContentAnalysis~1documentation~1SensitiveContentAnalysis~1SCSensitivityAnalysisPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCSensitivityAnalysisPolicy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensitivecontentanalysis/scsensitivityanalysispolicy/disabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensitivecontentanalysis/scsensitivityanalysispolicy/disabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
