{
  "abstract": [
    {
      "text": "All flags are clear.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/kAudioChannelFlags_AllOff"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AudioChannelFlags@kAudioChannelFlags_AllOff",
    "fragments": [
      {
        "kind": "identifier",
        "text": "kAudioChannelFlags_AllOff"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioChannelFlags_AllOff"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.4",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "kAudioChannelFlags_AllOff"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "kAudioChannelFlags_AllOff"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags": {
      "abstract": [
        {
          "text": "Constants that define the audio channel flags of an audio channel description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelFlags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelflags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/kAudioChannelFlags_AllOff": {
      "abstract": [
        {
          "text": "All flags are clear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAudioChannelFlags_AllOff"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/kAudioChannelFlags_AllOff",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAudioChannelFlags_AllOff",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelflags/kaudiochannelflags_alloff"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/meters": {
      "abstract": [
        {
          "text": "A flag that indicates that unit values are in meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelFlags",
          "text": "AudioChannelFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/meters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelFlags_Meters"
        }
      ],
      "role": "symbol",
      "title": "meters",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelflags/meters"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/rectangularCoordinates": {
      "abstract": [
        {
          "text": "A flag that indicates the channel uses the speaker position’s cartesian coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rectangularCoordinates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelFlags",
          "text": "AudioChannelFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/rectangularCoordinates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelFlags_RectangularCoordinates"
        }
      ],
      "role": "symbol",
      "title": "rectangularCoordinates",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelflags/rectangularcoordinates"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/sphericalCoordinates": {
      "abstract": [
        {
          "text": "A flag that indicates the channel uses the speaker position’s spherical coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sphericalCoordinates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelFlags",
          "text": "AudioChannelFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/sphericalCoordinates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelFlags_SphericalCoordinates"
        }
      ],
      "role": "symbol",
      "title": "sphericalCoordinates",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelflags/sphericalcoordinates"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Flags",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/meters",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/rectangularCoordinates",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelFlags/sphericalCoordinates"
      ],
      "title": "Flags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags/title",
          "value": "AudioChannelFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags~1meters/title",
          "value": "kAudioChannelFlags_Meters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags~1meters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelFlags_Meters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags~1sphericalCoordinates/title",
          "value": "kAudioChannelFlags_SphericalCoordinates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags~1sphericalCoordinates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelFlags_SphericalCoordinates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags~1rectangularCoordinates/title",
          "value": "kAudioChannelFlags_RectangularCoordinates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelFlags~1rectangularCoordinates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelFlags_RectangularCoordinates"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/audiochannelflags/kaudiochannelflags_alloff"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
