{
  "abstract": [
    {
      "text": "The system doesn’t support the platform for the attribution API call.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This has been replaced by functionality in AdServices.framework's AAAttribution class.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iad/documentation/iAd",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/unsupportedPlatform"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ADClientError@ADClientErrorUnsupportedPlatform",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unsupportedPlatform"
      }
    ],
    "modules": [
      {
        "name": "iAd"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ADClientErrorUnsupportedPlatform"
      }
    ],
    "platforms": [],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ADClientError.Code.unsupportedPlatform"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unsupportedPlatform"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Search Ads Attribution API only supports iOS and iPadOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iad/documentation/iAd": {
      "abstract": [
        {
          "text": "The Apple Search Ads iAd Attribution API is a legacy framework for attributing app data that originates from Apple Search Ads campaigns on iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd",
      "kind": "symbol",
      "role": "collection",
      "title": "iAd",
      "type": "topic",
      "url": "/documentation/iad"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-c.enum/ADClientErrorLimitAdTracking": {
      "abstract": [
        {
          "text": "Limited ad tracking is in an enabled state for the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ADClientErrorLimitAdTracking"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-c.enum/ADClientErrorLimitAdTracking",
      "kind": "symbol",
      "role": "symbol",
      "title": "ADClientErrorLimitAdTracking",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-c.enum/adclienterrorlimitadtracking"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct": {
      "abstract": [
        {
          "text": "The group of error codes that pass from the attribution response to the completion handler block.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ADClientError"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientError"
        }
      ],
      "role": "symbol",
      "title": "ADClientError",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code": {
      "abstract": [
        {
          "text": "The error codes that pass from the attribution response to the completion handler.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ADClientError.Code",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/code"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/corruptResponse": {
      "abstract": [
        {
          "text": "The response from the attribution server is corrupt.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "corruptResponse"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/corruptResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientErrorCorruptResponse"
        }
      ],
      "role": "symbol",
      "title": "ADClientError.Code.corruptResponse",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/code/corruptresponse"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/limitAdTracking": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limitAdTracking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC13ADClientErrorLeV",
          "text": "ADClientError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ADClientError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/limitAdTracking",
      "kind": "symbol",
      "role": "symbol",
      "title": "limitAdTracking",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/code/limitadtracking"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/missingData": {
      "abstract": [
        {
          "text": "The downloaded app has a payload without enough data to perform an attribution check.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingData"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/missingData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientErrorMissingData"
        }
      ],
      "role": "symbol",
      "title": "ADClientError.Code.missingData",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/code/missingdata"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/requestClientError": {
      "abstract": [
        {
          "text": "The response from the attribution server has an HTTP 4xx status code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestClientError"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/requestClientError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientErrorRequestClientError"
        }
      ],
      "role": "symbol",
      "title": "ADClientError.Code.requestClientError",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/code/requestclienterror"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/requestNetworkError": {
      "abstract": [
        {
          "text": "The communication with the attribution server has a network error.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestNetworkError"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/requestNetworkError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientErrorRequestNetworkError"
        }
      ],
      "role": "symbol",
      "title": "ADClientError.Code.requestNetworkError",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/code/requestnetworkerror"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/requestServerError": {
      "abstract": [
        {
          "text": "The response from the attribution server has an HTTP 5xx status code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestServerError"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/requestServerError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientErrorRequestServerError"
        }
      ],
      "role": "symbol",
      "title": "ADClientError.Code.requestServerError",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/code/requestservererror"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/trackingRestrictedOrDenied": {
      "abstract": [
        {
          "text": "The user has a restricted status or has denied tracking for the calling app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackingRestrictedOrDenied"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/trackingRestrictedOrDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientErrorTrackingRestrictedOrDenied"
        }
      ],
      "role": "symbol",
      "title": "ADClientError.Code.trackingRestrictedOrDenied",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/code/trackingrestrictedordenied"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "The response from the attribution server has an unknown error.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "ADClientError.Code.unknown",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/code/unknown"
    },
    "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/unsupportedPlatform": {
      "abstract": [
        {
          "text": "The system doesn’t support the platform for the attribution API call.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedPlatform"
        }
      ],
      "identifier": "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/unsupportedPlatform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ADClientErrorUnsupportedPlatform"
        }
      ],
      "role": "symbol",
      "title": "ADClientError.Code.unsupportedPlatform",
      "type": "topic",
      "url": "/documentation/iad/adclienterror-swift.struct/code/unsupportedplatform"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/corruptResponse",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/requestClientError",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/requestNetworkError",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/requestServerError",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/trackingRestrictedOrDenied",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/missingData",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/unknown",
        "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/limitAdTracking"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": []
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ADClientErrorUnsupportedPlatform"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientErrorUnsupportedPlatform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iad/documentation/iAd",
                "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/corruptResponse",
                "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/requestClientError",
                "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/requestNetworkError",
                "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/requestServerError",
                "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/trackingRestrictedOrDenied",
                "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/missingData",
                "doc://com.apple.iad/documentation/iAd/ADClientError-swift.struct/Code/unknown",
                "doc://com.apple.iad/documentation/iAd/ADClientError-c.enum/ADClientErrorLimitAdTracking"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ADClientErrorUnsupportedPlatform"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This has been replaced by functionality in AdServices.framework's AAAttribution class.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1unsupportedPlatform/title",
          "value": "ADClientErrorUnsupportedPlatform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1unsupportedPlatform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientErrorUnsupportedPlatform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1requestClientError/title",
          "value": "ADClientErrorRequestClientError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1requestClientError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientErrorRequestClientError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1trackingRestrictedOrDenied/title",
          "value": "ADClientErrorTrackingRestrictedOrDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1trackingRestrictedOrDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientErrorTrackingRestrictedOrDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code/title",
          "value": "ADClientError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1requestNetworkError/title",
          "value": "ADClientErrorRequestNetworkError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1requestNetworkError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientErrorRequestNetworkError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1corruptResponse/title",
          "value": "ADClientErrorCorruptResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1corruptResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientErrorCorruptResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1requestServerError/title",
          "value": "ADClientErrorRequestServerError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1requestServerError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientErrorRequestServerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1unknown/title",
          "value": "ADClientErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1missingData/title",
          "value": "ADClientErrorMissingData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iad~1documentation~1iAd~1ADClientError-swift.struct~1Code~1missingData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ADClientErrorMissingData"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iad/adclienterror-swift.struct/code/unsupportedplatform"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iad/adclienterror-swift.struct/code/unsupportedplatform"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
