{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/init(hostUserData:beatAndTempoProc:musicalTimeLocationProc:transportStateProc:transportStateProc2:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So16HostCallbackInfoV12hostUserData16beatAndTempoProc019musicalTimeLocationJ0014transportStateJ00nO5Proc2ABSvSg_s5Int32VAH_SpySdGSgALtXCSgAjH_Spys6UInt32VGSgSpySfGSgAqLtXCSgAjH_Spy6Darwin0S7BooleanVGSgAyly2LtXCSgAjH_A3yly2LtXCSgtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "hostUserData"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "beatAndTempoProc"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@HostCallback_GetBeatAndTempo",
        "text": "HostCallback_GetBeatAndTempo"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "musicalTimeLocationProc"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@HostCallback_GetMusicalTimeLocation",
        "text": "HostCallback_GetMusicalTimeLocation"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "transportStateProc"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@HostCallback_GetTransportState",
        "text": "HostCallback_GetTransportState"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "transportStateProc2"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@HostCallback_GetTransportState2",
        "text": "HostCallback_GetTransportState2"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(hostUserData:beatAndTempoProc:musicalTimeLocationProc:transportStateProc:transportStateProc2:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "hostUserData"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "beatAndTempoProc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetBeatAndTempo",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@HostCallback_GetBeatAndTempo",
              "text": "HostCallback_GetBeatAndTempo"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "musicalTimeLocationProc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetMusicalTimeLocation",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@HostCallback_GetMusicalTimeLocation",
              "text": "HostCallback_GetMusicalTimeLocation"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "transportStateProc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetTransportState",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@HostCallback_GetTransportState",
              "text": "HostCallback_GetTransportState"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "transportStateProc2"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetTransportState2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@HostCallback_GetTransportState2",
              "text": "HostCallback_GetTransportState2"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo": {
      "abstract": [
        {
          "text": "The time- and transport-related callback functions for an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostCallbackInfo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostCallbackInfo"
        }
      ],
      "role": "symbol",
      "title": "HostCallbackInfo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallbackinfo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/init(hostUserData:beatAndTempoProc:musicalTimeLocationProc:transportStateProc:transportStateProc2:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "hostUserData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "beatAndTempoProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HostCallback_GetBeatAndTempo",
          "text": "HostCallback_GetBeatAndTempo"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "musicalTimeLocationProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HostCallback_GetMusicalTimeLocation",
          "text": "HostCallback_GetMusicalTimeLocation"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "transportStateProc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HostCallback_GetTransportState",
          "text": "HostCallback_GetTransportState"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "transportStateProc2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HostCallback_GetTransportState2",
          "text": "HostCallback_GetTransportState2"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallbackInfo/init(hostUserData:beatAndTempoProc:musicalTimeLocationProc:transportStateProc:transportStateProc2:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(hostUserData:beatAndTempoProc:musicalTimeLocationProc:transportStateProc:transportStateProc2:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallbackinfo/init(hostuserdata:beatandtempoproc:musicaltimelocationproc:transportstateproc:transportstateproc2:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetBeatAndTempo": {
      "abstract": [
        {
          "text": "When called by the system, provides beat and tempo information to an audio unit from a host application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostCallback_GetBeatAndTempo"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetBeatAndTempo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostCallback_GetBeatAndTempo"
        }
      ],
      "role": "symbol",
      "title": "HostCallback_GetBeatAndTempo",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallback_getbeatandtempo"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetMusicalTimeLocation": {
      "abstract": [
        {
          "text": "When called by the system, provides musical timing information to an audio unit from a host application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostCallback_GetMusicalTimeLocation"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetMusicalTimeLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostCallback_GetMusicalTimeLocation"
        }
      ],
      "role": "symbol",
      "title": "HostCallback_GetMusicalTimeLocation",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallback_getmusicaltimelocation"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetTransportState": {
      "abstract": [
        {
          "text": "When called by the system, provides audio transport state and timeline information to an audio unit from a host application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostCallback_GetTransportState"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetTransportState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostCallback_GetTransportState"
        }
      ],
      "role": "symbol",
      "title": "HostCallback_GetTransportState",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallback_gettransportstate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetTransportState2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HostCallback_GetTransportState2"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/HostCallback_GetTransportState2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HostCallback_GetTransportState2"
        }
      ],
      "role": "symbol",
      "title": "HostCallback_GetTransportState2",
      "type": "topic",
      "url": "/documentation/audiotoolbox/hostcallback_gettransportstate2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetBeatAndTempo/title",
          "value": "HostCallback_GetBeatAndTempo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetBeatAndTempo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetBeatAndTempo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetBeatAndTempo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetBeatAndTempo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo/title",
          "value": "HostCallbackInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallbackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallbackInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallbackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetTransportState2/title",
          "value": "HostCallback_GetTransportState2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetTransportState2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetTransportState2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetTransportState2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetTransportState2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetMusicalTimeLocation/title",
          "value": "HostCallback_GetMusicalTimeLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetMusicalTimeLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetMusicalTimeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetMusicalTimeLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetMusicalTimeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetTransportState/title",
          "value": "HostCallback_GetTransportState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetTransportState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetTransportState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1HostCallback_GetTransportState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HostCallback_GetTransportState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/hostcallbackinfo/init(hostuserdata:beatandtempoproc:musicaltimelocationproc:transportstateproc:transportstateproc2:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
