{
  "abstract": [
    {
      "text": "An option to use optical bounds.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/useOpticalBounds"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTLineBoundsOptions@kCTLineBoundsUseOpticalBounds",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "useOpticalBounds"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CTLineBoundsOptions",
        "text": "CTLineBoundsOptions"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTLineBoundsUseOpticalBounds"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "useOpticalBounds"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "useOpticalBounds"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CTLineBoundsOptions",
              "text": "CTLineBoundsOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This option overrides ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/useGlyphPathBounds",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions": {
      "abstract": [
        {
          "text": "Options for getting the bounds of a line of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineBoundsOptions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineBoundsOptions"
        }
      ],
      "role": "symbol",
      "title": "CTLineBoundsOptions",
      "type": "topic",
      "url": "/documentation/coretext/ctlineboundsoptions"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/excludeTypographicLeading": {
      "abstract": [
        {
          "text": "An option to exclude typographic leading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "excludeTypographicLeading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTLineBoundsOptions",
          "text": "CTLineBoundsOptions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/excludeTypographicLeading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTLineBoundsExcludeTypographicLeading"
        }
      ],
      "role": "symbol",
      "title": "excludeTypographicLeading",
      "type": "topic",
      "url": "/documentation/coretext/ctlineboundsoptions/excludetypographicleading"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/excludeTypographicShifts": {
      "abstract": [
        {
          "text": "An option to ignore cross-stream shifts due to positioning, such as kerning or baseline alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "excludeTypographicShifts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTLineBoundsOptions",
          "text": "CTLineBoundsOptions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/excludeTypographicShifts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTLineBoundsExcludeTypographicShifts"
        }
      ],
      "role": "symbol",
      "title": "excludeTypographicShifts",
      "type": "topic",
      "url": "/documentation/coretext/ctlineboundsoptions/excludetypographicshifts"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/includeLanguageExtents": {
      "abstract": [
        {
          "text": "An option to include additional space based on common glyph sequences for various languages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "includeLanguageExtents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTLineBoundsOptions",
          "text": "CTLineBoundsOptions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/includeLanguageExtents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTLineBoundsIncludeLanguageExtents"
        }
      ],
      "role": "symbol",
      "title": "includeLanguageExtents",
      "type": "topic",
      "url": "/documentation/coretext/ctlineboundsoptions/includelanguageextents"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/useGlyphPathBounds": {
      "abstract": [
        {
          "text": "An option to use glyph path bounds rather than the default typographic bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useGlyphPathBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTLineBoundsOptions",
          "text": "CTLineBoundsOptions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/useGlyphPathBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTLineBoundsUseGlyphPathBounds"
        }
      ],
      "role": "symbol",
      "title": "useGlyphPathBounds",
      "type": "topic",
      "url": "/documentation/coretext/ctlineboundsoptions/useglyphpathbounds"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/useHangingPunctuation": {
      "abstract": [
        {
          "text": "An option to enable hanging punctuation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useHangingPunctuation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTLineBoundsOptions",
          "text": "CTLineBoundsOptions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/useHangingPunctuation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTLineBoundsUseHangingPunctuation"
        }
      ],
      "role": "symbol",
      "title": "useHangingPunctuation",
      "type": "topic",
      "url": "/documentation/coretext/ctlineboundsoptions/usehangingpunctuation"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/useOpticalBounds": {
      "abstract": [
        {
          "text": "An option to use optical bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useOpticalBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTLineBoundsOptions",
          "text": "CTLineBoundsOptions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/useOpticalBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTLineBoundsUseOpticalBounds"
        }
      ],
      "role": "symbol",
      "title": "useOpticalBounds",
      "type": "topic",
      "url": "/documentation/coretext/ctlineboundsoptions/useopticalbounds"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Line-Bounds-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/excludeTypographicLeading",
        "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/excludeTypographicShifts",
        "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/includeLanguageExtents",
        "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/useGlyphPathBounds",
        "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/useHangingPunctuation"
      ],
      "title": "Line Bounds Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTLineBoundsUseOpticalBounds"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLineBoundsUseOpticalBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Line-Bounds-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/excludeTypographicLeading",
                "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/excludeTypographicShifts",
                "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/includeLanguageExtents",
                "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/useGlyphPathBounds",
                "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions/useHangingPunctuation"
              ],
              "title": "Line Bounds Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTLineBoundsUseOpticalBounds"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions/title",
          "value": "CTLineBoundsOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBoundsOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBoundsOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions~1useHangingPunctuation/title",
          "value": "kCTLineBoundsUseHangingPunctuation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions~1useHangingPunctuation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLineBoundsUseHangingPunctuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions~1includeLanguageExtents/title",
          "value": "kCTLineBoundsIncludeLanguageExtents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions~1includeLanguageExtents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLineBoundsIncludeLanguageExtents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions~1useOpticalBounds/title",
          "value": "kCTLineBoundsUseOpticalBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions~1useOpticalBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLineBoundsUseOpticalBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions~1useGlyphPathBounds/title",
          "value": "kCTLineBoundsUseGlyphPathBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions~1useGlyphPathBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLineBoundsUseGlyphPathBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions~1excludeTypographicShifts/title",
          "value": "kCTLineBoundsExcludeTypographicShifts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions~1excludeTypographicShifts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLineBoundsExcludeTypographicShifts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions~1excludeTypographicLeading/title",
          "value": "kCTLineBoundsExcludeTypographicLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions~1excludeTypographicLeading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLineBoundsExcludeTypographicLeading"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctlineboundsoptions/useopticalbounds"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctlineboundsoptions/useopticalbounds"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
