{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionInterruptionReason/AVAudioSessionInterruptionReasonDeviceUnauthenticated"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAudioSessionInterruptionReason@AVAudioSessionInterruptionReasonDeviceUnauthenticated",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AVAudioSessionInterruptionReasonDeviceUnauthenticated"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioSessionInterruptionReasonDeviceUnauthenticated"
      }
    ],
    "platforms": [],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "AVAudioSessionInterruptionReasonDeviceUnauthenticated"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionReasonDeviceUnauthenticated"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason": {
      "abstract": [
        {
          "text": "Constants that define the reasons for an audio session interruption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InterruptionReason"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InterruptionReason"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.InterruptionReason",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/interruptionreason"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionInterruptionReason/AVAudioSessionInterruptionReasonDeviceUnauthenticated": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionInterruptionReasonDeviceUnauthenticated"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionInterruptionReason/AVAudioSessionInterruptionReasonDeviceUnauthenticated",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionInterruptionReasonDeviceUnauthenticated",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosessioninterruptionreason/avaudiosessioninterruptionreasondeviceunauthenticated"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason/title",
          "value": "AVAudioSessionInterruptionReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionReason"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiosessioninterruptionreason/avaudiosessioninterruptionreasondeviceunauthenticated"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
