{"seeAlsoSections":[{"anchor":"Constants","title":"Constants","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/leading","doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/bottom","doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/trailing","doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/all"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge"]]},"abstract":[{"text":"The top edge.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/nsdirectionalrectedge/top"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/nsdirectionalrectedge/top"]}],"sections":[],"metadata":{"role":"symbol","title":"top","modules":[{"name":"UIKit"}],"roleHeading":"Type Property","platforms":[{"beta":false,"name":"iOS","introducedAt":"13.0","deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","introducedAt":"13.0","deprecated":false,"unavailable":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","introducedAt":"13.0","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","introducedAt":"1.0","deprecated":false,"unavailable":false},{"beta":false,"name":"watchOS","introducedAt":"6.0","deprecated":false,"unavailable":false}],"externalID":"c:@E@NSDirectionalRectEdge@NSDirectionalRectEdgeTop","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"NSDirectionalRectEdgeTop"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSDirectionalRectEdge","preciseIdentifier":"c:@E@NSDirectionalRectEdge"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NSDirectionalRectEdge","kind":"typeIdentifier","text":"NSDirectionalRectEdge","identifier":"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/top"},"references":{"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/bottom":{"url":"/documentation/uikit/nsdirectionalrectedge/bottom","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/bottom","abstract":[{"text":"The bottom edge.","type":"text"}],"navigatorTitle":[{"text":"NSDirectionalRectEdgeBottom","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDirectionalRectEdge","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSDirectionalRectEdge"}],"type":"topic","title":"bottom"},"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/NSDirectionalRectEdgeNone":{"role":"symbol","fragments":[{"text":"NSDirectionalRectEdgeNone","kind":"identifier"}],"title":"NSDirectionalRectEdgeNone","identifier":"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/NSDirectionalRectEdgeNone","type":"topic","url":"/documentation/uikit/nsdirectionalrectedge/nsdirectionalrectedgenone","kind":"symbol","abstract":[{"text":"No specified edge.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/leading":{"url":"/documentation/uikit/nsdirectionalrectedge/leading","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/leading","abstract":[{"text":"The leading edge.","type":"text"}],"navigatorTitle":[{"text":"NSDirectionalRectEdgeLeading","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"leading","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDirectionalRectEdge","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSDirectionalRectEdge"}],"type":"topic","title":"leading"},"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/trailing":{"abstract":[{"text":"The trailing edge.","type":"text"}],"role":"symbol","url":"/documentation/uikit/nsdirectionalrectedge/trailing","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/trailing","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trailing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDirectionalRectEdge","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSDirectionalRectEdge"}],"navigatorTitle":[{"text":"NSDirectionalRectEdgeTrailing","kind":"identifier"}],"title":"trailing"},"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/all":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"all","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSDirectionalRectEdge","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSDirectionalRectEdge"}],"role":"symbol","title":"all","url":"/documentation/uikit/nsdirectionalrectedge/all","identifier":"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/all","navigatorTitle":[{"text":"NSDirectionalRectEdgeAll","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"All edges.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"NSDirectionalRectEdge","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge","title":"NSDirectionalRectEdge","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDirectionalRectEdge","kind":"identifier"}],"abstract":[{"text":"Constants that specify an edge or a set of edges, taking the user interface layout direction into account.","type":"text"}],"url":"/documentation/uikit/nsdirectionalrectedge"},"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/top":{"url":"/documentation/uikit/nsdirectionalrectedge/top","navigatorTitle":[{"kind":"identifier","text":"NSDirectionalRectEdgeTop"}],"kind":"symbol","abstract":[{"type":"text","text":"The top edge."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSDirectionalRectEdge","text":"NSDirectionalRectEdge"}],"title":"top","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/top"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"name":"iOS","introducedAt":"13.0","deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","introducedAt":"13.0","deprecated":false,"unavailable":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","introducedAt":"13.0","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","introducedAt":"1.0","deprecated":false,"unavailable":false},{"beta":false,"name":"watchOS","introducedAt":"6.0","deprecated":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"NSDirectionalRectEdgeTop"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"NSDirectionalRectEdgeTop"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/NSDirectionalRectEdgeNone","doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/leading","doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/bottom","doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/trailing","doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge/all"],"title":"Constants","generated":true,"anchor":"Constants"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"NSDirectionalRectEdgeTop"}]}]}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge~1bottom/title","op":"replace","value":"NSDirectionalRectEdgeBottom"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge~1bottom/fragments","op":"replace","value":[{"kind":"identifier","text":"NSDirectionalRectEdgeBottom"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge~1leading/title","op":"replace","value":"NSDirectionalRectEdgeLeading"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge~1leading/fragments","op":"replace","value":[{"kind":"identifier","text":"NSDirectionalRectEdgeLeading"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge~1trailing/title","op":"replace","value":"NSDirectionalRectEdgeTrailing"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge~1trailing/fragments","op":"replace","value":[{"text":"NSDirectionalRectEdgeTrailing","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge~1all/title","op":"replace","value":"NSDirectionalRectEdgeAll"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge~1all/fragments","op":"replace","value":[{"kind":"identifier","text":"NSDirectionalRectEdgeAll"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge/title","op":"replace","value":"NSDirectionalRectEdge"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge/fragments","op":"replace","value":[{"kind":"identifier","text":"NSDirectionalRectEdge"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSDirectionalRectEdge"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge~1top/title","op":"replace","value":"NSDirectionalRectEdgeTop"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge~1top/fragments","op":"replace","value":[{"text":"NSDirectionalRectEdgeTop","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}