{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/displayValuesKeyPath","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Supporting Bindings","anchor":"Supporting-Bindings","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/rowClass","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/rowTypeKeyPath","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/subrowsKeyPath","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/criteriaKeyPath"]}],"kind":"symbol","abstract":[{"text":"The display values key path.","type":"text"}],"metadata":{"platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayValuesKeyPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)NSRuleEditor(py)displayValuesKeyPath","modules":[{"name":"AppKit"}],"title":"displayValuesKeyPath","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"displayValuesKeyPath"}]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayValuesKeyPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SS","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"The key path is used to get the display values for a row in the “rows” binding. The display values are the objects returned by calling the delegate’s ","type":"text"},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditorDelegate/ruleEditor(_:displayValueForCriterion:inRow:)","isActive":true},{"text":" method for the specified row. The corresponding property is an ordered to-many relationship.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The default is "},{"type":"codeVoice","code":"@\"displayValues\""},{"text":".","type":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor"]]},"variants":[{"paths":["/documentation/appkit/nsruleeditor/displayvalueskeypath"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsruleeditor/displayvalueskeypath"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/subrowsKeyPath":{"navigatorTitle":[{"text":"subrowsKeyPath","kind":"identifier"}],"url":"/documentation/appkit/nsruleeditor/subrowskeypath","abstract":[{"text":"The key path for the subrows.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subrowsKeyPath","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","title":"subrowsKeyPath","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/subrowsKeyPath"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/rowTypeKeyPath":{"abstract":[{"type":"text","text":"The key path for the row type."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/rowTypeKeyPath","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rowTypeKeyPath","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"rowTypeKeyPath","kind":"identifier"}],"title":"rowTypeKeyPath","url":"/documentation/appkit/nsruleeditor/rowtypekeypath","kind":"symbol","type":"topic","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SS":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String","kind":"identifier"}],"type":"topic","title":"String","role":"symbol","abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor":{"abstract":[{"type":"text","text":"An interface for configuring a rule-based list of options."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSRuleEditor","kind":"identifier"}],"url":"/documentation/appkit/nsruleeditor","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor","role":"symbol","navigatorTitle":[{"text":"NSRuleEditor","kind":"identifier"}],"type":"topic","kind":"symbol","title":"NSRuleEditor"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/rowClass":{"navigatorTitle":[{"text":"rowClass","kind":"identifier"}],"url":"/documentation/appkit/nsruleeditor/rowclass","abstract":[{"text":"The class used to create a new row in the “rows” binding.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rowClass"},{"text":": ","kind":"text"},{"text":"AnyClass","preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier"}],"role":"symbol","title":"rowClass","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/rowClass"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/displayValuesKeyPath":{"abstract":[{"type":"text","text":"The display values key path."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/displayValuesKeyPath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayValuesKeyPath"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"displayValuesKeyPath","kind":"identifier"}],"title":"displayValuesKeyPath","url":"/documentation/appkit/nsruleeditor/displayvalueskeypath","kind":"symbol","type":"topic","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"title":"NSString","kind":"symbol","url":"/documentation/foundation/nsstring","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditorDelegate/ruleEditor(_:displayValueForCriterion:inRow:)":{"type":"topic","title":"ruleEditor(_:displayValueForCriterion:inRow:)","kind":"symbol","navigatorTitle":[{"text":"ruleEditor:displayValueForCriterion:inRow:","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the value for a given criterion."}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ruleEditor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSRuleEditor","preciseIdentifier":"c:objc(cs)NSRuleEditor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"displayValueForCriterion"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inRow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"text":"Any","kind":"keyword"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditorDelegate/ruleEditor(_:displayValueForCriterion:inRow:)","url":"/documentation/appkit/nsruleeditordelegate/ruleeditor(_:displayvalueforcriterion:inrow:)"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/criteriaKeyPath":{"role":"symbol","navigatorTitle":[{"text":"criteriaKeyPath","kind":"identifier"}],"url":"/documentation/appkit/nsruleeditor/criteriakeypath","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/criteriaKeyPath","title":"criteriaKeyPath","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"criteriaKeyPath","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"text":"The criteria key path.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"displayValuesKeyPath","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"displayValuesKeyPath","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Supporting Bindings","anchor":"Supporting-Bindings","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/rowClass","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/rowTypeKeyPath","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/subrowsKeyPath","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/criteriaKeyPath"]}],"op":"replace","path":"/seeAlsoSections"},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"displayValuesKeyPath","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]}},{"value":"subrowsKeyPath","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1subrowsKeyPath/title"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1subrowsKeyPath/fragments","op":"replace","value":[{"text":"subrowsKeyPath","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1rowTypeKeyPath/title","op":"replace","value":"rowTypeKeyPath"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1rowTypeKeyPath/fragments","op":"replace","value":[{"text":"rowTypeKeyPath","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor/title","op":"replace","value":"NSRuleEditor"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor/fragments","op":"replace","value":[{"text":"NSRuleEditor","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor/navigatorTitle","op":"replace","value":[{"text":"NSRuleEditor","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1rowClass/title","op":"replace","value":"rowClass"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1rowClass/fragments","op":"replace","value":[{"kind":"identifier","text":"rowClass"}]},{"op":"replace","value":"displayValuesKeyPath","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1displayValuesKeyPath/title"},{"op":"replace","value":[{"text":"displayValuesKeyPath","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1displayValuesKeyPath/fragments"},{"op":"replace","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract"},{"op":"replace","value":"ruleEditor:displayValueForCriterion:inRow:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditorDelegate~1ruleEditor(_:displayValueForCriterion:inRow:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ruleEditor:displayValueForCriterion:inRow:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditorDelegate~1ruleEditor(_:displayValueForCriterion:inRow:)/fragments"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1criteriaKeyPath/title","op":"replace","value":"criteriaKeyPath"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1criteriaKeyPath/fragments","op":"replace","value":[{"kind":"identifier","text":"criteriaKeyPath"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}