{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor"]]},"sections":[],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/rowType(forRow:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"AppKit"}],"navigatorTitle":[{"text":"rowTypeForRow:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rowType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forRow","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSRuleEditor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSRuleEditor"},{"text":".","kind":"text"},{"text":"RowType","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSRuleEditorRowType"}],"title":"rowType(forRow:)","platforms":[{"unavailable":false,"name":"macOS","deprecated":false,"beta":false}],"roleHeading":"Instance Method","externalID":"c:objc(cs)NSRuleEditor(im)rowTypeForRow:"},"seeAlsoSections":[{"title":"Obtaining Row Information","generated":true,"anchor":"Obtaining-Row-Information","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/numberOfRows","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/parentRow(forRow:)","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/row(forDisplayValue:)","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/RowType","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/subrowIndexes(forRow:)"]}],"variants":[{"paths":["/documentation/appkit/nsruleeditor/rowtype(forrow:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsruleeditor/rowtype(forrow:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Returns the type of a given row.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rowType"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forRow"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rowIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSRuleEditor","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor","text":"NSRuleEditor"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSRuleEditorRowType","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/RowType","text":"RowType"}],"platforms":["macOS"]}]},{"parameters":[{"name":"rowIndex","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The index of a row in the receiver."}]},{"style":"important","type":"aside","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"Raises an ","type":"text"},{"type":"codeVoice","code":"NSRangeException"},{"text":" if ","type":"text"},{"type":"codeVoice","code":"rowIndex"},{"text":" is less than ","type":"text"},{"type":"codeVoice","code":"0"},{"text":" or greater than or equal to the number of rows.","type":"text"}]}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of the row at "},{"code":"rowIndex","type":"codeVoice"},{"type":"text","text":"."}]}]}],"references":{"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/rowType(forRow:)":{"title":"rowType(forRow:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rowType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forRow","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSRuleEditor","preciseIdentifier":"c:objc(cs)NSRuleEditor","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"RowType","preciseIdentifier":"c:@E@NSRuleEditorRowType","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Returns the type of a given row.","type":"text"}],"url":"/documentation/appkit/nsruleeditor/rowtype(forrow:)","navigatorTitle":[{"text":"rowTypeForRow:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/rowType(forRow:)","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/row(forDisplayValue:)":{"title":"row(forDisplayValue:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"row","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forDisplayValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":") -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Returns the index of the row containing a given value.","type":"text"}],"url":"/documentation/appkit/nsruleeditor/row(fordisplayvalue:)","navigatorTitle":[{"text":"rowForDisplayValue:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/row(forDisplayValue:)","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/RowType":{"title":"NSRuleEditor.RowType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RowType","kind":"identifier"}],"type":"topic","abstract":[{"text":"Specifies a type for row types.","type":"text"}],"url":"/documentation/appkit/nsruleeditor/rowtype","navigatorTitle":[{"text":"RowType","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/RowType","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/subrowIndexes(forRow:)":{"title":"subrowIndexes(forRow:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subrowIndexes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forRow","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Returns the immediate subrows of a given row.","type":"text"}],"url":"/documentation/appkit/nsruleeditor/subrowindexes(forrow:)","navigatorTitle":[{"text":"subrowIndexesForRow:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/subrowIndexes(forRow:)","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/parentRow(forRow:)":{"title":"parentRow(forRow:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parentRow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forRow","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Returns the index of the parent of a given row.","type":"text"}],"url":"/documentation/appkit/nsruleeditor/parentrow(forrow:)","navigatorTitle":[{"text":"parentRowForRow:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/parentRow(forRow:)","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/numberOfRows":{"title":"numberOfRows","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberOfRows","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"The number of rows in the rule editor.","type":"text"}],"url":"/documentation/appkit/nsruleeditor/numberofrows","navigatorTitle":[{"text":"numberOfRows","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/numberOfRows","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor":{"abstract":[{"type":"text","text":"An interface for configuring a rule-based list of options."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSRuleEditor","kind":"identifier"}],"url":"/documentation/appkit/nsruleeditor","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor","role":"symbol","navigatorTitle":[{"text":"NSRuleEditor","kind":"identifier"}],"type":"topic","kind":"symbol","title":"NSRuleEditor"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"name":"macOS","deprecated":false,"beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"rowTypeForRow:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"rowTypeForRow:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Obtaining Row Information","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/numberOfRows","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/parentRow(forRow:)","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/row(forDisplayValue:)","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/RowType","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/subrowIndexes(forRow:)"],"generated":true,"anchor":"Obtaining-Row-Information"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@E@NSRuleEditorRowType","text":"NSRuleEditorRowType","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/RowType"},{"text":") ","kind":"text"},{"text":"rowTypeForRow:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"rowIndex","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/primaryContentSections/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"rowIndex","content":[{"type":"paragraph","inlineContent":[{"text":"The index of a row in the receiver.","type":"text"}]},{"name":"Important","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"Raises an "},{"type":"codeVoice","code":"NSRangeException"},{"type":"text","text":" if "},{"type":"codeVoice","code":"rowIndex"},{"type":"text","text":" is less than "},{"type":"codeVoice","code":"0"},{"text":" or greater than or equal to the number of rows.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"important"}]}]}},{"value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of the row at "},{"type":"codeVoice","code":"rowIndex"},{"type":"text","text":"."}]}]},"path":"/primaryContentSections/2","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1rowType(forRow:)/title","op":"replace","value":"rowTypeForRow:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1rowType(forRow:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rowTypeForRow:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1row(forDisplayValue:)/title","op":"replace","value":"rowForDisplayValue:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1row(forDisplayValue:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rowForDisplayValue:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1RowType/title","op":"replace","value":"NSRuleEditorRowType"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1RowType/fragments","op":"replace","value":[{"kind":"identifier","text":"NSRuleEditorRowType"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1RowType/navigatorTitle","op":"replace","value":[{"text":"NSRuleEditorRowType","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1subrowIndexes(forRow:)/title","op":"replace","value":"subrowIndexesForRow:"},{"value":[{"text":"- ","kind":"text"},{"text":"subrowIndexesForRow:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1subrowIndexes(forRow:)/fragments","op":"replace"},{"value":"parentRowForRow:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1parentRow(forRow:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parentRowForRow:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1parentRow(forRow:)/fragments","op":"replace"},{"value":"numberOfRows","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1numberOfRows/title","op":"replace"},{"value":[{"text":"numberOfRows","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1numberOfRows/fragments","op":"replace"},{"value":"NSRuleEditor","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor/title","op":"replace"},{"value":[{"text":"NSRuleEditor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor/fragments","op":"replace"},{"value":[{"text":"NSRuleEditor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}