{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedRowIndexes","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet","identifier":"doc://com.externally.resolved.symbol/s:10Foundation8IndexSetV","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"variants":[{"paths":["/documentation/appkit/nsruleeditor/selectedrowindexes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsruleeditor/selectedrowindexes"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"title":"Working with the Selection","anchor":"Working-with-the-Selection","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/selectRowIndexes(_:byExtendingSelection:)"]}],"abstract":[{"type":"text","text":"The indexes of the rule editor’s selected rows."}],"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)NSRuleEditor(py)selectedRowIndexes","navigatorTitle":[{"kind":"identifier","text":"selectedRowIndexes"}],"title":"selectedRowIndexes","modules":[{"name":"AppKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedRowIndexes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet"}],"role":"symbol","platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS"}],"symbolKind":"property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/selectedRowIndexes"},"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/selectRowIndexes(_:byExtendingSelection:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectRowIndexes"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"byExtendingSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/selectRowIndexes(_:byExtendingSelection:)","kind":"symbol","url":"/documentation/appkit/nsruleeditor/selectrowindexes(_:byextendingselection:)","abstract":[{"text":"Sets in the receiver the indexes of rows that are selected.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"selectRowIndexes:byExtendingSelection:"}],"title":"selectRowIndexes(_:byExtendingSelection:)","type":"topic","role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/selectedRowIndexes":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedRowIndexes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/selectedRowIndexes","kind":"symbol","url":"/documentation/appkit/nsruleeditor/selectedrowindexes","abstract":[{"type":"text","text":"The indexes of the rule editor’s selected rows."}],"navigatorTitle":[{"kind":"identifier","text":"selectedRowIndexes"}],"title":"selectedRowIndexes","type":"topic","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor":{"abstract":[{"type":"text","text":"An interface for configuring a rule-based list of options."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSRuleEditor","kind":"identifier"}],"url":"/documentation/appkit/nsruleeditor","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRuleEditor","role":"symbol","navigatorTitle":[{"text":"NSRuleEditor","kind":"identifier"}],"type":"topic","kind":"symbol","title":"NSRuleEditor"},"doc://com.externally.resolved.symbol/s:10Foundation8IndexSetV":{"identifier":"doc://com.externally.resolved.symbol/s:10Foundation8IndexSetV","url":"/documentation/foundation/indexset","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"IndexSet"}],"kind":"symbol","type":"topic","title":"IndexSet","role":"symbol","abstract":[{"text":"A collection of unique integer values that represent the indexes of elements in another collection. ","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"op":"replace","path":"/metadata/title","value":"selectedRowIndexes"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"selectedRowIndexes","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSRuleEditor"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Working-with-the-Selection","title":"Working with the Selection","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSRuleEditor/selectRowIndexes(_:byExtendingSelection:)"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexSet","text":"NSIndexSet"},{"text":" * ","kind":"text"},{"text":"selectedRowIndexes","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1selectRowIndexes(_:byExtendingSelection:)/title","op":"replace","value":"selectRowIndexes:byExtendingSelection:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1selectRowIndexes(_:byExtendingSelection:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"selectRowIndexes:byExtendingSelection:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1selectedRowIndexes/title","op":"replace","value":"selectedRowIndexes"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor~1selectedRowIndexes/fragments","op":"replace","value":[{"kind":"identifier","text":"selectedRowIndexes"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor/title","op":"replace","value":"NSRuleEditor"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor/fragments","op":"replace","value":[{"kind":"identifier","text":"NSRuleEditor"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRuleEditor/navigatorTitle","op":"replace","value":[{"text":"NSRuleEditor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}