{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/started"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CAClockMessage@kCAClockMessage_Started",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "started"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCAClockMessage_Started"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CAClockMessage.started"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "started"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAClockMessage"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAClockMessage"
        }
      ],
      "role": "symbol",
      "title": "CAClockMessage",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockmessage"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/armed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "armed"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/armed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockMessage_Armed"
        }
      ],
      "role": "symbol",
      "title": "CAClockMessage.armed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockmessage/armed"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/disarmed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disarmed"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/disarmed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockMessage_Disarmed"
        }
      ],
      "role": "symbol",
      "title": "CAClockMessage.disarmed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockmessage/disarmed"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/propertyChanged": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "propertyChanged"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/propertyChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockMessage_PropertyChanged"
        }
      ],
      "role": "symbol",
      "title": "CAClockMessage.propertyChanged",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockmessage/propertychanged"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/startTimeSet": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startTimeSet"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/startTimeSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockMessage_StartTimeSet"
        }
      ],
      "role": "symbol",
      "title": "CAClockMessage.startTimeSet",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockmessage/starttimeset"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/started": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "started"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/started",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockMessage_Started"
        }
      ],
      "role": "symbol",
      "title": "CAClockMessage.started",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockmessage/started"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/stopped": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopped"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/stopped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockMessage_Stopped"
        }
      ],
      "role": "symbol",
      "title": "CAClockMessage.stopped",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockmessage/stopped"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/wrongSMPTEFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wrongSMPTEFormat"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/wrongSMPTEFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAClockMessage_WrongSMPTEFormat"
        }
      ],
      "role": "symbol",
      "title": "CAClockMessage.wrongSMPTEFormat",
      "type": "topic",
      "url": "/documentation/audiotoolbox/caclockmessage/wrongsmpteformat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/armed",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/disarmed",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/propertyChanged",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/startTimeSet",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/stopped",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/wrongSMPTEFormat"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCAClockMessage_Started"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockMessage_Started"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/armed",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/disarmed",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/propertyChanged",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/startTimeSet",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/stopped",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/CAClockMessage/wrongSMPTEFormat"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCAClockMessage_Started"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage~1propertyChanged/title",
          "value": "kCAClockMessage_PropertyChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage~1propertyChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockMessage_PropertyChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage~1disarmed/title",
          "value": "kCAClockMessage_Disarmed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage~1disarmed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockMessage_Disarmed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage~1stopped/title",
          "value": "kCAClockMessage_Stopped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage~1stopped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockMessage_Stopped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage~1armed/title",
          "value": "kCAClockMessage_Armed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage~1armed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockMessage_Armed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage~1startTimeSet/title",
          "value": "kCAClockMessage_StartTimeSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage~1startTimeSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockMessage_StartTimeSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage~1wrongSMPTEFormat/title",
          "value": "kCAClockMessage_WrongSMPTEFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage~1wrongSMPTEFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockMessage_WrongSMPTEFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage~1started/title",
          "value": "kCAClockMessage_Started"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage~1started/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAClockMessage_Started"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage/title",
          "value": "CAClockMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAClockMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1CAClockMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAClockMessage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/caclockmessage/started"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/caclockmessage/started"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
