{
  "abstract": [
    {
      "text": "Indicates that the screen recording has stopped.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "No longer supported",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.replaykit/documentation/ReplayKit",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate/screenRecorder(_:didStopRecordingWithError:previewViewController:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)RPScreenRecorderDelegate(im)screenRecorder:didStopRecordingWithError:previewViewController:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "screenRecorder"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)RPScreenRecorder",
        "text": "RPScreenRecorder"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didStopRecordingWithError"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "previewViewController"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)RPPreviewViewController",
        "text": "RPPreviewViewController"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "ReplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "screenRecorder:didStopRecordingWithError:previewViewController:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "9.0",
        "message": "No longer supported",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "9.0",
        "message": "No longer supported",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "No longer supported",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "10.0",
        "message": "No longer supported",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "No longer supported",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "screenRecorder(_:didStopRecordingWithError:previewViewController:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "screenRecorder"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "screenRecorder"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)RPScreenRecorder",
              "text": "RPScreenRecorder"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didStopRecordingWithError"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "previewViewController"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPPreviewViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)RPPreviewViewController",
              "text": "RPPreviewViewController"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instance.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "screenRecorder"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " describing why the recording stopped.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPPreviewViewController",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " interface object that is returned if anything at all was recorded. The interface allows the user to preview and edit the recording.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "previewViewController"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate/screenRecorder(_:didStopRecordingWithError:previewViewController:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is called when recording stops due to an error or a change in recording availability. If any part of the stopped recording is available, an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPPreviewViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is returned.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit": {
      "abstract": [
        {
          "text": "Record or stream video from the screen, and audio from the app and microphone.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ReplayKit",
      "type": "topic",
      "url": "/documentation/replaykit"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPPreviewViewController": {
      "abstract": [
        {
          "text": "An object that displays a user interface where users preview and edit a screen recording that you create with ReplayKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPPreviewViewController"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPPreviewViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPPreviewViewController"
        }
      ],
      "role": "symbol",
      "title": "RPPreviewViewController",
      "type": "topic",
      "url": "/documentation/replaykit/rppreviewviewcontroller"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder": {
      "abstract": [
        {
          "text": "The shared recorder object that provides the ability to record audio and video of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPScreenRecorder"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPScreenRecorder"
        }
      ],
      "role": "symbol",
      "title": "RPScreenRecorder",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate": {
      "abstract": [
        {
          "text": "The protocol you implement to receive notifications from the screen recorder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPScreenRecorderDelegate"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPScreenRecorderDelegate"
        }
      ],
      "role": "symbol",
      "title": "RPScreenRecorderDelegate",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorderdelegate"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate/screenRecorder(_:didStopRecordingWith:error:)": {
      "abstract": [
        {
          "text": "Indicates that the screen recording has stopped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenRecorder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)RPScreenRecorder",
          "text": "RPScreenRecorder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didStopRecordingWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)RPPreviewViewController",
          "text": "RPPreviewViewController"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate/screenRecorder(_:didStopRecordingWith:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "screenRecorder:didStopRecordingWithPreviewViewController:error:"
        }
      ],
      "role": "symbol",
      "title": "screenRecorder(_:didStopRecordingWith:error:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorderdelegate/screenrecorder(_:didstoprecordingwith:error:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate/screenRecorder(_:didStopRecordingWithError:previewViewController:)": {
      "abstract": [
        {
          "text": "Indicates that the screen recording has stopped.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenRecorder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)RPScreenRecorder",
          "text": "RPScreenRecorder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didStopRecordingWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "previewViewController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)RPPreviewViewController",
          "text": "RPPreviewViewController"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate/screenRecorder(_:didStopRecordingWithError:previewViewController:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "screenRecorder:didStopRecordingWithError:previewViewController:"
        }
      ],
      "role": "symbol",
      "title": "screenRecorder(_:didStopRecordingWithError:previewViewController:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorderdelegate/screenrecorder(_:didstoprecordingwitherror:previewviewcontroller:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate/screenRecorderDidChangeAvailability(_:)": {
      "abstract": [
        {
          "text": "Indicates that the recorder has changed states between disabled and enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenRecorderDidChangeAvailability"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)RPScreenRecorder",
          "text": "RPScreenRecorder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate/screenRecorderDidChangeAvailability(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "screenRecorderDidChangeAvailability:"
        }
      ],
      "role": "symbol",
      "title": "screenRecorderDidChangeAvailability(_:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorderdelegate/screenrecorderdidchangeavailability(_:)"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-Recording-Changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate/screenRecorder(_:didStopRecordingWith:error:)",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate/screenRecorderDidChangeAvailability(_:)"
      ],
      "title": "Responding to Recording Changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "screenRecorder:didStopRecordingWithError:previewViewController:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "screenRecorder:didStopRecordingWithError:previewViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.replaykit/documentation/ReplayKit",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-Recording-Changes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate/screenRecorder(_:didStopRecordingWith:error:)",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorderDelegate/screenRecorderDidChangeAvailability(_:)"
              ],
              "title": "Responding to Recording Changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "screenRecorder:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)RPScreenRecorder",
                    "text": "RPScreenRecorder"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "screenRecorder"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didStopRecordingWithError:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "previewViewController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPPreviewViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)RPPreviewViewController",
                    "text": "RPPreviewViewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "previewViewController"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " instance.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "screenRecorder"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " describing why the recording stopped.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPPreviewViewController",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " interface object that is returned if anything at all was recorded. The interface allows the user to preview and edit the recording.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "previewViewController"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "No longer supported",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPPreviewViewController/title",
          "value": "RPPreviewViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPPreviewViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPPreviewViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPPreviewViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPPreviewViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorderDelegate~1screenRecorder(_:didStopRecordingWithError:previewViewController:)/title",
          "value": "screenRecorder:didStopRecordingWithError:previewViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorderDelegate~1screenRecorder(_:didStopRecordingWithError:previewViewController:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "screenRecorder:didStopRecordingWithError:previewViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder/title",
          "value": "RPScreenRecorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPScreenRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPScreenRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorderDelegate/title",
          "value": "RPScreenRecorderDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorderDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPScreenRecorderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorderDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPScreenRecorderDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorderDelegate~1screenRecorder(_:didStopRecordingWith:error:)/title",
          "value": "screenRecorder:didStopRecordingWithPreviewViewController:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorderDelegate~1screenRecorder(_:didStopRecordingWith:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "screenRecorder:didStopRecordingWithPreviewViewController:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorderDelegate~1screenRecorderDidChangeAvailability(_:)/title",
          "value": "screenRecorderDidChangeAvailability:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorderDelegate~1screenRecorderDidChangeAvailability(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "screenRecorderDidChangeAvailability:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/replaykit/rpscreenrecorderdelegate/screenrecorder(_:didstoprecordingwitherror:previewviewcontroller:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/replaykit/rpscreenrecorderdelegate/screenrecorder(_:didstoprecordingwitherror:previewviewcontroller:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
