{
  "abstract": [
    {
      "text": "Sets the language for a range of text within the tagger’s string.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/setLanguage(_:range:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "NaturalLanguage",
    "externalID": "s:So8NLTaggerC15NaturalLanguageE03setC0_5rangeySo10NLLanguagea_SnySS5IndexVGtF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setLanguage"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NLLanguage",
        "text": "NLLanguage"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "range"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sn",
        "text": "Range"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS5IndexV",
        "text": "Index"
      },
      {
        "kind": "text",
        "text": ">)"
      }
    ],
    "modules": [
      {
        "name": "Natural Language"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setLanguage(_:range:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@nonobjc"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setLanguage"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "language"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NLLanguage",
              "text": "NLLanguage"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sn",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sn",
              "text": "Range"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS5IndexV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS5IndexV",
              "text": "Index"
            },
            {
              "kind": "text",
              "text": ">)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The language of the text range.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "language"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The range of the string that is being assigned a language.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "range"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage": {
      "abstract": [
        {
          "text": "Analyze natural language text and deduce its language-specific metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
      "kind": "symbol",
      "role": "collection",
      "title": "Natural Language",
      "type": "topic",
      "url": "/documentation/naturallanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguage": {
      "abstract": [
        {
          "text": "The languages that the Natural Language framework supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLLanguage"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLLanguage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLLanguage"
        }
      ],
      "role": "symbol",
      "title": "NLLanguage",
      "type": "topic",
      "url": "/documentation/naturallanguage/nllanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger": {
      "abstract": [
        {
          "text": "A tagger that analyzes natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLTagger"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagger"
        }
      ],
      "role": "symbol",
      "title": "NLTagger",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagger"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/dominantLanguage": {
      "abstract": [
        {
          "text": "The dominant language of the string set for the linguistic tagger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dominantLanguage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLLanguage",
          "text": "NLLanguage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/dominantLanguage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dominantLanguage"
        }
      ],
      "role": "symbol",
      "title": "dominantLanguage",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagger/dominantlanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/setLanguage(_:range:)": {
      "abstract": [
        {
          "text": "Sets the language for a range of text within the tagger’s string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setLanguage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLLanguage",
          "text": "NLLanguage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS5IndexV",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/setLanguage(_:range:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setLanguage(_:range:)",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagger/setlanguage(_:range:)"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/setOrthography(_:range:)": {
      "abstract": [
        {
          "text": "Sets the orthography for the specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setOrthography"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOrthography",
          "text": "NSOrthography"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS5IndexV",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/setOrthography(_:range:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setOrthography(_:range:)",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagger/setorthography(_:range:)"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:SS5IndexV": {
      "abstract": [
        {
          "text": "A position of a character or code unit in a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Index"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS5IndexV",
      "kind": "symbol",
      "role": "symbol",
      "title": "String.Index",
      "type": "topic",
      "url": "/documentation/Swift/String/Index"
    },
    "doc://com.externally.resolved.symbol/s:Sn": {
      "abstract": [
        {
          "text": "A half-open interval from a lower bound up to, but not including, an upper bound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Bound"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Bound"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SL",
          "text": "Comparable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sn",
      "kind": "symbol",
      "role": "symbol",
      "title": "Range",
      "type": "topic",
      "url": "/documentation/Swift/Range"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-the-dominant-language-and-orthography",
      "generated": true,
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/dominantLanguage",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/setOrthography(_:range:)"
      ],
      "title": "Determining the dominant language and orthography"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguage/title",
          "value": "NLLanguage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLLanguage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagger/title",
          "value": "NLTagger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagger~1dominantLanguage/title",
          "value": "dominantLanguage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagger~1dominantLanguage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dominantLanguage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/naturallanguage/nltagger/setlanguage(_:range:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
