{
  "abstract": [
    {
      "text": "Finds multiple possible tags for a given linguistic unit, for a single scheme, at the specified character position.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/tagHypothesesAtIndex:unit:scheme:maximumCount:tokenRange:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NLTagger(im)tagHypothesesAtIndex:unit:scheme:maximumCount:tokenRange:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "tagHypothesesAtIndex:unit:scheme:maximumCount:tokenRange:"
      }
    ],
    "modules": [
      {
        "name": "Natural Language"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "tagHypothesesAtIndex:unit:scheme:maximumCount:tokenRange:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "tagHypothesesAtIndex:unit:scheme:maximumCount:tokenRange:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
              "text": "NSDictionary<NSString *,NSNumber *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "tagHypothesesAtIndex:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "characterIndex"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unit:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenUnit",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NLTokenUnit",
              "text": "NLTokenUnit"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "unit"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "scheme:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NLTagScheme",
              "text": "NLTagScheme"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "scheme"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "maximumCount:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "maximumCount"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tokenRange:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRangePointer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRangePointer",
              "text": "NSRangePointer"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "tokenRange"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The linguistic unit. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenUnit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for possible values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "unit"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The tag scheme. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for possible values. Not all tag schemes produce more than one prediction.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "scheme"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The maximum number of tag predictions to return.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "maximumCount"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The range of the token for which the tags were produced.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tokenRange"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A tuple containing a dictionary and a range.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-people-places-and-organizations"
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each dictionary entry is a predicted tag with its associated probability score. These tags are the top candidates proposed as possible tags for the token. The dictionary contains up to ",
              "type": "text"
            },
            {
              "code": "maximumCount",
              "type": "codeVoice"
            },
            {
              "text": " entries.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The range contains the range of the individual token for which these tags were produced.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage": {
      "abstract": [
        {
          "text": "Analyze natural language text and deduce its language-specific metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
      "kind": "symbol",
      "role": "collection",
      "title": "Natural Language",
      "type": "topic",
      "url": "/documentation/naturallanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme": {
      "abstract": [
        {
          "text": "Constants for the tag schemes specified when initializing a linguistic tagger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLTagScheme"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagScheme"
        }
      ],
      "role": "symbol",
      "title": "NLTagScheme",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagscheme"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger": {
      "abstract": [
        {
          "text": "A tagger that analyzes natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLTagger"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagger"
        }
      ],
      "role": "symbol",
      "title": "NLTagger",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagger"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/tagAtIndex:unit:scheme:tokenRange:": {
      "abstract": [
        {
          "text": "Finds a tag for a given linguistic unit, for a single scheme, at the specified character position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "tagAtIndex:unit:scheme:tokenRange:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/tagAtIndex:unit:scheme:tokenRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tagAtIndex:unit:scheme:tokenRange:"
        }
      ],
      "role": "symbol",
      "title": "tagAtIndex:unit:scheme:tokenRange:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagger/tagatindex:unit:scheme:tokenrange:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/tagHypothesesAtIndex:unit:scheme:maximumCount:tokenRange:": {
      "abstract": [
        {
          "text": "Finds multiple possible tags for a given linguistic unit, for a single scheme, at the specified character position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "tagHypothesesAtIndex:unit:scheme:maximumCount:tokenRange:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/tagHypothesesAtIndex:unit:scheme:maximumCount:tokenRange:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tagHypothesesAtIndex:unit:scheme:maximumCount:tokenRange:"
        }
      ],
      "role": "symbol",
      "title": "tagHypothesesAtIndex:unit:scheme:maximumCount:tokenRange:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagger/taghypothesesatindex:unit:scheme:maximumcount:tokenrange:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/tagsInRange:unit:scheme:options:tokenRanges:": {
      "abstract": [
        {
          "text": "Finds an array of linguistic tags and token ranges for a given string range and linguistic unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "tagsInRange:unit:scheme:options:tokenRanges:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/tagsInRange:unit:scheme:options:tokenRanges:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tagsInRange:unit:scheme:options:tokenRanges:"
        }
      ],
      "role": "symbol",
      "title": "tagsInRange:unit:scheme:options:tokenRanges:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagger/tagsinrange:unit:scheme:options:tokenranges:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenUnit": {
      "abstract": [
        {
          "text": "Constants representing linguistic units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLTokenUnit"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTokenUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTokenUnit"
        }
      ],
      "role": "symbol",
      "title": "NLTokenUnit",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltokenunit"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-people-places-and-organizations": {
      "abstract": [
        {
          "text": "Use a linguistic tagger to perform named entity recognition on a string.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/identifying-people-places-and-organizations",
      "kind": "article",
      "role": "article",
      "title": "Identifying people, places, and organizations",
      "type": "topic",
      "url": "/documentation/naturallanguage/identifying-people-places-and-organizations"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSRangePointer": {
      "abstract": [
        {
          "text": "Type indicating a parameter is a pointer to an `NSRange` structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSRangePointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRangePointer",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRangePointer",
      "type": "topic",
      "url": "/documentation/foundation/nsrangepointer"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-linguistic-tags",
      "generated": true,
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/tagsInRange:unit:scheme:options:tokenRanges:",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger/tagAtIndex:unit:scheme:tokenRange:"
      ],
      "title": "Getting linguistic tags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme/title",
          "value": "NLTagScheme"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagScheme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagScheme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTokenUnit/title",
          "value": "NLTokenUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTokenUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTokenUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTokenUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTokenUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagger/title",
          "value": "NLTagger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagger"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/naturallanguage/nltagger/taghypothesesatindex:unit:scheme:maximumcount:tokenrange:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
