{
  "abstract": [
    {
      "text": "An activation type that implements the hard shrink activation function.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardShrink"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCActivationType@MLCActivationTypeHardShrink",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "hardShrink"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCActivationTypeHardShrink"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MLCActivationType.hardShrink"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hardShrink"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This activation type implements the following function:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "f(x) = x",
              "type": "codeVoice"
            },
            {
              "text": ", if ",
              "type": "text"
            },
            {
              "code": "x > a",
              "type": "codeVoice"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "code": "x < −a",
              "type": "codeVoice"
            },
            {
              "text": ", else ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType": {
      "abstract": [
        {
          "text": "An activation type that you specify for an activation descriptor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCActivationType"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationType"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/absolute": {
      "abstract": [
        {
          "text": "An activation type that implements the absolute activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "absolute"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/absolute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeAbsolute"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.absolute",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/absolute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/celu": {
      "abstract": [
        {
          "text": "An activation type that implements the CELU activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "celu"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/celu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeCELU"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.celu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/celu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/clamp": {
      "abstract": [
        {
          "text": "An activation type that implements the clamp activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clamp"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/clamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeClamp"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.clamp",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/clamp"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/elu": {
      "abstract": [
        {
          "text": "An activation type that implements the exponential linear unit activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elu"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/elu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeELU"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.elu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/elu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/gelu": {
      "abstract": [
        {
          "text": "An activation type that implements the gaussian error linear unit activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gelu"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/gelu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeGELU"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.gelu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/gelu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardShrink": {
      "abstract": [
        {
          "text": "An activation type that implements the hard shrink activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardShrink"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardShrink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeHardShrink"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.hardShrink",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/hardshrink"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSigmoid": {
      "abstract": [
        {
          "text": "An activation type that implements the hard sigmoid activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardSigmoid"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeHardSigmoid"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.hardSigmoid",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/hardsigmoid"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSwish": {
      "abstract": [
        {
          "text": "An activation type that implements the hard swish activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hardSwish"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSwish",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeHardSwish"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.hardSwish",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/hardswish"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/linear": {
      "abstract": [
        {
          "text": "An activation type that implements the linear activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linear"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeLinear"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.linear",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/linear"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/logSigmoid": {
      "abstract": [
        {
          "text": "An activation type that implements the log sigmoid activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "logSigmoid"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/logSigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeLogSigmoid"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.logSigmoid",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/logsigmoid"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/none": {
      "abstract": [
        {
          "text": "An activation type that implements the identity function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeNone"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.none",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/none"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relu": {
      "abstract": [
        {
          "text": "An activation type that implements the rectified linear unit activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relu"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeReLU"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.relu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/relu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relun": {
      "abstract": [
        {
          "text": "An activation type that implements the ReLUN activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relun"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeReLUN"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.relun",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/relun"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/selu": {
      "abstract": [
        {
          "text": "An activation type that implements the scaled exponential linear unit activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selu"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/selu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeSELU"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.selu",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/selu"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/sigmoid": {
      "abstract": [
        {
          "text": "An activation type that implements the sigmoid activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sigmoid"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/sigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeSigmoid"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.sigmoid",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/sigmoid"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softPlus": {
      "abstract": [
        {
          "text": "An activation type that implements the soft plus activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "softPlus"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softPlus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCActivationTypeSoftPlus"
        }
      ],
      "role": "symbol",
      "title": "MLCActivationType.softPlus",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcactivationtype/softplus"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/absolute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/celu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/clamp",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/elu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/gelu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSigmoid",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSwish",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/linear",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/logSigmoid",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/none",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relun",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/selu",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/sigmoid",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softPlus"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCActivationTypeHardShrink"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeHardShrink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/absolute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/celu",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/clamp",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/elu",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/gelu",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSigmoid",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/hardSwish",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/linear",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/logSigmoid",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/none",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relu",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/relun",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/selu",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/sigmoid",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCActivationType/softPlus"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MLCActivationTypeHardShrink"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1elu/title",
          "value": "MLCActivationTypeELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1elu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1hardSwish/title",
          "value": "MLCActivationTypeHardSwish"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1hardSwish/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeHardSwish"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1linear/title",
          "value": "MLCActivationTypeLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1celu/title",
          "value": "MLCActivationTypeCELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1celu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeCELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1none/title",
          "value": "MLCActivationTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1sigmoid/title",
          "value": "MLCActivationTypeSigmoid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1sigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeSigmoid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1hardSigmoid/title",
          "value": "MLCActivationTypeHardSigmoid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1hardSigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeHardSigmoid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1relu/title",
          "value": "MLCActivationTypeReLU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1relu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeReLU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1logSigmoid/title",
          "value": "MLCActivationTypeLogSigmoid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1logSigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeLogSigmoid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType/title",
          "value": "MLCActivationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1absolute/title",
          "value": "MLCActivationTypeAbsolute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1absolute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeAbsolute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1softPlus/title",
          "value": "MLCActivationTypeSoftPlus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1softPlus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeSoftPlus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1hardShrink/title",
          "value": "MLCActivationTypeHardShrink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1hardShrink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeHardShrink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1selu/title",
          "value": "MLCActivationTypeSELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1selu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeSELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1gelu/title",
          "value": "MLCActivationTypeGELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1gelu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeGELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1relun/title",
          "value": "MLCActivationTypeReLUN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1relun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeReLUN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1clamp/title",
          "value": "MLCActivationTypeClamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCActivationType~1clamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCActivationTypeClamp"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcactivationtype/hardshrink"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcactivationtype/hardshrink"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
