{
  "abstract": [
    {
      "text": "IdentityLookup error codes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.identitylookup/documentation/IdentityLookup",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ILMessageFilterError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "SMS and Call Reporting"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ILMessageFilterError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup": {
      "abstract": [
        {
          "text": "Create app extensions to manage and report unwanted SMS messages and spam calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup",
      "kind": "symbol",
      "role": "collection",
      "title": "SMS and Call Reporting",
      "type": "topic",
      "url": "/documentation/identitylookup"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct": {
      "abstract": [
        {
          "text": "An error type that indicates problems with network requests and responses related to IdentityLookup APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILMessageFilterError"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterError"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code": {
      "abstract": [
        {
          "text": "IdentityLookup error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError.Code",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/invalidNetworkURL": {
      "abstract": [
        {
          "text": "The network request URL given by the ",
          "type": "text"
        },
        {
          "code": "ILMessageFilterExtensionNetworkURL",
          "type": "codeVoice"
        },
        {
          "text": " key in the app extension’s ",
          "type": "text"
        },
        {
          "code": "Info.plist",
          "type": "codeVoice"
        },
        {
          "text": " file is either missing or invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidNetworkURL"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/invalidNetworkURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterErrorInvalidNetworkURL"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError.Code.invalidNetworkURL",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code/invalidnetworkurl"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkRequestFailed": {
      "abstract": [
        {
          "text": "The network request failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkRequestFailed"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkRequestFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterErrorNetworkRequestFailed"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError.Code.networkRequestFailed",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code/networkrequestfailed"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkURLUnauthorized": {
      "abstract": [
        {
          "text": "The app extension’s containing app isn’t authorized to allow the app extension to defer network requests to the host specified in its ",
          "type": "text"
        },
        {
          "code": "Info.plist",
          "type": "codeVoice"
        },
        {
          "text": " file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkURLUnauthorized"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkURLUnauthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterErrorNetworkURLUnauthorized"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError.Code.networkURLUnauthorized",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code/networkurlunauthorized"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/redundantNetworkDeferral": {
      "abstract": [
        {
          "text": "The app extension tried to defer a request to its network service more than once, which isn’t allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "redundantNetworkDeferral"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/redundantNetworkDeferral",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterErrorRedundantNetworkDeferral"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError.Code.redundantNetworkDeferral",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code/redundantnetworkdeferral"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/system": {
      "abstract": [
        {
          "text": "An unspecified system error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "system"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/system",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterErrorSystem"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError.Code.system",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code/system"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for errors associated with the IdentityLookup APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILMessageFilterErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterErrorDomain",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererrordomain"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/system",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/invalidNetworkURL",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkURLUnauthorized",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkRequestFailed",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/redundantNetworkDeferral"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ILMessageFilterError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.identitylookup/documentation/IdentityLookup"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/system",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/invalidNetworkURL",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkURLUnauthorized",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/networkRequestFailed",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code/redundantNetworkDeferral"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ILMessageFilterError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterErrorDomain/title",
          "value": "ILMessageFilterErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1networkRequestFailed/title",
          "value": "ILMessageFilterErrorNetworkRequestFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1networkRequestFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterErrorNetworkRequestFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1redundantNetworkDeferral/title",
          "value": "ILMessageFilterErrorRedundantNetworkDeferral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1redundantNetworkDeferral/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterErrorRedundantNetworkDeferral"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code/title",
          "value": "ILMessageFilterError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1networkURLUnauthorized/title",
          "value": "ILMessageFilterErrorNetworkURLUnauthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1networkURLUnauthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterErrorNetworkURLUnauthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1system/title",
          "value": "ILMessageFilterErrorSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1system/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterErrorSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1invalidNetworkURL/title",
          "value": "ILMessageFilterErrorInvalidNetworkURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code~1invalidNetworkURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterErrorInvalidNetworkURL"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
