{
  "abstract": [
    {
      "text": "The app extension tried to defer a request to its network service more than once, which isn’t allowed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.identitylookup/documentation/IdentityLookup",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/redundantNetworkDeferral"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC20ILMessageFilterErrorLeV24redundantNetworkDeferralSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "redundantNetworkDeferral"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC20ILMessageFilterErrorLeV",
        "text": "ILMessageFilterError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@ILMessageFilterError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "SMS and Call Reporting"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "redundantNetworkDeferral"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "redundantNetworkDeferral"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC20ILMessageFilterErrorLeV",
              "text": "ILMessageFilterError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ILMessageFilterError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup": {
      "abstract": [
        {
          "text": "Create app extensions to manage and report unwanted SMS messages and spam calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup",
      "kind": "symbol",
      "role": "collection",
      "title": "SMS and Call Reporting",
      "type": "topic",
      "url": "/documentation/identitylookup"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct": {
      "abstract": [
        {
          "text": "An error type that indicates problems with network requests and responses related to IdentityLookup APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILMessageFilterError"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterError"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code": {
      "abstract": [
        {
          "text": "IdentityLookup error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterError.Code",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/code"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/invalidNetworkURL": {
      "abstract": [
        {
          "text": "The network request URL given by the ",
          "type": "text"
        },
        {
          "code": "ILMessageFilterExtensionNetworkURL",
          "type": "codeVoice"
        },
        {
          "text": " key in the app extension’s information property list file is either missing or invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidNetworkURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC20ILMessageFilterErrorLeV",
          "text": "ILMessageFilterError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ILMessageFilterError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/invalidNetworkURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidNetworkURL",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/invalidnetworkurl"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/networkRequestFailed": {
      "abstract": [
        {
          "text": "The network request failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkRequestFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC20ILMessageFilterErrorLeV",
          "text": "ILMessageFilterError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ILMessageFilterError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/networkRequestFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "networkRequestFailed",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/networkrequestfailed"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/networkURLUnauthorized": {
      "abstract": [
        {
          "text": "The app extension’s containing app isn’t authorized to allow the app extension to defer network requests to the host specified in its information property list file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkURLUnauthorized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC20ILMessageFilterErrorLeV",
          "text": "ILMessageFilterError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ILMessageFilterError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/networkURLUnauthorized",
      "kind": "symbol",
      "role": "symbol",
      "title": "networkURLUnauthorized",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/networkurlunauthorized"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/redundantNetworkDeferral": {
      "abstract": [
        {
          "text": "The app extension tried to defer a request to its network service more than once, which isn’t allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "redundantNetworkDeferral"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC20ILMessageFilterErrorLeV",
          "text": "ILMessageFilterError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ILMessageFilterError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/redundantNetworkDeferral",
      "kind": "symbol",
      "role": "symbol",
      "title": "redundantNetworkDeferral",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/redundantnetworkdeferral"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/system": {
      "abstract": [
        {
          "text": "An unspecified system error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "system"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC20ILMessageFilterErrorLeV",
          "text": "ILMessageFilterError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ILMessageFilterError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/system",
      "kind": "symbol",
      "role": "symbol",
      "title": "system",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltererror-swift.struct/system"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/invalidNetworkURL",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/networkRequestFailed",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/networkURLUnauthorized",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterError-swift.struct/system"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code/title",
          "value": "ILMessageFilterError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/identitylookup/ilmessagefiltererror-swift.struct/redundantnetworkdeferral"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
