{
  "abstract": [
    {
      "text": "The accessory should add water to the air.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueTargetHumidifierDehumidifierState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueTargetHumidifierDehumidifierState/humidify"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HMCharacteristicValueTargetHumidifierDehumidifierState@HMCharacteristicValueTargetHumidifierDehumidifierStateHumidify",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "humidify"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCharacteristicValueTargetHumidifierDehumidifierStateHumidify"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.1.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HMCharacteristicValueTargetHumidifierDehumidifierState.humidify"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "humidify"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueTargetHumidifierDehumidifierState": {
      "abstract": [
        {
          "text": "Possible values for the target humidifier or dehumidifier state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueTargetHumidifierDehumidifierState"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueTargetHumidifierDehumidifierState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueTargetHumidifierDehumidifierState"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueTargetHumidifierDehumidifierState",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluetargethumidifierdehumidifierstate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueTargetHumidifierDehumidifierState/automatic": {
      "abstract": [
        {
          "text": "The accessory should decide whether to add or remove water to or from the air.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueTargetHumidifierDehumidifierState/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueTargetHumidifierDehumidifierStateAutomatic"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueTargetHumidifierDehumidifierState.automatic",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluetargethumidifierdehumidifierstate/automatic"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueTargetHumidifierDehumidifierState/dehumidify": {
      "abstract": [
        {
          "text": "The accessory should remove water from the air.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dehumidify"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueTargetHumidifierDehumidifierState/dehumidify",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueTargetHumidifierDehumidifierStateDehumidify"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueTargetHumidifierDehumidifierState.dehumidify",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluetargethumidifierdehumidifierstate/dehumidify"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueTargetHumidifierDehumidifierState/humidify": {
      "abstract": [
        {
          "text": "The accessory should add water to the air.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "humidify"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueTargetHumidifierDehumidifierState/humidify",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueTargetHumidifierDehumidifierStateHumidify"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueTargetHumidifierDehumidifierState.humidify",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluetargethumidifierdehumidifierstate/humidify"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Target-States",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueTargetHumidifierDehumidifierState/automatic",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueTargetHumidifierDehumidifierState/dehumidify"
      ],
      "title": "Target States"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.1.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCharacteristicValueTargetHumidifierDehumidifierStateHumidify"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueTargetHumidifierDehumidifierStateHumidify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueTargetHumidifierDehumidifierState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Target-States",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueTargetHumidifierDehumidifierState/automatic",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueTargetHumidifierDehumidifierState/dehumidify"
              ],
              "title": "Target States"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HMCharacteristicValueTargetHumidifierDehumidifierStateHumidify"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueTargetHumidifierDehumidifierState~1dehumidify/title",
          "value": "HMCharacteristicValueTargetHumidifierDehumidifierStateDehumidify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueTargetHumidifierDehumidifierState~1dehumidify/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueTargetHumidifierDehumidifierStateDehumidify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueTargetHumidifierDehumidifierState/title",
          "value": "HMCharacteristicValueTargetHumidifierDehumidifierState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueTargetHumidifierDehumidifierState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueTargetHumidifierDehumidifierState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueTargetHumidifierDehumidifierState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueTargetHumidifierDehumidifierState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueTargetHumidifierDehumidifierState~1humidify/title",
          "value": "HMCharacteristicValueTargetHumidifierDehumidifierStateHumidify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueTargetHumidifierDehumidifierState~1humidify/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueTargetHumidifierDehumidifierStateHumidify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueTargetHumidifierDehumidifierState~1automatic/title",
          "value": "HMCharacteristicValueTargetHumidifierDehumidifierStateAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueTargetHumidifierDehumidifierState~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueTargetHumidifierDehumidifierStateAutomatic"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcharacteristicvaluetargethumidifierdehumidifierstate/humidify"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcharacteristicvaluetargethumidifierdehumidifierstate/humidify"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
