{
  "abstract": [
    {
      "text": "Allows image content to use extended dynamic range if it has dynamic range content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSImage",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange/high"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSImageDynamicRange@NSImageDynamicRangeHigh",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "high"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSImageDynamicRangeHigh"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSImage.DynamicRange.high"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "high"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage": {
      "abstract": [
        {
          "text": "A high-level interface for manipulating image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "role": "symbol",
      "title": "NSImage",
      "type": "topic",
      "url": "/documentation/appkit/nsimage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange": {
      "abstract": [
        {
          "text": "Describes how High Dynamic Range (HDR) image content displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DynamicRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DynamicRange"
        }
      ],
      "role": "symbol",
      "title": "NSImage.DynamicRange",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/dynamicrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange/constrainedHigh": {
      "abstract": [
        {
          "text": "Allows for constrained High Dynamic Range (HDR) image content which is useful for mixing HDR and Standard Dynamic Range (SDR) content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constrainedHigh"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange/constrainedHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageDynamicRangeConstrainedHigh"
        }
      ],
      "role": "symbol",
      "title": "NSImage.DynamicRange.constrainedHigh",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/dynamicrange/constrainedhigh"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange/high": {
      "abstract": [
        {
          "text": "Allows image content to use extended dynamic range if it has dynamic range content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageDynamicRangeHigh"
        }
      ],
      "role": "symbol",
      "title": "NSImage.DynamicRange.high",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/dynamicrange/high"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange/standard": {
      "abstract": [
        {
          "text": "Restricts the image content dynamic range to the standard range regardless of the actual range of the image content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standard"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange/standard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageDynamicRangeStandard"
        }
      ],
      "role": "symbol",
      "title": "NSImage.DynamicRange.standard",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/dynamicrange/standard"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange/unspecified": {
      "abstract": [
        {
          "text": "Indicates that the dynamic range treatment of the image is unknown or otherwise unspecified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageDynamicRangeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "NSImage.DynamicRange.unspecified",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/dynamicrange/unspecified"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-the-dynamic-range",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange/standard",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange/constrainedHigh",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange/unspecified"
      ],
      "title": "Setting the dynamic range"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSImageDynamicRangeHigh"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDynamicRangeHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-the-dynamic-range",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange/standard",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange/constrainedHigh",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange/unspecified"
              ],
              "title": "Setting the dynamic range"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSImageDynamicRangeHigh"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange~1constrainedHigh/title",
          "value": "NSImageDynamicRangeConstrainedHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange~1constrainedHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDynamicRangeConstrainedHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange~1unspecified/title",
          "value": "NSImageDynamicRangeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDynamicRangeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange~1high/title",
          "value": "NSImageDynamicRangeHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDynamicRangeHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange~1standard/title",
          "value": "NSImageDynamicRangeStandard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange~1standard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDynamicRangeStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange/title",
          "value": "NSImageDynamicRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDynamicRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDynamicRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title",
          "value": "NSImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsimage/dynamicrange/high"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsimage/dynamicrange/high"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
