{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_WARN_DEPRECATED"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@CA_WARN_DEPRECATED",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CA_WARN_DEPRECATED"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CA_WARN_DEPRECATED"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "CA_WARN_DEPRECATED"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CA_WARN_DEPRECATED"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_BOXABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_BOXABLE"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_BOXABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_BOXABLE",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_boxable"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_CONST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_CONST"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_CONST",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_CONST",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_const"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_DEPRECATED",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_deprecated"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_EXTERN",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_extern"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN_C_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_EXTERN_C_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN_C_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_EXTERN_C_BEGIN",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_extern_c_begin"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN_C_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_EXTERN_C_END"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN_C_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_EXTERN_C_END",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_extern_c_end"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_GNUC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_GNUC"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_GNUC",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_GNUC",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_gnuc"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_INLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_INLINE"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_INLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_INLINE",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_inline"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_MALLOC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_MALLOC"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_MALLOC",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_MALLOC",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_malloc"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_NOINLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_NOINLINE"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_NOINLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_NOINLINE",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_noinline"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_NORETURN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_NORETURN"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_NORETURN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_NORETURN",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_noreturn"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_PURE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_PURE"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_PURE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_PURE",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_pure"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_WARN_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CA_WARN_DEPRECATED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_WARN_DEPRECATED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CA_WARN_DEPRECATED"
        }
      ],
      "role": "symbol",
      "title": "CA_WARN_DEPRECATED",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_warn_deprecated"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_WARN_UNUSED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_WARN_UNUSED"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_WARN_UNUSED",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_WARN_UNUSED",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_warn_unused"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CA_WARN_DEPRECATED"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CA_WARN_DEPRECATED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_BOXABLE",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_CONST",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_DEPRECATED",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN_C_BEGIN",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN_C_END",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_GNUC",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_INLINE",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_MALLOC",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_NOINLINE",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_NORETURN",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_PURE",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_WARN_UNUSED"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CA_WARN_DEPRECATED"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CA_WARN_DEPRECATED/title",
          "value": "CA_WARN_DEPRECATED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CA_WARN_DEPRECATED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CA_WARN_DEPRECATED"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/ca_warn_deprecated"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/ca_warn_deprecated"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
