{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CACornerMask",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CACornerMask"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CACornerMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CACornerMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CACornerMask"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CACornerMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CACornerMask"
        }
      ],
      "role": "symbol",
      "title": "CACornerMask",
      "type": "topic",
      "url": "/documentation/quartzcore/cacornermask"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/quartzcore/cacornermask/init(rawvalue:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMaxXMaxYCorner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerMaxXMaxYCorner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CACornerMask",
          "text": "CACornerMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMaxXMaxYCorner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCALayerMaxXMaxYCorner"
        }
      ],
      "role": "symbol",
      "title": "layerMaxXMaxYCorner",
      "type": "topic",
      "url": "/documentation/quartzcore/cacornermask/layermaxxmaxycorner"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMaxXMinYCorner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerMaxXMinYCorner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CACornerMask",
          "text": "CACornerMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMaxXMinYCorner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCALayerMaxXMinYCorner"
        }
      ],
      "role": "symbol",
      "title": "layerMaxXMinYCorner",
      "type": "topic",
      "url": "/documentation/quartzcore/cacornermask/layermaxxminycorner"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMinXMaxYCorner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerMinXMaxYCorner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CACornerMask",
          "text": "CACornerMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMinXMaxYCorner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCALayerMinXMaxYCorner"
        }
      ],
      "role": "symbol",
      "title": "layerMinXMaxYCorner",
      "type": "topic",
      "url": "/documentation/quartzcore/cacornermask/layerminxmaxycorner"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMinXMinYCorner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerMinXMinYCorner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CACornerMask",
          "text": "CACornerMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMinXMinYCorner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCALayerMinXMinYCorner"
        }
      ],
      "role": "symbol",
      "title": "layerMinXMinYCorner",
      "type": "topic",
      "url": "/documentation/quartzcore/cacornermask/layerminxminycorner"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundColor": {
      "abstract": [
        {
          "text": "The background color of the receiver. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundColor"
        }
      ],
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/backgroundcolor"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderColor": {
      "abstract": [
        {
          "text": "The color of the layer’s border. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderColor"
        }
      ],
      "role": "symbol",
      "title": "borderColor",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/bordercolor"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderWidth": {
      "abstract": [
        {
          "text": "The width of the layer’s border. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderWidth"
        }
      ],
      "role": "symbol",
      "title": "borderWidth",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/borderwidth"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsGravity": {
      "abstract": [
        {
          "text": "A constant that specifies how the layer’s contents are positioned or scaled within its bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentsGravity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsGravity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentsGravity"
        }
      ],
      "role": "symbol",
      "title": "contentsGravity",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/contentsgravity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/cornerRadius": {
      "abstract": [
        {
          "text": "The radius to use when drawing rounded corners for the layer’s background. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cornerRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/cornerRadius",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cornerRadius"
        }
      ],
      "role": "symbol",
      "title": "cornerRadius",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/cornerradius"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isDoubleSided": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the layer displays its content when facing away from the viewer. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDoubleSided"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isDoubleSided",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doubleSided"
        }
      ],
      "role": "symbol",
      "title": "isDoubleSided",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/isdoublesided"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isHidden": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the layer is displayed. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hidden"
        }
      ],
      "role": "symbol",
      "title": "isHidden",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/ishidden"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/mask": {
      "abstract": [
        {
          "text": "An optional layer whose alpha channel is used to mask the layer’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CALayer",
          "text": "CALayer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/mask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mask"
        }
      ],
      "role": "symbol",
      "title": "mask",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/mask"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/maskedCorners": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maskedCorners"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CACornerMask",
          "text": "CACornerMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/maskedCorners",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maskedCorners"
        }
      ],
      "role": "symbol",
      "title": "maskedCorners",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/maskedcorners"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/masksToBounds": {
      "abstract": [
        {
          "text": "A Boolean indicating whether sublayers are clipped to the layer’s bounds. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "masksToBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/masksToBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "masksToBounds"
        }
      ],
      "role": "symbol",
      "title": "masksToBounds",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/maskstobounds"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/opacity": {
      "abstract": [
        {
          "text": "The opacity of the receiver. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/opacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "opacity"
        }
      ],
      "role": "symbol",
      "title": "opacity",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/opacity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOffset": {
      "abstract": [
        {
          "text": "The offset (in points) of the layer’s shadow. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadowOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shadowOffset"
        }
      ],
      "role": "symbol",
      "title": "shadowOffset",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/shadowoffset"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOpacity": {
      "abstract": [
        {
          "text": "The opacity of the layer’s shadow. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadowOpacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOpacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shadowOpacity"
        }
      ],
      "role": "symbol",
      "title": "shadowOpacity",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/shadowopacity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowRadius": {
      "abstract": [
        {
          "text": "The blur radius (in points) used to render the layer’s shadow. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadowRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowRadius",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shadowRadius"
        }
      ],
      "role": "symbol",
      "title": "shadowRadius",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/shadowradius"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/contents-gravity-values": {
      "abstract": [
        {
          "text": "The contents gravity constants specify the position of the content object when the layer bounds is larger than the bounds of the content object. They are used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsGravity",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/contents-gravity-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Contents Gravity Values",
      "type": "topic",
      "url": "/documentation/quartzcore/contents-gravity-values"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Modifying-the-Layers-Appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsGravity",
        "doc://com.apple.quartzcore/documentation/QuartzCore/contents-gravity-values",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/opacity",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isHidden",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/masksToBounds",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/mask",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isDoubleSided",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/cornerRadius",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/maskedCorners",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderWidth",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderColor",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundColor",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOpacity",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowRadius",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOffset"
      ],
      "title": "Modifying the Layer’s Appearance"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/init(rawValue:)",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMaxXMaxYCorner",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMaxXMinYCorner",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMinXMaxYCorner",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMinXMinYCorner"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CACornerMask"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CACornerMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CACornerMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMaxXMaxYCorner",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMaxXMinYCorner",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMinXMaxYCorner",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask/layerMinXMinYCorner"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Modifying-the-Layers-Appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsGravity",
                "doc://com.apple.quartzcore/documentation/QuartzCore/contents-gravity-values",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/opacity",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isHidden",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/masksToBounds",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/mask",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isDoubleSided",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/cornerRadius",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/maskedCorners",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderWidth",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderColor",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundColor",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOpacity",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowRadius",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOffset"
              ],
              "title": "Modifying the Layer’s Appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CACornerMask"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask/title",
          "value": "CACornerMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CACornerMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CACornerMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1borderWidth/title",
          "value": "borderWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1borderWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "borderWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1masksToBounds/title",
          "value": "masksToBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1masksToBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "masksToBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1cornerRadius/title",
          "value": "cornerRadius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1cornerRadius/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cornerRadius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1opacity/title",
          "value": "opacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1opacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "opacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1borderColor/title",
          "value": "borderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1borderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "borderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1contentsGravity/title",
          "value": "contentsGravity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1contentsGravity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentsGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask~1layerMaxXMinYCorner/title",
          "value": "kCALayerMaxXMinYCorner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask~1layerMaxXMinYCorner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCALayerMaxXMinYCorner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1mask/title",
          "value": "mask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1mask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowOffset/title",
          "value": "shadowOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shadowOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1isDoubleSided/title",
          "value": "doubleSided"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1isDoubleSided/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "doubleSided"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask~1layerMinXMinYCorner/title",
          "value": "kCALayerMinXMinYCorner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask~1layerMinXMinYCorner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCALayerMinXMinYCorner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1maskedCorners/title",
          "value": "maskedCorners"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1maskedCorners/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maskedCorners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask~1layerMaxXMaxYCorner/title",
          "value": "kCALayerMaxXMaxYCorner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask~1layerMaxXMaxYCorner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCALayerMaxXMaxYCorner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask~1layerMinXMaxYCorner/title",
          "value": "kCALayerMinXMaxYCorner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask~1layerMinXMaxYCorner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCALayerMinXMaxYCorner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1isHidden/title",
          "value": "hidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1isHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowRadius/title",
          "value": "shadowRadius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowRadius/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shadowRadius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowOpacity/title",
          "value": "shadowOpacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowOpacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shadowOpacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1backgroundColor/title",
          "value": "backgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1backgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/cacornermask"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/cacornermask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
