{
  "abstract": [
    {
      "text": "The definition of a particle emitted by a particle layer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CAEmitterCell",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CAEmitterCell"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CAEmitterCell"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CAEmitterCell"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CAEmitterCell"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class represents one source of particles being emitted by a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. An emitter cell defines the direction and properties of the emitted particles. Emitter cells can have an array of sub-cells, which lets the particles themselves emit particles.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell": {
      "abstract": [
        {
          "text": "The definition of a particle emitted by a particle layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEmitterCell"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEmitterCell"
        }
      ],
      "role": "symbol",
      "title": "CAEmitterCell",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/alphaRange": {
      "abstract": [
        {
          "text": "The amount by which the alpha component of the cell can vary. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alphaRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/alphaRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alphaRange"
        }
      ],
      "role": "symbol",
      "title": "alphaRange",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/alpharange"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/alphaSpeed": {
      "abstract": [
        {
          "text": "The speed, in seconds, at which the alpha component changes over the lifetime of the cell. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alphaSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/alphaSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alphaSpeed"
        }
      ],
      "role": "symbol",
      "title": "alphaSpeed",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/alphaspeed"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/birthRate": {
      "abstract": [
        {
          "text": "The number of emitted objects created every second. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "birthRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/birthRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "birthRate"
        }
      ],
      "role": "symbol",
      "title": "birthRate",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/birthrate"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/blueRange": {
      "abstract": [
        {
          "text": "The amount by which the blue color component of the cell can vary. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blueRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/blueRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "blueRange"
        }
      ],
      "role": "symbol",
      "title": "blueRange",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/bluerange"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/blueSpeed": {
      "abstract": [
        {
          "text": "The speed, in seconds, at which the blue color component changes over the lifetime of the cell. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blueSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/blueSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "blueSpeed"
        }
      ],
      "role": "symbol",
      "title": "blueSpeed",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/bluespeed"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/color": {
      "abstract": [
        {
          "text": "The color of each emitted object. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "color"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/color",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "color"
        }
      ],
      "role": "symbol",
      "title": "color",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/color"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/contents": {
      "abstract": [
        {
          "text": "An object that provides the contents of the layer. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/contents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contents"
        }
      ],
      "role": "symbol",
      "title": "contents",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/contents"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/contentsRect": {
      "abstract": [
        {
          "text": "A rectangle (in the unit coordinate space) that specifies the portion of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/contents",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " that the receiver should draw. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentsRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/contentsRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentsRect"
        }
      ],
      "role": "symbol",
      "title": "contentsRect",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/contentsrect"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/contentsScale": {
      "abstract": [
        {
          "text": "The scale factor of the cell contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentsScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/contentsScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentsScale"
        }
      ],
      "role": "symbol",
      "title": "contentsScale",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/contentsscale"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/defaultValue(forKey:)": {
      "abstract": [
        {
          "text": "Returns the default value of the property with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/defaultValue(forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultValueForKey:"
        }
      ],
      "role": "symbol",
      "title": "defaultValue(forKey:)",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/defaultvalue(forkey:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emissionLatitude": {
      "abstract": [
        {
          "text": "The latitudinal orientation of the emission angle. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emissionLatitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emissionLatitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emissionLatitude"
        }
      ],
      "role": "symbol",
      "title": "emissionLatitude",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/emissionlatitude"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emissionLongitude": {
      "abstract": [
        {
          "text": "The longitudinal orientation of the emission angle. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emissionLongitude"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emissionLongitude",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emissionLongitude"
        }
      ],
      "role": "symbol",
      "title": "emissionLongitude",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/emissionlongitude"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emissionRange": {
      "abstract": [
        {
          "text": "The angle, in radians, defining a cone around the emission angle. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emissionRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emissionRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emissionRange"
        }
      ],
      "role": "symbol",
      "title": "emissionRange",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/emissionrange"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emitterCell": {
      "abstract": [
        {
          "text": "Creates and returns an instance of ",
          "type": "text"
        },
        {
          "code": "CAEmitterCell",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "emitterCell"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emitterCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emitterCell"
        }
      ],
      "role": "symbol",
      "title": "emitterCell",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/emittercell"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emitterCells": {
      "abstract": [
        {
          "text": "An optional array containing the sub-cells of this cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emitterCells"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CAEmitterCell",
          "text": "CAEmitterCell"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emitterCells",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emitterCells"
        }
      ],
      "role": "symbol",
      "title": "emitterCells",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/emittercells"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/greenRange": {
      "abstract": [
        {
          "text": "The amount by which the green color component of the cell can vary. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "greenRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/greenRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "greenRange"
        }
      ],
      "role": "symbol",
      "title": "greenRange",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/greenrange"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/greenSpeed": {
      "abstract": [
        {
          "text": "The speed, in seconds, at which the green color component changes over the lifetime of the cell. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "greenSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/greenSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "greenSpeed"
        }
      ],
      "role": "symbol",
      "title": "greenSpeed",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/greenspeed"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/isEnabled": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether or not cells from this emitter are rendered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/isEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "role": "symbol",
      "title": "isEnabled",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/isenabled"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/lifetime": {
      "abstract": [
        {
          "text": "The lifetime of the cell, in seconds. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lifetime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/lifetime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lifetime"
        }
      ],
      "role": "symbol",
      "title": "lifetime",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/lifetime"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/lifetimeRange": {
      "abstract": [
        {
          "text": "The mean value by which the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/lifetime",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " of the cell can vary. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lifetimeRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/lifetimeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lifetimeRange"
        }
      ],
      "role": "symbol",
      "title": "lifetimeRange",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/lifetimerange"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/magnificationFilter": {
      "abstract": [
        {
          "text": "The filter used when increasing the size of the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magnificationFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/magnificationFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "magnificationFilter"
        }
      ],
      "role": "symbol",
      "title": "magnificationFilter",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/magnificationfilter"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/minificationFilter": {
      "abstract": [
        {
          "text": "The filter used when reducing the size of the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minificationFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/minificationFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minificationFilter"
        }
      ],
      "role": "symbol",
      "title": "minificationFilter",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/minificationfilter"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/minificationFilterBias": {
      "abstract": [
        {
          "text": "The bias factor used by the minification filter to determine the levels of detail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minificationFilterBias"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/minificationFilterBias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minificationFilterBias"
        }
      ],
      "role": "symbol",
      "title": "minificationFilterBias",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/minificationfilterbias"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/name": {
      "abstract": [
        {
          "text": "The name of the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/name"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/redRange": {
      "abstract": [
        {
          "text": "The amount by which the red color component of the cell can vary. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "redRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/redRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "redRange"
        }
      ],
      "role": "symbol",
      "title": "redRange",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/redrange"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/redSpeed": {
      "abstract": [
        {
          "text": "The speed, in seconds, at which the red color component changes over the lifetime of the cell. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "redSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/redSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "redSpeed"
        }
      ],
      "role": "symbol",
      "title": "redSpeed",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/redspeed"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/scale": {
      "abstract": [
        {
          "text": "Specifies the scale factor applied to the cell. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scale"
        }
      ],
      "role": "symbol",
      "title": "scale",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/scale"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/scaleRange": {
      "abstract": [
        {
          "text": "Specifies the range over which the scale value can vary. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/scaleRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleRange"
        }
      ],
      "role": "symbol",
      "title": "scaleRange",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/scalerange"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/scaleSpeed": {
      "abstract": [
        {
          "text": "The speed at which the scale changes over the lifetime of the cell. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/scaleSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleSpeed"
        }
      ],
      "role": "symbol",
      "title": "scaleSpeed",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/scalespeed"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/shouldArchiveValue(forKey:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the value for a given key should be archived.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldArchiveValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/shouldArchiveValue(forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldArchiveValueForKey:"
        }
      ],
      "role": "symbol",
      "title": "shouldArchiveValue(forKey:)",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/shouldarchivevalue(forkey:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/spin": {
      "abstract": [
        {
          "text": "The rotational velocity, measured in radians per second, to apply to the cell. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/spin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "spin"
        }
      ],
      "role": "symbol",
      "title": "spin",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/spin"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/spinRange": {
      "abstract": [
        {
          "text": "The amount by which the spin of the cell can vary over its lifetime. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spinRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/spinRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "spinRange"
        }
      ],
      "role": "symbol",
      "title": "spinRange",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/spinrange"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/style": {
      "abstract": [
        {
          "text": "An optional dictionary containing additional style values that are not explicitly defined by the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/style",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "style"
        }
      ],
      "role": "symbol",
      "title": "style",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/style"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/velocity": {
      "abstract": [
        {
          "text": "The initial velocity of the cell. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "velocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/velocity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "velocity"
        }
      ],
      "role": "symbol",
      "title": "velocity",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/velocity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/velocityRange": {
      "abstract": [
        {
          "text": "The amount by which the velocity of the cell can vary. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "velocityRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/velocityRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "velocityRange"
        }
      ],
      "role": "symbol",
      "title": "velocityRange",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/velocityrange"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/xAcceleration": {
      "abstract": [
        {
          "text": "The x component of an acceleration vector applied to cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xAcceleration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/xAcceleration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xAcceleration"
        }
      ],
      "role": "symbol",
      "title": "xAcceleration",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/xacceleration"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/yAcceleration": {
      "abstract": [
        {
          "text": "The y component of an acceleration vector applied to cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yAcceleration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/yAcceleration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "yAcceleration"
        }
      ],
      "role": "symbol",
      "title": "yAcceleration",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/yacceleration"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/zAcceleration": {
      "abstract": [
        {
          "text": "The z component of an acceleration vector applied to cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zAcceleration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/zAcceleration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "zAcceleration"
        }
      ],
      "role": "symbol",
      "title": "zAcceleration",
      "type": "topic",
      "url": "/documentation/quartzcore/caemittercell/zacceleration"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer": {
      "abstract": [
        {
          "text": "A layer that emits, animates, and renders a particle system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEmitterLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEmitterLayer"
        }
      ],
      "role": "symbol",
      "title": "CAEmitterLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming": {
      "abstract": [
        {
          "text": "Methods that model a hierarchical timing system, allowing objects to map time between their parent and local time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMediaTiming"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMediaTiming"
        }
      ],
      "role": "symbol",
      "title": "CAMediaTiming",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatiming"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming",
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Particle-Systems",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer"
      ],
      "title": "Particle Systems"
    }
  ],
  "topicSections": [
    {
      "anchor": "Providing-Emitter-Cell-Content",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/contents",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/contentsRect",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emitterCells"
      ],
      "title": "Providing Emitter Cell Content"
    },
    {
      "anchor": "Setting-Emitter-Cell-Visual-Attributes",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/isEnabled",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/color",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/redRange",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/greenRange",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/blueRange",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/alphaRange",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/redSpeed",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/greenSpeed",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/blueSpeed",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/alphaSpeed",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/magnificationFilter",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/minificationFilter",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/minificationFilterBias",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/scale",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/scaleRange",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/contentsScale",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/name",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/style"
      ],
      "title": "Setting Emitter Cell Visual Attributes"
    },
    {
      "anchor": "Setting-Emitter-Cell-Motion-Attributes",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/spin",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/spinRange",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emissionLatitude",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emissionLongitude",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emissionRange"
      ],
      "title": "Setting Emitter Cell Motion Attributes"
    },
    {
      "anchor": "Setting-Emitter-Cell-Temporal-Attributes",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/lifetime",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/lifetimeRange",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/birthRate",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/scaleSpeed",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/velocity",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/velocityRange",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/xAcceleration",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/yAcceleration",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/zAcceleration"
      ],
      "title": "Setting Emitter Cell Temporal Attributes"
    },
    {
      "anchor": "Using-Key-Value-Coding-Extensions",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/defaultValue(forKey:)",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/shouldArchiveValue(forKey:)"
      ],
      "title": "Using Key-Value Coding Extensions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CAEmitterCell"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-and-Initializing-an-Emitter-Cell",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emitterCell"
              ],
              "title": "Creating and Initializing an Emitter Cell"
            },
            {
              "anchor": "Providing-Emitter-Cell-Content",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/contents",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/contentsRect",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emitterCells"
              ],
              "title": "Providing Emitter Cell Content"
            },
            {
              "anchor": "Setting-Emitter-Cell-Visual-Attributes",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/isEnabled",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/color",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/redRange",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/greenRange",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/blueRange",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/alphaRange",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/redSpeed",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/greenSpeed",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/blueSpeed",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/alphaSpeed",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/magnificationFilter",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/minificationFilter",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/minificationFilterBias",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/scale",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/scaleRange",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/contentsScale",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/name",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/style"
              ],
              "title": "Setting Emitter Cell Visual Attributes"
            },
            {
              "anchor": "Setting-Emitter-Cell-Motion-Attributes",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/spin",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/spinRange",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emissionLatitude",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emissionLongitude",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/emissionRange"
              ],
              "title": "Setting Emitter Cell Motion Attributes"
            },
            {
              "anchor": "Setting-Emitter-Cell-Temporal-Attributes",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/lifetime",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/lifetimeRange",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/birthRate",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/scaleSpeed",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/velocity",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/velocityRange",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/xAcceleration",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/yAcceleration",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/zAcceleration"
              ],
              "title": "Setting Emitter Cell Temporal Attributes"
            },
            {
              "anchor": "Using-Key-Value-Coding-Extensions",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/defaultValue(forKey:)",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterCell/shouldArchiveValue(forKey:)"
              ],
              "title": "Using Key-Value Coding Extensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Particle-Systems",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer"
              ],
              "title": "Particle Systems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CAEmitterCell"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1alphaSpeed/title",
          "value": "alphaSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1alphaSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alphaSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer/title",
          "value": "CAEmitterLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1contentsRect/title",
          "value": "contentsRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1contentsRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentsRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1magnificationFilter/title",
          "value": "magnificationFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1magnificationFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "magnificationFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1blueSpeed/title",
          "value": "blueSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1blueSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "blueSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1scaleSpeed/title",
          "value": "scaleSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1scaleSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1defaultValue(forKey:)/title",
          "value": "defaultValueForKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1defaultValue(forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "defaultValueForKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1scaleRange/title",
          "value": "scaleRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1scaleRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1emitterCells/title",
          "value": "emitterCells"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1emitterCells/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "emitterCells"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1alphaRange/title",
          "value": "alphaRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1alphaRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alphaRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1velocity/title",
          "value": "velocity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1velocity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "velocity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1scale/title",
          "value": "scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1emissionLatitude/title",
          "value": "emissionLatitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1emissionLatitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "emissionLatitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1color/title",
          "value": "color"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1color/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "color"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1lifetime/title",
          "value": "lifetime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1lifetime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lifetime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1redSpeed/title",
          "value": "redSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1redSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "redSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1style/title",
          "value": "style"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1style/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "style"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1velocityRange/title",
          "value": "velocityRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1velocityRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "velocityRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1birthRate/title",
          "value": "birthRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1birthRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "birthRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1blueRange/title",
          "value": "blueRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1blueRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "blueRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1minificationFilter/title",
          "value": "minificationFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1minificationFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minificationFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1contentsScale/title",
          "value": "contentsScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1contentsScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentsScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1contents/title",
          "value": "contents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1contents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/title",
          "value": "CAMediaTiming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTiming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTiming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1redRange/title",
          "value": "redRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1redRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "redRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1lifetimeRange/title",
          "value": "lifetimeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1lifetimeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lifetimeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell/title",
          "value": "CAEmitterCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1emissionRange/title",
          "value": "emissionRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1emissionRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "emissionRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1spinRange/title",
          "value": "spinRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1spinRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "spinRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1zAcceleration/title",
          "value": "zAcceleration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1zAcceleration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "zAcceleration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1emissionLongitude/title",
          "value": "emissionLongitude"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1emissionLongitude/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "emissionLongitude"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1minificationFilterBias/title",
          "value": "minificationFilterBias"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1minificationFilterBias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minificationFilterBias"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1shouldArchiveValue(forKey:)/title",
          "value": "shouldArchiveValueForKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1shouldArchiveValue(forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "shouldArchiveValueForKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1xAcceleration/title",
          "value": "xAcceleration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1xAcceleration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xAcceleration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1yAcceleration/title",
          "value": "yAcceleration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1yAcceleration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "yAcceleration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1greenRange/title",
          "value": "greenRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1greenRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "greenRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1greenSpeed/title",
          "value": "greenSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1greenSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "greenSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1spin/title",
          "value": "spin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1spin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "spin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1isEnabled/title",
          "value": "enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterCell~1isEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/caemittercell"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/caemittercell"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
