{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRangeIsEqualToRange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CAFrameRateRangeIsEqualToRange",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CAFrameRateRangeIsEqualToRange"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CAFrameRateRangeIsEqualToRange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CAFrameRateRangeIsEqualToRange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:b",
              "text": "bool"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CAFrameRateRangeIsEqualToRange"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CAFrameRateRange",
              "text": "CAFrameRateRange"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CAFrameRateRange",
              "text": "CAFrameRateRange"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "other"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAFrameRateRange"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAFrameRateRange"
        }
      ],
      "role": "symbol",
      "title": "CAFrameRateRange",
      "type": "topic",
      "url": "/documentation/quartzcore/caframeraterange"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRangeIsEqualToRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CAFrameRateRangeIsEqualToRange"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRangeIsEqualToRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "CAFrameRateRangeIsEqualToRange",
      "type": "topic",
      "url": "/documentation/quartzcore/caframeraterangeisequaltorange"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRangeMake": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CAFrameRateRangeMake"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRangeMake",
      "kind": "symbol",
      "role": "symbol",
      "title": "CAFrameRateRangeMake",
      "type": "topic",
      "url": "/documentation/quartzcore/caframeraterangemake"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRangeMake"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAFrameRateRange/title",
          "value": "CAFrameRateRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAFrameRateRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFrameRateRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAFrameRateRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAFrameRateRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/caframeraterangeisequaltorange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
