{
  "abstract": [
    {
      "text": "An object that provides keyframe animation capabilities for a layer object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CAKeyframeAnimation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CAKeyframeAnimation"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CAKeyframeAnimation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CAKeyframeAnimation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CAKeyframeAnimation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object using the inherited ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation/init(keyPath:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, specifying the key path of the property that you want to animate on the layer. You can then specify the keyframe values to use to control the timing and animation behavior.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For most types of animations, you specify the keyframe values using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/values",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/keyTimes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties. During the animation, Core Animation generates intermediate values by interpolating between the values you provide. When animating a value that is a coordinate point, such as the layer’s position, you can specify a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/path",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for that point to follow instead of individual values. The pacing of the animation is controlled by the timing information you provide.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows how to create a keyframe animation that animates a layer’s background color from red to green to blue over a two second duration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let colorKeyframeAnimation = CAKeyframeAnimation(keyPath: \"backgroundColor\")",
            "",
            "colorKeyframeAnimation.values = [UIColor.red.cgColor,",
            "                                 UIColor.green.cgColor,",
            "                                 UIColor.blue.cgColor]",
            "colorKeyframeAnimation.keyTimes = [0, 0.5, 1]",
            "colorKeyframeAnimation.duration = 2"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAction": {
      "abstract": [
        {
          "text": "An interface that allows instances to respond to actions triggered by a Core Animation layer change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAction"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAction"
        }
      ],
      "role": "symbol",
      "title": "CAAction",
      "type": "topic",
      "url": "/documentation/quartzcore/caaction"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimation": {
      "abstract": [
        {
          "text": "The abstract superclass for animations in Core Animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAnimation"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAnimation"
        }
      ],
      "role": "symbol",
      "title": "CAAnimation",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimation"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationDelegate": {
      "abstract": [
        {
          "text": "Methods your app can implement to respond when animations start and stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAnimationDelegate"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAnimationDelegate"
        }
      ],
      "role": "symbol",
      "title": "CAAnimationDelegate",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationdelegate"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation": {
      "abstract": [
        {
          "text": "An object that provides basic, single-keyframe animation capabilities for a layer property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CABasicAnimation"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CABasicAnimation"
        }
      ],
      "role": "symbol",
      "title": "CABasicAnimation",
      "type": "topic",
      "url": "/documentation/quartzcore/cabasicanimation"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation": {
      "abstract": [
        {
          "text": "An object that provides keyframe animation capabilities for a layer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAKeyframeAnimation"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAKeyframeAnimation"
        }
      ],
      "role": "symbol",
      "title": "CAKeyframeAnimation",
      "type": "topic",
      "url": "/documentation/quartzcore/cakeyframeanimation"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/biasValues": {
      "abstract": [
        {
          "text": "An array of numbers that define the position of the curve relative to a control point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biasValues"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/biasValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "biasValues"
        }
      ],
      "role": "symbol",
      "title": "biasValues",
      "type": "topic",
      "url": "/documentation/quartzcore/cakeyframeanimation/biasvalues"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/calculationMode": {
      "abstract": [
        {
          "text": "Specifies how intermediate keyframe values are calculated by the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calculationMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAAnimationCalculationMode",
          "text": "CAAnimationCalculationMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/calculationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "calculationMode"
        }
      ],
      "role": "symbol",
      "title": "calculationMode",
      "type": "topic",
      "url": "/documentation/quartzcore/cakeyframeanimation/calculationmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/continuityValues": {
      "abstract": [
        {
          "text": "An array of numbers that define the sharpness of the timing curve’s corners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuityValues"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/continuityValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "continuityValues"
        }
      ],
      "role": "symbol",
      "title": "continuityValues",
      "type": "topic",
      "url": "/documentation/quartzcore/cakeyframeanimation/continuityvalues"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/keyTimes": {
      "abstract": [
        {
          "text": "An optional array of ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " objects that define the time at which to apply a given keyframe segment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyTimes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/keyTimes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyTimes"
        }
      ],
      "role": "symbol",
      "title": "keyTimes",
      "type": "topic",
      "url": "/documentation/quartzcore/cakeyframeanimation/keytimes"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/path": {
      "abstract": [
        {
          "text": "The path for a point-based property to follow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "path"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGPathRef",
          "text": "CGPath"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/path",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "path"
        }
      ],
      "role": "symbol",
      "title": "path",
      "type": "topic",
      "url": "/documentation/quartzcore/cakeyframeanimation/path"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/rotationMode": {
      "abstract": [
        {
          "text": "Determines whether objects animating along the path rotate to match the path tangent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotationMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAAnimationRotationMode",
          "text": "CAAnimationRotationMode"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/rotationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotationMode"
        }
      ],
      "role": "symbol",
      "title": "rotationMode",
      "type": "topic",
      "url": "/documentation/quartzcore/cakeyframeanimation/rotationmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/tensionValues": {
      "abstract": [
        {
          "text": "An array of numbers that define the tightness of the curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tensionValues"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/tensionValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tensionValues"
        }
      ],
      "role": "symbol",
      "title": "tensionValues",
      "type": "topic",
      "url": "/documentation/quartzcore/cakeyframeanimation/tensionvalues"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/timingFunctions": {
      "abstract": [
        {
          "text": "An optional array of ",
          "type": "text"
        },
        {
          "code": "CAMediaTimingFunction",
          "type": "codeVoice"
        },
        {
          "text": " objects that define the pacing for each keyframe segment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timingFunctions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CAMediaTimingFunction",
          "text": "CAMediaTimingFunction"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/timingFunctions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timingFunctions"
        }
      ],
      "role": "symbol",
      "title": "timingFunctions",
      "type": "topic",
      "url": "/documentation/quartzcore/cakeyframeanimation/timingfunctions"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/values": {
      "abstract": [
        {
          "text": "An array of objects that specify the keyframe values to use for the animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "values"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/values",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "values"
        }
      ],
      "role": "symbol",
      "title": "values",
      "type": "topic",
      "url": "/documentation/quartzcore/cakeyframeanimation/values"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming": {
      "abstract": [
        {
          "text": "Methods that model a hierarchical timing system, allowing objects to map time between their parent and local time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMediaTiming"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMediaTiming"
        }
      ],
      "role": "symbol",
      "title": "CAMediaTiming",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatiming"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation": {
      "abstract": [
        {
          "text": "An abstract subclass for creating animations that manipulate the value of layer properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAPropertyAnimation"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAPropertyAnimation"
        }
      ],
      "role": "symbol",
      "title": "CAPropertyAnimation",
      "type": "topic",
      "url": "/documentation/quartzcore/capropertyanimation"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation/init(keyPath:)": {
      "abstract": [
        {
          "text": "Creates and returns an ",
          "type": "text"
        },
        {
          "code": "CAPropertyAnimation",
          "type": "codeVoice"
        },
        {
          "text": " instance for the specified key path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "keyPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation/init(keyPath:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "animationWithKeyPath:"
        }
      ],
      "role": "symbol",
      "title": "init(keyPath:)",
      "type": "topic",
      "url": "/documentation/quartzcore/capropertyanimation/init(keypath:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation": {
      "abstract": [
        {
          "text": "An animation that applies a spring-like force to a layer’s properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CASpringAnimation"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CASpringAnimation"
        }
      ],
      "role": "symbol",
      "title": "CASpringAnimation",
      "type": "topic",
      "url": "/documentation/quartzcore/caspringanimation"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition": {
      "abstract": [
        {
          "text": "An object that provides an animated transition between a layer’s states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransition"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransition"
        }
      ],
      "role": "symbol",
      "title": "CATransition",
      "type": "topic",
      "url": "/documentation/quartzcore/catransition"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction": {
      "abstract": [
        {
          "text": "An object that provides a flexible method of defining animated transformations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAValueFunction"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAValueFunction"
        }
      ],
      "role": "symbol",
      "title": "CAValueFunction",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunction"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/rotation-mode-values": {
      "abstract": [
        {
          "text": "These constants are used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/rotationMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/rotation-mode-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Rotation Mode Values",
      "type": "topic",
      "url": "/documentation/quartzcore/rotation-mode-values"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/value-calculation-modes": {
      "abstract": [
        {
          "text": "These constants are used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/calculationMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/value-calculation-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Value calculation modes",
      "type": "topic",
      "url": "/documentation/quartzcore/value-calculation-modes"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAction",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming",
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Animation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimation",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationDelegate",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction"
      ],
      "title": "Animation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Providing-keyframe-values",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/values",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/path"
      ],
      "title": "Providing keyframe values"
    },
    {
      "anchor": "Keyframe-timing",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/keyTimes",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/timingFunctions",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/calculationMode"
      ],
      "title": "Keyframe timing"
    },
    {
      "anchor": "Rotation-Mode-Attribute",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/rotationMode"
      ],
      "title": "Rotation Mode Attribute"
    },
    {
      "anchor": "Cubic-Mode-Attributes",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/tensionValues",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/continuityValues",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/biasValues"
      ],
      "title": "Cubic Mode Attributes"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/rotation-mode-values",
        "doc://com.apple.quartzcore/documentation/QuartzCore/value-calculation-modes"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CAKeyframeAnimation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAKeyframeAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAKeyframeAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Providing-keyframe-values",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/values",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/path"
              ],
              "title": "Providing keyframe values"
            },
            {
              "anchor": "Keyframe-timing",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/keyTimes",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/timingFunctions",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/calculationMode"
              ],
              "title": "Keyframe timing"
            },
            {
              "anchor": "Rotation-Mode-Attribute",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/rotationMode"
              ],
              "title": "Rotation Mode Attribute"
            },
            {
              "anchor": "Cubic-Mode-Attributes",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/tensionValues",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/continuityValues",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation/biasValues"
              ],
              "title": "Cubic Mode Attributes"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/rotation-mode-values",
                "doc://com.apple.quartzcore/documentation/QuartzCore/value-calculation-modes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Animation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimation",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationDelegate",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction"
              ],
              "title": "Animation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CAKeyframeAnimation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CAPropertyAnimation",
                    "text": "CAPropertyAnimation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation/title",
          "value": "CASpringAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CASpringAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CASpringAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CABasicAnimation/title",
          "value": "CABasicAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CABasicAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CABasicAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CABasicAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CABasicAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1keyTimes/title",
          "value": "keyTimes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1keyTimes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyTimes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimation/title",
          "value": "CAAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1path/title",
          "value": "path"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1path/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "path"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationDelegate/title",
          "value": "CAAnimationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation/title",
          "value": "CAKeyframeAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAKeyframeAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAKeyframeAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1biasValues/title",
          "value": "biasValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1biasValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "biasValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1continuityValues/title",
          "value": "continuityValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1continuityValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "continuityValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1calculationMode/title",
          "value": "calculationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1calculationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "calculationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAction/title",
          "value": "CAAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1tensionValues/title",
          "value": "tensionValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1tensionValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tensionValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1timingFunctions/title",
          "value": "timingFunctions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1timingFunctions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timingFunctions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation/title",
          "value": "CAPropertyAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAPropertyAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAPropertyAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/title",
          "value": "CAMediaTiming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTiming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTiming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1values/title",
          "value": "values"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1values/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunction/title",
          "value": "CAValueFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1rotationMode/title",
          "value": "rotationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation~1rotationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rotationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition/title",
          "value": "CATransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation~1init(keyPath:)/title",
          "value": "animationWithKeyPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation~1init(keyPath:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "animationWithKeyPath:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/cakeyframeanimation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/cakeyframeanimation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
