{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CALayerContentsFormat",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CALayerContentsFormat"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CALayerContentsFormat"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CALayerContentsFormat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CALayerContentsFormat"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAnimationCalculationMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAnimationCalculationMode"
        }
      ],
      "role": "symbol",
      "title": "CAAnimationCalculationMode",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationcalculationmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationRotationMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAnimationRotationMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationRotationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAnimationRotationMode"
        }
      ],
      "role": "symbol",
      "title": "CAAnimationRotationMode",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationrotationmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEmitterLayerEmitterMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEmitterLayerEmitterMode"
        }
      ],
      "role": "symbol",
      "title": "CAEmitterLayerEmitterMode",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayeremittermode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEmitterLayerEmitterShape"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEmitterLayerEmitterShape"
        }
      ],
      "role": "symbol",
      "title": "CAEmitterLayerEmitterShape",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayeremittershape"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerRenderMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEmitterLayerRenderMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerRenderMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEmitterLayerRenderMode"
        }
      ],
      "role": "symbol",
      "title": "CAEmitterLayerRenderMode",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayerrendermode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayerType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAGradientLayerType"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAGradientLayerType"
        }
      ],
      "role": "symbol",
      "title": "CAGradientLayerType",
      "type": "topic",
      "url": "/documentation/quartzcore/cagradientlayertype"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFilter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerContentsFilter"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayerContentsFilter"
        }
      ],
      "role": "symbol",
      "title": "CALayerContentsFilter",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsfilter"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerContentsFormat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayerContentsFormat"
        }
      ],
      "role": "symbol",
      "title": "CALayerContentsFormat",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsformat"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat/RGBA16Float": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RGBA16Float"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsFormat",
          "text": "CALayerContentsFormat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat/RGBA16Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAContentsFormatRGBA16Float"
        }
      ],
      "role": "symbol",
      "title": "RGBA16Float",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsformat/rgba16float"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat/RGBA8Uint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RGBA8Uint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsFormat",
          "text": "CALayerContentsFormat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat/RGBA8Uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAContentsFormatRGBA8Uint"
        }
      ],
      "role": "symbol",
      "title": "RGBA8Uint",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsformat/rgba8uint"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat/gray8Uint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gray8Uint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsFormat",
          "text": "CALayerContentsFormat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat/gray8Uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAContentsFormatGray8Uint"
        }
      ],
      "role": "symbol",
      "title": "gray8Uint",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsformat/gray8uint"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsformat/init(rawvalue:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayerContentsGravity"
        }
      ],
      "role": "symbol",
      "title": "CALayerContentsGravity",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerCornerCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerCornerCurve"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerCornerCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayerCornerCurve"
        }
      ],
      "role": "symbol",
      "title": "CALayerCornerCurve",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercornercurve"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMediaTimingFillMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMediaTimingFillMode"
        }
      ],
      "role": "symbol",
      "title": "CAMediaTimingFillMode",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatimingfillmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunctionName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMediaTimingFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunctionName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMediaTimingFunctionName"
        }
      ],
      "role": "symbol",
      "title": "CAMediaTimingFunctionName",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatimingfunctionname"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayerScrollMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAScrollLayerScrollMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayerScrollMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAScrollLayerScrollMode"
        }
      ],
      "role": "symbol",
      "title": "CAScrollLayerScrollMode",
      "type": "topic",
      "url": "/documentation/quartzcore/cascrolllayerscrollmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerFillRule": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAShapeLayerFillRule"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerFillRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAShapeLayerFillRule"
        }
      ],
      "role": "symbol",
      "title": "CAShapeLayerFillRule",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayerfillrule"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAShapeLayerLineCap"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAShapeLayerLineCap"
        }
      ],
      "role": "symbol",
      "title": "CAShapeLayerLineCap",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayerlinecap"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineJoin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAShapeLayerLineJoin"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineJoin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAShapeLayerLineJoin"
        }
      ],
      "role": "symbol",
      "title": "CAShapeLayerLineJoin",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayerlinejoin"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationRotationMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerRenderMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayerType",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFilter",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerCornerCurve",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunctionName",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayerScrollMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerFillRule",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineJoin"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat/RGBA16Float",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat/RGBA8Uint",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat/gray8Uint"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CALayerContentsFormat"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat/RGBA16Float",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat/RGBA8Uint",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat/gray8Uint"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationRotationMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerRenderMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayerType",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFilter",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerCornerCurve",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunctionName",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayerScrollMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerFillRule",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineJoin"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "CALayerContentsFormat"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAGradientLayerType/title",
          "value": "CAGradientLayerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAGradientLayerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAGradientLayerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAGradientLayerType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAGradientLayerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterMode/title",
          "value": "CAEmitterLayerEmitterMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerEmitterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerEmitterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerCornerCurve/title",
          "value": "CALayerCornerCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerCornerCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerCornerCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerCornerCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerCornerCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape/title",
          "value": "CAEmitterLayerEmitterShape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerEmitterShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerEmitterShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode/title",
          "value": "CAAnimationCalculationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationCalculationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationCalculationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFormat/title",
          "value": "CALayerContentsFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerFillRule/title",
          "value": "CAShapeLayerFillRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerFillRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerFillRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerFillRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerFillRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineJoin/title",
          "value": "CAShapeLayerLineJoin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineJoin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerLineJoin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineJoin/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerLineJoin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode/title",
          "value": "CAMediaTimingFillMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTimingFillMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTimingFillMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFilter/title",
          "value": "CALayerContentsFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFunctionName/title",
          "value": "CAMediaTimingFunctionName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFunctionName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTimingFunctionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFunctionName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTimingFunctionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFormat~1RGBA16Float/title",
          "value": "kCAContentsFormatRGBA16Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFormat~1RGBA16Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAContentsFormatRGBA16Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFormat~1gray8Uint/title",
          "value": "kCAContentsFormatGray8Uint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFormat~1gray8Uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAContentsFormatGray8Uint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerRenderMode/title",
          "value": "CAEmitterLayerRenderMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerRenderMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerRenderMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerRenderMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerRenderMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineCap/title",
          "value": "CAShapeLayerLineCap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineCap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerLineCap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineCap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerLineCap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAScrollLayerScrollMode/title",
          "value": "CAScrollLayerScrollMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAScrollLayerScrollMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAScrollLayerScrollMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAScrollLayerScrollMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAScrollLayerScrollMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationRotationMode/title",
          "value": "CAAnimationRotationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationRotationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationRotationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationRotationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationRotationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity/title",
          "value": "CALayerContentsGravity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFormat~1RGBA8Uint/title",
          "value": "kCAContentsFormatRGBA8Uint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFormat~1RGBA8Uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAContentsFormatRGBA8Uint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/calayercontentsformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/calayercontentsformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
