{
  "abstract": [
    {
      "text": "A Metal drawable associated with a Core Animation layer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDrawable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CAMetalDrawable",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CAMetalDrawable"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CAMetalDrawable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CAMetalDrawable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CAMetalDrawable"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLDrawable",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLDrawable",
              "text": "MTLDrawable"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalLayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance owns any instance that implements this protocol. Don’t implement this protocol yourself. See the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalLayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " reference for information on how to request drawable objects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEAGLLayer": {
      "abstract": [
        {
          "text": "A layer that supports drawing OpenGL content in iOS and tvOS applications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEAGLLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEAGLLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEAGLLayer"
        }
      ],
      "role": "symbol",
      "title": "CAEAGLLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/caeagllayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEDRMetadata": {
      "abstract": [
        {
          "text": "Metadata describing how extended dynamic range (EDR) values should be tone mapped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEDRMetadata"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEDRMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEDRMetadata"
        }
      ],
      "role": "symbol",
      "title": "CAEDRMetadata",
      "type": "topic",
      "url": "/documentation/quartzcore/caedrmetadata"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDrawable": {
      "abstract": [
        {
          "text": "A Metal drawable associated with a Core Animation layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMetalDrawable"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDrawable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMetalDrawable"
        }
      ],
      "role": "symbol",
      "title": "CAMetalDrawable",
      "type": "topic",
      "url": "/documentation/quartzcore/cametaldrawable"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDrawable/layer": {
      "abstract": [
        {
          "text": "The layer that owns this drawable object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CAMetalLayer",
          "text": "CAMetalLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDrawable/layer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layer"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "layer",
      "type": "topic",
      "url": "/documentation/quartzcore/cametaldrawable/layer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDrawable/texture": {
      "abstract": [
        {
          "text": "A Metal texture object that contains the drawable’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texture"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDrawable/texture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "texture"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "texture",
      "type": "topic",
      "url": "/documentation/quartzcore/cametaldrawable/texture"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalLayer": {
      "abstract": [
        {
          "text": "A Core Animation layer that Metal can render into, typically displayed onscreen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMetalLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMetalLayer"
        }
      ],
      "role": "symbol",
      "title": "CAMetalLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/cametallayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAOpenGLLayer": {
      "abstract": [
        {
          "text": "A layer that provides a layer suitable for rendering OpenGL content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAOpenGLLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAOpenGLLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAOpenGLLayer"
        }
      ],
      "role": "symbol",
      "title": "CAOpenGLLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/caopengllayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CARenderer": {
      "abstract": [
        {
          "text": "A layer that allows an application to render a layer tree into a Core OpenGL context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CARenderer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CARenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CARenderer"
        }
      ],
      "role": "symbol",
      "title": "CARenderer",
      "type": "topic",
      "url": "/documentation/quartzcore/carenderer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)MTLDrawable": {
      "abstract": [
        {
          "text": "A displayable resource that can be rendered or written to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDrawable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLDrawable",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLDrawable",
      "type": "topic",
      "url": "/documentation/Metal/MTLDrawable"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)MTLDrawable",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metal-and-OpenGL",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalLayer",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEAGLLayer",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEDRMetadata",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAOpenGLLayer",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CARenderer"
      ],
      "title": "Metal and OpenGL"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Drawables-Texture",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDrawable/texture"
      ],
      "title": "Getting the Drawable’s Texture"
    },
    {
      "anchor": "Getting-the-Owning-Layer",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDrawable/layer"
      ],
      "title": "Getting the Owning Layer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CAMetalDrawable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-Drawables-Texture",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDrawable/texture"
              ],
              "title": "Getting the Drawable’s Texture"
            },
            {
              "anchor": "Getting-the-Owning-Layer",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalDrawable/layer"
              ],
              "title": "Getting the Owning Layer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)MTLDrawable"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Metal-and-OpenGL",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMetalLayer",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEAGLLayer",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEDRMetadata",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAOpenGLLayer",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CARenderer"
              ],
              "title": "Metal and OpenGL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CAMetalDrawable"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLDrawable",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)MTLDrawable",
                    "text": "MTLDrawable"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalLayer/title",
          "value": "CAMetalLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CARenderer/title",
          "value": "CARenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CARenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CARenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CARenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CARenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)MTLDrawable/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLDrawable"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEDRMetadata/title",
          "value": "CAEDRMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEDRMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEDRMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEDRMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEDRMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEAGLLayer/title",
          "value": "CAEAGLLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEAGLLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEAGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEAGLLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEAGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDrawable/title",
          "value": "CAMetalDrawable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDrawable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDrawable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMetalDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDrawable~1texture/title",
          "value": "texture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDrawable~1texture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "texture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAOpenGLLayer/title",
          "value": "CAOpenGLLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAOpenGLLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAOpenGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAOpenGLLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAOpenGLLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDrawable~1layer/title",
          "value": "layer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMetalDrawable~1layer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/cametaldrawable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/cametaldrawable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
