{
  "abstract": [
    {
      "text": "An animation that applies a spring-like force to a layer’s properties.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CASpringAnimation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CASpringAnimation"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CASpringAnimation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CASpringAnimation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CASpringAnimation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You would typically use a spring animation to animate a layer’s position so that it appears to be pulled towards a target by a spring. The further the layer is from the target, the greater the acceleration towards it is.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " allows control over physically based attributes such as the spring’s damping and stiffness.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can use a spring animation to animation properties of a layer other than its position. The following code shows how to create a spring animation that bounces a layer into view by animating its scale from ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": ". Because the spring animation can overshoot its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation/toValue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the animated layer may exceed its frame.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let springAnimation = CASpringAnimation(keyPath: \"transform.scale\")",
            "",
            "springAnimation.fromValue = 0",
            "springAnimation.toValue = 1"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAction": {
      "abstract": [
        {
          "text": "An interface that allows instances to respond to actions triggered by a Core Animation layer change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAction"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAction"
        }
      ],
      "role": "symbol",
      "title": "CAAction",
      "type": "topic",
      "url": "/documentation/quartzcore/caaction"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimation": {
      "abstract": [
        {
          "text": "The abstract superclass for animations in Core Animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAnimation"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAnimation"
        }
      ],
      "role": "symbol",
      "title": "CAAnimation",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimation"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationDelegate": {
      "abstract": [
        {
          "text": "Methods your app can implement to respond when animations start and stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAnimationDelegate"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAnimationDelegate"
        }
      ],
      "role": "symbol",
      "title": "CAAnimationDelegate",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationdelegate"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation": {
      "abstract": [
        {
          "text": "An object that provides basic, single-keyframe animation capabilities for a layer property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CABasicAnimation"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CABasicAnimation"
        }
      ],
      "role": "symbol",
      "title": "CABasicAnimation",
      "type": "topic",
      "url": "/documentation/quartzcore/cabasicanimation"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation/toValue": {
      "abstract": [
        {
          "text": "Defines the value the receiver uses to end interpolation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation/toValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toValue"
        }
      ],
      "role": "symbol",
      "title": "toValue",
      "type": "topic",
      "url": "/documentation/quartzcore/cabasicanimation/tovalue"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation": {
      "abstract": [
        {
          "text": "An object that provides keyframe animation capabilities for a layer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAKeyframeAnimation"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAKeyframeAnimation"
        }
      ],
      "role": "symbol",
      "title": "CAKeyframeAnimation",
      "type": "topic",
      "url": "/documentation/quartzcore/cakeyframeanimation"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming": {
      "abstract": [
        {
          "text": "Methods that model a hierarchical timing system, allowing objects to map time between their parent and local time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMediaTiming"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMediaTiming"
        }
      ],
      "role": "symbol",
      "title": "CAMediaTiming",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatiming"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation": {
      "abstract": [
        {
          "text": "An abstract subclass for creating animations that manipulate the value of layer properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAPropertyAnimation"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAPropertyAnimation"
        }
      ],
      "role": "symbol",
      "title": "CAPropertyAnimation",
      "type": "topic",
      "url": "/documentation/quartzcore/capropertyanimation"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation": {
      "abstract": [
        {
          "text": "An animation that applies a spring-like force to a layer’s properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CASpringAnimation"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CASpringAnimation"
        }
      ],
      "role": "symbol",
      "title": "CASpringAnimation",
      "type": "topic",
      "url": "/documentation/quartzcore/caspringanimation"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/allowsOverdamping": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsOverdamping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/allowsOverdamping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsOverdamping"
        }
      ],
      "role": "symbol",
      "title": "allowsOverdamping",
      "type": "topic",
      "url": "/documentation/quartzcore/caspringanimation/allowsoverdamping"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/bounce": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bounce"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/bounce",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bounce"
        }
      ],
      "role": "symbol",
      "title": "bounce",
      "type": "topic",
      "url": "/documentation/quartzcore/caspringanimation/bounce"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/damping": {
      "abstract": [
        {
          "text": "Defines how the spring’s motion should be damped due to the forces of friction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "damping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/damping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "damping"
        }
      ],
      "role": "symbol",
      "title": "damping",
      "type": "topic",
      "url": "/documentation/quartzcore/caspringanimation/damping"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/init(perceptualDuration:bounce:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "perceptualDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTimeInterval",
          "text": "CFTimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bounce"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/init(perceptualDuration:bounce:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPerceptualDuration:bounce:"
        }
      ],
      "role": "symbol",
      "title": "init(perceptualDuration:bounce:)",
      "type": "topic",
      "url": "/documentation/quartzcore/caspringanimation/init(perceptualduration:bounce:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/initialVelocity": {
      "abstract": [
        {
          "text": "The initial velocity of the object attached to the spring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initialVelocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/initialVelocity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initialVelocity"
        }
      ],
      "role": "symbol",
      "title": "initialVelocity",
      "type": "topic",
      "url": "/documentation/quartzcore/caspringanimation/initialvelocity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/mass": {
      "abstract": [
        {
          "text": "The mass of the object attached to the end of the spring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/mass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mass"
        }
      ],
      "role": "symbol",
      "title": "mass",
      "type": "topic",
      "url": "/documentation/quartzcore/caspringanimation/mass"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/perceptualDuration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perceptualDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTimeInterval",
          "text": "CFTimeInterval"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/perceptualDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "perceptualDuration"
        }
      ],
      "role": "symbol",
      "title": "perceptualDuration",
      "type": "topic",
      "url": "/documentation/quartzcore/caspringanimation/perceptualduration"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/settlingDuration": {
      "abstract": [
        {
          "text": "The estimated duration required for the spring system to be considered at rest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "settlingDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTimeInterval",
          "text": "CFTimeInterval"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/settlingDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "settlingDuration"
        }
      ],
      "role": "symbol",
      "title": "settlingDuration",
      "type": "topic",
      "url": "/documentation/quartzcore/caspringanimation/settlingduration"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/stiffness": {
      "abstract": [
        {
          "text": "The spring stiffness coefficient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stiffness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/stiffness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stiffness"
        }
      ],
      "role": "symbol",
      "title": "stiffness",
      "type": "topic",
      "url": "/documentation/quartzcore/caspringanimation/stiffness"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition": {
      "abstract": [
        {
          "text": "An object that provides an animated transition between a layer’s states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransition"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransition"
        }
      ],
      "role": "symbol",
      "title": "CATransition",
      "type": "topic",
      "url": "/documentation/quartzcore/catransition"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction": {
      "abstract": [
        {
          "text": "An object that provides a flexible method of defining animated transformations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAValueFunction"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAValueFunction"
        }
      ],
      "role": "symbol",
      "title": "CAValueFunction",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunction"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAction",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming",
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Animation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimation",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationDelegate",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction"
      ],
      "title": "Animation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-Physical-Attributes",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/damping",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/initialVelocity",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/mass",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/settlingDuration",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/stiffness"
      ],
      "title": "Configuring Physical Attributes"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/init(perceptualDuration:bounce:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/allowsOverdamping",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/bounce",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/perceptualDuration"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CASpringAnimation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CASpringAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CASpringAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-Physical-Attributes",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/damping",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/initialVelocity",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/mass",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/settlingDuration",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/stiffness"
              ],
              "title": "Configuring Physical Attributes"
            },
            {
              "anchor": "Initializers",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/init(perceptualDuration:bounce:)"
              ],
              "title": "Initializers"
            },
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/allowsOverdamping",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/bounce",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CASpringAnimation/perceptualDuration"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Animation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimation",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationDelegate",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAPropertyAnimation",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAKeyframeAnimation",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction"
              ],
              "title": "Animation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CASpringAnimation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CABasicAnimation",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CABasicAnimation",
                    "text": "CABasicAnimation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1settlingDuration/title",
          "value": "settlingDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1settlingDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "settlingDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1init(perceptualDuration:bounce:)/title",
          "value": "initWithPerceptualDuration:bounce:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1init(perceptualDuration:bounce:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPerceptualDuration:bounce:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1mass/title",
          "value": "mass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1mass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition/title",
          "value": "CATransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation/title",
          "value": "CASpringAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CASpringAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CASpringAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationDelegate/title",
          "value": "CAAnimationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CABasicAnimation/title",
          "value": "CABasicAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CABasicAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CABasicAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CABasicAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CABasicAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1stiffness/title",
          "value": "stiffness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1stiffness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stiffness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1allowsOverdamping/title",
          "value": "allowsOverdamping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1allowsOverdamping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsOverdamping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAction/title",
          "value": "CAAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1damping/title",
          "value": "damping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1damping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "damping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1perceptualDuration/title",
          "value": "perceptualDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1perceptualDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "perceptualDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1initialVelocity/title",
          "value": "initialVelocity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1initialVelocity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "initialVelocity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CABasicAnimation~1toValue/title",
          "value": "toValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CABasicAnimation~1toValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunction/title",
          "value": "CAValueFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation/title",
          "value": "CAKeyframeAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAKeyframeAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAKeyframeAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAKeyframeAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation/title",
          "value": "CAPropertyAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAPropertyAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAPropertyAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAPropertyAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1bounce/title",
          "value": "bounce"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CASpringAnimation~1bounce/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bounce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimation/title",
          "value": "CAAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/title",
          "value": "CAMediaTiming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTiming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTiming"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/caspringanimation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/caspringanimation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
