{
  "abstract": [
    {
      "text": "Inverts ",
      "type": "text"
    },
    {
      "code": "t",
      "type": "codeVoice"
    },
    {
      "text": " and returns the result.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DInvert(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CATransform3DInvert",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CATransform3DInvert"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CATransform3D",
        "text": "CATransform3D"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CATransform3D",
        "text": "CATransform3D"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CATransform3DInvert"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CATransform3DInvert(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CATransform3DInvert"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "t"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3D",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CATransform3D",
              "text": "CATransform3D"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3D",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CATransform3D",
              "text": "CATransform3D"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns the original matrix if ",
              "type": "text"
            },
            {
              "code": "t",
              "type": "codeVoice"
            },
            {
              "text": " has no inverse.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3D": {
      "abstract": [
        {
          "text": "The standard transform matrix used throughout Core Animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3D"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3D"
        }
      ],
      "role": "symbol",
      "title": "CATransform3D",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3d"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DInvert(_:)": {
      "abstract": [
        {
          "text": "Inverts ",
          "type": "text"
        },
        {
          "code": "t",
          "type": "codeVoice"
        },
        {
          "text": " and returns the result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3DInvert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DInvert(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3DInvert"
        }
      ],
      "role": "symbol",
      "title": "CATransform3DInvert(_:)",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3dinvert(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CATransform3DInvert"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DInvert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3D",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CATransform3D",
                    "text": "CATransform3D"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CATransform3DInvert"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3D",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CATransform3D",
                    "text": "CATransform3D"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "t"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DInvert(_:)/title",
          "value": "CATransform3DInvert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DInvert(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DInvert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3D/title",
          "value": "CATransform3D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3D"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/catransform3dinvert(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/catransform3dinvert(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
