{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CAValueFunctionName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CAValueFunctionName"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CAValueFunctionName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CAValueFunctionName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CAValueFunctionName"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAnimationCalculationMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAnimationCalculationMode"
        }
      ],
      "role": "symbol",
      "title": "CAAnimationCalculationMode",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationcalculationmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationRotationMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAnimationRotationMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationRotationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAnimationRotationMode"
        }
      ],
      "role": "symbol",
      "title": "CAAnimationRotationMode",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationrotationmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEmitterLayerEmitterMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEmitterLayerEmitterMode"
        }
      ],
      "role": "symbol",
      "title": "CAEmitterLayerEmitterMode",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayeremittermode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEmitterLayerEmitterShape"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEmitterLayerEmitterShape"
        }
      ],
      "role": "symbol",
      "title": "CAEmitterLayerEmitterShape",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayeremittershape"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerRenderMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEmitterLayerRenderMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerRenderMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEmitterLayerRenderMode"
        }
      ],
      "role": "symbol",
      "title": "CAEmitterLayerRenderMode",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayerrendermode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayerType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAGradientLayerType"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAGradientLayerType"
        }
      ],
      "role": "symbol",
      "title": "CAGradientLayerType",
      "type": "topic",
      "url": "/documentation/quartzcore/cagradientlayertype"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFilter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerContentsFilter"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayerContentsFilter"
        }
      ],
      "role": "symbol",
      "title": "CALayerContentsFilter",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsfilter"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerContentsFormat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayerContentsFormat"
        }
      ],
      "role": "symbol",
      "title": "CALayerContentsFormat",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsformat"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayerContentsGravity"
        }
      ],
      "role": "symbol",
      "title": "CALayerContentsGravity",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerCornerCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerCornerCurve"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerCornerCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayerCornerCurve"
        }
      ],
      "role": "symbol",
      "title": "CALayerCornerCurve",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercornercurve"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMediaTimingFillMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMediaTimingFillMode"
        }
      ],
      "role": "symbol",
      "title": "CAMediaTimingFillMode",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatimingfillmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunctionName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMediaTimingFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunctionName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMediaTimingFunctionName"
        }
      ],
      "role": "symbol",
      "title": "CAMediaTimingFunctionName",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatimingfunctionname"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayerScrollMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAScrollLayerScrollMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayerScrollMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAScrollLayerScrollMode"
        }
      ],
      "role": "symbol",
      "title": "CAScrollLayerScrollMode",
      "type": "topic",
      "url": "/documentation/quartzcore/cascrolllayerscrollmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerFillRule": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAShapeLayerFillRule"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerFillRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAShapeLayerFillRule"
        }
      ],
      "role": "symbol",
      "title": "CAShapeLayerFillRule",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayerfillrule"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAShapeLayerLineCap"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAShapeLayerLineCap"
        }
      ],
      "role": "symbol",
      "title": "CAShapeLayerLineCap",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayerlinecap"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAValueFunctionName"
        }
      ],
      "role": "symbol",
      "title": "CAValueFunctionName",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/init(rawvalue:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/rotateX": {
      "abstract": [
        {
          "text": "A value function that rotates by the input value, in radians, around the x-axis. This value function expects a single input value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotateX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/rotateX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionRotateX"
        }
      ],
      "role": "symbol",
      "title": "rotateX",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/rotatex"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/rotateY": {
      "abstract": [
        {
          "text": "A value function that rotates by the input value, in radians, around the y-axis. This value function expects a single input value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotateY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/rotateY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionRotateY"
        }
      ],
      "role": "symbol",
      "title": "rotateY",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/rotatey"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/rotateZ": {
      "abstract": [
        {
          "text": "A value function that rotates by the input value, in radians, around the z-axis. This value function expects a single input value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotateZ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/rotateZ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionRotateZ"
        }
      ],
      "role": "symbol",
      "title": "rotateZ",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/rotatez"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scale": {
      "abstract": [
        {
          "text": "A value function scales by the input value along all three axis. Animations using this value transform function must provide animation values in an ",
          "type": "text"
        },
        {
          "code": "NSArray",
          "type": "codeVoice"
        },
        {
          "text": " of three ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " instances that specify the (x, y, z) scale values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionScale"
        }
      ],
      "role": "symbol",
      "title": "scale",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/scale"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleX": {
      "abstract": [
        {
          "text": "A value function scales by the input value along the x-axis. Animations referencing this value transform function must provide a single animation value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionScaleX"
        }
      ],
      "role": "symbol",
      "title": "scaleX",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/scalex"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleY": {
      "abstract": [
        {
          "text": "A value function scales by the input value along the y-axis. Animations referencing this value function must provide a single animation value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionScaleY"
        }
      ],
      "role": "symbol",
      "title": "scaleY",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/scaley"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleZ": {
      "abstract": [
        {
          "text": "A value function that scales by the input value along the z-axis. Animations referencing this value function must provide a single animation value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleZ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleZ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionScaleZ"
        }
      ],
      "role": "symbol",
      "title": "scaleZ",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/scalez"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translate": {
      "abstract": [
        {
          "text": "A value function that translates by the input values along all three axis. Animations using this value transform function must provide animation values in an ",
          "type": "text"
        },
        {
          "code": "NSArray",
          "type": "codeVoice"
        },
        {
          "text": " of three ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " instances that specify the (x, y, z) translate values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "translate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionTranslate"
        }
      ],
      "role": "symbol",
      "title": "translate",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/translate"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateX": {
      "abstract": [
        {
          "text": "A value function translates by the input value along the x-axis. Animations referencing this value function must provide a single input value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "translateX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionTranslateX"
        }
      ],
      "role": "symbol",
      "title": "translateX",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/translatex"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateY": {
      "abstract": [
        {
          "text": "A value function translates by the input value along the y-axis. Animations referencing this value function must provide a single input value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "translateY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionTranslateY"
        }
      ],
      "role": "symbol",
      "title": "translateY",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/translatey"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateZ": {
      "abstract": [
        {
          "text": "A value function translates by the input value along the z-axis. Animations referencing this value function must provide a single input value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "translateZ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateZ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionTranslateZ"
        }
      ],
      "role": "symbol",
      "title": "translateZ",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/translatez"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationRotationMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerRenderMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayerType",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFilter",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerCornerCurve",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunctionName",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayerScrollMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerFillRule",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/rotateX",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/rotateY",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/rotateZ",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scale",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleX",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleY",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleZ",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translate",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateX",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateY",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateZ"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CAValueFunctionName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunctionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunctionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/rotateX",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/rotateY",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/rotateZ",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scale",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleX",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleY",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleZ",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translate",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateX",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateY",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateZ"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationRotationMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerRenderMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayerType",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFilter",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerCornerCurve",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunctionName",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayerScrollMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerFillRule",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "CAValueFunctionName"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scale/title",
          "value": "kCAValueFunctionScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerFillRule/title",
          "value": "CAShapeLayerFillRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerFillRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerFillRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerFillRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerFillRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode/title",
          "value": "CAAnimationCalculationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationCalculationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationCalculationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translateY/title",
          "value": "kCAValueFunctionTranslateY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translateY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionTranslateY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translateZ/title",
          "value": "kCAValueFunctionTranslateZ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translateZ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionTranslateZ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName/title",
          "value": "CAValueFunctionName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunctionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunctionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translateX/title",
          "value": "kCAValueFunctionTranslateX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translateX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionTranslateX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1rotateZ/title",
          "value": "kCAValueFunctionRotateZ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1rotateZ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionRotateZ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAScrollLayerScrollMode/title",
          "value": "CAScrollLayerScrollMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAScrollLayerScrollMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAScrollLayerScrollMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAScrollLayerScrollMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAScrollLayerScrollMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode/title",
          "value": "CAMediaTimingFillMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTimingFillMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTimingFillMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translate/title",
          "value": "kCAValueFunctionTranslate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionTranslate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFormat/title",
          "value": "CALayerContentsFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFunctionName/title",
          "value": "CAMediaTimingFunctionName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFunctionName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTimingFunctionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFunctionName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTimingFunctionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationRotationMode/title",
          "value": "CAAnimationRotationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationRotationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationRotationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationRotationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationRotationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape/title",
          "value": "CAEmitterLayerEmitterShape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerEmitterShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerEmitterShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1rotateX/title",
          "value": "kCAValueFunctionRotateX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1rotateX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionRotateX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerCornerCurve/title",
          "value": "CALayerCornerCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerCornerCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerCornerCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerCornerCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerCornerCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scaleX/title",
          "value": "kCAValueFunctionScaleX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scaleX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionScaleX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scaleZ/title",
          "value": "kCAValueFunctionScaleZ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scaleZ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionScaleZ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity/title",
          "value": "CALayerContentsGravity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scaleY/title",
          "value": "kCAValueFunctionScaleY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scaleY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionScaleY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerRenderMode/title",
          "value": "CAEmitterLayerRenderMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerRenderMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerRenderMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerRenderMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerRenderMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFilter/title",
          "value": "CALayerContentsFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1rotateY/title",
          "value": "kCAValueFunctionRotateY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1rotateY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionRotateY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterMode/title",
          "value": "CAEmitterLayerEmitterMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerEmitterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerEmitterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAGradientLayerType/title",
          "value": "CAGradientLayerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAGradientLayerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAGradientLayerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAGradientLayerType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAGradientLayerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineCap/title",
          "value": "CAShapeLayerLineCap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineCap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerLineCap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineCap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerLineCap"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/cavaluefunctionname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/cavaluefunctionname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
