{
  "abstract": [
    {
      "text": "These constants specify the transition types that can be used with the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition/type",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/common-transition-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Common Transition Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition": {
      "abstract": [
        {
          "text": "An object that provides an animated transition between a layer’s states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransition"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransition"
        }
      ],
      "role": "symbol",
      "title": "CATransition",
      "type": "topic",
      "url": "/documentation/quartzcore/catransition"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition/subtype": {
      "abstract": [
        {
          "text": "Specifies an optional subtype that indicates the direction for the predefined motion-based transitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CATransitionSubtype",
          "text": "CATransitionSubtype"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition/subtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subtype"
        }
      ],
      "role": "symbol",
      "title": "subtype",
      "type": "topic",
      "url": "/documentation/quartzcore/catransition/subtype"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition/type": {
      "abstract": [
        {
          "text": "Specifies the predefined transition type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CATransitionType",
          "text": "CATransitionType"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/quartzcore/catransition/type"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/fade": {
      "abstract": [
        {
          "text": "The layer’s content fades as it becomes visible or hidden.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fade"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CATransitionType",
          "text": "CATransitionType"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/fade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCATransitionFade"
        }
      ],
      "role": "symbol",
      "title": "fade",
      "type": "topic",
      "url": "/documentation/quartzcore/catransitiontype/fade"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/moveIn": {
      "abstract": [
        {
          "text": "The layer’s content slides into place over any existing content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CATransitionType",
          "text": "CATransitionType"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/moveIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCATransitionMoveIn"
        }
      ],
      "role": "symbol",
      "title": "moveIn",
      "type": "topic",
      "url": "/documentation/quartzcore/catransitiontype/movein"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/push": {
      "abstract": [
        {
          "text": "The layer’s content pushes any existing content as it slides into place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "push"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CATransitionType",
          "text": "CATransitionType"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/push",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCATransitionPush"
        }
      ],
      "role": "symbol",
      "title": "push",
      "type": "topic",
      "url": "/documentation/quartzcore/catransitiontype/push"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/reveal": {
      "abstract": [
        {
          "text": "The layer’s content is revealed gradually in the direction specified by the transition subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reveal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CATransitionType",
          "text": "CATransitionType"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/reveal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCATransitionReveal"
        }
      ],
      "role": "symbol",
      "title": "reveal",
      "type": "topic",
      "url": "/documentation/quartzcore/catransitiontype/reveal"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/common-transition-subtypes": {
      "abstract": [
        {
          "text": "These constants specify the direction of motion-based transitions. They are used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition/subtype",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/common-transition-subtypes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Common Transition Subtypes",
      "type": "topic",
      "url": "/documentation/quartzcore/common-transition-subtypes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/common-transition-subtypes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/fade",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/moveIn",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/push",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/reveal"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/fade",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/moveIn",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/push",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType/reveal"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/common-transition-subtypes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition/title",
          "value": "CATransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransitionType~1push/title",
          "value": "kCATransitionPush"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransitionType~1push/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCATransitionPush"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransitionType~1moveIn/title",
          "value": "kCATransitionMoveIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransitionType~1moveIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCATransitionMoveIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition~1subtype/title",
          "value": "subtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition~1subtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransitionType~1fade/title",
          "value": "kCATransitionFade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransitionType~1fade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCATransitionFade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransitionType~1reveal/title",
          "value": "kCATransitionReveal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransitionType~1reveal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCATransitionReveal"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/common-transition-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/common-transition-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
