{
  "abstract": [
    {
      "text": "The contents gravity constants specify the position of the content object when the layer bounds is larger than the bounds of the content object. They are used by the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsGravity",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/contents-gravity-values"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Contents Gravity Values"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CACornerMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CACornerMask"
        }
      ],
      "role": "symbol",
      "title": "CACornerMask",
      "type": "topic",
      "url": "/documentation/quartzcore/cacornermask"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer": {
      "abstract": [
        {
          "text": "An object that manages image-based content and allows you to perform animations on that content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayer"
        }
      ],
      "role": "symbol",
      "title": "CALayer",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundColor": {
      "abstract": [
        {
          "text": "The background color of the receiver. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundColor"
        }
      ],
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/backgroundcolor"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderColor": {
      "abstract": [
        {
          "text": "The color of the layer’s border. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderColor"
        }
      ],
      "role": "symbol",
      "title": "borderColor",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/bordercolor"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderWidth": {
      "abstract": [
        {
          "text": "The width of the layer’s border. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderWidth"
        }
      ],
      "role": "symbol",
      "title": "borderWidth",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/borderwidth"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsGravity": {
      "abstract": [
        {
          "text": "A constant that specifies how the layer’s contents are positioned or scaled within its bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentsGravity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsGravity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentsGravity"
        }
      ],
      "role": "symbol",
      "title": "contentsGravity",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/contentsgravity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/cornerRadius": {
      "abstract": [
        {
          "text": "The radius to use when drawing rounded corners for the layer’s background. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cornerRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/cornerRadius",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cornerRadius"
        }
      ],
      "role": "symbol",
      "title": "cornerRadius",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/cornerradius"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isDoubleSided": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the layer displays its content when facing away from the viewer. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDoubleSided"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isDoubleSided",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doubleSided"
        }
      ],
      "role": "symbol",
      "title": "isDoubleSided",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/isdoublesided"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isHidden": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the layer is displayed. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hidden"
        }
      ],
      "role": "symbol",
      "title": "isHidden",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/ishidden"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/mask": {
      "abstract": [
        {
          "text": "An optional layer whose alpha channel is used to mask the layer’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CALayer",
          "text": "CALayer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/mask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mask"
        }
      ],
      "role": "symbol",
      "title": "mask",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/mask"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/maskedCorners": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maskedCorners"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CACornerMask",
          "text": "CACornerMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/maskedCorners",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maskedCorners"
        }
      ],
      "role": "symbol",
      "title": "maskedCorners",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/maskedcorners"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/masksToBounds": {
      "abstract": [
        {
          "text": "A Boolean indicating whether sublayers are clipped to the layer’s bounds. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "masksToBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/masksToBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "masksToBounds"
        }
      ],
      "role": "symbol",
      "title": "masksToBounds",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/maskstobounds"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/opacity": {
      "abstract": [
        {
          "text": "The opacity of the receiver. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/opacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "opacity"
        }
      ],
      "role": "symbol",
      "title": "opacity",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/opacity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOffset": {
      "abstract": [
        {
          "text": "The offset (in points) of the layer’s shadow. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadowOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shadowOffset"
        }
      ],
      "role": "symbol",
      "title": "shadowOffset",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/shadowoffset"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOpacity": {
      "abstract": [
        {
          "text": "The opacity of the layer’s shadow. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadowOpacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOpacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shadowOpacity"
        }
      ],
      "role": "symbol",
      "title": "shadowOpacity",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/shadowopacity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowRadius": {
      "abstract": [
        {
          "text": "The blur radius (in points) used to render the layer’s shadow. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadowRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowRadius",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shadowRadius"
        }
      ],
      "role": "symbol",
      "title": "shadowRadius",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/shadowradius"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottom": {
      "abstract": [
        {
          "text": "The content is horizontally centered at the bottom-edge of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityBottom"
        }
      ],
      "role": "symbol",
      "title": "bottom",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/bottom"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomLeft": {
      "abstract": [
        {
          "text": "The content is positioned in the bottom-left corner of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityBottomLeft"
        }
      ],
      "role": "symbol",
      "title": "bottomLeft",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/bottomleft"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomRight": {
      "abstract": [
        {
          "text": "The content is positioned in the bottom-right corner of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityBottomRight"
        }
      ],
      "role": "symbol",
      "title": "bottomRight",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/bottomright"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/center": {
      "abstract": [
        {
          "text": "The content is horizontally and vertically centered in the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityCenter"
        }
      ],
      "role": "symbol",
      "title": "center",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/center"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/left": {
      "abstract": [
        {
          "text": "The content is vertically centered at the left-edge of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityLeft"
        }
      ],
      "role": "symbol",
      "title": "left",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/left"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resize": {
      "abstract": [
        {
          "text": "The content is resized to fit the entire bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityResize"
        }
      ],
      "role": "symbol",
      "title": "resize",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/resize"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspect": {
      "abstract": [
        {
          "text": "The content is resized to fit the bounds rectangle, preserving the aspect of the content. If the content does not completely fill the bounds rectangle, the content is centered in the partial axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resizeAspect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityResizeAspect"
        }
      ],
      "role": "symbol",
      "title": "resizeAspect",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/resizeaspect"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspectFill": {
      "abstract": [
        {
          "text": "The content is resized to completely fill the bounds rectangle, while still preserving the aspect of the content. The content is centered in the axis it exceeds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resizeAspectFill"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspectFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityResizeAspectFill"
        }
      ],
      "role": "symbol",
      "title": "resizeAspectFill",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/resizeaspectfill"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/right": {
      "abstract": [
        {
          "text": "The content is vertically centered at the right-edge of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityRight"
        }
      ],
      "role": "symbol",
      "title": "right",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/right"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/top": {
      "abstract": [
        {
          "text": "The content is horizontally centered at the top-edge of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityTop"
        }
      ],
      "role": "symbol",
      "title": "top",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/top"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topLeft": {
      "abstract": [
        {
          "text": "The content is positioned in the top-left corner of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityTopLeft"
        }
      ],
      "role": "symbol",
      "title": "topLeft",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/topleft"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topRight": {
      "abstract": [
        {
          "text": "The content is positioned in the top-right corner of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityTopRight"
        }
      ],
      "role": "symbol",
      "title": "topRight",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/topright"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Modifying-the-Layers-Appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsGravity",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/opacity",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isHidden",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/masksToBounds",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/mask",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isDoubleSided",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/cornerRadius",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/maskedCorners",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderWidth",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderColor",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundColor",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOpacity",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowRadius",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOffset"
      ],
      "title": "Modifying the Layer’s Appearance"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/center",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/top",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottom",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/left",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/right",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topLeft",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topRight",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomLeft",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomRight",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resize",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspect",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspectFill"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/center",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/top",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottom",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/left",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/right",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topLeft",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topRight",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomLeft",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomRight",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resize",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspect",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resizeAspectFill"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Modifying-the-Layers-Appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsGravity",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/opacity",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isHidden",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/masksToBounds",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/mask",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isDoubleSided",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/cornerRadius",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/maskedCorners",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderWidth",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderColor",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundColor",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOpacity",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowRadius",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOffset"
              ],
              "title": "Modifying the Layer’s Appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowRadius/title",
          "value": "shadowRadius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowRadius/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shadowRadius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1isDoubleSided/title",
          "value": "doubleSided"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1isDoubleSided/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "doubleSided"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1topRight/title",
          "value": "kCAGravityTopRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1topRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityTopRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1borderColor/title",
          "value": "borderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1borderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "borderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1maskedCorners/title",
          "value": "maskedCorners"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1maskedCorners/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maskedCorners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1borderWidth/title",
          "value": "borderWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1borderWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "borderWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1mask/title",
          "value": "mask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1mask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1resizeAspectFill/title",
          "value": "kCAGravityResizeAspectFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1resizeAspectFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityResizeAspectFill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1masksToBounds/title",
          "value": "masksToBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1masksToBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "masksToBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1opacity/title",
          "value": "opacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1opacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "opacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1contentsGravity/title",
          "value": "contentsGravity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1contentsGravity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentsGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1top/title",
          "value": "kCAGravityTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottom/title",
          "value": "kCAGravityBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1cornerRadius/title",
          "value": "cornerRadius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1cornerRadius/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cornerRadius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1backgroundColor/title",
          "value": "backgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1backgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1topLeft/title",
          "value": "kCAGravityTopLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1topLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityTopLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1right/title",
          "value": "kCAGravityRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask/title",
          "value": "CACornerMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CACornerMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CACornerMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer/title",
          "value": "CALayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1center/title",
          "value": "kCAGravityCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1resize/title",
          "value": "kCAGravityResize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1resize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityResize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowOpacity/title",
          "value": "shadowOpacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowOpacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shadowOpacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1resizeAspect/title",
          "value": "kCAGravityResizeAspect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1resizeAspect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityResizeAspect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottomRight/title",
          "value": "kCAGravityBottomRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottomRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityBottomRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottomLeft/title",
          "value": "kCAGravityBottomLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottomLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowOffset/title",
          "value": "shadowOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shadowOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1left/title",
          "value": "kCAGravityLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1isHidden/title",
          "value": "hidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1isHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hidden"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/contents-gravity-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/contents-gravity-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
