{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Animation Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAnimationCalculationMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAnimationCalculationMode"
        }
      ],
      "role": "symbol",
      "title": "CAAnimationCalculationMode",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationcalculationmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationRotationMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAAnimationRotationMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationRotationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAAnimationRotationMode"
        }
      ],
      "role": "symbol",
      "title": "CAAnimationRotationMode",
      "type": "topic",
      "url": "/documentation/quartzcore/caanimationrotationmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEmitterLayerEmitterMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEmitterLayerEmitterMode"
        }
      ],
      "role": "symbol",
      "title": "CAEmitterLayerEmitterMode",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayeremittermode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEmitterLayerEmitterShape"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEmitterLayerEmitterShape"
        }
      ],
      "role": "symbol",
      "title": "CAEmitterLayerEmitterShape",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayeremittershape"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerRenderMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEmitterLayerRenderMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerRenderMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEmitterLayerRenderMode"
        }
      ],
      "role": "symbol",
      "title": "CAEmitterLayerRenderMode",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayerrendermode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayerType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAGradientLayerType"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAGradientLayerType"
        }
      ],
      "role": "symbol",
      "title": "CAGradientLayerType",
      "type": "topic",
      "url": "/documentation/quartzcore/cagradientlayertype"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ToneMapMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ToneMapMode"
        }
      ],
      "role": "symbol",
      "title": "CALayer.ToneMapMode",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/tonemapmode-swift.struct"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct/automatic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CALayer",
          "text": "CALayer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAToneMapMode",
          "text": "ToneMapMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAToneMapModeAutomatic"
        }
      ],
      "role": "symbol",
      "title": "automatic",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/tonemapmode-swift.struct/automatic"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct/ifSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ifSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CALayer",
          "text": "CALayer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAToneMapMode",
          "text": "ToneMapMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct/ifSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAToneMapModeIfSupported"
        }
      ],
      "role": "symbol",
      "title": "ifSupported",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/tonemapmode-swift.struct/ifsupported"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct/never": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "never"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CALayer",
          "text": "CALayer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAToneMapMode",
          "text": "ToneMapMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct/never",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAToneMapModeNever"
        }
      ],
      "role": "symbol",
      "title": "never",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/tonemapmode-swift.struct/never"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFilter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerContentsFilter"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayerContentsFilter"
        }
      ],
      "role": "symbol",
      "title": "CALayerContentsFilter",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsfilter"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerContentsFormat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayerContentsFormat"
        }
      ],
      "role": "symbol",
      "title": "CALayerContentsFormat",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsformat"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayerContentsGravity"
        }
      ],
      "role": "symbol",
      "title": "CALayerContentsGravity",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerCornerCurve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerCornerCurve"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerCornerCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayerCornerCurve"
        }
      ],
      "role": "symbol",
      "title": "CALayerCornerCurve",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercornercurve"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMediaTimingFillMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMediaTimingFillMode"
        }
      ],
      "role": "symbol",
      "title": "CAMediaTimingFillMode",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatimingfillmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunctionName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMediaTimingFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunctionName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMediaTimingFunctionName"
        }
      ],
      "role": "symbol",
      "title": "CAMediaTimingFunctionName",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatimingfunctionname"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayerScrollMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAScrollLayerScrollMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayerScrollMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAScrollLayerScrollMode"
        }
      ],
      "role": "symbol",
      "title": "CAScrollLayerScrollMode",
      "type": "topic",
      "url": "/documentation/quartzcore/cascrolllayerscrollmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerFillRule": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAShapeLayerFillRule"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerFillRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAShapeLayerFillRule"
        }
      ],
      "role": "symbol",
      "title": "CAShapeLayerFillRule",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayerfillrule"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAShapeLayerLineCap"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAShapeLayerLineCap"
        }
      ],
      "role": "symbol",
      "title": "CAShapeLayerLineCap",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayerlinecap"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineJoin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAShapeLayerLineJoin"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineJoin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAShapeLayerLineJoin"
        }
      ],
      "role": "symbol",
      "title": "CAShapeLayerLineJoin",
      "type": "topic",
      "url": "/documentation/quartzcore/cashapelayerlinejoin"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayerAlignmentMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATextLayerAlignmentMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayerAlignmentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATextLayerAlignmentMode"
        }
      ],
      "role": "symbol",
      "title": "CATextLayerAlignmentMode",
      "type": "topic",
      "url": "/documentation/quartzcore/catextlayeralignmentmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayerTruncationMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATextLayerTruncationMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayerTruncationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATextLayerTruncationMode"
        }
      ],
      "role": "symbol",
      "title": "CATextLayerTruncationMode",
      "type": "topic",
      "url": "/documentation/quartzcore/catextlayertruncationmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionSubtype": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransitionSubtype"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransitionSubtype"
        }
      ],
      "role": "symbol",
      "title": "CATransitionSubtype",
      "type": "topic",
      "url": "/documentation/quartzcore/catransitionsubtype"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransitionType"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransitionType"
        }
      ],
      "role": "symbol",
      "title": "CATransitionType",
      "type": "topic",
      "url": "/documentation/quartzcore/catransitiontype"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAValueFunctionName"
        }
      ],
      "role": "symbol",
      "title": "CAValueFunctionName",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_BOXABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_BOXABLE"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_BOXABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_BOXABLE",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_boxable"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_CONST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_CONST"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_CONST",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_CONST",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_const"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_DEPRECATED",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_deprecated"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_EXTERN",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_extern"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN_C_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_EXTERN_C_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN_C_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_EXTERN_C_BEGIN",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_extern_c_begin"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN_C_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_EXTERN_C_END"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN_C_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_EXTERN_C_END",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_extern_c_end"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_GNUC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_GNUC"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_GNUC",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_GNUC",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_gnuc"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_INLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_INLINE"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_INLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_INLINE",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_inline"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_MALLOC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_MALLOC"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_MALLOC",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_MALLOC",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_malloc"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_NOINLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_NOINLINE"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_NOINLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_NOINLINE",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_noinline"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_NORETURN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_NORETURN"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_NORETURN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_NORETURN",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_noreturn"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_PURE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_PURE"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_PURE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_PURE",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_pure"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_WARN_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CA_WARN_DEPRECATED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_WARN_DEPRECATED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CA_WARN_DEPRECATED"
        }
      ],
      "role": "symbol",
      "title": "CA_WARN_DEPRECATED",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_warn_deprecated"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CA_WARN_UNUSED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CA_WARN_UNUSED"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CA_WARN_UNUSED",
      "kind": "symbol",
      "role": "symbol",
      "title": "CA_WARN_UNUSED",
      "type": "topic",
      "url": "/documentation/quartzcore/ca_warn_unused"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Animation Constants",
      "type": "topic",
      "url": "/documentation/quartzcore/core-animation-constants"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Animation Structures",
      "type": "topic",
      "url": "/documentation/quartzcore/core-animation-structures"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/quartzcore-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/quartzcore-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "QuartzCore Functions",
      "type": "topic",
      "url": "/documentation/quartzcore/quartzcore-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures",
        "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-constants",
        "doc://com.apple.quartzcore/documentation/QuartzCore/quartzcore-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationRotationMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerRenderMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayerType",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFilter",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerCornerCurve",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunctionName",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayerScrollMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerFillRule",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineJoin",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayerAlignmentMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayerTruncationMode",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionSubtype",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Variables",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct/automatic",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct/ifSupported",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct/never"
      ],
      "title": "Variables"
    },
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CA_WARN_DEPRECATED"
      ],
      "title": "Macros"
    },
    {
      "anchor": "Type-Aliases",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationCalculationMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAAnimationRotationMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerRenderMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAGradientLayerType",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFilter",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsFormat",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerCornerCurve",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFunctionName",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAScrollLayerScrollMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerFillRule",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineCap",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAShapeLayerLineJoin",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayerAlignmentMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayerTruncationMode",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionSubtype",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransitionType",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Variables",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct/automatic",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct/ifSupported",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct/never"
              ],
              "title": "Variables"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_BOXABLE",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_CONST",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_DEPRECATED",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN_C_BEGIN",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_EXTERN_C_END",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_GNUC",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_INLINE",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_MALLOC",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_NOINLINE",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_NORETURN",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_PURE",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_WARN_DEPRECATED",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CA_WARN_UNUSED"
              ],
              "title": "Macros"
            },
            {
              "anchor": "Type-Aliases",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/ToneMapMode-swift.struct"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures",
                "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-constants",
                "doc://com.apple.quartzcore/documentation/QuartzCore/quartzcore-functions"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAScrollLayerScrollMode/title",
          "value": "CAScrollLayerScrollMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAScrollLayerScrollMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAScrollLayerScrollMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAScrollLayerScrollMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAScrollLayerScrollMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATextLayerAlignmentMode/title",
          "value": "CATextLayerAlignmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATextLayerAlignmentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATextLayerAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATextLayerAlignmentMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATextLayerAlignmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATextLayerTruncationMode/title",
          "value": "CATextLayerTruncationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATextLayerTruncationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATextLayerTruncationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATextLayerTruncationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATextLayerTruncationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity/title",
          "value": "CALayerContentsGravity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineJoin/title",
          "value": "CAShapeLayerLineJoin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineJoin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerLineJoin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineJoin/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerLineJoin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAGradientLayerType/title",
          "value": "CAGradientLayerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAGradientLayerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAGradientLayerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAGradientLayerType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAGradientLayerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransitionType/title",
          "value": "CATransitionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransitionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransitionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransitionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransitionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1ToneMapMode-swift.struct/title",
          "value": "CAToneMapMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1ToneMapMode-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAToneMapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1ToneMapMode-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAToneMapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFunctionName/title",
          "value": "CAMediaTimingFunctionName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFunctionName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTimingFunctionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFunctionName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTimingFunctionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CA_WARN_DEPRECATED/title",
          "value": "CA_WARN_DEPRECATED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CA_WARN_DEPRECATED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CA_WARN_DEPRECATED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationRotationMode/title",
          "value": "CAAnimationRotationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationRotationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationRotationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationRotationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationRotationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineCap/title",
          "value": "CAShapeLayerLineCap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineCap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerLineCap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerLineCap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerLineCap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransitionSubtype/title",
          "value": "CATransitionSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransitionSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransitionSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransitionSubtype/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransitionSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode/title",
          "value": "CAMediaTimingFillMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTimingFillMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTimingFillMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFormat/title",
          "value": "CALayerContentsFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode/title",
          "value": "CAAnimationCalculationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationCalculationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAAnimationCalculationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAAnimationCalculationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFilter/title",
          "value": "CALayerContentsFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1ToneMapMode-swift.struct~1automatic/title",
          "value": "CAToneMapModeAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1ToneMapMode-swift.struct~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAToneMapModeAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerCornerCurve/title",
          "value": "CALayerCornerCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerCornerCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerCornerCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerCornerCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerCornerCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1ToneMapMode-swift.struct~1never/title",
          "value": "CAToneMapModeNever"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1ToneMapMode-swift.struct~1never/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAToneMapModeNever"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterMode/title",
          "value": "CAEmitterLayerEmitterMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerEmitterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerEmitterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName/title",
          "value": "CAValueFunctionName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunctionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunctionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape/title",
          "value": "CAEmitterLayerEmitterShape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerEmitterShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerEmitterShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerRenderMode/title",
          "value": "CAEmitterLayerRenderMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerRenderMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerRenderMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerRenderMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayerRenderMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerFillRule/title",
          "value": "CAShapeLayerFillRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerFillRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerFillRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAShapeLayerFillRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAShapeLayerFillRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1ToneMapMode-swift.struct~1ifSupported/title",
          "value": "CAToneMapModeIfSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1ToneMapMode-swift.struct~1ifSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAToneMapModeIfSupported"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/core-animation-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/core-animation-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
