{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Animation Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Animation Data Types",
      "type": "topic",
      "url": "/documentation/quartzcore/core-animation-data-types"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Animation Structures",
      "type": "topic",
      "url": "/documentation/quartzcore/core-animation-structures"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/kCARendererColorSpace": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCARendererColorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/kCARendererColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCARendererColorSpace"
        }
      ],
      "role": "symbol",
      "title": "kCARendererColorSpace",
      "type": "topic",
      "url": "/documentation/quartzcore/kcarenderercolorspace"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/kCARendererMetalCommandQueue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCARendererMetalCommandQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/kCARendererMetalCommandQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCARendererMetalCommandQueue"
        }
      ],
      "role": "symbol",
      "title": "kCARendererMetalCommandQueue",
      "type": "topic",
      "url": "/documentation/quartzcore/kcarenderermetalcommandqueue"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/quartzcore-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/quartzcore-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "QuartzCore Functions",
      "type": "topic",
      "url": "/documentation/quartzcore/quartzcore-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures",
        "doc://com.apple.quartzcore/documentation/QuartzCore/quartzcore-functions",
        "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/kCARendererColorSpace",
        "doc://com.apple.quartzcore/documentation/QuartzCore/kCARendererMetalCommandQueue"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/kCARendererColorSpace",
                "doc://com.apple.quartzcore/documentation/QuartzCore/kCARendererMetalCommandQueue"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures",
                "doc://com.apple.quartzcore/documentation/QuartzCore/quartzcore-functions",
                "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1kCARendererMetalCommandQueue/title",
          "value": "kCARendererMetalCommandQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1kCARendererMetalCommandQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCARendererMetalCommandQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1kCARendererColorSpace/title",
          "value": "kCARendererColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1kCARendererColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCARendererColorSpace"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/core-animation-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/core-animation-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
