{
  "abstract": [
    {
      "text": "The emission shape is a one, two or three dimensional shape that defines where the emitted particles originate. The shapes are defined by a subset of ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/emitterPosition",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ", ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/emitterZPosition",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ", ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/emitterSize",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " and ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/emitterDepth",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " properties.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/emitter-shape"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Emitter Shape"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer": {
      "abstract": [
        {
          "text": "A layer that emits, animates, and renders a particle system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAEmitterLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAEmitterLayer"
        }
      ],
      "role": "symbol",
      "title": "CAEmitterLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/emitterDepth": {
      "abstract": [
        {
          "text": "Determines the depth of the emitter shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emitterDepth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/emitterDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emitterDepth"
        }
      ],
      "role": "symbol",
      "title": "emitterDepth",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayer/emitterdepth"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/emitterMode": {
      "abstract": [
        {
          "text": "Specifies the emitter mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emitterMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAEmitterLayerEmitterMode",
          "text": "CAEmitterLayerEmitterMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/emitterMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emitterMode"
        }
      ],
      "role": "symbol",
      "title": "emitterMode",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayer/emittermode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/emitterPosition": {
      "abstract": [
        {
          "text": "The position of the center of the particle emitter. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emitterPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/emitterPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emitterPosition"
        }
      ],
      "role": "symbol",
      "title": "emitterPosition",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayer/emitterposition"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/emitterSize": {
      "abstract": [
        {
          "text": "Determines the size of the particle emitter shape. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emitterSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/emitterSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emitterSize"
        }
      ],
      "role": "symbol",
      "title": "emitterSize",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayer/emittersize"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/emitterZPosition": {
      "abstract": [
        {
          "text": "Specifies the center of the particle emitter shape along the z-axis. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emitterZPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/emitterZPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emitterZPosition"
        }
      ],
      "role": "symbol",
      "title": "emitterZPosition",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayer/emitterzposition"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/renderMode": {
      "abstract": [
        {
          "text": "Defines how particle cells are rendered into the layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renderMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAEmitterLayerRenderMode",
          "text": "CAEmitterLayerRenderMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/renderMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "renderMode"
        }
      ],
      "role": "symbol",
      "title": "renderMode",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayer/rendermode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/circle": {
      "abstract": [
        {
          "text": "Particles are emitted from a circle centered at (",
          "type": "text"
        },
        {
          "code": "emitterPosition.x",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "emitterPosition.y",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "emitterZPosition",
          "type": "codeVoice"
        },
        {
          "text": ") of radius ",
          "type": "text"
        },
        {
          "code": "emitterSize.width",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "circle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAEmitterLayerEmitterShape",
          "text": "CAEmitterLayerEmitterShape"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/circle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAEmitterLayerCircle"
        }
      ],
      "role": "symbol",
      "title": "circle",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayeremittershape/circle"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/cuboid": {
      "abstract": [
        {
          "text": "Particles are emitted from a cuboid (3D rectangle) with opposite corners: [emitterPosition.x - emitterSize.width/2, emitterPosition.y - emitterSize.height/2, emitterZPosition - emitterDepth/2], [emitterPosition.x + emitterSize.width/2, emitterPosition.y + emitterSize.height/2, emitterZPosition+emitterDepth/2].",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cuboid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAEmitterLayerEmitterShape",
          "text": "CAEmitterLayerEmitterShape"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/cuboid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAEmitterLayerCuboid"
        }
      ],
      "role": "symbol",
      "title": "cuboid",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayeremittershape/cuboid"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/line": {
      "abstract": [
        {
          "text": "Particles are emitted along a line from (",
          "type": "text"
        },
        {
          "code": "emitterPosition.x - emitterSize.width/2",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "emitterPosition.y",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "emitterZPosition",
          "type": "codeVoice"
        },
        {
          "text": ") to (",
          "type": "text"
        },
        {
          "code": "emitterPosition.x + emitterSize.width/2",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "emitterPosition.y",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "emitterZPosition",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "line"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAEmitterLayerEmitterShape",
          "text": "CAEmitterLayerEmitterShape"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/line",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAEmitterLayerLine"
        }
      ],
      "role": "symbol",
      "title": "line",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayeremittershape/line"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/point": {
      "abstract": [
        {
          "text": "Particles are emitted from a single point at (",
          "type": "text"
        },
        {
          "code": "emitterPosition.x",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "emitterPosition.y",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "emitterZPosition",
          "type": "codeVoice"
        },
        {
          "text": ")",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "point"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAEmitterLayerEmitterShape",
          "text": "CAEmitterLayerEmitterShape"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/point",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAEmitterLayerPoint"
        }
      ],
      "role": "symbol",
      "title": "point",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayeremittershape/point"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/rectangle": {
      "abstract": [
        {
          "text": "Particles are emitted from a rectangle with opposite corners [emitterPosition.x - emitterSize.width/2, emitterPosition.y - emitterSize.height/2, emitterZPosition], [emitterPosition.x + emitterSize.width/2, emitterPosition.y + emitterSize.height/2, emitterZPosition].",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rectangle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAEmitterLayerEmitterShape",
          "text": "CAEmitterLayerEmitterShape"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/rectangle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAEmitterLayerRectangle"
        }
      ],
      "role": "symbol",
      "title": "rectangle",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayeremittershape/rectangle"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/sphere": {
      "abstract": [
        {
          "text": "Particles are emitted from a sphere centered at (",
          "type": "text"
        },
        {
          "code": "emitterPosition.x",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "emitterPosition.y",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "emitterZPosition",
          "type": "codeVoice"
        },
        {
          "text": ") of radius ",
          "type": "text"
        },
        {
          "code": "emitterSize.width",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sphere"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAEmitterLayerEmitterShape",
          "text": "CAEmitterLayerEmitterShape"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/sphere",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAEmitterLayerSphere"
        }
      ],
      "role": "symbol",
      "title": "sphere",
      "type": "topic",
      "url": "/documentation/quartzcore/caemitterlayeremittershape/sphere"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/emitter-modes": {
      "abstract": [
        {
          "text": "These constants specify the possible emitter modes. They are used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/emitterMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/emitter-modes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Emitter Modes",
      "type": "topic",
      "url": "/documentation/quartzcore/emitter-modes"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/emitter-render-order": {
      "abstract": [
        {
          "text": "These constants specify the order that emitter cells are composited. They are used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayer/renderMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/emitter-render-order",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Emitter Render Order",
      "type": "topic",
      "url": "/documentation/quartzcore/emitter-render-order"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/emitter-modes",
        "doc://com.apple.quartzcore/documentation/QuartzCore/emitter-render-order"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/point",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/line",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/rectangle",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/cuboid",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/circle",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/sphere"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/point",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/line",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/rectangle",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/cuboid",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/circle",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAEmitterLayerEmitterShape/sphere"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/emitter-modes",
                "doc://com.apple.quartzcore/documentation/QuartzCore/emitter-render-order"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape~1cuboid/title",
          "value": "kCAEmitterLayerCuboid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape~1cuboid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAEmitterLayerCuboid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer~1emitterSize/title",
          "value": "emitterSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer~1emitterSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "emitterSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer/title",
          "value": "CAEmitterLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAEmitterLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer~1emitterZPosition/title",
          "value": "emitterZPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer~1emitterZPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "emitterZPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape~1rectangle/title",
          "value": "kCAEmitterLayerRectangle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape~1rectangle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAEmitterLayerRectangle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer~1emitterPosition/title",
          "value": "emitterPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer~1emitterPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "emitterPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape~1circle/title",
          "value": "kCAEmitterLayerCircle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape~1circle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAEmitterLayerCircle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape~1sphere/title",
          "value": "kCAEmitterLayerSphere"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape~1sphere/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAEmitterLayerSphere"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape~1point/title",
          "value": "kCAEmitterLayerPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape~1point/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAEmitterLayerPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer~1emitterDepth/title",
          "value": "emitterDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer~1emitterDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "emitterDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer~1emitterMode/title",
          "value": "emitterMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer~1emitterMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "emitterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape~1line/title",
          "value": "kCAEmitterLayerLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayerEmitterShape~1line/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAEmitterLayerLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer~1renderMode/title",
          "value": "renderMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAEmitterLayer~1renderMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "renderMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/emitter-shape"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/emitter-shape"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
