{
  "abstract": [
    {
      "text": "These constants determine how the timed object behaves once its active duration has completed. They are used with the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming/fillMode",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/fill-modes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Fill Modes"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming": {
      "abstract": [
        {
          "text": "Methods that model a hierarchical timing system, allowing objects to map time between their parent and local time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMediaTiming"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAMediaTiming"
        }
      ],
      "role": "symbol",
      "title": "CAMediaTiming",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatiming"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming/fillMode": {
      "abstract": [
        {
          "text": "Determines if the receiver’s presentation is frozen or removed once its active duration has completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fillMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAMediaTimingFillMode",
          "text": "CAMediaTimingFillMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTiming/fillMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fillMode"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "fillMode",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatiming/fillmode"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/backwards": {
      "abstract": [
        {
          "text": "The receiver clamps values before zero to zero when the animation is completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backwards"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAMediaTimingFillMode",
          "text": "CAMediaTimingFillMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/backwards",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFillModeBackwards"
        }
      ],
      "role": "symbol",
      "title": "backwards",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatimingfillmode/backwards"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/both": {
      "abstract": [
        {
          "text": "The receiver clamps values at both ends of the object’s time space",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "both"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAMediaTimingFillMode",
          "text": "CAMediaTimingFillMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/both",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFillModeBoth"
        }
      ],
      "role": "symbol",
      "title": "both",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatimingfillmode/both"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/forwards": {
      "abstract": [
        {
          "text": "The receiver remains visible in its final state when the animation is completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forwards"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAMediaTimingFillMode",
          "text": "CAMediaTimingFillMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/forwards",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFillModeForwards"
        }
      ],
      "role": "symbol",
      "title": "forwards",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatimingfillmode/forwards"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/removed": {
      "abstract": [
        {
          "text": "The receiver is removed from the presentation when the animation is completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAMediaTimingFillMode",
          "text": "CAMediaTimingFillMode"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/removed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAFillModeRemoved"
        }
      ],
      "role": "symbol",
      "title": "removed",
      "type": "topic",
      "url": "/documentation/quartzcore/camediatimingfillmode/removed"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/kcafillmodefrozen": {
      "abstract": [
        {
          "text": "The mode was deprecated before OS X v10.5 shipped.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/kcafillmodefrozen",
      "kind": "article",
      "role": "article",
      "title": "kCAFillModeFrozen",
      "type": "topic",
      "url": "/documentation/quartzcore/kcafillmodefrozen"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/removed",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/forwards",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/backwards",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/both"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/removed",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/forwards",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/backwards",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAMediaTimingFillMode/both",
                "doc://com.apple.quartzcore/documentation/QuartzCore/kcafillmodefrozen"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode~1forwards/title",
          "value": "kCAFillModeForwards"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode~1forwards/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFillModeForwards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode~1backwards/title",
          "value": "kCAFillModeBackwards"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode~1backwards/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFillModeBackwards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/title",
          "value": "CAMediaTiming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTiming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAMediaTiming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming~1fillMode/title",
          "value": "fillMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTiming~1fillMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fillMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode~1both/title",
          "value": "kCAFillModeBoth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode~1both/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFillModeBoth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode~1removed/title",
          "value": "kCAFillModeRemoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAMediaTimingFillMode~1removed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAFillModeRemoved"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/fill-modes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/fill-modes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
