{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/quartzcore-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "QuartzCore Functions"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRangeIsEqualToRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CAFrameRateRangeIsEqualToRange"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRangeIsEqualToRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "CAFrameRateRangeIsEqualToRange",
      "type": "topic",
      "url": "/documentation/quartzcore/caframeraterangeisequaltorange"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRangeMake": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CAFrameRateRangeMake"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRangeMake",
      "kind": "symbol",
      "role": "symbol",
      "title": "CAFrameRateRangeMake",
      "type": "topic",
      "url": "/documentation/quartzcore/caframeraterangemake"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Animation Constants",
      "type": "topic",
      "url": "/documentation/quartzcore/core-animation-constants"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Animation Data Types",
      "type": "topic",
      "url": "/documentation/quartzcore/core-animation-data-types"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Animation Structures",
      "type": "topic",
      "url": "/documentation/quartzcore/core-animation-structures"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures",
        "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-constants",
        "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-data-types"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRangeIsEqualToRange",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAFrameRateRangeMake"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-structures",
                "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-constants",
                "doc://com.apple.quartzcore/documentation/QuartzCore/core-animation-data-types"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/quartzcore-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/quartzcore-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
