{
  "abstract": [
    {
      "text": "Scale value transform functions construct a 4x4 matrix that represents the corresponding scale matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/scale-value-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Scale Value Functions"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction": {
      "abstract": [
        {
          "text": "An object that provides a flexible method of defining animated transformations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAValueFunction"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAValueFunction"
        }
      ],
      "role": "symbol",
      "title": "CAValueFunction",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunction"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scale": {
      "abstract": [
        {
          "text": "A value function scales by the input value along all three axis. Animations using this value transform function must provide animation values in an ",
          "type": "text"
        },
        {
          "code": "NSArray",
          "type": "codeVoice"
        },
        {
          "text": " of three ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " instances that specify the (x, y, z) scale values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionScale"
        }
      ],
      "role": "symbol",
      "title": "scale",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/scale"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleX": {
      "abstract": [
        {
          "text": "A value function scales by the input value along the x-axis. Animations referencing this value transform function must provide a single animation value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionScaleX"
        }
      ],
      "role": "symbol",
      "title": "scaleX",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/scalex"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleY": {
      "abstract": [
        {
          "text": "A value function scales by the input value along the y-axis. Animations referencing this value function must provide a single animation value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionScaleY"
        }
      ],
      "role": "symbol",
      "title": "scaleY",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/scaley"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleZ": {
      "abstract": [
        {
          "text": "A value function that scales by the input value along the z-axis. Animations referencing this value function must provide a single animation value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleZ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleZ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionScaleZ"
        }
      ],
      "role": "symbol",
      "title": "scaleZ",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/scalez"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/rotate-value-functions": {
      "abstract": [
        {
          "text": "Rotate value transform functions construct a 4x4 matrix that represents the corresponding rotation matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/rotate-value-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Rotate Value Functions",
      "type": "topic",
      "url": "/documentation/quartzcore/rotate-value-functions"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/translate-functions": {
      "abstract": [
        {
          "text": "Translate value transform functions construct a 4x4 matrix that represents the corresponding translate matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/translate-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Translate Functions",
      "type": "topic",
      "url": "/documentation/quartzcore/translate-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/rotate-value-functions",
        "doc://com.apple.quartzcore/documentation/QuartzCore/translate-functions"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scale",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleX",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleY",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleZ"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scale",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleX",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleY",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/scaleZ"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/rotate-value-functions",
                "doc://com.apple.quartzcore/documentation/QuartzCore/translate-functions"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scaleZ/title",
          "value": "kCAValueFunctionScaleZ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scaleZ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionScaleZ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scaleX/title",
          "value": "kCAValueFunctionScaleX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scaleX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionScaleX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scale/title",
          "value": "kCAValueFunctionScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scaleY/title",
          "value": "kCAValueFunctionScaleY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1scaleY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionScaleY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunction/title",
          "value": "CAValueFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/scale-value-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/scale-value-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
