{
  "abstract": [
    {
      "text": "Translate value transform functions construct a 4x4 matrix that represents the corresponding translate matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/translate-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Translate Functions"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction": {
      "abstract": [
        {
          "text": "An object that provides a flexible method of defining animated transformations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAValueFunction"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CAValueFunction"
        }
      ],
      "role": "symbol",
      "title": "CAValueFunction",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunction"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translate": {
      "abstract": [
        {
          "text": "A value function that translates by the input values along all three axis. Animations using this value transform function must provide animation values in an ",
          "type": "text"
        },
        {
          "code": "NSArray",
          "type": "codeVoice"
        },
        {
          "text": " of three ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " instances that specify the (x, y, z) translate values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "translate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionTranslate"
        }
      ],
      "role": "symbol",
      "title": "translate",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/translate"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateX": {
      "abstract": [
        {
          "text": "A value function translates by the input value along the x-axis. Animations referencing this value function must provide a single input value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "translateX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionTranslateX"
        }
      ],
      "role": "symbol",
      "title": "translateX",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/translatex"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateY": {
      "abstract": [
        {
          "text": "A value function translates by the input value along the y-axis. Animations referencing this value function must provide a single input value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "translateY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionTranslateY"
        }
      ],
      "role": "symbol",
      "title": "translateY",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/translatey"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateZ": {
      "abstract": [
        {
          "text": "A value function translates by the input value along the z-axis. Animations referencing this value function must provide a single input value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "translateZ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CAValueFunctionName",
          "text": "CAValueFunctionName"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateZ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAValueFunctionTranslateZ"
        }
      ],
      "role": "symbol",
      "title": "translateZ",
      "type": "topic",
      "url": "/documentation/quartzcore/cavaluefunctionname/translatez"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/rotate-value-functions": {
      "abstract": [
        {
          "text": "Rotate value transform functions construct a 4x4 matrix that represents the corresponding rotation matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/rotate-value-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Rotate Value Functions",
      "type": "topic",
      "url": "/documentation/quartzcore/rotate-value-functions"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/scale-value-functions": {
      "abstract": [
        {
          "text": "Scale value transform functions construct a 4x4 matrix that represents the corresponding scale matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/scale-value-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Scale Value Functions",
      "type": "topic",
      "url": "/documentation/quartzcore/scale-value-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/rotate-value-functions",
        "doc://com.apple.quartzcore/documentation/QuartzCore/scale-value-functions"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translate",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateX",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateY",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateZ"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translate",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateX",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateY",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CAValueFunctionName/translateZ"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/rotate-value-functions",
                "doc://com.apple.quartzcore/documentation/QuartzCore/scale-value-functions"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunction/title",
          "value": "CAValueFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CAValueFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translate/title",
          "value": "kCAValueFunctionTranslate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionTranslate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translateX/title",
          "value": "kCAValueFunctionTranslateX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translateX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionTranslateX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translateY/title",
          "value": "kCAValueFunctionTranslateY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translateY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionTranslateY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translateZ/title",
          "value": "kCAValueFunctionTranslateZ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CAValueFunctionName~1translateZ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAValueFunctionTranslateZ"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/translate-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/translate-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
