{
  "abstract": [
    {
      "text": "Define transform matrices to apply affine transformations to layers in Core Animation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/transforms"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Transforms"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3D": {
      "abstract": [
        {
          "text": "The standard transform matrix used throughout Core Animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3D"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3D"
        }
      ],
      "role": "symbol",
      "title": "CATransform3D",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3d"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DConcat(_:_:)": {
      "abstract": [
        {
          "text": "Concatenates ",
          "type": "text"
        },
        {
          "code": "b",
          "type": "codeVoice"
        },
        {
          "text": " to ",
          "type": "text"
        },
        {
          "code": "a",
          "type": "codeVoice"
        },
        {
          "text": " and returns the result: ",
          "type": "text"
        },
        {
          "code": "t = a * b",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3DConcat"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DConcat(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3DConcat"
        }
      ],
      "role": "symbol",
      "title": "CATransform3DConcat(_:_:)",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3dconcat(_:_:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DEqualToTransform(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the two transforms are exactly equal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3DEqualToTransform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DEqualToTransform(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3DEqualToTransform"
        }
      ],
      "role": "symbol",
      "title": "CATransform3DEqualToTransform(_:_:)",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3dequaltotransform(_:_:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DGetAffineTransform(_:)": {
      "abstract": [
        {
          "text": "Returns the affine transform represented by ",
          "type": "text"
        },
        {
          "code": "t",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3DGetAffineTransform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DGetAffineTransform(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3DGetAffineTransform"
        }
      ],
      "role": "symbol",
      "title": "CATransform3DGetAffineTransform(_:)",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3dgetaffinetransform(_:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DIdentity": {
      "abstract": [
        {
          "text": "The identity transform: ",
          "type": "text"
        },
        {
          "code": "[1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1]",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3DIdentity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3DIdentity"
        }
      ],
      "role": "symbol",
      "title": "CATransform3DIdentity",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3didentity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DInvert(_:)": {
      "abstract": [
        {
          "text": "Inverts ",
          "type": "text"
        },
        {
          "code": "t",
          "type": "codeVoice"
        },
        {
          "text": " and returns the result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3DInvert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DInvert(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3DInvert"
        }
      ],
      "role": "symbol",
      "title": "CATransform3DInvert(_:)",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3dinvert(_:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DIsAffine(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a transform can be exactly represented by an affine transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3DIsAffine"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DIsAffine(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3DIsAffine"
        }
      ],
      "role": "symbol",
      "title": "CATransform3DIsAffine(_:)",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3disaffine(_:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DIsIdentity(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the transform is the identity transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3DIsIdentity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DIsIdentity(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3DIsIdentity"
        }
      ],
      "role": "symbol",
      "title": "CATransform3DIsIdentity(_:)",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3disidentity(_:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeAffineTransform(_:)": {
      "abstract": [
        {
          "text": "Returns a transform with the same effect as affine transform ",
          "type": "text"
        },
        {
          "code": "m",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3DMakeAffineTransform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeAffineTransform(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3DMakeAffineTransform"
        }
      ],
      "role": "symbol",
      "title": "CATransform3DMakeAffineTransform(_:)",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3dmakeaffinetransform(_:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeRotation(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a transform that rotates by ",
          "type": "text"
        },
        {
          "code": "angle",
          "type": "codeVoice"
        },
        {
          "text": " radians about the vector ",
          "type": "text"
        },
        {
          "code": "(x, y, z)",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3DMakeRotation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeRotation(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3DMakeRotation"
        }
      ],
      "role": "symbol",
      "title": "CATransform3DMakeRotation(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3dmakerotation(_:_:_:_:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeScale(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a transform that scales by ",
          "type": "text"
        },
        {
          "code": "(sx, sy, sz)",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3DMakeScale"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeScale(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3DMakeScale"
        }
      ],
      "role": "symbol",
      "title": "CATransform3DMakeScale(_:_:_:)",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3dmakescale(_:_:_:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeTranslation(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a transform that translates by ",
          "type": "text"
        },
        {
          "code": "(tx, ty, tz)",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3DMakeTranslation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeTranslation(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3DMakeTranslation"
        }
      ],
      "role": "symbol",
      "title": "CATransform3DMakeTranslation(_:_:_:)",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3dmaketranslation(_:_:_:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DRotate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Rotates ",
          "type": "text"
        },
        {
          "code": "t",
          "type": "codeVoice"
        },
        {
          "text": " by ",
          "type": "text"
        },
        {
          "code": "angle",
          "type": "codeVoice"
        },
        {
          "text": " radians about the vector ",
          "type": "text"
        },
        {
          "code": "(x, y, z)",
          "type": "codeVoice"
        },
        {
          "text": " and returns the result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3DRotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DRotate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3DRotate"
        }
      ],
      "role": "symbol",
      "title": "CATransform3DRotate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3drotate(_:_:_:_:_:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DScale(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Scales ",
          "type": "text"
        },
        {
          "code": "t",
          "type": "codeVoice"
        },
        {
          "text": " by ",
          "type": "text"
        },
        {
          "code": "(sx, sy, sz)",
          "type": "codeVoice"
        },
        {
          "text": " and returns the result: ",
          "type": "text"
        },
        {
          "code": "t = scale(sx, sy, sz) * t",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3DScale"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DScale(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3DScale"
        }
      ],
      "role": "symbol",
      "title": "CATransform3DScale(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3dscale(_:_:_:_:)"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DTranslate(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Translates ",
          "type": "text"
        },
        {
          "code": "t",
          "type": "codeVoice"
        },
        {
          "text": " by ",
          "type": "text"
        },
        {
          "code": "(tx, ty, tz)",
          "type": "codeVoice"
        },
        {
          "text": " and returns the result: ",
          "type": "text"
        },
        {
          "code": "t",
          "type": "codeVoice"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "code": "= translate(tx, ty, tz) * t",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransform3DTranslate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CATransform3D",
          "text": "CATransform3D"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DTranslate(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransform3DTranslate"
        }
      ],
      "role": "symbol",
      "title": "CATransform3DTranslate(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/quartzcore/catransform3dtranslate(_:_:_:_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-Transforms",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeTranslation(_:_:_:)",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeScale(_:_:_:)",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeRotation(_:_:_:_:)"
      ],
      "title": "Creating Transforms"
    },
    {
      "anchor": "Chaining-Transforms",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DConcat(_:_:)",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DTranslate(_:_:_:_:)",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DScale(_:_:_:_:)",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DRotate(_:_:_:_:_:)"
      ],
      "title": "Chaining Transforms"
    },
    {
      "anchor": "Inverting-a-Transform",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DInvert(_:)"
      ],
      "title": "Inverting a Transform"
    },
    {
      "anchor": "Determining-Transform-Properties",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DIsAffine(_:)",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DIsIdentity(_:)",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DEqualToTransform(_:_:)"
      ],
      "title": "Determining Transform Properties"
    },
    {
      "anchor": "Converting-to-and-from-Core-Graphics-Affine-Transforms",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeAffineTransform(_:)",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DGetAffineTransform(_:)"
      ],
      "title": "Converting to and from Core Graphics Affine Transforms"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3D"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DIdentity"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Transforms",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeTranslation(_:_:_:)",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeScale(_:_:_:)",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeRotation(_:_:_:_:)"
              ],
              "title": "Creating Transforms"
            },
            {
              "anchor": "Chaining-Transforms",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DConcat(_:_:)",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DTranslate(_:_:_:_:)",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DScale(_:_:_:_:)",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DRotate(_:_:_:_:_:)"
              ],
              "title": "Chaining Transforms"
            },
            {
              "anchor": "Inverting-a-Transform",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DInvert(_:)"
              ],
              "title": "Inverting a Transform"
            },
            {
              "anchor": "Determining-Transform-Properties",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DIsAffine(_:)",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DIsIdentity(_:)",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DEqualToTransform(_:_:)"
              ],
              "title": "Determining Transform Properties"
            },
            {
              "anchor": "Converting-to-and-from-Core-Graphics-Affine-Transforms",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DMakeAffineTransform(_:)",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DGetAffineTransform(_:)"
              ],
              "title": "Converting to and from Core Graphics Affine Transforms"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3D"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransform3DIdentity"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DGetAffineTransform(_:)/title",
          "value": "CATransform3DGetAffineTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DGetAffineTransform(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DGetAffineTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DTranslate(_:_:_:_:)/title",
          "value": "CATransform3DTranslate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DTranslate(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DTranslate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DMakeAffineTransform(_:)/title",
          "value": "CATransform3DMakeAffineTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DMakeAffineTransform(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DMakeAffineTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DMakeRotation(_:_:_:_:)/title",
          "value": "CATransform3DMakeRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DMakeRotation(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DMakeRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DScale(_:_:_:_:)/title",
          "value": "CATransform3DScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DScale(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DConcat(_:_:)/title",
          "value": "CATransform3DConcat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DConcat(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DConcat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DRotate(_:_:_:_:_:)/title",
          "value": "CATransform3DRotate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DRotate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DRotate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DIsIdentity(_:)/title",
          "value": "CATransform3DIsIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DIsIdentity(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DIsIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DIsAffine(_:)/title",
          "value": "CATransform3DIsAffine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DIsAffine(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DIsAffine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DIdentity/title",
          "value": "CATransform3DIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DMakeScale(_:_:_:)/title",
          "value": "CATransform3DMakeScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DMakeScale(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DMakeScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DEqualToTransform(_:_:)/title",
          "value": "CATransform3DEqualToTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DEqualToTransform(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DEqualToTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3D/title",
          "value": "CATransform3D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DInvert(_:)/title",
          "value": "CATransform3DInvert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DInvert(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DInvert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DMakeTranslation(_:_:_:)/title",
          "value": "CATransform3DMakeTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransform3DMakeTranslation(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransform3DMakeTranslation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/transforms"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/transforms"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
