{
  "abstract": [
    {
      "text": "A signpost that marks an event in your code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os",
        "doc://com.apple.os/documentation/os/OSSignpostType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.os/documentation/os/os_signpost_type_t/OS_SIGNPOST_EVENT"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@os_signpost_type_t@OS_SIGNPOST_EVENT",
    "fragments": [
      {
        "kind": "identifier",
        "text": "OS_SIGNPOST_EVENT"
      }
    ],
    "modules": [
      {
        "name": "os"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OS_SIGNPOST_EVENT"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "OS_SIGNPOST_EVENT"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "OS_SIGNPOST_EVENT"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/OSSignpostType": {
      "abstract": [
        {
          "text": "The different kinds of signpost.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSignpostType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignpostType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSignpostType"
        }
      ],
      "role": "symbol",
      "title": "OSSignpostType",
      "type": "topic",
      "url": "/documentation/os/ossignposttype"
    },
    "doc://com.apple.os/documentation/os/os_signpost_type_t/OS_SIGNPOST_EVENT": {
      "abstract": [
        {
          "text": "A signpost that marks an event in your code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_SIGNPOST_EVENT"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_type_t/OS_SIGNPOST_EVENT",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_SIGNPOST_EVENT",
      "type": "topic",
      "url": "/documentation/os/os_signpost_type_t/os_signpost_event"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSSignpostType/title",
          "value": "os_signpost_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSSignpostType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSSignpostType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_type_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/os_signpost_type_t/os_signpost_event"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
