{
  "abstract": [
    {
      "text": "Renders a portion of a node’s contents and returns the rendered image as a SpriteKit texture.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSKScene"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSKScene/texture(from:crop:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKInterfaceSKScene(im)textureFromNode:crop:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "texture"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "from"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SKNode",
        "text": "SKNode"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "crop"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGRect",
        "text": "CGRect"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SKTexture",
        "text": "SKTexture"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "textureFromNode:crop:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "texture(from:crop:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "texture"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "from"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "node"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)SKNode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SKNode",
              "text": "SKNode"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "crop"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGRect",
              "text": "CGRect"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)SKTexture",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SKTexture",
              "text": "SKTexture"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A node object representing the root node of the tree to be render to the texture.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "node"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A rectangle in the ",
                  "type": "text"
                },
                {
                  "code": "node",
                  "type": "codeVoice"
                },
                {
                  "text": "’s coordinate system that describes the area to be rendered.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "crop"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A SpriteKit texture that holds the rendered image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "node",
              "type": "codeVoice"
            },
            {
              "text": " being rendered does not need to appear in the interface’s presented scene. The new texture is created with a size equal to the size of the ",
              "type": "text"
            },
            {
              "code": "crop",
              "type": "codeVoice"
            },
            {
              "text": " rectangle. If the ",
              "type": "text"
            },
            {
              "code": "node",
              "type": "codeVoice"
            },
            {
              "text": " is not a scene node, it is rendered with a clear background color (",
              "type": "text"
            },
            {
              "code": "[SKColor clearColor]",
              "type": "codeVoice"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSKScene": {
      "abstract": [
        {
          "text": "A visual WatchKit element that displays a SpriteKit scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceSKScene"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSKScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceSKScene"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceSKScene",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfaceskscene"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSKScene/texture(from:)": {
      "abstract": [
        {
          "text": "Renders the contents of a node tree and returns the rendered image as a SpriteKit texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKNode",
          "text": "SKNode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTexture",
          "text": "SKTexture"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSKScene/texture(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textureFromNode:"
        }
      ],
      "role": "symbol",
      "title": "texture(from:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfaceskscene/texture(from:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSKScene/texture(from:crop:)": {
      "abstract": [
        {
          "text": "Renders a portion of a node’s contents and returns the rendered image as a SpriteKit texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKNode",
          "text": "SKNode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "crop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKTexture",
          "text": "SKTexture"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSKScene/texture(from:crop:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textureFromNode:crop:"
        }
      ],
      "role": "symbol",
      "title": "texture(from:crop:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfaceskscene/texture(from:crop:)"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGRect": {
      "abstract": [
        {
          "text": "A structure that contains the location and dimensions of a rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGRect",
      "type": "topic",
      "url": "/documentation/corefoundation/cgrect"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)SKNode": {
      "abstract": [
        {
          "text": "The base class of all SpriteKit nodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKNode"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)SKNode",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKNode",
      "type": "topic",
      "url": "/documentation/SpriteKit/SKNode"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)SKTexture": {
      "abstract": [
        {
          "text": "An image, decoded on the GPU, that can be used to render various SpriteKit objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTexture"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)SKTexture",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKTexture",
      "type": "topic",
      "url": "/documentation/SpriteKit/SKTexture"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Snapshotting-Nodes-to-a-Texture",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSKScene/texture(from:)"
      ],
      "title": "Snapshotting Nodes to a Texture"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "textureFromNode:crop:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textureFromNode:crop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSKScene"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Snapshotting-Nodes-to-a-Texture",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceSKScene/texture(from:)"
              ],
              "title": "Snapshotting Nodes to a Texture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)SKTexture",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SKTexture",
                    "text": "SKTexture"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "textureFromNode:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)SKNode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SKNode",
                    "text": "SKNode"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "node"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "crop:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGRect",
                    "text": "CGRect"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "crop"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A node object representing the root node of the tree to be render to the texture.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "node"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A rectangle in the ",
                        "type": "text"
                      },
                      {
                        "code": "node",
                        "type": "codeVoice"
                      },
                      {
                        "text": "’s coordinate system that describes the area to be rendered.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "crop"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A SpriteKit texture that holds the rendered image.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSKScene~1texture(from:crop:)/title",
          "value": "textureFromNode:crop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSKScene~1texture(from:crop:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textureFromNode:crop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSKScene~1texture(from:)/title",
          "value": "textureFromNode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSKScene~1texture(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textureFromNode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)SKNode/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKNode"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIResponder",
              "text": "UIResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)SKTexture/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKTexture"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSKScene/title",
          "value": "WKInterfaceSKScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSKScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceSKScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceSKScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceSKScene"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkinterfaceskscene/texture(from:crop:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkinterfaceskscene/texture(from:crop:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
