{
  "abstract": [
    {
      "text": "A pointer to the first byte of the destination buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compression/documentation/Compression",
        "doc://com.apple.compression/documentation/Compression/compression_stream"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.compression/documentation/Compression/compression_stream/dst_ptr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@compression_stream@FI@dst_ptr",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dst_ptr"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5UInt8V",
        "text": "UInt8"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "Compression"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dst_ptr"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "dst_ptr"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dst_ptr"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5UInt8V",
              "text": "UInt8"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.compression/documentation/Compression": {
      "abstract": [
        {
          "text": "Leverage common compression algorithms for lossless data compression.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression",
      "kind": "symbol",
      "role": "collection",
      "title": "Compression",
      "type": "topic",
      "url": "/documentation/compression"
    },
    "doc://com.apple.compression/documentation/Compression/compression_stream": {
      "abstract": [
        {
          "text": "A structure representing a compression stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compression_stream"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compression_stream"
        }
      ],
      "role": "symbol",
      "title": "compression_stream",
      "type": "topic",
      "url": "/documentation/compression/compression_stream"
    },
    "doc://com.apple.compression/documentation/Compression/compression_stream/dst_ptr": {
      "abstract": [
        {
          "text": "A pointer to the first byte of the destination buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dst_ptr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream/dst_ptr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dst_ptr"
        }
      ],
      "role": "symbol",
      "title": "dst_ptr",
      "type": "topic",
      "url": "/documentation/compression/compression_stream/dst_ptr"
    },
    "doc://com.apple.compression/documentation/Compression/compression_stream/dst_size": {
      "abstract": [
        {
          "text": "The size, in bytes, of the destination buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dst_size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream/dst_size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dst_size"
        }
      ],
      "role": "symbol",
      "title": "dst_size",
      "type": "topic",
      "url": "/documentation/compression/compression_stream/dst_size"
    },
    "doc://com.apple.compression/documentation/Compression/compression_stream/src_ptr": {
      "abstract": [
        {
          "text": "A pointer to the first byte of the source buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "src_ptr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream/src_ptr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "src_ptr"
        }
      ],
      "role": "symbol",
      "title": "src_ptr",
      "type": "topic",
      "url": "/documentation/compression/compression_stream/src_ptr"
    },
    "doc://com.apple.compression/documentation/Compression/compression_stream/src_size": {
      "abstract": [
        {
          "text": "The size, in bytes, of the source buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "src_size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream/src_size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "src_size"
        }
      ],
      "role": "symbol",
      "title": "src_size",
      "type": "topic",
      "url": "/documentation/compression/compression_stream/src_size"
    },
    "doc://com.apple.compression/documentation/Compression/compression_stream/state": {
      "abstract": [
        {
          "text": "The stream state object of the compression stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.compression/documentation/Compression/compression_stream/state",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/compression/compression_stream/state"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:s5UInt8V": {
      "abstract": [
        {
          "text": "An 8-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt8",
      "type": "topic",
      "url": "/documentation/Swift/UInt8"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Compression-Stream-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compression/documentation/Compression/compression_stream/dst_size",
        "doc://com.apple.compression/documentation/Compression/compression_stream/src_ptr",
        "doc://com.apple.compression/documentation/Compression/compression_stream/src_size",
        "doc://com.apple.compression/documentation/Compression/compression_stream/state"
      ],
      "title": "Compression Stream Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "dst_ptr"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dst_ptr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.compression/documentation/Compression",
                "doc://com.apple.compression/documentation/Compression/compression_stream"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Compression-Stream-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.compression/documentation/Compression/compression_stream/dst_size",
                "doc://com.apple.compression/documentation/Compression/compression_stream/src_ptr",
                "doc://com.apple.compression/documentation/Compression/compression_stream/src_size",
                "doc://com.apple.compression/documentation/Compression/compression_stream/state"
              ],
              "title": "Compression Stream Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "dst_ptr"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream~1src_ptr/title",
          "value": "src_ptr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream~1src_ptr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "src_ptr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream~1dst_size/title",
          "value": "dst_size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream~1dst_size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dst_size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream~1dst_ptr/title",
          "value": "dst_ptr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream~1dst_ptr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dst_ptr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream/title",
          "value": "compression_stream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_stream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "compression_stream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream~1state/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream~1state/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream~1src_size/title",
          "value": "src_size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compression~1documentation~1Compression~1compression_stream~1src_size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "src_size"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compression/compression_stream/dst_ptr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/compression/compression_stream/dst_ptr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
