{
  "abstract": [
    {
      "text": "SOCKS4 subdomain response codes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/1518284-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/1518276-anonymous": {
      "abstract": [
        {
          "text": "SOCKS subdomain error codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/1518276-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/cfnetwork/1518276-anonymous"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/1518287-anonymous": {
      "abstract": [
        {
          "text": "SOCKS error codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/1518287-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/cfnetwork/1518287-anonymous"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-enumerations": {
      "abstract": [
        {
          "text": "Enumerated values related to SOCKS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CFNetwork Enumerations",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetwork-enumerations"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4IdConflict": {
      "abstract": [
        {
          "text": "Request rejected by the server because the client program and the ",
          "type": "text"
        },
        {
          "code": "identd",
          "type": "codeVoice"
        },
        {
          "text": " daemon reported different user IDs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4IdConflict"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4IdConflict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4IdConflict"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS4IdConflict",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks4idconflict"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4IdentdFailed": {
      "abstract": [
        {
          "text": "Request rejected by the server because it couldn’t connect to the ",
          "type": "text"
        },
        {
          "code": "identd",
          "type": "codeVoice"
        },
        {
          "text": " daemon on the client.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4IdentdFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4IdentdFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4IdentdFailed"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS4IdentdFailed",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks4identdfailed"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4RequestFailed": {
      "abstract": [
        {
          "text": "Request rejected by the server or request failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4RequestFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4RequestFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4RequestFailed"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS4RequestFailed",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks4requestfailed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/1518287-anonymous",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/1518276-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4IdConflict",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4IdentdFailed",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4RequestFailed"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4RequestFailed/title",
          "value": "kCFStreamErrorSOCKS4RequestFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4RequestFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS4RequestFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4IdentdFailed/title",
          "value": "kCFStreamErrorSOCKS4IdentdFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4IdentdFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS4IdentdFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4IdConflict/title",
          "value": "kCFStreamErrorSOCKS4IdConflict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4IdConflict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS4IdConflict"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/1518284-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
