{
  "abstract": [
    {
      "text": "SOCKS error codes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/1518287-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/1518276-anonymous": {
      "abstract": [
        {
          "text": "SOCKS subdomain error codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/1518276-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/cfnetwork/1518276-anonymous"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/1518284-anonymous": {
      "abstract": [
        {
          "text": "SOCKS4 subdomain response codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/1518284-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/cfnetwork/1518284-anonymous"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-enumerations": {
      "abstract": [
        {
          "text": "Enumerated values related to SOCKS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CFNetwork Enumerations",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetwork-enumerations"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4SubDomainResponse": {
      "abstract": [
        {
          "text": "The SOCKS4 status code returned by the server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4SubDomainResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4SubDomainResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4SubDomainResponse"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS4SubDomainResponse",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks4subdomainresponse"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainMethod": {
      "abstract": [
        {
          "text": "The server’s desired negotiation method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5SubDomainMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5SubDomainMethod"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS5SubDomainMethod",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks5subdomainmethod"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainResponse": {
      "abstract": [
        {
          "text": "The response code that the server returned in reply to the connection request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5SubDomainResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5SubDomainResponse"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS5SubDomainResponse",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks5subdomainresponse"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainUserPass": {
      "abstract": [
        {
          "text": "The status code that the server returned during authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5SubDomainUserPass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainUserPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5SubDomainUserPass"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS5SubDomainUserPass",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks5subdomainuserpass"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSSubDomainNone": {
      "abstract": [
        {
          "text": "A general SOCKS error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKSSubDomainNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSSubDomainNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKSSubDomainNone"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKSSubDomainNone",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsockssubdomainnone"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSSubDomainVersionCode": {
      "abstract": [
        {
          "text": "The version of SOCKS that the server wants to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKSSubDomainVersionCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSSubDomainVersionCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKSSubDomainVersionCode"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKSSubDomainVersionCode",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsockssubdomainversioncode"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/1518276-anonymous",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/1518284-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4SubDomainResponse",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainMethod",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainResponse",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainUserPass",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSSubDomainNone",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSSubDomainVersionCode"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4SubDomainResponse/title",
          "value": "kCFStreamErrorSOCKS4SubDomainResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4SubDomainResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS4SubDomainResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKSSubDomainNone/title",
          "value": "kCFStreamErrorSOCKSSubDomainNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKSSubDomainNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKSSubDomainNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5SubDomainUserPass/title",
          "value": "kCFStreamErrorSOCKS5SubDomainUserPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5SubDomainUserPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS5SubDomainUserPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKSSubDomainVersionCode/title",
          "value": "kCFStreamErrorSOCKSSubDomainVersionCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKSSubDomainVersionCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKSSubDomainVersionCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5SubDomainMethod/title",
          "value": "kCFStreamErrorSOCKS5SubDomainMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5SubDomainMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS5SubDomainMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5SubDomainResponse/title",
          "value": "kCFStreamErrorSOCKS5SubDomainResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5SubDomainResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS5SubDomainResponse"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/1518287-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
