{
  "abstract": [
    {
      "text": "Associates a client context and a callback function with a CFHost object or disassociates a client context and callback function that were previously set.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use Network framework instead, see deprecation notice in <CFNetwork/CFHost.h>",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostSetClient(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CFHostSetClient",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CFHostSetClient"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFHostRef",
        "text": "CFHost"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFHostClientCallBack",
        "text": "CFHostClientCallBack"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CFHostClientContext",
        "text": "CFHostClientContext"
      },
      {
        "kind": "text",
        "text": ">?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CFHostSetClient"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "2.0",
        "message": "Use Network framework instead, see deprecation notice in <CFNetwork/CFHost.h>",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "2.0",
        "message": "Use Network framework instead, see deprecation notice in <CFNetwork/CFHost.h>",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "message": "Use Network framework instead, see deprecation notice in <CFNetwork/CFHost.h>",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.3",
        "message": "Use Network framework instead, see deprecation notice in <CFNetwork/CFHost.h>",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "message": "Use Network framework instead, see deprecation notice in <CFNetwork/CFHost.h>",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Use Network framework instead, see deprecation notice in <CFNetwork/CFHost.h>",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CFHostSetClient(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CFHostSetClient"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "theHost"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHost",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFHostRef",
              "text": "CFHost"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "clientCB"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientCallBack",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFHostClientCallBack",
              "text": "CFHostClientCallBack"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "clientContext"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CFHostClientContext",
              "text": "CFHostClientContext"
            },
            {
              "kind": "text",
              "text": ">?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The host to modify. The value must not be ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "theHost"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The callback function to associate with ",
                  "type": "text"
                },
                {
                  "code": "theHost",
                  "type": "codeVoice"
                },
                {
                  "text": ". The callback function will be called when a resolution completes or is cancelled. If you are calling this function to disassociate a client context and callback from ",
                  "type": "text"
                },
                {
                  "code": "theHost",
                  "type": "codeVoice"
                },
                {
                  "text": ", p",
                  "type": "text"
                },
                {
                  "code": "clientCB",
                  "type": "codeVoice"
                },
                {
                  "text": "ass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "clientCB"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " structure whose ",
                  "type": "text"
                },
                {
                  "code": "info",
                  "type": "codeVoice"
                },
                {
                  "text": " field will be passed to the callback function specified by ",
                  "type": "text"
                },
                {
                  "code": "clientCB",
                  "type": "codeVoice"
                },
                {
                  "text": " when ",
                  "type": "text"
                },
                {
                  "code": "clientCB",
                  "type": "codeVoice"
                },
                {
                  "text": " is called. This value must not be ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " when setting an association.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " when disassociating a client context and a callback from a host.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "clientContext"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "code": "TRUE",
              "type": "codeVoice"
            },
            {
              "text": " if the association could be set or unset, otherwise ",
              "type": "text"
            },
            {
              "code": "FALSE",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The callback function specified by ",
              "type": "text"
            },
            {
              "code": "clientCB",
              "type": "codeVoice"
            },
            {
              "text": " will be called when a resolution completes or is cancelled.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Special-Considerations",
          "level": 3,
          "text": "Special Considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function is thread safe.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHost": {
      "abstract": [
        {
          "text": "An opaque reference representing an CFHost object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHost"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHost"
        }
      ],
      "role": "symbol",
      "title": "CFHost",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhost"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCancelInfoResolution(_:_:)": {
      "abstract": [
        {
          "text": "Cancels the resolution of a host.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostCancelInfoResolution"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHostRef",
          "text": "CFHost"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CFHostInfoType",
          "text": "CFHostInfoType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCancelInfoResolution(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostCancelInfoResolution"
        }
      ],
      "role": "symbol",
      "title": "CFHostCancelInfoResolution(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostcancelinforesolution(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientCallBack": {
      "abstract": [
        {
          "text": "Defines a pointer to the callback function that is called when an asynchronous resolution of a CFHost completes or an error occurs for an asynchronous CFHost resolution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostClientCallBack"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostClientCallBack"
        }
      ],
      "role": "symbol",
      "title": "CFHostClientCallBack",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostclientcallback"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext": {
      "abstract": [
        {
          "text": "A structure containing user-defined data and callbacks for CFHost objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostClientContext"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostClientContext"
        }
      ],
      "role": "symbol",
      "title": "CFHostClientContext",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostclientcontext"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCreateCopy(_:_:)": {
      "abstract": [
        {
          "text": "Creates a new host object by copying.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostCreateCopy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHostRef",
          "text": "CFHost"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHostRef",
          "text": "CFHost"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCreateCopy(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostCreateCopy"
        }
      ],
      "role": "symbol",
      "title": "CFHostCreateCopy(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostcreatecopy(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCreateWithAddress(_:_:)": {
      "abstract": [
        {
          "text": "Uses an address to create an instance of a host object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostCreateWithAddress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHostRef",
          "text": "CFHost"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCreateWithAddress(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostCreateWithAddress"
        }
      ],
      "role": "symbol",
      "title": "CFHostCreateWithAddress(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostcreatewithaddress(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCreateWithName(_:_:)": {
      "abstract": [
        {
          "text": "Uses a name to create an instance of a host object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostCreateWithName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHostRef",
          "text": "CFHost"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCreateWithName(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostCreateWithName"
        }
      ],
      "role": "symbol",
      "title": "CFHostCreateWithName(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostcreatewithname(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetAddressing(_:_:)": {
      "abstract": [
        {
          "text": "Gets the addresses from a host.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostGetAddressing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHostRef",
          "text": "CFHost"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetAddressing(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostGetAddressing"
        }
      ],
      "role": "symbol",
      "title": "CFHostGetAddressing(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostgetaddressing(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetNames(_:_:)": {
      "abstract": [
        {
          "text": "Gets the names from a CFHost.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostGetNames"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHostRef",
          "text": "CFHost"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetNames(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostGetNames"
        }
      ],
      "role": "symbol",
      "title": "CFHostGetNames(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostgetnames(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetReachability(_:_:)": {
      "abstract": [
        {
          "text": "Gets reachability information from a host.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostGetReachability"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHostRef",
          "text": "CFHost"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetReachability(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostGetReachability"
        }
      ],
      "role": "symbol",
      "title": "CFHostGetReachability(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostgetreachability(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetTypeID()": {
      "abstract": [
        {
          "text": "Gets the Core Foundation type identifier for the CFHost opaque type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CFHostGetTypeID()",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostgettypeid()"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostInfoType": {
      "abstract": [
        {
          "text": "Values indicating the type of data that is to be resolved or the type of data that was resolved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostInfoType"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostInfoType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostInfoType"
        }
      ],
      "role": "symbol",
      "title": "CFHostInfoType",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostinfotype"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostScheduleWithRunLoop(_:_:_:)": {
      "abstract": [
        {
          "text": "Schedules a CFHost on a run loop.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostScheduleWithRunLoop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHostRef",
          "text": "CFHost"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopRef",
          "text": "CFRunLoop"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostScheduleWithRunLoop(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostScheduleWithRunLoop"
        }
      ],
      "role": "symbol",
      "title": "CFHostScheduleWithRunLoop(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostschedulewithrunloop(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostSetClient(_:_:_:)": {
      "abstract": [
        {
          "text": "Associates a client context and a callback function with a CFHost object or disassociates a client context and callback function that were previously set.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostSetClient"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHostRef",
          "text": "CFHost"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHostClientCallBack",
          "text": "CFHostClientCallBack"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CFHostClientContext",
          "text": "CFHostClientContext"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostSetClient(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostSetClient"
        }
      ],
      "role": "symbol",
      "title": "CFHostSetClient(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostsetclient(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostStartInfoResolution(_:_:_:)": {
      "abstract": [
        {
          "text": "Starts resolution for a host object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostStartInfoResolution"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHostRef",
          "text": "CFHost"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CFHostInfoType",
          "text": "CFHostInfoType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostStartInfoResolution(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostStartInfoResolution"
        }
      ],
      "role": "symbol",
      "title": "CFHostStartInfoResolution(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhoststartinforesolution(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostUnscheduleFromRunLoop(_:_:_:)": {
      "abstract": [
        {
          "text": "Unschedules a CFHost from a run loop.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostUnscheduleFromRunLoop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHostRef",
          "text": "CFHost"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopRef",
          "text": "CFRunLoop"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostUnscheduleFromRunLoop(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostUnscheduleFromRunLoop"
        }
      ],
      "role": "symbol",
      "title": "CFHostUnscheduleFromRunLoop(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostunschedulefromrunloop(_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Hosts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHost",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostInfoType",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCancelInfoResolution(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCreateCopy(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCreateWithAddress(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCreateWithName(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetAddressing(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetNames(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetReachability(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetTypeID()",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostScheduleWithRunLoop(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostStartInfoResolution(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostUnscheduleFromRunLoop(_:_:_:)"
      ],
      "title": "Hosts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CFHostSetClient"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostSetClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Hosts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHost",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostInfoType",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCancelInfoResolution(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCreateCopy(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCreateWithAddress(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostCreateWithName(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetAddressing(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetNames(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetReachability(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostGetTypeID()",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostScheduleWithRunLoop(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostStartInfoResolution(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostUnscheduleFromRunLoop(_:_:_:)"
              ],
              "title": "Hosts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@Boolean",
                    "text": "Boolean"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CFHostSetClient"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHost",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFHostRef",
                    "text": "CFHostRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "theHost"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientCallBack",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFHostClientCallBack",
                    "text": "CFHostClientCallBack"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "clientCB"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CFHostClientContext",
                    "text": "CFHostClientContext"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "clientContext"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The host to modify. The value must not be ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "theHost"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The callback function to associate with ",
                        "type": "text"
                      },
                      {
                        "code": "theHost",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". The callback function will be called when a resolution completes or is cancelled. If you are calling this function to disassociate a client context and callback from ",
                        "type": "text"
                      },
                      {
                        "code": "theHost",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", p",
                        "type": "text"
                      },
                      {
                        "code": "clientCB",
                        "type": "codeVoice"
                      },
                      {
                        "text": "ass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "clientCB"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " structure whose ",
                        "type": "text"
                      },
                      {
                        "code": "info",
                        "type": "codeVoice"
                      },
                      {
                        "text": " field will be passed to the callback function specified by ",
                        "type": "text"
                      },
                      {
                        "code": "clientCB",
                        "type": "codeVoice"
                      },
                      {
                        "text": " when ",
                        "type": "text"
                      },
                      {
                        "code": "clientCB",
                        "type": "codeVoice"
                      },
                      {
                        "text": " is called. This value must not be ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " when setting an association.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "Pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " when disassociating a client context and a callback from a host.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "clientContext"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "code": "TRUE",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if the association could be set or unset, otherwise ",
                    "type": "text"
                  },
                  {
                    "code": "FALSE",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use Network framework instead, see deprecation notice in <CFNetwork/CFHost.h>",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext/title",
          "value": "CFHostClientContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostClientContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostClientContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHost/title",
          "value": "CFHostRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHost/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostGetAddressing(_:_:)/title",
          "value": "CFHostGetAddressing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostGetAddressing(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostGetAddressing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostStartInfoResolution(_:_:_:)/title",
          "value": "CFHostStartInfoResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostStartInfoResolution(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostStartInfoResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostCreateWithName(_:_:)/title",
          "value": "CFHostCreateWithName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostCreateWithName(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostCreateWithName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientCallBack/title",
          "value": "CFHostClientCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientCallBack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostSetClient(_:_:_:)/title",
          "value": "CFHostSetClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostSetClient(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostSetClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostScheduleWithRunLoop(_:_:_:)/title",
          "value": "CFHostScheduleWithRunLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostScheduleWithRunLoop(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostScheduleWithRunLoop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostCreateWithAddress(_:_:)/title",
          "value": "CFHostCreateWithAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostCreateWithAddress(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostCreateWithAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostInfoType/title",
          "value": "CFHostInfoType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostInfoType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostInfoType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostInfoType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostInfoType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostGetTypeID()/title",
          "value": "CFHostGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostCancelInfoResolution(_:_:)/title",
          "value": "CFHostCancelInfoResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostCancelInfoResolution(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostCancelInfoResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostGetReachability(_:_:)/title",
          "value": "CFHostGetReachability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostGetReachability(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostGetReachability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostGetNames(_:_:)/title",
          "value": "CFHostGetNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostGetNames(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostGetNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostCreateCopy(_:_:)/title",
          "value": "CFHostCreateCopy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostCreateCopy(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostCreateCopy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostUnscheduleFromRunLoop(_:_:_:)/title",
          "value": "CFHostUnscheduleFromRunLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostUnscheduleFromRunLoop(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostUnscheduleFromRunLoop"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfhostsetclient(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfhostsetclient(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
