{
  "abstract": [
    {
      "text": "Uses an authentication failure response to create a CFHTTPAuthentication object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCreateFromResponse(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CFHTTPAuthenticationCreateFromResponse",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CFHTTPAuthenticationCreateFromResponse"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFAllocatorRef",
        "text": "CFAllocator"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFHTTPMessageRef",
        "text": "CFHTTPMessage"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
        "text": "CFHTTPAuthentication"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CFHTTPAuthenticationCreateFromResponse"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CFHTTPAuthenticationCreateFromResponse(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationCreateFromResponse"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "alloc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFAllocatorRef",
              "text": "CFAllocator"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "response"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFHTTPMessageRef",
              "text": "CFHTTPMessage"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthentication",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
              "text": "CFHTTPAuthentication"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The allocator to use to allocate memory for the new object. Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " or kCFAllocatorDefault to use the current default allocator.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "alloc"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Response indicating an authentication failure; usually a 401 or a 407 response.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "response"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "CFHTTPAuthentication object that can be used for adding credentials to future requests. Ownership follows the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function uses a response containing authentication failure information to create a reference to a CFHTTPAuthentication object. You can use the object to add credentials to future requests. You can query the object to get the following information:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "whether it can be used and re-used to authenticate with its corresponding server [",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationIsValid(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "]",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "the authentication method that will be used when it is used to perform an authentication [",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyMethod(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "]",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "whether it is associated with a particular CFHTTPMessageRef [",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationAppliesToRequest(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "whether a user name and a password will be required when it is used to perform an authentication [",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresUserNameAndPassword(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "]",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "whether an account domain will be required when it is used to perform an authentication [",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresAccountDomain(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "]",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "whether authentication requests should be sent one at a time to the corresponding server [",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresOrderedRequests(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "]",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "the namespace (if any) that the domain uses to prompt for a name and password [",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyRealm(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "]",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "the domain URLs the instance applies to [",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyDomains(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "]",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When you have determined what information will be needed to perform the authentication and accumulated that information, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageApplyCredentials(_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageApplyCredentialDictionary(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to perform the authentication.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthentication": {
      "abstract": [
        {
          "text": "An opaque reference representing HTTP authentication information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthentication"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthentication"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthentication",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthentication"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationAppliesToRequest(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a CFHTTPAuthentication object is associated with a CFHTTPMessage object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationAppliesToRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationAppliesToRequest(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationAppliesToRequest"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationAppliesToRequest(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationappliestorequest(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyDomains(_:)": {
      "abstract": [
        {
          "text": "Returns an array of domain URLs to which a given CFHTTPAuthentication object can be applied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCopyDomains"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyDomains(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCopyDomains"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationCopyDomains(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationcopydomains(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyMethod(_:)": {
      "abstract": [
        {
          "text": "Gets the strongest authentication method that will be used when a CFHTTPAuthentication object is applied to a request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCopyMethod"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyMethod(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCopyMethod"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationCopyMethod(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationcopymethod(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyRealm(_:)": {
      "abstract": [
        {
          "text": "Gets an authentication information’s namespace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCopyRealm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyRealm(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCopyRealm"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationCopyRealm(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationcopyrealm(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCreateFromResponse(_:_:)": {
      "abstract": [
        {
          "text": "Uses an authentication failure response to create a CFHTTPAuthentication object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCreateFromResponse"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCreateFromResponse(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCreateFromResponse"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationCreateFromResponse(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationcreatefromresponse(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationGetTypeID()": {
      "abstract": [
        {
          "text": "Gets the Core Foundation type identifier for the CFHTTPAuthentication opaque type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationGetTypeID()",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationgettypeid()"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationIsValid(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a CFHTTPAuthentication object is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationIsValid"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationIsValid(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationIsValid"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationIsValid(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationisvalid(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresAccountDomain(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a CFHTTPAuthentication object uses an authentication method that requires an account domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationRequiresAccountDomain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresAccountDomain(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationRequiresAccountDomain"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationRequiresAccountDomain(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationrequiresaccountdomain(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresOrderedRequests(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether authentication requests should be made one at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationRequiresOrderedRequests"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresOrderedRequests(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationRequiresOrderedRequests"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationRequiresOrderedRequests(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationrequiresorderedrequests(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresUserNameAndPassword(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a CFHTTPAuthentication object uses an authentication method that requires a username and a password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationRequiresUserNameAndPassword"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresUserNameAndPassword(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationRequiresUserNameAndPassword"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationRequiresUserNameAndPassword(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationrequiresusernameandpassword(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessage": {
      "abstract": [
        {
          "text": "An opaque reference representing an HTTP message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessage"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessage"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessage",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessage"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageApplyCredentialDictionary(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Use a dictionary containing authentication credentials to perform the authentication method specified by a ",
          "type": "text"
        },
        {
          "code": "CFHTTPAuthentication",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageApplyCredentialDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageApplyCredentialDictionary(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageApplyCredentialDictionary"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageApplyCredentialDictionary(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessageapplycredentialdictionary(_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageApplyCredentials(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Performs the authentication method specified by a ",
          "type": "text"
        },
        {
          "code": "CFHTTPAuthentication",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageApplyCredentials"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageApplyCredentials(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageApplyCredentials"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageApplyCredentials(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessageapplycredentials(_:_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationAccountDomain": {
      "abstract": [
        {
          "text": "Account domain to use for authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationAccountDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationAccountDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationAccountDomain"
        }
      ],
      "role": "symbol",
      "title": "kCFHTTPAuthenticationAccountDomain",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfhttpauthenticationaccountdomain"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationPassword": {
      "abstract": [
        {
          "text": "Password to use for authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationPassword",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationPassword"
        }
      ],
      "role": "symbol",
      "title": "kCFHTTPAuthenticationPassword",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfhttpauthenticationpassword"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeBasic": {
      "abstract": [
        {
          "text": "Request the HTTP basic authentication scheme.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationSchemeBasic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeBasic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationSchemeBasic"
        }
      ],
      "role": "symbol",
      "title": "kCFHTTPAuthenticationSchemeBasic",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfhttpauthenticationschemebasic"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeDigest": {
      "abstract": [
        {
          "text": "Request the HTTP digest authentication scheme.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationSchemeDigest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeDigest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationSchemeDigest"
        }
      ],
      "role": "symbol",
      "title": "kCFHTTPAuthenticationSchemeDigest",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfhttpauthenticationschemedigest"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeKerberos": {
      "abstract": [
        {
          "text": "Request the HTTP Kerberos authentication scheme.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationSchemeKerberos"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeKerberos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationSchemeKerberos"
        }
      ],
      "role": "symbol",
      "title": "kCFHTTPAuthenticationSchemeKerberos",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfhttpauthenticationschemekerberos"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef": {
      "abstract": [
        {
          "text": "A reference to a CFAllocator object. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFAllocator"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocator",
      "type": "topic",
      "url": "/documentation/corefoundation/cfallocator"
    },
    "doc://com.externally.resolved.symbol/s:s9UnmanagedV": {
      "abstract": [
        {
          "text": "A type for propagating an unmanaged object reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Unmanaged",
      "type": "topic",
      "url": "/documentation/Swift/Unmanaged"
    },
    "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029": {
      "identifier": "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029",
      "title": "The Create Rule",
      "titleInlineContent": [
        {
          "text": "The Create Rule",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "HTTP-Authentication",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthentication",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationAppliesToRequest(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyDomains(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyMethod(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyRealm(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationGetTypeID()",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationIsValid(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresAccountDomain(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresOrderedRequests(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresUserNameAndPassword(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationAccountDomain",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationPassword",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeBasic",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeDigest",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeKerberos"
      ],
      "title": "HTTP Authentication"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CFHTTPAuthenticationCreateFromResponse"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationCreateFromResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "HTTP-Authentication",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthentication",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationAppliesToRequest(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyDomains(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyMethod(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyRealm(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationGetTypeID()",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationIsValid(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresAccountDomain(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresOrderedRequests(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresUserNameAndPassword(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationAccountDomain",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationPassword",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeBasic",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeDigest",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeKerberos"
              ],
              "title": "HTTP Authentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthentication",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
                    "text": "CFHTTPAuthenticationRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CFHTTPAuthenticationCreateFromResponse"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFAllocatorRef",
                    "text": "CFAllocatorRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "alloc"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFHTTPMessageRef",
                    "text": "CFHTTPMessageRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "response"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The allocator to use to allocate memory for the new object. Pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " or kCFAllocatorDefault to use the current default allocator.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "alloc"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Response indicating an authentication failure; usually a 401 or a 407 response.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "response"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "CFHTTPAuthentication object that can be used for adding credentials to future requests. Ownership follows the ",
                    "type": "text"
                  },
                  {
                    "identifier": "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationGetTypeID()/title",
          "value": "CFHTTPAuthenticationGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationSchemeKerberos/title",
          "value": "kCFHTTPAuthenticationSchemeKerberos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationSchemeKerberos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHTTPAuthenticationSchemeKerberos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationRequiresUserNameAndPassword(_:)/title",
          "value": "CFHTTPAuthenticationRequiresUserNameAndPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationRequiresUserNameAndPassword(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationRequiresUserNameAndPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationRequiresAccountDomain(_:)/title",
          "value": "CFHTTPAuthenticationRequiresAccountDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationRequiresAccountDomain(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationRequiresAccountDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationPassword/title",
          "value": "kCFHTTPAuthenticationPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationPassword/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHTTPAuthenticationPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationSchemeBasic/title",
          "value": "kCFHTTPAuthenticationSchemeBasic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationSchemeBasic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHTTPAuthenticationSchemeBasic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthentication/title",
          "value": "CFHTTPAuthenticationRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthentication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCopyMethod(_:)/title",
          "value": "CFHTTPAuthenticationCopyMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCopyMethod(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationCopyMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationAccountDomain/title",
          "value": "kCFHTTPAuthenticationAccountDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationAccountDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHTTPAuthenticationAccountDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessage/title",
          "value": "CFHTTPMessageRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCopyRealm(_:)/title",
          "value": "CFHTTPAuthenticationCopyRealm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCopyRealm(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationCopyRealm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageApplyCredentials(_:_:_:_:_:)/title",
          "value": "CFHTTPMessageApplyCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageApplyCredentials(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageApplyCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationSchemeDigest/title",
          "value": "kCFHTTPAuthenticationSchemeDigest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationSchemeDigest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHTTPAuthenticationSchemeDigest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationRequiresOrderedRequests(_:)/title",
          "value": "CFHTTPAuthenticationRequiresOrderedRequests"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationRequiresOrderedRequests(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationRequiresOrderedRequests"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationAppliesToRequest(_:_:)/title",
          "value": "CFHTTPAuthenticationAppliesToRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationAppliesToRequest(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationAppliesToRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageApplyCredentialDictionary(_:_:_:_:)/title",
          "value": "CFHTTPMessageApplyCredentialDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageApplyCredentialDictionary(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageApplyCredentialDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCreateFromResponse(_:_:)/title",
          "value": "CFHTTPAuthenticationCreateFromResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCreateFromResponse(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationCreateFromResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFAllocatorRef/title",
          "value": "CFAllocatorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationIsValid(_:_:)/title",
          "value": "CFHTTPAuthenticationIsValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationIsValid(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationIsValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCopyDomains(_:)/title",
          "value": "CFHTTPAuthenticationCopyDomains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCopyDomains(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationCopyDomains"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfhttpauthenticationcreatefromresponse(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfhttpauthenticationcreatefromresponse(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
