{
  "abstract": [
    {
      "text": "Constants for diagnostic status values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CFNetDiagnosticStatusValues",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CFNetDiagnosticStatusValues"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CFNetDiagnosticStatusValues"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.13",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CFNetDiagnosticStatusValues"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticStatusValues"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Diagnostic status values are returned by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticDiagnoseProblemInteractively(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCopyNetworkStatusPassively(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnostic": {
      "abstract": [
        {
          "text": "An opaque reference representing a CFNetDiagnostic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnostic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnostic"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnostic",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnostic"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCopyNetworkStatusPassively(_:_:)": {
      "abstract": [
        {
          "text": "Gets a network status value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticCopyNetworkStatusPassively"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetDiagnosticRef",
          "text": "CFNetDiagnostic"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetDiagnosticStatus",
          "text": "CFNetDiagnosticStatus"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCopyNetworkStatusPassively(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticCopyNetworkStatusPassively"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticCopyNetworkStatusPassively(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticcopynetworkstatuspassively(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCreateWithStreams(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a network diagnostic object from a pair of CFStreams.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticCreateWithStreams"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFReadStreamRef",
          "text": "CFReadStream"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFWriteStreamRef",
          "text": "CFWriteStream"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetDiagnosticRef",
          "text": "CFNetDiagnostic"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCreateWithStreams(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticCreateWithStreams"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticCreateWithStreams(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticcreatewithstreams(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCreateWithURL(_:_:)": {
      "abstract": [
        {
          "text": "Creates a CFNetDiagnosticRef from a CFURLRef.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticCreateWithURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetDiagnosticRef",
          "text": "CFNetDiagnostic"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCreateWithURL(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticCreateWithURL"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticCreateWithURL(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticcreatewithurl(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticDiagnoseProblemInteractively(_:)": {
      "abstract": [
        {
          "text": "Opens a Network Diagnostics window.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticDiagnoseProblemInteractively"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetDiagnosticRef",
          "text": "CFNetDiagnostic"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetDiagnosticStatus",
          "text": "CFNetDiagnosticStatus"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticDiagnoseProblemInteractively(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticDiagnoseProblemInteractively"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticDiagnoseProblemInteractively(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticdiagnoseprobleminteractively(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticSetName(_:_:)": {
      "abstract": [
        {
          "text": "Overrides the displayed application name.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticSetName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetDiagnosticRef",
          "text": "CFNetDiagnostic"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticSetName(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticSetName"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticSetName(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticsetname(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues": {
      "abstract": [
        {
          "text": "Constants for diagnostic status values.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticStatusValues"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticStatusValues"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticStatusValues",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticstatusvalues"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/connectionDown": {
      "abstract": [
        {
          "text": "The connection does not appear to be working.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionDown"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/connectionDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetDiagnosticConnectionDown"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticStatusValues.connectionDown",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticstatusvalues/connectiondown"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/connectionIndeterminate": {
      "abstract": [
        {
          "text": "The status of the connection is not known.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionIndeterminate"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/connectionIndeterminate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetDiagnosticConnectionIndeterminate"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticStatusValues.connectionIndeterminate",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticstatusvalues/connectionindeterminate"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/connectionUp": {
      "abstract": [
        {
          "text": "The connection appears to be working.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionUp"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/connectionUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetDiagnosticConnectionUp"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticStatusValues.connectionUp",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticstatusvalues/connectionup"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/err": {
      "abstract": [
        {
          "text": "An error occurred that prevented the call from completing.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "err"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/err",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetDiagnosticErr"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticStatusValues.err",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticstatusvalues/err"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticstatusvalues/init(rawvalue:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/noErr": {
      "abstract": [
        {
          "text": "No error occurred but there is no status.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noErr"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/noErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetDiagnosticNoErr"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticStatusValues.noErr",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticstatusvalues/noerr"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Network-Diagnostics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnostic",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCopyNetworkStatusPassively(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCreateWithStreams(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCreateWithURL(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticDiagnoseProblemInteractively(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticSetName(_:_:)"
      ],
      "title": "Network Diagnostics"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/noErr",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/err",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/connectionUp",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/connectionIndeterminate",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/connectionDown"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.13",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CFNetDiagnosticStatusValues"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticStatusValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticStatusValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/noErr",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/err",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/connectionUp",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/connectionIndeterminate",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues/connectionDown"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Network-Diagnostics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnostic",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCopyNetworkStatusPassively(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCreateWithStreams(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCreateWithURL(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticDiagnoseProblemInteractively(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticSetName(_:_:)"
              ],
              "title": "Network Diagnostics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CFNetDiagnosticStatusValues"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:I",
                    "text": "int"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticCreateWithStreams(_:_:_:)/title",
          "value": "CFNetDiagnosticCreateWithStreams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticCreateWithStreams(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticCreateWithStreams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues~1connectionIndeterminate/title",
          "value": "kCFNetDiagnosticConnectionIndeterminate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues~1connectionIndeterminate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetDiagnosticConnectionIndeterminate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticCopyNetworkStatusPassively(_:_:)/title",
          "value": "CFNetDiagnosticCopyNetworkStatusPassively"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticCopyNetworkStatusPassively(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticCopyNetworkStatusPassively"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnostic/title",
          "value": "CFNetDiagnosticRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnostic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnostic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues~1connectionUp/title",
          "value": "kCFNetDiagnosticConnectionUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues~1connectionUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetDiagnosticConnectionUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticCreateWithURL(_:_:)/title",
          "value": "CFNetDiagnosticCreateWithURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticCreateWithURL(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticCreateWithURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticDiagnoseProblemInteractively(_:)/title",
          "value": "CFNetDiagnosticDiagnoseProblemInteractively"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticDiagnoseProblemInteractively(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticDiagnoseProblemInteractively"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticSetName(_:_:)/title",
          "value": "CFNetDiagnosticSetName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticSetName(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticSetName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues/title",
          "value": "CFNetDiagnosticStatusValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticStatusValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticStatusValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues~1err/title",
          "value": "kCFNetDiagnosticErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues~1err/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetDiagnosticErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues~1connectionDown/title",
          "value": "kCFNetDiagnosticConnectionDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues~1connectionDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetDiagnosticConnectionDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues~1noErr/title",
          "value": "kCFNetDiagnosticNoErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues~1noErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetDiagnosticNoErr"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfnetdiagnosticstatusvalues"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfnetdiagnosticstatusvalues"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
