{
  "abstract": [
    {
      "text": "Defines a pointer to the callback function for a CFNetServiceBrowser.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserClientCallBack"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CFNetServiceBrowserClientCallBack",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CFNetServiceBrowserClientCallBack"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CFNetServiceBrowserClientCallBack"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CFNetServiceBrowserClientCallBack"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserClientCallBack"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowser",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
              "text": "CFNetServiceBrowser"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFOptionFlags",
              "text": "CFOptionFlags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeRef",
              "text": "CFTypeRef"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@CFStreamError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CFStreamError",
              "text": "CFStreamError"
            },
            {
              "kind": "text",
              "text": ">?, "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The CFNetServiceBrowser associated with this callback function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "browser"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Flags conveying additional information. The ",
                  "type": "text"
                },
                {
                  "code": "kCFNetServiceFlagIsDomain",
                  "type": "codeVoice"
                },
                {
                  "text": " bit is set if ",
                  "type": "text"
                },
                {
                  "code": "domainOrService",
                  "type": "codeVoice"
                },
                {
                  "text": " contains a domain; if this bit is not set, ",
                  "type": "text"
                },
                {
                  "code": "domainOrService",
                  "type": "codeVoice"
                },
                {
                  "text": " contains a CFNetService instance. For additional bit values, see ",
                  "type": "text"
                },
                {
                  "code": "CFNetServiceBrowserClientCallBack Bit Flags",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "flags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A string containing a domain name if this callback function is being called as a result of calling ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForDomains(_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", or a CFNetService instance if this callback function is being called as a result calling ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForServices(_:_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "domainOrService"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstreamerror",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " structure whose ",
                  "type": "text"
                },
                {
                  "code": "error",
                  "type": "codeVoice"
                },
                {
                  "text": " field may contain an error code.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "User-defined context information. The value of ",
                  "type": "text"
                },
                {
                  "code": "info",
                  "type": "codeVoice"
                },
                {
                  "text": " is the same as the value of the ",
                  "type": "text"
                },
                {
                  "code": "info",
                  "type": "codeVoice"
                },
                {
                  "text": " field of the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " structure that was provided when ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserCreate(_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " was called to create the CFNetServiceBrowser associated with this callback function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "info"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you name your callback ",
              "type": "text"
            },
            {
              "code": "MyNetServiceBrowserClientCallBack",
              "type": "codeVoice"
            },
            {
              "text": ", you would declare it like this:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Discussion",
          "level": 3,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The callback function for a CFNetServiceBrowser is called one or more times when domains or services are found as the result of calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForDomains(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForServices(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientCallBack": {
      "abstract": [
        {
          "text": "Defines a pointer to the callback function that is called when an asynchronous resolution of a CFHost completes or an error occurs for an asynchronous CFHost resolution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostClientCallBack"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostClientCallBack"
        }
      ],
      "role": "symbol",
      "title": "CFHostClientCallBack",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostclientcallback"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatus": {
      "abstract": [
        {
          "text": "A CFIndex type that is used to return status values from ",
          "type": "text"
        },
        {
          "code": "CFNetDiagnostic",
          "type": "codeVoice"
        },
        {
          "text": " status and diagnostic functions. For a list of possible values, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticStatus"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticStatus"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticStatus",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticstatus"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues": {
      "abstract": [
        {
          "text": "Constants for diagnostic status values.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticStatusValues"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticStatusValues"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticStatusValues",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticstatusvalues"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowser": {
      "abstract": [
        {
          "text": "An opaque reference representing a CFNetServiceBrowser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowser"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowser"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowser",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowser"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserClientCallBack": {
      "abstract": [
        {
          "text": "Defines a pointer to the callback function for a CFNetServiceBrowser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserClientCallBack"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserClientCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserClientCallBack"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserClientCallBack",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowserclientcallback"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserCreate(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an instance of a Network Service browser object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserClientCallBack",
          "text": "CFNetServiceBrowserClientCallBack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CFNetServiceClientContext",
          "text": "CFNetServiceClientContext"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserCreate(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserCreate"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserCreate(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowsercreate(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForDomains(_:_:_:)": {
      "abstract": [
        {
          "text": "Searches for domains.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserSearchForDomains"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForDomains(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserSearchForDomains"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserSearchForDomains(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowsersearchfordomains(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForServices(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Searches a domain for services of a specified type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserSearchForServices"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForServices(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserSearchForServices"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserSearchForServices(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowsersearchforservices(_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientCallBack": {
      "abstract": [
        {
          "text": "Defines a pointer to the callback function for a CFNetService.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceClientCallBack"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceClientCallBack"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceClientCallBack",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceclientcallback"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext": {
      "abstract": [
        {
          "text": "A structure provided when a CFNetService is associated with a callback function or when a CFNetServiceBrowser is created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceClientContext"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceClientContext"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceClientContext",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceclientcontext"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorClientCallBack": {
      "abstract": [
        {
          "text": "Defines a pointer to the callback function that is to be called when a monitored record type changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceMonitorClientCallBack"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorClientCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceMonitorClientCallBack"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceMonitorClientCallBack",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicemonitorclientcallback"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfstreamerror": {
      "abstract": [
        {
          "text": "The structure returned by  and .",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CFStreamError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstreamerror",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFStreamError",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstreamerror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@SA@CFStreamError": {
      "abstract": [
        {
          "text": "The structure returned by  and .",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CFStreamError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@CFStreamError",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFStreamError",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstreamerror"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags": {
      "abstract": [
        {
          "text": "A bitfield used for passing special allocation and other requests into Core Foundation functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFOptionFlags"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFOptionFlags",
      "type": "topic",
      "url": "/documentation/corefoundation/cfoptionflags"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFTypeRef": {
      "abstract": [
        {
          "text": "An untyped \"generic\" reference to any Core Foundation object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFTypeRef"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFTypeRef",
      "type": "topic",
      "url": "/documentation/corefoundation/cftyperef"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientCallBack",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientCallBack",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorClientCallBack",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatus"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CFNetServiceBrowserClientCallBack"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientCallBack",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientCallBack",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorClientCallBack",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatus"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:*Fv(#*$@S@__CFNetServiceBrowser#l#*1v#*$@SA@CFStreamError#*v)",
                    "text": "void (*)(struct __CFNetServiceBrowser *, unsigned long, const void *, CFStreamError *, void *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CFNetServiceBrowserClientCallBack"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowser/title",
          "value": "CFNetServiceBrowserRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserClientCallBack/title",
          "value": "CFNetServiceBrowserClientCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserClientCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserClientCallBack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserSearchForServices(_:_:_:_:)/title",
          "value": "CFNetServiceBrowserSearchForServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserSearchForServices(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserSearchForServices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues/title",
          "value": "CFNetDiagnosticStatusValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticStatusValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticStatusValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatus/title",
          "value": "CFNetDiagnosticStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserSearchForDomains(_:_:_:)/title",
          "value": "CFNetServiceBrowserSearchForDomains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserSearchForDomains(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserSearchForDomains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext/title",
          "value": "CFNetServiceClientContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceClientContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceClientContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientCallBack/title",
          "value": "CFNetServiceClientCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientCallBack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientCallBack/title",
          "value": "CFHostClientCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientCallBack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserCreate(_:_:_:)/title",
          "value": "CFNetServiceBrowserCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserCreate(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorClientCallBack/title",
          "value": "CFNetServiceMonitorClientCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorClientCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceMonitorClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorClientCallBack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceMonitorClientCallBack"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfnetservicebrowserclientcallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfnetservicebrowserclientcallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
