{
  "abstract": [
    {
      "text": "Constants for use with CFNetwork.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CFNetwork Constants"
  },
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFN_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CFN_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFN_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFN_EXPORT",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfn_export"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-data-types": {
      "abstract": [
        {
          "text": "Callback types for various network services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CFNetwork Data Types",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetwork-data-types"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-enumerations": {
      "abstract": [
        {
          "text": "Enumerated values related to SOCKS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CFNetwork Enumerations",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetwork-enumerations"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPVersion3_0": {
      "abstract": [
        {
          "text": "HTTP version 3.0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFHTTPVersion3_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPVersion3_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFHTTPVersion3_0"
        }
      ],
      "role": "symbol",
      "title": "kCFHTTPVersion3_0",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfhttpversion3_0"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeAVStreaming": {
      "abstract": [
        {
          "text": "A multimedia audio and video streaming service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamNetworkServiceTypeAVStreaming"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeAVStreaming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamNetworkServiceTypeAVStreaming"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamNetworkServiceTypeAVStreaming",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamnetworkservicetypeavstreaming"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveAV": {
      "abstract": [
        {
          "text": "A responsive, time-sensitive, multimedia audio and video service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamNetworkServiceTypeResponsiveAV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveAV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamNetworkServiceTypeResponsiveAV"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamNetworkServiceTypeResponsiveAV",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamnetworkservicetyperesponsiveav"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveData": {
      "abstract": [
        {
          "text": "A responsive, time-sensitive data service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamNetworkServiceTypeResponsiveData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamNetworkServiceTypeResponsiveData"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamNetworkServiceTypeResponsiveData",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamnetworkservicetyperesponsivedata"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyAllowConstrainedNetworkAccess": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether connections may use the network when the user has specified Low Data Mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyAllowConstrainedNetworkAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyAllowConstrainedNetworkAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyAllowConstrainedNetworkAccess"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyAllowConstrainedNetworkAccess",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyallowconstrainednetworkaccess"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyAllowExpensiveNetworkAccess": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether connections may use a network interface that the system considers expensive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyAllowExpensiveNetworkAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyAllowExpensiveNetworkAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyAllowExpensiveNetworkAccess"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyAllowExpensiveNetworkAccess",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyallowexpensivenetworkaccess"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyConnectionIsExpensive": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if the connection is using a network interface that the system considers expensive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyConnectionIsExpensive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyConnectionIsExpensive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyConnectionIsExpensive"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyConnectionIsExpensive",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyconnectionisexpensive"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-data-types",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPVersion3_0",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeAVStreaming",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveAV",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveData",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyAllowConstrainedNetworkAccess",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyAllowExpensiveNetworkAccess",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyConnectionIsExpensive"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPVersion3_0",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeAVStreaming",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveAV",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveData",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyAllowConstrainedNetworkAccess",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyAllowExpensiveNetworkAccess",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyConnectionIsExpensive"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFN_EXPORT"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-data-types",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamNetworkServiceTypeResponsiveData/title",
          "value": "kCFStreamNetworkServiceTypeResponsiveData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamNetworkServiceTypeResponsiveData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamNetworkServiceTypeResponsiveData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamNetworkServiceTypeResponsiveAV/title",
          "value": "kCFStreamNetworkServiceTypeResponsiveAV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamNetworkServiceTypeResponsiveAV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamNetworkServiceTypeResponsiveAV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyAllowExpensiveNetworkAccess/title",
          "value": "kCFStreamPropertyAllowExpensiveNetworkAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyAllowExpensiveNetworkAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyAllowExpensiveNetworkAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamNetworkServiceTypeAVStreaming/title",
          "value": "kCFStreamNetworkServiceTypeAVStreaming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamNetworkServiceTypeAVStreaming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamNetworkServiceTypeAVStreaming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyConnectionIsExpensive/title",
          "value": "kCFStreamPropertyConnectionIsExpensive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyConnectionIsExpensive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyConnectionIsExpensive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPVersion3_0/title",
          "value": "kCFHTTPVersion3_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPVersion3_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHTTPVersion3_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyAllowConstrainedNetworkAccess/title",
          "value": "kCFStreamPropertyAllowConstrainedNetworkAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyAllowConstrainedNetworkAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyAllowConstrainedNetworkAccess"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfnetwork-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfnetwork-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
