{
  "abstract": [
    {
      "text": "A structure provided when a CFNetService is associated with a callback function or when a CFNetServiceBrowser is created.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@CFNetServiceClientContext",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CFNetServiceClientContext"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CFNetServiceClientContext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CFNetServiceClientContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CFNetServiceClientContext"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetService": {
      "abstract": [
        {
          "text": "An opaque reference representing a CFNetService.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetService"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetService"
        }
      ],
      "role": "symbol",
      "title": "CFNetService",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservice"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowser": {
      "abstract": [
        {
          "text": "An opaque reference representing a CFNetServiceBrowser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowser"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowser"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowser",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowser"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserCreate(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an instance of a Network Service browser object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserClientCallBack",
          "text": "CFNetServiceBrowserClientCallBack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CFNetServiceClientContext",
          "text": "CFNetServiceClientContext"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserCreate(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserCreate"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserCreate(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowsercreate(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserFlags": {
      "abstract": [
        {
          "text": "Flags that the system passes to net service browser callbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserFlags"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserFlags"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserFlags",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowserflags"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserGetTypeID()": {
      "abstract": [
        {
          "text": "Gets the Core Foundation type identifier for the Network Service browser object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserGetTypeID()",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowsergettypeid()"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserInvalidate(_:)": {
      "abstract": [
        {
          "text": "Invalidates an instance of a Network Service browser object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserInvalidate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserInvalidate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserInvalidate"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserInvalidate(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowserinvalidate(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserScheduleWithRunLoop(_:_:_:)": {
      "abstract": [
        {
          "text": "Schedules a CFNetServiceBrowser on a run loop.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserScheduleWithRunLoop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopRef",
          "text": "CFRunLoop"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserScheduleWithRunLoop(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserScheduleWithRunLoop"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserScheduleWithRunLoop(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowserschedulewithrunloop(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForDomains(_:_:_:)": {
      "abstract": [
        {
          "text": "Searches for domains.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserSearchForDomains"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForDomains(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserSearchForDomains"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserSearchForDomains(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowsersearchfordomains(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForServices(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Searches a domain for services of a specified type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserSearchForServices"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForServices(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserSearchForServices"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserSearchForServices(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowsersearchforservices(_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserStopSearch(_:_:)": {
      "abstract": [
        {
          "text": "Stops a search for domains or services.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserStopSearch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserStopSearch(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserStopSearch"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserStopSearch(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowserstopsearch(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserUnscheduleFromRunLoop(_:_:_:)": {
      "abstract": [
        {
          "text": "Unschedules a CFNetServiceBrowser from a run loop and mode.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserUnscheduleFromRunLoop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopRef",
          "text": "CFRunLoop"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserUnscheduleFromRunLoop(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserUnscheduleFromRunLoop"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserUnscheduleFromRunLoop(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowserunschedulefromrunloop(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext": {
      "abstract": [
        {
          "text": "A structure provided when a CFNetService is associated with a callback function or when a CFNetServiceBrowser is created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceClientContext"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceClientContext"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceClientContext",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceclientcontext"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/copyDescription": {
      "abstract": [
        {
          "text": "Callback used to create a descriptive string representation of the data pointed to by ",
          "type": "text"
        },
        {
          "code": "info",
          "type": "codeVoice"
        },
        {
          "text": ". In implementing this function, return a reference to a CFString object that describes your allocator and some characteristics of your user-defined data, which is used by ",
          "type": "text"
        },
        {
          "code": "CFCopyDescription()",
          "type": "codeVoice"
        },
        {
          "text": ". You can set this field to ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ", in which case Core Foundation will provide a rudimentary description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorCopyDescriptionCallBack",
          "text": "CFAllocatorCopyDescriptionCallBack"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/copyDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "copyDescription"
        }
      ],
      "role": "symbol",
      "title": "copyDescription",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceclientcontext/copydescription"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/info": {
      "abstract": [
        {
          "text": "Arbitrary pointer to user-allocated memory containing user-defined data that is associated with the service, browser, or monitor and is passed to their respective callback functions. The data must be valid for as long as the CFNetService, CFNetServiceBrowser, or CFNetServiceMonitor is valid. Set this field to ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": " if your callback function doesn’t want to receive user-defined data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "info"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/info",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "info"
        }
      ],
      "role": "symbol",
      "title": "info",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceclientcontext/info"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/init()": {
      "abstract": [
        {
          "text": "Creates an object that contains user-defined data and callbacks for net service browsers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceclientcontext/init()"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/init(version:info:retain:release:copyDescription:)": {
      "abstract": [
        {
          "text": "Creates an object that contains user-defined data and callbacks for net service browsers using the specified values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "info"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "retain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRetainCallBack",
          "text": "CFAllocatorRetainCallBack"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "release"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorReleaseCallBack",
          "text": "CFAllocatorReleaseCallBack"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "copyDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorCopyDescriptionCallBack",
          "text": "CFAllocatorCopyDescriptionCallBack"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/init(version:info:retain:release:copyDescription:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(version:info:retain:release:copyDescription:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceclientcontext/init(version:info:retain:release:copydescription:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/release": {
      "abstract": [
        {
          "text": "Callback that removes a retain previously added for the service or browser on the ",
          "type": "text"
        },
        {
          "code": "info",
          "type": "codeVoice"
        },
        {
          "text": " pointer. This field can be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ", but setting this field to ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": " may result in memory leaks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "release"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorReleaseCallBack",
          "text": "CFAllocatorReleaseCallBack"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/release",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "release"
        }
      ],
      "role": "symbol",
      "title": "release",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceclientcontext/release"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/retain": {
      "abstract": [
        {
          "text": "The callback used to add a retain for the service or browser using ",
          "type": "text"
        },
        {
          "code": "info",
          "type": "codeVoice"
        },
        {
          "text": " for the life of the service or browser. This callback may be used for temporary references the service or browser needs to take. This callback returns the actual ",
          "type": "text"
        },
        {
          "code": "info",
          "type": "codeVoice"
        },
        {
          "text": " pointer so it can be stored in the service or browser. This field can be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "retain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRetainCallBack",
          "text": "CFAllocatorRetainCallBack"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/retain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "retain"
        }
      ],
      "role": "symbol",
      "title": "retain",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceclientcontext/retain"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/version": {
      "abstract": [
        {
          "text": "Version number for this structure. Currently the only valid value is zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceclientcontext/version"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitor": {
      "abstract": [
        {
          "text": "An opaque reference for a service monitor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceMonitor"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceMonitor"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceMonitor",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicemonitor"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorType": {
      "abstract": [
        {
          "text": "Record type specifier used to tell a service monitor the type of record changes to watch for.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceMonitorType"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceMonitorType"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceMonitorType",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicemonitortype"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceRegisterFlags": {
      "abstract": [
        {
          "text": "Options to use when registering a service on the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceRegisterFlags"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceRegisterFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceRegisterFlags"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceRegisterFlags",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceregisterflags"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError": {
      "abstract": [
        {
          "text": "Error codes that may be returned by CFNetServices functions or passed to CFNetServices callback functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServicesError"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServicesError"
        }
      ],
      "role": "symbol",
      "title": "CFNetServicesError",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceserror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Network-Services",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetService",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowser",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserFlags",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitor",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorType",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceRegisterFlags",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserInvalidate(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserScheduleWithRunLoop(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserCreate(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserGetTypeID()",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForDomains(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForServices(_:_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserStopSearch(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserUnscheduleFromRunLoop(_:_:_:)"
      ],
      "title": "Network Services"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/init()",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/init(version:info:retain:release:copyDescription:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/copyDescription",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/info",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/release",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/retain",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/version"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CFNetServiceClientContext"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceClientContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceClientContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/copyDescription",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/info",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/release",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/retain",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext/version"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Network-Services",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetService",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowser",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserFlags",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitor",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorType",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceRegisterFlags",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserInvalidate(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserScheduleWithRunLoop(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserCreate(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserGetTypeID()",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForDomains(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForServices(_:_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserStopSearch(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserUnscheduleFromRunLoop(_:_:_:)"
              ],
              "title": "Network Services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CFNetServiceClientContext"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserSearchForDomains(_:_:_:)/title",
          "value": "CFNetServiceBrowserSearchForDomains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserSearchForDomains(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserSearchForDomains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext~1release/title",
          "value": "release"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext~1release/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "release"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext~1info/title",
          "value": "info"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext~1info/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitor/title",
          "value": "CFNetServiceMonitorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceMonitorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceMonitorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserStopSearch(_:_:)/title",
          "value": "CFNetServiceBrowserStopSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserStopSearch(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserStopSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserFlags/title",
          "value": "CFNetServiceBrowserFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserScheduleWithRunLoop(_:_:_:)/title",
          "value": "CFNetServiceBrowserScheduleWithRunLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserScheduleWithRunLoop(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserScheduleWithRunLoop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserUnscheduleFromRunLoop(_:_:_:)/title",
          "value": "CFNetServiceBrowserUnscheduleFromRunLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserUnscheduleFromRunLoop(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserUnscheduleFromRunLoop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceRegisterFlags/title",
          "value": "CFNetServiceRegisterFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceRegisterFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceRegisterFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceRegisterFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceRegisterFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext~1copyDescription/title",
          "value": "copyDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext~1copyDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "copyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError/title",
          "value": "CFNetServicesError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServicesError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServicesError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetService/title",
          "value": "CFNetServiceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorType/title",
          "value": "CFNetServiceMonitorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceMonitorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceMonitorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext~1retain/title",
          "value": "retain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext~1retain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "retain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserInvalidate(_:)/title",
          "value": "CFNetServiceBrowserInvalidate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserInvalidate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserInvalidate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserGetTypeID()/title",
          "value": "CFNetServiceBrowserGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserCreate(_:_:_:)/title",
          "value": "CFNetServiceBrowserCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserCreate(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext/title",
          "value": "CFNetServiceClientContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceClientContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceClientContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserSearchForServices(_:_:_:_:)/title",
          "value": "CFNetServiceBrowserSearchForServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserSearchForServices(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserSearchForServices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowser/title",
          "value": "CFNetServiceBrowserRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfnetserviceclientcontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfnetserviceclientcontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
