{
  "abstract": [
    {
      "text": "Enumerated values related to SOCKS.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "role": "collectionGroup",
    "title": "CFNetwork Enumerations"
  },
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/1518276-anonymous": {
      "abstract": [
        {
          "text": "SOCKS subdomain error codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/1518276-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/cfnetwork/1518276-anonymous"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/1518284-anonymous": {
      "abstract": [
        {
          "text": "SOCKS4 subdomain response codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/1518284-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/cfnetwork/1518284-anonymous"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/1518287-anonymous": {
      "abstract": [
        {
          "text": "SOCKS error codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/1518287-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/cfnetwork/1518287-anonymous"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-constants": {
      "abstract": [
        {
          "text": "Constants for use with CFNetwork.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CFNetwork Constants",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetwork-constants"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-data-types": {
      "abstract": [
        {
          "text": "Callback types for various network services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CFNetwork Data Types",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetwork-data-types"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-data-types",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/1518287-anonymous",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/1518276-anonymous",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/1518284-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-data-types",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-constants"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfnetwork-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfnetwork-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
