{
  "abstract": [
    {
      "text": "Creates a network diagnostic object from a pair of CFStreams.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCreateWithStreams(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CFNetDiagnosticCreateWithStreams",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CFNetDiagnosticCreateWithStreams"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFAllocatorRef",
        "text": "CFAllocator"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFReadStreamRef",
        "text": "CFReadStream"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFWriteStreamRef",
        "text": "CFWriteStream"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFNetDiagnosticRef",
        "text": "CFNetDiagnostic"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CFNetDiagnosticCreateWithStreams"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.13",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CFNetDiagnosticCreateWithStreams(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticCreateWithStreams"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "alloc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFAllocatorRef",
              "text": "CFAllocator"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "readStream"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFReadStreamRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFReadStreamRef",
              "text": "CFReadStream"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "writeStream"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFWriteStreamRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFWriteStreamRef",
              "text": "CFWriteStream"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnostic",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFNetDiagnosticRef",
              "text": "CFNetDiagnostic"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The allocator to use to allocate memory for the new object. Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " or kCFAllocatorDefault to use the current default allocator.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "alloc"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Reference to a read stream whose connection has failed, or ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " if you do not want the CFNetDiagnosticRef to have a read stream.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "readStream"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Reference to a write stream whose connection has failed, or ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " if you do not want the CFNetDiagnosticRef to have a write stream.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "writeStream"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function uses references to a read steam and a write stream (or just a read stream or just a write stream) to create a reference to an instance of a CFNetDiagnostic object. You can pass the reference to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticDiagnoseProblemInteractively(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to open a Network Diagnostics window or to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCopyNetworkStatusPassively(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to get a description of the connection referenced by ",
              "type": "text"
            },
            {
              "code": "readStream",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "writeStream",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Special-Considerations",
          "level": 3,
          "text": "Special Considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function is thread safe as long as another thread does not alter the same CFNetDiagnosticRef at the same time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnostic": {
      "abstract": [
        {
          "text": "An opaque reference representing a CFNetDiagnostic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnostic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnostic"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnostic",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnostic"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCopyNetworkStatusPassively(_:_:)": {
      "abstract": [
        {
          "text": "Gets a network status value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticCopyNetworkStatusPassively"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetDiagnosticRef",
          "text": "CFNetDiagnostic"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetDiagnosticStatus",
          "text": "CFNetDiagnosticStatus"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCopyNetworkStatusPassively(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticCopyNetworkStatusPassively"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticCopyNetworkStatusPassively(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticcopynetworkstatuspassively(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCreateWithStreams(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a network diagnostic object from a pair of CFStreams.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticCreateWithStreams"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFReadStreamRef",
          "text": "CFReadStream"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFWriteStreamRef",
          "text": "CFWriteStream"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetDiagnosticRef",
          "text": "CFNetDiagnostic"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCreateWithStreams(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticCreateWithStreams"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticCreateWithStreams(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticcreatewithstreams(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCreateWithURL(_:_:)": {
      "abstract": [
        {
          "text": "Creates a CFNetDiagnosticRef from a CFURLRef.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticCreateWithURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetDiagnosticRef",
          "text": "CFNetDiagnostic"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCreateWithURL(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticCreateWithURL"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticCreateWithURL(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticcreatewithurl(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticDiagnoseProblemInteractively(_:)": {
      "abstract": [
        {
          "text": "Opens a Network Diagnostics window.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticDiagnoseProblemInteractively"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetDiagnosticRef",
          "text": "CFNetDiagnostic"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetDiagnosticStatus",
          "text": "CFNetDiagnosticStatus"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticDiagnoseProblemInteractively(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticDiagnoseProblemInteractively"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticDiagnoseProblemInteractively(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticdiagnoseprobleminteractively(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticSetName(_:_:)": {
      "abstract": [
        {
          "text": "Overrides the displayed application name.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticSetName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetDiagnosticRef",
          "text": "CFNetDiagnostic"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticSetName(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticSetName"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticSetName(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticsetname(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues": {
      "abstract": [
        {
          "text": "Constants for diagnostic status values.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticStatusValues"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticStatusValues"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticStatusValues",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticstatusvalues"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef": {
      "abstract": [
        {
          "text": "A reference to a CFAllocator object. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFAllocator"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocator",
      "type": "topic",
      "url": "/documentation/corefoundation/cfallocator"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFReadStreamRef": {
      "abstract": [
        {
          "text": "A reference to a readable stream object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFReadStream"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFReadStreamRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFReadStream",
      "type": "topic",
      "url": "/documentation/corefoundation/cfreadstream"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFWriteStreamRef": {
      "abstract": [
        {
          "text": "A reference to a writable stream object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFWriteStream"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFWriteStreamRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFWriteStream",
      "type": "topic",
      "url": "/documentation/corefoundation/cfwritestream"
    },
    "doc://com.externally.resolved.symbol/s:s9UnmanagedV": {
      "abstract": [
        {
          "text": "A type for propagating an unmanaged object reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Unmanaged",
      "type": "topic",
      "url": "/documentation/Swift/Unmanaged"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Network-Diagnostics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnostic",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCopyNetworkStatusPassively(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCreateWithURL(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticDiagnoseProblemInteractively(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticSetName(_:_:)"
      ],
      "title": "Network Diagnostics"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.13",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CFNetDiagnosticCreateWithStreams"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticCreateWithStreams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Network-Diagnostics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnostic",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCopyNetworkStatusPassively(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticCreateWithURL(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticDiagnoseProblemInteractively(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticSetName(_:_:)"
              ],
              "title": "Network Diagnostics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnostic",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFNetDiagnosticRef",
                    "text": "CFNetDiagnosticRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CFNetDiagnosticCreateWithStreams"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFAllocatorRef",
                    "text": "CFAllocatorRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "alloc"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFReadStreamRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFReadStreamRef",
                    "text": "CFReadStreamRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "readStream"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFWriteStreamRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFWriteStreamRef",
                    "text": "CFWriteStreamRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "writeStream"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The allocator to use to allocate memory for the new object. Pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " or kCFAllocatorDefault to use the current default allocator.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "alloc"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Reference to a read stream whose connection has failed, or ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if you do not want the CFNetDiagnosticRef to have a read stream.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "readStream"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Reference to a write stream whose connection has failed, or ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if you do not want the CFNetDiagnosticRef to have a write stream.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "writeStream"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticCreateWithURL(_:_:)/title",
          "value": "CFNetDiagnosticCreateWithURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticCreateWithURL(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticCreateWithURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues/title",
          "value": "CFNetDiagnosticStatusValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticStatusValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticStatusValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticCopyNetworkStatusPassively(_:_:)/title",
          "value": "CFNetDiagnosticCopyNetworkStatusPassively"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticCopyNetworkStatusPassively(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticCopyNetworkStatusPassively"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnostic/title",
          "value": "CFNetDiagnosticRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnostic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnostic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFWriteStreamRef/title",
          "value": "CFWriteStreamRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticCreateWithStreams(_:_:_:)/title",
          "value": "CFNetDiagnosticCreateWithStreams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticCreateWithStreams(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticCreateWithStreams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticSetName(_:_:)/title",
          "value": "CFNetDiagnosticSetName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticSetName(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticSetName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFAllocatorRef/title",
          "value": "CFAllocatorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticDiagnoseProblemInteractively(_:)/title",
          "value": "CFNetDiagnosticDiagnoseProblemInteractively"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticDiagnoseProblemInteractively(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticDiagnoseProblemInteractively"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFReadStreamRef/title",
          "value": "CFReadStreamRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfnetdiagnosticcreatewithstreams(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfnetdiagnosticcreatewithstreams(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
