{
  "abstract": [
    {
      "text": "Makes a CFNetService available on the network.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use nw_browser_t or nw_listener_t in Network framework instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceRegisterWithOptions(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CFNetServiceRegisterWithOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CFNetServiceRegisterWithOptions"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFNetServiceRef",
        "text": "CFNetService"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFOptionFlags",
        "text": "CFOptionFlags"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CFStreamError",
        "text": "CFStreamError"
      },
      {
        "kind": "text",
        "text": ">?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CFNetServiceRegisterWithOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "2.0",
        "message": "Use nw_browser_t or nw_listener_t in Network framework instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "2.0",
        "message": "Use nw_browser_t or nw_listener_t in Network framework instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "message": "Use nw_browser_t or nw_listener_t in Network framework instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.4",
        "message": "Use nw_browser_t or nw_listener_t in Network framework instead",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "message": "Use nw_browser_t or nw_listener_t in Network framework instead",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Use nw_browser_t or nw_listener_t in Network framework instead",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CFNetServiceRegisterWithOptions(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CFNetServiceRegisterWithOptions"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "theService"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetService",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFNetServiceRef",
              "text": "CFNetService"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFOptionFlags",
              "text": "CFOptionFlags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@CFStreamError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CFStreamError",
              "text": "CFStreamError"
            },
            {
              "kind": "text",
              "text": ">?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Network service to register; cannot be ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ". The registration will fail if the service doesn’t have a domain, a type, a name, and an IP address.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "theService"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Bit flags for specifying registration options. Currently, the only registration option is ",
                  "type": "text"
                },
                {
                  "code": "kCFNetServiceFlagNoAutoRename",
                  "type": "codeVoice"
                },
                {
                  "text": ". For details, see ",
                  "type": "text"
                },
                {
                  "code": "CFNetService Registration Options",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Pointer to a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstreamerror",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " structure that will be set to an error code and the error code’s domain if an error occurs; or ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " if you don’t want to receive the error code and its domain.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "code": "TRUE",
              "type": "codeVoice"
            },
            {
              "text": " if an asynchronous service registration was started; ",
              "type": "text"
            },
            {
              "code": "FALSE",
              "type": "codeVoice"
            },
            {
              "text": " if an asynchronous or synchronous registration failed or if a synchronous registration was canceled.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the service is to run in asynchronous mode, you must call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceSetClient(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to associate a callback function with this CFNetService before calling this function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When registering a service that runs in asynchronous mode, this function returns ",
              "type": "text"
            },
            {
              "code": "TRUE",
              "type": "codeVoice"
            },
            {
              "text": " if the service contains all of the required attributes and the registration process can start. If the registration process completes successfully, the service is available on the network until you shut down the service by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceUnscheduleFromRunLoop(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceSetClient(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceCancel(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If the service does not contain all of the required attributes or if the registration process does not complete successfully, this function returns ",
              "type": "text"
            },
            {
              "code": "FALSE",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When registering a service that runs in synchronous mode, this function blocks until an error occurs, in which case this function returns ",
              "type": "text"
            },
            {
              "code": "FALSE",
              "type": "codeVoice"
            },
            {
              "text": ". Until this function returns ",
              "type": "text"
            },
            {
              "code": "FALSE",
              "type": "codeVoice"
            },
            {
              "text": ", the service is available on the network. To force this function to return ",
              "type": "text"
            },
            {
              "code": "FALSE",
              "type": "codeVoice"
            },
            {
              "text": ", thereby shutting down the service, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceCancel(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " from another thread.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "options",
              "type": "codeVoice"
            },
            {
              "text": " parameter is a bit flag for specifying service registration options. Currently, ",
              "type": "text"
            },
            {
              "code": "kCFNetServiceFlagNoAutoRename",
              "type": "codeVoice"
            },
            {
              "text": " is the only supported registration option. If this bit is set and a service of the same name is running, the registration will fail. If this bit is not set and a service of the same name is running, the service that is being registered will be renamed automatically by appending ",
              "type": "text"
            },
            {
              "code": "(",
              "type": "codeVoice"
            },
            {
              "inlineContent": [
                {
                  "text": "n",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "code": ")",
              "type": "codeVoice"
            },
            {
              "text": " to the service name, where ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "n",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " is a number that is incremented until the service can be registered with a unique name.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Special-Considerations",
          "level": 3,
          "text": "Special Considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function is thread safe.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetService": {
      "abstract": [
        {
          "text": "An opaque reference representing a CFNetService.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetService"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetService"
        }
      ],
      "role": "symbol",
      "title": "CFNetService",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservice"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowser": {
      "abstract": [
        {
          "text": "An opaque reference representing a CFNetServiceBrowser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowser"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowser"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowser",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowser"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserCreate(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an instance of a Network Service browser object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserClientCallBack",
          "text": "CFNetServiceBrowserClientCallBack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CFNetServiceClientContext",
          "text": "CFNetServiceClientContext"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserCreate(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserCreate"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserCreate(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowsercreate(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserFlags": {
      "abstract": [
        {
          "text": "Flags that the system passes to net service browser callbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserFlags"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserFlags"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserFlags",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowserflags"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserGetTypeID()": {
      "abstract": [
        {
          "text": "Gets the Core Foundation type identifier for the Network Service browser object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserGetTypeID()",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowsergettypeid()"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserInvalidate(_:)": {
      "abstract": [
        {
          "text": "Invalidates an instance of a Network Service browser object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserInvalidate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserInvalidate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserInvalidate"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserInvalidate(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowserinvalidate(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserScheduleWithRunLoop(_:_:_:)": {
      "abstract": [
        {
          "text": "Schedules a CFNetServiceBrowser on a run loop.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserScheduleWithRunLoop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopRef",
          "text": "CFRunLoop"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserScheduleWithRunLoop(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserScheduleWithRunLoop"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserScheduleWithRunLoop(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowserschedulewithrunloop(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForDomains(_:_:_:)": {
      "abstract": [
        {
          "text": "Searches for domains.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserSearchForDomains"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForDomains(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserSearchForDomains"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserSearchForDomains(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowsersearchfordomains(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForServices(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Searches a domain for services of a specified type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserSearchForServices"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForServices(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserSearchForServices"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserSearchForServices(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowsersearchforservices(_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserStopSearch(_:_:)": {
      "abstract": [
        {
          "text": "Stops a search for domains or services.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserStopSearch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceBrowserRef",
          "text": "CFNetServiceBrowser"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserStopSearch(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserStopSearch"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserStopSearch(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowserstopsearch(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceCancel(_:)": {
      "abstract": [
        {
          "text": "Cancels a service registration or a service resolution.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceCancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceRef",
          "text": "CFNetService"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceCancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceCancel"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceCancel(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicecancel(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext": {
      "abstract": [
        {
          "text": "A structure provided when a CFNetService is associated with a callback function or when a CFNetServiceBrowser is created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceClientContext"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceClientContext"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceClientContext",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceclientcontext"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitor": {
      "abstract": [
        {
          "text": "An opaque reference for a service monitor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceMonitor"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceMonitor"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceMonitor",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicemonitor"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorType": {
      "abstract": [
        {
          "text": "Record type specifier used to tell a service monitor the type of record changes to watch for.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceMonitorType"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceMonitorType"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceMonitorType",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicemonitortype"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceRegisterFlags": {
      "abstract": [
        {
          "text": "Options to use when registering a service on the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceRegisterFlags"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceRegisterFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceRegisterFlags"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceRegisterFlags",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceregisterflags"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceRegisterWithOptions(_:_:_:)": {
      "abstract": [
        {
          "text": "Makes a CFNetService available on the network.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceRegisterWithOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceRef",
          "text": "CFNetService"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFOptionFlags",
          "text": "CFOptionFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceRegisterWithOptions(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceRegisterWithOptions"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceRegisterWithOptions(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceregisterwithoptions(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceSetClient(_:_:_:)": {
      "abstract": [
        {
          "text": "Associates a callback function with a CFNetService or disassociates a callback function from a CFNetService.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceSetClient"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceRef",
          "text": "CFNetService"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceClientCallBack",
          "text": "CFNetServiceClientCallBack"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CFNetServiceClientContext",
          "text": "CFNetServiceClientContext"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceSetClient(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceSetClient"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceSetClient(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicesetclient(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceUnscheduleFromRunLoop(_:_:_:)": {
      "abstract": [
        {
          "text": "Unschedules a CFNetService from a run loop.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceUnscheduleFromRunLoop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNetServiceRef",
          "text": "CFNetService"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopRef",
          "text": "CFRunLoop"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceUnscheduleFromRunLoop(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceUnscheduleFromRunLoop"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceUnscheduleFromRunLoop(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceunschedulefromrunloop(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError": {
      "abstract": [
        {
          "text": "Error codes that may be returned by CFNetServices functions or passed to CFNetServices callback functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServicesError"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServicesError"
        }
      ],
      "role": "symbol",
      "title": "CFNetServicesError",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceserror"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfstreamerror": {
      "abstract": [
        {
          "text": "The structure returned by  and .",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CFStreamError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstreamerror",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFStreamError",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstreamerror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@SA@CFStreamError": {
      "abstract": [
        {
          "text": "The structure returned by  and .",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CFStreamError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@CFStreamError",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFStreamError",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstreamerror"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags": {
      "abstract": [
        {
          "text": "A bitfield used for passing special allocation and other requests into Core Foundation functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFOptionFlags"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFOptionFlags",
      "type": "topic",
      "url": "/documentation/corefoundation/cfoptionflags"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Network-Services",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetService",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowser",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserFlags",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitor",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorType",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceRegisterFlags",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserInvalidate(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserScheduleWithRunLoop(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserCreate(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserGetTypeID()",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForDomains(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForServices(_:_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserStopSearch(_:_:)"
      ],
      "title": "Network Services"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CFNetServiceRegisterWithOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceRegisterWithOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Network-Services",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetService",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowser",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserFlags",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitor",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorType",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientContext",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceRegisterFlags",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServicesError",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserInvalidate(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserScheduleWithRunLoop(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserCreate(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserGetTypeID()",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForDomains(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserSearchForServices(_:_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserStopSearch(_:_:)"
              ],
              "title": "Network Services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@Boolean",
                    "text": "Boolean"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CFNetServiceRegisterWithOptions"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetService",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFNetServiceRef",
                    "text": "CFNetServiceRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "theService"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFOptionFlags",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFOptionFlags",
                    "text": "CFOptionFlags"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "options"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@SA@CFStreamError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@CFStreamError",
                    "text": "CFStreamError"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Network service to register; cannot be ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". The registration will fail if the service doesn’t have a domain, a type, a name, and an IP address.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "theService"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Bit flags for specifying registration options. Currently, the only registration option is ",
                        "type": "text"
                      },
                      {
                        "code": "kCFNetServiceFlagNoAutoRename",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". For details, see ",
                        "type": "text"
                      },
                      {
                        "code": "CFNetService Registration Options",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "options"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Pointer to a ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstreamerror",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " structure that will be set to an error code and the error code’s domain if an error occurs; or ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if you don’t want to receive the error code and its domain.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "code": "TRUE",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if an asynchronous service registration was started; ",
                    "type": "text"
                  },
                  {
                    "code": "FALSE",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if an asynchronous or synchronous registration failed or if a synchronous registration was canceled.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use nw_browser_t or nw_listener_t in Network framework instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserScheduleWithRunLoop(_:_:_:)/title",
          "value": "CFNetServiceBrowserScheduleWithRunLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserScheduleWithRunLoop(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserScheduleWithRunLoop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceSetClient(_:_:_:)/title",
          "value": "CFNetServiceSetClient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceSetClient(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceSetClient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceUnscheduleFromRunLoop(_:_:_:)/title",
          "value": "CFNetServiceUnscheduleFromRunLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceUnscheduleFromRunLoop(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceUnscheduleFromRunLoop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceRegisterFlags/title",
          "value": "CFNetServiceRegisterFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceRegisterFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceRegisterFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceRegisterFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceRegisterFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserSearchForDomains(_:_:_:)/title",
          "value": "CFNetServiceBrowserSearchForDomains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserSearchForDomains(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserSearchForDomains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserStopSearch(_:_:)/title",
          "value": "CFNetServiceBrowserStopSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserStopSearch(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserStopSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserInvalidate(_:)/title",
          "value": "CFNetServiceBrowserInvalidate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserInvalidate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserInvalidate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetService/title",
          "value": "CFNetServiceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserSearchForServices(_:_:_:_:)/title",
          "value": "CFNetServiceBrowserSearchForServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserSearchForServices(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserSearchForServices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceCancel(_:)/title",
          "value": "CFNetServiceCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceCancel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorType/title",
          "value": "CFNetServiceMonitorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceMonitorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceMonitorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError/title",
          "value": "CFNetServicesError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServicesError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServicesError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServicesError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserGetTypeID()/title",
          "value": "CFNetServiceBrowserGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserCreate(_:_:_:)/title",
          "value": "CFNetServiceBrowserCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserCreate(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowser/title",
          "value": "CFNetServiceBrowserRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitor/title",
          "value": "CFNetServiceMonitorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceMonitorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceMonitorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext/title",
          "value": "CFNetServiceClientContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceClientContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceClientContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserFlags/title",
          "value": "CFNetServiceBrowserFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceRegisterWithOptions(_:_:_:)/title",
          "value": "CFNetServiceRegisterWithOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceRegisterWithOptions(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceRegisterWithOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfnetserviceregisterwithoptions(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfnetserviceregisterwithoptions(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
