{
  "abstract": [
    {
      "text": "Callback types for various network services.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CFNetwork Data Types"
  },
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientCallBack": {
      "abstract": [
        {
          "text": "Defines a pointer to the callback function that is called when an asynchronous resolution of a CFHost completes or an error occurs for an asynchronous CFHost resolution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostClientCallBack"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostClientCallBack"
        }
      ],
      "role": "symbol",
      "title": "CFHostClientCallBack",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostclientcallback"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatus": {
      "abstract": [
        {
          "text": "A CFIndex type that is used to return status values from ",
          "type": "text"
        },
        {
          "code": "CFNetDiagnostic",
          "type": "codeVoice"
        },
        {
          "text": " status and diagnostic functions. For a list of possible values, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticStatus"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticStatus"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticStatus",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticstatus"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues": {
      "abstract": [
        {
          "text": "Constants for diagnostic status values.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticStatusValues"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatusValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetDiagnosticStatusValues"
        }
      ],
      "role": "symbol",
      "title": "CFNetDiagnosticStatusValues",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetdiagnosticstatusvalues"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserClientCallBack": {
      "abstract": [
        {
          "text": "Defines a pointer to the callback function for a CFNetServiceBrowser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserClientCallBack"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserClientCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceBrowserClientCallBack"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceBrowserClientCallBack",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicebrowserclientcallback"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientCallBack": {
      "abstract": [
        {
          "text": "Defines a pointer to the callback function for a CFNetService.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceClientCallBack"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceClientCallBack"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceClientCallBack",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetserviceclientcallback"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorClientCallBack": {
      "abstract": [
        {
          "text": "Defines a pointer to the callback function that is to be called when a monitored record type changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetServiceMonitorClientCallBack"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorClientCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetServiceMonitorClientCallBack"
        }
      ],
      "role": "symbol",
      "title": "CFNetServiceMonitorClientCallBack",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetservicemonitorclientcallback"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-constants": {
      "abstract": [
        {
          "text": "Constants for use with CFNetwork.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CFNetwork Constants",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetwork-constants"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-enumerations": {
      "abstract": [
        {
          "text": "Enumerated values related to SOCKS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CFNetwork Enumerations",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetwork-enumerations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-enumerations",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientCallBack",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserClientCallBack",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientCallBack",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorClientCallBack",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatus"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientCallBack",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceBrowserClientCallBack",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceClientCallBack",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetServiceMonitorClientCallBack",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetDiagnosticStatus"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-enumerations",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/cfnetwork-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientCallBack/title",
          "value": "CFHostClientCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientCallBack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientCallBack/title",
          "value": "CFNetServiceClientCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceClientCallBack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserClientCallBack/title",
          "value": "CFNetServiceBrowserClientCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserClientCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceBrowserClientCallBack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceBrowserClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues/title",
          "value": "CFNetDiagnosticStatusValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticStatusValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatusValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticStatusValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorClientCallBack/title",
          "value": "CFNetServiceMonitorClientCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorClientCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceMonitorClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetServiceMonitorClientCallBack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetServiceMonitorClientCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatus/title",
          "value": "CFNetDiagnosticStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetDiagnosticStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetDiagnosticStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfnetwork-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfnetwork-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
