{
  "abstract": [
    {
      "text": "Callback function called when a proxy autoconfiguration computation has completed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFProxyAutoConfigurationResultCallback"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CFProxyAutoConfigurationResultCallback",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CFProxyAutoConfigurationResultCallback"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CFProxyAutoConfigurationResultCallback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CFProxyAutoConfigurationResultCallback"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CFProxyAutoConfigurationResultCallback"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFErrorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFErrorRef",
              "text": "CFError"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The client reference originally passed in the ",
                  "type": "text"
                },
                {
                  "code": "clientContext",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter of the ",
                  "type": "text"
                },
                {
                  "code": "CFNetworkExecuteProxyAutoConfigurationScript",
                  "type": "codeVoice"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "code": "CFNetworkExecuteProxyAutoConfigurationURL",
                  "type": "codeVoice"
                },
                {
                  "text": " call that triggered this callback.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "client"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The list of proxies returned by the autoconfiguration script. This list is in a format suitable for passing to ",
                  "type": "text"
                },
                {
                  "code": "CFProxyCopyProxiesForURL",
                  "type": "codeVoice"
                },
                {
                  "text": " (with the added guarantee that no entries will ever be autoconfiguration URL entries). If an error occurs, this value will be ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "If you want to keep this list, you must retain it when your callback receives it.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              "name": "Note",
              "style": "note",
              "type": "aside"
            }
          ],
          "name": "proxyList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An error object that indicates any error that may have occurred. If no error occurred, this value will be NULL.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)": {
      "abstract": [
        {
          "text": "Executes a proxy autoconfiguration script to determine the best proxy to use to retrieve a specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForAutoConfigurationScript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForAutoConfigurationScript"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkcopyproxiesforautoconfigurationscript(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)": {
      "abstract": [
        {
          "text": "Returns the list of proxies that should be used to download a given URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForURL"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkCopyProxiesForURL(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkcopyproxiesforurl(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()": {
      "abstract": [
        {
          "text": "Returns a CFDictionary containing the current systemwide internet proxy settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkCopySystemProxySettings"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkCopySystemProxySettings"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkCopySystemProxySettings()",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkcopysystemproxysettings()"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Downloads a proxy autoconfiguration script and executes it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationScript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFProxyAutoConfigurationResultCallback",
          "text": "CFProxyAutoConfigurationResultCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamClientContext",
          "text": "CFStreamClientContext"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopSourceRef",
          "text": "CFRunLoopSource"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationScript"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkexecuteproxyautoconfigurationscript(_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Downloads a proxy autoconfiguration script and executes it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFProxyAutoConfigurationResultCallback",
          "text": "CFProxyAutoConfigurationResultCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamClientContext",
          "text": "CFStreamClientContext"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopSourceRef",
          "text": "CFRunLoopSource"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationURL"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkexecuteproxyautoconfigurationurl(_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFProxyAutoConfigurationResultCallback": {
      "abstract": [
        {
          "text": "Callback function called when a proxy autoconfiguration computation has completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFProxyAutoConfigurationResultCallback"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFProxyAutoConfigurationResultCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFProxyAutoConfigurationResultCallback"
        }
      ],
      "role": "symbol",
      "title": "CFProxyAutoConfigurationResultCallback",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfproxyautoconfigurationresultcallback"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/global-proxy-settings-constants": {
      "abstract": [
        {
          "text": "Constants for keys in the global proxy settings dictionary returned by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/global-proxy-settings-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Global Proxy Settings Constants",
      "type": "topic",
      "url": "/documentation/cfnetwork/global-proxy-settings-constants"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/property-keys": {
      "abstract": [
        {
          "text": "Keys for calls to property get/set functions such as ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539615-cfreadstreamsetproperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/property-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Property Keys",
      "type": "topic",
      "url": "/documentation/cfnetwork/property-keys"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/proxy-types": {
      "abstract": [
        {
          "text": "Constants that specify the type of proxy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/proxy-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Proxy Types",
      "type": "topic",
      "url": "/documentation/cfnetwork/proxy-types"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1539615-cfreadstreamsetproperty": {
      "abstract": [
        {
          "text": "Sets the value of a property for a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamSetProperty"
        },
        {
          "kind": "text",
          "text": "(CFReadStream!, CFStreamPropertyKey!, CFTypeRef!) -> Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539615-cfreadstreamsetproperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFReadStreamSetProperty(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1539615-cfreadstreamsetproperty"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty": {
      "abstract": [
        {
          "text": "Returns the value of a property for a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamCopyProperty"
        },
        {
          "kind": "text",
          "text": "(CFReadStream!, CFStreamPropertyKey!) -> CFTypeRef!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFReadStreamCopyProperty(_:_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1539715-cfreadstreamcopyproperty"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFErrorRef": {
      "abstract": [
        {
          "text": "A reference to a CFError object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFErrorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFError",
      "type": "topic",
      "url": "/documentation/corefoundation/cferror"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Global-Proxy-Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/property-keys",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/proxy-types",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/global-proxy-settings-constants"
      ],
      "title": "Global Proxy Configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CFProxyAutoConfigurationResultCallback"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFProxyAutoConfigurationResultCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFProxyAutoConfigurationResultCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Global-Proxy-Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/property-keys",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/proxy-types",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/global-proxy-settings-constants"
              ],
              "title": "Global Proxy Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:*Fv(#*v#*1$@S@__CFArray#*$@S@__CFError)",
                    "text": "void (*)(void *, const struct __CFArray *, struct __CFError *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CFProxyAutoConfigurationResultCallback"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForURL(_:_:)/title",
          "value": "CFNetworkCopyProxiesForURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForURL(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkCopyProxiesForURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)/title",
          "value": "CFNetworkExecuteProxyAutoConfigurationScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkExecuteProxyAutoConfigurationScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11539715-cfreadstreamcopyproperty/title",
          "value": "CFReadStreamCopyProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopySystemProxySettings()/title",
          "value": "CFNetworkCopySystemProxySettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopySystemProxySettings()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkCopySystemProxySettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFProxyAutoConfigurationResultCallback/title",
          "value": "CFProxyAutoConfigurationResultCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFProxyAutoConfigurationResultCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFProxyAutoConfigurationResultCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFProxyAutoConfigurationResultCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFProxyAutoConfigurationResultCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)/title",
          "value": "CFNetworkCopyProxiesForAutoConfigurationScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkCopyProxiesForAutoConfigurationScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11539615-cfreadstreamsetproperty/title",
          "value": "CFReadStreamSetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFErrorRef/title",
          "value": "CFErrorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)/title",
          "value": "CFNetworkExecuteProxyAutoConfigurationURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkExecuteProxyAutoConfigurationURL"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfproxyautoconfigurationresultcallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfproxyautoconfigurationresultcallback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
