{
  "abstract": [
    {
      "text": "Creates readable and writable streams connected to a given ",
      "type": "text"
    },
    {
      "code": "CFHost",
      "type": "codeVoice"
    },
    {
      "text": " object.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use Network framework instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamCreatePairWithSocketToCFHost(_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CFStreamCreatePairWithSocketToCFHost",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CFStreamCreatePairWithSocketToCFHost"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFAllocatorRef",
        "text": "CFAllocator"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFHostRef",
        "text": "CFHost"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFReadStreamRef",
        "text": "CFReadStream"
      },
      {
        "kind": "text",
        "text": ">?>?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFWriteStreamRef",
        "text": "CFWriteStream"
      },
      {
        "kind": "text",
        "text": ">?>?)"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CFStreamCreatePairWithSocketToCFHost"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "2.0",
        "message": "Use Network framework instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "2.0",
        "message": "Use Network framework instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "message": "Use Network framework instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.3",
        "message": "Use Network framework instead",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "message": "Use Network framework instead",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Use Network framework instead",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CFStreamCreatePairWithSocketToCFHost(_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CFStreamCreatePairWithSocketToCFHost"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "alloc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFAllocatorRef",
              "text": "CFAllocator"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "host"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHost",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFHostRef",
              "text": "CFHost"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "port"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "readStream"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFReadStreamRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFReadStreamRef",
              "text": "CFReadStream"
            },
            {
              "kind": "text",
              "text": ">?>?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "writeStream"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFWriteStreamRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFWriteStreamRef",
              "text": "CFWriteStream"
            },
            {
              "kind": "text",
              "text": ">?>?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The allocator to use to allocate memory for the ",
                  "type": "text"
                },
                {
                  "code": "CFReadStream",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "CFWriteStream",
                  "type": "codeVoice"
                },
                {
                  "text": " objects. Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " or kCFAllocatorDefault to use the current default allocator.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "alloc"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "code": "CFHost",
                  "type": "codeVoice"
                },
                {
                  "text": " object to which the streams are connected.  If unresolved, the host will be resolved prior to connecting.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "host"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The TCP port number to which the socket streams should connect.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "port"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Upon return, contains a ",
                  "type": "text"
                },
                {
                  "code": "CFReadStream",
                  "type": "codeVoice"
                },
                {
                  "text": " object connected to the host ",
                  "type": "text"
                },
                {
                  "code": "host",
                  "type": "codeVoice"
                },
                {
                  "text": " on port ",
                  "type": "text"
                },
                {
                  "code": "port",
                  "type": "codeVoice"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " if there is a failure during creation. If you pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ", the function will not create a readable stream. Ownership follows the ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "readStream"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Upon return, contains a ",
                  "type": "text"
                },
                {
                  "code": "CFWriteStream",
                  "type": "codeVoice"
                },
                {
                  "text": " object connected to the host ",
                  "type": "text"
                },
                {
                  "code": "host",
                  "type": "codeVoice"
                },
                {
                  "text": " on port ",
                  "type": "text"
                },
                {
                  "code": "port",
                  "type": "codeVoice"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " if there is a failure during creation. If you pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ", the function will not create a writable stream. Ownership follows the ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "writeStream"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The streams do not create a socket or connect to the specified host until you open one of the streams.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Most properties are shared by both streams. Setting a shared property for one stream automatically sets the property for the other.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHost": {
      "abstract": [
        {
          "text": "An opaque reference representing an CFHost object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHost"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHost"
        }
      ],
      "role": "symbol",
      "title": "CFHost",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhost"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForHTTPRequest(_:_:)": {
      "abstract": [
        {
          "text": "Creates a read stream for a CFHTTP request message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamCreateForHTTPRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFReadStreamRef",
          "text": "CFReadStream"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForHTTPRequest(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFReadStreamCreateForHTTPRequest"
        }
      ],
      "role": "symbol",
      "title": "CFReadStreamCreateForHTTPRequest(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfreadstreamcreateforhttprequest(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForStreamedHTTPRequest(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a read stream for a CFHTTP request message object whose body is too long to keep in memory.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamCreateForStreamedHTTPRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFReadStreamRef",
          "text": "CFReadStream"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFReadStreamRef",
          "text": "CFReadStream"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForStreamedHTTPRequest(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFReadStreamCreateForStreamedHTTPRequest"
        }
      ],
      "role": "symbol",
      "title": "CFReadStreamCreateForStreamedHTTPRequest(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfreadstreamcreateforstreamedhttprequest(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateWithFTPURL(_:_:)": {
      "abstract": [
        {
          "text": "Creates an FTP read stream.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamCreateWithFTPURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFReadStreamRef",
          "text": "CFReadStream"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateWithFTPURL(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFReadStreamCreateWithFTPURL"
        }
      ],
      "role": "symbol",
      "title": "CFReadStreamCreateWithFTPURL(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfreadstreamcreatewithftpurl(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamCreatePairWithSocketToCFHost(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates readable and writable streams connected to a given ",
          "type": "text"
        },
        {
          "code": "CFHost",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFStreamCreatePairWithSocketToCFHost"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHostRef",
          "text": "CFHost"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFReadStreamRef",
          "text": "CFReadStream"
        },
        {
          "kind": "text",
          "text": ">?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFWriteStreamRef",
          "text": "CFWriteStream"
        },
        {
          "kind": "text",
          "text": ">?>?)"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFStreamCreatePairWithSocketToCFHost(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFStreamCreatePairWithSocketToCFHost"
        }
      ],
      "role": "symbol",
      "title": "CFStreamCreatePairWithSocketToCFHost(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfstreamcreatepairwithsockettocfhost(_:_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFWriteStreamCreateWithFTPURL(_:_:)": {
      "abstract": [
        {
          "text": "Creates an FTP write stream.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFWriteStreamCreateWithFTPURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFWriteStreamRef",
          "text": "CFWriteStream"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFWriteStreamCreateWithFTPURL(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFWriteStreamCreateWithFTPURL"
        }
      ],
      "role": "symbol",
      "title": "CFWriteStreamCreateWithFTPURL(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfwritestreamcreatewithftpurl(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPAttemptPersistentConnection": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPAttemptPersistentConnection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPAttemptPersistentConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPAttemptPersistentConnection"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPAttemptPersistentConnection",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpattemptpersistentconnection"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalRequest": {
      "abstract": [
        {
          "text": "HTTP Final Request property. A value of type CFHTTPMessage containing the final message transmitted by the stream after all modifications (including authentication, connection policy, redirects, and so on) have been made. This property cannot be set.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPFinalRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPFinalRequest"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPFinalRequest",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpfinalrequest"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalURL": {
      "abstract": [
        {
          "text": "HTTP Final URL property. A value of type CFURL containing the final HTTP URL. This value differs from the URL in the original HTTP request if an autoredirection occurred. This property cannot be set.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPFinalURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPFinalURL"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPFinalURL",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpfinalurl"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxy": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPProxy"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPProxy",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpproxy"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyHost": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPProxyHost"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyHost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPProxyHost"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPProxyHost",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpproxyhost"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyPort": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPProxyPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPProxyPort"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPProxyPort",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpproxyport"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPRequestBytesWrittenCount": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPRequestBytesWrittenCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPRequestBytesWrittenCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPRequestBytesWrittenCount"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPRequestBytesWrittenCount",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttprequestbyteswrittencount"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPResponseHeader": {
      "abstract": [
        {
          "text": "HTTP Response Header property. When copied by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", the header of an HTTP response message is returned.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPResponseHeader"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPResponseHeader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPResponseHeader"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPResponseHeader",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpresponseheader"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyHost": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPSProxyHost"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyHost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPSProxyHost"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPSProxyHost",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpsproxyhost"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyPort": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPSProxyPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPSProxyPort"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPSProxyPort",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpsproxyport"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPShouldAutoredirect": {
      "abstract": [
        {
          "text": "HTTP Should Auto Redirect property. Set this property to ",
          "type": "text"
        },
        {
          "code": "kCFBooleanTrue",
          "type": "codeVoice"
        },
        {
          "text": " to enable autoredirection; set this property to ",
          "type": "text"
        },
        {
          "code": "kCFBooleanFalse",
          "type": "codeVoice"
        },
        {
          "text": " to disable autoredirection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPShouldAutoredirect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPShouldAutoredirect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPShouldAutoredirect"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPShouldAutoredirect",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpshouldautoredirect"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty": {
      "abstract": [
        {
          "text": "Returns the value of a property for a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamCopyProperty"
        },
        {
          "kind": "text",
          "text": "(CFReadStream!, CFStreamPropertyKey!) -> CFTypeRef!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFReadStreamCopyProperty(_:_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1539715-cfreadstreamcopyproperty"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef": {
      "abstract": [
        {
          "text": "A reference to a CFAllocator object. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFAllocator"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocator",
      "type": "topic",
      "url": "/documentation/corefoundation/cfallocator"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFReadStreamRef": {
      "abstract": [
        {
          "text": "A reference to a readable stream object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFReadStream"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFReadStreamRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFReadStream",
      "type": "topic",
      "url": "/documentation/corefoundation/cfreadstream"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFWriteStreamRef": {
      "abstract": [
        {
          "text": "A reference to a writable stream object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFWriteStream"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFWriteStreamRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFWriteStream",
      "type": "topic",
      "url": "/documentation/corefoundation/cfwritestream"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    },
    "doc://com.externally.resolved.symbol/s:s9UnmanagedV": {
      "abstract": [
        {
          "text": "A type for propagating an unmanaged object reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Unmanaged",
      "type": "topic",
      "url": "/documentation/Swift/Unmanaged"
    },
    "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029": {
      "identifier": "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029",
      "title": "The Create Rule",
      "titleInlineContent": [
        {
          "text": "The Create Rule",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Streams",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForHTTPRequest(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForStreamedHTTPRequest(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPAttemptPersistentConnection",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalRequest",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalURL",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxy",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyHost",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyPort",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPRequestBytesWrittenCount",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPResponseHeader",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyHost",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyPort",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPShouldAutoredirect",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFWriteStreamCreateWithFTPURL(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateWithFTPURL(_:_:)"
      ],
      "title": "Streams"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CFStreamCreatePairWithSocketToCFHost"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFStreamCreatePairWithSocketToCFHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Streams",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForHTTPRequest(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForStreamedHTTPRequest(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPAttemptPersistentConnection",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalRequest",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalURL",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxy",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyHost",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyPort",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPRequestBytesWrittenCount",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPResponseHeader",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyHost",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyPort",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPShouldAutoredirect",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFWriteStreamCreateWithFTPURL(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateWithFTPURL(_:_:)"
              ],
              "title": "Streams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CFStreamCreatePairWithSocketToCFHost"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFAllocatorRef",
                    "text": "CFAllocatorRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "alloc"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHost",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFHostRef",
                    "text": "CFHostRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "host"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SInt32",
                    "text": "SInt32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "port"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFReadStreamRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFReadStreamRef",
                    "text": "CFReadStreamRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "readStream"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFWriteStreamRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFWriteStreamRef",
                    "text": "CFWriteStreamRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "writeStream"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The allocator to use to allocate memory for the ",
                        "type": "text"
                      },
                      {
                        "code": "CFReadStream",
                        "type": "codeVoice"
                      },
                      {
                        "text": " and ",
                        "type": "text"
                      },
                      {
                        "code": "CFWriteStream",
                        "type": "codeVoice"
                      },
                      {
                        "text": " objects. Pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " or kCFAllocatorDefault to use the current default allocator.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "alloc"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A ",
                        "type": "text"
                      },
                      {
                        "code": "CFHost",
                        "type": "codeVoice"
                      },
                      {
                        "text": " object to which the streams are connected.  If unresolved, the host will be resolved prior to connecting.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "host"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The TCP port number to which the socket streams should connect.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "port"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Upon return, contains a ",
                        "type": "text"
                      },
                      {
                        "code": "CFReadStream",
                        "type": "codeVoice"
                      },
                      {
                        "text": " object connected to the host ",
                        "type": "text"
                      },
                      {
                        "code": "host",
                        "type": "codeVoice"
                      },
                      {
                        "text": " on port ",
                        "type": "text"
                      },
                      {
                        "code": "port",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", or ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if there is a failure during creation. If you pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", the function will not create a readable stream. Ownership follows the ",
                        "type": "text"
                      },
                      {
                        "identifier": "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "readStream"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Upon return, contains a ",
                        "type": "text"
                      },
                      {
                        "code": "CFWriteStream",
                        "type": "codeVoice"
                      },
                      {
                        "text": " object connected to the host ",
                        "type": "text"
                      },
                      {
                        "code": "host",
                        "type": "codeVoice"
                      },
                      {
                        "text": " on port ",
                        "type": "text"
                      },
                      {
                        "code": "port",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", or ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if there is a failure during creation. If you pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", the function will not create a writable stream. Ownership follows the ",
                        "type": "text"
                      },
                      {
                        "identifier": "https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "writeStream"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use Network framework instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11539715-cfreadstreamcopyproperty/title",
          "value": "CFReadStreamCopyProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPResponseHeader/title",
          "value": "kCFStreamPropertyHTTPResponseHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPResponseHeader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPResponseHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPSProxyPort/title",
          "value": "kCFStreamPropertyHTTPSProxyPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPSProxyPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPSProxyPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFReadStreamCreateForHTTPRequest(_:_:)/title",
          "value": "CFReadStreamCreateForHTTPRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFReadStreamCreateForHTTPRequest(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFReadStreamCreateForHTTPRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFWriteStreamRef/title",
          "value": "CFWriteStreamRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHost/title",
          "value": "CFHostRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHost/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPFinalURL/title",
          "value": "kCFStreamPropertyHTTPFinalURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPFinalURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPFinalURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPProxyHost/title",
          "value": "kCFStreamPropertyHTTPProxyHost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPProxyHost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPProxyHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFStreamCreatePairWithSocketToCFHost(_:_:_:_:_:)/title",
          "value": "CFStreamCreatePairWithSocketToCFHost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFStreamCreatePairWithSocketToCFHost(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFStreamCreatePairWithSocketToCFHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPRequestBytesWrittenCount/title",
          "value": "kCFStreamPropertyHTTPRequestBytesWrittenCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPRequestBytesWrittenCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPRequestBytesWrittenCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPFinalRequest/title",
          "value": "kCFStreamPropertyHTTPFinalRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPFinalRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPFinalRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFAllocatorRef/title",
          "value": "CFAllocatorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPProxy/title",
          "value": "kCFStreamPropertyHTTPProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFWriteStreamCreateWithFTPURL(_:_:)/title",
          "value": "CFWriteStreamCreateWithFTPURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFWriteStreamCreateWithFTPURL(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFWriteStreamCreateWithFTPURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPShouldAutoredirect/title",
          "value": "kCFStreamPropertyHTTPShouldAutoredirect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPShouldAutoredirect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPShouldAutoredirect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFReadStreamRef/title",
          "value": "CFReadStreamRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPAttemptPersistentConnection/title",
          "value": "kCFStreamPropertyHTTPAttemptPersistentConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPAttemptPersistentConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPAttemptPersistentConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPProxyPort/title",
          "value": "kCFStreamPropertyHTTPProxyPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPProxyPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPProxyPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFReadStreamCreateWithFTPURL(_:_:)/title",
          "value": "CFReadStreamCreateWithFTPURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFReadStreamCreateWithFTPURL(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFReadStreamCreateWithFTPURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPSProxyHost/title",
          "value": "kCFStreamPropertyHTTPSProxyHost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPSProxyHost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPSProxyHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFReadStreamCreateForStreamedHTTPRequest(_:_:_:)/title",
          "value": "CFReadStreamCreateForStreamedHTTPRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFReadStreamCreateForStreamedHTTPRequest(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFReadStreamCreateForStreamedHTTPRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfstreamcreatepairwithsockettocfhost(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfstreamcreatepairwithsockettocfhost(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
