{
  "abstract": [
    {
      "text": "High-level error domains.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/error-domains"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Error Domains"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To determine the source of an error, examine the ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary included in the ",
              "type": "text"
            },
            {
              "code": "CFError",
              "type": "codeVoice"
            },
            {
              "text": " object returned by a function call or call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/1494657-cferrorgetdomain",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and pass in the ",
              "type": "text"
            },
            {
              "code": "CFError",
              "type": "codeVoice"
            },
            {
              "text": " object and the domain whose value you want to read.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors": {
      "abstract": [
        {
          "text": "This enumeration contains error codes returned under the error domain ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFErrorDomainCFNetwork",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkErrors"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkErrors"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/error-dictionary-keys": {
      "abstract": [
        {
          "text": "Networking-related keys that may be available in a ",
          "type": "text"
        },
        {
          "code": "CFErrorRef",
          "type": "codeVoice"
        },
        {
          "text": " object’s ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/error-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Dictionary Keys",
      "type": "topic",
      "url": "/documentation/cfnetwork/error-dictionary-keys"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFErrorDomainCFNetwork": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFErrorDomainCFNetwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFErrorDomainCFNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFErrorDomainCFNetwork"
        }
      ],
      "role": "symbol",
      "title": "kCFErrorDomainCFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcferrordomaincfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFErrorDomainWinSock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFErrorDomainWinSock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFErrorDomainWinSock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFErrorDomainWinSock"
        }
      ],
      "role": "symbol",
      "title": "kCFErrorDomainWinSock",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcferrordomainwinsock"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1494657-cferrorgetdomain": {
      "abstract": [
        {
          "text": "Returns the error domain for a given CFError.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFErrorGetDomain"
        },
        {
          "kind": "text",
          "text": "(CFError!) -> CFErrorDomain!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1494657-cferrorgetdomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFErrorGetDomain(_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1494657-cferrorgetdomain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/error-dictionary-keys"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFErrorDomainCFNetwork",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFErrorDomainWinSock"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFErrorDomainCFNetwork",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFErrorDomainWinSock"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/error-dictionary-keys"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFErrorDomainWinSock/title",
          "value": "kCFErrorDomainWinSock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFErrorDomainWinSock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFErrorDomainWinSock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors/title",
          "value": "CFNetworkErrors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFErrorDomainCFNetwork/title",
          "value": "kCFErrorDomainCFNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFErrorDomainCFNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFErrorDomainCFNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11494657-cferrorgetdomain/title",
          "value": "CFErrorGetDomain"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/error-domains"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/error-domains"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
