{
  "abstract": [
    {
      "text": "Networking-related keys that may be available in a ",
      "type": "text"
    },
    {
      "code": "CFErrorRef",
      "type": "codeVoice"
    },
    {
      "text": " object’s ",
      "type": "text"
    },
    {
      "code": "userInfo",
      "type": "codeVoice"
    },
    {
      "text": " dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/error-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Error Dictionary Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Many network functions return ",
              "type": "text"
            },
            {
              "code": "CFErrorRef",
              "type": "codeVoice"
            },
            {
              "text": " objects. When the error object’s domain is ",
              "type": "text"
            },
            {
              "code": "kCFErrorDomainCFNetwork",
              "type": "codeVoice"
            },
            {
              "text": ", you can query the object for additional information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if (CFEqual(CFErrorGetDomain(err), kCFErrorDomainCFNetwork) && CFErrorGetCode(err) == kCFHostErrorUnknown) {",
            " ",
            "    CFDictionaryRef userInfo = CFErrorCopyUserInfo(err);",
            " ",
            "    CFNumberRef number = (CFNumberRef) CFDictionaryGetValue(userInfo, kCFGetAddrInfoFailureKey);",
            " ",
            "    ...",
            " ",
            "    CFRelease(userInfo);",
            "}"
          ],
          "syntax": "objc",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors": {
      "abstract": [
        {
          "text": "This enumeration contains error codes returned under the error domain ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFErrorDomainCFNetwork",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkErrors"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkErrors"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/error-domains": {
      "abstract": [
        {
          "text": "High-level error domains.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/error-domains",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Domains",
      "type": "topic",
      "url": "/documentation/cfnetwork/error-domains"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFDNSServiceFailureKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFDNSServiceFailureKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFDNSServiceFailureKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFDNSServiceFailureKey"
        }
      ],
      "role": "symbol",
      "title": "kCFDNSServiceFailureKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfdnsservicefailurekey"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFErrorDomainCFNetwork": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFErrorDomainCFNetwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFErrorDomainCFNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFErrorDomainCFNetwork"
        }
      ],
      "role": "symbol",
      "title": "kCFErrorDomainCFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcferrordomaincfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFFTPStatusCodeKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFFTPStatusCodeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFFTPStatusCodeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFFTPStatusCodeKey"
        }
      ],
      "role": "symbol",
      "title": "kCFFTPStatusCodeKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfftpstatuscodekey"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFGetAddrInfoFailureKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFGetAddrInfoFailureKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFGetAddrInfoFailureKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFGetAddrInfoFailureKey"
        }
      ],
      "role": "symbol",
      "title": "kCFGetAddrInfoFailureKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfgetaddrinfofailurekey"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFSOCKSNegotiationMethodKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFSOCKSNegotiationMethodKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFSOCKSNegotiationMethodKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFSOCKSNegotiationMethodKey"
        }
      ],
      "role": "symbol",
      "title": "kCFSOCKSNegotiationMethodKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfsocksnegotiationmethodkey"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFSOCKSStatusCodeKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFSOCKSStatusCodeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFSOCKSStatusCodeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFSOCKSStatusCodeKey"
        }
      ],
      "role": "symbol",
      "title": "kCFSOCKSStatusCodeKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfsocksstatuscodekey"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFSOCKSVersionKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFSOCKSVersionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFSOCKSVersionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFSOCKSVersionKey"
        }
      ],
      "role": "symbol",
      "title": "kCFSOCKSVersionKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfsocksversionkey"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFURLErrorFailingURLErrorKey": {
      "abstract": [
        {
          "text": "The URL that caused the load to fail as a ",
          "type": "text"
        },
        {
          "code": "CFURLRef",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFURLErrorFailingURLErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFURLErrorFailingURLErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFURLErrorFailingURLErrorKey"
        }
      ],
      "role": "symbol",
      "title": "kCFURLErrorFailingURLErrorKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfurlerrorfailingurlerrorkey"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFURLErrorFailingURLStringErrorKey": {
      "abstract": [
        {
          "text": "The URL that caused the load to fail as a ",
          "type": "text"
        },
        {
          "code": "CFStringRef",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFURLErrorFailingURLStringErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFURLErrorFailingURLStringErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFURLErrorFailingURLStringErrorKey"
        }
      ],
      "role": "symbol",
      "title": "kCFURLErrorFailingURLStringErrorKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfurlerrorfailingurlstringerrorkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/error-domains"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFURLErrorFailingURLErrorKey",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFURLErrorFailingURLStringErrorKey",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFGetAddrInfoFailureKey",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFSOCKSStatusCodeKey",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFSOCKSVersionKey",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFSOCKSNegotiationMethodKey",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFDNSServiceFailureKey",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFFTPStatusCodeKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFURLErrorFailingURLErrorKey",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFURLErrorFailingURLStringErrorKey",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFGetAddrInfoFailureKey",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFSOCKSStatusCodeKey",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFSOCKSVersionKey",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFSOCKSNegotiationMethodKey",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFDNSServiceFailureKey",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFFTPStatusCodeKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/error-domains"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFDNSServiceFailureKey/title",
          "value": "kCFDNSServiceFailureKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFDNSServiceFailureKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFDNSServiceFailureKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFSOCKSVersionKey/title",
          "value": "kCFSOCKSVersionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFSOCKSVersionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFSOCKSVersionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors/title",
          "value": "CFNetworkErrors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFErrorDomainCFNetwork/title",
          "value": "kCFErrorDomainCFNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFErrorDomainCFNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFErrorDomainCFNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFURLErrorFailingURLStringErrorKey/title",
          "value": "kCFURLErrorFailingURLStringErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFURLErrorFailingURLStringErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFURLErrorFailingURLStringErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFGetAddrInfoFailureKey/title",
          "value": "kCFGetAddrInfoFailureKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFGetAddrInfoFailureKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFGetAddrInfoFailureKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFFTPStatusCodeKey/title",
          "value": "kCFFTPStatusCodeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFFTPStatusCodeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFFTPStatusCodeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFURLErrorFailingURLErrorKey/title",
          "value": "kCFURLErrorFailingURLErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFURLErrorFailingURLErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFURLErrorFailingURLErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFSOCKSNegotiationMethodKey/title",
          "value": "kCFSOCKSNegotiationMethodKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFSOCKSNegotiationMethodKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFSOCKSNegotiationMethodKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFSOCKSStatusCodeKey/title",
          "value": "kCFSOCKSStatusCodeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFSOCKSStatusCodeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFSOCKSStatusCodeKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/error-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/error-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
