{
  "abstract": [
    {
      "text": "Constants for keys in the global proxy settings dictionary returned by ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/global-proxy-settings-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Global Proxy Settings Constants"
  },
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)": {
      "abstract": [
        {
          "text": "Executes a proxy autoconfiguration script to determine the best proxy to use to retrieve a specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForAutoConfigurationScript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForAutoConfigurationScript"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkcopyproxiesforautoconfigurationscript(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)": {
      "abstract": [
        {
          "text": "Returns the list of proxies that should be used to download a given URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForURL"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkCopyProxiesForURL(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkcopyproxiesforurl(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()": {
      "abstract": [
        {
          "text": "Returns a CFDictionary containing the current systemwide internet proxy settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkCopySystemProxySettings"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkCopySystemProxySettings"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkCopySystemProxySettings()",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkcopysystemproxysettings()"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Downloads a proxy autoconfiguration script and executes it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationScript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFProxyAutoConfigurationResultCallback",
          "text": "CFProxyAutoConfigurationResultCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamClientContext",
          "text": "CFStreamClientContext"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopSourceRef",
          "text": "CFRunLoopSource"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationScript"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkexecuteproxyautoconfigurationscript(_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Downloads a proxy autoconfiguration script and executes it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFProxyAutoConfigurationResultCallback",
          "text": "CFProxyAutoConfigurationResultCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamClientContext",
          "text": "CFStreamClientContext"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopSourceRef",
          "text": "CFRunLoopSource"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationURL"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkexecuteproxyautoconfigurationurl(_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFProxyAutoConfigurationResultCallback": {
      "abstract": [
        {
          "text": "Callback function called when a proxy autoconfiguration computation has completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFProxyAutoConfigurationResultCallback"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFProxyAutoConfigurationResultCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFProxyAutoConfigurationResultCallback"
        }
      ],
      "role": "symbol",
      "title": "CFProxyAutoConfigurationResultCallback",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfproxyautoconfigurationresultcallback"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExceptionsList": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": " of ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " objects indicating host name patterns that should bypass the proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesExceptionsList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExceptionsList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesExceptionsList"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesExceptionsList",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesexceptionslist"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExcludeSimpleHostnames": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether simple host names are excluded. Simple host names are excluded if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesExcludeSimpleHostnames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExcludeSimpleHostnames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesExcludeSimpleHostnames"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesExcludeSimpleHostnames",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesexcludesimplehostnames"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPEnable": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether an FTP proxy is enabled. The proxy is enabled if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPEnable"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesFTPEnable",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesftpenable"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPassive": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether an FTP proxy’s passive mode is enabled. The passive mode is enabled if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPPassive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPassive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPPassive"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesFTPPassive",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesftppassive"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPort": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating the port number of an FTP proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPPort"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesFTPPort",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesftpport"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPProxy": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " object indicating the host name or IP number of an FTP proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPProxy"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesFTPProxy",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesftpproxy"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherEnable": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether a gopher proxy is enabled. The proxy is enabled if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesGopherEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesGopherEnable"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesGopherEnable",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesgopherenable"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherPort": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " indicating the port number of a gopher proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesGopherPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesGopherPort"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesGopherPort",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesgopherport"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherProxy": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " object indicating the host name or IP number of a gopher proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesGopherProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesGopherProxy"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesGopherProxy",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesgopherproxy"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPEnable": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether an HTTP proxy is enabled. The proxy is enabled if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPEnable"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesHTTPEnable",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxieshttpenable"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPPort": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing the port number associated with the HTTP proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPPort"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesHTTPPort",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxieshttpport"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPProxy": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " object containing the HTTP proxy host name or IP number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPProxy"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesHTTPProxy",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxieshttpproxy"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSEnable": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether an HTTPS proxy is enabled. The proxy is enabled if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPSEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPSEnable"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesHTTPSEnable",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxieshttpsenable"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSPort": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing the port number associated with the HTTPS proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPSPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPSPort"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesHTTPSPort",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxieshttpsport"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSProxy": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " object containing the HTTPS proxy host name or IP number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPSProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPSProxy"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesHTTPSProxy",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxieshttpsproxy"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoConfigEnable": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether proxy autoconfiguration is enabled. Proxy autoconfiguration is enabled if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesProxyAutoConfigEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoConfigEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesProxyAutoConfigEnable"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesProxyAutoConfigEnable",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesproxyautoconfigenable"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoConfigJavaScript": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " object that contains the full JavaScript source of the ProxyAutoConfig (PAC) file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesProxyAutoConfigJavaScript"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoConfigJavaScript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesProxyAutoConfigJavaScript"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesProxyAutoConfigJavaScript",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesproxyautoconfigjavascript"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoConfigURLString": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " object that contains the URL of the proxy autoconfiguration (PAC) file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesProxyAutoConfigURLString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoConfigURLString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesProxyAutoConfigURLString"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesProxyAutoConfigURLString",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesproxyautoconfigurlstring"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoDiscoveryEnable": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether proxy autodiscovery is enabled. Proxy autodiscovery is enabled if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesProxyAutoDiscoveryEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoDiscoveryEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesProxyAutoDiscoveryEnable"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesProxyAutoDiscoveryEnable",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesproxyautodiscoveryenable"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPEnable": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether an RTSP proxy is enabled. The proxy is enabled if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesRTSPEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesRTSPEnable"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesRTSPEnable",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesrtspenable"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPPort": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing the port number associated with the RTSP proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesRTSPPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesRTSPPort"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesRTSPPort",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesrtspport"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPProxy": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " object containing the RTSP proxy host name or IP number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesRTSPProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesRTSPProxy"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesRTSPProxy",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesrtspproxy"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesSOCKSEnable": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether a SOCKS proxy is enabled. The proxy is enabled if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesSOCKSEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesSOCKSEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesSOCKSEnable"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesSOCKSEnable",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiessocksenable"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesSOCKSPort": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing the port number associated with the SOCKS proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesSOCKSPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesSOCKSPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesSOCKSPort"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesSOCKSPort",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiessocksport"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesSOCKSProxy": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " object containing the SOCKS proxy host name or IP number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesSOCKSProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesSOCKSProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesSOCKSProxy"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesSOCKSProxy",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiessocksproxy"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/property-keys": {
      "abstract": [
        {
          "text": "Keys for calls to property get/set functions such as ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539615-cfreadstreamsetproperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/property-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Property Keys",
      "type": "topic",
      "url": "/documentation/cfnetwork/property-keys"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/proxy-types": {
      "abstract": [
        {
          "text": "Constants that specify the type of proxy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/proxy-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Proxy Types",
      "type": "topic",
      "url": "/documentation/cfnetwork/proxy-types"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1539615-cfreadstreamsetproperty": {
      "abstract": [
        {
          "text": "Sets the value of a property for a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamSetProperty"
        },
        {
          "kind": "text",
          "text": "(CFReadStream!, CFStreamPropertyKey!, CFTypeRef!) -> Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539615-cfreadstreamsetproperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFReadStreamSetProperty(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1539615-cfreadstreamsetproperty"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty": {
      "abstract": [
        {
          "text": "Returns the value of a property for a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamCopyProperty"
        },
        {
          "kind": "text",
          "text": "(CFReadStream!, CFStreamPropertyKey!) -> CFTypeRef!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFReadStreamCopyProperty(_:_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1539715-cfreadstreamcopyproperty"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Global-Proxy-Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFProxyAutoConfigurationResultCallback",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/property-keys",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/proxy-types"
      ],
      "title": "Global Proxy Configuration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExceptionsList",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExcludeSimpleHostnames",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPEnable",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPassive",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPort",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPProxy",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherEnable",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherPort",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherProxy",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPEnable",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPPort",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPProxy",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSEnable",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSPort",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSProxy",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPEnable",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPPort",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPProxy",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesSOCKSEnable",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesSOCKSPort",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesSOCKSProxy",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoConfigEnable",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoConfigJavaScript",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoConfigURLString",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoDiscoveryEnable"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExceptionsList",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExcludeSimpleHostnames",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPEnable",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPassive",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPort",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPProxy",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherEnable",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherPort",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherProxy",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPEnable",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPPort",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPProxy",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSEnable",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSPort",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSProxy",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPEnable",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPPort",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPProxy",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesSOCKSEnable",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesSOCKSPort",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesSOCKSProxy",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoConfigEnable",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoConfigJavaScript",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoConfigURLString",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesProxyAutoDiscoveryEnable"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Global-Proxy-Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFProxyAutoConfigurationResultCallback",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/property-keys",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/proxy-types"
              ],
              "title": "Global Proxy Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesExceptionsList/title",
          "value": "kCFNetworkProxiesExceptionsList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesExceptionsList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesExceptionsList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPSPort/title",
          "value": "kCFNetworkProxiesHTTPSPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPSPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesHTTPSPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesSOCKSEnable/title",
          "value": "kCFNetworkProxiesSOCKSEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesSOCKSEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesSOCKSEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesSOCKSProxy/title",
          "value": "kCFNetworkProxiesSOCKSProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesSOCKSProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesSOCKSProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11539715-cfreadstreamcopyproperty/title",
          "value": "CFReadStreamCopyProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopySystemProxySettings()/title",
          "value": "CFNetworkCopySystemProxySettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopySystemProxySettings()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkCopySystemProxySettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesProxyAutoConfigEnable/title",
          "value": "kCFNetworkProxiesProxyAutoConfigEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesProxyAutoConfigEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesProxyAutoConfigEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPPassive/title",
          "value": "kCFNetworkProxiesFTPPassive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPPassive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesFTPPassive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesGopherPort/title",
          "value": "kCFNetworkProxiesGopherPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesGopherPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesGopherPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPProxy/title",
          "value": "kCFNetworkProxiesFTPProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesFTPProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)/title",
          "value": "CFNetworkExecuteProxyAutoConfigurationURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkExecuteProxyAutoConfigurationURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesProxyAutoConfigJavaScript/title",
          "value": "kCFNetworkProxiesProxyAutoConfigJavaScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesProxyAutoConfigJavaScript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesProxyAutoConfigJavaScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPPort/title",
          "value": "kCFNetworkProxiesFTPPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesFTPPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPSEnable/title",
          "value": "kCFNetworkProxiesHTTPSEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPSEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesHTTPSEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesRTSPPort/title",
          "value": "kCFNetworkProxiesRTSPPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesRTSPPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesRTSPPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPProxy/title",
          "value": "kCFNetworkProxiesHTTPProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesHTTPProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesGopherEnable/title",
          "value": "kCFNetworkProxiesGopherEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesGopherEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesGopherEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPEnable/title",
          "value": "kCFNetworkProxiesFTPEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesFTPEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPPort/title",
          "value": "kCFNetworkProxiesHTTPPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesHTTPPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesRTSPProxy/title",
          "value": "kCFNetworkProxiesRTSPProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesRTSPProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesRTSPProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)/title",
          "value": "CFNetworkExecuteProxyAutoConfigurationScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkExecuteProxyAutoConfigurationScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesGopherProxy/title",
          "value": "kCFNetworkProxiesGopherProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesGopherProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesGopherProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)/title",
          "value": "CFNetworkCopyProxiesForAutoConfigurationScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkCopyProxiesForAutoConfigurationScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesRTSPEnable/title",
          "value": "kCFNetworkProxiesRTSPEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesRTSPEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesRTSPEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesExcludeSimpleHostnames/title",
          "value": "kCFNetworkProxiesExcludeSimpleHostnames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesExcludeSimpleHostnames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesExcludeSimpleHostnames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesProxyAutoConfigURLString/title",
          "value": "kCFNetworkProxiesProxyAutoConfigURLString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesProxyAutoConfigURLString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesProxyAutoConfigURLString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForURL(_:_:)/title",
          "value": "CFNetworkCopyProxiesForURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForURL(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkCopyProxiesForURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesProxyAutoDiscoveryEnable/title",
          "value": "kCFNetworkProxiesProxyAutoDiscoveryEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesProxyAutoDiscoveryEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesProxyAutoDiscoveryEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFProxyAutoConfigurationResultCallback/title",
          "value": "CFProxyAutoConfigurationResultCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFProxyAutoConfigurationResultCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFProxyAutoConfigurationResultCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFProxyAutoConfigurationResultCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFProxyAutoConfigurationResultCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPEnable/title",
          "value": "kCFNetworkProxiesHTTPEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesHTTPEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11539615-cfreadstreamsetproperty/title",
          "value": "CFReadStreamSetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPSProxy/title",
          "value": "kCFNetworkProxiesHTTPSProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPSProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesHTTPSProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesSOCKSPort/title",
          "value": "kCFNetworkProxiesSOCKSPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesSOCKSPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesSOCKSPort"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/global-proxy-settings-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/global-proxy-settings-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
