{
  "abstract": [
    {
      "text": "Specifies HTTP version 1.0.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPVersion1_0"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCFHTTPVersion1_0",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCFHTTPVersion1_0"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCFHTTPVersion1_0"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCFHTTPVersion1_0"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCFHTTPVersion1_0"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessage": {
      "abstract": [
        {
          "text": "An opaque reference representing an HTTP message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessage"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessage"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessage",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessage"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageAddAuthentication(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Adds authentication information to a request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageAddAuthentication"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageAddAuthentication(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageAddAuthentication"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageAddAuthentication(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessageaddauthentication(_:_:_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageAppendBytes(_:_:_:)": {
      "abstract": [
        {
          "text": "Appends data to a ",
          "type": "text"
        },
        {
          "code": "CFHTTPMessage",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageAppendBytes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageAppendBytes(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageAppendBytes"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageAppendBytes(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessageappendbytes(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageApplyCredentialDictionary(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Use a dictionary containing authentication credentials to perform the authentication method specified by a ",
          "type": "text"
        },
        {
          "code": "CFHTTPAuthentication",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageApplyCredentialDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageApplyCredentialDictionary(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageApplyCredentialDictionary"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageApplyCredentialDictionary(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessageapplycredentialdictionary(_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageApplyCredentials(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Performs the authentication method specified by a ",
          "type": "text"
        },
        {
          "code": "CFHTTPAuthentication",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageApplyCredentials"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageApplyCredentials(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageApplyCredentials"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageApplyCredentials(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessageapplycredentials(_:_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyAllHeaderFields(_:)": {
      "abstract": [
        {
          "text": "Gets all header fields from a ",
          "type": "text"
        },
        {
          "code": "CFHTTPMessage",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopyAllHeaderFields"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyAllHeaderFields(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopyAllHeaderFields"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageCopyAllHeaderFields(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessagecopyallheaderfields(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyBody(_:)": {
      "abstract": [
        {
          "text": "Gets the body from a ",
          "type": "text"
        },
        {
          "code": "CFHTTPMessage",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopyBody"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyBody(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopyBody"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageCopyBody(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessagecopybody(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyHeaderFieldValue(_:_:)": {
      "abstract": [
        {
          "text": "Gets the value of a header field from a ",
          "type": "text"
        },
        {
          "code": "CFHTTPMessage",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopyHeaderFieldValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyHeaderFieldValue(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopyHeaderFieldValue"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageCopyHeaderFieldValue(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessagecopyheaderfieldvalue(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyRequestMethod(_:)": {
      "abstract": [
        {
          "text": "Gets the request method from a ",
          "type": "text"
        },
        {
          "code": "CFHTTPMessage",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopyRequestMethod"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyRequestMethod(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopyRequestMethod"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageCopyRequestMethod(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessagecopyrequestmethod(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyRequestURL(_:)": {
      "abstract": [
        {
          "text": "Gets the URL from a ",
          "type": "text"
        },
        {
          "code": "CFHTTPMessage",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopyRequestURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyRequestURL(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopyRequestURL"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageCopyRequestURL(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessagecopyrequesturl(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyResponseStatusLine(_:)": {
      "abstract": [
        {
          "text": "Gets the status line from a ",
          "type": "text"
        },
        {
          "code": "CFHTTPMessage",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopyResponseStatusLine"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyResponseStatusLine(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopyResponseStatusLine"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageCopyResponseStatusLine(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessagecopyresponsestatusline(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopySerializedMessage(_:)": {
      "abstract": [
        {
          "text": "Serializes a CFHTTPMessage object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopySerializedMessage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopySerializedMessage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopySerializedMessage"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageCopySerializedMessage(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessagecopyserializedmessage(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyVersion(_:)": {
      "abstract": [
        {
          "text": "Gets the HTTP version from a ",
          "type": "text"
        },
        {
          "code": "CFHTTPMessage",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopyVersion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyVersion(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCopyVersion"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageCopyVersion(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessagecopyversion(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCreateCopy(_:_:)": {
      "abstract": [
        {
          "text": "Gets a copy of a CFHTTPMessage object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCreateCopy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCreateCopy(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCreateCopy"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageCreateCopy(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessagecreatecopy(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCreateEmpty(_:_:)": {
      "abstract": [
        {
          "text": "Creates and returns a new, empty ",
          "type": "text"
        },
        {
          "code": "CFHTTPMessage",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCreateEmpty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCreateEmpty(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPMessageCreateEmpty"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPMessageCreateEmpty(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpmessagecreateempty(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPVersion1_0": {
      "abstract": [
        {
          "text": "Specifies HTTP version 1.0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFHTTPVersion1_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPVersion1_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFHTTPVersion1_0"
        }
      ],
      "role": "symbol",
      "title": "kCFHTTPVersion1_0",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfhttpversion1_0"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "HTTP-Messages",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessage",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageAddAuthentication(_:_:_:_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageAppendBytes(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageApplyCredentialDictionary(_:_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageApplyCredentials(_:_:_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyAllHeaderFields(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyBody(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyHeaderFieldValue(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyRequestMethod(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyRequestURL(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyResponseStatusLine(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopySerializedMessage(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyVersion(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCreateCopy(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCreateEmpty(_:_:)"
      ],
      "title": "HTTP Messages"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCFHTTPVersion1_0"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHTTPVersion1_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "HTTP-Messages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessage",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageAddAuthentication(_:_:_:_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageAppendBytes(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageApplyCredentialDictionary(_:_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageApplyCredentials(_:_:_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyAllHeaderFields(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyBody(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyHeaderFieldValue(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyRequestMethod(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyRequestURL(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyResponseStatusLine(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopySerializedMessage(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCopyVersion(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCreateCopy(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPMessageCreateEmpty(_:_:)"
              ],
              "title": "HTTP Messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCFHTTPVersion1_0"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopyHeaderFieldValue(_:_:)/title",
          "value": "CFHTTPMessageCopyHeaderFieldValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopyHeaderFieldValue(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageCopyHeaderFieldValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopyVersion(_:)/title",
          "value": "CFHTTPMessageCopyVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopyVersion(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageCopyVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopyRequestMethod(_:)/title",
          "value": "CFHTTPMessageCopyRequestMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopyRequestMethod(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageCopyRequestMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCreateCopy(_:_:)/title",
          "value": "CFHTTPMessageCreateCopy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCreateCopy(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageCreateCopy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageAddAuthentication(_:_:_:_:_:_:)/title",
          "value": "CFHTTPMessageAddAuthentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageAddAuthentication(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageAddAuthentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopySerializedMessage(_:)/title",
          "value": "CFHTTPMessageCopySerializedMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopySerializedMessage(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageCopySerializedMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCreateEmpty(_:_:)/title",
          "value": "CFHTTPMessageCreateEmpty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCreateEmpty(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageCreateEmpty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopyResponseStatusLine(_:)/title",
          "value": "CFHTTPMessageCopyResponseStatusLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopyResponseStatusLine(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageCopyResponseStatusLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessage/title",
          "value": "CFHTTPMessageRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageAppendBytes(_:_:_:)/title",
          "value": "CFHTTPMessageAppendBytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageAppendBytes(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageAppendBytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageApplyCredentials(_:_:_:_:_:)/title",
          "value": "CFHTTPMessageApplyCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageApplyCredentials(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageApplyCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageApplyCredentialDictionary(_:_:_:_:)/title",
          "value": "CFHTTPMessageApplyCredentialDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageApplyCredentialDictionary(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageApplyCredentialDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopyAllHeaderFields(_:)/title",
          "value": "CFHTTPMessageCopyAllHeaderFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopyAllHeaderFields(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageCopyAllHeaderFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopyRequestURL(_:)/title",
          "value": "CFHTTPMessageCopyRequestURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopyRequestURL(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageCopyRequestURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPVersion1_0/title",
          "value": "kCFHTTPVersion1_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPVersion1_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHTTPVersion1_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopyBody(_:)/title",
          "value": "CFHTTPMessageCopyBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPMessageCopyBody(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPMessageCopyBody"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/kcfhttpversion1_0"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/kcfhttpversion1_0"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
