{
  "abstract": [
    {
      "text": "Request the HTTP Negotiate authentication scheme.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeNegotiate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCFHTTPAuthenticationSchemeNegotiate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCFHTTPAuthenticationSchemeNegotiate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCFHTTPAuthenticationSchemeNegotiate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCFHTTPAuthenticationSchemeNegotiate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCFHTTPAuthenticationSchemeNegotiate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthentication": {
      "abstract": [
        {
          "text": "An opaque reference representing HTTP authentication information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthentication"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthentication"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthentication",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthentication"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationAppliesToRequest(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a CFHTTPAuthentication object is associated with a CFHTTPMessage object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationAppliesToRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationAppliesToRequest(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationAppliesToRequest"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationAppliesToRequest(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationappliestorequest(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyDomains(_:)": {
      "abstract": [
        {
          "text": "Returns an array of domain URLs to which a given CFHTTPAuthentication object can be applied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCopyDomains"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyDomains(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCopyDomains"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationCopyDomains(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationcopydomains(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyMethod(_:)": {
      "abstract": [
        {
          "text": "Gets the strongest authentication method that will be used when a CFHTTPAuthentication object is applied to a request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCopyMethod"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyMethod(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCopyMethod"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationCopyMethod(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationcopymethod(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyRealm(_:)": {
      "abstract": [
        {
          "text": "Gets an authentication information’s namespace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCopyRealm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyRealm(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCopyRealm"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationCopyRealm(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationcopyrealm(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCreateFromResponse(_:_:)": {
      "abstract": [
        {
          "text": "Uses an authentication failure response to create a CFHTTPAuthentication object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCreateFromResponse"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCreateFromResponse(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationCreateFromResponse"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationCreateFromResponse(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationcreatefromresponse(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationGetTypeID()": {
      "abstract": [
        {
          "text": "Gets the Core Foundation type identifier for the CFHTTPAuthentication opaque type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationGetTypeID()",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationgettypeid()"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationIsValid(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a CFHTTPAuthentication object is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationIsValid"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamError",
          "text": "CFStreamError"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationIsValid(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationIsValid"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationIsValid(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationisvalid(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresAccountDomain(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a CFHTTPAuthentication object uses an authentication method that requires an account domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationRequiresAccountDomain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresAccountDomain(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationRequiresAccountDomain"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationRequiresAccountDomain(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationrequiresaccountdomain(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresOrderedRequests(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether authentication requests should be made one at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationRequiresOrderedRequests"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresOrderedRequests(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationRequiresOrderedRequests"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationRequiresOrderedRequests(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationrequiresorderedrequests(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresUserNameAndPassword(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a CFHTTPAuthentication object uses an authentication method that requires a username and a password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationRequiresUserNameAndPassword"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPAuthenticationRef",
          "text": "CFHTTPAuthentication"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresUserNameAndPassword(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHTTPAuthenticationRequiresUserNameAndPassword"
        }
      ],
      "role": "symbol",
      "title": "CFHTTPAuthenticationRequiresUserNameAndPassword(_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhttpauthenticationrequiresusernameandpassword(_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationAccountDomain": {
      "abstract": [
        {
          "text": "Account domain to use for authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationAccountDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationAccountDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationAccountDomain"
        }
      ],
      "role": "symbol",
      "title": "kCFHTTPAuthenticationAccountDomain",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfhttpauthenticationaccountdomain"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationPassword": {
      "abstract": [
        {
          "text": "Password to use for authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationPassword",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationPassword"
        }
      ],
      "role": "symbol",
      "title": "kCFHTTPAuthenticationPassword",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfhttpauthenticationpassword"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeBasic": {
      "abstract": [
        {
          "text": "Request the HTTP basic authentication scheme.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationSchemeBasic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeBasic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationSchemeBasic"
        }
      ],
      "role": "symbol",
      "title": "kCFHTTPAuthenticationSchemeBasic",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfhttpauthenticationschemebasic"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeDigest": {
      "abstract": [
        {
          "text": "Request the HTTP digest authentication scheme.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationSchemeDigest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeDigest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationSchemeDigest"
        }
      ],
      "role": "symbol",
      "title": "kCFHTTPAuthenticationSchemeDigest",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfhttpauthenticationschemedigest"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeNegotiate": {
      "abstract": [
        {
          "text": "Request the HTTP Negotiate authentication scheme.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationSchemeNegotiate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeNegotiate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFHTTPAuthenticationSchemeNegotiate"
        }
      ],
      "role": "symbol",
      "title": "kCFHTTPAuthenticationSchemeNegotiate",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfhttpauthenticationschemenegotiate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "HTTP-Authentication",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthentication",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationAppliesToRequest(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyDomains(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyMethod(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyRealm(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCreateFromResponse(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationGetTypeID()",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationIsValid(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresAccountDomain(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresOrderedRequests(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresUserNameAndPassword(_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationAccountDomain",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationPassword",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeBasic",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeDigest"
      ],
      "title": "HTTP Authentication"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCFHTTPAuthenticationSchemeNegotiate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHTTPAuthenticationSchemeNegotiate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "HTTP-Authentication",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthentication",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationAppliesToRequest(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyDomains(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyMethod(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCopyRealm(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationCreateFromResponse(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationGetTypeID()",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationIsValid(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresAccountDomain(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresOrderedRequests(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHTTPAuthenticationRequiresUserNameAndPassword(_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationAccountDomain",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationPassword",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeBasic",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPAuthenticationSchemeDigest"
              ],
              "title": "HTTP Authentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCFHTTPAuthenticationSchemeNegotiate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationRequiresAccountDomain(_:)/title",
          "value": "CFHTTPAuthenticationRequiresAccountDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationRequiresAccountDomain(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationRequiresAccountDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCopyRealm(_:)/title",
          "value": "CFHTTPAuthenticationCopyRealm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCopyRealm(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationCopyRealm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCreateFromResponse(_:_:)/title",
          "value": "CFHTTPAuthenticationCreateFromResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCreateFromResponse(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationCreateFromResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationSchemeDigest/title",
          "value": "kCFHTTPAuthenticationSchemeDigest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationSchemeDigest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHTTPAuthenticationSchemeDigest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationIsValid(_:_:)/title",
          "value": "CFHTTPAuthenticationIsValid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationIsValid(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationIsValid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationSchemeNegotiate/title",
          "value": "kCFHTTPAuthenticationSchemeNegotiate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationSchemeNegotiate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHTTPAuthenticationSchemeNegotiate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationGetTypeID()/title",
          "value": "CFHTTPAuthenticationGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationRequiresUserNameAndPassword(_:)/title",
          "value": "CFHTTPAuthenticationRequiresUserNameAndPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationRequiresUserNameAndPassword(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationRequiresUserNameAndPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCopyMethod(_:)/title",
          "value": "CFHTTPAuthenticationCopyMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCopyMethod(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationCopyMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationSchemeBasic/title",
          "value": "kCFHTTPAuthenticationSchemeBasic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationSchemeBasic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHTTPAuthenticationSchemeBasic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthentication/title",
          "value": "CFHTTPAuthenticationRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthentication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationAccountDomain/title",
          "value": "kCFHTTPAuthenticationAccountDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationAccountDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHTTPAuthenticationAccountDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCopyDomains(_:)/title",
          "value": "CFHTTPAuthenticationCopyDomains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationCopyDomains(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationCopyDomains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationAppliesToRequest(_:_:)/title",
          "value": "CFHTTPAuthenticationAppliesToRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationAppliesToRequest(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationAppliesToRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationPassword/title",
          "value": "kCFHTTPAuthenticationPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPAuthenticationPassword/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHTTPAuthenticationPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationRequiresOrderedRequests(_:)/title",
          "value": "CFHTTPAuthenticationRequiresOrderedRequests"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHTTPAuthenticationRequiresOrderedRequests(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHTTPAuthenticationRequiresOrderedRequests"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/kcfhttpauthenticationschemenegotiate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/kcfhttpauthenticationschemenegotiate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
