{
  "abstract": [
    {
      "text": "Value is a ",
      "type": "text"
    },
    {
      "code": "CFNumber",
      "type": "codeVoice"
    },
    {
      "text": " indicating the port number of a gopher proxy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherPort"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCFNetworkProxiesGopherPort",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCFNetworkProxiesGopherPort"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCFNetworkProxiesGopherPort"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCFNetworkProxiesGopherPort"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesGopherPort"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExceptionsList": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": " of ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " objects indicating host name patterns that should bypass the proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesExceptionsList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExceptionsList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesExceptionsList"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesExceptionsList",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesexceptionslist"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExcludeSimpleHostnames": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether simple host names are excluded. Simple host names are excluded if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesExcludeSimpleHostnames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExcludeSimpleHostnames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesExcludeSimpleHostnames"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesExcludeSimpleHostnames",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesexcludesimplehostnames"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPEnable": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether an FTP proxy is enabled. The proxy is enabled if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPEnable"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesFTPEnable",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesftpenable"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPassive": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether an FTP proxy’s passive mode is enabled. The passive mode is enabled if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPPassive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPassive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPPassive"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesFTPPassive",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesftppassive"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPort": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating the port number of an FTP proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPPort"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesFTPPort",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesftpport"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPProxy": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " object indicating the host name or IP number of an FTP proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesFTPProxy"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesFTPProxy",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesftpproxy"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherEnable": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether a gopher proxy is enabled. The proxy is enabled if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesGopherEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesGopherEnable"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesGopherEnable",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesgopherenable"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherPort": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " indicating the port number of a gopher proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesGopherPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesGopherPort"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesGopherPort",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesgopherport"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherProxy": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " object indicating the host name or IP number of a gopher proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesGopherProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesGopherProxy"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesGopherProxy",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesgopherproxy"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPEnable": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether an HTTP proxy is enabled. The proxy is enabled if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPEnable"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesHTTPEnable",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxieshttpenable"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPPort": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing the port number associated with the HTTP proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPPort"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesHTTPPort",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxieshttpport"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPProxy": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " object containing the HTTP proxy host name or IP number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPProxy"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesHTTPProxy",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxieshttpproxy"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSEnable": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether an HTTPS proxy is enabled. The proxy is enabled if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPSEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPSEnable"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesHTTPSEnable",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxieshttpsenable"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSPort": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing the port number associated with the HTTPS proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPSPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPSPort"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesHTTPSPort",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxieshttpsport"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSProxy": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": " object containing the HTTPS proxy host name or IP number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPSProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesHTTPSProxy"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesHTTPSProxy",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxieshttpsproxy"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPEnable": {
      "abstract": [
        {
          "text": "Value is a ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " object indicating whether an RTSP proxy is enabled. The proxy is enabled if the key is present and the associated value is nonzero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesRTSPEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFNetworkProxiesRTSPEnable"
        }
      ],
      "role": "symbol",
      "title": "kCFNetworkProxiesRTSPEnable",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfnetworkproxiesrtspenable"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExceptionsList",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExcludeSimpleHostnames",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPEnable",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPassive",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPort",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPProxy",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherEnable",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherProxy",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPEnable",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPPort",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPProxy",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSEnable",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSPort",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSProxy",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPEnable"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCFNetworkProxiesGopherPort"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesGopherPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExceptionsList",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesExcludeSimpleHostnames",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPEnable",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPassive",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPPort",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesFTPProxy",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherEnable",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesGopherProxy",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPEnable",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPPort",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPProxy",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSEnable",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSPort",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesHTTPSProxy",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFNetworkProxiesRTSPEnable"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCFNetworkProxiesGopherPort"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPPassive/title",
          "value": "kCFNetworkProxiesFTPPassive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPPassive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesFTPPassive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesGopherProxy/title",
          "value": "kCFNetworkProxiesGopherProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesGopherProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesGopherProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesExcludeSimpleHostnames/title",
          "value": "kCFNetworkProxiesExcludeSimpleHostnames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesExcludeSimpleHostnames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesExcludeSimpleHostnames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesExceptionsList/title",
          "value": "kCFNetworkProxiesExceptionsList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesExceptionsList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesExceptionsList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPSPort/title",
          "value": "kCFNetworkProxiesHTTPSPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPSPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesHTTPSPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPPort/title",
          "value": "kCFNetworkProxiesFTPPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesFTPPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPSProxy/title",
          "value": "kCFNetworkProxiesHTTPSProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPSProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesHTTPSProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPPort/title",
          "value": "kCFNetworkProxiesHTTPPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesHTTPPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPEnable/title",
          "value": "kCFNetworkProxiesFTPEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesFTPEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesRTSPEnable/title",
          "value": "kCFNetworkProxiesRTSPEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesRTSPEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesRTSPEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesGopherEnable/title",
          "value": "kCFNetworkProxiesGopherEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesGopherEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesGopherEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPEnable/title",
          "value": "kCFNetworkProxiesHTTPEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesHTTPEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPProxy/title",
          "value": "kCFNetworkProxiesFTPProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesFTPProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesFTPProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPProxy/title",
          "value": "kCFNetworkProxiesHTTPProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesHTTPProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPSEnable/title",
          "value": "kCFNetworkProxiesHTTPSEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesHTTPSEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesHTTPSEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesGopherPort/title",
          "value": "kCFNetworkProxiesGopherPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFNetworkProxiesGopherPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFNetworkProxiesGopherPort"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/kcfnetworkproxiesgopherport"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/kcfnetworkproxiesgopherport"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
