{
  "abstract": [
    {
      "text": "Specifies an HTTP proxy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeHTTP"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCFProxyTypeHTTP",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCFProxyTypeHTTP"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCFProxyTypeHTTP"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCFProxyTypeHTTP"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCFProxyTypeHTTP"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationJavaScript": {
      "abstract": [
        {
          "text": "Specifies that the proxy is determined by a provided autoconfiguration script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyTypeAutoConfigurationJavaScript"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationJavaScript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyTypeAutoConfigurationJavaScript"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyTypeAutoConfigurationJavaScript",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxytypeautoconfigurationjavascript"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationURL": {
      "abstract": [
        {
          "text": "Specifies that the proxy is determined by an autoconfiguration file at a given URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyTypeAutoConfigurationURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyTypeAutoConfigurationURL"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyTypeAutoConfigurationURL",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxytypeautoconfigurationurl"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeFTP": {
      "abstract": [
        {
          "text": "Specifies an FTP proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyTypeFTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeFTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyTypeFTP"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyTypeFTP",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxytypeftp"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeHTTP": {
      "abstract": [
        {
          "text": "Specifies an HTTP proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyTypeHTTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeHTTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyTypeHTTP"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyTypeHTTP",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxytypehttp"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeHTTPS": {
      "abstract": [
        {
          "text": "Specifies an HTTPS proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyTypeHTTPS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeHTTPS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyTypeHTTPS"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyTypeHTTPS",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxytypehttps"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeNone": {
      "abstract": [
        {
          "text": "Specifies that no proxy should be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyTypeNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyTypeNone"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyTypeNone",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxytypenone"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeSOCKS": {
      "abstract": [
        {
          "text": "Specifies a SOCKS proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyTypeSOCKS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeSOCKS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyTypeSOCKS"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyTypeSOCKS",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxytypesocks"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeNone",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationURL",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationJavaScript",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeFTP",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeHTTPS",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeSOCKS"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCFProxyTypeHTTP"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeHTTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeNone",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationURL",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationJavaScript",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeFTP",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeHTTPS",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeSOCKS"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCFProxyTypeHTTP"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeHTTPS/title",
          "value": "kCFProxyTypeHTTPS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeHTTPS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeHTTPS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeHTTP/title",
          "value": "kCFProxyTypeHTTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeHTTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeHTTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeFTP/title",
          "value": "kCFProxyTypeFTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeFTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeFTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeSOCKS/title",
          "value": "kCFProxyTypeSOCKS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeSOCKS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeSOCKS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeAutoConfigurationURL/title",
          "value": "kCFProxyTypeAutoConfigurationURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeAutoConfigurationURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeAutoConfigurationURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeAutoConfigurationJavaScript/title",
          "value": "kCFProxyTypeAutoConfigurationJavaScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeAutoConfigurationJavaScript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeAutoConfigurationJavaScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeNone/title",
          "value": "kCFProxyTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeNone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/kcfproxytypehttp"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/kcfproxytypehttp"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
