{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether connections may use the network when the user has specified Low Data Mode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyAllowConstrainedNetworkAccess"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCFStreamPropertyAllowConstrainedNetworkAccess",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCFStreamPropertyAllowConstrainedNetworkAccess"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCFStreamPropertyAllowConstrainedNetworkAccess"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCFStreamPropertyAllowConstrainedNetworkAccess"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyAllowConstrainedNetworkAccess"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and allows the use of constrained interfaces. Set this property to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to disallow the use of constrained interfaces. For more information about constrained interfaces, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/urlsessionconfiguration/3235751-allowsconstrainednetworkaccess",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPVersion3_0": {
      "abstract": [
        {
          "text": "HTTP version 3.0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFHTTPVersion3_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPVersion3_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFHTTPVersion3_0"
        }
      ],
      "role": "symbol",
      "title": "kCFHTTPVersion3_0",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfhttpversion3_0"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeAVStreaming": {
      "abstract": [
        {
          "text": "A multimedia audio and video streaming service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamNetworkServiceTypeAVStreaming"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeAVStreaming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamNetworkServiceTypeAVStreaming"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamNetworkServiceTypeAVStreaming",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamnetworkservicetypeavstreaming"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveAV": {
      "abstract": [
        {
          "text": "A responsive, time-sensitive, multimedia audio and video service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamNetworkServiceTypeResponsiveAV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveAV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamNetworkServiceTypeResponsiveAV"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamNetworkServiceTypeResponsiveAV",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamnetworkservicetyperesponsiveav"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveData": {
      "abstract": [
        {
          "text": "A responsive, time-sensitive data service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamNetworkServiceTypeResponsiveData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamNetworkServiceTypeResponsiveData"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamNetworkServiceTypeResponsiveData",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamnetworkservicetyperesponsivedata"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyAllowConstrainedNetworkAccess": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether connections may use the network when the user has specified Low Data Mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyAllowConstrainedNetworkAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyAllowConstrainedNetworkAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyAllowConstrainedNetworkAccess"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyAllowConstrainedNetworkAccess",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyallowconstrainednetworkaccess"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyAllowExpensiveNetworkAccess": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether connections may use a network interface that the system considers expensive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyAllowExpensiveNetworkAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyAllowExpensiveNetworkAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyAllowExpensiveNetworkAccess"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyAllowExpensiveNetworkAccess",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyallowexpensivenetworkaccess"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyConnectionIsExpensive": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if the connection is using a network interface that the system considers expensive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyConnectionIsExpensive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyConnectionIsExpensive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyConnectionIsExpensive"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyConnectionIsExpensive",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyconnectionisexpensive"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse": {
      "abstract": [
        {
          "text": "Boolean false value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFBooleanFalse"
        },
        {
          "kind": "text",
          "text": ": CFBoolean!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleanfalse",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFBooleanFalse",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfbooleanfalse"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue": {
      "abstract": [
        {
          "text": "Boolean true value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFBooleanTrue"
        },
        {
          "kind": "text",
          "text": ": CFBoolean!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFBooleanTrue",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfbooleantrue"
    },
    "doc://com.apple.documentation/documentation/foundation/urlsessionconfiguration/3235751-allowsconstrainednetworkaccess": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether connections may use the network when the user has specified Low Data Mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "allowsConstrainedNetworkAccess"
        },
        {
          "kind": "text",
          "text": ": Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/urlsessionconfiguration/3235751-allowsconstrainednetworkaccess",
      "kind": "symbol",
      "role": "symbol",
      "title": "allowsConstrainedNetworkAccess",
      "type": "topic",
      "url": "/documentation/foundation/urlsessionconfiguration/3235751-allowsconstrainednetworkaccess"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPVersion3_0",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeAVStreaming",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveAV",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveData",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyAllowExpensiveNetworkAccess",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyConnectionIsExpensive"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCFStreamPropertyAllowConstrainedNetworkAccess"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyAllowConstrainedNetworkAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFHTTPVersion3_0",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeAVStreaming",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveAV",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamNetworkServiceTypeResponsiveData",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyAllowExpensiveNetworkAccess",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyConnectionIsExpensive"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCFStreamPropertyAllowConstrainedNetworkAccess"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPVersion3_0/title",
          "value": "kCFHTTPVersion3_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFHTTPVersion3_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHTTPVersion3_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamNetworkServiceTypeResponsiveAV/title",
          "value": "kCFStreamNetworkServiceTypeResponsiveAV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamNetworkServiceTypeResponsiveAV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamNetworkServiceTypeResponsiveAV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyAllowExpensiveNetworkAccess/title",
          "value": "kCFStreamPropertyAllowExpensiveNetworkAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyAllowExpensiveNetworkAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyAllowExpensiveNetworkAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamNetworkServiceTypeResponsiveData/title",
          "value": "kCFStreamNetworkServiceTypeResponsiveData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamNetworkServiceTypeResponsiveData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamNetworkServiceTypeResponsiveData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyAllowConstrainedNetworkAccess/title",
          "value": "kCFStreamPropertyAllowConstrainedNetworkAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyAllowConstrainedNetworkAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyAllowConstrainedNetworkAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamNetworkServiceTypeAVStreaming/title",
          "value": "kCFStreamNetworkServiceTypeAVStreaming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamNetworkServiceTypeAVStreaming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamNetworkServiceTypeAVStreaming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyConnectionIsExpensive/title",
          "value": "kCFStreamPropertyConnectionIsExpensive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyConnectionIsExpensive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyConnectionIsExpensive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/kcfstreampropertyallowconstrainednetworkaccess"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/kcfstreampropertyallowconstrainednetworkaccess"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
