{
  "abstract": [
    {
      "text": "Security property key whose value indicates whether root certificates should be allowed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamSSLAllowsAnyRoot"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCFStreamSSLAllowsAnyRoot",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCFStreamSSLAllowsAnyRoot"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCFStreamSSLAllowsAnyRoot"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCFStreamSSLAllowsAnyRoot"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCFStreamSSLAllowsAnyRoot"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By default, the value of this key is ",
              "type": "text"
            },
            {
              "code": "kCFBooleanFalse",
              "type": "codeVoice"
            },
            {
              "text": " (root certificates are not allowed).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForHTTPRequest(_:_:)": {
      "abstract": [
        {
          "text": "Creates a read stream for a CFHTTP request message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamCreateForHTTPRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFReadStreamRef",
          "text": "CFReadStream"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForHTTPRequest(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFReadStreamCreateForHTTPRequest"
        }
      ],
      "role": "symbol",
      "title": "CFReadStreamCreateForHTTPRequest(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfreadstreamcreateforhttprequest(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForStreamedHTTPRequest(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a read stream for a CFHTTP request message object whose body is too long to keep in memory.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamCreateForStreamedHTTPRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFHTTPMessageRef",
          "text": "CFHTTPMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFReadStreamRef",
          "text": "CFReadStream"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFReadStreamRef",
          "text": "CFReadStream"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForStreamedHTTPRequest(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFReadStreamCreateForStreamedHTTPRequest"
        }
      ],
      "role": "symbol",
      "title": "CFReadStreamCreateForStreamedHTTPRequest(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfreadstreamcreateforstreamedhttprequest(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateWithFTPURL(_:_:)": {
      "abstract": [
        {
          "text": "Creates an FTP read stream.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamCreateWithFTPURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFReadStreamRef",
          "text": "CFReadStream"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateWithFTPURL(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFReadStreamCreateWithFTPURL"
        }
      ],
      "role": "symbol",
      "title": "CFReadStreamCreateWithFTPURL(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfreadstreamcreatewithftpurl(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFWriteStreamCreateWithFTPURL(_:_:)": {
      "abstract": [
        {
          "text": "Creates an FTP write stream.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFWriteStreamCreateWithFTPURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFWriteStreamRef",
          "text": "CFWriteStream"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFWriteStreamCreateWithFTPURL(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFWriteStreamCreateWithFTPURL"
        }
      ],
      "role": "symbol",
      "title": "CFWriteStreamCreateWithFTPURL(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfwritestreamcreatewithftpurl(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPAttemptPersistentConnection": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPAttemptPersistentConnection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPAttemptPersistentConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPAttemptPersistentConnection"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPAttemptPersistentConnection",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpattemptpersistentconnection"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalRequest": {
      "abstract": [
        {
          "text": "HTTP Final Request property. A value of type CFHTTPMessage containing the final message transmitted by the stream after all modifications (including authentication, connection policy, redirects, and so on) have been made. This property cannot be set.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPFinalRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPFinalRequest"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPFinalRequest",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpfinalrequest"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalURL": {
      "abstract": [
        {
          "text": "HTTP Final URL property. A value of type CFURL containing the final HTTP URL. This value differs from the URL in the original HTTP request if an autoredirection occurred. This property cannot be set.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPFinalURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPFinalURL"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPFinalURL",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpfinalurl"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxy": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPProxy"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPProxy",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpproxy"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyHost": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPProxyHost"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyHost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPProxyHost"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPProxyHost",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpproxyhost"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyPort": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPProxyPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPProxyPort"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPProxyPort",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpproxyport"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPRequestBytesWrittenCount": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPRequestBytesWrittenCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPRequestBytesWrittenCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPRequestBytesWrittenCount"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPRequestBytesWrittenCount",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttprequestbyteswrittencount"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPResponseHeader": {
      "abstract": [
        {
          "text": "HTTP Response Header property. When copied by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", the header of an HTTP response message is returned.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPResponseHeader"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPResponseHeader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPResponseHeader"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPResponseHeader",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpresponseheader"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyHost": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPSProxyHost"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyHost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPSProxyHost"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPSProxyHost",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpsproxyhost"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyPort": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPSProxyPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPSProxyPort"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPSProxyPort",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpsproxyport"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPShouldAutoredirect": {
      "abstract": [
        {
          "text": "HTTP Should Auto Redirect property. Set this property to ",
          "type": "text"
        },
        {
          "code": "kCFBooleanTrue",
          "type": "codeVoice"
        },
        {
          "text": " to enable autoredirection; set this property to ",
          "type": "text"
        },
        {
          "code": "kCFBooleanFalse",
          "type": "codeVoice"
        },
        {
          "text": " to disable autoredirection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPShouldAutoredirect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPShouldAutoredirect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamPropertyHTTPShouldAutoredirect"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamPropertyHTTPShouldAutoredirect",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreampropertyhttpshouldautoredirect"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamSSLAllowsAnyRoot": {
      "abstract": [
        {
          "text": "Security property key whose value indicates whether root certificates should be allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamSSLAllowsAnyRoot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamSSLAllowsAnyRoot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamSSLAllowsAnyRoot"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamSSLAllowsAnyRoot",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamsslallowsanyroot"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty": {
      "abstract": [
        {
          "text": "Returns the value of a property for a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamCopyProperty"
        },
        {
          "kind": "text",
          "text": "(CFReadStream!, CFStreamPropertyKey!) -> CFTypeRef!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFReadStreamCopyProperty(_:_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1539715-cfreadstreamcopyproperty"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Streams",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForHTTPRequest(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForStreamedHTTPRequest(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPAttemptPersistentConnection",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalRequest",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalURL",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxy",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyHost",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyPort",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPRequestBytesWrittenCount",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPResponseHeader",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyHost",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyPort",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPShouldAutoredirect",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFWriteStreamCreateWithFTPURL(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateWithFTPURL(_:_:)"
      ],
      "title": "Streams"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "4.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "4.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.6",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCFStreamSSLAllowsAnyRoot"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamSSLAllowsAnyRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Streams",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForHTTPRequest(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateForStreamedHTTPRequest(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPAttemptPersistentConnection",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalRequest",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPFinalURL",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxy",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyHost",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPProxyPort",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPRequestBytesWrittenCount",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPResponseHeader",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyHost",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPSProxyPort",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamPropertyHTTPShouldAutoredirect",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFWriteStreamCreateWithFTPURL(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFReadStreamCreateWithFTPURL(_:_:)"
              ],
              "title": "Streams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCFStreamSSLAllowsAnyRoot"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFWriteStreamCreateWithFTPURL(_:_:)/title",
          "value": "CFWriteStreamCreateWithFTPURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFWriteStreamCreateWithFTPURL(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFWriteStreamCreateWithFTPURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamSSLAllowsAnyRoot/title",
          "value": "kCFStreamSSLAllowsAnyRoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamSSLAllowsAnyRoot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamSSLAllowsAnyRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPAttemptPersistentConnection/title",
          "value": "kCFStreamPropertyHTTPAttemptPersistentConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPAttemptPersistentConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPAttemptPersistentConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPProxyHost/title",
          "value": "kCFStreamPropertyHTTPProxyHost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPProxyHost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPProxyHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFReadStreamCreateForStreamedHTTPRequest(_:_:_:)/title",
          "value": "CFReadStreamCreateForStreamedHTTPRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFReadStreamCreateForStreamedHTTPRequest(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFReadStreamCreateForStreamedHTTPRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPSProxyPort/title",
          "value": "kCFStreamPropertyHTTPSProxyPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPSProxyPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPSProxyPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPFinalRequest/title",
          "value": "kCFStreamPropertyHTTPFinalRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPFinalRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPFinalRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPFinalURL/title",
          "value": "kCFStreamPropertyHTTPFinalURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPFinalURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPFinalURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPProxyPort/title",
          "value": "kCFStreamPropertyHTTPProxyPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPProxyPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPProxyPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFReadStreamCreateWithFTPURL(_:_:)/title",
          "value": "CFReadStreamCreateWithFTPURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFReadStreamCreateWithFTPURL(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFReadStreamCreateWithFTPURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPRequestBytesWrittenCount/title",
          "value": "kCFStreamPropertyHTTPRequestBytesWrittenCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPRequestBytesWrittenCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPRequestBytesWrittenCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPSProxyHost/title",
          "value": "kCFStreamPropertyHTTPSProxyHost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPSProxyHost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPSProxyHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPShouldAutoredirect/title",
          "value": "kCFStreamPropertyHTTPShouldAutoredirect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPShouldAutoredirect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPShouldAutoredirect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFReadStreamCreateForHTTPRequest(_:_:)/title",
          "value": "CFReadStreamCreateForHTTPRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFReadStreamCreateForHTTPRequest(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFReadStreamCreateForHTTPRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPProxy/title",
          "value": "kCFStreamPropertyHTTPProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11539715-cfreadstreamcopyproperty/title",
          "value": "CFReadStreamCopyProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPResponseHeader/title",
          "value": "kCFStreamPropertyHTTPResponseHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamPropertyHTTPResponseHeader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamPropertyHTTPResponseHeader"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/kcfstreamsslallowsanyroot"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/kcfstreamsslallowsanyroot"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
