{
  "abstract": [
    {
      "text": "The client and server couldn’t find a mutually agreeable authentication method.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/kSOCKS5NoAcceptableMethod"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kSOCKS5NoAcceptableMethod@kSOCKS5NoAcceptableMethod",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kSOCKS5NoAcceptableMethod"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSOCKS5NoAcceptableMethod"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kSOCKS5NoAcceptableMethod"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSOCKS5NoAcceptableMethod"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This error code is only valid for errors in the ",
              "type": "text"
            },
            {
              "code": "kCFStreamErrorSOCKS5SubDomainMethod",
              "type": "codeVoice"
            },
            {
              "text": " subdomain.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4IdConflict": {
      "abstract": [
        {
          "text": "Request rejected by the server because the client program and the ",
          "type": "text"
        },
        {
          "code": "identd",
          "type": "codeVoice"
        },
        {
          "text": " daemon reported different user IDs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4IdConflict"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4IdConflict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4IdConflict"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS4IdConflict",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks4idconflict"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4IdentdFailed": {
      "abstract": [
        {
          "text": "Request rejected by the server because it couldn’t connect to the ",
          "type": "text"
        },
        {
          "code": "identd",
          "type": "codeVoice"
        },
        {
          "text": " daemon on the client.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4IdentdFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4IdentdFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4IdentdFailed"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS4IdentdFailed",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks4identdfailed"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4RequestFailed": {
      "abstract": [
        {
          "text": "Request rejected by the server or request failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4RequestFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4RequestFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4RequestFailed"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS4RequestFailed",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks4requestfailed"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4SubDomainResponse": {
      "abstract": [
        {
          "text": "The SOCKS4 status code returned by the server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4SubDomainResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4SubDomainResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS4SubDomainResponse"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS4SubDomainResponse",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks4subdomainresponse"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5BadResponseAddr": {
      "abstract": [
        {
          "text": "The address returned is not of a known type. This error code is only valid for errors in the ",
          "type": "text"
        },
        {
          "code": "kCFStreamErrorSOCKSSubDomainNone",
          "type": "codeVoice"
        },
        {
          "text": " subdomain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5BadResponseAddr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5BadResponseAddr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5BadResponseAddr"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS5BadResponseAddr",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks5badresponseaddr"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5BadState": {
      "abstract": [
        {
          "text": "The stream is not in a state that allows the requested operation. This error code is only valid for errors in the ",
          "type": "text"
        },
        {
          "code": "kCFStreamErrorSOCKSSubDomainNone",
          "type": "codeVoice"
        },
        {
          "text": " subdomain..",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5BadState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5BadState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5BadState"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS5BadState",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks5badstate"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainMethod": {
      "abstract": [
        {
          "text": "The server’s desired negotiation method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5SubDomainMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5SubDomainMethod"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS5SubDomainMethod",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks5subdomainmethod"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainResponse": {
      "abstract": [
        {
          "text": "The response code that the server returned in reply to the connection request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5SubDomainResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5SubDomainResponse"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS5SubDomainResponse",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks5subdomainresponse"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainUserPass": {
      "abstract": [
        {
          "text": "The status code that the server returned during authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5SubDomainUserPass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainUserPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKS5SubDomainUserPass"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKS5SubDomainUserPass",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocks5subdomainuserpass"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSSubDomainNone": {
      "abstract": [
        {
          "text": "A general SOCKS error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKSSubDomainNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSSubDomainNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKSSubDomainNone"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKSSubDomainNone",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsockssubdomainnone"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSSubDomainVersionCode": {
      "abstract": [
        {
          "text": "The version of SOCKS that the server wants to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKSSubDomainVersionCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSSubDomainVersionCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKSSubDomainVersionCode"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKSSubDomainVersionCode",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsockssubdomainversioncode"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSUnknownClientVersion": {
      "abstract": [
        {
          "text": "The SOCKS server rejected access because it does not support connections with the requested SOCKS version. SOCKS client version. You can query the ",
          "type": "text"
        },
        {
          "code": "kCFSOCKSVersionKey",
          "type": "codeVoice"
        },
        {
          "text": " key to find out what version the server requested. This error code is only valid for errors in the ",
          "type": "text"
        },
        {
          "code": "kCFStreamErrorSOCKSSubDomainNone",
          "type": "codeVoice"
        },
        {
          "text": " subdomain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKSUnknownClientVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSUnknownClientVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFStreamErrorSOCKSUnknownClientVersion"
        }
      ],
      "role": "symbol",
      "title": "kCFStreamErrorSOCKSUnknownClientVersion",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfstreamerrorsocksunknownclientversion"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kSOCKS5NoAcceptableMethod": {
      "abstract": [
        {
          "text": "The client and server couldn’t find a mutually agreeable authentication method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSOCKS5NoAcceptableMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kSOCKS5NoAcceptableMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSOCKS5NoAcceptableMethod"
        }
      ],
      "role": "symbol",
      "title": "kSOCKS5NoAcceptableMethod",
      "type": "topic",
      "url": "/documentation/cfnetwork/ksocks5noacceptablemethod"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4IdConflict",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4IdentdFailed",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4RequestFailed",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4SubDomainResponse",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainMethod",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainResponse",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainUserPass",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSSubDomainNone",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSSubDomainVersionCode",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5BadResponseAddr",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5BadState",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSUnknownClientVersion"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSOCKS5NoAcceptableMethod"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSOCKS5NoAcceptableMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4IdConflict",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4IdentdFailed",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4RequestFailed",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS4SubDomainResponse",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainMethod",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainResponse",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5SubDomainUserPass",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSSubDomainNone",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSSubDomainVersionCode",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5BadResponseAddr",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKS5BadState",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFStreamErrorSOCKSUnknownClientVersion"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kSOCKS5NoAcceptableMethod"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5BadResponseAddr/title",
          "value": "kCFStreamErrorSOCKS5BadResponseAddr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5BadResponseAddr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS5BadResponseAddr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5SubDomainUserPass/title",
          "value": "kCFStreamErrorSOCKS5SubDomainUserPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5SubDomainUserPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS5SubDomainUserPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5SubDomainMethod/title",
          "value": "kCFStreamErrorSOCKS5SubDomainMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5SubDomainMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS5SubDomainMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4IdConflict/title",
          "value": "kCFStreamErrorSOCKS4IdConflict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4IdConflict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS4IdConflict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4RequestFailed/title",
          "value": "kCFStreamErrorSOCKS4RequestFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4RequestFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS4RequestFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4IdentdFailed/title",
          "value": "kCFStreamErrorSOCKS4IdentdFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4IdentdFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS4IdentdFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4SubDomainResponse/title",
          "value": "kCFStreamErrorSOCKS4SubDomainResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS4SubDomainResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS4SubDomainResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kSOCKS5NoAcceptableMethod/title",
          "value": "kSOCKS5NoAcceptableMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kSOCKS5NoAcceptableMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSOCKS5NoAcceptableMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKSSubDomainVersionCode/title",
          "value": "kCFStreamErrorSOCKSSubDomainVersionCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKSSubDomainVersionCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKSSubDomainVersionCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKSSubDomainNone/title",
          "value": "kCFStreamErrorSOCKSSubDomainNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKSSubDomainNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKSSubDomainNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5SubDomainResponse/title",
          "value": "kCFStreamErrorSOCKS5SubDomainResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5SubDomainResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS5SubDomainResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5BadState/title",
          "value": "kCFStreamErrorSOCKS5BadState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKS5BadState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKS5BadState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKSUnknownClientVersion/title",
          "value": "kCFStreamErrorSOCKSUnknownClientVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFStreamErrorSOCKSUnknownClientVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFStreamErrorSOCKSUnknownClientVersion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/ksocks5noacceptablemethod"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/ksocks5noacceptablemethod"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
