{
  "abstract": [
    {
      "text": "Keys for calls to property get/set functions such as ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539615-cfreadstreamsetproperty",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " and ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/property-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Property Keys"
  },
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)": {
      "abstract": [
        {
          "text": "Executes a proxy autoconfiguration script to determine the best proxy to use to retrieve a specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForAutoConfigurationScript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForAutoConfigurationScript"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkcopyproxiesforautoconfigurationscript(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)": {
      "abstract": [
        {
          "text": "Returns the list of proxies that should be used to download a given URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForURL"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkCopyProxiesForURL(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkcopyproxiesforurl(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()": {
      "abstract": [
        {
          "text": "Returns a CFDictionary containing the current systemwide internet proxy settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkCopySystemProxySettings"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkCopySystemProxySettings"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkCopySystemProxySettings()",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkcopysystemproxysettings()"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Downloads a proxy autoconfiguration script and executes it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationScript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFProxyAutoConfigurationResultCallback",
          "text": "CFProxyAutoConfigurationResultCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamClientContext",
          "text": "CFStreamClientContext"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopSourceRef",
          "text": "CFRunLoopSource"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationScript"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkexecuteproxyautoconfigurationscript(_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Downloads a proxy autoconfiguration script and executes it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFProxyAutoConfigurationResultCallback",
          "text": "CFProxyAutoConfigurationResultCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamClientContext",
          "text": "CFStreamClientContext"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopSourceRef",
          "text": "CFRunLoopSource"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationURL"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkexecuteproxyautoconfigurationurl(_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFProxyAutoConfigurationResultCallback": {
      "abstract": [
        {
          "text": "Callback function called when a proxy autoconfiguration computation has completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFProxyAutoConfigurationResultCallback"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFProxyAutoConfigurationResultCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFProxyAutoConfigurationResultCallback"
        }
      ],
      "role": "symbol",
      "title": "CFProxyAutoConfigurationResultCallback",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfproxyautoconfigurationresultcallback"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/global-proxy-settings-constants": {
      "abstract": [
        {
          "text": "Constants for keys in the global proxy settings dictionary returned by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/global-proxy-settings-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Global Proxy Settings Constants",
      "type": "topic",
      "url": "/documentation/cfnetwork/global-proxy-settings-constants"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyAutoConfigurationHTTPResponseKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyAutoConfigurationHTTPResponseKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyAutoConfigurationHTTPResponseKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyAutoConfigurationHTTPResponseKey"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyAutoConfigurationHTTPResponseKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxyautoconfigurationhttpresponsekey"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyAutoConfigurationJavaScriptKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyAutoConfigurationJavaScriptKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyAutoConfigurationJavaScriptKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyAutoConfigurationJavaScriptKey"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyAutoConfigurationJavaScriptKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxyautoconfigurationjavascriptkey"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyAutoConfigurationURLKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyAutoConfigurationURLKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyAutoConfigurationURLKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyAutoConfigurationURLKey"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyAutoConfigurationURLKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxyautoconfigurationurlkey"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyHostNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyHostNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyHostNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyHostNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyHostNameKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxyhostnamekey"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyPasswordKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyPasswordKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyPasswordKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyPasswordKey"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyPasswordKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxypasswordkey"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyPortNumberKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyPortNumberKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyPortNumberKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyPortNumberKey"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyPortNumberKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxyportnumberkey"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyTypeKey"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyTypeKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxytypekey"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyUsernameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyUsernameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyUsernameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyUsernameKey"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyUsernameKey",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxyusernamekey"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/proxy-types": {
      "abstract": [
        {
          "text": "Constants that specify the type of proxy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/proxy-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Proxy Types",
      "type": "topic",
      "url": "/documentation/cfnetwork/proxy-types"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1539615-cfreadstreamsetproperty": {
      "abstract": [
        {
          "text": "Sets the value of a property for a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamSetProperty"
        },
        {
          "kind": "text",
          "text": "(CFReadStream!, CFStreamPropertyKey!, CFTypeRef!) -> Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539615-cfreadstreamsetproperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFReadStreamSetProperty(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1539615-cfreadstreamsetproperty"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty": {
      "abstract": [
        {
          "text": "Returns the value of a property for a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamCopyProperty"
        },
        {
          "kind": "text",
          "text": "(CFReadStream!, CFStreamPropertyKey!) -> CFTypeRef!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFReadStreamCopyProperty(_:_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1539715-cfreadstreamcopyproperty"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Global-Proxy-Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFProxyAutoConfigurationResultCallback",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/proxy-types",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/global-proxy-settings-constants"
      ],
      "title": "Global Proxy Configuration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyAutoConfigurationHTTPResponseKey",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyAutoConfigurationJavaScriptKey",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyAutoConfigurationURLKey",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyHostNameKey",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyPasswordKey",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyPortNumberKey",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeKey",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyUsernameKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyAutoConfigurationHTTPResponseKey",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyAutoConfigurationJavaScriptKey",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyAutoConfigurationURLKey",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyHostNameKey",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyPasswordKey",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyPortNumberKey",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeKey",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyUsernameKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Global-Proxy-Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFProxyAutoConfigurationResultCallback",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/proxy-types",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/global-proxy-settings-constants"
              ],
              "title": "Global Proxy Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyPasswordKey/title",
          "value": "kCFProxyPasswordKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyPasswordKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyPasswordKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyAutoConfigurationHTTPResponseKey/title",
          "value": "kCFProxyAutoConfigurationHTTPResponseKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyAutoConfigurationHTTPResponseKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyAutoConfigurationHTTPResponseKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFProxyAutoConfigurationResultCallback/title",
          "value": "CFProxyAutoConfigurationResultCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFProxyAutoConfigurationResultCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFProxyAutoConfigurationResultCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFProxyAutoConfigurationResultCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFProxyAutoConfigurationResultCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForURL(_:_:)/title",
          "value": "CFNetworkCopyProxiesForURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForURL(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkCopyProxiesForURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeKey/title",
          "value": "kCFProxyTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyAutoConfigurationURLKey/title",
          "value": "kCFProxyAutoConfigurationURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyAutoConfigurationURLKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyAutoConfigurationURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)/title",
          "value": "CFNetworkCopyProxiesForAutoConfigurationScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkCopyProxiesForAutoConfigurationScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyAutoConfigurationJavaScriptKey/title",
          "value": "kCFProxyAutoConfigurationJavaScriptKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyAutoConfigurationJavaScriptKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyAutoConfigurationJavaScriptKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)/title",
          "value": "CFNetworkExecuteProxyAutoConfigurationURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkExecuteProxyAutoConfigurationURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyPortNumberKey/title",
          "value": "kCFProxyPortNumberKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyPortNumberKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyPortNumberKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11539715-cfreadstreamcopyproperty/title",
          "value": "CFReadStreamCopyProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopySystemProxySettings()/title",
          "value": "CFNetworkCopySystemProxySettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopySystemProxySettings()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkCopySystemProxySettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyHostNameKey/title",
          "value": "kCFProxyHostNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyHostNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyHostNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)/title",
          "value": "CFNetworkExecuteProxyAutoConfigurationScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkExecuteProxyAutoConfigurationScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11539615-cfreadstreamsetproperty/title",
          "value": "CFReadStreamSetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyUsernameKey/title",
          "value": "kCFProxyUsernameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyUsernameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyUsernameKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/property-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/property-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
