{
  "abstract": [
    {
      "text": "Constants that specify the type of proxy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/proxy-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Proxy Types"
  },
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)": {
      "abstract": [
        {
          "text": "Executes a proxy autoconfiguration script to determine the best proxy to use to retrieve a specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForAutoConfigurationScript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForAutoConfigurationScript"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkcopyproxiesforautoconfigurationscript(_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)": {
      "abstract": [
        {
          "text": "Returns the list of proxies that should be used to download a given URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkCopyProxiesForURL"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkCopyProxiesForURL(_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkcopyproxiesforurl(_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()": {
      "abstract": [
        {
          "text": "Returns a CFDictionary containing the current systemwide internet proxy settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkCopySystemProxySettings"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkCopySystemProxySettings"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkCopySystemProxySettings()",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkcopysystemproxysettings()"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Downloads a proxy autoconfiguration script and executes it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationScript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFProxyAutoConfigurationResultCallback",
          "text": "CFProxyAutoConfigurationResultCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamClientContext",
          "text": "CFStreamClientContext"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopSourceRef",
          "text": "CFRunLoopSource"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationScript"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkexecuteproxyautoconfigurationscript(_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Downloads a proxy autoconfiguration script and executes it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFProxyAutoConfigurationResultCallback",
          "text": "CFProxyAutoConfigurationResultCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFStreamClientContext",
          "text": "CFStreamClientContext"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopSourceRef",
          "text": "CFRunLoopSource"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkExecuteProxyAutoConfigurationURL"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkexecuteproxyautoconfigurationurl(_:_:_:_:)"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFProxyAutoConfigurationResultCallback": {
      "abstract": [
        {
          "text": "Callback function called when a proxy autoconfiguration computation has completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFProxyAutoConfigurationResultCallback"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFProxyAutoConfigurationResultCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFProxyAutoConfigurationResultCallback"
        }
      ],
      "role": "symbol",
      "title": "CFProxyAutoConfigurationResultCallback",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfproxyautoconfigurationresultcallback"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/global-proxy-settings-constants": {
      "abstract": [
        {
          "text": "Constants for keys in the global proxy settings dictionary returned by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/global-proxy-settings-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Global Proxy Settings Constants",
      "type": "topic",
      "url": "/documentation/cfnetwork/global-proxy-settings-constants"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationJavaScript": {
      "abstract": [
        {
          "text": "Specifies that the proxy is determined by a provided autoconfiguration script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyTypeAutoConfigurationJavaScript"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationJavaScript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyTypeAutoConfigurationJavaScript"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyTypeAutoConfigurationJavaScript",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxytypeautoconfigurationjavascript"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationURL": {
      "abstract": [
        {
          "text": "Specifies that the proxy is determined by an autoconfiguration file at a given URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyTypeAutoConfigurationURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyTypeAutoConfigurationURL"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyTypeAutoConfigurationURL",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxytypeautoconfigurationurl"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeFTP": {
      "abstract": [
        {
          "text": "Specifies an FTP proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyTypeFTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeFTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyTypeFTP"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyTypeFTP",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxytypeftp"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeHTTP": {
      "abstract": [
        {
          "text": "Specifies an HTTP proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyTypeHTTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeHTTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyTypeHTTP"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyTypeHTTP",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxytypehttp"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeHTTPS": {
      "abstract": [
        {
          "text": "Specifies an HTTPS proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyTypeHTTPS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeHTTPS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyTypeHTTPS"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyTypeHTTPS",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxytypehttps"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeNone": {
      "abstract": [
        {
          "text": "Specifies that no proxy should be used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyTypeNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyTypeNone"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyTypeNone",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxytypenone"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeSOCKS": {
      "abstract": [
        {
          "text": "Specifies a SOCKS proxy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFProxyTypeSOCKS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeSOCKS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFProxyTypeSOCKS"
        }
      ],
      "role": "symbol",
      "title": "kCFProxyTypeSOCKS",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcfproxytypesocks"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/property-keys": {
      "abstract": [
        {
          "text": "Keys for calls to property get/set functions such as ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539615-cfreadstreamsetproperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/property-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Property Keys",
      "type": "topic",
      "url": "/documentation/cfnetwork/property-keys"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1539615-cfreadstreamsetproperty": {
      "abstract": [
        {
          "text": "Sets the value of a property for a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamSetProperty"
        },
        {
          "kind": "text",
          "text": "(CFReadStream!, CFStreamPropertyKey!, CFTypeRef!) -> Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539615-cfreadstreamsetproperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFReadStreamSetProperty(_:_:_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1539615-cfreadstreamsetproperty"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty": {
      "abstract": [
        {
          "text": "Returns the value of a property for a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFReadStreamCopyProperty"
        },
        {
          "kind": "text",
          "text": "(CFReadStream!, CFStreamPropertyKey!) -> CFTypeRef!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1539715-cfreadstreamcopyproperty",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFReadStreamCopyProperty(_:_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1539715-cfreadstreamcopyproperty"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Global-Proxy-Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFProxyAutoConfigurationResultCallback",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/property-keys",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/global-proxy-settings-constants"
      ],
      "title": "Global Proxy Configuration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeNone",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationURL",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationJavaScript",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeFTP",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeHTTP",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeHTTPS",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeSOCKS"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeNone",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationURL",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeAutoConfigurationJavaScript",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeFTP",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeHTTP",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeHTTPS",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFProxyTypeSOCKS"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Global-Proxy-Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForURL(_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkCopySystemProxySettings()",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFProxyAutoConfigurationResultCallback",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/property-keys",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/global-proxy-settings-constants"
              ],
              "title": "Global Proxy Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeAutoConfigurationURL/title",
          "value": "kCFProxyTypeAutoConfigurationURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeAutoConfigurationURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeAutoConfigurationURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11539615-cfreadstreamsetproperty/title",
          "value": "CFReadStreamSetProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)/title",
          "value": "CFNetworkExecuteProxyAutoConfigurationScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationScript(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkExecuteProxyAutoConfigurationScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeAutoConfigurationJavaScript/title",
          "value": "kCFProxyTypeAutoConfigurationJavaScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeAutoConfigurationJavaScript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeAutoConfigurationJavaScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeFTP/title",
          "value": "kCFProxyTypeFTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeFTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeFTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11539715-cfreadstreamcopyproperty/title",
          "value": "CFReadStreamCopyProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFProxyAutoConfigurationResultCallback/title",
          "value": "CFProxyAutoConfigurationResultCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFProxyAutoConfigurationResultCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFProxyAutoConfigurationResultCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFProxyAutoConfigurationResultCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFProxyAutoConfigurationResultCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)/title",
          "value": "CFNetworkExecuteProxyAutoConfigurationURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkExecuteProxyAutoConfigurationURL(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkExecuteProxyAutoConfigurationURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopySystemProxySettings()/title",
          "value": "CFNetworkCopySystemProxySettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopySystemProxySettings()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkCopySystemProxySettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeHTTP/title",
          "value": "kCFProxyTypeHTTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeHTTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeHTTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForURL(_:_:)/title",
          "value": "CFNetworkCopyProxiesForURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForURL(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkCopyProxiesForURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeSOCKS/title",
          "value": "kCFProxyTypeSOCKS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeSOCKS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeSOCKS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeHTTPS/title",
          "value": "kCFProxyTypeHTTPS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeHTTPS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeHTTPS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)/title",
          "value": "CFNetworkCopyProxiesForAutoConfigurationScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkCopyProxiesForAutoConfigurationScript(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkCopyProxiesForAutoConfigurationScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeNone/title",
          "value": "kCFProxyTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFProxyTypeNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFProxyTypeNone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/proxy-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/proxy-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
