{
  "abstract": [
    {
      "text": "A routing method that routes traffic based on network rule objects specified by the provider.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NETunnelProviderRoutingMethod"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NETunnelProviderRoutingMethod/networkRule"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NETunnelProviderRoutingMethod@NETunnelProviderRoutingMethodNetworkRule",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "networkRule"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NETunnelProviderRoutingMethodNetworkRule"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NETunnelProviderRoutingMethod.networkRule"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "networkRule"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NETunnelProviderRoutingMethod": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NETunnelProviderRoutingMethod"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NETunnelProviderRoutingMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NETunnelProviderRoutingMethod"
        }
      ],
      "role": "symbol",
      "title": "NETunnelProviderRoutingMethod",
      "type": "topic",
      "url": "/documentation/networkextension/netunnelproviderroutingmethod"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NETunnelProviderRoutingMethod/destinationIP": {
      "abstract": [
        {
          "text": "Route network traffic to the tunnel based on destination IP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destinationIP"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NETunnelProviderRoutingMethod/destinationIP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NETunnelProviderRoutingMethodDestinationIP"
        }
      ],
      "role": "symbol",
      "title": "NETunnelProviderRoutingMethod.destinationIP",
      "type": "topic",
      "url": "/documentation/networkextension/netunnelproviderroutingmethod/destinationip"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NETunnelProviderRoutingMethod/networkRule": {
      "abstract": [
        {
          "text": "A routing method that routes traffic based on network rule objects specified by the provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkRule"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NETunnelProviderRoutingMethod/networkRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NETunnelProviderRoutingMethodNetworkRule"
        }
      ],
      "role": "symbol",
      "title": "NETunnelProviderRoutingMethod.networkRule",
      "type": "topic",
      "url": "/documentation/networkextension/netunnelproviderroutingmethod/networkrule"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NETunnelProviderRoutingMethod/sourceApplication": {
      "abstract": [
        {
          "text": "Route network traffic to the tunnel based on source application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceApplication"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NETunnelProviderRoutingMethod/sourceApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NETunnelProviderRoutingMethodSourceApplication"
        }
      ],
      "role": "symbol",
      "title": "NETunnelProviderRoutingMethod.sourceApplication",
      "type": "topic",
      "url": "/documentation/networkextension/netunnelproviderroutingmethod/sourceapplication"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Routing-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NETunnelProviderRoutingMethod/destinationIP",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NETunnelProviderRoutingMethod/sourceApplication"
      ],
      "title": "Routing Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NETunnelProviderRoutingMethodNetworkRule"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NETunnelProviderRoutingMethodNetworkRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NETunnelProviderRoutingMethod"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Routing-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NETunnelProviderRoutingMethod/destinationIP",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NETunnelProviderRoutingMethod/sourceApplication"
              ],
              "title": "Routing Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NETunnelProviderRoutingMethodNetworkRule"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NETunnelProviderRoutingMethod~1networkRule/title",
          "value": "NETunnelProviderRoutingMethodNetworkRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NETunnelProviderRoutingMethod~1networkRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NETunnelProviderRoutingMethodNetworkRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NETunnelProviderRoutingMethod/title",
          "value": "NETunnelProviderRoutingMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NETunnelProviderRoutingMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NETunnelProviderRoutingMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NETunnelProviderRoutingMethod/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NETunnelProviderRoutingMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NETunnelProviderRoutingMethod~1sourceApplication/title",
          "value": "NETunnelProviderRoutingMethodSourceApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NETunnelProviderRoutingMethod~1sourceApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NETunnelProviderRoutingMethodSourceApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NETunnelProviderRoutingMethod~1destinationIP/title",
          "value": "NETunnelProviderRoutingMethodDestinationIP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NETunnelProviderRoutingMethod~1destinationIP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NETunnelProviderRoutingMethodDestinationIP"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/netunnelproviderroutingmethod/networkrule"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/netunnelproviderroutingmethod/networkrule"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
