{
  "abstract": [
    {
      "text": "Use text in SwiftUI complications.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/adding-text-to-a-complication"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Adding text to a complication"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When creating ClockKit templates with SwiftUI views, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " views adapt their appearance based on the template’s complication family. The system automatically sets the font and size to match other templates in the same family.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Match-the-Expected-Font-Size",
          "level": 3,
          "text": "Match the Expected Font Size",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the default font size as a guide for the type of information your complication displays. For example, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicExtraLargeCircularView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " template provides a large canvas for drawing, but it’s intended to present large, easy-to-read content instead of a lot of small, detailed data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Use-Text-Formatters",
          "level": 3,
          "text": "Use Text Formatters",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When displaying dates and times, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to create localized strings. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " also defines formatters such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/relative",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/offset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/timer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". ClockKit automatically updates information in these formatters, and you can use these formatters when instantiating a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "Text(myEvent.startDate, style: .timer)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Or use them inline in an interpolated string.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "Text(\"\\(myEvent.name) starts in \\(myEvent.startDate, style: .timer)\")"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3666648",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicExtraLargeCircularView": {
      "abstract": [
        {
          "text": "A template for displaying a circular SwiftUI view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicExtraLargeCircularView"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicExtraLargeCircularView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicExtraLargeCircularView"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicExtraLargeCircularView",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicextralargecircularview"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/building-complications-with-swiftui": {
      "abstract": [
        {
          "text": "Design the appearance of a graphic complication using SwiftUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/building-complications-with-swiftui",
      "kind": "article",
      "role": "article",
      "title": "Building complications with SwiftUI",
      "type": "topic",
      "url": "/documentation/clockkit/building-complications-with-swiftui"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/creating-a-timeline-entry": {
      "abstract": [
        {
          "text": "Package your app-specific data into a template and create a timeline entry for that template.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/creating-a-timeline-entry",
      "kind": "article",
      "role": "article",
      "title": "Creating a timeline entry",
      "type": "topic",
      "url": "/documentation/clockkit/creating-a-timeline-entry"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/creating-complications-for-your-watchos-app": {
      "abstract": [
        {
          "text": "Set up and implement complications for your watchOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/creating-complications-for-your-watchos-app",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Creating complications for your watchOS app",
      "type": "topic",
      "url": "/documentation/clockkit/creating-complications-for-your-watchos-app"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/declaring-complications-for-your-app": {
      "abstract": [
        {
          "text": "Define the complications that your app supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/declaring-complications-for-your-app",
      "kind": "article",
      "role": "article",
      "title": "Declaring complications for your app",
      "type": "topic",
      "url": "/documentation/clockkit/declaring-complications-for-your-app"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols": {
      "abstract": [],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated articles and symbols",
      "type": "topic",
      "url": "/documentation/clockkit/deprecated-articles-and-symbols"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/displaying-progress-views-and-gauges": {
      "abstract": [
        {
          "text": "Add rich visual data to your SwiftUI complications with progress views and gauges.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/displaying-progress-views-and-gauges",
      "kind": "article",
      "role": "article",
      "title": "Displaying progress views and gauges",
      "type": "topic",
      "url": "/documentation/clockkit/displaying-progress-views-and-gauges"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/keeping-your-complications-up-to-date": {
      "abstract": [
        {
          "text": "Replace or extend the data in your complication’s timeline.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/keeping-your-complications-up-to-date",
      "kind": "article",
      "role": "article",
      "title": "Keeping your complications up to date",
      "type": "topic",
      "url": "/documentation/clockkit/keeping-your-complications-up-to-date"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/loading-future-timeline-events": {
      "abstract": [
        {
          "text": "Preserve battery life and improve performance on the watch by providing a timeline with expected data and updates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/loading-future-timeline-events",
      "kind": "article",
      "role": "article",
      "title": "Loading future timeline events",
      "type": "topic",
      "url": "/documentation/clockkit/loading-future-timeline-events"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Text": {
      "abstract": [
        {
          "text": "A view that displays one or more lines of read-only text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text",
      "kind": "symbol",
      "role": "symbol",
      "title": "Text",
      "type": "topic",
      "url": "/documentation/SwiftUI/Text"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle": {
      "abstract": [
        {
          "text": "A predefined style used to display a `Date`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DateStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "Text.DateStyle",
      "type": "topic",
      "url": "/documentation/SwiftUI/Text/DateStyle"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/offset": {
      "abstract": [
        {
          "text": "A style displaying a date as offset from now.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV9DateStyleV",
          "text": "DateStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/offset",
      "kind": "symbol",
      "role": "symbol",
      "title": "offset",
      "type": "topic",
      "url": "/documentation/SwiftUI/Text/DateStyle/offset"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/relative": {
      "abstract": [
        {
          "text": "A style displaying a date as relative to now.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relative"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV9DateStyleV",
          "text": "DateStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/relative",
      "kind": "symbol",
      "role": "symbol",
      "title": "relative",
      "type": "topic",
      "url": "/documentation/SwiftUI/Text/DateStyle/relative"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/timer": {
      "abstract": [
        {
          "text": "A style displaying a date as timer counting from now.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV9DateStyleV",
          "text": "DateStyle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Text/DateStyle/timer",
      "kind": "symbol",
      "role": "symbol",
      "title": "timer",
      "type": "topic",
      "url": "/documentation/SwiftUI/Text/DateStyle/timer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3666648": {
      "alt": "A preview of a large rectangular complication with a text view that displays a timer that automatically counts down to the next event.",
      "identifier": "media-3666648",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2aeb07ea3989a2e71c8c6879a28a474d/media-3666648@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2aeb07ea3989a2e71c8c6879a28a474d/media-3666648~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Articles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/creating-complications-for-your-watchos-app",
        "doc://com.apple.clockkit/documentation/ClockKit/declaring-complications-for-your-app",
        "doc://com.apple.clockkit/documentation/ClockKit/creating-a-timeline-entry",
        "doc://com.apple.clockkit/documentation/ClockKit/loading-future-timeline-events",
        "doc://com.apple.clockkit/documentation/ClockKit/keeping-your-complications-up-to-date",
        "doc://com.apple.clockkit/documentation/ClockKit/building-complications-with-swiftui",
        "doc://com.apple.clockkit/documentation/ClockKit/displaying-progress-views-and-gauges"
      ],
      "title": "Articles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Articles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/creating-complications-for-your-watchos-app",
                "doc://com.apple.clockkit/documentation/ClockKit/declaring-complications-for-your-app",
                "doc://com.apple.clockkit/documentation/ClockKit/creating-a-timeline-entry",
                "doc://com.apple.clockkit/documentation/ClockKit/loading-future-timeline-events",
                "doc://com.apple.clockkit/documentation/ClockKit/keeping-your-complications-up-to-date",
                "doc://com.apple.clockkit/documentation/ClockKit/building-complications-with-swiftui",
                "doc://com.apple.clockkit/documentation/ClockKit/displaying-progress-views-and-gauges"
              ],
              "title": "Articles"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/adding-text-to-a-complication"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/adding-text-to-a-complication"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
