{
  "abstract": [
    {
      "text": "Design the appearance of a graphic complication using SwiftUI.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/building-complications-with-swiftui"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Building complications with SwiftUI"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "ClockKit provides SwiftUI templates for all of the graphic complication families. These templates use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance to define some or all of the complication’s content. To access these templates, import both ClockKit and SwiftUI.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import ClockKit",
            "import SwiftUI"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "ClockKit provides a variety of templates for each family. Many of these mix SwiftUI views with other data providers. However, some templates take only a single SwiftUI view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCircularView",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularFullView",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicExtraLargeCircularView",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "These templates provide a blank canvas that you can use to draw the entire complication.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Present-a-View",
          "level": 3,
          "text": "Present a View",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "ClockKit varies the SwiftUI view’s size based on the template. The SwiftUI template replaces a full color image provider with a SwiftUI view. The view has the same dimensions as the corresponding image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Also, the template may mask the SwiftUI view to a circle or apply a corner radius to the view, just as it does for the full color images. In particular, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularFullView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " template provides the full graphic rectangular complication as a single SwiftUI view. This view is 162 pt x 69 pt on the 40 mm Apple Watch, and 184 pt x 78 pt on the 44 mm watch, but the template provides a safe area inset to help you avoid clipping your content. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/edgesIgnoringSafeArea(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " modifier, if you need to fill the complication to the edges.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3683203",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For additional details, see each template’s class reference document.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Design-a-View",
          "level": 3,
          "text": "Design a View",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use SwiftUI static views, such as text, shapes, or images, to create your complication’s content. You can also add render effects like blurs and gradients, but keep in mind that complications only have one or two frames in which to render the effect.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Because complications show a snapshot of the apps data at a particular point in time, they don’t support features like animation. Additionally, if the user touches your complication, the system launches your app instead of passing the touch event to the SwiftUI views, so a complication can’t use interactive elements like buttons or switches.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Support-Tinted-Views",
          "level": 3,
          "text": "Support Tinted Views",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Some watch faces let the user select a tint color that affects how the face displays graphical complications. Some watch faces use a complex set of colors; for example, the Solar Dial face sets both a foreground and background color, and the colors change based on the time of day.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "By default, when ClockKit displays your complication on a tinted watch face, it desaturates your SwiftUI view to create a grayscale version. For some faces, like the California face, it then applies a single tint color to the desaturated view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To control how the system tints your view, divide your view hierarchy into two layers, a foreground layer and the background layer. ClockKit looks at the opacity of each layer when applying the tint.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For most watch faces, ClockKit applies the user-selected tint color to one layer, and a system-defined color to the other. For example, the Infograph watch face applies white to the background and the user-selected tint to the foreground. However, the foreground and background colors can change from face to face. in the X-Large watch face, ClockKit applies white to the foreground, and the tint color to the background. On other faces, like Solar Dial, it applies system-defined colors to both layers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3666656",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To divide your view into layers, add the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/complicationForeground()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " modifier to part of your view hierarchy. That view and all of its subviews become the foreground layer. Everything else is in the background layer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "ZStack {",
            "    Rectangle()",
            "        .fill(Color.purple)",
            "    Image(\"coffee_template\")",
            "        .renderingMode(.template)",
            "        .resizable()",
            "        .aspectRatio(contentMode: .fit)",
            "        .foregroundColor(.yellow)",
            "        .complicationForeground()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3666654",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For even greater control, you can check the complication’s rendering mode, and then change the design based on whether the system displays the face in a full color or a tinted mode. You can access the current ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Environment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "@Environment(\\.complicationRenderingMode) var renderingMode",
            "",
            "var body: some View {",
            "    ZStack {",
            "        ",
            "        if renderingMode == .fullColor {",
            "            Circle()",
            "                .fill(Color.purple)",
            "        } else {",
            "            Circle()",
            "                .fill(LinearGradient(",
            "                        gradient: Gradient(",
            "                            colors: [Color.white.opacity(0.3),",
            "                                     Color.white.opacity(1.0)]),",
            "                        startPoint: .top,",
            "                        endPoint: .bottom))",
            "        }",
            "        ",
            "        Image(\"coffee_template\")",
            "            .renderingMode(.template)",
            "            .resizable()",
            "            .aspectRatio(contentMode: .fit)",
            "            .foregroundColor(.yellow)",
            "            .complicationForeground()",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In this example, if the system renders the watch face in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode/fullColor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " mode, it uses a solid blue circle as the background. However, if the system renders the face in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode/tinted",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " mode, it uses a gradient fill. For a tinted complication, the selected color has no effect; the system only looks at the opacity, and then applies its own color.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3666655",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Preview-the-Complication",
          "level": 3,
          "text": "Preview the Complication",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Like other SwiftUI views, you can preview your complications as you design them. To enable previews:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PreviewProvider",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to the bottom of your complication controller’s file.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PreviewProvider/previews-swift.type.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property, instantiate your template, and call its ",
                      "type": "text"
                    },
                    {
                      "code": "previewContext(faceColor:)",
                      "type": "codeVoice"
                    },
                    {
                      "text": " method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Calling ",
              "type": "text"
            },
            {
              "code": "previewContext()",
              "type": "codeVoice"
            },
            {
              "text": " with no argument defaults to a full-color watch face. To preview a tinted watch face, pass the desired tint color to the ",
              "type": "text"
            },
            {
              "code": "faceColor",
              "type": "codeVoice"
            },
            {
              "text": " parameter. Use a ",
              "type": "text"
            },
            {
              "code": "Group",
              "type": "codeVoice"
            },
            {
              "text": " to preview multiple complications at once.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "struct ComplicationController_Previews: PreviewProvider {",
            "    static var previews: some View {",
            "        Group {",
            "            ",
            "            CLKComplicationTemplateGraphicExtraLargeCircularView(MyCoffeeView()).previewContext()",
            "            ",
            "            CLKComplicationTemplateGraphicExtraLargeCircularView(MyCoffeeView()).previewContext(faceColor: .red)",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3666657",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCircularView": {
      "abstract": [
        {
          "text": "A template for displaying a circular view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCircularView"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCircularView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCircularView"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicCircularView",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphiccircularview"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicExtraLargeCircularView": {
      "abstract": [
        {
          "text": "A template for displaying a circular SwiftUI view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicExtraLargeCircularView"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicExtraLargeCircularView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicExtraLargeCircularView"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicExtraLargeCircularView",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicextralargecircularview"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularFullView": {
      "abstract": [
        {
          "text": "A template for displaying a SwiftUI view that fills the entire template.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularFullView"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularFullView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularFullView"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicRectangularFullView",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularfullview"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode": {
      "abstract": [
        {
          "text": "The complication’s appearance, as specified by the watch face.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ComplicationRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ComplicationRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "ComplicationRenderingMode",
      "type": "topic",
      "url": "/documentation/clockkit/complicationrenderingmode"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode/fullColor": {
      "abstract": [
        {
          "text": "The system renders the complication in full color.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullColor"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode/fullColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "ComplicationRenderingMode.fullColor",
      "type": "topic",
      "url": "/documentation/clockkit/complicationrenderingmode/fullcolor"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode/tinted": {
      "abstract": [
        {
          "text": "The system renders the complication as a tinted complication.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tinted"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode/tinted",
      "kind": "symbol",
      "role": "symbol",
      "title": "ComplicationRenderingMode.tinted",
      "type": "topic",
      "url": "/documentation/clockkit/complicationrenderingmode/tinted"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/adding-text-to-a-complication": {
      "abstract": [
        {
          "text": "Use text in SwiftUI complications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/adding-text-to-a-complication",
      "kind": "article",
      "role": "article",
      "title": "Adding text to a complication",
      "type": "topic",
      "url": "/documentation/clockkit/adding-text-to-a-complication"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/creating-a-timeline-entry": {
      "abstract": [
        {
          "text": "Package your app-specific data into a template and create a timeline entry for that template.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/creating-a-timeline-entry",
      "kind": "article",
      "role": "article",
      "title": "Creating a timeline entry",
      "type": "topic",
      "url": "/documentation/clockkit/creating-a-timeline-entry"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/creating-complications-for-your-watchos-app": {
      "abstract": [
        {
          "text": "Set up and implement complications for your watchOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/creating-complications-for-your-watchos-app",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Creating complications for your watchOS app",
      "type": "topic",
      "url": "/documentation/clockkit/creating-complications-for-your-watchos-app"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/declaring-complications-for-your-app": {
      "abstract": [
        {
          "text": "Define the complications that your app supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/declaring-complications-for-your-app",
      "kind": "article",
      "role": "article",
      "title": "Declaring complications for your app",
      "type": "topic",
      "url": "/documentation/clockkit/declaring-complications-for-your-app"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols": {
      "abstract": [],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated articles and symbols",
      "type": "topic",
      "url": "/documentation/clockkit/deprecated-articles-and-symbols"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/displaying-progress-views-and-gauges": {
      "abstract": [
        {
          "text": "Add rich visual data to your SwiftUI complications with progress views and gauges.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/displaying-progress-views-and-gauges",
      "kind": "article",
      "role": "article",
      "title": "Displaying progress views and gauges",
      "type": "topic",
      "url": "/documentation/clockkit/displaying-progress-views-and-gauges"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/keeping-your-complications-up-to-date": {
      "abstract": [
        {
          "text": "Replace or extend the data in your complication’s timeline.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/keeping-your-complications-up-to-date",
      "kind": "article",
      "role": "article",
      "title": "Keeping your complications up to date",
      "type": "topic",
      "url": "/documentation/clockkit/keeping-your-complications-up-to-date"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/loading-future-timeline-events": {
      "abstract": [
        {
          "text": "Preserve battery life and improve performance on the watch by providing a timeline with expected data and updates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/loading-future-timeline-events",
      "kind": "article",
      "role": "article",
      "title": "Loading future timeline events",
      "type": "topic",
      "url": "/documentation/clockkit/loading-future-timeline-events"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Environment": {
      "abstract": [
        {
          "text": "A property wrapper that reads a value from a view’s environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@propertyWrapper"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Environment"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Environment",
      "kind": "symbol",
      "role": "symbol",
      "title": "Environment",
      "type": "topic",
      "url": "/documentation/SwiftUI/Environment"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/PreviewProvider": {
      "abstract": [
        {
          "text": "A type that produces view previews in Xcode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PreviewProvider"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "text": "_PreviewProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PreviewProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "PreviewProvider",
      "type": "topic",
      "url": "/documentation/SwiftUI/PreviewProvider"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/PreviewProvider/previews-swift.type.property": {
      "abstract": [
        {
          "text": "A collection of views to preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:7SwiftUI11ViewBuilderV",
          "text": "ViewBuilder"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previews"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15PreviewProviderP8PreviewsQa",
          "text": "Previews"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/PreviewProvider/previews-swift.type.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "previews",
      "type": "topic",
      "url": "/documentation/SwiftUI/PreviewProvider/previews-swift.type.property"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View": {
      "abstract": [
        {
          "text": "A type that represents part of your app’s user interface and provides modifiers that you use to configure views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View",
      "kind": "symbol",
      "role": "symbol",
      "title": "View",
      "type": "topic",
      "url": "/documentation/SwiftUI/View"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View/complicationForeground()": {
      "abstract": [
        {
          "text": "Promotes this view to the foreground in a complication.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "complicationForeground"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/complicationForeground()",
      "kind": "symbol",
      "role": "symbol",
      "title": "complicationForeground()",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/complicationForeground()"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View/edgesIgnoringSafeArea(_:)": {
      "abstract": [
        {
          "text": "Changes the view’s proposed area to extend outside the screen’s safe areas.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "edgesIgnoringSafeArea"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "edges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4EdgeO",
          "text": "Edge"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4EdgeO3SetV",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/edgesIgnoringSafeArea(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "edgesIgnoringSafeArea(_:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/edgesIgnoringSafeArea(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3666654": {
      "alt": "An image of two watch faces with an extra-large circular complication. The first face displays the full-color version, while the second displays the tinted version.",
      "identifier": "media-3666654",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/72c68d04d89f5bcdbf64fef840e0f04b/media-3666654@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/72c68d04d89f5bcdbf64fef840e0f04b/media-3666654~dark@2x.png"
        }
      ]
    },
    "media-3666655": {
      "alt": "An image of two watch faces with an extra-large circular complication. The first face displays the full-color version, while the second displays the tinted version with a gradient fill.",
      "identifier": "media-3666655",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8f42c390bf5d10537538cd2340933901/media-3666655@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8f42c390bf5d10537538cd2340933901/media-3666655~dark@2x.png"
        }
      ]
    },
    "media-3666656": {
      "alt": "Two watch faces. The first face displays a tinted circular graphic template in the upper left corner as a red icon on a white background. The second face displays the extra-large version of that template in the center of the screen with a white icon on a red background.",
      "identifier": "media-3666656",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/7dd0c57b64844500c2ab6376343e33ef/media-3666656@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/7dd0c57b64844500c2ab6376343e33ef/media-3666656~dark@2x.png"
        }
      ]
    },
    "media-3666657": {
      "alt": "An image of two watch previews of an extra-large circular complication. The first preview displays the full-color version, while the second displays a red-tinted version.",
      "identifier": "media-3666657",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8111333d80569f7f219ac5de2a4f1539/media-3666657@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8111333d80569f7f219ac5de2a4f1539/media-3666657~dark@2x.png"
        }
      ]
    },
    "media-3683203": {
      "alt": "An illustration showing a graph drawn using the rectangular full-view template.",
      "identifier": "media-3683203",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/acd6832a230be836af2d31f4adf36337/media-3683203@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/acd6832a230be836af2d31f4adf36337/media-3683203~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Articles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/creating-complications-for-your-watchos-app",
        "doc://com.apple.clockkit/documentation/ClockKit/declaring-complications-for-your-app",
        "doc://com.apple.clockkit/documentation/ClockKit/creating-a-timeline-entry",
        "doc://com.apple.clockkit/documentation/ClockKit/loading-future-timeline-events",
        "doc://com.apple.clockkit/documentation/ClockKit/keeping-your-complications-up-to-date",
        "doc://com.apple.clockkit/documentation/ClockKit/displaying-progress-views-and-gauges",
        "doc://com.apple.clockkit/documentation/ClockKit/adding-text-to-a-complication"
      ],
      "title": "Articles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Articles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/creating-complications-for-your-watchos-app",
                "doc://com.apple.clockkit/documentation/ClockKit/declaring-complications-for-your-app",
                "doc://com.apple.clockkit/documentation/ClockKit/creating-a-timeline-entry",
                "doc://com.apple.clockkit/documentation/ClockKit/loading-future-timeline-events",
                "doc://com.apple.clockkit/documentation/ClockKit/keeping-your-complications-up-to-date",
                "doc://com.apple.clockkit/documentation/ClockKit/displaying-progress-views-and-gauges",
                "doc://com.apple.clockkit/documentation/ClockKit/adding-text-to-a-complication"
              ],
              "title": "Articles"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/building-complications-with-swiftui"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/building-complications-with-swiftui"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
