{
  "abstract": [
    {
      "text": "Display small, circular content in the corners of the Color watch face.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/circular-small"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Circular small"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Circular small templates display a small image or a few characters of text in the corners of the Color watch face.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2878965",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily": {
      "abstract": [
        {
          "text": "Constants indicating the template groups.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationFamily"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamily"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate": {
      "abstract": [
        {
          "text": "An abstract class that defines the base behavior for all templates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplate"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplate"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplate",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallRingImage": {
      "abstract": [
        {
          "text": "A template for displaying a single image surrounded by a configurable progress ring.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallRingImage"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallRingImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallRingImage"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateCircularSmallRingImage",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatecircularsmallringimage"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallRingText": {
      "abstract": [
        {
          "text": "A template for displaying a short text string encircled by a configurable progress ring.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallRingText"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallRingText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallRingText"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateCircularSmallRingText",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatecircularsmallringtext"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallSimpleImage": {
      "abstract": [
        {
          "text": "A template for displaying a single image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallSimpleImage"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallSimpleImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallSimpleImage"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateCircularSmallSimpleImage",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatecircularsmallsimpleimage"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallSimpleText": {
      "abstract": [
        {
          "text": "A template for displaying a short text string.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallSimpleText"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallSimpleText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallSimpleText"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateCircularSmallSimpleText",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatecircularsmallsimpletext"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackImage": {
      "abstract": [
        {
          "text": "A template for displaying an image with a line of text below it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallStackImage"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallStackImage"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateCircularSmallStackImage",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatecircularsmallstackimage"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText": {
      "abstract": [
        {
          "text": "A template for displaying two text strings stacked on top of each other.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallStackText"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallStackText"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateCircularSmallStackText",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatecircularsmallstacktext"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode": {
      "abstract": [
        {
          "text": "The complication’s appearance, as specified by the watch face.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ComplicationRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ComplicationRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "ComplicationRenderingMode",
      "type": "topic",
      "url": "/documentation/clockkit/complicationrenderingmode"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/data-providers": {
      "abstract": [
        {
          "text": "Feed data to a complication template.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/data-providers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data providers",
      "type": "topic",
      "url": "/documentation/clockkit/data-providers"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols": {
      "abstract": [],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated articles and symbols",
      "type": "topic",
      "url": "/documentation/clockkit/deprecated-articles-and-symbols"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/extra-large": {
      "abstract": [
        {
          "text": "Display content on the X-Large watch face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/extra-large",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extra large",
      "type": "topic",
      "url": "/documentation/clockkit/extra-large"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/graphic": {
      "abstract": [
        {
          "text": "Display visually rich content on watch faces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/graphic",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Graphic",
      "type": "topic",
      "url": "/documentation/clockkit/graphic"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/modular-large": {
      "abstract": [
        {
          "text": "Display multiple rows of content in the large, central complication on the Modular watch face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/modular-large",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Modular large",
      "type": "topic",
      "url": "/documentation/clockkit/modular-large"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/modular-small": {
      "abstract": [
        {
          "text": "Display content in the smaller spaces of the Modular watch face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/modular-small",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Modular small",
      "type": "topic",
      "url": "/documentation/clockkit/modular-small"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/swiftui-templates": {
      "abstract": [
        {
          "text": "Design complication templates using SwiftUI views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/swiftui-templates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SwiftUI templates",
      "type": "topic",
      "url": "/documentation/clockkit/swiftui-templates"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/utilitarian": {
      "abstract": [
        {
          "text": "Use the utilitarian templates to display content on a variety of watch faces, including the Utility, Chronograph, Simple, and character watch faces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/utilitarian",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Utilitarian",
      "type": "topic",
      "url": "/documentation/clockkit/utilitarian"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies": {
      "abstract": [
        {
          "text": "The complication families for which the app can provide data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLKComplicationSupportedFamilies",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-2878965": {
      "alt": "Examples of the circular small templates. From left to right they are stack text, ring image, stack image, simple text, simple image, and ring text.",
      "identifier": "media-2878965",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5d4d85d3cfd8e416e13d84dbd6da319f/media-2878965@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5d4d85d3cfd8e416e13d84dbd6da319f/media-2878965~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Templates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/swiftui-templates",
        "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode",
        "doc://com.apple.clockkit/documentation/ClockKit/data-providers",
        "doc://com.apple.clockkit/documentation/ClockKit/extra-large",
        "doc://com.apple.clockkit/documentation/ClockKit/modular-small",
        "doc://com.apple.clockkit/documentation/ClockKit/modular-large",
        "doc://com.apple.clockkit/documentation/ClockKit/utilitarian",
        "doc://com.apple.clockkit/documentation/ClockKit/graphic",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies"
      ],
      "title": "Templates"
    }
  ],
  "topicSections": [
    {
      "anchor": "Image-templates",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallRingImage",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallSimpleImage",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackImage"
      ],
      "title": "Image templates"
    },
    {
      "anchor": "Text-templates",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallRingText",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallSimpleText",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText"
      ],
      "title": "Text templates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Image-templates",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallRingImage",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallSimpleImage",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackImage"
              ],
              "title": "Image templates"
            },
            {
              "anchor": "Text-templates",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallRingText",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallSimpleText",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText"
              ],
              "title": "Text templates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Templates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/swiftui-templates",
                "doc://com.apple.clockkit/documentation/ClockKit/data-providers",
                "doc://com.apple.clockkit/documentation/ClockKit/extra-large",
                "doc://com.apple.clockkit/documentation/ClockKit/modular-small",
                "doc://com.apple.clockkit/documentation/ClockKit/modular-large",
                "doc://com.apple.clockkit/documentation/ClockKit/utilitarian",
                "doc://com.apple.clockkit/documentation/ClockKit/graphic",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies"
              ],
              "title": "Templates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallRingImage/title",
          "value": "CLKComplicationTemplateCircularSmallRingImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallRingImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallRingImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallRingImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallRingImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallStackText/title",
          "value": "CLKComplicationTemplateCircularSmallStackText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallStackText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallStackText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallStackText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallStackText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallStackImage/title",
          "value": "CLKComplicationTemplateCircularSmallStackImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallStackImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallStackImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallStackImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallStackImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily/title",
          "value": "CLKComplicationFamily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallSimpleText/title",
          "value": "CLKComplicationTemplateCircularSmallSimpleText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallSimpleText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallSimpleText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallSimpleText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallSimpleText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/title",
          "value": "CLKComplicationTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallRingText/title",
          "value": "CLKComplicationTemplateCircularSmallRingText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallRingText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallRingText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallRingText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallRingText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallSimpleImage/title",
          "value": "CLKComplicationTemplateCircularSmallSimpleImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallSimpleImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallSimpleImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallSimpleImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallSimpleImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/circular-small"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/circular-small"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
