{
  "abstract": [
    {
      "text": "A configuration object that specifies an intents-based complication in WidgetKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLKComplicationIntentWidgetMigrationConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLKComplicationIntentWidgetMigrationConfiguration"
      }
    ],
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLKComplicationIntentWidgetMigrationConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CLKComplicationIntentWidgetMigrationConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLKComplicationIntentWidgetMigrationConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These configuration objects use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Intents/INIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to provide dynamic configuration information. Use intent-based complications when your app customizes the list of complications available in the complication picker based on the state of your app. For example, if you provide temperature complications for the top cities in the user’s favorites list, use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Intents/INIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to describe each city.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WidgetKit/Converting-A-ClockKit-App",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationAppIntentWidgetMigrationConfiguration": {
      "abstract": [
        {
          "text": "A configuration object that specifies a WidgetKit complication that uses app intents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationAppIntentWidgetMigrationConfiguration"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationAppIntentWidgetMigrationConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationAppIntentWidgetMigrationConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationAppIntentWidgetMigrationConfiguration",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationappintentwidgetmigrationconfiguration"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationDataSource/widgetMigrator": {
      "abstract": [
        {
          "text": "A migrator that maps ClockKit complications to their WidgetKit replacements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetMigrator"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CLKComplicationWidgetMigrator",
          "text": "CLKComplicationWidgetMigrator"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationDataSource/widgetMigrator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widgetMigrator"
        }
      ],
      "role": "symbol",
      "title": "widgetMigrator",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationdatasource/widgetmigrator"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration": {
      "abstract": [
        {
          "text": "A configuration object that specifies an intents-based complication in WidgetKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationIntentWidgetMigrationConfiguration"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationIntentWidgetMigrationConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationIntentWidgetMigrationConfiguration",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationintentwidgetmigrationconfiguration"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/extensionBundleIdentifier": {
      "abstract": [
        {
          "text": "The bundle identifier for your WidgetKit extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionBundleIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/extensionBundleIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extensionBundleIdentifier"
        }
      ],
      "role": "symbol",
      "title": "extensionBundleIdentifier",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationintentwidgetmigrationconfiguration/extensionbundleidentifier"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/init(kind:extensionBundleIdentifier:intent:localizedDisplayName:)": {
      "abstract": [
        {
          "text": "Creates an object that describes an intents-based watchOS complication in your WidgetKit extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "kind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "extensionBundleIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INIntent",
          "text": "INIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedDisplayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/init(kind:extensionBundleIdentifier:intent:localizedDisplayName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithKind:extensionBundleIdentifier:intent:localizedDisplayName:"
        }
      ],
      "role": "symbol",
      "title": "init(kind:extensionBundleIdentifier:intent:localizedDisplayName:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationintentwidgetmigrationconfiguration/init(kind:extensionbundleidentifier:intent:localizeddisplayname:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/intent": {
      "abstract": [
        {
          "text": "A SiriKit intent that provides additional configuration information to your WidgetKit complication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INIntent",
          "text": "INIntent"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/intent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "intent"
        }
      ],
      "role": "symbol",
      "title": "intent",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationintentwidgetmigrationconfiguration/intent"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/intentWidgetMigrationConfigurationWithKind:extensionBundleIdentifier:intent:localizedDisplayName:": {
      "abstract": [
        {
          "text": "Creates an object that describes an intents-based watchOS complication in your WidgetKit extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "intentWidgetMigrationConfigurationWithKind:extensionBundleIdentifier:intent:localizedDisplayName:"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/intentWidgetMigrationConfigurationWithKind:extensionBundleIdentifier:intent:localizedDisplayName:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "intentWidgetMigrationConfigurationWithKind:extensionBundleIdentifier:intent:localizedDisplayName:"
        }
      ],
      "role": "symbol",
      "title": "intentWidgetMigrationConfigurationWithKind:extensionBundleIdentifier:intent:localizedDisplayName:",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationintentwidgetmigrationconfiguration/intentwidgetmigrationconfigurationwithkind:extensionbundleidentifier:intent:localizeddisplayname:"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/kind": {
      "abstract": [
        {
          "text": "A string that uniquely identifies a widget in your WidgetKit extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/kind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kind"
        }
      ],
      "role": "symbol",
      "title": "kind",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationintentwidgetmigrationconfiguration/kind"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/localizedDisplayName": {
      "abstract": [
        {
          "text": "A localized name for the complication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedDisplayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/localizedDisplayName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedDisplayName"
        }
      ],
      "role": "symbol",
      "title": "localizedDisplayName",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationintentwidgetmigrationconfiguration/localizeddisplayname"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationStaticWidgetMigrationConfiguration": {
      "abstract": [
        {
          "text": "A configuration object that specifies a static complication in WidgetKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationStaticWidgetMigrationConfiguration"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationStaticWidgetMigrationConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationStaticWidgetMigrationConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationStaticWidgetMigrationConfiguration",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationstaticwidgetmigrationconfiguration"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrationConfiguration": {
      "abstract": [
        {
          "text": "An abstract class that specifies WidgetKit complications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationWidgetMigrationConfiguration"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrationConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationWidgetMigrationConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationWidgetMigrationConfiguration",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationwidgetmigrationconfiguration"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrator": {
      "abstract": [
        {
          "text": "A protocol that maps ClockKit complications to their WidgetKit replacements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationWidgetMigrator"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationWidgetMigrator"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationWidgetMigrator",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationwidgetmigrator"
    },
    "doc://com.apple.documentation/documentation/Intents/INIntent": {
      "abstract": [
        {
          "text": "A request to fulfill in your app or Intents extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntent"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Intents/INIntent",
      "kind": "symbol",
      "role": "symbol",
      "title": "INIntent",
      "type": "topic",
      "url": "/documentation/Intents/INIntent"
    },
    "doc://com.apple.documentation/documentation/WidgetKit/Converting-A-ClockKit-App": {
      "abstract": [
        {
          "text": "Leverage WidgetKit’s API to create watchOS complications using SwiftUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WidgetKit/Converting-A-ClockKit-App",
      "kind": "article",
      "role": "article",
      "title": "Migrating ClockKit complications to WidgetKit",
      "type": "topic",
      "url": "/documentation/WidgetKit/Converting-A-ClockKit-App"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrationConfiguration"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Migrating-to-WidgetKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationDataSource/widgetMigrator",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationStaticWidgetMigrationConfiguration",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationAppIntentWidgetMigrationConfiguration",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrator",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrationConfiguration"
      ],
      "title": "Migrating to WidgetKit"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Intent-widget-configurations",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/init(kind:extensionBundleIdentifier:intent:localizedDisplayName:)"
      ],
      "title": "Creating Intent widget configurations"
    },
    {
      "anchor": "Accessing-configuration-properties",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/kind",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/extensionBundleIdentifier",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/intent",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/localizedDisplayName"
      ],
      "title": "Accessing configuration properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLKComplicationIntentWidgetMigrationConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationIntentWidgetMigrationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationIntentWidgetMigrationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.clockkit/documentation/ClockKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Intent-widget-configurations",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/init(kind:extensionBundleIdentifier:intent:localizedDisplayName:)",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/intentWidgetMigrationConfigurationWithKind:extensionBundleIdentifier:intent:localizedDisplayName:"
              ],
              "title": "Creating Intent widget configurations"
            },
            {
              "anchor": "Accessing-configuration-properties",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/kind",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/extensionBundleIdentifier",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/intent",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration/localizedDisplayName"
              ],
              "title": "Accessing configuration properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrationConfiguration"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Migrating-to-WidgetKit",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationDataSource/widgetMigrator",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationStaticWidgetMigrationConfiguration",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrator",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrationConfiguration"
              ],
              "title": "Migrating to WidgetKit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLKComplicationIntentWidgetMigrationConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrationConfiguration",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CLKComplicationWidgetMigrationConfiguration",
                    "text": "CLKComplicationWidgetMigrationConfiguration"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationWidgetMigrationConfiguration/title",
          "value": "CLKComplicationWidgetMigrationConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationWidgetMigrationConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationWidgetMigrationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationWidgetMigrationConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationWidgetMigrationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Intents~1INIntent/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INIntent"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationDataSource~1widgetMigrator/title",
          "value": "widgetMigrator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationDataSource~1widgetMigrator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "widgetMigrator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration~1localizedDisplayName/title",
          "value": "localizedDisplayName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration~1localizedDisplayName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedDisplayName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration~1init(kind:extensionBundleIdentifier:intent:localizedDisplayName:)/title",
          "value": "initWithKind:extensionBundleIdentifier:intent:localizedDisplayName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration~1init(kind:extensionBundleIdentifier:intent:localizedDisplayName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithKind:extensionBundleIdentifier:intent:localizedDisplayName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration/title",
          "value": "CLKComplicationIntentWidgetMigrationConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationIntentWidgetMigrationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationIntentWidgetMigrationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration~1extensionBundleIdentifier/title",
          "value": "extensionBundleIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration~1extensionBundleIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extensionBundleIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration~1kind/title",
          "value": "kind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration~1kind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration~1intent/title",
          "value": "intent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration~1intent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "intent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationStaticWidgetMigrationConfiguration/title",
          "value": "CLKComplicationStaticWidgetMigrationConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationStaticWidgetMigrationConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationStaticWidgetMigrationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationStaticWidgetMigrationConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationStaticWidgetMigrationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationWidgetMigrator/title",
          "value": "CLKComplicationWidgetMigrator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationWidgetMigrator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationWidgetMigrator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationWidgetMigrator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationWidgetMigrator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationintentwidgetmigrationconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationintentwidgetmigrationconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
