{
  "abstract": [
    {
      "text": "Metadata about a custom complication.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to create complications for watchOS 10 or later. For more information, see Migrating to WidgetKit.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLKComplication",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLKComplication"
      }
    ],
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLKComplication"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "2.0",
        "message": "On watchOS 9.0 or later, use WidgetKit instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CLKComplication"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLKComplication"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.clockkit/documentation/ClockKit/creating-a-timeline-entry",
        "doc://com.apple.clockkit/documentation/ClockKit/sharing-an-apple-watch-face"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "ClockKit defines each complication by its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/family",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/identifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties. Each pair represents a unique complication that the user can select when configuring a watch face. When creating timeline entries, check both properties before creating and filling the complication’s template.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You specify the possible ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/family",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/identifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " combinations in your data source’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationDataSource/getComplicationDescriptors(handler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. Each of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects you provide defines a unique identifier and the families that it supports.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In watchOS 6 and earlier, each app can have only one complication per supported family. When your app creates complication templates, determine the complication’s type from its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/family",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property only. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/declaring-complications-for-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You don’t create instances of this class directly. Instead, you retrieve them from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationServer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. Complication objects are only available when your complication is in use on the watch face.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In addition to getting information about the complication, you use complication objects to extend or replace the timeline data for one of your active complications. When calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationServer/extendTimeline(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationServer/reloadTimeline(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods of the shared ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationServer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, pass the complication object you want to update.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication": {
      "abstract": [
        {
          "text": "Metadata about a custom complication.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplication"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplication"
        }
      ],
      "role": "symbol",
      "title": "CLKComplication",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplication"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/family": {
      "abstract": [
        {
          "text": "The family to which the complication belongs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "family"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLKComplicationFamily",
          "text": "CLKComplicationFamily"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/family",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "family"
        }
      ],
      "role": "symbol",
      "title": "family",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplication/family"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/identifier": {
      "abstract": [
        {
          "text": "An identifier that specifies a complication if your app supports multiple complications per family.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplication/identifier"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/userActivity": {
      "abstract": [
        {
          "text": "An object that represents the state of the app at a moment in time.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/userActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userActivity"
        }
      ],
      "role": "symbol",
      "title": "userActivity",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplication/useractivity"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/userInfo": {
      "abstract": [
        {
          "text": "A dictionary of additional data associated with the complication.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/userInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInfo"
        }
      ],
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplication/userinfo"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationDataSource/getComplicationDescriptors(handler:)": {
      "abstract": [
        {
          "text": "Returns the list of complication descriptors.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getComplicationDescriptors"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKComplicationDescriptor",
          "text": "CLKComplicationDescriptor"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationDataSource/getComplicationDescriptors(handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getComplicationDescriptorsWithHandler:"
        }
      ],
      "role": "symbol",
      "title": "getComplicationDescriptors(handler:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationdatasource/getcomplicationdescriptors(handler:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationDescriptor": {
      "abstract": [
        {
          "text": "A descriptor that defines a complication and the families that it supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationDescriptor"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationDescriptor"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationDescriptor",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationdescriptor"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationServer": {
      "abstract": [
        {
          "text": "An object that manages the active complications for an app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationServer"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationServer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationServer"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationServer",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationserver"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationServer/extendTimeline(for:)": {
      "abstract": [
        {
          "text": "Asks the system to extend the data in your complication’s timeline.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendTimeline"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKComplication",
          "text": "CLKComplication"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationServer/extendTimeline(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendTimelineForComplication:"
        }
      ],
      "role": "symbol",
      "title": "extendTimeline(for:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationserver/extendtimeline(for:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationServer/reloadTimeline(for:)": {
      "abstract": [
        {
          "text": "Invalidates your existing timeline data and triggers an update session to reload it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reloadTimeline"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKComplication",
          "text": "CLKComplication"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationServer/reloadTimeline(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reloadTimelineForComplication:"
        }
      ],
      "role": "symbol",
      "title": "reloadTimeline(for:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationserver/reloadtimeline(for:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTimelineEntry": {
      "abstract": [
        {
          "text": "A container for the complication template object to display and the time to display it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTimelineEntry"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTimelineEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTimelineEntry"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTimelineEntry",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtimelineentry"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/creating-a-timeline-entry": {
      "abstract": [
        {
          "text": "Package your app-specific data into a template and create a timeline entry for that template.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/creating-a-timeline-entry",
      "kind": "article",
      "role": "article",
      "title": "Creating a timeline entry",
      "type": "topic",
      "url": "/documentation/clockkit/creating-a-timeline-entry"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/declaring-complications-for-your-app": {
      "abstract": [
        {
          "text": "Define the complications that your app supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/declaring-complications-for-your-app",
      "kind": "article",
      "role": "article",
      "title": "Declaring complications for your app",
      "type": "topic",
      "url": "/documentation/clockkit/declaring-complications-for-your-app"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/sharing-an-apple-watch-face": {
      "abstract": [
        {
          "text": "Distribute a customized watch face to Apple Watch users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/sharing-an-apple-watch-face",
      "kind": "article",
      "role": "article",
      "title": "Sharing an Apple Watch face",
      "type": "topic",
      "url": "/documentation/clockkit/sharing-an-apple-watch-face"
    },
    "doc://com.apple.documentation/documentation/WidgetKit": {
      "abstract": [
        {
          "text": "Extend the reach of your app by creating widgets, watch complications, Live Activities, and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WidgetKit",
      "type": "topic",
      "url": "/documentation/WidgetKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Other-Symbols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationServer",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTimelineEntry"
      ],
      "title": "Other Symbols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Data-About-the-Complication",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/family",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/identifier",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/userActivity",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/userInfo"
      ],
      "title": "Accessing Data About the Complication"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLKComplication"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.clockkit/documentation/ClockKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Data-About-the-Complication",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/family",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/identifier",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/userActivity",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplication/userInfo"
              ],
              "title": "Accessing Data About the Complication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Other-Symbols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationServer",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTimelineEntry"
              ],
              "title": "Other Symbols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLKComplication"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to create complications for watchOS 10 or later. For more information, see Migrating to WidgetKit.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplication~1userInfo/title",
          "value": "userInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplication~1userInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplication/title",
          "value": "CLKComplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationServer/title",
          "value": "CLKComplicationServer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationServer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationServer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationServer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationServer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplication~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplication~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationDataSource~1getComplicationDescriptors(handler:)/title",
          "value": "getComplicationDescriptorsWithHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationDataSource~1getComplicationDescriptors(handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getComplicationDescriptorsWithHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTimelineEntry/title",
          "value": "CLKComplicationTimelineEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTimelineEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTimelineEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTimelineEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTimelineEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationServer~1extendTimeline(for:)/title",
          "value": "extendTimelineForComplication:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationServer~1extendTimeline(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "extendTimelineForComplication:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplication~1family/title",
          "value": "family"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplication~1family/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "family"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplication~1userActivity/title",
          "value": "userActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplication~1userActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationDescriptor/title",
          "value": "CLKComplicationDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationServer~1reloadTimeline(for:)/title",
          "value": "reloadTimelineForComplication:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationServer~1reloadTimeline(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reloadTimelineForComplication:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkcomplication"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/clkcomplication"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
