{
  "abstract": [
    {
      "text": "A protocol that maps ClockKit complications to their WidgetKit replacements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrator"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CLKComplicationWidgetMigrator",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLKComplicationWidgetMigrator"
      }
    ],
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLKComplicationWidgetMigrator"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CLKComplicationWidgetMigrator"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLKComplicationWidgetMigrator"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationAppIntentWidgetMigrationConfiguration": {
      "abstract": [
        {
          "text": "A configuration object that specifies a WidgetKit complication that uses app intents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationAppIntentWidgetMigrationConfiguration"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationAppIntentWidgetMigrationConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationAppIntentWidgetMigrationConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationAppIntentWidgetMigrationConfiguration",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationappintentwidgetmigrationconfiguration"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationDataSource/widgetMigrator": {
      "abstract": [
        {
          "text": "A migrator that maps ClockKit complications to their WidgetKit replacements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetMigrator"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CLKComplicationWidgetMigrator",
          "text": "CLKComplicationWidgetMigrator"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationDataSource/widgetMigrator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widgetMigrator"
        }
      ],
      "role": "symbol",
      "title": "widgetMigrator",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationdatasource/widgetmigrator"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration": {
      "abstract": [
        {
          "text": "A configuration object that specifies an intents-based complication in WidgetKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationIntentWidgetMigrationConfiguration"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationIntentWidgetMigrationConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationIntentWidgetMigrationConfiguration",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationintentwidgetmigrationconfiguration"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationStaticWidgetMigrationConfiguration": {
      "abstract": [
        {
          "text": "A configuration object that specifies a static complication in WidgetKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationStaticWidgetMigrationConfiguration"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationStaticWidgetMigrationConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationStaticWidgetMigrationConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationStaticWidgetMigrationConfiguration",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationstaticwidgetmigrationconfiguration"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrationConfiguration": {
      "abstract": [
        {
          "text": "An abstract class that specifies WidgetKit complications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationWidgetMigrationConfiguration"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrationConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationWidgetMigrationConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationWidgetMigrationConfiguration",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationwidgetmigrationconfiguration"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrator": {
      "abstract": [
        {
          "text": "A protocol that maps ClockKit complications to their WidgetKit replacements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationWidgetMigrator"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationWidgetMigrator"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationWidgetMigrator",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationwidgetmigrator"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrator/getWidgetConfiguration(from:completionHandler:)": {
      "abstract": [
        {
          "text": "Returns a configuration object that defines the WidgetKit replacement for the provided ClockKit complication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getWidgetConfiguration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKComplicationDescriptor",
          "text": "CLKComplicationDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKComplicationWidgetMigrationConfiguration",
          "text": "CLKComplicationWidgetMigrationConfiguration"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrator/getWidgetConfiguration(from:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getWidgetConfigurationFrom:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "getWidgetConfiguration(from:completionHandler:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationwidgetmigrator/getwidgetconfiguration(from:completionhandler:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Migrating-to-WidgetKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationDataSource/widgetMigrator",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationStaticWidgetMigrationConfiguration",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationAppIntentWidgetMigrationConfiguration",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrationConfiguration"
      ],
      "title": "Migrating to WidgetKit"
    }
  ],
  "topicSections": [
    {
      "anchor": "Migrating-complications",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrator/getWidgetConfiguration(from:completionHandler:)"
      ],
      "title": "Migrating complications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLKComplicationWidgetMigrator"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationWidgetMigrator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationWidgetMigrator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.clockkit/documentation/ClockKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Migrating-complications",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrator/getWidgetConfiguration(from:completionHandler:)"
              ],
              "title": "Migrating complications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Migrating-to-WidgetKit",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationDataSource/widgetMigrator",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationStaticWidgetMigrationConfiguration",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationIntentWidgetMigrationConfiguration",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationWidgetMigrationConfiguration"
              ],
              "title": "Migrating to WidgetKit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLKComplicationWidgetMigrator"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationWidgetMigrator~1getWidgetConfiguration(from:completionHandler:)/title",
          "value": "getWidgetConfigurationFrom:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationWidgetMigrator~1getWidgetConfiguration(from:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getWidgetConfigurationFrom:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationStaticWidgetMigrationConfiguration/title",
          "value": "CLKComplicationStaticWidgetMigrationConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationStaticWidgetMigrationConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationStaticWidgetMigrationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationStaticWidgetMigrationConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationStaticWidgetMigrationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationWidgetMigrator/title",
          "value": "CLKComplicationWidgetMigrator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationWidgetMigrator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationWidgetMigrator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationWidgetMigrator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationWidgetMigrator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration/title",
          "value": "CLKComplicationIntentWidgetMigrationConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationIntentWidgetMigrationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationIntentWidgetMigrationConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationIntentWidgetMigrationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationWidgetMigrationConfiguration/title",
          "value": "CLKComplicationWidgetMigrationConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationWidgetMigrationConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationWidgetMigrationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationWidgetMigrationConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationWidgetMigrationConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationDataSource~1widgetMigrator/title",
          "value": "widgetMigrator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationDataSource~1widgetMigrator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "widgetMigrator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationwidgetmigrator"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationwidgetmigrator"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
