{
  "abstract": [
    {
      "text": "A template for displaying two text strings stacked on top of each other.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to create complications for watchOS 10 or later. For more information, see Migrating to WidgetKit.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLKComplicationTemplateCircularSmallStackText",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLKComplicationTemplateCircularSmallStackText"
      }
    ],
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLKComplicationTemplateCircularSmallStackText"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "2.0",
        "message": "On watchOS 9.0 or later, use WidgetKit instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CLKComplicationTemplateCircularSmallStackText"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallStackText"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This template belongs to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/circularSmall",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " family.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2933743",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/circularSmall": {
      "abstract": [
        {
          "text": "A small circular area that ClockKit displays on the Color watch face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "circularSmall"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/circularSmall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyCircularSmall"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.circularSmall",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/circularsmall"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate": {
      "abstract": [
        {
          "text": "An abstract class that defines the base behavior for all templates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplate"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplate"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplate",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallRingText": {
      "abstract": [
        {
          "text": "A template for displaying a short text string encircled by a configurable progress ring.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallRingText"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallRingText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallRingText"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateCircularSmallRingText",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatecircularsmallringtext"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallSimpleText": {
      "abstract": [
        {
          "text": "A template for displaying a short text string.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallSimpleText"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallSimpleText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallSimpleText"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateCircularSmallSimpleText",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatecircularsmallsimpletext"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText": {
      "abstract": [
        {
          "text": "A template for displaying two text strings stacked on top of each other.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallStackText"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateCircularSmallStackText"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateCircularSmallStackText",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatecircularsmallstacktext"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText/init(line1TextProvider:line2TextProvider:)": {
      "abstract": [
        {
          "text": "Creates a new template that has two lines of text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "line1TextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "line2TextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText/init(line1TextProvider:line2TextProvider:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLine1TextProvider:line2TextProvider:"
        }
      ],
      "role": "symbol",
      "title": "init(line1TextProvider:line2TextProvider:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatecircularsmallstacktext/init(line1textprovider:line2textprovider:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText/line1TextProvider": {
      "abstract": [
        {
          "text": "The text to display on the top line of the complication.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "line1TextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText/line1TextProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "line1TextProvider"
        }
      ],
      "role": "symbol",
      "title": "line1TextProvider",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatecircularsmallstacktext/line1textprovider"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText/line2TextProvider": {
      "abstract": [
        {
          "text": "The text to display on the bottom line of the complication.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "line2TextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText/line2TextProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "line2TextProvider"
        }
      ],
      "role": "symbol",
      "title": "line2TextProvider",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatecircularsmallstacktext/line2textprovider"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText/templateWithLine1TextProvider:line2TextProvider:": {
      "abstract": [
        {
          "text": "Returns a new template that has two lines of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "templateWithLine1TextProvider:line2TextProvider:"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText/templateWithLine1TextProvider:line2TextProvider:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateWithLine1TextProvider:line2TextProvider:"
        }
      ],
      "role": "symbol",
      "title": "templateWithLine1TextProvider:line2TextProvider:",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatecircularsmallstacktext/templatewithline1textprovider:line2textprovider:"
    },
    "doc://com.apple.documentation/documentation/WidgetKit": {
      "abstract": [
        {
          "text": "Extend the reach of your app by creating widgets, watch complications, Live Activities, and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WidgetKit",
      "type": "topic",
      "url": "/documentation/WidgetKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "media-2933743": {
      "alt": "A diagram showing the layout of the circular small stack text complication. The diagram has two examples, each showing two small rows of text.",
      "identifier": "media-2933743",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c65d0106f8b763df0c4843c10f46047a/media-2933743@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6e3eb36dab7d79718f04b9b13b722e75/media-2933743~dark@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-templates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallRingText",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallSimpleText"
      ],
      "title": "Text templates"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-the-Template",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText/init(line1TextProvider:line2TextProvider:)"
      ],
      "title": "Creating the Template"
    },
    {
      "anchor": "Setting-the-Complication-Data",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText/line1TextProvider",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText/line2TextProvider"
      ],
      "title": "Setting the Complication Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLKComplicationTemplateCircularSmallStackText"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallStackText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallStackText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.clockkit/documentation/ClockKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-the-Template",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText/init(line1TextProvider:line2TextProvider:)",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText/templateWithLine1TextProvider:line2TextProvider:"
              ],
              "title": "Creating the Template"
            },
            {
              "anchor": "Setting-the-Complication-Data",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText/line1TextProvider",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallStackText/line2TextProvider"
              ],
              "title": "Setting the Complication Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text-templates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallRingText",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateCircularSmallSimpleText"
              ],
              "title": "Text templates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLKComplicationTemplateCircularSmallStackText"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CLKComplicationTemplate",
                    "text": "CLKComplicationTemplate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to create complications for watchOS 10 or later. For more information, see Migrating to WidgetKit.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallStackText~1line2TextProvider/title",
          "value": "line2TextProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallStackText~1line2TextProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "line2TextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallStackText~1line1TextProvider/title",
          "value": "line1TextProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallStackText~1line1TextProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "line1TextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1circularSmall/title",
          "value": "CLKComplicationFamilyCircularSmall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1circularSmall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyCircularSmall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallRingText/title",
          "value": "CLKComplicationTemplateCircularSmallRingText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallRingText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallRingText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallRingText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallRingText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallStackText~1init(line1TextProvider:line2TextProvider:)/title",
          "value": "initWithLine1TextProvider:line2TextProvider:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallStackText~1init(line1TextProvider:line2TextProvider:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLine1TextProvider:line2TextProvider:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/title",
          "value": "CLKComplicationTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallStackText/title",
          "value": "CLKComplicationTemplateCircularSmallStackText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallStackText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallStackText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallStackText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallStackText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallSimpleText/title",
          "value": "CLKComplicationTemplateCircularSmallSimpleText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallSimpleText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallSimpleText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateCircularSmallSimpleText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateCircularSmallSimpleText"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationtemplatecircularsmallstacktext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationtemplatecircularsmallstacktext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
