{
  "abstract": [
    {
      "text": "Constants indicating the template groups.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to create complications for watchOS 10 or later. For more information, see Migrating to WidgetKit.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLKComplicationFamily",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLKComplicationFamily"
      }
    ],
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLKComplicationFamily"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CLKComplicationFamily"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLKComplicationFamily"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.clockkit/documentation/ClockKit/creating-a-timeline-entry"
      ]
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily": {
      "abstract": [
        {
          "text": "Constants indicating the template groups.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationFamily"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamily"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/circularSmall": {
      "abstract": [
        {
          "text": "A small circular area that ClockKit displays on the Color watch face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "circularSmall"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/circularSmall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyCircularSmall"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.circularSmall",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/circularsmall"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/extraLarge": {
      "abstract": [
        {
          "text": "A large square area that ClockKit displays on the X-Large watch face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extraLarge"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/extraLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyExtraLarge"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.extraLarge",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/extralarge"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicBezel": {
      "abstract": [
        {
          "text": "A circular area with optional curved text that ClockKit displays along the bezel of the Infograph watch face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicBezel"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicBezel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyGraphicBezel"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.graphicBezel",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/graphicbezel"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCircular": {
      "abstract": [
        {
          "text": "A circular area that ClockKit displays on the Infograph and Infograph Modular watch faces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicCircular"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCircular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyGraphicCircular"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.graphicCircular",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/graphiccircular"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCorner": {
      "abstract": [
        {
          "text": "A curved area that fills the corners in the Infograph watch face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicCorner"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCorner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyGraphicCorner"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.graphicCorner",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/graphiccorner"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicExtraLarge": {
      "abstract": [
        {
          "text": "A large square area that ClockKit displays on the X-Large watch face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicExtraLarge"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicExtraLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyGraphicExtraLarge"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.graphicExtraLarge",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/graphicextralarge"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicRectangular": {
      "abstract": [
        {
          "text": "A large rectangular area that ClockKit displays in the center of the Infograph Modular watch face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicRectangular"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicRectangular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyGraphicRectangular"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.graphicRectangular",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/graphicrectangular"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/init(rawvalue:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/modularLarge": {
      "abstract": [
        {
          "text": "A large rectangular area that ClockKit displays on the Modular watch face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modularLarge"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/modularLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyModularLarge"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.modularLarge",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/modularlarge"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/modularSmall": {
      "abstract": [
        {
          "text": "A small square area that ClockKit displays on the Modular watch face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modularSmall"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/modularSmall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyModularSmall"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.modularSmall",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/modularsmall"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/utilitarianLarge": {
      "abstract": [
        {
          "text": "A large rectangular area that spans the width of the screen in the Utility and Mickey watch faces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "utilitarianLarge"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/utilitarianLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyUtilitarianLarge"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.utilitarianLarge",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/utilitarianlarge"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/utilitarianSmall": {
      "abstract": [
        {
          "text": "A small square or rectangular area that ClockKit Displays on the Utility, Mickey, Chronograph, and Simple watch faces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "utilitarianSmall"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/utilitarianSmall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyUtilitarianSmall"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.utilitarianSmall",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/utilitariansmall"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/utilitarianSmallFlat": {
      "abstract": [
        {
          "text": "A small rectangular area that ClockKit Displays on the Photos, Motion, and Timelapse watch faces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "utilitarianSmallFlat"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/utilitarianSmallFlat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyUtilitarianSmallFlat"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.utilitarianSmallFlat",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/utilitariansmallflat"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate": {
      "abstract": [
        {
          "text": "An abstract class that defines the base behavior for all templates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplate"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplate"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplate",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode": {
      "abstract": [
        {
          "text": "The complication’s appearance, as specified by the watch face.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ComplicationRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ComplicationRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "ComplicationRenderingMode",
      "type": "topic",
      "url": "/documentation/clockkit/complicationrenderingmode"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/circular-small": {
      "abstract": [
        {
          "text": "Display small, circular content in the corners of the Color watch face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/circular-small",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Circular small",
      "type": "topic",
      "url": "/documentation/clockkit/circular-small"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/creating-a-timeline-entry": {
      "abstract": [
        {
          "text": "Package your app-specific data into a template and create a timeline entry for that template.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/creating-a-timeline-entry",
      "kind": "article",
      "role": "article",
      "title": "Creating a timeline entry",
      "type": "topic",
      "url": "/documentation/clockkit/creating-a-timeline-entry"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/data-providers": {
      "abstract": [
        {
          "text": "Feed data to a complication template.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/data-providers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data providers",
      "type": "topic",
      "url": "/documentation/clockkit/data-providers"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/extra-large": {
      "abstract": [
        {
          "text": "Display content on the X-Large watch face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/extra-large",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extra large",
      "type": "topic",
      "url": "/documentation/clockkit/extra-large"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/graphic": {
      "abstract": [
        {
          "text": "Display visually rich content on watch faces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/graphic",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Graphic",
      "type": "topic",
      "url": "/documentation/clockkit/graphic"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/modular-large": {
      "abstract": [
        {
          "text": "Display multiple rows of content in the large, central complication on the Modular watch face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/modular-large",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Modular large",
      "type": "topic",
      "url": "/documentation/clockkit/modular-large"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/modular-small": {
      "abstract": [
        {
          "text": "Display content in the smaller spaces of the Modular watch face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/modular-small",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Modular small",
      "type": "topic",
      "url": "/documentation/clockkit/modular-small"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/swiftui-templates": {
      "abstract": [
        {
          "text": "Design complication templates using SwiftUI views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/swiftui-templates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SwiftUI templates",
      "type": "topic",
      "url": "/documentation/clockkit/swiftui-templates"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/utilitarian": {
      "abstract": [
        {
          "text": "Use the utilitarian templates to display content on a variety of watch faces, including the Utility, Chronograph, Simple, and character watch faces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/utilitarian",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Utilitarian",
      "type": "topic",
      "url": "/documentation/clockkit/utilitarian"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies": {
      "abstract": [
        {
          "text": "The complication families for which the app can provide data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLKComplicationSupportedFamilies",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies"
    },
    "doc://com.apple.documentation/documentation/WidgetKit": {
      "abstract": [
        {
          "text": "Extend the reach of your app by creating widgets, watch complications, Live Activities, and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WidgetKit",
      "type": "topic",
      "url": "/documentation/WidgetKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s12CaseIterableP": {
      "abstract": [
        {
          "text": "A type that provides a collection of all of its values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CaseIterable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s12CaseIterableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CaseIterable",
      "type": "topic",
      "url": "/documentation/Swift/CaseIterable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s12CaseIterableP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Templates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/swiftui-templates",
        "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode",
        "doc://com.apple.clockkit/documentation/ClockKit/data-providers",
        "doc://com.apple.clockkit/documentation/ClockKit/circular-small",
        "doc://com.apple.clockkit/documentation/ClockKit/extra-large",
        "doc://com.apple.clockkit/documentation/ClockKit/modular-small",
        "doc://com.apple.clockkit/documentation/ClockKit/modular-large",
        "doc://com.apple.clockkit/documentation/ClockKit/utilitarian",
        "doc://com.apple.clockkit/documentation/ClockKit/graphic",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies"
      ],
      "title": "Templates"
    }
  ],
  "topicSections": [
    {
      "anchor": "Circular-Small",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/circularSmall"
      ],
      "title": "Circular Small"
    },
    {
      "anchor": "Extra-Large",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/extraLarge"
      ],
      "title": "Extra Large"
    },
    {
      "anchor": "Modular",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/modularSmall",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/modularLarge"
      ],
      "title": "Modular"
    },
    {
      "anchor": "Utilitarian",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/utilitarianSmall",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/utilitarianSmallFlat",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/utilitarianLarge"
      ],
      "title": "Utilitarian"
    },
    {
      "anchor": "Graphic",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCorner",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCircular",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicBezel",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicRectangular",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicExtraLarge"
      ],
      "title": "Graphic"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLKComplicationFamily"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.clockkit/documentation/ClockKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Circular-Small",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/circularSmall"
              ],
              "title": "Circular Small"
            },
            {
              "anchor": "Extra-Large",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/extraLarge"
              ],
              "title": "Extra Large"
            },
            {
              "anchor": "Modular",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/modularSmall",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/modularLarge"
              ],
              "title": "Modular"
            },
            {
              "anchor": "Utilitarian",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/utilitarianSmall",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/utilitarianSmallFlat",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/utilitarianLarge"
              ],
              "title": "Utilitarian"
            },
            {
              "anchor": "Graphic",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCorner",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicCircular",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicBezel",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicRectangular",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicExtraLarge"
              ],
              "title": "Graphic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Templates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/swiftui-templates",
                "doc://com.apple.clockkit/documentation/ClockKit/data-providers",
                "doc://com.apple.clockkit/documentation/ClockKit/circular-small",
                "doc://com.apple.clockkit/documentation/ClockKit/extra-large",
                "doc://com.apple.clockkit/documentation/ClockKit/modular-small",
                "doc://com.apple.clockkit/documentation/ClockKit/modular-large",
                "doc://com.apple.clockkit/documentation/ClockKit/utilitarian",
                "doc://com.apple.clockkit/documentation/ClockKit/graphic",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies"
              ],
              "title": "Templates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLKComplicationFamily"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to create complications for watchOS 10 or later. For more information, see Migrating to WidgetKit.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1modularLarge/title",
          "value": "CLKComplicationFamilyModularLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1modularLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyModularLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1utilitarianLarge/title",
          "value": "CLKComplicationFamilyUtilitarianLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1utilitarianLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyUtilitarianLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily/title",
          "value": "CLKComplicationFamily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1utilitarianSmallFlat/title",
          "value": "CLKComplicationFamilyUtilitarianSmallFlat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1utilitarianSmallFlat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyUtilitarianSmallFlat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicCorner/title",
          "value": "CLKComplicationFamilyGraphicCorner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicCorner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyGraphicCorner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicExtraLarge/title",
          "value": "CLKComplicationFamilyGraphicExtraLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicExtraLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyGraphicExtraLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicRectangular/title",
          "value": "CLKComplicationFamilyGraphicRectangular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicRectangular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyGraphicRectangular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/title",
          "value": "CLKComplicationTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicCircular/title",
          "value": "CLKComplicationFamilyGraphicCircular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicCircular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyGraphicCircular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1utilitarianSmall/title",
          "value": "CLKComplicationFamilyUtilitarianSmall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1utilitarianSmall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyUtilitarianSmall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1modularSmall/title",
          "value": "CLKComplicationFamilyModularSmall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1modularSmall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyModularSmall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicBezel/title",
          "value": "CLKComplicationFamilyGraphicBezel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicBezel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyGraphicBezel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1circularSmall/title",
          "value": "CLKComplicationFamilyCircularSmall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1circularSmall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyCircularSmall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1extraLarge/title",
          "value": "CLKComplicationFamilyExtraLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1extraLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyExtraLarge"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationfamily"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationfamily"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
