{
  "abstract": [
    {
      "text": "A template for displaying a large rectangle containing text and a gauge.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to create complications for watchOS 10 or later. For more information, see Migrating to WidgetKit.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLKComplicationTemplateGraphicRectangularTextGauge",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CLKComplicationTemplateGraphicRectangularTextGauge"
      }
    ],
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLKComplicationTemplateGraphicRectangularTextGauge"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "5.0",
        "message": "On watchOS 9.0 or later, use WidgetKit instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CLKComplicationTemplateGraphicRectangularTextGauge"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularTextGauge"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This template belongs to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicRectangular",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " family. ",
              "type": "text"
            },
            {
              "identifier": "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge#3030706",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " shows the layout of the image and where the template might appear on the clock face.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3030706",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following table lists the dimensions of the image you use in this template. All dimensions are in pixels. All images must be specified as @2x images for display on Apple Watch, so the point-based dimensions are half the listed size.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Apple Watch Size",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Width",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Height",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "40 mm",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "24 pixels",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "24 pixels",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "41 mm",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "25 pixels",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "25 pixels",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "44 mm",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "27 pixels",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "27 pixels",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "45 mm",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "29 pixels",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "29 pixels",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "This template supports full-color images.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Instead of providing multiple images with different resolutions, you can provide a single, scaleable PDF asset. For more information, see ",
              "type": "text"
            },
            {
              "code": "Supporting Multiple Watch Sizes",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge#3030706": {
      "identifier": "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge#3030706",
      "title": "Figure 1",
      "titleInlineContent": [
        {
          "text": "Figure 1",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge#3030706"
    },
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicRectangular": {
      "abstract": [
        {
          "text": "A large rectangular area that ClockKit displays in the center of the Infograph Modular watch face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicRectangular"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily/graphicRectangular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamilyGraphicRectangular"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily.graphicRectangular",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily/graphicrectangular"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate": {
      "abstract": [
        {
          "text": "An abstract class that defines the base behavior for all templates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplate"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplate"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplate",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody": {
      "abstract": [
        {
          "text": "A template for displaying a large rectangle containing text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularStandardBody"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularStandardBody"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicRectangularStandardBody",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularstandardbody"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBodyView": {
      "abstract": [
        {
          "text": "A template for displaying a SwiftUI label and up to three rows of text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularStandardBodyView"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBodyView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularStandardBodyView"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicRectangularStandardBodyView",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularstandardbodyview"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge": {
      "abstract": [
        {
          "text": "A template for displaying a large rectangle containing text and a gauge.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularTextGauge"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularTextGauge"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicRectangularTextGauge",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/body1TextProvider": {
      "abstract": [
        {
          "text": "The main body text to display in the complication.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "body1TextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/body1TextProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "body1TextProvider"
        }
      ],
      "role": "symbol",
      "title": "body1TextProvider",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge/body1textprovider"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/gaugeProvider": {
      "abstract": [
        {
          "text": "The gauge to display in the complication.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gaugeProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKGaugeProvider",
          "text": "CLKGaugeProvider"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/gaugeProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gaugeProvider"
        }
      ],
      "role": "symbol",
      "title": "gaugeProvider",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge/gaugeprovider"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/headerImageProvider": {
      "abstract": [
        {
          "text": "The header image to display.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headerImageProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKFullColorImageProvider",
          "text": "CLKFullColorImageProvider"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/headerImageProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "headerImageProvider"
        }
      ],
      "role": "symbol",
      "title": "headerImageProvider",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge/headerimageprovider"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/headerTextProvider": {
      "abstract": [
        {
          "text": "The header text to display in the complication.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headerTextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/headerTextProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "headerTextProvider"
        }
      ],
      "role": "symbol",
      "title": "headerTextProvider",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge/headertextprovider"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/init(headerImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:)": {
      "abstract": [
        {
          "text": "Creates a new template that has a header row with an image and text, body text, and a gauge.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "headerImageProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKFullColorImageProvider",
          "text": "CLKFullColorImageProvider"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "headerTextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "body1TextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "gaugeProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKGaugeProvider",
          "text": "CLKGaugeProvider"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/init(headerImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithHeaderImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:"
        }
      ],
      "role": "symbol",
      "title": "init(headerImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge/init(headerimageprovider:headertextprovider:body1textprovider:gaugeprovider:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/init(headerTextProvider:body1TextProvider:gaugeProvider:)": {
      "abstract": [
        {
          "text": "Creates a new template that has header text, body text, and a gauge.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "headerTextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "body1TextProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKTextProvider",
          "text": "CLKTextProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "gaugeProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLKGaugeProvider",
          "text": "CLKGaugeProvider"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/init(headerTextProvider:body1TextProvider:gaugeProvider:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithHeaderTextProvider:body1TextProvider:gaugeProvider:"
        }
      ],
      "role": "symbol",
      "title": "init(headerTextProvider:body1TextProvider:gaugeProvider:)",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge/init(headertextprovider:body1textprovider:gaugeprovider:)"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:": {
      "abstract": [
        {
          "text": "Returns a new template that has a header row with an image and text, body text, and a gauge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:"
        }
      ],
      "role": "symbol",
      "title": "templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge/templatewithheaderimageprovider:headertextprovider:body1textprovider:gaugeprovider:"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/templateWithHeaderTextProvider:body1TextProvider:gaugeProvider:": {
      "abstract": [
        {
          "text": "Returns a new template that has header text, body text, and a gauge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "templateWithHeaderTextProvider:body1TextProvider:gaugeProvider:"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/templateWithHeaderTextProvider:body1TextProvider:gaugeProvider:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateWithHeaderTextProvider:body1TextProvider:gaugeProvider:"
        }
      ],
      "role": "symbol",
      "title": "templateWithHeaderTextProvider:body1TextProvider:gaugeProvider:",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge/templatewithheadertextprovider:body1textprovider:gaugeprovider:"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGaugeView": {
      "abstract": [
        {
          "text": "A template for displaying a header row with a SwiftUI view and text, a second row of text, and a gauge.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularTextGaugeView"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGaugeView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularTextGaugeView"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicRectangularTextGaugeView",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgaugeview"
    },
    "doc://com.apple.documentation/documentation/WidgetKit": {
      "abstract": [
        {
          "text": "Extend the reach of your app by creating widgets, watch complications, Live Activities, and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WidgetKit",
      "type": "topic",
      "url": "/documentation/WidgetKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "media-3030706": {
      "alt": "Diagram showing the layout of a header image, header text, body text, and a gauge.",
      "identifier": "media-3030706",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4095e05f1e6e9e5453a8180a33325f81/media-3030706@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-and-gauges",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBodyView",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGaugeView"
      ],
      "title": "Text and gauges"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-the-Template",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/init(headerTextProvider:body1TextProvider:gaugeProvider:)",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/init(headerImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:)"
      ],
      "title": "Creating the Template"
    },
    {
      "anchor": "Setting-the-Complication-Data",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/headerTextProvider",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/headerImageProvider",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/body1TextProvider",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/gaugeProvider"
      ],
      "title": "Setting the Complication Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLKComplicationTemplateGraphicRectangularTextGauge"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularTextGauge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularTextGauge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.clockkit/documentation/ClockKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-the-Template",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/init(headerTextProvider:body1TextProvider:gaugeProvider:)",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/init(headerImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:)",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/templateWithHeaderTextProvider:body1TextProvider:gaugeProvider:",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/templateWithHeaderImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:"
              ],
              "title": "Creating the Template"
            },
            {
              "anchor": "Setting-the-Complication-Data",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/headerTextProvider",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/headerImageProvider",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/body1TextProvider",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge/gaugeProvider"
              ],
              "title": "Setting the Complication Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text-and-gauges",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody"
              ],
              "title": "Text and gauges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CLKComplicationTemplateGraphicRectangularTextGauge"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CLKComplicationTemplate",
                    "text": "CLKComplicationTemplate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to create complications for watchOS 10 or later. For more information, see Migrating to WidgetKit.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge~1headerImageProvider/title",
          "value": "headerImageProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge~1headerImageProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "headerImageProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge/title",
          "value": "CLKComplicationTemplateGraphicRectangularTextGauge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularTextGauge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularTextGauge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge~1headerTextProvider/title",
          "value": "headerTextProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge~1headerTextProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "headerTextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge~1init(headerImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:)/title",
          "value": "initWithHeaderImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge~1init(headerImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithHeaderImageProvider:headerTextProvider:body1TextProvider:gaugeProvider:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/title",
          "value": "CLKComplicationTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge~1body1TextProvider/title",
          "value": "body1TextProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge~1body1TextProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "body1TextProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicRectangular/title",
          "value": "CLKComplicationFamilyGraphicRectangular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily~1graphicRectangular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamilyGraphicRectangular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge~1gaugeProvider/title",
          "value": "gaugeProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge~1gaugeProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gaugeProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge~1init(headerTextProvider:body1TextProvider:gaugeProvider:)/title",
          "value": "initWithHeaderTextProvider:body1TextProvider:gaugeProvider:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge~1init(headerTextProvider:body1TextProvider:gaugeProvider:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithHeaderTextProvider:body1TextProvider:gaugeProvider:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody/title",
          "value": "CLKComplicationTemplateGraphicRectangularStandardBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularStandardBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularStandardBody"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
