{
  "abstract": [
    {
      "text": "Display graphically rich data in the watch face’s corner.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols",
        "doc://com.apple.clockkit/documentation/ClockKit/graphic"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/corner-complication-templates"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Corner complication templates"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The graphic corner templates display gauges, images, and text in the watch face’s corner.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3744078",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The tinted versions of the templates are shown below:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3744091",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicBezelCircularText": {
      "abstract": [
        {
          "text": "A template for displaying a circular complication with text along the bezel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicBezelCircularText"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicBezelCircularText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicBezelCircularText"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicBezelCircularText",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicbezelcirculartext"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerCircularImage": {
      "abstract": [
        {
          "text": "A template for displaying an image in the clock face’s corner.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerCircularImage"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerCircularImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerCircularImage"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicCornerCircularImage",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphiccornercircularimage"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerCircularView": {
      "abstract": [
        {
          "text": "A template for displaying a SwiftUI view in the clock face’s corner.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerCircularView"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerCircularView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerCircularView"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicCornerCircularView",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphiccornercircularview"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerGaugeImage": {
      "abstract": [
        {
          "text": "A template for displaying an image and a gauge in the clock face’s corner.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerGaugeImage"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerGaugeImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerGaugeImage"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicCornerGaugeImage",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphiccornergaugeimage"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerGaugeText": {
      "abstract": [
        {
          "text": "A template for displaying text and a gauge in the clock face’s corner.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerGaugeText"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerGaugeText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerGaugeText"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicCornerGaugeText",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphiccornergaugetext"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerGaugeView": {
      "abstract": [
        {
          "text": "A template for displaying a SwiftUI view and a gauge in the clock face’s corner.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerGaugeView"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerGaugeView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerGaugeView"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicCornerGaugeView",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphiccornergaugeview"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerStackText": {
      "abstract": [
        {
          "text": "A template for displaying stacked text in the clock face’s corner.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerStackText"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerStackText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerStackText"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicCornerStackText",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphiccornerstacktext"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerTextImage": {
      "abstract": [
        {
          "text": "A template for displaying an image and text in the clock face’s corner.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerTextImage"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerTextImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerTextImage"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicCornerTextImage",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphiccornertextimage"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerTextView": {
      "abstract": [
        {
          "text": "A template for displaying a SwiftUI view and text in the clock face’s corner.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerTextView"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicCornerTextView"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicCornerTextView",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphiccornertextview"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/circular-complication-templates": {
      "abstract": [
        {
          "text": "Display graphical data in a compact circle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/circular-complication-templates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Circular complication templates",
      "type": "topic",
      "url": "/documentation/clockkit/circular-complication-templates"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols": {
      "abstract": [],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated articles and symbols",
      "type": "topic",
      "url": "/documentation/clockkit/deprecated-articles-and-symbols"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/extra-large-circular-templates": {
      "abstract": [
        {
          "text": "Display large, easy-to-read content on the X-Large watch face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/extra-large-circular-templates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extra large circular templates",
      "type": "topic",
      "url": "/documentation/clockkit/extra-large-circular-templates"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/graphic": {
      "abstract": [
        {
          "text": "Display visually rich content on watch faces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/graphic",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Graphic",
      "type": "topic",
      "url": "/documentation/clockkit/graphic"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/rectangular-complication-templates": {
      "abstract": [
        {
          "text": "Displays large, rectangular complications for charts, images, or multiple lines of text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/rectangular-complication-templates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Rectangular complication templates.",
      "type": "topic",
      "url": "/documentation/clockkit/rectangular-complication-templates"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3744078": {
      "alt": "An illustration of templates in all four corners, including curved text and gauges.",
      "identifier": "media-3744078",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a3fc0c9a1809a1b45c41fb829bf2d2b8/media-3744078@2x.png"
        }
      ]
    },
    "media-3744091": {
      "alt": "An illustration that shows tinted versions of templates in all four corners, including curved text and gauges.",
      "identifier": "media-3744091",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/dbcfaf72752adf846c0346f47536bd88/media-3744091@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Graphic-template-families",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/circular-complication-templates",
        "doc://com.apple.clockkit/documentation/ClockKit/rectangular-complication-templates",
        "doc://com.apple.clockkit/documentation/ClockKit/extra-large-circular-templates",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicBezelCircularText"
      ],
      "title": "Graphic template families"
    }
  ],
  "topicSections": [
    {
      "anchor": "Text-and-image",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerCircularImage",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerCircularView",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerStackText",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerTextImage",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerTextView"
      ],
      "title": "Text and image"
    },
    {
      "anchor": "Gauges",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerGaugeImage",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerGaugeView",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerGaugeText"
      ],
      "title": "Gauges"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Text-and-image",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerCircularImage",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerStackText",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerTextImage"
              ],
              "title": "Text and image"
            },
            {
              "anchor": "Gauges",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerGaugeImage",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicCornerGaugeText"
              ],
              "title": "Gauges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Graphic-template-families",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/circular-complication-templates",
                "doc://com.apple.clockkit/documentation/ClockKit/rectangular-complication-templates",
                "doc://com.apple.clockkit/documentation/ClockKit/extra-large-circular-templates",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicBezelCircularText"
              ],
              "title": "Graphic template families"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicCornerCircularImage/title",
          "value": "CLKComplicationTemplateGraphicCornerCircularImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicCornerCircularImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicCornerCircularImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicCornerCircularImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicCornerCircularImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicCornerStackText/title",
          "value": "CLKComplicationTemplateGraphicCornerStackText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicCornerStackText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicCornerStackText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicCornerStackText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicCornerStackText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicBezelCircularText/title",
          "value": "CLKComplicationTemplateGraphicBezelCircularText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicBezelCircularText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicBezelCircularText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicBezelCircularText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicBezelCircularText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicCornerGaugeText/title",
          "value": "CLKComplicationTemplateGraphicCornerGaugeText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicCornerGaugeText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicCornerGaugeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicCornerGaugeText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicCornerGaugeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicCornerGaugeImage/title",
          "value": "CLKComplicationTemplateGraphicCornerGaugeImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicCornerGaugeImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicCornerGaugeImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicCornerGaugeImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicCornerGaugeImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicCornerTextImage/title",
          "value": "CLKComplicationTemplateGraphicCornerTextImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicCornerTextImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicCornerTextImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicCornerTextImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicCornerTextImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/corner-complication-templates"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/corner-complication-templates"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
