{
  "abstract": [
    {
      "text": "Display content in the smaller spaces of the Modular watch face.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/modular-small"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Modular small"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Modular small templates display two stacked rows of content, an icon and content, a circular graph, or a single larger item on the Modular watch face.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2878968",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily": {
      "abstract": [
        {
          "text": "Constants indicating the template groups.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationFamily"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationFamily"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationFamily",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationfamily"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate": {
      "abstract": [
        {
          "text": "An abstract class that defines the base behavior for all templates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplate"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplate"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplate",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplate"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallColumnsText": {
      "abstract": [
        {
          "text": "A template for displaying two rows and two columns of text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallColumnsText"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallColumnsText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallColumnsText"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateModularSmallColumnsText",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatemodularsmallcolumnstext"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingImage": {
      "abstract": [
        {
          "text": "A template for displaying an image encircled by a configurable progress ring.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallRingImage"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallRingImage"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateModularSmallRingImage",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatemodularsmallringimage"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingText": {
      "abstract": [
        {
          "text": "A template for displaying text encircled by a configurable progress ring.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallRingText"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallRingText"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateModularSmallRingText",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatemodularsmallringtext"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallSimpleImage": {
      "abstract": [
        {
          "text": "A template for displaying an image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallSimpleImage"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallSimpleImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallSimpleImage"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateModularSmallSimpleImage",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatemodularsmallsimpleimage"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallSimpleText": {
      "abstract": [
        {
          "text": "A template for displaying a small amount of text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallSimpleText"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallSimpleText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallSimpleText"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateModularSmallSimpleText",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatemodularsmallsimpletext"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallStackImage": {
      "abstract": [
        {
          "text": "A template for displaying a single image with a short line of text below it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallStackImage"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallStackImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallStackImage"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateModularSmallStackImage",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatemodularsmallstackimage"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallStackText": {
      "abstract": [
        {
          "text": "A template for displaying two strings stacked one on top of the other.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallStackText"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallStackText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateModularSmallStackText"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateModularSmallStackText",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplatemodularsmallstacktext"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode": {
      "abstract": [
        {
          "text": "The complication’s appearance, as specified by the watch face.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ComplicationRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ComplicationRenderingMode"
        }
      ],
      "role": "symbol",
      "title": "ComplicationRenderingMode",
      "type": "topic",
      "url": "/documentation/clockkit/complicationrenderingmode"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/circular-small": {
      "abstract": [
        {
          "text": "Display small, circular content in the corners of the Color watch face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/circular-small",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Circular small",
      "type": "topic",
      "url": "/documentation/clockkit/circular-small"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/data-providers": {
      "abstract": [
        {
          "text": "Feed data to a complication template.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/data-providers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data providers",
      "type": "topic",
      "url": "/documentation/clockkit/data-providers"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols": {
      "abstract": [],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated articles and symbols",
      "type": "topic",
      "url": "/documentation/clockkit/deprecated-articles-and-symbols"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/extra-large": {
      "abstract": [
        {
          "text": "Display content on the X-Large watch face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/extra-large",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extra large",
      "type": "topic",
      "url": "/documentation/clockkit/extra-large"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/graphic": {
      "abstract": [
        {
          "text": "Display visually rich content on watch faces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/graphic",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Graphic",
      "type": "topic",
      "url": "/documentation/clockkit/graphic"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/modular-large": {
      "abstract": [
        {
          "text": "Display multiple rows of content in the large, central complication on the Modular watch face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/modular-large",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Modular large",
      "type": "topic",
      "url": "/documentation/clockkit/modular-large"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/swiftui-templates": {
      "abstract": [
        {
          "text": "Design complication templates using SwiftUI views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/swiftui-templates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SwiftUI templates",
      "type": "topic",
      "url": "/documentation/clockkit/swiftui-templates"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/utilitarian": {
      "abstract": [
        {
          "text": "Use the utilitarian templates to display content on a variety of watch faces, including the Utility, Chronograph, Simple, and character watch faces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/utilitarian",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Utilitarian",
      "type": "topic",
      "url": "/documentation/clockkit/utilitarian"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies": {
      "abstract": [
        {
          "text": "The complication families for which the app can provide data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLKComplicationSupportedFamilies",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-2878968": {
      "alt": "Examples of the modular small templates. From left to right they are columns text, stacked text, ring image, stack image, simple text, simple image, and ring text.",
      "identifier": "media-2878968",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed28a6fa96a62a7e0669047b7217da70/media-2878968@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed28a6fa96a62a7e0669047b7217da70/media-2878968~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Templates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/swiftui-templates",
        "doc://com.apple.clockkit/documentation/ClockKit/ComplicationRenderingMode",
        "doc://com.apple.clockkit/documentation/ClockKit/data-providers",
        "doc://com.apple.clockkit/documentation/ClockKit/circular-small",
        "doc://com.apple.clockkit/documentation/ClockKit/extra-large",
        "doc://com.apple.clockkit/documentation/ClockKit/modular-large",
        "doc://com.apple.clockkit/documentation/ClockKit/utilitarian",
        "doc://com.apple.clockkit/documentation/ClockKit/graphic",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies"
      ],
      "title": "Templates"
    }
  ],
  "topicSections": [
    {
      "anchor": "Image-templates",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingImage",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallSimpleImage",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallStackImage"
      ],
      "title": "Image templates"
    },
    {
      "anchor": "Text-templates",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallColumnsText",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingText",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallSimpleText",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallStackText"
      ],
      "title": "Text templates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Image-templates",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingImage",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallSimpleImage",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallStackImage"
              ],
              "title": "Image templates"
            },
            {
              "anchor": "Text-templates",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallColumnsText",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallRingText",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallSimpleText",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateModularSmallStackText"
              ],
              "title": "Text templates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Templates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/swiftui-templates",
                "doc://com.apple.clockkit/documentation/ClockKit/data-providers",
                "doc://com.apple.clockkit/documentation/ClockKit/circular-small",
                "doc://com.apple.clockkit/documentation/ClockKit/extra-large",
                "doc://com.apple.clockkit/documentation/ClockKit/modular-large",
                "doc://com.apple.clockkit/documentation/ClockKit/utilitarian",
                "doc://com.apple.clockkit/documentation/ClockKit/graphic",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplate",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationFamily",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CLKComplicationSupportedFamilies"
              ],
              "title": "Templates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily/title",
          "value": "CLKComplicationFamily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationFamily/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/title",
          "value": "CLKComplicationTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallRingText/title",
          "value": "CLKComplicationTemplateModularSmallRingText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallRingText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallRingText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallRingText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallRingText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallStackText/title",
          "value": "CLKComplicationTemplateModularSmallStackText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallStackText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallStackText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallStackText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallStackText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallColumnsText/title",
          "value": "CLKComplicationTemplateModularSmallColumnsText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallColumnsText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallColumnsText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallColumnsText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallColumnsText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallStackImage/title",
          "value": "CLKComplicationTemplateModularSmallStackImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallStackImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallStackImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallStackImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallStackImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallSimpleImage/title",
          "value": "CLKComplicationTemplateModularSmallSimpleImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallSimpleImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallSimpleImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallSimpleImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallSimpleImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallSimpleText/title",
          "value": "CLKComplicationTemplateModularSmallSimpleText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallSimpleText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallSimpleText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallSimpleText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallSimpleText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallRingImage/title",
          "value": "CLKComplicationTemplateModularSmallRingImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallRingImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallRingImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateModularSmallRingImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateModularSmallRingImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/modular-small"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/modular-small"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
