{
  "abstract": [
    {
      "text": "Displays large, rectangular complications for charts, images, or multiple lines of text.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols",
        "doc://com.apple.clockkit/documentation/ClockKit/graphic"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/rectangular-complication-templates"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Rectangular complication templates."
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The graphic rectangular templates provide a larger space for displaying images or multiple lines of text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3744083",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The tinted versions of the templates are shown below:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3744088",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicBezelCircularText": {
      "abstract": [
        {
          "text": "A template for displaying a circular complication with text along the bezel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicBezelCircularText"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicBezelCircularText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicBezelCircularText"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicBezelCircularText",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicbezelcirculartext"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularFullImage": {
      "abstract": [
        {
          "text": "A template for displaying a full-color image that fills the complication.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularFullImage"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularFullImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularFullImage"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicRectangularFullImage",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularfullimage"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularFullView": {
      "abstract": [
        {
          "text": "A template for displaying a SwiftUI view that fills the entire template.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularFullView"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularFullView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularFullView"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicRectangularFullView",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularfullview"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularLargeImage": {
      "abstract": [
        {
          "text": "A template for displaying a large rectangle containing header text and an image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularLargeImage"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularLargeImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularLargeImage"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicRectangularLargeImage",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularlargeimage"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularLargeView": {
      "abstract": [
        {
          "text": "A template for displaying a large rectangle containing header text and a SwiftUI view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularLargeView"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularLargeView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularLargeView"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicRectangularLargeView",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularlargeview"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody": {
      "abstract": [
        {
          "text": "A template for displaying a large rectangle containing text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularStandardBody"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularStandardBody"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicRectangularStandardBody",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularstandardbody"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBodyView": {
      "abstract": [
        {
          "text": "A template for displaying a SwiftUI label and up to three rows of text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularStandardBodyView"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBodyView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularStandardBodyView"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicRectangularStandardBodyView",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangularstandardbodyview"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge": {
      "abstract": [
        {
          "text": "A template for displaying a large rectangle containing text and a gauge.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularTextGauge"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularTextGauge"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicRectangularTextGauge",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgauge"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGaugeView": {
      "abstract": [
        {
          "text": "A template for displaying a header row with a SwiftUI view and text, a second row of text, and a gauge.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularTextGaugeView"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGaugeView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKComplicationTemplateGraphicRectangularTextGaugeView"
        }
      ],
      "role": "symbol",
      "title": "CLKComplicationTemplateGraphicRectangularTextGaugeView",
      "type": "topic",
      "url": "/documentation/clockkit/clkcomplicationtemplategraphicrectangulartextgaugeview"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/circular-complication-templates": {
      "abstract": [
        {
          "text": "Display graphical data in a compact circle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/circular-complication-templates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Circular complication templates",
      "type": "topic",
      "url": "/documentation/clockkit/circular-complication-templates"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/corner-complication-templates": {
      "abstract": [
        {
          "text": "Display graphically rich data in the watch face’s corner.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/corner-complication-templates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Corner complication templates",
      "type": "topic",
      "url": "/documentation/clockkit/corner-complication-templates"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols": {
      "abstract": [],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/deprecated-articles-and-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated articles and symbols",
      "type": "topic",
      "url": "/documentation/clockkit/deprecated-articles-and-symbols"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/extra-large-circular-templates": {
      "abstract": [
        {
          "text": "Display large, easy-to-read content on the X-Large watch face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/extra-large-circular-templates",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extra large circular templates",
      "type": "topic",
      "url": "/documentation/clockkit/extra-large-circular-templates"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/graphic": {
      "abstract": [
        {
          "text": "Display visually rich content on watch faces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/graphic",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Graphic",
      "type": "topic",
      "url": "/documentation/clockkit/graphic"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3744083": {
      "alt": "An illustration of three graphic rectangular templates, showing text, an image of a graph, and a gauge.",
      "identifier": "media-3744083",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1f31ba28aacc44d8061c58eaf695c430/media-3744083@2x.png"
        }
      ]
    },
    "media-3744088": {
      "alt": "An illustration that shows tinted versions of three graphic rectangular templates, with text, an image of a graph, and a gauge. ",
      "identifier": "media-3744088",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2890ce63e0e0fb5053198c41efc9d8f4/media-3744088@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Graphic-template-families",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/circular-complication-templates",
        "doc://com.apple.clockkit/documentation/ClockKit/corner-complication-templates",
        "doc://com.apple.clockkit/documentation/ClockKit/extra-large-circular-templates",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicBezelCircularText"
      ],
      "title": "Graphic template families"
    }
  ],
  "topicSections": [
    {
      "anchor": "Text-and-gauges",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBodyView",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGaugeView"
      ],
      "title": "Text and gauges"
    },
    {
      "anchor": "Large-Images-and-Views",
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularLargeImage",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularLargeView",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularFullImage",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularFullView"
      ],
      "title": "Large Images and Views"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Text-and-gauges",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularStandardBody",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularTextGauge"
              ],
              "title": "Text and gauges"
            },
            {
              "anchor": "Large-Images-and-Views",
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularLargeImage",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicRectangularFullImage"
              ],
              "title": "Large Images and Views"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Graphic-template-families",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/circular-complication-templates",
                "doc://com.apple.clockkit/documentation/ClockKit/corner-complication-templates",
                "doc://com.apple.clockkit/documentation/ClockKit/extra-large-circular-templates",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKComplicationTemplateGraphicBezelCircularText"
              ],
              "title": "Graphic template families"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicBezelCircularText/title",
          "value": "CLKComplicationTemplateGraphicBezelCircularText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicBezelCircularText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicBezelCircularText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicBezelCircularText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicBezelCircularText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody/title",
          "value": "CLKComplicationTemplateGraphicRectangularStandardBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularStandardBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularStandardBody/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularStandardBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularLargeImage/title",
          "value": "CLKComplicationTemplateGraphicRectangularLargeImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularLargeImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularLargeImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularLargeImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularLargeImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge/title",
          "value": "CLKComplicationTemplateGraphicRectangularTextGauge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularTextGauge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularTextGauge/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularTextGauge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularFullImage/title",
          "value": "CLKComplicationTemplateGraphicRectangularFullImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularFullImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularFullImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKComplicationTemplateGraphicRectangularFullImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKComplicationTemplateGraphicRectangularFullImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/rectangular-complication-templates"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/rectangular-complication-templates"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
