{
  "abstract": [
    {
      "text": "The file operation failed because it doesn’t have permission to read the file.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfurlErrorNoPermissionsToReadFile"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CFNetworkErrors@kCFURLErrorNoPermissionsToReadFile",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "cfurlErrorNoPermissionsToReadFile"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCFURLErrorNoPermissionsToReadFile"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CFNetworkErrors.cfurlErrorNoPermissionsToReadFile"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cfurlErrorNoPermissionsToReadFile"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors": {
      "abstract": [
        {
          "text": "This enumeration contains error codes returned under the error domain ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFErrorDomainCFNetwork",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFNetworkErrors"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFNetworkErrors"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfErrorHTTPAuthenticationTypeUnsupported": {
      "abstract": [
        {
          "text": "The client and server couldn’t agree on a supported authentication type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfErrorHTTPAuthenticationTypeUnsupported"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfErrorHTTPAuthenticationTypeUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFErrorHTTPAuthenticationTypeUnsupported"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfErrorHTTPAuthenticationTypeUnsupported",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cferrorhttpauthenticationtypeunsupported"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfHostErrorHostNotFound": {
      "abstract": [
        {
          "text": "The specified host wasn’t found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfHostErrorHostNotFound"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfHostErrorHostNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFHostErrorHostNotFound"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfHostErrorHostNotFound",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cfhosterrorhostnotfound"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfHostErrorUnknown": {
      "abstract": [
        {
          "text": "An unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfHostErrorUnknown"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfHostErrorUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFHostErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfHostErrorUnknown",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cfhosterrorunknown"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfftpErrorUnexpectedStatusCode": {
      "abstract": [
        {
          "text": "The server returned an unexpected status code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfftpErrorUnexpectedStatusCode"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfftpErrorUnexpectedStatusCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFFTPErrorUnexpectedStatusCode"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfftpErrorUnexpectedStatusCode",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cfftperrorunexpectedstatuscode"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorIdConflict": {
      "abstract": [
        {
          "text": "The server rejected the request because the client program and the ",
          "type": "text"
        },
        {
          "code": "identd",
          "type": "codeVoice"
        },
        {
          "text": " daemon reported different user IDs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfsocks4ErrorIdConflict"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorIdConflict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFSOCKS4ErrorIdConflict"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfsocks4ErrorIdConflict",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cfsocks4erroridconflict"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorIdentdFailed": {
      "abstract": [
        {
          "text": "The server couldn’t connect to the ",
          "type": "text"
        },
        {
          "code": "identd",
          "type": "codeVoice"
        },
        {
          "text": " daemon on the client and rejected the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfsocks4ErrorIdentdFailed"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorIdentdFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFSOCKS4ErrorIdentdFailed"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfsocks4ErrorIdentdFailed",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cfsocks4erroridentdfailed"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorRequestFailed": {
      "abstract": [
        {
          "text": "The server rejected the request, or the request failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfsocks4ErrorRequestFailed"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorRequestFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFSOCKS4ErrorRequestFailed"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfsocks4ErrorRequestFailed",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cfsocks4errorrequestfailed"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorUnknownStatusCode": {
      "abstract": [
        {
          "text": "The server returned an unknown status code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfsocks4ErrorUnknownStatusCode"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorUnknownStatusCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFSOCKS4ErrorUnknownStatusCode"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfsocks4ErrorUnknownStatusCode",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cfsocks4errorunknownstatuscode"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorBadCredentials": {
      "abstract": [
        {
          "text": "The SOCKS server refused the client connection because of bad login credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfsocks5ErrorBadCredentials"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorBadCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFSOCKS5ErrorBadCredentials"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfsocks5ErrorBadCredentials",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cfsocks5errorbadcredentials"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorBadResponseAddr": {
      "abstract": [
        {
          "text": "The address type returned isn’t supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfsocks5ErrorBadResponseAddr"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorBadResponseAddr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFSOCKS5ErrorBadResponseAddr"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfsocks5ErrorBadResponseAddr",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cfsocks5errorbadresponseaddr"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorBadState": {
      "abstract": [
        {
          "text": "The stream isn’t in a state that allows the requested operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfsocks5ErrorBadState"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorBadState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFSOCKS5ErrorBadState"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfsocks5ErrorBadState",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cfsocks5errorbadstate"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorNoAcceptableMethod": {
      "abstract": [
        {
          "text": "The client and server couldn’t find a mutually agreeable authentication method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfsocks5ErrorNoAcceptableMethod"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorNoAcceptableMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFSOCKS5ErrorNoAcceptableMethod"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfsocks5ErrorNoAcceptableMethod",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cfsocks5errornoacceptablemethod"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorUnsupportedNegotiationMethod": {
      "abstract": [
        {
          "text": "The requested method isn’t supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfsocks5ErrorUnsupportedNegotiationMethod"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorUnsupportedNegotiationMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFSOCKS5ErrorUnsupportedNegotiationMethod"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfsocks5ErrorUnsupportedNegotiationMethod",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cfsocks5errorunsupportednegotiationmethod"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocksErrorUnknownClientVersion": {
      "abstract": [
        {
          "text": "The SOCKS server rejected access because it doesn’t support connections with the requested SOCKS version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfsocksErrorUnknownClientVersion"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocksErrorUnknownClientVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFSOCKSErrorUnknownClientVersion"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfsocksErrorUnknownClientVersion",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cfsockserrorunknownclientversion"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocksErrorUnsupportedServerVersion": {
      "abstract": [
        {
          "text": "The SOCKS server doesn’t support the requested version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfsocksErrorUnsupportedServerVersion"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocksErrorUnsupportedServerVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFSOCKSErrorUnsupportedServerVersion"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfsocksErrorUnsupportedServerVersion",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cfsockserrorunsupportedserverversion"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfurlErrorNoPermissionsToReadFile": {
      "abstract": [
        {
          "text": "The file operation failed because it doesn’t have permission to read the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfurlErrorNoPermissionsToReadFile"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfurlErrorNoPermissionsToReadFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFURLErrorNoPermissionsToReadFile"
        }
      ],
      "role": "symbol",
      "title": "CFNetworkErrors.cfurlErrorNoPermissionsToReadFile",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfnetworkerrors/cfurlerrornopermissionstoreadfile"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFErrorDomainCFNetwork": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFErrorDomainCFNetwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/kCFErrorDomainCFNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFErrorDomainCFNetwork"
        }
      ],
      "role": "symbol",
      "title": "kCFErrorDomainCFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork/kcferrordomaincfnetwork"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfHostErrorHostNotFound",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfHostErrorUnknown",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocksErrorUnknownClientVersion",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocksErrorUnsupportedServerVersion",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorRequestFailed",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorIdentdFailed",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorIdConflict",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorUnknownStatusCode",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorBadState",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorBadResponseAddr",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorBadCredentials",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorUnsupportedNegotiationMethod",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorNoAcceptableMethod",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfftpErrorUnexpectedStatusCode",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfErrorHTTPAuthenticationTypeUnsupported"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCFURLErrorNoPermissionsToReadFile"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFURLErrorNoPermissionsToReadFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfHostErrorHostNotFound",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfHostErrorUnknown",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocksErrorUnknownClientVersion",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocksErrorUnsupportedServerVersion",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorRequestFailed",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorIdentdFailed",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorIdConflict",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks4ErrorUnknownStatusCode",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorBadState",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorBadResponseAddr",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorBadCredentials",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorUnsupportedNegotiationMethod",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfsocks5ErrorNoAcceptableMethod",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfftpErrorUnexpectedStatusCode",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFNetworkErrors/cfErrorHTTPAuthenticationTypeUnsupported"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCFURLErrorNoPermissionsToReadFile"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors/title",
          "value": "CFNetworkErrors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFNetworkErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks4ErrorRequestFailed/title",
          "value": "kCFSOCKS4ErrorRequestFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks4ErrorRequestFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFSOCKS4ErrorRequestFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfHostErrorHostNotFound/title",
          "value": "kCFHostErrorHostNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfHostErrorHostNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHostErrorHostNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocksErrorUnknownClientVersion/title",
          "value": "kCFSOCKSErrorUnknownClientVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocksErrorUnknownClientVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFSOCKSErrorUnknownClientVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks4ErrorUnknownStatusCode/title",
          "value": "kCFSOCKS4ErrorUnknownStatusCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks4ErrorUnknownStatusCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFSOCKS4ErrorUnknownStatusCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks4ErrorIdentdFailed/title",
          "value": "kCFSOCKS4ErrorIdentdFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks4ErrorIdentdFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFSOCKS4ErrorIdentdFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfurlErrorNoPermissionsToReadFile/title",
          "value": "kCFURLErrorNoPermissionsToReadFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfurlErrorNoPermissionsToReadFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFURLErrorNoPermissionsToReadFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfftpErrorUnexpectedStatusCode/title",
          "value": "kCFFTPErrorUnexpectedStatusCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfftpErrorUnexpectedStatusCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFFTPErrorUnexpectedStatusCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfHostErrorUnknown/title",
          "value": "kCFHostErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfHostErrorUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFHostErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks5ErrorBadResponseAddr/title",
          "value": "kCFSOCKS5ErrorBadResponseAddr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks5ErrorBadResponseAddr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFSOCKS5ErrorBadResponseAddr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks5ErrorBadState/title",
          "value": "kCFSOCKS5ErrorBadState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks5ErrorBadState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFSOCKS5ErrorBadState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfErrorHTTPAuthenticationTypeUnsupported/title",
          "value": "kCFErrorHTTPAuthenticationTypeUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfErrorHTTPAuthenticationTypeUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFErrorHTTPAuthenticationTypeUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks5ErrorUnsupportedNegotiationMethod/title",
          "value": "kCFSOCKS5ErrorUnsupportedNegotiationMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks5ErrorUnsupportedNegotiationMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFSOCKS5ErrorUnsupportedNegotiationMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks4ErrorIdConflict/title",
          "value": "kCFSOCKS4ErrorIdConflict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks4ErrorIdConflict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFSOCKS4ErrorIdConflict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks5ErrorNoAcceptableMethod/title",
          "value": "kCFSOCKS5ErrorNoAcceptableMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks5ErrorNoAcceptableMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFSOCKS5ErrorNoAcceptableMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFErrorDomainCFNetwork/title",
          "value": "kCFErrorDomainCFNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1kCFErrorDomainCFNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFErrorDomainCFNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks5ErrorBadCredentials/title",
          "value": "kCFSOCKS5ErrorBadCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocks5ErrorBadCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFSOCKS5ErrorBadCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocksErrorUnsupportedServerVersion/title",
          "value": "kCFSOCKSErrorUnsupportedServerVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFNetworkErrors~1cfsocksErrorUnsupportedServerVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFSOCKSErrorUnsupportedServerVersion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfnetworkerrors/cfurlerrornopermissionstoreadfile"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfnetworkerrors/cfurlerrornopermissionstoreadfile"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
