{"metadata":{"symbolKind":"property","platforms":[{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.0"},{"message":"MediaLibrary.framework will be removed in a future OS version. Use Photos.framework or iTunesLibrary.framework instead.","unavailable":false,"name":"macOS","beta":false,"deprecatedAt":"10.15","deprecated":false,"introducedAt":"10.9"}],"title":"image","roleHeading":"Type Property","modules":[{"name":"Media Library"}],"role":"symbol","externalID":"c:@E@MLMediaSourceType@MLMediaSourceTypeImage","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MLMediaSourceType","kind":"typeIdentifier","text":"MLMediaSourceType"}],"navigatorTitle":[{"kind":"identifier","text":"MLMediaSourceTypeImage"}]},"variants":[{"paths":["/documentation/medialibrary/mlmediasourcetype/image"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/medialibrary/mlmediasourcetype/image"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/image","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.medialibrary/documentation/MediaLibrary","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Image source type. Includes iPhoto, Aperture, and Photo Booth."}],"seeAlsoSections":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/audio","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/movie"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MLMediaSourceType","kind":"typeIdentifier","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType","text":"MLMediaSourceType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["macOS"],"languages":["swift"]}]}],"references":{"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/image":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MLMediaSourceType","kind":"typeIdentifier","text":"MLMediaSourceType"}],"navigatorTitle":[{"kind":"identifier","text":"MLMediaSourceTypeImage"}],"url":"/documentation/medialibrary/mlmediasourcetype/image","kind":"symbol","type":"topic","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/image","abstract":[{"text":"Image source type. Includes iPhoto, Aperture, and Photo Booth.","type":"text"}],"title":"image","role":"symbol"},"doc://com.apple.medialibrary/documentation/MediaLibrary":{"kind":"symbol","title":"Media Library","abstract":[{"type":"text","text":"Access read-only collections of the user’s multimedia content."}],"type":"topic","deprecated":true,"url":"/documentation/medialibrary","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary","role":"collection"},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/movie":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"movie"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MLMediaSourceType","kind":"typeIdentifier","text":"MLMediaSourceType"}],"navigatorTitle":[{"kind":"identifier","text":"MLMediaSourceTypeMovie"}],"url":"/documentation/medialibrary/mlmediasourcetype/movie","kind":"symbol","type":"topic","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/movie","abstract":[{"text":"Movie source type. Includes iMovie and Final Cut Pro.","type":"text"}],"title":"movie","role":"symbol"},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType":{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/medialibrary/mlmediasourcetype","abstract":[{"text":"Specifies the source type associated with a particular media source. Source type reflects the primary type of media within the source. These constants are used to specify values for ","type":"text"},{"type":"reference","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey","isActive":true},{"text":" in the ","type":"text"},{"type":"reference","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary/init(options:)","isActive":true},{"text":" method of ","type":"text"},{"type":"reference","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary","isActive":true},{"text":".","type":"text"}],"navigatorTitle":[{"text":"MLMediaSourceType","kind":"identifier"}],"title":"MLMediaSourceType","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MLMediaSourceType","kind":"identifier"}]},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey":{"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLoadSourceTypesKey","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/medialibrary/mlmedialoadsourcetypeskey","abstract":[{"text":"Defines which sources to load based on library type. If not present, this will load all sources. The value for this key is a media source type. For a list of valid media source types, see ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"MLMediaLoadSourceTypesKey","kind":"identifier"}],"title":"MLMediaLoadSourceTypesKey","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"MLMediaLoadSourceTypesKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/audio":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MLMediaSourceType","kind":"typeIdentifier","text":"MLMediaSourceType"}],"navigatorTitle":[{"kind":"identifier","text":"MLMediaSourceTypeAudio"}],"url":"/documentation/medialibrary/mlmediasourcetype/audio","kind":"symbol","type":"topic","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/audio","abstract":[{"text":"Audio source type. Includes iTunes, GarageBand, and Logic.","type":"text"}],"title":"audio","role":"symbol"},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary":{"kind":"symbol","title":"MLMediaLibrary","abstract":[{"text":"The ","type":"text"},{"code":"MLMediaLibrary","type":"codeVoice"},{"text":" class provides an interface for accessing a collection of media objects from various sources. It serves as the initial access point of the Media Library framework.","type":"text"}],"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MLMediaLibrary"}],"navigatorTitle":[{"kind":"identifier","text":"MLMediaLibrary"}],"url":"/documentation/medialibrary/mlmedialibrary","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","type":"topic","role":"overview"},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary/init(options:)":{"title":"init(options:)","abstract":[{"text":"Initializes the media library based on the specified load options.","type":"text"}],"kind":"symbol","role":"symbol","url":"/documentation/medialibrary/mlmedialibrary/init(options:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"initWithOptions:","kind":"identifier"}],"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaLibrary/init(options:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"introducedAt":"13.0","deprecated":false,"beta":false,"name":"Mac Catalyst"},{"deprecatedAt":"10.15","unavailable":false,"introducedAt":"10.9","beta":false,"name":"macOS","deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"/metadata/title","op":"replace","value":"MLMediaSourceTypeImage"},{"path":"/metadata/symbolKind","op":"replace","value":"case"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"MLMediaSourceTypeImage"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.medialibrary/documentation/MediaLibrary","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/audio","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaSourceType/movie"],"generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"MLMediaSourceTypeImage"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"MLMediaSourceTypeImage","op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType~1image/title"},{"value":[{"kind":"identifier","text":"MLMediaSourceTypeImage"}],"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType~1image/fragments"},{"value":"MLMediaSourceTypeMovie","op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType~1movie/title"},{"value":[{"text":"MLMediaSourceTypeMovie","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType~1movie/fragments"},{"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/title","value":"MLMediaSourceType"},{"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/fragments","value":[{"kind":"identifier","text":"MLMediaSourceType"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType/navigatorTitle","value":[{"text":"MLMediaSourceType","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadSourceTypesKey/title","value":"MLMediaLoadSourceTypesKey"},{"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLoadSourceTypesKey/fragments","value":[{"kind":"identifier","text":"MLMediaLoadSourceTypesKey"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType~1audio/title","value":"MLMediaSourceTypeAudio"},{"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaSourceType~1audio/fragments","value":[{"text":"MLMediaSourceTypeAudio","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLibrary/title","value":"MLMediaLibrary"},{"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLibrary/fragments","value":[{"kind":"identifier","text":"MLMediaLibrary"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLibrary/navigatorTitle","value":[{"text":"MLMediaLibrary","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLibrary~1init(options:)/title","value":"initWithOptions:"},{"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaLibrary~1init(options:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithOptions:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}