{"metadata":{"roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(cs)VZMacOSInstaller(im)installWithCompletionHandler:","symbolKind":"method","modules":[{"name":"Virtualization"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"install","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"install()","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"12.0","name":"macOS"}],"navigatorTitle":[{"text":"installWithCompletionHandler:","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller/install(completionHandler:)"],"generated":true,"title":"Installing macOS","anchor":"Installing-macOS"}],"variants":[{"paths":["/documentation/virtualization/vzmacosinstaller/install()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/virtualization/vzmacosinstaller/install()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller/install()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"install"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}]}]},{"kind":"mentions","mentions":["doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine"]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This method starts the installation process. The VM must be in a stopped state. During the installation operation, pausing or stopping the VM results in an undefined behavior.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"If you start the installation on the same ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller"},{"text":" object more than once, the framework raises an exception.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this method only on the VM’s queue."}]}]}],"abstract":[{"type":"text","text":"Start installing macOS."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization","doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller"]]},"references":{"doc://com.apple.virtualization/documentation/Virtualization":{"type":"topic","abstract":[{"text":"Create virtual machines and run macOS and Linux-based operating systems.","type":"text"}],"role":"collection","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization","title":"Virtualization","url":"/documentation/virtualization"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","role":"overview","kind":"technologies","abstract":[{"text":"","type":"text"}],"type":"topic","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller/install()":{"identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller/install()","navigatorTitle":[{"kind":"identifier","text":"installWithCompletionHandler:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"install","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"title":"install()","url":"/documentation/virtualization/vzmacosinstaller/install()","type":"topic","kind":"symbol","abstract":[{"text":"Start installing macOS.","type":"text"}],"role":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller":{"url":"/documentation/virtualization/vzmacosinstaller","title":"VZMacOSInstaller","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller","type":"topic","abstract":[{"text":"An object you use to install macOS on the specified virtual machine.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"VZMacOSInstaller"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VZMacOSInstaller"}],"role":"symbol"},"doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine":{"abstract":[{"type":"text","text":"Download a macOS restore image and install it in a new VM."}],"title":"Installing macOS on a Virtual Machine","identifier":"doc://com.apple.virtualization/documentation/Virtualization/installing-macos-on-a-virtual-machine","kind":"article","url":"/documentation/virtualization/installing-macos-on-a-virtual-machine","type":"topic","role":"article"},"doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller/install(completionHandler:)":{"title":"install(completionHandler:)","url":"/documentation/virtualization/vzmacosinstaller/install(completionhandler:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller/install(completionHandler:)","abstract":[{"type":"text","text":"Start installing macOS."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"install"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":", any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSError":{"abstract":[{"type":"text","text":"Information about an error condition including a domain, a domain-specific error code, and application-specific information."}],"title":"NSError","fragments":[{"kind":"text","text":"class "},{"text":"NSError","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","kind":"symbol","url":"/documentation/foundation/nserror","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"deprecated":false,"introducedAt":"12.0","name":"macOS","beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"installWithCompletionHandler:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"installWithCompletionHandler:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.virtualization/documentation/Virtualization","doc://com.apple.virtualization/documentation/Virtualization/VZMacOSInstaller"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"installWithCompletionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A block the framework calls after installation has completed successfully or has failed.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"error"},{"text":" parameter passed to the block is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if installation was successful. The framework invokes the block on the VM’s queue.","type":"text"}]}],"name":"completionHandler"}]},"path":"/primaryContentSections/1","op":"add"},{"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSInstaller~1install()/title","value":"installWithCompletionHandler:"},{"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSInstaller~1install()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"installWithCompletionHandler:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSInstaller/title","value":"VZMacOSInstaller"},{"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSInstaller/fragments","value":[{"kind":"identifier","text":"VZMacOSInstaller"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZMacOSInstaller/navigatorTitle","value":[{"text":"VZMacOSInstaller","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}