{
  "abstract": [
    {
      "text": "The callback used to add a retain for the host on the info pointer for the life of the host, and may be used for temporary references the host needs to take. This callback returns the actual info pointer to store in the host, almost always just the pointer passed as the parameter.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cfnetwork/documentation/CFNetwork",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/retain"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@CFHostClientContext@FI@retain",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "retain"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFAllocatorRetainCallBack",
        "text": "CFAllocatorRetainCallBack"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "CFNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "retain"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "retain"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "retain"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRetainCallBack",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFAllocatorRetainCallBack",
              "text": "CFAllocatorRetainCallBack"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cfnetwork/documentation/CFNetwork": {
      "abstract": [
        {
          "text": "Access network services and handle changes in network configurations. Build on abstractions of network protocols to simplify tasks such as working with BSD sockets, administering HTTP and FTP servers, and managing Bonjour services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "CFNetwork",
      "type": "topic",
      "url": "/documentation/cfnetwork"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext": {
      "abstract": [
        {
          "text": "A structure containing user-defined data and callbacks for CFHost objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CFHostClientContext"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFHostClientContext"
        }
      ],
      "role": "symbol",
      "title": "CFHostClientContext",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostclientcontext"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/copyDescription": {
      "abstract": [
        {
          "text": "The callback used to create a descriptive string representation of the info pointer (or the data pointed to by the info pointer) for debugging purposes. This callback is called by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521252-cfcopydescription",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorCopyDescriptionCallBack",
          "text": "CFAllocatorCopyDescriptionCallBack"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/copyDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "copyDescription"
        }
      ],
      "role": "symbol",
      "title": "copyDescription",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostclientcontext/copydescription"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/info": {
      "abstract": [
        {
          "text": "An arbitrary pointer to allocated memory containing user-defined data that can be associated with the host and that is passed to the callbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "info"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/info",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "info"
        }
      ],
      "role": "symbol",
      "title": "info",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostclientcontext/info"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/release": {
      "abstract": [
        {
          "text": "The callback used to remove a retain previously added for the host on the info pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "release"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorReleaseCallBack",
          "text": "CFAllocatorReleaseCallBack"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/release",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "release"
        }
      ],
      "role": "symbol",
      "title": "release",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostclientcontext/release"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/retain": {
      "abstract": [
        {
          "text": "The callback used to add a retain for the host on the info pointer for the life of the host, and may be used for temporary references the host needs to take. This callback returns the actual info pointer to store in the host, almost always just the pointer passed as the parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "retain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRetainCallBack",
          "text": "CFAllocatorRetainCallBack"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/retain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "retain"
        }
      ],
      "role": "symbol",
      "title": "retain",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostclientcontext/retain"
    },
    "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/version": {
      "abstract": [
        {
          "text": "The version number of the structure type passed as a parameter to the host client function. The only valid version number is ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/cfnetwork/cfhostclientcontext/version"
    },
    "doc://com.apple.documentation/documentation/corefoundation/1521252-cfcopydescription": {
      "abstract": [
        {
          "text": "Returns a textual description of a Core Foundation object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "CFCopyDescription"
        },
        {
          "kind": "text",
          "text": "(CFTypeRef!) -> CFString!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521252-cfcopydescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFCopyDescription(_:)",
      "type": "topic",
      "url": "/documentation/corefoundation/1521252-cfcopydescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRetainCallBack": {
      "abstract": [
        {
          "text": "A prototype for a function callback that retains the given data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFAllocatorRetainCallBack"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRetainCallBack",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocatorRetainCallBack",
      "type": "topic",
      "url": "/documentation/corefoundation/cfallocatorretaincallback"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/copyDescription",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/info",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/release",
        "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/version"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "retain"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "retain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cfnetwork/documentation/CFNetwork",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/copyDescription",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/info",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/release",
                "doc://com.apple.cfnetwork/documentation/CFNetwork/CFHostClientContext/version"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRetainCallBack",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFAllocatorRetainCallBack",
                    "text": "CFAllocatorRetainCallBack"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "retain"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext~1retain/title",
          "value": "retain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext~1retain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "retain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext/title",
          "value": "CFHostClientContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostClientContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFHostClientContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext~1info/title",
          "value": "info"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext~1info/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext~1release/title",
          "value": "release"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext~1release/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "release"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~11521252-cfcopydescription/title",
          "value": "CFCopyDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext~1copyDescription/title",
          "value": "copyDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cfnetwork~1documentation~1CFNetwork~1CFHostClientContext~1copyDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "copyDescription"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cfnetwork/cfhostclientcontext/retain"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cfnetwork/cfhostclientcontext/retain"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
