{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate/addPaymentPassViewController(_:didFinishAdding:error:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PKAddPaymentPassViewControllerDelegate(im)addPaymentPassViewController:didFinishAddingPaymentPass:error:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "addPaymentPassViewController"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PKAddPaymentPassViewController",
        "text": "PKAddPaymentPassViewController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didFinishAdding"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PKPaymentPass",
        "text": "PKPaymentPass"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "error"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?)"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "addPaymentPassViewController:didFinishAddingPaymentPass:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "addPaymentPassViewController(_:didFinishAdding:error:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "addPaymentPassViewController"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKAddPaymentPassViewController",
              "text": "PKAddPaymentPassViewController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didFinishAdding"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "pass"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentPass",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PKPaymentPass",
              "text": "PKPaymentPass"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The controller adding the pass.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "controller"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The completed pass, or ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " if there was an error.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pass"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If the request failed, this parameter contains an error object using the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitErrorDomain",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " error domain. For a list of possible error codes, see the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassError",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " enum.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is called when the request successfully adds the card to Apple Pay or when the request fails.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassError": {
      "abstract": [
        {
          "text": "Error codes for adding payment passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassError"
        }
      ],
      "role": "symbol",
      "title": "PKAddPaymentPassError",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpasserror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequest": {
      "abstract": [
        {
          "text": "Contains the card data needed to add a card to Apple Pay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassRequest"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassRequest"
        }
      ],
      "role": "symbol",
      "title": "PKAddPaymentPassRequest",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassrequest"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewController": {
      "abstract": [
        {
          "text": "Displays an interface that lets users add cards to Apple Pay from within your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassViewController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassViewController"
        }
      ],
      "role": "symbol",
      "title": "PKAddPaymentPassViewController",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassviewcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate": {
      "abstract": [
        {
          "text": "Methods that let the system prompt you for an add payment request, and inform you when a request has succeeded or failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPaymentPassViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "PKAddPaymentPassViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassviewcontrollerdelegate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate/addPaymentPassViewController(_:didFinishAdding:error:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addPaymentPassViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKAddPaymentPassViewController",
          "text": "PKAddPaymentPassViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishAdding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKPaymentPass",
          "text": "PKPaymentPass"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate/addPaymentPassViewController(_:didFinishAdding:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPaymentPassViewController:didFinishAddingPaymentPass:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "addPaymentPassViewController(_:didFinishAdding:error:)",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassviewcontrollerdelegate/addpaymentpassviewcontroller(_:didfinishadding:error:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)": {
      "abstract": [
        {
          "text": "Asks the delegate to create an add payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addPaymentPassViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKAddPaymentPassViewController",
          "text": "PKAddPaymentPassViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "generateRequestWithCertificateChain"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "nonce"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "nonceSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PKAddPaymentPassRequest",
          "text": "PKAddPaymentPassRequest"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpaymentpassviewcontrollerdelegate/addpaymentpassviewcontroller(_:generaterequestwithcertificatechain:nonce:noncesignature:completionhandler:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassKitErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for PassKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassKitErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassKitErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "PKPassKitErrorDomain",
      "type": "topic",
      "url": "/documentation/passkit/pkpasskiterrordomain"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentPass": {
      "abstract": [
        {
          "text": "An object that represents a provisioned payment card for in-app payments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentPass"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentPass"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentPass",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentpass"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Requesting-to-add-payment-cards-to-Apple-Pay",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequest"
      ],
      "title": "Requesting to add payment cards to Apple Pay"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "addPaymentPassViewController:didFinishAddingPaymentPass:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addPaymentPassViewController:didFinishAddingPaymentPass:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Requesting-to-add-payment-cards-to-Apple-Pay",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewControllerDelegate/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassRequest"
              ],
              "title": "Requesting to add payment cards to Apple Pay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "addPaymentPassViewController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PKAddPaymentPassViewController",
                    "text": "PKAddPaymentPassViewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "controller"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didFinishAddingPaymentPass:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentPass",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PKPaymentPass",
                    "text": "PKPaymentPass"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "pass"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The controller adding the pass.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "controller"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The completed pass, or ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if there was an error.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "pass"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "If the request failed, this parameter contains an error object using the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitErrorDomain",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " error domain. For a list of possible error codes, see the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPaymentPassError",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " enum.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitErrorDomain/title",
          "value": "PKPassKitErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassKitErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequest/title",
          "value": "PKAddPaymentPassRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewControllerDelegate~1addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)/title",
          "value": "addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewControllerDelegate~1addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPass/title",
          "value": "PKPaymentPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentPass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassError/title",
          "value": "PKAddPaymentPassError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewControllerDelegate/title",
          "value": "PKAddPaymentPassViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewController/title",
          "value": "PKAddPaymentPassViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPaymentPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewControllerDelegate~1addPaymentPassViewController(_:didFinishAdding:error:)/title",
          "value": "addPaymentPassViewController:didFinishAddingPaymentPass:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPaymentPassViewControllerDelegate~1addPaymentPassViewController(_:didFinishAdding:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addPaymentPassViewController:didFinishAddingPaymentPass:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkaddpaymentpassviewcontrollerdelegate/addpaymentpassviewcontroller(_:didfinishadding:error:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkaddpaymentpassviewcontrollerdelegate/addpaymentpassviewcontroller(_:didfinishadding:error:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
