{
  "abstract": [
    {
      "text": "The top-rear right channel.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopRear"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AudioChannelBitmap@kAudioChannelBit_RightTopRear",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bit_RightTopRear"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AudioChannelBitmap",
        "text": "AudioChannelBitmap"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioChannelBit_RightTopRear"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "bit_RightTopRear"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bit_RightTopRear"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AudioChannelBitmap",
              "text": "AudioChannelBitmap"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap": {
      "abstract": [
        {
          "text": "The supported channel bitmaps to use when defining channel layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelBitmap"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelBitmap",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Right": {
      "abstract": [
        {
          "text": "The right channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_Right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_Right"
        }
      ],
      "role": "symbol",
      "title": "bit_Right",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_right"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightCenter": {
      "abstract": [
        {
          "text": "The right center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_RightCenter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_RightCenter"
        }
      ],
      "role": "symbol",
      "title": "bit_RightCenter",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_rightcenter"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurround": {
      "abstract": [
        {
          "text": "The rIght surround channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_RightSurround"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurround",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_RightSurround"
        }
      ],
      "role": "symbol",
      "title": "bit_RightSurround",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_rightsurround"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurroundDirect": {
      "abstract": [
        {
          "text": "The right surround direct channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_RightSurroundDirect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurroundDirect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_RightSurroundDirect"
        }
      ],
      "role": "symbol",
      "title": "bit_RightSurroundDirect",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_rightsurrounddirect"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopFront": {
      "abstract": [
        {
          "text": "The top-front front channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_RightTopFront"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopFront",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_RightTopFront"
        }
      ],
      "role": "symbol",
      "title": "bit_RightTopFront",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_righttopfront"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopMiddle": {
      "abstract": [
        {
          "text": "The top-middle right channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_RightTopMiddle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopMiddle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_RightTopMiddle"
        }
      ],
      "role": "symbol",
      "title": "bit_RightTopMiddle",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_righttopmiddle"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopRear": {
      "abstract": [
        {
          "text": "The top-rear right channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_RightTopRear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopRear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_RightTopRear"
        }
      ],
      "role": "symbol",
      "title": "bit_RightTopRear",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_righttoprear"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackRight": {
      "abstract": [
        {
          "text": "The top-back right channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_TopBackRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_TopBackRight"
        }
      ],
      "role": "symbol",
      "title": "bit_TopBackRight",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_topbackright"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightRight": {
      "abstract": [
        {
          "text": "The vertical height right channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_VerticalHeightRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_VerticalHeightRight"
        }
      ],
      "role": "symbol",
      "title": "bit_VerticalHeightRight",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_verticalheightright"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Right",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Right",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightCenter",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurround",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurroundDirect",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopFront",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopMiddle",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackRight",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightRight"
      ],
      "title": "Right"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioChannelBit_RightTopRear"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_RightTopRear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Right",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Right",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightCenter",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurround",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightSurroundDirect",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopFront",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_RightTopMiddle",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackRight",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightRight"
              ],
              "title": "Right"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioChannelBit_RightTopRear"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightTopMiddle/title",
          "value": "kAudioChannelBit_RightTopMiddle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightTopMiddle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_RightTopMiddle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_Right/title",
          "value": "kAudioChannelBit_Right"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_Right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_Right"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap/title",
          "value": "AudioChannelBitmap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightCenter/title",
          "value": "kAudioChannelBit_RightCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_RightCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_VerticalHeightRight/title",
          "value": "kAudioChannelBit_VerticalHeightRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_VerticalHeightRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_VerticalHeightRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_TopBackRight/title",
          "value": "kAudioChannelBit_TopBackRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_TopBackRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_TopBackRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightTopFront/title",
          "value": "kAudioChannelBit_RightTopFront"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightTopFront/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_RightTopFront"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightTopRear/title",
          "value": "kAudioChannelBit_RightTopRear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightTopRear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_RightTopRear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightSurround/title",
          "value": "kAudioChannelBit_RightSurround"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightSurround/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_RightSurround"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightSurroundDirect/title",
          "value": "kAudioChannelBit_RightSurroundDirect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_RightSurroundDirect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_RightSurroundDirect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/audiochannelbitmap/bit_righttoprear"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/audiochannelbitmap/bit_righttoprear"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
