{
  "abstract": [
    {
      "text": "The vertical height center channel.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightCenter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AudioChannelBitmap@kAudioChannelBit_VerticalHeightCenter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bit_VerticalHeightCenter"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AudioChannelBitmap",
        "text": "AudioChannelBitmap"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioChannelBit_VerticalHeightCenter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.2",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "bit_VerticalHeightCenter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bit_VerticalHeightCenter"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AudioChannelBitmap",
              "text": "AudioChannelBitmap"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap": {
      "abstract": [
        {
          "text": "The supported channel bitmaps to use when defining channel layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioChannelBitmap"
        }
      ],
      "role": "symbol",
      "title": "AudioChannelBitmap",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Center": {
      "abstract": [
        {
          "text": "The center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_Center"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_Center"
        }
      ],
      "role": "symbol",
      "title": "bit_Center",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_center"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterSurround": {
      "abstract": [
        {
          "text": "The center surround channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_CenterSurround"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterSurround",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_CenterSurround"
        }
      ],
      "role": "symbol",
      "title": "bit_CenterSurround",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_centersurround"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopFront": {
      "abstract": [
        {
          "text": "The top-front center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_CenterTopFront"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopFront",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_CenterTopFront"
        }
      ],
      "role": "symbol",
      "title": "bit_CenterTopFront",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_centertopfront"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopMiddle": {
      "abstract": [
        {
          "text": "The top-middle center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_CenterTopMiddle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopMiddle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_CenterTopMiddle"
        }
      ],
      "role": "symbol",
      "title": "bit_CenterTopMiddle",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_centertopmiddle"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopRear": {
      "abstract": [
        {
          "text": "The top-right center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_CenterTopRear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopRear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_CenterTopRear"
        }
      ],
      "role": "symbol",
      "title": "bit_CenterTopRear",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_centertoprear"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackCenter": {
      "abstract": [
        {
          "text": "The top-back center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_TopBackCenter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_TopBackCenter"
        }
      ],
      "role": "symbol",
      "title": "bit_TopBackCenter",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_topbackcenter"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopCenterSurround": {
      "abstract": [
        {
          "text": "The top center surround channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_TopCenterSurround"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopCenterSurround",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_TopCenterSurround"
        }
      ],
      "role": "symbol",
      "title": "bit_TopCenterSurround",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_topcentersurround"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightCenter": {
      "abstract": [
        {
          "text": "The vertical height center channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bit_VerticalHeightCenter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioChannelBitmap",
          "text": "AudioChannelBitmap"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_VerticalHeightCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioChannelBit_VerticalHeightCenter"
        }
      ],
      "role": "symbol",
      "title": "bit_VerticalHeightCenter",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiochannelbitmap/bit_verticalheightcenter"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Center",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Center",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterSurround",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopFront",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopMiddle",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopRear",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackCenter",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopCenterSurround"
      ],
      "title": "Center"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioChannelBit_VerticalHeightCenter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_VerticalHeightCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Center",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_Center",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterSurround",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopFront",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopMiddle",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_CenterTopRear",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopBackCenter",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioChannelBitmap/bit_TopCenterSurround"
              ],
              "title": "Center"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioChannelBit_VerticalHeightCenter"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap/title",
          "value": "AudioChannelBitmap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioChannelBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterTopRear/title",
          "value": "kAudioChannelBit_CenterTopRear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterTopRear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_CenterTopRear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterTopMiddle/title",
          "value": "kAudioChannelBit_CenterTopMiddle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterTopMiddle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_CenterTopMiddle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterSurround/title",
          "value": "kAudioChannelBit_CenterSurround"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterSurround/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_CenterSurround"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_TopBackCenter/title",
          "value": "kAudioChannelBit_TopBackCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_TopBackCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_TopBackCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_VerticalHeightCenter/title",
          "value": "kAudioChannelBit_VerticalHeightCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_VerticalHeightCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_VerticalHeightCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_Center/title",
          "value": "kAudioChannelBit_Center"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_Center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_Center"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterTopFront/title",
          "value": "kAudioChannelBit_CenterTopFront"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_CenterTopFront/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_CenterTopFront"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_TopCenterSurround/title",
          "value": "kAudioChannelBit_TopCenterSurround"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioChannelBitmap~1bit_TopCenterSurround/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioChannelBit_TopCenterSurround"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/audiochannelbitmap/bit_verticalheightcenter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/audiochannelbitmap/bit_verticalheightcenter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
