{
  "abstract": [
    {
      "text": "The media type the format description defines isn’t value for the requested operation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/invalidMediaTypeForOperation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So17CMSampleBufferRefa9CoreMediaE5ErrorV07invalidE16TypeForOperationSo7NSErrorCvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidMediaTypeForOperation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSError",
        "text": "NSError"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "invalidMediaTypeForOperation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidMediaTypeForOperation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This error occurs, for example, if you call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/withUnsafeAudioStreamPacketDescriptions(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with nonaudio data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer": {
      "abstract": [
        {
          "text": "A reference to a buffer of media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSampleBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSampleBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMSampleBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error": {
      "abstract": [
        {
          "text": "A structure that defines errors that occur during framework operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "role": "symbol",
      "title": "CMSampleBuffer.Error",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/allocationFailed": {
      "abstract": [
        {
          "text": "The system failed to allocate memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allocationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/allocationFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "allocationFailed",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/allocationfailed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/alreadyHasDataBuffer": {
      "abstract": [
        {
          "text": "You attempted to set data on a sample buffer that already contains media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyHasDataBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/alreadyHasDataBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "alreadyHasDataBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/alreadyhasdatabuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/arrayTooSmall": {
      "abstract": [
        {
          "text": "The output array isn’t large enough to hold the requested array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrayTooSmall"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/arrayTooSmall",
      "kind": "symbol",
      "role": "symbol",
      "title": "arrayTooSmall",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/arraytoosmall"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/bufferHasNoSampleSizes": {
      "abstract": [
        {
          "text": "You requested sample sizes on a buffer that doesn’t provide that information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bufferHasNoSampleSizes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/bufferHasNoSampleSizes",
      "kind": "symbol",
      "role": "symbol",
      "title": "bufferHasNoSampleSizes",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/bufferhasnosamplesizes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/bufferHasNoSampleTimingInfo": {
      "abstract": [
        {
          "text": "You requested sample timing on a buffer that doesn’t contain that information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bufferHasNoSampleTimingInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/bufferHasNoSampleTimingInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "bufferHasNoSampleTimingInfo",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/bufferhasnosampletiminginfo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/bufferNotReady": {
      "abstract": [
        {
          "text": "The system can’t make the buffer’s data ready for use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bufferNotReady"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/bufferNotReady",
      "kind": "symbol",
      "role": "symbol",
      "title": "bufferNotReady",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/buffernotready"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/cannotSubdivide": {
      "abstract": [
        {
          "text": "A sample buffer doesn’t contain sample sizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cannotSubdivide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/cannotSubdivide",
      "kind": "symbol",
      "role": "symbol",
      "title": "cannotSubdivide",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/cannotsubdivide"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/dataCanceled": {
      "abstract": [
        {
          "text": "A sample buffer canceled its data loading operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataCanceled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/dataCanceled",
      "kind": "symbol",
      "role": "symbol",
      "title": "dataCanceled",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/datacanceled"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/dataFailed": {
      "abstract": [
        {
          "text": "A sample buffer failed to load its data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/dataFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "dataFailed",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/datafailed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/invalidEntryCount": {
      "abstract": [
        {
          "text": "A timing or size value isn’t within the allowed range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidEntryCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/invalidEntryCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidEntryCount",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/invalidentrycount"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/invalidMediaFormat": {
      "abstract": [
        {
          "text": "The format of the media doesn’t match the sample buffer’s format description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidMediaFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/invalidMediaFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidMediaFormat",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/invalidmediaformat"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/invalidMediaTypeForOperation": {
      "abstract": [
        {
          "text": "The media type the format description defines isn’t value for the requested operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidMediaTypeForOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/invalidMediaTypeForOperation",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidMediaTypeForOperation",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/invalidmediatypeforoperation"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/invalidSampleData": {
      "abstract": [
        {
          "text": "The sample buffer contains bad data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSampleData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/invalidSampleData",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidSampleData",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/invalidsampledata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/invalidated": {
      "abstract": [
        {
          "text": "A sample buffer invalidated its data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/invalidated",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidated",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/invalidated"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/requiredParameterMissing": {
      "abstract": [
        {
          "text": "You didn’t provide a valid value for a required parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiredParameterMissing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/requiredParameterMissing",
      "kind": "symbol",
      "role": "symbol",
      "title": "requiredParameterMissing",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/requiredparametermissing"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/sampleIndexOutOfRange": {
      "abstract": [
        {
          "text": "You specified a sample index that’s outside of the range of samples that the buffer contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleIndexOutOfRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSError",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/sampleIndexOutOfRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "sampleIndexOutOfRange",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error/sampleindexoutofrange"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/withUnsafeAudioStreamPacketDescriptions(_:)": {
      "abstract": [
        {
          "text": "Calls a closure with an audio stream packet description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withUnsafeAudioStreamPacketDescriptions"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ">(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SR",
          "text": "UnsafeBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamPacketDescription",
          "text": "AudioStreamPacketDescription"
        },
        {
          "kind": "text",
          "text": ">) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/withUnsafeAudioStreamPacketDescriptions(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "withUnsafeAudioStreamPacketDescriptions(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/withunsafeaudiostreampacketdescriptions(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/allocationFailed",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/alreadyHasDataBuffer",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/arrayTooSmall",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/bufferHasNoSampleSizes",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/bufferHasNoSampleTimingInfo",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/bufferNotReady",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/cannotSubdivide",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/dataCanceled",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/dataFailed",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/invalidEntryCount",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/invalidMediaFormat",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/invalidSampleData",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/invalidated",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/requiredParameterMissing",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error/sampleIndexOutOfRange"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBuffer/title",
          "value": "CMSampleBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleBufferRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmsamplebuffer/error/invalidmediatypeforoperation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
