{
  "abstract": [
    {
      "text": "A project extension created from an existing Photos project.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/project"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHProjectCreationSource@PHProjectCreationSourceProject",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "project"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHProjectCreationSourceProject"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PHProjectInfo.CreationSource.project"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "project"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo": {
      "abstract": [
        {
          "text": "Information about the project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectInfo"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectInfo"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum": {
      "abstract": [
        {
          "text": "Defines the source of a project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CreationSource"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CreationSource"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo.CreationSource",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/creationsource-swift.enum"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/album": {
      "abstract": [
        {
          "text": "A project extension created from a photo album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "album"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/album",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectCreationSourceAlbum"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo.CreationSource.album",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/creationsource-swift.enum/album"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/memory": {
      "abstract": [
        {
          "text": "A project extension created from a memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "memory"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/memory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectCreationSourceMemory"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo.CreationSource.memory",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/creationsource-swift.enum/memory"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/moment": {
      "abstract": [
        {
          "text": "A project extension created from a moment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moment"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/moment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectCreationSourceMoment"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo.CreationSource.moment",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/creationsource-swift.enum/moment"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/project": {
      "abstract": [
        {
          "text": "A project extension created from an existing Photos project.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "project"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/project",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectCreationSourceProject"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo.CreationSource.project",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/creationsource-swift.enum/project"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectBook": {
      "abstract": [
        {
          "text": "A project extension created from a Photos project book.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projectBook"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectBook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectCreationSourceProjectBook"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo.CreationSource.projectBook",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/creationsource-swift.enum/projectbook"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectCalendar": {
      "abstract": [
        {
          "text": "A project extension created from a calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projectCalendar"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectCalendar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectCreationSourceProjectCalendar"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo.CreationSource.projectCalendar",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/creationsource-swift.enum/projectcalendar"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectCard": {
      "abstract": [
        {
          "text": "A project extension created from a card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projectCard"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectCard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectCreationSourceProjectCard"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo.CreationSource.projectCard",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/creationsource-swift.enum/projectcard"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectExtension": {
      "abstract": [
        {
          "text": "A project extension created from another project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projectExtension"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectCreationSourceProjectExtension"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo.CreationSource.projectExtension",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/creationsource-swift.enum/projectextension"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectPrintOrder": {
      "abstract": [
        {
          "text": "A project extension created from a print order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projectPrintOrder"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectPrintOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectCreationSourceProjectPrintOrder"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo.CreationSource.projectPrintOrder",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/creationsource-swift.enum/projectprintorder"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectSlideshow": {
      "abstract": [
        {
          "text": "A project slideshow extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projectSlideshow"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectSlideshow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectCreationSourceProjectSlideshow"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo.CreationSource.projectSlideshow",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/creationsource-swift.enum/projectslideshow"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/undefined": {
      "abstract": [
        {
          "text": "An undefined project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefined"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/undefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectCreationSourceUndefined"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo.CreationSource.undefined",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/creationsource-swift.enum/undefined"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/userSelection": {
      "abstract": [
        {
          "text": "A project extension created from a user selection of photos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userSelection"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/userSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectCreationSourceUserSelection"
        }
      ],
      "role": "symbol",
      "title": "PHProjectInfo.CreationSource.userSelection",
      "type": "topic",
      "url": "/documentation/photosui/phprojectinfo/creationsource-swift.enum/userselection"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Project-Sources",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/undefined",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/userSelection",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/album",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/memory",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/moment",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectBook",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectCalendar",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectCard",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectPrintOrder",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectSlideshow",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectExtension"
      ],
      "title": "Project Sources"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHProjectCreationSourceProject"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSourceProject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/PhotosUI",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Project-Sources",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/undefined",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/userSelection",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/album",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/memory",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/moment",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectBook",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectCalendar",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectCard",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectPrintOrder",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectSlideshow",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectInfo/CreationSource-swift.enum/projectExtension"
              ],
              "title": "Project Sources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PHProjectCreationSourceProject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1userSelection/title",
          "value": "PHProjectCreationSourceUserSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1userSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSourceUserSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1moment/title",
          "value": "PHProjectCreationSourceMoment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1moment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSourceMoment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1projectPrintOrder/title",
          "value": "PHProjectCreationSourceProjectPrintOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1projectPrintOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSourceProjectPrintOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1album/title",
          "value": "PHProjectCreationSourceAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1album/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSourceAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum/title",
          "value": "PHProjectCreationSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1memory/title",
          "value": "PHProjectCreationSourceMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1memory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSourceMemory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1undefined/title",
          "value": "PHProjectCreationSourceUndefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1undefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSourceUndefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1projectSlideshow/title",
          "value": "PHProjectCreationSourceProjectSlideshow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1projectSlideshow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSourceProjectSlideshow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo/title",
          "value": "PHProjectInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1projectBook/title",
          "value": "PHProjectCreationSourceProjectBook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1projectBook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSourceProjectBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1projectExtension/title",
          "value": "PHProjectCreationSourceProjectExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1projectExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSourceProjectExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1projectCalendar/title",
          "value": "PHProjectCreationSourceProjectCalendar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1projectCalendar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSourceProjectCalendar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1projectCard/title",
          "value": "PHProjectCreationSourceProjectCard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1projectCard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSourceProjectCard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1project/title",
          "value": "PHProjectCreationSourceProject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectInfo~1CreationSource-swift.enum~1project/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectCreationSourceProject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phprojectinfo/creationsource-swift.enum/project"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photosui/phprojectinfo/creationsource-swift.enum/project"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
