{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode2idx"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@IOBluetoothHandsFreeCallHoldModes@IOBluetoothHandsFreeCallHoldMode2idx",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mode2idx"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOBluetoothHandsFreeCallHoldMode2idx"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "IOBluetoothHandsFreeCallHoldModes.mode2idx"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mode2idx"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeCallHoldModes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeCallHoldModes"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeCallHoldModes",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreecallholdmodes"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode0"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeCallHoldMode0"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeCallHoldModes.mode0",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreecallholdmodes/mode0"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode1"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeCallHoldMode1"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeCallHoldModes.mode1",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreecallholdmodes/mode1"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode1idx": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode1idx"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode1idx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeCallHoldMode1idx"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeCallHoldModes.mode1idx",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreecallholdmodes/mode1idx"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode2"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeCallHoldMode2"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeCallHoldModes.mode2",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreecallholdmodes/mode2"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode2idx": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode2idx"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode2idx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeCallHoldMode2idx"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeCallHoldModes.mode2idx",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreecallholdmodes/mode2idx"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode3"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeCallHoldMode3"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeCallHoldModes.mode3",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreecallholdmodes/mode3"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode4"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeCallHoldMode4"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeCallHoldModes.mode4",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreecallholdmodes/mode4"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode0",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode1",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode1idx",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode2",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode3",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode4"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOBluetoothHandsFreeCallHoldMode2idx"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeCallHoldMode2idx"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode0",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode1",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode1idx",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode2",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode3",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeCallHoldModes/mode4"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "IOBluetoothHandsFreeCallHoldMode2idx"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes~1mode1/title",
          "value": "IOBluetoothHandsFreeCallHoldMode1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes~1mode1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeCallHoldMode1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes~1mode2idx/title",
          "value": "IOBluetoothHandsFreeCallHoldMode2idx"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes~1mode2idx/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeCallHoldMode2idx"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes~1mode3/title",
          "value": "IOBluetoothHandsFreeCallHoldMode3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes~1mode3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeCallHoldMode3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes~1mode2/title",
          "value": "IOBluetoothHandsFreeCallHoldMode2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes~1mode2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeCallHoldMode2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes/title",
          "value": "IOBluetoothHandsFreeCallHoldModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeCallHoldModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeCallHoldModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes~1mode1idx/title",
          "value": "IOBluetoothHandsFreeCallHoldMode1idx"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes~1mode1idx/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeCallHoldMode1idx"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes~1mode4/title",
          "value": "IOBluetoothHandsFreeCallHoldMode4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes~1mode4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeCallHoldMode4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes~1mode0/title",
          "value": "IOBluetoothHandsFreeCallHoldMode0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeCallHoldModes~1mode0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeCallHoldMode0"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothhandsfreecallholdmodes/mode2idx"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothhandsfreecallholdmodes/mode2idx"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
