{
  "abstract": [
    {
      "text": "The region containing points that trace the right eyebrow.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/rightEyebrow"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNFaceLandmarks2D(py)rightEyebrow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rightEyebrow"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
        "text": "VNFaceLandmarkRegion2D"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "rightEyebrow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "rightEyebrow"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rightEyebrow"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarkRegion2D",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
              "text": "VNFaceLandmarkRegion2D"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarkRegion2D": {
      "abstract": [
        {
          "text": "2D geometry information for a specific facial feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNFaceLandmarkRegion2D"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarkRegion2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNFaceLandmarkRegion2D"
        }
      ],
      "role": "symbol",
      "title": "VNFaceLandmarkRegion2D",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarkregion2d"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D": {
      "abstract": [
        {
          "text": "A collection of facial features that a request detects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNFaceLandmarks2D"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNFaceLandmarks2D"
        }
      ],
      "role": "symbol",
      "title": "VNFaceLandmarks2D",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarks2d"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/allPoints": {
      "abstract": [
        {
          "text": "The region containing all face landmark points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allPoints"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
          "text": "VNFaceLandmarkRegion2D"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/allPoints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allPoints"
        }
      ],
      "role": "symbol",
      "title": "allPoints",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarks2d/allpoints"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/faceContour": {
      "abstract": [
        {
          "text": "The region containing points that trace the face contour from the left cheek, over the chin, to the right cheek.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceContour"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
          "text": "VNFaceLandmarkRegion2D"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/faceContour",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "faceContour"
        }
      ],
      "role": "symbol",
      "title": "faceContour",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarks2d/facecontour"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/innerLips": {
      "abstract": [
        {
          "text": "The region containing points that outline the space between the lips.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "innerLips"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
          "text": "VNFaceLandmarkRegion2D"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/innerLips",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "innerLips"
        }
      ],
      "role": "symbol",
      "title": "innerLips",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarks2d/innerlips"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/leftEye": {
      "abstract": [
        {
          "text": "The region containing points that outline the left eye.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftEye"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
          "text": "VNFaceLandmarkRegion2D"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/leftEye",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftEye"
        }
      ],
      "role": "symbol",
      "title": "leftEye",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarks2d/lefteye"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/leftEyebrow": {
      "abstract": [
        {
          "text": "The region containing points that trace the left eyebrow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftEyebrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
          "text": "VNFaceLandmarkRegion2D"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/leftEyebrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftEyebrow"
        }
      ],
      "role": "symbol",
      "title": "leftEyebrow",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarks2d/lefteyebrow"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/leftPupil": {
      "abstract": [
        {
          "text": "The region containing the point where the left pupil is located.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftPupil"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
          "text": "VNFaceLandmarkRegion2D"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/leftPupil",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftPupil"
        }
      ],
      "role": "symbol",
      "title": "leftPupil",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarks2d/leftpupil"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/medianLine": {
      "abstract": [
        {
          "text": "The region containing points that trace a vertical line down the center of the face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medianLine"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
          "text": "VNFaceLandmarkRegion2D"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/medianLine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "medianLine"
        }
      ],
      "role": "symbol",
      "title": "medianLine",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarks2d/medianline"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/nose": {
      "abstract": [
        {
          "text": "The region containing points that outline the nose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nose"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
          "text": "VNFaceLandmarkRegion2D"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/nose",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nose"
        }
      ],
      "role": "symbol",
      "title": "nose",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarks2d/nose"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/noseCrest": {
      "abstract": [
        {
          "text": "The region containing points that trace the center crest of the nose.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noseCrest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
          "text": "VNFaceLandmarkRegion2D"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/noseCrest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "noseCrest"
        }
      ],
      "role": "symbol",
      "title": "noseCrest",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarks2d/nosecrest"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/outerLips": {
      "abstract": [
        {
          "text": "The region containing points that outline the outside of the lips.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outerLips"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
          "text": "VNFaceLandmarkRegion2D"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/outerLips",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outerLips"
        }
      ],
      "role": "symbol",
      "title": "outerLips",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarks2d/outerlips"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/rightEye": {
      "abstract": [
        {
          "text": "The region containing points that outline the right eye.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightEye"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
          "text": "VNFaceLandmarkRegion2D"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/rightEye",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightEye"
        }
      ],
      "role": "symbol",
      "title": "rightEye",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarks2d/righteye"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/rightEyebrow": {
      "abstract": [
        {
          "text": "The region containing points that trace the right eyebrow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightEyebrow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
          "text": "VNFaceLandmarkRegion2D"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/rightEyebrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightEyebrow"
        }
      ],
      "role": "symbol",
      "title": "rightEyebrow",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarks2d/righteyebrow"
    },
    "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/rightPupil": {
      "abstract": [
        {
          "text": "The region containing the point where the right pupil is located.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightPupil"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
          "text": "VNFaceLandmarkRegion2D"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/rightPupil",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightPupil"
        }
      ],
      "role": "symbol",
      "title": "rightPupil",
      "type": "topic",
      "url": "/documentation/vision/vnfacelandmarks2d/rightpupil"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Face-Landmark-Points",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/allPoints",
        "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/faceContour",
        "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/leftEye",
        "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/rightEye",
        "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/leftEyebrow",
        "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/nose",
        "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/noseCrest",
        "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/medianLine",
        "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/outerLips",
        "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/innerLips",
        "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/leftPupil",
        "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/rightPupil"
      ],
      "title": "Face Landmark Points"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "rightEyebrow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightEyebrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision",
                "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Face-Landmark-Points",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/allPoints",
                "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/faceContour",
                "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/leftEye",
                "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/rightEye",
                "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/leftEyebrow",
                "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/nose",
                "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/noseCrest",
                "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/medianLine",
                "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/outerLips",
                "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/innerLips",
                "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/leftPupil",
                "doc://com.apple.vision/documentation/Vision/VNFaceLandmarks2D/rightPupil"
              ],
              "title": "Face Landmark Points"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.vision/documentation/Vision/VNFaceLandmarkRegion2D",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VNFaceLandmarkRegion2D",
                    "text": "VNFaceLandmarkRegion2D"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "rightEyebrow"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1medianLine/title",
          "value": "medianLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1medianLine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "medianLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1leftEye/title",
          "value": "leftEye"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1leftEye/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftEye"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1nose/title",
          "value": "nose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1nose/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1rightEye/title",
          "value": "rightEye"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1rightEye/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightEye"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D/title",
          "value": "VNFaceLandmarks2D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNFaceLandmarks2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNFaceLandmarks2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1leftPupil/title",
          "value": "leftPupil"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1leftPupil/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftPupil"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1outerLips/title",
          "value": "outerLips"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1outerLips/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outerLips"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1noseCrest/title",
          "value": "noseCrest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1noseCrest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "noseCrest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarkRegion2D/title",
          "value": "VNFaceLandmarkRegion2D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarkRegion2D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNFaceLandmarkRegion2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarkRegion2D/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNFaceLandmarkRegion2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1rightPupil/title",
          "value": "rightPupil"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1rightPupil/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightPupil"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1rightEyebrow/title",
          "value": "rightEyebrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1rightEyebrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightEyebrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1faceContour/title",
          "value": "faceContour"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1faceContour/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "faceContour"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1innerLips/title",
          "value": "innerLips"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1innerLips/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "innerLips"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1leftEyebrow/title",
          "value": "leftEyebrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1leftEyebrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftEyebrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1allPoints/title",
          "value": "allPoints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNFaceLandmarks2D~1allPoints/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allPoints"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vnfacelandmarks2d/righteyebrow"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vnfacelandmarks2d/righteyebrow"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
