{
  "abstract": [
    {
      "text": "Display lesson content that’s synchronized to a learning video by matching the audio to a custom reference signature and associated metadata.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.shazamkit/documentation/ShazamKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.shazamkit/documentation/ShazamKit/building-a-custom-catalog-and-matching-audio"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ShazamKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Building a Custom Catalog and Matching Audio"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC21 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc21/10045/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Configure-the-Sample-Code-Project",
          "level": 3,
          "text": "Configure the Sample Code Project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before you run the sample code project in Xcode:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Download the associated video from the URL given in the session video.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "381514c405ff/BuildingACustomCatalogAndMatchingAudio.zip": {
      "checksum": "381514c405ffa249a131776d0f131b861eaa74d549048dfd4970eef4b5c0ee7f78ab28bc2bbc7870ff2132cf64a5bdb88d27aca0a5a2636c72ed76ea17d3bf18",
      "identifier": "381514c405ff/BuildingACustomCatalogAndMatchingAudio.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/381514c405ff/BuildingACustomCatalogAndMatchingAudio.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit": {
      "abstract": [
        {
          "text": "Find information about a specific audio recording when a segment of it’s part of captured sound in the Shazam catalog or your custom catalog.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ShazamKit",
      "type": "topic",
      "url": "/documentation/shazamkit"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog": {
      "abstract": [
        {
          "text": "An abstract base class for storing reference signatures and their associated metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHCatalog"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHCatalog"
        }
      ],
      "role": "symbol",
      "title": "SHCatalog",
      "type": "topic",
      "url": "/documentation/shazamkit/shcatalog"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHCustomCatalog": {
      "abstract": [
        {
          "text": "An object for storing the reference signatures for custom audio recordings and their associated metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHCustomCatalog"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHCustomCatalog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHCustomCatalog"
        }
      ],
      "role": "symbol",
      "title": "SHCustomCatalog",
      "type": "topic",
      "url": "/documentation/shazamkit/shcustomcatalog"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/shazamkit-dance-finder-with-managed-session": {
      "abstract": [
        {
          "text": "Find a video of dance moves for a specific song by matching the audio to a custom catalog, and show a history of recognized songs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/shazamkit-dance-finder-with-managed-session",
      "kind": "article",
      "role": "sampleCode",
      "title": "ShazamKit Dance Finder with Managed Session",
      "type": "topic",
      "url": "/documentation/shazamkit/shazamkit-dance-finder-with-managed-session"
    },
    "https://developer.apple.com/wwdc21/10045/": {
      "identifier": "https://developer.apple.com/wwdc21/10045/",
      "title": "10045: Create Custom Audio Experiences with ShazamKit",
      "titleInlineContent": [
        {
          "text": "10045: Create Custom Audio Experiences with ShazamKit",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc21/10045/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "381514c405ff/BuildingACustomCatalogAndMatchingAudio.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Create-a-custom-audio-catalog",
      "generated": true,
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/shazamkit-dance-finder-with-managed-session",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHCustomCatalog",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog"
      ],
      "title": "Create a custom audio catalog"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Create-a-custom-audio-catalog",
              "generated": true,
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHCustomCatalog",
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog"
              ],
              "title": "Create a custom audio catalog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHCustomCatalog/title",
          "value": "SHCustomCatalog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHCustomCatalog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHCustomCatalog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHCustomCatalog/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SHCustomCatalog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHCatalog/title",
          "value": "SHCatalog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHCatalog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHCatalog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHCatalog/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SHCatalog"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/shazamkit/building-a-custom-catalog-and-matching-audio"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/shazamkit/building-a-custom-catalog-and-matching-audio"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
