{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.shazamkit/documentation/ShazamKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.shazamkit/documentation/ShazamKit/shazamkit-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ShazamKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "ShazamKit Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit": {
      "abstract": [
        {
          "text": "Find information about a specific audio recording when a segment of it’s part of captured sound in the Shazam catalog or your custom catalog.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ShazamKit",
      "type": "topic",
      "url": "/documentation/shazamkit"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHDEFINES_H": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SHDEFINES_H"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHDEFINES_H",
      "kind": "symbol",
      "role": "symbol",
      "title": "SHDEFINES_H",
      "type": "topic",
      "url": "/documentation/shazamkit/shdefines_h"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for specific errors for ShazamKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SHErrorDomain",
      "type": "topic",
      "url": "/documentation/shazamkit/sherrordomain"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SH_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SH_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SH_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "SH_EXPORT",
      "type": "topic",
      "url": "/documentation/shazamkit/sh_export"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/shazamkit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/shazamkit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ShazamKit Enumerations",
      "type": "topic",
      "url": "/documentation/shazamkit/shazamkit-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/shazamkit-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHErrorDomain"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHErrorDomain"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHDEFINES_H",
                "doc://com.apple.shazamkit/documentation/ShazamKit/SH_EXPORT"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/shazamkit-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHErrorDomain/title",
          "value": "SHErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/shazamkit/shazamkit-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/shazamkit/shazamkit-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
