{
  "abstract": [
    {
      "text": "A half-open interval from a lower bound up to, but not including, an upper bound.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.shazamkit/documentation/ShazamKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SHRange",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SHRange"
      }
    ],
    "modules": [
      {
        "name": "ShazamKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SHRange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SHRange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SHRange"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit": {
      "abstract": [
        {
          "text": "Find information about a specific audio recording when a segment of it’s part of captured sound in the Shazam catalog or your custom catalog.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ShazamKit",
      "type": "topic",
      "url": "/documentation/shazamkit"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/frequencySkewRanges-4yqx": {
      "abstract": [
        {
          "text": "An array of ranges that indicate the frequency skews in the reference signature that this media item describes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "frequencySkewRanges"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/frequencySkewRanges-4yqx",
      "kind": "symbol",
      "role": "symbol",
      "title": "frequencySkewRanges",
      "type": "topic",
      "url": "/documentation/shazamkit/shmediaitem/frequencyskewranges-4yqx"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/subscript(_:)": {
      "abstract": [
        {
          "text": "Accesses the property for the specified key for reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SHMediaItemProperty",
          "text": "SHMediaItemProperty"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/subscript(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKeyedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/shazamkit/shmediaitem/subscript(_:)"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/timeRanges-43654": {
      "abstract": [
        {
          "text": "An array of ranges that indicate the offsets within the reference signature that this media item describes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "timeRanges"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/timeRanges-43654",
      "kind": "symbol",
      "role": "symbol",
      "title": "timeRanges",
      "type": "topic",
      "url": "/documentation/shazamkit/shmediaitem/timeranges-43654"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/valueForProperty:": {
      "abstract": [
        {
          "text": "Accesses the property for the specified key for reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "valueForProperty:"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/valueForProperty:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueForProperty:"
        }
      ],
      "role": "symbol",
      "title": "valueForProperty:",
      "type": "topic",
      "url": "/documentation/shazamkit/shmediaitem/valueforproperty:"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItemProperty": {
      "abstract": [
        {
          "text": "Constants for the media item property names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHMediaItemProperty"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItemProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHMediaItemProperty"
        }
      ],
      "role": "symbol",
      "title": "SHMediaItemProperty",
      "type": "topic",
      "url": "/documentation/shazamkit/shmediaitemproperty"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange": {
      "abstract": [
        {
          "text": "A half-open interval from a lower bound up to, but not including, an upper bound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SHRange"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "SHRange",
      "type": "topic",
      "url": "/documentation/shazamkit/shrange"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange/initWithLowerBound:upperBound:": {
      "abstract": [
        {
          "text": "Creates a range with the bounds you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithLowerBound:upperBound:"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange/initWithLowerBound:upperBound:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLowerBound:upperBound:"
        }
      ],
      "role": "symbol",
      "title": "initWithLowerBound:upperBound:",
      "type": "topic",
      "url": "/documentation/shazamkit/shrange/initwithlowerbound:upperbound:"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange/lowerBound": {
      "abstract": [
        {
          "text": "The range’s lower bound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "lowerBound"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange/lowerBound",
      "kind": "symbol",
      "role": "symbol",
      "title": "lowerBound",
      "type": "topic",
      "url": "/documentation/shazamkit/shrange/lowerbound"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange/rangeWithLowerBound:upperBound:": {
      "abstract": [
        {
          "text": "Creates a range with the bounds you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "rangeWithLowerBound:upperBound:"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange/rangeWithLowerBound:upperBound:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rangeWithLowerBound:upperBound:"
        }
      ],
      "role": "symbol",
      "title": "rangeWithLowerBound:upperBound:",
      "type": "topic",
      "url": "/documentation/shazamkit/shrange/rangewithlowerbound:upperbound:"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange/upperBound": {
      "abstract": [
        {
          "text": "The range’s upper bound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "upperBound"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange/upperBound",
      "kind": "symbol",
      "role": "symbol",
      "title": "upperBound",
      "type": "topic",
      "url": "/documentation/shazamkit/shrange/upperbound"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-media-item-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/subscript(_:)",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/valueForProperty:",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItemProperty",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/timeRanges-43654",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHMediaItem/frequencySkewRanges-4yqx"
      ],
      "title": "Working with media item properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-range",
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange/rangeWithLowerBound:upperBound:",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange/initWithLowerBound:upperBound:"
      ],
      "title": "Creating a range"
    },
    {
      "anchor": "Inspecting-a-range",
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange/lowerBound",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHRange/upperBound"
      ],
      "title": "Inspecting a range"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItemProperty/title",
          "value": "SHMediaItemProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItemProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHMediaItemProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItemProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SHMediaItemProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1subscript(_:)/title",
          "value": "objectForKeyedSubscript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHMediaItem~1subscript(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectForKeyedSubscript:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/shazamkit/shrange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
