{
  "abstract": [
    {
      "text": "An object for converting audio data into a signature.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.shazamkit/documentation/ShazamKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SHSignatureGenerator",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SHSignatureGenerator"
      }
    ],
    "modules": [
      {
        "name": "ShazamKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SHSignatureGenerator"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SHSignatureGenerator"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SHSignatureGenerator"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/generating-a-signature-from-an-audio-buffer"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create both reference and query signatures using this class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit": {
      "abstract": [
        {
          "text": "Find information about a specific audio recording when a segment of it’s part of captured sound in the Shazam catalog or your custom catalog.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ShazamKit",
      "type": "topic",
      "url": "/documentation/shazamkit"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature": {
      "abstract": [
        {
          "text": "An object that contains the opaque data and other information for a signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHSignature"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHSignature"
        }
      ],
      "role": "symbol",
      "title": "SHSignature",
      "type": "topic",
      "url": "/documentation/shazamkit/shsignature"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator": {
      "abstract": [
        {
          "text": "An object for converting audio data into a signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHSignatureGenerator"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHSignatureGenerator"
        }
      ],
      "role": "symbol",
      "title": "SHSignatureGenerator",
      "type": "topic",
      "url": "/documentation/shazamkit/shsignaturegenerator"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator/append(_:at:)": {
      "abstract": [
        {
          "text": "Adds audio to the generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "append"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioPCMBuffer",
          "text": "AVAudioPCMBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioTime",
          "text": "AVAudioTime"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator/append(_:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appendBuffer:atTime:error:"
        }
      ],
      "role": "symbol",
      "title": "append(_:at:)",
      "type": "topic",
      "url": "/documentation/shazamkit/shsignaturegenerator/append(_:at:)"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator/generateSignature(from:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a signature with the asset you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "generateSignature"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAsset",
          "text": "AVAsset"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SHSignature",
          "text": "SHSignature"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator/generateSignature(from:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "generateSignatureFromAsset:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "generateSignature(from:completionHandler:)",
      "type": "topic",
      "url": "/documentation/shazamkit/shsignaturegenerator/generatesignature(from:completionhandler:)"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator/signature()": {
      "abstract": [
        {
          "text": "Converts the audio buffer into a signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signature"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SHSignature",
          "text": "SHSignature"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator/signature()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signature"
        }
      ],
      "role": "symbol",
      "title": "signature()",
      "type": "topic",
      "url": "/documentation/shazamkit/shsignaturegenerator/signature()"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/generating-a-signature-from-an-audio-buffer": {
      "abstract": [
        {
          "text": "Create a signature from an audio file or the microphone for a reference track in a custom catalog, or for matching tracks in a catalog.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/generating-a-signature-from-an-audio-buffer",
      "kind": "article",
      "role": "article",
      "title": "Generating a signature from an audio buffer",
      "type": "topic",
      "url": "/documentation/shazamkit/generating-a-signature-from-an-audio-buffer"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Create-a-signature-from-audio",
      "generated": true,
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature"
      ],
      "title": "Create a signature from audio"
    }
  ],
  "topicSections": [
    {
      "anchor": "Generating-a-signature-from-audio",
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator/append(_:at:)",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator/signature()",
        "doc://com.apple.shazamkit/documentation/ShazamKit/generating-a-signature-from-an-audio-buffer"
      ],
      "title": "Generating a signature from audio"
    },
    {
      "anchor": "Generate-a-signature-from-assets",
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator/generateSignature(from:completionHandler:)"
      ],
      "title": "Generate a signature from assets"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SHSignatureGenerator"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHSignatureGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SHSignatureGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.shazamkit/documentation/ShazamKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Generating-a-signature-from-audio",
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator/append(_:at:)",
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator/signature()",
                "doc://com.apple.shazamkit/documentation/ShazamKit/generating-a-signature-from-an-audio-buffer"
              ],
              "title": "Generating a signature from audio"
            },
            {
              "anchor": "Generate-a-signature-from-assets",
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator/generateSignature(from:completionHandler:)"
              ],
              "title": "Generate a signature from assets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Create-a-signature-from-audio",
              "generated": true,
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature"
              ],
              "title": "Create a signature from audio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SHSignatureGenerator"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignatureGenerator~1append(_:at:)/title",
          "value": "appendBuffer:atTime:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignatureGenerator~1append(_:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "appendBuffer:atTime:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignatureGenerator~1generateSignature(from:completionHandler:)/title",
          "value": "generateSignatureFromAsset:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignatureGenerator~1generateSignature(from:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "generateSignatureFromAsset:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignatureGenerator~1signature()/title",
          "value": "signature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignatureGenerator~1signature()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "signature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignatureGenerator/title",
          "value": "SHSignatureGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignatureGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHSignatureGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignatureGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SHSignatureGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature/title",
          "value": "SHSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SHSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/shazamkit/shsignaturegenerator"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/shazamkit/shsignaturegenerator"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
