{
  "abstract": [
    {
      "text": "An object that contains the opaque data and other information for a signature.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.shazamkit/documentation/ShazamKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SHSignature",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SHSignature"
      }
    ],
    "modules": [
      {
        "name": "ShazamKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SHSignature"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SHSignature"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SHSignature"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Save your signature to a file and share it with others by writing the data to a file. You can use the saved signatures of reference recordings to populate a custom catalog.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Check whether your captured query signature is long enough to search for a match by comparing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/duration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog/minimumQuerySignatureDuration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog/maximumQuerySignatureDuration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " of a catalog.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UniformTypeIdentifiers/UTType-swift.struct/shazamSignature": {
      "abstract": [
        {
          "text": "A type that represents a signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shazamSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
          "text": "UTType"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UniformTypeIdentifiers/UTType-swift.struct/shazamSignature",
      "kind": "symbol",
      "role": "symbol",
      "title": "shazamSignature",
      "type": "topic",
      "url": "/documentation/UniformTypeIdentifiers/UTType-swift.struct/shazamSignature"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/documentation/uniformtypeidentifiers/uttype/4042905-shsignaturecontenttype": {
      "abstract": [
        {
          "text": "A type that represents a signature.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/uniformtypeidentifiers/uttype/4042905-shsignaturecontenttype",
      "kind": "symbol",
      "role": "symbol",
      "title": "SHSignatureContentType",
      "type": "topic",
      "url": "/documentation/uniformtypeidentifiers/uttype/4042905-shsignaturecontenttype"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit": {
      "abstract": [
        {
          "text": "Find information about a specific audio recording when a segment of it’s part of captured sound in the Shazam catalog or your custom catalog.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ShazamKit",
      "type": "topic",
      "url": "/documentation/shazamkit"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog/maximumQuerySignatureDuration": {
      "abstract": [
        {
          "text": "The maximum duration of a query signature that you use to match reference signatures in the catalog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumQuerySignatureDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog/maximumQuerySignatureDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumQuerySignatureDuration"
        }
      ],
      "role": "symbol",
      "title": "maximumQuerySignatureDuration",
      "type": "topic",
      "url": "/documentation/shazamkit/shcatalog/maximumquerysignatureduration"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog/minimumQuerySignatureDuration": {
      "abstract": [
        {
          "text": "The minimum duration of a query signature that you use to match reference signatures in the catalog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumQuerySignatureDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHCatalog/minimumQuerySignatureDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumQuerySignatureDuration"
        }
      ],
      "role": "symbol",
      "title": "minimumQuerySignatureDuration",
      "type": "topic",
      "url": "/documentation/shazamkit/shcatalog/minimumquerysignatureduration"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature": {
      "abstract": [
        {
          "text": "An object that contains the opaque data and other information for a signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHSignature"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHSignature"
        }
      ],
      "role": "symbol",
      "title": "SHSignature",
      "type": "topic",
      "url": "/documentation/shazamkit/shsignature"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/Slices": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Slices"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/Slices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Slices"
        }
      ],
      "role": "symbol",
      "title": "SHSignature.Slices",
      "type": "topic",
      "url": "/documentation/shazamkit/shsignature/slices"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/dataRepresentation": {
      "abstract": [
        {
          "text": "The raw data for the signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataRepresentation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/dataRepresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataRepresentation"
        }
      ],
      "role": "symbol",
      "title": "dataRepresentation",
      "type": "topic",
      "url": "/documentation/shazamkit/shsignature/datarepresentation"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/duration": {
      "abstract": [
        {
          "text": "The duration of the audio you use to generate the signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/shazamkit/shsignature/duration"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/init(dataRepresentation:)": {
      "abstract": [
        {
          "text": "Creates a signature object from raw data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "dataRepresentation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/init(dataRepresentation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDataRepresentation:error:"
        }
      ],
      "role": "symbol",
      "title": "init(dataRepresentation:)",
      "type": "topic",
      "url": "/documentation/shazamkit/shsignature/init(datarepresentation:)"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/signatureWithDataRepresentation:error:": {
      "abstract": [
        {
          "text": "Creates a signature object from raw data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "signatureWithDataRepresentation:error:"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/signatureWithDataRepresentation:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signatureWithDataRepresentation:error:"
        }
      ],
      "role": "symbol",
      "title": "signatureWithDataRepresentation:error:",
      "type": "topic",
      "url": "/documentation/shazamkit/shsignature/signaturewithdatarepresentation:error:"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/slices(from:duration:stride:)": {
      "abstract": [
        {
          "text": "Returns a sequence of signatures of the specified duration from a starting value, stepping by the stride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slices"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "stride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SHSignature",
          "text": "SHSignature"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So11SHSignatureC9ShazamKitE6SlicesV",
          "text": "Slices"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/slices(from:duration:stride:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "slices(from:duration:stride:)",
      "type": "topic",
      "url": "/documentation/shazamkit/shsignature/slices(from:duration:stride:)"
    },
    "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator": {
      "abstract": [
        {
          "text": "An object for converting audio data into a signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHSignatureGenerator"
        }
      ],
      "identifier": "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SHSignatureGenerator"
        }
      ],
      "role": "symbol",
      "title": "SHSignatureGenerator",
      "type": "topic",
      "url": "/documentation/shazamkit/shsignaturegenerator"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Create-a-signature-from-audio",
      "generated": true,
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator"
      ],
      "title": "Create a signature from audio"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-signature-object",
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/init(dataRepresentation:)"
      ],
      "title": "Creating a signature object"
    },
    {
      "anchor": "Reading-signature-information",
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/dataRepresentation",
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/duration"
      ],
      "title": "Reading signature information"
    },
    {
      "anchor": "Getting-the-content-type",
      "identifiers": [
        "doc://com.apple.documentation/documentation/UniformTypeIdentifiers/UTType-swift.struct/shazamSignature"
      ],
      "title": "Getting the content type"
    },
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/Slices"
      ],
      "title": "Structures"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/slices(from:duration:stride:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SHSignature"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SHSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.shazamkit/documentation/ShazamKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-signature-object",
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/signatureWithDataRepresentation:error:",
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/init(dataRepresentation:)"
              ],
              "title": "Creating a signature object"
            },
            {
              "anchor": "Reading-signature-information",
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/dataRepresentation",
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignature/duration"
              ],
              "title": "Reading signature information"
            },
            {
              "anchor": "Getting-the-content-type",
              "identifiers": [
                "doc://com.apple.documentation/documentation/uniformtypeidentifiers/uttype/4042905-shsignaturecontenttype"
              ],
              "title": "Getting the content type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Create-a-signature-from-audio",
              "generated": true,
              "identifiers": [
                "doc://com.apple.shazamkit/documentation/ShazamKit/SHSignatureGenerator"
              ],
              "title": "Create a signature from audio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SHSignature"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature~1init(dataRepresentation:)/title",
          "value": "initWithDataRepresentation:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature~1init(dataRepresentation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDataRepresentation:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHCatalog~1maximumQuerySignatureDuration/title",
          "value": "maximumQuerySignatureDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHCatalog~1maximumQuerySignatureDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumQuerySignatureDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature~1dataRepresentation/title",
          "value": "dataRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature~1dataRepresentation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dataRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignatureGenerator/title",
          "value": "SHSignatureGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignatureGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHSignatureGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignatureGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SHSignatureGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature/title",
          "value": "SHSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SHSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SHSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHCatalog~1minimumQuerySignatureDuration/title",
          "value": "minimumQuerySignatureDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHCatalog~1minimumQuerySignatureDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumQuerySignatureDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature~1duration/title",
          "value": "duration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.shazamkit~1documentation~1ShazamKit~1SHSignature~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/shazamkit/shsignature"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/shazamkit/shsignature"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
