{
  "abstract": [
    {
      "text": "A value that represents lane guidance associated with this maneuver.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/linkedLaneGuidance"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPManeuver(py)linkedLaneGuidance",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "linkedLaneGuidance"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPLaneGuidance",
        "text": "CPLaneGuidance"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "linkedLaneGuidance"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "linkedLaneGuidance"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "unowned(unsafe)"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "linkedLaneGuidance"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPLaneGuidance",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPLaneGuidance",
              "text": "CPLaneGuidance"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This value is optional; however ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " requires this value if there is a corresponding lane guidance value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPLaneGuidance": {
      "abstract": [
        {
          "text": "A class that provides information that describes the number of lanes on a roadway and navigation instruction variants.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPLaneGuidance"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPLaneGuidance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPLaneGuidance"
        }
      ],
      "role": "symbol",
      "title": "CPLaneGuidance",
      "type": "topic",
      "url": "/documentation/carplay/cplaneguidance"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver": {
      "abstract": [
        {
          "text": "An object that describes a single navigation instruction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPManeuver"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuver"
        }
      ],
      "role": "symbol",
      "title": "CPManeuver",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/highwayExitLabel": {
      "abstract": [
        {
          "text": "A string that describes a highway exit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highwayExitLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/highwayExitLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highwayExitLabel"
        }
      ],
      "role": "symbol",
      "title": "highwayExitLabel",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/highwayexitlabel"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/linkedLaneGuidance": {
      "abstract": [
        {
          "text": "A value that represents lane guidance associated with this maneuver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkedLaneGuidance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPLaneGuidance",
          "text": "CPLaneGuidance"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/linkedLaneGuidance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "linkedLaneGuidance"
        }
      ],
      "role": "symbol",
      "title": "linkedLaneGuidance",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/linkedlaneguidance"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/maneuverType": {
      "abstract": [
        {
          "text": "A value that represents the type of maneuver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maneuverType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPManeuverType",
          "text": "CPManeuverType"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/maneuverType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maneuverType"
        }
      ],
      "role": "symbol",
      "title": "maneuverType",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/maneuvertype"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/roadFollowingManeuverVariants": {
      "abstract": [
        {
          "text": "An array of strings that represent the names of the road following this maneuver, arranged from most to least preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "roadFollowingManeuverVariants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/roadFollowingManeuverVariants",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "roadFollowingManeuverVariants"
        }
      ],
      "role": "symbol",
      "title": "roadFollowingManeuverVariants",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/roadfollowingmaneuvervariants"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/trafficSide": {
      "abstract": [
        {
          "text": "A value that represents which side of the road the traffic drives on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trafficSide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPTrafficSide",
          "text": "CPTrafficSide"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/trafficSide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trafficSide"
        }
      ],
      "role": "symbol",
      "title": "trafficSide",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/trafficside"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-maneuver-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/maneuverType",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/roadFollowingManeuverVariants",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/highwayExitLabel",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/trafficSide"
      ],
      "title": "Providing maneuver information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "linkedLaneGuidance"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "linkedLaneGuidance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-maneuver-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/maneuverType",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/roadFollowingManeuverVariants",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/highwayExitLabel",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/trafficSide"
              ],
              "title": "Providing maneuver information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPLaneGuidance",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPLaneGuidance",
                    "text": "CPLaneGuidance"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "linkedLaneGuidance"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPLaneGuidance/title",
          "value": "CPLaneGuidance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPLaneGuidance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPLaneGuidance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPLaneGuidance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPLaneGuidance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1linkedLaneGuidance/title",
          "value": "linkedLaneGuidance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1linkedLaneGuidance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "linkedLaneGuidance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver/title",
          "value": "CPManeuver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1roadFollowingManeuverVariants/title",
          "value": "roadFollowingManeuverVariants"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1roadFollowingManeuverVariants/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "roadFollowingManeuverVariants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1trafficSide/title",
          "value": "trafficSide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1trafficSide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trafficSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1highwayExitLabel/title",
          "value": "highwayExitLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1highwayExitLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highwayExitLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1maneuverType/title",
          "value": "maneuverType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1maneuverType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maneuverType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpmaneuver/linkedlaneguidance"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpmaneuver/linkedlaneguidance"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
