{"abstract":[{"type":"text","text":"Sets the calendar to use when formatting date information."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate/setCalendar(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Configuring the Date and Time Display","generated":true,"identifiers":["doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate/setTextColor(_:)","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate/setTimeZone(_:)"],"anchor":"Configuring-the-Date-and-Time-Display"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCalendar","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"calendar","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Calendar","identifier":"doc://com.externally.resolved.symbol/s:10Foundation8CalendarV","preciseIdentifier":"s:10Foundation8CalendarV","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["watchOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The calendar to be used. Specifying nil removes the calendar information and causes Apple Watch to use the default calendar based on the user’s settings."}]}],"name":"calendar"}],"kind":"parameters"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Use this method to configure the calendar to one that is different from the user’s current calendar. You might change the calendar to format dates differently based on your app’s needs. For example, a financial reporting app might use a calendar that breaks the year into fiscal quarters rather than months.","type":"text"}]}],"kind":"content"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/watchkit/wkinterfacedate/setcalendar(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/watchkit/wkinterfacedate/setcalendar(_:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCalendar","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Calendar","preciseIdentifier":"s:10Foundation8CalendarV","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"modules":[{"name":"WatchKit"}],"navigatorTitle":[{"kind":"identifier","text":"setCalendar:"}],"roleHeading":"Instance Method","platforms":[{"introducedAt":"2.0","deprecated":false,"beta":false,"unavailable":false,"name":"watchOS"}],"symbolKind":"method","externalID":"c:objc(cs)WKInterfaceDate(im)setCalendar:","title":"setCalendar(_:)","role":"symbol"},"references":{"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate/setTextColor(_:)":{"title":"setTextColor(_:)","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate/setTextColor(_:)","navigatorTitle":[{"kind":"identifier","text":"setTextColor:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTextColor","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?)"}],"url":"/documentation/watchkit/wkinterfacedate/settextcolor(_:)","abstract":[{"text":"Sets the color of the date and time text.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/s:10Foundation8CalendarV":{"type":"topic","abstract":[{"type":"text","text":"A definition of the relationships between calendar units and absolute points in time, providing features for calculation and comparison of dates.   "}],"url":"/documentation/foundation/calendar","fragments":[{"text":"struct ","kind":"text"},{"text":"Calendar","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:10Foundation8CalendarV","title":"Calendar","role":"symbol"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate/setTimeZone(_:)":{"title":"setTimeZone(_:)","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate/setTimeZone(_:)","navigatorTitle":[{"kind":"identifier","text":"setTimeZone:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setTimeZone","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TimeZone","preciseIdentifier":"s:10Foundation8TimeZoneV"},{"kind":"text","text":"?)"}],"url":"/documentation/watchkit/wkinterfacedate/settimezone(_:)","abstract":[{"text":"Sets the time zone to use when displaying time information.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WKInterfaceDate","kind":"identifier"}],"navigatorTitle":[{"text":"WKInterfaceDate","kind":"identifier"}],"abstract":[{"text":"A label that displays the current date or time.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate","title":"WKInterfaceDate","url":"/documentation/watchkit/wkinterfacedate"},"doc://com.apple.watchkit/documentation/WatchKit":{"kind":"symbol","abstract":[{"type":"text","text":"Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions."}],"role":"collection","type":"topic","identifier":"doc://com.apple.watchkit/documentation/WatchKit","title":"WatchKit","url":"/documentation/watchkit"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate/setCalendar(_:)":{"title":"setCalendar(_:)","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate/setCalendar(_:)","navigatorTitle":[{"kind":"identifier","text":"setCalendar:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCalendar","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Calendar","preciseIdentifier":"s:10Foundation8CalendarV"},{"kind":"text","text":"?)"}],"url":"/documentation/watchkit/wkinterfacedate/setcalendar(_:)","abstract":[{"text":"Sets the calendar to use when formatting date information.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","abstract":[{"type":"text","text":""}],"role":"overview","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"unavailable":false,"name":"watchOS","deprecated":false,"introducedAt":"2.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"setCalendar:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"setCalendar:","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Configuring the Date and Time Display","generated":true,"anchor":"Configuring-the-Date-and-Time-Display","identifiers":["doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate/setTextColor(_:)","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceDate/setTimeZone(_:)"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["watchOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"setCalendar:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSCalendar","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCalendar"},{"text":" *) ","kind":"text"},{"text":"calendar","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"calendar","content":[{"inlineContent":[{"type":"text","text":"The calendar to be used. Specifying nil removes the calendar information and causes Apple Watch to use the default calendar based on the user’s settings."}],"type":"paragraph"}]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDate~1setTextColor(_:)/title","value":"setTextColor:"},{"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDate~1setTextColor(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTextColor:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDate~1setTimeZone(_:)/title","value":"setTimeZone:"},{"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDate~1setTimeZone(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTimeZone:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDate/title","value":"WKInterfaceDate"},{"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDate/fragments","value":[{"kind":"identifier","text":"WKInterfaceDate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDate/navigatorTitle","value":[{"text":"WKInterfaceDate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDate~1setCalendar(_:)/title","value":"setCalendar:"},{"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceDate~1setCalendar(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCalendar:"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}