{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/soundanalysis/snerror/code/unknownerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/soundanalysis/snerror/code/unknownerror"]}],"identifier":{"url":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/unknownError","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.soundanalysis/documentation/SoundAnalysis","doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError","doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"An error that represents a failure that no other error handles."}],"seeAlsoSections":[{"title":"Errors","identifiers":["doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidModel","doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFormat","doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFile","doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/operationFailed"],"anchor":"Errors","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Case","externalID":"c:@E@SNErrorCode@SNErrorCodeUnknownError","navigatorTitle":[{"kind":"identifier","text":"SNErrorCodeUnknownError"}],"title":"SNError.Code.unknownError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"modules":[{"name":"Sound Analysis"}],"platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"13.1","beta":false},{"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.15","beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false},{"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0","beta":false},{"name":"watchOS","deprecated":false,"unavailable":false,"introducedAt":"6.0","beta":false}],"role":"symbol","symbolKind":"case"},"references":{"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/unknownError":{"abstract":[{"text":"An error that represents a failure that no other error handles.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"navigatorTitle":[{"kind":"identifier","text":"SNErrorCodeUnknownError"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/unknownError","title":"SNError.Code.unknownError","url":"/documentation/soundanalysis/snerror/code/unknownerror"},"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFormat":{"kind":"symbol","navigatorTitle":[{"text":"SNErrorCodeInvalidFormat","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"An error that indicates the audio data’s format isn’t valid.","type":"text"}],"title":"SNError.Code.invalidFormat","identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFormat","url":"/documentation/soundanalysis/snerror/code/invalidformat","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidFormat","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","abstract":[{"text":"","type":"text"}],"kind":"technologies","title":"Technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic"},"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The enumerated error codes that the Sound Analysis framework produces.","type":"text"}],"kind":"symbol","title":"SNError.Code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"url":"/documentation/soundanalysis/snerror/code","identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code","type":"topic"},"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidModel":{"abstract":[{"text":"An error that indicates the sound classifier’s underlying Core ML model is an invalid model type.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidModel"}],"navigatorTitle":[{"kind":"identifier","text":"SNErrorCodeInvalidModel"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidModel","title":"SNError.Code.invalidModel","url":"/documentation/soundanalysis/snerror/code/invalidmodel"},"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFile":{"abstract":[{"text":"An error that indicates an audio file is invalid.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidFile"}],"navigatorTitle":[{"kind":"identifier","text":"SNErrorCodeInvalidFile"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFile","title":"SNError.Code.invalidFile","url":"/documentation/soundanalysis/snerror/code/invalidfile"},"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SNError","kind":"identifier"}],"role":"symbol","abstract":[{"text":"An error from the Sound Analysis framework.","type":"text"}],"kind":"symbol","title":"SNError","navigatorTitle":[{"text":"SNError","kind":"identifier"}],"url":"/documentation/soundanalysis/snerror","identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError","type":"topic"},"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/operationFailed":{"abstract":[{"text":"An error that occurs when the framework fails to analyze audio.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"operationFailed"}],"navigatorTitle":[{"kind":"identifier","text":"SNErrorCodeOperationFailed"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/operationFailed","title":"SNError.Code.operationFailed","url":"/documentation/soundanalysis/snerror/code/operationfailed"},"doc://com.apple.soundanalysis/documentation/SoundAnalysis":{"role":"collection","abstract":[{"text":"Classify various sounds by analyzing audio files or streams.","type":"text"}],"kind":"symbol","title":"Sound Analysis","url":"/documentation/soundanalysis","identifier":"doc://com.apple.soundanalysis/documentation/SoundAnalysis","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"watchOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"/metadata/title","value":"SNErrorCodeUnknownError","op":"replace"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"SNErrorCodeUnknownError"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.soundanalysis/documentation/SoundAnalysis","doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidModel","doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFormat","doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFile","doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/operationFailed"],"generated":true,"title":"Errors","anchor":"Errors"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SNErrorCodeUnknownError"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1unknownError/title","op":"replace","value":"SNErrorCodeUnknownError"},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1unknownError/fragments","op":"replace","value":[{"text":"SNErrorCodeUnknownError","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1invalidFormat/title","op":"replace","value":"SNErrorCodeInvalidFormat"},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1invalidFormat/fragments","op":"replace","value":[{"text":"SNErrorCodeInvalidFormat","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code/title","op":"replace","value":"SNErrorCode"},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code/fragments","op":"replace","value":[{"text":"SNErrorCode","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SNErrorCode"}]},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1invalidModel/title","op":"replace","value":"SNErrorCodeInvalidModel"},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1invalidModel/fragments","op":"replace","value":[{"kind":"identifier","text":"SNErrorCodeInvalidModel"}]},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1invalidFile/title","op":"replace","value":"SNErrorCodeInvalidFile"},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1invalidFile/fragments","op":"replace","value":[{"text":"SNErrorCodeInvalidFile","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1operationFailed/title","op":"replace","value":"SNErrorCodeOperationFailed"},{"path":"/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1operationFailed/fragments","op":"replace","value":[{"kind":"identifier","text":"SNErrorCodeOperationFailed"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}