{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSCollectionView/prefetchDataSource","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchDataSource","kind":"identifier"},{"text":": (any ","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching","preciseIdentifier":"c:objc(pl)NSCollectionViewPrefetching","text":"NSCollectionViewPrefetching","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"AppKit"}],"title":"prefetchDataSource","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefetchDataSource","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSCollectionViewPrefetching","text":"NSCollectionViewPrefetching","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"externalID":"c:objc(cs)NSCollectionView(py)prefetchDataSource","symbolKind":"property","navigatorTitle":[{"text":"prefetchDataSource","kind":"identifier"}],"roleHeading":"Instance Property","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"10.13","name":"macOS"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCollectionView"]]},"variants":[{"paths":["/documentation/appkit/nscollectionview/prefetchdatasource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nscollectionview/prefetchdatasource"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching"],"title":"Prefetching Collection View Cells and Data","anchor":"Prefetching-Collection-View-Cells-and-Data","generated":true}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSCollectionView/prefetchDataSource":{"title":"prefetchDataSource","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionView/prefetchDataSource","type":"topic","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchDataSource"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)NSCollectionViewPrefetching","kind":"typeIdentifier","text":"NSCollectionViewPrefetching"},{"kind":"text","text":")?"}],"navigatorTitle":[{"kind":"identifier","text":"prefetchDataSource"}],"url":"/documentation/appkit/nscollectionview/prefetchdatasource"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionView":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionView","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionView","navigatorTitle":[{"text":"NSCollectionView","kind":"identifier"}],"abstract":[{"type":"text","text":"An ordered collection of data items displayed in a customizable layout."}],"type":"topic","title":"NSCollectionView","url":"/documentation/appkit/nscollectionview"},"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching":{"title":"NSCollectionViewPrefetching","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching","type":"topic","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionViewPrefetching"}],"navigatorTitle":[{"kind":"identifier","text":"NSCollectionViewPrefetching"}],"url":"/documentation/appkit/nscollectionviewprefetching"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"beta":false,"introducedAt":"10.13","deprecated":false,"name":"macOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"prefetchDataSource","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"prefetchDataSource"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCollectionView"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCollectionViewPrefetching"],"anchor":"Prefetching-Collection-View-Cells-and-Data","generated":true,"title":"Prefetching Collection View Cells and Data"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qoobjc(pl)NSCollectionViewPrefetching","kind":"typeIdentifier","text":"id<NSCollectionViewPrefetching>"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchDataSource"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1prefetchDataSource/title","op":"replace","value":"prefetchDataSource"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView~1prefetchDataSource/fragments","op":"replace","value":[{"kind":"identifier","text":"prefetchDataSource"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/title","op":"replace","value":"NSCollectionView"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/fragments","op":"replace","value":[{"text":"NSCollectionView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/navigatorTitle","op":"replace","value":[{"text":"NSCollectionView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewPrefetching/title","op":"replace","value":"NSCollectionViewPrefetching"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewPrefetching/fragments","op":"replace","value":[{"kind":"identifier","text":"NSCollectionViewPrefetching"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewPrefetching/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSCollectionViewPrefetching"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}