{"kind":"symbol","abstract":[{"type":"text","text":"Creates a macOS stroke with the line properties, path, transform, mask, and random seed that you specify."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ink"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9PencilKit5PKInkV","text":"PKInk","identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct"},{"kind":"text","text":", "},{"kind":"externalParam","text":"path"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9PencilKit12PKStrokePathV","text":"PKStrokePath","identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePath-swift.struct"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGAffineTransform","text":"CGAffineTransform","identifier":"doc://com.externally.resolved.symbol/c:@S@CGAffineTransform"},{"kind":"text","text":" = .identity, "},{"kind":"externalParam","text":"mask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBezierPath","text":"NSBezierPath","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSBezierPath"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"randomSeed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32","identifier":"doc://com.externally.resolved.symbol/s:s6UInt32V"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"ink","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKInkReference","isActive":true},{"type":"text","text":" the framework uses to render this stroke."}]}]},{"name":"path","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The B-spline path that describes this stroke."}]}]},{"name":"transform","content":[{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/corefoundation/cgaffinetransform","type":"reference"},{"text":" to apply to this stroke. Defaults to ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/coregraphics/cgaffinetransformidentity","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"mask","content":[{"type":"paragraph","inlineContent":[{"text":"The pretransform mask the framework uses to clip the rendering of the stroke.","type":"text"}]}]},{"name":"randomSeed","content":[{"type":"paragraph","inlineContent":[{"text":"The random seed for the stroke.","type":"text"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct/init(ink:path:transform:mask:randomSeed:)-epus"},"variants":[{"paths":["/documentation/pencilkit/pkstroke-swift.struct/init(ink:path:transform:mask:randomseed:)-epus"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pencilkit/documentation/PencilKit","doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct"]]},"seeAlsoSections":[{"anchor":"Creating-a-stroke-object","identifiers":["doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct/init(ink:path:transform:mask:)-1imp6","doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct/init(ink:path:transform:mask:)-w7ti","doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct/init(ink:path:transform:mask:randomSeed:)-10m5j"],"title":"Creating a stroke object","generated":true}],"metadata":{"modules":[{"name":"PencilKit"}],"symbolKind":"init","externalID":"s:9PencilKit8PKStrokeV3ink4path9transform4mask10randomSeedAcA5PKInkV_AA0C4PathVSo17CGAffineTransformVSo08NSBezierK0CSgs6UInt32Vtcfc","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ink","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9PencilKit5PKInkV","text":"PKInk","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"path","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9PencilKit12PKStrokePathV","text":"PKStrokePath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGAffineTransform","text":"CGAffineTransform"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mask"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSBezierPath","kind":"typeIdentifier","text":"NSBezierPath"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"randomSeed"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"},{"text":")","kind":"text"}],"role":"symbol","title":"init(ink:path:transform:mask:randomSeed:)","platforms":[{"beta":false,"deprecated":false,"name":"iOS","introducedAt":"16.0","unavailable":false},{"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"16.0","unavailable":false},{"beta":false,"deprecated":false,"name":"macOS","introducedAt":"13.0","unavailable":false}]},"references":{"doc://com.apple.documentation/documentation/corefoundation/cgaffinetransform":{"abstract":[{"text":"An affine transformation matrix for use in drawing 2D graphics.","type":"text"}],"role":"symbol","url":"/documentation/corefoundation/cgaffinetransform","title":"CGAffineTransform","kind":"symbol","type":"topic","identifier":"doc://com.apple.documentation/documentation/corefoundation/cgaffinetransform","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"CGAffineTransform"}]},"doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct/init(ink:path:transform:mask:randomSeed:)-epus":{"abstract":[{"type":"text","text":"Creates a macOS stroke with the line properties, path, transform, mask, and random seed that you specify."}],"title":"init(ink:path:transform:mask:randomSeed:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ink"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9PencilKit5PKInkV","text":"PKInk"},{"kind":"text","text":", "},{"kind":"externalParam","text":"path"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9PencilKit12PKStrokePathV","text":"PKStrokePath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGAffineTransform","text":"CGAffineTransform"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBezierPath","text":"NSBezierPath"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"randomSeed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"kind":"text","text":")"}],"url":"/documentation/pencilkit/pkstroke-swift.struct/init(ink:path:transform:mask:randomseed:)-epus","role":"symbol","identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct/init(ink:path:transform:mask:randomSeed:)-epus"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","url":"/documentation/technologies","kind":"technologies","abstract":[{"text":"","type":"text"}],"title":"Technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.pencilkit/documentation/PencilKit":{"type":"topic","url":"/documentation/pencilkit","kind":"symbol","abstract":[{"type":"text","text":"Capture touch and Apple Pencil input as a drawing, and display that content from your app."}],"title":"PencilKit","role":"collection","identifier":"doc://com.apple.pencilkit/documentation/PencilKit"},"doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct":{"navigatorTitle":[{"kind":"identifier","text":"PKInk"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKInk"}],"title":"PKInk","kind":"symbol","abstract":[{"type":"text","text":"A structure that represents an ink that specifies its type, color, and width."}],"identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKInk-swift.struct","role":"symbol","url":"/documentation/pencilkit/pkink-swift.struct"},"doc://com.externally.resolved.symbol/s:s6UInt32V":{"type":"topic","url":"/documentation/Swift/UInt32","kind":"symbol","abstract":[{"text":"A 32-bit unsigned integer value type.","type":"text"}],"fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UInt32","kind":"identifier"}],"title":"UInt32","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s6UInt32V"},"doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePath-swift.struct":{"type":"topic","url":"/documentation/pencilkit/pkstrokepath-swift.struct","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PKStrokePath"}],"abstract":[{"text":"A structure that captures the components of a stroke and provides methods to find and interpolate points along the stroke’s path.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKStrokePath"}],"title":"PKStrokePath","role":"symbol","identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKStrokePath-swift.struct"},"doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct/init(ink:path:transform:mask:randomSeed:)-10m5j":{"title":"init(ink:path:transform:mask:randomSeed:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ink"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9PencilKit5PKInkV","text":"PKInk"},{"kind":"text","text":", "},{"kind":"externalParam","text":"path"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:9PencilKit12PKStrokePathV","text":"PKStrokePath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGAffineTransform","text":"CGAffineTransform"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"randomSeed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"kind":"text","text":")"}],"url":"/documentation/pencilkit/pkstroke-swift.struct/init(ink:path:transform:mask:randomseed:)-10m5j","abstract":[{"type":"text","text":"Creates a stroke with the line properties, path, transform, mask, and random seed that you specify."}],"identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct/init(ink:path:transform:mask:randomSeed:)-10m5j","type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSBezierPath":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSBezierPath"}],"title":"NSBezierPath","kind":"symbol","abstract":[{"type":"text","text":"An object that can create paths using PostScript-style commands."}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSBezierPath","role":"symbol","url":"/documentation/AppKit/NSBezierPath"},"doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct/init(ink:path:transform:mask:)-w7ti":{"title":"init(ink:path:transform:mask:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ink","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PKInk","preciseIdentifier":"s:9PencilKit5PKInkV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"path","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PKStrokePath","preciseIdentifier":"s:9PencilKit12PKStrokePathV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"transform","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGAffineTransform","preciseIdentifier":"c:@S@CGAffineTransform","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mask","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSBezierPath","preciseIdentifier":"c:objc(cs)NSBezierPath","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"/documentation/pencilkit/pkstroke-swift.struct/init(ink:path:transform:mask:)-w7ti","abstract":[{"type":"text","text":"Creates a stroke with the line properties, path, transform, and mask that you specify."}],"identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct/init(ink:path:transform:mask:)-w7ti","type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.pencilkit/documentation/PencilKit/PKInkReference":{"title":"PKInkReference","navigatorTitle":[{"kind":"identifier","text":"PKInkReference"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKInkReference"}],"url":"/documentation/pencilkit/pkinkreference","abstract":[{"type":"text","text":"Provides a description of the creation and rendering of marks on a canvas."}],"identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKInkReference","type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct":{"navigatorTitle":[{"kind":"identifier","text":"PKStroke"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PKStroke"}],"title":"PKStroke","kind":"symbol","abstract":[{"type":"text","text":"A structure that represents the paths, boundaries, and other properties of a stroke drawn on a canvas."}],"identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct","role":"symbol","url":"/documentation/pencilkit/pkstroke-swift.struct"},"doc://com.externally.resolved.symbol/c:@S@CGAffineTransform":{"type":"topic","fragments":[{"kind":"text","text":"struct "},{"text":"CGAffineTransform","kind":"identifier"}],"title":"CGAffineTransform","kind":"symbol","abstract":[{"type":"text","text":"An affine transformation matrix for use in drawing 2D graphics."}],"identifier":"doc://com.externally.resolved.symbol/c:@S@CGAffineTransform","role":"symbol","url":"/documentation/corefoundation/cgaffinetransform"},"doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct/init(ink:path:transform:mask:)-1imp6":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ink","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9PencilKit5PKInkV","text":"PKInk","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"path","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:9PencilKit12PKStrokePathV","text":"PKStrokePath","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"transform","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGAffineTransform","text":"CGAffineTransform","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mask","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","title":"init(ink:path:transform:mask:)","role":"symbol","abstract":[{"text":"Creates a stroke with the line properties, path, transform, and mask that you specify.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.pencilkit/documentation/PencilKit/PKStroke-swift.struct/init(ink:path:transform:mask:)-1imp6","url":"/documentation/pencilkit/pkstroke-swift.struct/init(ink:path:transform:mask:)-1imp6"},"doc://com.apple.documentation/documentation/coregraphics/cgaffinetransformidentity":{"type":"topic","url":"/documentation/coregraphics/cgaffinetransformidentity","kind":"symbol","abstract":[{"text":"The identity transform.","type":"text"}],"fragments":[{"text":"static var ","kind":"text"},{"text":"identity","kind":"identifier"},{"text":": CGAffineTransform","kind":"text"}],"title":"CGAffineTransformIdentity","role":"symbol","identifier":"doc://com.apple.documentation/documentation/coregraphics/cgaffinetransformidentity"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSBezierPath/fragments","op":"replace","value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSBezierPath","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]},{"path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkReference/title","op":"replace","value":"PKInk"},{"path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkReference/fragments","op":"replace","value":[{"kind":"identifier","text":"PKInk"}]},{"path":"/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKInkReference/navigatorTitle","op":"replace","value":[{"text":"PKInk","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}