{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/delegate","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/presentEditMenu(with:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/updateVisibleMenuPosition(animated:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/dismissMenu()","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/location(in:)"],"generated":true,"anchor":"Managing-edit-menu-interactions","title":"Managing edit menu interactions"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadVisibleMenu"},{"kind":"text","text":"()"}]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"Discussion","type":"heading"},{"inlineContent":[{"text":"You use this method to update the actions the menu displays. The method calls ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:menuFor:suggestedActions:)","type":"reference"},{"text":" and updates the UI with the menu the delegate returns. The method has no effect if no menu is present.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uieditmenuinteraction/reloadvisiblemenu()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uieditmenuinteraction/reloadvisiblemenu()"]}],"kind":"symbol","sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadVisibleMenu"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)UIEditMenuInteraction(im)reloadVisibleMenu","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"reloadVisibleMenu"}],"title":"reloadVisibleMenu()","modules":[{"name":"UIKit"}],"symbolKind":"method","platforms":[{"beta":false,"unavailable":false,"introducedAt":"16.0","name":"iOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"16.0","name":"iPadOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"16.0","name":"Mac Catalyst","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS","deprecated":false}]},"abstract":[{"text":"Updates the actions an edit menu displays.","type":"text"}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/reloadVisibleMenu()","interfaceLanguage":"swift"},"references":{"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/dismissMenu()":{"url":"/documentation/uikit/uieditmenuinteraction/dismissmenu()","abstract":[{"type":"text","text":"Dismiss the edit menu if present."}],"role":"symbol","navigatorTitle":[{"text":"dismissMenu","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/dismissMenu()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dismissMenu","kind":"identifier"},{"text":"()","kind":"text"}],"title":"dismissMenu()"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/location(in:)":{"url":"/documentation/uikit/uieditmenuinteraction/location(in:)","abstract":[{"type":"text","text":"Returns the location of the user interaction in the specified view’s coordinate system."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"locationInView:"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/location(in:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"location","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?) -> ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"title":"location(in:)"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:menuFor:suggestedActions:)":{"type":"topic","abstract":[{"text":"Provides the menu to use when the interaction begins or requires an update.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"editMenuInteraction:menuForConfiguration:suggestedActions:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:menuFor:suggestedActions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"editMenuInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIEditMenuInteraction","preciseIdentifier":"c:objc(cs)UIEditMenuInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"menuFor"},{"kind":"text","text":": "},{"text":"UIEditMenuConfiguration","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"suggestedActions","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIMenuElement","preciseIdentifier":"c:objc(cs)UIMenuElement","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"text":"UIMenu","preciseIdentifier":"c:objc(cs)UIMenu","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"/documentation/uikit/uieditmenuinteractiondelegate/editmenuinteraction(_:menufor:suggestedactions:)","title":"editMenuInteraction(_:menuFor:suggestedActions:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/reloadVisibleMenu()":{"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reloadVisibleMenu","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"reloadVisibleMenu","kind":"identifier"}],"url":"/documentation/uikit/uieditmenuinteraction/reloadvisiblemenu()","abstract":[{"text":"Updates the actions an edit menu displays.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/reloadVisibleMenu()","role":"symbol","title":"reloadVisibleMenu()"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/delegate":{"url":"/documentation/uikit/uieditmenuinteraction/delegate","abstract":[{"type":"text","text":"An object that customizes presentation of the menu and actions to display for an edit menu interaction."}],"role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/delegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIEditMenuInteractionDelegate","text":"UIEditMenuInteractionDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"title":"delegate"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/presentEditMenu(with:)":{"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentEditMenu","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEditMenuConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"presentEditMenuWithConfiguration:","kind":"identifier"}],"url":"/documentation/uikit/uieditmenuinteraction/presenteditmenu(with:)","abstract":[{"text":"Presents an edit menu using the object you provide for configuration.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/presentEditMenu(with:)","role":"symbol","title":"presentEditMenu(with:)"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/updateVisibleMenuPosition(animated:)":{"url":"/documentation/uikit/uieditmenuinteraction/updatevisiblemenuposition(animated:)","abstract":[{"type":"text","text":"Updates the position of the currently visible menu with an option to animate the action."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"updateVisibleMenuPositionAnimated:"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/updateVisibleMenuPosition(animated:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"updateVisibleMenuPosition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"title":"updateVisibleMenuPosition(animated:)"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction":{"navigatorTitle":[{"text":"UIEditMenuInteraction","kind":"identifier"}],"title":"UIEditMenuInteraction","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIEditMenuInteraction","kind":"identifier"}],"abstract":[{"type":"text","text":"An interaction that provides edit operations using a menu."}],"url":"/documentation/uikit/uieditmenuinteraction","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"unavailable":false,"introducedAt":"16.0","name":"iOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"16.0","name":"iPadOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"16.0","name":"Mac Catalyst","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS","deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"reloadVisibleMenu"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reloadVisibleMenu"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Managing edit menu interactions","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/delegate","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/presentEditMenu(with:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/updateVisibleMenuPosition(animated:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/dismissMenu()","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/location(in:)"],"anchor":"Managing-edit-menu-interactions"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"reloadVisibleMenu","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"dismissMenu","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1dismissMenu()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"dismissMenu","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1dismissMenu()/fragments"},{"value":"locationInView:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1location(in:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"locationInView:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1location(in:)/fragments"},{"value":"editMenuInteraction:menuForConfiguration:suggestedActions:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:menuFor:suggestedActions:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editMenuInteraction:menuForConfiguration:suggestedActions:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:menuFor:suggestedActions:)/fragments"},{"value":"reloadVisibleMenu","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1reloadVisibleMenu()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"reloadVisibleMenu","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1reloadVisibleMenu()/fragments"},{"value":"delegate","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1delegate/title"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1delegate/fragments"},{"value":"presentEditMenuWithConfiguration:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1presentEditMenu(with:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"presentEditMenuWithConfiguration:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1presentEditMenu(with:)/fragments"},{"value":"updateVisibleMenuPositionAnimated:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1updateVisibleMenuPosition(animated:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"updateVisibleMenuPositionAnimated:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1updateVisibleMenuPosition(animated:)/fragments"},{"value":"UIEditMenuInteraction","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction/title"},{"value":[{"text":"UIEditMenuInteraction","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction/fragments"},{"value":[{"text":"UIEditMenuInteraction","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}