{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction"]]},"metadata":{"platforms":[{"beta":false,"unavailable":false,"deprecated":false,"introducedAt":"16.0","name":"iOS"},{"beta":false,"unavailable":false,"deprecated":false,"introducedAt":"16.0","name":"iPadOS"},{"beta":false,"unavailable":false,"deprecated":false,"introducedAt":"16.0","name":"Mac Catalyst"},{"beta":false,"unavailable":false,"deprecated":false,"introducedAt":"1.0","name":"visionOS"}],"modules":[{"name":"UIKit"}],"title":"updateVisibleMenuPosition(animated:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateVisibleMenuPosition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)UIEditMenuInteraction(im)updateVisibleMenuPositionAnimated:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"updateVisibleMenuPositionAnimated:"}]},"abstract":[{"text":"Updates the position of the currently visible menu with an option to animate the action.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Managing edit menu interactions","anchor":"Managing-edit-menu-interactions","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/delegate","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/presentEditMenu(with:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/reloadVisibleMenu()","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/dismissMenu()","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/location(in:)"]}],"variants":[{"paths":["/documentation/uikit/uieditmenuinteraction/updatevisiblemenuposition(animated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uieditmenuinteraction/updatevisiblemenuposition(animated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateVisibleMenuPosition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"animated","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"YES"},{"text":" to animate the transition to the new position; ","type":"text"},{"type":"codeVoice","code":"NO"},{"text":" to make the transition immediate.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"Discussion","type":"heading"},{"inlineContent":[{"text":"You use this method to update the location of the menu. This method calls ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:targetRectFor:)","type":"reference","isActive":true},{"text":" and updates the position of the menu using the position the delegate returns. The method has no effect if no menu is present.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/updateVisibleMenuPosition(animated:)","interfaceLanguage":"swift"},"references":{"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/presentEditMenu(with:)":{"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentEditMenu","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEditMenuConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"presentEditMenuWithConfiguration:","kind":"identifier"}],"url":"/documentation/uikit/uieditmenuinteraction/presenteditmenu(with:)","abstract":[{"text":"Presents an edit menu using the object you provide for configuration.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/presentEditMenu(with:)","role":"symbol","title":"presentEditMenu(with:)"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/reloadVisibleMenu()":{"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reloadVisibleMenu","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"reloadVisibleMenu","kind":"identifier"}],"url":"/documentation/uikit/uieditmenuinteraction/reloadvisiblemenu()","abstract":[{"text":"Updates the actions an edit menu displays.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/reloadVisibleMenu()","role":"symbol","title":"reloadVisibleMenu()"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:targetRectFor:)":{"abstract":[{"text":"Provides the target rectangle to position the menu relative to when the interaction begins or requires an update.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"editMenuInteraction:targetRectForConfiguration:","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:targetRectFor:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"editMenuInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIEditMenuInteraction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuInteraction"},{"text":", ","kind":"text"},{"text":"targetRectFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEditMenuConfiguration","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/uikit/uieditmenuinteractiondelegate/editmenuinteraction(_:targetrectfor:)","title":"editMenuInteraction(_:targetRectFor:)"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/updateVisibleMenuPosition(animated:)":{"url":"/documentation/uikit/uieditmenuinteraction/updatevisiblemenuposition(animated:)","abstract":[{"type":"text","text":"Updates the position of the currently visible menu with an option to animate the action."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"updateVisibleMenuPositionAnimated:"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/updateVisibleMenuPosition(animated:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"updateVisibleMenuPosition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"title":"updateVisibleMenuPosition(animated:)"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction":{"navigatorTitle":[{"text":"UIEditMenuInteraction","kind":"identifier"}],"title":"UIEditMenuInteraction","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIEditMenuInteraction","kind":"identifier"}],"abstract":[{"type":"text","text":"An interaction that provides edit operations using a menu."}],"url":"/documentation/uikit/uieditmenuinteraction","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/delegate":{"url":"/documentation/uikit/uieditmenuinteraction/delegate","abstract":[{"type":"text","text":"An object that customizes presentation of the menu and actions to display for an edit menu interaction."}],"role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/delegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIEditMenuInteractionDelegate","text":"UIEditMenuInteractionDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"title":"delegate"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/dismissMenu()":{"url":"/documentation/uikit/uieditmenuinteraction/dismissmenu()","abstract":[{"type":"text","text":"Dismiss the edit menu if present."}],"role":"symbol","navigatorTitle":[{"text":"dismissMenu","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/dismissMenu()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dismissMenu","kind":"identifier"},{"text":"()","kind":"text"}],"title":"dismissMenu()"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/location(in:)":{"url":"/documentation/uikit/uieditmenuinteraction/location(in:)","abstract":[{"type":"text","text":"Returns the location of the user interaction in the specified view’s coordinate system."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"locationInView:"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/location(in:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"location","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?) -> ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"title":"location(in:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","deprecated":false,"introducedAt":"16.0","beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"introducedAt":"16.0","beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"16.0","beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"value":"updateVisibleMenuPositionAnimated:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateVisibleMenuPositionAnimated:"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/delegate","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/presentEditMenu(with:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/reloadVisibleMenu()","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/dismissMenu()","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/location(in:)"],"anchor":"Managing-edit-menu-interactions","generated":true,"title":"Managing edit menu interactions"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateVisibleMenuPositionAnimated:"},{"kind":"text","text":"("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"YES"},{"type":"text","text":" to animate the transition to the new position; "},{"type":"codeVoice","code":"NO"},{"type":"text","text":" to make the transition immediate."}],"type":"paragraph"}],"name":"animated"}]}},{"value":"presentEditMenuWithConfiguration:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1presentEditMenu(with:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"presentEditMenuWithConfiguration:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1presentEditMenu(with:)/fragments"},{"value":"reloadVisibleMenu","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1reloadVisibleMenu()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"reloadVisibleMenu","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1reloadVisibleMenu()/fragments"},{"value":"editMenuInteraction:targetRectForConfiguration:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:targetRectFor:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"editMenuInteraction:targetRectForConfiguration:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:targetRectFor:)/fragments"},{"value":"updateVisibleMenuPositionAnimated:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1updateVisibleMenuPosition(animated:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateVisibleMenuPositionAnimated:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1updateVisibleMenuPosition(animated:)/fragments"},{"value":"UIEditMenuInteraction","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction/title"},{"value":[{"kind":"identifier","text":"UIEditMenuInteraction"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction/fragments"},{"value":[{"text":"UIEditMenuInteraction","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction/navigatorTitle"},{"value":"delegate","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1delegate/title"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1delegate/fragments"},{"value":"dismissMenu","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1dismissMenu()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissMenu"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1dismissMenu()/fragments"},{"value":"locationInView:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1location(in:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"locationInView:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1location(in:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}