{
  "abstract": [
    {
      "text": "Provides actions in response to a Crash Detection event.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safetykit/documentation/SafetyKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SAEmergencyResponseManager",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SAEmergencyResponseManager"
      }
    ],
    "modules": [
      {
        "name": "SafetyKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SAEmergencyResponseManager"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SAEmergencyResponseManager"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManager"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the manager to place a voice call to an emergency contact upon receipt of a Crash Detection event. Provide an object that adopts ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in order to respond to the status of the voice call.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit": {
      "abstract": [
        {
          "text": "Detect and respond to car crash events in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SafetyKit",
      "type": "topic",
      "url": "/documentation/safetykit"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum": {
      "abstract": [
        {
          "text": "An enumeration that defines possible emergency responses to a Crash Detection event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Response"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Response"
        }
      ],
      "role": "symbol",
      "title": "SACrashDetectionEvent.Response",
      "type": "topic",
      "url": "/documentation/safetykit/sacrashdetectionevent/response-swift.enum"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseDelegate": {
      "abstract": [
        {
          "text": "The interface for receiving updates about a requested emergency response action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SAEmergencyResponseDelegate"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SAEmergencyResponseDelegate"
        }
      ],
      "role": "symbol",
      "title": "SAEmergencyResponseDelegate",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsedelegate"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager": {
      "abstract": [
        {
          "text": "Provides actions in response to a Crash Detection event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SAEmergencyResponseManager"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SAEmergencyResponseManager"
        }
      ],
      "role": "symbol",
      "title": "SAEmergencyResponseManager",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus": {
      "abstract": [
        {
          "text": "An enumeration that defines the status of a requested voice call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VoiceCallStatus"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VoiceCallStatus"
        }
      ],
      "role": "symbol",
      "title": "SAEmergencyResponseManager.VoiceCallStatus",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager/voicecallstatus"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/delegate": {
      "abstract": [
        {
          "text": "The object that receives voice call status updates and requested emergency response actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SAEmergencyResponseDelegate",
          "text": "SAEmergencyResponseDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager/delegate"
    },
    "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/dialVoiceCall(toPhoneNumber:completionHandler:)": {
      "abstract": [
        {
          "text": "Request the system to dial a voice call on behalf of someone involved in a crash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dialVoiceCall"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toPhoneNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/dialVoiceCall(toPhoneNumber:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dialVoiceCallToPhoneNumber:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "dialVoiceCall(toPhoneNumber:completionHandler:)",
      "type": "topic",
      "url": "/documentation/safetykit/saemergencyresponsemanager/dialvoicecall(tophonenumber:completionhandler:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-a-crash",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseDelegate",
        "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum"
      ],
      "title": "Responding to a crash"
    }
  ],
  "topicSections": [
    {
      "anchor": "Placing-a-voice-call",
      "identifiers": [
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus",
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/dialVoiceCall(toPhoneNumber:completionHandler:)",
        "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/delegate"
      ],
      "title": "Placing a voice call"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SAEmergencyResponseManager"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.safetykit/documentation/SafetyKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Placing-a-voice-call",
              "identifiers": [
                "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/VoiceCallStatus",
                "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/dialVoiceCall(toPhoneNumber:completionHandler:)",
                "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseManager/delegate"
              ],
              "title": "Placing a voice call"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-a-crash",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safetykit/documentation/SafetyKit/SAEmergencyResponseDelegate",
                "doc://com.apple.safetykit/documentation/SafetyKit/SACrashDetectionEvent/Response-swift.enum"
              ],
              "title": "Responding to a crash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SAEmergencyResponseManager"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager/title",
          "value": "SAEmergencyResponseManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1VoiceCallStatus/title",
          "value": "SAEmergencyResponseManagerVoiceCallStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1VoiceCallStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManagerVoiceCallStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1VoiceCallStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseManagerVoiceCallStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent~1Response-swift.enum/title",
          "value": "SACrashDetectionEventResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent~1Response-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionEventResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SACrashDetectionEvent~1Response-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SACrashDetectionEventResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseDelegate/title",
          "value": "SAEmergencyResponseDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SAEmergencyResponseDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1dialVoiceCall(toPhoneNumber:completionHandler:)/title",
          "value": "dialVoiceCallToPhoneNumber:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safetykit~1documentation~1SafetyKit~1SAEmergencyResponseManager~1dialVoiceCall(toPhoneNumber:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dialVoiceCallToPhoneNumber:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safetykit/saemergencyresponsemanager"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safetykit/saemergencyresponsemanager"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
