{
  "abstract": [
    {
      "text": "Returns information about your app’s authorization to access the user’s photo library.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/authorizationStatus(for:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/authorizationStatus()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHPhotoLibrary(cm)authorizationStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "authorizationStatus"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PHAuthorizationStatus",
        "text": "PHAuthorizationStatus"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "authorizationStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecatedAt": "14.0",
        "introducedAt": "8.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "deprecatedAt": "14.0",
        "introducedAt": "8.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.1",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.13",
        "name": "macOS"
      },
      {
        "beta": false,
        "deprecatedAt": "14.0",
        "introducedAt": "10.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "authorizationStatus()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "authorizationStatus"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PHAuthorizationStatus",
              "text": "PHAuthorizationStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The current authorization status.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.photokit/documentation/PhotoKit/delivering-an-enhanced-privacy-experience-in-your-photos-app"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotoKit/delivering-an-enhanced-privacy-experience-in-your-photos-app": {
      "abstract": [
        {
          "text": "Adopt the latest privacy enhancements to deliver advanced user-privacy controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotoKit/delivering-an-enhanced-privacy-experience-in-your-photos-app",
      "kind": "article",
      "role": "article",
      "title": "Delivering an Enhanced Privacy Experience in Your Photos App",
      "type": "topic",
      "url": "/documentation/photokit/delivering-an-enhanced-privacy-experience-in-your-photos-app"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAccessLevel": {
      "abstract": [
        {
          "text": "The app’s level of access to the user’s photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAccessLevel"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAccessLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAccessLevel"
        }
      ],
      "role": "symbol",
      "title": "PHAccessLevel",
      "type": "topic",
      "url": "/documentation/photos/phaccesslevel"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus": {
      "abstract": [
        {
          "text": "Information about your app’s authorization to access the user’s photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "PHAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/photos/phauthorizationstatus"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary": {
      "abstract": [
        {
          "text": "An object that manages access and changes to the user’s photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPhotoLibrary"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotoLibrary"
        }
      ],
      "role": "symbol",
      "title": "PHPhotoLibrary",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/authorizationStatus()": {
      "abstract": [
        {
          "text": "Returns information about your app’s authorization to access the user’s photo library.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAuthorizationStatus",
          "text": "PHAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/authorizationStatus()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "authorizationStatus()",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/authorizationstatus()"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/authorizationStatus(for:)": {
      "abstract": [
        {
          "text": "Returns the app’s authorization to access the user’s photo library for the specified access level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAccessLevel",
          "text": "PHAccessLevel"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAuthorizationStatus",
          "text": "PHAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/authorizationStatus(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationStatusForAccessLevel:"
        }
      ],
      "role": "symbol",
      "title": "authorizationStatus(for:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/authorizationstatus(for:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/requestAuthorization(_:)": {
      "abstract": [
        {
          "text": "Requests the user’s permission, if needed, to access the photo library.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAuthorization"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAuthorizationStatus",
          "text": "PHAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/requestAuthorization(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAuthorization:"
        }
      ],
      "role": "symbol",
      "title": "requestAuthorization(_:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/requestauthorization(_:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/requestAuthorization(for:handler:)": {
      "abstract": [
        {
          "text": "Prompts the user to grant the app permission to access the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAuthorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAccessLevel",
          "text": "PHAccessLevel"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAuthorizationStatus",
          "text": "PHAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/requestAuthorization(for:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAuthorizationForAccessLevel:handler:"
        }
      ],
      "role": "symbol",
      "title": "requestAuthorization(for:handler:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/requestauthorization(for:handler:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Verifying-Authorization",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/authorizationStatus(for:)",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/requestAuthorization(for:handler:)",
        "doc://com.apple.photokit/documentation/Photos/PHAccessLevel",
        "doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/requestAuthorization(_:)"
      ],
      "title": "Verifying Authorization"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "authorizationStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "authorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos",
                "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Verifying-Authorization",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/authorizationStatus(for:)",
                "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/requestAuthorization(for:handler:)",
                "doc://com.apple.photokit/documentation/Photos/PHAccessLevel",
                "doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus",
                "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/requestAuthorization(_:)"
              ],
              "title": "Verifying Authorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.apple.photokit/documentation/Photos/PHAuthorizationStatus",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@PHAuthorizationStatus",
                    "text": "PHAuthorizationStatus"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "authorizationStatus"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The current authorization status.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/authorizationStatus(for:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAccessLevel/title",
          "value": "PHAccessLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAccessLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAccessLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAccessLevel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAccessLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1authorizationStatus()/title",
          "value": "authorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1authorizationStatus()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "authorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1requestAuthorization(_:)/title",
          "value": "requestAuthorization:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1requestAuthorization(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestAuthorization:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1authorizationStatus(for:)/title",
          "value": "authorizationStatusForAccessLevel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1authorizationStatus(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "authorizationStatusForAccessLevel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1requestAuthorization(for:handler:)/title",
          "value": "requestAuthorizationForAccessLevel:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1requestAuthorization(for:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestAuthorizationForAccessLevel:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/title",
          "value": "PHPhotoLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotoLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotoLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus/title",
          "value": "PHAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAuthorizationStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phphotolibrary/authorizationstatus()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phphotolibrary/authorizationstatus()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
