{
  "abstract": [
    {
      "text": "Retrieves the local identifier mappings for the list of cloud identifiers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifierMappingsForCloudIdentifiers:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHPhotoLibrary(im)localIdentifierMappingsForCloudIdentifiers:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "localIdentifierMappingsForCloudIdentifiers:"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "localIdentifierMappingsForCloudIdentifiers:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "localIdentifierMappingsForCloudIdentifiers:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
              "text": "NSDictionary<PHCloudIdentifier *,PHLocalIdentifierMapping *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "localIdentifierMappingsForCloudIdentifiers:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<PHCloudIdentifier *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "cloudIdentifiers"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A list of cloud identifiers for which to retrieve local identifier mappings.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "cloudIdentifiers"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A dictionary that contains a map of cloud identifiers to their corresponding local mappings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Retrieving local identifiers can be an expensive operation, so perform this lookup sparingly. Instead, work with local identifiers and perform mapping work at load and save points. Then store and share the cloud identifiers to make them available on other devices.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the attempt to look up a local identifier fails, the error parameter indicates the reason.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifier": {
      "abstract": [
        {
          "text": "An object that identifies an asset or collection that syncs through iCloud Photos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHCloudIdentifier"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCloudIdentifier"
        }
      ],
      "role": "symbol",
      "title": "PHCloudIdentifier",
      "type": "topic",
      "url": "/documentation/photos/phcloudidentifier"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifierMapping": {
      "abstract": [
        {
          "text": "An object that contains the cloud identifier result from looking up a local identifier, or an error indicating why the lookup failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHCloudIdentifierMapping"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifierMapping",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHCloudIdentifierMapping",
      "type": "topic",
      "url": "/documentation/photos/phcloudidentifiermapping"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping": {
      "abstract": [
        {
          "text": "An object that contains the local identifier result from looking up a cloud identifier, or an error indicating why the lookup failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "PHLocalIdentifierMapping"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHLocalIdentifierMapping",
      "type": "topic",
      "url": "/documentation/photos/phlocalidentifiermapping"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierNotFound": {
      "abstract": [
        {
          "text": "A constant value that indicates that the system can’t resolve a local object from a global identifier.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLocalIdentifierNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLocalIdentifierNotFound"
        }
      ],
      "role": "symbol",
      "title": "PHLocalIdentifierNotFound",
      "type": "topic",
      "url": "/documentation/photos/phlocalidentifiernotfound"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary": {
      "abstract": [
        {
          "text": "An object that manages access and changes to the user’s photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPhotoLibrary"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHPhotoLibrary"
        }
      ],
      "role": "symbol",
      "title": "PHPhotoLibrary",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifierMappingsForLocalIdentifiers:": {
      "abstract": [
        {
          "text": "Retrieves the cloud identifier mappings for the list of local identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "cloudIdentifierMappingsForLocalIdentifiers:"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifierMappingsForLocalIdentifiers:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cloudIdentifierMappingsForLocalIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "cloudIdentifierMappingsForLocalIdentifiers:",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/cloudidentifiermappingsforlocalidentifiers:"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifiers(forLocalIdentifiers:)": {
      "abstract": [
        {
          "text": "Retrieves the equivalent iCloud identifiers for the list of local identifiers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudIdentifiers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLocalIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCloudIdentifier",
          "text": "PHCloudIdentifier"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifiers(forLocalIdentifiers:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cloudIdentifiersForLocalIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "cloudIdentifiers(forLocalIdentifiers:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/cloudidentifiers(forlocalidentifiers:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifierMappingsForCloudIdentifiers:": {
      "abstract": [
        {
          "text": "Retrieves the local identifier mappings for the list of cloud identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "localIdentifierMappingsForCloudIdentifiers:"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifierMappingsForCloudIdentifiers:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localIdentifierMappingsForCloudIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "localIdentifierMappingsForCloudIdentifiers:",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/localidentifiermappingsforcloudidentifiers:"
    },
    "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifiers(for:)": {
      "abstract": [
        {
          "text": "Retrieves the equivalent local identifiers for the list of iCloud identifiers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localIdentifiers"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHCloudIdentifier",
          "text": "PHCloudIdentifier"
        },
        {
          "kind": "text",
          "text": "]) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifiers(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localIdentifiersForCloudIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "localIdentifiers(for:)",
      "type": "topic",
      "url": "/documentation/photos/phphotolibrary/localidentifiers(for:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Converting-Between-Local-and-iCloud-Identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifierMappingsForLocalIdentifiers:",
        "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifier",
        "doc://com.apple.photokit/documentation/Photos/PHCloudIdentifierMapping",
        "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierMapping",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/cloudIdentifiers(forLocalIdentifiers:)",
        "doc://com.apple.photokit/documentation/Photos/PHPhotoLibrary/localIdentifiers(for:)",
        "doc://com.apple.photokit/documentation/Photos/PHLocalIdentifierNotFound"
      ],
      "title": "Converting Between Local and iCloud Identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLocalIdentifierNotFound/title",
          "value": "PHLocalIdentifierNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLocalIdentifierNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLocalIdentifierNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1cloudIdentifiers(forLocalIdentifiers:)/title",
          "value": "cloudIdentifiersForLocalIdentifiers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1cloudIdentifiers(forLocalIdentifiers:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cloudIdentifiersForLocalIdentifiers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/title",
          "value": "PHPhotoLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotoLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHPhotoLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1localIdentifiers(for:)/title",
          "value": "localIdentifiersForCloudIdentifiers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHPhotoLibrary~1localIdentifiers(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "localIdentifiersForCloudIdentifiers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCloudIdentifier/title",
          "value": "PHCloudIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCloudIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCloudIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCloudIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCloudIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phphotolibrary/localidentifiermappingsforcloudidentifiers:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
