{
  "abstract": [
    {
      "text": "Three signed 16-bit two’s complement values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short3"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLAttributeFormat@MTLAttributeFormatShort3",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "short3"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLAttributeFormatShort3"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLAttributeFormat.short3"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "short3"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat": {
      "abstract": [
        {
          "text": "Values indicating the organization and format of data for function attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAttributeFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormat"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short": {
      "abstract": [
        {
          "text": "One signed 16-bit two’s complement value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "short"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatShort"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.short",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/short"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short2": {
      "abstract": [
        {
          "text": "Two signed 16-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "short2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatShort2"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.short2",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/short2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short2Normalized": {
      "abstract": [
        {
          "text": "Two signed normalized 16-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "short2Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short2Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatShort2Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.short2Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/short2normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short3": {
      "abstract": [
        {
          "text": "Three signed 16-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "short3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatShort3"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.short3",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/short3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short3Normalized": {
      "abstract": [
        {
          "text": "Three signed normalized 16-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "short3Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short3Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatShort3Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.short3Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/short3normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short4": {
      "abstract": [
        {
          "text": "Four signed 16-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "short4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatShort4"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.short4",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/short4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short4Normalized": {
      "abstract": [
        {
          "text": "Four signed normalized 16-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "short4Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short4Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatShort4Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.short4Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/short4normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/shortNormalized": {
      "abstract": [
        {
          "text": "One signed normalized 16-bit two’s complement value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shortNormalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/shortNormalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatShortNormalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.shortNormalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/shortnormalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort": {
      "abstract": [
        {
          "text": "One unsigned 16-bit value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ushort"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUShort"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.ushort",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/ushort"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort2": {
      "abstract": [
        {
          "text": "Two unsigned 16-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ushort2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUShort2"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.ushort2",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/ushort2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort2Normalized": {
      "abstract": [
        {
          "text": "Two unsigned normalized 16-bit values",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ushort2Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort2Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUShort2Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.ushort2Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/ushort2normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort3": {
      "abstract": [
        {
          "text": "Three unsigned 16-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ushort3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUShort3"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.ushort3",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/ushort3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort3Normalized": {
      "abstract": [
        {
          "text": "Three unsigned normalized 16-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ushort3Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort3Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUShort3Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.ushort3Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/ushort3normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort4": {
      "abstract": [
        {
          "text": "Four unsigned 16-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ushort4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUShort4"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.ushort4",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/ushort4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort4Normalized": {
      "abstract": [
        {
          "text": "Four unsigned normalized 16-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ushort4Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort4Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUShort4Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.ushort4Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/ushort4normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushortNormalized": {
      "abstract": [
        {
          "text": "One unsigned normalized 16-bit value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ushortNormalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushortNormalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUShortNormalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.ushortNormalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/ushortnormalized"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "16-bit-integer-data-formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort2",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort3",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort4",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short2",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short4",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushortNormalized",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort2Normalized",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort3Normalized",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort4Normalized",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/shortNormalized",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short2Normalized",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short3Normalized",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short4Normalized"
      ],
      "title": "16- bit integer data formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLAttributeFormatShort3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatShort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "16-bit-integer-data-formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort2",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort3",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort4",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short2",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short4",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushortNormalized",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort2Normalized",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort3Normalized",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ushort4Normalized",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/shortNormalized",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short2Normalized",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short3Normalized",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/short4Normalized"
              ],
              "title": "16- bit integer data formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLAttributeFormatShort3"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1short2/title",
          "value": "MTLAttributeFormatShort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1short2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatShort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushort3Normalized/title",
          "value": "MTLAttributeFormatUShort3Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushort3Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUShort3Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushort/title",
          "value": "MTLAttributeFormatUShort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUShort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1short4Normalized/title",
          "value": "MTLAttributeFormatShort4Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1short4Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatShort4Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1short3/title",
          "value": "MTLAttributeFormatShort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1short3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatShort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushort3/title",
          "value": "MTLAttributeFormatUShort3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushort3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUShort3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushort4/title",
          "value": "MTLAttributeFormatUShort4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushort4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUShort4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushort2/title",
          "value": "MTLAttributeFormatUShort2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushort2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUShort2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1short/title",
          "value": "MTLAttributeFormatShort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1short/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatShort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat/title",
          "value": "MTLAttributeFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1short4/title",
          "value": "MTLAttributeFormatShort4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1short4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatShort4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1short3Normalized/title",
          "value": "MTLAttributeFormatShort3Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1short3Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatShort3Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushort4Normalized/title",
          "value": "MTLAttributeFormatUShort4Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushort4Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUShort4Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1shortNormalized/title",
          "value": "MTLAttributeFormatShortNormalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1shortNormalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatShortNormalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1short2Normalized/title",
          "value": "MTLAttributeFormatShort2Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1short2Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatShort2Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushortNormalized/title",
          "value": "MTLAttributeFormatUShortNormalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushortNormalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUShortNormalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushort2Normalized/title",
          "value": "MTLAttributeFormatUShort2Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ushort2Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUShort2Normalized"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlattributeformat/short3"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlattributeformat/short3"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
