{
  "abstract": [
    {
      "text": "Two unsigned normalized 8-bit values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar2Normalized"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLAttributeFormat@MTLAttributeFormatUChar2Normalized",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "uchar2Normalized"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLAttributeFormatUChar2Normalized"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLAttributeFormat.uchar2Normalized"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "uchar2Normalized"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat": {
      "abstract": [
        {
          "text": "Values indicating the organization and format of data for function attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAttributeFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormat"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char": {
      "abstract": [
        {
          "text": "One signed 8-bit two’s complement value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatChar"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.char",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/char"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char2": {
      "abstract": [
        {
          "text": "Two signed 8-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatChar2"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.char2",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/char2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char2Normalized": {
      "abstract": [
        {
          "text": "Two signed normalized 8-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char2Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char2Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatChar2Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.char2Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/char2normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char3": {
      "abstract": [
        {
          "text": "Three signed 8-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatChar3"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.char3",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/char3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char3Normalized": {
      "abstract": [
        {
          "text": "Three signed normalized 8-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char3Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char3Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatChar3Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.char3Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/char3normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char4": {
      "abstract": [
        {
          "text": "Four signed 8-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatChar4"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.char4",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/char4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char4Normalized": {
      "abstract": [
        {
          "text": "Four signed normalized 8-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char4Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char4Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatChar4Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.char4Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/char4normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/charNormalized": {
      "abstract": [
        {
          "text": "One signed normalized 8-bit two’s complement value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "charNormalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/charNormalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatCharNormalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.charNormalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/charnormalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar": {
      "abstract": [
        {
          "text": "One unsigned 8-bit value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUChar"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.uchar",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/uchar"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar2": {
      "abstract": [
        {
          "text": "Two unsigned 8-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUChar2"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.uchar2",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/uchar2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar2Normalized": {
      "abstract": [
        {
          "text": "Two unsigned normalized 8-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar2Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar2Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUChar2Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.uchar2Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/uchar2normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar3": {
      "abstract": [
        {
          "text": "Three unsigned 8-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUChar3"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.uchar3",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/uchar3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar3Normalized": {
      "abstract": [
        {
          "text": "Three unsigned normalized 8-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar3Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar3Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUChar3Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.uchar3Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/uchar3normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar4": {
      "abstract": [
        {
          "text": "Four unsigned 8-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUChar4"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.uchar4",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/uchar4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar4Normalized": {
      "abstract": [
        {
          "text": "Four unsigned normalized 8-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar4Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar4Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUChar4Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.uchar4Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/uchar4normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ucharNormalized": {
      "abstract": [
        {
          "text": "One unsigned normalized 8-bit value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ucharNormalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ucharNormalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUCharNormalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.ucharNormalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/ucharnormalized"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Character-data-formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar2",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar3",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar4",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char2",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char3",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char4",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ucharNormalized",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar3Normalized",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar4Normalized",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/charNormalized",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char2Normalized",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char3Normalized",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char4Normalized"
      ],
      "title": "Character data formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLAttributeFormatUChar2Normalized"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUChar2Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Character-data-formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar2",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar3",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar4",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char2",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char3",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char4",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/ucharNormalized",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar3Normalized",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uchar4Normalized",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/charNormalized",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char2Normalized",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char3Normalized",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/char4Normalized"
              ],
              "title": "Character data formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLAttributeFormatUChar2Normalized"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1char4Normalized/title",
          "value": "MTLAttributeFormatChar4Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1char4Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatChar4Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1char2Normalized/title",
          "value": "MTLAttributeFormatChar2Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1char2Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatChar2Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1char2/title",
          "value": "MTLAttributeFormatChar2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1char2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatChar2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1char4/title",
          "value": "MTLAttributeFormatChar4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1char4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatChar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uchar4Normalized/title",
          "value": "MTLAttributeFormatUChar4Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uchar4Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUChar4Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uchar3/title",
          "value": "MTLAttributeFormatUChar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uchar3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUChar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1charNormalized/title",
          "value": "MTLAttributeFormatCharNormalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1charNormalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatCharNormalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uchar3Normalized/title",
          "value": "MTLAttributeFormatUChar3Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uchar3Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUChar3Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1char3Normalized/title",
          "value": "MTLAttributeFormatChar3Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1char3Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatChar3Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uchar2Normalized/title",
          "value": "MTLAttributeFormatUChar2Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uchar2Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUChar2Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uchar/title",
          "value": "MTLAttributeFormatUChar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uchar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUChar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1char/title",
          "value": "MTLAttributeFormatChar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1char/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatChar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ucharNormalized/title",
          "value": "MTLAttributeFormatUCharNormalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1ucharNormalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUCharNormalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat/title",
          "value": "MTLAttributeFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uchar2/title",
          "value": "MTLAttributeFormatUChar2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uchar2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUChar2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1char3/title",
          "value": "MTLAttributeFormatChar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1char3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatChar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uchar4/title",
          "value": "MTLAttributeFormatUChar4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uchar4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUChar4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlattributeformat/uchar2normalized"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlattributeformat/uchar2normalized"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
