{
  "abstract": [
    {
      "text": "One packed 32-bit value with four normalized unsigned integer values, arranged as 10 bits, 10 bits, 10 bits, and 2 bits.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint1010102Normalized"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLAttributeFormat@MTLAttributeFormatUInt1010102Normalized",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "uint1010102Normalized"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLAttributeFormatUInt1010102Normalized"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLAttributeFormat.uint1010102Normalized"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "uint1010102Normalized"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat": {
      "abstract": [
        {
          "text": "Values indicating the organization and format of data for function attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAttributeFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormat"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int": {
      "abstract": [
        {
          "text": "One signed 32-bit two’s complement value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatInt"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.int",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/int"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int1010102Normalized": {
      "abstract": [
        {
          "text": "One packed 32-bit value with four normalized signed two’s complement integer values, arranged as 10 bits, 10 bits, 10 bits, and 2 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int1010102Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int1010102Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatInt1010102Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.int1010102Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/int1010102normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int2": {
      "abstract": [
        {
          "text": "Two signed 32-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatInt2"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.int2",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/int2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int3": {
      "abstract": [
        {
          "text": "Three signed 32-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatInt3"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.int3",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/int3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int4": {
      "abstract": [
        {
          "text": "Four signed 32-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatInt4"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.int4",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/int4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint": {
      "abstract": [
        {
          "text": "One unsigned 32-bit value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUInt"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.uint",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/uint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint1010102Normalized": {
      "abstract": [
        {
          "text": "One packed 32-bit value with four normalized unsigned integer values, arranged as 10 bits, 10 bits, 10 bits, and 2 bits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint1010102Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint1010102Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUInt1010102Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.uint1010102Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/uint1010102normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint2": {
      "abstract": [
        {
          "text": "Two unsigned 32-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUInt2"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.uint2",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/uint2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint3": {
      "abstract": [
        {
          "text": "Three unsigned 32-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUInt3"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.uint3",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/uint3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint4": {
      "abstract": [
        {
          "text": "Four unsigned 32-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAttributeFormatUInt4"
        }
      ],
      "role": "symbol",
      "title": "MTLAttributeFormat.uint4",
      "type": "topic",
      "url": "/documentation/metal/mtlattributeformat/uint4"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "32-bit-integer-data-formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint2",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint3",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint4",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int2",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int3",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int4",
        "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int1010102Normalized"
      ],
      "title": "32-bit integer data formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLAttributeFormatUInt1010102Normalized"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUInt1010102Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "32-bit-integer-data-formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint2",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint3",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/uint4",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int2",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int3",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int4",
                "doc://com.apple.metal/documentation/Metal/MTLAttributeFormat/int1010102Normalized"
              ],
              "title": "32-bit integer data formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLAttributeFormatUInt1010102Normalized"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uint2/title",
          "value": "MTLAttributeFormatUInt2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uint2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUInt2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1int3/title",
          "value": "MTLAttributeFormatInt3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1int3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatInt3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uint3/title",
          "value": "MTLAttributeFormatUInt3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uint3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUInt3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uint/title",
          "value": "MTLAttributeFormatUInt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUInt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat/title",
          "value": "MTLAttributeFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1int1010102Normalized/title",
          "value": "MTLAttributeFormatInt1010102Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1int1010102Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatInt1010102Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1int2/title",
          "value": "MTLAttributeFormatInt2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1int2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatInt2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uint1010102Normalized/title",
          "value": "MTLAttributeFormatUInt1010102Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uint1010102Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUInt1010102Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1int4/title",
          "value": "MTLAttributeFormatInt4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1int4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatInt4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1int/title",
          "value": "MTLAttributeFormatInt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1int/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatInt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uint4/title",
          "value": "MTLAttributeFormatUInt4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAttributeFormat~1uint4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAttributeFormatUInt4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlattributeformat/uint1010102normalized"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlattributeformat/uint1010102normalized"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
