{"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/view","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextDropProposal","doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"A performer type that indicates that the text view is responsible for doing the drop operation."}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/delegate"],"title":"Performers","anchor":"Performers"}],"metadata":{"role":"symbol","modules":[{"name":"UIKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"}],"roleHeading":"Case","symbolKind":"case","title":"UITextDropProposal.Performer.view","navigatorTitle":[{"kind":"identifier","text":"UITextDropPerformerView"}],"externalID":"c:@E@UITextDropPerformer@UITextDropPerformerView","platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"11.0","beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","beta":false},{"deprecated":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0","beta":false}]},"variants":[{"paths":["/documentation/uikit/uitextdropproposal/performer/view"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uitextdropproposal/performer/view"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"view","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This performer is the default for a "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal","isActive":true},{"type":"text","text":" object. If this performer is used, the "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:willPerformDrop:)","isActive":true},{"type":"text","text":" method is called (if implemented). However, implementing the delegate method isn’t required when using this performer."}]}]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/view":{"title":"UITextDropProposal.Performer.view","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/view","type":"topic","url":"/documentation/uikit/uitextdropproposal/performer/view","abstract":[{"type":"text","text":"A performer type that indicates that the text view is responsible for doing the drop operation."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextDropPerformerView"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDropProposal"}],"role":"symbol","abstract":[{"type":"text","text":"A proposed configuration for the behavior of a text drop interaction."}],"title":"UITextDropProposal","type":"topic","url":"/documentation/uikit/uitextdropproposal","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextDropProposal"}]},"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/delegate":{"title":"UITextDropProposal.Performer.delegate","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/delegate","type":"topic","url":"/documentation/uikit/uitextdropproposal/performer/delegate","abstract":[{"type":"text","text":"A performer type that indicates the delegate object is responsible for doing the drop operation."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextDropPerformerDelegate"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:willPerformDrop:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:willPerformDrop:)","navigatorTitle":[{"text":"textDroppableView:willPerformDrop:","kind":"identifier"}],"title":"textDroppableView(_:willPerformDrop:)","kind":"symbol","role":"symbol","url":"/documentation/uikit/uitextdropdelegate/textdroppableview(_:willperformdrop:)","abstract":[{"type":"text","text":"Tells the delegate that the drop operation is about to happen."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDroppableView"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"UITextDroppable","preciseIdentifier":"c:objc(pl)UITextDroppable"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willPerformDrop"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"UITextDropRequest","preciseIdentifier":"c:objc(pl)UITextDropRequest"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer":{"title":"UITextDropProposal.Performer","abstract":[{"type":"text","text":"The performers that are responsible for handling the drop operation."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer","url":"/documentation/uikit/uitextdropproposal/performer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Performer"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Performer","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"introducedAt":"11.0","name":"iOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"11.0","name":"iPadOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"1.0","name":"visionOS","beta":false,"deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"/metadata/title","value":"UITextDropPerformerView","op":"replace"},{"path":"/metadata/symbolKind","value":"case","op":"replace"},{"value":[{"text":"UITextDropPerformerView","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Performers","generated":true,"anchor":"Performers","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDropProposal/Performer/delegate"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"UITextDropPerformerView","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Performer~1view/title","value":"UITextDropPerformerView"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Performer~1view/fragments","op":"replace","value":[{"text":"UITextDropPerformerView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal/title","op":"replace","value":"UITextDropProposal"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal/fragments","op":"replace","value":[{"kind":"identifier","text":"UITextDropProposal"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UITextDropProposal"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Performer~1delegate/title","op":"replace","value":"UITextDropPerformerDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Performer~1delegate/fragments","op":"replace","value":[{"kind":"identifier","text":"UITextDropPerformerDelegate"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:willPerformDrop:)/title","op":"replace","value":"textDroppableView:willPerformDrop:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:willPerformDrop:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"textDroppableView:willPerformDrop:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Performer/title","op":"replace","value":"UITextDropPerformer"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Performer/fragments","op":"replace","value":[{"text":"UITextDropPerformer","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropProposal~1Performer/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UITextDropPerformer"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}