{
  "abstract": [
    {
      "text": "Returns an ",
      "type": "text"
    },
    {
      "code": "NSOpenGLPixelBuffer",
      "type": "codeVoice"
    },
    {
      "text": " object initialized with the specified parameters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer/initWithTextureTarget:textureInternalFormat:textureMaxMipMapLevel:pixelsWide:pixelsHigh:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSOpenGLPixelBuffer(im)initWithTextureTarget:textureInternalFormat:textureMaxMipMapLevel:pixelsWide:pixelsHigh:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "initWithTextureTarget:textureInternalFormat:textureMaxMipMapLevel:pixelsWide:pixelsHigh:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithTextureTarget:textureInternalFormat:textureMaxMipMapLevel:pixelsWide:pixelsHigh:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "initWithTextureTarget:textureInternalFormat:textureMaxMipMapLevel:pixelsWide:pixelsHigh:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithTextureTarget:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLenum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLenum",
              "text": "GLenum"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "target"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "textureInternalFormat:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLenum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLenum",
              "text": "GLenum"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "format"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "textureMaxMipMapLevel:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLint",
              "text": "GLint"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "maxLevel"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pixelsWide:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLsizei",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLsizei",
              "text": "GLsizei"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "pixelsWide"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pixelsHigh:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@GLsizei",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GLsizei",
              "text": "GLsizei"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "pixelsHigh"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The texture object. This value should be one of the following:  ",
                  "type": "text"
                },
                {
                  "code": "GL_TEXTURE_2D",
                  "type": "codeVoice"
                },
                {
                  "text": ",",
                  "type": "text"
                },
                {
                  "code": "GL_TEXTURE_CUBE_MAP",
                  "type": "codeVoice"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "code": "GL_TEXTURE_RECTANGLE_EXT",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "target"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The base internal format of the texture. This value should be ",
                  "type": "text"
                },
                {
                  "code": "GL_RGB",
                  "type": "codeVoice"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "code": "GL_RGBA",
                  "type": "codeVoice"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "code": "GL_DEPTH_COMPONENT",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "format"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The desired maximum mipmap level of the structure, starting with zero.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "maxLevel"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The width of the texture (in pixels) in the pixel buffer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pixelsWide"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The height of the texture (in pixels) in the pixel buffer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pixelsHigh"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An initialized ",
              "type": "text"
            },
            {
              "code": "NSOpenGLPixelBuffer",
              "type": "codeVoice"
            },
            {
              "text": " object or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the initialization failed. Initialization can fail if there is inconsistency among the parameter values. See the OpenGL documentation for ",
              "type": "text"
            },
            {
              "code": "glTexImage2D",
              "type": "codeVoice"
            },
            {
              "text": " for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value you pass to the ",
              "type": "text"
            },
            {
              "code": "target",
              "type": "codeVoice"
            },
            {
              "text": " parameter defines several other constraints that are then applied to the remaining parameters. The list below gives the values you can pass to ",
              "type": "text"
            },
            {
              "code": "target",
              "type": "codeVoice"
            },
            {
              "text": " and the additional constraints.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "GL_TEXTURE_2D",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "GL_TEXTURE_CUBE_MAP",
                      "type": "codeVoice"
                    },
                    {
                      "text": " - the values in ",
                      "type": "text"
                    },
                    {
                      "code": "pixelsWide",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "code": "pixelsHigh",
                      "type": "codeVoice"
                    },
                    {
                      "text": " must be equal.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "GL_TEXTURE_RECTANGLE_EXT",
                      "type": "codeVoice"
                    },
                    {
                      "text": " - ",
                      "type": "text"
                    },
                    {
                      "code": "maxLevel",
                      "type": "codeVoice"
                    },
                    {
                      "text": " must be zero.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Normally, when using the ",
              "type": "text"
            },
            {
              "code": "GL_TEXTURE_2D",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "GL_TEXTURE_CUBE_MAP",
              "type": "codeVoice"
            },
            {
              "text": " targets, you must specify width and height values that are powers of two. When the ",
              "type": "text"
            },
            {
              "code": "ARB_texture_non_power_of_two",
              "type": "codeVoice"
            },
            {
              "text": " extension is present, however, some types of hardware can support values that are not powers of two. You should check for the presence of this extension before specifying non power-of-two values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the texture map cannot be created, you can use the ",
              "type": "text"
            },
            {
              "code": "glGetError",
              "type": "codeVoice"
            },
            {
              "text": " function to get the error code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer": {
      "abstract": [
        {
          "text": "An object that provides access to accelerated offscreen rendering.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOpenGLPixelBuffer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOpenGLPixelBuffer",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglpixelbuffer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer/initWithCGLPBufferObj:": {
      "abstract": [
        {
          "text": "Initializes and returns an OpenGL pixel buffer object that encapsulates an existing CGL pixel buffer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithCGLPBufferObj:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer/initWithCGLPBufferObj:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCGLPBufferObj:"
        }
      ],
      "role": "symbol",
      "title": "initWithCGLPBufferObj:",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglpixelbuffer/initwithcglpbufferobj:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer/initWithTextureTarget:textureInternalFormat:textureMaxMipMapLevel:pixelsWide:pixelsHigh:": {
      "abstract": [
        {
          "text": "Returns an ",
          "type": "text"
        },
        {
          "code": "NSOpenGLPixelBuffer",
          "type": "codeVoice"
        },
        {
          "text": " object initialized with the specified parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTextureTarget:textureInternalFormat:textureMaxMipMapLevel:pixelsWide:pixelsHigh:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer/initWithTextureTarget:textureInternalFormat:textureMaxMipMapLevel:pixelsWide:pixelsHigh:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTextureTarget:textureInternalFormat:textureMaxMipMapLevel:pixelsWide:pixelsHigh:"
        }
      ],
      "role": "symbol",
      "title": "initWithTextureTarget:textureInternalFormat:textureMaxMipMapLevel:pixelsWide:pixelsHigh:",
      "type": "topic",
      "url": "/documentation/appkit/nsopenglpixelbuffer/initwithtexturetarget:textureinternalformat:texturemaxmipmaplevel:pixelswide:pixelshigh:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@GLenum": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLenum"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@GLenum",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLenum",
      "type": "topic",
      "url": "/documentation/OpenGLES/GLenum"
    },
    "doc://com.externally.resolved.symbol/c:@T@GLint": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLint"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@GLint",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLint",
      "type": "topic",
      "url": "/documentation/OpenGLES/GLint"
    },
    "doc://com.externally.resolved.symbol/c:@T@GLsizei": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLsizei"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@GLsizei",
      "kind": "symbol",
      "role": "symbol",
      "title": "GLsizei",
      "type": "topic",
      "url": "/documentation/OpenGLES/GLsizei"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290",
      "title": "Cocoa Drawing Guide",
      "titleInlineContent": [
        {
          "text": "Cocoa Drawing Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Initializing-an-OpenGL-Pixel-Buffer",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSOpenGLPixelBuffer/initWithCGLPBufferObj:"
      ],
      "title": "Initializing an OpenGL Pixel Buffer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@GLsizei/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@int32_t",
              "text": "int32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLsizei"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@GLint/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@int32_t",
              "text": "int32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLint"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@GLenum/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GLenum"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsopenglpixelbuffer/initwithtexturetarget:textureinternalformat:texturemaxmipmaplevel:pixelswide:pixelshigh:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
