{
  "abstract": [
    {
      "text": "An app category for dining.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/foodAndDrink"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SensorKit",
    "externalID": "c:@SRDeviceUsageCategoryFoodAndDrink",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "foodAndDrink"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
        "text": "SRDeviceUsageReport"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
        "text": "CategoryKey"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SRDeviceUsageCategoryFoodAndDrink"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "foodAndDrink"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "foodAndDrink"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
              "text": "SRDeviceUsageReport"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
              "text": "CategoryKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport": {
      "abstract": [
        {
          "text": "The frequency and relative duration that the user uses their device, particular Apple apps, or websites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRDeviceUsageReport"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageReport"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey": {
      "abstract": [
        {
          "text": "Categories of apps or websites that the user uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CategoryKey"
        }
      ],
      "role": "symbol",
      "title": "SRDeviceUsageReport.CategoryKey",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/books": {
      "abstract": [
        {
          "text": "An app category for reading books.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "books"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/books",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryBooks"
        }
      ],
      "role": "symbol",
      "title": "books",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/books"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/business": {
      "abstract": [
        {
          "text": "An app category for doing business.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "business"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/business",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryBusiness"
        }
      ],
      "role": "symbol",
      "title": "business",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/business"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/catalogs": {
      "abstract": [
        {
          "text": "An app category for reading catalogs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "catalogs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/catalogs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryCatalogs"
        }
      ],
      "role": "symbol",
      "title": "catalogs",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/catalogs"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/developerTools": {
      "abstract": [
        {
          "text": "An app category for creating apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "developerTools"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/developerTools",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryDeveloperTools"
        }
      ],
      "role": "symbol",
      "title": "developerTools",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/developertools"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/education": {
      "abstract": [
        {
          "text": "An app category for learning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "education"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/education",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryEducation"
        }
      ],
      "role": "symbol",
      "title": "education",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/education"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/entertainment": {
      "abstract": [
        {
          "text": "An app category for entertainment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entertainment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/entertainment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryEntertainment"
        }
      ],
      "role": "symbol",
      "title": "entertainment",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/entertainment"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/finance": {
      "abstract": [
        {
          "text": "An app category for finance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/finance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryFinance"
        }
      ],
      "role": "symbol",
      "title": "finance",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/finance"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/foodAndDrink": {
      "abstract": [
        {
          "text": "An app category for dining.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foodAndDrink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/foodAndDrink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryFoodAndDrink"
        }
      ],
      "role": "symbol",
      "title": "foodAndDrink",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/foodanddrink"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/games": {
      "abstract": [
        {
          "text": "An app category for gaming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "games"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/games",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryGames"
        }
      ],
      "role": "symbol",
      "title": "games",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/games"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/graphicsAndDesign": {
      "abstract": [
        {
          "text": "An app category for graphic design.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "graphicsAndDesign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/graphicsAndDesign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryGraphicsAndDesign"
        }
      ],
      "role": "symbol",
      "title": "graphicsAndDesign",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/graphicsanddesign"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/healthAndFitness": {
      "abstract": [
        {
          "text": "An app category for health and fitness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "healthAndFitness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/healthAndFitness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryHealthAndFitness"
        }
      ],
      "role": "symbol",
      "title": "healthAndFitness",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/healthandfitness"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/kids": {
      "abstract": [
        {
          "text": "An app category for children.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kids"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/kids",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryKids"
        }
      ],
      "role": "symbol",
      "title": "kids",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/kids"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/lifestyle": {
      "abstract": [
        {
          "text": "An app category for lifestyle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lifestyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/lifestyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryLifestyle"
        }
      ],
      "role": "symbol",
      "title": "lifestyle",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/lifestyle"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/medical": {
      "abstract": [
        {
          "text": "An app category for healthcare.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/medical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryMedical"
        }
      ],
      "role": "symbol",
      "title": "medical",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/medical"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/miscellaneous": {
      "abstract": [
        {
          "text": "An app category for miscellaneous apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "miscellaneous"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/miscellaneous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryMiscellaneous"
        }
      ],
      "role": "symbol",
      "title": "miscellaneous",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/miscellaneous"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/music": {
      "abstract": [
        {
          "text": "An app category for music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "music"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRDeviceUsageReport",
          "text": "SRDeviceUsageReport"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
          "text": "CategoryKey"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/music",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRDeviceUsageCategoryMusic"
        }
      ],
      "role": "symbol",
      "title": "music",
      "type": "topic",
      "url": "/documentation/sensorkit/srdeviceusagereport/categorykey/music"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Categories",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/books",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/business",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/catalogs",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/developerTools",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/education",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/entertainment",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/finance",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/games",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/graphicsAndDesign",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/healthAndFitness",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/kids",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/lifestyle",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/medical",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/miscellaneous",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/music"
      ],
      "title": "Categories"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SRDeviceUsageCategoryFoodAndDrink"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryFoodAndDrink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Categories",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/books",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/business",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/catalogs",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/developerTools",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/education",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/entertainment",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/finance",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/games",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/graphicsAndDesign",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/healthAndFitness",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/kids",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/lifestyle",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/medical",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/miscellaneous",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey/music"
              ],
              "title": "Categories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport/CategoryKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SRDeviceUsageCategoryKey",
                    "text": "SRDeviceUsageCategoryKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SRDeviceUsageCategoryFoodAndDrink"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1medical/title",
          "value": "SRDeviceUsageCategoryMedical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1medical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryMedical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1entertainment/title",
          "value": "SRDeviceUsageCategoryEntertainment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1entertainment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryEntertainment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1healthAndFitness/title",
          "value": "SRDeviceUsageCategoryHealthAndFitness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1healthAndFitness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryHealthAndFitness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1books/title",
          "value": "SRDeviceUsageCategoryBooks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1books/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryBooks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/title",
          "value": "SRDeviceUsageReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1foodAndDrink/title",
          "value": "SRDeviceUsageCategoryFoodAndDrink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1foodAndDrink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryFoodAndDrink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1education/title",
          "value": "SRDeviceUsageCategoryEducation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1education/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryEducation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1games/title",
          "value": "SRDeviceUsageCategoryGames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1games/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryGames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1music/title",
          "value": "SRDeviceUsageCategoryMusic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1music/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryMusic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey/title",
          "value": "SRDeviceUsageCategoryKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1developerTools/title",
          "value": "SRDeviceUsageCategoryDeveloperTools"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1developerTools/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryDeveloperTools"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1catalogs/title",
          "value": "SRDeviceUsageCategoryCatalogs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1catalogs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryCatalogs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1lifestyle/title",
          "value": "SRDeviceUsageCategoryLifestyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1lifestyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryLifestyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1miscellaneous/title",
          "value": "SRDeviceUsageCategoryMiscellaneous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1miscellaneous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryMiscellaneous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1graphicsAndDesign/title",
          "value": "SRDeviceUsageCategoryGraphicsAndDesign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1graphicsAndDesign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryGraphicsAndDesign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1kids/title",
          "value": "SRDeviceUsageCategoryKids"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1kids/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryKids"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1finance/title",
          "value": "SRDeviceUsageCategoryFinance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1finance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryFinance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1business/title",
          "value": "SRDeviceUsageCategoryBusiness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport~1CategoryKey~1business/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRDeviceUsageCategoryBusiness"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srdeviceusagereport/categorykey/foodanddrink"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srdeviceusagereport/categorykey/foodanddrink"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
