{
  "abstract": [
    {
      "text": "The transmitting device’s calibration confidence.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ENCalibrationConfidence",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ENCalibrationConfidence"
      }
    ],
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ENCalibrationConfidence"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ENCalibrationConfidence"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ENCalibrationConfidence"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This property is available in iOS 12.5, and in iOS 13.7 and later.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENActivityFlags": {
      "abstract": [
        {
          "text": "Activities that occur while the app isn’t running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENActivityFlags"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENActivityFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENActivityFlags"
        }
      ],
      "role": "symbol",
      "title": "ENActivityFlags",
      "type": "topic",
      "url": "/documentation/exposurenotification/enactivityflags"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence": {
      "abstract": [
        {
          "text": "The transmitting device’s calibration confidence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENCalibrationConfidence"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENCalibrationConfidence"
        }
      ],
      "role": "symbol",
      "title": "ENCalibrationConfidence",
      "type": "topic",
      "url": "/documentation/exposurenotification/encalibrationconfidence"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/high": {
      "abstract": [
        {
          "text": "The highest confidence in the calibration data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENCalibrationConfidenceHigh"
        }
      ],
      "role": "symbol",
      "title": "ENCalibrationConfidence.high",
      "type": "topic",
      "url": "/documentation/exposurenotification/encalibrationconfidence/high"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/exposurenotification/encalibrationconfidence/init(rawvalue:)"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/low": {
      "abstract": [
        {
          "text": "The average confidence in the calibration data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "low"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENCalibrationConfidenceLow"
        }
      ],
      "role": "symbol",
      "title": "ENCalibrationConfidence.low",
      "type": "topic",
      "url": "/documentation/exposurenotification/encalibrationconfidence/low"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/lowest": {
      "abstract": [
        {
          "text": "No confidence in the calibration data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lowest"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/lowest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENCalibrationConfidenceLowest"
        }
      ],
      "role": "symbol",
      "title": "ENCalibrationConfidence.lowest",
      "type": "topic",
      "url": "/documentation/exposurenotification/encalibrationconfidence/lowest"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/medium": {
      "abstract": [
        {
          "text": "The medium confidence in the calibration data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENCalibrationConfidenceMedium"
        }
      ],
      "role": "symbol",
      "title": "ENCalibrationConfidence.medium",
      "type": "topic",
      "url": "/documentation/exposurenotification/encalibrationconfidence/medium"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType": {
      "abstract": [
        {
          "text": "The type of a report that describes the origin of a diagnosis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENDiagnosisReportType"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENDiagnosisReportType"
        }
      ],
      "role": "symbol",
      "title": "ENDiagnosisReportType",
      "type": "topic",
      "url": "/documentation/exposurenotification/endiagnosisreporttype"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness": {
      "abstract": [
        {
          "text": "The degree to which a person’s symptoms may indicate transmission risk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENInfectiousness"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENInfectiousness"
        }
      ],
      "role": "symbol",
      "title": "ENInfectiousness",
      "type": "topic",
      "url": "/documentation/exposurenotification/eninfectiousness"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/attenuation": {
      "abstract": [
        {
          "text": "The minimum and maximum signal attenuations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/attenuation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Attenuation",
      "type": "topic",
      "url": "/documentation/exposurenotification/attenuation"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level": {
      "abstract": [
        {
          "text": "The minimum and maximum risk levels.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Risk Level",
      "type": "topic",
      "url": "/documentation/exposurenotification/risk-level"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level-value": {
      "abstract": [
        {
          "text": "The minimum and maximum risk level values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level-value",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Risk Level Value",
      "type": "topic",
      "url": "/documentation/exposurenotification/risk-level-value"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-score": {
      "abstract": [
        {
          "text": "The minimum and maximum risk score.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-score",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Risk Score",
      "type": "topic",
      "url": "/documentation/exposurenotification/risk-score"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-weight": {
      "abstract": [
        {
          "text": "The minimum, default, and maximum risk weights.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-weight",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Risk Weight",
      "type": "topic",
      "url": "/documentation/exposurenotification/risk-weight"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/attenuation",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level-value",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-score",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-weight",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENActivityFlags",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/high",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/medium",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/low",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/lowest"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ENCalibrationConfidence"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENCalibrationConfidence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENCalibrationConfidence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/high",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/medium",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/low",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence/lowest"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENActivityFlags",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ENCalibrationConfidence"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENActivityFlags/title",
          "value": "ENActivityFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENActivityFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENActivityFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENActivityFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENActivityFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence~1high/title",
          "value": "ENCalibrationConfidenceHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENCalibrationConfidenceHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence~1medium/title",
          "value": "ENCalibrationConfidenceMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENCalibrationConfidenceMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENInfectiousness/title",
          "value": "ENInfectiousness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENInfectiousness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENInfectiousness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENInfectiousness/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENInfectiousness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence~1lowest/title",
          "value": "ENCalibrationConfidenceLowest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence~1lowest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENCalibrationConfidenceLowest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence~1low/title",
          "value": "ENCalibrationConfidenceLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence~1low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENCalibrationConfidenceLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence/title",
          "value": "ENCalibrationConfidence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENCalibrationConfidence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENCalibrationConfidence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType/title",
          "value": "ENDiagnosisReportType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDiagnosisReportType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDiagnosisReportType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/encalibrationconfidence"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification/encalibrationconfidence"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
