{
  "abstract": [
    {
      "text": "The incident information related to a potential exposure.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ENExposureInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ENExposureInfo"
      }
    ],
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ENExposureInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ENExposureInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ENExposureInfo"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This class is available in iOS 12.5, and in iOS 13.5 and later. It isn’t supported for apps with ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " set to ",
                  "type": "text"
                },
                {
                  "code": "2",
                  "type": "codeVoice"
                },
                {
                  "text": " in the ",
                  "type": "text"
                },
                {
                  "code": "Info.plist",
                  "type": "codeVoice"
                },
                {
                  "text": " file. Instead, ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/getExposureWindows(summary:completionHandler:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " provides an array of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " objects.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "This class carries information about an exposure incident.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion": {
      "abstract": [
        {
          "text": "A number that specifies the version of the API to use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "ENAPIVersion",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/ENAPIVersion"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENAttenuation": {
      "abstract": [
        {
          "text": "The signal strength value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENAttenuation"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENAttenuation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENAttenuation"
        }
      ],
      "role": "symbol",
      "title": "ENAttenuation",
      "type": "topic",
      "url": "/documentation/exposurenotification/enattenuation"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDaysSinceOnsetOfSymptomsUnknown": {
      "abstract": [
        {
          "text": "A value used when the number of days since onset of symptoms is unknown.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENDaysSinceOnsetOfSymptomsUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDaysSinceOnsetOfSymptomsUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENDaysSinceOnsetOfSymptomsUnknown"
        }
      ],
      "role": "symbol",
      "title": "ENDaysSinceOnsetOfSymptomsUnknown",
      "type": "topic",
      "url": "/documentation/exposurenotification/endayssinceonsetofsymptomsunknown"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo": {
      "abstract": [
        {
          "text": "The incident information related to a potential exposure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureInfo"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureInfo"
        }
      ],
      "role": "symbol",
      "title": "ENExposureInfo",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/attenuationDurations": {
      "abstract": [
        {
          "text": "An array of durations at specific radio signal attenuations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attenuationDurations"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/attenuationDurations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attenuationDurations"
        }
      ],
      "role": "symbol",
      "title": "attenuationDurations",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/attenuationdurations"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/attenuationValue": {
      "abstract": [
        {
          "text": "The attenutation risk level value for the exposure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attenuationValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ENAttenuation",
          "text": "ENAttenuation"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/attenuationValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attenuationValue"
        }
      ],
      "role": "symbol",
      "title": "attenuationValue",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/attenuationvalue"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/date": {
      "abstract": [
        {
          "text": "The date the exposure occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "date"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/date",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "date"
        }
      ],
      "role": "symbol",
      "title": "date",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/date"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/daysSinceOnsetOfSymptoms": {
      "abstract": [
        {
          "text": "The number of days since the onset of symptoms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "daysSinceOnsetOfSymptoms"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/daysSinceOnsetOfSymptoms",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "daysSinceOnsetOfSymptoms"
        }
      ],
      "role": "symbol",
      "title": "daysSinceOnsetOfSymptoms",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/dayssinceonsetofsymptoms"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/diagnosisReportType": {
      "abstract": [
        {
          "text": "The method used to report the positive diagnosis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "diagnosisReportType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENDiagnosisReportType",
          "text": "ENDiagnosisReportType"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/diagnosisReportType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "diagnosisReportType"
        }
      ],
      "role": "symbol",
      "title": "diagnosisReportType",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/diagnosisreporttype"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/duration": {
      "abstract": [
        {
          "text": "The length of time that the contact was in proximity to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/duration"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/metadata": {
      "abstract": [
        {
          "text": "The metadata associated with the exposure information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadata"
        }
      ],
      "role": "symbol",
      "title": "metadata",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/metadata"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScore": {
      "abstract": [
        {
          "text": "The value that represents the total risk score the framework calculates for this exposure incident.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalRiskScore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ENRiskScore",
          "text": "ENRiskScore"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalRiskScore"
        }
      ],
      "role": "symbol",
      "title": "totalRiskScore",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/totalriskscore"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScoreFullRange": {
      "abstract": [
        {
          "text": "The value that represents the full-range total risk score the framework calculates for this exposure incident.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalRiskScoreFullRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScoreFullRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalRiskScoreFullRange"
        }
      ],
      "role": "symbol",
      "title": "totalRiskScoreFullRange",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/totalriskscorefullrange"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/transmissionRiskLevel": {
      "abstract": [
        {
          "text": "The transmission risk associated with a diagnosis key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transmissionRiskLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ENRiskLevel",
          "text": "ENRiskLevel"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/transmissionRiskLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transmissionRiskLevel"
        }
      ],
      "role": "symbol",
      "title": "transmissionRiskLevel",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureinfo/transmissionrisklevel"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow": {
      "abstract": [
        {
          "text": "A set of scan events from observed beacons within a time span.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureWindow"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureWindow"
        }
      ],
      "role": "symbol",
      "title": "ENExposureWindow",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposurewindow"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/getExposureWindows(summary:completionHandler:)": {
      "abstract": [
        {
          "text": "Obtains information from the provided summary about the user’s exposure within a window of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getExposureWindows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "summary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ENExposureDetectionSummary",
          "text": "ENExposureDetectionSummary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ENGetExposureWindowsHandler",
          "text": "ENGetExposureWindowsHandler"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSProgress",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager/getExposureWindows(summary:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getExposureWindowsFromSummary:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "getExposureWindows(summary:completionHandler:)",
      "type": "topic",
      "url": "/documentation/exposurenotification/enmanager/getexposurewindows(summary:completionhandler:)"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskLevel": {
      "abstract": [
        {
          "text": "The user’s estimated risk of exposure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENRiskLevel"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENRiskLevel"
        }
      ],
      "role": "symbol",
      "title": "ENRiskLevel",
      "type": "topic",
      "url": "/documentation/exposurenotification/enrisklevel"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskLevelValue": {
      "abstract": [
        {
          "text": "The value associated with a particular risk level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENRiskLevelValue"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskLevelValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENRiskLevelValue"
        }
      ],
      "role": "symbol",
      "title": "ENRiskLevelValue",
      "type": "topic",
      "url": "/documentation/exposurenotification/enrisklevelvalue"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskScore": {
      "abstract": [
        {
          "text": "A value signifying the risk of an exposure event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENRiskScore"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskScore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENRiskScore"
        }
      ],
      "role": "symbol",
      "title": "ENRiskScore",
      "type": "topic",
      "url": "/documentation/exposurenotification/enriskscore"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Exposure-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskScore",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskLevel",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskLevelValue"
      ],
      "title": "Exposure Information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Exposure-Criteria",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/attenuationDurations",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/attenuationValue",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/date",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/duration",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScore",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScoreFullRange",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/transmissionRiskLevel",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENAttenuation",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/metadata",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/daysSinceOnsetOfSymptoms",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/diagnosisReportType",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDaysSinceOnsetOfSymptomsUnknown"
      ],
      "title": "Exposure Criteria"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ENExposureInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Exposure-Criteria",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/attenuationDurations",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/attenuationValue",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/date",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/duration",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScore",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/totalRiskScoreFullRange",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/transmissionRiskLevel",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENAttenuation",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/metadata",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/daysSinceOnsetOfSymptoms",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureInfo/diagnosisReportType",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDaysSinceOnsetOfSymptomsUnknown"
              ],
              "title": "Exposure Criteria"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Exposure-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskScore",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskLevel",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskLevelValue"
              ],
              "title": "Exposure Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ENExposureInfo"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENAttenuation/title",
          "value": "ENAttenuation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENAttenuation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENAttenuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENAttenuation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENAttenuation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1diagnosisReportType/title",
          "value": "diagnosisReportType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1diagnosisReportType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "diagnosisReportType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1date/title",
          "value": "date"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1date/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "date"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1daysSinceOnsetOfSymptoms/title",
          "value": "daysSinceOnsetOfSymptoms"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1daysSinceOnsetOfSymptoms/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "daysSinceOnsetOfSymptoms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1duration/title",
          "value": "duration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1attenuationDurations/title",
          "value": "attenuationDurations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1attenuationDurations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attenuationDurations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1metadata/title",
          "value": "metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskLevelValue/title",
          "value": "ENRiskLevelValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskLevelValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENRiskLevelValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskLevelValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENRiskLevelValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1transmissionRiskLevel/title",
          "value": "transmissionRiskLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1transmissionRiskLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transmissionRiskLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1totalRiskScore/title",
          "value": "totalRiskScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1totalRiskScore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalRiskScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1totalRiskScoreFullRange/title",
          "value": "totalRiskScoreFullRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1totalRiskScoreFullRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalRiskScoreFullRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDaysSinceOnsetOfSymptomsUnknown/title",
          "value": "ENDaysSinceOnsetOfSymptomsUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDaysSinceOnsetOfSymptomsUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDaysSinceOnsetOfSymptomsUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1attenuationValue/title",
          "value": "attenuationValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo~1attenuationValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attenuationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskLevel/title",
          "value": "ENRiskLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENRiskLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskLevel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENRiskLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo/title",
          "value": "ENExposureInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskScore/title",
          "value": "ENRiskScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskScore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENRiskScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskScore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENRiskScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow/title",
          "value": "ENExposureWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager~1getExposureWindows(summary:completionHandler:)/title",
          "value": "getExposureWindowsFromSummary:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager~1getExposureWindows(summary:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getExposureWindowsFromSummary:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/enexposureinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification/enexposureinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
