{
  "abstract": [
    {
      "text": "A summary of exposures.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ENExposureDetectionSummary",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ENExposureDetectionSummary"
      }
    ],
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ENExposureDetectionSummary"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ENExposureDetectionSummary"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ENExposureDetectionSummary"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This class is available in iOS 12.5, and in iOS 13.5 and later.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDaySummary": {
      "abstract": [
        {
          "text": "The summary of exposure information for a single day.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureDaySummary"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDaySummary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureDaySummary"
        }
      ],
      "role": "symbol",
      "title": "ENExposureDaySummary",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposuredaysummary"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary": {
      "abstract": [
        {
          "text": "A summary of exposures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureDetectionSummary"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureDetectionSummary"
        }
      ],
      "role": "symbol",
      "title": "ENExposureDetectionSummary",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposuredetectionsummary"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/attenuationDurations": {
      "abstract": [
        {
          "text": "An array of durations at specific radio signal attenuations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attenuationDurations"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/attenuationDurations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attenuationDurations"
        }
      ],
      "role": "symbol",
      "title": "attenuationDurations",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposuredetectionsummary/attenuationdurations"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/daySummaries": {
      "abstract": [
        {
          "text": "The summary of each day that contains an exposure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "daySummaries"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ENExposureDaySummary",
          "text": "ENExposureDaySummary"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/daySummaries",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "daySummaries"
        }
      ],
      "role": "symbol",
      "title": "daySummaries",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposuredetectionsummary/daysummaries"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/daysSinceLastExposure": {
      "abstract": [
        {
          "text": "Number of days since the most recent exposure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "daysSinceLastExposure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/daysSinceLastExposure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "daysSinceLastExposure"
        }
      ],
      "role": "symbol",
      "title": "daysSinceLastExposure",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposuredetectionsummary/dayssincelastexposure"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/matchedKeyCount": {
      "abstract": [
        {
          "text": "The number of keys that matched for an exposure detection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchedKeyCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/matchedKeyCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchedKeyCount"
        }
      ],
      "role": "symbol",
      "title": "matchedKeyCount",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposuredetectionsummary/matchedkeycount"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/maximumRiskScore": {
      "abstract": [
        {
          "text": "The vaue that represents the highest risk score of all exposure incidents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumRiskScore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ENRiskScore",
          "text": "ENRiskScore"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/maximumRiskScore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumRiskScore"
        }
      ],
      "role": "symbol",
      "title": "maximumRiskScore",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposuredetectionsummary/maximumriskscore"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/maximumRiskScoreFullRange": {
      "abstract": [
        {
          "text": "The value that represents the highest, full-range risk score of all the exposures for the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumRiskScoreFullRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/maximumRiskScoreFullRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumRiskScoreFullRange"
        }
      ],
      "role": "symbol",
      "title": "maximumRiskScoreFullRange",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposuredetectionsummary/maximumriskscorefullrange"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/metadata": {
      "abstract": [
        {
          "text": "The metadata associated with the summary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadata"
        }
      ],
      "role": "symbol",
      "title": "metadata",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposuredetectionsummary/metadata"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/riskScoreSumFullRange": {
      "abstract": [
        {
          "text": "The sum of the full-range risk scores for all exposures for the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "riskScoreSumFullRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/riskScoreSumFullRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "riskScoreSumFullRange"
        }
      ],
      "role": "symbol",
      "title": "riskScoreSumFullRange",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposuredetectionsummary/riskscoresumfullrange"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureSummaryItem": {
      "abstract": [
        {
          "text": "The summary of exposures for a specific time period or report type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureSummaryItem"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureSummaryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureSummaryItem"
        }
      ],
      "role": "symbol",
      "title": "ENExposureSummaryItem",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposuresummaryitem"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Summaries",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDaySummary",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureSummaryItem"
      ],
      "title": "Summaries"
    }
  ],
  "topicSections": [
    {
      "anchor": "Exposure-Criteria",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/attenuationDurations",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/daysSinceLastExposure",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/matchedKeyCount",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/maximumRiskScore",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/maximumRiskScoreFullRange",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/riskScoreSumFullRange",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/metadata",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/daySummaries"
      ],
      "title": "Exposure Criteria"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ENExposureDetectionSummary"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureDetectionSummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureDetectionSummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Exposure-Criteria",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/attenuationDurations",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/daysSinceLastExposure",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/matchedKeyCount",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/maximumRiskScore",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/maximumRiskScoreFullRange",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/riskScoreSumFullRange",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/metadata",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDetectionSummary/daySummaries"
              ],
              "title": "Exposure Criteria"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Summaries",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureDaySummary",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureSummaryItem"
              ],
              "title": "Summaries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ENExposureDetectionSummary"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1matchedKeyCount/title",
          "value": "matchedKeyCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1matchedKeyCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matchedKeyCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1attenuationDurations/title",
          "value": "attenuationDurations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1attenuationDurations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attenuationDurations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1daysSinceLastExposure/title",
          "value": "daysSinceLastExposure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1daysSinceLastExposure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "daysSinceLastExposure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1daySummaries/title",
          "value": "daySummaries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1daySummaries/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "daySummaries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDaySummary/title",
          "value": "ENExposureDaySummary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDaySummary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureDaySummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDaySummary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureDaySummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1maximumRiskScore/title",
          "value": "maximumRiskScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1maximumRiskScore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumRiskScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1metadata/title",
          "value": "metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1maximumRiskScoreFullRange/title",
          "value": "maximumRiskScoreFullRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1maximumRiskScoreFullRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumRiskScoreFullRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureSummaryItem/title",
          "value": "ENExposureSummaryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureSummaryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureSummaryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureSummaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1riskScoreSumFullRange/title",
          "value": "riskScoreSumFullRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary~1riskScoreSumFullRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "riskScoreSumFullRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary/title",
          "value": "ENExposureDetectionSummary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureDetectionSummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureDetectionSummary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureDetectionSummary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/enexposuredetectionsummary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification/enexposuredetectionsummary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
