{
  "abstract": [
    {
      "text": "The object that contains parameters for configuring exposure notification risk scoring behavior.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ENExposureConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ENExposureConfiguration"
      }
    ],
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ENExposureConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.5",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ENExposureConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ENExposureConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-in-ios-12-5"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This class is available in iOS 12.5, and in iOS 13.5 and later.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The ExposureNotification framework defines an Exposure Risk Value (ERV) to allow Health Authorities to define when to alert a user that they may have been exposed to someone diagnosed with COVID-19. The app uses the ERV to calculate the user’s Meaningful Exposure Minutes (MEMs) value. Health Authorities have flexibility in calculating this value by setting weights and values related to Bluetooth attenuations, infectiousness of the affected individual, and diagnosis report type. They can also determine what threshold will result in a notification.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "While the ERV is measured in MEMs, the system actually calculates and returns a number of seconds, rounded to the nearest minute. For example, if a person has an ERV of 2 MEMs, the app returns a value of 120 (seconds). Convert ERVs to minutes before displaying it to the user by dividing the returned value by 60.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The calculation method described in this document is available starting with iOS 14. To adopt this method of risk assessment, set the ",
              "type": "text"
            },
            {
              "code": "ENAPIVersion",
              "type": "codeVoice"
            },
            {
              "text": " key to the integer value 2 in the app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file. For more information on the V1 calculation used in earlier versions of iOS, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-risk-value-calculation-in-exposurenotification-version-1",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following diagram shows how to calculate an ERV:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3670910",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The class defines three sets of weights that give priority to the components of the ERV: minutes-at-attenuation, infectiousness, and report type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The weighted minutes-at-attenuation assigns priority to the amount of time that the user is near beacons at different Bluetooth attenuations. Assign values between 0–250 percent to weights that represent Immediate, Near, Medium, and Other distances.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3670915",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The infectiousness weight modifies the ERV based on the affected userʼs infectiousness level for the day of exposure relative to the day of symptom onset. To set the infectiousness level for when there is no symptom onset date provided, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDaysSinceOnsetOfSymptomsUnknown",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". A user’s infectiousness level can be ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness/high",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness/standard",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness/none",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Assign both ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/infectiousnessHighWeight",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/infectiousnessStandardWeight",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " a value between 0 percent and 250 percent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3671401",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The weighted report type assigns priority to the method of diagnosis. Assign values ranging from 0–250 percent to weights that represent a confirmed test diagnosis, clinical diagnosis, self- reported diagnoisis, and recursive diagnosis.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3670917",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In addition to setting the weights, you can perform additional filtering by setting ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/daysSinceLastExposureThreshold",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to limit the number of days to consider when calculating the risk level.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Calculating-an-Example-Exposure-Risk-Value",
          "level": 3,
          "text": "Calculating an Example Exposure Risk Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The following diagrams illustrate calculating an ERV using a real-world scenario.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The weighted minutes-at-attenuation shows 5 minutes of immediate exposure with a 150 percent weight, 10 minutes of near exposure with a 100 percent weight, 10 minutes of medium exposure with a 50 percent weight, and 5 minutes of other exposure with a 0 percent weight.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3670907",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The weighted infectiousness indicates days –14 to –6 from the current day with no infectiousness, days –5 to –3 with 100 percent of standard infectiousness, days –2 to +5 with 200 percent high infectiousness, days +6 to +10 with 100 percent standard infectiousness, and days +11 to +14 with no infectiousness.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3671402",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Here are the weighted report types for all three tests:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3670914",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The result of the calculation shows an ERV of 45 minutes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3670911",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "To prevent an ERV of 0, set any unused weight to 100 percent.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDaysSinceOnsetOfSymptomsUnknown": {
      "abstract": [
        {
          "text": "A value used when the number of days since onset of symptoms is unknown.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENDaysSinceOnsetOfSymptomsUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDaysSinceOnsetOfSymptomsUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENDaysSinceOnsetOfSymptomsUnknown"
        }
      ],
      "role": "symbol",
      "title": "ENDaysSinceOnsetOfSymptomsUnknown",
      "type": "topic",
      "url": "/documentation/exposurenotification/endayssinceonsetofsymptomsunknown"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration": {
      "abstract": [
        {
          "text": "The object that contains parameters for configuring exposure notification risk scoring behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureConfiguration"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureConfiguration"
        }
      ],
      "role": "symbol",
      "title": "ENExposureConfiguration",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/attenuationDurationThresholds": {
      "abstract": [
        {
          "text": "The configurable signal-loss thresholds for calculating exposure risk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attenuationDurationThresholds"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/attenuationDurationThresholds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attenuationDurationThresholds"
        }
      ],
      "role": "symbol",
      "title": "attenuationDurationThresholds",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/attenuationdurationthresholds"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/daysSinceLastExposureThreshold": {
      "abstract": [
        {
          "text": "The number of days to consider when calculating the risk level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "daysSinceLastExposureThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/daysSinceLastExposureThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "daysSinceLastExposureThreshold"
        }
      ],
      "role": "symbol",
      "title": "daysSinceLastExposureThreshold",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/dayssincelastexposurethreshold"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/immediateDurationWeight": {
      "abstract": [
        {
          "text": "The weight assigned to a risk level indicating the duration of the user’s exposure at immediate distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "immediateDurationWeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/immediateDurationWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "immediateDurationWeight"
        }
      ],
      "role": "symbol",
      "title": "immediateDurationWeight",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/immediatedurationweight"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/infectiousnessForDaysSinceOnsetOfSymptoms": {
      "abstract": [
        {
          "text": "The mapping between the days since onset of symptoms to the degree of infectiousness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "infectiousnessForDaysSinceOnsetOfSymptoms"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/infectiousnessForDaysSinceOnsetOfSymptoms",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "infectiousnessForDaysSinceOnsetOfSymptoms"
        }
      ],
      "role": "symbol",
      "title": "infectiousnessForDaysSinceOnsetOfSymptoms",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/infectiousnessfordayssinceonsetofsymptoms"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/infectiousnessHighWeight": {
      "abstract": [
        {
          "text": "The weight to apply for severe infectiousness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "infectiousnessHighWeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/infectiousnessHighWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "infectiousnessHighWeight"
        }
      ],
      "role": "symbol",
      "title": "infectiousnessHighWeight",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/infectiousnesshighweight"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/infectiousnessStandardWeight": {
      "abstract": [
        {
          "text": "The weight to apply for mild infectiousness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "infectiousnessStandardWeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/infectiousnessStandardWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "infectiousnessStandardWeight"
        }
      ],
      "role": "symbol",
      "title": "infectiousnessStandardWeight",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/infectiousnessstandardweight"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/mediumDurationWeight": {
      "abstract": [
        {
          "text": "The weight assigned to a risk level indicating the duration of the user’s exposure at medium distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediumDurationWeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/mediumDurationWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediumDurationWeight"
        }
      ],
      "role": "symbol",
      "title": "mediumDurationWeight",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/mediumdurationweight"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/nearDurationWeight": {
      "abstract": [
        {
          "text": "The weight assigned to a risk level indicating the duration of the user’s exposure at close distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nearDurationWeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/nearDurationWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nearDurationWeight"
        }
      ],
      "role": "symbol",
      "title": "nearDurationWeight",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/neardurationweight"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/otherDurationWeight": {
      "abstract": [
        {
          "text": "The weight assigned to a risk level indicating the duration of the user’s exposure at a large distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "otherDurationWeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/otherDurationWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "otherDurationWeight"
        }
      ],
      "role": "symbol",
      "title": "otherDurationWeight",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/otherdurationweight"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeConfirmedClinicalDiagnosisWeight": {
      "abstract": [
        {
          "text": "The weight assigned to a risk level based on a confirmed clinical diagnosis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportTypeConfirmedClinicalDiagnosisWeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeConfirmedClinicalDiagnosisWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportTypeConfirmedClinicalDiagnosisWeight"
        }
      ],
      "role": "symbol",
      "title": "reportTypeConfirmedClinicalDiagnosisWeight",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/reporttypeconfirmedclinicaldiagnosisweight"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeConfirmedTestWeight": {
      "abstract": [
        {
          "text": "The weight assigned to a risk level based on a confirmed test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportTypeConfirmedTestWeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeConfirmedTestWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportTypeConfirmedTestWeight"
        }
      ],
      "role": "symbol",
      "title": "reportTypeConfirmedTestWeight",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/reporttypeconfirmedtestweight"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeNoneMap": {
      "abstract": [
        {
          "text": "The report type to map an unknown diagnosis to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportTypeNoneMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENDiagnosisReportType",
          "text": "ENDiagnosisReportType"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeNoneMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportTypeNoneMap"
        }
      ],
      "role": "symbol",
      "title": "reportTypeNoneMap",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/reporttypenonemap"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeRecursiveWeight": {
      "abstract": [
        {
          "text": "The weight assigned to a risk level based on an exposure to someone exposed to someone else.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportTypeRecursiveWeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeRecursiveWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportTypeRecursiveWeight"
        }
      ],
      "role": "symbol",
      "title": "reportTypeRecursiveWeight",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/reporttyperecursiveweight"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeSelfReportedWeight": {
      "abstract": [
        {
          "text": "The weight assigned to a risk level based on a self-reported diagnoisis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportTypeSelfReportedWeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeSelfReportedWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportTypeSelfReportedWeight"
        }
      ],
      "role": "symbol",
      "title": "reportTypeSelfReportedWeight",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration/reporttypeselfreportedweight"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow": {
      "abstract": [
        {
          "text": "A set of scan events from observed beacons within a time span.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureWindow"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureWindow"
        }
      ],
      "role": "symbol",
      "title": "ENExposureWindow",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposurewindow"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness/high": {
      "abstract": [
        {
          "text": "The user is highly infectious.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENInfectiousnessHigh"
        }
      ],
      "role": "symbol",
      "title": "ENInfectiousness.high",
      "type": "topic",
      "url": "/documentation/exposurenotification/eninfectiousness/high"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness/none": {
      "abstract": [
        {
          "text": "The user is not infectious.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENInfectiousnessNone"
        }
      ],
      "role": "symbol",
      "title": "ENInfectiousness.none",
      "type": "topic",
      "url": "/documentation/exposurenotification/eninfectiousness/none"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness/standard": {
      "abstract": [
        {
          "text": "The user is mildly infectious.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standard"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness/standard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENInfectiousnessStandard"
        }
      ],
      "role": "symbol",
      "title": "ENInfectiousness.standard",
      "type": "topic",
      "url": "/documentation/exposurenotification/eninfectiousness/standard"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENScanInstance": {
      "abstract": [
        {
          "text": "The aggregation of attenuations of beacons received during a scan.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENScanInstance"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENScanInstance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENScanInstance"
        }
      ],
      "role": "symbol",
      "title": "ENScanInstance",
      "type": "topic",
      "url": "/documentation/exposurenotification/enscaninstance"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/configuring-exposure-notifications": {
      "abstract": [
        {
          "text": "Define how Exposure Notifications work for a region by assigning server-based key-value pairs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/configuring-exposure-notifications",
      "kind": "article",
      "role": "article",
      "title": "Configuring Exposure Notifications",
      "type": "topic",
      "url": "/documentation/exposurenotification/configuring-exposure-notifications"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-parameter-limits": {
      "abstract": [
        {
          "text": "The limits for the parameters you use in exposure risk calculations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-parameter-limits",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Exposure Parameter Limits",
      "type": "topic",
      "url": "/documentation/exposurenotification/exposure-parameter-limits"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-risk-value-calculation-in-exposurenotification-version-1": {
      "abstract": [
        {
          "text": "Learn how to determine a user’s risk of exposure.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-risk-value-calculation-in-exposurenotification-version-1",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Exposure Risk Value Calculation in ExposureNotification Version 1",
      "type": "topic",
      "url": "/documentation/exposurenotification/exposure-risk-value-calculation-in-exposurenotification-version-1"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-in-ios-12-5": {
      "abstract": [
        {
          "text": "Prepare your Exposure Notifications app to run on a previous version of iOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-in-ios-12-5",
      "kind": "article",
      "role": "article",
      "title": "Supporting Exposure Notifications in iOS 12.5",
      "type": "topic",
      "url": "/documentation/exposurenotification/supporting-exposure-notifications-in-ios-12-5"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "media-3670907": {
      "alt": "A diagram showing the weighted minutes-at-attention example.",
      "identifier": "media-3670907",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cecff092c23f19855051cdb8aff9522c/media-3670907@2x.png"
        }
      ]
    },
    "media-3670910": {
      "alt": "A diagram showing how to calculate the exposure ERV.",
      "identifier": "media-3670910",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/106a1342224588f2e601071f22c3d703/media-3670910@2x.png"
        }
      ]
    },
    "media-3670911": {
      "alt": "A diagram showing an example of calculating the ERV.",
      "identifier": "media-3670911",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2aa6cf44c52a213313a371f390c80b59/media-3670911@2x.png"
        }
      ]
    },
    "media-3670914": {
      "alt": "A table showing the weighted report types in the example.",
      "identifier": "media-3670914",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ddea82a79718bad16aebfbf2828ff5d9/media-3670914@2x.png"
        }
      ]
    },
    "media-3670915": {
      "alt": "A diagram showing the weighted minutes-at-attenuation calculation.",
      "identifier": "media-3670915",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9b05a56753ac2d2b2b0f73449edc7282/media-3670915@2x.png"
        }
      ]
    },
    "media-3670917": {
      "alt": "A table showing the weighted report types and their ranges.",
      "identifier": "media-3670917",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1a4be158bc5df5633050eef9ef814ec9/media-3670917@2x.png"
        }
      ]
    },
    "media-3671401": {
      "alt": "A diagram showing a user’s infectiousness over the course of days.",
      "identifier": "media-3671401",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/512371c75b087a0bec2dbdf6705b3da7/media-3671401@2x.png"
        }
      ]
    },
    "media-3671402": {
      "alt": "A diagram showing an example of infectiousness weights over the course of 29 days.",
      "identifier": "media-3671402",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/06317e295c02b87ca0fe0a41400aea41/media-3671402@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Exposures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/configuring-exposure-notifications",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENScanInstance",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-parameter-limits"
      ],
      "title": "Exposures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-Duration",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/attenuationDurationThresholds",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/immediateDurationWeight",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/mediumDurationWeight",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/nearDurationWeight",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/otherDurationWeight",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/daysSinceLastExposureThreshold"
      ],
      "title": "Configuring Duration"
    },
    {
      "anchor": "Configuring-Infectiousness",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/infectiousnessForDaysSinceOnsetOfSymptoms",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/infectiousnessHighWeight",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/infectiousnessStandardWeight",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDaysSinceOnsetOfSymptomsUnknown"
      ],
      "title": "Configuring Infectiousness"
    },
    {
      "anchor": "Configuring-Report-Types",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeConfirmedClinicalDiagnosisWeight",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeConfirmedTestWeight",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeRecursiveWeight",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeSelfReportedWeight",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeNoneMap"
      ],
      "title": "Configuring Report Types"
    },
    {
      "anchor": "Determining-Exposure-Risk-Level-in-Version-1",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-risk-value-calculation-in-exposurenotification-version-1"
      ],
      "title": "Determining Exposure Risk Level in Version 1"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.5",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ENExposureConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-Duration",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/attenuationDurationThresholds",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/immediateDurationWeight",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/mediumDurationWeight",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/nearDurationWeight",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/otherDurationWeight",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/daysSinceLastExposureThreshold"
              ],
              "title": "Configuring Duration"
            },
            {
              "anchor": "Configuring-Infectiousness",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/infectiousnessForDaysSinceOnsetOfSymptoms",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/infectiousnessHighWeight",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/infectiousnessStandardWeight",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDaysSinceOnsetOfSymptomsUnknown"
              ],
              "title": "Configuring Infectiousness"
            },
            {
              "anchor": "Configuring-Report-Types",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeConfirmedClinicalDiagnosisWeight",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeConfirmedTestWeight",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeRecursiveWeight",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeSelfReportedWeight",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration/reportTypeNoneMap"
              ],
              "title": "Configuring Report Types"
            },
            {
              "anchor": "Determining-Exposure-Risk-Level-in-Version-1",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-risk-value-calculation-in-exposurenotification-version-1"
              ],
              "title": "Determining Exposure Risk Level in Version 1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Exposures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/configuring-exposure-notifications",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENScanInstance",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-parameter-limits"
              ],
              "title": "Exposures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ENExposureConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENInfectiousness~1none/title",
          "value": "ENInfectiousnessNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENInfectiousness~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENInfectiousnessNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1immediateDurationWeight/title",
          "value": "immediateDurationWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1immediateDurationWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "immediateDurationWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1daysSinceLastExposureThreshold/title",
          "value": "daysSinceLastExposureThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1daysSinceLastExposureThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "daysSinceLastExposureThreshold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1mediumDurationWeight/title",
          "value": "mediumDurationWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1mediumDurationWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediumDurationWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow/title",
          "value": "ENExposureWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeNoneMap/title",
          "value": "reportTypeNoneMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeNoneMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportTypeNoneMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1otherDurationWeight/title",
          "value": "otherDurationWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1otherDurationWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "otherDurationWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1attenuationDurationThresholds/title",
          "value": "attenuationDurationThresholds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1attenuationDurationThresholds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attenuationDurationThresholds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1infectiousnessForDaysSinceOnsetOfSymptoms/title",
          "value": "infectiousnessForDaysSinceOnsetOfSymptoms"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1infectiousnessForDaysSinceOnsetOfSymptoms/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "infectiousnessForDaysSinceOnsetOfSymptoms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/title",
          "value": "ENExposureConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENScanInstance/title",
          "value": "ENScanInstance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENScanInstance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENScanInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENScanInstance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENScanInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1nearDurationWeight/title",
          "value": "nearDurationWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1nearDurationWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nearDurationWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDaysSinceOnsetOfSymptomsUnknown/title",
          "value": "ENDaysSinceOnsetOfSymptomsUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDaysSinceOnsetOfSymptomsUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDaysSinceOnsetOfSymptomsUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeConfirmedClinicalDiagnosisWeight/title",
          "value": "reportTypeConfirmedClinicalDiagnosisWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeConfirmedClinicalDiagnosisWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportTypeConfirmedClinicalDiagnosisWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeRecursiveWeight/title",
          "value": "reportTypeRecursiveWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeRecursiveWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportTypeRecursiveWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1infectiousnessHighWeight/title",
          "value": "infectiousnessHighWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1infectiousnessHighWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "infectiousnessHighWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeConfirmedTestWeight/title",
          "value": "reportTypeConfirmedTestWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeConfirmedTestWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportTypeConfirmedTestWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeSelfReportedWeight/title",
          "value": "reportTypeSelfReportedWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1reportTypeSelfReportedWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportTypeSelfReportedWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENInfectiousness~1standard/title",
          "value": "ENInfectiousnessStandard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENInfectiousness~1standard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENInfectiousnessStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1infectiousnessStandardWeight/title",
          "value": "infectiousnessStandardWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration~1infectiousnessStandardWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "infectiousnessStandardWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENInfectiousness~1high/title",
          "value": "ENInfectiousnessHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENInfectiousness~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENInfectiousnessHigh"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/enexposureconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification/enexposureconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
