{
  "abstract": [
    {
      "text": "A set of user-definable types that indicate variants of concern.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ENVariantOfConcernType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ENVariantOfConcernType"
      }
    ],
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ENVariantOfConcernType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.2",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ENVariantOfConcernType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A Public Health Authority (PHA) defines the meaning of the types that indicate variants of concern. For example, a PHA could define the meaning of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type1",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " as “Vaccine is effective”, and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type2",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " as “Highly transmissive.” The PHA could assign the definition of “High severity” to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type3",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and “Vaccine breakthrough” to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type4",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/calibrationConfidence": {
      "abstract": [
        {
          "text": "The transmitting device’s calibration confidence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calibrationConfidence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENCalibrationConfidence",
          "text": "ENCalibrationConfidence"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/calibrationConfidence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "calibrationConfidence"
        }
      ],
      "role": "symbol",
      "title": "calibrationConfidence",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposurewindow/calibrationconfidence"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/date": {
      "abstract": [
        {
          "text": "The date that the exposure occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "date"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/date",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "date"
        }
      ],
      "role": "symbol",
      "title": "date",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposurewindow/date"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/diagnosisReportType": {
      "abstract": [
        {
          "text": "The report type of the observed diagnosis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "diagnosisReportType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENDiagnosisReportType",
          "text": "ENDiagnosisReportType"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/diagnosisReportType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "diagnosisReportType"
        }
      ],
      "role": "symbol",
      "title": "diagnosisReportType",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposurewindow/diagnosisreporttype"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/infectiousness": {
      "abstract": [
        {
          "text": "How infectious the user is, based on the number of days since the onset of symptoms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "infectiousness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENInfectiousness",
          "text": "ENInfectiousness"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/infectiousness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "infectiousness"
        }
      ],
      "role": "symbol",
      "title": "infectiousness",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposurewindow/infectiousness"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/scanInstances": {
      "abstract": [
        {
          "text": "An array of scans corresponding to a beacon associated with an exposure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scanInstances"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ENScanInstance",
          "text": "ENScanInstance"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/scanInstances",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scanInstances"
        }
      ],
      "role": "symbol",
      "title": "scanInstances",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposurewindow/scaninstances"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/variantOfConcernType": {
      "abstract": [
        {
          "text": "The variant of concern associated with this user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "variantOfConcernType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ENVariantOfConcernType",
          "text": "ENVariantOfConcernType"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/variantOfConcernType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "variantOfConcernType"
        }
      ],
      "role": "symbol",
      "title": "variantOfConcernType",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposurewindow/variantofconcerntype"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType": {
      "abstract": [
        {
          "text": "A set of user-definable types that indicate variants of concern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENVariantOfConcernType"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENVariantOfConcernType"
        }
      ],
      "role": "symbol",
      "title": "ENVariantOfConcernType",
      "type": "topic",
      "url": "/documentation/exposurenotification/envariantofconcerntype"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/exposurenotification/envariantofconcerntype/init(rawvalue:)"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type1": {
      "abstract": [
        {
          "text": "The first user-definable type for a variant of concern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type1"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENVariantOfConcernType1"
        }
      ],
      "role": "symbol",
      "title": "ENVariantOfConcernType.type1",
      "type": "topic",
      "url": "/documentation/exposurenotification/envariantofconcerntype/type1"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type2": {
      "abstract": [
        {
          "text": "The second user-definable type for a variant of concern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type2"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENVariantOfConcernType2"
        }
      ],
      "role": "symbol",
      "title": "ENVariantOfConcernType.type2",
      "type": "topic",
      "url": "/documentation/exposurenotification/envariantofconcerntype/type2"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type3": {
      "abstract": [
        {
          "text": "The third user-definable type for a variant of concern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type3"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENVariantOfConcernType3"
        }
      ],
      "role": "symbol",
      "title": "ENVariantOfConcernType.type3",
      "type": "topic",
      "url": "/documentation/exposurenotification/envariantofconcerntype/type3"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type4": {
      "abstract": [
        {
          "text": "The fourth user-definable type for a variant of concern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type4"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENVariantOfConcernType4"
        }
      ],
      "role": "symbol",
      "title": "ENVariantOfConcernType.type4",
      "type": "topic",
      "url": "/documentation/exposurenotification/envariantofconcerntype/type4"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/typeUnknown": {
      "abstract": [
        {
          "text": "The unknown type for a variant of concern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeUnknown"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/typeUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENVariantOfConcernTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "ENVariantOfConcernType.typeUnknown",
      "type": "topic",
      "url": "/documentation/exposurenotification/envariantofconcerntype/typeunknown"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Window-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/calibrationConfidence",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/date",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/diagnosisReportType",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/infectiousness",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/scanInstances",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/variantOfConcernType"
      ],
      "title": "Getting Window Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "User-Defined-Types",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type1",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type2",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type3",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type4",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/typeUnknown"
      ],
      "title": "User-Defined Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.2",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ENVariantOfConcernType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "User-Defined-Types",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type1",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type2",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type3",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/type4",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENVariantOfConcernType/typeUnknown"
              ],
              "title": "User-Defined Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Window-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/calibrationConfidence",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/date",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/diagnosisReportType",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/infectiousness",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/scanInstances",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow/variantOfConcernType"
              ],
              "title": "Getting Window Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ENVariantOfConcernType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType/title",
          "value": "ENVariantOfConcernType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow~1date/title",
          "value": "date"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow~1date/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "date"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type2/title",
          "value": "ENVariantOfConcernType2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow~1infectiousness/title",
          "value": "infectiousness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow~1infectiousness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "infectiousness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type1/title",
          "value": "ENVariantOfConcernType1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type3/title",
          "value": "ENVariantOfConcernType3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type4/title",
          "value": "ENVariantOfConcernType4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1type4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernType4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1typeUnknown/title",
          "value": "ENVariantOfConcernTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENVariantOfConcernType~1typeUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENVariantOfConcernTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow~1scanInstances/title",
          "value": "scanInstances"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow~1scanInstances/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scanInstances"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow~1calibrationConfidence/title",
          "value": "calibrationConfidence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow~1calibrationConfidence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "calibrationConfidence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow~1diagnosisReportType/title",
          "value": "diagnosisReportType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow~1diagnosisReportType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "diagnosisReportType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow~1variantOfConcernType/title",
          "value": "variantOfConcernType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow~1variantOfConcernType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "variantOfConcernType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/envariantofconcerntype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification/envariantofconcerntype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
