{
  "abstract": [
    {
      "text": "The limits for the parameters you use in exposure risk calculations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-parameter-limits"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Exposure Parameter Limits"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENActivityFlags": {
      "abstract": [
        {
          "text": "Activities that occur while the app isn’t running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENActivityFlags"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENActivityFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENActivityFlags"
        }
      ],
      "role": "symbol",
      "title": "ENActivityFlags",
      "type": "topic",
      "url": "/documentation/exposurenotification/enactivityflags"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence": {
      "abstract": [
        {
          "text": "The transmitting device’s calibration confidence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENCalibrationConfidence"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENCalibrationConfidence"
        }
      ],
      "role": "symbol",
      "title": "ENCalibrationConfidence",
      "type": "topic",
      "url": "/documentation/exposurenotification/encalibrationconfidence"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType": {
      "abstract": [
        {
          "text": "The type of a report that describes the origin of a diagnosis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENDiagnosisReportType"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENDiagnosisReportType"
        }
      ],
      "role": "symbol",
      "title": "ENDiagnosisReportType",
      "type": "topic",
      "url": "/documentation/exposurenotification/endiagnosisreporttype"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration": {
      "abstract": [
        {
          "text": "The object that contains parameters for configuring exposure notification risk scoring behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureConfiguration"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureConfiguration"
        }
      ],
      "role": "symbol",
      "title": "ENExposureConfiguration",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposureconfiguration"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow": {
      "abstract": [
        {
          "text": "A set of scan events from observed beacons within a time span.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENExposureWindow"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENExposureWindow"
        }
      ],
      "role": "symbol",
      "title": "ENExposureWindow",
      "type": "topic",
      "url": "/documentation/exposurenotification/enexposurewindow"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness": {
      "abstract": [
        {
          "text": "The degree to which a person’s symptoms may indicate transmission risk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENInfectiousness"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENInfectiousness"
        }
      ],
      "role": "symbol",
      "title": "ENInfectiousness",
      "type": "topic",
      "url": "/documentation/exposurenotification/eninfectiousness"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENScanInstance": {
      "abstract": [
        {
          "text": "The aggregation of attenuations of beacons received during a scan.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENScanInstance"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENScanInstance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENScanInstance"
        }
      ],
      "role": "symbol",
      "title": "ENScanInstance",
      "type": "topic",
      "url": "/documentation/exposurenotification/enscaninstance"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/attenuation": {
      "abstract": [
        {
          "text": "The minimum and maximum signal attenuations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/attenuation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Attenuation",
      "type": "topic",
      "url": "/documentation/exposurenotification/attenuation"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/configuring-exposure-notifications": {
      "abstract": [
        {
          "text": "Define how Exposure Notifications work for a region by assigning server-based key-value pairs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/configuring-exposure-notifications",
      "kind": "article",
      "role": "article",
      "title": "Configuring Exposure Notifications",
      "type": "topic",
      "url": "/documentation/exposurenotification/configuring-exposure-notifications"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level": {
      "abstract": [
        {
          "text": "The minimum and maximum risk levels.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Risk Level",
      "type": "topic",
      "url": "/documentation/exposurenotification/risk-level"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level-value": {
      "abstract": [
        {
          "text": "The minimum and maximum risk level values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level-value",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Risk Level Value",
      "type": "topic",
      "url": "/documentation/exposurenotification/risk-level-value"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-score": {
      "abstract": [
        {
          "text": "The minimum and maximum risk score.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-score",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Risk Score",
      "type": "topic",
      "url": "/documentation/exposurenotification/risk-score"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-weight": {
      "abstract": [
        {
          "text": "The minimum, default, and maximum risk weights.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-weight",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Risk Weight",
      "type": "topic",
      "url": "/documentation/exposurenotification/risk-weight"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Exposures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/configuring-exposure-notifications",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENScanInstance"
      ],
      "title": "Exposures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/attenuation",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level-value",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-score",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-weight",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENActivityFlags",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENActivityFlags",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Exposures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/configuring-exposure-notifications",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureConfiguration",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENExposureWindow",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENScanInstance"
              ],
              "title": "Exposures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/title",
          "value": "ENExposureConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENScanInstance/title",
          "value": "ENScanInstance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENScanInstance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENScanInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENScanInstance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENScanInstance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType/title",
          "value": "ENDiagnosisReportType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDiagnosisReportType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDiagnosisReportType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENActivityFlags/title",
          "value": "ENActivityFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENActivityFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENActivityFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENActivityFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENActivityFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENInfectiousness/title",
          "value": "ENInfectiousness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENInfectiousness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENInfectiousness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENInfectiousness/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENInfectiousness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow/title",
          "value": "ENExposureWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENExposureWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENExposureWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence/title",
          "value": "ENCalibrationConfidence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENCalibrationConfidence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENCalibrationConfidence"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/exposure-parameter-limits"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification/exposure-parameter-limits"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
