{
  "abstract": [
    {
      "text": "The minimum, default, and maximum risk weights.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-parameter-limits"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-weight"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Risk Weight"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This property is available in iOS 12.5, and in iOS 13.6 and later.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENActivityFlags": {
      "abstract": [
        {
          "text": "Activities that occur while the app isn’t running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENActivityFlags"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENActivityFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENActivityFlags"
        }
      ],
      "role": "symbol",
      "title": "ENActivityFlags",
      "type": "topic",
      "url": "/documentation/exposurenotification/enactivityflags"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence": {
      "abstract": [
        {
          "text": "The transmitting device’s calibration confidence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENCalibrationConfidence"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENCalibrationConfidence"
        }
      ],
      "role": "symbol",
      "title": "ENCalibrationConfidence",
      "type": "topic",
      "url": "/documentation/exposurenotification/encalibrationconfidence"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType": {
      "abstract": [
        {
          "text": "The type of a report that describes the origin of a diagnosis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENDiagnosisReportType"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENDiagnosisReportType"
        }
      ],
      "role": "symbol",
      "title": "ENDiagnosisReportType",
      "type": "topic",
      "url": "/documentation/exposurenotification/endiagnosisreporttype"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness": {
      "abstract": [
        {
          "text": "The degree to which a person’s symptoms may indicate transmission risk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENInfectiousness"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENInfectiousness"
        }
      ],
      "role": "symbol",
      "title": "ENInfectiousness",
      "type": "topic",
      "url": "/documentation/exposurenotification/eninfectiousness"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightDefault": {
      "abstract": [
        {
          "text": "The value that is the default for risk weight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENRiskWeightDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENRiskWeightDefault"
        }
      ],
      "role": "symbol",
      "title": "ENRiskWeightDefault",
      "type": "topic",
      "url": "/documentation/exposurenotification/enriskweightdefault"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightMax": {
      "abstract": [
        {
          "text": "The value that is the maximum for risk weight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENRiskWeightMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENRiskWeightMax"
        }
      ],
      "role": "symbol",
      "title": "ENRiskWeightMax",
      "type": "topic",
      "url": "/documentation/exposurenotification/enriskweightmax"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightMin": {
      "abstract": [
        {
          "text": "The value that is the minimum for risk weight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENRiskWeightMin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightMin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENRiskWeightMin"
        }
      ],
      "role": "symbol",
      "title": "ENRiskWeightMin",
      "type": "topic",
      "url": "/documentation/exposurenotification/enriskweightmin"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/attenuation": {
      "abstract": [
        {
          "text": "The minimum and maximum signal attenuations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/attenuation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Attenuation",
      "type": "topic",
      "url": "/documentation/exposurenotification/attenuation"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-parameter-limits": {
      "abstract": [
        {
          "text": "The limits for the parameters you use in exposure risk calculations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/exposure-parameter-limits",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Exposure Parameter Limits",
      "type": "topic",
      "url": "/documentation/exposurenotification/exposure-parameter-limits"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level": {
      "abstract": [
        {
          "text": "The minimum and maximum risk levels.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Risk Level",
      "type": "topic",
      "url": "/documentation/exposurenotification/risk-level"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level-value": {
      "abstract": [
        {
          "text": "The minimum and maximum risk level values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level-value",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Risk Level Value",
      "type": "topic",
      "url": "/documentation/exposurenotification/risk-level-value"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-score": {
      "abstract": [
        {
          "text": "The minimum and maximum risk score.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-score",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Risk Score",
      "type": "topic",
      "url": "/documentation/exposurenotification/risk-score"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/attenuation",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-level-value",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/risk-score",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENActivityFlags",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENCalibrationConfidence",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENDiagnosisReportType",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENInfectiousness"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightMin",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightMax",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENRiskWeightDefault"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENInfectiousness/title",
          "value": "ENInfectiousness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENInfectiousness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENInfectiousness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENInfectiousness/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENInfectiousness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskWeightDefault/title",
          "value": "ENRiskWeightDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskWeightDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENRiskWeightDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType/title",
          "value": "ENDiagnosisReportType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDiagnosisReportType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENDiagnosisReportType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENDiagnosisReportType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENActivityFlags/title",
          "value": "ENActivityFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENActivityFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENActivityFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENActivityFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENActivityFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskWeightMax/title",
          "value": "ENRiskWeightMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskWeightMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENRiskWeightMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskWeightMin/title",
          "value": "ENRiskWeightMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENRiskWeightMin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENRiskWeightMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence/title",
          "value": "ENCalibrationConfidence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENCalibrationConfidence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENCalibrationConfidence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENCalibrationConfidence"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/risk-weight"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
