{
  "abstract": [
    {
      "text": "Ensure that your server meets the requirements for supporting Exposure Notifications.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/setting-up-a-key-server"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Setting Up a Key Server"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apps that use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework rely on a key server to identify potential exposure to individuals diagnosed with COVID-19, the disease caused by the SARS-CoV-2 virus. The key server is responsible for collecting and distributing exposure keys to allow on-device exposure detection. This article describes how to provide the data that allows exposure notification to work, and details the data format the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework requires.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A key server, at a minimum, must allow exposure notification clients to:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Retrieve diagnosis keys so they can check for potential exposures",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Submit temporary exposure keys",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If providing a client app, a Health Authority can choose how to implement these capabilities as long as the data that passes to and from the exposure notification client conforms to the data formats this article describes. To support Exposure Notifications Express, which allows exposure notifications without an app in iOS 13.7 and above, a key server’s functionality must conform to specific requirements. For more information on how to support Exposure Notifications Express with your key server, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/configuring-a-key-server-for-exposure-notifications-express",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Google has created an ",
              "type": "text"
            },
            {
              "identifier": "https://github.com/google/exposure-notifications-server/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "that you can use as a reference, or as a starting point for creating your own key server.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Diagnosis keys are temporary exposure keys for individuals who have had a positive diagnosis of COVID-19.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Before you begin setting up your key server, ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/contact/request/exposure-notification-entitlement",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Once your request is accepted, you’ll be asked to provide information that clients will use to authenticate the data they receive from your server, such as its public key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Reject-Invalid-Temporary-Exposure-Keys",
          "level": 3,
          "text": "Reject Invalid Temporary Exposure Keys",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A key server must reject invalid key files uploaded from a client app. Uploaded key data is considered invalid if:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The period of time covered by the data file exceeds 14 days",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "TEKRollingPeriod",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", if included, must be a positive value that is no greater than 144",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If ",
              "type": "text"
            },
            {
              "code": "TEKRollingPeriod",
              "type": "codeVoice"
            },
            {
              "text": " is not included, use a default value of 144. You may optionally want to validate the clock time the device submits.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For detailed information on implementing key validity checks, see ",
              "type": "text"
            },
            {
              "identifier": "https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-CryptographySpecificationv1.2.pdf",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Take-Precautions-with-Temporary-Exposure-Keys",
          "level": 3,
          "text": "Take Precautions with Temporary Exposure Keys",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To help ensure that the data sent to client devices canʼt be used to reveal a userʼs identity, your key server:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Must store temporary exposure keys in randomized order, not in the order in which theyʼre received, and not grouped by user",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Must not distribute temporary exposure key data until at least 2 hours after the end of the keyʼs expiration window",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Must periodically delete any stored temporary exposure keys to ensure that none are over 30 days old",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Sign-Downloads-with-the-Latest-Registered-Certificate",
          "level": 3,
          "text": "Sign Downloads with the Latest Registered Certificate",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A key server must always sign files with the private key that corresponds to the latest public key provided to Apple using SHA-256 with ECDSA. Exposure notification clients reject keys retrieved from a server when they can’t verify them against the current public key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Package-Temporary-Exposure-Key-Data-in-a-Zip-Archive",
          "level": 3,
          "text": "Package Temporary Exposure Key Data in a Zip Archive",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A key server must deliver diagnosis key data to clients as a zip archive that contains two files, both stored at the root level, and both with the same base name, but different extensions. The file that contains the temporary exposure key data must have the extension ",
              "type": "text"
            },
            {
              "code": ".bin",
              "type": "codeVoice"
            },
            {
              "text": " and the file that contains the signature and signature-verification metadata must have the extension ",
              "type": "text"
            },
            {
              "code": ".sig",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A key server can send multiple zip archives to the same client, but each archive sent at the same time must use different base names for the contained files. For compatibility, send a maximum of 15 key files to a single client in a 24-hour period, because clients running on iOS 13.5 and earlier are limited to 15 key files in this time frame.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For best results, zip archives should be no larger than 16 MB and contain no more than 750,000 keys.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "While both the key and signature file specifications support multi-file batches, not all exposure notification clients accept them. To ensure that all clients can accept your key server’s diagnosis keys, always set ",
                  "type": "text"
                },
                {
                  "code": "batch_num",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "batch_size",
                  "type": "codeVoice"
                },
                {
                  "text": " to a value of 1.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": ".bin",
              "type": "codeVoice"
            },
            {
              "text": " file in the zip archive is a binary file that begins with a 16-byte header that contains ",
              "type": "text"
            },
            {
              "code": "​EK Export v1",
              "type": "codeVoice"
            },
            {
              "text": "​  in UTF-8 encoding, right-padded with whitespace characters. This header represents the current version of the exposure-key binary format. The header is followed by a serialized ​protocol buffer​ message named ",
              "type": "text"
            },
            {
              "code": "TemporaryExposureKeyExport",
              "type": "codeVoice"
            },
            {
              "text": ",​ which uses the following protocol buffer definition:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "syntax = \"proto2\";",
            "message TemporaryExposureKeyExport {",
            "    // Time window of keys in the file, based on arrival",
            "    // at the server, in UTC seconds.",
            "    optional fixed64 start_timestamp = 1;",
            "    optional fixed64 end_timestamp = 2;",
            "",
            "    // The region from which these keys came",
            "    optional string region = 3;",
            "",
            "    // Reserved for future use. Both batch_num and batch_size",
            "    // must be set to a value of 1.",
            "    optional int32 batch_num = 4;",
            "    optional int32 batch_size = 5;",
            "",
            "    // Information about associated signatures",
            "    repeated SignatureInfo signature_infos = 6;",
            "    ",
            "    // Exposure keys that are new. ",
            "    repeated TemporaryExposureKey keys = 7;",
            "    ",
            "    // Keys that have changed status from previous key archives,",
            "    // including keys that are being revoked.",
            "    repeated TemporaryExposureKey revised_keys = 8;",
            "}",
            "message SignatureInfo {",
            "    // The first two fields have been deprecated.",
            "    reserved 1, 2;",
            "    reserved \"app_bundle_id\", \"android_package\";",
            "    ",
            "    // Key version in case the key server signing key is rotated. (e.g. \"v1\")",
            "    // A PHA can only have one active public key at a time, so they must rotate",
            "    // keys on all devices and servers at the same time to avoid problems.",
            "    optional string verification_key_version = 3;",
            "    ",
            "    // Implementation-specific string that can be used in key verification.",
            "    // Valid character in this string are all alphanumeric characters, ",
            "    // underscores, and periods.",
            "    optional string verification_key_id = 4;",
            "",
            "    // All keys must be signed using the SHA-256 with ECDSA algorithm.",
            "    // This field must contain the string \"1.2.840.10045.4.3.2\". ",
            "    optional string signature_algorithm = 5;",
            "}",
            "message TemporaryExposureKey {",
            "    // Temporary exposure key for an infected user.",
            "    optional bytes key_data = 1;",
            "    ",
            "    // Varying risk associated with a key depending on diagnosis method. ",
            "    // Deprecated and no longer used.",
            "    optional int32 transmission_risk_level = 2 [deprecated = true];",
            "    ",
            "    // The interval number since epoch for which a key starts",
            "    optional int32 rolling_start_interval_number = 3;",
            "    ",
            "    // How long this key is valid, specified in increments of 10 minutes",
            "    optional int32 rolling_period = 4",
            "    [default = 144]; // defaults to 24 hours",
            "    ",
            "    // Data type that represents why this key was published.",
            "    enum ReportType {",
            "      UNKNOWN = 0;  // Never returned by the client API.",
            "      CONFIRMED_TEST = 1;",
            "      CONFIRMED_CLINICAL_DIAGNOSIS = 2;",
            "      SELF_REPORT = 3;",
            "      RECURSIVE = 4;  // Reserved for future use.",
            "      REVOKED = 5;  // Used to revoke a key, never returned by client API.",
            "    }",
            "",
            "    // Type of diagnosis associated with a key.",
            "    optional ReportType report_type = 5;",
            "",
            "    // Number of days elapsed between symptom onset and the TEK being used.",
            "    // E.g. 2 means TEK is from 2 days after onset of symptoms.",
            "    // Valid values range is from -14 to 14.",
            "    optional sint32 days_since_onset_of_symptoms = 6;",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": ".sig",
              "type": "codeVoice"
            },
            {
              "text": " file in the archive contains the signature and information the client needs to validate the download. The key server generates the signature file by serializing a single ",
              "type": "text"
            },
            {
              "code": "TEKSignatureList",
              "type": "codeVoice"
            },
            {
              "text": " protocol buffer message, which uses the following protocol buffer definition:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "syntax = \"proto2\";",
            " ",
            "message TEKSignatureList {",
            "    // Information about associated signatures",
            "    repeated TEKSignature signatures = 1;",
            "}",
            "",
            "message TEKSignature {",
            "    // Information to uniquely identify the public key associated ",
            "    // with the key server's signing key.",
            "    optional SignatureInfo signature_info = 1;",
            "",
            "    // Reserved for future use. Both batch_num and batch_size",
            "    // must be set to a value of 1.",
            "    optional int32 batch_num = 2; ",
            "    optional int32 batch_size = 3;",
            "",
            "    // Signature in X9.62 format (ASN.1 SEQUENCE of two INTEGER fields).",
            "    optional bytes signature = 4;    ",
            "}",
            ""
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To calculate the ",
              "type": "text"
            },
            {
              "code": "signature",
              "type": "codeVoice"
            },
            {
              "text": " data inside a ",
              "type": "text"
            },
            {
              "code": "TEKSignature",
              "type": "codeVoice"
            },
            {
              "text": " message, start by generating a digest of the data file in the archive using the SHA-256 hash algorithm. Then, sign the digest value using the ECDSA with P-256 algorithm. The private key you use for signing must be the one that corresponds to the public key registered with Appleʼs key server.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion": {
      "abstract": [
        {
          "text": "A number that specifies the version of the API to use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "ENAPIVersion",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/ENAPIVersion"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENDeveloperRegion": {
      "abstract": [
        {
          "text": "A string that specifies the region that the app supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENDeveloperRegion",
      "kind": "symbol",
      "role": "symbol",
      "title": "ENDeveloperRegion",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/ENDeveloperRegion"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager": {
      "abstract": [
        {
          "text": "A class that manages exposure notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENManager"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENManager"
        }
      ],
      "role": "symbol",
      "title": "ENManager",
      "type": "topic",
      "url": "/documentation/exposurenotification/enmanager"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/building-an-app-to-notify-users-of-covid-19-exposure": {
      "abstract": [
        {
          "text": "Inform people when they may have been exposed to COVID-19.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/building-an-app-to-notify-users-of-covid-19-exposure",
      "kind": "article",
      "role": "sampleCode",
      "title": "Building an App to Notify Users of COVID-19 Exposure",
      "type": "topic",
      "url": "/documentation/exposurenotification/building-an-app-to-notify-users-of-covid-19-exposure"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/changing-configuration-values-using-the-server-to-server-api": {
      "abstract": [
        {
          "text": "Update Exposure Notifications configuration values from a Public Health Authority’s server.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/changing-configuration-values-using-the-server-to-server-api",
      "kind": "article",
      "role": "article",
      "title": "Changing Configuration Values Using the Server‑to‑Server API",
      "type": "topic",
      "url": "/documentation/exposurenotification/changing-configuration-values-using-the-server-to-server-api"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/configuring-a-key-server-for-exposure-notifications-express": {
      "abstract": [
        {
          "text": "Support exposure key upload and download for app-less exposure notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/configuring-a-key-server-for-exposure-notifications-express",
      "kind": "article",
      "role": "article",
      "title": "Configuring a Key Server for Exposure Notifications Express",
      "type": "topic",
      "url": "/documentation/exposurenotification/configuring-a-key-server-for-exposure-notifications-express"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-express": {
      "abstract": [
        {
          "text": "Configure servers to notify users of potential exposures to COVID-19 without an app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-express",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Supporting Exposure Notifications Express",
      "type": "topic",
      "url": "/documentation/exposurenotification/supporting-exposure-notifications-express"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-in-ios-12-5": {
      "abstract": [
        {
          "text": "Prepare your Exposure Notifications app to run on a previous version of iOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-in-ios-12-5",
      "kind": "article",
      "role": "article",
      "title": "Supporting Exposure Notifications in iOS 12.5",
      "type": "topic",
      "url": "/documentation/exposurenotification/supporting-exposure-notifications-in-ios-12-5"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/testing-exposure-notifications-apps-in-ios-13-7-and-later": {
      "abstract": [
        {
          "text": "Perform end-to-end validation of Exposure Notifications apps on a device by manually loading configuration files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/testing-exposure-notifications-apps-in-ios-13-7-and-later",
      "kind": "article",
      "role": "article",
      "title": "Testing Exposure Notifications Apps in iOS 13.7 and Later",
      "type": "topic",
      "url": "/documentation/exposurenotification/testing-exposure-notifications-apps-in-ios-13-7-and-later"
    },
    "https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-CryptographySpecificationv1.2.pdf": {
      "identifier": "https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-CryptographySpecificationv1.2.pdf",
      "title": "Exposure Notification Cryptography Specification",
      "titleInlineContent": [
        {
          "text": "Exposure Notification Cryptography Specification",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-CryptographySpecificationv1.2.pdf"
    },
    "https://developer.apple.com/contact/request/exposure-notification-entitlement": {
      "identifier": "https://developer.apple.com/contact/request/exposure-notification-entitlement",
      "title": "request an Exposure Notification Entitlement",
      "titleInlineContent": [
        {
          "text": "request an Exposure Notification Entitlement",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/contact/request/exposure-notification-entitlement"
    },
    "https://github.com/google/exposure-notifications-server/": {
      "identifier": "https://github.com/google/exposure-notifications-server/",
      "title": "implementation of a key server ",
      "titleInlineContent": [
        {
          "text": "implementation of a key server ",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://github.com/google/exposure-notifications-server/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-express",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/building-an-app-to-notify-users-of-covid-19-exposure",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENDeveloperRegion",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/changing-configuration-values-using-the-server-to-server-api",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/testing-exposure-notifications-apps-in-ios-13-7-and-later",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-in-ios-12-5"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-express",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENDeveloperRegion",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/changing-configuration-values-using-the-server-to-server-api",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/testing-exposure-notifications-apps-in-ios-13-7-and-later",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-in-ios-12-5"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager/title",
          "value": "ENManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/setting-up-a-key-server"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification/setting-up-a-key-server"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
