{
  "abstract": [
    {
      "text": "Perform end-to-end validation of Exposure Notifications apps on a device by manually loading configuration files.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.exposurenotification/documentation/ExposureNotification/testing-exposure-notifications-apps-in-ios-13-7-and-later"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Exposure Notification"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Testing Exposure Notifications Apps in iOS 13.7 and Later"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Exposure Notifications apps automatically download configuration information for the phone’s current region, such as the public key, public key version, and agency name. During development, those configuration files may not yet be available, or you may need to override the configuration values, for example, to point your app at a test server. You can manually set the default configuration values for your region by loading custom configuration files onto your development iPhone.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To load custom configuration files, you’ll need a Mac running Xcode, a device with your region’s Exposure Notifications app loaded on it, and the device profile you received from Apple when you registered as a PHA.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Enable-the-Developer-Menu",
          "level": 3,
          "text": "Enable the Developer Menu",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To load a custom Exposure Notifications configuration, the device must have the Developer menu enabled in the Settings app. If you’ve used the device to test applications from Xcode, the menu is already enabled. To verify that it’s enabled, go to the Settings app and scroll down to make sure Developer is listed. Alternatively, type “developer” into the search bar and confirm it’s listed. Once you confirm the Developer menu is enabled, you’re ready to create your configuration file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your iPhone doesn’t have a Developer row in the Settings app, launch Xcode on a Mac, select Devices & Simulators from the Window menu, and plug your iPhone into your Mac. As Xcode prepares your device, a yellow bar appears at the top of the Devices & Simulators window. If you’ve never plugged your iPhone into this computer, you’ll be asked if you want to trust it. Select “Trust” on your iPhone. After a few minutes, the yellow bar disappears, which signals that your device is configured for development.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-Configuration-File",
          "level": 3,
          "text": "Create a Configuration File",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Next, you need to create a configuration file that provides the configuration information your Exposure Notifications app needs to connect with your region’s servers. Start by copying the JSON below into a text file:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{",
            "    \"appConfigs\": [",
            "        {",
            "            \"appBundleId\": \"[bundle identifier]\",",
            "            \"config\": {",
            "                \"V1Enable\": true,",
            "                \"agencyColor\": [",
            "                    0,",
            "                    0,",
            "                    0",
            "                ],",
            "                \"agencyDisplayName_EN_US\": \"PHA Agency\",",
            "                \"agencyHeaderStyle\": 0,",
            "                \"agencyHeaderSubtitle_EN_US\": \"The agency subtitle for Agency goes here\",",
            "                \"agencyHeaderTextColor\": [",
            "                    0.5,",
            "                    1,",
            "                    0.5",
            "                ],",
            "                \"agencyImage\": \"agencyImage\",",
            "                \"agencyMessage_EN_US\": \"Agency PHA has an agency Message for you\",",
            "                \"agencyRegionName_EN_US\": \"Region\",",
            "                \"applicationBackgroundRuntimeIntervalinHours\": 2,",
            "                \"callbackIntervalInMin\": 240,",
            "                \"detectExposureDailyLimit\": 20,",
            "                \"detectExposureNKDLimit\": 6,",
            "                \"dynamicAlgorithmEnabled\": true,",
            "                \"dynamicThrottleDownAdvDensity\": 6,",
            "                \"dynamicThrottleDownDurationInSeconds\": 216,",
            "                \"dynamicThrottleDownRSSI\": -55,",
            "                \"dynamicThrottleUpAdvDensity\": 20,",
            "                \"dynamicThrottleUpDurationInMinutes\": 900,",
            "                \"enEnabled\": true,",
            "                \"enVersion\": 1,",
            "                \"enableRecursiveType\": false,",
            "                \"exposureMatching\": true,",
            "                \"forceAPWakeIntervalInMinutesThreshold\": 5,",
            "                \"hasStateRegions\": false,",
            "                \"isMatchingRestrictedRegion\": false,",
            "                \"maxMatchingAttempts\": 7,",
            "                \"maxTtkMatchAttempt\": 8,",
            "                \"maxTtkMatchAttemptPerDay\": 9,",
            "                \"numberOfAdvSamplesForRPIThreshold\": 1,",
            "                \"osTriggeredAppRunTimeInSeconds\": 300,",
            "                \"privacyParameterInputCandence\": 7,",
            "                \"regionDisabledTransitionGracePeriodMinutes\": 1440,",
            "                \"regionTransitionGracePeriodInMinutes\": 180,",
            "                \"reportTypeRecursiveWeight\": 100,",
            "                \"rpiAdvertisementToleranceInMinutes\": 120,",
            "                \"rpiDuplicateAdvertisementToleranceInMinutes\": 20,",
            "                \"serverConfigVersion\": 1,",
            "                \"status\": \"approved\"",
            "            },",
            "            \"countryCode\": \"[country code]\",",
            "            \"publicKey\": \"[public key]\",",
            "            \"publicKeyVersion\": \"[public key version]\",",
            "            \"signAuthorityName\": \"Agency Sample Authority\",",
            "            \"state\": \"\"",
            "        }",
            "    ]",
            "}"
          ],
          "syntax": "json",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Modify the JSON so the field values match your desired configuration. At a minimum, you must replace:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "[bundle identifier]",
                      "type": "codeVoice"
                    },
                    {
                      "text": " with your app’s actual bundle identifier",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "[public key]",
                      "type": "codeVoice"
                    },
                    {
                      "text": " with the most recent public key you registered with Apple",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "[public key version]",
                      "type": "codeVoice"
                    },
                    {
                      "text": " with the version number of your public key as a string (for example, ",
                      "type": "text"
                    },
                    {
                      "code": "v2",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "[countryCode]",
                      "type": "codeVoice"
                    },
                    {
                      "text": " with the ",
                      "type": "text"
                    },
                    {
                      "code": "ENDeveloperRegion",
                      "type": "codeVoice"
                    },
                    {
                      "text": " value from your app’s ",
                      "type": "text"
                    },
                    {
                      "code": "info.plist",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If your app’s region includes both a country and subdivision code, such as “US-CA”, only include the country code (for example “US”), not the entire region code in the ",
              "type": "text"
            },
            {
              "code": "countryCode",
              "type": "codeVoice"
            },
            {
              "text": " field, and then populate the ",
              "type": "text"
            },
            {
              "code": "state",
              "type": "codeVoice"
            },
            {
              "text": " field with the full region code (for example, “US-CA”, not just “CA”).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After you’ve made your changes, save the file somewhere on your Mac with the name ",
              "type": "text"
            },
            {
              "code": "Test_Config.json",
              "type": "codeVoice"
            },
            {
              "text": ". If you’re testing in iOS 14.1 or later, copy ",
              "type": "text"
            },
            {
              "code": "Test_Config.json",
              "type": "codeVoice"
            },
            {
              "text": " to the Files app on your iPhone by using AirDrop, or by adding it to the iCloud Drive folder on your Mac and then waiting for it to sync to your iPhone. If you’re testing in iOS 14.0 or iOS 13.7, you’ll need to convert the JSON file you created into a property list before copying it to your iPhone.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Convert-the-JSON-File-to-a-Property-List-iOS-14-and-iOS-137",
          "level": 3,
          "text": "Convert the JSON File to a Property List (iOS 14 and iOS 13.7)",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To convert the JSON file you created into a property list in iOS 14.0 or iOS 13.7, open the Terminal app on your Mac, use ",
              "type": "text"
            },
            {
              "code": "cd",
              "type": "codeVoice"
            },
            {
              "text": " to navigate to the directory where you saved T",
              "type": "text"
            },
            {
              "code": "est_Config.json",
              "type": "codeVoice"
            },
            {
              "text": ", then type the following command to generate the configuration property list to load onto your iPhone:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "plutil -convert xml1 Test_Config.json -o Test_Config.plist"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "plutil",
              "type": "codeVoice"
            },
            {
              "text": " command converts your JSON file into a new ",
              "type": "text"
            },
            {
              "code": ".plist",
              "type": "codeVoice"
            },
            {
              "text": " file called ",
              "type": "text"
            },
            {
              "code": "Test_Config.plist",
              "type": "codeVoice"
            },
            {
              "text": " and places it in the same directory as the original JSON file. Copy that new file to the Files app on your iPhone by using AirDrop, or by adding the file to the iCloud Drive folder on your Mac and then waiting for it to sync to your iPhone.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Load-the-Configuration-File",
          "level": 3,
          "text": "Load the Configuration File",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Once the configuration file is available in the Files app on your iPhone, open the Settings app, scroll down, and tap Developer. Select Exposure Notifications, then tap Developer Server Configuration to enable it, and choose Override Configuration File. Your phone will prompt you for the location of the configuration file. Select ",
              "type": "text"
            },
            {
              "code": "Test_Config.json",
              "type": "codeVoice"
            },
            {
              "text": " if you’re testing in iOS 14.1 or later, or ",
              "type": "text"
            },
            {
              "code": "Test_Config.plist",
              "type": "codeVoice"
            },
            {
              "text": " if testing in iOS 14.0 or iOS 13.7. After you select the configuration file, you’ll receive a notification that says, “Successfully set override configuration file”.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "if you don’t see an Exposure Notifications option under the Develop menu in the Settings app, you may need to install the Exposure Notifications profile provided by Apple, which enables that option. If you have installed the profile and still don’t see the option, ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/membercenter/index.action#requestTechSupport",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Navigate back to the top level of the Settings app and tap Exposure Notifications. Select Turn on Exposure Notifications and then select your app’s region. Once you do this, your phone will use the information from the custom configuration file. When you want to stop using your custom configuration file, disable Developer Server Configuration under Exposure Notifications in the Developer section of the Settings app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion": {
      "abstract": [
        {
          "text": "A number that specifies the version of the API to use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "ENAPIVersion",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/ENAPIVersion"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENDeveloperRegion": {
      "abstract": [
        {
          "text": "A string that specifies the region that the app supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENDeveloperRegion",
      "kind": "symbol",
      "role": "symbol",
      "title": "ENDeveloperRegion",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/ENDeveloperRegion"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification": {
      "abstract": [
        {
          "text": "Implement a COVID-19 exposure notification system that protects user privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification",
      "kind": "symbol",
      "role": "collection",
      "title": "Exposure Notification",
      "type": "topic",
      "url": "/documentation/exposurenotification"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager": {
      "abstract": [
        {
          "text": "A class that manages exposure notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ENManager"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ENManager"
        }
      ],
      "role": "symbol",
      "title": "ENManager",
      "type": "topic",
      "url": "/documentation/exposurenotification/enmanager"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/building-an-app-to-notify-users-of-covid-19-exposure": {
      "abstract": [
        {
          "text": "Inform people when they may have been exposed to COVID-19.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/building-an-app-to-notify-users-of-covid-19-exposure",
      "kind": "article",
      "role": "sampleCode",
      "title": "Building an App to Notify Users of COVID-19 Exposure",
      "type": "topic",
      "url": "/documentation/exposurenotification/building-an-app-to-notify-users-of-covid-19-exposure"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/changing-configuration-values-using-the-server-to-server-api": {
      "abstract": [
        {
          "text": "Update Exposure Notifications configuration values from a Public Health Authority’s server.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/changing-configuration-values-using-the-server-to-server-api",
      "kind": "article",
      "role": "article",
      "title": "Changing Configuration Values Using the Server‑to‑Server API",
      "type": "topic",
      "url": "/documentation/exposurenotification/changing-configuration-values-using-the-server-to-server-api"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/setting-up-a-key-server": {
      "abstract": [
        {
          "text": "Ensure that your server meets the requirements for supporting Exposure Notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/setting-up-a-key-server",
      "kind": "article",
      "role": "article",
      "title": "Setting Up a Key Server",
      "type": "topic",
      "url": "/documentation/exposurenotification/setting-up-a-key-server"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-express": {
      "abstract": [
        {
          "text": "Configure servers to notify users of potential exposures to COVID-19 without an app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-express",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Supporting Exposure Notifications Express",
      "type": "topic",
      "url": "/documentation/exposurenotification/supporting-exposure-notifications-express"
    },
    "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-in-ios-12-5": {
      "abstract": [
        {
          "text": "Prepare your Exposure Notifications app to run on a previous version of iOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-in-ios-12-5",
      "kind": "article",
      "role": "article",
      "title": "Supporting Exposure Notifications in iOS 12.5",
      "type": "topic",
      "url": "/documentation/exposurenotification/supporting-exposure-notifications-in-ios-12-5"
    },
    "https://developer.apple.com/membercenter/index.action#requestTechSupport": {
      "identifier": "https://developer.apple.com/membercenter/index.action#requestTechSupport",
      "title": "contact Apple Developer Technical Support",
      "titleInlineContent": [
        {
          "text": "contact Apple Developer Technical Support",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/membercenter/index.action#requestTechSupport"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-express",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/building-an-app-to-notify-users-of-covid-19-exposure",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/setting-up-a-key-server",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENDeveloperRegion",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/changing-configuration-values-using-the-server-to-server-api",
        "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-in-ios-12-5"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-express",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/setting-up-a-key-server",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/ENManager",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENDeveloperRegion",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/ENAPIVersion",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/changing-configuration-values-using-the-server-to-server-api",
                "doc://com.apple.exposurenotification/documentation/ExposureNotification/supporting-exposure-notifications-in-ios-12-5"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager/title",
          "value": "ENManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ENManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ENManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/exposurenotification/testing-exposure-notifications-apps-in-ios-13-7-and-later"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/exposurenotification/testing-exposure-notifications-apps-in-ios-13-7-and-later"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
