{
  "abstract": [
    {
      "text": "The incoming call is filtered because Do Not Disturb is active and the incoming caller is not a VIP.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.callkit/documentation/CallKit",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/filteredByDoNotDisturb"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CXErrorCodeIncomingCallError@CXErrorCodeIncomingCallErrorFilteredByDoNotDisturb",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "filteredByDoNotDisturb"
      }
    ],
    "modules": [
      {
        "name": "CallKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CXErrorCodeIncomingCallErrorFilteredByDoNotDisturb"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CXErrorCodeIncomingCallError.Code.filteredByDoNotDisturb"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "filteredByDoNotDisturb"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.callkit/documentation/CallKit": {
      "abstract": [
        {
          "text": "Display the system-calling UI for your app’s VoIP services, and coordinate your calling services with other apps and the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CallKit",
      "type": "topic",
      "url": "/documentation/callkit"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct": {
      "abstract": [
        {
          "text": "Codes for errors that occur during incoming calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CXErrorCodeIncomingCallError"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeIncomingCallError"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeIncomingCallError",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodeincomingcallerror-swift.struct"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Codes for errors that occur during incoming calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeIncomingCallError.Code",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodeincomingcallerror-swift.struct/code"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/callUUIDAlreadyExists": {
      "abstract": [
        {
          "text": "The incoming call UUID already exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callUUIDAlreadyExists"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/callUUIDAlreadyExists",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeIncomingCallErrorCallUUIDAlreadyExists"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeIncomingCallError.Code.callUUIDAlreadyExists",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodeincomingcallerror-swift.struct/code/calluuidalreadyexists"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/filteredByBlockList": {
      "abstract": [
        {
          "text": "The incoming call is filtered because the incoming caller has been blocked by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filteredByBlockList"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/filteredByBlockList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeIncomingCallErrorFilteredByBlockList"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeIncomingCallError.Code.filteredByBlockList",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodeincomingcallerror-swift.struct/code/filteredbyblocklist"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/filteredByDoNotDisturb": {
      "abstract": [
        {
          "text": "The incoming call is filtered because Do Not Disturb is active and the incoming caller is not a VIP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filteredByDoNotDisturb"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/filteredByDoNotDisturb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeIncomingCallErrorFilteredByDoNotDisturb"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeIncomingCallError.Code.filteredByDoNotDisturb",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodeincomingcallerror-swift.struct/code/filteredbydonotdisturb"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/unentitled": {
      "abstract": [
        {
          "text": "The app isn’t entitled to receive incoming calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unentitled"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/unentitled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeIncomingCallErrorUnentitled"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeIncomingCallError.Code.unentitled",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodeincomingcallerror-swift.struct/code/unentitled"
    },
    "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CXErrorCodeIncomingCallErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "CXErrorCodeIncomingCallError.Code.unknown",
      "type": "topic",
      "url": "/documentation/callkit/cxerrorcodeincomingcallerror-swift.struct/code/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/unknown",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/unentitled",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/callUUIDAlreadyExists",
        "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/filteredByBlockList"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CXErrorCodeIncomingCallErrorFilteredByDoNotDisturb"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeIncomingCallErrorFilteredByDoNotDisturb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.callkit/documentation/CallKit",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/unknown",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/unentitled",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/callUUIDAlreadyExists",
                "doc://com.apple.callkit/documentation/CallKit/CXErrorCodeIncomingCallError-swift.struct/Code/filteredByBlockList"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CXErrorCodeIncomingCallErrorFilteredByDoNotDisturb"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code~1filteredByDoNotDisturb/title",
          "value": "CXErrorCodeIncomingCallErrorFilteredByDoNotDisturb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code~1filteredByDoNotDisturb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeIncomingCallErrorFilteredByDoNotDisturb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code~1filteredByBlockList/title",
          "value": "CXErrorCodeIncomingCallErrorFilteredByBlockList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code~1filteredByBlockList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeIncomingCallErrorFilteredByBlockList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code~1unentitled/title",
          "value": "CXErrorCodeIncomingCallErrorUnentitled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code~1unentitled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeIncomingCallErrorUnentitled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code~1unknown/title",
          "value": "CXErrorCodeIncomingCallErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeIncomingCallErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code~1callUUIDAlreadyExists/title",
          "value": "CXErrorCodeIncomingCallErrorCallUUIDAlreadyExists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code~1callUUIDAlreadyExists/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeIncomingCallErrorCallUUIDAlreadyExists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code/title",
          "value": "CXErrorCodeIncomingCallError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeIncomingCallError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.callkit~1documentation~1CallKit~1CXErrorCodeIncomingCallError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CXErrorCodeIncomingCallError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/callkit/cxerrorcodeincomingcallerror-swift.struct/code/filteredbydonotdisturb"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/callkit/cxerrorcodeincomingcallerror-swift.struct/code/filteredbydonotdisturb"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
