{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_5"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSAppKitVersionNumber10_10_5",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "macOS10_10_5"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSAppKitVersion",
        "text": "NSAppKitVersion"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAppKitVersionNumber10_10_5"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "macOS10_10_5"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "macOS10_10_5"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAppKitVersion",
              "text": "NSAppKitVersion"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion": {
      "abstract": [
        {
          "text": "Constants for determining which version of AppKit is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersion"
        }
      ],
      "role": "symbol",
      "title": "NSAppKitVersion",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/current": {
      "abstract": [
        {
          "text": "The most recent version of AppKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "current"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/current",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber"
        }
      ],
      "role": "symbol",
      "title": "current",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/current"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_0": {
      "abstract": [
        {
          "text": "The AppKit framework included in OS X v10.0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_0"
        }
      ],
      "role": "symbol",
      "title": "macOS10_0",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_0"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_1": {
      "abstract": [
        {
          "text": "The AppKit framework included in OS X v10.1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_1"
        }
      ],
      "role": "symbol",
      "title": "macOS10_1",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_1"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_10"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_10"
        }
      ],
      "role": "symbol",
      "title": "macOS10_10",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_10"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_10_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_10_2"
        }
      ],
      "role": "symbol",
      "title": "macOS10_10_2",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_10_2"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_10_3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_10_3"
        }
      ],
      "role": "symbol",
      "title": "macOS10_10_3",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_10_3"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_10_4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_10_4"
        }
      ],
      "role": "symbol",
      "title": "macOS10_10_4",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_10_4"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_10_5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_10_5"
        }
      ],
      "role": "symbol",
      "title": "macOS10_10_5",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_10_5"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_Max": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_10_Max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_Max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_10_Max"
        }
      ],
      "role": "symbol",
      "title": "macOS10_10_Max",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_10_max"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_11"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_11"
        }
      ],
      "role": "symbol",
      "title": "macOS10_11",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_11"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_11_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_11_1"
        }
      ],
      "role": "symbol",
      "title": "macOS10_11_1",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_11_1"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_11_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_11_2"
        }
      ],
      "role": "symbol",
      "title": "macOS10_11_2",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_11_2"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11_3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_11_3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11_3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_11_3"
        }
      ],
      "role": "symbol",
      "title": "macOS10_11_3",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_11_3"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_12": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_12"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_12",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_12"
        }
      ],
      "role": "symbol",
      "title": "macOS10_12",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_12"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_12_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_12_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_12_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_12_1"
        }
      ],
      "role": "symbol",
      "title": "macOS10_12_1",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_12_1"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_12_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_12_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_12_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_12_2"
        }
      ],
      "role": "symbol",
      "title": "macOS10_12_2",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_12_2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Release-Versions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/current",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_0",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_1",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_2",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_3",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_4",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_Max",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11_1",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11_2",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11_3",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_12",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_12_1",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_12_2"
      ],
      "title": "Release Versions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSAppKitVersionNumber10_10_5"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_10_5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Release-Versions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/current",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_0",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_1",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_2",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_3",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_4",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_10_Max",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11_1",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11_2",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_11_3",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_12",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_12_1",
                "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_12_2"
              ],
              "title": "Release Versions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSAppKitVersion",
                    "text": "NSAppKitVersion"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSAppKitVersionNumber10_10_5"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_11_3/title",
          "value": "NSAppKitVersionNumber10_11_3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_11_3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_11_3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1current/title",
          "value": "NSAppKitVersionNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1current/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_10_Max/title",
          "value": "NSAppKitVersionNumber10_10_Max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_10_Max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_10_Max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_11/title",
          "value": "NSAppKitVersionNumber10_11"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_11/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_11"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_0/title",
          "value": "NSAppKitVersionNumber10_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_11_1/title",
          "value": "NSAppKitVersionNumber10_11_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_11_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_11_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_10_3/title",
          "value": "NSAppKitVersionNumber10_10_3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_10_3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_10_3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion/title",
          "value": "NSAppKitVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_10_2/title",
          "value": "NSAppKitVersionNumber10_10_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_10_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_10_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_10/title",
          "value": "NSAppKitVersionNumber10_10"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_11_2/title",
          "value": "NSAppKitVersionNumber10_11_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_11_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_11_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_12/title",
          "value": "NSAppKitVersionNumber10_12"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_12/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_12"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_12_1/title",
          "value": "NSAppKitVersionNumber10_12_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_12_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_12_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_10_5/title",
          "value": "NSAppKitVersionNumber10_10_5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_10_5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_10_5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_12_2/title",
          "value": "NSAppKitVersionNumber10_12_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_12_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_12_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_1/title",
          "value": "NSAppKitVersionNumber10_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_10_4/title",
          "value": "NSAppKitVersionNumber10_10_4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_10_4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_10_4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsappkitversion/macos10_10_5"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsappkitversion/macos10_10_5"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
