{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/number10_14_4"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "s:So15NSAppKitVersiona03AppB0E13number10_14_4ABvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "number10_14_4"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSAppKitVersion",
        "text": "NSAppKitVersion"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "renamed": "macOS10_14_4",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "number10_14_4"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "number10_14_4"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAppKitVersion",
              "text": "NSAppKitVersion"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion": {
      "abstract": [
        {
          "text": "Constants for determining which version of AppKit is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersion"
        }
      ],
      "role": "symbol",
      "title": "NSAppKitVersion",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_15"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_15"
        }
      ],
      "role": "symbol",
      "title": "macOS10_15",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_15"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_15_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_15_1"
        }
      ],
      "role": "symbol",
      "title": "macOS10_15_1",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_15_1"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_15_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_15_2"
        }
      ],
      "role": "symbol",
      "title": "macOS10_15_2",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_15_2"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_15_3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_15_3"
        }
      ],
      "role": "symbol",
      "title": "macOS10_15_3",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_15_3"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_15_4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_15_4"
        }
      ],
      "role": "symbol",
      "title": "macOS10_15_4",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_15_4"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_15_5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_15_5"
        }
      ],
      "role": "symbol",
      "title": "macOS10_15_5",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_15_5"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS10_15_6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber10_15_6"
        }
      ],
      "role": "symbol",
      "title": "macOS10_15_6",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos10_15_6"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS11_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber11_0"
        }
      ],
      "role": "symbol",
      "title": "macOS11_0",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos11_0"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS11_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber11_1"
        }
      ],
      "role": "symbol",
      "title": "macOS11_1",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos11_1"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS11_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber11_2"
        }
      ],
      "role": "symbol",
      "title": "macOS11_2",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos11_2"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS11_3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber11_3"
        }
      ],
      "role": "symbol",
      "title": "macOS11_3",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos11_3"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS11_4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber11_4"
        }
      ],
      "role": "symbol",
      "title": "macOS11_4",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos11_4"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS11_5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber11_5"
        }
      ],
      "role": "symbol",
      "title": "macOS11_5",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos11_5"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS12_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS12_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS12_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber12_0"
        }
      ],
      "role": "symbol",
      "title": "macOS12_0",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos12_0"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS12_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "macOS12_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS12_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAppKitVersionNumber12_1"
        }
      ],
      "role": "symbol",
      "title": "macOS12_1",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/macos12_1"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/number10_14_4": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "number10_14_4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAppKitVersion",
          "text": "NSAppKitVersion"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/number10_14_4",
      "kind": "symbol",
      "role": "symbol",
      "title": "number10_14_4",
      "type": "topic",
      "url": "/documentation/appkit/nsappkitversion/number10_14_4"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_1",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_2",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_3",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_4",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_5",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS10_15_6",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_0",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_1",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_2",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_3",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_4",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS11_5",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS12_0",
        "doc://com.apple.appkit/documentation/AppKit/NSAppKitVersion/macOS12_1"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_15_3/title",
          "value": "NSAppKitVersionNumber10_15_3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_15_3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_15_3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS12_0/title",
          "value": "NSAppKitVersionNumber12_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS12_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber12_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_15_5/title",
          "value": "NSAppKitVersionNumber10_15_5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_15_5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_15_5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion/title",
          "value": "NSAppKitVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_15/title",
          "value": "NSAppKitVersionNumber10_15"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_15/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_15"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS11_0/title",
          "value": "NSAppKitVersionNumber11_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS11_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber11_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_15_1/title",
          "value": "NSAppKitVersionNumber10_15_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_15_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_15_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS11_4/title",
          "value": "NSAppKitVersionNumber11_4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS11_4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber11_4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS12_1/title",
          "value": "NSAppKitVersionNumber12_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS12_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber12_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS11_1/title",
          "value": "NSAppKitVersionNumber11_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS11_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber11_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_15_4/title",
          "value": "NSAppKitVersionNumber10_15_4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_15_4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_15_4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_15_2/title",
          "value": "NSAppKitVersionNumber10_15_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_15_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_15_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS11_3/title",
          "value": "NSAppKitVersionNumber11_3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS11_3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber11_3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_15_6/title",
          "value": "NSAppKitVersionNumber10_15_6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS10_15_6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber10_15_6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS11_2/title",
          "value": "NSAppKitVersionNumber11_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS11_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber11_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS11_5/title",
          "value": "NSAppKitVersionNumber11_5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAppKitVersion~1macOS11_5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAppKitVersionNumber11_5"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsappkitversion/number10_14_4"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
