{
  "abstract": [
    {
      "text": "Error codes for error values from app metrics.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metrickit/documentation/MetricKit",
        "doc://com.apple.metrickit/documentation/MetricKit/MXError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MXErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "MetricKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MXError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metrickit/documentation/MetricKit": {
      "abstract": [
        {
          "text": "Aggregate and analyze per-device reports on exception and crash diagnostics and on power and performance metrics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetricKit",
      "type": "topic",
      "url": "/documentation/metrickit"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXAverage": {
      "abstract": [
        {
          "text": "A unit of measure for an average.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXAverage"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXAverage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXAverage"
        }
      ],
      "role": "symbol",
      "title": "MXAverage",
      "type": "topic",
      "url": "/documentation/metrickit/mxaverage"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCallStackTree": {
      "abstract": [
        {
          "text": "An object representing the call stack for an exception.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXCallStackTree"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCallStackTree",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXCallStackTree"
        }
      ],
      "role": "symbol",
      "title": "MXCallStackTree",
      "type": "topic",
      "url": "/documentation/metrickit/mxcallstacktree"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnosticObjectiveCExceptionReason": {
      "abstract": [
        {
          "text": "An object that represents the exception reason for an uncaught ObjC exception.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXCrashDiagnosticObjectiveCExceptionReason"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnosticObjectiveCExceptionReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXCrashDiagnosticObjectiveCExceptionReason"
        }
      ],
      "role": "symbol",
      "title": "MXCrashDiagnosticObjectiveCExceptionReason",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnosticobjectivecexceptionreason"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic": {
      "abstract": [
        {
          "text": "An abstract data class for a diagnostic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXDiagnostic"
        }
      ],
      "role": "symbol",
      "title": "MXDiagnostic",
      "type": "topic",
      "url": "/documentation/metrickit/mxdiagnostic"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError": {
      "abstract": [
        {
          "text": "Error domain for error handling of app metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXError"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXError"
        }
      ],
      "role": "symbol",
      "title": "MXError",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code": {
      "abstract": [
        {
          "text": "Error codes for error values from app metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MXError.Code",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/code"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/code/init(rawvalue:)"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskDuplicated": {
      "abstract": [
        {
          "text": "A task with the same ID has already been started.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launchTaskDuplicated"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskDuplicated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXErrorLaunchTaskDuplicated"
        }
      ],
      "role": "symbol",
      "title": "MXError.Code.launchTaskDuplicated",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/code/launchtaskduplicated"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskInternalFailure": {
      "abstract": [
        {
          "text": "Internal failures happened inside the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launchTaskInternalFailure"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskInternalFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXErrorLaunchTaskInternalFailure"
        }
      ],
      "role": "symbol",
      "title": "MXError.Code.launchTaskInternalFailure",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/code/launchtaskinternalfailure"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskInvalidID": {
      "abstract": [
        {
          "text": "The task ID is a ",
          "type": "text"
        },
        {
          "code": "null",
          "type": "codeVoice"
        },
        {
          "text": " value or exceeds the maximum 128 character length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launchTaskInvalidID"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskInvalidID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXErrorLaunchTaskInvalidID"
        }
      ],
      "role": "symbol",
      "title": "MXError.Code.launchTaskInvalidID",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/code/launchtaskinvalidid"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskMaxCount": {
      "abstract": [
        {
          "text": "Exceeded the maximum number of tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launchTaskMaxCount"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskMaxCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXErrorLaunchTaskMaxCount"
        }
      ],
      "role": "symbol",
      "title": "MXError.Code.launchTaskMaxCount",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/code/launchtaskmaxcount"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskPastDeadline": {
      "abstract": [
        {
          "text": "The start call was made too late.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launchTaskPastDeadline"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskPastDeadline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXErrorLaunchTaskPastDeadline"
        }
      ],
      "role": "symbol",
      "title": "MXError.Code.launchTaskPastDeadline",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/code/launchtaskpastdeadline"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskUnknown": {
      "abstract": [
        {
          "text": "The task hasn’t been started or has already been finished.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launchTaskUnknown"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXErrorLaunchTaskUnknown"
        }
      ],
      "role": "symbol",
      "title": "MXError.Code.launchTaskUnknown",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/code/launchtaskunknown"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXErrorDomain": {
      "abstract": [
        {
          "text": "Error domain for error values from app metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MXErrorDomain",
      "type": "topic",
      "url": "/documentation/metrickit/mxerrordomain"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXHistogram": {
      "abstract": [
        {
          "text": "An object representing a histogram of data values of the same type of unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXHistogram"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXHistogram",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXHistogram"
        }
      ],
      "role": "symbol",
      "title": "MXHistogram",
      "type": "topic",
      "url": "/documentation/metrickit/mxhistogram"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetaData": {
      "abstract": [
        {
          "text": "An object containing system-level information about the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMetaData"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetaData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMetaData"
        }
      ],
      "role": "symbol",
      "title": "MXMetaData",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetadata"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXMetric": {
      "abstract": [
        {
          "text": "An abstract data class for a metric.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXMetric"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXMetric"
        }
      ],
      "role": "symbol",
      "title": "MXMetric",
      "type": "topic",
      "url": "/documentation/metrickit/mxmetric"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXSignpostRecord": {
      "abstract": [
        {
          "text": "An object representing the record for a signpost interval or event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXSignpostRecord"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXSignpostRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXSignpostRecord"
        }
      ],
      "role": "symbol",
      "title": "MXSignpostRecord",
      "type": "topic",
      "url": "/documentation/metrickit/mxsignpostrecord"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXCallStackTree",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetaData",
        "doc://com.apple.metrickit/documentation/MetricKit/MXAverage",
        "doc://com.apple.metrickit/documentation/MetricKit/MXHistogram",
        "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic",
        "doc://com.apple.metrickit/documentation/MetricKit/MXMetric",
        "doc://com.apple.metrickit/documentation/MetricKit/MXErrorDomain",
        "doc://com.apple.metrickit/documentation/MetricKit/MXError",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnosticObjectiveCExceptionReason",
        "doc://com.apple.metrickit/documentation/MetricKit/MXSignpostRecord"
      ],
      "title": "Data types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Launch-errors",
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskDuplicated",
        "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskInternalFailure",
        "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskInvalidID",
        "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskMaxCount",
        "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskPastDeadline",
        "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskUnknown"
      ],
      "title": "Launch errors"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MXErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metrickit/documentation/MetricKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Launch-errors",
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskDuplicated",
                "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskInternalFailure",
                "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskInvalidID",
                "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskMaxCount",
                "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskPastDeadline",
                "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code/launchTaskUnknown"
              ],
              "title": "Launch errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXCallStackTree",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetaData",
                "doc://com.apple.metrickit/documentation/MetricKit/MXAverage",
                "doc://com.apple.metrickit/documentation/MetricKit/MXHistogram",
                "doc://com.apple.metrickit/documentation/MetricKit/MXDiagnostic",
                "doc://com.apple.metrickit/documentation/MetricKit/MXMetric",
                "doc://com.apple.metrickit/documentation/MetricKit/MXErrorDomain",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnosticObjectiveCExceptionReason",
                "doc://com.apple.metrickit/documentation/MetricKit/MXSignpostRecord"
              ],
              "title": "Data types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MXErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnostic/title",
          "value": "MXDiagnostic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnostic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXDiagnostic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code~1launchTaskPastDeadline/title",
          "value": "MXErrorLaunchTaskPastDeadline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code~1launchTaskPastDeadline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorLaunchTaskPastDeadline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXErrorDomain/title",
          "value": "MXErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code~1launchTaskInvalidID/title",
          "value": "MXErrorLaunchTaskInvalidID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code~1launchTaskInvalidID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorLaunchTaskInvalidID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCallStackTree/title",
          "value": "MXCallStackTree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCallStackTree/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCallStackTree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCallStackTree/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCallStackTree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetric/title",
          "value": "MXMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetric/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code~1launchTaskUnknown/title",
          "value": "MXErrorLaunchTaskUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code~1launchTaskUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorLaunchTaskUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code~1launchTaskInternalFailure/title",
          "value": "MXErrorLaunchTaskInternalFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code~1launchTaskInternalFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorLaunchTaskInternalFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnosticObjectiveCExceptionReason/title",
          "value": "MXCrashDiagnosticObjectiveCExceptionReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnosticObjectiveCExceptionReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCrashDiagnosticObjectiveCExceptionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnosticObjectiveCExceptionReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCrashDiagnosticObjectiveCExceptionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXHistogram/title",
          "value": "MXHistogram"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXHistogram/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXHistogram"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXHistogram/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXHistogram"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code~1launchTaskMaxCount/title",
          "value": "MXErrorLaunchTaskMaxCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code~1launchTaskMaxCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorLaunchTaskMaxCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code/title",
          "value": "MXErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetaData/title",
          "value": "MXMetaData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetaData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetaData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXMetaData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXMetaData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAverage/title",
          "value": "MXAverage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAverage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAverage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXAverage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXAverage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXSignpostRecord/title",
          "value": "MXSignpostRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXSignpostRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXSignpostRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXSignpostRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXSignpostRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code~1launchTaskDuplicated/title",
          "value": "MXErrorLaunchTaskDuplicated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code~1launchTaskDuplicated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorLaunchTaskDuplicated"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metrickit/mxerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metrickit/mxerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
