{
  "abstract": [
    {
      "text": "A task with the same ID has already been started.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metrickit/documentation/MetricKit",
        "doc://com.apple.metrickit/documentation/MetricKit/MXError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskDuplicated"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11MXErrorCodeLeV20launchTaskDuplicatedSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "launchTaskDuplicated"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC11MXErrorCodeLeV",
        "text": "MXError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MXErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "MetricKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "launchTaskDuplicated"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "launchTaskDuplicated"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC11MXErrorCodeLeV",
              "text": "MXError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MXErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metrickit/documentation/MetricKit": {
      "abstract": [
        {
          "text": "Aggregate and analyze per-device reports on exception and crash diagnostics and on power and performance metrics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetricKit",
      "type": "topic",
      "url": "/documentation/metrickit"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError": {
      "abstract": [
        {
          "text": "Error domain for error handling of app metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXError"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXError"
        }
      ],
      "role": "symbol",
      "title": "MXError",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code": {
      "abstract": [
        {
          "text": "Error codes for error values from app metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MXError.Code",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/code"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskDuplicated": {
      "abstract": [
        {
          "text": "A task with the same ID has already been started.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launchTaskDuplicated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MXErrorCodeLeV",
          "text": "MXError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MXErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskDuplicated",
      "kind": "symbol",
      "role": "symbol",
      "title": "launchTaskDuplicated",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/launchtaskduplicated"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskInternalFailure": {
      "abstract": [
        {
          "text": "Internal failures happened inside the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launchTaskInternalFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MXErrorCodeLeV",
          "text": "MXError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MXErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskInternalFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "launchTaskInternalFailure",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/launchtaskinternalfailure"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskInvalidID": {
      "abstract": [
        {
          "text": "The task ID is a ",
          "type": "text"
        },
        {
          "code": "null",
          "type": "codeVoice"
        },
        {
          "text": " value or exceeds the maximum 128 character length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launchTaskInvalidID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MXErrorCodeLeV",
          "text": "MXError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MXErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskInvalidID",
      "kind": "symbol",
      "role": "symbol",
      "title": "launchTaskInvalidID",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/launchtaskinvalidid"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskMaxCount": {
      "abstract": [
        {
          "text": "Exceeded the maximum number of tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launchTaskMaxCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MXErrorCodeLeV",
          "text": "MXError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MXErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskMaxCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "launchTaskMaxCount",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/launchtaskmaxcount"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskPastDeadline": {
      "abstract": [
        {
          "text": "The start call was made too late.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launchTaskPastDeadline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MXErrorCodeLeV",
          "text": "MXError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MXErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskPastDeadline",
      "kind": "symbol",
      "role": "symbol",
      "title": "launchTaskPastDeadline",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/launchtaskpastdeadline"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskUnknown": {
      "abstract": [
        {
          "text": "The task hasn’t been started or has already been finished.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "launchTaskUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11MXErrorCodeLeV",
          "text": "MXError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MXErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskUnknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "launchTaskUnknown",
      "type": "topic",
      "url": "/documentation/metrickit/mxerror/launchtaskunknown"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXErrorDomain": {
      "abstract": [
        {
          "text": "Error domain for error values from app metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MXErrorDomain",
      "type": "topic",
      "url": "/documentation/metrickit/mxerrordomain"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-launch-error-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskInternalFailure",
        "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskInvalidID",
        "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskMaxCount",
        "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskPastDeadline",
        "doc://com.apple.metrickit/documentation/MetricKit/MXError/launchTaskUnknown",
        "doc://com.apple.metrickit/documentation/MetricKit/MXError/Code",
        "doc://com.apple.metrickit/documentation/MetricKit/MXErrorDomain"
      ],
      "title": "Getting the launch error properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code/title",
          "value": "MXErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXErrorDomain/title",
          "value": "MXErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metrickit/mxerror/launchtaskduplicated"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
