{
  "abstract": [
    {
      "text": "Tells the delegate that a home changed the name of a zone.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didUpdateNameFor:)-1k32g"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)HMHomeDelegate(im)home:didUpdateNameForZone:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "home"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HMHome",
        "text": "HMHome"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didUpdateNameFor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HMZone",
        "text": "HMZone"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "home:didUpdateNameForZone:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "home(_:didUpdateNameFor:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "home"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "home"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HMHome",
              "text": "HMHome"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didUpdateNameFor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "zone"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMZone",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HMZone",
              "text": "HMZone"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The home.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "home"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The zone whose name was changed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "zone"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHome": {
      "abstract": [
        {
          "text": "The primary unit of living space, typically composed of rooms organized into zones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "role": "symbol",
      "title": "HMHome",
      "type": "topic",
      "url": "/documentation/homekit/hmhome"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate": {
      "abstract": [
        {
          "text": "An interface that communicates changes to a home’s configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHomeDelegate"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHomeDelegate"
        }
      ],
      "role": "symbol",
      "title": "HMHomeDelegate",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-42aqd": {
      "abstract": [
        {
          "text": "Tells the delegate that a home added a new room.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMRoom",
          "text": "HMRoom"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-42aqd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "home:didAddRoom:"
        }
      ],
      "role": "symbol",
      "title": "home(_:didAdd:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/home(_:didadd:)-42aqd"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-6jcl7": {
      "abstract": [
        {
          "text": "Tells the delegate that a home added a new accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessory",
          "text": "HMAccessory"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-6jcl7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "home:didAddAccessory:"
        }
      ],
      "role": "symbol",
      "title": "home(_:didAdd:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/home(_:didadd:)-6jcl7"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-7vyoe": {
      "abstract": [
        {
          "text": "Tells the delegate that a home added a new zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMZone",
          "text": "HMZone"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-7vyoe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "home:didAddZone:"
        }
      ],
      "role": "symbol",
      "title": "home(_:didAdd:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/home(_:didadd:)-7vyoe"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-8q7jm": {
      "abstract": [
        {
          "text": "Tells the delegate that a home added a user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMUser",
          "text": "HMUser"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-8q7jm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "home:didAddUser:"
        }
      ],
      "role": "symbol",
      "title": "home(_:didAdd:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/home(_:didadd:)-8q7jm"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:to:)-4hiew": {
      "abstract": [
        {
          "text": "Tells the delegate that a home added a room to a zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMRoom",
          "text": "HMRoom"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMZone",
          "text": "HMZone"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:to:)-4hiew",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "home:didAddRoom:toZone:"
        }
      ],
      "role": "symbol",
      "title": "home(_:didAdd:to:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/home(_:didadd:to:)-4hiew"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-3fm38": {
      "abstract": [
        {
          "text": "Tells the delegate that a home removed a user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRemove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMUser",
          "text": "HMUser"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-3fm38",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "home:didRemoveUser:"
        }
      ],
      "role": "symbol",
      "title": "home(_:didRemove:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/home(_:didremove:)-3fm38"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-3if6s": {
      "abstract": [
        {
          "text": "Tells the delegate that a home removed a room.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRemove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMRoom",
          "text": "HMRoom"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-3if6s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "home:didRemoveRoom:"
        }
      ],
      "role": "symbol",
      "title": "home(_:didRemove:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/home(_:didremove:)-3if6s"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-3o8ta": {
      "abstract": [
        {
          "text": "Tells the delegate that a home removed a zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRemove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMZone",
          "text": "HMZone"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-3o8ta",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "home:didRemoveZone:"
        }
      ],
      "role": "symbol",
      "title": "home(_:didRemove:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/home(_:didremove:)-3o8ta"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-6plye": {
      "abstract": [
        {
          "text": "Tells the delegate that a home removed an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRemove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessory",
          "text": "HMAccessory"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-6plye",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "home:didRemoveAccessory:"
        }
      ],
      "role": "symbol",
      "title": "home(_:didRemove:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/home(_:didremove:)-6plye"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:from:)-8oz67": {
      "abstract": [
        {
          "text": "Tells the delegate that a home removed a room from a zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRemove"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMRoom",
          "text": "HMRoom"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMZone",
          "text": "HMZone"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:from:)-8oz67",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "home:didRemoveRoom:fromZone:"
        }
      ],
      "role": "symbol",
      "title": "home(_:didRemove:from:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/home(_:didremove:from:)-8oz67"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didUpdate:)-5fntk": {
      "abstract": [
        {
          "text": "Tells the delegate that the state of the home hub has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HMHomeHubState",
          "text": "HMHomeHubState"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didUpdate:)-5fntk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "home:didUpdateHomeHubState:"
        }
      ],
      "role": "symbol",
      "title": "home(_:didUpdate:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/home(_:didupdate:)-5fntk"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didUpdate:for:)": {
      "abstract": [
        {
          "text": "Tells the delegate that a home assigned an accessory to a different room.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMRoom",
          "text": "HMRoom"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessory",
          "text": "HMAccessory"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didUpdate:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "home:didUpdateRoom:forAccessory:"
        }
      ],
      "role": "symbol",
      "title": "home(_:didUpdate:for:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/home(_:didupdate:for:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didUpdateNameFor:)-1a110": {
      "abstract": [
        {
          "text": "Tells the delegate that a home updated the name of one of its rooms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdateNameFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMRoom",
          "text": "HMRoom"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didUpdateNameFor:)-1a110",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "home:didUpdateNameForRoom:"
        }
      ],
      "role": "symbol",
      "title": "home(_:didUpdateNameFor:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/home(_:didupdatenamefor:)-1a110"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didUpdateNameFor:)-1k32g": {
      "abstract": [
        {
          "text": "Tells the delegate that a home changed the name of a zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdateNameFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMZone",
          "text": "HMZone"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didUpdateNameFor:)-1k32g",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "home:didUpdateNameForZone:"
        }
      ],
      "role": "symbol",
      "title": "home(_:didUpdateNameFor:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/home(_:didupdatenamefor:)-1k32g"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/homeDidUpdateAccessControl(forCurrentUser:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the access control for the current user has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "homeDidUpdateAccessControl"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forCurrentUser"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/homeDidUpdateAccessControl(forCurrentUser:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "homeDidUpdateAccessControlForCurrentUser:"
        }
      ],
      "role": "symbol",
      "title": "homeDidUpdateAccessControl(forCurrentUser:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/homedidupdateaccesscontrol(forcurrentuser:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/homeDidUpdateName(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that a home’s name changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "homeDidUpdateName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMHome",
          "text": "HMHome"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/homeDidUpdateName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "homeDidUpdateName:"
        }
      ],
      "role": "symbol",
      "title": "homeDidUpdateName(_:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhomedelegate/homedidupdatename(_:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMZone": {
      "abstract": [
        {
          "text": "A collection of rooms that users think of as a single area, like upstairs or downstairs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMZone"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMZone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMZone"
        }
      ],
      "role": "symbol",
      "title": "HMZone",
      "type": "topic",
      "url": "/documentation/homekit/hmzone"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Observing-Home-Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/homeDidUpdateName(_:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-6jcl7",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didUpdate:for:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-6plye",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-42aqd",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didUpdateNameFor:)-1a110",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:to:)-4hiew",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:from:)-8oz67",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-3if6s",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-7vyoe",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-3o8ta",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-8q7jm",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-3fm38",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/homeDidUpdateAccessControl(forCurrentUser:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didUpdate:)-5fntk"
      ],
      "title": "Observing Home Configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "home:didUpdateNameForZone:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "home:didUpdateNameForZone:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Observing-Home-Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/homeDidUpdateName(_:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-6jcl7",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didUpdate:for:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-6plye",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-42aqd",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didUpdateNameFor:)-1a110",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:to:)-4hiew",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:from:)-8oz67",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-3if6s",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-7vyoe",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-3o8ta",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didAdd:)-8q7jm",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didRemove:)-3fm38",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/homeDidUpdateAccessControl(forCurrentUser:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeDelegate/home(_:didUpdate:)-5fntk"
              ],
              "title": "Observing Home Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "home:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HMHome",
                    "text": "HMHome"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "home"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didUpdateNameForZone:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMZone",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HMZone",
                    "text": "HMZone"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "zone"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The home.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "home"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The zone whose name was changed.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "zone"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didRemove:)-3fm38/title",
          "value": "home:didRemoveUser:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didRemove:)-3fm38/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "home:didRemoveUser:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didRemove:from:)-8oz67/title",
          "value": "home:didRemoveRoom:fromZone:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didRemove:from:)-8oz67/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "home:didRemoveRoom:fromZone:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didRemove:)-3if6s/title",
          "value": "home:didRemoveRoom:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didRemove:)-3if6s/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "home:didRemoveRoom:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didUpdateNameFor:)-1k32g/title",
          "value": "home:didUpdateNameForZone:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didUpdateNameFor:)-1k32g/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "home:didUpdateNameForZone:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didAdd:)-42aqd/title",
          "value": "home:didAddRoom:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didAdd:)-42aqd/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "home:didAddRoom:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMZone/title",
          "value": "HMZone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMZone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMZone/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didUpdate:for:)/title",
          "value": "home:didUpdateRoom:forAccessory:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didUpdate:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "home:didUpdateRoom:forAccessory:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/title",
          "value": "HMHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didRemove:)-6plye/title",
          "value": "home:didRemoveAccessory:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didRemove:)-6plye/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "home:didRemoveAccessory:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1homeDidUpdateName(_:)/title",
          "value": "homeDidUpdateName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1homeDidUpdateName(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "homeDidUpdateName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didAdd:to:)-4hiew/title",
          "value": "home:didAddRoom:toZone:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didAdd:to:)-4hiew/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "home:didAddRoom:toZone:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didUpdate:)-5fntk/title",
          "value": "home:didUpdateHomeHubState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didUpdate:)-5fntk/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "home:didUpdateHomeHubState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didAdd:)-8q7jm/title",
          "value": "home:didAddUser:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didAdd:)-8q7jm/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "home:didAddUser:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didAdd:)-6jcl7/title",
          "value": "home:didAddAccessory:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didAdd:)-6jcl7/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "home:didAddAccessory:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didRemove:)-3o8ta/title",
          "value": "home:didRemoveZone:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didRemove:)-3o8ta/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "home:didRemoveZone:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1homeDidUpdateAccessControl(forCurrentUser:)/title",
          "value": "homeDidUpdateAccessControlForCurrentUser:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1homeDidUpdateAccessControl(forCurrentUser:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "homeDidUpdateAccessControlForCurrentUser:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate/title",
          "value": "HMHomeDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didUpdateNameFor:)-1a110/title",
          "value": "home:didUpdateNameForRoom:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didUpdateNameFor:)-1a110/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "home:didUpdateNameForRoom:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didAdd:)-7vyoe/title",
          "value": "home:didAddZone:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeDelegate~1home(_:didAdd:)-7vyoe/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "home:didAddZone:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmhomedelegate/home(_:didupdatenamefor:)-1k32g"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmhomedelegate/home(_:didupdatenamefor:)-1k32g"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
