{
  "abstract": [
    {
      "text": "The system couldn’t determine the device’s placement.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/unknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKDevicePlacementSide@HKDevicePlacementSideUnknown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unknown"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKDevicePlacementSideUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKDevicePlacementSide.unknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unknown"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide": {
      "abstract": [
        {
          "text": "Values that indicate the placement of the device that measured a sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKDevicePlacementSide"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePlacementSide"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePlacementSide",
      "type": "topic",
      "url": "/documentation/healthkit/hkdeviceplacementside"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/central": {
      "abstract": [
        {
          "text": "A device predominately located near the center of the body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "central"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/central",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePlacementSideCentral"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePlacementSide.central",
      "type": "topic",
      "url": "/documentation/healthkit/hkdeviceplacementside/central"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/left": {
      "abstract": [
        {
          "text": "A device predominately located on the left side.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePlacementSideLeft"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePlacementSide.left",
      "type": "topic",
      "url": "/documentation/healthkit/hkdeviceplacementside/left"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/right": {
      "abstract": [
        {
          "text": "A device predominately located on the right side.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePlacementSideRight"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePlacementSide.right",
      "type": "topic",
      "url": "/documentation/healthkit/hkdeviceplacementside/right"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/unknown": {
      "abstract": [
        {
          "text": "The system couldn’t determine the device’s placement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKDevicePlacementSideUnknown"
        }
      ],
      "role": "symbol",
      "title": "HKDevicePlacementSide.unknown",
      "type": "topic",
      "url": "/documentation/healthkit/hkdeviceplacementside/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Placements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/central",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/left",
        "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/right"
      ],
      "title": "Placements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKDevicePlacementSideUnknown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSideUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Placements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/central",
                "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/left",
                "doc://com.apple.healthkit/documentation/HealthKit/HKDevicePlacementSide/right"
              ],
              "title": "Placements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKDevicePlacementSideUnknown"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1left/title",
          "value": "HKDevicePlacementSideLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSideLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1central/title",
          "value": "HKDevicePlacementSideCentral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1central/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSideCentral"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1right/title",
          "value": "HKDevicePlacementSideRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSideRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1unknown/title",
          "value": "HKDevicePlacementSideUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSideUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide/title",
          "value": "HKDevicePlacementSide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKDevicePlacementSide/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKDevicePlacementSide"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkdeviceplacementside/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkdeviceplacementside/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
