{
  "abstract": [
    {
      "text": "A bitwise OR combination of the features of this library.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Apple has deprecated this property and will remove it in future versions of the framework.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/features"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ITLibrary(py)features",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "features"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@ITLibExportFeature",
        "text": "ITLibExportFeature"
      }
    ],
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "features"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "features"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "features"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibExportFeature",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ITLibExportFeature",
              "text": "ITLibExportFeature"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibExportFeature": {
      "abstract": [
        {
          "text": "These constants describe the features that an iTunes library supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibExportFeature"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibExportFeature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibExportFeature"
        }
      ],
      "role": "symbol",
      "title": "ITLibExportFeature",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibexportfeature"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary": {
      "abstract": [
        {
          "text": "This class serves as the entry point to the iTunesLibrary framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibrary"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibrary"
        }
      ],
      "role": "symbol",
      "title": "ITLibrary",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/features": {
      "abstract": [
        {
          "text": "A bitwise OR combination of the features of this library.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "features"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ITLibExportFeature",
          "text": "ITLibExportFeature"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/features",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "features"
        }
      ],
      "role": "symbol",
      "title": "features",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/features"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/musicFolderLocation": {
      "abstract": [
        {
          "text": "The location of the iTunes music folder.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "musicFolderLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/musicFolderLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "musicFolderLocation"
        }
      ],
      "role": "symbol",
      "title": "musicFolderLocation",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/musicfolderlocation"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibExportFeature",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/musicFolderLocation"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "features"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "features"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibExportFeature",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/musicFolderLocation"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibExportFeature",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@ITLibExportFeature",
                    "text": "ITLibExportFeature"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "features"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Apple has deprecated this property and will remove it in future versions of the framework.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibExportFeature/title",
          "value": "ITLibExportFeature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibExportFeature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibExportFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibExportFeature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibExportFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1features/title",
          "value": "features"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1features/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "features"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1musicFolderLocation/title",
          "value": "musicFolderLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1musicFolderLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "musicFolderLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary/title",
          "value": "ITLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibrary"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary/itlibrary/features"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary/itlibrary/features"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
