{
  "abstract": [
    {
      "text": "Initializes an instance of ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " that can retrieve media entities.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/init(apiVersion:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ITLibrary(im)initWithAPIVersion:error:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "apiVersion"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ") "
      },
      {
        "kind": "keyword",
        "text": "throws"
      }
    ],
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithAPIVersion:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(apiVersion:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "apiVersion"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "requestedAPIVersion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The version of the iTunesLibrary API that the app is requesting. Provide ",
                  "type": "text"
                },
                {
                  "code": "\"1.0\"",
                  "type": "codeVoice"
                },
                {
                  "text": " if unknown.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "requestedAPIVersion"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance that can retrieve media entities, or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the method fails.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "During initialization of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class, the system reads and parses the default iTunes database for the current user. All media entities cache in memory until deallocation of the object occurs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 1.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "#import <iTunesLibrary/ITLibrary.h>",
            " ",
            "NSError * error = nil;",
            "ITLibrary* library = [[ITLibrary alloc] initWithAPIVersion:@\"1.0\" error:&error];",
            "if (library)",
            "{",
            "  NSArray playlists = library.allPlaylists; //  <- NSArray of ITLibPlaylist",
            "  NSArray mediaItems = library.allMediaItems; //  <- NSArray of ITLibMediaItem",
            "}"
          ],
          "syntax": "objc",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibInitOptions": {
      "abstract": [
        {
          "text": "These constants describe initialization options for an iTunes library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibInitOptions"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibInitOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibInitOptions"
        }
      ],
      "role": "symbol",
      "title": "ITLibInitOptions",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibinitoptions"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary": {
      "abstract": [
        {
          "text": "This class serves as the entry point to the iTunesLibrary framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibrary"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibrary"
        }
      ],
      "role": "symbol",
      "title": "ITLibrary",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/init(apiVersion:)": {
      "abstract": [
        {
          "text": "Initializes an instance of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " that can retrieve media entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "apiVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/init(apiVersion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAPIVersion:error:"
        }
      ],
      "role": "symbol",
      "title": "init(apiVersion:)",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/init(apiversion:)"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/init(apiVersion:options:)": {
      "abstract": [
        {
          "text": "Initializes an instance of ",
          "type": "text"
        },
        {
          "code": "ITLibrary",
          "type": "codeVoice"
        },
        {
          "text": " that can retrieve media entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "apiVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ITLibInitOptions",
          "text": "ITLibInitOptions"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/init(apiVersion:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAPIVersion:options:error:"
        }
      ],
      "role": "symbol",
      "title": "init(apiVersion:options:)",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/init(apiversion:options:)"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/libraryWithAPIVersion:error:": {
      "abstract": [
        {
          "text": "Creates and initializes an instance of ",
          "type": "text"
        },
        {
          "code": "ITLibrary",
          "type": "codeVoice"
        },
        {
          "text": " that can retrieve media entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "libraryWithAPIVersion:error:"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/libraryWithAPIVersion:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "libraryWithAPIVersion:error:"
        }
      ],
      "role": "symbol",
      "title": "libraryWithAPIVersion:error:",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/librarywithapiversion:error:"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/libraryWithAPIVersion:options:error:": {
      "abstract": [
        {
          "text": "Creates and initializes an instance of ITLibrary that can retrieve media entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "libraryWithAPIVersion:options:error:"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/libraryWithAPIVersion:options:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "libraryWithAPIVersion:options:error:"
        }
      ],
      "role": "symbol",
      "title": "libraryWithAPIVersion:options:error:",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibrary/librarywithapiversion:options:error:"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/init(apiVersion:options:)",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibInitOptions"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithAPIVersion:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAPIVersion:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/init(apiVersion:options:)",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/libraryWithAPIVersion:error:",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary/libraryWithAPIVersion:options:error:",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibInitOptions"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithAPIVersion:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "requestedAPIVersion"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The version of the iTunesLibrary API that the app is requesting. Provide ",
                        "type": "text"
                      },
                      {
                        "code": "\"1.0\"",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if unknown.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "requestedAPIVersion"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to a variable that receives an ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " if this method fails. Can be ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if the error isn’t applicable to the caller.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibrary",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " instance that can retrieve media entities, or ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if the method fails.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibInitOptions/title",
          "value": "ITLibInitOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibInitOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibInitOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibInitOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibInitOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1init(apiVersion:options:)/title",
          "value": "initWithAPIVersion:options:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1init(apiVersion:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAPIVersion:options:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1init(apiVersion:)/title",
          "value": "initWithAPIVersion:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary~1init(apiVersion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAPIVersion:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary/title",
          "value": "ITLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibrary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibrary"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary/itlibrary/init(apiversion:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary/itlibrary/init(apiversion:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
