{
  "abstract": [
    {
      "text": "The audio format list items that describe the audio formats.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioFormatList"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreMedia",
    "externalID": "s:So22CMFormatDescriptionRefa9CoreMediaE15audioFormatListSaySo05AudiogH4ItemVGvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "audioFormatList"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@AudioFormatListItem",
        "text": "AudioFormatListItem"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "audioFormatList"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "audioFormatList"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioFormatListItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@AudioFormatListItem",
              "text": "AudioFormatListItem"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription": {
      "abstract": [
        {
          "text": "An object that describes a media format descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioChannelLayout": {
      "abstract": [
        {
          "text": "The audio channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreAudio07ManagedB13ChannelLayoutV",
          "text": "ManagedAudioChannelLayout"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioChannelLayout",
      "kind": "symbol",
      "role": "symbol",
      "title": "audioChannelLayout",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/audiochannellayout"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioFormatList": {
      "abstract": [
        {
          "text": "The audio format list items that describe the audio formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioFormatList"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioFormatListItem",
          "text": "AudioFormatListItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioFormatList",
      "kind": "symbol",
      "role": "symbol",
      "title": "audioFormatList",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/audioformatlist"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioStreamBasicDescription": {
      "abstract": [
        {
          "text": "The audio stream description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioStreamBasicDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamBasicDescription",
          "text": "AudioStreamBasicDescription"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioStreamBasicDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "audioStreamBasicDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/audiostreambasicdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/dimensions": {
      "abstract": [
        {
          "text": "The encoded pixels not including the pixel aspect ratio or clean aperture tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/dimensions",
      "kind": "symbol",
      "role": "symbol",
      "title": "dimensions",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/dimensions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/extensions-swift.property": {
      "abstract": [
        {
          "text": "A dictionary that contains all of the extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE10ExtensionsV",
          "text": "Extensions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/extensions-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "extensions",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/extensions-swift.property"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/frameDuration": {
      "abstract": [
        {
          "text": "The duration of each frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/frameDuration",
      "kind": "symbol",
      "role": "symbol",
      "title": "frameDuration",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/frameduration"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/frameQuanta": {
      "abstract": [
        {
          "text": "The frames per second for the time code, or the frame per tick for counter mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameQuanta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/frameQuanta",
      "kind": "symbol",
      "role": "symbol",
      "title": "frameQuanta",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/framequanta"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/identifiers": {
      "abstract": [
        {
          "text": "An array of metadata identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/identifiers",
      "kind": "symbol",
      "role": "symbol",
      "title": "identifiers",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/identifiers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/magicCookie": {
      "abstract": [
        {
          "text": "A copy of the magic cookie, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magicCookie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/magicCookie",
      "kind": "symbol",
      "role": "symbol",
      "title": "magicCookie",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/magiccookie"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mediaSubType-swift.property": {
      "abstract": [
        {
          "text": "The media subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaSubType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE0E7SubTypeV",
          "text": "MediaSubType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mediaSubType-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "mediaSubType",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/mediasubtype-swift.property"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mediaType-swift.property": {
      "abstract": [
        {
          "text": "The media type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE0E4TypeV",
          "text": "MediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mediaType-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "mediaType",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/mediatype-swift.property"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mostCompatibleFormat": {
      "abstract": [
        {
          "text": "The most compatible audio format list item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mostCompatibleFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioFormatListItem",
          "text": "AudioFormatListItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mostCompatibleFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "mostCompatibleFormat",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/mostcompatibleformat"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/nalUnitHeaderLength": {
      "abstract": [
        {
          "text": "The size, in bytes, of the unit length field in an AVC or HEVC video sample or parameter set sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nalUnitHeaderLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/nalUnitHeaderLength",
      "kind": "symbol",
      "role": "symbol",
      "title": "nalUnitHeaderLength",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/nalunitheaderlength"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/parameterSets": {
      "abstract": [
        {
          "text": "The parameter sets that an H.264 or HEVC format contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameterSets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE22ParameterSetCollectionV",
          "text": "ParameterSetCollection"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/parameterSets",
      "kind": "symbol",
      "role": "symbol",
      "title": "parameterSets",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/parametersets"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/richestDecodableFormat": {
      "abstract": [
        {
          "text": "The audio format list item the system validates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "richestDecodableFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioFormatListItem",
          "text": "AudioFormatListItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/richestDecodableFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "richestDecodableFormat",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/richestdecodableformat"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/timeCodeFlags": {
      "abstract": [
        {
          "text": "The flags for the available time codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeCodeFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE8TimeCodeV",
          "text": "TimeCode"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE8TimeCodeV4FlagV",
          "text": "Flag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/timeCodeFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "timeCodeFlags",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription/timecodeflags"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@AudioFormatListItem": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioFormatListItem"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@AudioFormatListItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "AudioFormatListItem",
      "type": "topic",
      "url": "/documentation/CoreAudioTypes/AudioFormatListItem"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Format-Descriptions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioStreamBasicDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/audioChannelLayout",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/dimensions",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/extensions-swift.property",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/frameDuration",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/frameQuanta",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/identifiers",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/magicCookie",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mediaSubType-swift.property",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mediaType-swift.property",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/mostCompatibleFormat",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/nalUnitHeaderLength",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/parameterSets",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/richestDecodableFormat",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription/timeCodeFlags"
      ],
      "title": "Inspecting Format Descriptions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@S@AudioFormatListItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AudioFormatListItem"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMFormatDescription/title",
          "value": "CMFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFormatDescriptionRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmformatdescription/audioformatlist"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
