{
  "abstract": [
    {
      "text": "The content has no particular shape.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvservices/documentation/TVServices",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/none"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@TVContentItemImageShape@TVContentItemImageShapeNone",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "none"
      }
    ],
    "modules": [
      {
        "name": "TV Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVContentItemImageShapeNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "TVContentItemImageShape.none"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "none"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvservices/documentation/TVServices": {
      "abstract": [
        {
          "text": "Display content and descriptions, provide channel guides, and support multiple users on Apple TV.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices",
      "kind": "symbol",
      "role": "collection",
      "title": "TV Services",
      "type": "topic",
      "url": "/documentation/tvservices"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape": {
      "abstract": [
        {
          "text": "An enumerated type that identifies the shape in which the content item should be displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVContentItemImageShape"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShape"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/HDTV": {
      "abstract": [
        {
          "text": "The content is high-definition television content with a width:height ratio of ",
          "type": "text"
        },
        {
          "code": "16:9",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HDTV"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/HDTV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShapeHDTV"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape.HDTV",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape/hdtv"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/SDTV": {
      "abstract": [
        {
          "text": "The content is standard-definition television content with a width:height ratio of ",
          "type": "text"
        },
        {
          "code": "4:3",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SDTV"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/SDTV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShapeSDTV"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape.SDTV",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape/sdtv"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/extraWide": {
      "abstract": [
        {
          "text": "The content has a width:height ratio of ",
          "type": "text"
        },
        {
          "code": "80:27",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extraWide"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/extraWide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShapeExtraWide"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape.extraWide",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape/extrawide"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/none": {
      "abstract": [
        {
          "text": "The content has no particular shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShapeNone"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape.none",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape/none"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/poster": {
      "abstract": [
        {
          "text": "The content has a width:height ratio of ",
          "type": "text"
        },
        {
          "code": "2:3",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "poster"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/poster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShapePoster"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape.poster",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape/poster"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/square": {
      "abstract": [
        {
          "text": "The content has a width:height ratio of ",
          "type": "text"
        },
        {
          "code": "1:1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "square"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/square",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShapeSquare"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape.square",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape/square"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/wide": {
      "abstract": [
        {
          "text": "The content has a width:height ratio of ",
          "type": "text"
        },
        {
          "code": "8:3",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wide"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/wide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVContentItemImageShapeWide"
        }
      ],
      "role": "symbol",
      "title": "TVContentItemImageShape.wide",
      "type": "topic",
      "url": "/documentation/tvservices/tvcontentitemimageshape/wide"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/poster",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/square",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/SDTV",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/HDTV",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/wide",
        "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/extraWide"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVContentItemImageShapeNone"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShapeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvservices/documentation/TVServices",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/poster",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/square",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/SDTV",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/HDTV",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/wide",
                "doc://com.apple.tvservices/documentation/TVServices/TVContentItemImageShape/extraWide"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "TVContentItemImageShapeNone"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape/title",
          "value": "TVContentItemImageShape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1none/title",
          "value": "TVContentItemImageShapeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShapeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1square/title",
          "value": "TVContentItemImageShapeSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1square/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShapeSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1SDTV/title",
          "value": "TVContentItemImageShapeSDTV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1SDTV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShapeSDTV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1poster/title",
          "value": "TVContentItemImageShapePoster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1poster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShapePoster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1wide/title",
          "value": "TVContentItemImageShapeWide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1wide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShapeWide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1HDTV/title",
          "value": "TVContentItemImageShapeHDTV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1HDTV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShapeHDTV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1extraWide/title",
          "value": "TVContentItemImageShapeExtraWide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVContentItemImageShape~1extraWide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVContentItemImageShapeExtraWide"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvservices/tvcontentitemimageshape/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvservices/tvcontentitemimageshape/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
