{
  "abstract": [
    {
      "text": "Autoresize all columns by distributing space equally, simultaneously.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/uniformColumnAutoresizingStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTableViewColumnAutoresizingStyle@NSTableViewUniformColumnAutoresizingStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "uniformColumnAutoresizingStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTableViewUniformColumnAutoresizingStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSTableView.ColumnAutoresizingStyle.uniformColumnAutoresizingStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "uniformColumnAutoresizingStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView": {
      "abstract": [
        {
          "text": "A set of related records, displayed in rows that represent individual records and columns that represent the attributes of those records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableView"
        }
      ],
      "role": "symbol",
      "title": "NSTableView",
      "type": "topic",
      "url": "/documentation/appkit/nstableview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum": {
      "abstract": [
        {
          "text": "The following constants specify the autoresizing styles. These constants are used by the  ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/columnAutoresizingStyle-swift.property",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColumnAutoresizingStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColumnAutoresizingStyle"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.ColumnAutoresizingStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/columnautoresizingstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/firstColumnOnlyAutoresizingStyle": {
      "abstract": [
        {
          "text": "Autoresize only the first table column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstColumnOnlyAutoresizingStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/firstColumnOnlyAutoresizingStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewFirstColumnOnlyAutoresizingStyle"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.ColumnAutoresizingStyle.firstColumnOnlyAutoresizingStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/columnautoresizingstyle-swift.enum/firstcolumnonlyautoresizingstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/lastColumnOnlyAutoresizingStyle": {
      "abstract": [
        {
          "text": "Autoresize only the last table column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastColumnOnlyAutoresizingStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/lastColumnOnlyAutoresizingStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewLastColumnOnlyAutoresizingStyle"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.ColumnAutoresizingStyle.lastColumnOnlyAutoresizingStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/columnautoresizingstyle-swift.enum/lastcolumnonlyautoresizingstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/noColumnAutoresizing": {
      "abstract": [
        {
          "text": "Disable table column autoresizing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noColumnAutoresizing"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/noColumnAutoresizing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewNoColumnAutoresizing"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.ColumnAutoresizingStyle.noColumnAutoresizing",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/columnautoresizingstyle-swift.enum/nocolumnautoresizing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/reverseSequentialColumnAutoresizingStyle": {
      "abstract": [
        {
          "text": "Autoresize each table column sequentially, from the first auto-resizable column to the last auto-resizable column; proceed to the next column when the current column has reached its minimum or maximum size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverseSequentialColumnAutoresizingStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/reverseSequentialColumnAutoresizingStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewReverseSequentialColumnAutoresizingStyle"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.ColumnAutoresizingStyle.reverseSequentialColumnAutoresizingStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/columnautoresizingstyle-swift.enum/reversesequentialcolumnautoresizingstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/sequentialColumnAutoresizingStyle": {
      "abstract": [
        {
          "text": "Autoresize each table column sequentially, from the last auto-resizable column to the first auto-resizable column; proceed to the next column when the current column has reached its minimum or maximum size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sequentialColumnAutoresizingStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/sequentialColumnAutoresizingStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewSequentialColumnAutoresizingStyle"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.ColumnAutoresizingStyle.sequentialColumnAutoresizingStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/columnautoresizingstyle-swift.enum/sequentialcolumnautoresizingstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/uniformColumnAutoresizingStyle": {
      "abstract": [
        {
          "text": "Autoresize all columns by distributing space equally, simultaneously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uniformColumnAutoresizingStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/uniformColumnAutoresizingStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTableViewUniformColumnAutoresizingStyle"
        }
      ],
      "role": "symbol",
      "title": "NSTableView.ColumnAutoresizingStyle.uniformColumnAutoresizingStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/columnautoresizingstyle-swift.enum/uniformcolumnautoresizingstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTableView/columnAutoresizingStyle-swift.property": {
      "abstract": [
        {
          "text": "The table view’s column autoresizing style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columnAutoresizingStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTableView",
          "text": "NSTableView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTableViewColumnAutoresizingStyle",
          "text": "ColumnAutoresizingStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTableView/columnAutoresizingStyle-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columnAutoresizingStyle"
        }
      ],
      "role": "symbol",
      "title": "columnAutoresizingStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstableview/columnautoresizingstyle-swift.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/noColumnAutoresizing",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/sequentialColumnAutoresizingStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/reverseSequentialColumnAutoresizingStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/lastColumnOnlyAutoresizingStyle",
        "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/firstColumnOnlyAutoresizingStyle"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTableViewUniformColumnAutoresizingStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewUniformColumnAutoresizingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/noColumnAutoresizing",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/sequentialColumnAutoresizingStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/reverseSequentialColumnAutoresizingStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/lastColumnOnlyAutoresizingStyle",
                "doc://com.apple.appkit/documentation/AppKit/NSTableView/ColumnAutoresizingStyle-swift.enum/firstColumnOnlyAutoresizingStyle"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTableViewUniformColumnAutoresizingStyle"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1ColumnAutoresizingStyle-swift.enum/title",
          "value": "NSTableViewColumnAutoresizingStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1ColumnAutoresizingStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewColumnAutoresizingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1ColumnAutoresizingStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewColumnAutoresizingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1ColumnAutoresizingStyle-swift.enum~1firstColumnOnlyAutoresizingStyle/title",
          "value": "NSTableViewFirstColumnOnlyAutoresizingStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1ColumnAutoresizingStyle-swift.enum~1firstColumnOnlyAutoresizingStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewFirstColumnOnlyAutoresizingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1ColumnAutoresizingStyle-swift.enum~1lastColumnOnlyAutoresizingStyle/title",
          "value": "NSTableViewLastColumnOnlyAutoresizingStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1ColumnAutoresizingStyle-swift.enum~1lastColumnOnlyAutoresizingStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewLastColumnOnlyAutoresizingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1ColumnAutoresizingStyle-swift.enum~1reverseSequentialColumnAutoresizingStyle/title",
          "value": "NSTableViewReverseSequentialColumnAutoresizingStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1ColumnAutoresizingStyle-swift.enum~1reverseSequentialColumnAutoresizingStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewReverseSequentialColumnAutoresizingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1ColumnAutoresizingStyle-swift.enum~1sequentialColumnAutoresizingStyle/title",
          "value": "NSTableViewSequentialColumnAutoresizingStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1ColumnAutoresizingStyle-swift.enum~1sequentialColumnAutoresizingStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewSequentialColumnAutoresizingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/title",
          "value": "NSTableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1ColumnAutoresizingStyle-swift.enum~1noColumnAutoresizing/title",
          "value": "NSTableViewNoColumnAutoresizing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1ColumnAutoresizingStyle-swift.enum~1noColumnAutoresizing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewNoColumnAutoresizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1ColumnAutoresizingStyle-swift.enum~1uniformColumnAutoresizingStyle/title",
          "value": "NSTableViewUniformColumnAutoresizingStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1ColumnAutoresizingStyle-swift.enum~1uniformColumnAutoresizingStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTableViewUniformColumnAutoresizingStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1columnAutoresizingStyle-swift.property/title",
          "value": "columnAutoresizingStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTableView~1columnAutoresizingStyle-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "columnAutoresizingStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstableview/columnautoresizingstyle-swift.enum/uniformcolumnautoresizingstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstableview/columnautoresizingstyle-swift.enum/uniformcolumnautoresizingstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
