{
  "abstract": [
    {
      "text": "No additional effects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSColor",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/none"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSColorSystemEffect@NSColorSystemEffectNone",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "none"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSColorSystemEffectNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSColor.SystemEffect.none"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "none"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity (alpha value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "role": "symbol",
      "title": "NSColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect": {
      "abstract": [
        {
          "text": "Constants for user interactions that change the appearance of a view or control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SystemEffect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SystemEffect"
        }
      ],
      "role": "symbol",
      "title": "NSColor.SystemEffect",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemeffect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/deepPressed": {
      "abstract": [
        {
          "text": "The color that indicates the item received a deep press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deepPressed"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/deepPressed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSystemEffectDeepPressed"
        }
      ],
      "role": "symbol",
      "title": "NSColor.SystemEffect.deepPressed",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemeffect/deeppressed"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/disabled": {
      "abstract": [
        {
          "text": "The color that indicates the item is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disabled"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/disabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSystemEffectDisabled"
        }
      ],
      "role": "symbol",
      "title": "NSColor.SystemEffect.disabled",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemeffect/disabled"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/none": {
      "abstract": [
        {
          "text": "No additional effects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSystemEffectNone"
        }
      ],
      "role": "symbol",
      "title": "NSColor.SystemEffect.none",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemeffect/none"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/pressed": {
      "abstract": [
        {
          "text": "The color that indicates the item was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pressed"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/pressed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSystemEffectPressed"
        }
      ],
      "role": "symbol",
      "title": "NSColor.SystemEffect.pressed",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemeffect/pressed"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/rollover": {
      "abstract": [
        {
          "text": "The color that indicates the mouse rolled over the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rollover"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/rollover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSystemEffectRollover"
        }
      ],
      "role": "symbol",
      "title": "NSColor.SystemEffect.rollover",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/systemeffect/rollover"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Appearances",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/pressed",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/deepPressed",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/disabled",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/rollover"
      ],
      "title": "Appearances"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSColorSystemEffectNone"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSystemEffectNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Appearances",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/pressed",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/deepPressed",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/disabled",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/SystemEffect/rollover"
              ],
              "title": "Appearances"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSColorSystemEffectNone"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1SystemEffect~1none/title",
          "value": "NSColorSystemEffectNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1SystemEffect~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSystemEffectNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/title",
          "value": "NSColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1SystemEffect~1deepPressed/title",
          "value": "NSColorSystemEffectDeepPressed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1SystemEffect~1deepPressed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSystemEffectDeepPressed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1SystemEffect~1rollover/title",
          "value": "NSColorSystemEffectRollover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1SystemEffect~1rollover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSystemEffectRollover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1SystemEffect~1pressed/title",
          "value": "NSColorSystemEffectPressed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1SystemEffect~1pressed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSystemEffectPressed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1SystemEffect~1disabled/title",
          "value": "NSColorSystemEffectDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1SystemEffect~1disabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSystemEffectDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1SystemEffect/title",
          "value": "NSColorSystemEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1SystemEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSystemEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1SystemEffect/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSystemEffect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscolor/systemeffect/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscolor/systemeffect/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
