{
  "abstract": [
    {
      "text": "Keys used to specify items in a dictionary of peripheral advertisement data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/advertisement-data-retrieval-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Advertisement Data Retrieval Keys"
  },
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataIsConnectable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the advertising event type is connectable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataIsConnectable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataIsConnectable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataIsConnectable"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataIsConnectable",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdataisconnectable"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey": {
      "abstract": [
        {
          "text": "The local name of a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataLocalNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataLocalNameKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataLocalNameKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdatalocalnamekey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataManufacturerDataKey": {
      "abstract": [
        {
          "text": "The manufacturer data of a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataManufacturerDataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataManufacturerDataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataManufacturerDataKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataManufacturerDataKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdatamanufacturerdatakey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey": {
      "abstract": [
        {
          "text": "An array of UUIDs found in the overflow area of the advertisement data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataOverflowServiceUUIDsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataOverflowServiceUUIDsKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataOverflowServiceUUIDsKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdataoverflowserviceuuidskey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceDataKey": {
      "abstract": [
        {
          "text": "A dictionary that contains service-specific advertisement data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataServiceDataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceDataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataServiceDataKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataServiceDataKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdataservicedatakey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey": {
      "abstract": [
        {
          "text": "An array of service UUIDs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataServiceUUIDsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataServiceUUIDsKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataServiceUUIDsKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdataserviceuuidskey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataSolicitedServiceUUIDsKey": {
      "abstract": [
        {
          "text": "An array of solicited service UUIDs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataSolicitedServiceUUIDsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataSolicitedServiceUUIDsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataSolicitedServiceUUIDsKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataSolicitedServiceUUIDsKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdatasolicitedserviceuuidskey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataTxPowerLevelKey": {
      "abstract": [
        {
          "text": "The transmit power of a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataTxPowerLevelKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataTxPowerLevelKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataTxPowerLevelKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataTxPowerLevelKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdatatxpowerlevelkey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate": {
      "abstract": [
        {
          "text": "A protocol that provides updates for the discovery and management of peripheral devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBCentralManagerDelegate"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBCentralManagerDelegate"
        }
      ],
      "role": "symbol",
      "title": "CBCentralManagerDelegate",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbcentralmanagerdelegate"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didDiscover:advertisementData:rssi:)": {
      "abstract": [
        {
          "text": "Tells the delegate the central manager discovered a peripheral while scanning for devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centralManager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBCentralManager",
          "text": "CBCentralManager"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didDiscover"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBPeripheral",
          "text": "CBPeripheral"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "advertisementData"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "rssi"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didDiscover:advertisementData:rssi:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centralManager:didDiscoverPeripheral:advertisementData:RSSI:"
        }
      ],
      "role": "symbol",
      "title": "centralManager(_:didDiscover:advertisementData:rssi:)",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbcentralmanagerdelegate/centralmanager(_:diddiscover:advertisementdata:rssi:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Discovering-and-Retrieving-Peripherals",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didDiscover:advertisementData:rssi:)"
      ],
      "title": "Discovering and Retrieving Peripherals"
    }
  ],
  "topicSections": [
    {
      "anchor": "Advertisement-Keys",
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataManufacturerDataKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceDataKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataTxPowerLevelKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataIsConnectable",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataSolicitedServiceUUIDsKey"
      ],
      "title": "Advertisement Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Advertisement-Keys",
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataManufacturerDataKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceDataKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataTxPowerLevelKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataIsConnectable",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataSolicitedServiceUUIDsKey"
              ],
              "title": "Advertisement Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Discovering-and-Retrieving-Peripherals",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManagerDelegate/centralManager(_:didDiscover:advertisementData:rssi:)"
              ],
              "title": "Discovering and Retrieving Peripherals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataTxPowerLevelKey/title",
          "value": "CBAdvertisementDataTxPowerLevelKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataTxPowerLevelKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataTxPowerLevelKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataManufacturerDataKey/title",
          "value": "CBAdvertisementDataManufacturerDataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataManufacturerDataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataManufacturerDataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataServiceDataKey/title",
          "value": "CBAdvertisementDataServiceDataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataServiceDataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataServiceDataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataOverflowServiceUUIDsKey/title",
          "value": "CBAdvertisementDataOverflowServiceUUIDsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataOverflowServiceUUIDsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataOverflowServiceUUIDsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataServiceUUIDsKey/title",
          "value": "CBAdvertisementDataServiceUUIDsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataServiceUUIDsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataServiceUUIDsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataSolicitedServiceUUIDsKey/title",
          "value": "CBAdvertisementDataSolicitedServiceUUIDsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataSolicitedServiceUUIDsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataSolicitedServiceUUIDsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate/title",
          "value": "CBCentralManagerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBCentralManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBCentralManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataIsConnectable/title",
          "value": "CBAdvertisementDataIsConnectable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataIsConnectable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataIsConnectable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:didDiscover:advertisementData:rssi:)/title",
          "value": "centralManager:didDiscoverPeripheral:advertisementData:RSSI:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManagerDelegate~1centralManager(_:didDiscover:advertisementData:rssi:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "centralManager:didDiscoverPeripheral:advertisementData:RSSI:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataLocalNameKey/title",
          "value": "CBAdvertisementDataLocalNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataLocalNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataLocalNameKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/advertisement-data-retrieval-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corebluetooth/advertisement-data-retrieval-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
