{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/advertising-data"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Advertising Data"
  },
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataIsConnectable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the advertising event type is connectable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataIsConnectable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataIsConnectable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataIsConnectable"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataIsConnectable",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdataisconnectable"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey": {
      "abstract": [
        {
          "text": "The local name of a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataLocalNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataLocalNameKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataLocalNameKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdatalocalnamekey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataManufacturerDataKey": {
      "abstract": [
        {
          "text": "The manufacturer data of a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataManufacturerDataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataManufacturerDataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataManufacturerDataKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataManufacturerDataKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdatamanufacturerdatakey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey": {
      "abstract": [
        {
          "text": "An array of UUIDs found in the overflow area of the advertisement data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataOverflowServiceUUIDsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataOverflowServiceUUIDsKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataOverflowServiceUUIDsKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdataoverflowserviceuuidskey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceDataKey": {
      "abstract": [
        {
          "text": "A dictionary that contains service-specific advertisement data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataServiceDataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceDataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataServiceDataKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataServiceDataKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdataservicedatakey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey": {
      "abstract": [
        {
          "text": "An array of service UUIDs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataServiceUUIDsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataServiceUUIDsKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataServiceUUIDsKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdataserviceuuidskey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataSolicitedServiceUUIDsKey": {
      "abstract": [
        {
          "text": "An array of solicited service UUIDs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataSolicitedServiceUUIDsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataSolicitedServiceUUIDsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataSolicitedServiceUUIDsKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataSolicitedServiceUUIDsKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdatasolicitedserviceuuidskey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataTxPowerLevelKey": {
      "abstract": [
        {
          "text": "The transmit power of a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataTxPowerLevelKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataTxPowerLevelKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataTxPowerLevelKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataTxPowerLevelKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdatatxpowerlevelkey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager": {
      "abstract": [
        {
          "text": "An object that manages and advertises peripheral services exposed by this app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBPeripheralManager"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBPeripheralManager"
        }
      ],
      "role": "symbol",
      "title": "CBPeripheralManager",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbperipheralmanager"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/isAdvertising": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the peripheral is advertising data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAdvertising"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/isAdvertising",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isAdvertising"
        }
      ],
      "role": "symbol",
      "title": "isAdvertising",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbperipheralmanager/isadvertising"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/startAdvertising(_:)": {
      "abstract": [
        {
          "text": "Advertises peripheral manager data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startAdvertising"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/startAdvertising(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startAdvertising:"
        }
      ],
      "role": "symbol",
      "title": "startAdvertising(_:)",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbperipheralmanager/startadvertising(_:)"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/stopAdvertising()": {
      "abstract": [
        {
          "text": "Stops advertising peripheral manager data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopAdvertising"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/stopAdvertising()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopAdvertising"
        }
      ],
      "role": "symbol",
      "title": "stopAdvertising()",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbperipheralmanager/stopadvertising()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Advertising",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/startAdvertising(_:)",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/stopAdvertising()",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/isAdvertising"
      ],
      "title": "Managing Advertising"
    }
  ],
  "topicSections": [
    {
      "anchor": "Advertising-Keys",
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataIsConnectable",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataManufacturerDataKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceDataKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataSolicitedServiceUUIDsKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataTxPowerLevelKey"
      ],
      "title": "Advertising Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Advertising-Keys",
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataIsConnectable",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataManufacturerDataKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceDataKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataSolicitedServiceUUIDsKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataTxPowerLevelKey"
              ],
              "title": "Advertising Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Advertising",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/startAdvertising(_:)",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/stopAdvertising()",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheralManager/isAdvertising"
              ],
              "title": "Managing Advertising"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager~1isAdvertising/title",
          "value": "isAdvertising"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager~1isAdvertising/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isAdvertising"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager/title",
          "value": "CBPeripheralManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBPeripheralManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBPeripheralManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataLocalNameKey/title",
          "value": "CBAdvertisementDataLocalNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataLocalNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataLocalNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataManufacturerDataKey/title",
          "value": "CBAdvertisementDataManufacturerDataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataManufacturerDataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataManufacturerDataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataIsConnectable/title",
          "value": "CBAdvertisementDataIsConnectable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataIsConnectable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataIsConnectable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataSolicitedServiceUUIDsKey/title",
          "value": "CBAdvertisementDataSolicitedServiceUUIDsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataSolicitedServiceUUIDsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataSolicitedServiceUUIDsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager~1stopAdvertising()/title",
          "value": "stopAdvertising"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager~1stopAdvertising()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopAdvertising"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataOverflowServiceUUIDsKey/title",
          "value": "CBAdvertisementDataOverflowServiceUUIDsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataOverflowServiceUUIDsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataOverflowServiceUUIDsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager~1startAdvertising(_:)/title",
          "value": "startAdvertising:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheralManager~1startAdvertising(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startAdvertising:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataServiceUUIDsKey/title",
          "value": "CBAdvertisementDataServiceUUIDsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataServiceUUIDsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataServiceUUIDsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataServiceDataKey/title",
          "value": "CBAdvertisementDataServiceDataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataServiceDataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataServiceDataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataTxPowerLevelKey/title",
          "value": "CBAdvertisementDataTxPowerLevelKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataTxPowerLevelKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataTxPowerLevelKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/advertising-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corebluetooth/advertising-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
