{
  "abstract": [
    {
      "text": "An array of solicited service UUIDs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataSolicitedServiceUUIDsKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@CBAdvertisementDataSolicitedServiceUUIDsKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CBAdvertisementDataSolicitedServiceUUIDsKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CBAdvertisementDataSolicitedServiceUUIDsKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "CBAdvertisementDataSolicitedServiceUUIDsKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataSolicitedServiceUUIDsKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value associated with this key is an array of one or more ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects, representing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBService",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " UUIDs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataIsConnectable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the advertising event type is connectable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataIsConnectable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataIsConnectable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataIsConnectable"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataIsConnectable",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdataisconnectable"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey": {
      "abstract": [
        {
          "text": "The local name of a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataLocalNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataLocalNameKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataLocalNameKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdatalocalnamekey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataManufacturerDataKey": {
      "abstract": [
        {
          "text": "The manufacturer data of a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataManufacturerDataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataManufacturerDataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataManufacturerDataKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataManufacturerDataKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdatamanufacturerdatakey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey": {
      "abstract": [
        {
          "text": "An array of UUIDs found in the overflow area of the advertisement data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataOverflowServiceUUIDsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataOverflowServiceUUIDsKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataOverflowServiceUUIDsKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdataoverflowserviceuuidskey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceDataKey": {
      "abstract": [
        {
          "text": "A dictionary that contains service-specific advertisement data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataServiceDataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceDataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataServiceDataKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataServiceDataKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdataservicedatakey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey": {
      "abstract": [
        {
          "text": "An array of service UUIDs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataServiceUUIDsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataServiceUUIDsKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataServiceUUIDsKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdataserviceuuidskey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataSolicitedServiceUUIDsKey": {
      "abstract": [
        {
          "text": "An array of solicited service UUIDs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataSolicitedServiceUUIDsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataSolicitedServiceUUIDsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataSolicitedServiceUUIDsKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataSolicitedServiceUUIDsKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdatasolicitedserviceuuidskey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataTxPowerLevelKey": {
      "abstract": [
        {
          "text": "The transmit power of a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataTxPowerLevelKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataTxPowerLevelKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAdvertisementDataTxPowerLevelKey"
        }
      ],
      "role": "symbol",
      "title": "CBAdvertisementDataTxPowerLevelKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbadvertisementdatatxpowerlevelkey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBService": {
      "abstract": [
        {
          "text": "A collection of data and associated behaviors that accomplish a function or feature of a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBService"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBService"
        }
      ],
      "role": "symbol",
      "title": "CBService",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbservice"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID": {
      "abstract": [
        {
          "text": "A universally unique identifier, as defined by Bluetooth standards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUID"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUID"
        }
      ],
      "role": "symbol",
      "title": "CBUUID",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Advertisement-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataManufacturerDataKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceDataKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataTxPowerLevelKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataIsConnectable"
      ],
      "title": "Advertisement Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CBAdvertisementDataSolicitedServiceUUIDsKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataSolicitedServiceUUIDsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Advertisement-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataLocalNameKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataManufacturerDataKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceDataKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataServiceUUIDsKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataOverflowServiceUUIDsKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataTxPowerLevelKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAdvertisementDataIsConnectable"
              ],
              "title": "Advertisement Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CBAdvertisementDataSolicitedServiceUUIDsKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataIsConnectable/title",
          "value": "CBAdvertisementDataIsConnectable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataIsConnectable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataIsConnectable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataServiceDataKey/title",
          "value": "CBAdvertisementDataServiceDataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataServiceDataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataServiceDataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataManufacturerDataKey/title",
          "value": "CBAdvertisementDataManufacturerDataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataManufacturerDataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataManufacturerDataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBService/title",
          "value": "CBService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataLocalNameKey/title",
          "value": "CBAdvertisementDataLocalNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataLocalNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataLocalNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataOverflowServiceUUIDsKey/title",
          "value": "CBAdvertisementDataOverflowServiceUUIDsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataOverflowServiceUUIDsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataOverflowServiceUUIDsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataSolicitedServiceUUIDsKey/title",
          "value": "CBAdvertisementDataSolicitedServiceUUIDsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataSolicitedServiceUUIDsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataSolicitedServiceUUIDsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataTxPowerLevelKey/title",
          "value": "CBAdvertisementDataTxPowerLevelKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataTxPowerLevelKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataTxPowerLevelKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUID/title",
          "value": "CBUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataServiceUUIDsKey/title",
          "value": "CBAdvertisementDataServiceUUIDsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAdvertisementDataServiceUUIDsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAdvertisementDataServiceUUIDsKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/cbadvertisementdatasolicitedserviceuuidskey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corebluetooth/cbadvertisementdatasolicitedserviceuuidskey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
