{
  "abstract": [
    {
      "text": "A Boolean value that specifies whether the system should display an alert when disconnecting a peripheral in the background.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnDisconnectionKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@CBConnectPeripheralOptionNotifyOnDisconnectionKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CBConnectPeripheralOptionNotifyOnDisconnectionKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CBConnectPeripheralOptionNotifyOnDisconnectionKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "CBConnectPeripheralOptionNotifyOnDisconnectionKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionNotifyOnDisconnectionKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value for this key is an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. This key is useful for apps that haven’t specified the ",
              "type": "text"
            },
            {
              "code": "bluetooth-central",
              "type": "codeVoice"
            },
            {
              "text": " background mode and can’t display their own alert. If more than one app requests a notification for a given peripheral, the one that was most recently in the foreground receives the alert. If the key isn’t specified, the default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableAutoReconnect": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the system automatically reconnects with a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionEnableAutoReconnect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableAutoReconnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionEnableAutoReconnect"
        }
      ],
      "role": "symbol",
      "title": "CBConnectPeripheralOptionEnableAutoReconnect",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbconnectperipheraloptionenableautoreconnect"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableTransportBridgingKey": {
      "abstract": [
        {
          "text": "An option to bridge classic Bluetooth technology profiles, if already connected over Bluetooth Low Energy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionEnableTransportBridgingKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableTransportBridgingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionEnableTransportBridgingKey"
        }
      ],
      "role": "symbol",
      "title": "CBConnectPeripheralOptionEnableTransportBridgingKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbconnectperipheraloptionenabletransportbridgingkey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnConnectionKey": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the system should display an alert when connecting a peripheral in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionNotifyOnConnectionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnConnectionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionNotifyOnConnectionKey"
        }
      ],
      "role": "symbol",
      "title": "CBConnectPeripheralOptionNotifyOnConnectionKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbconnectperipheraloptionnotifyonconnectionkey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnDisconnectionKey": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the system should display an alert when disconnecting a peripheral in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionNotifyOnDisconnectionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnDisconnectionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionNotifyOnDisconnectionKey"
        }
      ],
      "role": "symbol",
      "title": "CBConnectPeripheralOptionNotifyOnDisconnectionKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbconnectperipheraloptionnotifyondisconnectionkey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnNotificationKey": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the system should display an alert for any notification sent by a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionNotifyOnNotificationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnNotificationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionNotifyOnNotificationKey"
        }
      ],
      "role": "symbol",
      "title": "CBConnectPeripheralOptionNotifyOnNotificationKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbconnectperipheraloptionnotifyonnotificationkey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionRequiresANCS": {
      "abstract": [
        {
          "text": "An option to require Apple Notification Center Service (ANCS) when connecting a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionRequiresANCS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionRequiresANCS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionRequiresANCS"
        }
      ],
      "role": "symbol",
      "title": "CBConnectPeripheralOptionRequiresANCS",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbconnectperipheraloptionrequiresancs"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionStartDelayKey": {
      "abstract": [
        {
          "text": "An option that indicates a delay before the system makes a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionStartDelayKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionStartDelayKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionStartDelayKey"
        }
      ],
      "role": "symbol",
      "title": "CBConnectPeripheralOptionStartDelayKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbconnectperipheraloptionstartdelaykey"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableAutoReconnect",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableTransportBridgingKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnConnectionKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnNotificationKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionRequiresANCS",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionStartDelayKey"
      ],
      "title": "Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CBConnectPeripheralOptionNotifyOnDisconnectionKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionNotifyOnDisconnectionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableAutoReconnect",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableTransportBridgingKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnConnectionKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnNotificationKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionRequiresANCS",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionStartDelayKey"
              ],
              "title": "Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CBConnectPeripheralOptionNotifyOnDisconnectionKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionNotifyOnDisconnectionKey/title",
          "value": "CBConnectPeripheralOptionNotifyOnDisconnectionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionNotifyOnDisconnectionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionNotifyOnDisconnectionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionEnableTransportBridgingKey/title",
          "value": "CBConnectPeripheralOptionEnableTransportBridgingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionEnableTransportBridgingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionEnableTransportBridgingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionNotifyOnConnectionKey/title",
          "value": "CBConnectPeripheralOptionNotifyOnConnectionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionNotifyOnConnectionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionNotifyOnConnectionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionEnableAutoReconnect/title",
          "value": "CBConnectPeripheralOptionEnableAutoReconnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionEnableAutoReconnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionEnableAutoReconnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionNotifyOnNotificationKey/title",
          "value": "CBConnectPeripheralOptionNotifyOnNotificationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionNotifyOnNotificationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionNotifyOnNotificationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionRequiresANCS/title",
          "value": "CBConnectPeripheralOptionRequiresANCS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionRequiresANCS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionRequiresANCS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionStartDelayKey/title",
          "value": "CBConnectPeripheralOptionStartDelayKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionStartDelayKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionStartDelayKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/cbconnectperipheraloptionnotifyondisconnectionkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corebluetooth/cbconnectperipheraloptionnotifyondisconnectionkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
