{
  "abstract": [
    {
      "text": "An object that provides further information about a remote peripheral’s characteristic.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CBDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CBDescriptor"
      }
    ],
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CBDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CBDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CBDescriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and its subclass ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBMutableDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " represent a descriptor of a peripheral’s characteristic. In partcular, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects represent the descriptors of a remote peripheral’s characteristic. Descriptors provide further information about a characteristic’s value. For example, they may describe the value in human-readable form and describe how to format the value for presentation purposes. Characteristic descriptors also indicate whether a characteristic’s value indicates or notifies a client (a central) when the value of the characteristic changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " details six predefined descriptors and their corresponding value types. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " lists the predefined descriptors and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " constants that represent them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Descriptor type",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Descriptor constant",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Characteristic extended properties",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicExtendedPropertiesString",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Characteristic user description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicUserDescriptionString",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Client characteristic configuration",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDClientCharacteristicConfigurationString",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Server characteristic configuration",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDServerCharacteristicConfigurationString",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Characteristic format",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicFormatString",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Characteristic aggregate format",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicAggregateFormatString",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAttribute": {
      "abstract": [
        {
          "text": "A representation of common aspects of services offered by a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBAttribute"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBAttribute"
        }
      ],
      "role": "symbol",
      "title": "CBAttribute",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbattribute"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCharacteristic": {
      "abstract": [
        {
          "text": "A characteristic of a remote peripheral’s service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCharacteristic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBCharacteristic"
        }
      ],
      "role": "symbol",
      "title": "CBCharacteristic",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbcharacteristic"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBDescriptor": {
      "abstract": [
        {
          "text": "An object that provides further information about a remote peripheral’s characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBDescriptor"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBDescriptor"
        }
      ],
      "role": "symbol",
      "title": "CBDescriptor",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbdescriptor"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBDescriptor/characteristic": {
      "abstract": [
        {
          "text": "The characteristic to which this descriptor belongs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "characteristic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBCharacteristic",
          "text": "CBCharacteristic"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBDescriptor/characteristic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "characteristic"
        }
      ],
      "role": "symbol",
      "title": "characteristic",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbdescriptor/characteristic"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBDescriptor/value": {
      "abstract": [
        {
          "text": "The value of the descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBDescriptor/value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "value"
        }
      ],
      "role": "symbol",
      "title": "value",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbdescriptor/value"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBMutableCharacteristic": {
      "abstract": [
        {
          "text": "A characteristic of a local peripheral’s service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBMutableCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBMutableCharacteristic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBMutableCharacteristic"
        }
      ],
      "role": "symbol",
      "title": "CBMutableCharacteristic",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbmutablecharacteristic"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBMutableDescriptor": {
      "abstract": [
        {
          "text": "An object that provides additional information about a local peripheral’s characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBMutableDescriptor"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBMutableDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBMutableDescriptor"
        }
      ],
      "role": "symbol",
      "title": "CBMutableDescriptor",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbmutabledescriptor"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBMutableService": {
      "abstract": [
        {
          "text": "A service with writeable property values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBMutableService"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBMutableService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBMutableService"
        }
      ],
      "role": "symbol",
      "title": "CBMutableService",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbmutableservice"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBService": {
      "abstract": [
        {
          "text": "A collection of data and associated behaviors that accomplish a function or feature of a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBService"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBService"
        }
      ],
      "role": "symbol",
      "title": "CBService",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbservice"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID": {
      "abstract": [
        {
          "text": "A universally unique identifier, as defined by Bluetooth standards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUID"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUID"
        }
      ],
      "role": "symbol",
      "title": "CBUUID",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuid"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicAggregateFormatString": {
      "abstract": [
        {
          "text": "The UUID for the Aggregate Format descriptor, as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicAggregateFormatString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicAggregateFormatString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicAggregateFormatString"
        }
      ],
      "role": "symbol",
      "title": "CBUUIDCharacteristicAggregateFormatString",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuidcharacteristicaggregateformatstring"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicExtendedPropertiesString": {
      "abstract": [
        {
          "text": "The UUID for the Extended Properties descriptor, as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicExtendedPropertiesString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicExtendedPropertiesString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicExtendedPropertiesString"
        }
      ],
      "role": "symbol",
      "title": "CBUUIDCharacteristicExtendedPropertiesString",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuidcharacteristicextendedpropertiesstring"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicFormatString": {
      "abstract": [
        {
          "text": "The UUID for the Presentation Format descriptor, as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicFormatString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicFormatString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicFormatString"
        }
      ],
      "role": "symbol",
      "title": "CBUUIDCharacteristicFormatString",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuidcharacteristicformatstring"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicUserDescriptionString": {
      "abstract": [
        {
          "text": "The UUID for the User Description descriptor, as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicUserDescriptionString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicUserDescriptionString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicUserDescriptionString"
        }
      ],
      "role": "symbol",
      "title": "CBUUIDCharacteristicUserDescriptionString",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuidcharacteristicuserdescriptionstring"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDClientCharacteristicConfigurationString": {
      "abstract": [
        {
          "text": "The UUID for the Client Configuration descriptor, as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUIDClientCharacteristicConfigurationString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDClientCharacteristicConfigurationString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUIDClientCharacteristicConfigurationString"
        }
      ],
      "role": "symbol",
      "title": "CBUUIDClientCharacteristicConfigurationString",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuidclientcharacteristicconfigurationstring"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDServerCharacteristicConfigurationString": {
      "abstract": [
        {
          "text": "The UUID for the Server Configuration descriptor, as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUIDServerCharacteristicConfigurationString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDServerCharacteristicConfigurationString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUIDServerCharacteristicConfigurationString"
        }
      ],
      "role": "symbol",
      "title": "CBUUIDServerCharacteristicConfigurationString",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuidservercharacteristicconfigurationstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAttribute"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBMutableDescriptor"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Services",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBService",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBMutableService",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCharacteristic",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBMutableCharacteristic",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBMutableDescriptor"
      ],
      "title": "Services"
    }
  ],
  "topicSections": [
    {
      "anchor": "Identifying-a-Descriptor",
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBDescriptor/characteristic"
      ],
      "title": "Identifying a Descriptor"
    },
    {
      "anchor": "Accessing-Descriptor-Data",
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBDescriptor/value"
      ],
      "title": "Accessing Descriptor Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CBDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Identifying-a-Descriptor",
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBDescriptor/characteristic"
              ],
              "title": "Identifying a Descriptor"
            },
            {
              "anchor": "Accessing-Descriptor-Data",
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBDescriptor/value"
              ],
              "title": "Accessing Descriptor Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAttribute"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBMutableDescriptor"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Services",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBService",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBMutableService",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCharacteristic",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBMutableCharacteristic",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBMutableDescriptor"
              ],
              "title": "Services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CBDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBAttribute",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CBAttribute",
                    "text": "CBAttribute"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBMutableService/title",
          "value": "CBMutableService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBMutableService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBMutableService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBMutableService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBMutableService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBDescriptor~1value/title",
          "value": "value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBDescriptor~1value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDServerCharacteristicConfigurationString/title",
          "value": "CBUUIDServerCharacteristicConfigurationString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDServerCharacteristicConfigurationString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUIDServerCharacteristicConfigurationString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBMutableCharacteristic/title",
          "value": "CBMutableCharacteristic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBMutableCharacteristic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBMutableCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBMutableCharacteristic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBMutableCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAttribute/title",
          "value": "CBAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicUserDescriptionString/title",
          "value": "CBUUIDCharacteristicUserDescriptionString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicUserDescriptionString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUIDCharacteristicUserDescriptionString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBDescriptor~1characteristic/title",
          "value": "characteristic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBDescriptor~1characteristic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "characteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCharacteristic/title",
          "value": "CBCharacteristic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCharacteristic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCharacteristic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicExtendedPropertiesString/title",
          "value": "CBUUIDCharacteristicExtendedPropertiesString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicExtendedPropertiesString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUIDCharacteristicExtendedPropertiesString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBDescriptor/title",
          "value": "CBDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBMutableDescriptor/title",
          "value": "CBMutableDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBMutableDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBMutableDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBMutableDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBMutableDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBService/title",
          "value": "CBService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicAggregateFormatString/title",
          "value": "CBUUIDCharacteristicAggregateFormatString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicAggregateFormatString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUIDCharacteristicAggregateFormatString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDClientCharacteristicConfigurationString/title",
          "value": "CBUUIDClientCharacteristicConfigurationString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDClientCharacteristicConfigurationString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUIDClientCharacteristicConfigurationString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicFormatString/title",
          "value": "CBUUIDCharacteristicFormatString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicFormatString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUIDCharacteristicFormatString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUID/title",
          "value": "CBUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/cbdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corebluetooth/cbdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
