{
  "abstract": [
    {
      "text": "An error that Core Bluetooth returns during Bluetooth transactions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC7CBErrorLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CBError"
      }
    ],
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CBError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CBError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CBError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct": {
      "abstract": [
        {
          "text": "An error that Core Bluetooth returns while using Attribute Protocol (ATT).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBATTError"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTError"
        }
      ],
      "role": "symbol",
      "title": "CBATTError",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code": {
      "abstract": [
        {
          "text": "The possible errors returned by a GATT server (a remote peripheral) during Bluetooth low energy ATT transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CBATTError.Code",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterror-swift.struct/code"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Core Bluetooth ATT errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBATTErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBATTErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "CBATTErrorDomain",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbatterrordomain"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct": {
      "abstract": [
        {
          "text": "An error that Core Bluetooth returns during Bluetooth transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBError"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBError"
        }
      ],
      "role": "symbol",
      "title": "CBError",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code": {
      "abstract": [
        {
          "text": "The codes for errors that Core Bluetooth returns during Bluetooth transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CBError.Code",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/code"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/alreadyAdvertising": {
      "abstract": [
        {
          "text": "The peripheral is already advertising.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyAdvertising"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/alreadyAdvertising",
      "kind": "symbol",
      "role": "symbol",
      "title": "alreadyAdvertising",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/alreadyadvertising"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionFailed": {
      "abstract": [
        {
          "text": "The connection failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "connectionFailed",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/connectionfailed"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionLimitReached": {
      "abstract": [
        {
          "text": "The device already has the maximum number of connections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionLimitReached"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionLimitReached",
      "kind": "symbol",
      "role": "symbol",
      "title": "connectionLimitReached",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/connectionlimitreached"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionTimeout": {
      "abstract": [
        {
          "text": "The connection timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionTimeout",
      "kind": "symbol",
      "role": "symbol",
      "title": "connectionTimeout",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/connectiontimeout"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/encryptionTimedOut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encryptionTimedOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/encryptionTimedOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "encryptionTimedOut",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/encryptiontimedout"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/errordomain"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/invalidHandle": {
      "abstract": [
        {
          "text": "The specified attribute handle is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidHandle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/invalidHandle",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidHandle",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/invalidhandle"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/invalidParameters": {
      "abstract": [
        {
          "text": "The specified parameters are invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/invalidParameters",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidParameters",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/invalidparameters"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/leGattExceededBackgroundNotificationLimit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leGattExceededBackgroundNotificationLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/leGattExceededBackgroundNotificationLimit",
      "kind": "symbol",
      "role": "symbol",
      "title": "leGattExceededBackgroundNotificationLimit",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/legattexceededbackgroundnotificationlimit"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/leGattNearBackgroundNotificationLimit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leGattNearBackgroundNotificationLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/leGattNearBackgroundNotificationLimit",
      "kind": "symbol",
      "role": "symbol",
      "title": "leGattNearBackgroundNotificationLimit",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/legattnearbackgroundnotificationlimit"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/notConnected": {
      "abstract": [
        {
          "text": "The device isn’t currently connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notConnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/notConnected",
      "kind": "symbol",
      "role": "symbol",
      "title": "notConnected",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/notconnected"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/operationCancelled": {
      "abstract": [
        {
          "text": "The error represents a canceled operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/operationCancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "operationCancelled",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/operationcancelled"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/operationNotSupported": {
      "abstract": [
        {
          "text": "The operation isn’t supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/operationNotSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "operationNotSupported",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/operationnotsupported"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/outOfSpace": {
      "abstract": [
        {
          "text": "The device has run out of space to complete the intended operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/outOfSpace",
      "kind": "symbol",
      "role": "symbol",
      "title": "outOfSpace",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/outofspace"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/peerRemovedPairingInformation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peerRemovedPairingInformation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/peerRemovedPairingInformation",
      "kind": "symbol",
      "role": "symbol",
      "title": "peerRemovedPairingInformation",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/peerremovedpairinginformation"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/peripheralDisconnected": {
      "abstract": [
        {
          "text": "The peripheral disconnected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peripheralDisconnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/peripheralDisconnected",
      "kind": "symbol",
      "role": "symbol",
      "title": "peripheralDisconnected",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/peripheraldisconnected"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/tooManyLEPairedDevices": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tooManyLEPairedDevices"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/tooManyLEPairedDevices",
      "kind": "symbol",
      "role": "symbol",
      "title": "tooManyLEPairedDevices",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/toomanylepaireddevices"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/unknown"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unknownDevice": {
      "abstract": [
        {
          "text": "The device is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unknownDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownDevice",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/unknowndevice"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unkownDevice": {
      "abstract": [
        {
          "text": "A misspelled version of the unknown device error code.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unkownDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unkownDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "unkownDevice",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/unkowndevice"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/uuidNotAllowed": {
      "abstract": [
        {
          "text": "The specified UUID isn’t permitted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uuidNotAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7CBErrorLeV",
          "text": "CBError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/uuidNotAllowed",
      "kind": "symbol",
      "role": "symbol",
      "title": "uuidNotAllowed",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberror-swift.struct/uuidnotallowed"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Core Bluetooth errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "CBErrorDomain",
      "type": "topic",
      "url": "/documentation/corebluetooth/cberrordomain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBErrorDomain",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTErrorDomain",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct/Code",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBATTError-swift.struct"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unknown",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/invalidParameters",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/invalidHandle",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/notConnected",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/outOfSpace",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/operationCancelled",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionTimeout",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/peripheralDisconnected",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/uuidNotAllowed",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/alreadyAdvertising",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionFailed",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/connectionLimitReached",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/operationNotSupported",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unknownDevice",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/unkownDevice"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/encryptionTimedOut",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/leGattExceededBackgroundNotificationLimit",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/leGattNearBackgroundNotificationLimit",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/peerRemovedPairingInformation",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/tooManyLEPairedDevices",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/errorDomain"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBError-swift.struct/Code"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTErrorDomain/title",
          "value": "CBATTErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/title",
          "value": "CBError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code/title",
          "value": "CBATTError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBATTError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBATTError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBErrorDomain/title",
          "value": "CBErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/cberror-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
