{
  "abstract": [
    {
      "text": "A live L2CAP connection to a remote device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CBL2CAPChannel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CBL2CAPChannel"
      }
    ],
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CBL2CAPChannel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CBL2CAPChannel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CBL2CAPChannel"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel": {
      "abstract": [
        {
          "text": "A live L2CAP connection to a remote device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBL2CAPChannel"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBL2CAPChannel"
        }
      ],
      "role": "symbol",
      "title": "CBL2CAPChannel",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbl2capchannel"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/inputStream": {
      "abstract": [
        {
          "text": "The stream used for reading data from the remote peer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputStream"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSInputStream",
          "text": "InputStream"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/inputStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputStream"
        }
      ],
      "role": "symbol",
      "title": "inputStream",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbl2capchannel/inputstream"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/outputStream": {
      "abstract": [
        {
          "text": "The stream used for writing data to the peer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputStream"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOutputStream",
          "text": "OutputStream"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/outputStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputStream"
        }
      ],
      "role": "symbol",
      "title": "outputStream",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbl2capchannel/outputstream"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/peer": {
      "abstract": [
        {
          "text": "The peer connected to the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBPeer",
          "text": "CBPeer"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/peer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peer"
        }
      ],
      "role": "symbol",
      "title": "peer",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbl2capchannel/peer"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/psm": {
      "abstract": [
        {
          "text": "The PSM of the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "psm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CBL2CAPPSM",
          "text": "CBL2CAPPSM"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/psm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PSM"
        }
      ],
      "role": "symbol",
      "title": "psm",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbl2capchannel/psm"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPPSM": {
      "abstract": [
        {
          "text": "The type of PSM identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBL2CAPPSM"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPPSM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBL2CAPPSM"
        }
      ],
      "role": "symbol",
      "title": "CBL2CAPPSM",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbl2cappsm"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheral/openL2CAPChannel(_:)": {
      "abstract": [
        {
          "text": "Attempts to open an L2CAP channel to the peripheral using the supplied Protocol/Service Multiplexer (PSM).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openL2CAPChannel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CBL2CAPPSM",
          "text": "CBL2CAPPSM"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheral/openL2CAPChannel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openL2CAPChannel:"
        }
      ],
      "role": "symbol",
      "title": "openL2CAPChannel(_:)",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbperipheral/openl2capchannel(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-L2CAP-Channels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheral/openL2CAPChannel(_:)",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPPSM"
      ],
      "title": "Working with L2CAP Channels"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Streams",
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/inputStream",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/outputStream"
      ],
      "title": "Accessing Streams"
    },
    {
      "anchor": "Accessing-the-Peer",
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/peer"
      ],
      "title": "Accessing the Peer"
    },
    {
      "anchor": "Accessing-the-ProtocolService-Multiplexer",
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/psm"
      ],
      "title": "Accessing the Protocol/Service Multiplexer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CBL2CAPChannel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBL2CAPChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBL2CAPChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Streams",
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/inputStream",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/outputStream"
              ],
              "title": "Accessing Streams"
            },
            {
              "anchor": "Accessing-the-Peer",
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/peer"
              ],
              "title": "Accessing the Peer"
            },
            {
              "anchor": "Accessing-the-ProtocolService-Multiplexer",
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPChannel/psm"
              ],
              "title": "Accessing the Protocol/Service Multiplexer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-L2CAP-Channels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBPeripheral/openL2CAPChannel(_:)",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBL2CAPPSM"
              ],
              "title": "Working with L2CAP Channels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CBL2CAPChannel"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPChannel~1inputStream/title",
          "value": "inputStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPChannel~1inputStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPChannel~1outputStream/title",
          "value": "outputStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPChannel~1outputStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPChannel/title",
          "value": "CBL2CAPChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBL2CAPChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPChannel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBL2CAPChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheral~1openL2CAPChannel(_:)/title",
          "value": "openL2CAPChannel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBPeripheral~1openL2CAPChannel(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openL2CAPChannel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPChannel~1psm/title",
          "value": "PSM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPChannel~1psm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PSM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPChannel~1peer/title",
          "value": "peer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPChannel~1peer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "peer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPPSM/title",
          "value": "CBL2CAPPSM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPPSM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBL2CAPPSM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBL2CAPPSM/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBL2CAPPSM"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/cbl2capchannel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corebluetooth/cbl2capchannel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
