{
  "abstract": [
    {
      "text": "Values that represent the UUIDs of the characteristic descriptors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/characteristic-descriptors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Characteristic Descriptors"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these UUIDs to add well-known descriptors to characteristics you create, or to find specific descriptors from characteristics of remote services.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID": {
      "abstract": [
        {
          "text": "A universally unique identifier, as defined by Bluetooth standards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUID"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUID"
        }
      ],
      "role": "symbol",
      "title": "CBUUID",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuid"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicAggregateFormatString": {
      "abstract": [
        {
          "text": "The UUID for the Aggregate Format descriptor, as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicAggregateFormatString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicAggregateFormatString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicAggregateFormatString"
        }
      ],
      "role": "symbol",
      "title": "CBUUIDCharacteristicAggregateFormatString",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuidcharacteristicaggregateformatstring"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicExtendedPropertiesString": {
      "abstract": [
        {
          "text": "The UUID for the Extended Properties descriptor, as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicExtendedPropertiesString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicExtendedPropertiesString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicExtendedPropertiesString"
        }
      ],
      "role": "symbol",
      "title": "CBUUIDCharacteristicExtendedPropertiesString",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuidcharacteristicextendedpropertiesstring"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicFormatString": {
      "abstract": [
        {
          "text": "The UUID for the Presentation Format descriptor, as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicFormatString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicFormatString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicFormatString"
        }
      ],
      "role": "symbol",
      "title": "CBUUIDCharacteristicFormatString",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuidcharacteristicformatstring"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicUserDescriptionString": {
      "abstract": [
        {
          "text": "The UUID for the User Description descriptor, as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicUserDescriptionString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicUserDescriptionString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUIDCharacteristicUserDescriptionString"
        }
      ],
      "role": "symbol",
      "title": "CBUUIDCharacteristicUserDescriptionString",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuidcharacteristicuserdescriptionstring"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDClientCharacteristicConfigurationString": {
      "abstract": [
        {
          "text": "The UUID for the Client Configuration descriptor, as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUIDClientCharacteristicConfigurationString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDClientCharacteristicConfigurationString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUIDClientCharacteristicConfigurationString"
        }
      ],
      "role": "symbol",
      "title": "CBUUIDClientCharacteristicConfigurationString",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuidclientcharacteristicconfigurationstring"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDL2CAPPSMCharacteristicString": {
      "abstract": [
        {
          "text": "The PSM of an L2CAP channel associated with the GATT service containing this characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUIDL2CAPPSMCharacteristicString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDL2CAPPSMCharacteristicString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUIDL2CAPPSMCharacteristicString"
        }
      ],
      "role": "symbol",
      "title": "CBUUIDL2CAPPSMCharacteristicString",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuidl2cappsmcharacteristicstring"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDServerCharacteristicConfigurationString": {
      "abstract": [
        {
          "text": "The UUID for the Server Configuration descriptor, as a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBUUIDServerCharacteristicConfigurationString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDServerCharacteristicConfigurationString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBUUIDServerCharacteristicConfigurationString"
        }
      ],
      "role": "symbol",
      "title": "CBUUIDServerCharacteristicConfigurationString",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbuuidservercharacteristicconfigurationstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Characteristic-Descriptors",
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicExtendedPropertiesString",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicUserDescriptionString",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDClientCharacteristicConfigurationString",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDServerCharacteristicConfigurationString",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicFormatString",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicAggregateFormatString",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDL2CAPPSMCharacteristicString"
      ],
      "title": "Characteristic Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Characteristic-Descriptors",
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicExtendedPropertiesString",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicUserDescriptionString",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDClientCharacteristicConfigurationString",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDServerCharacteristicConfigurationString",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicFormatString",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDCharacteristicAggregateFormatString",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBUUIDL2CAPPSMCharacteristicString"
              ],
              "title": "Characteristic Descriptors"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicFormatString/title",
          "value": "CBUUIDCharacteristicFormatString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicFormatString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUIDCharacteristicFormatString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDServerCharacteristicConfigurationString/title",
          "value": "CBUUIDServerCharacteristicConfigurationString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDServerCharacteristicConfigurationString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUIDServerCharacteristicConfigurationString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDClientCharacteristicConfigurationString/title",
          "value": "CBUUIDClientCharacteristicConfigurationString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDClientCharacteristicConfigurationString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUIDClientCharacteristicConfigurationString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUID/title",
          "value": "CBUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicExtendedPropertiesString/title",
          "value": "CBUUIDCharacteristicExtendedPropertiesString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicExtendedPropertiesString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUIDCharacteristicExtendedPropertiesString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDL2CAPPSMCharacteristicString/title",
          "value": "CBUUIDL2CAPPSMCharacteristicString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDL2CAPPSMCharacteristicString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUIDL2CAPPSMCharacteristicString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicUserDescriptionString/title",
          "value": "CBUUIDCharacteristicUserDescriptionString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicUserDescriptionString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUIDCharacteristicUserDescriptionString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicAggregateFormatString/title",
          "value": "CBUUIDCharacteristicAggregateFormatString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBUUIDCharacteristicAggregateFormatString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBUUIDCharacteristicAggregateFormatString"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/characteristic-descriptors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corebluetooth/characteristic-descriptors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
