{
  "abstract": [
    {
      "text": "Keys used to pass options when connecting to a peripheral.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/peripheral-connection-options"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Bluetooth"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Peripheral Connection Options"
  },
  "references": {
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth": {
      "abstract": [
        {
          "text": "Communicate with Bluetooth low energy and BR/EDR (“Classic”) Devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Bluetooth",
      "type": "topic",
      "url": "/documentation/corebluetooth"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager": {
      "abstract": [
        {
          "text": "An object that scans for, discovers, connects to, and manages peripherals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBCentralManager"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBCentralManager"
        }
      ],
      "role": "symbol",
      "title": "CBCentralManager",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbcentralmanager"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/cancelPeripheralConnection(_:)": {
      "abstract": [
        {
          "text": "Cancels an active or pending local connection to a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelPeripheralConnection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBPeripheral",
          "text": "CBPeripheral"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/cancelPeripheralConnection(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelPeripheralConnection:"
        }
      ],
      "role": "symbol",
      "title": "cancelPeripheralConnection(_:)",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbcentralmanager/cancelperipheralconnection(_:)"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/connect(_:options:)": {
      "abstract": [
        {
          "text": "Establishes a local connection to a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBPeripheral",
          "text": "CBPeripheral"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/connect(_:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "connectPeripheral:options:"
        }
      ],
      "role": "symbol",
      "title": "connect(_:options:)",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbcentralmanager/connect(_:options:)"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableAutoReconnect": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the system automatically reconnects with a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionEnableAutoReconnect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableAutoReconnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionEnableAutoReconnect"
        }
      ],
      "role": "symbol",
      "title": "CBConnectPeripheralOptionEnableAutoReconnect",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbconnectperipheraloptionenableautoreconnect"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableTransportBridgingKey": {
      "abstract": [
        {
          "text": "An option to bridge classic Bluetooth technology profiles, if already connected over Bluetooth Low Energy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionEnableTransportBridgingKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableTransportBridgingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionEnableTransportBridgingKey"
        }
      ],
      "role": "symbol",
      "title": "CBConnectPeripheralOptionEnableTransportBridgingKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbconnectperipheraloptionenabletransportbridgingkey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnConnectionKey": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the system should display an alert when connecting a peripheral in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionNotifyOnConnectionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnConnectionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionNotifyOnConnectionKey"
        }
      ],
      "role": "symbol",
      "title": "CBConnectPeripheralOptionNotifyOnConnectionKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbconnectperipheraloptionnotifyonconnectionkey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnDisconnectionKey": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the system should display an alert when disconnecting a peripheral in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionNotifyOnDisconnectionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnDisconnectionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionNotifyOnDisconnectionKey"
        }
      ],
      "role": "symbol",
      "title": "CBConnectPeripheralOptionNotifyOnDisconnectionKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbconnectperipheraloptionnotifyondisconnectionkey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnNotificationKey": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the system should display an alert for any notification sent by a peripheral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionNotifyOnNotificationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnNotificationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionNotifyOnNotificationKey"
        }
      ],
      "role": "symbol",
      "title": "CBConnectPeripheralOptionNotifyOnNotificationKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbconnectperipheraloptionnotifyonnotificationkey"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionRequiresANCS": {
      "abstract": [
        {
          "text": "An option to require Apple Notification Center Service (ANCS) when connecting a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionRequiresANCS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionRequiresANCS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionRequiresANCS"
        }
      ],
      "role": "symbol",
      "title": "CBConnectPeripheralOptionRequiresANCS",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbconnectperipheraloptionrequiresancs"
    },
    "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionStartDelayKey": {
      "abstract": [
        {
          "text": "An option that indicates a delay before the system makes a connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionStartDelayKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionStartDelayKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBConnectPeripheralOptionStartDelayKey"
        }
      ],
      "role": "symbol",
      "title": "CBConnectPeripheralOptionStartDelayKey",
      "type": "topic",
      "url": "/documentation/corebluetooth/cbconnectperipheraloptionstartdelaykey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Establishing-or-Canceling-Connections-with-Peripherals",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/connect(_:options:)",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/cancelPeripheralConnection(_:)"
      ],
      "title": "Establishing or Canceling Connections with Peripherals"
    }
  ],
  "topicSections": [
    {
      "anchor": "Options",
      "identifiers": [
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableAutoReconnect",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableTransportBridgingKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnConnectionKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnDisconnectionKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnNotificationKey",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionRequiresANCS",
        "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionStartDelayKey"
      ],
      "title": "Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Options",
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableAutoReconnect",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionEnableTransportBridgingKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnConnectionKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnDisconnectionKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionNotifyOnNotificationKey",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionRequiresANCS",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBConnectPeripheralOptionStartDelayKey"
              ],
              "title": "Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Establishing-or-Canceling-Connections-with-Peripherals",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/connect(_:options:)",
                "doc://com.apple.corebluetooth/documentation/CoreBluetooth/CBCentralManager/cancelPeripheralConnection(_:)"
              ],
              "title": "Establishing or Canceling Connections with Peripherals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionRequiresANCS/title",
          "value": "CBConnectPeripheralOptionRequiresANCS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionRequiresANCS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionRequiresANCS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionStartDelayKey/title",
          "value": "CBConnectPeripheralOptionStartDelayKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionStartDelayKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionStartDelayKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionEnableTransportBridgingKey/title",
          "value": "CBConnectPeripheralOptionEnableTransportBridgingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionEnableTransportBridgingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionEnableTransportBridgingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionNotifyOnNotificationKey/title",
          "value": "CBConnectPeripheralOptionNotifyOnNotificationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionNotifyOnNotificationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionNotifyOnNotificationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1cancelPeripheralConnection(_:)/title",
          "value": "cancelPeripheralConnection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1cancelPeripheralConnection(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelPeripheralConnection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1connect(_:options:)/title",
          "value": "connectPeripheral:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager~1connect(_:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "connectPeripheral:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionNotifyOnDisconnectionKey/title",
          "value": "CBConnectPeripheralOptionNotifyOnDisconnectionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionNotifyOnDisconnectionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionNotifyOnDisconnectionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/title",
          "value": "CBCentralManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBCentralManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBCentralManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBCentralManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionEnableAutoReconnect/title",
          "value": "CBConnectPeripheralOptionEnableAutoReconnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionEnableAutoReconnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionEnableAutoReconnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionNotifyOnConnectionKey/title",
          "value": "CBConnectPeripheralOptionNotifyOnConnectionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corebluetooth~1documentation~1CoreBluetooth~1CBConnectPeripheralOptionNotifyOnConnectionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBConnectPeripheralOptionNotifyOnConnectionKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corebluetooth/peripheral-connection-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corebluetooth/peripheral-connection-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
