{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/topTrailing","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"NSRectAlignmentTopTrailing"}],"symbolKind":"case","externalID":"c:@E@NSRectAlignment@NSRectAlignmentTopTrailing","modules":[{"name":"AppKit"}],"platforms":[{"name":"macOS","beta":false,"introducedAt":"10.15","unavailable":false,"deprecated":false}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"topTrailing"}],"role":"symbol","title":"NSRectAlignment.topTrailing"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment"]]},"abstract":[{"text":"Aligns to the top and trailing edges.","type":"text"}],"seeAlsoSections":[{"title":"Alignments","anchor":"Alignments","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/none","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/top","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/topLeading","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/leading","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/bottomLeading","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/bottom","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/bottomTrailing","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/trailing"],"generated":true}],"variants":[{"paths":["/documentation/appkit/nsrectalignment/toptrailing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsrectalignment/toptrailing"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topTrailing","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/leading":{"url":"/documentation/appkit/nsrectalignment/leading","kind":"symbol","title":"NSRectAlignment.leading","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/leading","type":"topic","navigatorTitle":[{"text":"NSRectAlignmentLeading","kind":"identifier"}],"abstract":[{"type":"text","text":"Aligns to the leading edge."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leading"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/bottomLeading":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/bottomLeading","abstract":[{"type":"text","text":"Aligns to the bottom and leading edges."}],"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomLeading","kind":"identifier"}],"title":"NSRectAlignment.bottomLeading","url":"/documentation/appkit/nsrectalignment/bottomleading","type":"topic","navigatorTitle":[{"text":"NSRectAlignmentBottomLeading","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/trailing":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"NSRectAlignmentTrailing","kind":"identifier"}],"abstract":[{"type":"text","text":"Aligns to the trailing edge."}],"url":"/documentation/appkit/nsrectalignment/trailing","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trailing","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/trailing","title":"NSRectAlignment.trailing"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/top":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/top","abstract":[{"type":"text","text":"Aligns to the top edge."}],"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"}],"title":"NSRectAlignment.top","url":"/documentation/appkit/nsrectalignment/top","type":"topic","navigatorTitle":[{"text":"NSRectAlignmentTop","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/bottom":{"title":"NSRectAlignment.bottom","navigatorTitle":[{"text":"NSRectAlignmentBottom","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/bottom","role":"symbol","url":"/documentation/appkit/nsrectalignment/bottom","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"}],"abstract":[{"type":"text","text":"Aligns to the bottom edge."}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"NSRectAlignment","kind":"identifier"}],"abstract":[{"type":"text","text":"Constants that specify alignment to an edge or a set of edges depending on the user interface layout direction."}],"url":"/documentation/appkit/nsrectalignment","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSRectAlignment","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment","title":"NSRectAlignment"},"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/topTrailing":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSRectAlignmentTopTrailing"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/topTrailing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"topTrailing"}],"kind":"symbol","url":"/documentation/appkit/nsrectalignment/toptrailing","abstract":[{"type":"text","text":"Aligns to the top and trailing edges."}],"title":"NSRectAlignment.topTrailing"},"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/bottomTrailing":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/bottomTrailing","abstract":[{"type":"text","text":"Aligns to the bottom and trailing edges."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomTrailing"}],"title":"NSRectAlignment.bottomTrailing","url":"/documentation/appkit/nsrectalignment/bottomtrailing","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSRectAlignmentBottomTrailing"}]},"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/topLeading":{"title":"NSRectAlignment.topLeading","navigatorTitle":[{"text":"NSRectAlignmentTopLeading","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/topLeading","role":"symbol","url":"/documentation/appkit/nsrectalignment/topleading","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"topLeading","kind":"identifier"}],"abstract":[{"text":"Aligns to the top and leading edges.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/none":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSRectAlignmentNone"}],"abstract":[{"type":"text","text":"Has no specified alignment."}],"url":"/documentation/appkit/nsrectalignment/none","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/none","title":"NSRectAlignment.none"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"10.15","name":"macOS","unavailable":false,"deprecated":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"NSRectAlignmentTopTrailing"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"NSRectAlignmentTopTrailing","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment"]]}},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"anchor":"Alignments","title":"Alignments","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/none","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/top","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/topLeading","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/leading","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/bottomLeading","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/bottom","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/bottomTrailing","doc://com.apple.appkit/documentation/AppKit/NSRectAlignment/trailing"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"NSRectAlignmentTopTrailing","kind":"identifier"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":"NSRectAlignmentLeading","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1leading/title","op":"replace"},{"value":[{"text":"NSRectAlignmentLeading","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1leading/fragments","op":"replace"},{"value":"NSRectAlignmentBottomLeading","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1bottomLeading/title","op":"replace"},{"value":[{"text":"NSRectAlignmentBottomLeading","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1bottomLeading/fragments","op":"replace"},{"value":"NSRectAlignmentTrailing","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1trailing/title","op":"replace"},{"value":[{"text":"NSRectAlignmentTrailing","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1trailing/fragments","op":"replace"},{"value":"NSRectAlignmentTop","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1top/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSRectAlignmentTop"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1top/fragments","op":"replace"},{"value":"NSRectAlignmentBottom","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1bottom/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSRectAlignmentBottom"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1bottom/fragments","op":"replace"},{"value":"NSRectAlignment","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSRectAlignment"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSRectAlignment"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment/navigatorTitle","op":"replace"},{"value":"NSRectAlignmentTopTrailing","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1topTrailing/title","op":"replace"},{"value":[{"text":"NSRectAlignmentTopTrailing","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1topTrailing/fragments","op":"replace"},{"value":"NSRectAlignmentBottomTrailing","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1bottomTrailing/title","op":"replace"},{"value":[{"text":"NSRectAlignmentBottomTrailing","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1bottomTrailing/fragments","op":"replace"},{"value":"NSRectAlignmentTopLeading","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1topLeading/title","op":"replace"},{"value":[{"text":"NSRectAlignmentTopLeading","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1topLeading/fragments","op":"replace"},{"value":"NSRectAlignmentNone","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1none/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSRectAlignmentNone"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSRectAlignment~1none/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}