{
  "abstract": [
    {
      "text": "Tells the delegate that the controller is about to begin searching.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate/searchDisplayControllerWillBeginSearch(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UISearchDisplayDelegate(im)searchDisplayControllerWillBeginSearch:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "searchDisplayControllerWillBeginSearch"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UISearchDisplayController",
        "text": "UISearchDisplayController"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "searchDisplayControllerWillBeginSearch:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "searchDisplayControllerWillBeginSearch(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "searchDisplayControllerWillBeginSearch"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UISearchDisplayController",
              "text": "UISearchDisplayController"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The search display controller for which the receiver is the delegate.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "controller"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayController": {
      "abstract": [
        {
          "text": "An object that manages the display of a search bar, along with a table view that displays search results.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchDisplayController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchDisplayController"
        }
      ],
      "role": "symbol",
      "title": "UISearchDisplayController",
      "type": "topic",
      "url": "/documentation/uikit/uisearchdisplaycontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate": {
      "abstract": [
        {
          "text": "The interface for the delegate of a search display controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchDisplayDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchDisplayDelegate"
        }
      ],
      "role": "symbol",
      "title": "UISearchDisplayDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uisearchdisplaydelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate/searchDisplayControllerDidBeginSearch(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the controller has started searching.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchDisplayControllerDidBeginSearch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchDisplayController",
          "text": "UISearchDisplayController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate/searchDisplayControllerDidBeginSearch(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchDisplayControllerDidBeginSearch:"
        }
      ],
      "role": "symbol",
      "title": "searchDisplayControllerDidBeginSearch(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchdisplaydelegate/searchdisplaycontrollerdidbeginsearch(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate/searchDisplayControllerDidEndSearch(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the controller has finished searching.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchDisplayControllerDidEndSearch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchDisplayController",
          "text": "UISearchDisplayController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate/searchDisplayControllerDidEndSearch(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchDisplayControllerDidEndSearch:"
        }
      ],
      "role": "symbol",
      "title": "searchDisplayControllerDidEndSearch(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchdisplaydelegate/searchdisplaycontrollerdidendsearch(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate/searchDisplayControllerWillBeginSearch(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the controller is about to begin searching.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchDisplayControllerWillBeginSearch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchDisplayController",
          "text": "UISearchDisplayController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate/searchDisplayControllerWillBeginSearch(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchDisplayControllerWillBeginSearch:"
        }
      ],
      "role": "symbol",
      "title": "searchDisplayControllerWillBeginSearch(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchdisplaydelegate/searchdisplaycontrollerwillbeginsearch(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate/searchDisplayControllerWillEndSearch(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the controller is about to end searching.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchDisplayControllerWillEndSearch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchDisplayController",
          "text": "UISearchDisplayController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate/searchDisplayControllerWillEndSearch(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchDisplayControllerWillEndSearch:"
        }
      ],
      "role": "symbol",
      "title": "searchDisplayControllerWillEndSearch(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchdisplaydelegate/searchdisplaycontrollerwillendsearch(_:)"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-search-state-change",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate/searchDisplayControllerDidBeginSearch(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate/searchDisplayControllerWillEndSearch(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate/searchDisplayControllerDidEndSearch(_:)"
      ],
      "title": "Responding to search state change"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "searchDisplayControllerWillBeginSearch:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchDisplayControllerWillBeginSearch:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-search-state-change",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate/searchDisplayControllerDidBeginSearch(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate/searchDisplayControllerWillEndSearch(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate/searchDisplayControllerDidEndSearch(_:)"
              ],
              "title": "Responding to search state change"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "searchDisplayControllerWillBeginSearch:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UISearchDisplayController",
                    "text": "UISearchDisplayController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "controller"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The search display controller for which the receiver is the delegate.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "controller"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayDelegate~1searchDisplayControllerWillBeginSearch(_:)/title",
          "value": "searchDisplayControllerWillBeginSearch:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayDelegate~1searchDisplayControllerWillBeginSearch(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchDisplayControllerWillBeginSearch:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayDelegate/title",
          "value": "UISearchDisplayDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchDisplayDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchDisplayDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayController/title",
          "value": "UISearchDisplayController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchDisplayController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchDisplayController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayDelegate~1searchDisplayControllerDidEndSearch(_:)/title",
          "value": "searchDisplayControllerDidEndSearch:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayDelegate~1searchDisplayControllerDidEndSearch(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchDisplayControllerDidEndSearch:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayDelegate~1searchDisplayControllerDidBeginSearch(_:)/title",
          "value": "searchDisplayControllerDidBeginSearch:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayDelegate~1searchDisplayControllerDidBeginSearch(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchDisplayControllerDidBeginSearch:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayDelegate~1searchDisplayControllerWillEndSearch(_:)/title",
          "value": "searchDisplayControllerWillEndSearch:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayDelegate~1searchDisplayControllerWillEndSearch(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchDisplayControllerWillEndSearch:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisearchdisplaydelegate/searchdisplaycontrollerwillbeginsearch(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uisearchdisplaydelegate/searchdisplaycontrollerwillbeginsearch(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
