{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest/update"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@BAContentRequest@BAContentRequestUpdate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "update"
      }
    ],
    "modules": [
      {
        "name": "Background Assets"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BAContentRequestUpdate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "BAContentRequest.update"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "update"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets": {
      "abstract": [
        {
          "text": "Schedule background downloads of large assets after app installation, when the app updates, and periodically while the app remains on-device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets",
      "kind": "symbol",
      "role": "collection",
      "title": "Background Assets",
      "type": "topic",
      "url": "/documentation/backgroundassets"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BAContentRequest"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAContentRequest"
        }
      ],
      "role": "symbol",
      "title": "BAContentRequest",
      "type": "topic",
      "url": "/documentation/backgroundassets/bacontentrequest"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest/install": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "install"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest/install",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAContentRequestInstall"
        }
      ],
      "role": "symbol",
      "title": "BAContentRequest.install",
      "type": "topic",
      "url": "/documentation/backgroundassets/bacontentrequest/install"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest/periodic": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "periodic"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest/periodic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAContentRequestPeriodic"
        }
      ],
      "role": "symbol",
      "title": "BAContentRequest.periodic",
      "type": "topic",
      "url": "/documentation/backgroundassets/bacontentrequest/periodic"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest/update": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "update"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest/update",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAContentRequestUpdate"
        }
      ],
      "role": "symbol",
      "title": "BAContentRequest.update",
      "type": "topic",
      "url": "/documentation/backgroundassets/bacontentrequest/update"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Content-request-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest/install",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest/periodic"
      ],
      "title": "Content request types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BAContentRequestUpdate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAContentRequestUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Content-request-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest/install",
                "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest/periodic"
              ],
              "title": "Content request types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "BAContentRequestUpdate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAContentRequest/title",
          "value": "BAContentRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAContentRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAContentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAContentRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BAContentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAContentRequest~1update/title",
          "value": "BAContentRequestUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAContentRequest~1update/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAContentRequestUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAContentRequest~1periodic/title",
          "value": "BAContentRequestPeriodic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAContentRequest~1periodic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAContentRequestPeriodic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAContentRequest~1install/title",
          "value": "BAContentRequestInstall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAContentRequest~1install/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAContentRequestInstall"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/backgroundassets/bacontentrequest/update"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/backgroundassets/bacontentrequest/update"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
