{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uicollectionviewcell/configurationupdatehandler-ajhn"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCellConfigurationUpdateHandler","preciseIdentifier":"c:@T@UICollectionViewCellConfigurationUpdateHandler","text":"UICollectionViewCellConfigurationUpdateHandler"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationUpdateHandler"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]},{"kind":"content","content":[{"anchor":"Discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"A configuration update handler provides an alternative approach to overriding "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfigurationUsingState:","isActive":true},{"type":"text","text":" in a subclass. Set a configuration update handler to update the cell’s configuration using the new state in response to a configuration state change:"}],"type":"paragraph"},{"code":["[cell setConfigurationUpdateHandler:^(UICollectionViewCell *cell, UICellConfigurationState *state) {","    UIListContentConfiguration *content = [[UIListContentConfiguration cellConfiguration] updatedConfigurationForState:state];","    [content setText: @\"Hello world!\"];","    if (state.isDisabled) {","        [content.textProperties setColor:[UIColor systemGrayColor]];","    }","    [cell setContentConfiguration:content];","}];"],"type":"codeListing","syntax":"objc"},{"inlineContent":[{"type":"text","text":"Setting the value of this property calls "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/setNeedsUpdateConfiguration()","type":"reference","isActive":true},{"type":"text","text":". The system calls this handler after calling "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfigurationUsingState:","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"text":"In iOS 18 and later, UIKit supports automatic trait tracking inside this block for traits from this cell’s ","type":"text"},{"type":"codeVoice","code":"traitCollection"},{"text":". For more information, see ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"metadata":{"modules":[{"name":"UIKit"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"configurationUpdateHandler","kind":"identifier"}],"roleHeading":"Instance Property","title":"configurationUpdateHandler","fragments":[{"text":"configurationUpdateHandler","kind":"identifier"}],"externalID":"c:objc(cs)UICollectionViewCell(py)configurationUpdateHandler","platforms":[{"introducedAt":"15.0","name":"iOS","beta":false,"unavailable":false,"deprecated":false},{"introducedAt":"15.0","name":"iPadOS","beta":false,"unavailable":false,"deprecated":false},{"introducedAt":"15.0","name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"15.0","deprecated":false,"name":"tvOS"},{"beta":false,"unavailable":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell"]]},"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationUpdateHandler-ajhn"},"seeAlsoSections":[{"title":"Collection view cells","generated":true,"anchor":"Collection-view-cells","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfigurationUsingState:"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"A block for handling updates to the cell’s configuration using the current state.","type":"text"}],"sections":[],"references":{"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCellConfigurationUpdateHandler":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCellConfigurationUpdateHandler","type":"topic","title":"UICollectionViewCellConfigurationUpdateHandler","url":"/documentation/uikit/uicollectionviewcellconfigurationupdatehandler","kind":"symbol","fragments":[{"kind":"identifier","text":"UICollectionViewCellConfigurationUpdateHandler"}],"abstract":[{"text":"The type of block for handling updates to the cell’s configuration using the current state.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking":{"kind":"article","abstract":[{"text":"Reduce the need to manually register for trait changes when you use traits within a method or closure that supports automatic trait tracking.","type":"text"}],"url":"/documentation/uikit/automatic-trait-tracking","identifier":"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking","title":"Automatic trait tracking","role":"collectionGroup","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationUpdateHandler-ajhn":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationUpdateHandler-ajhn","type":"topic","title":"configurationUpdateHandler","url":"/documentation/uikit/uicollectionviewcell/configurationupdatehandler-ajhn","kind":"symbol","fragments":[{"kind":"identifier","text":"configurationUpdateHandler"}],"abstract":[{"text":"A block for handling updates to the cell’s configuration using the current state.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell":{"kind":"symbol","title":"UICollectionViewCell","abstract":[{"type":"text","text":"A single data item when that item is within the collection view’s visible bounds."}],"url":"/documentation/uikit/uicollectionviewcell","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UICollectionViewCell"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionViewCell"}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/setNeedsUpdateConfiguration()":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/setNeedsUpdateConfiguration()","type":"topic","url":"/documentation/uikit/uicollectionviewcell/setneedsupdateconfiguration()","abstract":[{"text":"Informs the cell to update its configuration for its current state.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setNeedsUpdateConfiguration","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"setNeedsUpdateConfiguration","kind":"identifier"}],"title":"setNeedsUpdateConfiguration()","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfigurationUsingState:":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfigurationUsingState:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateConfigurationUsingState:"}],"type":"topic","abstract":[{"text":"Updates the cell’s configuration using the current state.","type":"text"}],"role":"symbol","url":"/documentation/uikit/uicollectionviewcell/updateconfigurationusingstate:","title":"updateConfigurationUsingState:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"updateConfigurationUsingState:"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"UICollectionViewCell","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell/title"},{"value":[{"text":"UICollectionViewCell","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UICollectionViewCell"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell/navigatorTitle","op":"replace"},{"value":"setNeedsUpdateConfiguration","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell~1setNeedsUpdateConfiguration()/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setNeedsUpdateConfiguration","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell~1setNeedsUpdateConfiguration()/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}