{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfiguration(using:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell"]]},"sections":[],"abstract":[{"text":"Updates the cell’s configuration using the current state.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationUpdateHandler-7rqbu"],"generated":true,"anchor":"Collection-view-cells","title":"Collection view cells"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uicollectionviewcell/updateconfiguration(using:)"]}],"metadata":{"externalID":"c:@CM@UIKit@@objc(cs)UICollectionViewCell(im)_bridgedUpdateConfigurationUsingState:","title":"updateConfiguration(using:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateConfiguration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICellConfigurationState","preciseIdentifier":"s:5UIKit24UICellConfigurationStateV"},{"kind":"text","text":")"}],"modules":[{"name":"UIKit"}],"extendedModule":"UIKit","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","platforms":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"14.0"},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"14.0"},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"14.0","unavailable":false},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":"(_bridgedUpdateConfigurationUsingState:) ","kind":"text"},{"text":"@preconcurrency","kind":"attribute"},{"text":" ","kind":"text"},{"text":"dynamic","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"using","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"state","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-swift.struct","text":"UICellConfigurationState","preciseIdentifier":"s:5UIKit24UICellConfigurationStateV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Avoid calling this method directly. Instead, use "},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/setNeedsUpdateConfiguration()","type":"reference"},{"type":"text","text":" to request an update."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Override this method in a subclass to update the cell’s configuration using the provided state."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In iOS 18 and later, UIKit supports automatic trait tracking inside this method for traits from this cell’s "},{"type":"codeVoice","code":"traitCollection"},{"type":"text","text":". For more information, see "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking","isActive":true},{"type":"text","text":"."}]}],"kind":"content"}],"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell":{"kind":"symbol","title":"UICollectionViewCell","abstract":[{"type":"text","text":"A single data item when that item is within the collection view’s visible bounds."}],"url":"/documentation/uikit/uicollectionviewcell","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UICollectionViewCell"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionViewCell"}]},"doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-swift.struct":{"role":"symbol","url":"/documentation/uikit/uicellconfigurationstate-swift.struct","abstract":[{"text":"A structure that encapsulates a cell’s state.","type":"text"}],"type":"topic","title":"UICellConfigurationState","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICellConfigurationState","kind":"identifier"}],"navigatorTitle":[{"text":"UICellConfigurationState","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-swift.struct","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfiguration(using:)":{"abstract":[{"text":"Updates the cell’s configuration using the current state.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"text":"using","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UICellConfigurationState","kind":"typeIdentifier","preciseIdentifier":"s:5UIKit24UICellConfigurationStateV"},{"text":")","kind":"text"}],"url":"/documentation/uikit/uicollectionviewcell/updateconfiguration(using:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfiguration(using:)","kind":"symbol","type":"topic","role":"symbol","title":"updateConfiguration(using:)"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking":{"kind":"article","abstract":[{"text":"Reduce the need to manually register for trait changes when you use traits within a method or closure that supports automatic trait tracking.","type":"text"}],"url":"/documentation/uikit/automatic-trait-tracking","identifier":"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking","title":"Automatic trait tracking","role":"collectionGroup","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/setNeedsUpdateConfiguration()":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/setNeedsUpdateConfiguration()","type":"topic","url":"/documentation/uikit/uicollectionviewcell/setneedsupdateconfiguration()","abstract":[{"text":"Informs the cell to update its configuration for its current state.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setNeedsUpdateConfiguration","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"setNeedsUpdateConfiguration","kind":"identifier"}],"title":"setNeedsUpdateConfiguration()","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationUpdateHandler-7rqbu":{"role":"symbol","url":"/documentation/uikit/uicollectionviewcell/configurationupdatehandler-7rqbu","abstract":[{"type":"text","text":"A block for handling updates to the cell’s configuration using the current state."}],"type":"topic","title":"configurationUpdateHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationUpdateHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewCell","text":"UICollectionViewCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:So20UICollectionViewCellC5UIKitE26ConfigurationUpdateHandlera","text":"ConfigurationUpdateHandler"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationUpdateHandler-7rqbu","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell/title","value":"UICollectionViewCell","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell/fragments","value":[{"text":"UICollectionViewCell","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell/navigatorTitle","value":[{"kind":"identifier","text":"UICollectionViewCell"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell~1setNeedsUpdateConfiguration()/title","value":"setNeedsUpdateConfiguration","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setNeedsUpdateConfiguration"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell~1setNeedsUpdateConfiguration()/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}