{
  "abstract": [
    {
      "text": "Tests whether or not a record matches a search element.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElement"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElement/matchesRecord(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ABSearchElement(im)matchesRecord:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "matchesRecord"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ABRecord",
        "text": "ABRecord"
      },
      {
        "kind": "text",
        "text": "!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "matchesRecord:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "matchesRecord(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "matchesRecord"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "record"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.class",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ABRecord",
              "text": "ABRecord"
            },
            {
              "kind": "text",
              "text": "!) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The record to be tested against the search object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "record"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if the ",
              "type": "text"
            },
            {
              "code": "record",
              "type": "codeVoice"
            },
            {
              "text": " argument satisfies the conditions in the search element; otherwise, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If ",
              "type": "text"
            },
            {
              "code": "record",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", this method raises an exception.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.class": {
      "abstract": [
        {
          "text": "An abstract class that defines the common properties for all Address Book records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecord"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABRecord"
        }
      ],
      "role": "symbol",
      "title": "ABRecord",
      "type": "topic",
      "url": "/documentation/addressbook/abrecord-swift.class"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElement": {
      "abstract": [
        {
          "text": "An object you use to specify a search query for records in the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABSearchElement"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABSearchElement"
        }
      ],
      "role": "symbol",
      "title": "ABSearchElement",
      "type": "topic",
      "url": "/documentation/addressbook/absearchelement"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElement/matchesRecord(_:)": {
      "abstract": [
        {
          "text": "Tests whether or not a record matches a search element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchesRecord"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABRecord",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElement/matchesRecord(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchesRecord:"
        }
      ],
      "role": "symbol",
      "title": "matchesRecord(_:)",
      "type": "topic",
      "url": "/documentation/addressbook/absearchelement/matchesrecord(_:)"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "matchesRecord:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "matchesRecord:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook",
                "doc://com.apple.addressbook/documentation/AddressBook/ABSearchElement"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "matchesRecord:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABRecord-swift.class",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ABRecord",
                    "text": "ABRecord"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "record"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The record to be tested against the search object.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "record"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/true",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if the ",
                    "type": "text"
                  },
                  {
                    "code": "record",
                    "type": "codeVoice"
                  },
                  {
                    "text": " argument satisfies the conditions in the search element; otherwise, ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/false",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchElement/title",
          "value": "ABSearchElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABSearchElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchElement~1matchesRecord(_:)/title",
          "value": "matchesRecord:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABSearchElement~1matchesRecord(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "matchesRecord:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.class/title",
          "value": "ABRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABRecord-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABRecord"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/absearchelement/matchesrecord(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/absearchelement/matchesrecord(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
