{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/collection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSFontPanelModeMask@NSFontPanelModeMaskCollection",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "collection"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSFontPanel",
        "text": "NSFontPanel"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSFontPanelModeMask",
        "text": "ModeMask"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFontPanelModeMaskCollection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "collection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "collection"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSFontPanel",
              "text": "NSFontPanel"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSFontPanelModeMask",
              "text": "ModeMask"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel": {
      "abstract": [
        {
          "text": "The Font panel—a user interface object that displays a list of available fonts, letting the user preview them and change the font used to display text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanel"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ModeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ModeMask"
        }
      ],
      "role": "symbol",
      "title": "NSFontPanel.ModeMask",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel/modemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/allEffects": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allEffects"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontPanel",
          "text": "NSFontPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontPanelModeMask",
          "text": "ModeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/allEffects",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelModeMaskAllEffects"
        }
      ],
      "role": "symbol",
      "title": "allEffects",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel/modemask/alleffects"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/allModes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allModes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontPanel",
          "text": "NSFontPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontPanelModeMask",
          "text": "ModeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/allModes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelModesMaskAllModes"
        }
      ],
      "role": "symbol",
      "title": "allModes",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel/modemask/allmodes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/collection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontPanel",
          "text": "NSFontPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontPanelModeMask",
          "text": "ModeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/collection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelModeMaskCollection"
        }
      ],
      "role": "symbol",
      "title": "collection",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel/modemask/collection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/documentColorEffect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentColorEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontPanel",
          "text": "NSFontPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontPanelModeMask",
          "text": "ModeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/documentColorEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelModeMaskDocumentColorEffect"
        }
      ],
      "role": "symbol",
      "title": "documentColorEffect",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel/modemask/documentcoloreffect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/face": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "face"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontPanel",
          "text": "NSFontPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontPanelModeMask",
          "text": "ModeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/face",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelModeMaskFace"
        }
      ],
      "role": "symbol",
      "title": "face",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel/modemask/face"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/shadowEffect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadowEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontPanel",
          "text": "NSFontPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontPanelModeMask",
          "text": "ModeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/shadowEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelModeMaskShadowEffect"
        }
      ],
      "role": "symbol",
      "title": "shadowEffect",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel/modemask/shadoweffect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/size": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontPanel",
          "text": "NSFontPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontPanelModeMask",
          "text": "ModeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelModeMaskSize"
        }
      ],
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel/modemask/size"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/standardModes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standardModes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontPanel",
          "text": "NSFontPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontPanelModeMask",
          "text": "ModeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/standardModes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelModesMaskStandardModes"
        }
      ],
      "role": "symbol",
      "title": "standardModes",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel/modemask/standardmodes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/strikethroughEffect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strikethroughEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontPanel",
          "text": "NSFontPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontPanelModeMask",
          "text": "ModeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/strikethroughEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelModeMaskStrikethroughEffect"
        }
      ],
      "role": "symbol",
      "title": "strikethroughEffect",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel/modemask/strikethrougheffect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/textColorEffect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textColorEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontPanel",
          "text": "NSFontPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontPanelModeMask",
          "text": "ModeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/textColorEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelModeMaskTextColorEffect"
        }
      ],
      "role": "symbol",
      "title": "textColorEffect",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel/modemask/textcoloreffect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/underlineEffect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "underlineEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontPanel",
          "text": "NSFontPanel"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFontPanelModeMask",
          "text": "ModeMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/underlineEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontPanelModeMaskUnderlineEffect"
        }
      ],
      "role": "symbol",
      "title": "underlineEffect",
      "type": "topic",
      "url": "/documentation/appkit/nsfontpanel/modemask/underlineeffect"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/allEffects",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/allModes",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/documentColorEffect",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/face",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/shadowEffect",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/size",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/standardModes",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/strikethroughEffect",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/textColorEffect",
        "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/underlineEffect"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFontPanelModeMaskCollection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModeMaskCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/allEffects",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/allModes",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/documentColorEffect",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/face",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/shadowEffect",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/size",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/standardModes",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/strikethroughEffect",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/textColorEffect",
                "doc://com.apple.appkit/documentation/AppKit/NSFontPanel/ModeMask/underlineEffect"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSFontPanelModeMaskCollection"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1allModes/title",
          "value": "NSFontPanelModesMaskAllModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1allModes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModesMaskAllModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1face/title",
          "value": "NSFontPanelModeMaskFace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1face/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModeMaskFace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1collection/title",
          "value": "NSFontPanelModeMaskCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1collection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModeMaskCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1documentColorEffect/title",
          "value": "NSFontPanelModeMaskDocumentColorEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1documentColorEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModeMaskDocumentColorEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1shadowEffect/title",
          "value": "NSFontPanelModeMaskShadowEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1shadowEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModeMaskShadowEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1textColorEffect/title",
          "value": "NSFontPanelModeMaskTextColorEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1textColorEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModeMaskTextColorEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1allEffects/title",
          "value": "NSFontPanelModeMaskAllEffects"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1allEffects/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModeMaskAllEffects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel/title",
          "value": "NSFontPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1underlineEffect/title",
          "value": "NSFontPanelModeMaskUnderlineEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1underlineEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModeMaskUnderlineEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1size/title",
          "value": "NSFontPanelModeMaskSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModeMaskSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask/title",
          "value": "NSFontPanelModeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1strikethroughEffect/title",
          "value": "NSFontPanelModeMaskStrikethroughEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1strikethroughEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModeMaskStrikethroughEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1standardModes/title",
          "value": "NSFontPanelModesMaskStandardModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontPanel~1ModeMask~1standardModes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontPanelModesMaskStandardModes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfontpanel/modemask/collection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfontpanel/modemask/collection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
