{
  "abstract": [
    {
      "text": "The AR session is attempting to resume after an interruption.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARCamera",
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum",
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/relocalizing"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So8ARCameraC5ARKitE13TrackingStateO6ReasonO12relocalizingyA2GmF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "relocalizing"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ARCamera.TrackingState.Reason.relocalizing"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "relocalizing"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.arkit/documentation/ARKit/managing-session-life-cycle-and-tracking-quality"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "ARKit cannot track device position or orientation when the session has been interrupted (for example, by dismissing the view hosting an AR session or switching to another app). When resuming the session after an interruption, the world coordinate system (used for placing anchors) likely no longer match the device’s real-world environment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your session or view delegate implements the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSessionObserver/sessionShouldAttemptRelocalization(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method and returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ARKit attempts to reconcile pre- and post-interruption world tracking state. During this process, called ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "relocalization",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", world tracking quality is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/limited(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", with a resaon value of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/relocalizing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", indicating that hit tests and anchor placement are less accurate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If successful, relocalization ends after a short time, tracking quality returns to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/normal",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " state, and the world coordinate system and anchor positions reflect their state before the interruption.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For relocalization to succeed, the device must be returned to a position and orientation approximately near where it was when the session was interrupted. If these conditions never occur (or cannot occur; for example, if the device has moved to an entirely different environment), the session will remain in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/relocalizing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " state indefinitely.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "When in the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/relocalizing",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " state, offer the user a way out in case relocalization never succeeds. For example, offer a button for resetting the session, which appears after the relocalizing state has remained for a fixed amount of time.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera": {
      "abstract": [
        {
          "text": "Information about the camera position and imaging characteristics for a given frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARCamera"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARCamera"
        }
      ],
      "role": "symbol",
      "title": "ARCamera",
      "type": "topic",
      "url": "/documentation/arkit/arcamera"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum": {
      "abstract": [
        {
          "text": "Values for position tracking quality, with possible causes when tracking quality is limited.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TrackingState"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TrackingState"
        }
      ],
      "role": "symbol",
      "title": "ARCamera.TrackingState",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstate-swift.enum"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason": {
      "abstract": [
        {
          "text": "Causes of limited position-tracking quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Reason"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Reason"
        }
      ],
      "role": "symbol",
      "title": "ARCamera.TrackingState.Reason",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstate-swift.enum/reason"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/excessiveMotion": {
      "abstract": [
        {
          "text": "The device is moving too fast for accurate image-based position tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "excessiveMotion"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/excessiveMotion",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARCamera.TrackingState.Reason.excessiveMotion",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstate-swift.enum/reason/excessivemotion"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/initializing": {
      "abstract": [
        {
          "text": "The AR session has not gathered enough camera or motion data to provide tracking information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initializing"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/initializing",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARCamera.TrackingState.Reason.initializing",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstate-swift.enum/reason/initializing"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/insufficientFeatures": {
      "abstract": [
        {
          "text": "The scene visible to the camera doesn’t contain enough distinguishable features for image-based position tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientFeatures"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/insufficientFeatures",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARCamera.TrackingState.Reason.insufficientFeatures",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstate-swift.enum/reason/insufficientfeatures"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/relocalizing": {
      "abstract": [
        {
          "text": "The AR session is attempting to resume after an interruption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relocalizing"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/relocalizing",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARCamera.TrackingState.Reason.relocalizing",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstate-swift.enum/reason/relocalizing"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/limited(_:)": {
      "abstract": [
        {
          "text": "Tracking is available, but the quality of results is questionable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limited"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARCamera",
          "text": "ARCamera"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8ARCameraC5ARKitE13TrackingStateO",
          "text": "TrackingState"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8ARCameraC5ARKitE13TrackingStateO6ReasonO",
          "text": "Reason"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/limited(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARCamera.TrackingState.limited(_:)",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstate-swift.enum/limited(_:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/normal": {
      "abstract": [
        {
          "text": "Camera position tracking is providing optimal results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normal"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/normal",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARCamera.TrackingState.normal",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstate-swift.enum/normal"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSessionObserver/sessionShouldAttemptRelocalization(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether to attempt recovery of world-tracking state after an interruption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionShouldAttemptRelocalization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSession",
          "text": "ARSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSessionObserver/sessionShouldAttemptRelocalization(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sessionShouldAttemptRelocalization:"
        }
      ],
      "role": "symbol",
      "title": "sessionShouldAttemptRelocalization(_:)",
      "type": "topic",
      "url": "/documentation/arkit/arsessionobserver/sessionshouldattemptrelocalization(_:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/managing-session-life-cycle-and-tracking-quality": {
      "abstract": [
        {
          "text": "Keep the user informed on the current session state and recover from interruptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/managing-session-life-cycle-and-tracking-quality",
      "kind": "article",
      "role": "article",
      "title": "Managing Session Life Cycle and Tracking Quality",
      "type": "topic",
      "url": "/documentation/arkit/managing-session-life-cycle-and-tracking-quality"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inhibitors-of-Tracking-Quality",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/initializing",
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/excessiveMotion",
        "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/insufficientFeatures"
      ],
      "title": "Inhibitors of Tracking Quality"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSessionObserver~1sessionShouldAttemptRelocalization(_:)/title",
          "value": "sessionShouldAttemptRelocalization:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSessionObserver~1sessionShouldAttemptRelocalization(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sessionShouldAttemptRelocalization:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera/title",
          "value": "ARCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARCamera/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARCamera"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arcamera/trackingstate-swift.enum/reason/relocalizing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
