{
  "abstract": [
    {
      "text": "Creates a hinge joint connecting two physics bodies.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/init(bodyA:axisA:anchorA:bodyB:axisB:anchorB:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SCNPhysicsHingeJoint(cm)jointWithBodyA:axisA:anchorA:bodyB:axisB:anchorB:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "bodyA"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SCNPhysicsBody",
        "text": "SCNPhysicsBody"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "axisA"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@SCNVector3",
        "text": "SCNVector3"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "anchorA"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@SCNVector3",
        "text": "SCNVector3"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "bodyB"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SCNPhysicsBody",
        "text": "SCNPhysicsBody"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "axisB"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@SCNVector3",
        "text": "SCNVector3"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "anchorB"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@SCNVector3",
        "text": "SCNVector3"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "jointWithBodyA:axisA:anchorA:bodyB:axisB:anchorB:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(bodyA:axisA:anchorA:bodyB:axisB:anchorB:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "bodyA"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SCNPhysicsBody",
              "text": "SCNPhysicsBody"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "axisA"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNVector3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@SCNVector3",
              "text": "SCNVector3"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "anchorA"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNVector3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@SCNVector3",
              "text": "SCNVector3"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "bodyB"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SCNPhysicsBody",
              "text": "SCNPhysicsBody"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "axisB"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNVector3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@SCNVector3",
              "text": "SCNVector3"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "anchorB"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNVector3",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@SCNVector3",
              "text": "SCNVector3"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The first physics body to be connected by the joint.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "bodyA"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The axis that the hinge pivots around, relative to the node containing the first body.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "axisA"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The point at which the hinge connects, relative to the node containing the first body.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "anchorA"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The second physics body to be connected by the joint.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "bodyB"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The axis that the hinge pivots around, relative to the node containing the second body.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "axisB"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The point at which the hinge connects, relative to the node containing the second body.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "anchorB"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new hinge joint behavior.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For a behavior to take effect, add it to the physics simulation by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsWorld/addBehavior(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on your scene’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsWorld",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. The physics bodies constrained by the joint must be attached to nodes in the scene.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody": {
      "abstract": [
        {
          "text": "The physics simulation attributes attached to a scene graph node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPhysicsBody"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsBody"
        }
      ],
      "role": "symbol",
      "title": "SCNPhysicsBody",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint": {
      "abstract": [
        {
          "text": "A physics behavior that connects two bodies and allows them to pivot around each other on a single axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPhysicsHingeJoint"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsHingeJoint"
        }
      ],
      "role": "symbol",
      "title": "SCNPhysicsHingeJoint",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicshingejoint"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/init(body:axis:anchor:)": {
      "abstract": [
        {
          "text": "Creates a hinge joint that anchors a single physics body in space and lets it rotate around a specific axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "body"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNPhysicsBody",
          "text": "SCNPhysicsBody"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "axis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "anchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/init(body:axis:anchor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "jointWithBody:axis:anchor:"
        }
      ],
      "role": "symbol",
      "title": "init(body:axis:anchor:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicshingejoint/init(body:axis:anchor:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/init(bodyA:axisA:anchorA:bodyB:axisB:anchorB:)": {
      "abstract": [
        {
          "text": "Creates a hinge joint connecting two physics bodies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bodyA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNPhysicsBody",
          "text": "SCNPhysicsBody"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "axisA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "anchorA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bodyB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNPhysicsBody",
          "text": "SCNPhysicsBody"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "axisB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "anchorB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/init(bodyA:axisA:anchorA:bodyB:axisB:anchorB:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "jointWithBodyA:axisA:anchorA:bodyB:axisB:anchorB:"
        }
      ],
      "role": "symbol",
      "title": "init(bodyA:axisA:anchorA:bodyB:axisB:anchorB:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicshingejoint/init(bodya:axisa:anchora:bodyb:axisb:anchorb:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsWorld": {
      "abstract": [
        {
          "text": "The global simulation of collisions, gravity, joints, and other physics effects in a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPhysicsWorld"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsWorld",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsWorld"
        }
      ],
      "role": "symbol",
      "title": "SCNPhysicsWorld",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsworld"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsWorld/addBehavior(_:)": {
      "abstract": [
        {
          "text": "Adds a behavior to the physics world.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addBehavior"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNPhysicsBehavior",
          "text": "SCNPhysicsBehavior"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsWorld/addBehavior(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addBehavior:"
        }
      ],
      "role": "symbol",
      "title": "addBehavior(_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsworld/addbehavior(_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNVector3": {
      "abstract": [
        {
          "text": "A representation of a three-component vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNVector3"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNVector3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNVector3"
        }
      ],
      "role": "symbol",
      "title": "SCNVector3",
      "type": "topic",
      "url": "/documentation/scenekit/scnvector3"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Hinge-Joint",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/init(body:axis:anchor:)"
      ],
      "title": "Creating a Hinge Joint"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "jointWithBodyA:axisA:anchorA:bodyB:axisB:anchorB:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "jointWithBodyA:axisA:anchorA:bodyB:axisB:anchorB:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Hinge-Joint",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsHingeJoint/init(body:axis:anchor:)"
              ],
              "title": "Creating a Hinge Joint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "jointWithBodyA:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SCNPhysicsBody",
                    "text": "SCNPhysicsBody"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "bodyA"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "axisA:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNVector3",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@SCNVector3",
                    "text": "SCNVector3"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "axisA"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "anchorA:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNVector3",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@SCNVector3",
                    "text": "SCNVector3"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "anchorA"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "bodyB:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SCNPhysicsBody",
                    "text": "SCNPhysicsBody"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "bodyB"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "axisB:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNVector3",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@SCNVector3",
                    "text": "SCNVector3"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "axisB"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "anchorB:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNVector3",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@SCNVector3",
                    "text": "SCNVector3"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "anchorB"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The first physics body to be connected by the joint.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "bodyA"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The axis that the hinge pivots around, relative to the node containing the first body.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "axisA"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The point at which the hinge connects, relative to the node containing the first body.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "anchorA"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The second physics body to be connected by the joint.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "bodyB"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The axis that the hinge pivots around, relative to the node containing the second body.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "axisB"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The point at which the hinge connects, relative to the node containing the second body.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "anchorB"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new hinge joint behavior.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector3/title",
          "value": "SCNVector3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNVector3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNVector3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint/title",
          "value": "SCNPhysicsHingeJoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsHingeJoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsHingeJoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsWorld~1addBehavior(_:)/title",
          "value": "addBehavior:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsWorld~1addBehavior(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addBehavior:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1init(body:axis:anchor:)/title",
          "value": "jointWithBody:axis:anchor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1init(body:axis:anchor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "jointWithBody:axis:anchor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/title",
          "value": "SCNPhysicsBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1init(bodyA:axisA:anchorA:bodyB:axisB:anchorB:)/title",
          "value": "jointWithBodyA:axisA:anchorA:bodyB:axisB:anchorB:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsHingeJoint~1init(bodyA:axisA:anchorA:bodyB:axisB:anchorB:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "jointWithBodyA:axisA:anchorA:bodyB:axisB:anchorB:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsWorld/title",
          "value": "SCNPhysicsWorld"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsWorld/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsWorld"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsWorld/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsWorld"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnphysicshingejoint/init(bodya:axisa:anchora:bodyb:axisb:anchorb:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnphysicshingejoint/init(bodya:axisa:anchora:bodyb:axisb:anchorb:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
