{
  "abstract": [
    {
      "text": "Sets the delegate that will accept captured buffers and the dispatch queue on which the delegate will be called.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutput"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutput/setSampleBufferDelegate(_:queue:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVCaptureAudioDataOutput(im)setSampleBufferDelegate:queue:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setSampleBufferDelegate"
      },
      {
        "kind": "text",
        "text": "((any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)AVCaptureAudioDataOutputSampleBufferDelegate",
        "text": "AVCaptureAudioDataOutputSampleBufferDelegate"
      },
      {
        "kind": "text",
        "text": ")?, "
      },
      {
        "kind": "externalParam",
        "text": "queue"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@dispatch_queue_t",
        "text": "dispatch_queue_t"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setSampleBufferDelegate:queue:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setSampleBufferDelegate(_:queue:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setSampleBufferDelegate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sampleBufferDelegate"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutputSampleBufferDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)AVCaptureAudioDataOutputSampleBufferDelegate",
              "text": "AVCaptureAudioDataOutputSampleBufferDelegate"
            },
            {
              "kind": "text",
              "text": ")?, "
            },
            {
              "kind": "externalParam",
              "text": "queue"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "sampleBufferCallbackQueue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_queue_t",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object conforming to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutputSampleBufferDelegate",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " protocol that will receive sample buffers after they are captured.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sampleBufferDelegate"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "You must pass a serial dispatch to guarantee that audio samples will be delivered in order.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "The value may not be ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ", except when setting the ",
                  "type": "text"
                },
                {
                  "code": "sampleBufferDelegate",
                  "type": "codeVoice"
                },
                {
                  "text": " to ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "sampleBufferCallbackQueue"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When a new audio sample buffer is captured it is vended to the sample buffer delegate using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutputSampleBufferDelegate/captureOutput(_:didOutput:from:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " delegate method. All delegate methods are called on the specified dispatch queue.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the queue is blocked when new samples are captured, those samples will be automatically dropped when they become sufficiently late. This allows you to process existing samples on the same queue without having to manage the potential memory usage increases that would otherwise occur when that processing is unable to keep up with the rate of incoming samples.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you need to minimize the chances of samples being dropped, you should specify a queue on which a sufficiently small amount of processing is being done outside of receiving sample buffers. When migrating extra processing to another queue, you are responsible for ensuring that memory usage does not grow without bound from samples that have not been processed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Special-Considerations",
          "level": 3,
          "text": "Special Considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method uses ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/dispatch/1496306-dispatch_retain",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/dispatch/1496328-dispatch_release",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to manage the queue.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutput": {
      "abstract": [
        {
          "text": "A capture output that records audio and provides access to audio sample buffers as they are recorded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureAudioDataOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureAudioDataOutput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureAudioDataOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureaudiodataoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutput/sampleBufferCallbackQueue": {
      "abstract": [
        {
          "text": "The queue on which delegate callbacks are invoked",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleBufferCallbackQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutput/sampleBufferCallbackQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sampleBufferCallbackQueue"
        }
      ],
      "role": "symbol",
      "title": "sampleBufferCallbackQueue",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureaudiodataoutput/samplebuffercallbackqueue"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutput/sampleBufferDelegate": {
      "abstract": [
        {
          "text": "The capture object’s delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleBufferDelegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVCaptureAudioDataOutputSampleBufferDelegate",
          "text": "AVCaptureAudioDataOutputSampleBufferDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutput/sampleBufferDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sampleBufferDelegate"
        }
      ],
      "role": "symbol",
      "title": "sampleBufferDelegate",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureaudiodataoutput/samplebufferdelegate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutput/setSampleBufferDelegate(_:queue:)": {
      "abstract": [
        {
          "text": "Sets the delegate that will accept captured buffers and the dispatch queue on which the delegate will be called.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setSampleBufferDelegate"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVCaptureAudioDataOutputSampleBufferDelegate",
          "text": "AVCaptureAudioDataOutputSampleBufferDelegate"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutput/setSampleBufferDelegate(_:queue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSampleBufferDelegate:queue:"
        }
      ],
      "role": "symbol",
      "title": "setSampleBufferDelegate(_:queue:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureaudiodataoutput/setsamplebufferdelegate(_:queue:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutputSampleBufferDelegate": {
      "abstract": [
        {
          "text": "Methods for receiving audio sample data from an audio capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureAudioDataOutputSampleBufferDelegate"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutputSampleBufferDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureAudioDataOutputSampleBufferDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureAudioDataOutputSampleBufferDelegate",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureaudiodataoutputsamplebufferdelegate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutputSampleBufferDelegate/captureOutput(_:didOutput:from:)": {
      "abstract": [
        {
          "text": "Notifies the delegate that a sample buffer was written.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "captureOutput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureOutput",
          "text": "AVCaptureOutput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureConnection",
          "text": "AVCaptureConnection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutputSampleBufferDelegate/captureOutput(_:didOutput:from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "captureOutput:didOutputSampleBuffer:fromConnection:"
        }
      ],
      "role": "symbol",
      "title": "captureOutput(_:didOutput:from:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureaudiodataoutputsamplebufferdelegate/captureoutput(_:didoutput:from:)"
    },
    "doc://com.apple.documentation/documentation/dispatch/1496306-dispatch_retain": {
      "abstract": [
        {
          "text": "Increments the reference count (the retain count) of a dispatch object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/dispatch/1496306-dispatch_retain",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_retain",
      "type": "topic",
      "url": "/documentation/dispatch/1496306-dispatch_retain"
    },
    "doc://com.apple.documentation/documentation/dispatch/1496328-dispatch_release": {
      "abstract": [
        {
          "text": "Decrements the reference count (the retain count) of a dispatch object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/dispatch/1496328-dispatch_release",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_release",
      "type": "topic",
      "url": "/documentation/dispatch/1496328-dispatch_release"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t": {
      "abstract": [
        {
          "text": "A lightweight object to which your application submits blocks for subsequent execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_t",
      "type": "topic",
      "url": "/documentation/Dispatch/dispatch_queue_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Receiving-Captured-Audio-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutput/sampleBufferDelegate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutput/sampleBufferCallbackQueue",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutputSampleBufferDelegate"
      ],
      "title": "Receiving Captured Audio Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setSampleBufferDelegate:queue:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setSampleBufferDelegate:queue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutput"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Receiving-Captured-Audio-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutput/sampleBufferDelegate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutput/sampleBufferCallbackQueue",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutputSampleBufferDelegate"
              ],
              "title": "Receiving Captured Audio Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setSampleBufferDelegate:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)AVCaptureAudioDataOutputSampleBufferDelegate",
                    "text": "id<AVCaptureAudioDataOutputSampleBufferDelegate>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sampleBufferDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "queue:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@dispatch_queue_t",
                    "text": "dispatch_queue_t"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "sampleBufferCallbackQueue"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An object conforming to the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioDataOutputSampleBufferDelegate",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " protocol that will receive sample buffers after they are captured.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sampleBufferDelegate"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "You must pass a serial dispatch to guarantee that audio samples will be delivered in order.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The value may not be ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", except when setting the ",
                        "type": "text"
                      },
                      {
                        "code": "sampleBufferDelegate",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "sampleBufferCallbackQueue"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioDataOutput~1sampleBufferCallbackQueue/title",
          "value": "sampleBufferCallbackQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioDataOutput~1sampleBufferCallbackQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sampleBufferCallbackQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioDataOutput/title",
          "value": "AVCaptureAudioDataOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioDataOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureAudioDataOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioDataOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureAudioDataOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioDataOutput~1sampleBufferDelegate/title",
          "value": "sampleBufferDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioDataOutput~1sampleBufferDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sampleBufferDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@dispatch_queue_t/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue",
              "text": "NSObject<OS_dispatch_queue>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioDataOutput~1setSampleBufferDelegate(_:queue:)/title",
          "value": "setSampleBufferDelegate:queue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioDataOutput~1setSampleBufferDelegate(_:queue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setSampleBufferDelegate:queue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioDataOutputSampleBufferDelegate/title",
          "value": "AVCaptureAudioDataOutputSampleBufferDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioDataOutputSampleBufferDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureAudioDataOutputSampleBufferDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioDataOutputSampleBufferDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureAudioDataOutputSampleBufferDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioDataOutputSampleBufferDelegate~1captureOutput(_:didOutput:from:)/title",
          "value": "captureOutput:didOutputSampleBuffer:fromConnection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioDataOutputSampleBufferDelegate~1captureOutput(_:didOutput:from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "captureOutput:didOutputSampleBuffer:fromConnection:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcaptureaudiodataoutput/setsamplebufferdelegate(_:queue:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcaptureaudiodataoutput/setsamplebufferdelegate(_:queue:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
