{
  "abstract": [
    {
      "text": "Indicates that a file uses the LZFSE compression algorithm codec.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/lzfse"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLIOCompressionMethod@MTLIOCompressionMethodLZFSE",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lzfse"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLIOCompressionMethodLZFSE"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLIOCompressionMethod.lzfse"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lzfse"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on the LZFSE codec, see:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Compression/Algorithm/lzfse",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Compression/COMPRESSION_LZFSE",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Compression/Algorithm/lzfse": {
      "abstract": [
        {
          "text": "The LZFSE compression algorithm, which is recommended for use on Apple platforms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lzfse"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Compression/Algorithm/lzfse",
      "kind": "symbol",
      "role": "symbol",
      "title": "Algorithm.lzfse",
      "type": "topic",
      "url": "/documentation/Compression/Algorithm/lzfse"
    },
    "doc://com.apple.documentation/documentation/Compression/COMPRESSION_LZFSE": {
      "abstract": [
        {
          "text": "The LZFSE compression algorithm, which is recommended for use on Apple platforms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPRESSION_LZFSE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@compression_algorithm",
          "text": "compression_algorithm"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Compression/COMPRESSION_LZFSE",
      "kind": "symbol",
      "role": "symbol",
      "title": "COMPRESSION_LZFSE",
      "type": "topic",
      "url": "/documentation/Compression/COMPRESSION_LZFSE"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod": {
      "abstract": [
        {
          "text": "The compression codecs that Metal supports for input/output handles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLIOCompressionMethod"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCompressionMethod"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCompressionMethod",
      "type": "topic",
      "url": "/documentation/metal/mtliocompressionmethod"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/lz4": {
      "abstract": [
        {
          "text": "Indicates that a file uses the LZ4 compression algorithm codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lz4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/lz4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCompressionMethodLZ4"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCompressionMethod.lz4",
      "type": "topic",
      "url": "/documentation/metal/mtliocompressionmethod/lz4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/lzBitmap": {
      "abstract": [
        {
          "text": "Indicates that a file uses the LZBitmap compression algorithm codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lzBitmap"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/lzBitmap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCompressionMethodLZBitmap"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCompressionMethod.lzBitmap",
      "type": "topic",
      "url": "/documentation/metal/mtliocompressionmethod/lzbitmap"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/lzfse": {
      "abstract": [
        {
          "text": "Indicates that a file uses the LZFSE compression algorithm codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lzfse"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/lzfse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCompressionMethodLZFSE"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCompressionMethod.lzfse",
      "type": "topic",
      "url": "/documentation/metal/mtliocompressionmethod/lzfse"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/lzma": {
      "abstract": [
        {
          "text": "Indicates that a file uses the LZMA compression algorithm codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lzma"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/lzma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCompressionMethodLZMA"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCompressionMethod.lzma",
      "type": "topic",
      "url": "/documentation/metal/mtliocompressionmethod/lzma"
    },
    "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/zlib": {
      "abstract": [
        {
          "text": "Indicates that a file uses the zlib compression algorithm codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zlib"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/zlib",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLIOCompressionMethodZlib"
        }
      ],
      "role": "symbol",
      "title": "MTLIOCompressionMethod.zlib",
      "type": "topic",
      "url": "/documentation/metal/mtliocompressionmethod/zlib"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Compression-Codecs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/zlib",
        "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/lz4",
        "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/lzma",
        "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/lzBitmap"
      ],
      "title": "Compression Codecs"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLIOCompressionMethodLZFSE"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionMethodLZFSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Compression-Codecs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/zlib",
                "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/lz4",
                "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/lzma",
                "doc://com.apple.metal/documentation/Metal/MTLIOCompressionMethod/lzBitmap"
              ],
              "title": "Compression Codecs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLIOCompressionMethodLZFSE"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod~1lzfse/title",
          "value": "MTLIOCompressionMethodLZFSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod~1lzfse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionMethodLZFSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Compression~1COMPRESSION_LZFSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPRESSION_LZFSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod~1lzBitmap/title",
          "value": "MTLIOCompressionMethodLZBitmap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod~1lzBitmap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionMethodLZBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod~1lzma/title",
          "value": "MTLIOCompressionMethodLZMA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod~1lzma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionMethodLZMA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod~1zlib/title",
          "value": "MTLIOCompressionMethodZlib"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod~1zlib/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionMethodZlib"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod~1lz4/title",
          "value": "MTLIOCompressionMethodLZ4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod~1lz4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionMethodLZ4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod/title",
          "value": "MTLIOCompressionMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIOCompressionMethod/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLIOCompressionMethod"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtliocompressionmethod/lzfse"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtliocompressionmethod/lzfse"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
