{
  "abstract": [
    {
      "text": "Constants that describe the possible arrangements for a split view interface.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UISplitViewControllerDisplayMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DisplayMode"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DisplayMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UISplitViewController.DisplayMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DisplayMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A split view controller’s display mode controls the visual arrangement of its child view controllers. You set a preferred display mode by using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/preferredDisplayMode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, and the split view controller updates itself and reflects the actual display mode in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/displayMode-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Display modes apply to a split view controller in an expanded arrangement. When the split view interface is collapsed — when ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/isCollapsed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " — the display mode has no impact on the appearance of the split view controller interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A split view controller’s split behavior (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/splitBehavior-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") affects its possible display modes. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/SplitBehavior-swift.enum",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Split Behavior",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Possible Display Modes",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Tile",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/secondaryOnly",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/oneBesideSecondary",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/twoBesideSecondary",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Overlay",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/secondaryOnly",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/oneOverSecondary",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/twoOverSecondary",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Displace",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/secondaryOnly",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/oneBesideSecondary",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/twoDisplaceSecondary",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "There are several ways for user interaction to change the current display mode. Based on the type of user interaction (gesture or button tap), the display mode can transition between a set of predetermined states.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3624554",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController": {
      "abstract": [
        {
          "text": "A container view controller that implements a hierarchical interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISplitViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewController"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the possible arrangements for a split view interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController.DisplayMode",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymode-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/allVisible": {
      "abstract": [
        {
          "text": "The primary and secondary view controllers are displayed side-by-side onscreen.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allVisible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerDisplayMode",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/allVisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewControllerDisplayModeAllVisible"
        }
      ],
      "role": "symbol",
      "title": "allVisible",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymode-swift.enum/allvisible"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/automatic": {
      "abstract": [
        {
          "text": "The split view controller automatically decides the most appropriate display mode based on the device and the current app size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewControllerDisplayModeAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController.DisplayMode.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymode-swift.enum/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymode-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/oneBesideSecondary": {
      "abstract": [
        {
          "text": "One sidebar appears side-by-side with the secondary view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneBesideSecondary"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/oneBesideSecondary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewControllerDisplayModeOneBesideSecondary"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController.DisplayMode.oneBesideSecondary",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymode-swift.enum/onebesidesecondary"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/oneOverSecondary": {
      "abstract": [
        {
          "text": "One sidebar is layered on top of the secondary view controller, leaving the secondary view controller partially visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneOverSecondary"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/oneOverSecondary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewControllerDisplayModeOneOverSecondary"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController.DisplayMode.oneOverSecondary",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymode-swift.enum/oneoversecondary"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/primaryHidden": {
      "abstract": [
        {
          "text": "The primary view controller is hidden.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerDisplayMode",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/primaryHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewControllerDisplayModePrimaryHidden"
        }
      ],
      "role": "symbol",
      "title": "primaryHidden",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymode-swift.enum/primaryhidden"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/primaryOverlay": {
      "abstract": [
        {
          "text": "The primary view controller is layered on top of the secondary view controller, leaving the secondary view controller partially visible.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryOverlay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerDisplayMode",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/primaryOverlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewControllerDisplayModePrimaryOverlay"
        }
      ],
      "role": "symbol",
      "title": "primaryOverlay",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymode-swift.enum/primaryoverlay"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/secondaryOnly": {
      "abstract": [
        {
          "text": "Only the secondary view controller is shown onscreen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryOnly"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/secondaryOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewControllerDisplayModeSecondaryOnly"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController.DisplayMode.secondaryOnly",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymode-swift.enum/secondaryonly"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/twoBesideSecondary": {
      "abstract": [
        {
          "text": "Two sidebars appear side-by-side with the secondary view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "twoBesideSecondary"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/twoBesideSecondary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewControllerDisplayModeTwoBesideSecondary"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController.DisplayMode.twoBesideSecondary",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymode-swift.enum/twobesidesecondary"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/twoDisplaceSecondary": {
      "abstract": [
        {
          "text": "Two sidebars displace the secondary view controller instead of overlapping it, moving it partially offscreen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "twoDisplaceSecondary"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/twoDisplaceSecondary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewControllerDisplayModeTwoDisplaceSecondary"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController.DisplayMode.twoDisplaceSecondary",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymode-swift.enum/twodisplacesecondary"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/twoOverSecondary": {
      "abstract": [
        {
          "text": "Two sidebars are layered on top of the secondary view controller, leaving the secondary view controller partially visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "twoOverSecondary"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/twoOverSecondary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewControllerDisplayModeTwoOverSecondary"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController.DisplayMode.twoOverSecondary",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymode-swift.enum/twooversecondary"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayModeButtonVisibility-swift.enum": {
      "abstract": [
        {
          "text": "Constants that determine the visibility of the display mode button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayModeButtonVisibility"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayModeButtonVisibility-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisplayModeButtonVisibility"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController.DisplayModeButtonVisibility",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymodebuttonvisibility-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/SplitBehavior-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the possible ways that the child view controllers appear in relation to each other.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SplitBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/SplitBehavior-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SplitBehavior"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController.SplitBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/splitbehavior-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/displayMode-swift.property": {
      "abstract": [
        {
          "text": "The current arrangement of the split view interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerDisplayMode",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/displayMode-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayMode"
        }
      ],
      "role": "symbol",
      "title": "displayMode",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymode-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/displayModeButtonItem": {
      "abstract": [
        {
          "text": "A button that changes the display mode of the split view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayModeButtonItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBarButtonItem",
          "text": "UIBarButtonItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/displayModeButtonItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayModeButtonItem"
        }
      ],
      "role": "symbol",
      "title": "displayModeButtonItem",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymodebuttonitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/displayModeButtonVisibility-swift.property": {
      "abstract": [
        {
          "text": "A setting that determines whether the display mode button is visible in the interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayModeButtonVisibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerDisplayModeButtonVisibility",
          "text": "DisplayModeButtonVisibility"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/displayModeButtonVisibility-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayModeButtonVisibility"
        }
      ],
      "role": "symbol",
      "title": "displayModeButtonVisibility",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/displaymodebuttonvisibility-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/isCollapsed": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether only one of the child view controllers displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCollapsed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/isCollapsed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collapsed"
        }
      ],
      "role": "symbol",
      "title": "isCollapsed",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/iscollapsed"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/preferredDisplayMode": {
      "abstract": [
        {
          "text": "The preferred arrangement of the split view interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredDisplayMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerDisplayMode",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/preferredDisplayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredDisplayMode"
        }
      ],
      "role": "symbol",
      "title": "preferredDisplayMode",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/preferreddisplaymode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/presentsWithGesture": {
      "abstract": [
        {
          "text": "Specifies whether a hidden view controller can be presented and dismissed using a swipe gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentsWithGesture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/presentsWithGesture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentsWithGesture"
        }
      ],
      "role": "symbol",
      "title": "presentsWithGesture",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/presentswithgesture"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/showsSecondaryOnlyButton": {
      "abstract": [
        {
          "text": "Specifies whether the secondary view controller shows a button to toggle to and from the secondary-only display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsSecondaryOnlyButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/showsSecondaryOnlyButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsSecondaryOnlyButton"
        }
      ],
      "role": "symbol",
      "title": "showsSecondaryOnlyButton",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/showssecondaryonlybutton"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/splitBehavior-swift.property": {
      "abstract": [
        {
          "text": "The current behavior that determines how the child view controllers appear in relation to each other.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitBehavior"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerSplitBehavior",
          "text": "SplitBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/splitBehavior-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitBehavior"
        }
      ],
      "role": "symbol",
      "title": "splitBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/splitbehavior-swift.property"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "media-3624554": {
      "alt": "Flow diagram showing the possible state transitions between display modes, based on split behavior and column style.",
      "identifier": "media-3624554",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6d9d7f1ee87afacb1be85dbc9857b8e9/media-3624554@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2025335ff4b6a99aa605beec5447f1f3/media-3624554~dark@2x.png"
        }
      ]
    },
    "spacer": {
      "alt": null,
      "identifier": "spacer",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/67dc4b07a8d84366d4cc0e812eb40b4a/spacer.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-display-mode",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/preferredDisplayMode",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/displayMode-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/displayModeButtonItem",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/presentsWithGesture",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/showsSecondaryOnlyButton",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/displayModeButtonVisibility-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayModeButtonVisibility-swift.enum"
      ],
      "title": "Managing the display mode"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/secondaryOnly",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/oneBesideSecondary",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/oneOverSecondary",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/twoBesideSecondary",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/twoOverSecondary",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/twoDisplaceSecondary"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/primaryHidden",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/allVisible",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/primaryOverlay"
      ],
      "title": "Deprecated"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISplitViewControllerDisplayMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/secondaryOnly",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/oneBesideSecondary",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/oneOverSecondary",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/twoBesideSecondary",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/twoOverSecondary",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/twoDisplaceSecondary"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/primaryHidden",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/allVisible",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayMode-swift.enum/primaryOverlay"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-display-mode",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/preferredDisplayMode",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/displayMode-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/displayModeButtonItem",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/presentsWithGesture",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/showsSecondaryOnlyButton",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/displayModeButtonVisibility-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/DisplayModeButtonVisibility-swift.enum"
              ],
              "title": "Managing the display mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UISplitViewControllerDisplayMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1primaryHidden/title",
          "value": "UISplitViewControllerDisplayModePrimaryHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1primaryHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayModePrimaryHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayModeButtonVisibility-swift.enum/title",
          "value": "UISplitViewControllerDisplayModeButtonVisibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayModeButtonVisibility-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayModeButtonVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayModeButtonVisibility-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayModeButtonVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1automatic/title",
          "value": "UISplitViewControllerDisplayModeAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayModeAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController/title",
          "value": "UISplitViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1displayModeButtonVisibility-swift.property/title",
          "value": "displayModeButtonVisibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1displayModeButtonVisibility-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayModeButtonVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1splitBehavior-swift.property/title",
          "value": "splitBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1splitBehavior-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "splitBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1twoBesideSecondary/title",
          "value": "UISplitViewControllerDisplayModeTwoBesideSecondary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1twoBesideSecondary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayModeTwoBesideSecondary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1SplitBehavior-swift.enum/title",
          "value": "UISplitViewControllerSplitBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1SplitBehavior-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerSplitBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1SplitBehavior-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerSplitBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1twoOverSecondary/title",
          "value": "UISplitViewControllerDisplayModeTwoOverSecondary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1twoOverSecondary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayModeTwoOverSecondary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1secondaryOnly/title",
          "value": "UISplitViewControllerDisplayModeSecondaryOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1secondaryOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayModeSecondaryOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1primaryOverlay/title",
          "value": "UISplitViewControllerDisplayModePrimaryOverlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1primaryOverlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayModePrimaryOverlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1oneBesideSecondary/title",
          "value": "UISplitViewControllerDisplayModeOneBesideSecondary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1oneBesideSecondary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayModeOneBesideSecondary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1twoDisplaceSecondary/title",
          "value": "UISplitViewControllerDisplayModeTwoDisplaceSecondary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1twoDisplaceSecondary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayModeTwoDisplaceSecondary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1displayMode-swift.property/title",
          "value": "displayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1displayMode-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1preferredDisplayMode/title",
          "value": "preferredDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1preferredDisplayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1isCollapsed/title",
          "value": "collapsed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1isCollapsed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "collapsed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1displayModeButtonItem/title",
          "value": "displayModeButtonItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1displayModeButtonItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayModeButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1presentsWithGesture/title",
          "value": "presentsWithGesture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1presentsWithGesture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "presentsWithGesture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum/title",
          "value": "UISplitViewControllerDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1oneOverSecondary/title",
          "value": "UISplitViewControllerDisplayModeOneOverSecondary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1oneOverSecondary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayModeOneOverSecondary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1allVisible/title",
          "value": "UISplitViewControllerDisplayModeAllVisible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1DisplayMode-swift.enum~1allVisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDisplayModeAllVisible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1showsSecondaryOnlyButton/title",
          "value": "showsSecondaryOnlyButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1showsSecondaryOnlyButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsSecondaryOnlyButton"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisplitviewcontroller/displaymode-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uisplitviewcontroller/displaymode-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
