{
  "abstract": [
    {
      "text": "The client data to supply to the relying party.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest/clientData-655pi"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AuthenticationServices",
    "externalID": "s:So68ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequestP22AuthenticationServicesE10clientDataAC08ASPublicfg6ClientM0VSgvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "clientData"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:22AuthenticationServices31ASPublicKeyCredentialClientDataV",
        "text": "ASPublicKeyCredentialClientData"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.6",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "clientData"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "clientData"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPublicKeyCredentialClientData-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:22AuthenticationServices31ASPublicKeyCredentialClientDataV",
              "text": "ASPublicKeyCredentialClientData"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest": {
      "abstract": [
        {
          "text": "An interface you use to respond to authentication challenges in a web browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialassertionrequest"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest/clientData-655pi": {
      "abstract": [
        {
          "text": "The client data to supply to the relying party.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22AuthenticationServices31ASPublicKeyCredentialClientDataV",
          "text": "ASPublicKeyCredentialClientData"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest/clientData-655pi",
      "kind": "symbol",
      "role": "symbol",
      "title": "clientData",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialassertionrequest/clientdata-655pi"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest/shouldShowHybridTransport": {
      "abstract": [
        {
          "text": "Whether a remote authenticator that communicates with the operating system using Bluetooth can resolve the challenge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldShowHybridTransport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest/shouldShowHybridTransport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldShowHybridTransport"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "shouldShowHybridTransport",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialassertionrequest/shouldshowhybridtransport"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPublicKeyCredentialClientData-swift.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASPublicKeyCredentialClientData"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPublicKeyCredentialClientData-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASPublicKeyCredentialClientData"
        }
      ],
      "role": "symbol",
      "title": "ASPublicKeyCredentialClientData",
      "type": "topic",
      "url": "/documentation/authenticationservices/aspublickeycredentialclientdata-swift.struct"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Information-about-the-assertion",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest/shouldShowHybridTransport"
      ],
      "title": "Information about the assertion"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest/title",
          "value": "ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest~1shouldShowHybridTransport/title",
          "value": "shouldShowHybridTransport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest~1shouldShowHybridTransport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldShowHybridTransport"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/asauthorizationwebbrowserplatformpublickeycredentialassertionrequest/clientdata-655pi"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
