{"identifier":{"url":"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/index","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Returns the index of the outline."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/pdfkit/pdfoutline/index"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/pdfkit/pdfoutline/index"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"index","navigatorTitle":[{"text":"index","kind":"identifier"}],"modules":[{"name":"PDFKit"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"index","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"externalID":"c:objc(cs)PDFOutline(py)index","platforms":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false,"introducedAt":"11.0"},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"11.0"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.1"},{"unavailable":false,"name":"macOS","beta":false,"deprecated":false,"introducedAt":"10.5"},{"unavailable":false,"name":"tvOS","beta":false,"deprecated":false,"introducedAt":"11.0"},{"unavailable":false,"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"index","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"The index of the outline object is relative to its siblings and from the perspective of the parent of the outline object. The root outline object, and any outline object without a parent, has an index value of ","type":"text"},{"code":"0","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/document","doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/numberOfChildren","doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/parent","doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/child(at:)"],"anchor":"Getting-Information-About-an-Outline","title":"Getting Information About an Outline","generated":true}],"references":{"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/index":{"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/index","url":"/documentation/pdfkit/pdfoutline/index","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"index"}],"role":"symbol","title":"index","abstract":[{"text":"Returns the index of the outline.","type":"text"}]},"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/document":{"navigatorTitle":[{"kind":"identifier","text":"document"}],"role":"symbol","title":"document","url":"/documentation/pdfkit/pdfoutline/document","type":"topic","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/document","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PDFDocument","preciseIdentifier":"c:objc(cs)PDFDocument"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"type":"text","text":"Returns the document with which the outline is associated."}]},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"title":"Technologies","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/parent":{"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/parent","url":"/documentation/pdfkit/pdfoutline/parent","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parent","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PDFOutline","text":"PDFOutline","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"parent"}],"role":"symbol","title":"parent","abstract":[{"text":"Returns the parent outline object of the outline (returns ","type":"text"},{"type":"codeVoice","code":"NULL"},{"text":" if called on the root outline object).","type":"text"}]},"doc://com.externally.resolved.symbol/s:Si":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Si","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"title":"Int","url":"/documentation/Swift/Int","abstract":[{"type":"text","text":"A signed integer value type."}],"type":"topic","role":"symbol"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/child(at:)":{"navigatorTitle":[{"kind":"identifier","text":"childAtIndex:"}],"role":"symbol","title":"child(at:)","url":"/documentation/pdfkit/pdfoutline/child(at:)","type":"topic","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/child(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"child"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PDFOutline","preciseIdentifier":"c:objc(cs)PDFOutline"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"type":"text","text":"Returns the child outline object at the specified index."}]},"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/numberOfChildren":{"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/numberOfChildren","url":"/documentation/pdfkit/pdfoutline/numberofchildren","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberOfChildren","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"numberOfChildren"}],"role":"symbol","title":"numberOfChildren","abstract":[{"text":"Returns the number of child outline objects in the outline.","type":"text"}]},"doc://com.apple.pdfkit/documentation/PDFKit":{"role":"collection","identifier":"doc://com.apple.pdfkit/documentation/PDFKit","type":"topic","abstract":[{"type":"text","text":"Display and manipulate PDF documents in your apps."}],"kind":"symbol","title":"PDFKit","url":"/documentation/pdfkit"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline":{"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline","title":"PDFOutline","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFOutline","kind":"identifier"}],"url":"/documentation/pdfkit/pdfoutline","abstract":[{"text":"A ","type":"text"},{"code":"PDFOutline","type":"codeVoice"},{"text":" object is an element in a tree-structured hierarchy that can represent the structure of a PDF document.","type":"text"}],"navigatorTitle":[{"text":"PDFOutline","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS","introducedAt":"11.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"11.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS","introducedAt":"10.5"},{"unavailable":false,"beta":false,"deprecated":false,"name":"tvOS","introducedAt":"11.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"value":"index","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"index"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Getting Information About an Outline","anchor":"Getting-Information-About-an-Outline","identifiers":["doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/document","doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/numberOfChildren","doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/parent","doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/child(at:)"],"generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"index","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"index","op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1index/title"},{"value":[{"kind":"identifier","text":"index"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1index/fragments"},{"value":"document","op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1document/title"},{"value":[{"text":"document","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1document/fragments"},{"value":"parent","op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1parent/title"},{"value":[{"kind":"identifier","text":"parent"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1parent/fragments"},{"value":"childAtIndex:","op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1child(at:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"childAtIndex:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1child(at:)/fragments"},{"value":"numberOfChildren","op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1numberOfChildren/title"},{"value":[{"kind":"identifier","text":"numberOfChildren"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1numberOfChildren/fragments"},{"value":"PDFOutline","op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline/title"},{"value":[{"text":"PDFOutline","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline/fragments"},{"value":[{"kind":"identifier","text":"PDFOutline"}],"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"diffAvailability":{"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}