{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"]}]},{"content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you want the "},{"code":"PDFOutline","type":"codeVoice"},{"type":"text","text":" object returned by this method to be the outline root, you must add additional "},{"code":"PDFOutline","type":"codeVoice"},{"type":"text","text":" objects to create the outline hierarchy you desire. Then, you must add the root outline object to your PDF document by passing it to the "},{"code":"PDFDocument","type":"codeVoice"},{"type":"text","text":" "},{"code":"setOutlineRoot(_:)","type":"codeVoice"},{"type":"text","text":" method."}]},{"type":"paragraph","inlineContent":[{"text":"If you want the ","type":"text"},{"type":"codeVoice","code":"PDFOutline"},{"text":" object returned by this method to be a child of an existing outline, you must use ","type":"text"},{"type":"codeVoice","code":"setLabel(_:)"},{"text":" to give it a label and give it either a destination or action using ","type":"text"},{"type":"codeVoice","code":"setDestination(_:)"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"setAction(_:)"},{"text":", respectively. In addition, you must add this outline object to the existing ","type":"text"},{"type":"codeVoice","code":"PDFOutline"},{"text":" object as a new child, using ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/insertChild(_:at:)"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Initializes a "},{"code":"PDFOutline","type":"codeVoice"},{"type":"text","text":" object."}],"variants":[{"paths":["/documentation/pdfkit/pdfoutline/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/pdfkit/pdfoutline/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"PDFKit"}],"externalID":"c:objc(cs)PDFOutline(im)init","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"platforms":[{"name":"iOS","deprecated":false,"introducedAt":"11.0","beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"introducedAt":"11.0","beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","beta":false,"unavailable":false},{"name":"macOS","deprecated":false,"introducedAt":"10.4","beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"introducedAt":"11.0","beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false,"unavailable":false}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"roleHeading":"Initializer","symbolKind":"init","title":"init()"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/init()"},"sections":[],"references":{"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"title":"Technologies","type":"topic"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/init()":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"PDFOutline"},{"type":"text","text":" object."}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/init()","title":"init()","role":"symbol","url":"/documentation/pdfkit/pdfoutline/init()"},"doc://com.apple.pdfkit/documentation/PDFKit":{"role":"collection","identifier":"doc://com.apple.pdfkit/documentation/PDFKit","type":"topic","abstract":[{"type":"text","text":"Display and manipulate PDF documents in your apps."}],"kind":"symbol","title":"PDFKit","url":"/documentation/pdfkit"},"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/insertChild(_:at:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"insertChild","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PDFOutline","text":"PDFOutline","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"at","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"type":"text","text":"Inserts the specified outline object at the specified index."}],"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/insertChild(_:at:)","type":"topic","url":"/documentation/pdfkit/pdfoutline/insertchild(_:at:)","title":"insertChild(_:at:)","navigatorTitle":[{"kind":"identifier","text":"insertChild:atIndex:"}]},"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline":{"identifier":"doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline","title":"PDFOutline","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PDFOutline","kind":"identifier"}],"url":"/documentation/pdfkit/pdfoutline","abstract":[{"text":"A ","type":"text"},{"code":"PDFOutline","type":"codeVoice"},{"text":" object is an element in a tree-structured hierarchy that can represent the structure of a PDF document.","type":"text"}],"navigatorTitle":[{"text":"PDFOutline","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"11.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"11.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.4"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"11.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"init"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.pdfkit/documentation/PDFKit","doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1init()/title","value":"init"},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1init()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1insertChild(_:at:)/title","value":"insertChild:atIndex:"},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1insertChild(_:at:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertChild:atIndex:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline/title","value":"PDFOutline"},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline/fragments","value":[{"text":"PDFOutline","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline/navigatorTitle","value":[{"kind":"identifier","text":"PDFOutline"}]}]}],"diffAvailability":{"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}