{
  "abstract": [
    {
      "text": "Removes the outline object from its parent (does nothing if outline object is the root outline object).",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/removeFromParent()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PDFOutline(im)removeFromParent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "removeFromParent"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "removeFromParent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "removeFromParent()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "removeFromParent"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFOutline",
          "type": "codeVoice"
        },
        {
          "text": " object is an element in a tree-structured hierarchy that can represent the structure of a PDF document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFOutline"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFOutline"
        }
      ],
      "role": "symbol",
      "title": "PDFOutline",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfoutline"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/insertChild(_:at:)": {
      "abstract": [
        {
          "text": "Inserts the specified outline object at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertChild"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFOutline",
          "text": "PDFOutline"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/insertChild(_:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "insertChild:atIndex:"
        }
      ],
      "role": "symbol",
      "title": "insertChild(_:at:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfoutline/insertchild(_:at:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/parent": {
      "abstract": [
        {
          "text": "Returns the parent outline object of the outline (returns ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": " if called on the root outline object).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PDFOutline",
          "text": "PDFOutline"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/parent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parent"
        }
      ],
      "role": "symbol",
      "title": "parent",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfoutline/parent"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/removeFromParent()": {
      "abstract": [
        {
          "text": "Removes the outline object from its parent (does nothing if outline object is the root outline object).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeFromParent"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/removeFromParent()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeFromParent"
        }
      ],
      "role": "symbol",
      "title": "removeFromParent()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfoutline/removefromparent()"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/parent"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Changing-an-Outline-Hierarchy",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/insertChild(_:at:)"
      ],
      "title": "Changing an Outline Hierarchy"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "removeFromParent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeFromParent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/parent"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Changing-an-Outline-Hierarchy",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFOutline/insertChild(_:at:)"
              ],
              "title": "Changing an Outline Hierarchy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "removeFromParent"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1removeFromParent()/title",
          "value": "removeFromParent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1removeFromParent()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeFromParent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1insertChild(_:at:)/title",
          "value": "insertChild:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1insertChild(_:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "insertChild:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1parent/title",
          "value": "parent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline~1parent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline/title",
          "value": "PDFOutline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFOutline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFOutline/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFOutline"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfoutline/removefromparent()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfoutline/removefromparent()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
