{"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenu/didAddItemNotification","doc://com.apple.appkit/documentation/AppKit/NSMenu/didChangeItemNotification","doc://com.apple.appkit/documentation/AppKit/NSMenu/didBeginTrackingNotification","doc://com.apple.appkit/documentation/AppKit/NSMenu/didEndTrackingNotification","doc://com.apple.appkit/documentation/AppKit/NSMenu/didSendActionNotification","doc://com.apple.appkit/documentation/AppKit/NSMenu/willSendActionNotification"],"generated":true,"anchor":"Notifications","title":"Notifications"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRemoveItemNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName","identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName"}]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"Discussion"},{"inlineContent":[{"text":"The notification object is the instance of ","type":"text"},{"code":"NSMenu","type":"codeVoice"},{"text":" that just removed the menu item. The ","type":"text"},{"code":"userInfo","type":"codeVoice"},{"text":" dictionary contains the following information.","type":"text"}],"type":"paragraph"},{"rows":[[[{"type":"paragraph","inlineContent":[{"text":"Key","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Value"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"@\"NSMenuItemIndex\""}]}],[{"type":"paragraph","inlineContent":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"NSNumber"},{"text":" object containing the integer index of the menu item that was removed. Note that this index may no longer be valid and in any event no longer points to the menu item that was removed.","type":"text"}]}]]],"type":"table","header":"row"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenu"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsmenu/didremoveitemnotification"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsmenu/didremoveitemnotification"]}],"abstract":[{"type":"text","text":"Posted after a menu item is removed from the menu."}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSMenu/didRemoveItemNotification","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"c:@NSMenuDidRemoveItemNotification","extendedModule":"AppKit","platforms":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"navigatorTitle":[{"text":"NSMenuDidRemoveItemNotification","kind":"identifier"}],"roleHeading":"Type Property","modules":[{"name":"AppKit"}],"title":"didRemoveItemNotification","symbolKind":"property","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didRemoveItemNotification","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}]},"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/willSendActionNotification":{"url":"/documentation/appkit/nsmenu/willsendactionnotification","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"willSendActionNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"navigatorTitle":[{"kind":"identifier","text":"NSMenuWillSendActionNotification"}],"title":"willSendActionNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/willSendActionNotification","abstract":[{"type":"text","text":"Posted just before the application dispatches a menu item’s action method to the menu item’s target."}]},"doc://com.apple.appkit/documentation/AppKit/NSMenu/didChangeItemNotification":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/didChangeItemNotification","navigatorTitle":[{"kind":"identifier","text":"NSMenuDidChangeItemNotification"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeItemNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"role":"symbol","type":"topic","kind":"symbol","url":"/documentation/appkit/nsmenu/didchangeitemnotification","abstract":[{"text":"Posted after a menu item in the menu changes appearance.","type":"text"}],"title":"didChangeItemNotification"},"doc://com.apple.appkit/documentation/AppKit/NSMenu":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSMenu"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSMenu"}],"url":"/documentation/appkit/nsmenu","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu","title":"NSMenu","abstract":[{"text":"An object that manages an app’s menus.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/didRemoveItemNotification":{"url":"/documentation/appkit/nsmenu/didremoveitemnotification","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRemoveItemNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"navigatorTitle":[{"kind":"identifier","text":"NSMenuDidRemoveItemNotification"}],"title":"didRemoveItemNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/didRemoveItemNotification","abstract":[{"text":"Posted after a menu item is removed from the menu.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSMenu/didEndTrackingNotification":{"url":"/documentation/appkit/nsmenu/didendtrackingnotification","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEndTrackingNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"navigatorTitle":[{"kind":"identifier","text":"NSMenuDidEndTrackingNotification"}],"title":"didEndTrackingNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/didEndTrackingNotification","abstract":[{"type":"text","text":"Posted when menu tracking ends, even if no action is sent."}]},"doc://com.apple.appkit/documentation/AppKit/NSMenu/didSendActionNotification":{"url":"/documentation/appkit/nsmenu/didsendactionnotification","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"didSendActionNotification","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"NSMenuDidSendActionNotification","kind":"identifier"}],"title":"didSendActionNotification","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/didSendActionNotification","abstract":[{"type":"text","text":"Posted just after the application dispatches a menu item’s action method to the menu item’s target."}]},"doc://com.externally.resolved.symbol/c:@T@NSNotificationName":{"abstract":[{"text":"A structure that defines the name of a notification.","type":"text"}],"type":"topic","identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName","url":"/documentation/foundation/nsnotification/name","kind":"symbol","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"NSNotification.Name"}],"role":"symbol","title":"NSNotification.Name"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification":{"fragments":[{"text":"class ","kind":"text"},{"text":"NSNotification","kind":"identifier"}],"url":"/documentation/foundation/nsnotification","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNotification","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"An object containing information broadcast to registered observers that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"title":"NSNotification"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/didBeginTrackingNotification":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/didBeginTrackingNotification","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSMenuDidBeginTrackingNotification"}],"title":"didBeginTrackingNotification","url":"/documentation/appkit/nsmenu/didbegintrackingnotification","abstract":[{"text":"Posted when menu tracking begins.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didBeginTrackingNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}]},"doc://com.apple.appkit/documentation/AppKit/NSMenu/didAddItemNotification":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/didAddItemNotification","type":"topic","navigatorTitle":[{"text":"NSMenuDidAddItemNotification","kind":"identifier"}],"title":"didAddItemNotification","url":"/documentation/appkit/nsmenu/didadditemnotification","abstract":[{"type":"text","text":"Posted after a menu item is added to the menu."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"didAddItemNotification","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"path":"/metadata/platforms","value":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Global Variable","op":"replace"},{"path":"/metadata/title","value":"NSMenuDidRemoveItemNotification","op":"replace"},{"path":"/metadata/symbolKind","value":"var","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"NSMenuDidRemoveItemNotification"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenu/didAddItemNotification","doc://com.apple.appkit/documentation/AppKit/NSMenu/didChangeItemNotification","doc://com.apple.appkit/documentation/AppKit/NSMenu/didBeginTrackingNotification","doc://com.apple.appkit/documentation/AppKit/NSMenu/didEndTrackingNotification","doc://com.apple.appkit/documentation/AppKit/NSMenu/didSendActionNotification","doc://com.apple.appkit/documentation/AppKit/NSMenu/willSendActionNotification"],"title":"Notifications","anchor":"Notifications"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSNotificationName","identifier":"doc://com.externally.resolved.symbol/c:@T@NSNotificationName","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"NSMenuDidRemoveItemNotification","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}]},"op":"replace"},{"value":"NSMenuWillSendActionNotification","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1willSendActionNotification/title"},{"value":[{"kind":"identifier","text":"NSMenuWillSendActionNotification"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1willSendActionNotification/fragments"},{"value":"NSMenuDidChangeItemNotification","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1didChangeItemNotification/title"},{"value":[{"kind":"identifier","text":"NSMenuDidChangeItemNotification"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1didChangeItemNotification/fragments"},{"value":"NSMenu","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/title"},{"value":[{"kind":"identifier","text":"NSMenu"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/fragments"},{"value":[{"kind":"identifier","text":"NSMenu"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/navigatorTitle"},{"value":"NSMenuDidRemoveItemNotification","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1didRemoveItemNotification/title"},{"value":[{"text":"NSMenuDidRemoveItemNotification","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1didRemoveItemNotification/fragments"},{"value":"NSMenuDidEndTrackingNotification","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1didEndTrackingNotification/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSMenuDidEndTrackingNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1didEndTrackingNotification/fragments"},{"op":"replace","value":"NSMenuDidSendActionNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1didSendActionNotification/title"},{"op":"replace","value":[{"text":"NSMenuDidSendActionNotification","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1didSendActionNotification/fragments"},{"op":"replace","value":"NSNotificationName","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSNotificationName/title"},{"op":"replace","value":[{"text":"A container for information broadcast through a notification center to all registered observers.","type":"text"}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSNotification/abstract"},{"op":"replace","value":"NSMenuDidBeginTrackingNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1didBeginTrackingNotification/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSMenuDidBeginTrackingNotification"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1didBeginTrackingNotification/fragments"},{"op":"replace","value":"NSMenuDidAddItemNotification","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1didAddItemNotification/title"},{"op":"replace","value":[{"text":"NSMenuDidAddItemNotification","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1didAddItemNotification/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}