{"abstract":[{"type":"text","text":"Returns the index of the first menu item in the menu that has a specified action and target."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenu/item(at:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/insertItem(_:at:)"],"title":"Related Documentation","anchor":"Related-Documentation"},{"anchor":"Finding-Indices-of-Menu-Items","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenu/index(of:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTitle:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTag:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withRepresentedObject:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withSubmenu:)"],"title":"Finding Indices of Menu Items","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["/documentation/appkit/nsmenu/indexofitem(withtarget:andaction:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsmenu/indexofitem(withtarget:andaction:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTarget:andAction:)"},"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexOfItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withTarget","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"andAction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"platforms":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"role":"symbol","externalID":"c:objc(cs)NSMenu(im)indexOfItemWithTarget:andAction:","modules":[{"name":"AppKit"}],"roleHeading":"Instance Method","title":"indexOfItem(withTarget:andAction:)","navigatorTitle":[{"kind":"identifier","text":"indexOfItemWithTarget:andAction:"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenu"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexOfItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withTarget","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"target","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"andAction","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"actionSelector","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["macOS"]}]},{"parameters":[{"name":"target","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object that is set as the target of a menu item of the menu."}]}]},{"name":"actionSelector","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A selector identifying an action method. If "},{"code":"actionSelector","type":"codeVoice"},{"type":"text","text":" is "},{"code":"NULL","type":"codeVoice"},{"type":"text","text":", the first menu item in the menu that has target "},{"code":"anObject","type":"codeVoice"},{"type":"text","text":" is returned."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"The integer index of the menu item or, if no such menu item is in the menu, –1."}],"type":"paragraph"}]}],"references":{"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV":{"type":"topic","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"Selector"}],"url":"/documentation/objectivec/selector","title":"Selector","abstract":[{"type":"text","text":""}],"identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTag:)":{"role":"symbol","url":"/documentation/appkit/nsmenu/indexofitem(withtag:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTag:)","title":"indexOfItem(withTag:)","abstract":[{"type":"text","text":"Returns the index of the first menu item in the menu identified by a tag."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"indexOfItemWithTag:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexOfItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withTag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withRepresentedObject:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withRepresentedObject:)","kind":"symbol","navigatorTitle":[{"text":"indexOfItemWithRepresentedObject:","kind":"identifier"}],"role":"symbol","type":"topic","title":"indexOfItem(withRepresentedObject:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexOfItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withRepresentedObject","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"text":"Returns the index of the first menu item in the menu that has a given represented object.","type":"text"}],"url":"/documentation/appkit/nsmenu/indexofitem(withrepresentedobject:)"},"doc://com.externally.resolved.symbol/c:@T@SEL":{"identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","type":"topic","abstract":[{"type":"text","text":"Defines an opaque type that represents a method selector."}],"url":"/documentation/objectivec/sel","title":"SEL","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSMenu":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSMenu"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSMenu"}],"url":"/documentation/appkit/nsmenu","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu","title":"NSMenu","abstract":[{"text":"An object that manages an app’s menus.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/index(of:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"index"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMenuItem","preciseIdentifier":"c:objc(cs)NSMenuItem"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"/documentation/appkit/nsmenu/index(of:)","abstract":[{"text":"Returns the index identifying the location of a specified menu item in the menu.","type":"text"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/index(of:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"indexOfItem:"}],"title":"index(of:)"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTarget:andAction:)":{"url":"/documentation/appkit/nsmenu/indexofitem(withtarget:andaction:)","type":"topic","title":"indexOfItem(withTarget:andAction:)","kind":"symbol","navigatorTitle":[{"text":"indexOfItemWithTarget:andAction:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexOfItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withTarget","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"andAction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Selector","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"text":"?) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"text":"Returns the index of the first menu item in the menu that has a specified action and target.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTarget:andAction:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withSubmenu:)":{"role":"symbol","url":"/documentation/appkit/nsmenu/indexofitem(withsubmenu:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withSubmenu:)","title":"indexOfItem(withSubmenu:)","abstract":[{"text":"Returns the index of the menu item in the menu with the given submenu.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"indexOfItemWithSubmenu:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexOfItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSubmenu"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMenu","preciseIdentifier":"c:objc(cs)NSMenu"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTitle:)":{"url":"/documentation/appkit/nsmenu/indexofitem(withtitle:)","role":"symbol","kind":"symbol","title":"indexOfItem(withTitle:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"indexOfItemWithTitle:"}],"abstract":[{"type":"text","text":"Returns the index of the first menu item in the menu that has a specified title."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexOfItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTitle:)"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/insertItem(_:at:)":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/insertItem(_:at:)","url":"/documentation/appkit/nsmenu/insertitem(_:at:)","abstract":[{"text":"Inserts a menu item into the menu at a specific location.","type":"text"}],"kind":"symbol","title":"insertItem(_:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMenuItem","preciseIdentifier":"c:objc(cs)NSMenuItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"insertItem:atIndex:"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSMenu/item(at:)":{"kind":"symbol","url":"/documentation/appkit/nsmenu/item(at:)","title":"item(at:)","navigatorTitle":[{"text":"itemAtIndex:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"item","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSMenuItem","preciseIdentifier":"c:objc(cs)NSMenuItem","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"Returns the menu item at a specific location of the menu.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/item(at:)","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"path":"/metadata/platforms","op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"indexOfItemWithTarget:andAction:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"indexOfItemWithTarget:andAction:"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenu"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenu/item(at:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/insertItem(_:at:)"]},{"anchor":"Finding-Indices-of-Menu-Items","title":"Finding Indices of Menu Items","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenu/index(of:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTitle:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTag:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withRepresentedObject:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withSubmenu:)"],"generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"indexOfItemWithTarget:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"target"},{"kind":"text","text":" "},{"kind":"identifier","text":"andAction:"},{"kind":"text","text":"("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","preciseIdentifier":"c:@T@SEL","kind":"typeIdentifier","text":"SEL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"actionSelector"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object that is set as the target of a menu item of the menu."}]}],"name":"target"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A selector identifying an action method. If "},{"code":"actionSelector","type":"codeVoice"},{"type":"text","text":" is "},{"code":"NULL","type":"codeVoice"},{"type":"text","text":", the first menu item in the menu that has target "},{"code":"anObject","type":"codeVoice"},{"type":"text","text":" is returned."}]}],"name":"actionSelector"}]}},{"path":"/primaryContentSections/2","value":{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The integer index of the menu item or, if no such menu item is in the menu, –1.","type":"text"}]}]},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withTag:)/title","value":"indexOfItemWithTag:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withTag:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexOfItemWithTag:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withRepresentedObject:)/title","value":"indexOfItemWithRepresentedObject:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withRepresentedObject:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"indexOfItemWithRepresentedObject:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/title","value":"NSMenu"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/fragments","value":[{"text":"NSMenu","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/navigatorTitle","value":[{"text":"NSMenu","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1index(of:)/title","value":"indexOfItem:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1index(of:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexOfItem:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withTarget:andAction:)/title","value":"indexOfItemWithTarget:andAction:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withTarget:andAction:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"indexOfItemWithTarget:andAction:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withSubmenu:)/title","value":"indexOfItemWithSubmenu:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withSubmenu:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexOfItemWithSubmenu:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withTitle:)/title","value":"indexOfItemWithTitle:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withTitle:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"indexOfItemWithTitle:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1insertItem(_:at:)/title","value":"insertItem:atIndex:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1insertItem(_:at:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertItem:atIndex:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1item(at:)/title","value":"itemAtIndex:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1item(at:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"itemAtIndex:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}