{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenu"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTitle:)"},"variants":[{"paths":["/documentation/appkit/nsmenu/indexofitem(withtitle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsmenu/indexofitem(withtitle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenu/item(at:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/item(withTitle:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/insertItem(_:at:)"],"anchor":"Related-Documentation"},{"generated":true,"title":"Finding Indices of Menu Items","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenu/index(of:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTag:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTarget:andAction:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withRepresentedObject:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withSubmenu:)"],"anchor":"Finding-Indices-of-Menu-Items"}],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexOfItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"modules":[{"name":"AppKit"}],"title":"indexOfItem(withTitle:)","symbolKind":"method","navigatorTitle":[{"text":"indexOfItemWithTitle:","kind":"identifier"}],"role":"symbol","platforms":[{"deprecated":false,"beta":false,"unavailable":false,"name":"macOS"}],"externalID":"c:objc(cs)NSMenu(im)indexOfItemWithTitle:"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexOfItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withTitle"},{"kind":"text","text":" "},{"kind":"internalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SS","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si","text":"Int"}]}],"kind":"declarations"},{"parameters":[{"name":"title","content":[{"type":"paragraph","inlineContent":[{"text":"The title of a menu item in the menu.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"The integer index of the menu item or, if no such menu item is in the menu, –1.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Returns the index of the first menu item in the menu that has a specified title.","type":"text"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTarget:andAction:)":{"url":"/documentation/appkit/nsmenu/indexofitem(withtarget:andaction:)","type":"topic","title":"indexOfItem(withTarget:andAction:)","kind":"symbol","navigatorTitle":[{"text":"indexOfItemWithTarget:andAction:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexOfItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withTarget","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"andAction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Selector","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"text":"?) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"text":"Returns the index of the first menu item in the menu that has a specified action and target.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTarget:andAction:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSMenu":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSMenu"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSMenu"}],"url":"/documentation/appkit/nsmenu","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu","title":"NSMenu","abstract":[{"text":"An object that manages an app’s menus.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withRepresentedObject:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withRepresentedObject:)","kind":"symbol","navigatorTitle":[{"text":"indexOfItemWithRepresentedObject:","kind":"identifier"}],"role":"symbol","type":"topic","title":"indexOfItem(withRepresentedObject:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexOfItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withRepresentedObject","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"text":"Returns the index of the first menu item in the menu that has a given represented object.","type":"text"}],"url":"/documentation/appkit/nsmenu/indexofitem(withrepresentedobject:)"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"title":"NSString","kind":"symbol","url":"/documentation/foundation/nsstring","type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/item(at:)":{"kind":"symbol","url":"/documentation/appkit/nsmenu/item(at:)","title":"item(at:)","navigatorTitle":[{"text":"itemAtIndex:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"item","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSMenuItem","preciseIdentifier":"c:objc(cs)NSMenuItem","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"Returns the menu item at a specific location of the menu.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/item(at:)","role":"symbol"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withSubmenu:)":{"role":"symbol","url":"/documentation/appkit/nsmenu/indexofitem(withsubmenu:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withSubmenu:)","title":"indexOfItem(withSubmenu:)","abstract":[{"text":"Returns the index of the menu item in the menu with the given submenu.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"indexOfItemWithSubmenu:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexOfItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSubmenu"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMenu","preciseIdentifier":"c:objc(cs)NSMenu"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.apple.appkit/documentation/AppKit/NSMenu/index(of:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"index"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMenuItem","preciseIdentifier":"c:objc(cs)NSMenuItem"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"/documentation/appkit/nsmenu/index(of:)","abstract":[{"text":"Returns the index identifying the location of a specified menu item in the menu.","type":"text"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/index(of:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"indexOfItem:"}],"title":"index(of:)"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/item(withTitle:)":{"url":"/documentation/appkit/nsmenu/item(withtitle:)","abstract":[{"text":"Returns the first menu item in the menu with a specified title.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"item","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSMenuItem","preciseIdentifier":"c:objc(cs)NSMenuItem","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"item(withTitle:)","role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/item(withTitle:)","navigatorTitle":[{"text":"itemWithTitle:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:SS":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String","kind":"identifier"}],"type":"topic","title":"String","role":"symbol","abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSMenu/insertItem(_:at:)":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/insertItem(_:at:)","url":"/documentation/appkit/nsmenu/insertitem(_:at:)","abstract":[{"text":"Inserts a menu item into the menu at a specific location.","type":"text"}],"kind":"symbol","title":"insertItem(_:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMenuItem","preciseIdentifier":"c:objc(cs)NSMenuItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"insertItem:atIndex:"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTag:)":{"role":"symbol","url":"/documentation/appkit/nsmenu/indexofitem(withtag:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTag:)","title":"indexOfItem(withTag:)","abstract":[{"type":"text","text":"Returns the index of the first menu item in the menu identified by a tag."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"indexOfItemWithTag:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexOfItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withTag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTitle:)":{"url":"/documentation/appkit/nsmenu/indexofitem(withtitle:)","role":"symbol","kind":"symbol","title":"indexOfItem(withTitle:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"indexOfItemWithTitle:"}],"abstract":[{"type":"text","text":"Returns the index of the first menu item in the menu that has a specified title."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexOfItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTitle:)"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"indexOfItemWithTitle:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexOfItemWithTitle:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenu"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenu/item(at:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/item(withTitle:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/insertItem(_:at:)"]},{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenu/index(of:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTag:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withTarget:andAction:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withRepresentedObject:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/indexOfItem(withSubmenu:)"],"title":"Finding Indices of Menu Items","anchor":"Finding-Indices-of-Menu-Items"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"indexOfItemWithTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"title"},{"kind":"text","text":";"}]}]}},{"value":{"kind":"parameters","parameters":[{"name":"title","content":[{"inlineContent":[{"type":"text","text":"The title of a menu item in the menu."}],"type":"paragraph"}]}]},"op":"replace","path":"/primaryContentSections/1"},{"path":"/primaryContentSections/2","op":"replace","value":{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The integer index of the menu item or, if no such menu item is in the menu, –1.","type":"text"}]}],"kind":"content"}},{"value":"indexOfItemWithTarget:andAction:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withTarget:andAction:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexOfItemWithTarget:andAction:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withTarget:andAction:)/fragments"},{"value":"NSMenu","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/title"},{"value":[{"kind":"identifier","text":"NSMenu"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/fragments"},{"value":[{"text":"NSMenu","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/navigatorTitle"},{"value":"indexOfItemWithRepresentedObject:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withRepresentedObject:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexOfItemWithRepresentedObject:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withRepresentedObject:)/fragments"},{"value":[{"type":"text","text":"A static, plain-text Unicode string object."}],"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1item(at:)/title","value":"itemAtIndex:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1item(at:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"itemAtIndex:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withSubmenu:)/title","value":"indexOfItemWithSubmenu:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withSubmenu:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"indexOfItemWithSubmenu:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1index(of:)/title","value":"indexOfItem:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1index(of:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"indexOfItem:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1item(withTitle:)/title","value":"itemWithTitle:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1item(withTitle:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"itemWithTitle:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1insertItem(_:at:)/title","value":"insertItem:atIndex:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1insertItem(_:at:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"insertItem:atIndex:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withTag:)/title","value":"indexOfItemWithTag:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withTag:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"indexOfItemWithTag:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withTitle:)/title","value":"indexOfItemWithTitle:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1indexOfItem(withTitle:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexOfItemWithTitle:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}