{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenu"]]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSMenu/isAttached","interfaceLanguage":"occ"},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"isAttached","kind":"identifier"}],"modules":[{"name":"AppKit"}],"externalID":"c:objc(cs)NSMenu(im)isAttached","platforms":[{"deprecatedAt":"10.2","introducedAt":"10.0","name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"role":"symbol","title":"isAttached","fragments":[{"text":"- ","kind":"text"},{"text":"isAttached","kind":"identifier"}]},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSMenu/setSubmenu(_:for:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/submenuAction(_:)","doc://com.apple.appkit/documentation/AppKit/NSMenu/attachedMenu","doc://com.apple.appkit/documentation/AppKit/NSMenu/locationForSubmenu:","doc://com.apple.appkit/documentation/AppKit/NSMenu/supermenu","doc://com.apple.appkit/documentation/AppKit/NSMenu/isTornOff"],"generated":true,"title":"Managing Submenus","anchor":"Managing-Submenus"}],"sections":[],"abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the menu is currently attached to another menu."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isAttached","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"type":"text","text":" if the menu is currently attached to another menu, otherwise "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"type":"text","text":"."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsmenu/isattached"]}],"references":{"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.appkit/documentation/AppKit/NSMenu":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSMenu"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSMenu"}],"url":"/documentation/appkit/nsmenu","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu","title":"NSMenu","abstract":[{"text":"An object that manages an app’s menus.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/setSubmenu(_:for:)":{"type":"topic","kind":"symbol","url":"/documentation/appkit/nsmenu/setsubmenu(_:for:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/setSubmenu(_:for:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setSubmenu:forItem:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setSubmenu","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMenu","text":"NSMenu"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMenuItem","text":"NSMenuItem"},{"kind":"text","text":")"}],"title":"setSubmenu(_:for:)","abstract":[{"type":"text","text":"Assigns a menu to be a submenu of the menu controlled by a given menu item."}]},"doc://com.apple.appkit/documentation/AppKit/NSMenu/isAttached":{"type":"topic","kind":"symbol","url":"/documentation/appkit/nsmenu/isattached","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/isAttached","role":"symbol","navigatorTitle":[{"text":"isAttached","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"isAttached","kind":"identifier"}],"title":"isAttached","abstract":[{"text":"Returns a Boolean value that indicates whether the menu is currently attached to another menu.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/attachedMenu":{"type":"topic","kind":"symbol","url":"/documentation/appkit/nsmenu/attachedmenu","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/attachedMenu","role":"symbol","navigatorTitle":[{"text":"attachedMenu","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"attachedMenu","kind":"identifier"}],"title":"attachedMenu","abstract":[{"type":"text","text":"Returns the menu currently attached to the menu."}]},"doc://com.apple.appkit/documentation/AppKit/NSMenu/submenuAction(_:)":{"type":"topic","kind":"symbol","url":"/documentation/appkit/nsmenu/submenuaction(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/submenuAction(_:)","role":"symbol","navigatorTitle":[{"text":"submenuAction:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"submenuAction"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"title":"submenuAction(_:)","abstract":[{"type":"text","text":"The action method assigned to menu items that open submenus."}]},"doc://com.apple.appkit/documentation/AppKit/NSMenu/isTornOff":{"abstract":[{"type":"text","text":"Indicates whether the menu is offscreen or attached to another menu (or if it’s the main menu)."}],"type":"topic","url":"/documentation/appkit/nsmenu/istornoff","title":"isTornOff","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTornOff","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"tornOff","kind":"identifier"}],"deprecated":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/isTornOff"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/supermenu":{"type":"topic","kind":"symbol","url":"/documentation/appkit/nsmenu/supermenu","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/supermenu","role":"symbol","navigatorTitle":[{"text":"supermenu","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"supermenu"},{"text":": ","kind":"text"},{"text":"NSMenu","preciseIdentifier":"c:objc(cs)NSMenu","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"supermenu","abstract":[{"type":"text","text":"The parent menu that contains the menu as a submenu."}]},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/locationForSubmenu:":{"type":"topic","kind":"symbol","url":"/documentation/appkit/nsmenu/locationforsubmenu:","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/locationForSubmenu:","role":"symbol","navigatorTitle":[{"text":"locationForSubmenu:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"locationForSubmenu:","kind":"identifier"}],"title":"locationForSubmenu:","abstract":[{"text":"Returns the location in screen coordinates where the given submenu is displayed when opened as a submenu of the menu.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"NSMenu","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/title"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/fragments","op":"replace","value":[{"kind":"identifier","text":"NSMenu"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSMenu"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1setSubmenu(_:for:)/title","op":"replace","value":"setSubmenu:forItem:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSubmenu:forItem:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1setSubmenu(_:for:)/fragments"},{"value":"submenuAction:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1submenuAction(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"submenuAction:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1submenuAction(_:)/fragments"},{"value":"tornOff","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1isTornOff/title"},{"value":[{"kind":"identifier","text":"tornOff"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1isTornOff/fragments"},{"value":"supermenu","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1supermenu/title"},{"value":[{"text":"supermenu","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1supermenu/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}