{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenu"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:SS","preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This property contains a string value indicating the title of the menu. If the menu is a submenu of the application’s main menu, then the title of the menu appears in the menu bar.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsmenu/title"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsmenu/title"]}],"sections":[],"metadata":{"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"title":"title","symbolKind":"property","modules":[{"name":"AppKit"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)NSMenu(py)title","role":"symbol","navigatorTitle":[{"text":"title","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSMenu/title","interfaceLanguage":"swift"},"abstract":[{"text":"The title of the menu.","type":"text"}],"references":{"doc://com.externally.resolved.symbol/s:SS":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String","kind":"identifier"}],"type":"topic","title":"String","role":"symbol","abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"title":"NSString","kind":"symbol","url":"/documentation/foundation/nsstring","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSMenu":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSMenu"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSMenu"}],"url":"/documentation/appkit/nsmenu","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu","title":"NSMenu","abstract":[{"text":"An object that manages an app’s menus.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSMenu/title":{"abstract":[{"type":"text","text":"The title of the menu."}],"role":"symbol","title":"title","kind":"symbol","url":"/documentation/appkit/nsmenu/title","identifier":"doc://com.apple.appkit/documentation/AppKit/NSMenu/title","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"title"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"value":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"title","op":"replace","path":"/metadata/title"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"title","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSMenu"]]},"path":"/hierarchy","op":"replace"},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"title"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]}},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/title","value":"NSMenu"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/fragments","value":[{"text":"NSMenu","kind":"identifier"}]},{"op":"replace","value":[{"text":"NSMenu","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/navigatorTitle"},{"op":"replace","value":"title","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1title/title"},{"op":"replace","value":[{"text":"title","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu~1title/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}