{
  "abstract": [
    {
      "text": "A font style among those typefaces designed to simulate handwriting.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classScripts"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontStylisticClass@kCTFontClassScripts",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "classScripts"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CTFontStylisticClass",
        "text": "CTFontStylisticClass"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTFontClassScripts"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "classScripts"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "classScripts"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CTFontStylisticClass",
              "text": "CTFontStylisticClass"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass": {
      "abstract": [
        {
          "text": "The stylistic class values of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontStylisticClass"
        }
      ],
      "role": "symbol",
      "title": "CTFontStylisticClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classClarendonSerifs": {
      "abstract": [
        {
          "text": "A font style variation of the Oldstyle Serifs and the Transitional Serifs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classClarendonSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classClarendonSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassClarendonSerifs"
        }
      ],
      "role": "symbol",
      "title": "classClarendonSerifs",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classclarendonserifs"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classFreeformSerifs": {
      "abstract": [
        {
          "text": "A font style that includes serifs but expresses a design freedom that doesn’t generally fit within the other serif design classifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classFreeformSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classFreeformSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassFreeformSerifs"
        }
      ],
      "role": "symbol",
      "title": "classFreeformSerifs",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classfreeformserifs"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classModernSerifs": {
      "abstract": [
        {
          "text": "A font style based on the Latin printing style of the 20th century.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classModernSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classModernSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassModernSerifs"
        }
      ],
      "role": "symbol",
      "title": "classModernSerifs",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classmodernserifs"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOldStyleSerifs": {
      "abstract": [
        {
          "text": "A font style based on the Latin printing style of the 15th to 17th century.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classOldStyleSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOldStyleSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassOldStyleSerifs"
        }
      ],
      "role": "symbol",
      "title": "classOldStyleSerifs",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classoldstyleserifs"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOrnamentals": {
      "abstract": [
        {
          "text": "A font style that includes highly decorated or stylized character shapes such as those typically used in headlines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classOrnamentals"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOrnamentals",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassOrnamentals"
        }
      ],
      "role": "symbol",
      "title": "classOrnamentals",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classornamentals"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSansSerif": {
      "abstract": [
        {
          "text": "A font style that includes most basic letter forms (excluding Scripts and Ornamentals) that do not have serifs on the strokes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classSansSerif"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSansSerif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassSansSerif"
        }
      ],
      "role": "symbol",
      "title": "classSansSerif",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classsansserif"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classScripts": {
      "abstract": [
        {
          "text": "A font style among those typefaces designed to simulate handwriting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classScripts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classScripts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassScripts"
        }
      ],
      "role": "symbol",
      "title": "classScripts",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classscripts"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSlabSerifs": {
      "abstract": [
        {
          "text": "A font style characterized by serifs with a square transition between the strokes and the serifs (no brackets).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classSlabSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSlabSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassSlabSerifs"
        }
      ],
      "role": "symbol",
      "title": "classSlabSerifs",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classslabserifs"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSymbolic": {
      "abstract": [
        {
          "text": "A generally design-independent font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classSymbolic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSymbolic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassSymbolic"
        }
      ],
      "role": "symbol",
      "title": "classSymbolic",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classsymbolic"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classTransitionalSerifs": {
      "abstract": [
        {
          "text": "A font style based on the Latin printing style of the 18th to 19th century.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classTransitionalSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classTransitionalSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassTransitionalSerifs"
        }
      ],
      "role": "symbol",
      "title": "classTransitionalSerifs",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classtransitionalserifs"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/kCTFontClassUnknown": {
      "abstract": [
        {
          "text": "The font has no design classification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCTFontClassUnknown"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/kCTFontClassUnknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCTFontClassUnknown",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/kctfontclassunknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Stylistic-Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOldStyleSerifs",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classTransitionalSerifs",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classModernSerifs",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classClarendonSerifs",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSlabSerifs",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classFreeformSerifs",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSansSerif",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOrnamentals",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSymbolic"
      ],
      "title": "Stylistic Classes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTFontClassScripts"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassScripts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Stylistic-Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/kCTFontClassUnknown",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOldStyleSerifs",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classTransitionalSerifs",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classModernSerifs",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classClarendonSerifs",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSlabSerifs",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classFreeformSerifs",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSansSerif",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOrnamentals",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSymbolic"
              ],
              "title": "Stylistic Classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTFontClassScripts"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classScripts/title",
          "value": "kCTFontClassScripts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classScripts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassScripts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classModernSerifs/title",
          "value": "kCTFontClassModernSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classModernSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassModernSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classOrnamentals/title",
          "value": "kCTFontClassOrnamentals"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classOrnamentals/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassOrnamentals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classOldStyleSerifs/title",
          "value": "kCTFontClassOldStyleSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classOldStyleSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassOldStyleSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classFreeformSerifs/title",
          "value": "kCTFontClassFreeformSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classFreeformSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassFreeformSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classClarendonSerifs/title",
          "value": "kCTFontClassClarendonSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classClarendonSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassClarendonSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classSymbolic/title",
          "value": "kCTFontClassSymbolic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classSymbolic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassSymbolic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classTransitionalSerifs/title",
          "value": "kCTFontClassTransitionalSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classTransitionalSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassTransitionalSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classSansSerif/title",
          "value": "kCTFontClassSansSerif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classSansSerif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassSansSerif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classSlabSerifs/title",
          "value": "kCTFontClassSlabSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classSlabSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassSlabSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass/title",
          "value": "CTFontStylisticClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontStylisticClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontStylisticClass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontstylisticclass/classscripts"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontstylisticclass/classscripts"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
