{
  "abstract": [
    {
      "text": "The font’s style is based on the Latin printing style of the 15th to 17th century.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOldStyleSerifs",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/oldStyleSerifsClass"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontStylisticClass@kCTFontOldStyleSerifsClass",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "oldStyleSerifsClass"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CTFontStylisticClass",
        "text": "CTFontStylisticClass"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTFontOldStyleSerifsClass"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "oldStyleSerifsClass"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "oldStyleSerifsClass"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CTFontStylisticClass",
              "text": "CTFontStylisticClass"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass": {
      "abstract": [
        {
          "text": "The stylistic class values of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontStylisticClass"
        }
      ],
      "role": "symbol",
      "title": "CTFontStylisticClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/clarendonSerifsClass": {
      "abstract": [
        {
          "text": "The font’s style is a variation of the Oldstyle Serifs and the Transitional Serifs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clarendonSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/clarendonSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClarendonSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "clarendonSerifsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/clarendonserifsclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOldStyleSerifs": {
      "abstract": [
        {
          "text": "A font style based on the Latin printing style of the 15th to 17th century.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classOldStyleSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOldStyleSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassOldStyleSerifs"
        }
      ],
      "role": "symbol",
      "title": "classOldStyleSerifs",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classoldstyleserifs"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/freeformSerifsClass": {
      "abstract": [
        {
          "text": "The font’s style includes serifs but expresses a design freedom that doesn’t generally fit within the other serif design classifications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "freeformSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/freeformSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFreeformSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "freeformSerifsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/freeformserifsclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/kCTFontUnknownClass": {
      "abstract": [
        {
          "text": "The font has no design classification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCTFontUnknownClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/kCTFontUnknownClass",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCTFontUnknownClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/kctfontunknownclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/modernSerifsClass": {
      "abstract": [
        {
          "text": "The font’s style is based on the Latin printing style of the 20th century.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modernSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/modernSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontModernSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "modernSerifsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/modernserifsclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/oldStyleSerifsClass": {
      "abstract": [
        {
          "text": "The font’s style is based on the Latin printing style of the 15th to 17th century.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oldStyleSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/oldStyleSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontOldStyleSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "oldStyleSerifsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/oldstyleserifsclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/ornamentalsClass": {
      "abstract": [
        {
          "text": "The font’s style includes highly decorated or stylized character shapes such as those typically used in headlines.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ornamentalsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/ornamentalsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontOrnamentalsClass"
        }
      ],
      "role": "symbol",
      "title": "ornamentalsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/ornamentalsclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/sansSerifClass": {
      "abstract": [
        {
          "text": "The font’s style includes most basic letter forms (excluding Scripts and Ornamentals) that do not have serifs on the strokes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sansSerifClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/sansSerifClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontSansSerifClass"
        }
      ],
      "role": "symbol",
      "title": "sansSerifClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/sansserifclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/scriptsClass": {
      "abstract": [
        {
          "text": "The font’s style is among those typefaces designed to simulate handwriting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scriptsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/scriptsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontScriptsClass"
        }
      ],
      "role": "symbol",
      "title": "scriptsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/scriptsclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/slabSerifsClass": {
      "abstract": [
        {
          "text": "The font’s style is characterized by serifs with a square transition between the strokes and the serifs (no brackets).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slabSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/slabSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontSlabSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "slabSerifsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/slabserifsclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/symbolicClass": {
      "abstract": [
        {
          "text": "The font’s style is generally design independent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symbolicClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/symbolicClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontSymbolicClass"
        }
      ],
      "role": "symbol",
      "title": "symbolicClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/symbolicclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/transitionalSerifsClass": {
      "abstract": [
        {
          "text": "The font’s style is based on the Latin printing style of the 18th to 19th century.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transitionalSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/transitionalSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTransitionalSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "transitionalSerifsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/transitionalserifsclass"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/transitionalSerifsClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/modernSerifsClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/clarendonSerifsClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/slabSerifsClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/freeformSerifsClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/sansSerifClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/ornamentalsClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/scriptsClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/symbolicClass"
      ],
      "title": "Deprecated Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTFontOldStyleSerifsClass"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontOldStyleSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/kCTFontUnknownClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/transitionalSerifsClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/modernSerifsClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/clarendonSerifsClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/slabSerifsClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/freeformSerifsClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/sansSerifClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/ornamentalsClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/scriptsClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/symbolicClass"
              ],
              "title": "Deprecated Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTFontOldStyleSerifsClass"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOldStyleSerifs",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1oldStyleSerifsClass/title",
          "value": "kCTFontOldStyleSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1oldStyleSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontOldStyleSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1ornamentalsClass/title",
          "value": "kCTFontOrnamentalsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1ornamentalsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontOrnamentalsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass/title",
          "value": "CTFontStylisticClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontStylisticClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontStylisticClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1symbolicClass/title",
          "value": "kCTFontSymbolicClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1symbolicClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSymbolicClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1modernSerifsClass/title",
          "value": "kCTFontModernSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1modernSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontModernSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1sansSerifClass/title",
          "value": "kCTFontSansSerifClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1sansSerifClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSansSerifClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1transitionalSerifsClass/title",
          "value": "kCTFontTransitionalSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1transitionalSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTransitionalSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1freeformSerifsClass/title",
          "value": "kCTFontFreeformSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1freeformSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFreeformSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1scriptsClass/title",
          "value": "kCTFontScriptsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1scriptsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontScriptsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classOldStyleSerifs/title",
          "value": "kCTFontClassOldStyleSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classOldStyleSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassOldStyleSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1slabSerifsClass/title",
          "value": "kCTFontSlabSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1slabSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSlabSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1clarendonSerifsClass/title",
          "value": "kCTFontClarendonSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1clarendonSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClarendonSerifsClass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontstylisticclass/oldstyleserifsclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontstylisticclass/oldstyleserifsclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
