{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/trait"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@XCUIAccessibilityAuditType@XCUIAccessibilityAuditTypeTrait",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "trait"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@XCUIAccessibilityAuditType",
        "text": "XCUIAccessibilityAuditType"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUIAccessibilityAuditTypeTrait"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "trait"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "tvOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "trait"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@XCUIAccessibilityAuditType",
              "text": "XCUIAccessibilityAuditType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditType"
        }
      ],
      "role": "symbol",
      "title": "XCUIAccessibilityAuditType",
      "type": "topic",
      "url": "/documentation/xctest/xcuiaccessibilityaudittype"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/action": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIAccessibilityAuditType",
          "text": "XCUIAccessibilityAuditType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/action",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditTypeAction"
        }
      ],
      "role": "symbol",
      "title": "action",
      "type": "topic",
      "url": "/documentation/xctest/xcuiaccessibilityaudittype/action"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/all": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIAccessibilityAuditType",
          "text": "XCUIAccessibilityAuditType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditTypeAll"
        }
      ],
      "role": "symbol",
      "title": "all",
      "type": "topic",
      "url": "/documentation/xctest/xcuiaccessibilityaudittype/all"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/contrast": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contrast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIAccessibilityAuditType",
          "text": "XCUIAccessibilityAuditType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/contrast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditTypeContrast"
        }
      ],
      "role": "symbol",
      "title": "contrast",
      "type": "topic",
      "url": "/documentation/xctest/xcuiaccessibilityaudittype/contrast"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/dynamicType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dynamicType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIAccessibilityAuditType",
          "text": "XCUIAccessibilityAuditType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/dynamicType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditTypeDynamicType"
        }
      ],
      "role": "symbol",
      "title": "dynamicType",
      "type": "topic",
      "url": "/documentation/xctest/xcuiaccessibilityaudittype/dynamictype"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/elementDetection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elementDetection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIAccessibilityAuditType",
          "text": "XCUIAccessibilityAuditType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/elementDetection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditTypeElementDetection"
        }
      ],
      "role": "symbol",
      "title": "elementDetection",
      "type": "topic",
      "url": "/documentation/xctest/xcuiaccessibilityaudittype/elementdetection"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/hitRegion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hitRegion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIAccessibilityAuditType",
          "text": "XCUIAccessibilityAuditType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/hitRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditTypeHitRegion"
        }
      ],
      "role": "symbol",
      "title": "hitRegion",
      "type": "topic",
      "url": "/documentation/xctest/xcuiaccessibilityaudittype/hitregion"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/parentChild": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentChild"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIAccessibilityAuditType",
          "text": "XCUIAccessibilityAuditType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/parentChild",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditTypeParentChild"
        }
      ],
      "role": "symbol",
      "title": "parentChild",
      "type": "topic",
      "url": "/documentation/xctest/xcuiaccessibilityaudittype/parentchild"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/sufficientElementDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sufficientElementDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIAccessibilityAuditType",
          "text": "XCUIAccessibilityAuditType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/sufficientElementDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditTypeSufficientElementDescription"
        }
      ],
      "role": "symbol",
      "title": "sufficientElementDescription",
      "type": "topic",
      "url": "/documentation/xctest/xcuiaccessibilityaudittype/sufficientelementdescription"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/textClipped": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textClipped"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIAccessibilityAuditType",
          "text": "XCUIAccessibilityAuditType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/textClipped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditTypeTextClipped"
        }
      ],
      "role": "symbol",
      "title": "textClipped",
      "type": "topic",
      "url": "/documentation/xctest/xcuiaccessibilityaudittype/textclipped"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/trait": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIAccessibilityAuditType",
          "text": "XCUIAccessibilityAuditType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/trait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIAccessibilityAuditTypeTrait"
        }
      ],
      "role": "symbol",
      "title": "trait",
      "type": "topic",
      "url": "/documentation/xctest/xcuiaccessibilityaudittype/trait"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessibility-audit-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/action",
        "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/all",
        "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/contrast",
        "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/dynamicType",
        "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/elementDetection",
        "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/hitRegion",
        "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/parentChild",
        "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/sufficientElementDescription",
        "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/textClipped"
      ],
      "title": "Accessibility audit types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUIAccessibilityAuditTypeTrait"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditTypeTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessibility-audit-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/action",
                "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/all",
                "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/contrast",
                "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/dynamicType",
                "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/elementDetection",
                "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/hitRegion",
                "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/parentChild",
                "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/sufficientElementDescription",
                "doc://com.apple.xctest/documentation/XCTest/XCUIAccessibilityAuditType/textClipped"
              ],
              "title": "Accessibility audit types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "tvOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "XCUIAccessibilityAuditTypeTrait"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1elementDetection/title",
          "value": "XCUIAccessibilityAuditTypeElementDetection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1elementDetection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditTypeElementDetection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1trait/title",
          "value": "XCUIAccessibilityAuditTypeTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1trait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditTypeTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1sufficientElementDescription/title",
          "value": "XCUIAccessibilityAuditTypeSufficientElementDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1sufficientElementDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditTypeSufficientElementDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1contrast/title",
          "value": "XCUIAccessibilityAuditTypeContrast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1contrast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditTypeContrast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1hitRegion/title",
          "value": "XCUIAccessibilityAuditTypeHitRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1hitRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditTypeHitRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1action/title",
          "value": "XCUIAccessibilityAuditTypeAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1action/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditTypeAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1dynamicType/title",
          "value": "XCUIAccessibilityAuditTypeDynamicType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1dynamicType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditTypeDynamicType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1parentChild/title",
          "value": "XCUIAccessibilityAuditTypeParentChild"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1parentChild/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditTypeParentChild"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType/title",
          "value": "XCUIAccessibilityAuditType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1all/title",
          "value": "XCUIAccessibilityAuditTypeAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditTypeAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1textClipped/title",
          "value": "XCUIAccessibilityAuditTypeTextClipped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIAccessibilityAuditType~1textClipped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIAccessibilityAuditTypeTextClipped"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuiaccessibilityaudittype/trait"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuiaccessibilityaudittype/trait"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
