{"metadata":{"modules":[{"name":"Quick Look"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"4.0","deprecated":false},{"introducedAt":"4.0","deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS"},{"introducedAt":"13.1","deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"},{"introducedAt":"1.0","deprecated":false,"beta":false,"unavailable":false,"name":"visionOS"}],"title":"previewControllerWillDismiss(_:)","externalID":"c:objc(pl)QLPreviewControllerDelegate(im)previewControllerWillDismiss:","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"previewControllerWillDismiss:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewControllerWillDismiss","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":")"}]},"seeAlsoSections":[{"generated":true,"title":"Responding to preview requests","anchor":"Responding-to-preview-requests","identifiers":["doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:frameFor:inSourceView:)","doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:transitionImageFor:contentRect:)","doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:transitionViewFor:)","doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewControllerDidDismiss(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Tells the delegate that the preview is about to close."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewControllerWillDismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)QLPreviewController","text":"QLPreviewController"},{"kind":"text","text":")"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewController","isActive":true},{"text":" that’s about to close.","type":"text"}],"type":"paragraph"}],"name":"controller"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewControllerWillDismiss(_:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/quicklook/qlpreviewcontrollerdelegate/previewcontrollerwilldismiss(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/quicklook/qlpreviewcontrollerdelegate/previewcontrollerwilldismiss(_:)"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quicklook/documentation/QuickLook","doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate"]]},"references":{"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:transitionViewFor:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"previewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"QLPreviewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"text":", ","kind":"text"},{"text":"transitionViewFor","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"QLPreviewItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)QLPreviewItem"},{"text":") -> ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"previewController:transitionViewForPreviewItem:","kind":"identifier"}],"type":"topic","title":"previewController(_:transitionViewFor:)","identifier":"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:transitionViewFor:)","url":"/documentation/quicklook/qlpreviewcontrollerdelegate/previewcontroller(_:transitionviewfor:)","abstract":[{"type":"text","text":"Tells the delegate that the system is about to present the preview full screen or dismiss it, and asks for information to provide a smooth transition when zooming."}]},"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:transitionImageFor:contentRect:)":{"identifier":"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:transitionImageFor:contentRect:)","type":"topic","abstract":[{"type":"text","text":"Tells the delegate that the system is about to present the preview full screen or dismiss it, and asks for information to provide a smooth transition when zooming."}],"kind":"symbol","title":"previewController(_:transitionImageFor:contentRect:)","url":"/documentation/quicklook/qlpreviewcontrollerdelegate/previewcontroller(_:transitionimagefor:contentrect:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"previewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"transitionImageFor","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"QLPreviewItem","preciseIdentifier":"c:objc(pl)QLPreviewItem","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"contentRect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"previewController:transitionImageForPreviewItem:contentRect:"}]},"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewControllerWillDismiss(_:)":{"navigatorTitle":[{"text":"previewControllerWillDismiss:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewControllerWillDismiss","kind":"identifier"},{"text":"(","kind":"text"},{"text":"QLPreviewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Tells the delegate that the preview is about to close."}],"type":"topic","url":"/documentation/quicklook/qlpreviewcontrollerdelegate/previewcontrollerwilldismiss(_:)","title":"previewControllerWillDismiss(_:)","kind":"symbol","identifier":"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewControllerWillDismiss(_:)","role":"symbol"},"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:frameFor:inSourceView:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"frameFor","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"QLPreviewItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)QLPreviewItem"},{"text":", ","kind":"text"},{"text":"inSourceView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoreleasingUnsafeMutablePointer","preciseIdentifier":"s:SA","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":"?>) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"kind":"symbol","identifier":"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:frameFor:inSourceView:)","title":"previewController(_:frameFor:inSourceView:)","role":"symbol","abstract":[{"text":"Tells the delegate that the system is about to present the preview full screen or dismiss it, and asks for information to provide a zoom effect.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"previewController:frameForPreviewItem:inSourceView:"}],"url":"/documentation/quicklook/qlpreviewcontrollerdelegate/previewcontroller(_:framefor:insourceview:)","type":"topic"},"doc://com.apple.quicklook/documentation/QuickLook":{"role":"collection","type":"topic","url":"/documentation/quicklook","abstract":[{"text":"Create previews of files to use inside your app, or perform simple edits on previews.","type":"text"}],"kind":"symbol","title":"Quick Look","identifier":"doc://com.apple.quicklook/documentation/QuickLook"},"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewControllerDidDismiss(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewControllerDidDismiss","kind":"identifier"},{"text":"(","kind":"text"},{"text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewControllerDidDismiss(_:)","title":"previewControllerDidDismiss(_:)","role":"symbol","abstract":[{"text":"Tells the delegate that the preview was closed.","type":"text"}],"navigatorTitle":[{"text":"previewControllerDidDismiss:","kind":"identifier"}],"url":"/documentation/quicklook/qlpreviewcontrollerdelegate/previewcontrollerdiddismiss(_:)","type":"topic"},"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QLPreviewController","kind":"identifier"}],"role":"symbol","type":"topic","url":"/documentation/quicklook/qlpreviewcontroller","abstract":[{"text":"A specialized view controller for previewing an item.","type":"text"}],"kind":"symbol","title":"QLPreviewController","navigatorTitle":[{"text":"QLPreviewController","kind":"identifier"}],"identifier":"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewController"},"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"QLPreviewControllerDelegate"}],"identifier":"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QLPreviewControllerDelegate"}],"url":"/documentation/quicklook/qlpreviewcontrollerdelegate","title":"QLPreviewControllerDelegate","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The protocol that a delegate of a preview controller needs to adopt to handle Quick Look previews."}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","title":"Technologies","kind":"technologies","type":"topic","abstract":[{"text":"","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"4.0","name":"iOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"4.0","deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS"},{"introducedAt":"13.0","deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"},{"introducedAt":"1.0","deprecated":false,"beta":false,"unavailable":false,"name":"visionOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"previewControllerWillDismiss:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previewControllerWillDismiss:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quicklook/documentation/QuickLook","doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"title":"Responding to preview requests","anchor":"Responding-to-preview-requests","identifiers":["doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:frameFor:inSourceView:)","doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:transitionImageFor:contentRect:)","doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:transitionViewFor:)","doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewControllerDidDismiss(_:)"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"previewControllerWillDismiss:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewController","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}]}},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc://com.apple.quicklook/documentation/QuickLook/QLPreviewController","isActive":true,"type":"reference"},{"text":" that’s about to close.","type":"text"}]}],"name":"controller"}]},"path":"/primaryContentSections/1"},{"op":"replace","path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:transitionViewFor:)/title","value":"previewController:transitionViewForPreviewItem:"},{"op":"replace","path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:transitionViewFor:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"previewController:transitionViewForPreviewItem:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:transitionImageFor:contentRect:)/title","value":"previewController:transitionImageForPreviewItem:contentRect:"},{"op":"replace","path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:transitionImageFor:contentRect:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"previewController:transitionImageForPreviewItem:contentRect:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewControllerWillDismiss(_:)/title","value":"previewControllerWillDismiss:"},{"op":"replace","path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewControllerWillDismiss(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"previewControllerWillDismiss:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:frameFor:inSourceView:)/title","value":"previewController:frameForPreviewItem:inSourceView:"},{"op":"replace","path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:frameFor:inSourceView:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previewController:frameForPreviewItem:inSourceView:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewControllerDidDismiss(_:)/title","value":"previewControllerDidDismiss:"},{"path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewControllerDidDismiss(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"previewControllerDidDismiss:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewController/title","value":"QLPreviewController","op":"replace"},{"path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewController/fragments","value":[{"text":"QLPreviewController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewController/navigatorTitle","value":[{"text":"QLPreviewController","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate/title","value":"QLPreviewControllerDelegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate/fragments","value":[{"kind":"identifier","text":"QLPreviewControllerDelegate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate/navigatorTitle","value":[{"kind":"identifier","text":"QLPreviewControllerDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}