{
  "abstract": [
    {
      "text": "Tells the delegate that the preview item’s edited content was successfully saved to a copy at the given URL.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklook/documentation/QuickLook",
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:didSaveEditedCopyOf:at:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)QLPreviewControllerDelegate(im)previewController:didSaveEditedCopyOfPreviewItem:atURL:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "previewController"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)QLPreviewController",
        "text": "QLPreviewController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didSaveEditedCopyOf"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)QLPreviewItem",
        "text": "QLPreviewItem"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "at"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation3URLV",
        "text": "URL"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Quick Look"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "previewController:didSaveEditedCopyOfPreviewItem:atURL:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "previewController(_:didSaveEditedCopyOf:at:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "previewController"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)QLPreviewController",
              "text": "QLPreviewController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didSaveEditedCopyOf"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "previewItem"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)QLPreviewItem",
              "text": "QLPreviewItem"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "at"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "modifiedContentsURL"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation3URLV",
              "text": "URL"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The controller that displays the preview.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "controller"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The preview item for a file.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "previewItem"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A URL pointing to a temporary file that contains the edited version of the previewed file.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "modifiedContentsURL"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The platform invokes this callback with an edited copy of the preview item at ",
              "type": "text"
            },
            {
              "code": "modifiedContentsURL",
              "type": "codeVoice"
            },
            {
              "text": ". It invokes the callback in the following scenarios:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The editing mode of the ",
                      "type": "text"
                    },
                    {
                      "code": "previewItem",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/createCopy",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The editing mode of the ",
                      "type": "text"
                    },
                    {
                      "code": "previewItem",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/updateContents",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and the system can’t overwrite its ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItem/previewItemURL",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". In this case, ",
                      "type": "text"
                    },
                    {
                      "code": "modifiedContentsURL",
                      "type": "codeVoice"
                    },
                    {
                      "text": " points to a temporary file on disk containing the edited copy.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The editing mode of the preview item is ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/updateContents",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and its content type doesn’t match the content type of the edited version. This mismatch means that the file type of the file at ",
                      "type": "text"
                    },
                    {
                      "code": "modifiedContentsURL",
                      "type": "codeVoice"
                    },
                    {
                      "text": " may be different from the file type of the preview item.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The platform may invoke the callback multiple times consecutively with the successive edited versions of the preview item. It typically invokes the callback once for each time the user saves their edits.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklook/documentation/QuickLook": {
      "abstract": [
        {
          "text": "Create previews of files to use inside your app, or perform simple edits on previews.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look",
      "type": "topic",
      "url": "/documentation/quicklook"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewController": {
      "abstract": [
        {
          "text": "A specialized view controller for previewing an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewController"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewController"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewController",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewcontroller"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate": {
      "abstract": [
        {
          "text": "The protocol that a delegate of a preview controller needs to adopt to handle Quick Look previews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewControllerDelegate",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewcontrollerdelegate"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:didSaveEditedCopyOf:at:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the preview item’s edited content was successfully saved to a copy at the given URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLPreviewController",
          "text": "QLPreviewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSaveEditedCopyOf"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)QLPreviewItem",
          "text": "QLPreviewItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:didSaveEditedCopyOf:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewController:didSaveEditedCopyOfPreviewItem:atURL:"
        }
      ],
      "role": "symbol",
      "title": "previewController(_:didSaveEditedCopyOf:at:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewcontrollerdelegate/previewcontroller(_:didsaveeditedcopyof:at:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:didUpdateContentsOf:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the content of a preview was updated successfully.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLPreviewController",
          "text": "QLPreviewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdateContentsOf"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)QLPreviewItem",
          "text": "QLPreviewItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:didUpdateContentsOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewController:didUpdateContentsOfPreviewItem:"
        }
      ],
      "role": "symbol",
      "title": "previewController(_:didUpdateContentsOf:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewcontrollerdelegate/previewcontroller(_:didupdatecontentsof:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:editingModeFor:)": {
      "abstract": [
        {
          "text": "Returns a value that indicates how the preview controller handles edits to the content of the previewed file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLPreviewController",
          "text": "QLPreviewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "editingModeFor"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)QLPreviewItem",
          "text": "QLPreviewItem"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@QLPreviewItemEditingMode",
          "text": "QLPreviewItemEditingMode"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:editingModeFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewController:editingModeForPreviewItem:"
        }
      ],
      "role": "symbol",
      "title": "previewController(_:editingModeFor:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewcontrollerdelegate/previewcontroller(_:editingmodefor:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItem": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewItem"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItem"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItem",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewitem"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItem/previewItemURL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewItemURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItem/previewItemURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewItemURL"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "previewItemURL",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewitem/previewitemurl"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewItemEditingMode"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItemEditingMode"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItemEditingMode",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewitemeditingmode"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/createCopy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createCopy"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/createCopy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItemEditingModeCreateCopy"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItemEditingMode.createCopy",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewitemeditingmode/createcopy"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/updateContents": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateContents"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/updateContents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItemEditingModeUpdateContents"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItemEditingMode.updateContents",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewitemeditingmode/updatecontents"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation3URLV": {
      "abstract": [
        {
          "text": "A value that identifies the location of a resource, such as an item on a remote server or the path to a local file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
      "kind": "symbol",
      "role": "symbol",
      "title": "URL",
      "type": "topic",
      "url": "/documentation/foundation/url"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Editing-the-content-of-a-preview",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:editingModeFor:)",
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode",
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:didUpdateContentsOf:)"
      ],
      "title": "Editing the content of a preview"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "previewController:didSaveEditedCopyOfPreviewItem:atURL:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "previewController:didSaveEditedCopyOfPreviewItem:atURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklook/documentation/QuickLook",
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Editing-the-content-of-a-preview",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:editingModeFor:)",
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode",
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:didUpdateContentsOf:)"
              ],
              "title": "Editing the content of a preview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "previewController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)QLPreviewController",
                    "text": "QLPreviewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "controller"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didSaveEditedCopyOfPreviewItem:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)QLPreviewItem",
                    "text": "id<QLPreviewItem>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "previewItem"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "atURL:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSURL",
                    "text": "NSURL"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "modifiedContentsURL"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The controller that displays the preview.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "controller"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The preview item for a file.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "previewItem"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A URL pointing to a temporary file that contains the edited version of the previewed file.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "modifiedContentsURL"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItem~1previewItemURL/title",
          "value": "previewItemURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItem~1previewItemURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previewItemURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItem/title",
          "value": "QLPreviewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode~1updateContents/title",
          "value": "QLPreviewItemEditingModeUpdateContents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode~1updateContents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingModeUpdateContents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate/title",
          "value": "QLPreviewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode/title",
          "value": "QLPreviewItemEditingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:didUpdateContentsOf:)/title",
          "value": "previewController:didUpdateContentsOfPreviewItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:didUpdateContentsOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "previewController:didUpdateContentsOfPreviewItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:didSaveEditedCopyOf:at:)/title",
          "value": "previewController:didSaveEditedCopyOfPreviewItem:atURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:didSaveEditedCopyOf:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "previewController:didSaveEditedCopyOfPreviewItem:atURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:editingModeFor:)/title",
          "value": "previewController:editingModeForPreviewItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:editingModeFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "previewController:editingModeForPreviewItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode~1createCopy/title",
          "value": "QLPreviewItemEditingModeCreateCopy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode~1createCopy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingModeCreateCopy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewController/title",
          "value": "QLPreviewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklook/qlpreviewcontrollerdelegate/previewcontroller(_:didsaveeditedcopyof:at:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklook/qlpreviewcontrollerdelegate/previewcontroller(_:didsaveeditedcopyof:at:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
