{
  "abstract": [
    {
      "text": "Tells the delegate to present the ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "Add Shortcut",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": " view controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/IntentsUI",
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonDelegate/present(_:for:)-5foo8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INUIAddVoiceShortcutButtonDelegate(im)presentAddVoiceShortcutViewController:forAddVoiceShortcutButton:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "present"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INUIAddVoiceShortcutViewController",
        "text": "INUIAddVoiceShortcutViewController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INUIAddVoiceShortcutButton",
        "text": "INUIAddVoiceShortcutButton"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "IntentsUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "presentAddVoiceShortcutViewController:forAddVoiceShortcutButton:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "present(_:for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "present"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "addVoiceShortcutViewController"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INUIAddVoiceShortcutViewController",
              "text": "INUIAddVoiceShortcutViewController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "addVoiceShortcutButton"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INUIAddVoiceShortcutButton",
              "text": "INUIAddVoiceShortcutButton"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The view controller to present.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "addVoiceShortcutViewController"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The Siri Shortcut button calling this method.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "addVoiceShortcutButton"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI": {
      "abstract": [
        {
          "text": "Customize content in the interface for Siri and Maps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IntentsUI",
      "type": "topic",
      "url": "/documentation/intentsui"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton": {
      "abstract": [
        {
          "text": "A button that allows the user to add or edit a shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutButton"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutButton"
        }
      ],
      "role": "symbol",
      "title": "INUIAddVoiceShortcutButton",
      "type": "topic",
      "url": "/documentation/intentsui/inuiaddvoiceshortcutbutton"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonDelegate": {
      "abstract": [
        {
          "text": "The protocol an object implements to receive notifications from the Siri Shortcut button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutButtonDelegate"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutButtonDelegate"
        }
      ],
      "role": "symbol",
      "title": "INUIAddVoiceShortcutButtonDelegate",
      "type": "topic",
      "url": "/documentation/intentsui/inuiaddvoiceshortcutbuttondelegate"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonDelegate/present(_:for:)-5foo8": {
      "abstract": [
        {
          "text": "Tells the delegate to present the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Add Shortcut",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "present"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INUIAddVoiceShortcutViewController",
          "text": "INUIAddVoiceShortcutViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INUIAddVoiceShortcutButton",
          "text": "INUIAddVoiceShortcutButton"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonDelegate/present(_:for:)-5foo8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentAddVoiceShortcutViewController:forAddVoiceShortcutButton:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "present(_:for:)",
      "type": "topic",
      "url": "/documentation/intentsui/inuiaddvoiceshortcutbuttondelegate/present(_:for:)-5foo8"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonDelegate/present(_:for:)-9n4m9": {
      "abstract": [
        {
          "text": "Tells the delegate to present the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Edit Shortcut",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "present"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INUIEditVoiceShortcutViewController",
          "text": "INUIEditVoiceShortcutViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INUIAddVoiceShortcutButton",
          "text": "INUIAddVoiceShortcutButton"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonDelegate/present(_:for:)-9n4m9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentEditVoiceShortcutViewController:forAddVoiceShortcutButton:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "present(_:for:)",
      "type": "topic",
      "url": "/documentation/intentsui/inuiaddvoiceshortcutbuttondelegate/present(_:for:)-9n4m9"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutViewController": {
      "abstract": [
        {
          "text": "A view controller that guides the user through the steps for adding a shortcut to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutViewController"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutViewController"
        }
      ],
      "role": "symbol",
      "title": "INUIAddVoiceShortcutViewController",
      "type": "topic",
      "url": "/documentation/intentsui/inuiaddvoiceshortcutviewcontroller"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presenting-Shortcut-Editors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonDelegate/present(_:for:)-9n4m9"
      ],
      "title": "Presenting Shortcut Editors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "presentAddVoiceShortcutViewController:forAddVoiceShortcutButton:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentAddVoiceShortcutViewController:forAddVoiceShortcutButton:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/IntentsUI",
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presenting-Shortcut-Editors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonDelegate/present(_:for:)-9n4m9"
              ],
              "title": "Presenting Shortcut Editors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "presentAddVoiceShortcutViewController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INUIAddVoiceShortcutViewController",
                    "text": "INUIAddVoiceShortcutViewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "addVoiceShortcutViewController"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "forAddVoiceShortcutButton:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INUIAddVoiceShortcutButton",
                    "text": "INUIAddVoiceShortcutButton"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "addVoiceShortcutButton"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The view controller to present.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "addVoiceShortcutViewController"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The Siri Shortcut button calling this method.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "addVoiceShortcutButton"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButton/title",
          "value": "INUIAddVoiceShortcutButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButtonDelegate/title",
          "value": "INUIAddVoiceShortcutButtonDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButtonDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutButtonDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButtonDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutButtonDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButtonDelegate~1present(_:for:)-9n4m9/title",
          "value": "presentEditVoiceShortcutViewController:forAddVoiceShortcutButton:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButtonDelegate~1present(_:for:)-9n4m9/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentEditVoiceShortcutViewController:forAddVoiceShortcutButton:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutViewController/title",
          "value": "INUIAddVoiceShortcutViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButtonDelegate~1present(_:for:)-5foo8/title",
          "value": "presentAddVoiceShortcutViewController:forAddVoiceShortcutButton:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButtonDelegate~1present(_:for:)-5foo8/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentAddVoiceShortcutViewController:forAddVoiceShortcutButton:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intentsui/inuiaddvoiceshortcutbuttondelegate/present(_:for:)-5foo8"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intentsui/inuiaddvoiceshortcutbuttondelegate/present(_:for:)-5foo8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
