{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_Complete"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AUScheduledAudioSliceFlags@kScheduledAudioSliceFlag_Complete",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "scheduledAudioSliceFlag_Complete"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AUScheduledAudioSliceFlags",
        "text": "AUScheduledAudioSliceFlags"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kScheduledAudioSliceFlag_Complete"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "scheduledAudioSliceFlag_Complete"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "scheduledAudioSliceFlag_Complete"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AUScheduledAudioSliceFlags",
              "text": "AUScheduledAudioSliceFlags"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUScheduledAudioSliceFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUScheduledAudioSliceFlags"
        }
      ],
      "role": "symbol",
      "title": "AUScheduledAudioSliceFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auscheduledaudiosliceflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_BeganToRender": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduledAudioSliceFlag_BeganToRender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUScheduledAudioSliceFlags",
          "text": "AUScheduledAudioSliceFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_BeganToRender",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kScheduledAudioSliceFlag_BeganToRender"
        }
      ],
      "role": "symbol",
      "title": "scheduledAudioSliceFlag_BeganToRender",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auscheduledaudiosliceflags/scheduledaudiosliceflag_begantorender"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_BeganToRenderLate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduledAudioSliceFlag_BeganToRenderLate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUScheduledAudioSliceFlags",
          "text": "AUScheduledAudioSliceFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_BeganToRenderLate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kScheduledAudioSliceFlag_BeganToRenderLate"
        }
      ],
      "role": "symbol",
      "title": "scheduledAudioSliceFlag_BeganToRenderLate",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auscheduledaudiosliceflags/scheduledaudiosliceflag_begantorenderlate"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_Complete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduledAudioSliceFlag_Complete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUScheduledAudioSliceFlags",
          "text": "AUScheduledAudioSliceFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_Complete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kScheduledAudioSliceFlag_Complete"
        }
      ],
      "role": "symbol",
      "title": "scheduledAudioSliceFlag_Complete",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auscheduledaudiosliceflags/scheduledaudiosliceflag_complete"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_Interrupt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduledAudioSliceFlag_Interrupt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUScheduledAudioSliceFlags",
          "text": "AUScheduledAudioSliceFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_Interrupt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kScheduledAudioSliceFlag_Interrupt"
        }
      ],
      "role": "symbol",
      "title": "scheduledAudioSliceFlag_Interrupt",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auscheduledaudiosliceflags/scheduledaudiosliceflag_interrupt"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_InterruptAtLoop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduledAudioSliceFlag_InterruptAtLoop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUScheduledAudioSliceFlags",
          "text": "AUScheduledAudioSliceFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_InterruptAtLoop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kScheduledAudioSliceFlag_InterruptAtLoop"
        }
      ],
      "role": "symbol",
      "title": "scheduledAudioSliceFlag_InterruptAtLoop",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auscheduledaudiosliceflags/scheduledaudiosliceflag_interruptatloop"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_Loop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduledAudioSliceFlag_Loop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUScheduledAudioSliceFlags",
          "text": "AUScheduledAudioSliceFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_Loop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kScheduledAudioSliceFlag_Loop"
        }
      ],
      "role": "symbol",
      "title": "scheduledAudioSliceFlag_Loop",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auscheduledaudiosliceflags/scheduledaudiosliceflag_loop"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_BeganToRender",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_BeganToRenderLate",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_Interrupt",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_InterruptAtLoop",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_Loop"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kScheduledAudioSliceFlag_Complete"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kScheduledAudioSliceFlag_Complete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_BeganToRender",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_BeganToRenderLate",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_Interrupt",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_InterruptAtLoop",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUScheduledAudioSliceFlags/scheduledAudioSliceFlag_Loop"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kScheduledAudioSliceFlag_Complete"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUScheduledAudioSliceFlags~1scheduledAudioSliceFlag_Interrupt/title",
          "value": "kScheduledAudioSliceFlag_Interrupt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUScheduledAudioSliceFlags~1scheduledAudioSliceFlag_Interrupt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kScheduledAudioSliceFlag_Interrupt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUScheduledAudioSliceFlags~1scheduledAudioSliceFlag_Loop/title",
          "value": "kScheduledAudioSliceFlag_Loop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUScheduledAudioSliceFlags~1scheduledAudioSliceFlag_Loop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kScheduledAudioSliceFlag_Loop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUScheduledAudioSliceFlags~1scheduledAudioSliceFlag_Complete/title",
          "value": "kScheduledAudioSliceFlag_Complete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUScheduledAudioSliceFlags~1scheduledAudioSliceFlag_Complete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kScheduledAudioSliceFlag_Complete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUScheduledAudioSliceFlags/title",
          "value": "AUScheduledAudioSliceFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUScheduledAudioSliceFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUScheduledAudioSliceFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUScheduledAudioSliceFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUScheduledAudioSliceFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUScheduledAudioSliceFlags~1scheduledAudioSliceFlag_BeganToRender/title",
          "value": "kScheduledAudioSliceFlag_BeganToRender"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUScheduledAudioSliceFlags~1scheduledAudioSliceFlag_BeganToRender/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kScheduledAudioSliceFlag_BeganToRender"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUScheduledAudioSliceFlags~1scheduledAudioSliceFlag_BeganToRenderLate/title",
          "value": "kScheduledAudioSliceFlag_BeganToRenderLate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUScheduledAudioSliceFlags~1scheduledAudioSliceFlag_BeganToRenderLate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kScheduledAudioSliceFlag_BeganToRenderLate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUScheduledAudioSliceFlags~1scheduledAudioSliceFlag_InterruptAtLoop/title",
          "value": "kScheduledAudioSliceFlag_InterruptAtLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUScheduledAudioSliceFlags~1scheduledAudioSliceFlag_InterruptAtLoop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kScheduledAudioSliceFlag_InterruptAtLoop"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/auscheduledaudiosliceflags/scheduledaudiosliceflag_complete"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/auscheduledaudiosliceflags/scheduledaudiosliceflag_complete"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
