{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier"},"abstract":[{"text":"An identifier for the media group’s type.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.medialibrary/documentation/MediaLibrary","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup"]]},"sections":[],"seeAlsoSections":[{"title":"Identifying the Group","identifiers":["doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/identifier","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/mediaSourceIdentifier","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/mediaLibrary"],"generated":true,"anchor":"Identifying-the-Group"}],"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"typeIdentifier"}],"platforms":[{"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"13.0","deprecated":false},{"name":"macOS","deprecatedAt":"10.15","beta":false,"unavailable":false,"introducedAt":"10.9","message":"MediaLibrary.framework will be removed in a future OS version. Use Photos.framework or iTunesLibrary.framework instead.","deprecated":false}],"role":"symbol","externalID":"c:objc(cs)MLMediaGroup(py)typeIdentifier","modules":[{"name":"Media Library"}],"roleHeading":"Instance Property","title":"typeIdentifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"typeIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String","identifier":"doc://com.externally.resolved.symbol/s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"inlineContent":[{"text":"Multiple groups within a media source can have the same type identifier. For descriptions of group type identifiers, see ","type":"text"},{"type":"reference","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["/documentation/medialibrary/mlmediagroup/typeidentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/medialibrary/mlmediagroup/typeidentifier"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/mediaLibrary":{"url":"/documentation/medialibrary/mlmediagroup/medialibrary","title":"mediaLibrary","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/mediaLibrary","abstract":[{"text":"A pointer to the media library instance that loaded the media group’s source.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaLibrary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MLMediaLibrary","text":"MLMediaLibrary"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"mediaLibrary"}],"type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SS":{"url":"/documentation/Swift/String","kind":"symbol","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"identifier":"doc://com.externally.resolved.symbol/s:SS","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String","kind":"identifier"}],"title":"String","type":"topic","role":"symbol"},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier":{"url":"/documentation/medialibrary/mlmediagroup/typeidentifier","abstract":[{"text":"An identifier for the media group’s type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"typeIdentifier"}],"identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/typeIdentifier","title":"typeIdentifier","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"typeIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/mediaSourceIdentifier":{"url":"/documentation/medialibrary/mlmediagroup/mediasourceidentifier","title":"mediaSourceIdentifier","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/mediaSourceIdentifier","abstract":[{"text":"An identifier for the source that loaded the media group.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaSourceIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"mediaSourceIdentifier"}],"type":"topic","kind":"symbol"},"doc://com.apple.medialibrary/documentation/MediaLibrary":{"kind":"symbol","title":"Media Library","abstract":[{"type":"text","text":"Access read-only collections of the user’s multimedia content."}],"type":"topic","deprecated":true,"url":"/documentation/medialibrary","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","type":"topic","role":"overview"},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup":{"abstract":[{"text":"The ","type":"text"},{"code":"MLMediaGroup","type":"codeVoice"},{"text":" class provides groupings for media objects from a single source of media, such as iTunes or Aperture. The media objects—individual files containing a piece of media such as a photo, song, or movie—are referenced by one or more groups within each media source. These groupings serve as filters, providing hierarchical structure to the collection of objects in each source.","type":"text"}],"type":"topic","title":"MLMediaGroup","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup","kind":"symbol","url":"/documentation/medialibrary/mlmediagroup","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MLMediaGroup"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MLMediaGroup"}]},"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/identifier":{"url":"/documentation/medialibrary/mlmediagroup/identifier","title":"identifier","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/identifier","abstract":[{"text":"An identifier for the media group.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants":{"url":"/documentation/medialibrary/medialibrary-constants","type":"topic","title":"MediaLibrary Constants","role":"collectionGroup","kind":"article","identifier":"doc://com.apple.medialibrary/documentation/MediaLibrary/medialibrary-constants","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"beta":false,"name":"macOS","deprecated":false,"introducedAt":"10.9","deprecatedAt":"10.15"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"typeIdentifier","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"typeIdentifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.medialibrary/documentation/MediaLibrary","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Identifying-the-Group","title":"Identifying the Group","identifiers":["doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/identifier","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/mediaSourceIdentifier","doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaGroup/mediaLibrary"],"generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1mediaLibrary/title","op":"replace","value":"mediaLibrary"},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1mediaLibrary/fragments","op":"replace","value":[{"text":"mediaLibrary","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1typeIdentifier/title","op":"replace","value":"typeIdentifier"},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1typeIdentifier/fragments","op":"replace","value":[{"kind":"identifier","text":"typeIdentifier"}]},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1mediaSourceIdentifier/title","op":"replace","value":"mediaSourceIdentifier"},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1mediaSourceIdentifier/fragments","op":"replace","value":[{"kind":"identifier","text":"mediaSourceIdentifier"}]},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup/title","op":"replace","value":"MLMediaGroup"},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup/fragments","op":"replace","value":[{"text":"MLMediaGroup","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MLMediaGroup"}]},{"path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1identifier/title","op":"replace","value":"identifier"},{"op":"replace","path":"/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaGroup~1identifier/fragments","value":[{"text":"identifier","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}