{
  "abstract": [
    {
      "text": "The enumerated error codes that the Sound Analysis framework produces.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SNErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Sound Analysis"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SNError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis": {
      "abstract": [
        {
          "text": "Classify various sounds by analyzing audio files or streams.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis",
      "kind": "symbol",
      "role": "collection",
      "title": "Sound Analysis",
      "type": "topic",
      "url": "/documentation/soundanalysis"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError": {
      "abstract": [
        {
          "text": "An error from the Sound Analysis framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNError"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNError"
        }
      ],
      "role": "symbol",
      "title": "SNError",
      "type": "topic",
      "url": "/documentation/soundanalysis/snerror"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code": {
      "abstract": [
        {
          "text": "The enumerated error codes that the Sound Analysis framework produces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SNError.Code",
      "type": "topic",
      "url": "/documentation/soundanalysis/snerror/code"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/soundanalysis/snerror/code/init(rawvalue:)"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFile": {
      "abstract": [
        {
          "text": "An error that indicates an audio file is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFile"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNErrorCodeInvalidFile"
        }
      ],
      "role": "symbol",
      "title": "SNError.Code.invalidFile",
      "type": "topic",
      "url": "/documentation/soundanalysis/snerror/code/invalidfile"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFormat": {
      "abstract": [
        {
          "text": "An error that indicates the audio data’s format isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFormat"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNErrorCodeInvalidFormat"
        }
      ],
      "role": "symbol",
      "title": "SNError.Code.invalidFormat",
      "type": "topic",
      "url": "/documentation/soundanalysis/snerror/code/invalidformat"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidModel": {
      "abstract": [
        {
          "text": "An error that indicates the sound classifier’s underlying Core ML model is an invalid model type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidModel"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNErrorCodeInvalidModel"
        }
      ],
      "role": "symbol",
      "title": "SNError.Code.invalidModel",
      "type": "topic",
      "url": "/documentation/soundanalysis/snerror/code/invalidmodel"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/operationFailed": {
      "abstract": [
        {
          "text": "An error that occurs when the framework fails to analyze audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationFailed"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/operationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNErrorCodeOperationFailed"
        }
      ],
      "role": "symbol",
      "title": "SNError.Code.operationFailed",
      "type": "topic",
      "url": "/documentation/soundanalysis/snerror/code/operationfailed"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/unknownError": {
      "abstract": [
        {
          "text": "An error that represents a failure that no other error handles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/unknownError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNErrorCodeUnknownError"
        }
      ],
      "role": "symbol",
      "title": "SNError.Code.unknownError",
      "type": "topic",
      "url": "/documentation/soundanalysis/snerror/code/unknownerror"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNErrorDomain": {
      "abstract": [
        {
          "text": "A string that identifies the Sound Analysis error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "SNErrorDomain",
      "type": "topic",
      "url": "/documentation/soundanalysis/snerrordomain"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidModel",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFormat",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFile",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/operationFailed",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/unknownError"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SNErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidModel",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFormat",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/invalidFile",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/operationFailed",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNError/Code/unknownError"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SNErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1invalidModel/title",
          "value": "SNErrorCodeInvalidModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1invalidModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNErrorCodeInvalidModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1operationFailed/title",
          "value": "SNErrorCodeOperationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1operationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNErrorCodeOperationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1unknownError/title",
          "value": "SNErrorCodeUnknownError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1unknownError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNErrorCodeUnknownError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1invalidFile/title",
          "value": "SNErrorCodeInvalidFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1invalidFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNErrorCodeInvalidFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNErrorDomain/title",
          "value": "SNErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code/title",
          "value": "SNErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1invalidFormat/title",
          "value": "SNErrorCodeInvalidFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNError~1Code~1invalidFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNErrorCodeInvalidFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/soundanalysis/snerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/soundanalysis/snerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
