{
  "abstract": [
    {
      "text": "The value that describes an abstract socket with a name you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization",
        "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare",
        "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/abstractSocket(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So28VZLinuxRosettaDirectoryShareC14VirtualizationE14CachingOptionsO14abstractSocketyAESScAEmF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "abstractSocket"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "VZLinuxRosettaDirectoryShare.CachingOptions.abstractSocket(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "abstractSocket"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name to use for the abstract socket.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "name"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare": {
      "abstract": [
        {
          "text": "The Linux directory share for Rosetta.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZLinuxRosettaDirectoryShare"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZLinuxRosettaDirectoryShare"
        }
      ],
      "role": "symbol",
      "title": "VZLinuxRosettaDirectoryShare",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum": {
      "abstract": [
        {
          "text": "Socket values you specify to configure Rosetta’s caching capabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CachingOptions"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CachingOptions"
        }
      ],
      "role": "symbol",
      "title": "VZLinuxRosettaDirectoryShare.CachingOptions",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare/cachingoptions-swift.enum"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/abstractSocket(_:)": {
      "abstract": [
        {
          "text": "The value that describes an abstract socket with a name you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "abstractSocket"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/abstractSocket(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "VZLinuxRosettaDirectoryShare.CachingOptions.abstractSocket(_:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare/cachingoptions-swift.enum/abstractsocket(_:)"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/unixSocket(_:)": {
      "abstract": [
        {
          "text": "The value that describes an UNIX domain socket at a path that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unixSocket"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/unixSocket(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "VZLinuxRosettaDirectoryShare.CachingOptions.unixSocket(_:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzlinuxrosettadirectoryshare/cachingoptions-swift.enum/unixsocket(_:)"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Socket-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZLinuxRosettaDirectoryShare/CachingOptions-swift.enum/unixSocket(_:)"
      ],
      "title": "Socket types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxRosettaDirectoryShare/title",
          "value": "VZLinuxRosettaDirectoryShare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxRosettaDirectoryShare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZLinuxRosettaDirectoryShare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZLinuxRosettaDirectoryShare/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZLinuxRosettaDirectoryShare"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzlinuxrosettadirectoryshare/cachingoptions-swift.enum/abstractsocket(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
