{
  "abstract": [
    {
      "text": "A status that indicates the framework’s Camera Assistance feature requires action from the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve/notConverged(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:17NearbyInteraction28NIAlgorithmConvergenceStatusO12notConvergedyACSayAC6ReasonVGcACmF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "notConverged"
      },
      {
        "kind": "text",
        "text": "(["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:17NearbyInteraction28NIAlgorithmConvergenceStatusO",
        "text": "NIAlgorithmConvergenceStatus"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:17NearbyInteraction28NIAlgorithmConvergenceStatusO6ReasonV",
        "text": "Reason"
      },
      {
        "kind": "text",
        "text": "])"
      }
    ],
    "modules": [
      {
        "name": "Nearby Interaction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NIAlgorithmConvergenceStatus.notConverged(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "notConverged"
            },
            {
              "kind": "text",
              "text": "(["
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:17NearbyInteraction28NIAlgorithmConvergenceStatusO",
              "text": "NIAlgorithmConvergenceStatus"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve/Reason",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:17NearbyInteraction28NIAlgorithmConvergenceStatusO6ReasonV",
              "text": "Reason"
            },
            {
              "kind": "text",
              "text": "])"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A user action that the framework recommends to get the Camera Assistance feature operational.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "reason"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In this state, the framework needs more information about the user’s physical environment before setting ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/horizontalAngle-hsg",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and/or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/verticalDirectionEstimate-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Look to the reasons array of the ",
              "type": "text"
            },
            {
              "code": "convergence",
              "type": "codeVoice"
            },
            {
              "text": " object provided by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didUpdateAlgorithmConvergence:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information on the cause. Each reason indicates a specific action the user can do to provide ARKit with the necessary camera data to support Nearby Interaction’s Camera Assistance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction": {
      "abstract": [
        {
          "text": "Locate and interact with nearby devices using identifiers, distance, and direction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
      "kind": "symbol",
      "role": "collection",
      "title": "Nearby Interaction",
      "type": "topic",
      "url": "/documentation/nearbyinteraction"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve": {
      "abstract": [
        {
          "text": "The possible states of Camera Assistance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatus"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatus"
        }
      ],
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatus",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatus-2fnve"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve/Reason": {
      "abstract": [
        {
          "text": "The possible reasons for the Camera Assistance status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Reason"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve/Reason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Reason"
        }
      ],
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatus.Reason",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatus-2fnve/reason"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve/converged": {
      "abstract": [
        {
          "text": "A status that indicates the framework’s Camera Assistance feature is operational.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "converged"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve/converged",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatus.converged",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatus-2fnve/converged"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve/notConverged(_:)": {
      "abstract": [
        {
          "text": "A status that indicates the framework’s Camera Assistance feature requires action from the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notConverged"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17NearbyInteraction28NIAlgorithmConvergenceStatusO",
          "text": "NIAlgorithmConvergenceStatus"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17NearbyInteraction28NIAlgorithmConvergenceStatusO6ReasonV",
          "text": "Reason"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve/notConverged(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatus.notConverged(_:)",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatus-2fnve/notconverged(_:)"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve/unknown": {
      "abstract": [
        {
          "text": "An indication that the framework is unsure of the Camera Assistance status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatus.unknown",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatus-2fnve/unknown"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/horizontalAngle-hsg": {
      "abstract": [
        {
          "text": "An angle in radians that indicates the azimuthal direction to the nearby object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontalAngle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/horizontalAngle-hsg",
      "kind": "symbol",
      "role": "symbol",
      "title": "horizontalAngle",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject/horizontalangle-hsg"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/verticalDirectionEstimate-swift.property": {
      "abstract": [
        {
          "text": "The estimation of a nearby object’s vertical position as it relates to the user’s device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalDirectionEstimate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NINearbyObject",
          "text": "NINearbyObject"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NINearbyObjectVerticalDirectionEstimate",
          "text": "VerticalDirectionEstimate"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyObject/verticalDirectionEstimate-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "verticalDirectionEstimate"
        }
      ],
      "role": "symbol",
      "title": "verticalDirectionEstimate",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbyobject/verticaldirectionestimate-swift.property"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didUpdateAlgorithmConvergence:for:)": {
      "abstract": [
        {
          "text": "Provides recommended actions the user can take to facilitate the framework’s Camera Assistance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NISession",
          "text": "NISession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdateAlgorithmConvergence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NIAlgorithmConvergence",
          "text": "NIAlgorithmConvergence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NINearbyObject",
          "text": "NINearbyObject"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didUpdateAlgorithmConvergence:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session:didUpdateAlgorithmConvergence:forObject:"
        }
      ],
      "role": "symbol",
      "title": "session(_:didUpdateAlgorithmConvergence:for:)",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nisessiondelegate/session(_:didupdatealgorithmconvergence:for:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interpreting-the-convergence-state",
      "generated": true,
      "identifiers": [
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve/converged",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve/unknown"
      ],
      "title": "Interpreting the convergence state"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1verticalDirectionEstimate-swift.property/title",
          "value": "verticalDirectionEstimate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyObject~1verticalDirectionEstimate-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "verticalDirectionEstimate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISessionDelegate~1session(_:didUpdateAlgorithmConvergence:for:)/title",
          "value": "session:didUpdateAlgorithmConvergence:forObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISessionDelegate~1session(_:didUpdateAlgorithmConvergence:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:didUpdateAlgorithmConvergence:forObject:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/nearbyinteraction/nialgorithmconvergencestatus-2fnve/notconverged(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
