{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/mode-swift.property"},"sections":[],"abstract":[{"type":"text","text":"A VAS protocol mode."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration","text":"NFCVASCommandConfiguration","preciseIdentifier":"c:objc(cs)NFCVASCommandConfiguration"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum","text":"Mode","preciseIdentifier":"c:@E@NFCVASMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/corenfc/nfcvascommandconfiguration/mode-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/corenfc/nfcvascommandconfiguration/mode-swift.property"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"platforms":[{"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","introducedAt":"13.0","deprecated":false,"beta":false},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"beta":false}],"symbolKind":"property","externalID":"c:objc(cs)NFCVASCommandConfiguration(py)mode","modules":[{"name":"Core NFC"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NFCVASCommandConfiguration","text":"NFCVASCommandConfiguration","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NFCVASMode","text":"Mode","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"mode","kind":"identifier"}],"roleHeading":"Instance Property","title":"mode","role":"symbol"},"seeAlsoSections":[{"generated":true,"title":"Setting Configuration Items","anchor":"Setting-Configuration-Items","identifiers":["doc://com.apple.corenfc/documentation/CoreNFC/VASMode","doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/passTypeIdentifier","doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/url"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corenfc/documentation/CoreNFC","doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration"]]},"references":{"doc://com.apple.corenfc/documentation/CoreNFC":{"abstract":[{"type":"text","text":"Detect NFC tags, read messages that contain NDEF data, and save data to writable tags."}],"title":"Core NFC","identifier":"doc://com.apple.corenfc/documentation/CoreNFC","type":"topic","kind":"symbol","url":"/documentation/corenfc","role":"collection"},"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/passTypeIdentifier":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passTypeIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/passTypeIdentifier","url":"/documentation/corenfc/nfcvascommandconfiguration/passtypeidentifier","role":"symbol","title":"passTypeIdentifier","kind":"symbol","type":"topic","abstract":[{"text":"A type identifier for the Wallet Pass.","type":"text"}],"navigatorTitle":[{"text":"passTypeIdentifier","kind":"identifier"}]},"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NFCVASCommandConfiguration"}],"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration","url":"/documentation/corenfc/nfcvascommandconfiguration","role":"symbol","title":"NFCVASCommandConfiguration","kind":"symbol","type":"topic","abstract":[{"text":"An object providing the configuration for a GET VAS DATA command.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NFCVASCommandConfiguration"}]},"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mode"}],"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum","url":"/documentation/corenfc/nfcvascommandconfiguration/mode-swift.enum","role":"symbol","title":"NFCVASCommandConfiguration.Mode","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Mode"}]},"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/url":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/url","url":"/documentation/corenfc/nfcvascommandconfiguration/url","role":"symbol","title":"url","kind":"symbol","type":"topic","abstract":[{"text":"A merchant URL.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"url"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","title":"Technologies","kind":"technologies","abstract":[{"type":"text","text":""}],"role":"overview","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/mode-swift.property":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NFCVASCommandConfiguration","preciseIdentifier":"c:objc(cs)NFCVASCommandConfiguration","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Mode","preciseIdentifier":"c:@E@NFCVASMode","kind":"typeIdentifier"}],"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/mode-swift.property","url":"/documentation/corenfc/nfcvascommandconfiguration/mode-swift.property","role":"symbol","title":"mode","kind":"symbol","type":"topic","abstract":[{"text":"A VAS protocol mode.","type":"text"}],"navigatorTitle":[{"text":"mode","kind":"identifier"}]},"doc://com.apple.corenfc/documentation/CoreNFC/VASMode":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VASMode","kind":"identifier"}],"identifier":"doc://com.apple.corenfc/documentation/CoreNFC/VASMode","url":"/documentation/corenfc/vasmode","role":"symbol","deprecated":true,"title":"VASMode","kind":"symbol","type":"topic","abstract":[{"text":"Constants that indicate the VAS protocol mode.","type":"text"}],"navigatorTitle":[{"text":"VASMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"name":"iOS","introducedAt":"13.0","unavailable":false,"beta":false},{"deprecated":false,"name":"iPadOS","introducedAt":"13.0","unavailable":false,"beta":false},{"introducedAt":"13.1","deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"mode"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"mode","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.corenfc/documentation/CoreNFC","doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Setting-Configuration-Items","generated":true,"title":"Setting Configuration Items","identifiers":["doc://com.apple.corenfc/documentation/CoreNFC/VASMode","doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/passTypeIdentifier","doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/url"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum","preciseIdentifier":"c:@E@NFCVASMode","text":"NFCVASMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"passTypeIdentifier","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1passTypeIdentifier/title","op":"replace"},{"value":[{"text":"passTypeIdentifier","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1passTypeIdentifier/fragments","op":"replace"},{"value":"NFCVASCommandConfiguration","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration/title","op":"replace"},{"value":[{"kind":"identifier","text":"NFCVASCommandConfiguration"}],"path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration/fragments","op":"replace"},{"value":[{"text":"NFCVASCommandConfiguration","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration/navigatorTitle","op":"replace"},{"value":"NFCVASMode","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1Mode-swift.enum/title","op":"replace"},{"value":[{"text":"NFCVASMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1Mode-swift.enum/fragments","op":"replace"},{"value":[{"text":"NFCVASMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1Mode-swift.enum/navigatorTitle","op":"replace"},{"value":"url","path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1url/title","op":"replace"},{"value":[{"kind":"identifier","text":"url"}],"path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1url/fragments","op":"replace"},{"path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1mode-swift.property/title","op":"replace","value":"mode"},{"path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1mode-swift.property/fragments","op":"replace","value":[{"kind":"identifier","text":"mode"}]},{"path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1VASMode/title","op":"replace","value":"VASMode"},{"path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1VASMode/fragments","op":"replace","value":[{"kind":"identifier","text":"VASMode"}]},{"path":"/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1VASMode/navigatorTitle","op":"replace","value":[{"text":"VASMode","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}