{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/sample"},"seeAlsoSections":[{"title":"Sampling Data","generated":true,"identifiers":["doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/timestamp"],"anchor":"Sampling-Data"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.sensorkit/documentation/SensorKit","doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sample","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SampleType","kind":"typeIdentifier"}],"externalID":"c:objc(cs)SRFetchResult(py)sample","modules":[{"name":"SensorKit"}],"roleHeading":"Instance Property","platforms":[{"unavailable":false,"beta":false,"introducedAt":"14.0","deprecated":false,"name":"iOS"},{"unavailable":false,"beta":false,"introducedAt":"14.0","deprecated":false,"name":"iPadOS"},{"unavailable":false,"beta":false,"introducedAt":"14.0","deprecated":false,"name":"Mac Catalyst"}],"title":"sample","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"sample","kind":"identifier"}]},"sections":[],"abstract":[{"type":"text","text":"A recording that the sensor reader fetches."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@NSCopying","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sample","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SampleType","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"The framework expects the app to know the result type based on the reader’s sensor."}],"type":"paragraph"},{"level":3,"type":"heading","text":"Sample types","anchor":"Sample-types"},{"inlineContent":[{"type":"text","text":"This property’s type is a superclass from which the framework derives discrete sample types. Depending on the sensor associated with your app’s sensor reader, type cast the fetch result’s "},{"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/sample","isActive":true},{"type":"text","text":" to the sensor’s associated sample type. The following list provides the sample type per sensor:"}],"type":"paragraph"},{"items":[{"definition":{"content":[{"inlineContent":[{"text":"[","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/CoreMotion/CMRecordedAccelerometerData"},{"text":"]","type":"text"}],"type":"paragraph"}]},"term":{"inlineContent":[{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/accelerometer","type":"reference","isActive":true}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample"}]}]},"term":{"inlineContent":[{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/ambientLightSensor","type":"reference","isActive":true}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"["},{"identifier":"doc://com.apple.documentation/documentation/CoreMotion/CMRecordedPressureData","isActive":true,"type":"reference"},{"type":"codeVoice","code":"]"}]}]},"term":{"inlineContent":[{"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/ambientPressure","isActive":true}]}},{"definition":{"content":[{"inlineContent":[{"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport","isActive":true}],"type":"paragraph"}]},"term":{"inlineContent":[{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/deviceUsageReport","type":"reference","isActive":true}]}},{"definition":{"content":[{"inlineContent":[{"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics","isActive":true}],"type":"paragraph"}]},"term":{"inlineContent":[{"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/faceMetrics","isActive":true}]}},{"definition":{"content":[{"inlineContent":[{"identifier":"doc://com.apple.documentation/documentation/CoreMotion/CMHighFrequencyHeartRateData","type":"reference","isActive":true}],"type":"paragraph"}]},"term":{"inlineContent":[{"isActive":true,"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/heartRate","type":"reference"}]}},{"definition":{"content":[{"inlineContent":[{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics","isActive":true,"type":"reference"}],"type":"paragraph"}]},"term":{"inlineContent":[{"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/keyboardMetrics","isActive":true}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEvent","type":"reference"}]}]},"term":{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/mediaEvents"}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRMessagesUsageReport","type":"reference","isActive":true}]}]},"term":{"inlineContent":[{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/messagesUsageReport","isActive":true,"type":"reference"}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/CoreMotion/CMOdometerData"}]}]},"term":{"inlineContent":[{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/odometer","isActive":true,"type":"reference"}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection"}]}]},"term":{"inlineContent":[{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/onWristState","isActive":true,"type":"reference"}]}},{"definition":{"content":[{"inlineContent":[{"identifier":"doc://com.apple.documentation/documentation/CoreMotion/CMPedometerData","isActive":true,"type":"reference"}],"type":"paragraph"}]},"term":{"inlineContent":[{"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/pedometerData","isActive":true}]}},{"definition":{"content":[{"inlineContent":[{"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRPhoneUsageReport","isActive":true}],"type":"paragraph"}]},"term":{"inlineContent":[{"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/phoneUsageReport","isActive":true}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"text":"[","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/CoreMotion/CMRecordedRotationRateData","type":"reference"},{"text":"]","type":"text"}]}]},"term":{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/rotationRate"}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSpeechMetrics","type":"reference","isActive":true}]}]},"term":{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/siriSpeechMetrics"}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSpeechMetrics","isActive":true,"type":"reference"}]}]},"term":{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/telephonySpeechMetrics"}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRVisit"}]}]},"term":{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/visits"}]}},{"definition":{"content":[{"inlineContent":[{"type":"reference","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature","isActive":true}],"type":"paragraph"}]},"term":{"inlineContent":[{"isActive":true,"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/wristTemperature","type":"reference"}]}}],"type":"termList"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/sensorkit/srfetchresult/sample"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/sensorkit/srfetchresult/sample"]}],"references":{"doc://com.apple.documentation/documentation/CoreMotion/CMRecordedAccelerometerData":{"type":"topic","abstract":[{"text":"A single piece of accelerometer data that was recorded by the device.","type":"text"}],"url":"/documentation/CoreMotion/CMRecordedAccelerometerData","title":"CMRecordedAccelerometerData","role":"symbol","kind":"symbol","identifier":"doc://com.apple.documentation/documentation/CoreMotion/CMRecordedAccelerometerData","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMRecordedAccelerometerData"}]},"doc://com.apple.documentation/documentation/CoreMotion/CMOdometerData":{"url":"/documentation/CoreMotion/CMOdometerData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMOdometerData"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.documentation/documentation/CoreMotion/CMOdometerData","type":"topic","abstract":[{"type":"text","text":"A class that represents odometer data for workouts."}],"title":"CMOdometerData"},"doc://com.apple.documentation/documentation/CoreMotion/CMPedometerData":{"url":"/documentation/CoreMotion/CMPedometerData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMPedometerData"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.documentation/documentation/CoreMotion/CMPedometerData","type":"topic","abstract":[{"type":"text","text":"Information about the distance traveled by a user on foot."}],"title":"CMPedometerData"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/faceMetrics":{"kind":"symbol","title":"faceMetrics","role":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/faceMetrics","abstract":[{"type":"text","text":"A sensor that provides data describing a user’s face."}],"navigatorTitle":[{"text":"SRSensorFaceMetrics","kind":"identifier"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceMetrics"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@SRSensor","text":"SRSensor","kind":"typeIdentifier"}],"url":"/documentation/sensorkit/srsensor/facemetrics"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/siriSpeechMetrics":{"abstract":[{"type":"text","text":"A sensor that provides data describing a user’s speech to Siri."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"siriSpeechMetrics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SRSensor","preciseIdentifier":"c:@T@SRSensor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SRSensorSiriSpeechMetrics","kind":"identifier"}],"type":"topic","url":"/documentation/sensorkit/srsensor/sirispeechmetrics","role":"symbol","kind":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/siriSpeechMetrics","title":"siriSpeechMetrics"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/odometer":{"abstract":[{"type":"text","text":"A sensor that provides information about speed and slope."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SRSensorOdometer"}],"url":"/documentation/sensorkit/srsensor/odometer","type":"topic","role":"symbol","title":"odometer","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"odometer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SRSensor","preciseIdentifier":"c:@T@SRSensor"}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/odometer"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/wristTemperature":{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/wristTemperature","title":"wristTemperature","abstract":[{"text":"A sensor that provides wrist temperature while the user sleeps.","type":"text"}],"url":"/documentation/sensorkit/srsensor/wristtemperature","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wristTemperature","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@SRSensor","text":"SRSensor","kind":"typeIdentifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SRSensorWristTemperature","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","title":"Technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies"},"doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport":{"abstract":[{"type":"text","text":"The frequency and relative duration that the user uses their device, particular Apple apps, or websites."}],"url":"/documentation/sensorkit/srdeviceusagereport","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRDeviceUsageReport","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SRDeviceUsageReport","kind":"identifier"}],"title":"SRDeviceUsageReport","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SRDeviceUsageReport","kind":"identifier"}],"type":"topic"},"doc://com.apple.sensorkit/documentation/SensorKit/SRPhoneUsageReport":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SRPhoneUsageReport","kind":"identifier"}],"abstract":[{"text":"An object that describes the user’s phone activity over a period of time.","type":"text"}],"type":"topic","title":"SRPhoneUsageReport","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRPhoneUsageReport","navigatorTitle":[{"text":"SRPhoneUsageReport","kind":"identifier"}],"url":"/documentation/sensorkit/srphoneusagereport","role":"symbol","kind":"symbol"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/onWristState":{"role":"symbol","title":"onWristState","kind":"symbol","url":"/documentation/sensorkit/srsensor/onwriststate","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"onWristState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SRSensor","preciseIdentifier":"c:@T@SRSensor"}],"abstract":[{"type":"text","text":"A sensor that describes the watch’s position on the wrist."}],"navigatorTitle":[{"kind":"identifier","text":"SRSensorOnWristState"}],"type":"topic","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/onWristState"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/mediaEvents":{"role":"symbol","abstract":[{"text":"A sensor that provides information about interactions with media, such as images and videos, in messaging apps.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mediaEvents"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SRSensor","preciseIdentifier":"c:@T@SRSensor"}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/mediaEvents","title":"mediaEvents","url":"/documentation/sensorkit/srsensor/mediaevents","navigatorTitle":[{"kind":"identifier","text":"SRSensorMediaEvents"}],"kind":"symbol","type":"topic"},"doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEvent":{"type":"topic","kind":"symbol","abstract":[{"text":"A user interaction with a media object, such as an image or a video.","type":"text"}],"title":"SRMediaEvent","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRMediaEvent","navigatorTitle":[{"text":"SRMediaEvent","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SRMediaEvent","kind":"identifier"}],"url":"/documentation/sensorkit/srmediaevent","role":"symbol"},"doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult":{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult","role":"symbol","abstract":[{"text":"Recorded data that a sensor reader fetches.","type":"text"}],"kind":"symbol","title":"SRFetchResult","navigatorTitle":[{"kind":"identifier","text":"SRFetchResult"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SRFetchResult"}],"url":"/documentation/sensorkit/srfetchresult"},"doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics":{"navigatorTitle":[{"kind":"identifier","text":"SRKeyboardMetrics"}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRKeyboardMetrics","title":"SRKeyboardMetrics","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The configuration of a device’s keyboard and its usage patterns."}],"kind":"symbol","url":"/documentation/sensorkit/srkeyboardmetrics","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SRKeyboardMetrics"}]},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/visits":{"kind":"symbol","title":"visits","role":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/visits","abstract":[{"text":"A sensor that provides information about frequently visited locations.","type":"text"}],"navigatorTitle":[{"text":"SRSensorVisits","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"visits"},{"kind":"text","text":": "},{"text":"SRSensor","kind":"typeIdentifier","preciseIdentifier":"c:@T@SRSensor"}],"url":"/documentation/sensorkit/srsensor/visits"},"doc://com.apple.documentation/documentation/CoreMotion/CMRecordedPressureData":{"url":"/documentation/CoreMotion/CMRecordedPressureData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMRecordedPressureData"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.documentation/documentation/CoreMotion/CMRecordedPressureData","type":"topic","abstract":[{"type":"text","text":"A recorded measurement of pressure data."}],"title":"CMRecordedPressureData"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/rotationRate":{"abstract":[{"text":"A sensor that provides rotation motion data.","type":"text"}],"title":"rotationRate","kind":"symbol","url":"/documentation/sensorkit/srsensor/rotationrate","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"rotationRate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SRSensor","kind":"typeIdentifier","preciseIdentifier":"c:@T@SRSensor"}],"navigatorTitle":[{"text":"SRSensorRotationRate","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/rotationRate"},"doc://com.apple.sensorkit/documentation/SensorKit/SRVisit":{"title":"SRVisit","navigatorTitle":[{"text":"SRVisit","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SRVisit","kind":"identifier"}],"abstract":[{"text":"The user’s progress in their daily travel routine.","type":"text"}],"url":"/documentation/sensorkit/srvisit","role":"symbol","type":"topic","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRVisit"},"doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics":{"title":"SRFaceMetrics","role":"symbol","abstract":[{"type":"text","text":"An object that represents metrics about the user’s face."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SRFaceMetrics"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SRFaceMetrics"}],"url":"/documentation/sensorkit/srfacemetrics","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRFaceMetrics"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/messagesUsageReport":{"abstract":[{"text":"A sensor that provides information about use of the Messages app.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesUsageReport"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SRSensor","preciseIdentifier":"c:@T@SRSensor"}],"url":"/documentation/sensorkit/srsensor/messagesusagereport","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SRSensorMessagesUsageReport"}],"type":"topic","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/messagesUsageReport","title":"messagesUsageReport"},"doc://com.apple.sensorkit/documentation/SensorKit":{"type":"topic","title":"SensorKit","abstract":[{"type":"text","text":"Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch."}],"url":"/documentation/sensorkit","role":"collection","identifier":"doc://com.apple.sensorkit/documentation/SensorKit","kind":"symbol"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/heartRate":{"abstract":[{"type":"text","text":"A sensor that provides the user’s heart rate data."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"heartRate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SRSensor","preciseIdentifier":"c:@T@SRSensor"}],"navigatorTitle":[{"kind":"identifier","text":"SRSensorHeartRate"}],"type":"topic","url":"/documentation/sensorkit/srsensor/heartrate","role":"symbol","kind":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/heartRate","title":"heartRate"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/phoneUsageReport":{"type":"topic","url":"/documentation/sensorkit/srsensor/phoneusagereport","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SRSensorPhoneUsageReport"}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/phoneUsageReport","abstract":[{"type":"text","text":"A sensor that reports the amount of time that the user is on phone calls."}],"title":"phoneUsageReport","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneUsageReport"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@SRSensor","kind":"typeIdentifier","text":"SRSensor"}],"role":"symbol"},"doc://com.apple.documentation/documentation/CoreMotion/CMRecordedRotationRateData":{"url":"/documentation/CoreMotion/CMRecordedRotationRateData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMRecordedRotationRateData"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.documentation/documentation/CoreMotion/CMRecordedRotationRateData","type":"topic","abstract":[{"type":"text","text":"A data object that contains a single rotation-rate measurement at a specific time."}],"title":"CMRecordedRotationRateData"},"doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection":{"title":"SRWristDetection","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SRWristDetection"}],"abstract":[{"type":"text","text":"The configuration of a watch on the wearer’s wrist."}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRWristDetection","navigatorTitle":[{"kind":"identifier","text":"SRWristDetection"}],"url":"/documentation/sensorkit/srwristdetection"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/keyboardMetrics":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardMetrics","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@SRSensor","text":"SRSensor","kind":"typeIdentifier"}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/keyboardMetrics","title":"keyboardMetrics","role":"symbol","type":"topic","url":"/documentation/sensorkit/srsensor/keyboardmetrics","abstract":[{"text":"A sensor that provides information about keyboard usage.","type":"text"}],"navigatorTitle":[{"text":"SRSensorKeyboardMetrics","kind":"identifier"}]},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/ambientPressure":{"url":"/documentation/sensorkit/srsensor/ambientpressure","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ambientPressure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SRSensor","preciseIdentifier":"c:@T@SRSensor"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/ambientPressure","navigatorTitle":[{"kind":"identifier","text":"SRSensorAmbientPressure"}],"type":"topic","abstract":[{"type":"text","text":"A sensor that provides pressure and temperature metrics."}],"title":"ambientPressure"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/pedometerData":{"abstract":[{"type":"text","text":"A sensor that provides information about the user’s steps."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pedometerData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SRSensor","preciseIdentifier":"c:@T@SRSensor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SRSensorPedometerData","kind":"identifier"}],"type":"topic","url":"/documentation/sensorkit/srsensor/pedometerdata","role":"symbol","kind":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/pedometerData","title":"pedometerData"},"doc://com.apple.sensorkit/documentation/SensorKit/SRMessagesUsageReport":{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRMessagesUsageReport","url":"/documentation/sensorkit/srmessagesusagereport","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SRMessagesUsageReport"}],"abstract":[{"type":"text","text":"An object that describes the user’s Messages app activity over a period of time."}],"title":"SRMessagesUsageReport","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SRMessagesUsageReport"}]},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/accelerometer":{"role":"symbol","abstract":[{"text":"A sensor that provides acceleration motion data.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"accelerometer","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SRSensor","preciseIdentifier":"c:@T@SRSensor"}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/accelerometer","title":"accelerometer","url":"/documentation/sensorkit/srsensor/accelerometer","navigatorTitle":[{"kind":"identifier","text":"SRSensorAccelerometer"}],"kind":"symbol","type":"topic"},"doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample":{"type":"topic","abstract":[{"type":"text","text":"The amount of ambient light in the user’s environment."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SRAmbientLightSample"}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRAmbientLightSample","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SRAmbientLightSample"}],"title":"SRAmbientLightSample","url":"/documentation/sensorkit/srambientlightsample"},"doc://com.apple.documentation/documentation/CoreMotion/CMHighFrequencyHeartRateData":{"url":"/documentation/CoreMotion/CMHighFrequencyHeartRateData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMHighFrequencyHeartRateData"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.documentation/documentation/CoreMotion/CMHighFrequencyHeartRateData","type":"topic","abstract":[{"type":"text","text":"A class that represents heart rate data collected at 1 Hz."}],"title":"CMHighFrequencyHeartRateData"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/deviceUsageReport":{"abstract":[{"type":"text","text":"A sensor that provides information about device usage."}],"type":"topic","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/deviceUsageReport","url":"/documentation/sensorkit/srsensor/deviceusagereport","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SRSensorDeviceUsageReport"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceUsageReport","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SRSensor","preciseIdentifier":"c:@T@SRSensor"}],"title":"deviceUsageReport","kind":"symbol"},"doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/timestamp":{"abstract":[{"text":"The time when the framework records the sample.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SRAbsoluteTime","preciseIdentifier":"c:@T@SRAbsoluteTime"}],"role":"symbol","title":"timestamp","type":"topic","url":"/documentation/sensorkit/srfetchresult/timestamp","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"timestamp"}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/timestamp"},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/ambientLightSensor":{"type":"topic","url":"/documentation/sensorkit/srsensor/ambientlightsensor","role":"symbol","abstract":[{"type":"text","text":"A sensor that provides ambient light information."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ambientLightSensor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SRSensor","preciseIdentifier":"c:@T@SRSensor"}],"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/ambientLightSensor","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SRSensorAmbientLightSensor"}],"title":"ambientLightSensor"},"doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/sample":{"navigatorTitle":[{"kind":"identifier","text":"sample"}],"type":"topic","role":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/sample","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sample"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SampleType"}],"url":"/documentation/sensorkit/srfetchresult/sample","kind":"symbol","title":"sample","abstract":[{"type":"text","text":"A recording that the sensor reader fetches."}]},"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/telephonySpeechMetrics":{"abstract":[{"type":"text","text":"A sensor that provides data describing speech during phone calls."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"telephonySpeechMetrics","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SRSensor","preciseIdentifier":"c:@T@SRSensor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SRSensorTelephonySpeechMetrics","kind":"identifier"}],"type":"topic","url":"/documentation/sensorkit/srsensor/telephonyspeechmetrics","role":"symbol","kind":"symbol","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSensor/telephonySpeechMetrics","title":"telephonySpeechMetrics"},"doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature":{"identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRWristTemperature","title":"SRWristTemperature","abstract":[{"text":"The temperature of the user’s wrist while the user sleeps.","type":"text"}],"url":"/documentation/sensorkit/srwristtemperature","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SRWristTemperature","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SRWristTemperature","kind":"identifier"}]},"doc://com.apple.sensorkit/documentation/SensorKit/SRSpeechMetrics":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SRSpeechMetrics","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc://com.apple.sensorkit/documentation/SensorKit/SRSpeechMetrics","abstract":[{"type":"text","text":"An object that represents metrics about a range of speech."}],"title":"SRSpeechMetrics","url":"/documentation/sensorkit/srspeechmetrics","navigatorTitle":[{"text":"SRSpeechMetrics","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"beta":false,"introducedAt":"14.0","name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"sample","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"sample"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.sensorkit/documentation/SensorKit","doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Sampling-Data","generated":true,"identifiers":["doc://com.apple.sensorkit/documentation/SensorKit/SRFetchResult/timestamp"],"title":"Sampling Data"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"SampleType"},{"kind":"text","text":" "},{"kind":"identifier","text":"sample"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMRecordedAccelerometerData"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)CMAccelerometerData","kind":"typeIdentifier","text":"CMAccelerometerData"}],"op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMRecordedAccelerometerData/fragments"},{"value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMOdometerData"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMOdometerData/fragments"},{"value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMPedometerData"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMPedometerData/fragments"},{"value":"SRSensorFaceMetrics","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1faceMetrics/title"},{"value":[{"text":"SRSensorFaceMetrics","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1faceMetrics/fragments"},{"value":"SRSensorSiriSpeechMetrics","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1siriSpeechMetrics/title"},{"value":[{"text":"SRSensorSiriSpeechMetrics","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1siriSpeechMetrics/fragments"},{"value":"SRSensorOdometer","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1odometer/title"},{"value":[{"kind":"identifier","text":"SRSensorOdometer"}],"op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1odometer/fragments"},{"value":"SRSensorWristTemperature","op":"replace","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1wristTemperature/title"},{"op":"replace","value":[{"kind":"identifier","text":"SRSensorWristTemperature"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1wristTemperature/fragments"},{"op":"replace","value":"SRDeviceUsageReport","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/title"},{"op":"replace","value":[{"kind":"identifier","text":"SRDeviceUsageReport"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SRDeviceUsageReport"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRDeviceUsageReport/navigatorTitle"},{"op":"replace","value":"SRPhoneUsageReport","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhoneUsageReport/title"},{"op":"replace","value":[{"kind":"identifier","text":"SRPhoneUsageReport"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhoneUsageReport/fragments"},{"op":"replace","value":[{"text":"SRPhoneUsageReport","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhoneUsageReport/navigatorTitle"},{"op":"replace","value":"SRSensorOnWristState","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1onWristState/title"},{"op":"replace","value":[{"text":"SRSensorOnWristState","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1onWristState/fragments"},{"op":"replace","value":"SRSensorMediaEvents","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1mediaEvents/title"},{"op":"replace","value":[{"text":"SRSensorMediaEvents","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1mediaEvents/fragments"},{"op":"replace","value":"SRMediaEvent","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEvent/title"},{"op":"replace","value":[{"text":"SRMediaEvent","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEvent/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SRMediaEvent"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMediaEvent/navigatorTitle"},{"op":"replace","value":"SRFetchResult","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult/title"},{"op":"replace","value":[{"kind":"identifier","text":"SRFetchResult"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SRFetchResult"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult/navigatorTitle"},{"op":"replace","value":"SRKeyboardMetrics","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/title"},{"op":"replace","value":[{"kind":"identifier","text":"SRKeyboardMetrics"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/fragments"},{"op":"replace","value":[{"text":"SRKeyboardMetrics","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRKeyboardMetrics/navigatorTitle"},{"op":"replace","value":"SRSensorVisits","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1visits/title"},{"op":"replace","value":[{"text":"SRSensorVisits","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1visits/fragments"},{"op":"replace","value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMRecordedPressureData"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"CMAmbientPressureData","preciseIdentifier":"c:objc(cs)CMAmbientPressureData"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMRecordedPressureData/fragments"},{"op":"replace","value":"SRSensorRotationRate","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1rotationRate/title"},{"op":"replace","value":[{"text":"SRSensorRotationRate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1rotationRate/fragments"},{"op":"replace","value":"SRVisit","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit/title"},{"op":"replace","value":[{"text":"SRVisit","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SRVisit"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRVisit/navigatorTitle"},{"op":"replace","value":"SRFaceMetrics","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetrics/title"},{"op":"replace","value":[{"text":"SRFaceMetrics","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetrics/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SRFaceMetrics"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFaceMetrics/navigatorTitle"},{"op":"replace","value":"SRSensorMessagesUsageReport","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1messagesUsageReport/title"},{"op":"replace","value":[{"text":"SRSensorMessagesUsageReport","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1messagesUsageReport/fragments"},{"op":"replace","value":"SRSensorHeartRate","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1heartRate/title"},{"op":"replace","value":[{"text":"SRSensorHeartRate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1heartRate/fragments"},{"op":"replace","value":"SRSensorPhoneUsageReport","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1phoneUsageReport/title"},{"op":"replace","value":[{"text":"SRSensorPhoneUsageReport","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1phoneUsageReport/fragments"},{"op":"replace","value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CMRecordedRotationRateData","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"CMRotationRateData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CMRotationRateData"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMRecordedRotationRateData/fragments"},{"op":"replace","value":"SRWristDetection","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection/title"},{"op":"replace","value":[{"kind":"identifier","text":"SRWristDetection"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SRWristDetection"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristDetection/navigatorTitle"},{"op":"replace","value":"SRSensorKeyboardMetrics","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1keyboardMetrics/title"},{"op":"replace","value":[{"kind":"identifier","text":"SRSensorKeyboardMetrics"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1keyboardMetrics/fragments"},{"op":"replace","value":"SRSensorAmbientPressure","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1ambientPressure/title"},{"op":"replace","value":[{"kind":"identifier","text":"SRSensorAmbientPressure"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1ambientPressure/fragments"},{"op":"replace","value":"SRSensorPedometerData","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1pedometerData/title"},{"op":"replace","value":[{"kind":"identifier","text":"SRSensorPedometerData"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1pedometerData/fragments"},{"op":"replace","value":"SRMessagesUsageReport","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMessagesUsageReport/title"},{"op":"replace","value":[{"text":"SRMessagesUsageReport","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMessagesUsageReport/fragments"},{"op":"replace","value":[{"text":"SRMessagesUsageReport","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRMessagesUsageReport/navigatorTitle"},{"op":"replace","value":"SRSensorAccelerometer","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1accelerometer/title"},{"op":"replace","value":[{"text":"SRSensorAccelerometer","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1accelerometer/fragments"},{"op":"replace","value":"SRAmbientLightSample","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/title"},{"op":"replace","value":[{"text":"SRAmbientLightSample","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SRAmbientLightSample"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRAmbientLightSample/navigatorTitle"},{"op":"replace","value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CMHighFrequencyHeartRateData","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CMLogItem","text":"CMLogItem","kind":"typeIdentifier"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMHighFrequencyHeartRateData/fragments"},{"op":"replace","value":"SRSensorDeviceUsageReport","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1deviceUsageReport/title"},{"op":"replace","value":[{"text":"SRSensorDeviceUsageReport","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1deviceUsageReport/fragments"},{"op":"replace","value":"timestamp","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult~1timestamp/title"},{"op":"replace","value":[{"kind":"identifier","text":"timestamp"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult~1timestamp/fragments"},{"op":"replace","value":"SRSensorAmbientLightSensor","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1ambientLightSensor/title"},{"op":"replace","value":[{"kind":"identifier","text":"SRSensorAmbientLightSensor"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1ambientLightSensor/fragments"},{"op":"replace","value":"sample","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult~1sample/title"},{"op":"replace","value":[{"kind":"identifier","text":"sample"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRFetchResult~1sample/fragments"},{"op":"replace","value":"SRSensorTelephonySpeechMetrics","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1telephonySpeechMetrics/title"},{"op":"replace","value":[{"text":"SRSensorTelephonySpeechMetrics","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSensor~1telephonySpeechMetrics/fragments"},{"op":"replace","value":"SRWristTemperature","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/title"},{"op":"replace","value":[{"text":"SRWristTemperature","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/fragments"},{"op":"replace","value":[{"text":"SRWristTemperature","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRWristTemperature/navigatorTitle"},{"op":"replace","value":"SRSpeechMetrics","path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSpeechMetrics/title"},{"op":"replace","value":[{"text":"SRSpeechMetrics","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSpeechMetrics/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SRSpeechMetrics"}],"path":"/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRSpeechMetrics/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}