{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iosurface/documentation/IOSurface",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState/kIOSurfacePurgeableNonVolatile"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@IOSurfacePurgeabilityState@kIOSurfacePurgeableNonVolatile",
    "fragments": [
      {
        "kind": "identifier",
        "text": "kIOSurfacePurgeableNonVolatile"
      }
    ],
    "modules": [
      {
        "name": "IOSurface"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kIOSurfacePurgeableNonVolatile"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "kIOSurfacePurgeableNonVolatile"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePurgeableNonVolatile"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iosurface/documentation/IOSurface": {
      "abstract": [
        {
          "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface",
      "kind": "symbol",
      "role": "collection",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfacePurgeabilityState"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePurgeabilityState"
        }
      ],
      "role": "symbol",
      "title": "IOSurfacePurgeabilityState",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepurgeabilitystate"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState/kIOSurfacePurgeableNonVolatile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePurgeableNonVolatile"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState/kIOSurfacePurgeableNonVolatile",
      "kind": "symbol",
      "role": "symbol",
      "title": "kIOSurfacePurgeableNonVolatile",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepurgeabilitystate/kiosurfacepurgeablenonvolatile"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState/title",
          "value": "IOSurfacePurgeabilityState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePurgeabilityState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePurgeabilityState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iosurface/iosurfacepurgeabilitystate/kiosurfacepurgeablenonvolatile"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
