{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iosurface/documentation/IOSurface",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState/purgeableVolatile"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@IOSurfacePurgeabilityState@kIOSurfacePurgeableVolatile",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "purgeableVolatile"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@IOSurfacePurgeabilityState",
        "text": "IOSurfacePurgeabilityState"
      }
    ],
    "modules": [
      {
        "name": "IOSurface"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kIOSurfacePurgeableVolatile"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "purgeableVolatile"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "purgeableVolatile"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@IOSurfacePurgeabilityState",
              "text": "IOSurfacePurgeabilityState"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iosurface/documentation/IOSurface": {
      "abstract": [
        {
          "text": "Share hardware-accelerated buffer data (framebuffers and textures) across multiple processes. Manage image memory more efficiently.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface",
      "kind": "symbol",
      "role": "collection",
      "title": "IOSurface",
      "type": "topic",
      "url": "/documentation/iosurface"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOSurfacePurgeabilityState"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOSurfacePurgeabilityState"
        }
      ],
      "role": "symbol",
      "title": "IOSurfacePurgeabilityState",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepurgeabilitystate"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState/purgeableEmpty": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purgeableEmpty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOSurfacePurgeabilityState",
          "text": "IOSurfacePurgeabilityState"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState/purgeableEmpty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePurgeableEmpty"
        }
      ],
      "role": "symbol",
      "title": "purgeableEmpty",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepurgeabilitystate/purgeableempty"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState/purgeableKeepCurrent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purgeableKeepCurrent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOSurfacePurgeabilityState",
          "text": "IOSurfacePurgeabilityState"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState/purgeableKeepCurrent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePurgeableKeepCurrent"
        }
      ],
      "role": "symbol",
      "title": "purgeableKeepCurrent",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepurgeabilitystate/purgeablekeepcurrent"
    },
    "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState/purgeableVolatile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purgeableVolatile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOSurfacePurgeabilityState",
          "text": "IOSurfacePurgeabilityState"
        }
      ],
      "identifier": "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState/purgeableVolatile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOSurfacePurgeableVolatile"
        }
      ],
      "role": "symbol",
      "title": "purgeableVolatile",
      "type": "topic",
      "url": "/documentation/iosurface/iosurfacepurgeabilitystate/purgeablevolatile"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState/purgeableEmpty",
        "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState/purgeableKeepCurrent"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kIOSurfacePurgeableVolatile"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePurgeableVolatile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iosurface/documentation/IOSurface",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState/purgeableEmpty",
                "doc://com.apple.iosurface/documentation/IOSurface/IOSurfacePurgeabilityState/purgeableKeepCurrent"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kIOSurfacePurgeableVolatile"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState~1purgeableVolatile/title",
          "value": "kIOSurfacePurgeableVolatile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState~1purgeableVolatile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePurgeableVolatile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState~1purgeableEmpty/title",
          "value": "kIOSurfacePurgeableEmpty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState~1purgeableEmpty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePurgeableEmpty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState~1purgeableKeepCurrent/title",
          "value": "kIOSurfacePurgeableKeepCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState~1purgeableKeepCurrent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOSurfacePurgeableKeepCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState/title",
          "value": "IOSurfacePurgeabilityState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePurgeabilityState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iosurface~1documentation~1IOSurface~1IOSurfacePurgeabilityState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOSurfacePurgeabilityState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iosurface/iosurfacepurgeabilitystate/purgeablevolatile"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iosurface/iosurfacepurgeabilitystate/purgeablevolatile"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
