{
  "abstract": [
    {
      "text": "The mode that indicates whether the layer produces a single result tensor or three result tensors — final output, last hidden state, and the cell state.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/resultMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCLSTMDescriptor(py)resultMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "resultMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MLCLSTMResultMode",
        "text": "MLCLSTMResultMode"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "resultMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "resultMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "resultMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMResultMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MLCLSTMResultMode",
              "text": "MLCLSTMResultMode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor": {
      "abstract": [
        {
          "text": "The configuration object you use to create the LSTM layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLSTMDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLSTMDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCLSTMDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmdescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/batchFirst": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the input and output shape is batch first.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "batchFirst"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/batchFirst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "batchFirst"
        }
      ],
      "role": "symbol",
      "title": "batchFirst",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmdescriptor/batchfirst"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/dropout": {
      "abstract": [
        {
          "text": "The dropout probability.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dropout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/dropout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropout"
        }
      ],
      "role": "symbol",
      "title": "dropout",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmdescriptor/dropout"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/hiddenSize": {
      "abstract": [
        {
          "text": "The number of features in the hidden state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hiddenSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/hiddenSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hiddenSize"
        }
      ],
      "role": "symbol",
      "title": "hiddenSize",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmdescriptor/hiddensize"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/inputSize": {
      "abstract": [
        {
          "text": "The number of expected features in the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/inputSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputSize"
        }
      ],
      "role": "symbol",
      "title": "inputSize",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmdescriptor/inputsize"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/isBidirectional": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the layer is bidirectional.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isBidirectional"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/isBidirectional",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isBidirectional"
        }
      ],
      "role": "symbol",
      "title": "isBidirectional",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmdescriptor/isbidirectional"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/layerCount": {
      "abstract": [
        {
          "text": "The number of recurrent layers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/layerCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerCount"
        }
      ],
      "role": "symbol",
      "title": "layerCount",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmdescriptor/layercount"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/resultMode": {
      "abstract": [
        {
          "text": "The mode that indicates whether the layer produces a single result tensor or three result tensors — final output, last hidden state, and the cell state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resultMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLCLSTMResultMode",
          "text": "MLCLSTMResultMode"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/resultMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resultMode"
        }
      ],
      "role": "symbol",
      "title": "resultMode",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmdescriptor/resultmode"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/returnsSequences": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the layer returns output for all sequences.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "returnsSequences"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/returnsSequences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "returnsSequences"
        }
      ],
      "role": "symbol",
      "title": "returnsSequences",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmdescriptor/returnssequences"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/usesBiases": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether you use bias weights.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usesBiases"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/usesBiases",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usesBiases"
        }
      ],
      "role": "symbol",
      "title": "usesBiases",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmdescriptor/usesbiases"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMResultMode": {
      "abstract": [
        {
          "text": "Constants that describe the result of an LSTM layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCLSTMResultMode"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMResultMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCLSTMResultMode"
        }
      ],
      "role": "symbol",
      "title": "MLCLSTMResultMode",
      "type": "topic",
      "url": "/documentation/mlcompute/mlclstmresultmode"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-LSTM-Descriptors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/batchFirst",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/dropout",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/hiddenSize",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/inputSize",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/isBidirectional",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/layerCount",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/returnsSequences",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/usesBiases"
      ],
      "title": "Inspecting LSTM Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.3",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "resultMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resultMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-LSTM-Descriptors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/batchFirst",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/dropout",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/hiddenSize",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/inputSize",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/isBidirectional",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/layerCount",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/returnsSequences",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMDescriptor/usesBiases"
              ],
              "title": "Inspecting LSTM Descriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCLSTMResultMode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MLCLSTMResultMode",
                    "text": "MLCLSTMResultMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "resultMode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMResultMode/title",
          "value": "MLCLSTMResultMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMResultMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLSTMResultMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMResultMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLSTMResultMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1layerCount/title",
          "value": "layerCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1layerCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layerCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1returnsSequences/title",
          "value": "returnsSequences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1returnsSequences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "returnsSequences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1usesBiases/title",
          "value": "usesBiases"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1usesBiases/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usesBiases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1batchFirst/title",
          "value": "batchFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1batchFirst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "batchFirst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1resultMode/title",
          "value": "resultMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1resultMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resultMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1hiddenSize/title",
          "value": "hiddenSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1hiddenSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hiddenSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor/title",
          "value": "MLCLSTMDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLSTMDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCLSTMDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1inputSize/title",
          "value": "inputSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1inputSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1dropout/title",
          "value": "dropout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1dropout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dropout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1isBidirectional/title",
          "value": "isBidirectional"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCLSTMDescriptor~1isBidirectional/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isBidirectional"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlclstmdescriptor/resultmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlclstmdescriptor/resultmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
