{
  "abstract": [
    {
      "text": "The image data for this sample.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.RealityKit/documentation/RealityKit",
        "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample/image"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:17RealityFoundation20PhotogrammetrySampleV5imageSo11CVBufferRefavp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "image"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CVPixelBufferRef",
        "text": "CVPixelBuffer"
      }
    ],
    "modules": [
      {
        "name": "RealityKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "image"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "image"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CVPixelBufferRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVPixelBufferRef",
              "text": "CVPixelBuffer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Provide image data in the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreVideo/kCVPixelFormatType_32BGRA",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreVideo/kCVPixelFormatType_32ARGB",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "pixel formats.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.RealityKit/documentation/RealityKit": {
      "abstract": [
        {
          "text": "Simulate and render 3D content for use in your augmented reality apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit",
      "kind": "symbol",
      "role": "collection",
      "title": "RealityKit",
      "type": "topic",
      "url": "/documentation/realitykit"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample": {
      "abstract": [
        {
          "text": "An object that represents one image and its corresponding metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PhotogrammetrySample"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PhotogrammetrySample"
        }
      ],
      "role": "symbol",
      "title": "PhotogrammetrySample",
      "type": "topic",
      "url": "/documentation/realitykit/photogrammetrysample"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample/depthDataMap": {
      "abstract": [
        {
          "text": "The image’s depth data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depthDataMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample/depthDataMap",
      "kind": "symbol",
      "role": "symbol",
      "title": "depthDataMap",
      "type": "topic",
      "url": "/documentation/realitykit/photogrammetrysample/depthdatamap"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample/gravity": {
      "abstract": [
        {
          "text": "An image’s gravity vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gravity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMAcceleration",
          "text": "CMAcceleration"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample/gravity",
      "kind": "symbol",
      "role": "symbol",
      "title": "gravity",
      "type": "topic",
      "url": "/documentation/realitykit/photogrammetrysample/gravity"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample/image": {
      "abstract": [
        {
          "text": "The image data for this sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample/image",
      "kind": "symbol",
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/realitykit/photogrammetrysample/image"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample/metadata": {
      "abstract": [
        {
          "text": "An image’s EXIF metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample/metadata",
      "kind": "symbol",
      "role": "symbol",
      "title": "metadata",
      "type": "topic",
      "url": "/documentation/realitykit/photogrammetrysample/metadata"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample/objectMask": {
      "abstract": [
        {
          "text": "The image’s object mask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample/objectMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "objectMask",
      "type": "topic",
      "url": "/documentation/realitykit/photogrammetrysample/objectmask"
    },
    "doc://com.apple.documentation/documentation/CoreVideo/kCVPixelFormatType_32ARGB": {
      "abstract": [
        {
          "text": "32-bit ARGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_32ARGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreVideo/kCVPixelFormatType_32ARGB",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCVPixelFormatType_32ARGB",
      "type": "topic",
      "url": "/documentation/CoreVideo/kCVPixelFormatType_32ARGB"
    },
    "doc://com.apple.documentation/documentation/CoreVideo/kCVPixelFormatType_32BGRA": {
      "abstract": [
        {
          "text": "32-bit BGRA.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelFormatType_32BGRA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreVideo/kCVPixelFormatType_32BGRA",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCVPixelFormatType_32BGRA",
      "type": "topic",
      "url": "/documentation/CoreVideo/kCVPixelFormatType_32BGRA"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CVPixelBufferRef": {
      "abstract": [
        {
          "text": "A reference to a Core Video pixel buffer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CVPixelBufferRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVPixelBuffer",
      "type": "topic",
      "url": "/documentation/CoreVideo/CVPixelBuffer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Describing-the-sample",
      "generated": true,
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample/metadata",
        "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample/depthDataMap",
        "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample/gravity",
        "doc://com.apple.RealityKit/documentation/RealityKit/PhotogrammetrySample/objectMask"
      ],
      "title": "Describing the sample"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreVideo~1kCVPixelFormatType_32BGRA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_32BGRA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreVideo~1kCVPixelFormatType_32ARGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCVPixelFormatType_32ARGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CVPixelBufferRef/title",
          "value": "CVPixelBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CVPixelBufferRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CVImageBufferRef",
              "text": "CVImageBufferRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CVPixelBufferRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/realitykit/photogrammetrysample/image"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
