{
  "abstract": [
    {
      "text": "Values that indicate the orientation of user interface elements, such as scroll bars and split views.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@T@NSAccessibilityOrientationValue",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OrientationValue"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OrientationValue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSAccessibility.OrientationValue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OrientationValue"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct": {
      "abstract": [
        {
          "text": "A namespace for accessibility symbols for AppKit apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibility"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibility"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Action": {
      "abstract": [
        {
          "text": "Constants that describe types of actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Action"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Action",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Action"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.Action",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/action"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/AnnotationAttributeKey": {
      "abstract": [
        {
          "text": "Keys for annotation attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnnotationAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/AnnotationAttributeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnnotationAttributeKey"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.AnnotationAttributeKey",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/annotationattributekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute": {
      "abstract": [
        {
          "text": "Constants that describe attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Attribute"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.Attribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/attribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey": {
      "abstract": [
        {
          "text": "Keys for font attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FontAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FontAttributeKey"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.FontAttributeKey",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/fontattributekey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue": {
      "abstract": [
        {
          "text": "Values that indicate the orientation of user interface elements, such as scroll bars and split views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OrientationValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OrientationValue"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.OrientationValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/orientationvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/horizontal": {
      "abstract": [
        {
          "text": "The element is oriented horizontally.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityOrientationValue",
          "text": "OrientationValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/horizontal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityHorizontalOrientationValue"
        }
      ],
      "role": "symbol",
      "title": "horizontal",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/orientationvalue/horizontal"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/orientationvalue/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/unknown": {
      "abstract": [
        {
          "text": "The element has unknown orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityOrientationValue",
          "text": "OrientationValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnknownOrientationValue"
        }
      ],
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/orientationvalue/unknown"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/vertical": {
      "abstract": [
        {
          "text": "The element is oriented vertically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityOrientationValue",
          "text": "OrientationValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/vertical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityVerticalOrientationValue"
        }
      ],
      "role": "symbol",
      "title": "vertical",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/orientationvalue/vertical"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute": {
      "abstract": [
        {
          "text": "Values that describe parameterized attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ParameterizedAttribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ParameterizedAttribute"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.ParameterizedAttribute",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/parameterizedattribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Role": {
      "abstract": [
        {
          "text": "Values that describe types of objects that accessibility elements represent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Role"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Role",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Role"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.Role",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/role"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue": {
      "abstract": [
        {
          "text": "Values that describe ruler marker types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RulerMarkerTypeValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RulerMarkerTypeValue"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.RulerMarkerTypeValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/rulermarkertypevalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerUnitValue": {
      "abstract": [
        {
          "text": "Values that indicate the unit values of a ruler or layout area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RulerUnitValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerUnitValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RulerUnitValue"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.RulerUnitValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/rulerunitvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/SortDirectionValue": {
      "abstract": [
        {
          "text": "Values that indicate the sort direction of a column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SortDirectionValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/SortDirectionValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SortDirectionValue"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.SortDirectionValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/sortdirectionvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole": {
      "abstract": [
        {
          "text": "Values that describe specialized object subtypes that accessibility elements represent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Subrole"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Subrole"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.Subrole",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/subrole"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAnnotationPosition": {
      "abstract": [
        {
          "text": "Constants that specify the position where the annotation applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityAnnotationPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAnnotationPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityAnnotationPosition"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityAnnotationPosition",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityannotationposition"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOrientation": {
      "abstract": [
        {
          "text": "Values that indicate the orientation of accessibility elements, such as scroll bars and split views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityOrientation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityOrientation"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityOrientation",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityorientation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType": {
      "abstract": [
        {
          "text": "Values that indicate the marker type of an accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityRulerMarkerType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRulerMarkerType"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityRulerMarkerType",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityrulermarkertype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySortDirection": {
      "abstract": [
        {
          "text": "Values that indicate the sort direction of a column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilitySortDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySortDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilitySortDirection"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilitySortDirection",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitysortdirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnits": {
      "abstract": [
        {
          "text": "Values that indicate the unit values of a ruler or layout area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnits"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnits"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityUnits",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilityunits"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessibility-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Action",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/AnnotationAttributeKey",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAnnotationPosition",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOrientation",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Role",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerUnitValue",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/SortDirectionValue",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySortDirection",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnits"
      ],
      "title": "Accessibility Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Orientations",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/horizontal",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/vertical",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/unknown"
      ],
      "title": "Orientations"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSAccessibilityOrientationValue"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityOrientationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityOrientationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Orientations",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/horizontal",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/vertical",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/OrientationValue/unknown"
              ],
              "title": "Orientations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessibility-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Action",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/AnnotationAttributeKey",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityAnnotationPosition",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Attribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/FontAttributeKey",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityOrientation",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/ParameterizedAttribute",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Role",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRulerMarkerType",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerUnitValue",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/SortDirectionValue",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilitySortDirection",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Subrole",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityUnits"
              ],
              "title": "Accessibility Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSAccessibilityOrientationValue"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue/title",
          "value": "NSAccessibilityRulerMarkerTypeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerTypeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerTypeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityUnits/title",
          "value": "NSAccessibilityUnits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityUnits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityUnits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityUnits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityUnits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerUnitValue/title",
          "value": "NSAccessibilityRulerUnitValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerUnitValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerUnitValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerUnitValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerUnitValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey/title",
          "value": "NSAccessibilityFontAttributeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFontAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1FontAttributeKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFontAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1AnnotationAttributeKey/title",
          "value": "NSAccessibilityAnnotationAttributeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1AnnotationAttributeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityAnnotationAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1AnnotationAttributeKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityAnnotationAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue~1vertical/title",
          "value": "NSAccessibilityVerticalOrientationValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue~1vertical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityVerticalOrientationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue~1unknown/title",
          "value": "NSAccessibilityUnknownOrientationValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityUnknownOrientationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityAnnotationPosition/title",
          "value": "NSAccessibilityAnnotationPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityAnnotationPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityAnnotationPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityAnnotationPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityAnnotationPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue/title",
          "value": "NSAccessibilityOrientationValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityOrientationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityOrientationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute/title",
          "value": "NSAccessibilityAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Attribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Action/title",
          "value": "NSAccessibilityActionName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Action/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityActionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Action/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityActionName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole/title",
          "value": "NSAccessibilitySubrole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Subrole/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySubrole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilitySortDirection/title",
          "value": "NSAccessibilitySortDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilitySortDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySortDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilitySortDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySortDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType/title",
          "value": "NSAccessibilityRulerMarkerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRulerMarkerType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1SortDirectionValue/title",
          "value": "NSAccessibilitySortDirectionValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1SortDirectionValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySortDirectionValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1SortDirectionValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilitySortDirectionValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Role/title",
          "value": "NSAccessibilityRole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Role/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Role/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute/title",
          "value": "NSAccessibilityParameterizedAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityParameterizedAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1ParameterizedAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityParameterizedAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue~1horizontal/title",
          "value": "NSAccessibilityHorizontalOrientationValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1OrientationValue~1horizontal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityHorizontalOrientationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityOrientation/title",
          "value": "NSAccessibilityOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityOrientation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibility-swift.struct/orientationvalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsaccessibility-swift.struct/orientationvalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
