{
  "abstract": [
    {
      "text": "IEEE 802.11n PHY.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11n"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CWPHYMode@kCWPHYMode11n",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mode11n"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCWPHYMode11n"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CWPHYMode.mode11n"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mode11n"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode": {
      "abstract": [
        {
          "text": "CoreWLAN physical layer modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWPHYMode"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWPHYMode"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11a": {
      "abstract": [
        {
          "text": "IEEE 802.11a PHY.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode11a"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11a",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWPHYMode11a"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode.mode11a",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode/mode11a"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11ac": {
      "abstract": [
        {
          "text": "IEEE 802.11ac PHY.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode11ac"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11ac",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWPHYMode11ac"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode.mode11ac",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode/mode11ac"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11b": {
      "abstract": [
        {
          "text": "IEEE 802.11b PHY.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode11b"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11b",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWPHYMode11b"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode.mode11b",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode/mode11b"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11g": {
      "abstract": [
        {
          "text": "IEEE 802.11g PHY.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode11g"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11g",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWPHYMode11g"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode.mode11g",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode/mode11g"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11n": {
      "abstract": [
        {
          "text": "IEEE 802.11n PHY.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode11n"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11n",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWPHYMode11n"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode.mode11n",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode/mode11n"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/modeNone": {
      "abstract": [
        {
          "text": "No specified mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modeNone"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/modeNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWPHYModeNone"
        }
      ],
      "role": "symbol",
      "title": "CWPHYMode.modeNone",
      "type": "topic",
      "url": "/documentation/corewlan/cwphymode/modenone"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/modeNone",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11a",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11b",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11g",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11ac"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCWPHYMode11n"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWPHYMode11n"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/modeNone",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11a",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11b",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11g",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWPHYMode/mode11ac"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCWPHYMode11n"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11g/title",
          "value": "kCWPHYMode11g"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11g/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWPHYMode11g"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1modeNone/title",
          "value": "kCWPHYModeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1modeNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWPHYModeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode/title",
          "value": "CWPHYMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWPHYMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWPHYMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11a/title",
          "value": "kCWPHYMode11a"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11a/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWPHYMode11a"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11b/title",
          "value": "kCWPHYMode11b"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11b/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWPHYMode11b"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11ac/title",
          "value": "kCWPHYMode11ac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11ac/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWPHYMode11ac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11n/title",
          "value": "kCWPHYMode11n"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWPHYMode~1mode11n/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWPHYMode11n"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cwphymode/mode11n"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cwphymode/mode11n"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
