{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/customPlacementConstraints"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSGridCell(py)customPlacementConstraints",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "customPlacementConstraints"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
        "text": "NSLayoutConstraint"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "customPlacementConstraints"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "customPlacementConstraints"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "customPlacementConstraints"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
              "text": "NSLayoutConstraint"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell": {
      "abstract": [
        {
          "text": "An individual content area within a grid view, typically at the intersection of a row and a column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGridCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCell"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Placement"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell.Placement",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/customPlacementConstraints": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customPlacementConstraints"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/customPlacementConstraints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customPlacementConstraints"
        }
      ],
      "role": "symbol",
      "title": "customPlacementConstraints",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/customplacementconstraints"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/rowAlignment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridRow",
          "text": "NSGridRow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGridRowAlignment",
          "text": "Alignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/rowAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowAlignment"
        }
      ],
      "role": "symbol",
      "title": "rowAlignment",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/rowalignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/xPlacement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xPlacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridCell",
          "text": "NSGridCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGridCellPlacement",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/xPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xPlacement"
        }
      ],
      "role": "symbol",
      "title": "xPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/xplacement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/yPlacement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yPlacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridCell",
          "text": "NSGridCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGridCellPlacement",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/yPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "yPlacement"
        }
      ],
      "role": "symbol",
      "title": "yPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/yplacement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint": {
      "abstract": [
        {
          "text": "The relationship between two user interface objects that must be satisfied by the constraint-based layout system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutConstraint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutConstraint"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Formatting-the-Cell",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/rowAlignment",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/xPlacement",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/yPlacement",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement"
      ],
      "title": "Formatting the Cell"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "customPlacementConstraints"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "customPlacementConstraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Formatting-the-Cell",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/rowAlignment",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/xPlacement",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/yPlacement",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement"
              ],
              "title": "Formatting the Cell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSLayoutConstraint *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "customPlacementConstraints"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell/title",
          "value": "NSGridCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1rowAlignment/title",
          "value": "rowAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1rowAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rowAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1xPlacement/title",
          "value": "xPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1xPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint/title",
          "value": "NSLayoutConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement/title",
          "value": "NSGridCellPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1yPlacement/title",
          "value": "yPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1yPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "yPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1customPlacementConstraints/title",
          "value": "customPlacementConstraints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1customPlacementConstraints/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "customPlacementConstraints"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsgridcell/customplacementconstraints"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsgridcell/customplacementconstraints"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
