{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSGridCellPlacement",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Placement"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Placement"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSGridCell.Placement"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Placement"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell": {
      "abstract": [
        {
          "text": "An individual content area within a grid view, typically at the intersection of a row and a column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSGridCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCell"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Placement"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell.Placement",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/bottom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridCell",
          "text": "NSGridCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGridCellPlacement",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementBottom"
        }
      ],
      "role": "symbol",
      "title": "bottom",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/bottom"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/center": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementCenter"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell.Placement.center",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/center"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/fill": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fill"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/fill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementFill"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell.Placement.fill",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/fill"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/inherited": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inherited"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/inherited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementInherited"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell.Placement.inherited",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/inherited"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/leading": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/leading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementLeading"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell.Placement.leading",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/leading"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/none": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementNone"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell.Placement.none",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/none"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/top": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridCell",
          "text": "NSGridCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGridCellPlacement",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementTop"
        }
      ],
      "role": "symbol",
      "title": "top",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/top"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/trailing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailing"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/trailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSGridCellPlacementTrailing"
        }
      ],
      "role": "symbol",
      "title": "NSGridCell.Placement.trailing",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/placement/trailing"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/customPlacementConstraints": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customPlacementConstraints"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/customPlacementConstraints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customPlacementConstraints"
        }
      ],
      "role": "symbol",
      "title": "customPlacementConstraints",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/customplacementconstraints"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/rowAlignment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridRow",
          "text": "NSGridRow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGridRowAlignment",
          "text": "Alignment"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/rowAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowAlignment"
        }
      ],
      "role": "symbol",
      "title": "rowAlignment",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/rowalignment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/xPlacement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xPlacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridCell",
          "text": "NSGridCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGridCellPlacement",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/xPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "xPlacement"
        }
      ],
      "role": "symbol",
      "title": "xPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/xplacement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSGridCell/yPlacement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yPlacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSGridCell",
          "text": "NSGridCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGridCellPlacement",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSGridCell/yPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "yPlacement"
        }
      ],
      "role": "symbol",
      "title": "yPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nsgridcell/yplacement"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Formatting-the-Cell",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/customPlacementConstraints",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/rowAlignment",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/xPlacement",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/yPlacement"
      ],
      "title": "Formatting the Cell"
    }
  ],
  "topicSections": [
    {
      "anchor": "Placement-Options",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/top",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/bottom",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/center",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/fill",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/inherited",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/leading",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/none",
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/trailing"
      ],
      "title": "Placement Options"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSGridCellPlacement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Placement-Options",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/top",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/bottom",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/center",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/fill",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/inherited",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/leading",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/none",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/Placement/trailing"
              ],
              "title": "Placement Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Formatting-the-Cell",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/customPlacementConstraints",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/rowAlignment",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/xPlacement",
                "doc://com.apple.appkit/documentation/AppKit/NSGridCell/yPlacement"
              ],
              "title": "Formatting the Cell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSGridCellPlacement"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1none/title",
          "value": "NSGridCellPlacementNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1yPlacement/title",
          "value": "yPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1yPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "yPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell/title",
          "value": "NSGridCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1inherited/title",
          "value": "NSGridCellPlacementInherited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1inherited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementInherited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1customPlacementConstraints/title",
          "value": "customPlacementConstraints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1customPlacementConstraints/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "customPlacementConstraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1trailing/title",
          "value": "NSGridCellPlacementTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1trailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement/title",
          "value": "NSGridCellPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1fill/title",
          "value": "NSGridCellPlacementFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1fill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementFill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1top/title",
          "value": "NSGridCellPlacementTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1rowAlignment/title",
          "value": "rowAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1rowAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rowAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1leading/title",
          "value": "NSGridCellPlacementLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1leading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1bottom/title",
          "value": "NSGridCellPlacementBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1center/title",
          "value": "NSGridCellPlacementCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1Placement~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGridCellPlacementCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1xPlacement/title",
          "value": "xPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSGridCell~1xPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "xPlacement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsgridcell/placement"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsgridcell/placement"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
