{"abstract":[{"text":"Tells the delegate when the recognition of all requested utterances is finished.","type":"text"}],"identifier":{"url":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate/speechRecognitionTask(_:didFinishSuccessfully:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"speechRecognitionTask","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"task","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SFSpeechRecognitionTask","identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask","preciseIdentifier":"c:objc(cs)SFSpeechRecognitionTask","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishSuccessfully","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"successfully","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}]},{"kind":"parameters","parameters":[{"name":"task","content":[{"inlineContent":[{"type":"text","text":"The speech recognition task (an "},{"type":"reference","identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask","isActive":true},{"type":"text","text":" object) that represents the request."}],"type":"paragraph"}]},{"name":"successfully","content":[{"inlineContent":[{"type":"text","text":"A Boolean value that indicates whether the task was successful. When this parameter is "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/nsexpression/1416488-false"},{"type":"text","text":", use the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask/error"},{"type":"text","text":" property of the task to get information about why the task was unsuccessful."}],"type":"paragraph"}]}]}],"sections":[],"metadata":{"roleHeading":"Instance Method","platforms":[{"name":"iOS","unavailable":false,"introducedAt":"10.0","beta":false,"deprecated":false},{"name":"iPadOS","unavailable":false,"introducedAt":"10.0","beta":false,"deprecated":false},{"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1","beta":false,"deprecated":false},{"name":"macOS","unavailable":false,"introducedAt":"10.15","beta":false,"deprecated":false},{"name":"visionOS","unavailable":false,"introducedAt":"1.0","beta":false,"deprecated":false}],"modules":[{"name":"Speech"}],"role":"symbol","externalID":"c:objc(pl)SFSpeechRecognitionTaskDelegate(im)speechRecognitionTask:didFinishSuccessfully:","navigatorTitle":[{"kind":"identifier","text":"speechRecognitionTask:didFinishSuccessfully:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"speechRecognitionTask"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SFSpeechRecognitionTask","preciseIdentifier":"c:objc(cs)SFSpeechRecognitionTask"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishSuccessfully"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"speechRecognitionTask(_:didFinishSuccessfully:)","symbolKind":"method"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.speech/documentation/Speech","doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/speech/sfspeechrecognitiontaskdelegate/speechrecognitiontask(_:didfinishsuccessfully:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/speech/sfspeechrecognitiontaskdelegate/speechrecognitiontask(_:didfinishsuccessfully:)"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate/speechRecognitionTask(_:didFinishRecognition:)","doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate/speechRecognitionTaskWasCancelled(_:)"],"anchor":"Finishing-a-Speech-Recognition-Task","title":"Finishing a Speech Recognition Task"}],"references":{"doc://com.apple.speech/documentation/Speech":{"title":"Speech","kind":"symbol","identifier":"doc://com.apple.speech/documentation/Speech","type":"topic","role":"collection","abstract":[{"text":"Perform speech recognition on live or prerecorded audio, and receive transcriptions, alternative interpretations, and confidence levels of the results.","type":"text"}],"url":"/documentation/speech"},"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate/speechRecognitionTask(_:didFinishSuccessfully:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"speechRecognitionTask","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SFSpeechRecognitionTask","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSpeechRecognitionTask"},{"text":", ","kind":"text"},{"text":"didFinishSuccessfully","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"speechRecognitionTask:didFinishSuccessfully:"}],"title":"speechRecognitionTask(_:didFinishSuccessfully:)","identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate/speechRecognitionTask(_:didFinishSuccessfully:)","url":"/documentation/speech/sfspeechrecognitiontaskdelegate/speechrecognitiontask(_:didfinishsuccessfully:)","type":"topic","abstract":[{"text":"Tells the delegate when the recognition of all requested utterances is finished.","type":"text"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/foundation/nsexpression/1416488-false":{"identifier":"doc://com.apple.documentation/documentation/foundation/nsexpression/1416488-false","fragments":[{"text":"var ","kind":"text"},{"text":"`false`","kind":"identifier"},{"text":": NSExpression","kind":"text"}],"kind":"symbol","url":"/documentation/foundation/nsexpression/1416488-false","type":"topic","abstract":[{"text":"An expression to evalutate if a conditional expression’s predicate evaluates to false.","type":"text"}],"role":"symbol","title":"false"},"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate":{"identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SFSpeechRecognitionTaskDelegate"}],"title":"SFSpeechRecognitionTaskDelegate","abstract":[{"type":"text","text":"A protocol with methods for managing multi-utterance speech recognition requests."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SFSpeechRecognitionTaskDelegate"}],"url":"/documentation/speech/sfspeechrecognitiontaskdelegate","type":"topic"},"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SFSpeechRecognitionTask"}],"navigatorTitle":[{"kind":"identifier","text":"SFSpeechRecognitionTask"}],"type":"topic","abstract":[{"text":"A task object for monitoring the speech recognition progress.","type":"text"}],"url":"/documentation/speech/sfspeechrecognitiontask","role":"symbol","title":"SFSpeechRecognitionTask","identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask"},"doc://com.externally.resolved.symbol/s:Sb":{"kind":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"url":"/documentation/Swift/Bool","role":"symbol","title":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview","abstract":[{"text":"","type":"text"}],"url":"/documentation/technologies"},"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask/error":{"type":"topic","navigatorTitle":[{"text":"error","kind":"identifier"}],"abstract":[{"text":"An error object that specifies the error that occurred during a speech recognition task.","type":"text"}],"title":"error","role":"symbol","kind":"symbol","url":"/documentation/speech/sfspeechrecognitiontask/error","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?","kind":"text"}],"identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask/error"},"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate/speechRecognitionTaskWasCancelled(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"speechRecognitionTaskWasCancelled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SFSpeechRecognitionTask","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSpeechRecognitionTask"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"speechRecognitionTaskWasCancelled:","kind":"identifier"}],"title":"speechRecognitionTaskWasCancelled(_:)","identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate/speechRecognitionTaskWasCancelled(_:)","url":"/documentation/speech/sfspeechrecognitiontaskdelegate/speechrecognitiontaskwascancelled(_:)","type":"topic","abstract":[{"text":"Tells the delegate that the task has been canceled.","type":"text"}],"kind":"symbol"},"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate/speechRecognitionTask(_:didFinishRecognition:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"speechRecognitionTask","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SFSpeechRecognitionTask","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSpeechRecognitionTask"},{"text":", ","kind":"text"},{"text":"didFinishRecognition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SFSpeechRecognitionResult","preciseIdentifier":"c:objc(cs)SFSpeechRecognitionResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"speechRecognitionTask:didFinishRecognition:","kind":"identifier"}],"title":"speechRecognitionTask(_:didFinishRecognition:)","identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate/speechRecognitionTask(_:didFinishRecognition:)","url":"/documentation/speech/sfspeechrecognitiontaskdelegate/speechrecognitiontask(_:didfinishrecognition:)","type":"topic","abstract":[{"text":"Tells the delegate when the final utterance is recognized.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"10.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"10.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.15"},{"deprecated":false,"introducedAt":"1.0","unavailable":false,"name":"visionOS","beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"speechRecognitionTask:didFinishSuccessfully:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"speechRecognitionTask:didFinishSuccessfully:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.speech/documentation/Speech","doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"anchor":"Finishing-a-Speech-Recognition-Task","title":"Finishing a Speech Recognition Task","identifiers":["doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate/speechRecognitionTask(_:didFinishRecognition:)","doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate/speechRecognitionTaskWasCancelled(_:)"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"speechRecognitionTask:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)SFSpeechRecognitionTask","kind":"typeIdentifier","identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask","text":"SFSpeechRecognitionTask"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"task"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishSuccessfully:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"successfully"},{"kind":"text","text":";"}]}]}},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"task","content":[{"inlineContent":[{"text":"The speech recognition task (an ","type":"text"},{"identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask","isActive":true,"type":"reference"},{"text":" object) that represents the request.","type":"text"}],"type":"paragraph"}]},{"name":"successfully","content":[{"inlineContent":[{"text":"A Boolean value that indicates whether the task was successful. When this parameter is ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/nsexpression/1416488-false"},{"text":", use the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask/error"},{"text":" property of the task to get information about why the task was unsuccessful.","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskDelegate~1speechRecognitionTask(_:didFinishSuccessfully:)/title","op":"replace","value":"speechRecognitionTask:didFinishSuccessfully:"},{"path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskDelegate~1speechRecognitionTask(_:didFinishSuccessfully:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"speechRecognitionTask:didFinishSuccessfully:"}]},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsexpression~11416488-false/title","op":"replace","value":"falseExpression"},{"path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskDelegate/title","op":"replace","value":"SFSpeechRecognitionTaskDelegate"},{"path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskDelegate/fragments","op":"replace","value":[{"text":"SFSpeechRecognitionTaskDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskDelegate/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SFSpeechRecognitionTaskDelegate"}]},{"path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTask/title","op":"replace","value":"SFSpeechRecognitionTask"},{"path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTask/fragments","op":"replace","value":[{"kind":"identifier","text":"SFSpeechRecognitionTask"}]},{"path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTask/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SFSpeechRecognitionTask"}]},{"path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTask~1error/title","op":"replace","value":"error"},{"path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTask~1error/fragments","op":"replace","value":[{"text":"error","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskDelegate~1speechRecognitionTaskWasCancelled(_:)/title","op":"replace","value":"speechRecognitionTaskWasCancelled:"},{"path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskDelegate~1speechRecognitionTaskWasCancelled(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"speechRecognitionTaskWasCancelled:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskDelegate~1speechRecognitionTask(_:didFinishRecognition:)/title","op":"replace","value":"speechRecognitionTask:didFinishRecognition:"},{"path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskDelegate~1speechRecognitionTask(_:didFinishRecognition:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"speechRecognitionTask:didFinishRecognition:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}