{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.speech/documentation/Speech","doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/speech/sfspeechrecognitiontaskdelegate/speechrecognitiontask(_:didhypothesizetranscription:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/speech/sfspeechrecognitiontaskdelegate/speechrecognitiontask(_:didhypothesizetranscription:)"]}],"abstract":[{"text":"Tells the delegate that a hypothesized transcription is available.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate/speechRecognitionTask(_:didHypothesizeTranscription:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"speechRecognitionTask"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"task","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SFSpeechRecognitionTask","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSpeechRecognitionTask","identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask"},{"text":", ","kind":"text"},{"text":"didHypothesizeTranscription","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"transcription","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SFTranscription","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFTranscription","identifier":"doc://com.apple.speech/documentation/Speech/SFTranscription"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The speech recognition task (an ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask","type":"reference"},{"text":" object) that represents the request.","type":"text"}],"type":"paragraph"}],"name":"task"},{"content":[{"inlineContent":[{"type":"text","text":"The hypothesized transcription in an "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.speech/documentation/Speech/SFTranscription"},{"type":"text","text":" object."}],"type":"paragraph"}],"name":"transcription"}],"kind":"parameters"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"inlineContent":[{"text":"This method is called for all recognitions, including partial recognitions.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"roleHeading":"Instance Method","platforms":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"10.0","unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"10.0","unavailable":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.1","unavailable":false},{"name":"macOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"10.15"},{"name":"visionOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"1.0"}],"title":"speechRecognitionTask(_:didHypothesizeTranscription:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"speechRecognitionTask"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SFSpeechRecognitionTask","preciseIdentifier":"c:objc(cs)SFSpeechRecognitionTask"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didHypothesizeTranscription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SFTranscription","preciseIdentifier":"c:objc(cs)SFTranscription"},{"text":")","kind":"text"}],"modules":[{"name":"Speech"}],"navigatorTitle":[{"text":"speechRecognitionTask:didHypothesizeTranscription:","kind":"identifier"}],"role":"symbol","externalID":"c:objc(pl)SFSpeechRecognitionTaskDelegate(im)speechRecognitionTask:didHypothesizeTranscription:","symbolKind":"method"},"references":{"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview","abstract":[{"text":"","type":"text"}],"url":"/documentation/technologies"},"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate/speechRecognitionTask(_:didHypothesizeTranscription:)":{"navigatorTitle":[{"text":"speechRecognitionTask:didHypothesizeTranscription:","kind":"identifier"}],"identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate/speechRecognitionTask(_:didHypothesizeTranscription:)","url":"/documentation/speech/sfspeechrecognitiontaskdelegate/speechrecognitiontask(_:didhypothesizetranscription:)","role":"symbol","kind":"symbol","type":"topic","title":"speechRecognitionTask(_:didHypothesizeTranscription:)","abstract":[{"text":"Tells the delegate that a hypothesized transcription is available.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"speechRecognitionTask","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SFSpeechRecognitionTask","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSpeechRecognitionTask"},{"text":", ","kind":"text"},{"text":"didHypothesizeTranscription","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SFTranscription","preciseIdentifier":"c:objc(cs)SFTranscription","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.apple.speech/documentation/Speech":{"title":"Speech","kind":"symbol","identifier":"doc://com.apple.speech/documentation/Speech","type":"topic","role":"collection","abstract":[{"text":"Perform speech recognition on live or prerecorded audio, and receive transcriptions, alternative interpretations, and confidence levels of the results.","type":"text"}],"url":"/documentation/speech"},"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate":{"identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SFSpeechRecognitionTaskDelegate"}],"title":"SFSpeechRecognitionTaskDelegate","abstract":[{"type":"text","text":"A protocol with methods for managing multi-utterance speech recognition requests."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SFSpeechRecognitionTaskDelegate"}],"url":"/documentation/speech/sfspeechrecognitiontaskdelegate","type":"topic"},"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SFSpeechRecognitionTask"}],"navigatorTitle":[{"kind":"identifier","text":"SFSpeechRecognitionTask"}],"type":"topic","abstract":[{"text":"A task object for monitoring the speech recognition progress.","type":"text"}],"url":"/documentation/speech/sfspeechrecognitiontask","role":"symbol","title":"SFSpeechRecognitionTask","identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask"},"doc://com.apple.speech/documentation/Speech/SFTranscription":{"navigatorTitle":[{"kind":"identifier","text":"SFTranscription"}],"kind":"symbol","role":"symbol","url":"/documentation/speech/sftranscription","abstract":[{"text":"A textual representation of the specified speech in its entirety, as recognized by the speech recognizer.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SFTranscription"}],"title":"SFTranscription","type":"topic","identifier":"doc://com.apple.speech/documentation/Speech/SFTranscription"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"10.0"},{"name":"iPadOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"10.0"},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.1"},{"name":"macOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"10.15"},{"name":"visionOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"1.0"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"speechRecognitionTask:didHypothesizeTranscription:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"speechRecognitionTask:didHypothesizeTranscription:"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.speech/documentation/Speech","doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTaskDelegate"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"speechRecognitionTask:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SFSpeechRecognitionTask","text":"SFSpeechRecognitionTask","kind":"typeIdentifier","identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask"},{"text":" *) ","kind":"text"},{"text":"task","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didHypothesizeTranscription:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SFTranscription","text":"SFTranscription","kind":"typeIdentifier","identifier":"doc://com.apple.speech/documentation/Speech/SFTranscription"},{"text":" *) ","kind":"text"},{"text":"transcription","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The speech recognition task (an ","type":"text"},{"identifier":"doc://com.apple.speech/documentation/Speech/SFSpeechRecognitionTask","type":"reference","isActive":true},{"text":" object) that represents the request.","type":"text"}]}],"name":"task"},{"content":[{"inlineContent":[{"text":"The hypothesized transcription in an ","type":"text"},{"type":"reference","identifier":"doc://com.apple.speech/documentation/Speech/SFTranscription","isActive":true},{"text":" object.","type":"text"}],"type":"paragraph"}],"name":"transcription"}]},"path":"/primaryContentSections/1"},{"value":"speechRecognitionTask:didHypothesizeTranscription:","op":"replace","path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskDelegate~1speechRecognitionTask(_:didHypothesizeTranscription:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"speechRecognitionTask:didHypothesizeTranscription:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskDelegate~1speechRecognitionTask(_:didHypothesizeTranscription:)/fragments"},{"value":"SFSpeechRecognitionTaskDelegate","op":"replace","path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskDelegate/title"},{"value":[{"kind":"identifier","text":"SFSpeechRecognitionTaskDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskDelegate/fragments"},{"value":[{"text":"SFSpeechRecognitionTaskDelegate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTaskDelegate/navigatorTitle"},{"value":"SFSpeechRecognitionTask","op":"replace","path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTask/title"},{"value":[{"kind":"identifier","text":"SFSpeechRecognitionTask"}],"op":"replace","path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTask/fragments"},{"value":[{"text":"SFSpeechRecognitionTask","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFSpeechRecognitionTask/navigatorTitle"},{"value":"SFTranscription","op":"replace","path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscription/title"},{"value":[{"text":"SFTranscription","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscription/fragments"},{"value":[{"text":"SFTranscription","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.speech~1documentation~1Speech~1SFTranscription/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}