{
  "abstract": [
    {
      "text": "Indicates that the color values in the texture were not premultiplied by the alpha value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.glkit/documentation/GLKit",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState/nonPremultiplied"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GLKTextureInfoAlphaState@GLKTextureInfoAlphaStateNonPremultiplied",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nonPremultiplied"
      }
    ],
    "modules": [
      {
        "name": "GLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GLKTextureInfoAlphaStateNonPremultiplied"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "GLKTextureInfoAlphaState.nonPremultiplied"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nonPremultiplied"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.glkit/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/glkit"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState": {
      "abstract": [
        {
          "text": "Values that describe the alpha information stored in a source image’s pixel data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GLKTextureInfoAlphaState"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureInfoAlphaState"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureInfoAlphaState",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfoalphastate"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState/nonPremultiplied": {
      "abstract": [
        {
          "text": "Indicates that the color values in the texture were not premultiplied by the alpha value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonPremultiplied"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState/nonPremultiplied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureInfoAlphaStateNonPremultiplied"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureInfoAlphaState.nonPremultiplied",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfoalphastate/nonpremultiplied"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState/none": {
      "abstract": [
        {
          "text": "Indicates that the texture has no alpha information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureInfoAlphaStateNone"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureInfoAlphaState.none",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfoalphastate/none"
    },
    "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState/premultiplied": {
      "abstract": [
        {
          "text": "Indicates that the color values in the texture have already been premultiplied by the alpha value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "premultiplied"
        }
      ],
      "identifier": "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState/premultiplied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GLKTextureInfoAlphaStatePremultiplied"
        }
      ],
      "role": "symbol",
      "title": "GLKTextureInfoAlphaState.premultiplied",
      "type": "topic",
      "url": "/documentation/glkit/glktextureinfoalphastate/premultiplied"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState/none",
        "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState/premultiplied"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GLKTextureInfoAlphaStateNonPremultiplied"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfoAlphaStateNonPremultiplied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.glkit/documentation/GLKit",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState/none",
                "doc://com.apple.glkit/documentation/GLKit/GLKTextureInfoAlphaState/premultiplied"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "GLKTextureInfoAlphaStateNonPremultiplied"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoAlphaState~1premultiplied/title",
          "value": "GLKTextureInfoAlphaStatePremultiplied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoAlphaState~1premultiplied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfoAlphaStatePremultiplied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoAlphaState~1none/title",
          "value": "GLKTextureInfoAlphaStateNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoAlphaState~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfoAlphaStateNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoAlphaState~1nonPremultiplied/title",
          "value": "GLKTextureInfoAlphaStateNonPremultiplied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoAlphaState~1nonPremultiplied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfoAlphaStateNonPremultiplied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoAlphaState/title",
          "value": "GLKTextureInfoAlphaState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoAlphaState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfoAlphaState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.glkit~1documentation~1GLKit~1GLKTextureInfoAlphaState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GLKTextureInfoAlphaState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/glkit/glktextureinfoalphastate/nonpremultiplied"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/glkit/glktextureinfoalphastate/nonpremultiplied"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
