{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteBackward"},{"kind":"text","text":"()"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}]},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/handling-text-interactions-in-custom-keyboards"]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Remove the character just before the cursor from your class’s backing store and redisplay the text."}]}],"kind":"content"}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIKeyInput/deleteBackward()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uikeyinput/deletebackward()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uikeyinput/deletebackward()"]}],"metadata":{"externalID":"c:objc(pl)UIKeyInput(im)deleteBackward","required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteBackward","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"UIKit"}],"platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false},{"name":"tvOS","unavailable":false,"deprecated":false,"beta":false},{"name":"visionOS","unavailable":false,"deprecated":false,"beta":false}],"title":"deleteBackward()","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"deleteBackward","kind":"identifier"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIKeyInput"]]},"abstract":[{"type":"text","text":"Deletes a character from the displayed text."}],"sections":[],"seeAlsoSections":[{"generated":true,"title":"Inserting and deleting text","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIKeyInput/insertText(_:)","doc://com.apple.uikit/documentation/UIKit/UIKeyInput/hasText"],"anchor":"Inserting-and-deleting-text"}],"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/handling-text-interactions-in-custom-keyboards":{"url":"/documentation/uikit/handling-text-interactions-in-custom-keyboards","role":"article","identifier":"doc://com.apple.uikit/documentation/UIKit/handling-text-interactions-in-custom-keyboards","abstract":[{"text":"Insert, delete, and manipulate text by using a proxy to a text input view.","type":"text"}],"kind":"article","type":"topic","title":"Handling text interactions in custom keyboards"},"doc://com.apple.uikit/documentation/UIKit/UIKeyInput/insertText(_:)":{"kind":"symbol","type":"topic","url":"/documentation/uikit/uikeyinput/inserttext(_:)","role":"symbol","title":"insertText(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertText"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"insertText:"}],"required":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyInput/insertText(_:)","abstract":[{"text":"Inserts a character into the displayed text.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIKeyInput/hasText":{"kind":"symbol","type":"topic","url":"/documentation/uikit/uikeyinput/hastext","role":"symbol","title":"hasText","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"hasText"}],"required":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyInput/hasText","abstract":[{"text":"A Boolean value that indicates whether the text-entry object has any text.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIKeyInput":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyInput","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIKeyInput"}],"type":"topic","title":"UIKeyInput","url":"/documentation/uikit/uikeyinput","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIKeyInput"}],"role":"symbol","abstract":[{"type":"text","text":"A set of methods a responder uses to implement simple text entry."}]},"doc://com.apple.uikit/documentation/UIKit/UIKeyInput/deleteBackward()":{"navigatorTitle":[{"kind":"identifier","text":"deleteBackward"}],"url":"/documentation/uikit/uikeyinput/deletebackward()","kind":"symbol","role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteBackward"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyInput/deleteBackward()","title":"deleteBackward()","abstract":[{"type":"text","text":"Deletes a character from the displayed text."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false},{"name":"tvOS","unavailable":false,"deprecated":false,"beta":false},{"name":"visionOS","unavailable":false,"deprecated":false,"beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"deleteBackward","path":"/metadata/title","op":"replace"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteBackward"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIKeyInput"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Inserting and deleting text","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIKeyInput/insertText(_:)","doc://com.apple.uikit/documentation/UIKit/UIKeyInput/hasText"],"generated":true,"anchor":"Inserting-and-deleting-text"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"deleteBackward","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput~1insertText(_:)/title","op":"replace","value":"insertText:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput~1insertText(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertText:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput~1hasText/title","op":"replace","value":"hasText"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput~1hasText/fragments","op":"replace","value":[{"kind":"identifier","text":"hasText"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput/title","op":"replace","value":"UIKeyInput"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput/fragments","op":"replace","value":[{"text":"UIKeyInput","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIKeyInput"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput~1deleteBackward()/title","op":"replace","value":"deleteBackward"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput~1deleteBackward()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteBackward"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}