{
  "abstract": [
    {
      "text": "Display image media.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController",
        "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library/image"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSMediaLibrary@NSMediaLibraryImage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "image"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSMediaLibraryBrowserController",
        "text": "NSMediaLibraryBrowserController"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSMediaLibrary",
        "text": "Library"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSMediaLibraryImage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "image"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "image"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSMediaLibraryBrowserController",
              "text": "NSMediaLibraryBrowserController"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSMediaLibrary",
              "text": "Library"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController": {
      "abstract": [
        {
          "text": "An object that configures and displays a Media Library Browser panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMediaLibraryBrowserController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMediaLibraryBrowserController"
        }
      ],
      "role": "symbol",
      "title": "NSMediaLibraryBrowserController",
      "type": "topic",
      "url": "/documentation/appkit/nsmedialibrarybrowsercontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library": {
      "abstract": [
        {
          "text": "These constants are masks used to configure a Media Library Browser to display specific types of media. Combined masks are not yet supported.  In other words, only one nonzero mask value is supported at a time.  If masks are combined, the lowest mask value is used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Library"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Library"
        }
      ],
      "role": "symbol",
      "title": "NSMediaLibraryBrowserController.Library",
      "type": "topic",
      "url": "/documentation/appkit/nsmedialibrarybrowsercontroller/library"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library/audio": {
      "abstract": [
        {
          "text": "Display audio media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMediaLibraryBrowserController",
          "text": "NSMediaLibraryBrowserController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSMediaLibrary",
          "text": "Library"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library/audio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMediaLibraryAudio"
        }
      ],
      "role": "symbol",
      "title": "audio",
      "type": "topic",
      "url": "/documentation/appkit/nsmedialibrarybrowsercontroller/library/audio"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library/image": {
      "abstract": [
        {
          "text": "Display image media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMediaLibraryBrowserController",
          "text": "NSMediaLibraryBrowserController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSMediaLibrary",
          "text": "Library"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMediaLibraryImage"
        }
      ],
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/appkit/nsmedialibrarybrowsercontroller/library/image"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library/movie": {
      "abstract": [
        {
          "text": "Display movie media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "movie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMediaLibraryBrowserController",
          "text": "NSMediaLibraryBrowserController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSMediaLibrary",
          "text": "Library"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library/movie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMediaLibraryMovie"
        }
      ],
      "role": "symbol",
      "title": "movie",
      "type": "topic",
      "url": "/documentation/appkit/nsmedialibrarybrowsercontroller/library/movie"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library/audio",
        "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library/movie"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSMediaLibraryImage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMediaLibraryImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library/audio",
                "doc://com.apple.appkit/documentation/AppKit/NSMediaLibraryBrowserController/Library/movie"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSMediaLibraryImage"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1Library~1image/title",
          "value": "NSMediaLibraryImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1Library~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMediaLibraryImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController/title",
          "value": "NSMediaLibraryBrowserController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMediaLibraryBrowserController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMediaLibraryBrowserController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1Library/title",
          "value": "NSMediaLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1Library/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMediaLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1Library/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMediaLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1Library~1audio/title",
          "value": "NSMediaLibraryAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1Library~1audio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMediaLibraryAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1Library~1movie/title",
          "value": "NSMediaLibraryMovie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMediaLibraryBrowserController~1Library~1movie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMediaLibraryMovie"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsmedialibrarybrowsercontroller/library/image"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsmedialibrarybrowsercontroller/library/image"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
