{
  "abstract": [
    {
      "text": "Sent by an ",
      "type": "text"
    },
    {
      "code": "SBApplication",
      "type": "codeVoice"
    },
    {
      "text": " object when a target application returns an error",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "Apple event.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge",
        "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplicationDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplicationDelegate/eventDidFail(_:withError:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)SBApplicationDelegate(im)eventDidFail:withError:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "eventDidFail"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AppleEvent",
        "text": "AppleEvent"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "externalParam",
        "text": "withError"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Scripting Bridge"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "eventDidFail:withError:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "eventDidFail(_:withError:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "eventDidFail"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "event"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@AppleEvent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AppleEvent",
              "text": "AppleEvent"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "withError"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to the Apple event sent to the target application causing",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "the error.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "event"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object containing information about the error Apple event.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Specific information may be included in the ",
                  "type": "text"
                },
                {
                  "code": "useInfo",
                  "type": "codeVoice"
                },
                {
                  "text": " dictionary of the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "error object. The following table shows the possible",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "keys for this dictionary.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "header": "row",
              "rows": [
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "Key",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "Description",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "ErrorBriefMessage",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "A short human-readable description of the error, as an ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
                          "isActive": true,
                          "type": "reference"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "ErrorExpectedType",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The type of data the target application expected, as an ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/foundation/nsappleeventdescriptor",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " object.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "ErrorOffendingObject",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The object that caused the error.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "ErrorString",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "A full human-readable description of the error, as an ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": "\u0004 object.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ],
                [
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "ErrorNumber",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  [
                    {
                      "inlineContent": [
                        {
                          "text": "The Apple event error number, as an ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " object.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                ]
              ],
              "type": "table"
            }
          ],
          "name": "error"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you return a result, it will become the result of the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSApplication/sendEvent(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that failed. Can be ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge": {
      "abstract": [
        {
          "text": "Automate scriptable apps by sending and receiving Apple events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge",
      "kind": "symbol",
      "role": "collection",
      "title": "Scripting Bridge",
      "type": "topic",
      "url": "/documentation/scriptingbridge"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplicationDelegate": {
      "abstract": [
        {
          "text": "This informal protocol defines a delegation method for handling Apple event",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "errors that are sent from a target application to an",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/ScriptingBridge/SBApplication",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SBApplicationDelegate"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplicationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SBApplicationDelegate"
        }
      ],
      "role": "symbol",
      "title": "SBApplicationDelegate",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbapplicationdelegate"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplicationDelegate/eventDidFail(_:withError:)": {
      "abstract": [
        {
          "text": "Sent by an ",
          "type": "text"
        },
        {
          "code": "SBApplication",
          "type": "codeVoice"
        },
        {
          "text": " object when a target application returns an error",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Apple event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventDidFail"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AppleEvent",
          "text": "AppleEvent"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "withError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplicationDelegate/eventDidFail(_:withError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eventDidFail:withError:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "eventDidFail(_:withError:)",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbapplicationdelegate/eventdidfail(_:witherror:)"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSApplication/sendEvent(_:)": {
      "abstract": [
        {
          "text": "Dispatches an event to other objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendEvent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "event"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSApplication/sendEvent(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "sendEvent(_:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSApplication/sendEvent(_:)"
    },
    "doc://com.apple.documentation/documentation/ScriptingBridge/SBApplication": {
      "abstract": [
        {
          "text": "The `SBApplication` class provides a mechanism enabling an Objective-C program to send Apple events to a scriptable application and receive Apple events in response. It thereby makes it possible for that program to control the application and exchange data with it. Scripting Bridge works by bridging data types between Apple event descriptors and Cocoa objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SBApplication"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ScriptingBridge/SBApplication",
      "kind": "symbol",
      "role": "symbol",
      "title": "SBApplication",
      "type": "topic",
      "url": "/documentation/ScriptingBridge/SBApplication"
    },
    "doc://com.apple.documentation/documentation/foundation/nsappleeventdescriptor": {
      "abstract": [
        {
          "text": "A wrapper for the Apple event descriptor data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSAppleEventDescriptor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsappleeventdescriptor",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppleEventDescriptor",
      "type": "topic",
      "url": "/documentation/foundation/nsappleeventdescriptor"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@AppleEvent": {
      "abstract": [
        {
          "text": "A descriptor whose data is a list of descriptors containingboth attributes and parameters that make up an Apple event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "AppleEvent"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@AppleEvent",
      "kind": "symbol",
      "role": "symbol",
      "title": "AppleEvent",
      "type": "topic",
      "url": "/documentation/coreservices/appleevent"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "eventDidFail:withError:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "eventDidFail:withError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge",
                "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBApplicationDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "eventDidFail:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@AppleEvent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AppleEvent",
                    "text": "AppleEvent"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "event"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "withError:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to the Apple event sent to the target application causing",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "the error.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "event"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An object containing information about the error Apple event.",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "Specific information may be included in the ",
                        "type": "text"
                      },
                      {
                        "code": "useInfo",
                        "type": "codeVoice"
                      },
                      {
                        "text": " dictionary of the",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "error object. The following table shows the possible",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "keys for this dictionary.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "header": "row",
                    "rows": [
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "Key",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "Description",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "ErrorBriefMessage",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "A short human-readable description of the error, as an ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
                                "isActive": true,
                                "type": "reference"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "ErrorExpectedType",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The type of data the target application expected, as an ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/foundation/nsappleeventdescriptor",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " object.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "ErrorOffendingObject",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The object that caused the error.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "ErrorString",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "A full human-readable description of the error, as an ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": "\u0004 object.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ],
                      [
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "ErrorNumber",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ],
                        [
                          {
                            "inlineContent": [
                              {
                                "text": "The Apple event error number, as an ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " object.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      ]
                    ],
                    "type": "table"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "If you return a result, it will become the result of the",
                    "type": "text"
                  },
                  {
                    "text": " ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/AppKit/NSApplication/sendEvent(_:)",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " ",
                    "type": "text"
                  },
                  {
                    "text": "that failed. Can be ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ScriptingBridge~1SBApplication/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SBApplication"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SBObject",
              "text": "SBObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplicationDelegate~1eventDidFail(_:withError:)/title",
          "value": "eventDidFail:withError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplicationDelegate~1eventDidFail(_:withError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "eventDidFail:withError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSApplication~1sendEvent(_:)/title",
          "value": "sendEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSApplication~1sendEvent(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "sendEvent:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSEvent",
              "text": "NSEvent"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "event"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplicationDelegate/title",
          "value": "SBApplicationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplicationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SBApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBApplicationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SBApplicationDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scriptingbridge/sbapplicationdelegate/eventdidfail(_:witherror:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scriptingbridge/sbapplicationdelegate/eventdidfail(_:witherror:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
