{
  "abstract": [
    {
      "text": "A request for access to the ",
      "type": "text"
    },
    {
      "code": "browser.contextMenus",
      "type": "codeVoice"
    },
    {
      "text": " APIs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/contextMenus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "WebKit",
    "externalID": "c:@WKWebExtensionPermissionContextMenus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "contextMenus"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)WKWebExtension",
        "text": "WKWebExtension"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@WKWebExtensionPermission",
        "text": "Permission"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKWebExtensionPermissionContextMenus"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "contextMenus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "nonisolated"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "contextMenus"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WKWebExtension",
              "text": "WKWebExtension"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@WKWebExtensionPermission",
              "text": "Permission"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension": {
      "abstract": [
        {
          "text": "An object that encapsulates a web extension’s resources that the manifest file defines.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebExtension"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtension"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission": {
      "abstract": [
        {
          "text": "Constants for specifying permission in a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionContext",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Permission"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtension.Permission",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/activeTab": {
      "abstract": [
        {
          "text": "A request indicating that when a person interacts with the extension, the system grants extra permissions for the active tab only.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeTab"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/activeTab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionActiveTab"
        }
      ],
      "role": "symbol",
      "title": "activeTab",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/activetab"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/alarms": {
      "abstract": [
        {
          "text": "A request for access to the ",
          "type": "text"
        },
        {
          "code": "browser.alarms",
          "type": "codeVoice"
        },
        {
          "text": " APIs.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alarms"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/alarms",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionAlarms"
        }
      ],
      "role": "symbol",
      "title": "alarms",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/alarms"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/clipboardWrite": {
      "abstract": [
        {
          "text": "A request for access to write to the clipboard.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clipboardWrite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/clipboardWrite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionClipboardWrite"
        }
      ],
      "role": "symbol",
      "title": "clipboardWrite",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/clipboardwrite"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/contextMenus": {
      "abstract": [
        {
          "text": "A request for access to the ",
          "type": "text"
        },
        {
          "code": "browser.contextMenus",
          "type": "codeVoice"
        },
        {
          "text": " APIs.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contextMenus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/contextMenus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionContextMenus"
        }
      ],
      "role": "symbol",
      "title": "contextMenus",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/contextmenus"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/cookies": {
      "abstract": [
        {
          "text": "A request for access to the ",
          "type": "text"
        },
        {
          "code": "browser.cookies",
          "type": "codeVoice"
        },
        {
          "text": " APIs.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cookies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/cookies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionCookies"
        }
      ],
      "role": "symbol",
      "title": "cookies",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/cookies"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/declarativeNetRequest": {
      "abstract": [
        {
          "text": "A request for access to the ",
          "type": "text"
        },
        {
          "code": "browser.declarativeNetRequest",
          "type": "codeVoice"
        },
        {
          "text": " APIs.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "declarativeNetRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/declarativeNetRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionDeclarativeNetRequest"
        }
      ],
      "role": "symbol",
      "title": "declarativeNetRequest",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/declarativenetrequest"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/declarativeNetRequestFeedback": {
      "abstract": [
        {
          "text": "A request for access to the ",
          "type": "text"
        },
        {
          "code": "browser.declarativeNetRequest",
          "type": "codeVoice"
        },
        {
          "text": " APIs with extra information on matched rules.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "declarativeNetRequestFeedback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/declarativeNetRequestFeedback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionDeclarativeNetRequestFeedback"
        }
      ],
      "role": "symbol",
      "title": "declarativeNetRequestFeedback",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/declarativenetrequestfeedback"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/declarativeNetRequestWithHostAccess": {
      "abstract": [
        {
          "text": "A request for access to the ",
          "type": "text"
        },
        {
          "code": "browser.declarativeNetRequest",
          "type": "codeVoice"
        },
        {
          "text": " APIs with the ability to modify or redirect requests.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "declarativeNetRequestWithHostAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/declarativeNetRequestWithHostAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionDeclarativeNetRequestWithHostAccess"
        }
      ],
      "role": "symbol",
      "title": "declarativeNetRequestWithHostAccess",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/declarativenetrequestwithhostaccess"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/menus": {
      "abstract": [
        {
          "text": "A request for access to the ",
          "type": "text"
        },
        {
          "code": "browser.menus",
          "type": "codeVoice"
        },
        {
          "text": " APIs.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/menus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionMenus"
        }
      ],
      "role": "symbol",
      "title": "menus",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/menus"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/nativeMessaging": {
      "abstract": [
        {
          "text": "A request for access to send messages to the app extension bundle.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nativeMessaging"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/nativeMessaging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionNativeMessaging"
        }
      ],
      "role": "symbol",
      "title": "nativeMessaging",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/nativemessaging"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/scripting": {
      "abstract": [
        {
          "text": "A request for access to the ",
          "type": "text"
        },
        {
          "code": "browser.scripting",
          "type": "codeVoice"
        },
        {
          "text": " APIs.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scripting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/scripting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionScripting"
        }
      ],
      "role": "symbol",
      "title": "scripting",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/scripting"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/storage": {
      "abstract": [
        {
          "text": "A request for access to the ",
          "type": "text"
        },
        {
          "code": "browser.storage",
          "type": "codeVoice"
        },
        {
          "text": " APIs.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/storage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionStorage"
        }
      ],
      "role": "symbol",
      "title": "storage",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/storage"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/tabs": {
      "abstract": [
        {
          "text": "A request for access to extra information on the ",
          "type": "text"
        },
        {
          "code": "browser.tabs",
          "type": "codeVoice"
        },
        {
          "text": " APIs.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/tabs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionTabs"
        }
      ],
      "role": "symbol",
      "title": "tabs",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/tabs"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/unlimitedStorage": {
      "abstract": [
        {
          "text": "A request for access to an unlimited quota on the ",
          "type": "text"
        },
        {
          "code": "browser.storage.local",
          "type": "codeVoice"
        },
        {
          "text": " APIs.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlimitedStorage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/unlimitedStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionUnlimitedStorage"
        }
      ],
      "role": "symbol",
      "title": "unlimitedStorage",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/unlimitedstorage"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/webNavigation": {
      "abstract": [
        {
          "text": "A request for access to the ",
          "type": "text"
        },
        {
          "code": "browser.webNavigation",
          "type": "codeVoice"
        },
        {
          "text": " APIs.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webNavigation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/webNavigation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionWebNavigation"
        }
      ],
      "role": "symbol",
      "title": "webNavigation",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/webnavigation"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/webRequest": {
      "abstract": [
        {
          "text": "A request for access to the ",
          "type": "text"
        },
        {
          "code": "browser.webRequest",
          "type": "codeVoice"
        },
        {
          "text": " APIs.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebExtension",
          "text": "WKWebExtension"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKWebExtensionPermission",
          "text": "Permission"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/webRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionPermissionWebRequest"
        }
      ],
      "role": "symbol",
      "title": "webRequest",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextension/permission/webrequest"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionContext": {
      "abstract": [
        {
          "text": "An object that represents the runtime environment for a web extension.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebExtensionContext"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtensionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebExtensionContext"
        }
      ],
      "role": "symbol",
      "title": "WKWebExtensionContext",
      "type": "topic",
      "url": "/documentation/webkit/wkwebextensioncontext"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/activeTab",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/alarms",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/clipboardWrite",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/cookies",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/declarativeNetRequest",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/declarativeNetRequestFeedback",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/declarativeNetRequestWithHostAccess",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/menus",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/nativeMessaging",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/scripting",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/storage",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/tabs",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/unlimitedStorage",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/webNavigation",
        "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/webRequest"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "2.4",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKWebExtensionPermissionContextMenus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionContextMenus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/activeTab",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/alarms",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/clipboardWrite",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/cookies",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/declarativeNetRequest",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/declarativeNetRequestFeedback",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/declarativeNetRequestWithHostAccess",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/menus",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/nativeMessaging",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/scripting",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/storage",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/tabs",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/unlimitedStorage",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/webNavigation",
                "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission/webRequest"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebExtension/Permission",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@WKWebExtensionPermission",
                    "text": "WKWebExtensionPermission"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKWebExtensionPermissionContextMenus"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1activeTab/title",
          "value": "WKWebExtensionPermissionActiveTab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1activeTab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionActiveTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1declarativeNetRequestWithHostAccess/title",
          "value": "WKWebExtensionPermissionDeclarativeNetRequestWithHostAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1declarativeNetRequestWithHostAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionDeclarativeNetRequestWithHostAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1contextMenus/title",
          "value": "WKWebExtensionPermissionContextMenus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1contextMenus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionContextMenus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1unlimitedStorage/title",
          "value": "WKWebExtensionPermissionUnlimitedStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1unlimitedStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionUnlimitedStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1webNavigation/title",
          "value": "WKWebExtensionPermissionWebNavigation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1webNavigation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionWebNavigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionContext/title",
          "value": "WKWebExtensionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtensionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1declarativeNetRequestFeedback/title",
          "value": "WKWebExtensionPermissionDeclarativeNetRequestFeedback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1declarativeNetRequestFeedback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionDeclarativeNetRequestFeedback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1alarms/title",
          "value": "WKWebExtensionPermissionAlarms"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1alarms/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionAlarms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1menus/title",
          "value": "WKWebExtensionPermissionMenus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1menus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionMenus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension/title",
          "value": "WKWebExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission/title",
          "value": "WKWebExtensionPermission"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermission"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermission"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1webRequest/title",
          "value": "WKWebExtensionPermissionWebRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1webRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionWebRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1cookies/title",
          "value": "WKWebExtensionPermissionCookies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1cookies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionCookies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1declarativeNetRequest/title",
          "value": "WKWebExtensionPermissionDeclarativeNetRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1declarativeNetRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionDeclarativeNetRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1tabs/title",
          "value": "WKWebExtensionPermissionTabs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1tabs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionTabs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1storage/title",
          "value": "WKWebExtensionPermissionStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1storage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1clipboardWrite/title",
          "value": "WKWebExtensionPermissionClipboardWrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1clipboardWrite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionClipboardWrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1scripting/title",
          "value": "WKWebExtensionPermissionScripting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1scripting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionScripting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1nativeMessaging/title",
          "value": "WKWebExtensionPermissionNativeMessaging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebExtension~1Permission~1nativeMessaging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebExtensionPermissionNativeMessaging"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkwebextension/permission/contextmenus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkwebextension/permission/contextmenus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
