{
  "abstract": [
    {
      "text": "The operation’s type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/type"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSFileProviderTestingOperation(py)type",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "type"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSFileProviderTestingOperationType",
        "text": "NSFileProviderTestingOperationType"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "type"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "type"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSFileProviderTestingOperationType",
              "text": "NSFileProviderTestingOperationType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation": {
      "abstract": [
        {
          "text": "An operation that the system can schedule.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperation"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperation"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperation",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asChildrenEnumeration": {
      "abstract": [
        {
          "text": "Returns the operation if it enumerates contained items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asChildrenEnumeration"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asChildrenEnumeration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asChildrenEnumeration"
        }
      ],
      "role": "symbol",
      "title": "asChildrenEnumeration",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/aschildrenenumeration"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asCollisionResolution": {
      "abstract": [
        {
          "text": "Returns the operation if it resolves a collision by renaming the new item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asCollisionResolution"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asCollisionResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asCollisionResolution"
        }
      ],
      "role": "symbol",
      "title": "asCollisionResolution",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/ascollisionresolution"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asContentFetch": {
      "abstract": [
        {
          "text": "Returns the operation if it fetches an item’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asContentFetch"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asContentFetch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asContentFetch"
        }
      ],
      "role": "symbol",
      "title": "asContentFetch",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/ascontentfetch"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asCreation": {
      "abstract": [
        {
          "text": "Returns the operation if it propagates the creation of an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asCreation"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asCreation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asCreation"
        }
      ],
      "role": "symbol",
      "title": "asCreation",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/ascreation"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asDeletion": {
      "abstract": [
        {
          "text": "Returns the operation if it propagates the deletion of an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asDeletion"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asDeletion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asDeletion"
        }
      ],
      "role": "symbol",
      "title": "asDeletion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/asdeletion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asIngestion": {
      "abstract": [
        {
          "text": "Returns the operation if it alerts the system to changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asIngestion"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asIngestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asIngestion"
        }
      ],
      "role": "symbol",
      "title": "asIngestion",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/asingestion"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asLookup": {
      "abstract": [
        {
          "text": "Returns the operation if it looks up an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asLookup"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asLookup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asLookup"
        }
      ],
      "role": "symbol",
      "title": "asLookup",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/aslookup"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asModification": {
      "abstract": [
        {
          "text": "Returns the operation if it propagates a change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "asModification"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asModification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asModification"
        }
      ],
      "role": "symbol",
      "title": "asModification",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/asmodification"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/type": {
      "abstract": [
        {
          "text": "The operation’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderTestingOperationType",
          "text": "NSFileProviderTestingOperationType"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperation/type"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType": {
      "abstract": [
        {
          "text": "The action that an operation performs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationType"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderTestingOperationType"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderTestingOperationType",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidertestingoperationtype"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileprovider/documentation/FileProvider",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Access-the-Operation-Type",
              "generated": true,
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asChildrenEnumeration",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asCollisionResolution",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asContentFetch",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asCreation",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asDeletion",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asIngestion",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asLookup",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperation/asModification"
              ],
              "title": "Access the Operation Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderTestingOperationType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSFileProviderTestingOperationType",
                    "text": "NSFileProviderTestingOperationType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "type"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperation~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperation~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType/title",
          "value": "NSFileProviderTestingOperationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperation/title",
          "value": "NSFileProviderTestingOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderTestingOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderTestingOperation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidertestingoperation/type"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidertestingoperation/type"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
