{
  "abstract": [
    {
      "text": "Reveal how your app represents itself to people using accessibility features.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-inspector"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "Developer Tool",
    "title": "Accessibility Inspector"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use Accessibility Inspector to display, query, and test accessibility information for the elements in your app’s view hierarchy. Audit your app to confirm that it addresses accessibility issues such as clipped text and unlabeled elements, and uses appropriate text size and color contrast levels. The information provided by the inspector supplements accessibility testing by providing some of the raw information you need to debug accessibility issues.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To use Accessibility Inspector, open Xcode and choose Xcode > Open Developer Tool > Accessibility Inspector.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "accessibility-inspector-overview",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "accessibility-inspector-overview": {
      "alt": null,
      "identifier": "accessibility-inspector-overview",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a8aa927ecb03cecbba300b0a09258e4f/accessibility-inspector-overview~dark@2x.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/be82179a1110c56d69ee735ea919bae7/accessibility-inspector-overview@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/inspecting-the-accessibility-of-screens": {
      "abstract": [
        {
          "text": "Focus on your app with Accessibility Inspector and investigate potential issues on each screen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/inspecting-the-accessibility-of-screens",
      "kind": "article",
      "role": "article",
      "title": "Inspecting the accessibility of the screens in your app",
      "type": "topic",
      "url": "/documentation/accessibility/inspecting-the-accessibility-of-screens"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-audits-for-your-app": {
      "abstract": [
        {
          "text": "Audit your app for common accessibility issues with Accessibility Inspector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-audits-for-your-app",
      "kind": "article",
      "role": "article",
      "title": "Performing accessibility audits for your app",
      "type": "topic",
      "url": "/documentation/accessibility/performing-accessibility-audits-for-your-app"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/testing-system-accessibility-features-in-your-app": {
      "abstract": [
        {
          "text": "Confirm that your app provides a good experience for everyone",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "by testing system accessibility settings in Accessibility Inspector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/testing-system-accessibility-features-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Testing system accessibility features in your app",
      "type": "topic",
      "url": "/documentation/accessibility/testing-system-accessibility-features-in-your-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "App-inspection",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/inspecting-the-accessibility-of-screens"
      ],
      "title": "App inspection"
    },
    {
      "anchor": "Accessibility-audits",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-audits-for-your-app"
      ],
      "title": "Accessibility audits"
    },
    {
      "anchor": "Accessibility-feature-testing",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/testing-system-accessibility-features-in-your-app"
      ],
      "title": "Accessibility feature testing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "App-inspection",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/inspecting-the-accessibility-of-screens"
              ],
              "title": "App inspection"
            },
            {
              "anchor": "Accessibility-audits",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-audits-for-your-app"
              ],
              "title": "Accessibility audits"
            },
            {
              "anchor": "Accessibility-feature-testing",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/testing-system-accessibility-features-in-your-app"
              ],
              "title": "Accessibility feature testing"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/accessibility-inspector"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/accessibility-inspector"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
