{
  "abstract": [
    {
      "text": "A structure for working with accessibility system settings.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AccessibilitySettings",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AccessibilitySettings"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AccessibilitySettings"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AccessibilitySettings"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AccessibilitySettings"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings": {
      "abstract": [
        {
          "text": "A structure for working with accessibility system settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessibilitySettings"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessibilitySettings"
        }
      ],
      "role": "symbol",
      "title": "AccessibilitySettings",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/Feature": {
      "abstract": [
        {
          "text": "Constants that describe specific Accessibility settings in the Settings app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Feature"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/Feature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Feature"
        }
      ],
      "role": "symbol",
      "title": "AccessibilitySettings.Feature",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings/feature"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/animatedImagesEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system setting for playing animated images is on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animatedImagesEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/animatedImagesEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "animatedImagesEnabled",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings/animatedimagesenabled"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/animatedImagesEnabledDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that posts when the system setting for playing animated images changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animatedImagesEnabledDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV4Namea",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/animatedImagesEnabledDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "animatedImagesEnabledDidChangeNotification",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings/animatedimagesenableddidchangenotification"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings/init()"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/isAssistiveAccessEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether Assistive Access is running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAssistiveAccessEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/isAssistiveAccessEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXAssistiveAccessEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAssistiveAccessEnabled",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings/isassistiveaccessenabled"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/openSettings(for:)": {
      "abstract": [
        {
          "text": "Opens the Settings app to a specific section of Accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openSettings"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AccessibilitySettings",
          "text": "AccessibilitySettings"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXSettingsFeature",
          "text": "Feature"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/openSettings(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "openSettings(for:)",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings/opensettings(for:)"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersHeadAnchorAlternative": {
      "abstract": [
        {
          "text": "A Boolean value that indicates the person’s preference for content that follows",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "their head position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersHeadAnchorAlternative"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersHeadAnchorAlternative",
      "kind": "symbol",
      "role": "symbol",
      "title": "prefersHeadAnchorAlternative",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings/prefersheadanchoralternative"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersHeadAnchorAlternativeDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that posts when the system setting for head-anchored content changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersHeadAnchorAlternativeDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV4Namea",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersHeadAnchorAlternativeDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "prefersHeadAnchorAlternativeDidChangeNotification",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings/prefersheadanchoralternativedidchangenotification"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersHorizontalTextLayout": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system setting to prefer horizontal text for languages that support both vertical and horizontal text layout is on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersHorizontalTextLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersHorizontalTextLayout",
      "kind": "symbol",
      "role": "symbol",
      "title": "prefersHorizontalTextLayout",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings/prefershorizontaltextlayout"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersHorizontalTextLayoutDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that posts when the system setting to prefer horizontal text for languages that support both vertical and horizontal text layout changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersHorizontalTextLayoutDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV4Namea",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersHorizontalTextLayoutDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "prefersHorizontalTextLayoutDidChangeNotification",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings/prefershorizontaltextlayoutdidchangenotification"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersNonBlinkingTextInsertionIndicator": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system setting to prefer a nonblinking cursor in editable text fields is on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersNonBlinkingTextInsertionIndicator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersNonBlinkingTextInsertionIndicator",
      "kind": "symbol",
      "role": "symbol",
      "title": "prefersNonBlinkingTextInsertionIndicator",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings/prefersnonblinkingtextinsertionindicator"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersNonBlinkingTextInsertionIndicatorDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that posts when the system setting to prefer a nonblinking cursor in editable text fields changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersNonBlinkingTextInsertionIndicatorDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersNonBlinkingTextInsertionIndicatorDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXPrefersNonBlinkingTextInsertionIndicatorDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "prefersNonBlinkingTextInsertionIndicatorDidChangeNotification",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings/prefersnonblinkingtextinsertionindicatordidchangenotification"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/animated-images": {
      "abstract": [
        {
          "text": "Pause animations in animated images in your app when people turn off the Animated",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Images setting.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/animated-images",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Animated images",
      "type": "topic",
      "url": "/documentation/accessibility/animated-images"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/horizontal-text": {
      "abstract": [
        {
          "text": "Lay out vertical text horizontally in your app when people turn on the Prefer Horizontal",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Text setting.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/horizontal-text",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Horizontal text",
      "type": "topic",
      "url": "/documentation/accessibility/horizontal-text"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Opening-the-Settings-app",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/openSettings(for:)",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/Feature"
      ],
      "title": "Opening the Settings app"
    },
    {
      "anchor": "Pausing-animated-images",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/animated-images",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/animatedImagesEnabled",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/animatedImagesEnabledDidChangeNotification"
      ],
      "title": "Pausing animated images"
    },
    {
      "anchor": "Customizing-vertical-text-layout",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/horizontal-text",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersHorizontalTextLayout",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersHorizontalTextLayoutDidChangeNotification"
      ],
      "title": "Customizing vertical text layout"
    },
    {
      "anchor": "Supporting-head-anchored-content",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersHeadAnchorAlternative",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersHeadAnchorAlternativeDidChangeNotification"
      ],
      "title": "Supporting head-anchored content"
    },
    {
      "anchor": "Reducing-animation-for-text-insertion-indicators",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersNonBlinkingTextInsertionIndicator",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/prefersNonBlinkingTextInsertionIndicatorDidChangeNotification"
      ],
      "title": "Reducing animation for text insertion indicators"
    },
    {
      "anchor": "Checking-if-Assistive-Access-is-running",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/isAssistiveAccessEnabled"
      ],
      "title": "Checking if Assistive Access is running"
    },
    {
      "anchor": "Creating-an-accessibility-settings-structure",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/init()"
      ],
      "title": "Creating an accessibility settings structure"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilitySettings~1prefersNonBlinkingTextInsertionIndicatorDidChangeNotification/title",
          "value": "AXPrefersNonBlinkingTextInsertionIndicatorDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilitySettings~1prefersNonBlinkingTextInsertionIndicatorDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXPrefersNonBlinkingTextInsertionIndicatorDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilitySettings~1isAssistiveAccessEnabled/title",
          "value": "AXAssistiveAccessEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilitySettings~1isAssistiveAccessEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXAssistiveAccessEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilitySettings~1Feature/title",
          "value": "AXSettingsFeature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilitySettings~1Feature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXSettingsFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilitySettings~1Feature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXSettingsFeature"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/accessibilitysettings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
