{
  "abstract": [
    {
      "text": "Browse API in the Accessibility framework.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-api"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Accessibility API"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "While many Apple frameworks provide built-in accessibility support,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the Accessibility framework defines API for supporting additional accessibility features across multiple platforms.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The Accessibility framework includes API that enable you to:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Respond to changes in Accessibility system settings",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Post accessibility notifications",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Define an accessible representation of your chart to support audio graphs",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Interact with hardware such as braille displays and hearing devices",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Generate a localized description of a color",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXAnimatedImagesEnabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXAnimatedImagesEnabled"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXAnimatedImagesEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXAnimatedImagesEnabled",
      "type": "topic",
      "url": "/documentation/accessibility/axanimatedimagesenabled"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXAnimatedImagesEnabled()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the system setting for Animated Images",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "is on.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXAnimatedImagesEnabled"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXAnimatedImagesEnabled()",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXAnimatedImagesEnabled()",
      "type": "topic",
      "url": "/documentation/accessibility/axanimatedimagesenabled()"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXAnimatedImagesEnabledDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXAnimatedImagesEnabledDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXAnimatedImagesEnabledDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXAnimatedImagesEnabledDidChangeNotification",
      "type": "topic",
      "url": "/documentation/accessibility/axanimatedimagesenableddidchangenotification"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNameFromColor(_:)": {
      "abstract": [
        {
          "text": "Returns a localized description of the color to use in accessibility attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXNameFromColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNameFromColor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXNameFromColor"
        }
      ],
      "role": "symbol",
      "title": "AXNameFromColor(_:)",
      "type": "topic",
      "url": "/documentation/accessibility/axnamefromcolor(_:)"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXOpenSettingsFeature": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXOpenSettingsFeature"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXOpenSettingsFeature",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXOpenSettingsFeature",
      "type": "topic",
      "url": "/documentation/accessibility/axopensettingsfeature"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHeadAnchorAlternative": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXPrefersHeadAnchorAlternative"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHeadAnchorAlternative",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXPrefersHeadAnchorAlternative",
      "type": "topic",
      "url": "/documentation/accessibility/axprefersheadanchoralternative"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHeadAnchorAlternative()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates the person’s preference for content that follows",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "their head position.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXPrefersHeadAnchorAlternative"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHeadAnchorAlternative()",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXPrefersHeadAnchorAlternative()",
      "type": "topic",
      "url": "/documentation/accessibility/axprefersheadanchoralternative()"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHeadAnchorAlternativeDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXPrefersHeadAnchorAlternativeDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHeadAnchorAlternativeDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXPrefersHeadAnchorAlternativeDidChangeNotification",
      "type": "topic",
      "url": "/documentation/accessibility/axprefersheadanchoralternativedidchangenotification"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHorizontalTextLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXPrefersHorizontalTextLayout"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHorizontalTextLayout",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXPrefersHorizontalTextLayout",
      "type": "topic",
      "url": "/documentation/accessibility/axprefershorizontaltextlayout"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHorizontalTextLayout()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the system setting for Prefer Horizontal",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Text is on.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXPrefersHorizontalTextLayout"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHorizontalTextLayout()",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXPrefersHorizontalTextLayout()",
      "type": "topic",
      "url": "/documentation/accessibility/axprefershorizontaltextlayout()"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHorizontalTextLayoutDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXPrefersHorizontalTextLayoutDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHorizontalTextLayoutDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXPrefersHorizontalTextLayoutDidChangeNotification",
      "type": "topic",
      "url": "/documentation/accessibility/axprefershorizontaltextlayoutdidchangenotification"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersNonBlinkingTextInsertionIndicator": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXPrefersNonBlinkingTextInsertionIndicator"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersNonBlinkingTextInsertionIndicator",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXPrefersNonBlinkingTextInsertionIndicator",
      "type": "topic",
      "url": "/documentation/accessibility/axprefersnonblinkingtextinsertionindicator"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityNotification": {
      "abstract": [
        {
          "text": "Types of accessibility notifications that an app can post.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessibilityNotification"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessibilityNotification"
        }
      ],
      "role": "symbol",
      "title": "AccessibilityNotification",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitynotification"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessibilityRequest"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessibilityRequest"
        }
      ],
      "role": "symbol",
      "title": "AccessibilityRequest",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilityrequest"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings": {
      "abstract": [
        {
          "text": "A structure for working with accessibility system settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessibilitySettings"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessibilitySettings"
        }
      ],
      "role": "symbol",
      "title": "AccessibilitySettings",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessibilityTechnology"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessibilityTechnology"
        }
      ],
      "role": "symbol",
      "title": "AccessibilityTechnology",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitytechnology"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/automation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AXTechnology",
          "text": "AccessibilityTechnology"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/automation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXTechnologyAutomation"
        }
      ],
      "role": "symbol",
      "title": "automation",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitytechnology/automation"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/fullKeyboardAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullKeyboardAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AXTechnology",
          "text": "AccessibilityTechnology"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/fullKeyboardAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXTechnologyFullKeyboardAccess"
        }
      ],
      "role": "symbol",
      "title": "fullKeyboardAccess",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitytechnology/fullkeyboardaccess"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/hoverText": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hoverText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AXTechnology",
          "text": "AccessibilityTechnology"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/hoverText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXTechnologyHoverText"
        }
      ],
      "role": "symbol",
      "title": "hoverText",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitytechnology/hovertext"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/speakScreen": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speakScreen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AXTechnology",
          "text": "AccessibilityTechnology"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/speakScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXTechnologySpeakScreen"
        }
      ],
      "role": "symbol",
      "title": "speakScreen",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitytechnology/speakscreen"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/switchControl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "switchControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AXTechnology",
          "text": "AccessibilityTechnology"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/switchControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXTechnologySwitchControl"
        }
      ],
      "role": "symbol",
      "title": "switchControl",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitytechnology/switchcontrol"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/voiceControl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voiceControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AXTechnology",
          "text": "AccessibilityTechnology"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/voiceControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXTechnologyVoiceControl"
        }
      ],
      "role": "symbol",
      "title": "voiceControl",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitytechnology/voicecontrol"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/voiceOver": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voiceOver"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AXTechnology",
          "text": "AccessibilityTechnology"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/voiceOver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXTechnologyVoiceOver"
        }
      ],
      "role": "symbol",
      "title": "voiceOver",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitytechnology/voiceover"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/zoom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zoom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AXTechnology",
          "text": "AccessibilityTechnology"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/zoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXTechnologyZoom"
        }
      ],
      "role": "symbol",
      "title": "zoom",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitytechnology/zoom"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/audio-graphs": {
      "abstract": [
        {
          "text": "Define an accessible representation of your chart for VoiceOver to generate an audio",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "graph.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/audio-graphs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio graphs",
      "type": "topic",
      "url": "/documentation/accessibility/audio-graphs"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/braille-displays": {
      "abstract": [
        {
          "text": "Display a graphical representation of images, icons, data, and more on a two-dimensional",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "braille display.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/braille-displays",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Braille displays",
      "type": "topic",
      "url": "/documentation/accessibility/braille-displays"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/customized-accessibility-content": {
      "abstract": [
        {
          "text": "Customize your apps to deliver accessibility information to your users in measured",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "portions as they need it.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/customized-accessibility-content",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Customized accessibility content",
      "type": "topic",
      "url": "/documentation/accessibility/customized-accessibility-content"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support": {
      "abstract": [
        {
          "text": "Access information about paired hearing aid devices and streaming status.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Hearing device support",
      "type": "topic",
      "url": "/documentation/accessibility/hearing-device-support"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "System-settings",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings"
      ],
      "title": "System settings"
    },
    {
      "anchor": "Notifications",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityNotification"
      ],
      "title": "Notifications"
    },
    {
      "anchor": "Assistive-technologies",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/automation",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/fullKeyboardAccess",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/hoverText",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/speakScreen",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/switchControl",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/voiceControl",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/voiceOver",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/zoom",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityRequest"
      ],
      "title": "Assistive technologies"
    },
    {
      "anchor": "Features",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/customized-accessibility-content",
        "doc://com.apple.Accessibility/documentation/Accessibility/audio-graphs",
        "doc://com.apple.Accessibility/documentation/Accessibility/braille-displays",
        "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXNameFromColor(_:)"
      ],
      "title": "Features"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXAnimatedImagesEnabled()",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHeadAnchorAlternative()",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHorizontalTextLayout()"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "System-settings",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXOpenSettingsFeature",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXAnimatedImagesEnabled",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXAnimatedImagesEnabledDidChangeNotification",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHorizontalTextLayout",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHorizontalTextLayoutDidChangeNotification",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHeadAnchorAlternative",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHeadAnchorAlternativeDidChangeNotification",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersNonBlinkingTextInsertionIndicator"
              ],
              "title": "System settings"
            },
            {
              "anchor": "Assistive-technologies",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology",
                "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/automation",
                "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/fullKeyboardAccess",
                "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/hoverText",
                "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/speakScreen",
                "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/switchControl",
                "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/voiceControl",
                "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/voiceOver",
                "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityTechnology/zoom",
                "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilityRequest"
              ],
              "title": "Assistive technologies"
            },
            {
              "anchor": "Features",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/customized-accessibility-content",
                "doc://com.apple.Accessibility/documentation/Accessibility/audio-graphs",
                "doc://com.apple.Accessibility/documentation/Accessibility/braille-displays",
                "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXNameFromColor(_:)"
              ],
              "title": "Features"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1fullKeyboardAccess/title",
          "value": "AXTechnologyFullKeyboardAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1fullKeyboardAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXTechnologyFullKeyboardAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityRequest/title",
          "value": "AXRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology/title",
          "value": "AXTechnology"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXTechnology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXTechnology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1automation/title",
          "value": "AXTechnologyAutomation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1automation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXTechnologyAutomation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1zoom/title",
          "value": "AXTechnologyZoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1zoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXTechnologyZoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1voiceControl/title",
          "value": "AXTechnologyVoiceControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1voiceControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXTechnologyVoiceControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1hoverText/title",
          "value": "AXTechnologyHoverText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1hoverText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXTechnologyHoverText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1speakScreen/title",
          "value": "AXTechnologySpeakScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1speakScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXTechnologySpeakScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNameFromColor(_:)/title",
          "value": "AXNameFromColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNameFromColor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXNameFromColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1switchControl/title",
          "value": "AXTechnologySwitchControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1switchControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXTechnologySwitchControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1voiceOver/title",
          "value": "AXTechnologyVoiceOver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilityTechnology~1voiceOver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXTechnologyVoiceOver"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/accessibility-api"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/accessibility-api"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
