{
  "abstract": [
    {
      "text": "Improve navigation in your app by using keyboard shortcuts and accessibility containers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/accessibility_design_for_mac_catalyst"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Accessibility design for Mac Catalyst"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC20 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/videos/play/wwdc2020/10117/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "aa0c1c7a730c/AccessibilityDesignForMacCatalyst.zip": {
      "checksum": "aa0c1c7a730ce710e3c12db29ca5e9d1c881c3dfa6ed64e392a4f6431fd388dd2d2650f8a058eae821bc00d910cbf68574ee95f68ba3501841cb14782bdcb78a",
      "identifier": "aa0c1c7a730c/AccessibilityDesignForMacCatalyst.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/aa0c1c7a730c/AccessibilityDesignForMacCatalyst.zip"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/delivering_an_exceptional_accessibility_experience": {
      "abstract": [
        {
          "text": "Make improvements to your app’s interaction model to support assistive technologies such as VoiceOver.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/delivering_an_exceptional_accessibility_experience",
      "kind": "article",
      "role": "sampleCode",
      "title": "Delivering an exceptional accessibility experience",
      "type": "topic",
      "url": "/documentation/accessibility/delivering_an_exceptional_accessibility_experience"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/enhancing-the-accessibility-of-your-swiftui-app": {
      "abstract": [
        {
          "text": "Support advancements in SwiftUI accessibility to make your app accessible to everyone.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/enhancing-the-accessibility-of-your-swiftui-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Enhancing the accessibility of your SwiftUI app",
      "type": "topic",
      "url": "/documentation/accessibility/enhancing-the-accessibility-of-your-swiftui-app"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/integrating_accessibility_into_your_app": {
      "abstract": [
        {
          "text": "Make your app more accessible to users with disabilities by adding accessibility features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/integrating_accessibility_into_your_app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Integrating accessibility into your app",
      "type": "topic",
      "url": "/documentation/accessibility/integrating_accessibility_into_your_app"
    },
    "doc://com.apple.documentation/documentation/swiftui/creating_accessible_views": {
      "abstract": [
        {
          "text": "Make your app accessible to everyone by applying accessibility modifiers to your SwiftUI views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swiftui/creating_accessible_views",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating Accessible Views",
      "type": "topic",
      "url": "/documentation/swiftui/creating_accessible_views"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/videos/play/wwdc2020/10117/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2020/10117/",
      "title": "10117: Accessibility design for Mac Catalyst",
      "titleInlineContent": [
        {
          "text": "10117: Accessibility design for Mac Catalyst",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2020/10117/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "aa0c1c7a730c/AccessibilityDesignForMacCatalyst.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sample-code",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/enhancing-the-accessibility-of-your-swiftui-app",
        "doc://com.apple.documentation/documentation/swiftui/creating_accessible_views",
        "doc://com.apple.Accessibility/documentation/Accessibility/delivering_an_exceptional_accessibility_experience",
        "doc://com.apple.Accessibility/documentation/Accessibility/integrating_accessibility_into_your_app"
      ],
      "title": "Sample code"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sample-code",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/delivering_an_exceptional_accessibility_experience",
                "doc://com.apple.Accessibility/documentation/Accessibility/integrating_accessibility_into_your_app"
              ],
              "title": "Sample code"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/accessibility_design_for_mac_catalyst"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/accessibility_design_for_mac_catalyst"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
