{
  "abstract": [
    {
      "text": "A mode that tailors the iOS and iPadOS experience for people with cognitive disabilities.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/cognitive"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "images": [
      {
        "identifier": "assistive-access-card.png",
        "type": "card"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "Assistive Technology",
    "title": "Assistive Access"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Assistive Access is an accessibility feature that tailors the iOS and iPadOS experience for people with cognitive disabilities.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "A trusted supporter, such as a family member or caregiver, sets up this feature in Settings > Accessibility > Assistive Access.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "They choose the system and third-party apps to make available in Assistive Access.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "assistive-access",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Learn-to-use-Assistive-Access",
          "level": 4,
          "text": "Learn to use Assistive Access",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/guide/assistive-access-iphone/welcome/ios",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Related-videos",
          "level": 4,
          "text": "Related videos",
          "type": "heading"
        },
        {
          "items": [
            "doc://com.apple.documentation/videos/play/wwdc2023/10032"
          ],
          "style": "compactGrid",
          "type": "links"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "3BF48B60-4462-4461-BAB8-7E4A6224A2F5": {
      "alt": null,
      "identifier": "3BF48B60-4462-4461-BAB8-7E4A6224A2F5",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/3BF48B60-4462-4461-BAB8-7E4A6224A2F5/8060_wide_250x141_1x.jpg"
        },
        {
          "traits": [
            "2x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/3BF48B60-4462-4461-BAB8-7E4A6224A2F5/8060_wide_250x141_2x.jpg"
        },
        {
          "traits": [
            "3x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/3BF48B60-4462-4461-BAB8-7E4A6224A2F5/8060_wide_250x141_3x.jpg"
        }
      ]
    },
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "Performing-Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Performing-Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e051f9ccd83bfe36b3b3f6d9f40cbdb7/Performing-Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/aa888b2429f4c432b6746549abb24c55/Performing-Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "accessibility-card-cognitive.png": {
      "alt": "An illustration that shows a person standing and looking at an Apple Watch on their left wrist.",
      "identifier": "accessibility-card-cognitive.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e160ce0d82939c6b6866af282cc4bc9c/accessibility-card-cognitive@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3d882a73b0819d3d605fb78bda492908/accessibility-card-cognitive~dark@2x.png"
        }
      ]
    },
    "assistive-access": {
      "alt": "",
      "identifier": "assistive-access",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/74e17932b9b8096a565e7c9b884a798b/assistive-access@2x.png"
        }
      ]
    },
    "assistive-access-card.png": {
      "alt": null,
      "identifier": "assistive-access-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6a2ce2f33aac08a5727273235f9f0bb6/assistive-access-card@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/isAssistiveAccessEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether Assistive Access is running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAssistiveAccessEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/isAssistiveAccessEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXAssistiveAccessEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAssistiveAccessEnabled",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings/isassistiveaccessenabled"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies": {
      "abstract": [
        {
          "text": "Make sure your app provides a great experience for people who use assistive technologies.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Assistive technologies",
      "type": "topic",
      "url": "/documentation/accessibility/assistive-technologies"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/cognitive": {
      "abstract": [
        {
          "text": "A person may have difficulty remembering a sequence of steps, or they",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "may find an overly complex user interface difficult to process and manage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/cognitive",
      "images": [
        {
          "identifier": "accessibility-card-cognitive.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cognitive",
      "type": "topic",
      "url": "/documentation/accessibility/cognitive"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/optimizing-your-app-for-assistive-access": {
      "abstract": [
        {
          "text": "Adjust your app’s UI to make sure it works well for people who use Assistive Access.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/optimizing-your-app-for-assistive-access",
      "kind": "article",
      "role": "article",
      "title": "Optimizing your app for Assistive Access",
      "type": "topic",
      "url": "/documentation/accessibility/optimizing-your-app-for-assistive-access"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app": {
      "abstract": [
        {
          "text": "Test your app with accessibility settings and assistive technologies to discover and address accessibility issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app",
      "images": [
        {
          "identifier": "Performing-Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Performing accessibility testing for your app",
      "type": "topic",
      "url": "/documentation/accessibility/performing-accessibility-testing-for-your-app"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/switch-control": {
      "abstract": [
        {
          "text": "An interface for navigating a device with a variety of adaptive switch hardware, wireless game controllers, or sounds such as a click or a pop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/switch-control",
      "images": [
        {
          "identifier": "switch-control-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Switch Control",
      "type": "topic",
      "url": "/documentation/accessibility/switch-control"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/voice-control": {
      "abstract": [
        {
          "text": "An interface for navigating a device using voice commands to tap, swipe, type, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
      "images": [
        {
          "identifier": "voice-control-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Voice Control",
      "type": "topic",
      "url": "/documentation/accessibility/voice-control"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/voiceover": {
      "abstract": [
        {
          "text": "A gesture-based screen reader that provides an auditory description of the content onscreen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
      "images": [
        {
          "identifier": "voiceover-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "VoiceOver",
      "type": "topic",
      "url": "/documentation/accessibility/voiceover"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if an iOS or iPadOS app appears as full screen in Assistive Access.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess",
      "kind": "symbol",
      "role": "symbol",
      "title": "UISupportsFullScreenInAssistiveAccess",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/accessibilityAssistiveAccessEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether Assistive Access is in use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAssistiveAccessEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/accessibilityAssistiveAccessEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityAssistiveAccessEnabled",
      "type": "topic",
      "url": "/documentation/SwiftUI/EnvironmentValues/accessibilityAssistiveAccessEnabled"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/videos/play/wwdc2023/10032": {
      "abstract": [
        {
          "text": "Learn how Assistive Access can help people with cognitive disabilities more easily use iPhone and iPad. Discover the design principles that guide Assistive Access and find out how the system experience adapts to lighten cognitive load. We’ll show you how Assistive Access works and what you can do to support this experience in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/videos/play/wwdc2023/10032",
      "images": [
        {
          "identifier": "3BF48B60-4462-4461-BAB8-7E4A6224A2F5",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Meet Assistive Access",
      "type": "topic",
      "url": "https://developer.apple.com/videos/play/wwdc2023/10032"
    },
    "https://support.apple.com/guide/assistive-access-iphone/welcome/ios": {
      "identifier": "https://support.apple.com/guide/assistive-access-iphone/welcome/ios",
      "title": "Assistive Access User Guide",
      "titleInlineContent": [
        {
          "text": "Assistive Access User Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/assistive-access-iphone/welcome/ios"
    },
    "switch-control-card.png": {
      "alt": "",
      "identifier": "switch-control-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4b37322483b5831fc6a7e44fb9dc05b4/switch-control-card@2x.png"
        }
      ]
    },
    "voice-control-card.png": {
      "alt": "",
      "identifier": "voice-control-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9b9495b7277bc069208a522c435b7fc7/voice-control-card@2x.png"
        }
      ]
    },
    "voiceover-card.png": {
      "alt": "",
      "identifier": "voiceover-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6d02ab927e1e3865da0472d09dc3aae4/voiceover-card@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Assistive-technologies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
        "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
        "doc://com.apple.Accessibility/documentation/Accessibility/switch-control"
      ],
      "title": "Assistive technologies"
    }
  ],
  "topicSections": [
    {
      "anchor": "Develop-for-Assistive-Access",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/optimizing-your-app-for-assistive-access",
        "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/isAssistiveAccessEnabled",
        "doc://com.apple.documentation/documentation/SwiftUI/EnvironmentValues/accessibilityAssistiveAccessEnabled",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess"
      ],
      "title": "Develop for Assistive Access"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Develop-for-Assistive-Access",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/optimizing-your-app-for-assistive-access",
                "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app",
                "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/isAssistiveAccessEnabled",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess"
              ],
              "title": "Develop for Assistive Access"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Assistive-technologies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
                "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
                "doc://com.apple.Accessibility/documentation/Accessibility/switch-control"
              ],
              "title": "Assistive technologies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilitySettings~1isAssistiveAccessEnabled/title",
          "value": "AXAssistiveAccessEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilitySettings~1isAssistiveAccessEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXAssistiveAccessEnabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/assistive-access"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/assistive-access"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
