{
  "abstract": [
    {
      "text": "Make sure your app provides a great experience for people who use assistive technologies.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "Overview",
    "title": "Assistive technologies"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Everyone uses their devices differently.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Apple devices provide many assistive technologies",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to support people’s vision, hearing, speech, physical and motor, and learning needs.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "These assistive technologies provide alternative ways to navigate your app’s content,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "interact with your UI, and input data.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "When you design and build your app, it’s important to consider the full range of ways",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that people might use it rather than optimizing for just one use case.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Learn more about building and testing your app with assistive technologies to create a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "great experience for everyone.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "assistive-access-card.png": {
      "alt": "",
      "identifier": "assistive-access-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6a2ce2f33aac08a5727273235f9f0bb6/assistive-access-card@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access": {
      "abstract": [
        {
          "text": "A mode that tailors the iOS and iPadOS experience for people with cognitive disabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access",
      "images": [
        {
          "identifier": "assistive-access-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Assistive Access",
      "type": "topic",
      "url": "/documentation/accessibility/assistive-access"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/switch-control": {
      "abstract": [
        {
          "text": "An interface for navigating a device with a variety of adaptive switch hardware, wireless game controllers, or sounds such as a click or a pop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/switch-control",
      "images": [
        {
          "identifier": "switch-control-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Switch Control",
      "type": "topic",
      "url": "/documentation/accessibility/switch-control"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/voice-control": {
      "abstract": [
        {
          "text": "An interface for navigating a device using voice commands to tap, swipe, type, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
      "images": [
        {
          "identifier": "voice-control-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Voice Control",
      "type": "topic",
      "url": "/documentation/accessibility/voice-control"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/voiceover": {
      "abstract": [
        {
          "text": "A gesture-based screen reader that provides an auditory description of the content onscreen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
      "images": [
        {
          "identifier": "voiceover-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "VoiceOver",
      "type": "topic",
      "url": "/documentation/accessibility/voiceover"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "switch-control-card.png": {
      "alt": "",
      "identifier": "switch-control-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4b37322483b5831fc6a7e44fb9dc05b4/switch-control-card@2x.png"
        }
      ]
    },
    "voice-control-card.png": {
      "alt": "",
      "identifier": "voice-control-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9b9495b7277bc069208a522c435b7fc7/voice-control-card@2x.png"
        }
      ]
    },
    "voiceover-card.png": {
      "alt": "",
      "identifier": "voiceover-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6d02ab927e1e3865da0472d09dc3aae4/voiceover-card@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Assistive-technologies",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
        "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
        "doc://com.apple.Accessibility/documentation/Accessibility/switch-control",
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access"
      ],
      "title": "Assistive technologies"
    }
  ],
  "topicSectionsStyle": "detailedGrid",
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Assistive-technologies",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
                "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
                "doc://com.apple.Accessibility/documentation/Accessibility/switch-control",
                "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access"
              ],
              "title": "Assistive technologies"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/assistive-technologies"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/assistive-technologies"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
