{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpression"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AXMathExpression",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AXMathExpression"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AXMathExpression"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.2",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AXMathExpression"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AXMathExpression"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpression": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpression"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpression"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpression",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpression"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFenced": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionFenced"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFenced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionFenced"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionFenced",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionfenced"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFraction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionFraction"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionFraction"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionFraction",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionfraction"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionIdentifier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionIdentifier"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionIdentifier",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionidentifier"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionMultiscript": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionMultiscript"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionMultiscript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionMultiscript"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionMultiscript",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionmultiscript"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionNumber"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionNumber"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionNumber",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionnumber"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionOperator": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionOperator"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionOperator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionOperator"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionOperator",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionoperator"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRoot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionRoot"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRoot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionRoot"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionRoot",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionroot"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionRow"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionRow"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionRow",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionrow"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionSubSuperscript": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionSubSuperscript"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionSubSuperscript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionSubSuperscript"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionSubSuperscript",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionsubsuperscript"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionTable"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionTable"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionTable",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressiontable"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableCell": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionTableCell"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionTableCell"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionTableCell",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressiontablecell"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableRow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionTableRow"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionTableRow"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionTableRow",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressiontablerow"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionText": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionText"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionText"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionText",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressiontext"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionUnderOver": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMathExpressionUnderOver"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionUnderOver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMathExpressionUnderOver"
        }
      ],
      "role": "symbol",
      "title": "AXMathExpressionUnderOver",
      "type": "topic",
      "url": "/documentation/accessibility/axmathexpressionunderover"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFenced",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFraction",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionIdentifier",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionMultiscript",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionNumber",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionOperator",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRoot",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRow",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionSubSuperscript",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTable",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableCell",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableRow",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionText",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionUnderOver"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.2",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AXMathExpression"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Accessibility/documentation/Accessibility"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFenced",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionFraction",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionIdentifier",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionMultiscript",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionNumber",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionOperator",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRoot",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionRow",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionSubSuperscript",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTable",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableCell",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionTableRow",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionText",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXMathExpressionUnderOver"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AXMathExpression"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpression/title",
          "value": "AXMathExpression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpression/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionRoot/title",
          "value": "AXMathExpressionRoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionRoot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionRoot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionIdentifier/title",
          "value": "AXMathExpressionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionOperator/title",
          "value": "AXMathExpressionOperator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionOperator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionOperator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionOperator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionOperator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionSubSuperscript/title",
          "value": "AXMathExpressionSubSuperscript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionSubSuperscript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionSubSuperscript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionSubSuperscript/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionSubSuperscript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionRow/title",
          "value": "AXMathExpressionRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionRow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTableRow/title",
          "value": "AXMathExpressionTableRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTableRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionTableRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTableRow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionTableRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionNumber/title",
          "value": "AXMathExpressionNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionNumber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionUnderOver/title",
          "value": "AXMathExpressionUnderOver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionUnderOver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionUnderOver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionUnderOver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionUnderOver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionMultiscript/title",
          "value": "AXMathExpressionMultiscript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionMultiscript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionMultiscript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionMultiscript/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionMultiscript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTable/title",
          "value": "AXMathExpressionTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionFraction/title",
          "value": "AXMathExpressionFraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionFraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionFraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionFraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionFraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTableCell/title",
          "value": "AXMathExpressionTableCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTableCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionTableCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionTableCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionTableCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionText/title",
          "value": "AXMathExpressionText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionFenced/title",
          "value": "AXMathExpressionFenced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionFenced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionFenced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMathExpressionFenced/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMathExpressionFenced"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/axmathexpression"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/axmathexpression"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
