{
  "abstract": [
    {
      "text": "A namespace for hearing device accessibility symbols in Swift.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AXMFiHearingDevice",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AXMFiHearingDevice"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AXMFiHearingDevice"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AXMFiHearingDevice"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AXMFiHearingDevice"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice": {
      "abstract": [
        {
          "text": "A namespace for hearing device accessibility symbols in Swift.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXMFiHearingDevice"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMFiHearingDevice"
        }
      ],
      "role": "symbol",
      "title": "AXMFiHearingDevice",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear": {
      "abstract": [
        {
          "text": "Constants that represent a hearing device ear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Ear"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Ear"
        }
      ],
      "role": "symbol",
      "title": "AXMFiHearingDevice.Ear",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/ear"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/pairedDeviceIdentifiers()": {
      "abstract": [
        {
          "text": "Returns the UUIDs of the hearing device peripherals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pairedDeviceIdentifiers"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/pairedDeviceIdentifiers()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMFiHearingDevicePairedUUIDs"
        }
      ],
      "role": "symbol",
      "title": "pairedDeviceIdentifiers()",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/paireddeviceidentifiers()"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/pairedUUIDsDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that the system posts when there’s a change to the UUIDs of the hearing",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "device peripherals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pairedUUIDsDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/pairedUUIDsDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMFiHearingDevicePairedUUIDsDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "pairedUUIDsDidChangeNotification",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/paireduuidsdidchangenotification"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/streamingEar()": {
      "abstract": [
        {
          "text": "Returns which ears enable streaming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streamingEar"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AXMFiHearingDevice",
          "text": "AXMFiHearingDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXHearingDeviceEar",
          "text": "Ear"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/streamingEar()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMFiHearingDeviceStreamingEar"
        }
      ],
      "role": "symbol",
      "title": "streamingEar()",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/streamingear()"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/streamingEarDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that the system posts when there’s a change to which ears enable streaming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streamingEarDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/streamingEarDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXMFiHearingDeviceStreamingEarDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "streamingEarDidChangeNotification",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/streamingeardidchangenotification"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/supportsBidirectionalStreaming()": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the iOS device supports bidirectional",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "streaming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsBidirectionalStreaming"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/supportsBidirectionalStreaming()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXSupportsBidirectionalAXMFiHearingDeviceStreaming"
        }
      ],
      "role": "symbol",
      "title": "supportsBidirectionalStreaming()",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/supportsbidirectionalstreaming()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Streaming-status",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/streamingEar()",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/streamingEarDidChangeNotification"
      ],
      "title": "Streaming status"
    },
    {
      "anchor": "Streaming-type",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/supportsBidirectionalStreaming()"
      ],
      "title": "Streaming type"
    },
    {
      "anchor": "Paired-hearing-devices",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/pairedDeviceIdentifiers()",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/pairedUUIDsDidChangeNotification"
      ],
      "title": "Paired hearing devices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1pairedUUIDsDidChangeNotification/title",
          "value": "AXMFiHearingDevicePairedUUIDsDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1pairedUUIDsDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMFiHearingDevicePairedUUIDsDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1streamingEarDidChangeNotification/title",
          "value": "AXMFiHearingDeviceStreamingEarDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1streamingEarDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMFiHearingDeviceStreamingEarDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1streamingEar()/title",
          "value": "AXMFiHearingDeviceStreamingEar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1streamingEar()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMFiHearingDeviceStreamingEar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1supportsBidirectionalStreaming()/title",
          "value": "AXSupportsBidirectionalAXMFiHearingDeviceStreaming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1supportsBidirectionalStreaming()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXSupportsBidirectionalAXMFiHearingDeviceStreaming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1pairedDeviceIdentifiers()/title",
          "value": "AXMFiHearingDevicePairedUUIDs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1pairedDeviceIdentifiers()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXMFiHearingDevicePairedUUIDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear/title",
          "value": "AXHearingDeviceEar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXHearingDeviceEar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXHearingDeviceEar"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/axmfihearingdevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
