{
  "abstract": [
    {
      "text": "An object that represents an axis of numerical data.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AXNumericDataAxisDescriptor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AXNumericDataAxisDescriptor"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AXNumericDataAxisDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AXNumericDataAxisDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AXNumericDataAxisDescriptor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXCategoricalDataAxisDescriptor": {
      "abstract": [
        {
          "text": "An object that represents an axis of categorical data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXCategoricalDataAxisDescriptor"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXCategoricalDataAxisDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXCategoricalDataAxisDescriptor"
        }
      ],
      "role": "symbol",
      "title": "AXCategoricalDataAxisDescriptor",
      "type": "topic",
      "url": "/documentation/accessibility/axcategoricaldataaxisdescriptor"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXDataAxisDescriptor": {
      "abstract": [
        {
          "text": "The basic interface for a data axis in a chart.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXDataAxisDescriptor"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXDataAxisDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXDataAxisDescriptor"
        }
      ],
      "role": "symbol",
      "title": "AXDataAxisDescriptor",
      "type": "topic",
      "url": "/documentation/accessibility/axdataaxisdescriptor"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor": {
      "abstract": [
        {
          "text": "An object that represents an axis of numerical data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXNumericDataAxisDescriptor"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXNumericDataAxisDescriptor"
        }
      ],
      "role": "symbol",
      "title": "AXNumericDataAxisDescriptor",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the scale of a numeric axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScaleType"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScaleType"
        }
      ],
      "role": "symbol",
      "title": "AXNumericDataAxisDescriptor.ScaleType",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/scaletype-swift.enum"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/gridlinePositions-5cfmw": {
      "abstract": [
        {
          "text": "The positions of the gridlines along the axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gridlinePositions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/gridlinePositions-5cfmw",
      "kind": "symbol",
      "role": "symbol",
      "title": "gridlinePositions",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/gridlinepositions-5cfmw"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/gridlinePositions-9z10e": {
      "abstract": [
        {
          "text": "The positions of the gridlines along the axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "gridlinePositions"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/gridlinePositions-9z10e",
      "kind": "symbol",
      "role": "symbol",
      "title": "gridlinePositions",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/gridlinepositions-9z10e"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/init(attributedTitle:range:gridlinePositions:valueDescriptionProvider:)": {
      "abstract": [
        {
          "text": "Creates a numeric data axis with the specified attributed title, range, gridline",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "positions, and value description provider closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "attributedTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SN",
          "text": "ClosedRange"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "gridlinePositions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "valueDescriptionProvider"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/init(attributedTitle:range:gridlinePositions:valueDescriptionProvider:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(attributedTitle:range:gridlinePositions:valueDescriptionProvider:)",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/init(attributedtitle:range:gridlinepositions:valuedescriptionprovider:)"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/init(title:range:gridlinePositions:valueDescriptionProvider:)": {
      "abstract": [
        {
          "text": "Creates a numeric data axis with the specified title, range, gridline positions,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and value description provider closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SN",
          "text": "ClosedRange"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "gridlinePositions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "valueDescriptionProvider"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/init(title:range:gridlinePositions:valueDescriptionProvider:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(title:range:gridlinePositions:valueDescriptionProvider:)",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/init(title:range:gridlinepositions:valuedescriptionprovider:)"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/initWithAttributedTitle:lowerBound:upperBound:gridlinePositions:valueDescriptionProvider:": {
      "abstract": [
        {
          "text": "Creates a numeric data axis with the specified attributed title, lower bound value,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "upper bound value, gridline positions, and value description provider block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithAttributedTitle:lowerBound:upperBound:gridlinePositions:valueDescriptionProvider:"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/initWithAttributedTitle:lowerBound:upperBound:gridlinePositions:valueDescriptionProvider:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAttributedTitle:lowerBound:upperBound:gridlinePositions:valueDescriptionProvider:"
        }
      ],
      "role": "symbol",
      "title": "initWithAttributedTitle:lowerBound:upperBound:gridlinePositions:valueDescriptionProvider:",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/initwithattributedtitle:lowerbound:upperbound:gridlinepositions:valuedescriptionprovider:"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/initWithTitle:lowerBound:upperBound:gridlinePositions:valueDescriptionProvider:": {
      "abstract": [
        {
          "text": "Creates a numeric data axis with the specified title, lower bound value, upper bound",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "value, gridline positions, and value description provider block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTitle:lowerBound:upperBound:gridlinePositions:valueDescriptionProvider:"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/initWithTitle:lowerBound:upperBound:gridlinePositions:valueDescriptionProvider:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTitle:lowerBound:upperBound:gridlinePositions:valueDescriptionProvider:"
        }
      ],
      "role": "symbol",
      "title": "initWithTitle:lowerBound:upperBound:gridlinePositions:valueDescriptionProvider:",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/initwithtitle:lowerbound:upperbound:gridlinepositions:valuedescriptionprovider:"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/lowerBound": {
      "abstract": [
        {
          "text": "The minimum displayable value for the axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "lowerBound"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/lowerBound",
      "kind": "symbol",
      "role": "symbol",
      "title": "lowerBound",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/lowerbound"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/range": {
      "abstract": [
        {
          "text": "A range that defines the minimum and maximum displayable values for the axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SN",
          "text": "ClosedRange"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/range",
      "kind": "symbol",
      "role": "symbol",
      "title": "range",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/range"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/scaleType-swift.property": {
      "abstract": [
        {
          "text": "The scale for the axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXNumericDataAxisDescriptor",
          "text": "AXNumericDataAxisDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXNumericDataAxisDescriptorScale",
          "text": "ScaleType"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/scaleType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaleType"
        }
      ],
      "role": "symbol",
      "title": "scaleType",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/scaletype-swift.property"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/upperBound": {
      "abstract": [
        {
          "text": "The maximum displayable value for the axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "upperBound"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/upperBound",
      "kind": "symbol",
      "role": "symbol",
      "title": "upperBound",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/upperbound"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/valueDescriptionProvider": {
      "abstract": [
        {
          "text": "A description to speak for a particular data value on the axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valueDescriptionProvider"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/valueDescriptionProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueDescriptionProvider"
        }
      ],
      "role": "symbol",
      "title": "valueDescriptionProvider",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/valuedescriptionprovider"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXDataAxisDescriptor",
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Axis-representation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXDataAxisDescriptor",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXCategoricalDataAxisDescriptor"
      ],
      "title": "Axis representation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-numeric-data-axis",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/init(title:range:gridlinePositions:valueDescriptionProvider:)",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/init(attributedTitle:range:gridlinePositions:valueDescriptionProvider:)"
      ],
      "title": "Creating a numeric data axis"
    },
    {
      "anchor": "Specifying-the-value-description",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/valueDescriptionProvider"
      ],
      "title": "Specifying the value description"
    },
    {
      "anchor": "Configuring-the-axis-scale",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/scaleType-swift.property",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum"
      ],
      "title": "Configuring the axis scale"
    },
    {
      "anchor": "Configuring-the-axis-range",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/range"
      ],
      "title": "Configuring the axis range"
    },
    {
      "anchor": "Configuring-the-gridlines",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/gridlinePositions-5cfmw"
      ],
      "title": "Configuring the gridlines"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AXNumericDataAxisDescriptor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXNumericDataAxisDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXNumericDataAxisDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Accessibility/documentation/Accessibility"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-numeric-data-axis",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/initWithTitle:lowerBound:upperBound:gridlinePositions:valueDescriptionProvider:",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/initWithAttributedTitle:lowerBound:upperBound:gridlinePositions:valueDescriptionProvider:"
              ],
              "title": "Creating a numeric data axis"
            },
            {
              "anchor": "Specifying-the-value-description",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/valueDescriptionProvider"
              ],
              "title": "Specifying the value description"
            },
            {
              "anchor": "Configuring-the-axis-scale",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/scaleType-swift.property",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum"
              ],
              "title": "Configuring the axis scale"
            },
            {
              "anchor": "Configuring-the-axis-range",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/lowerBound",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/upperBound"
              ],
              "title": "Configuring the axis range"
            },
            {
              "anchor": "Configuring-the-gridlines",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/gridlinePositions-9z10e"
              ],
              "title": "Configuring the gridlines"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXDataAxisDescriptor"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Axis-representation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXDataAxisDescriptor",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXCategoricalDataAxisDescriptor"
              ],
              "title": "Axis representation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AXNumericDataAxisDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataAxisDescriptor/title",
          "value": "AXDataAxisDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataAxisDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXDataAxisDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXDataAxisDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXDataAxisDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor/title",
          "value": "AXNumericDataAxisDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXNumericDataAxisDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXNumericDataAxisDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1ScaleType-swift.enum/title",
          "value": "AXNumericDataAxisDescriptorScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1ScaleType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXNumericDataAxisDescriptorScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1ScaleType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXNumericDataAxisDescriptorScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCategoricalDataAxisDescriptor/title",
          "value": "AXCategoricalDataAxisDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCategoricalDataAxisDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXCategoricalDataAxisDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCategoricalDataAxisDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXCategoricalDataAxisDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1valueDescriptionProvider/title",
          "value": "valueDescriptionProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1valueDescriptionProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "valueDescriptionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1scaleType-swift.property/title",
          "value": "scaleType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1scaleType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaleType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/axnumericdataaxisdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/axnumericdataaxisdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
