{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/AXOpenSettingsFeature"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@AXOpenSettingsFeature",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AXOpenSettingsFeature"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AXOpenSettingsFeature"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "AXOpenSettingsFeature"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AXOpenSettingsFeature"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/Feature",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AXSettingsFeature",
              "text": "AXSettingsFeature"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "feature"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^"
            },
            {
              "kind": "internalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ")("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": "));"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXAnimatedImagesEnabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXAnimatedImagesEnabled"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXAnimatedImagesEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXAnimatedImagesEnabled",
      "type": "topic",
      "url": "/documentation/accessibility/axanimatedimagesenabled"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXAnimatedImagesEnabledDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXAnimatedImagesEnabledDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXAnimatedImagesEnabledDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXAnimatedImagesEnabledDidChangeNotification",
      "type": "topic",
      "url": "/documentation/accessibility/axanimatedimagesenableddidchangenotification"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXOpenSettingsFeature": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXOpenSettingsFeature"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXOpenSettingsFeature",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXOpenSettingsFeature",
      "type": "topic",
      "url": "/documentation/accessibility/axopensettingsfeature"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHeadAnchorAlternative": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXPrefersHeadAnchorAlternative"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHeadAnchorAlternative",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXPrefersHeadAnchorAlternative",
      "type": "topic",
      "url": "/documentation/accessibility/axprefersheadanchoralternative"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHeadAnchorAlternativeDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXPrefersHeadAnchorAlternativeDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHeadAnchorAlternativeDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXPrefersHeadAnchorAlternativeDidChangeNotification",
      "type": "topic",
      "url": "/documentation/accessibility/axprefersheadanchoralternativedidchangenotification"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHorizontalTextLayout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXPrefersHorizontalTextLayout"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHorizontalTextLayout",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXPrefersHorizontalTextLayout",
      "type": "topic",
      "url": "/documentation/accessibility/axprefershorizontaltextlayout"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHorizontalTextLayoutDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXPrefersHorizontalTextLayoutDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHorizontalTextLayoutDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXPrefersHorizontalTextLayoutDidChangeNotification",
      "type": "topic",
      "url": "/documentation/accessibility/axprefershorizontaltextlayoutdidchangenotification"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersNonBlinkingTextInsertionIndicator": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXPrefersNonBlinkingTextInsertionIndicator"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersNonBlinkingTextInsertionIndicator",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXPrefersNonBlinkingTextInsertionIndicator",
      "type": "topic",
      "url": "/documentation/accessibility/axprefersnonblinkingtextinsertionindicator"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/Feature": {
      "abstract": [
        {
          "text": "Constants that describe specific Accessibility settings in the Settings app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Feature"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/Feature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Feature"
        }
      ],
      "role": "symbol",
      "title": "AccessibilitySettings.Feature",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings/feature"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "System-settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXAnimatedImagesEnabled",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXAnimatedImagesEnabledDidChangeNotification",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHorizontalTextLayout",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHorizontalTextLayoutDidChangeNotification",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHeadAnchorAlternative",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersHeadAnchorAlternativeDidChangeNotification",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXPrefersNonBlinkingTextInsertionIndicator"
      ],
      "title": "System settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilitySettings~1Feature/title",
          "value": "AXSettingsFeature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilitySettings~1Feature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXSettingsFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilitySettings~1Feature/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXSettingsFeature"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/axopensettingsfeature"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
