{
  "abstract": [
    {
      "text": "Display a graphical representation of images, icons, data, and more on a two-dimensional",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "braille display.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-api"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/braille-displays"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Braille displays"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A refreshable braille display is a hardware device that shows rows of pins that can",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "raise and lower. People who are blind or deafblind use these devices to read digital",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "content through interaction with a screenreader, such as VoiceOver. For information",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "about connecting a braille display to an Apple device, read ",
              "type": "text"
            },
            {
              "identifier": "https://support.apple.com/guide/iphone/use-a-braille-display-iph73b8c43/ios",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A two-dimensional refreshable braille display has a grid of evenly spaced pins that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you can use to represent images, charts, and other visual data to VoiceOver users",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "so they can experience your content through touch.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "accessibility-card-vision.png": {
      "alt": "An illustration that shows a person with low vision walking with the assistance of a guide dog while using an iPhone and AirPods.",
      "identifier": "accessibility-card-vision.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/11631c0b01fa73cc082557dc6067840e/accessibility-card-vision@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/624a8a2e8a195d6785905c00a619d3ac/accessibility-card-vision~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXBrailleMap": {
      "abstract": [
        {
          "text": "A representation of a two-dimensional braille display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXBrailleMap"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXBrailleMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXBrailleMap"
        }
      ],
      "role": "symbol",
      "title": "AXBrailleMap",
      "type": "topic",
      "url": "/documentation/accessibility/axbraillemap"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXBrailleMapRenderer": {
      "abstract": [
        {
          "text": "The interface for providing data for a braille map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXBrailleMapRenderer"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXBrailleMapRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXBrailleMapRenderer"
        }
      ],
      "role": "symbol",
      "title": "AXBrailleMapRenderer",
      "type": "topic",
      "url": "/documentation/accessibility/axbraillemaprenderer"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNameFromColor(_:)": {
      "abstract": [
        {
          "text": "Returns a localized description of the color to use in accessibility attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXNameFromColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNameFromColor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXNameFromColor"
        }
      ],
      "role": "symbol",
      "title": "AXNameFromColor(_:)",
      "type": "topic",
      "url": "/documentation/accessibility/axnamefromcolor(_:)"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-api": {
      "abstract": [
        {
          "text": "Browse API in the Accessibility framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility API",
      "type": "topic",
      "url": "/documentation/accessibility/accessibility-api"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/audio-graphs": {
      "abstract": [
        {
          "text": "Define an accessible representation of your chart for VoiceOver to generate an audio",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "graph.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/audio-graphs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio graphs",
      "type": "topic",
      "url": "/documentation/accessibility/audio-graphs"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/customized-accessibility-content": {
      "abstract": [
        {
          "text": "Customize your apps to deliver accessibility information to your users in measured",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "portions as they need it.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/customized-accessibility-content",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Customized accessibility content",
      "type": "topic",
      "url": "/documentation/accessibility/customized-accessibility-content"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support": {
      "abstract": [
        {
          "text": "Access information about paired hearing aid devices and streaming status.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Hearing device support",
      "type": "topic",
      "url": "/documentation/accessibility/hearing-device-support"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/vision": {
      "abstract": [
        {
          "text": "A person may be blind or color blind, or have a vision challenge that",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "makes focusing difficult.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/vision",
      "images": [
        {
          "identifier": "accessibility-card-vision.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/accessibility/vision"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://support.apple.com/guide/iphone/use-a-braille-display-iph73b8c43/ios": {
      "identifier": "https://support.apple.com/guide/iphone/use-a-braille-display-iph73b8c43/ios",
      "title": "Use a braille display with VoiceOver on iPhone",
      "titleInlineContent": [
        {
          "text": "Use a braille display",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "with VoiceOver on iPhone",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/iphone/use-a-braille-display-iph73b8c43/ios"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Features",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/customized-accessibility-content",
        "doc://com.apple.Accessibility/documentation/Accessibility/audio-graphs",
        "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXNameFromColor(_:)"
      ],
      "title": "Features"
    }
  ],
  "topicSections": [
    {
      "anchor": "Braille-maps",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXBrailleMap",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXBrailleMapRenderer"
      ],
      "title": "Braille maps"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Braille-maps",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXBrailleMap",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXBrailleMapRenderer"
              ],
              "title": "Braille maps"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Features",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/customized-accessibility-content",
                "doc://com.apple.Accessibility/documentation/Accessibility/audio-graphs",
                "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXNameFromColor(_:)"
              ],
              "title": "Features"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNameFromColor(_:)/title",
          "value": "AXNameFromColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNameFromColor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXNameFromColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXBrailleMapRenderer/title",
          "value": "AXBrailleMapRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXBrailleMapRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXBrailleMapRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXBrailleMapRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXBrailleMapRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXBrailleMap/title",
          "value": "AXBrailleMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXBrailleMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXBrailleMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXBrailleMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXBrailleMap"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/braille-displays"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/braille-displays"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
