{
  "abstract": [
    {
      "text": "A person may have difficulty remembering a sequence of steps, or they",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "may find an overly complex user interface difficult to process and manage.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/cognitive"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "images": [
      {
        "identifier": "accessibility-card-cognitive.png",
        "type": "card"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Cognitive"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "People who have cognitive impairments or challenges with maintaining focus",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "can use Apple’s cognitive accessibility features",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to stay focused, streamline tasks, or limit the number of decisions to make.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Design and develop your app to support cognitive accessibility features and provide a great experience",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for people who rely on these features.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "accessibility-scene-cognitive",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Related-videos",
          "level": 3,
          "text": "Related videos",
          "type": "heading"
        },
        {
          "items": [
            "doc://com.apple.documentation/videos/play/wwdc2023/10032"
          ],
          "style": "compactGrid",
          "type": "links"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "3BF48B60-4462-4461-BAB8-7E4A6224A2F5": {
      "alt": null,
      "identifier": "3BF48B60-4462-4461-BAB8-7E4A6224A2F5",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/3BF48B60-4462-4461-BAB8-7E4A6224A2F5/8060_wide_250x141_1x.jpg"
        },
        {
          "traits": [
            "2x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/3BF48B60-4462-4461-BAB8-7E4A6224A2F5/8060_wide_250x141_2x.jpg"
        },
        {
          "traits": [
            "3x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/D35E0E85-CCB6-41A1-B227-7995ECD83ED5/3BF48B60-4462-4461-BAB8-7E4A6224A2F5/8060_wide_250x141_3x.jpg"
        }
      ]
    },
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "accessibility-card-cognitive.png": {
      "alt": null,
      "identifier": "accessibility-card-cognitive.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e160ce0d82939c6b6866af282cc4bc9c/accessibility-card-cognitive@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3d882a73b0819d3d605fb78bda492908/accessibility-card-cognitive~dark@2x.png"
        }
      ]
    },
    "accessibility-card-hearing.png": {
      "alt": "An illustration that shows a person wearing a hearing aid and a camping backpack. The person is walking and using an iPhone.",
      "identifier": "accessibility-card-hearing.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/08122f4b2e9f57caf30f8e244ccd3dfe/accessibility-card-hearing@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/db59daa0db79629fb85282bf8a9e4908/accessibility-card-hearing~dark@2x.png"
        }
      ]
    },
    "accessibility-card-mobility.png": {
      "alt": "An illustration that shows a person in a wheelchair using a MacBook in their lap.",
      "identifier": "accessibility-card-mobility.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c55383b0bf084116e82d7e4aba87c3cc/accessibility-card-mobility@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d0ce2da05b4c6805e5c3f5862222b099/accessibility-card-mobility~dark@2x.png"
        }
      ]
    },
    "accessibility-card-speech.png": {
      "alt": "An illustration that shows a person in an electric wheelchair sitting at a desk and using speech synthesis features on a Mac.",
      "identifier": "accessibility-card-speech.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c1f425b12f45643f5a126e3852ab9d76/accessibility-card-speech@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5655a5854b8b46288245fde1cd517f97/accessibility-card-speech~dark@2x.png"
        }
      ]
    },
    "accessibility-card-vision.png": {
      "alt": "An illustration that shows a person with low vision walking with the assistance of a guide dog while using an iPhone and AirPods.",
      "identifier": "accessibility-card-vision.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/11631c0b01fa73cc082557dc6067840e/accessibility-card-vision@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/624a8a2e8a195d6785905c00a619d3ac/accessibility-card-vision~dark@2x.png"
        }
      ]
    },
    "accessibility-scene-cognitive": {
      "alt": "An illustration that shows a a person in a room with an easel, desk, lamp, computer chair, Mac, and their pet cat. The person is holding a paintbrush and painting while wearing AirPods to maintain focus on their task.",
      "identifier": "accessibility-scene-cognitive",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e9d29f6acd65c88746859f7e48fea15a/accessibility-scene-cognitive@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e2f3a880ab206cae71ad809fb073f028/accessibility-scene-cognitive~dark@2x.png"
        }
      ]
    },
    "assistive-access-card.png": {
      "alt": "",
      "identifier": "assistive-access-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6a2ce2f33aac08a5727273235f9f0bb6/assistive-access-card@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/isAssistiveAccessEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether Assistive Access is running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAssistiveAccessEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/isAssistiveAccessEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXAssistiveAccessEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAssistiveAccessEnabled",
      "type": "topic",
      "url": "/documentation/accessibility/accessibilitysettings/isassistiveaccessenabled"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access": {
      "abstract": [
        {
          "text": "A mode that tailors the iOS and iPadOS experience for people with cognitive disabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access",
      "images": [
        {
          "identifier": "assistive-access-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Assistive Access",
      "type": "topic",
      "url": "/documentation/accessibility/assistive-access"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/hearing": {
      "abstract": [
        {
          "text": "A person may be deaf, have partial hearing loss, or have difficulty hearing",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "sounds within a certain range.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/hearing",
      "images": [
        {
          "identifier": "accessibility-card-hearing.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Hearing",
      "type": "topic",
      "url": "/documentation/accessibility/hearing"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/mobility": {
      "abstract": [
        {
          "text": "A person with reduced mobility may have difficulty holding a device",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "or tapping the interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/mobility",
      "images": [
        {
          "identifier": "accessibility-card-mobility.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mobility",
      "type": "topic",
      "url": "/documentation/accessibility/mobility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/speech": {
      "abstract": [
        {
          "text": "A person may have a speech disability or prefer to connect without using their voice.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/speech",
      "images": [
        {
          "identifier": "accessibility-card-speech.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Speech",
      "type": "topic",
      "url": "/documentation/accessibility/speech"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/vision": {
      "abstract": [
        {
          "text": "A person may be blind or color blind, or have a vision challenge that",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "makes focusing difficult.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/vision",
      "images": [
        {
          "identifier": "accessibility-card-vision.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/accessibility/vision"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if an iOS or iPadOS app appears as full screen in Assistive Access.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess",
      "kind": "symbol",
      "role": "symbol",
      "title": "UISupportsFullScreenInAssistiveAccess",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/videos/play/wwdc2023/10032": {
      "abstract": [
        {
          "text": "Learn how Assistive Access can help people with cognitive disabilities more easily use iPhone and iPad. Discover the design principles that guide Assistive Access and find out how the system experience adapts to lighten cognitive load. We’ll show you how Assistive Access works and what you can do to support this experience in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/videos/play/wwdc2023/10032",
      "images": [
        {
          "identifier": "3BF48B60-4462-4461-BAB8-7E4A6224A2F5",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Meet Assistive Access",
      "type": "topic",
      "url": "https://developer.apple.com/videos/play/wwdc2023/10032"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Domains",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/vision",
        "doc://com.apple.Accessibility/documentation/Accessibility/speech",
        "doc://com.apple.Accessibility/documentation/Accessibility/mobility",
        "doc://com.apple.Accessibility/documentation/Accessibility/hearing"
      ],
      "title": "Domains"
    }
  ],
  "topicSections": [
    {
      "anchor": "Supporting-cognitive-accessibility-features",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access",
        "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/isAssistiveAccessEnabled",
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess"
      ],
      "title": "Supporting cognitive accessibility features"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Supporting-cognitive-accessibility-features",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access",
                "doc://com.apple.Accessibility/documentation/Accessibility/AccessibilitySettings/isAssistiveAccessEnabled",
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsFullScreenInAssistiveAccess"
              ],
              "title": "Supporting cognitive accessibility features"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Domains",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/vision",
                "doc://com.apple.Accessibility/documentation/Accessibility/speech",
                "doc://com.apple.Accessibility/documentation/Accessibility/mobility",
                "doc://com.apple.Accessibility/documentation/Accessibility/hearing"
              ],
              "title": "Domains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilitySettings~1isAssistiveAccessEnabled/title",
          "value": "AXAssistiveAccessEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AccessibilitySettings~1isAssistiveAccessEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXAssistiveAccessEnabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/cognitive"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/cognitive"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
