{
  "abstract": [
    {
      "text": "Customize your apps to deliver accessibility information to your users in measured",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "portions as they need it.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/customized-accessibility-content"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Customized accessibility content"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Custom Content API is useful for delivering accessibility information from complex",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "data sets to your users in measured portions. Using this API allows you to leverage",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "assistive technologies to present only the accessible content your app’s users need,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "when they need it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, in a photography app, you may want the user to know the date, time,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "orientation, and shutter speed for a photo. However, the user might not always need",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that complete set of information. Using the custom content provider in your app lets",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the user experience the content in way that’s more appropriate for an assistive technology.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent": {
      "abstract": [
        {
          "text": "Objects that define custom content and the timing of its output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXCustomContent"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXCustomContent"
        }
      ],
      "role": "symbol",
      "title": "AXCustomContent",
      "type": "topic",
      "url": "/documentation/accessibility/axcustomcontent"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContentProvider": {
      "abstract": [
        {
          "text": "The interface for customizing the accessibility content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXCustomContentProvider"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContentProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXCustomContentProvider"
        }
      ],
      "role": "symbol",
      "title": "AXCustomContentProvider",
      "type": "topic",
      "url": "/documentation/accessibility/axcustomcontentprovider"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContentReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXCustomContentReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContentReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXCustomContentReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXCustomContentReturnBlock",
      "type": "topic",
      "url": "/documentation/accessibility/axcustomcontentreturnblock"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNameFromColor(_:)": {
      "abstract": [
        {
          "text": "Returns a localized description of the color to use in accessibility attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXNameFromColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNameFromColor(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXNameFromColor"
        }
      ],
      "role": "symbol",
      "title": "AXNameFromColor(_:)",
      "type": "topic",
      "url": "/documentation/accessibility/axnamefromcolor(_:)"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-api": {
      "abstract": [
        {
          "text": "Browse API in the Accessibility framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility API",
      "type": "topic",
      "url": "/documentation/accessibility/accessibility-api"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/audio-graphs": {
      "abstract": [
        {
          "text": "Define an accessible representation of your chart for VoiceOver to generate an audio",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "graph.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/audio-graphs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio graphs",
      "type": "topic",
      "url": "/documentation/accessibility/audio-graphs"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/braille-displays": {
      "abstract": [
        {
          "text": "Display a graphical representation of images, icons, data, and more on a two-dimensional",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "braille display.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/braille-displays",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Braille displays",
      "type": "topic",
      "url": "/documentation/accessibility/braille-displays"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support": {
      "abstract": [
        {
          "text": "Access information about paired hearing aid devices and streaming status.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Hearing device support",
      "type": "topic",
      "url": "/documentation/accessibility/hearing-device-support"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Features",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/audio-graphs",
        "doc://com.apple.Accessibility/documentation/Accessibility/braille-displays",
        "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXNameFromColor(_:)"
      ],
      "title": "Features"
    }
  ],
  "topicSections": [
    {
      "anchor": "Custom-accessibility-content",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContentProvider",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContentReturnBlock"
      ],
      "title": "Custom accessibility content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Custom-accessibility-content",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContent",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContentProvider",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXCustomContentReturnBlock"
              ],
              "title": "Custom accessibility content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Features",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/audio-graphs",
                "doc://com.apple.Accessibility/documentation/Accessibility/braille-displays",
                "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXNameFromColor(_:)"
              ],
              "title": "Features"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent/title",
          "value": "AXCustomContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXCustomContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXCustomContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContentProvider/title",
          "value": "AXCustomContentProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContentProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXCustomContentProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContentProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXCustomContentProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContentReturnBlock/title",
          "value": "AXCustomContentReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContentReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXCustomContentReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXCustomContentReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXCustomContentReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNameFromColor(_:)/title",
          "value": "AXNameFromColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNameFromColor(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXNameFromColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/customized-accessibility-content"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/customized-accessibility-content"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
