{
  "abstract": [
    {
      "text": "A person may be deaf, have partial hearing loss, or have difficulty hearing",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "sounds within a certain range.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/hearing"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "images": [
      {
        "identifier": "accessibility-card-hearing.png",
        "type": "card"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "role": "collectionGroup",
    "title": "Hearing"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "People who are who are deaf or hard of hearing",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "can use Apple’s hearing accessibility features",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to use hearing devices, enhance the sounds they hear, and filter out extraneous noises.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Design and develop your app to support hearing accessibility features and provide a great experience",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for people who rely on these features.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "accessibility-scene-hearing",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "accessibility-card-cognitive.png": {
      "alt": "An illustration that shows a person standing and looking at an Apple Watch on their left wrist.",
      "identifier": "accessibility-card-cognitive.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e160ce0d82939c6b6866af282cc4bc9c/accessibility-card-cognitive@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3d882a73b0819d3d605fb78bda492908/accessibility-card-cognitive~dark@2x.png"
        }
      ]
    },
    "accessibility-card-hearing.png": {
      "alt": null,
      "identifier": "accessibility-card-hearing.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/08122f4b2e9f57caf30f8e244ccd3dfe/accessibility-card-hearing@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/db59daa0db79629fb85282bf8a9e4908/accessibility-card-hearing~dark@2x.png"
        }
      ]
    },
    "accessibility-card-mobility.png": {
      "alt": "An illustration that shows a person in a wheelchair using a MacBook in their lap.",
      "identifier": "accessibility-card-mobility.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c55383b0bf084116e82d7e4aba87c3cc/accessibility-card-mobility@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d0ce2da05b4c6805e5c3f5862222b099/accessibility-card-mobility~dark@2x.png"
        }
      ]
    },
    "accessibility-card-speech.png": {
      "alt": "An illustration that shows a person in an electric wheelchair sitting at a desk and using speech synthesis features on a Mac.",
      "identifier": "accessibility-card-speech.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c1f425b12f45643f5a126e3852ab9d76/accessibility-card-speech@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5655a5854b8b46288245fde1cd517f97/accessibility-card-speech~dark@2x.png"
        }
      ]
    },
    "accessibility-card-vision.png": {
      "alt": "An illustration that shows a person with low vision walking with the assistance of a guide dog while using an iPhone and AirPods.",
      "identifier": "accessibility-card-vision.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/11631c0b01fa73cc082557dc6067840e/accessibility-card-vision@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/624a8a2e8a195d6785905c00a619d3ac/accessibility-card-vision~dark@2x.png"
        }
      ]
    },
    "accessibility-scene-hearing": {
      "alt": "An illustration that shows a person in a home office with a chair, desk, mug, potted plant, and Mac. The person is wearing a hearing aid and communicating using sign language to another participant on a video call on their Mac.",
      "identifier": "accessibility-scene-hearing",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cf1fe90f1d9abd375c780881eceb71ce/accessibility-scene-hearing@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/16805b720db143037a2c7ec1b676f0a6/accessibility-scene-hearing~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/cognitive": {
      "abstract": [
        {
          "text": "A person may have difficulty remembering a sequence of steps, or they",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "may find an overly complex user interface difficult to process and manage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/cognitive",
      "images": [
        {
          "identifier": "accessibility-card-cognitive.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cognitive",
      "type": "topic",
      "url": "/documentation/accessibility/cognitive"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support": {
      "abstract": [
        {
          "text": "Access information about paired hearing aid devices and streaming status.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Hearing device support",
      "type": "topic",
      "url": "/documentation/accessibility/hearing-device-support"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/mobility": {
      "abstract": [
        {
          "text": "A person with reduced mobility may have difficulty holding a device",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "or tapping the interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/mobility",
      "images": [
        {
          "identifier": "accessibility-card-mobility.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mobility",
      "type": "topic",
      "url": "/documentation/accessibility/mobility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/speech": {
      "abstract": [
        {
          "text": "A person may have a speech disability or prefer to connect without using their voice.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/speech",
      "images": [
        {
          "identifier": "accessibility-card-speech.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Speech",
      "type": "topic",
      "url": "/documentation/accessibility/speech"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/vision": {
      "abstract": [
        {
          "text": "A person may be blind or color blind, or have a vision challenge that",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "makes focusing difficult.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/vision",
      "images": [
        {
          "identifier": "accessibility-card-vision.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/accessibility/vision"
    },
    "doc://com.apple.documentation/documentation/MediaAccessibility/captions": {
      "abstract": [
        {
          "text": "Coordinate the presentation of closed-captioned data for your app’s media files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MediaAccessibility/captions",
      "kind": "article",
      "role": "article",
      "title": "Captions",
      "type": "topic",
      "url": "/documentation/MediaAccessibility/captions"
    },
    "doc://com.apple.documentation/documentation/MediaAccessibility/music-haptics": {
      "abstract": [
        {
          "text": "Play haptic tracks along with known music tracks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MediaAccessibility/music-haptics",
      "kind": "article",
      "role": "article",
      "title": "Music Haptics",
      "type": "topic",
      "url": "/documentation/MediaAccessibility/music-haptics"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Domains",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/vision",
        "doc://com.apple.Accessibility/documentation/Accessibility/speech",
        "doc://com.apple.Accessibility/documentation/Accessibility/mobility",
        "doc://com.apple.Accessibility/documentation/Accessibility/cognitive"
      ],
      "title": "Domains"
    }
  ],
  "topicSections": [
    {
      "anchor": "Supporting-hearing-accessibility-features",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support",
        "doc://com.apple.documentation/documentation/MediaAccessibility/music-haptics",
        "doc://com.apple.documentation/documentation/MediaAccessibility/captions"
      ],
      "title": "Supporting hearing accessibility features"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Supporting-hearing-accessibility-features",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/hearing-device-support",
                "doc://com.apple.documentation/documentation/MediaAccessibility/music-haptics",
                "doc://com.apple.documentation/documentation/MediaAccessibility/captions"
              ],
              "title": "Supporting hearing accessibility features"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Domains",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/vision",
                "doc://com.apple.Accessibility/documentation/Accessibility/speech",
                "doc://com.apple.Accessibility/documentation/Accessibility/mobility",
                "doc://com.apple.Accessibility/documentation/Accessibility/cognitive"
              ],
              "title": "Domains"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/hearing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/hearing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
