{
  "abstract": [
    {
      "text": "Test your app with accessibility settings and assistive technologies to discover and address accessibility issues.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility/switch-control"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility/voice-control"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility/voiceover"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/cognitive",
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/mobility",
        "doc://com.apple.Accessibility/documentation/Accessibility/switch-control"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/mobility",
        "doc://com.apple.Accessibility/documentation/Accessibility/voice-control"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/vision",
        "doc://com.apple.Accessibility/documentation/Accessibility/voiceover"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "images": [
      {
        "identifier": "Performing-Accessibility-PageImage-card.png",
        "type": "card"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Performing accessibility testing for your app"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "It’s always a good idea to experience your app from the perspective of the people using it.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "When you test your app from the user’s perspective, make sure you also test with different accessibility settings and assistive technologies like VoiceOver, Voice Control, and Switch Control so you can experience the app in the same way as people who rely on these features.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Testing your app with accessibility settings reveals which tasks are possible to complete, which elements are accessible and which aren’t, and whether your navigation is clear and logical for every use case.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "performing-accessibility-testing",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Identify-the-main-tasks-in-your-app",
          "level": 3,
          "text": "Identify the main tasks in your app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before you begin accessibility testing, compile a list of the main tasks that a person can perform on each screen in your app.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, a to-do list app might contain several screens with one or more possible tasks as described in the following list.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The user may need to complete or opt out of an onboarding flow.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "First launch experience",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The user may need to choose a login service, enter a username and password, interact with a login button, request a password reset, or enter information to create a new account.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Login screen",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The user may need to create a new task, or open app settings.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Empty to-do list",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The user may need to mark a task as complete, undo marking a task as complete, or create a new task.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "To-do list with tasks",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The user may need to enter information about the task, save the task to the list, or exit the screen without saving the task.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "New task screen",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The user may need to adjust app settings, or exit the screen without changing anything.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Settings screen",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "anchor": "Create-an-accessibility-testing-matrix",
          "level": 3,
          "text": "Create an accessibility testing matrix",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After you identify your app’s main tasks, choose which devices, accessibility settings, and assistive technologies to test those tasks with.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "It’s recommended to test your app on each type of device your app supports (for example, iPhone, iPad, and Mac).",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Testing on each of those devices lets you experience the app in the same way as a person who downloads and installs it.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Testing on device can also highlight subtle differences in your app’s user experience across platforms.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After you prepare your devices for testing, identify which accessibility features to test.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "As a starting point, it’s recommended that you test your app for the following accessibility categories,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "although you’re encouraged to test with additional settings and technologies if you can:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Visual accessibility for accessibility settings related to color, text, motion, and more",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Media accessibility for accessibility settings related to captions, audio descriptions, audio transcripts, and more",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Assistive technologies such as VoiceOver, Voice Control, Switch Control, and more",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The following sections describe how to test your app for visual accessibility, media accessibility, and several key assistive technologies.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Test-with-accessibility-settings",
          "level": 3,
          "text": "Test with accessibility settings",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To test with accessibility settings, turn on each of the following accessibility features in Settings > Accessibility, one at a time.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Work through your testing matrix by completing the main tasks in your app while each accessibility setting is on.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Display & Text Size > Bold Text",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Display & Text Size > Larger Text > Larger Accessibility Sizes",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Display & Text Size > Button Shapes",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Display & Text Size > On/Off Labels",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Display & Text Size > Reduce Transparency",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Display & Text Size > Increase Contrast",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Display & Text Size > Differentiate Without Color",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Display & Text Size > Color Filters > Red/Green Filter, Green/Red Filter, Blue/Yellow Filter",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Motion > Reduce Motion",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Motion > Dim Flashing Lights",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                }
              ],
              "title": "Visual accessibility"
            },
            {
              "content": [
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Audio Descriptions",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Subtitles & Captioning > Closed Captions + SDH",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Subtitles & Captioning > Show Audio Transcriptions",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                }
              ],
              "title": "Media accessibility"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Test-with-assistive-technologies",
          "level": 3,
          "text": "Test with assistive technologies",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To test with assistive technologies, set up and turn on each of the following assistive technologies, one at a time.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Work through your testing matrix by completing the main tasks in your app using only that assistive technology.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Install your app on a physical device, since VoiceOver isn’t available on Simulator.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Learn how to turn VoiceOver off so you can exit it after testing. For example, in iOS, you can set up ",
                              "type": "text"
                            },
                            {
                              "identifier": "https://support.apple.com/guide/iphone/open-features-with-accessibility-shortcut-iph3e2e31a5/ios",
                              "isActive": true,
                              "type": "reference"
                            },
                            {
                              "text": " to turn VoiceOver on and off. In macOS, you can press Command-F5.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Adjust your device volume to an appropriate level.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Navigate to Settings > Accessibility > VoiceOver, and turn on VoiceOver.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Adjust the Speaking Rate slider to an appropriate speaking pace.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "If you provide hints for any accessible elements in your app, make sure the Verbosity > Speak Hints setting is on.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                },
                {
                  "inlineContent": [
                    {
                      "text": "With VoiceOver on, use VoiceOver gestures to navigate your app.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "Although you don’t need to become an expert VoiceOver user to test your app with it, you do need to know several key gestures, which have slight variations across platforms.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "For example, the following gestures apply to devices with touchscreen and trackpad input.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "header": "row",
                  "rows": [
                    [
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Gesture",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ],
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Action",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    ],
                    [
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Tap",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ],
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Select and speak an item.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    ],
                    [
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Swipe right or left",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ],
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Select the next or previous item.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    ],
                    [
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Double tap",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ],
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Select and speak an item.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    ],
                    [
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Two-finger tap",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ],
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Pause or continue speaking.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    ],
                    [
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Two-finger swipe up",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ],
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Speak the entire screen from the top.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    ],
                    [
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Three-finger triple tap",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ],
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Turn the screen curtain on or off.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    ]
                  ],
                  "type": "table"
                },
                {
                  "inlineContent": [
                    {
                      "text": "To begin testing, turn on the ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "screen curtain",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": " to replicate the experience of someone who is solely relying on VoiceOver.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "When the screen curtain is on, the screen contents are active even though the display is black and appears to be turned off.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "A great place to practice VoiceOver gestures is in the VoiceOver Practice area in Settings > Accessibility > VoiceOver. VoiceOver needs to be on for the VoiceOver Practice button to appear.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  "name": "Tip",
                  "style": "tip",
                  "type": "aside"
                },
                {
                  "inlineContent": [
                    {
                      "text": "To learn more about VoiceOver gestures, read the platform-specific user guides listed in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              "title": "VoiceOver"
            },
            {
              "content": [
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Install your app on a physical device, since Voice Control isn’t available on Simulator.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Learn how to turn Voice Control off. For example, in iOS, you can set up ",
                              "type": "text"
                            },
                            {
                              "identifier": "https://support.apple.com/guide/iphone/open-features-with-accessibility-shortcut-iph3e2e31a5/ios",
                              "isActive": true,
                              "overridingTitle": "Accessibility Shortcut",
                              "overridingTitleInlineContent": [
                                {
                                  "text": "Accessibility Shortcut",
                                  "type": "text"
                                }
                              ],
                              "type": "reference"
                            },
                            {
                              "text": " to turn Voice Control on and off. In macOS, you can press Command-F5.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Make sure you’re in an environment where you can speak clearly and audibly. For example, being in a public space like a coffee shop with a lot of cross-talk and background noise may make Voice Control testing challenging.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Navigate to Settings > Accessibility > Voice Control, and turn on Voice Control.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                },
                {
                  "inlineContent": [
                    {
                      "text": "With Voice Control on, use voice commands to navigate your app.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "Although you don’t need to become an expert Voice Control user to test your app with it, you do need to know several key commands, which have slight variations across platforms.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "header": "row",
                  "rows": [
                    [
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Command",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ],
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Action",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    ],
                    [
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "“Open ",
                              "type": "text"
                            },
                            {
                              "inlineContent": [
                                {
                                  "text": "app name",
                                  "type": "text"
                                }
                              ],
                              "type": "emphasis"
                            },
                            {
                              "text": "”",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ],
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Open a specific app.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    ],
                    [
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "“Show names” or “Show numbers”",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ],
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Display a screen overlay that shows item names or numbers.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    ],
                    [
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "“Tap ",
                              "type": "text"
                            },
                            {
                              "inlineContent": [
                                {
                                  "text": "item name or number",
                                  "type": "text"
                                }
                              ],
                              "type": "emphasis"
                            },
                            {
                              "text": "”",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ],
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Interact with an item.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    ],
                    [
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "“Scroll down” or “Scroll up”",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ],
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Perform a scroll.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    ],
                    [
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "“Stop listening” and “Start listening”",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ],
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Pause or continue Voice Control.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    ],
                    [
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "“Show commands”",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ],
                      [
                        {
                          "inlineContent": [
                            {
                              "text": "Learn more about Voice Control commands.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    ]
                  ],
                  "type": "table"
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "A great place to practice Voice Control commands is in the Voice Control guide in Settings > Accessibility > Voice Control. Open the guide for a tutorial of different kinds of commands Voice Control supports.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ],
                  "name": "Tip",
                  "style": "tip",
                  "type": "aside"
                },
                {
                  "inlineContent": [
                    {
                      "text": "To learn more about Voice Control commands, read the platform-specific user guides listed in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              "title": "Voice Control"
            },
            {
              "content": [
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Install your app on a physical device, since Switch Control isn’t available on Simulator.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Learn how to turn Switch Control off. For example, in iOS, you can set up ",
                              "type": "text"
                            },
                            {
                              "identifier": "https://support.apple.com/guide/iphone/open-features-with-accessibility-shortcut-iph3e2e31a5/17.0/ios/17.0",
                              "isActive": true,
                              "type": "reference"
                            },
                            {
                              "text": " to turn Switch Control on and off. In macOS, you can press Command-F5.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Navigate to Settings > Accessibility > Switch Control > Switches. Select Add New Switch, select a type of switch, then select an action for the switch. Alternatively, you can choose Bluetooth Devices, select a device to use as a switch, and select an action for that switch.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "When you’re ready to start testing, turn on Switch Control.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                },
                {
                  "inlineContent": [
                    {
                      "text": "With Switch Control on, use Switch Control actions to navigate your app.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "Although you don’t need to become an expert Switch Control user to test your app with it, you do need to know several key actions.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "To learn more about Switch Control actions, read the platform-specific user guides listed in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/switch-control",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              "title": "Switch Control"
            },
            {
              "content": [
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Install your app on a physical device, since Assistive Access isn’t available on Simulator.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Learn how to turn Assistive Access off so you can exit it after testing. For example, triple-click the Home button or the Side button on certain devices at any time to exit Assistive Access. For more information, read ",
                              "type": "text"
                            },
                            {
                              "identifier": "https://support.apple.com/guide/assistive-access-iphone/enter-and-exit-assistive-access-devdedddc678/ios",
                              "isActive": true,
                              "type": "reference"
                            },
                            {
                              "text": ".",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Navigate to Settings > Accessibility > Assistive Access, and set up Assistive Access.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Add your app to the list of available apps.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "When you’re ready to start testing, tap Start Assistive Access and enter the Assistive Access passcode.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                },
                {
                  "inlineContent": [
                    {
                      "text": "With Assistive Access on, use standard system gestures to navigate your app.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "Assistive Access turns off the system edge swipe gesture, so you need to perform several key interactions in different ways:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "To unlock the device, tap the Open system button at the bottom of the screen.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "To navigate to the Home Screen, tap the Back system button at the bottom of the screen.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "For any interactions in your app that rely on edge swiping, like showing a sidebar or navigating a navigation stack, use buttons instead of swipes.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                },
                {
                  "inlineContent": [
                    {
                      "text": "To learn more about using Assistive Access, read",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://support.apple.com/guide/assistive-access-iphone/welcome/ios",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              "title": "Assistive Access"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Diagnose-and-address-accessibility-issues",
          "level": 3,
          "text": "Diagnose and address accessibility issues",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "As you test your app’s workflows, make sure your app continues to provide a good user experience while accessibility settings and assistive technologies are on.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Check that you can access every element and that the ordering of those elements is what you intend.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Make note when you find it difficult to perform a task.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Confirm that your UI adjusts appropriately when the system font size, color filter, or other visual settings change to something other than the default.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You can use the following list as a starting point for ensuring that your app provides a good experience in various accessibility categories.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "A user with low vision can perceive all UI elements, images, and text in your app.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Your app doesn’t use color alone to convey information.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Your app uses sufficient contrast for important UI elements.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Your app responds to Dynamic Type accessibility text sizes by reflowing its layout, avoiding text truncation, and making sure UI elements don’t overlap for larger sizes.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Your app responds to the Increase Contrast accessibility setting by increasing color contrast between background and foreground elements.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Your app responds to the Button Shapes accessibility setting to indicate where button controls exist.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Your app responds to the Reduce Motion accessibility setting by reducing excessive motion where appropriate.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Your app responds to the Dim Flashing Lights accessibility setting by reducing flickering in the UI or videos.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                }
              ],
              "title": "Visual accessibility"
            },
            {
              "content": [
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "A user with limited hearing can make use of all media in your app.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Your app contains audio descriptions for all video.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Your app contains captions for all video.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Your app contains transcripts for all video.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                }
              ],
              "title": "Media accessibility"
            },
            {
              "content": [
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "A user can perform all tasks within your app using only VoiceOver.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "VoiceOver can output all information in the app.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "For each item in the UI, VoiceOver reports the UI element name and status correctly.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                }
              ],
              "title": "VoiceOver"
            },
            {
              "content": [
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "A user can perform all tasks within your app using only Voice Control.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Voice Control can output all information in the app.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "For each item in the UI, Voice Control reports the UI element name and status correctly.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                }
              ],
              "title": "Voice Control"
            },
            {
              "content": [
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "A user can perform all tasks within your app using only Switch Control.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "Switch Control can output all information in the app.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "text": "For each item in the UI, Switch Control reports the UI element name and status correctly.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                }
              ],
              "title": "Switch Control"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "Take notes about any issues as you discover them so you can address them in your app’s design and implementation.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If you encounter accessibility issues that you aren’t able to troubleshoot while testing on the device, try using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-inspector",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to help diagnose and resolve issues.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You can also automate accessibility testing by adding accessibility audits in your UI tests, as described in ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/videos/play/wwdc2023/10035",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Address accessibility issues that you discover during testing so that you’re able to successfully complete all the tasks in your app when accessibility settings and assistive technologies are on.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "Performing-Accessibility-PageImage-card.png": {
      "alt": null,
      "identifier": "Performing-Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e051f9ccd83bfe36b3b3f6d9f40cbdb7/Performing-Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/aa888b2429f4c432b6746549abb24c55/Performing-Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "accessibility-card-cognitive.png": {
      "alt": "An illustration that shows a person standing and looking at an Apple Watch on their left wrist.",
      "identifier": "accessibility-card-cognitive.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e160ce0d82939c6b6866af282cc4bc9c/accessibility-card-cognitive@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3d882a73b0819d3d605fb78bda492908/accessibility-card-cognitive~dark@2x.png"
        }
      ]
    },
    "accessibility-card-mobility.png": {
      "alt": "An illustration that shows a person in a wheelchair using a MacBook in their lap.",
      "identifier": "accessibility-card-mobility.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c55383b0bf084116e82d7e4aba87c3cc/accessibility-card-mobility@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d0ce2da05b4c6805e5c3f5862222b099/accessibility-card-mobility~dark@2x.png"
        }
      ]
    },
    "accessibility-card-vision.png": {
      "alt": "An illustration that shows a person with low vision walking with the assistance of a guide dog while using an iPhone and AirPods.",
      "identifier": "accessibility-card-vision.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/11631c0b01fa73cc082557dc6067840e/accessibility-card-vision@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/624a8a2e8a195d6785905c00a619d3ac/accessibility-card-vision~dark@2x.png"
        }
      ]
    },
    "accessibility.svg": {
      "alt": null,
      "identifier": "accessibility.svg",
      "type": "image",
      "variants": [
        {
          "svgID": "accessibility",
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/83c941607786e0ba1f582082f4e94361/accessibility.svg"
        }
      ]
    },
    "assistive-access-card.png": {
      "alt": "",
      "identifier": "assistive-access-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6a2ce2f33aac08a5727273235f9f0bb6/assistive-access-card@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-inspector": {
      "abstract": [
        {
          "text": "Reveal how your app represents itself to people using accessibility features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-inspector",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility Inspector",
      "type": "topic",
      "url": "/documentation/accessibility/accessibility-inspector"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access": {
      "abstract": [
        {
          "text": "A mode that tailors the iOS and iPadOS experience for people with cognitive disabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access",
      "images": [
        {
          "identifier": "assistive-access-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Assistive Access",
      "type": "topic",
      "url": "/documentation/accessibility/assistive-access"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies": {
      "abstract": [
        {
          "text": "Make sure your app provides a great experience for people who use assistive technologies.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Assistive technologies",
      "type": "topic",
      "url": "/documentation/accessibility/assistive-technologies"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/cognitive": {
      "abstract": [
        {
          "text": "A person may have difficulty remembering a sequence of steps, or they",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "may find an overly complex user interface difficult to process and manage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/cognitive",
      "images": [
        {
          "identifier": "accessibility-card-cognitive.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cognitive",
      "type": "topic",
      "url": "/documentation/accessibility/cognitive"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/mobility": {
      "abstract": [
        {
          "text": "A person with reduced mobility may have difficulty holding a device",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "or tapping the interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/mobility",
      "images": [
        {
          "identifier": "accessibility-card-mobility.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mobility",
      "type": "topic",
      "url": "/documentation/accessibility/mobility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/switch-control": {
      "abstract": [
        {
          "text": "An interface for navigating a device with a variety of adaptive switch hardware, wireless game controllers, or sounds such as a click or a pop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/switch-control",
      "images": [
        {
          "identifier": "switch-control-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Switch Control",
      "type": "topic",
      "url": "/documentation/accessibility/switch-control"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/vision": {
      "abstract": [
        {
          "text": "A person may be blind or color blind, or have a vision challenge that",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "makes focusing difficult.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/vision",
      "images": [
        {
          "identifier": "accessibility-card-vision.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/accessibility/vision"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/voice-control": {
      "abstract": [
        {
          "text": "An interface for navigating a device using voice commands to tap, swipe, type, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
      "images": [
        {
          "identifier": "voice-control-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Voice Control",
      "type": "topic",
      "url": "/documentation/accessibility/voice-control"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/voiceover": {
      "abstract": [
        {
          "text": "A gesture-based screen reader that provides an auditory description of the content onscreen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
      "images": [
        {
          "identifier": "voiceover-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "VoiceOver",
      "type": "topic",
      "url": "/documentation/accessibility/voiceover"
    },
    "doc://com.apple.documentation/design/Human-Interface-Guidelines/accessibility": {
      "abstract": [
        {
          "text": "Accessible user interfaces empower everyone to have a great experience with your app or game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/design/Human-Interface-Guidelines/accessibility",
      "images": [
        {
          "identifier": "accessibility.svg",
          "type": "icon"
        },
        {
          "identifier": "foundations-accessibility-thumbnail.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Accessibility",
      "type": "topic",
      "url": "/design/Human-Interface-Guidelines/accessibility"
    },
    "doc://com.apple.documentation/documentation/Updates/Accessibility": {
      "abstract": [
        {
          "text": "Learn about important changes to Accessibility.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Updates/Accessibility",
      "kind": "article",
      "role": "article",
      "title": "Accessibility updates",
      "type": "topic",
      "url": "/documentation/Updates/Accessibility"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "foundations-accessibility-thumbnail.png": {
      "alt": null,
      "identifier": "foundations-accessibility-thumbnail.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8b7b11d06dd958f4e9449f0a5acdadbd/foundations-accessibility-thumbnail@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/fea544b1ff706c10ba3a1d06f528da46/foundations-accessibility-thumbnail~dark@2x.png"
        }
      ]
    },
    "https://developer.apple.com/videos/play/wwdc2023/10035": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2023/10035",
      "title": "Perform accessibility audits for your app",
      "titleInlineContent": [
        {
          "text": "Perform accessibility audits for your app",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2023/10035"
    },
    "https://support.apple.com/guide/assistive-access-iphone/enter-and-exit-assistive-access-devdedddc678/ios": {
      "identifier": "https://support.apple.com/guide/assistive-access-iphone/enter-and-exit-assistive-access-devdedddc678/ios",
      "title": "Enter and exit Assistive Access on iPhone",
      "titleInlineContent": [
        {
          "text": "Enter and exit Assistive Access on iPhone",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/assistive-access-iphone/enter-and-exit-assistive-access-devdedddc678/ios"
    },
    "https://support.apple.com/guide/assistive-access-iphone/welcome/ios": {
      "identifier": "https://support.apple.com/guide/assistive-access-iphone/welcome/ios",
      "title": "Assistive Access User Guide",
      "titleInlineContent": [
        {
          "text": "Assistive Access User Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/assistive-access-iphone/welcome/ios"
    },
    "https://support.apple.com/guide/iphone/open-features-with-accessibility-shortcut-iph3e2e31a5/17.0/ios/17.0": {
      "identifier": "https://support.apple.com/guide/iphone/open-features-with-accessibility-shortcut-iph3e2e31a5/17.0/ios/17.0",
      "title": "Accessibility Shortcut",
      "titleInlineContent": [
        {
          "text": "Accessibility Shortcut",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/iphone/open-features-with-accessibility-shortcut-iph3e2e31a5/17.0/ios/17.0"
    },
    "https://support.apple.com/guide/iphone/open-features-with-accessibility-shortcut-iph3e2e31a5/ios": {
      "identifier": "https://support.apple.com/guide/iphone/open-features-with-accessibility-shortcut-iph3e2e31a5/ios",
      "title": "Accessibility Shortcut",
      "titleInlineContent": [
        {
          "text": "Accessibility Shortcut",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/iphone/open-features-with-accessibility-shortcut-iph3e2e31a5/ios"
    },
    "performing-accessibility-testing": {
      "alt": null,
      "identifier": "performing-accessibility-testing",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/54a857292994cb77dc0abc95ea382205/performing-accessibility-testing@2x.png"
        }
      ]
    },
    "switch-control-card.png": {
      "alt": "",
      "identifier": "switch-control-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4b37322483b5831fc6a7e44fb9dc05b4/switch-control-card@2x.png"
        }
      ]
    },
    "voice-control-card.png": {
      "alt": "",
      "identifier": "voice-control-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9b9495b7277bc069208a522c435b7fc7/voice-control-card@2x.png"
        }
      ]
    },
    "voiceover-card.png": {
      "alt": "",
      "identifier": "voiceover-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6d02ab927e1e3865da0472d09dc3aae4/voiceover-card@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/Updates/Accessibility",
        "doc://com.apple.documentation/design/Human-Interface-Guidelines/accessibility"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [],
              "title": "Essentials"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/performing-accessibility-testing-for-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/performing-accessibility-testing-for-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
