{
  "abstract": [
    {
      "text": "Audit your app for common accessibility issues with Accessibility Inspector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-inspector"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-audits-for-your-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Performing accessibility audits for your app"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In Accessibility Inspector, the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Audits pane",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " provides the ability to audit",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your app for a few of the most common accessibility issues.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "An ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "audit",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " inspects a particular screen in your app and provides feedback",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "about the issues it encounters in your UI, such as insufficient contrast,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "text clipping, or missing element descriptions.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Use this pane to perform audits, view audit results with explanations, view fix suggestions,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or save audit results for later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "accessibility-inspector-audit-result",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Target-your-app",
          "level": 3,
          "text": "Target your app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In Accessibility Inspector, the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "target menu",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " displays a list of connected devices and apps you can inspect.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To begin an audit, choose your app from this menu.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Selecting an app to audit causes the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Run Audit button",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Options menu",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to appear in the Audits pane.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "accessibility-inspector-audits-pane-empty",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Choose-which-types-of-audits-to-perform",
          "level": 3,
          "text": "Choose which types of audits to perform",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Options menu",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " lets you configure the types of audits to run",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "depending on the platform you test on. Select the checkbox next to the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "corresponding type of test to include it in the audit. Listed below are",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the platform-specific types of tests you can select from the Options menu.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "All-platforms",
          "level": 4,
          "text": "All platforms",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Element description",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": ". This test checks each element’s accessibility label.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "All accessible elements must provide some context-specific, descriptive label.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Hit region",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": ". This test checks whether the size of an element is too small",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for a person to interact with.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Contrast",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": ". This test checks for sufficient color contrast between overlapping elements.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Element detection",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": ". This test checks whether any elements contain inaccessible",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "content that your app might need to be expose as separate accessibility children.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "iOS-watchOS-and-tvOS",
          "level": 4,
          "text": "iOS, watchOS, and tvOS",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Clipped text",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": ". This test checks whether clipping might occur for any text labels at",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "larger Dynamic Type sizes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Traits",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": ". This test verifies that an accessibility object implements all the properties",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and methods required for the accessibility traits it possesses.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Dynamic Type",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": ". This test checks whether the text in your app supports Dynamic Type,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "letting people adjust the size of the text in your app according to their system preference for font size.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "macOS",
          "level": 4,
          "text": "macOS",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Parent/child",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": ". This test checks the integrity of the accessibility hierarchy by",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "making sure each parent-child pair forms a closed loop. For example,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "if parent object lists a child as part of its accessibility children, but the child object",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "doesn’t refer to that object as its parent, this parent-child pair is invalid.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Invalid parent-child pairs can prevent an assistive app from correctly traversing an app’s accessibility hierarchy.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Action",
                  "type": "text"
                }
              ],
              "type": "strong"
            },
            {
              "text": ". This test checks whether an element’s accessibility action is valid for that type of element.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Run-an-audit-for-every-screen",
          "level": 3,
          "text": "Run an audit for every screen",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After you choose which types of tests to perform, you can begin auditing your UI.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To test the accessibility of every workflow in your app,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "make sure to run an audit for each of the screens in your app.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, a to-do list app might audit each of the following screens:",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "first launch experience, login screen, empty to-do list, to-do list with tasks, and the screen for adding a new task.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Click the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Run Audit button",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " to begin an audit for the current screen.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Accessibility Inspector runs the tests and displays the results for each.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Every time you run an audit for the same app,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a new audit result name with a corresponding number appears.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Next to the audit result name is a summary of the issues,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "reporting the number of issues for each type of test.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "accessibility-inspector-audit-result-annotated",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Interact-with-the-audit-issues",
          "level": 3,
          "text": "Interact with the audit issues",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each audit issue identifies a particular element in the UI that raises a potential accessibility concern.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You can interact with these issues in Accessibility Inspector to get more details.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To read a detailed explanation of the audit issue, click the dropdown next to the issue.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To draw a highlight over the element in question, click the issue.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To inspect the element in question in the ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "Inspection pane",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": ", double-click the issue.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Capture-a-screenshot-of-each-audit-issue",
          "level": 3,
          "text": "Capture a screenshot of each audit issue",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Audits pane lets you quickly capture a screenshot of any audit issue from the most recent audit.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Click the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Capture icon",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " next to an audit issue",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to show a screenshot of the current screen with a blue highlight over the element in question.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "capture-screenshot-audit-issue",
              "metadata": {
                "deviceFrame": "iPhone14Pro"
              },
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "View-fix-suggestions-for-audit-issues",
          "level": 3,
          "text": "View fix suggestions for audit issues",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each audit issue presents a corresponding fix suggestion to help you resolve that issue in your app.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Click the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Fix suggestions icon",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " next to an audit issue",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to receive a fix suggestion for the element in question.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, a fix suggestion might provide guidance for specific colors, font sizes, or APIs to use to address the audit issue.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "accessibility-inspector-audit-fix-suggestion",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Export-and-save-audit-results",
          "level": 3,
          "text": "Export and save audit results",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You might want to keep a record of audit results to share with app designers",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or reference later while resolving audit issues.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To generate an HTML document with audit results for your app, choose File > Save Audit Report As…",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This export provides a single HTML file that contains a summary of every audit result from the Audits pane.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You can navigate through the details of each result, including screenshots, descriptions, and fix suggestions for each audit issue.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-audits-to-your-UI-tests",
          "level": 3,
          "text": "Add audits to your UI tests",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In addition to performing accessibility audits manually in Accessibility Inspector,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you can automate these audits in your UI tests.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XCTest/XCUIApplication/performAccessibilityAudit(for:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/XCTest/XCUIApplication",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " audits the current screen for accessibility issues",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the same way that running an audit in Accessibility Inspector does.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "If the UI test finds any audit issues, it automatically fails.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about automating audits, see",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/videos/play/wwdc2023/10035",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Performing accessibility audits is an excellent start to improving the accessibility of your app,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "but eliminating all audit issues that Accessibility Inspector reports doesn’t guarantee a fully accessible app.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Always test your app with various assistive apps, such as VoiceOver, to make sure there are no problems.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "accessibility-inspector-audit-fix-suggestion": {
      "alt": "Fix suggestion for a missing element description audit issue that recommends setting the accessibility label for the element.",
      "identifier": "accessibility-inspector-audit-fix-suggestion",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/af7b1240da94c9fadea78c5344c4cb3b/accessibility-inspector-audit-fix-suggestion@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/aecf5c55558a66ff492178103d22367d/accessibility-inspector-audit-fix-suggestion~dark@2x.png"
        }
      ]
    },
    "accessibility-inspector-audit-result": {
      "alt": "Audits pane with one audit result that lists two element description issues.",
      "identifier": "accessibility-inspector-audit-result",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/785b2782f464521f77d27fb2b40c9af1/accessibility-inspector-audit-result@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/0cee50e4da74a51c354ca2b74a1156c2/accessibility-inspector-audit-result~dark@2x.png"
        }
      ]
    },
    "accessibility-inspector-audit-result-annotated": {
      "alt": "Audits pane showing one audit result. A label that shows the number of each type of audit issue appears next to the audit result name. The result shows two element description audit issues that provide more detail when disclosed.",
      "identifier": "accessibility-inspector-audit-result-annotated",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/61950b3d7925fab64dc68a06cec6b93c/accessibility-inspector-audit-result-annotated@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3328f0d5e9dc3dc1221c5baefe357d14/accessibility-inspector-audit-result-annotated~dark@2x.png"
        }
      ]
    },
    "accessibility-inspector-audits-pane-empty": {
      "alt": "Audits pane showing the Run Audit button that begins an audit, and the Options menu that allows selection of the types of audits to perform.",
      "identifier": "accessibility-inspector-audits-pane-empty",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c12d6c5a5ffcf9eb3df4ad33523159de/accessibility-inspector-audits-pane-empty@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/eade16c2855324b6b946e26e80bb56b6/accessibility-inspector-audits-pane-empty~dark@2x.png"
        }
      ]
    },
    "capture-screenshot-audit-issue": {
      "alt": "Screenshot of a blue rectangle over an image in a sample app where Accessibility Inspector reported an audit issue.",
      "identifier": "capture-screenshot-audit-issue",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/74daa185e238504c3f1eb0d37a4362aa/capture-screenshot-audit-issue@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a26846dbd9aa37273db73e3c07cf7b79/capture-screenshot-audit-issue~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-inspector": {
      "abstract": [
        {
          "text": "Reveal how your app represents itself to people using accessibility features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/accessibility-inspector",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility Inspector",
      "type": "topic",
      "url": "/documentation/accessibility/accessibility-inspector"
    },
    "doc://com.apple.documentation/documentation/XCTest/XCUIApplication": {
      "abstract": [
        {
          "text": "A proxy that can launch, monitor, and terminate a test application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIApplication"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest/XCUIApplication",
      "kind": "symbol",
      "role": "symbol",
      "title": "XCUIApplication",
      "type": "topic",
      "url": "/documentation/XCTest/XCUIApplication"
    },
    "doc://com.apple.documentation/documentation/XCTest/XCUIApplication/performAccessibilityAudit(for:_:)": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@nonobjc"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "attribute",
          "text": "@preconcurrency"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performAccessibilityAudit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "auditTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIAccessibilityAuditType",
          "text": "XCUIAccessibilityAuditType"
        },
        {
          "kind": "text",
          "text": " = .all, "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "issueHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIAccessibilityAuditIssue",
          "text": "XCUIAccessibilityAuditIssue"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")? = nil) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XCTest/XCUIApplication/performAccessibilityAudit(for:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "performAccessibilityAudit(for:_:)",
      "type": "topic",
      "url": "/documentation/XCTest/XCUIApplication/performAccessibilityAudit(for:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/videos/play/wwdc2023/10035": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2023/10035",
      "title": "Perform accessibility audits for your app",
      "titleInlineContent": [
        {
          "text": "Perform accessibility audits for your app",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2023/10035"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XCTest~1XCUIApplication/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCUIApplication"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCUIElement",
              "text": "XCUIElement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/performing-accessibility-audits-for-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/performing-accessibility-audits-for-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
