{
  "abstract": [
    {
      "text": "An interface for navigating a device with a variety of adaptive switch hardware, wireless game controllers, or sounds such as a click or a pop.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/mobility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/switch-control"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "images": [
      {
        "identifier": "switch-control-card.png",
        "type": "card"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "Assistive Technology",
    "title": "Switch Control"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Switch Control is an assistive technology that lets people control their iOS devices using a single switch or multiple switches.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "With Switch Control, people can use switches to perform actions like selecting, tapping, dragging and dropping, typing, and freehand drawing.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "A person uses a switch to select an item or location on the screen, then uses the switch to choose an action.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Learn more about testing your app with Switch Control to make sure it works well for people who use this assistive technology.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "switch-control",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Learn-to-use-Switch-Control",
          "level": 4,
          "text": "Learn to use Switch Control",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/guide/iphone/intro-to-switch-control-iphc9d32b862/ios",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/en-asia/guide/ipad/ipad90b36e17/ipados",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/guide/mac-help/use-switch-control-mh43607/mac",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/guide/tv/use-switch-control-atvb1e5d42fa/tvos",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/guide/apple-vision-pro/use-switch-control-tan1248f5483/visionos",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/news/?id=2nfiv7v0",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Related-videos",
          "level": 4,
          "text": "Related videos",
          "type": "heading"
        },
        {
          "items": [
            "doc://com.apple.documentation/videos/play/wwdc2020/10019",
            "doc://com.apple.documentation/videos/play/wwdc2022/10151"
          ],
          "style": "compactGrid",
          "type": "links"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "2B5F701C-62F9-4D73-B6DB-5B4A7B1ACFFA": {
      "alt": null,
      "identifier": "2B5F701C-62F9-4D73-B6DB-5B4A7B1ACFFA",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/124/2B5F701C-62F9-4D73-B6DB-5B4A7B1ACFFA/6650_wide_250x141_1x.jpg"
        },
        {
          "traits": [
            "2x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/124/2B5F701C-62F9-4D73-B6DB-5B4A7B1ACFFA/6650_wide_250x141_2x.jpg"
        },
        {
          "traits": [
            "3x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/124/2B5F701C-62F9-4D73-B6DB-5B4A7B1ACFFA/6650_wide_250x141_3x.jpg"
        }
      ]
    },
    "A1032935-6679-4A6E-AF71-6905A0486871": {
      "alt": null,
      "identifier": "A1032935-6679-4A6E-AF71-6905A0486871",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/49/A1032935-6679-4A6E-AF71-6905A0486871/3472_wide_250x141_1x.jpg"
        },
        {
          "traits": [
            "2x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/49/A1032935-6679-4A6E-AF71-6905A0486871/3472_wide_250x141_2x.jpg"
        },
        {
          "traits": [
            "3x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/49/A1032935-6679-4A6E-AF71-6905A0486871/3472_wide_250x141_3x.jpg"
        }
      ]
    },
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "Performing-Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Performing-Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e051f9ccd83bfe36b3b3f6d9f40cbdb7/Performing-Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/aa888b2429f4c432b6746549abb24c55/Performing-Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "accessibility-card-mobility.png": {
      "alt": "An illustration that shows a person in a wheelchair using a MacBook in their lap.",
      "identifier": "accessibility-card-mobility.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c55383b0bf084116e82d7e4aba87c3cc/accessibility-card-mobility@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d0ce2da05b4c6805e5c3f5862222b099/accessibility-card-mobility~dark@2x.png"
        }
      ]
    },
    "assistive-access-card.png": {
      "alt": "",
      "identifier": "assistive-access-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6a2ce2f33aac08a5727273235f9f0bb6/assistive-access-card@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access": {
      "abstract": [
        {
          "text": "A mode that tailors the iOS and iPadOS experience for people with cognitive disabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access",
      "images": [
        {
          "identifier": "assistive-access-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Assistive Access",
      "type": "topic",
      "url": "/documentation/accessibility/assistive-access"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies": {
      "abstract": [
        {
          "text": "Make sure your app provides a great experience for people who use assistive technologies.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Assistive technologies",
      "type": "topic",
      "url": "/documentation/accessibility/assistive-technologies"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/mobility": {
      "abstract": [
        {
          "text": "A person with reduced mobility may have difficulty holding a device",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "or tapping the interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/mobility",
      "images": [
        {
          "identifier": "accessibility-card-mobility.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mobility",
      "type": "topic",
      "url": "/documentation/accessibility/mobility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app": {
      "abstract": [
        {
          "text": "Test your app with accessibility settings and assistive technologies to discover and address accessibility issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app",
      "images": [
        {
          "identifier": "Performing-Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Performing accessibility testing for your app",
      "type": "topic",
      "url": "/documentation/accessibility/performing-accessibility-testing-for-your-app"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/voice-control": {
      "abstract": [
        {
          "text": "An interface for navigating a device using voice commands to tap, swipe, type, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
      "images": [
        {
          "identifier": "voice-control-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Voice Control",
      "type": "topic",
      "url": "/documentation/accessibility/voice-control"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/voiceover": {
      "abstract": [
        {
          "text": "A gesture-based screen reader that provides an auditory description of the content onscreen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
      "images": [
        {
          "identifier": "voiceover-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "VoiceOver",
      "type": "topic",
      "url": "/documentation/accessibility/voiceover"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming": {
      "abstract": [
        {
          "text": "Play a card-matching game using Switch Control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming",
      "kind": "article",
      "role": "sampleCode",
      "title": "WWDC22 Challenge: Learn Switch Control through gaming",
      "type": "topic",
      "url": "/documentation/accessibility/wwdc22_challenge_learn_switch_control_through_gaming"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/videos/play/wwdc2020/10019": {
      "abstract": [
        {
          "text": "Switch Control is a powerful accessibility technology for anyone with very limited mobility. The feature is available natively on iOS, and you can create an even better Switch Control experience in your app with tips, tricks, and a few APIs. We’ll walk you through how people use Switch Control, as well as provide best practices for supporting it in your app effectively. \n\nTo get the most out of this session, you should be familiar with general accessibility principles and VoiceOver accessibility APIs. Check out \"Making Apps More Accessible With Custom Actions,\" \"Writing Great Accessibility Labels, and \"VoiceOver: App Testing Beyond The Visuals\" for more information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/videos/play/wwdc2020/10019",
      "images": [
        {
          "identifier": "A1032935-6679-4A6E-AF71-6905A0486871",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "App accessibility for Switch Control",
      "type": "topic",
      "url": "https://developer.apple.com/videos/play/wwdc2020/10019"
    },
    "doc://com.apple.documentation/videos/play/wwdc2022/10151": {
      "abstract": [
        {
          "text": "Learn how you can make your Unity games accessible on Apple platforms using our open source Accessibility plug-in. Follow along as we add support for assistive technologies like VoiceOver and Switch Control to a sample Unity game project. We'll show you how you can automatically scale text with Dynamic Type, support interface accommodations like reduced transparency or increased contrast, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/videos/play/wwdc2022/10151",
      "images": [
        {
          "identifier": "2B5F701C-62F9-4D73-B6DB-5B4A7B1ACFFA",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Add accessibility to your Unity games",
      "type": "topic",
      "url": "https://developer.apple.com/videos/play/wwdc2022/10151"
    },
    "https://developer.apple.com/news/?id=2nfiv7v0": {
      "identifier": "https://developer.apple.com/news/?id=2nfiv7v0",
      "title": "Challenge: Learn Switch Control through gaming",
      "titleInlineContent": [
        {
          "text": "Challenge: Learn Switch Control through gaming",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/news/?id=2nfiv7v0"
    },
    "https://support.apple.com/en-asia/guide/ipad/ipad90b36e17/ipados": {
      "identifier": "https://support.apple.com/en-asia/guide/ipad/ipad90b36e17/ipados",
      "title": "Intro to Switch Control on iPad",
      "titleInlineContent": [
        {
          "text": "Intro to Switch Control on iPad",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/en-asia/guide/ipad/ipad90b36e17/ipados"
    },
    "https://support.apple.com/guide/apple-vision-pro/use-switch-control-tan1248f5483/visionos": {
      "identifier": "https://support.apple.com/guide/apple-vision-pro/use-switch-control-tan1248f5483/visionos",
      "title": "Use Switch Control on Apple Vision Pro",
      "titleInlineContent": [
        {
          "text": "Use Switch Control on Apple Vision Pro",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/apple-vision-pro/use-switch-control-tan1248f5483/visionos"
    },
    "https://support.apple.com/guide/iphone/intro-to-switch-control-iphc9d32b862/ios": {
      "identifier": "https://support.apple.com/guide/iphone/intro-to-switch-control-iphc9d32b862/ios",
      "title": "Intro to Switch Control on iPhone",
      "titleInlineContent": [
        {
          "text": "Intro to Switch Control on iPhone",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/iphone/intro-to-switch-control-iphc9d32b862/ios"
    },
    "https://support.apple.com/guide/mac-help/use-switch-control-mh43607/mac": {
      "identifier": "https://support.apple.com/guide/mac-help/use-switch-control-mh43607/mac",
      "title": "Use Switch Control on Mac",
      "titleInlineContent": [
        {
          "text": "Use Switch Control on Mac",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/mac-help/use-switch-control-mh43607/mac"
    },
    "https://support.apple.com/guide/tv/use-switch-control-atvb1e5d42fa/tvos": {
      "identifier": "https://support.apple.com/guide/tv/use-switch-control-atvb1e5d42fa/tvos",
      "title": "Use Switch Control on Apple TV",
      "titleInlineContent": [
        {
          "text": "Use Switch Control on Apple TV",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/tv/use-switch-control-atvb1e5d42fa/tvos"
    },
    "switch-control": {
      "alt": "",
      "identifier": "switch-control",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/f4e00d2a4a4652b7e7bbc893d09c9c69/switch-control@2x.png"
        }
      ]
    },
    "switch-control-card.png": {
      "alt": null,
      "identifier": "switch-control-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4b37322483b5831fc6a7e44fb9dc05b4/switch-control-card@2x.png"
        }
      ]
    },
    "voice-control-card.png": {
      "alt": "",
      "identifier": "voice-control-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9b9495b7277bc069208a522c435b7fc7/voice-control-card@2x.png"
        }
      ]
    },
    "voiceover-card.png": {
      "alt": "",
      "identifier": "voiceover-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6d02ab927e1e3865da0472d09dc3aae4/voiceover-card@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Assistive-technologies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
        "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access"
      ],
      "title": "Assistive technologies"
    }
  ],
  "topicSections": [
    {
      "anchor": "Develop-for-Switch-Control",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app",
        "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming"
      ],
      "title": "Develop for Switch Control"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Develop-for-Switch-Control",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app",
                "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming"
              ],
              "title": "Develop for Switch Control"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Assistive-technologies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
                "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
                "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access"
              ],
              "title": "Assistive technologies"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/switch-control"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/switch-control"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
