{
  "abstract": [
    {
      "text": "An interface for navigating a device using voice commands to tap, swipe, type, and more.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/mobility"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/voice-control"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "images": [
      {
        "identifier": "voice-control-card.png",
        "type": "card"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "Assistive Technology",
    "title": "Voice Control"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Voice Control is an assistive technology that lets people interact with their devices using only their voice.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "People speak commands to perform gestures, interact with screen elements, dictate and edit text, and more.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Learn more about testing your app with Voice Control to make sure it works well for people who use this assistive technology.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "voice-control",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Learn-to-use-Voice-Control",
          "level": 4,
          "text": "Learn to use Voice Control",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://www.apple.com/macos/big-sur/docs/Voice_Control_Tech_Brief_Sept_2019.pdf",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/guide/iphone/use-voice-control-iph2c21a3c88/ios",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/guide/apple-vision-pro/voice-control-tan14d179ad1/visionos",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/guide/mac-help/get-started-mchl1a04f324/mac",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/news/?id=4dcwl3iv",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "Performing-Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Performing-Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e051f9ccd83bfe36b3b3f6d9f40cbdb7/Performing-Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/aa888b2429f4c432b6746549abb24c55/Performing-Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "accessibility-card-mobility.png": {
      "alt": "An illustration that shows a person in a wheelchair using a MacBook in their lap.",
      "identifier": "accessibility-card-mobility.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c55383b0bf084116e82d7e4aba87c3cc/accessibility-card-mobility@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d0ce2da05b4c6805e5c3f5862222b099/accessibility-card-mobility~dark@2x.png"
        }
      ]
    },
    "assistive-access-card.png": {
      "alt": "",
      "identifier": "assistive-access-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6a2ce2f33aac08a5727273235f9f0bb6/assistive-access-card@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access": {
      "abstract": [
        {
          "text": "A mode that tailors the iOS and iPadOS experience for people with cognitive disabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access",
      "images": [
        {
          "identifier": "assistive-access-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Assistive Access",
      "type": "topic",
      "url": "/documentation/accessibility/assistive-access"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies": {
      "abstract": [
        {
          "text": "Make sure your app provides a great experience for people who use assistive technologies.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Assistive technologies",
      "type": "topic",
      "url": "/documentation/accessibility/assistive-technologies"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/mobility": {
      "abstract": [
        {
          "text": "A person with reduced mobility may have difficulty holding a device",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "or tapping the interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/mobility",
      "images": [
        {
          "identifier": "accessibility-card-mobility.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mobility",
      "type": "topic",
      "url": "/documentation/accessibility/mobility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app": {
      "abstract": [
        {
          "text": "Test your app with accessibility settings and assistive technologies to discover and address accessibility issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app",
      "images": [
        {
          "identifier": "Performing-Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Performing accessibility testing for your app",
      "type": "topic",
      "url": "/documentation/accessibility/performing-accessibility-testing-for-your-app"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/switch-control": {
      "abstract": [
        {
          "text": "An interface for navigating a device with a variety of adaptive switch hardware, wireless game controllers, or sounds such as a click or a pop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/switch-control",
      "images": [
        {
          "identifier": "switch-control-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Switch Control",
      "type": "topic",
      "url": "/documentation/accessibility/switch-control"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/voiceover": {
      "abstract": [
        {
          "text": "A gesture-based screen reader that provides an auditory description of the content onscreen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
      "images": [
        {
          "identifier": "voiceover-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "VoiceOver",
      "type": "topic",
      "url": "/documentation/accessibility/voiceover"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/news/?id=4dcwl3iv": {
      "identifier": "https://developer.apple.com/news/?id=4dcwl3iv",
      "title": "Challenge: Voice Control Synonyms",
      "titleInlineContent": [
        {
          "text": "Challenge: Voice Control Synonyms",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/news/?id=4dcwl3iv"
    },
    "https://support.apple.com/guide/apple-vision-pro/voice-control-tan14d179ad1/visionos": {
      "identifier": "https://support.apple.com/guide/apple-vision-pro/voice-control-tan14d179ad1/visionos",
      "title": "Use Voice Control to interact with Apple Vision Pro",
      "titleInlineContent": [
        {
          "text": "Use Voice Control to interact with Apple Vision Pro",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/apple-vision-pro/voice-control-tan14d179ad1/visionos"
    },
    "https://support.apple.com/guide/iphone/use-voice-control-iph2c21a3c88/ios": {
      "identifier": "https://support.apple.com/guide/iphone/use-voice-control-iph2c21a3c88/ios",
      "title": "Use Voice Control to interact with iPhone",
      "titleInlineContent": [
        {
          "text": "Use Voice Control to interact with iPhone",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/iphone/use-voice-control-iph2c21a3c88/ios"
    },
    "https://support.apple.com/guide/mac-help/get-started-mchl1a04f324/mac": {
      "identifier": "https://support.apple.com/guide/mac-help/get-started-mchl1a04f324/mac",
      "title": "Get started with Voice Control on Mac",
      "titleInlineContent": [
        {
          "text": "Get started with Voice Control on Mac",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/mac-help/get-started-mchl1a04f324/mac"
    },
    "https://www.apple.com/macos/big-sur/docs/Voice_Control_Tech_Brief_Sept_2019.pdf": {
      "identifier": "https://www.apple.com/macos/big-sur/docs/Voice_Control_Tech_Brief_Sept_2019.pdf",
      "title": "Voice Control",
      "titleInlineContent": [
        {
          "text": "Voice Control",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.apple.com/macos/big-sur/docs/Voice_Control_Tech_Brief_Sept_2019.pdf"
    },
    "switch-control-card.png": {
      "alt": "",
      "identifier": "switch-control-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4b37322483b5831fc6a7e44fb9dc05b4/switch-control-card@2x.png"
        }
      ]
    },
    "voice-control": {
      "alt": "",
      "identifier": "voice-control",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/96476548475a2eea3b109e4c888c2e6f/voice-control@2x.png"
        }
      ]
    },
    "voice-control-card.png": {
      "alt": null,
      "identifier": "voice-control-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9b9495b7277bc069208a522c435b7fc7/voice-control-card@2x.png"
        }
      ]
    },
    "voiceover-card.png": {
      "alt": "",
      "identifier": "voiceover-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6d02ab927e1e3865da0472d09dc3aae4/voiceover-card@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Assistive-technologies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
        "doc://com.apple.Accessibility/documentation/Accessibility/switch-control",
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access"
      ],
      "title": "Assistive technologies"
    }
  ],
  "topicSections": [
    {
      "anchor": "Develop-for-Voice-Control",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app"
      ],
      "title": "Develop for Voice Control"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Develop-for-Voice-Control",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app"
              ],
              "title": "Develop for Voice Control"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Assistive-technologies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/voiceover",
                "doc://com.apple.Accessibility/documentation/Accessibility/switch-control",
                "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access"
              ],
              "title": "Assistive technologies"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/voice-control"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/voice-control"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
