{
  "abstract": [
    {
      "text": "A gesture-based screen reader that provides an auditory description of the content onscreen.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/voiceover"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "images": [
      {
        "identifier": "voiceover-card.png",
        "type": "card"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "Assistive Technology",
    "title": "VoiceOver"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "VoiceOver is an assistive technology that enables people to experience the interface on their devices without having to see the screen.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "People who are blind or have low vision depend on VoiceOver to provide auditory feedback while using their devices, but VoiceOver can be useful to people in a wide variety of contexts.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, someone prone to motion sickness might choose to turn VoiceOver on while they’re in a moving vehicle.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Learn more about testing your app with VoiceOver to make sure it works well for people who use this assistive technology.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "voiceover",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Learn-to-use-VoiceOver",
          "level": 4,
          "text": "Learn to use VoiceOver",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/guide/iphone/turn-on-and-practice-voiceover-iph3e2e415f/ios",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/guide/ipad/turn-on-and-practice-voiceover-ipad9a246898/ipados",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/guide/apple-vision-pro/turn-on-and-practice-voiceover-tanae5174040/visionos",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/guide/watch/voiceover-apdaabc79d3b/watchos",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/guide/tv/use-voiceover-atvbfa4ff6cd/tvos",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://support.apple.com/guide/voiceover/welcome/mac",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Related-videos",
          "level": 3,
          "text": "Related videos",
          "type": "heading"
        },
        {
          "items": [
            "doc://com.apple.documentation/videos/play/wwdc2021/10121",
            "doc://com.apple.documentation/videos/play/wwdc2020/10116"
          ],
          "style": "compactGrid",
          "type": "links"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "1A6C1BBD-8ADD-4B35-896E-7EBAA39B82FC": {
      "alt": null,
      "identifier": "1A6C1BBD-8ADD-4B35-896E-7EBAA39B82FC",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/119/1A6C1BBD-8ADD-4B35-896E-7EBAA39B82FC/5019_wide_250x141_1x.jpg"
        },
        {
          "traits": [
            "2x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/119/1A6C1BBD-8ADD-4B35-896E-7EBAA39B82FC/5019_wide_250x141_2x.jpg"
        },
        {
          "traits": [
            "3x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/119/1A6C1BBD-8ADD-4B35-896E-7EBAA39B82FC/5019_wide_250x141_3x.jpg"
        }
      ]
    },
    "669BA7EE-2BAE-4B94-84E7-41D399756313": {
      "alt": null,
      "identifier": "669BA7EE-2BAE-4B94-84E7-41D399756313",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/49/669BA7EE-2BAE-4B94-84E7-41D399756313/3471_wide_250x141_1x.jpg"
        },
        {
          "traits": [
            "2x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/49/669BA7EE-2BAE-4B94-84E7-41D399756313/3471_wide_250x141_2x.jpg"
        },
        {
          "traits": [
            "3x"
          ],
          "url": "https://devimages-cdn.apple.com/wwdc-services/images/49/669BA7EE-2BAE-4B94-84E7-41D399756313/3471_wide_250x141_3x.jpg"
        }
      ]
    },
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "Performing-Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Performing-Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e051f9ccd83bfe36b3b3f6d9f40cbdb7/Performing-Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/aa888b2429f4c432b6746549abb24c55/Performing-Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "accessibility-card-vision.png": {
      "alt": "An illustration that shows a person with low vision walking with the assistance of a guide dog while using an iPhone and AirPods.",
      "identifier": "accessibility-card-vision.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/11631c0b01fa73cc082557dc6067840e/accessibility-card-vision@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/624a8a2e8a195d6785905c00a619d3ac/accessibility-card-vision~dark@2x.png"
        }
      ]
    },
    "assistive-access-card.png": {
      "alt": "",
      "identifier": "assistive-access-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6a2ce2f33aac08a5727273235f9f0bb6/assistive-access-card@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access": {
      "abstract": [
        {
          "text": "A mode that tailors the iOS and iPadOS experience for people with cognitive disabilities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access",
      "images": [
        {
          "identifier": "assistive-access-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Assistive Access",
      "type": "topic",
      "url": "/documentation/accessibility/assistive-access"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies": {
      "abstract": [
        {
          "text": "Make sure your app provides a great experience for people who use assistive technologies.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/assistive-technologies",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Assistive technologies",
      "type": "topic",
      "url": "/documentation/accessibility/assistive-technologies"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app": {
      "abstract": [
        {
          "text": "Test your app with accessibility settings and assistive technologies to discover and address accessibility issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app",
      "images": [
        {
          "identifier": "Performing-Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Performing accessibility testing for your app",
      "type": "topic",
      "url": "/documentation/accessibility/performing-accessibility-testing-for-your-app"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/switch-control": {
      "abstract": [
        {
          "text": "An interface for navigating a device with a variety of adaptive switch hardware, wireless game controllers, or sounds such as a click or a pop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/switch-control",
      "images": [
        {
          "identifier": "switch-control-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Switch Control",
      "type": "topic",
      "url": "/documentation/accessibility/switch-control"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/vision": {
      "abstract": [
        {
          "text": "A person may be blind or color blind, or have a vision challenge that",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "makes focusing difficult.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/vision",
      "images": [
        {
          "identifier": "accessibility-card-vision.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/accessibility/vision"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/voice-control": {
      "abstract": [
        {
          "text": "An interface for navigating a device using voice commands to tap, swipe, type, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
      "images": [
        {
          "identifier": "voice-control-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Voice Control",
      "type": "topic",
      "url": "/documentation/accessibility/voice-control"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze": {
      "abstract": [
        {
          "text": "Navigate to the end of a dark maze using VoiceOver as your guide.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze",
      "kind": "article",
      "role": "sampleCode",
      "title": "WWDC21 Challenge: VoiceOver Maze",
      "type": "topic",
      "url": "/documentation/accessibility/wwdc21_challenge_voiceover_maze"
    },
    "doc://com.apple.documentation/documentation/UIKit/supporting-voiceover-in-your-app": {
      "abstract": [
        {
          "text": "Add VoiceOver support to make your iOS app more accessible to users who are blind or have low vision.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/supporting-voiceover-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Supporting VoiceOver in your app",
      "type": "topic",
      "url": "/documentation/UIKit/supporting-voiceover-in-your-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/videos/play/wwdc2020/10116": {
      "abstract": [
        {
          "text": "Discover how you can integrate custom rotors and help people who use VoiceOver navigate complex situations within your app. Learn how custom rotors can help people explore even the most intricate interfaces, explore how to implement a custom rotor, and find out how rotors can improve navigation for someone who relies on VoiceOver.\n\nTo get the most out of this session, you should be familiar with general accessibility principles and VoiceOver accessibility APIs on iOS and iPadOS. For an overview, watch “Making Apps More Accessible with Custom Actions.”",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/videos/play/wwdc2020/10116",
      "images": [
        {
          "identifier": "669BA7EE-2BAE-4B94-84E7-41D399756313",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "VoiceOver efficiency with custom rotors",
      "type": "topic",
      "url": "https://developer.apple.com/videos/play/wwdc2020/10116"
    },
    "doc://com.apple.documentation/videos/play/wwdc2021/10121": {
      "abstract": [
        {
          "text": "Learn how to present complex data through VoiceOver with the Accessibility Custom Content API. Discover how you can deliver accessibility information in a concise form, and only when someone wants it. We’ll show you how you can integrate AXCustomContent and help people who want VoiceOver enabled to navigate your data-rich apps in an efficient manner.\n\nTo get the most out of this session, you should be familiar with general accessibility principles and VoiceOver accessibility APIs available in Swift and SwiftUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/videos/play/wwdc2021/10121",
      "images": [
        {
          "identifier": "1A6C1BBD-8ADD-4B35-896E-7EBAA39B82FC",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Tailor the VoiceOver experience in your data-rich apps",
      "type": "topic",
      "url": "https://developer.apple.com/videos/play/wwdc2021/10121"
    },
    "https://support.apple.com/guide/apple-vision-pro/turn-on-and-practice-voiceover-tanae5174040/visionos": {
      "identifier": "https://support.apple.com/guide/apple-vision-pro/turn-on-and-practice-voiceover-tanae5174040/visionos",
      "title": "Turn on and practice VoiceOver on Apple Vision Pro",
      "titleInlineContent": [
        {
          "text": "Turn on and practice VoiceOver on Apple Vision Pro",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/apple-vision-pro/turn-on-and-practice-voiceover-tanae5174040/visionos"
    },
    "https://support.apple.com/guide/ipad/turn-on-and-practice-voiceover-ipad9a246898/ipados": {
      "identifier": "https://support.apple.com/guide/ipad/turn-on-and-practice-voiceover-ipad9a246898/ipados",
      "title": "Turn on and practice VoiceOver on iPad",
      "titleInlineContent": [
        {
          "text": "Turn on and practice VoiceOver on iPad",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/ipad/turn-on-and-practice-voiceover-ipad9a246898/ipados"
    },
    "https://support.apple.com/guide/iphone/turn-on-and-practice-voiceover-iph3e2e415f/ios": {
      "identifier": "https://support.apple.com/guide/iphone/turn-on-and-practice-voiceover-iph3e2e415f/ios",
      "title": "Turn on and practice VoiceOver on iPhone",
      "titleInlineContent": [
        {
          "text": "Turn on and practice VoiceOver on iPhone",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/iphone/turn-on-and-practice-voiceover-iph3e2e415f/ios"
    },
    "https://support.apple.com/guide/tv/use-voiceover-atvbfa4ff6cd/tvos": {
      "identifier": "https://support.apple.com/guide/tv/use-voiceover-atvbfa4ff6cd/tvos",
      "title": "Use VoiceOver on Apple TV",
      "titleInlineContent": [
        {
          "text": "Use VoiceOver on Apple TV",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/tv/use-voiceover-atvbfa4ff6cd/tvos"
    },
    "https://support.apple.com/guide/voiceover/welcome/mac": {
      "identifier": "https://support.apple.com/guide/voiceover/welcome/mac",
      "title": "VoiceOver User Guide for Mac",
      "titleInlineContent": [
        {
          "text": "VoiceOver User Guide for Mac",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/voiceover/welcome/mac"
    },
    "https://support.apple.com/guide/watch/voiceover-apdaabc79d3b/watchos": {
      "identifier": "https://support.apple.com/guide/watch/voiceover-apdaabc79d3b/watchos",
      "title": "Use VoiceOver on Apple Watch",
      "titleInlineContent": [
        {
          "text": "Use VoiceOver on Apple Watch",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/watch/voiceover-apdaabc79d3b/watchos"
    },
    "switch-control-card.png": {
      "alt": "",
      "identifier": "switch-control-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4b37322483b5831fc6a7e44fb9dc05b4/switch-control-card@2x.png"
        }
      ]
    },
    "voice-control-card.png": {
      "alt": "",
      "identifier": "voice-control-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9b9495b7277bc069208a522c435b7fc7/voice-control-card@2x.png"
        }
      ]
    },
    "voiceover": {
      "alt": "",
      "identifier": "voiceover",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3cd218b9da43d8e5fd580797ddc711e9/voiceover@2x.png"
        }
      ]
    },
    "voiceover-card.png": {
      "alt": null,
      "identifier": "voiceover-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6d02ab927e1e3865da0472d09dc3aae4/voiceover-card@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Assistive-technologies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
        "doc://com.apple.Accessibility/documentation/Accessibility/switch-control",
        "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access"
      ],
      "title": "Assistive technologies"
    }
  ],
  "topicSections": [
    {
      "anchor": "Develop-for-VoiceOver",
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app",
        "doc://com.apple.documentation/documentation/UIKit/supporting-voiceover-in-your-app",
        "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze"
      ],
      "title": "Develop for VoiceOver"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Develop-for-VoiceOver",
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/performing-accessibility-testing-for-your-app",
                "doc://com.apple.documentation/documentation/UIKit/supporting-voiceover-in-your-app",
                "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze"
              ],
              "title": "Develop for VoiceOver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Assistive-technologies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/voice-control",
                "doc://com.apple.Accessibility/documentation/Accessibility/switch-control",
                "doc://com.apple.Accessibility/documentation/Accessibility/assistive-access"
              ],
              "title": "Assistive technologies"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/voiceover"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/voiceover"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
