{
  "abstract": [
    {
      "text": "Simulate a conversation using speech synthesis.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/speech"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_speech_synthesizer_simulator"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "WWDC21 Challenge: Speech Synthesizer Simulator"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This is a companion project for WWDC21 Challenge ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/news/?id=ux4fipi2",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "440080dfff4e/WWDC21ChallengeSpeechSynthesizerSimulator.zip": {
      "checksum": "440080dfff4e6c1cec54fc4b84e7a68d4de81d223b52c78d808e175067764536ec13dbc602610a9b4c93dab6eb85ac858f7c6aca10e8ac62f38447d10d77cd10",
      "identifier": "440080dfff4e/WWDC21ChallengeSpeechSynthesizerSimulator.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/440080dfff4e/WWDC21ChallengeSpeechSynthesizerSimulator.zip"
    },
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "accessibility-card-speech.png": {
      "alt": "An illustration that shows a person in an electric wheelchair sitting at a desk and using speech synthesis features on a Mac.",
      "identifier": "accessibility-card-speech.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c1f425b12f45643f5a126e3852ab9d76/accessibility-card-speech@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5655a5854b8b46288245fde1cd517f97/accessibility-card-speech~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/speech": {
      "abstract": [
        {
          "text": "A person may have a speech disability or prefer to connect without using their voice.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/speech",
      "images": [
        {
          "identifier": "accessibility-card-speech.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Speech",
      "type": "topic",
      "url": "/documentation/accessibility/speech"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_large_text_challenge": {
      "abstract": [
        {
          "text": "Design for large text sizes by modifying the user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_large_text_challenge",
      "kind": "article",
      "role": "sampleCode",
      "title": "WWDC21 Challenge: Large Text Challenge",
      "type": "topic",
      "url": "/documentation/accessibility/wwdc21_challenge_large_text_challenge"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze": {
      "abstract": [
        {
          "text": "Navigate to the end of a dark maze using VoiceOver as your guide.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze",
      "kind": "article",
      "role": "sampleCode",
      "title": "WWDC21 Challenge: VoiceOver Maze",
      "type": "topic",
      "url": "/documentation/accessibility/wwdc21_challenge_voiceover_maze"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming": {
      "abstract": [
        {
          "text": "Play a card-matching game using Switch Control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming",
      "kind": "article",
      "role": "sampleCode",
      "title": "WWDC22 Challenge: Learn Switch Control through gaming",
      "type": "topic",
      "url": "/documentation/accessibility/wwdc22_challenge_learn_switch_control_through_gaming"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/news/?id=ux4fipi2": {
      "identifier": "https://developer.apple.com/news/?id=ux4fipi2",
      "title": "Speech Synthesizer Simulator",
      "titleInlineContent": [
        {
          "text": "Speech Synthesizer Simulator",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/news/?id=ux4fipi2"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "440080dfff4e/WWDC21ChallengeSpeechSynthesizerSimulator.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "WWDC-Challenges",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming",
        "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_large_text_challenge",
        "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze"
      ],
      "title": "WWDC Challenges"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "WWDC-Challenges",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming",
                "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_large_text_challenge",
                "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze"
              ],
              "title": "WWDC Challenges"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/wwdc21_challenge_speech_synthesizer_simulator"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/wwdc21_challenge_speech_synthesizer_simulator"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
