{
  "abstract": [
    {
      "text": "Design for large text sizes by modifying the user interface.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/vision"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_large_text_challenge"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "WWDC21 Challenge: Large Text Challenge"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This is a companion project for WWDC21 Challenge ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/news/?id=w6r26g7r",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "64fbb2b49a80/WWDC21ChallengeLargeTextChallenge.zip": {
      "checksum": "64fbb2b49a80d7ca408ce2189364cb8fd7aa4fbd6b4505cd131ce7c3b6debc1271fb4dcd0dd589cf7c14214568490043eceb3cd88f58217e56186793ac417f18",
      "identifier": "64fbb2b49a80/WWDC21ChallengeLargeTextChallenge.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/64fbb2b49a80/WWDC21ChallengeLargeTextChallenge.zip"
    },
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "accessibility-card-vision.png": {
      "alt": "An illustration that shows a person with low vision walking with the assistance of a guide dog while using an iPhone and AirPods.",
      "identifier": "accessibility-card-vision.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/11631c0b01fa73cc082557dc6067840e/accessibility-card-vision@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/624a8a2e8a195d6785905c00a619d3ac/accessibility-card-vision~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/vision": {
      "abstract": [
        {
          "text": "A person may be blind or color blind, or have a vision challenge that",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "makes focusing difficult.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/vision",
      "images": [
        {
          "identifier": "accessibility-card-vision.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/accessibility/vision"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_speech_synthesizer_simulator": {
      "abstract": [
        {
          "text": "Simulate a conversation using speech synthesis.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_speech_synthesizer_simulator",
      "kind": "article",
      "role": "sampleCode",
      "title": "WWDC21 Challenge: Speech Synthesizer Simulator",
      "type": "topic",
      "url": "/documentation/accessibility/wwdc21_challenge_speech_synthesizer_simulator"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze": {
      "abstract": [
        {
          "text": "Navigate to the end of a dark maze using VoiceOver as your guide.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze",
      "kind": "article",
      "role": "sampleCode",
      "title": "WWDC21 Challenge: VoiceOver Maze",
      "type": "topic",
      "url": "/documentation/accessibility/wwdc21_challenge_voiceover_maze"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming": {
      "abstract": [
        {
          "text": "Play a card-matching game using Switch Control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming",
      "kind": "article",
      "role": "sampleCode",
      "title": "WWDC22 Challenge: Learn Switch Control through gaming",
      "type": "topic",
      "url": "/documentation/accessibility/wwdc22_challenge_learn_switch_control_through_gaming"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/news/?id=w6r26g7r": {
      "identifier": "https://developer.apple.com/news/?id=w6r26g7r",
      "title": "Large Text Challenge",
      "titleInlineContent": [
        {
          "text": "Large Text Challenge",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/news/?id=w6r26g7r"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "64fbb2b49a80/WWDC21ChallengeLargeTextChallenge.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "WWDC-Challenges",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming",
        "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_speech_synthesizer_simulator",
        "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze"
      ],
      "title": "WWDC Challenges"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "WWDC-Challenges",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/wwdc22_challenge_learn_switch_control_through_gaming",
                "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_speech_synthesizer_simulator",
                "doc://com.apple.Accessibility/documentation/Accessibility/wwdc21_challenge_voiceover_maze"
              ],
              "title": "WWDC Challenges"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/wwdc21_challenge_large_text_challenge"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/wwdc21_challenge_large_text_challenge"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
