{
  "abstract": [
    {
      "text": "Error codes that the system may return when you use Contacts framework methods.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts",
        "doc://com.apple.contacts/documentation/Contacts/CNError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CNErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CNError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError": {
      "abstract": [
        {
          "text": "Error information that may be returned when using the methods of the Contacts framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNError"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNError"
        }
      ],
      "role": "symbol",
      "title": "CNError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code": {
      "abstract": [
        {
          "text": "Error codes that the system may return when you use Contacts framework methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/authorizationDenied": {
      "abstract": [
        {
          "text": "An error that indicates the system denied authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationDenied"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/authorizationDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeAuthorizationDenied"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.authorizationDenied",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/authorizationdenied"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryExpired": {
      "abstract": [
        {
          "text": "An error that indicates the change history expired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeHistoryExpired"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryExpired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeChangeHistoryExpired"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.changeHistoryExpired",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/changehistoryexpired"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidAnchor": {
      "abstract": [
        {
          "text": "An error that indicates a change history anchor is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeHistoryInvalidAnchor"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeChangeHistoryInvalidAnchor"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.changeHistoryInvalidAnchor",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/changehistoryinvalidanchor"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidFetchRequest": {
      "abstract": [
        {
          "text": "An error that indicates a change history fetch request is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeHistoryInvalidFetchRequest"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidFetchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeChangeHistoryInvalidFetchRequest"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.changeHistoryInvalidFetchRequest",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/changehistoryinvalidfetchrequest"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierCollision": {
      "abstract": [
        {
          "text": "An error that indicates a client identifier collision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientIdentifierCollision"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierCollision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeClientIdentifierCollision"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.clientIdentifierCollision",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/clientidentifiercollision"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierDoesNotExist": {
      "abstract": [
        {
          "text": "An error that indicates the client identifier doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientIdentifierDoesNotExist"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierDoesNotExist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeClientIdentifierDoesNotExist"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.clientIdentifierDoesNotExist",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/clientidentifierdoesnotexist"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierInvalid": {
      "abstract": [
        {
          "text": "An error that indicates the client identifier is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientIdentifierInvalid"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeClientIdentifierInvalid"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.clientIdentifierInvalid",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/clientidentifierinvalid"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/communicationError": {
      "abstract": [
        {
          "text": "An error that indicates a communication error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "communicationError"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/communicationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeCommunicationError"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.communicationError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/communicationerror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentCycle": {
      "abstract": [
        {
          "text": "An error with the containment cycle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containmentCycle"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentCycle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeContainmentCycle"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.containmentCycle",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/containmentcycle"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentScope": {
      "abstract": [
        {
          "text": "An error with containment scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containmentScope"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentScope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeContainmentScope"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.containmentScope",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/containmentscope"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/dataAccessError": {
      "abstract": [
        {
          "text": "An error with data access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataAccessError"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/dataAccessError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeDataAccessError"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.dataAccessError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/dataaccesserror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureDisabledByUser": {
      "abstract": [
        {
          "text": "An error that indicates the user disabled the feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureDisabledByUser"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureDisabledByUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeFeatureDisabledByUser"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.featureDisabledByUser",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/featuredisabledbyuser"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureNotAvailable": {
      "abstract": [
        {
          "text": "An error that indicates the feature isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeFeatureNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.featureNotAvailable",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/featurenotavailable"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/init(rawvalue:)"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/insertedRecordAlreadyExists": {
      "abstract": [
        {
          "text": "An error that indicates the inserted record already exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertedRecordAlreadyExists"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/insertedRecordAlreadyExists",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeInsertedRecordAlreadyExists"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.insertedRecordAlreadyExists",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/insertedrecordalreadyexists"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/noAccessableWritableContainers": {
      "abstract": [
        {
          "text": "An error that indicates there are no accessible writable containers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noAccessableWritableContainers"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/noAccessableWritableContainers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeNoAccessableWritableContainers"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.noAccessableWritableContainers",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/noaccessablewritablecontainers"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/parentContainerNotWritable": {
      "abstract": [
        {
          "text": "An error that indicates the parent container isn’t writable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentContainerNotWritable"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/parentContainerNotWritable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeParentContainerNotWritable"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.parentContainerNotWritable",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/parentcontainernotwritable"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/parentRecordDoesNotExist": {
      "abstract": [
        {
          "text": "An error that indicates the parent record doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentRecordDoesNotExist"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/parentRecordDoesNotExist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeParentRecordDoesNotExist"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.parentRecordDoesNotExist",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/parentrecorddoesnotexist"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/policyViolation": {
      "abstract": [
        {
          "text": "An error that indicates a policy violation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "policyViolation"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/policyViolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodePolicyViolation"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.policyViolation",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/policyviolation"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/predicateInvalid": {
      "abstract": [
        {
          "text": "An error that indicates an invalid predicate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicateInvalid"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/predicateInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodePredicateInvalid"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.predicateInvalid",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/predicateinvalid"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/recordDoesNotExist": {
      "abstract": [
        {
          "text": "An error that indicates a record doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordDoesNotExist"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/recordDoesNotExist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeRecordDoesNotExist"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.recordDoesNotExist",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/recorddoesnotexist"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/recordIdentifierInvalid": {
      "abstract": [
        {
          "text": "An error that indicates a record identifier is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordIdentifierInvalid"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/recordIdentifierInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeRecordIdentifierInvalid"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.recordIdentifierInvalid",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/recordidentifierinvalid"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/recordNotWritable": {
      "abstract": [
        {
          "text": "An error that indicates a record isn’t writable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordNotWritable"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/recordNotWritable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeRecordNotWritable"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.recordNotWritable",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/recordnotwritable"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/unauthorizedKeys": {
      "abstract": [
        {
          "text": "An error that indicates unauthorized keys usage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unauthorizedKeys"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/unauthorizedKeys",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeUnauthorizedKeys"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.unauthorizedKeys",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/unauthorizedkeys"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/vCardMalformed": {
      "abstract": [
        {
          "text": "An error that indicates a malformed vCard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vCardMalformed"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/vCardMalformed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeVCardMalformed"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.vCardMalformed",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/vcardmalformed"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/vCardSummarizationError": {
      "abstract": [
        {
          "text": "An error that indicates a vCard summarization problem.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vCardSummarizationError"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/vCardSummarizationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeVCardSummarizationError"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.vCardSummarizationError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/vcardsummarizationerror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/validationConfigurationError": {
      "abstract": [
        {
          "text": "An error with validation configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validationConfigurationError"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/validationConfigurationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeValidationConfigurationError"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.validationConfigurationError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/validationconfigurationerror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/validationMultipleErrors": {
      "abstract": [
        {
          "text": "An error that indicates the system encountered multiple validation errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validationMultipleErrors"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/validationMultipleErrors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeValidationMultipleErrors"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.validationMultipleErrors",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/validationmultipleerrors"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code/validationTypeMismatch": {
      "abstract": [
        {
          "text": "A validation error that indicates a type mismatch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validationTypeMismatch"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code/validationTypeMismatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNErrorCodeValidationTypeMismatch"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code.validationTypeMismatch",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code/validationtypemismatch"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNError"
      ],
      "title": "Error codes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/authorizationDenied",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryExpired",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidAnchor",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidFetchRequest",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierCollision",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierInvalid",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierDoesNotExist",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/communicationError",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentCycle",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentScope",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/dataAccessError",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureDisabledByUser",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureNotAvailable",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/insertedRecordAlreadyExists",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/noAccessableWritableContainers",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/parentContainerNotWritable",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/parentRecordDoesNotExist",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/policyViolation",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/predicateInvalid",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/recordDoesNotExist",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/recordIdentifierInvalid",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/recordNotWritable",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/unauthorizedKeys",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/validationMultipleErrors",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/validationTypeMismatch",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/validationConfigurationError",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/vCardMalformed",
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/vCardSummarizationError"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CNErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.contacts/documentation/Contacts"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/authorizationDenied",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryExpired",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidAnchor",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/changeHistoryInvalidFetchRequest",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierCollision",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierInvalid",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/clientIdentifierDoesNotExist",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/communicationError",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentCycle",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/containmentScope",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/dataAccessError",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureDisabledByUser",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/featureNotAvailable",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/insertedRecordAlreadyExists",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/noAccessableWritableContainers",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/parentContainerNotWritable",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/parentRecordDoesNotExist",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/policyViolation",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/predicateInvalid",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/recordDoesNotExist",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/recordIdentifierInvalid",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/recordNotWritable",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/unauthorizedKeys",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/validationMultipleErrors",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/validationTypeMismatch",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/validationConfigurationError",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/vCardMalformed",
                "doc://com.apple.contacts/documentation/Contacts/CNError/Code/vCardSummarizationError"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CNErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1featureNotAvailable/title",
          "value": "CNErrorCodeFeatureNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1featureNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeFeatureNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1parentContainerNotWritable/title",
          "value": "CNErrorCodeParentContainerNotWritable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1parentContainerNotWritable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeParentContainerNotWritable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1communicationError/title",
          "value": "CNErrorCodeCommunicationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1communicationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeCommunicationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1parentRecordDoesNotExist/title",
          "value": "CNErrorCodeParentRecordDoesNotExist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1parentRecordDoesNotExist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeParentRecordDoesNotExist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1changeHistoryInvalidAnchor/title",
          "value": "CNErrorCodeChangeHistoryInvalidAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1changeHistoryInvalidAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeChangeHistoryInvalidAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1validationTypeMismatch/title",
          "value": "CNErrorCodeValidationTypeMismatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1validationTypeMismatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeValidationTypeMismatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1recordDoesNotExist/title",
          "value": "CNErrorCodeRecordDoesNotExist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1recordDoesNotExist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeRecordDoesNotExist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1validationConfigurationError/title",
          "value": "CNErrorCodeValidationConfigurationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1validationConfigurationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeValidationConfigurationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1recordIdentifierInvalid/title",
          "value": "CNErrorCodeRecordIdentifierInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1recordIdentifierInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeRecordIdentifierInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1containmentScope/title",
          "value": "CNErrorCodeContainmentScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1containmentScope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeContainmentScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1insertedRecordAlreadyExists/title",
          "value": "CNErrorCodeInsertedRecordAlreadyExists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1insertedRecordAlreadyExists/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeInsertedRecordAlreadyExists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1validationMultipleErrors/title",
          "value": "CNErrorCodeValidationMultipleErrors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1validationMultipleErrors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeValidationMultipleErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1unauthorizedKeys/title",
          "value": "CNErrorCodeUnauthorizedKeys"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1unauthorizedKeys/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeUnauthorizedKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1changeHistoryInvalidFetchRequest/title",
          "value": "CNErrorCodeChangeHistoryInvalidFetchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1changeHistoryInvalidFetchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeChangeHistoryInvalidFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code/title",
          "value": "CNErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1noAccessableWritableContainers/title",
          "value": "CNErrorCodeNoAccessableWritableContainers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1noAccessableWritableContainers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeNoAccessableWritableContainers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1vCardSummarizationError/title",
          "value": "CNErrorCodeVCardSummarizationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1vCardSummarizationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeVCardSummarizationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1authorizationDenied/title",
          "value": "CNErrorCodeAuthorizationDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1authorizationDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeAuthorizationDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1predicateInvalid/title",
          "value": "CNErrorCodePredicateInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1predicateInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodePredicateInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1changeHistoryExpired/title",
          "value": "CNErrorCodeChangeHistoryExpired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1changeHistoryExpired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeChangeHistoryExpired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1clientIdentifierCollision/title",
          "value": "CNErrorCodeClientIdentifierCollision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1clientIdentifierCollision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeClientIdentifierCollision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1containmentCycle/title",
          "value": "CNErrorCodeContainmentCycle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1containmentCycle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeContainmentCycle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1clientIdentifierDoesNotExist/title",
          "value": "CNErrorCodeClientIdentifierDoesNotExist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1clientIdentifierDoesNotExist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeClientIdentifierDoesNotExist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1policyViolation/title",
          "value": "CNErrorCodePolicyViolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1policyViolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodePolicyViolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1featureDisabledByUser/title",
          "value": "CNErrorCodeFeatureDisabledByUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1featureDisabledByUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeFeatureDisabledByUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1vCardMalformed/title",
          "value": "CNErrorCodeVCardMalformed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1vCardMalformed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeVCardMalformed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1clientIdentifierInvalid/title",
          "value": "CNErrorCodeClientIdentifierInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1clientIdentifierInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeClientIdentifierInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1recordNotWritable/title",
          "value": "CNErrorCodeRecordNotWritable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1recordNotWritable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeRecordNotWritable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1dataAccessError/title",
          "value": "CNErrorCodeDataAccessError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code~1dataAccessError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCodeDataAccessError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cnerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/contacts/cnerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
