{
  "abstract": [
    {
      "text": "An error that indicates the feature isn’t available.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.contacts/documentation/Contacts",
        "doc://com.apple.contacts/documentation/Contacts/CNError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.contacts/documentation/Contacts/CNError/featureNotAvailable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11CNErrorCodeLeV19featureNotAvailableSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "featureNotAvailable"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC11CNErrorCodeLeV",
        "text": "CNError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CNErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Contacts"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "featureNotAvailable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "featureNotAvailable"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC11CNErrorCodeLeV",
              "text": "CNError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CNErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.contacts/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/contacts"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError": {
      "abstract": [
        {
          "text": "Error information that may be returned when using the methods of the Contacts framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNError"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNError"
        }
      ],
      "role": "symbol",
      "title": "CNError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/Code": {
      "abstract": [
        {
          "text": "Error codes that the system may return when you use Contacts framework methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CNError.Code",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/code"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/authorizationDenied": {
      "abstract": [
        {
          "text": "An error that indicates the system denied authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/authorizationDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "authorizationDenied",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/authorizationdenied"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryExpired": {
      "abstract": [
        {
          "text": "An error that indicates the change history expired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeHistoryExpired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryExpired",
      "kind": "symbol",
      "role": "symbol",
      "title": "changeHistoryExpired",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/changehistoryexpired"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryInvalidAnchor": {
      "abstract": [
        {
          "text": "An error that indicates a change history anchor is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeHistoryInvalidAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryInvalidAnchor",
      "kind": "symbol",
      "role": "symbol",
      "title": "changeHistoryInvalidAnchor",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/changehistoryinvalidanchor"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryInvalidFetchRequest": {
      "abstract": [
        {
          "text": "An error that indicates a change history fetch request is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeHistoryInvalidFetchRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryInvalidFetchRequest",
      "kind": "symbol",
      "role": "symbol",
      "title": "changeHistoryInvalidFetchRequest",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/changehistoryinvalidfetchrequest"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierCollision": {
      "abstract": [
        {
          "text": "An error that indicates a client identifier collision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientIdentifierCollision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierCollision",
      "kind": "symbol",
      "role": "symbol",
      "title": "clientIdentifierCollision",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/clientidentifiercollision"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierDoesNotExist": {
      "abstract": [
        {
          "text": "An error that indicates the client identifier doesn’t exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientIdentifierDoesNotExist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierDoesNotExist",
      "kind": "symbol",
      "role": "symbol",
      "title": "clientIdentifierDoesNotExist",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/clientidentifierdoesnotexist"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierInvalid": {
      "abstract": [
        {
          "text": "An error that indicates the client identifier is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientIdentifierInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "clientIdentifierInvalid",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/clientidentifierinvalid"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/communicationError": {
      "abstract": [
        {
          "text": "An error that indicates a communication error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "communicationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/communicationError",
      "kind": "symbol",
      "role": "symbol",
      "title": "communicationError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/communicationerror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/containmentCycle": {
      "abstract": [
        {
          "text": "An error with the containment cycle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containmentCycle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/containmentCycle",
      "kind": "symbol",
      "role": "symbol",
      "title": "containmentCycle",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/containmentcycle"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/containmentScope": {
      "abstract": [
        {
          "text": "An error with containment scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containmentScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/containmentScope",
      "kind": "symbol",
      "role": "symbol",
      "title": "containmentScope",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/containmentscope"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/dataAccessError": {
      "abstract": [
        {
          "text": "An error with data access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataAccessError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/dataAccessError",
      "kind": "symbol",
      "role": "symbol",
      "title": "dataAccessError",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/dataaccesserror"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/featureDisabledByUser": {
      "abstract": [
        {
          "text": "An error that indicates the user disabled the feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureDisabledByUser"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/featureDisabledByUser",
      "kind": "symbol",
      "role": "symbol",
      "title": "featureDisabledByUser",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/featuredisabledbyuser"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/featureNotAvailable": {
      "abstract": [
        {
          "text": "An error that indicates the feature isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/featureNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "featureNotAvailable",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/featurenotavailable"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/insertedRecordAlreadyExists": {
      "abstract": [
        {
          "text": "An error that indicates the inserted record already exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertedRecordAlreadyExists"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/insertedRecordAlreadyExists",
      "kind": "symbol",
      "role": "symbol",
      "title": "insertedRecordAlreadyExists",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/insertedrecordalreadyexists"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/noAccessableWritableContainers": {
      "abstract": [
        {
          "text": "An error that indicates there are no accessible writable containers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noAccessableWritableContainers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/noAccessableWritableContainers",
      "kind": "symbol",
      "role": "symbol",
      "title": "noAccessableWritableContainers",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/noaccessablewritablecontainers"
    },
    "doc://com.apple.contacts/documentation/Contacts/CNError/parentContainerNotWritable": {
      "abstract": [
        {
          "text": "An error that indicates the parent container isn’t writable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentContainerNotWritable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11CNErrorCodeLeV",
          "text": "CNError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CNErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.contacts/documentation/Contacts/CNError/parentContainerNotWritable",
      "kind": "symbol",
      "role": "symbol",
      "title": "parentContainerNotWritable",
      "type": "topic",
      "url": "/documentation/contacts/cnerror/parentcontainernotwritable"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.contacts/documentation/Contacts/CNError/authorizationDenied",
        "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryExpired",
        "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryInvalidAnchor",
        "doc://com.apple.contacts/documentation/Contacts/CNError/changeHistoryInvalidFetchRequest",
        "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierCollision",
        "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierDoesNotExist",
        "doc://com.apple.contacts/documentation/Contacts/CNError/clientIdentifierInvalid",
        "doc://com.apple.contacts/documentation/Contacts/CNError/communicationError",
        "doc://com.apple.contacts/documentation/Contacts/CNError/containmentCycle",
        "doc://com.apple.contacts/documentation/Contacts/CNError/containmentScope",
        "doc://com.apple.contacts/documentation/Contacts/CNError/dataAccessError",
        "doc://com.apple.contacts/documentation/Contacts/CNError/featureDisabledByUser",
        "doc://com.apple.contacts/documentation/Contacts/CNError/insertedRecordAlreadyExists",
        "doc://com.apple.contacts/documentation/Contacts/CNError/noAccessableWritableContainers",
        "doc://com.apple.contacts/documentation/Contacts/CNError/parentContainerNotWritable"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code/title",
          "value": "CNErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.contacts~1documentation~1Contacts~1CNError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/contacts/cnerror/featurenotavailable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
