{
  "abstract": [
    {
      "text": "A constant that represents neither ear.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/AXHearingDeviceEar/AXHearingDeviceEarNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AXHearingDeviceEar@AXHearingDeviceEarNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AXHearingDeviceEarNone"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AXHearingDeviceEarNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "AXHearingDeviceEarNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "AXHearingDeviceEarNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXHearingDeviceEar/AXHearingDeviceEarNone": {
      "abstract": [
        {
          "text": "A constant that represents neither ear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AXHearingDeviceEarNone"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXHearingDeviceEar/AXHearingDeviceEarNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXHearingDeviceEarNone",
      "type": "topic",
      "url": "/documentation/accessibility/axhearingdeviceear/axhearingdeviceearnone"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear": {
      "abstract": [
        {
          "text": "Constants that represent a hearing device ear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Ear"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Ear"
        }
      ],
      "role": "symbol",
      "title": "AXMFiHearingDevice.Ear",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/ear"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/both": {
      "abstract": [
        {
          "text": "A constant that represents both ears.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "both"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AXMFiHearingDevice",
          "text": "AXMFiHearingDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXHearingDeviceEar",
          "text": "Ear"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/both",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXHearingDeviceEarBoth"
        }
      ],
      "role": "symbol",
      "title": "both",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/ear/both"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/left": {
      "abstract": [
        {
          "text": "A constant that represents the left ear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AXMFiHearingDevice",
          "text": "AXMFiHearingDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXHearingDeviceEar",
          "text": "Ear"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXHearingDeviceEarLeft"
        }
      ],
      "role": "symbol",
      "title": "left",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/ear/left"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/right": {
      "abstract": [
        {
          "text": "A constant that represents the right ear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AXMFiHearingDevice",
          "text": "AXMFiHearingDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXHearingDeviceEar",
          "text": "Ear"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXHearingDeviceEarRight"
        }
      ],
      "role": "symbol",
      "title": "right",
      "type": "topic",
      "url": "/documentation/accessibility/axmfihearingdevice/ear/right"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/both",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/left",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXMFiHearingDevice/Ear/right"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear~1both/title",
          "value": "AXHearingDeviceEarBoth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear~1both/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXHearingDeviceEarBoth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear/title",
          "value": "AXHearingDeviceEar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXHearingDeviceEar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXHearingDeviceEar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear~1right/title",
          "value": "AXHearingDeviceEarRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXHearingDeviceEarRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear~1left/title",
          "value": "AXHearingDeviceEarLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXMFiHearingDevice~1Ear~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXHearingDeviceEarLeft"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/axhearingdeviceear/axhearingdeviceearnone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
