{
  "abstract": [
    {
      "text": "The accessory category types supported by HomeKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategory"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager",
        "doc://com.apple.homekit/documentation/HomeKit/HMHome",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/accessory-category-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Accessory Category Types"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategory",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance’s read-only ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategory/categoryType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property contains one of the values listed below to tell you what the associated accessory does.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Don’t confuse these values with the service types found in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/accessory-service-types",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Despite the similarities, they describe different things. Accessories are the physical objects that the user installs in the home, like a garage door opener. Accessories belong to one of the categories listed here, like ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeGarageDoorOpener",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Accessories have one or more services that perform tasks. The garage door opener accessory has a garage door opener service with service type ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMServiceTypeGarageDoorOpener",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The same accessory might also have an attached light providing a light bulb service with service type ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMServiceTypeLightbulb",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessory": {
      "abstract": [
        {
          "text": "A home automation accessory, like a garage door opener or a thermostat.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessory"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessory"
        }
      ],
      "role": "symbol",
      "title": "HMAccessory",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessory"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategory": {
      "abstract": [
        {
          "text": "A category for a HomeKit accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategory"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategory"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategory",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategory"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategory/categoryType": {
      "abstract": [
        {
          "text": "The category to which this accessory belongs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "categoryType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategory/categoryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "categoryType"
        }
      ],
      "role": "symbol",
      "title": "categoryType",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategory/categorytype"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirConditioner": {
      "abstract": [
        {
          "text": "An air conditioner accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeAirConditioner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirConditioner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeAirConditioner"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeAirConditioner",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypeairconditioner"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirDehumidifier": {
      "abstract": [
        {
          "text": "A dehumidifier accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeAirDehumidifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirDehumidifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeAirDehumidifier"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeAirDehumidifier",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypeairdehumidifier"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirHeater": {
      "abstract": [
        {
          "text": "An air heater accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeAirHeater"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirHeater",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeAirHeater"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeAirHeater",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypeairheater"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirHumidifier": {
      "abstract": [
        {
          "text": "A humidifier accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeAirHumidifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirHumidifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeAirHumidifier"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeAirHumidifier",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypeairhumidifier"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirPort": {
      "abstract": [
        {
          "text": "An AirPort accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeAirPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeAirPort"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeAirPort",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypeairport"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirPurifier": {
      "abstract": [
        {
          "text": "An air purifier accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeAirPurifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirPurifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeAirPurifier"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeAirPurifier",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypeairpurifier"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAudioReceiver": {
      "abstract": [
        {
          "text": "An audio receiver accessory that supports HAP and AirPlay2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeAudioReceiver"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAudioReceiver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeAudioReceiver"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeAudioReceiver",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypeaudioreceiver"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeBridge": {
      "abstract": [
        {
          "text": "A bridge accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeBridge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeBridge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeBridge"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeBridge",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypebridge"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeDoor": {
      "abstract": [
        {
          "text": "A door accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeDoor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeDoor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeDoor"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeDoor",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypedoor"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeDoorLock": {
      "abstract": [
        {
          "text": "A door lock accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeDoorLock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeDoorLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeDoorLock"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeDoorLock",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypedoorlock"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeFan": {
      "abstract": [
        {
          "text": "A fan accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeFan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeFan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeFan"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeFan",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypefan"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeFaucet": {
      "abstract": [
        {
          "text": "A faucet accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeFaucet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeFaucet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeFaucet"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeFaucet",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypefaucet"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeGarageDoorOpener": {
      "abstract": [
        {
          "text": "A garage door opener accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeGarageDoorOpener"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeGarageDoorOpener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeGarageDoorOpener"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeGarageDoorOpener",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypegaragedooropener"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeIPCamera": {
      "abstract": [
        {
          "text": "A networked camera accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeIPCamera"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeIPCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeIPCamera"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeIPCamera",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypeipcamera"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeLightbulb": {
      "abstract": [
        {
          "text": "A lightbulb accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeLightbulb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeLightbulb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeLightbulb"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeLightbulb",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypelightbulb"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeOther": {
      "abstract": [
        {
          "text": "An uncategorized accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeOther"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeOther",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeOther"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeOther",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypeother"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeOutlet": {
      "abstract": [
        {
          "text": "An outlet accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeOutlet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeOutlet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeOutlet"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeOutlet",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypeoutlet"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeProgrammableSwitch": {
      "abstract": [
        {
          "text": "A programmable switch accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeProgrammableSwitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeProgrammableSwitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeProgrammableSwitch"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeProgrammableSwitch",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypeprogrammableswitch"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeRangeExtender": {
      "abstract": [
        {
          "text": "A range extender accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeRangeExtender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeRangeExtender",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeRangeExtender"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeRangeExtender",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytyperangeextender"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSecuritySystem": {
      "abstract": [
        {
          "text": "A security system accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeSecuritySystem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSecuritySystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeSecuritySystem"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeSecuritySystem",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypesecuritysystem"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSensor": {
      "abstract": [
        {
          "text": "A sensor accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeSensor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeSensor"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeSensor",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypesensor"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeShowerHead": {
      "abstract": [
        {
          "text": "A shower head accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeShowerHead"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeShowerHead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeShowerHead"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeShowerHead",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypeshowerhead"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSpeaker": {
      "abstract": [
        {
          "text": "A speaker accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeSpeaker"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSpeaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeSpeaker"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeSpeaker",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypespeaker"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSprinkler": {
      "abstract": [
        {
          "text": "A sprinkler system accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeSprinkler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSprinkler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeSprinkler"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeSprinkler",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypesprinkler"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSwitch": {
      "abstract": [
        {
          "text": "A switch accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeSwitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSwitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeSwitch"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeSwitch",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypeswitch"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeTelevision": {
      "abstract": [
        {
          "text": "A television accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeTelevision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeTelevision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeTelevision"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeTelevision",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypetelevision"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeTelevisionSetTopBox": {
      "abstract": [
        {
          "text": "A television set-top box accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeTelevisionSetTopBox"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeTelevisionSetTopBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeTelevisionSetTopBox"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeTelevisionSetTopBox",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypetelevisionsettopbox"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeTelevisionStreamingStick": {
      "abstract": [
        {
          "text": "A television streaming stick accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeTelevisionStreamingStick"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeTelevisionStreamingStick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeTelevisionStreamingStick"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeTelevisionStreamingStick",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypetelevisionstreamingstick"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeThermostat": {
      "abstract": [
        {
          "text": "A thermostat accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeThermostat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeThermostat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeThermostat"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeThermostat",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypethermostat"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeVideoDoorbell": {
      "abstract": [
        {
          "text": "A video doorbell accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeVideoDoorbell"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeVideoDoorbell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeVideoDoorbell"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeVideoDoorbell",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypevideodoorbell"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeWiFiRouter": {
      "abstract": [
        {
          "text": "A WiFi router accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeWiFiRouter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeWiFiRouter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeWiFiRouter"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeWiFiRouter",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypewifirouter"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeWindow": {
      "abstract": [
        {
          "text": "A window accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeWindow"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeWindow",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypewindow"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeWindowCovering": {
      "abstract": [
        {
          "text": "A window covering accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeWindowCovering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeWindowCovering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeWindowCovering"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeWindowCovering",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypewindowcovering"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHome": {
      "abstract": [
        {
          "text": "The primary unit of living space, typically composed of rooms organized into zones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "role": "symbol",
      "title": "HMHome",
      "type": "topic",
      "url": "/documentation/homekit/hmhome"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager": {
      "abstract": [
        {
          "text": "The manager for a collection of one or more of a user’s homes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "role": "symbol",
      "title": "HMHomeManager",
      "type": "topic",
      "url": "/documentation/homekit/hmhomemanager"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMServiceTypeGarageDoorOpener": {
      "abstract": [
        {
          "text": "A garage door opener service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMServiceTypeGarageDoorOpener"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMServiceTypeGarageDoorOpener",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMServiceTypeGarageDoorOpener"
        }
      ],
      "role": "symbol",
      "title": "HMServiceTypeGarageDoorOpener",
      "type": "topic",
      "url": "/documentation/homekit/hmservicetypegaragedooropener"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMServiceTypeLightbulb": {
      "abstract": [
        {
          "text": "A light bulb service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMServiceTypeLightbulb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMServiceTypeLightbulb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMServiceTypeLightbulb"
        }
      ],
      "role": "symbol",
      "title": "HMServiceTypeLightbulb",
      "type": "topic",
      "url": "/documentation/homekit/hmservicetypelightbulb"
    },
    "doc://com.apple.homekit/documentation/HomeKit/accessory-service-types": {
      "abstract": [
        {
          "text": "The service types supported by HomeKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/accessory-service-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessory Service Types",
      "type": "topic",
      "url": "/documentation/homekit/accessory-service-types"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-the-category-type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategory/categoryType"
      ],
      "title": "Reading the category type"
    }
  ],
  "topicSections": [
    {
      "anchor": "Light",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeLightbulb"
      ],
      "title": "Light"
    },
    {
      "anchor": "Power-and-switches",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeOutlet",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeProgrammableSwitch",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSwitch"
      ],
      "title": "Power and switches"
    },
    {
      "anchor": "Air-quality-and-smoke-detection",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeFan",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirPurifier"
      ],
      "title": "Air quality and smoke detection"
    },
    {
      "anchor": "Temperature-and-humidity",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeThermostat",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirConditioner",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirDehumidifier",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirHeater",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirHumidifier"
      ],
      "title": "Temperature and humidity"
    },
    {
      "anchor": "Windows",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeWindow",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeWindowCovering"
      ],
      "title": "Windows"
    },
    {
      "anchor": "Locks-and-openers",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeDoor",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeDoorLock",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeGarageDoorOpener",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeVideoDoorbell"
      ],
      "title": "Locks and openers"
    },
    {
      "anchor": "Safety-and-security",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSensor",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSecuritySystem"
      ],
      "title": "Safety and security"
    },
    {
      "anchor": "Cameras",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeIPCamera"
      ],
      "title": "Cameras"
    },
    {
      "anchor": "Water",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSprinkler",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeFaucet",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeShowerHead"
      ],
      "title": "Water"
    },
    {
      "anchor": "Network",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeBridge",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeRangeExtender",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirPort",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeWiFiRouter"
      ],
      "title": "Network"
    },
    {
      "anchor": "Audio-and-sound",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAudioReceiver",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSpeaker"
      ],
      "title": "Audio and sound"
    },
    {
      "anchor": "Television",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeTelevision",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeTelevisionSetTopBox",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeTelevisionStreamingStick"
      ],
      "title": "Television"
    },
    {
      "anchor": "Uncategorized",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeOther"
      ],
      "title": "Uncategorized"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Light",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeLightbulb"
              ],
              "title": "Light"
            },
            {
              "anchor": "Power-and-switches",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeOutlet",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeProgrammableSwitch",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSwitch"
              ],
              "title": "Power and switches"
            },
            {
              "anchor": "Air-quality-and-smoke-detection",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeFan",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirPurifier"
              ],
              "title": "Air quality and smoke detection"
            },
            {
              "anchor": "Temperature-and-humidity",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeThermostat",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirConditioner",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirDehumidifier",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirHeater",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirHumidifier"
              ],
              "title": "Temperature and humidity"
            },
            {
              "anchor": "Windows",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeWindow",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeWindowCovering"
              ],
              "title": "Windows"
            },
            {
              "anchor": "Locks-and-openers",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeDoor",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeDoorLock",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeGarageDoorOpener",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeVideoDoorbell"
              ],
              "title": "Locks and openers"
            },
            {
              "anchor": "Safety-and-security",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSensor",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSecuritySystem"
              ],
              "title": "Safety and security"
            },
            {
              "anchor": "Cameras",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeIPCamera"
              ],
              "title": "Cameras"
            },
            {
              "anchor": "Water",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSprinkler",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeFaucet",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeShowerHead"
              ],
              "title": "Water"
            },
            {
              "anchor": "Network",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeBridge",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeRangeExtender",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAirPort",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeWiFiRouter"
              ],
              "title": "Network"
            },
            {
              "anchor": "Audio-and-sound",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeAudioReceiver",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSpeaker"
              ],
              "title": "Audio and sound"
            },
            {
              "anchor": "Television",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeTelevision",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeTelevisionSetTopBox",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeTelevisionStreamingStick"
              ],
              "title": "Television"
            },
            {
              "anchor": "Uncategorized",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeOther"
              ],
              "title": "Uncategorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reading-the-category-type",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategory/categoryType"
              ],
              "title": "Reading the category type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeIPCamera/title",
          "value": "HMAccessoryCategoryTypeIPCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeIPCamera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeIPCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeWindow/title",
          "value": "HMAccessoryCategoryTypeWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeTelevision/title",
          "value": "HMAccessoryCategoryTypeTelevision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeTelevision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeTelevision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeLightbulb/title",
          "value": "HMAccessoryCategoryTypeLightbulb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeLightbulb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeLightbulb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/title",
          "value": "HMHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeThermostat/title",
          "value": "HMAccessoryCategoryTypeThermostat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeThermostat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeThermostat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeAirHeater/title",
          "value": "HMAccessoryCategoryTypeAirHeater"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeAirHeater/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeAirHeater"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategory/title",
          "value": "HMAccessoryCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeSensor/title",
          "value": "HMAccessoryCategoryTypeSensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeSensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeSprinkler/title",
          "value": "HMAccessoryCategoryTypeSprinkler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeSprinkler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeSprinkler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeAirPort/title",
          "value": "HMAccessoryCategoryTypeAirPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeAirPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeAirPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/title",
          "value": "HMAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategory~1categoryType/title",
          "value": "categoryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategory~1categoryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "categoryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeFan/title",
          "value": "HMAccessoryCategoryTypeFan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeFan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeFan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeWiFiRouter/title",
          "value": "HMAccessoryCategoryTypeWiFiRouter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeWiFiRouter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeWiFiRouter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeDoorLock/title",
          "value": "HMAccessoryCategoryTypeDoorLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeDoorLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeDoorLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeGarageDoorOpener/title",
          "value": "HMAccessoryCategoryTypeGarageDoorOpener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeGarageDoorOpener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeGarageDoorOpener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeBridge/title",
          "value": "HMAccessoryCategoryTypeBridge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeBridge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeBridge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeTelevisionSetTopBox/title",
          "value": "HMAccessoryCategoryTypeTelevisionSetTopBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeTelevisionSetTopBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeTelevisionSetTopBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeAirPurifier/title",
          "value": "HMAccessoryCategoryTypeAirPurifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeAirPurifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeAirPurifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeAudioReceiver/title",
          "value": "HMAccessoryCategoryTypeAudioReceiver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeAudioReceiver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeAudioReceiver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeSecuritySystem/title",
          "value": "HMAccessoryCategoryTypeSecuritySystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeSecuritySystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeSecuritySystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeShowerHead/title",
          "value": "HMAccessoryCategoryTypeShowerHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeShowerHead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeShowerHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeFaucet/title",
          "value": "HMAccessoryCategoryTypeFaucet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeFaucet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeFaucet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeSpeaker/title",
          "value": "HMAccessoryCategoryTypeSpeaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeSpeaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeSpeaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeVideoDoorbell/title",
          "value": "HMAccessoryCategoryTypeVideoDoorbell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeVideoDoorbell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeVideoDoorbell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeAirConditioner/title",
          "value": "HMAccessoryCategoryTypeAirConditioner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeAirConditioner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeAirConditioner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMServiceTypeLightbulb/title",
          "value": "HMServiceTypeLightbulb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMServiceTypeLightbulb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMServiceTypeLightbulb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeAirDehumidifier/title",
          "value": "HMAccessoryCategoryTypeAirDehumidifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeAirDehumidifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeAirDehumidifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeWindowCovering/title",
          "value": "HMAccessoryCategoryTypeWindowCovering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeWindowCovering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeWindowCovering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeOutlet/title",
          "value": "HMAccessoryCategoryTypeOutlet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeOutlet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeOutlet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeAirHumidifier/title",
          "value": "HMAccessoryCategoryTypeAirHumidifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeAirHumidifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeAirHumidifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeOther/title",
          "value": "HMAccessoryCategoryTypeOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeOther/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeRangeExtender/title",
          "value": "HMAccessoryCategoryTypeRangeExtender"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeRangeExtender/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeRangeExtender"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/title",
          "value": "HMHomeManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeDoor/title",
          "value": "HMAccessoryCategoryTypeDoor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeDoor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeDoor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeSwitch/title",
          "value": "HMAccessoryCategoryTypeSwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeSwitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeTelevisionStreamingStick/title",
          "value": "HMAccessoryCategoryTypeTelevisionStreamingStick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeTelevisionStreamingStick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeTelevisionStreamingStick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMServiceTypeGarageDoorOpener/title",
          "value": "HMServiceTypeGarageDoorOpener"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMServiceTypeGarageDoorOpener/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMServiceTypeGarageDoorOpener"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeProgrammableSwitch/title",
          "value": "HMAccessoryCategoryTypeProgrammableSwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeProgrammableSwitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeProgrammableSwitch"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/accessory-category-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/accessory-category-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
