{
  "abstract": [
    {
      "text": "The types of action sets that you can define.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSet"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager",
        "doc://com.apple.homekit/documentation/HomeKit/HMHome",
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSet"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/action-set-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Action Set Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSet": {
      "abstract": [
        {
          "text": "A collection of actions that you trigger as a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMActionSet"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMActionSet"
        }
      ],
      "role": "symbol",
      "title": "HMActionSet",
      "type": "topic",
      "url": "/documentation/homekit/hmactionset"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/actionSetType": {
      "abstract": [
        {
          "text": "The type of the action set, such as built-in or user-defined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionSetType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/actionSetType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "actionSetType"
        }
      ],
      "role": "symbol",
      "title": "actionSetType",
      "type": "topic",
      "url": "/documentation/homekit/hmactionset/actionsettype"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeHomeArrival": {
      "abstract": [
        {
          "text": "Specifies the HomeArrival built-in action set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMActionSetTypeHomeArrival"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeHomeArrival",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMActionSetTypeHomeArrival"
        }
      ],
      "role": "symbol",
      "title": "HMActionSetTypeHomeArrival",
      "type": "topic",
      "url": "/documentation/homekit/hmactionsettypehomearrival"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeHomeDeparture": {
      "abstract": [
        {
          "text": "Specifies the HomeDeparture built-in action set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMActionSetTypeHomeDeparture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeHomeDeparture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMActionSetTypeHomeDeparture"
        }
      ],
      "role": "symbol",
      "title": "HMActionSetTypeHomeDeparture",
      "type": "topic",
      "url": "/documentation/homekit/hmactionsettypehomedeparture"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeSleep": {
      "abstract": [
        {
          "text": "Specifies the Sleep built-in action set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMActionSetTypeSleep"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeSleep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMActionSetTypeSleep"
        }
      ],
      "role": "symbol",
      "title": "HMActionSetTypeSleep",
      "type": "topic",
      "url": "/documentation/homekit/hmactionsettypesleep"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeTriggerOwned": {
      "abstract": [
        {
          "text": "Specifies a trigger-owned action set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMActionSetTypeTriggerOwned"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeTriggerOwned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMActionSetTypeTriggerOwned"
        }
      ],
      "role": "symbol",
      "title": "HMActionSetTypeTriggerOwned",
      "type": "topic",
      "url": "/documentation/homekit/hmactionsettypetriggerowned"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeUserDefined": {
      "abstract": [
        {
          "text": "Specifies a user-defined action set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMActionSetTypeUserDefined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeUserDefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMActionSetTypeUserDefined"
        }
      ],
      "role": "symbol",
      "title": "HMActionSetTypeUserDefined",
      "type": "topic",
      "url": "/documentation/homekit/hmactionsettypeuserdefined"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeWakeUp": {
      "abstract": [
        {
          "text": "Specifies the WakeUp built-in action set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMActionSetTypeWakeUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeWakeUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMActionSetTypeWakeUp"
        }
      ],
      "role": "symbol",
      "title": "HMActionSetTypeWakeUp",
      "type": "topic",
      "url": "/documentation/homekit/hmactionsettypewakeup"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHome": {
      "abstract": [
        {
          "text": "The primary unit of living space, typically composed of rooms organized into zones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "role": "symbol",
      "title": "HMHome",
      "type": "topic",
      "url": "/documentation/homekit/hmhome"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager": {
      "abstract": [
        {
          "text": "The manager for a collection of one or more of a user’s homes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "role": "symbol",
      "title": "HMHomeManager",
      "type": "topic",
      "url": "/documentation/homekit/hmhomemanager"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-a-type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/actionSetType"
      ],
      "title": "Specifying a type"
    }
  ],
  "topicSections": [
    {
      "anchor": "Built-in-Types",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeHomeArrival",
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeHomeDeparture",
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeSleep",
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeWakeUp"
      ],
      "title": "Built-in Types"
    },
    {
      "anchor": "User-Defined-Types",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeUserDefined"
      ],
      "title": "User Defined Types"
    },
    {
      "anchor": "Trigger-Owned-Types",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeTriggerOwned"
      ],
      "title": "Trigger Owned Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Built-in-Types",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeHomeArrival",
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeHomeDeparture",
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeSleep",
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeWakeUp"
              ],
              "title": "Built-in Types"
            },
            {
              "anchor": "User-Defined-Types",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeUserDefined"
              ],
              "title": "User Defined Types"
            },
            {
              "anchor": "Trigger-Owned-Types",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSetTypeTriggerOwned"
              ],
              "title": "Trigger Owned Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-a-type",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/actionSetType"
              ],
              "title": "Specifying a type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSetTypeHomeArrival/title",
          "value": "HMActionSetTypeHomeArrival"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSetTypeHomeArrival/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMActionSetTypeHomeArrival"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSetTypeHomeDeparture/title",
          "value": "HMActionSetTypeHomeDeparture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSetTypeHomeDeparture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMActionSetTypeHomeDeparture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/title",
          "value": "HMHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSetTypeWakeUp/title",
          "value": "HMActionSetTypeWakeUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSetTypeWakeUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMActionSetTypeWakeUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSetTypeUserDefined/title",
          "value": "HMActionSetTypeUserDefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSetTypeUserDefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMActionSetTypeUserDefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet/title",
          "value": "HMActionSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMActionSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMActionSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSetTypeTriggerOwned/title",
          "value": "HMActionSetTypeTriggerOwned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSetTypeTriggerOwned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMActionSetTypeTriggerOwned"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSetTypeSleep/title",
          "value": "HMActionSetTypeSleep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSetTypeSleep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMActionSetTypeSleep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1actionSetType/title",
          "value": "actionSetType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1actionSetType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "actionSetType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/title",
          "value": "HMHomeManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/action-set-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/action-set-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
