{
  "abstract": [
    {
      "text": "Constants for identifying the data format of characteristic values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMService",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
        "doc://com.apple.homekit/documentation/HomeKit/HMService",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager",
        "doc://com.apple.homekit/documentation/HomeKit/HMHome",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
        "doc://com.apple.homekit/documentation/HomeKit/HMService",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/characteristic-data-formats"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Characteristic Data Formats"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Expect to find one of these values in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata/format",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of a characteristic’s metadata.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessory": {
      "abstract": [
        {
          "text": "A home automation accessory, like a garage door opener or a thermostat.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessory"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessory"
        }
      ],
      "role": "symbol",
      "title": "HMAccessory",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessory"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic": {
      "abstract": [
        {
          "text": "A specific characteristic of a service, like the brightness of a dimmable light or its color temperature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristic"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristic",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata": {
      "abstract": [
        {
          "text": "Metadata that describes a characteristic’s value and that may be useful for presentation purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadata"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadata"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadata",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadata"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata/format": {
      "abstract": [
        {
          "text": "The format of the values for the characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata/format",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "format"
        }
      ],
      "role": "symbol",
      "title": "format",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadata/format"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatArray": {
      "abstract": [
        {
          "text": "Indicates that the characteristic has array values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatArray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatArray"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataFormatArray",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataformatarray"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatBool": {
      "abstract": [
        {
          "text": "Indicates that the characteristic has Boolean values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatBool"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatBool",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatBool"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataFormatBool",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataformatbool"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatData": {
      "abstract": [
        {
          "text": "Indicates that the characteristic has data blob values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatData"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataFormatData",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataformatdata"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatDictionary": {
      "abstract": [
        {
          "text": "Indicates that the characteristic has dictionary values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatDictionary"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataFormatDictionary",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataformatdictionary"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatFloat": {
      "abstract": [
        {
          "text": "Indicates that the characteristic has ",
          "type": "text"
        },
        {
          "code": "float",
          "type": "codeVoice"
        },
        {
          "text": " values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatFloat"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataFormatFloat",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataformatfloat"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatInt": {
      "abstract": [
        {
          "text": "Indicates that the characteristic has ",
          "type": "text"
        },
        {
          "code": "int",
          "type": "codeVoice"
        },
        {
          "text": " values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatInt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatInt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatInt"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataFormatInt",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataformatint"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatString": {
      "abstract": [
        {
          "text": "Indicates that the characteristic has string values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatString"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataFormatString",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataformatstring"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatTLV8": {
      "abstract": [
        {
          "text": "Indicates that the characteristic has TLV8 values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatTLV8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatTLV8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatTLV8"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataFormatTLV8",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataformattlv8"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt16": {
      "abstract": [
        {
          "text": "Indicates that the characteristic has unsigned 16-bit integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatUInt16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatUInt16"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataFormatUInt16",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataformatuint16"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt32": {
      "abstract": [
        {
          "text": "Indicates that the characteristic has unsigned 32-bit integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatUInt32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatUInt32"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataFormatUInt32",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataformatuint32"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt64": {
      "abstract": [
        {
          "text": "Indicates that the characteristic has unsigned 64-bit integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatUInt64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatUInt64"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataFormatUInt64",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataformatuint64"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt8": {
      "abstract": [
        {
          "text": "Indicates that the characteristic has unsigned 8-bit integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatUInt8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataFormatUInt8"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataFormatUInt8",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataformatuint8"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHome": {
      "abstract": [
        {
          "text": "The primary unit of living space, typically composed of rooms organized into zones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "role": "symbol",
      "title": "HMHome",
      "type": "topic",
      "url": "/documentation/homekit/hmhome"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager": {
      "abstract": [
        {
          "text": "The manager for a collection of one or more of a user’s homes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "role": "symbol",
      "title": "HMHomeManager",
      "type": "topic",
      "url": "/documentation/homekit/hmhomemanager"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMService": {
      "abstract": [
        {
          "text": "A controllable feature of an accessory, like a light attached to a garage door opener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMService"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMService"
        }
      ],
      "role": "symbol",
      "title": "HMService",
      "type": "topic",
      "url": "/documentation/homekit/hmservice"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Formatting-the-value",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata/format"
      ],
      "title": "Formatting the value"
    }
  ],
  "topicSections": [
    {
      "anchor": "Booleans",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatBool"
      ],
      "title": "Booleans"
    },
    {
      "anchor": "Strings",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatString"
      ],
      "title": "Strings"
    },
    {
      "anchor": "Signed-Values",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatInt",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatFloat"
      ],
      "title": "Signed Values"
    },
    {
      "anchor": "Unsigned-Integers",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt8",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt16",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt32",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt64"
      ],
      "title": "Unsigned Integers"
    },
    {
      "anchor": "Data",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatData",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatTLV8"
      ],
      "title": "Data"
    },
    {
      "anchor": "Collections",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatArray",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatDictionary"
      ],
      "title": "Collections"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Booleans",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatBool"
              ],
              "title": "Booleans"
            },
            {
              "anchor": "Strings",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatString"
              ],
              "title": "Strings"
            },
            {
              "anchor": "Signed-Values",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatInt",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatFloat"
              ],
              "title": "Signed Values"
            },
            {
              "anchor": "Unsigned-Integers",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt8",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt16",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt32",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatUInt64"
              ],
              "title": "Unsigned Integers"
            },
            {
              "anchor": "Data",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatData",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatTLV8"
              ],
              "title": "Data"
            },
            {
              "anchor": "Collections",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatArray",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataFormatDictionary"
              ],
              "title": "Collections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Formatting-the-value",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata/format"
              ],
              "title": "Formatting the value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatBool/title",
          "value": "HMCharacteristicMetadataFormatBool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatBool/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataFormatBool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/title",
          "value": "HMAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatInt/title",
          "value": "HMCharacteristicMetadataFormatInt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatInt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataFormatInt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatData/title",
          "value": "HMCharacteristicMetadataFormatData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataFormatData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatUInt8/title",
          "value": "HMCharacteristicMetadataFormatUInt8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatUInt8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataFormatUInt8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatString/title",
          "value": "HMCharacteristicMetadataFormatString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataFormatString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatUInt16/title",
          "value": "HMCharacteristicMetadataFormatUInt16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatUInt16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataFormatUInt16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/title",
          "value": "HMHomeManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic/title",
          "value": "HMCharacteristic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatDictionary/title",
          "value": "HMCharacteristicMetadataFormatDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataFormatDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatTLV8/title",
          "value": "HMCharacteristicMetadataFormatTLV8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatTLV8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataFormatTLV8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/title",
          "value": "HMHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadata/title",
          "value": "HMCharacteristicMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatFloat/title",
          "value": "HMCharacteristicMetadataFormatFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataFormatFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatArray/title",
          "value": "HMCharacteristicMetadataFormatArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataFormatArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatUInt64/title",
          "value": "HMCharacteristicMetadataFormatUInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatUInt64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataFormatUInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadata~1format/title",
          "value": "format"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadata~1format/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "format"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService/title",
          "value": "HMService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatUInt32/title",
          "value": "HMCharacteristicMetadataFormatUInt32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataFormatUInt32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataFormatUInt32"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/characteristic-data-formats"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/characteristic-data-formats"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
