{
  "abstract": [
    {
      "text": "Descriptions of the units of a characteristic.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMService",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
        "doc://com.apple.homekit/documentation/HomeKit/HMService",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager",
        "doc://com.apple.homekit/documentation/HomeKit/HMHome",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
        "doc://com.apple.homekit/documentation/HomeKit/HMService",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/characteristic-units"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Characteristic Units"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Expect to find one of these values in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata/units",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of a characteristic’s metadata.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessory": {
      "abstract": [
        {
          "text": "A home automation accessory, like a garage door opener or a thermostat.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessory"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessory"
        }
      ],
      "role": "symbol",
      "title": "HMAccessory",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessory"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic": {
      "abstract": [
        {
          "text": "A specific characteristic of a service, like the brightness of a dimmable light or its color temperature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristic"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristic",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata": {
      "abstract": [
        {
          "text": "Metadata that describes a characteristic’s value and that may be useful for presentation purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadata"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadata"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadata",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadata"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata/units": {
      "abstract": [
        {
          "text": "The units of the characteristic value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "units"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata/units",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "units"
        }
      ],
      "role": "symbol",
      "title": "units",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadata/units"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsArcDegree": {
      "abstract": [
        {
          "text": "The unit of the characteristic is the degrees of an arc.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsArcDegree"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsArcDegree",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsArcDegree"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataUnitsArcDegree",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataunitsarcdegree"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsCelsius": {
      "abstract": [
        {
          "text": "The unit of the characteristic is celsius.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsCelsius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsCelsius",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsCelsius"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataUnitsCelsius",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataunitscelsius"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsFahrenheit": {
      "abstract": [
        {
          "text": "The unit of the characteristic is fahrenheit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsFahrenheit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsFahrenheit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsFahrenheit"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataUnitsFahrenheit",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataunitsfahrenheit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsLux": {
      "abstract": [
        {
          "text": "The unit of the characteristic is lux (that is, illuminance).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsLux"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsLux",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsLux"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataUnitsLux",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataunitslux"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsMicrogramsPerCubicMeter": {
      "abstract": [
        {
          "text": "The unit of the characteristic is micrograms per cubic meter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsMicrogramsPerCubicMeter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsMicrogramsPerCubicMeter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsMicrogramsPerCubicMeter"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataUnitsMicrogramsPerCubicMeter",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataunitsmicrogramspercubicmeter"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsPartsPerMillion": {
      "abstract": [
        {
          "text": "The unit of the characters is parts per million.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsPartsPerMillion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsPartsPerMillion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsPartsPerMillion"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataUnitsPartsPerMillion",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataunitspartspermillion"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsPercentage": {
      "abstract": [
        {
          "text": "The unit of the characteristic is a percentage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsPercentage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsPercentage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsPercentage"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataUnitsPercentage",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataunitspercentage"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsSeconds": {
      "abstract": [
        {
          "text": "The unit of the characteristic is seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsSeconds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsSeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadataUnitsSeconds"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadataUnitsSeconds",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadataunitsseconds"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHome": {
      "abstract": [
        {
          "text": "The primary unit of living space, typically composed of rooms organized into zones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "role": "symbol",
      "title": "HMHome",
      "type": "topic",
      "url": "/documentation/homekit/hmhome"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager": {
      "abstract": [
        {
          "text": "The manager for a collection of one or more of a user’s homes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "role": "symbol",
      "title": "HMHomeManager",
      "type": "topic",
      "url": "/documentation/homekit/hmhomemanager"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMService": {
      "abstract": [
        {
          "text": "A controllable feature of an accessory, like a light attached to a garage door opener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMService"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMService"
        }
      ],
      "role": "symbol",
      "title": "HMService",
      "type": "topic",
      "url": "/documentation/homekit/hmservice"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-units",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata/units"
      ],
      "title": "Specifying units"
    }
  ],
  "topicSections": [
    {
      "anchor": "Parts-Per-Total",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsPercentage",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsPartsPerMillion"
      ],
      "title": "Parts Per Total"
    },
    {
      "anchor": "Temperature",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsCelsius",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsFahrenheit"
      ],
      "title": "Temperature"
    },
    {
      "anchor": "Time",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsSeconds"
      ],
      "title": "Time"
    },
    {
      "anchor": "Light",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsLux"
      ],
      "title": "Light"
    },
    {
      "anchor": "Mass",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsMicrogramsPerCubicMeter"
      ],
      "title": "Mass"
    },
    {
      "anchor": "Rotation",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsArcDegree"
      ],
      "title": "Rotation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Parts-Per-Total",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsPercentage",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsPartsPerMillion"
              ],
              "title": "Parts Per Total"
            },
            {
              "anchor": "Temperature",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsCelsius",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsFahrenheit"
              ],
              "title": "Temperature"
            },
            {
              "anchor": "Time",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsSeconds"
              ],
              "title": "Time"
            },
            {
              "anchor": "Light",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsLux"
              ],
              "title": "Light"
            },
            {
              "anchor": "Mass",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsMicrogramsPerCubicMeter"
              ],
              "title": "Mass"
            },
            {
              "anchor": "Rotation",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadataUnitsArcDegree"
              ],
              "title": "Rotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-units",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata/units"
              ],
              "title": "Specifying units"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadata~1units/title",
          "value": "units"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadata~1units/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "units"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadata/title",
          "value": "HMCharacteristicMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/title",
          "value": "HMHomeManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic/title",
          "value": "HMCharacteristic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/title",
          "value": "HMAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsArcDegree/title",
          "value": "HMCharacteristicMetadataUnitsArcDegree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsArcDegree/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataUnitsArcDegree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsPercentage/title",
          "value": "HMCharacteristicMetadataUnitsPercentage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsPercentage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataUnitsPercentage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService/title",
          "value": "HMService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsMicrogramsPerCubicMeter/title",
          "value": "HMCharacteristicMetadataUnitsMicrogramsPerCubicMeter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsMicrogramsPerCubicMeter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataUnitsMicrogramsPerCubicMeter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsCelsius/title",
          "value": "HMCharacteristicMetadataUnitsCelsius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsCelsius/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataUnitsCelsius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/title",
          "value": "HMHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsPartsPerMillion/title",
          "value": "HMCharacteristicMetadataUnitsPartsPerMillion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsPartsPerMillion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataUnitsPartsPerMillion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsFahrenheit/title",
          "value": "HMCharacteristicMetadataUnitsFahrenheit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsFahrenheit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataUnitsFahrenheit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsSeconds/title",
          "value": "HMCharacteristicMetadataUnitsSeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsSeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataUnitsSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsLux/title",
          "value": "HMCharacteristicMetadataUnitsLux"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadataUnitsLux/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadataUnitsLux"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/characteristic-units"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/characteristic-units"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
