{
  "abstract": [
    {
      "text": "Give users a familiar experience when they manage HomeKit accessories.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/configuring-a-home-automation-device"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "12.1",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "12.1",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.2",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Configuring a home automation device"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample presents a simplified version of the kind of app a HomeKit-enabled accessory manufacturer might provide. You use the app to configure and control a specific device—a garage door opener from a fictional manufacturer, Kilgo Devices. The app offers access to secondary and custom characteristics that Apple’s Home app doesn’t expose. It provides a user experience that’s consistent with the Home app’s approach and terminology, but doesn’t attempt to replicate every feature of the Home app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "GarageControl.png",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about user interface considerations for HomeKit-enabled apps, see the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/homekit/overview/introduction/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " section of the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-the-sample-code-project",
          "level": 3,
          "text": "Configure the sample code project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To be able to use HomeKit, you enable the HomeKit capability and include the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/bundleresources/information_property_list/nshomekitusagedescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key in your app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file, as described in ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/homekit/enabling_homekit_in_your_app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". In this sample app, the capability is already enabled and a usage description is provided.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Perform the following steps before building and running the app:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set a valid signing team in the target’s General pane so that Xcode can create a provisioning profile containing the HomeKit entitlement when you build for the first time.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Download and install the Home Accessory Simulator (HAS) on your Mac to be able to emulate HomeKit-enabled accessories. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/documentation/homekit/testing_your_app_with_the_homekit_accessory_simulator",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Import the ",
                      "type": "text"
                    },
                    {
                      "code": "hasaccessory",
                      "type": "codeVoice"
                    },
                    {
                      "text": " file that the sample app bundles to define the specific garage door opener accessory that the app controls. Choose ",
                      "type": "text"
                    },
                    {
                      "code": "File > Import Accessory",
                      "type": "codeVoice"
                    },
                    {
                      "text": " from the HAS menu. In the dialog that appears, navigate to the downloaded sample code project’s ",
                      "type": "text"
                    },
                    {
                      "code": "Documentation",
                      "type": "codeVoice"
                    },
                    {
                      "text": " folder, and select the ",
                      "type": "text"
                    },
                    {
                      "code": "garage.hasaccessory",
                      "type": "codeVoice"
                    },
                    {
                      "text": " file.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The import creates a single accessory with a hidden accessory information service that all accessories have, and two user-interactive services: one that controls a garage door and another to control an attached light bulb. Most of the associated characteristics are standard for their service. Only one—the light bulb’s fade rate—is custom. You can use HAS to inspect and manipulate all of these items.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-home-manager-and-get-the-primary-home",
          "level": 3,
          "text": "Create a home manager and get the primary home",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You always use an instance of ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/homekit/hmhomemanager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " as the root HomeKit object. The home manager contains an array of homes, each of which has a collection of accessories. The sample app defines a ",
              "type": "text"
            },
            {
              "code": "HomeStore",
              "type": "codeVoice"
            },
            {
              "text": " class for use as a singleton that holds the one and only home manager for the app:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class HomeStore: NSObject {",
            "    /// A singleton that can be used anywhere in the app to access the home manager.",
            "    static var shared = HomeStore()",
            "    ",
            "    /// The one and only home manager that belongs to the home store singleton.",
            "    let homeManager = HMHomeManager()",
            "    ",
            "    /// A set of objects that want to receive home delegate callbacks.",
            "    var homeDelegates = Set<NSObject>()",
            "    ",
            "    /// A set of objects that want to receive accessory delegate callbacks.",
            "    var accessoryDelegates = Set<NSObject>()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "You create an accessory list collection view controller to present the list of connected accessories. Because this root view controller never gets deallocated, it can safely assign itself as the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/homekit/hmhomemanagerdelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol delegate:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "HomeStore.shared.homeManager.delegate = self"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The manager tells its delegate when the list of homes changes, including the first time the home manager loads data from the HomeKit database during initialization. When this happens, the accessory list reloads to show the accessories in the primary home, or prompts the user to create a new home if none exists.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can extend the app to allow the user to select among all known homes instead of always choosing the primary home. You can also allow users to add, remove, or rename homes, although the user performs these tasks infrequently, and typically relies on the Home app to do so.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-new-accessories",
          "level": 3,
          "text": "Add new accessories",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The first time you run the app, the accessory list is empty, because you haven’t associated any accessories from Kilgo Devices. The app’s UI presents a ",
              "type": "text"
            },
            {
              "code": "+",
              "type": "codeVoice"
            },
            {
              "text": " button in the navigation bar that you tap to initiate a search for accessories on the local network. The button’s tap handler calls the home’s ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/homekit/hmhome/1771427-addandsetupaccessories",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "home?.addAndSetupAccessories(completionHandler: { error in",
            "    if let error = error {",
            "        print(error)",
            "    } else {",
            "        // Make no assumption about changes; just reload everything.",
            "        self.reloadData()",
            "    }",
            "})"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This presents the standard HomeKit UI for locating and adding new accessories to a given home. On success, the completion handler refreshes the app’s copy of the HomeKit data and redraws the display.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When your app enters the standard accessory association flow, which is the same one that the Home app uses, the user follows these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Scan or enter the new device’s HomeKit setup code.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " This code comes packaged with the device, or is available in the HAS display for the accessory.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Select from a list of devices on the network that don’t already have an existing HomeKit association.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " This includes both real and simulated devices that can access the local area network.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Wait for HomeKit to verify that the setup code entered in step 1 matches the device’s code.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Assign a name and room to each service associated with the device.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " HomeKit provides a default name and room for each service, one page per service, that the user can accept or change.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Each item that the user names in step 4 appears in the Home app as an “accessory”. However, in HomeKit, these are ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/homekit/hmservice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instances. They are owned by an ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/homekit/hmaccessory",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance that represents the physical device that you selected in step 2. To maintain a user experience consistent with the Home app, the sample app UI (and the rest of this article) also refers to each ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/homekit/hmservice",
              "isActive": true,
              "overridingTitle": "HMService",
              "overridingTitleInlineContent": [
                {
                  "code": "HMService",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " instance as an accessory.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Show-only-accessories-relevant-to-your-app",
          "level": 3,
          "text": "Show only accessories relevant to your app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You draw the display based on a copy of data from HomeKit captured into an array of Kilgo services:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var kilgoServices = [HMService]()    // These are called \"accessories\" in the UI."
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When the accessory list reloads, either because a new home is set or because the accessory-add flow completes, you populate the above array, filtering out ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/homekit/hmaccessory",
              "isActive": true,
              "overridingTitle": "HMAccessory",
              "overridingTitleInlineContent": [
                {
                  "code": "HMAccessory",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " instances from manufacturers other than Kilgo, and ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/homekit/hmservice",
              "isActive": true,
              "overridingTitle": "HMService",
              "overridingTitleInlineContent": [
                {
                  "code": "HMService",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " instances that aren’t user interactive. Also while gathering the list, you request notifications for changes on any of the corresponding characteristics, which are the individual points of status and control for a given service:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "for accessory in home.accessories.filter({ $0.manufacturer == \"Kilgo Devices, Inc.\" }) {",
            "    accessory.delegate = HomeStore.shared",
            "    ",
            "    for service in accessory.services.filter({ $0.isUserInteractive }) {",
            "        kilgoServices.append(service)",
            "        ",
            "        // Ask for notifications from any characteristics that support them.",
            "        for characteristic in service.characteristics.filter({",
            "            $0.properties.contains(HMCharacteristicPropertySupportsEventNotification)",
            "        }) {",
            "            characteristic.enableNotification(true) { _ in }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "As a result, the display shows only the accessories relevant to this particular app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Use care when crafting your filters. For example, the name “Kilgo Devices, Inc.” might not be unique among all past and future manufacturers, and therefore might not serve as a sufficient predicate in a real app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Tailor-common-interactions-to-specific-accessories",
          "level": 3,
          "text": "Tailor common interactions to specific accessories",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Accessories (like light bulbs) have characteristics (like power state, color temperature, brightness, and so on) that users control or observe. Users typically care about one of these characteristics above the others, because they change or read that characteristic most often. This is the primary characteristic, and you should give users quick access to it. For a light bulb, users most often want to switch it on or off, so the power state is the primary characteristic.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "It’s up to you to define what the primary charactersitc is for the accessories you control. You can do that by creating a computed property on ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/homekit/hmservice",
              "isActive": true,
              "overridingTitle": "HMService",
              "overridingTitleInlineContent": [
                {
                  "code": "HMService",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " in an extension that returns the type of primary characteristic:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var primaryControlCharacteristicType: String? {",
            "    switch kilgoServiceType {",
            "    case .lightBulb: return HMCharacteristicTypePowerState",
            "    case .garageDoor: return HMCharacteristicTypeTargetDoorState",
            "    case .unknown: return nil",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Then use this primary characteristic type to locate and return the characteristic that has that type:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var primaryControlCharacteristic: HMCharacteristic? {",
            "    return characteristics.first { $0.characteristicType == primaryControlCharacteristicType }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For Kilgo Devices, both the light bulb and garage door have binary primary state. The bulb is on or off. The target state of the door is open or closed. This lends itself to an interface where a toggle switch is sufficient to control all primary characteristics. You can implement this as the tap handler on each item in the accessory list collection view. When the user taps the accessory, you read the current characteristic value and then write the opposite:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func tap() {",
            "    if let characteristic = service?.primaryControlCharacteristic,",
            "        let value = characteristic.value as? Bool {",
            "",
            "        // Provide visual feedback that the item was tapped.",
            "        bounce()",
            "        ",
            "        // Write the new value to HomeKit.",
            "        characteristic.writeValue(!value) { error in",
            "            self.redrawState(error: error)",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The write involves network access, so HomeKit calls a completion handler when the write completes. Use this opportunity to update the state of the interface, as shown in the snippet above.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Enable-custom-configuration",
          "level": 3,
          "text": "Enable custom configuration",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the user taps an accessory’s information button, the app reveals details about the accessory. From the detail view, the user can rename the accessory, assign it to a room, remove it from the home, and see device information, like the firmware version. The user can also tap Settings to reveal a list of secondary characteristics for that accessory.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Control the user experience by presenting only relevant characteristic types. The ",
              "type": "text"
            },
            {
              "code": "KilgoService",
              "type": "codeVoice"
            },
            {
              "text": " extension of ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/homekit/hmservice",
              "isActive": true,
              "overridingTitle": "HMService",
              "overridingTitleInlineContent": [
                {
                  "code": "HMService",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " defines a computed property that limits the list of displayable characteristics to those in a curated list:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var displayableCharacteristics: [HMCharacteristic] {",
            "    let characteristicTypes = [HMCharacteristicTypePowerState,",
            "                               HMCharacteristicTypeBrightness,",
            "                               HMCharacteristicTypeHue,",
            "                               HMCharacteristicTypeSaturation,",
            "                               HMCharacteristicTypeTargetDoorState,",
            "                               HMCharacteristicTypeCurrentDoorState,",
            "                               HMCharacteristicTypeObstructionDetected,",
            "                               HMCharacteristicTypeTargetLockMechanismState,",
            "                               HMCharacteristicTypeCurrentLockMechanismState,",
            "                               KilgoCharacteristicTypes.fadeRate.rawValue]",
            "    ",
            "    return characteristics.filter { characteristicTypes.contains($0.characteristicType) }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "These are mostly HomeKit standard types, all of which are applicable to Kilgo devices. There’s also one custom type—fade rate—defined earlier in the same extension:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "enum KilgoCharacteristicTypes: String {",
            "    case fadeRate = \"7E536242-341C-4862-BE90-272CE15BD633\"",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Characteristic types are stored as UUID strings. The value specified in the code for fade rate matches the value found in the accessory simulator, which you can inspect in HAS. If you also build a real Kilgo device, the value used there would have to match as well.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "41e814f00d11/ConfiguringAHomeAutomationDevice.zip": {
      "checksum": "41e814f00d11fa462a83c99b1708c9c2b7352360f5089e55c3b7f3e4489d3923e6fc1b2438e3af463b941ad424e16fde2def79d83d7f8f69832b9a662bae0180",
      "identifier": "41e814f00d11/ConfiguringAHomeAutomationDevice.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/41e814f00d11/ConfiguringAHomeAutomationDevice.zip"
    },
    "GarageControl.png": {
      "alt": "High level diagram of an iOS device controlling a garage door opener.",
      "identifier": "GarageControl.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b016fb7beedcb68ed3df5ff2fcb6cd86/GarageControl.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager": {
      "abstract": [
        {
          "text": "The manager for a collection of one or more of a user’s homes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "role": "symbol",
      "title": "HMHomeManager",
      "type": "topic",
      "url": "/documentation/homekit/hmhomemanager"
    },
    "doc://com.apple.homekit/documentation/HomeKit/testing-your-app-with-the-homekit-accessory-simulator": {
      "abstract": [
        {
          "text": "Install the HomeKit Accessory Simulator to help you debug your HomeKit-enabled app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/testing-your-app-with-the-homekit-accessory-simulator",
      "kind": "article",
      "role": "article",
      "title": "Testing your app with the HomeKit Accessory Simulator",
      "type": "topic",
      "url": "/documentation/homekit/testing-your-app-with-the-homekit-accessory-simulator"
    },
    "https://developer.apple.com/design/human-interface-guidelines/": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/",
      "title": "Human Interface Guidelines",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/"
    },
    "https://developer.apple.com/design/human-interface-guidelines/homekit/overview/introduction/": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/homekit/overview/introduction/",
      "title": "HomeKit",
      "titleInlineContent": [
        {
          "text": "HomeKit",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/homekit/overview/introduction/"
    },
    "https://developer.apple.com/documentation/bundleresources/information_property_list/nshomekitusagedescription": {
      "identifier": "https://developer.apple.com/documentation/bundleresources/information_property_list/nshomekitusagedescription",
      "title": "NSHomeKitUsageDescription",
      "titleInlineContent": [
        {
          "code": "NSHomeKitUsageDescription",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/bundleresources/information_property_list/nshomekitusagedescription"
    },
    "https://developer.apple.com/documentation/homekit/enabling_homekit_in_your_app": {
      "identifier": "https://developer.apple.com/documentation/homekit/enabling_homekit_in_your_app",
      "title": "Enabling HomeKit in Your App",
      "titleInlineContent": [
        {
          "text": "Enabling HomeKit in Your App",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/homekit/enabling_homekit_in_your_app"
    },
    "https://developer.apple.com/documentation/homekit/hmaccessory": {
      "identifier": "https://developer.apple.com/documentation/homekit/hmaccessory",
      "title": "HMAccessory",
      "titleInlineContent": [
        {
          "code": "HMAccessory",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/homekit/hmaccessory"
    },
    "https://developer.apple.com/documentation/homekit/hmhome/1771427-addandsetupaccessories": {
      "identifier": "https://developer.apple.com/documentation/homekit/hmhome/1771427-addandsetupaccessories",
      "title": "addAndSetupAccessories(completionHandler:)",
      "titleInlineContent": [
        {
          "code": "addAndSetupAccessories(completionHandler:)",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/homekit/hmhome/1771427-addandsetupaccessories"
    },
    "https://developer.apple.com/documentation/homekit/hmhomemanager": {
      "identifier": "https://developer.apple.com/documentation/homekit/hmhomemanager",
      "title": "HMHomeManager",
      "titleInlineContent": [
        {
          "code": "HMHomeManager",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/homekit/hmhomemanager"
    },
    "https://developer.apple.com/documentation/homekit/hmhomemanagerdelegate": {
      "identifier": "https://developer.apple.com/documentation/homekit/hmhomemanagerdelegate",
      "title": "HMHomeManagerDelegate",
      "titleInlineContent": [
        {
          "code": "HMHomeManagerDelegate",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/homekit/hmhomemanagerdelegate"
    },
    "https://developer.apple.com/documentation/homekit/hmservice": {
      "identifier": "https://developer.apple.com/documentation/homekit/hmservice",
      "title": "HMService",
      "titleInlineContent": [
        {
          "code": "HMService",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/homekit/hmservice"
    },
    "https://developer.apple.com/documentation/homekit/testing_your_app_with_the_homekit_accessory_simulator": {
      "identifier": "https://developer.apple.com/documentation/homekit/testing_your_app_with_the_homekit_accessory_simulator",
      "title": "Testing Your App with the HomeKit Accessory Simulator",
      "titleInlineContent": [
        {
          "text": "Testing Your App with the HomeKit Accessory Simulator",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/homekit/testing_your_app_with_the_homekit_accessory_simulator"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "41e814f00d11/ConfiguringAHomeAutomationDevice.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Home-Manager",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/testing-your-app-with-the-homekit-accessory-simulator",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager"
      ],
      "title": "Home Manager"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Home-Manager",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/testing-your-app-with-the-homekit-accessory-simulator",
                "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager"
              ],
              "title": "Home Manager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/title",
          "value": "HMHomeManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/configuring-a-home-automation-device"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/configuring-a-home-automation-device"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
