{
  "abstract": [
    {
      "text": "A shower head accessory.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeShowerHead"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@HMAccessoryCategoryTypeShowerHead",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HMAccessoryCategoryTypeShowerHead"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMAccessoryCategoryTypeShowerHead"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "HMAccessoryCategoryTypeShowerHead"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeShowerHead"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeFaucet": {
      "abstract": [
        {
          "text": "A faucet accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeFaucet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeFaucet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeFaucet"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeFaucet",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypefaucet"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeShowerHead": {
      "abstract": [
        {
          "text": "A shower head accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeShowerHead"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeShowerHead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeShowerHead"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeShowerHead",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypeshowerhead"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSprinkler": {
      "abstract": [
        {
          "text": "A sprinkler system accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeSprinkler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSprinkler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryCategoryTypeSprinkler"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryCategoryTypeSprinkler",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorycategorytypesprinkler"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Water",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSprinkler",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeFaucet"
      ],
      "title": "Water"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMAccessoryCategoryTypeShowerHead"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeShowerHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Water",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeSprinkler",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryCategoryTypeFaucet"
              ],
              "title": "Water"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HMAccessoryCategoryTypeShowerHead"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeSprinkler/title",
          "value": "HMAccessoryCategoryTypeSprinkler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeSprinkler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeSprinkler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeShowerHead/title",
          "value": "HMAccessoryCategoryTypeShowerHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeShowerHead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeShowerHead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeFaucet/title",
          "value": "HMAccessoryCategoryTypeFaucet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryCategoryTypeFaucet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryCategoryTypeFaucet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmaccessorycategorytypeshowerhead"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmaccessorycategorytypeshowerhead"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
