{
  "abstract": [
    {
      "text": "A collection of actions that you trigger as a group.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMActionSet"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HMActionSet",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HMActionSet"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMActionSet"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "HMActionSet"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HMActionSet"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Action sets can be executed as a result of evaluating a trigger (instances of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMTrigger",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") or manually with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome/executeActionSet(_:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Actions in an action set are performed in an unspecified order. You create new action sets using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome/addActionSet(withName:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAction": {
      "abstract": [
        {
          "text": "An abstract base class for actions in HomeKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAction"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAction"
        }
      ],
      "role": "symbol",
      "title": "HMAction",
      "type": "topic",
      "url": "/documentation/homekit/hmaction"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSet": {
      "abstract": [
        {
          "text": "A collection of actions that you trigger as a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMActionSet"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMActionSet"
        }
      ],
      "role": "symbol",
      "title": "HMActionSet",
      "type": "topic",
      "url": "/documentation/homekit/hmactionset"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/actionSetType": {
      "abstract": [
        {
          "text": "The type of the action set, such as built-in or user-defined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionSetType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/actionSetType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "actionSetType"
        }
      ],
      "role": "symbol",
      "title": "actionSetType",
      "type": "topic",
      "url": "/documentation/homekit/hmactionset/actionsettype"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/actions": {
      "abstract": [
        {
          "text": "Set of actions in the action set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAction",
          "text": "HMAction"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/actions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "actions"
        }
      ],
      "role": "symbol",
      "title": "actions",
      "type": "topic",
      "url": "/documentation/homekit/hmactionset/actions"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/addAction(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Adds an action to the action set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAction",
          "text": "HMAction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HMErrorBlock",
          "text": "HMErrorBlock"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/addAction(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAction:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "addAction(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/homekit/hmactionset/addaction(_:completionhandler:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/isExecuting": {
      "abstract": [
        {
          "text": "The execution status of the action set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isExecuting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/isExecuting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "executing"
        }
      ],
      "role": "symbol",
      "title": "isExecuting",
      "type": "topic",
      "url": "/documentation/homekit/hmactionset/isexecuting"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/lastExecutionDate": {
      "abstract": [
        {
          "text": "The last execution date of the action set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastExecutionDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/lastExecutionDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastExecutionDate"
        }
      ],
      "role": "symbol",
      "title": "lastExecutionDate",
      "type": "topic",
      "url": "/documentation/homekit/hmactionset/lastexecutiondate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/name": {
      "abstract": [
        {
          "text": "The name of the action set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/homekit/hmactionset/name"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/removeAction(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Removes an action from the action set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAction",
          "text": "HMAction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HMErrorBlock",
          "text": "HMErrorBlock"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/removeAction(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAction:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "removeAction(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/homekit/hmactionset/removeaction(_:completionhandler:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/uniqueIdentifier": {
      "abstract": [
        {
          "text": "The action set’s unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uniqueIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/uniqueIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniqueIdentifier"
        }
      ],
      "role": "symbol",
      "title": "uniqueIdentifier",
      "type": "topic",
      "url": "/documentation/homekit/hmactionset/uniqueidentifier"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/updateName(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Updates the name of the action set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HMErrorBlock",
          "text": "HMErrorBlock"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/updateName(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateName:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "updateName(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/homekit/hmactionset/updatename(_:completionhandler:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicWriteAction": {
      "abstract": [
        {
          "text": "An action in an action set that writes a value to a characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicWriteAction"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicWriteAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicWriteAction"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicWriteAction",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicwriteaction"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger": {
      "abstract": [
        {
          "text": "A trigger to activate an action set based on a set of events and optional conditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMEventTrigger"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMEventTrigger"
        }
      ],
      "role": "symbol",
      "title": "HMEventTrigger",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHome": {
      "abstract": [
        {
          "text": "The primary unit of living space, typically composed of rooms organized into zones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "role": "symbol",
      "title": "HMHome",
      "type": "topic",
      "url": "/documentation/homekit/hmhome"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHome/addActionSet(withName:completionHandler:)": {
      "abstract": [
        {
          "text": "Adds a new action set to the home.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addActionSet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMActionSet",
          "text": "HMActionSet"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome/addActionSet(withName:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addActionSetWithName:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "addActionSet(withName:completionHandler:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhome/addactionset(withname:completionhandler:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHome/executeActionSet(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Executes all the actions in a specified action set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "executeActionSet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMActionSet",
          "text": "HMActionSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome/executeActionSet(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "executeActionSet:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "executeActionSet(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/homekit/hmhome/executeactionset(_:completionhandler:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMTimerTrigger": {
      "abstract": [
        {
          "text": "A trigger to activate an action set based on a periodic timer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMTimerTrigger"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMTimerTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMTimerTrigger"
        }
      ],
      "role": "symbol",
      "title": "HMTimerTrigger",
      "type": "topic",
      "url": "/documentation/homekit/hmtimertrigger"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMTrigger": {
      "abstract": [
        {
          "text": "An abstract base class for triggering actions based on a set of conditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMTrigger"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMTrigger"
        }
      ],
      "role": "symbol",
      "title": "HMTrigger",
      "type": "topic",
      "url": "/documentation/homekit/hmtrigger"
    },
    "doc://com.apple.homekit/documentation/HomeKit/action-set-types": {
      "abstract": [
        {
          "text": "The types of action sets that you can define.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/action-set-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Action Set Types",
      "type": "topic",
      "url": "/documentation/homekit/action-set-types"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Action-Sets",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMTimerTrigger",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger"
      ],
      "title": "Action Sets"
    }
  ],
  "topicSections": [
    {
      "anchor": "Identifiying-an-action-set",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/uniqueIdentifier",
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/name",
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/updateName(_:completionHandler:)"
      ],
      "title": "Identifiying an action set"
    },
    {
      "anchor": "Specifying-a-type",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/actionSetType",
        "doc://com.apple.homekit/documentation/HomeKit/action-set-types"
      ],
      "title": "Specifying a type"
    },
    {
      "anchor": "Defining-the-associated-actions",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/actions",
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/addAction(_:completionHandler:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/removeAction(_:completionHandler:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicWriteAction",
        "doc://com.apple.homekit/documentation/HomeKit/HMAction"
      ],
      "title": "Defining the associated actions"
    },
    {
      "anchor": "Keeping-track-of-execution",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/isExecuting",
        "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/lastExecutionDate"
      ],
      "title": "Keeping track of execution"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMActionSet"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMActionSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMActionSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Identifiying-an-action-set",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/uniqueIdentifier",
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/name",
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/updateName(_:completionHandler:)"
              ],
              "title": "Identifiying an action set"
            },
            {
              "anchor": "Specifying-a-type",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/actionSetType",
                "doc://com.apple.homekit/documentation/HomeKit/action-set-types"
              ],
              "title": "Specifying a type"
            },
            {
              "anchor": "Defining-the-associated-actions",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/actions",
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/addAction(_:completionHandler:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/removeAction(_:completionHandler:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicWriteAction",
                "doc://com.apple.homekit/documentation/HomeKit/HMAction"
              ],
              "title": "Defining the associated actions"
            },
            {
              "anchor": "Keeping-track-of-execution",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/isExecuting",
                "doc://com.apple.homekit/documentation/HomeKit/HMActionSet/lastExecutionDate"
              ],
              "title": "Keeping track of execution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Action-Sets",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMTimerTrigger",
                "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger"
              ],
              "title": "Action Sets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HMActionSet"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1removeAction(_:completionHandler:)/title",
          "value": "removeAction:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1removeAction(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAction:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger/title",
          "value": "HMTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome~1executeActionSet(_:completionHandler:)/title",
          "value": "executeActionSet:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome~1executeActionSet(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "executeActionSet:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger/title",
          "value": "HMEventTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1actions/title",
          "value": "actions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1actions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1lastExecutionDate/title",
          "value": "lastExecutionDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1lastExecutionDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastExecutionDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1actionSetType/title",
          "value": "actionSetType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1actionSetType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "actionSetType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAction/title",
          "value": "HMAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1uniqueIdentifier/title",
          "value": "uniqueIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1uniqueIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uniqueIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicWriteAction/title",
          "value": "HMCharacteristicWriteAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicWriteAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicWriteAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicWriteAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicWriteAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1isExecuting/title",
          "value": "executing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1isExecuting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "executing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1addAction(_:completionHandler:)/title",
          "value": "addAction:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1addAction(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAction:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1updateName(_:completionHandler:)/title",
          "value": "updateName:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet~1updateName(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateName:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/title",
          "value": "HMHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet/title",
          "value": "HMActionSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMActionSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMActionSet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMActionSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTimerTrigger/title",
          "value": "HMTimerTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTimerTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMTimerTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTimerTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMTimerTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome~1addActionSet(withName:completionHandler:)/title",
          "value": "addActionSetWithName:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome~1addActionSet(withName:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addActionSetWithName:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmactionset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmactionset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
