{
  "abstract": [
    {
      "text": "A camera profile that interacts with an accessory’s camera.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HMCameraProfile",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HMCameraProfile"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCameraProfile"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "HMCameraProfile"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HMCameraProfile"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each profile control is optional, because an individual camera vendor may not support all of the features defined by the HomeKit camera specifications.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessory/profiles": {
      "abstract": [
        {
          "text": "An array of profiles implemented by the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "profiles"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMAccessoryProfile",
          "text": "HMAccessoryProfile"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessory/profiles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "profiles"
        }
      ],
      "role": "symbol",
      "title": "profiles",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessory/profiles"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryProfile": {
      "abstract": [
        {
          "text": "A profile that certain accessories implement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessoryProfile"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessoryProfile"
        }
      ],
      "role": "symbol",
      "title": "HMAccessoryProfile",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessoryprofile"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioControl": {
      "abstract": [
        {
          "text": "An object that controls a camera’s audio settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCameraAudioControl"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCameraAudioControl"
        }
      ],
      "role": "symbol",
      "title": "HMCameraAudioControl",
      "type": "topic",
      "url": "/documentation/homekit/hmcameraaudiocontrol"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraControl": {
      "abstract": [
        {
          "text": "An abstract class that represents a camera control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCameraControl"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCameraControl"
        }
      ],
      "role": "symbol",
      "title": "HMCameraControl",
      "type": "topic",
      "url": "/documentation/homekit/hmcameracontrol"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile": {
      "abstract": [
        {
          "text": "A camera profile that interacts with an accessory’s camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCameraProfile"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCameraProfile"
        }
      ],
      "role": "symbol",
      "title": "HMCameraProfile",
      "type": "topic",
      "url": "/documentation/homekit/hmcameraprofile"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/microphoneControl": {
      "abstract": [
        {
          "text": "Controls the microphone settings on the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "microphoneControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMCameraAudioControl",
          "text": "HMCameraAudioControl"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/microphoneControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "microphoneControl"
        }
      ],
      "role": "symbol",
      "title": "microphoneControl",
      "type": "topic",
      "url": "/documentation/homekit/hmcameraprofile/microphonecontrol"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/settingsControl": {
      "abstract": [
        {
          "text": "Controls the settings on the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "settingsControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMCameraSettingsControl",
          "text": "HMCameraSettingsControl"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/settingsControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "settingsControl"
        }
      ],
      "role": "symbol",
      "title": "settingsControl",
      "type": "topic",
      "url": "/documentation/homekit/hmcameraprofile/settingscontrol"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/snapshotControl": {
      "abstract": [
        {
          "text": "Controls the camera’s snapshot function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "snapshotControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMCameraSnapshotControl",
          "text": "HMCameraSnapshotControl"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/snapshotControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "snapshotControl"
        }
      ],
      "role": "symbol",
      "title": "snapshotControl",
      "type": "topic",
      "url": "/documentation/homekit/hmcameraprofile/snapshotcontrol"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/speakerControl": {
      "abstract": [
        {
          "text": "Controls the speaker settings on the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speakerControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMCameraAudioControl",
          "text": "HMCameraAudioControl"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/speakerControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "speakerControl"
        }
      ],
      "role": "symbol",
      "title": "speakerControl",
      "type": "topic",
      "url": "/documentation/homekit/hmcameraprofile/speakercontrol"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/streamControl": {
      "abstract": [
        {
          "text": "Controls the camera stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streamControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMCameraStreamControl",
          "text": "HMCameraStreamControl"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/streamControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "streamControl"
        }
      ],
      "role": "symbol",
      "title": "streamControl",
      "type": "topic",
      "url": "/documentation/homekit/hmcameraprofile/streamcontrol"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraSettingsControl": {
      "abstract": [
        {
          "text": "An object that represents the ability to control a camera’s settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCameraSettingsControl"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraSettingsControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCameraSettingsControl"
        }
      ],
      "role": "symbol",
      "title": "HMCameraSettingsControl",
      "type": "topic",
      "url": "/documentation/homekit/hmcamerasettingscontrol"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControl": {
      "abstract": [
        {
          "text": "An object that can take an image snapshot from a camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCameraSnapshotControl"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCameraSnapshotControl"
        }
      ],
      "role": "symbol",
      "title": "HMCameraSnapshotControl",
      "type": "topic",
      "url": "/documentation/homekit/hmcamerasnapshotcontrol"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCameraStreamControl": {
      "abstract": [
        {
          "text": "An object that can start and stop the camera stream and contains the view into which the stream is rendered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCameraStreamControl"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCameraStreamControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCameraStreamControl"
        }
      ],
      "role": "symbol",
      "title": "HMCameraStreamControl",
      "type": "topic",
      "url": "/documentation/homekit/hmcamerastreamcontrol"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMNetworkConfigurationProfile": {
      "abstract": [
        {
          "text": "A profile that provides information about network protection for an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMNetworkConfigurationProfile"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMNetworkConfigurationProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMNetworkConfigurationProfile"
        }
      ],
      "role": "symbol",
      "title": "HMNetworkConfigurationProfile",
      "type": "topic",
      "url": "/documentation/homekit/hmnetworkconfigurationprofile"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryProfile"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-accessory-profiles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessory/profiles",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryProfile",
        "doc://com.apple.homekit/documentation/HomeKit/HMNetworkConfigurationProfile"
      ],
      "title": "Managing accessory profiles"
    }
  ],
  "topicSections": [
    {
      "anchor": "Controlling-camera-settings",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/settingsControl",
        "doc://com.apple.homekit/documentation/HomeKit/HMCameraSettingsControl",
        "doc://com.apple.homekit/documentation/HomeKit/HMCameraControl"
      ],
      "title": "Controlling camera settings"
    },
    {
      "anchor": "Playing-audio",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/microphoneControl",
        "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/speakerControl",
        "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioControl"
      ],
      "title": "Playing audio"
    },
    {
      "anchor": "Streaming",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/streamControl",
        "doc://com.apple.homekit/documentation/HomeKit/HMCameraStreamControl"
      ],
      "title": "Streaming"
    },
    {
      "anchor": "Capturing-snapshots",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/snapshotControl",
        "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControl"
      ],
      "title": "Capturing snapshots"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCameraProfile"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Controlling-camera-settings",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/settingsControl",
                "doc://com.apple.homekit/documentation/HomeKit/HMCameraSettingsControl",
                "doc://com.apple.homekit/documentation/HomeKit/HMCameraControl"
              ],
              "title": "Controlling camera settings"
            },
            {
              "anchor": "Playing-audio",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/microphoneControl",
                "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/speakerControl",
                "doc://com.apple.homekit/documentation/HomeKit/HMCameraAudioControl"
              ],
              "title": "Playing audio"
            },
            {
              "anchor": "Streaming",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/streamControl",
                "doc://com.apple.homekit/documentation/HomeKit/HMCameraStreamControl"
              ],
              "title": "Streaming"
            },
            {
              "anchor": "Capturing-snapshots",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCameraProfile/snapshotControl",
                "doc://com.apple.homekit/documentation/HomeKit/HMCameraSnapshotControl"
              ],
              "title": "Capturing snapshots"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryProfile"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-accessory-profiles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessory/profiles",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryProfile",
                "doc://com.apple.homekit/documentation/HomeKit/HMNetworkConfigurationProfile"
              ],
              "title": "Managing accessory profiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HMCameraProfile"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessoryProfile",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)HMAccessoryProfile",
                    "text": "HMAccessoryProfile"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraProfile~1speakerControl/title",
          "value": "speakerControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraProfile~1speakerControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "speakerControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryProfile/title",
          "value": "HMAccessoryProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessoryProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessoryProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraAudioControl/title",
          "value": "HMCameraAudioControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraAudioControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraAudioControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraAudioControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraAudioControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory~1profiles/title",
          "value": "profiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory~1profiles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "profiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraStreamControl/title",
          "value": "HMCameraStreamControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraStreamControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraStreamControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraStreamControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraStreamControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMNetworkConfigurationProfile/title",
          "value": "HMNetworkConfigurationProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMNetworkConfigurationProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMNetworkConfigurationProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMNetworkConfigurationProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMNetworkConfigurationProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraProfile~1microphoneControl/title",
          "value": "microphoneControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraProfile~1microphoneControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "microphoneControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSettingsControl/title",
          "value": "HMCameraSettingsControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSettingsControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraSettingsControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSettingsControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraSettingsControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraControl/title",
          "value": "HMCameraControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraProfile~1streamControl/title",
          "value": "streamControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraProfile~1streamControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "streamControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraProfile/title",
          "value": "HMCameraProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSnapshotControl/title",
          "value": "HMCameraSnapshotControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSnapshotControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraSnapshotControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraSnapshotControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCameraSnapshotControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraProfile~1snapshotControl/title",
          "value": "snapshotControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraProfile~1snapshotControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "snapshotControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraProfile~1settingsControl/title",
          "value": "settingsControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCameraProfile~1settingsControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "settingsControl"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcameraprofile"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcameraprofile"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
