{
  "abstract": [
    {
      "text": "The target position of a door, window, awning, or window covering.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetPosition"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@HMCharacteristicTypeTargetPosition",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HMCharacteristicTypeTargetPosition"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCharacteristicTypeTargetPosition"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "HMCharacteristicTypeTargetPosition"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeTargetPosition"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The corresponding value is an integer percentage. A value of ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " indicates a door or window should be fully closed, or that awnings or shades should permit the least possible light. A value of ",
              "type": "text"
            },
            {
              "code": "100",
              "type": "codeVoice"
            },
            {
              "text": " indicates the opposite.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentDoorState": {
      "abstract": [
        {
          "text": "The current door state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCurrentDoorState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentDoorState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCurrentDoorState"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeCurrentDoorState",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypecurrentdoorstate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentPosition": {
      "abstract": [
        {
          "text": "The current position of a door, window, awning, or window covering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCurrentPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCurrentPosition"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeCurrentPosition",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypecurrentposition"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentSlatState": {
      "abstract": [
        {
          "text": "The current state of slats on an accessory like a window or a fan.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCurrentSlatState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentSlatState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCurrentSlatState"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeCurrentSlatState",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypecurrentslatstate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeHoldPosition": {
      "abstract": [
        {
          "text": "A control for holding the position of an accessory like a door or window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeHoldPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeHoldPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeHoldPosition"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeHoldPosition",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeholdposition"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypePositionState": {
      "abstract": [
        {
          "text": "The position of an accessory like a door, window, awning, or window covering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypePositionState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypePositionState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypePositionState"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypePositionState",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypepositionstate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSlatType": {
      "abstract": [
        {
          "text": "The type of slat on an accessory like a window or a fan.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSlatType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSlatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSlatType"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeSlatType",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeslattype"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusJammed": {
      "abstract": [
        {
          "text": "An indicator of whether an accessory is jammed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeStatusJammed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusJammed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeStatusJammed"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeStatusJammed",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypestatusjammed"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetDoorState": {
      "abstract": [
        {
          "text": "The target door state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeTargetDoorState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetDoorState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeTargetDoorState"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeTargetDoorState",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypetargetdoorstate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetPosition": {
      "abstract": [
        {
          "text": "The target position of a door, window, awning, or window covering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeTargetPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeTargetPosition"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeTargetPosition",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypetargetposition"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Doors-and-windows",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentDoorState",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetDoorState",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentPosition",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypePositionState",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusJammed",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeHoldPosition",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSlatType",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentSlatState"
      ],
      "title": "Doors and windows"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCharacteristicTypeTargetPosition"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeTargetPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Doors-and-windows",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentDoorState",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetDoorState",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentPosition",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypePositionState",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusJammed",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeHoldPosition",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSlatType",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentSlatState"
              ],
              "title": "Doors and windows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HMCharacteristicTypeTargetPosition"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypePositionState/title",
          "value": "HMCharacteristicTypePositionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypePositionState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypePositionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeTargetDoorState/title",
          "value": "HMCharacteristicTypeTargetDoorState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeTargetDoorState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeTargetDoorState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCurrentSlatState/title",
          "value": "HMCharacteristicTypeCurrentSlatState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCurrentSlatState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeCurrentSlatState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCurrentDoorState/title",
          "value": "HMCharacteristicTypeCurrentDoorState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCurrentDoorState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeCurrentDoorState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeStatusJammed/title",
          "value": "HMCharacteristicTypeStatusJammed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeStatusJammed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeStatusJammed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeTargetPosition/title",
          "value": "HMCharacteristicTypeTargetPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeTargetPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeTargetPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeHoldPosition/title",
          "value": "HMCharacteristicTypeHoldPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeHoldPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeHoldPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCurrentPosition/title",
          "value": "HMCharacteristicTypeCurrentPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCurrentPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeCurrentPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSlatType/title",
          "value": "HMCharacteristicTypeSlatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSlatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeSlatType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcharacteristictypetargetposition"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcharacteristictypetargetposition"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
