{
  "abstract": [
    {
      "text": "The video stream’s configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSupportedVideoStreamConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@HMCharacteristicTypeSupportedVideoStreamConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HMCharacteristicTypeSupportedVideoStreamConfiguration"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCharacteristicTypeSupportedVideoStreamConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "HMCharacteristicTypeSupportedVideoStreamConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeSupportedVideoStreamConfiguration"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The corresponding value is TLV8-encoded data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAudioFeedback": {
      "abstract": [
        {
          "text": "An indicator of whether audio feedback, like a beep or other external sound mechanism, is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeAudioFeedback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAudioFeedback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeAudioFeedback"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeAudioFeedback",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeaudiofeedback"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeDigitalZoom": {
      "abstract": [
        {
          "text": "The digital zoom of a video Real-time Transport Protocol (RTP) service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeDigitalZoom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeDigitalZoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeDigitalZoom"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeDigitalZoom",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypedigitalzoom"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeImageMirroring": {
      "abstract": [
        {
          "text": "An indicator of whether the image should be flipped about the vertical axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeImageMirroring"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeImageMirroring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeImageMirroring"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeImageMirroring",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeimagemirroring"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeImageRotation": {
      "abstract": [
        {
          "text": "The angle of rotation for an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeImageRotation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeImageRotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeImageRotation"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeImageRotation",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeimagerotation"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeMute": {
      "abstract": [
        {
          "text": "A control for muting audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeMute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeMute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeMute"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeMute",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypemute"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeNightVision": {
      "abstract": [
        {
          "text": "An indicator of whether night vision is enabled on a video Real-time Transport Protocol (RTP) service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeNightVision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeNightVision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeNightVision"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeNightVision",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypenightvision"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeOpticalZoom": {
      "abstract": [
        {
          "text": "The optical zoom setting of the camera sourcing a video Real-time Transport Protocol (RTP) service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeOpticalZoom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeOpticalZoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeOpticalZoom"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeOpticalZoom",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeopticalzoom"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSelectedStreamConfiguration": {
      "abstract": [
        {
          "text": "The selected stream’s configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSelectedStreamConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSelectedStreamConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSelectedStreamConfiguration"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeSelectedStreamConfiguration",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeselectedstreamconfiguration"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSetupStreamEndpoint": {
      "abstract": [
        {
          "text": "The stream’s endpoint configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSetupStreamEndpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSetupStreamEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSetupStreamEndpoint"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeSetupStreamEndpoint",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypesetupstreamendpoint"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStreamingStatus": {
      "abstract": [
        {
          "text": "A description of the status of the Real-time Transport Protocol (RTP) stream management service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeStreamingStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStreamingStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeStreamingStatus"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeStreamingStatus",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypestreamingstatus"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSupportedAudioStreamConfiguration": {
      "abstract": [
        {
          "text": "The audio stream’s configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSupportedAudioStreamConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSupportedAudioStreamConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSupportedAudioStreamConfiguration"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeSupportedAudioStreamConfiguration",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypesupportedaudiostreamconfiguration"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSupportedRTPConfiguration": {
      "abstract": [
        {
          "text": "The supported Real-time Transport Protocol (RTP) configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSupportedRTPConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSupportedRTPConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSupportedRTPConfiguration"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeSupportedRTPConfiguration",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypesupportedrtpconfiguration"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSupportedVideoStreamConfiguration": {
      "abstract": [
        {
          "text": "The video stream’s configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSupportedVideoStreamConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSupportedVideoStreamConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSupportedVideoStreamConfiguration"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeSupportedVideoStreamConfiguration",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypesupportedvideostreamconfiguration"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolume": {
      "abstract": [
        {
          "text": "The input or output volume of an audio device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeVolume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeVolume"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeVolume",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypevolume"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolumeControlType": {
      "abstract": [
        {
          "text": "The volume control capabilities of an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeVolumeControlType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolumeControlType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeVolumeControlType"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeVolumeControlType",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypevolumecontroltype"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolumeSelector": {
      "abstract": [
        {
          "text": "The mechanism to increment or decrement the volume by the default step value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeVolumeSelector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolumeSelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeVolumeSelector"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeVolumeSelector",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypevolumeselector"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-and-video",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSupportedRTPConfiguration",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeDigitalZoom",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeOpticalZoom",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeImageMirroring",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeImageRotation",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeNightVision",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStreamingStatus",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSupportedAudioStreamConfiguration",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSelectedStreamConfiguration",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSetupStreamEndpoint",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAudioFeedback",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolume",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeMute",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolumeSelector",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolumeControlType"
      ],
      "title": "Audio and video"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCharacteristicTypeSupportedVideoStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeSupportedVideoStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-and-video",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSupportedRTPConfiguration",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeDigitalZoom",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeOpticalZoom",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeImageMirroring",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeImageRotation",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeNightVision",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStreamingStatus",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSupportedAudioStreamConfiguration",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSelectedStreamConfiguration",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSetupStreamEndpoint",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAudioFeedback",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolume",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeMute",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolumeSelector",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolumeControlType"
              ],
              "title": "Audio and video"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HMCharacteristicTypeSupportedVideoStreamConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSupportedVideoStreamConfiguration/title",
          "value": "HMCharacteristicTypeSupportedVideoStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSupportedVideoStreamConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeSupportedVideoStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeImageRotation/title",
          "value": "HMCharacteristicTypeImageRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeImageRotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeImageRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeNightVision/title",
          "value": "HMCharacteristicTypeNightVision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeNightVision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeNightVision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeOpticalZoom/title",
          "value": "HMCharacteristicTypeOpticalZoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeOpticalZoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeOpticalZoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSupportedAudioStreamConfiguration/title",
          "value": "HMCharacteristicTypeSupportedAudioStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSupportedAudioStreamConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeSupportedAudioStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSetupStreamEndpoint/title",
          "value": "HMCharacteristicTypeSetupStreamEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSetupStreamEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeSetupStreamEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeAudioFeedback/title",
          "value": "HMCharacteristicTypeAudioFeedback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeAudioFeedback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeAudioFeedback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeMute/title",
          "value": "HMCharacteristicTypeMute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeMute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeMute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeVolumeControlType/title",
          "value": "HMCharacteristicTypeVolumeControlType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeVolumeControlType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeVolumeControlType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSelectedStreamConfiguration/title",
          "value": "HMCharacteristicTypeSelectedStreamConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSelectedStreamConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeSelectedStreamConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeImageMirroring/title",
          "value": "HMCharacteristicTypeImageMirroring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeImageMirroring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeImageMirroring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeVolume/title",
          "value": "HMCharacteristicTypeVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeVolumeSelector/title",
          "value": "HMCharacteristicTypeVolumeSelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeVolumeSelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeVolumeSelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeStreamingStatus/title",
          "value": "HMCharacteristicTypeStreamingStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeStreamingStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeStreamingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSupportedRTPConfiguration/title",
          "value": "HMCharacteristicTypeSupportedRTPConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSupportedRTPConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeSupportedRTPConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeDigitalZoom/title",
          "value": "HMCharacteristicTypeDigitalZoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeDigitalZoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeDigitalZoom"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcharacteristictypesupportedvideostreamconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcharacteristictypesupportedvideostreamconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
