{
  "abstract": [
    {
      "text": "The measured carbon monoxide level.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonMonoxideLevel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@HMCharacteristicTypeCarbonMonoxideLevel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HMCharacteristicTypeCarbonMonoxideLevel"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCharacteristicTypeCarbonMonoxideLevel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "HMCharacteristicTypeCarbonMonoxideLevel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeCarbonMonoxideLevel"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The corresponding value is a floating point number in units of parts per million.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAirParticulateDensity": {
      "abstract": [
        {
          "text": "The density of air-particulate matter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeAirParticulateDensity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAirParticulateDensity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeAirParticulateDensity"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeAirParticulateDensity",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeairparticulatedensity"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAirParticulateSize": {
      "abstract": [
        {
          "text": "The size of the air-particulate matter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeAirParticulateSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAirParticulateSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeAirParticulateSize"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeAirParticulateSize",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeairparticulatesize"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAirQuality": {
      "abstract": [
        {
          "text": "The air quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeAirQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAirQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeAirQuality"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeAirQuality",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeairquality"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonDioxideDetected": {
      "abstract": [
        {
          "text": "An indicator of abnormally high levels of carbon dioxide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCarbonDioxideDetected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonDioxideDetected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCarbonDioxideDetected"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeCarbonDioxideDetected",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypecarbondioxidedetected"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonDioxideLevel": {
      "abstract": [
        {
          "text": "The measured carbon dioxide level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCarbonDioxideLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonDioxideLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCarbonDioxideLevel"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeCarbonDioxideLevel",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypecarbondioxidelevel"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonDioxidePeakLevel": {
      "abstract": [
        {
          "text": "The highest recorded level of carbon dioxide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCarbonDioxidePeakLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonDioxidePeakLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCarbonDioxidePeakLevel"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeCarbonDioxidePeakLevel",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypecarbondioxidepeaklevel"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonMonoxideDetected": {
      "abstract": [
        {
          "text": "An indicator of abnormally high levels of carbon monoxide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCarbonMonoxideDetected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonMonoxideDetected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCarbonMonoxideDetected"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeCarbonMonoxideDetected",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypecarbonmonoxidedetected"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonMonoxideLevel": {
      "abstract": [
        {
          "text": "The measured carbon monoxide level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCarbonMonoxideLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonMonoxideLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCarbonMonoxideLevel"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeCarbonMonoxideLevel",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypecarbonmonoxidelevel"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonMonoxidePeakLevel": {
      "abstract": [
        {
          "text": "The highest recorded level of carbon monoxide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCarbonMonoxidePeakLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonMonoxidePeakLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCarbonMonoxidePeakLevel"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeCarbonMonoxidePeakLevel",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypecarbonmonoxidepeaklevel"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeNitrogenDioxideDensity": {
      "abstract": [
        {
          "text": "The measured density of nitrogen dioxide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeNitrogenDioxideDensity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeNitrogenDioxideDensity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeNitrogenDioxideDensity"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeNitrogenDioxideDensity",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypenitrogendioxidedensity"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeOzoneDensity": {
      "abstract": [
        {
          "text": "The measured density of ozone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeOzoneDensity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeOzoneDensity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeOzoneDensity"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeOzoneDensity",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeozonedensity"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypePM10Density": {
      "abstract": [
        {
          "text": "The measured density of air-particulate matter of size 10 micrograms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypePM10Density"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypePM10Density",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypePM10Density"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypePM10Density",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypepm10density"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypePM2_5Density": {
      "abstract": [
        {
          "text": "The measured density of air-particulate matter of size 2.5 micrograms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypePM2_5Density"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypePM2_5Density",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypePM2_5Density"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypePM2_5Density",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypepm2_5density"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSmokeDetected": {
      "abstract": [
        {
          "text": "A smoke detection indicator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSmokeDetected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSmokeDetected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSmokeDetected"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeSmokeDetected",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypesmokedetected"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSulphurDioxideDensity": {
      "abstract": [
        {
          "text": "The measured density of sulphur dioxide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSulphurDioxideDensity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSulphurDioxideDensity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSulphurDioxideDensity"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeSulphurDioxideDensity",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypesulphurdioxidedensity"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolatileOrganicCompoundDensity": {
      "abstract": [
        {
          "text": "The measured density of volatile organic compounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeVolatileOrganicCompoundDensity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolatileOrganicCompoundDensity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeVolatileOrganicCompoundDensity"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeVolatileOrganicCompoundDensity",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypevolatileorganiccompounddensity"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Air-quality-and-smoke-detection",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAirQuality",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAirParticulateDensity",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAirParticulateSize",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSmokeDetected",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonDioxideDetected",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonDioxideLevel",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonDioxidePeakLevel",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonMonoxideDetected",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonMonoxidePeakLevel",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeNitrogenDioxideDensity",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeOzoneDensity",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypePM10Density",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypePM2_5Density",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSulphurDioxideDensity",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolatileOrganicCompoundDensity"
      ],
      "title": "Air quality and smoke detection"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCharacteristicTypeCarbonMonoxideLevel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeCarbonMonoxideLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Air-quality-and-smoke-detection",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAirQuality",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAirParticulateDensity",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAirParticulateSize",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSmokeDetected",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonDioxideDetected",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonDioxideLevel",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonDioxidePeakLevel",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonMonoxideDetected",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCarbonMonoxidePeakLevel",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeNitrogenDioxideDensity",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeOzoneDensity",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypePM10Density",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypePM2_5Density",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSulphurDioxideDensity",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVolatileOrganicCompoundDensity"
              ],
              "title": "Air quality and smoke detection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HMCharacteristicTypeCarbonMonoxideLevel"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeAirParticulateSize/title",
          "value": "HMCharacteristicTypeAirParticulateSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeAirParticulateSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeAirParticulateSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeVolatileOrganicCompoundDensity/title",
          "value": "HMCharacteristicTypeVolatileOrganicCompoundDensity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeVolatileOrganicCompoundDensity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeVolatileOrganicCompoundDensity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypePM2_5Density/title",
          "value": "HMCharacteristicTypePM2_5Density"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypePM2_5Density/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypePM2_5Density"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeNitrogenDioxideDensity/title",
          "value": "HMCharacteristicTypeNitrogenDioxideDensity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeNitrogenDioxideDensity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeNitrogenDioxideDensity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCarbonDioxideDetected/title",
          "value": "HMCharacteristicTypeCarbonDioxideDetected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCarbonDioxideDetected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeCarbonDioxideDetected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCarbonMonoxideLevel/title",
          "value": "HMCharacteristicTypeCarbonMonoxideLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCarbonMonoxideLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeCarbonMonoxideLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCarbonMonoxideDetected/title",
          "value": "HMCharacteristicTypeCarbonMonoxideDetected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCarbonMonoxideDetected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeCarbonMonoxideDetected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeAirParticulateDensity/title",
          "value": "HMCharacteristicTypeAirParticulateDensity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeAirParticulateDensity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeAirParticulateDensity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeAirQuality/title",
          "value": "HMCharacteristicTypeAirQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeAirQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeAirQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCarbonDioxidePeakLevel/title",
          "value": "HMCharacteristicTypeCarbonDioxidePeakLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCarbonDioxidePeakLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeCarbonDioxidePeakLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCarbonMonoxidePeakLevel/title",
          "value": "HMCharacteristicTypeCarbonMonoxidePeakLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCarbonMonoxidePeakLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeCarbonMonoxidePeakLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSmokeDetected/title",
          "value": "HMCharacteristicTypeSmokeDetected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSmokeDetected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeSmokeDetected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypePM10Density/title",
          "value": "HMCharacteristicTypePM10Density"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypePM10Density/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypePM10Density"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeOzoneDensity/title",
          "value": "HMCharacteristicTypeOzoneDensity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeOzoneDensity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeOzoneDensity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCarbonDioxideLevel/title",
          "value": "HMCharacteristicTypeCarbonDioxideLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCarbonDioxideLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeCarbonDioxideLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSulphurDioxideDensity/title",
          "value": "HMCharacteristicTypeSulphurDioxideDensity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSulphurDioxideDensity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeSulphurDioxideDensity"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcharacteristictypecarbonmonoxidelevel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcharacteristictypecarbonmonoxidelevel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
