{
  "abstract": [
    {
      "text": "The lock’s physical control state.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLockPhysicalControls"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@HMCharacteristicTypeLockPhysicalControls",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HMCharacteristicTypeLockPhysicalControls"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCharacteristicTypeLockPhysicalControls"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.1.1",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "HMCharacteristicTypeLockPhysicalControls"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeLockPhysicalControls"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The corresponding value is one of the constants in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockPhysicalControlsState",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " enumeration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentLockMechanismState": {
      "abstract": [
        {
          "text": "The current state of the locking mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCurrentLockMechanismState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentLockMechanismState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCurrentLockMechanismState"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeCurrentLockMechanismState",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypecurrentlockmechanismstate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLockManagementAutoSecureTimeout": {
      "abstract": [
        {
          "text": "The automatic timeout for a lockable accessory that supports automatic lockout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeLockManagementAutoSecureTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLockManagementAutoSecureTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeLockManagementAutoSecureTimeout"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeLockManagementAutoSecureTimeout",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypelockmanagementautosecuretimeout"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLockManagementControlPoint": {
      "abstract": [
        {
          "text": "A control that accepts vendor-specific actions for lock management.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeLockManagementControlPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLockManagementControlPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeLockManagementControlPoint"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeLockManagementControlPoint",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypelockmanagementcontrolpoint"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLockMechanismLastKnownAction": {
      "abstract": [
        {
          "text": "The last known action of the locking mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeLockMechanismLastKnownAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLockMechanismLastKnownAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeLockMechanismLastKnownAction"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeLockMechanismLastKnownAction",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypelockmechanismlastknownaction"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLockPhysicalControls": {
      "abstract": [
        {
          "text": "The lock’s physical control state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeLockPhysicalControls"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLockPhysicalControls",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeLockPhysicalControls"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeLockPhysicalControls",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypelockphysicalcontrols"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeMotionDetected": {
      "abstract": [
        {
          "text": "An indicator of whether the accessory has detected motion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeMotionDetected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeMotionDetected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeMotionDetected"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeMotionDetected",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypemotiondetected"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeRemoteKey": {
      "abstract": [
        {
          "text": "The accessory remote control key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeRemoteKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeRemoteKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeRemoteKey"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeRemoteKey",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictyperemotekey"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetLockMechanismState": {
      "abstract": [
        {
          "text": "The target state for the locking mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeTargetLockMechanismState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetLockMechanismState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeTargetLockMechanismState"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeTargetLockMechanismState",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypetargetlockmechanismstate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockPhysicalControlsState": {
      "abstract": [
        {
          "text": "Possible values for the lock physical control state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLockPhysicalControlsState"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockPhysicalControlsState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLockPhysicalControlsState"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueLockPhysicalControlsState",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluelockphysicalcontrolsstate"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Locks-and-openers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLockManagementAutoSecureTimeout",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLockManagementControlPoint",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLockMechanismLastKnownAction",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeMotionDetected",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentLockMechanismState",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetLockMechanismState",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeRemoteKey"
      ],
      "title": "Locks and openers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Values",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockPhysicalControlsState"
      ],
      "title": "Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.1.1",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCharacteristicTypeLockPhysicalControls"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeLockPhysicalControls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Values",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLockPhysicalControlsState"
              ],
              "title": "Values"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Locks-and-openers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLockManagementAutoSecureTimeout",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLockManagementControlPoint",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLockMechanismLastKnownAction",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeMotionDetected",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentLockMechanismState",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetLockMechanismState",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeRemoteKey"
              ],
              "title": "Locks and openers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HMCharacteristicTypeLockPhysicalControls"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCurrentLockMechanismState/title",
          "value": "HMCharacteristicTypeCurrentLockMechanismState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCurrentLockMechanismState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeCurrentLockMechanismState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeRemoteKey/title",
          "value": "HMCharacteristicTypeRemoteKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeRemoteKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeRemoteKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeTargetLockMechanismState/title",
          "value": "HMCharacteristicTypeTargetLockMechanismState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeTargetLockMechanismState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeTargetLockMechanismState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeLockMechanismLastKnownAction/title",
          "value": "HMCharacteristicTypeLockMechanismLastKnownAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeLockMechanismLastKnownAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeLockMechanismLastKnownAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockPhysicalControlsState/title",
          "value": "HMCharacteristicValueLockPhysicalControlsState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockPhysicalControlsState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockPhysicalControlsState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLockPhysicalControlsState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLockPhysicalControlsState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeLockPhysicalControls/title",
          "value": "HMCharacteristicTypeLockPhysicalControls"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeLockPhysicalControls/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeLockPhysicalControls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeLockManagementControlPoint/title",
          "value": "HMCharacteristicTypeLockManagementControlPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeLockManagementControlPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeLockManagementControlPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeLockManagementAutoSecureTimeout/title",
          "value": "HMCharacteristicTypeLockManagementAutoSecureTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeLockManagementAutoSecureTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeLockManagementAutoSecureTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeMotionDetected/title",
          "value": "HMCharacteristicTypeMotionDetected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeMotionDetected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeMotionDetected"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcharacteristictypelockphysicalcontrols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcharacteristictypelockphysicalcontrols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
