{
  "abstract": [
    {
      "text": "The naming schema used to label the services on an accessory with multiple services of the same type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLabelNamespace"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@HMCharacteristicTypeLabelNamespace",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HMCharacteristicTypeLabelNamespace"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCharacteristicTypeLabelNamespace"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "HMCharacteristicTypeLabelNamespace"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeLabelNamespace"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The corresponding value is one of the constants in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLabelNamespace",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " enumeration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeActiveIdentifier": {
      "abstract": [
        {
          "text": "An index that maps to the current active Input Source service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeActiveIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeActiveIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeActiveIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeActiveIdentifier",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeactiveidentifier"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAdminOnlyAccess": {
      "abstract": [
        {
          "text": "An indicator of whether the accessory accepts only administrator access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeAdminOnlyAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAdminOnlyAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeAdminOnlyAccess"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeAdminOnlyAccess",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeadminonlyaccess"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeConfiguredName": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "UTF‑8",
          "type": "codeVoice"
        },
        {
          "text": " encoded user visible name on an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeConfiguredName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeConfiguredName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeConfiguredName"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeConfiguredName",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeconfiguredname"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeHardwareVersion": {
      "abstract": [
        {
          "text": "The hardware version of the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeHardwareVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeHardwareVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeHardwareVersion"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeHardwareVersion",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypehardwareversion"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeIdentifier": {
      "abstract": [
        {
          "text": "The identifier for an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeIdentifier",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeidentifier"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeIdentify": {
      "abstract": [
        {
          "text": "A control you can use to ask the accessory to identify itself.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeIdentify"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeIdentify",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeIdentify"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeIdentify",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeidentify"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeInputDeviceType": {
      "abstract": [
        {
          "text": "The accessory input device type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeInputDeviceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeInputDeviceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeInputDeviceType"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeInputDeviceType",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeinputdevicetype"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeInputSourceType": {
      "abstract": [
        {
          "text": "The accessory input source type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeInputSourceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeInputSourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeInputSourceType"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeInputSourceType",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeinputsourcetype"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLabelIndex": {
      "abstract": [
        {
          "text": "The index of the label for the service on an accessory with multiple instances of the same service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeLabelIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLabelIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeLabelIndex"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeLabelIndex",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypelabelindex"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLabelNamespace": {
      "abstract": [
        {
          "text": "The naming schema used to label the services on an accessory with multiple services of the same type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeLabelNamespace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLabelNamespace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeLabelNamespace"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeLabelNamespace",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypelabelnamespace"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLogs": {
      "abstract": [
        {
          "text": "Log data for the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeLogs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLogs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeLogs"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeLogs",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypelogs"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeName": {
      "abstract": [
        {
          "text": "The name of the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeName"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeName",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypename"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSoftwareVersion": {
      "abstract": [
        {
          "text": "The software version of the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSoftwareVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSoftwareVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSoftwareVersion"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeSoftwareVersion",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypesoftwareversion"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVersion": {
      "abstract": [
        {
          "text": "The version of the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeVersion"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeVersion",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeversion"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLabelNamespace": {
      "abstract": [
        {
          "text": "Possible values for the label namespace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLabelNamespace"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLabelNamespace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueLabelNamespace"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueLabelNamespace",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluelabelnamespace"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessory-identification",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeName",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeIdentify",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVersion",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLogs",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAdminOnlyAccess",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeHardwareVersion",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSoftwareVersion",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLabelIndex",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeActiveIdentifier",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeIdentifier",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeInputDeviceType",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeInputSourceType",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeConfiguredName"
      ],
      "title": "Accessory identification"
    }
  ],
  "topicSections": [
    {
      "anchor": "Values",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLabelNamespace"
      ],
      "title": "Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCharacteristicTypeLabelNamespace"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeLabelNamespace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Values",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueLabelNamespace"
              ],
              "title": "Values"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessory-identification",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeName",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeIdentify",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeVersion",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLogs",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeAdminOnlyAccess",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeHardwareVersion",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSoftwareVersion",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeLabelIndex",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeActiveIdentifier",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeIdentifier",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeInputDeviceType",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeInputSourceType",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeConfiguredName"
              ],
              "title": "Accessory identification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HMCharacteristicTypeLabelNamespace"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeIdentify/title",
          "value": "HMCharacteristicTypeIdentify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeIdentify/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeIdentify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeLogs/title",
          "value": "HMCharacteristicTypeLogs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeLogs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeLogs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSoftwareVersion/title",
          "value": "HMCharacteristicTypeSoftwareVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSoftwareVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeSoftwareVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeConfiguredName/title",
          "value": "HMCharacteristicTypeConfiguredName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeConfiguredName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeConfiguredName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeAdminOnlyAccess/title",
          "value": "HMCharacteristicTypeAdminOnlyAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeAdminOnlyAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeAdminOnlyAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLabelNamespace/title",
          "value": "HMCharacteristicValueLabelNamespace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLabelNamespace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLabelNamespace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueLabelNamespace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueLabelNamespace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeVersion/title",
          "value": "HMCharacteristicTypeVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeIdentifier/title",
          "value": "HMCharacteristicTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeInputSourceType/title",
          "value": "HMCharacteristicTypeInputSourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeInputSourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeInputSourceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeName/title",
          "value": "HMCharacteristicTypeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeLabelIndex/title",
          "value": "HMCharacteristicTypeLabelIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeLabelIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeLabelIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeHardwareVersion/title",
          "value": "HMCharacteristicTypeHardwareVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeHardwareVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeHardwareVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeActiveIdentifier/title",
          "value": "HMCharacteristicTypeActiveIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeActiveIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeActiveIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeLabelNamespace/title",
          "value": "HMCharacteristicTypeLabelNamespace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeLabelNamespace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeLabelNamespace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeInputDeviceType/title",
          "value": "HMCharacteristicTypeInputDeviceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeInputDeviceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeInputDeviceType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcharacteristictypelabelnamespace"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcharacteristictypelabelnamespace"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
