{
  "abstract": [
    {
      "text": "A specific characteristic of a service, like the brightness of a dimmable light or its color temperature.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HMCharacteristic",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HMCharacteristic"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCharacteristic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "HMCharacteristic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HMCharacteristic"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance represents an aspect of a service that provides data, or that your app can control.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You don’t create characteristic instances. Instead, an accessory manufacturer incorporates them into a device, which publishes them to you through the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMService/characteristics",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array of an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMService",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Characteristics have a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/properties",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array that indicates attributes like readability, writability, and user-visibility. They also have a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/characteristicType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property that tells your app what the characteristic controls or describes. Device manufacturers can use one of the standard types, given in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/characteristic-types",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or they can create custom types.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each characteristic has a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/value",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that you can read or write. Some characteristics use plain numbers, Booleans, or strings. Others have application specific meanings declared in enumerations associated with the given characteristic type. The characteristic’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/metadata",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " can help your app interpret the value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessory": {
      "abstract": [
        {
          "text": "A home automation accessory, like a garage door opener or a thermostat.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessory"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessory"
        }
      ],
      "role": "symbol",
      "title": "HMAccessory",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessory"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupManager": {
      "abstract": [
        {
          "text": "An object that setups up new accessories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessorySetupManager"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessorySetupManager"
        }
      ],
      "role": "symbol",
      "title": "HMAccessorySetupManager",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorysetupmanager"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest": {
      "abstract": [
        {
          "text": "An object that describes how to add and setup up new accessories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessorySetupRequest"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessorySetupRequest"
        }
      ],
      "role": "symbol",
      "title": "HMAccessorySetupRequest",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorysetuprequest"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupResult": {
      "abstract": [
        {
          "text": "A result object describing information about a successful accessory setup request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMAccessorySetupResult"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMAccessorySetupResult"
        }
      ],
      "role": "symbol",
      "title": "HMAccessorySetupResult",
      "type": "topic",
      "url": "/documentation/homekit/hmaccessorysetupresult"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic": {
      "abstract": [
        {
          "text": "A specific characteristic of a service, like the brightness of a dimmable light or its color temperature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristic"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristic",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/characteristicType": {
      "abstract": [
        {
          "text": "The type of the characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "characteristicType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/characteristicType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "characteristicType"
        }
      ],
      "role": "symbol",
      "title": "characteristicType",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic/characteristictype"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/enableNotification(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Enables or disables notifications for changes in the value of the characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableNotification"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/enableNotification(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableNotification:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "enableNotification(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic/enablenotification(_:completionhandler:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/init()": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic/init()"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/isNotificationEnabled": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the characteristic has been set to send notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isNotificationEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/isNotificationEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notificationEnabled"
        }
      ],
      "role": "symbol",
      "title": "isNotificationEnabled",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic/isnotificationenabled"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/localizedDescription": {
      "abstract": [
        {
          "text": "The localized description of the characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/localizedDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedDescription"
        }
      ],
      "role": "symbol",
      "title": "localizedDescription",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic/localizeddescription"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/metadata": {
      "abstract": [
        {
          "text": "Metadata about the units and other properties of the characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMCharacteristicMetadata",
          "text": "HMCharacteristicMetadata"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadata"
        }
      ],
      "role": "symbol",
      "title": "metadata",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic/metadata"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/properties": {
      "abstract": [
        {
          "text": "An array of properties that describe the characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "properties"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/properties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "properties"
        }
      ],
      "role": "symbol",
      "title": "properties",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic/properties"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/readValue(completionHandler:)": {
      "abstract": [
        {
          "text": "Reads the value for the characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/readValue(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readValueWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "readValue(completionHandler:)",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic/readvalue(completionhandler:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/service": {
      "abstract": [
        {
          "text": "The service that contains this characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "service"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMService",
          "text": "HMService"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/service",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "service"
        }
      ],
      "role": "symbol",
      "title": "service",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic/service"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/uniqueIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for the characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uniqueIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/uniqueIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uniqueIdentifier"
        }
      ],
      "role": "symbol",
      "title": "uniqueIdentifier",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic/uniqueidentifier"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/updateAuthorizationData(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Sets or clears authorization data used when writing to the characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateAuthorizationData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/updateAuthorizationData(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateAuthorizationData:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "updateAuthorizationData(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic/updateauthorizationdata(_:completionhandler:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/value": {
      "abstract": [
        {
          "text": "The current value of the characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "value"
        }
      ],
      "role": "symbol",
      "title": "value",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic/value"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/writeValue(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Modifies the value of the characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/writeValue(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeValue:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "writeValue(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristic/writevalue(_:completionhandler:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata": {
      "abstract": [
        {
          "text": "Metadata that describes a characteristic’s value and that may be useful for presentation purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadata"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicMetadata"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicMetadata",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicmetadata"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile": {
      "abstract": [
        {
          "text": "An interface from which to read and, if allowed by the accessory, update the ordering of input sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMMediaSourceDisplayOrderProfile"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMMediaSourceDisplayOrderProfile"
        }
      ],
      "role": "symbol",
      "title": "HMMediaSourceDisplayOrderProfile",
      "type": "topic",
      "url": "/documentation/homekit/hmmediasourcedisplayorderprofile"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMService": {
      "abstract": [
        {
          "text": "A controllable feature of an accessory, like a light attached to a garage door opener.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMService"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMService"
        }
      ],
      "role": "symbol",
      "title": "HMService",
      "type": "topic",
      "url": "/documentation/homekit/hmservice"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMService/characteristics": {
      "abstract": [
        {
          "text": "An array of characteristics for the service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "characteristics"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMCharacteristic",
          "text": "HMCharacteristic"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMService/characteristics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "characteristics"
        }
      ],
      "role": "symbol",
      "title": "characteristics",
      "type": "topic",
      "url": "/documentation/homekit/hmservice/characteristics"
    },
    "doc://com.apple.homekit/documentation/HomeKit/characteristic-properties": {
      "abstract": [
        {
          "text": "The properties that characteristics can have.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/characteristic-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Characteristic Properties",
      "type": "topic",
      "url": "/documentation/homekit/characteristic-properties"
    },
    "doc://com.apple.homekit/documentation/HomeKit/characteristic-types": {
      "abstract": [
        {
          "text": "The characteristic types supported by HomeKit-based accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/characteristic-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Characteristic types",
      "type": "topic",
      "url": "/documentation/homekit/characteristic-types"
    },
    "doc://com.apple.homekit/documentation/HomeKit/interacting-with-a-home-automation-network": {
      "abstract": [
        {
          "text": "Find all the automation accessories in the primary home and control their state.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/interacting-with-a-home-automation-network",
      "kind": "article",
      "role": "sampleCode",
      "title": "Interacting with a home automation network",
      "type": "topic",
      "url": "/documentation/homekit/interacting-with-a-home-automation-network"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessories",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupManager",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupResult",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest",
        "doc://com.apple.homekit/documentation/HomeKit/interacting-with-a-home-automation-network",
        "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
        "doc://com.apple.homekit/documentation/HomeKit/HMService",
        "doc://com.apple.homekit/documentation/HomeKit/HMMediaSourceDisplayOrderProfile"
      ],
      "title": "Accessories"
    }
  ],
  "topicSections": [
    {
      "anchor": "Identifying-a-characteristic",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/uniqueIdentifier",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/localizedDescription"
      ],
      "title": "Identifying a characteristic"
    },
    {
      "anchor": "Reading-characteristic-properties",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/properties",
        "doc://com.apple.homekit/documentation/HomeKit/characteristic-properties"
      ],
      "title": "Reading characteristic properties"
    },
    {
      "anchor": "Determining-what-a-characteristic-controls",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/characteristicType",
        "doc://com.apple.homekit/documentation/HomeKit/characteristic-types"
      ],
      "title": "Determining what a characteristic controls"
    },
    {
      "anchor": "Controlling-a-characteristic",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/value",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/readValue(completionHandler:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/writeValue(_:completionHandler:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/updateAuthorizationData(_:completionHandler:)"
      ],
      "title": "Controlling a characteristic"
    },
    {
      "anchor": "Managing-characteristic-presentation",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/metadata",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata"
      ],
      "title": "Managing characteristic presentation"
    },
    {
      "anchor": "Receiving-change-notifications",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/enableNotification(_:completionHandler:)",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/isNotificationEnabled"
      ],
      "title": "Receiving change notifications"
    },
    {
      "anchor": "Getting-the-characterized-service",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/service"
      ],
      "title": "Getting the characterized service"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/init()"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCharacteristic"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Identifying-a-characteristic",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/uniqueIdentifier",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/localizedDescription"
              ],
              "title": "Identifying a characteristic"
            },
            {
              "anchor": "Reading-characteristic-properties",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/properties",
                "doc://com.apple.homekit/documentation/HomeKit/characteristic-properties"
              ],
              "title": "Reading characteristic properties"
            },
            {
              "anchor": "Determining-what-a-characteristic-controls",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/characteristicType",
                "doc://com.apple.homekit/documentation/HomeKit/characteristic-types"
              ],
              "title": "Determining what a characteristic controls"
            },
            {
              "anchor": "Controlling-a-characteristic",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/value",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/readValue(completionHandler:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/writeValue(_:completionHandler:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/updateAuthorizationData(_:completionHandler:)"
              ],
              "title": "Controlling a characteristic"
            },
            {
              "anchor": "Managing-characteristic-presentation",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/metadata",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicMetadata"
              ],
              "title": "Managing characteristic presentation"
            },
            {
              "anchor": "Receiving-change-notifications",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/enableNotification(_:completionHandler:)",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/isNotificationEnabled"
              ],
              "title": "Receiving change notifications"
            },
            {
              "anchor": "Getting-the-characterized-service",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/service"
              ],
              "title": "Getting the characterized service"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristic/init()"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessories",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupManager",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupResult",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessorySetupRequest",
                "doc://com.apple.homekit/documentation/HomeKit/interacting-with-a-home-automation-network",
                "doc://com.apple.homekit/documentation/HomeKit/HMAccessory",
                "doc://com.apple.homekit/documentation/HomeKit/HMService"
              ],
              "title": "Accessories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HMCharacteristic"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic/title",
          "value": "HMCharacteristic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1updateAuthorizationData(_:completionHandler:)/title",
          "value": "updateAuthorizationData:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1updateAuthorizationData(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateAuthorizationData:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupResult/title",
          "value": "HMAccessorySetupResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/title",
          "value": "HMAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1writeValue(_:completionHandler:)/title",
          "value": "writeValue:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1writeValue(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeValue:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadata/title",
          "value": "HMCharacteristicMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1isNotificationEnabled/title",
          "value": "notificationEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1isNotificationEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notificationEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1properties/title",
          "value": "properties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1properties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1readValue(completionHandler:)/title",
          "value": "readValueWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1readValue(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readValueWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1characteristicType/title",
          "value": "characteristicType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1characteristicType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "characteristicType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupManager/title",
          "value": "HMAccessorySetupManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService~1characteristics/title",
          "value": "characteristics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService~1characteristics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "characteristics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1uniqueIdentifier/title",
          "value": "uniqueIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1uniqueIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uniqueIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest/title",
          "value": "HMAccessorySetupRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMAccessorySetupRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMAccessorySetupRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1service/title",
          "value": "service"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1service/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "service"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1value/title",
          "value": "value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService/title",
          "value": "HMService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1enableNotification(_:completionHandler:)/title",
          "value": "enableNotification:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1enableNotification(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enableNotification:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1localizedDescription/title",
          "value": "localizedDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1localizedDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1metadata/title",
          "value": "metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristic~1metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadata"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcharacteristic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcharacteristic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
