{
  "abstract": [
    {
      "text": "Modes of the television picture.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HMCharacteristicValuePictureMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HMCharacteristicValuePictureMode"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCharacteristicValuePictureMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "HMCharacteristicValuePictureMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode": {
      "abstract": [
        {
          "text": "Modes of the television picture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureMode"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureMode"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValuePictureMode",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/bright": {
      "abstract": [
        {
          "text": "A bright picture mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bright"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/bright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureModeBright"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValuePictureMode.bright",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode/bright"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/calibrated": {
      "abstract": [
        {
          "text": "A calibrated picture mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calibrated"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/calibrated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureModeCalibrated"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValuePictureMode.calibrated",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode/calibrated"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/computer": {
      "abstract": [
        {
          "text": "A computer picture mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "computer"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/computer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureModeComputer"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValuePictureMode.computer",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode/computer"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/custom1": {
      "abstract": [
        {
          "text": "A customized picture mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "custom1"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/custom1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureModeCustom1"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValuePictureMode.custom1",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode/custom1"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/custom2": {
      "abstract": [
        {
          "text": "A customized picture mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "custom2"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/custom2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureModeCustom2"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValuePictureMode.custom2",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode/custom2"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/custom3": {
      "abstract": [
        {
          "text": "A customized picture mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "custom3"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/custom3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureModeCustom3"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValuePictureMode.custom3",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode/custom3"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/dark": {
      "abstract": [
        {
          "text": "A dark picture mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dark"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/dark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureModeDark"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValuePictureMode.dark",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode/dark"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/game": {
      "abstract": [
        {
          "text": "A game picture mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "game"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/game",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureModeGame"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValuePictureMode.game",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode/game"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode/init(rawvalue:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/movie": {
      "abstract": [
        {
          "text": "A movie picture mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "movie"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/movie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureModeMovie"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValuePictureMode.movie",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode/movie"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/night": {
      "abstract": [
        {
          "text": "A night picture mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "night"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/night",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureModeNight"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValuePictureMode.night",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode/night"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/photo": {
      "abstract": [
        {
          "text": "A photo picture mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photo"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/photo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureModePhoto"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValuePictureMode.photo",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode/photo"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/sport": {
      "abstract": [
        {
          "text": "A sport picture mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sport"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/sport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureModeSport"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValuePictureMode.sport",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode/sport"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/standard": {
      "abstract": [
        {
          "text": "A standard picture mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standard"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/standard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureModeStandard"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValuePictureMode.standard",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode/standard"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/vivid": {
      "abstract": [
        {
          "text": "A vivid picture mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vivid"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/vivid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValuePictureModeVivid"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValuePictureMode.vivid",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvaluepicturemode/vivid"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Television-states",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/bright",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/calibrated",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/computer",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/custom1",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/custom2",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/custom3",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/dark",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/game",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/movie",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/night",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/photo",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/sport",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/standard",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/vivid"
      ],
      "title": "Television states"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCharacteristicValuePictureMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Television-states",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/bright",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/calibrated",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/computer",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/custom1",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/custom2",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/custom3",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/dark",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/game",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/movie",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/night",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/photo",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/sport",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/standard",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValuePictureMode/vivid"
              ],
              "title": "Television states"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HMCharacteristicValuePictureMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1custom2/title",
          "value": "HMCharacteristicValuePictureModeCustom2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1custom2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureModeCustom2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1dark/title",
          "value": "HMCharacteristicValuePictureModeDark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1dark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureModeDark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1bright/title",
          "value": "HMCharacteristicValuePictureModeBright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1bright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureModeBright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1movie/title",
          "value": "HMCharacteristicValuePictureModeMovie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1movie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureModeMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1calibrated/title",
          "value": "HMCharacteristicValuePictureModeCalibrated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1calibrated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureModeCalibrated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1game/title",
          "value": "HMCharacteristicValuePictureModeGame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1game/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureModeGame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode/title",
          "value": "HMCharacteristicValuePictureMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1computer/title",
          "value": "HMCharacteristicValuePictureModeComputer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1computer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureModeComputer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1vivid/title",
          "value": "HMCharacteristicValuePictureModeVivid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1vivid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureModeVivid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1custom3/title",
          "value": "HMCharacteristicValuePictureModeCustom3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1custom3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureModeCustom3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1night/title",
          "value": "HMCharacteristicValuePictureModeNight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1night/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureModeNight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1custom1/title",
          "value": "HMCharacteristicValuePictureModeCustom1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1custom1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureModeCustom1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1photo/title",
          "value": "HMCharacteristicValuePictureModePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1photo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureModePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1standard/title",
          "value": "HMCharacteristicValuePictureModeStandard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1standard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureModeStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1sport/title",
          "value": "HMCharacteristicValuePictureModeSport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValuePictureMode~1sport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValuePictureModeSport"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcharacteristicvaluepicturemode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcharacteristicvaluepicturemode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
