{
  "abstract": [
    {
      "text": "The current usage state of an accessory.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeInUse"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@HMCharacteristicTypeInUse",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "HMCharacteristicTypeInUse"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMCharacteristicTypeInUse"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "HMCharacteristicTypeInUse"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeInUse"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The corresponding value is one of the constants in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueUsageState",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " enumeration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeActive": {
      "abstract": [
        {
          "text": "The current status of an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeActive"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeActive",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeactive"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentMediaState": {
      "abstract": [
        {
          "text": "The current state of the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCurrentMediaState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentMediaState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCurrentMediaState"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeCurrentMediaState",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypecurrentmediastate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentVisibilityState": {
      "abstract": [
        {
          "text": "The current visibility state for a service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCurrentVisibilityState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentVisibilityState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeCurrentVisibilityState"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeCurrentVisibilityState",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypecurrentvisibilitystate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeInUse": {
      "abstract": [
        {
          "text": "The current usage state of an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeInUse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeInUse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeInUse"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeInUse",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeinuse"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeIsConfigured": {
      "abstract": [
        {
          "text": "The configuration state of an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeIsConfigured"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeIsConfigured",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeIsConfigured"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeIsConfigured",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeisconfigured"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeProgramMode": {
      "abstract": [
        {
          "text": "The current mode of the accessory’s scheduled programs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeProgramMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeProgramMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeProgramMode"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeProgramMode",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypeprogrammode"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeRemainingDuration": {
      "abstract": [
        {
          "text": "The number of seconds remaining for the activity being carried out by the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeRemainingDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeRemainingDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeRemainingDuration"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeRemainingDuration",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictyperemainingduration"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeRouterStatus": {
      "abstract": [
        {
          "text": "The current status of the router.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeRouterStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeRouterStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeRouterStatus"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeRouterStatus",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictyperouterstatus"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSetDuration": {
      "abstract": [
        {
          "text": "The duration of the activity being carried out by the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSetDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSetDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeSetDuration"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeSetDuration",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypesetduration"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusActive": {
      "abstract": [
        {
          "text": "An indicator of whether the service is working.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeStatusActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeStatusActive"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeStatusActive",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypestatusactive"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusFault": {
      "abstract": [
        {
          "text": "An indicator of whether the accessory has experienced a fault.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeStatusFault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeStatusFault"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeStatusFault",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypestatusfault"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusTampered": {
      "abstract": [
        {
          "text": "An indicator of whether an accessory has been tampered with.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeStatusTampered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusTampered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeStatusTampered"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeStatusTampered",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypestatustampered"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetMediaState": {
      "abstract": [
        {
          "text": "The target media state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeTargetMediaState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetMediaState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeTargetMediaState"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeTargetMediaState",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypetargetmediastate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetVisibilityState": {
      "abstract": [
        {
          "text": "The target visibility state for a service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeTargetVisibilityState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetVisibilityState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeTargetVisibilityState"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeTargetVisibilityState",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypetargetvisibilitystate"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeWANStatusList": {
      "abstract": [
        {
          "text": "The WAN status list of an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeWANStatusList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeWANStatusList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeWANStatusList"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeWANStatusList",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypewanstatuslist"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeWiFiSatelliteStatus": {
      "abstract": [
        {
          "text": "The network status of the WiFi satellite accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeWiFiSatelliteStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeWiFiSatelliteStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicTypeWiFiSatelliteStatus"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicTypeWiFiSatelliteStatus",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristictypewifisatellitestatus"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueUsageState": {
      "abstract": [
        {
          "text": "Possible values for the usage state of an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueUsageState"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueUsageState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCharacteristicValueUsageState"
        }
      ],
      "role": "symbol",
      "title": "HMCharacteristicValueUsageState",
      "type": "topic",
      "url": "/documentation/homekit/hmcharacteristicvalueusagestate"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "General-state",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeActive",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusTampered",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusFault",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusActive",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeIsConfigured",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeRemainingDuration",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSetDuration",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeProgramMode",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeWiFiSatelliteStatus",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeWANStatusList",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetMediaState",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeRouterStatus",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentMediaState",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentVisibilityState",
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetVisibilityState"
      ],
      "title": "General state"
    }
  ],
  "topicSections": [
    {
      "anchor": "Values",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueUsageState"
      ],
      "title": "Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMCharacteristicTypeInUse"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeInUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Values",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicValueUsageState"
              ],
              "title": "Values"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "General-state",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeActive",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusTampered",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusFault",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeStatusActive",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeIsConfigured",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeRemainingDuration",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeSetDuration",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeProgramMode",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeWiFiSatelliteStatus",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeWANStatusList",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetMediaState",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeRouterStatus",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentMediaState",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeCurrentVisibilityState",
                "doc://com.apple.homekit/documentation/HomeKit/HMCharacteristicTypeTargetVisibilityState"
              ],
              "title": "General state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HMCharacteristicTypeInUse"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeStatusTampered/title",
          "value": "HMCharacteristicTypeStatusTampered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeStatusTampered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeStatusTampered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeStatusFault/title",
          "value": "HMCharacteristicTypeStatusFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeStatusFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeStatusFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeRemainingDuration/title",
          "value": "HMCharacteristicTypeRemainingDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeRemainingDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeRemainingDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeWANStatusList/title",
          "value": "HMCharacteristicTypeWANStatusList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeWANStatusList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeWANStatusList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeRouterStatus/title",
          "value": "HMCharacteristicTypeRouterStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeRouterStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeRouterStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeIsConfigured/title",
          "value": "HMCharacteristicTypeIsConfigured"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeIsConfigured/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeIsConfigured"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeTargetVisibilityState/title",
          "value": "HMCharacteristicTypeTargetVisibilityState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeTargetVisibilityState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeTargetVisibilityState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeInUse/title",
          "value": "HMCharacteristicTypeInUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeInUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeInUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCurrentVisibilityState/title",
          "value": "HMCharacteristicTypeCurrentVisibilityState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCurrentVisibilityState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeCurrentVisibilityState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeStatusActive/title",
          "value": "HMCharacteristicTypeStatusActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeStatusActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeStatusActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeActive/title",
          "value": "HMCharacteristicTypeActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueUsageState/title",
          "value": "HMCharacteristicValueUsageState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueUsageState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueUsageState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicValueUsageState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicValueUsageState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeWiFiSatelliteStatus/title",
          "value": "HMCharacteristicTypeWiFiSatelliteStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeWiFiSatelliteStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeWiFiSatelliteStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeProgramMode/title",
          "value": "HMCharacteristicTypeProgramMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeProgramMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeProgramMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCurrentMediaState/title",
          "value": "HMCharacteristicTypeCurrentMediaState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeCurrentMediaState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeCurrentMediaState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeTargetMediaState/title",
          "value": "HMCharacteristicTypeTargetMediaState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeTargetMediaState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeTargetMediaState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSetDuration/title",
          "value": "HMCharacteristicTypeSetDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCharacteristicTypeSetDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCharacteristicTypeSetDuration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmcharacteristictypeinuse"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmcharacteristictypeinuse"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
