{
  "abstract": [
    {
      "text": "Events that represent the user’s movement among regions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager",
        "doc://com.apple.homekit/documentation/HomeKit/HMHome",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/location-events"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Location events"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEvent": {
      "abstract": [
        {
          "text": "The abstract base class for a HomeKit event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMEvent"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMEvent"
        }
      ],
      "role": "symbol",
      "title": "HMEvent",
      "type": "topic",
      "url": "/documentation/homekit/hmevent"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger": {
      "abstract": [
        {
          "text": "A trigger to activate an action set based on a set of events and optional conditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMEventTrigger"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMEventTrigger"
        }
      ],
      "role": "symbol",
      "title": "HMEventTrigger",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/events": {
      "abstract": [
        {
          "text": "The events that activate the trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "events"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMEvent",
          "text": "HMEvent"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/events",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "events"
        }
      ],
      "role": "symbol",
      "title": "events",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger/events"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/updateEvents(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Updates the set of trigger events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateEvents"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMEvent",
          "text": "HMEvent"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/updateEvents(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateEvents:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "updateEvents(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger/updateevents(_:completionhandler:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHome": {
      "abstract": [
        {
          "text": "The primary unit of living space, typically composed of rooms organized into zones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "role": "symbol",
      "title": "HMHome",
      "type": "topic",
      "url": "/documentation/homekit/hmhome"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager": {
      "abstract": [
        {
          "text": "The manager for a collection of one or more of a user’s homes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "role": "symbol",
      "title": "HMHomeManager",
      "type": "topic",
      "url": "/documentation/homekit/hmhomemanager"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMLocationEvent": {
      "abstract": [
        {
          "text": "An event that is evaluated based on entry to or exit from a region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMLocationEvent"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMLocationEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMLocationEvent"
        }
      ],
      "role": "symbol",
      "title": "HMLocationEvent",
      "type": "topic",
      "url": "/documentation/homekit/hmlocationevent"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMMutableLocationEvent": {
      "abstract": [
        {
          "text": "A mutable event that is evaluated based on entry to or exit from a region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMMutableLocationEvent"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMMutableLocationEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMMutableLocationEvent"
        }
      ],
      "role": "symbol",
      "title": "HMMutableLocationEvent",
      "type": "topic",
      "url": "/documentation/homekit/hmmutablelocationevent"
    },
    "doc://com.apple.homekit/documentation/HomeKit/characteristic-events": {
      "abstract": [
        {
          "text": "Events based on the capabilities or characteristics of accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/characteristic-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Characteristic events",
      "type": "topic",
      "url": "/documentation/homekit/characteristic-events"
    },
    "doc://com.apple.homekit/documentation/HomeKit/presence-events": {
      "abstract": [
        {
          "text": "Events based on the user’s presence in a home.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/presence-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Presence events",
      "type": "topic",
      "url": "/documentation/homekit/presence-events"
    },
    "doc://com.apple.homekit/documentation/HomeKit/time-events": {
      "abstract": [
        {
          "text": "Events based on time, significant occurrences, and time durations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/time-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Time events",
      "type": "topic",
      "url": "/documentation/homekit/time-events"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-trigger-events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/events",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/updateEvents(_:completionHandler:)",
        "doc://com.apple.homekit/documentation/HomeKit/time-events",
        "doc://com.apple.homekit/documentation/HomeKit/characteristic-events",
        "doc://com.apple.homekit/documentation/HomeKit/presence-events",
        "doc://com.apple.homekit/documentation/HomeKit/HMEvent"
      ],
      "title": "Setting trigger events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Locations",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMLocationEvent",
        "doc://com.apple.homekit/documentation/HomeKit/HMMutableLocationEvent"
      ],
      "title": "Locations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Locations",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMLocationEvent",
                "doc://com.apple.homekit/documentation/HomeKit/HMMutableLocationEvent"
              ],
              "title": "Locations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-trigger-events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/events",
                "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/updateEvents(_:completionHandler:)",
                "doc://com.apple.homekit/documentation/HomeKit/time-events",
                "doc://com.apple.homekit/documentation/HomeKit/characteristic-events",
                "doc://com.apple.homekit/documentation/HomeKit/presence-events",
                "doc://com.apple.homekit/documentation/HomeKit/HMEvent"
              ],
              "title": "Setting trigger events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger/title",
          "value": "HMEventTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEvent/title",
          "value": "HMEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/title",
          "value": "HMHomeManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/title",
          "value": "HMHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMLocationEvent/title",
          "value": "HMLocationEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMLocationEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMLocationEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMLocationEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMLocationEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMMutableLocationEvent/title",
          "value": "HMMutableLocationEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMMutableLocationEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMMutableLocationEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMMutableLocationEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMMutableLocationEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1events/title",
          "value": "events"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1events/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1updateEvents(_:completionHandler:)/title",
          "value": "updateEvents:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1updateEvents(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateEvents:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/location-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/location-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
