{
  "abstract": [
    {
      "text": "Events based on time, significant occurrences, and time durations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager",
        "doc://com.apple.homekit/documentation/HomeKit/HMHome",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/time-events"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Time events"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMCalendarEvent": {
      "abstract": [
        {
          "text": "An event that fires at a specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMCalendarEvent"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMCalendarEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMCalendarEvent"
        }
      ],
      "role": "symbol",
      "title": "HMCalendarEvent",
      "type": "topic",
      "url": "/documentation/homekit/hmcalendarevent"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMDurationEvent": {
      "abstract": [
        {
          "text": "An event that ends after the specified time duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMDurationEvent"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMDurationEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMDurationEvent"
        }
      ],
      "role": "symbol",
      "title": "HMDurationEvent",
      "type": "topic",
      "url": "/documentation/homekit/hmdurationevent"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEvent": {
      "abstract": [
        {
          "text": "The abstract base class for a HomeKit event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMEvent"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMEvent"
        }
      ],
      "role": "symbol",
      "title": "HMEvent",
      "type": "topic",
      "url": "/documentation/homekit/hmevent"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger": {
      "abstract": [
        {
          "text": "A trigger to activate an action set based on a set of events and optional conditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMEventTrigger"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMEventTrigger"
        }
      ],
      "role": "symbol",
      "title": "HMEventTrigger",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/events": {
      "abstract": [
        {
          "text": "The events that activate the trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "events"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMEvent",
          "text": "HMEvent"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/events",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "events"
        }
      ],
      "role": "symbol",
      "title": "events",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger/events"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/updateEvents(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Updates the set of trigger events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateEvents"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HMEvent",
          "text": "HMEvent"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/updateEvents(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateEvents:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "updateEvents(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/homekit/hmeventtrigger/updateevents(_:completionhandler:)"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHome": {
      "abstract": [
        {
          "text": "The primary unit of living space, typically composed of rooms organized into zones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHome"
        }
      ],
      "role": "symbol",
      "title": "HMHome",
      "type": "topic",
      "url": "/documentation/homekit/hmhome"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager": {
      "abstract": [
        {
          "text": "The manager for a collection of one or more of a user’s homes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMHomeManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "role": "symbol",
      "title": "HMHomeManager",
      "type": "topic",
      "url": "/documentation/homekit/hmhomemanager"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMMutableCalendarEvent": {
      "abstract": [
        {
          "text": "A mutable event that fires at a specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMMutableCalendarEvent"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMMutableCalendarEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMMutableCalendarEvent"
        }
      ],
      "role": "symbol",
      "title": "HMMutableCalendarEvent",
      "type": "topic",
      "url": "/documentation/homekit/hmmutablecalendarevent"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMMutableDurationEvent": {
      "abstract": [
        {
          "text": "A mutable event that fires after the specified time duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMMutableDurationEvent"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMMutableDurationEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMMutableDurationEvent"
        }
      ],
      "role": "symbol",
      "title": "HMMutableDurationEvent",
      "type": "topic",
      "url": "/documentation/homekit/hmmutabledurationevent"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMMutableSignificantTimeEvent": {
      "abstract": [
        {
          "text": "A mutable event that fires at the specified temporal offset to a significant event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMMutableSignificantTimeEvent"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMMutableSignificantTimeEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMMutableSignificantTimeEvent"
        }
      ],
      "role": "symbol",
      "title": "HMMutableSignificantTimeEvent",
      "type": "topic",
      "url": "/documentation/homekit/hmmutablesignificanttimeevent"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMSignificantEvent": {
      "abstract": [
        {
          "text": "An event that represents significant time-based events, including sunrise and sunset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMSignificantEvent"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMSignificantEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMSignificantEvent"
        }
      ],
      "role": "symbol",
      "title": "HMSignificantEvent",
      "type": "topic",
      "url": "/documentation/homekit/hmsignificantevent"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMSignificantTimeEvent": {
      "abstract": [
        {
          "text": "An event that fires at a time offset from a significant time-based event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMSignificantTimeEvent"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMSignificantTimeEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMSignificantTimeEvent"
        }
      ],
      "role": "symbol",
      "title": "HMSignificantTimeEvent",
      "type": "topic",
      "url": "/documentation/homekit/hmsignificanttimeevent"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMTimeEvent": {
      "abstract": [
        {
          "text": "An abstract superclass for time-based events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMTimeEvent"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMTimeEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMTimeEvent"
        }
      ],
      "role": "symbol",
      "title": "HMTimeEvent",
      "type": "topic",
      "url": "/documentation/homekit/hmtimeevent"
    },
    "doc://com.apple.homekit/documentation/HomeKit/characteristic-events": {
      "abstract": [
        {
          "text": "Events based on the capabilities or characteristics of accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/characteristic-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Characteristic events",
      "type": "topic",
      "url": "/documentation/homekit/characteristic-events"
    },
    "doc://com.apple.homekit/documentation/HomeKit/location-events": {
      "abstract": [
        {
          "text": "Events that represent the user’s movement among regions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/location-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Location events",
      "type": "topic",
      "url": "/documentation/homekit/location-events"
    },
    "doc://com.apple.homekit/documentation/HomeKit/presence-events": {
      "abstract": [
        {
          "text": "Events based on the user’s presence in a home.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/presence-events",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Presence events",
      "type": "topic",
      "url": "/documentation/homekit/presence-events"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-trigger-events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/events",
        "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/updateEvents(_:completionHandler:)",
        "doc://com.apple.homekit/documentation/HomeKit/location-events",
        "doc://com.apple.homekit/documentation/HomeKit/characteristic-events",
        "doc://com.apple.homekit/documentation/HomeKit/presence-events",
        "doc://com.apple.homekit/documentation/HomeKit/HMEvent"
      ],
      "title": "Setting trigger events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Dates-and-times",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMCalendarEvent",
        "doc://com.apple.homekit/documentation/HomeKit/HMMutableCalendarEvent",
        "doc://com.apple.homekit/documentation/HomeKit/HMTimeEvent"
      ],
      "title": "Dates and times"
    },
    {
      "anchor": "Significant-events",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMSignificantEvent",
        "doc://com.apple.homekit/documentation/HomeKit/HMSignificantTimeEvent",
        "doc://com.apple.homekit/documentation/HomeKit/HMMutableSignificantTimeEvent"
      ],
      "title": "Significant events"
    },
    {
      "anchor": "Durations",
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMDurationEvent",
        "doc://com.apple.homekit/documentation/HomeKit/HMMutableDurationEvent"
      ],
      "title": "Durations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dates-and-times",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMCalendarEvent",
                "doc://com.apple.homekit/documentation/HomeKit/HMMutableCalendarEvent",
                "doc://com.apple.homekit/documentation/HomeKit/HMTimeEvent"
              ],
              "title": "Dates and times"
            },
            {
              "anchor": "Significant-events",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMSignificantEvent",
                "doc://com.apple.homekit/documentation/HomeKit/HMSignificantTimeEvent",
                "doc://com.apple.homekit/documentation/HomeKit/HMMutableSignificantTimeEvent"
              ],
              "title": "Significant events"
            },
            {
              "anchor": "Durations",
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMDurationEvent",
                "doc://com.apple.homekit/documentation/HomeKit/HMMutableDurationEvent"
              ],
              "title": "Durations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-trigger-events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/events",
                "doc://com.apple.homekit/documentation/HomeKit/HMEventTrigger/updateEvents(_:completionHandler:)",
                "doc://com.apple.homekit/documentation/HomeKit/location-events",
                "doc://com.apple.homekit/documentation/HomeKit/characteristic-events",
                "doc://com.apple.homekit/documentation/HomeKit/presence-events",
                "doc://com.apple.homekit/documentation/HomeKit/HMEvent"
              ],
              "title": "Setting trigger events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTimeEvent/title",
          "value": "HMTimeEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTimeEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMTimeEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMTimeEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMTimeEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMMutableCalendarEvent/title",
          "value": "HMMutableCalendarEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMMutableCalendarEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMMutableCalendarEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMMutableCalendarEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMMutableCalendarEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMSignificantEvent/title",
          "value": "HMSignificantEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMSignificantEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMSignificantEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMSignificantEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMSignificantEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/title",
          "value": "HMHomeManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHomeManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMSignificantTimeEvent/title",
          "value": "HMSignificantTimeEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMSignificantTimeEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMSignificantTimeEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMSignificantTimeEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMSignificantTimeEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1events/title",
          "value": "events"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1events/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1updateEvents(_:completionHandler:)/title",
          "value": "updateEvents:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger~1updateEvents(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateEvents:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCalendarEvent/title",
          "value": "HMCalendarEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCalendarEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCalendarEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMCalendarEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMCalendarEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEvent/title",
          "value": "HMEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger/title",
          "value": "HMEventTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMEventTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMMutableDurationEvent/title",
          "value": "HMMutableDurationEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMMutableDurationEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMMutableDurationEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMMutableDurationEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMMutableDurationEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMDurationEvent/title",
          "value": "HMDurationEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMDurationEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMDurationEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMDurationEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMDurationEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMMutableSignificantTimeEvent/title",
          "value": "HMMutableSignificantTimeEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMMutableSignificantTimeEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMMutableSignificantTimeEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMMutableSignificantTimeEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMMutableSignificantTimeEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/title",
          "value": "HMHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMHome/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMHome"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/time-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/time-events"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
