{
  "abstract": [
    {
      "text": "Sent when the user finishes creating a contact or adding the displayed person properties to an existing contact.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbookui/documentation/AddressBookUI",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate/unknownPersonViewController(_:didResolveToPerson:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)ABUnknownPersonViewControllerDelegate(im)unknownPersonViewController:didResolveToPerson:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unknownPersonViewController"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ABUnknownPersonViewController",
        "text": "ABUnknownPersonViewController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didResolveToPerson"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ABRecordRef",
        "text": "ABRecord"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "Address Book UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "unknownPersonViewController:didResolveToPerson:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "unknownPersonViewController(_:didResolveToPerson:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unknownPersonViewController"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "unknownCardViewController"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ABUnknownPersonViewController",
              "text": "ABUnknownPersonViewController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didResolveToPerson"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "person"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@ABRecordRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ABRecordRef",
              "text": "ABRecord"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The contact the user created or to which they added information. This record is saved in the Address Book database.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " when the user cancelled the interaction.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "person"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.addressbookui/documentation/AddressBookUI": {
      "abstract": [
        {
          "text": "Access users’ contacts and display them in a graphical interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book UI",
      "type": "topic",
      "url": "/documentation/addressbookui"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewController": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "ABUnknownPersonViewController",
          "type": "codeVoice"
        },
        {
          "text": " class (whose instances are known as ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "unknown-person view controllers",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": ") implements a view controller used to create a person record from a set of person properties.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABUnknownPersonViewController"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABUnknownPersonViewController"
        }
      ],
      "role": "symbol",
      "title": "ABUnknownPersonViewController",
      "type": "topic",
      "url": "/documentation/addressbookui/abunknownpersonviewcontroller"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate": {
      "abstract": [
        {
          "text": "The methods you use to respond to events in an unknown person view controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABUnknownPersonViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABUnknownPersonViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "ABUnknownPersonViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/addressbookui/abunknownpersonviewcontrollerdelegate"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate/unknownPersonViewController(_:didResolveToPerson:)": {
      "abstract": [
        {
          "text": "Sent when the user finishes creating a contact or adding the displayed person properties to an existing contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownPersonViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABUnknownPersonViewController",
          "text": "ABUnknownPersonViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didResolveToPerson"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate/unknownPersonViewController(_:didResolveToPerson:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unknownPersonViewController:didResolveToPerson:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "unknownPersonViewController(_:didResolveToPerson:)",
      "type": "topic",
      "url": "/documentation/addressbookui/abunknownpersonviewcontrollerdelegate/unknownpersonviewcontroller(_:didresolvetoperson:)"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate/unknownPersonViewController(_:shouldPerformDefaultActionForPerson:property:identifier:)": {
      "abstract": [
        {
          "text": "Sent when the user selects a property value of the person displayed in a person view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownPersonViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABUnknownPersonViewController",
          "text": "ABUnknownPersonViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldPerformDefaultActionForPerson"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "property"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPropertyID",
          "text": "ABPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABMultiValueIdentifier",
          "text": "ABMultiValueIdentifier"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate/unknownPersonViewController(_:shouldPerformDefaultActionForPerson:property:identifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unknownPersonViewController:shouldPerformDefaultActionForPerson:property:identifier:"
        }
      ],
      "role": "symbol",
      "title": "unknownPersonViewController(_:shouldPerformDefaultActionForPerson:property:identifier:)",
      "type": "topic",
      "url": "/documentation/addressbookui/abunknownpersonviewcontrollerdelegate/unknownpersonviewcontroller(_:shouldperformdefaultactionforperson:property:identifier:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@ABRecordRef": {
      "abstract": [
        {
          "text": "A reference to an ABRecord object or any of its derivedopaque types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@ABRecordRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "ABRecord",
      "type": "topic",
      "url": "/documentation/AddressBook/ABRecord-swift.typealias"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-User-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate/unknownPersonViewController(_:shouldPerformDefaultActionForPerson:property:identifier:)"
      ],
      "title": "Responding to User Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "unknownPersonViewController:didResolveToPerson:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unknownPersonViewController:didResolveToPerson:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbookui/documentation/AddressBookUI",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-User-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewControllerDelegate/unknownPersonViewController(_:shouldPerformDefaultActionForPerson:property:identifier:)"
              ],
              "title": "Responding to User Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "unknownPersonViewController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABUnknownPersonViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ABUnknownPersonViewController",
                    "text": "ABUnknownPersonViewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "unknownCardViewController"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didResolveToPerson:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@ABRecordRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ABRecordRef",
                    "text": "ABRecordRef"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "person"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The contact the user created or to which they added information. This record is saved in the Address Book database.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " when the user cancelled the interaction.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "person"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewControllerDelegate~1unknownPersonViewController(_:shouldPerformDefaultActionForPerson:property:identifier:)/title",
          "value": "unknownPersonViewController:shouldPerformDefaultActionForPerson:property:identifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewControllerDelegate~1unknownPersonViewController(_:shouldPerformDefaultActionForPerson:property:identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unknownPersonViewController:shouldPerformDefaultActionForPerson:property:identifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@ABRecordRef/title",
          "value": "ABRecordRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@ABRecordRef/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeRef",
              "text": "CFTypeRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ABRecordRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewControllerDelegate~1unknownPersonViewController(_:didResolveToPerson:)/title",
          "value": "unknownPersonViewController:didResolveToPerson:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewControllerDelegate~1unknownPersonViewController(_:didResolveToPerson:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unknownPersonViewController:didResolveToPerson:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewControllerDelegate/title",
          "value": "ABUnknownPersonViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABUnknownPersonViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABUnknownPersonViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewController/title",
          "value": "ABUnknownPersonViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABUnknownPersonViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABUnknownPersonViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABUnknownPersonViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbookui/abunknownpersonviewcontrollerdelegate/unknownpersonviewcontroller(_:didresolvetoperson:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbookui/abunknownpersonviewcontrollerdelegate/unknownpersonviewcontroller(_:didresolvetoperson:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
