{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusStoUnsent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@IOBluetoothHandsFreePDUMessageStatus@IOBluetoothHandsFreePDUStatusStoUnsent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "statusStoUnsent"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOBluetoothHandsFreePDUStatusStoUnsent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "IOBluetoothHandsFreePDUMessageStatus.statusStoUnsent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "statusStoUnsent"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreePDUMessageStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreePDUMessageStatus"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreePDUMessageStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreepdumessagestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusAll": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusAll"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusAll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreePDUStatusAll"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreePDUMessageStatus.statusAll",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreepdumessagestatus/statusall"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusRecRead": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusRecRead"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusRecRead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreePDUStatusRecRead"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreePDUMessageStatus.statusRecRead",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreepdumessagestatus/statusrecread"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusRecUnread": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusRecUnread"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusRecUnread",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreePDUStatusRecUnread"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreePDUMessageStatus.statusRecUnread",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreepdumessagestatus/statusrecunread"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusStoSent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusStoSent"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusStoSent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreePDUStatusStoSent"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreePDUMessageStatus.statusStoSent",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreepdumessagestatus/statusstosent"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusStoUnsent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusStoUnsent"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusStoUnsent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreePDUStatusStoUnsent"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreePDUMessageStatus.statusStoUnsent",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreepdumessagestatus/statusstounsent"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusAll",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusRecRead",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusRecUnread",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusStoSent"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOBluetoothHandsFreePDUStatusStoUnsent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreePDUStatusStoUnsent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusAll",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusRecRead",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusRecUnread",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreePDUMessageStatus/statusStoSent"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "IOBluetoothHandsFreePDUStatusStoUnsent"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreePDUMessageStatus~1statusRecRead/title",
          "value": "IOBluetoothHandsFreePDUStatusRecRead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreePDUMessageStatus~1statusRecRead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreePDUStatusRecRead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreePDUMessageStatus~1statusAll/title",
          "value": "IOBluetoothHandsFreePDUStatusAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreePDUMessageStatus~1statusAll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreePDUStatusAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreePDUMessageStatus~1statusStoUnsent/title",
          "value": "IOBluetoothHandsFreePDUStatusStoUnsent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreePDUMessageStatus~1statusStoUnsent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreePDUStatusStoUnsent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreePDUMessageStatus/title",
          "value": "IOBluetoothHandsFreePDUMessageStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreePDUMessageStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreePDUMessageStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreePDUMessageStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreePDUMessageStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreePDUMessageStatus~1statusStoSent/title",
          "value": "IOBluetoothHandsFreePDUStatusStoSent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreePDUMessageStatus~1statusStoSent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreePDUStatusStoSent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreePDUMessageStatus~1statusRecUnread/title",
          "value": "IOBluetoothHandsFreePDUStatusRecUnread"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreePDUMessageStatus~1statusRecUnread/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreePDUStatusRecUnread"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothhandsfreepdumessagestatus/statusstounsent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothhandsfreepdumessagestatus/statusstounsent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
