{
  "abstract": [
    {
      "text": "Perform any required actions after a live broadcast is resumed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.replaykit/documentation/ReplayKit",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastResumed()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)RPBroadcastSampleHandler(im)broadcastResumed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "broadcastResumed"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "ReplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "broadcastResumed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "broadcastResumed()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "broadcastResumed"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "ReplayKit calls this method when the the broadcasting app calls its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController/resumeBroadcast()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit": {
      "abstract": [
        {
          "text": "Record or stream video from the screen, and audio from the app and microphone.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ReplayKit",
      "type": "topic",
      "url": "/documentation/replaykit"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPApplicationInfoBundleIdentifierKey": {
      "abstract": [
        {
          "text": "The key to retrieve the app’s bundle identifier from the user-information dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPApplicationInfoBundleIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPApplicationInfoBundleIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPApplicationInfoBundleIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "RPApplicationInfoBundleIdentifierKey",
      "type": "topic",
      "url": "/documentation/replaykit/rpapplicationinfobundleidentifierkey"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController/resumeBroadcast()": {
      "abstract": [
        {
          "text": "Resumes a paused broadcast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resumeBroadcast"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastController/resumeBroadcast()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resumeBroadcast"
        }
      ],
      "role": "symbol",
      "title": "resumeBroadcast()",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastcontroller/resumebroadcast()"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler": {
      "abstract": [
        {
          "text": "An object that processes buffer objects as received from ReplayKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPBroadcastSampleHandler"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPBroadcastSampleHandler"
        }
      ],
      "role": "symbol",
      "title": "RPBroadcastSampleHandler",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastsamplehandler"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastAnnotated(withApplicationInfo:)": {
      "abstract": [
        {
          "text": "Perform any required actions after starting a live broadcast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "broadcastAnnotated"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withApplicationInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastAnnotated(withApplicationInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "broadcastAnnotatedWithApplicationInfo:"
        }
      ],
      "role": "symbol",
      "title": "broadcastAnnotated(withApplicationInfo:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastsamplehandler/broadcastannotated(withapplicationinfo:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastFinished()": {
      "abstract": [
        {
          "text": "Perform any required actions after a live broadcast is finished.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "broadcastFinished"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastFinished()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "broadcastFinished"
        }
      ],
      "role": "symbol",
      "title": "broadcastFinished()",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastsamplehandler/broadcastfinished()"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastPaused()": {
      "abstract": [
        {
          "text": "Perform any required actions after a live broadcast is paused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "broadcastPaused"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastPaused()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "broadcastPaused"
        }
      ],
      "role": "symbol",
      "title": "broadcastPaused()",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastsamplehandler/broadcastpaused()"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastResumed()": {
      "abstract": [
        {
          "text": "Perform any required actions after a live broadcast is resumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "broadcastResumed"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastResumed()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "broadcastResumed"
        }
      ],
      "role": "symbol",
      "title": "broadcastResumed()",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastsamplehandler/broadcastresumed()"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastStarted(withSetupInfo:)": {
      "abstract": [
        {
          "text": "Perform any required actions after starting a live broadcast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "broadcastStarted"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withSetupInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastStarted(withSetupInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "broadcastStartedWithSetupInfo:"
        }
      ],
      "role": "symbol",
      "title": "broadcastStarted(withSetupInfo:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastsamplehandler/broadcaststarted(withsetupinfo:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/finishBroadcastWithError(_:)": {
      "abstract": [
        {
          "text": "Stops the broadcast and passes an error back to the broadcasting app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishBroadcastWithError"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/finishBroadcastWithError(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishBroadcastWithError:"
        }
      ],
      "role": "symbol",
      "title": "finishBroadcastWithError(_:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastsamplehandler/finishbroadcastwitherror(_:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/processSampleBuffer(_:with:)": {
      "abstract": [
        {
          "text": "Processes video and audio data as it becomes available during a live broadcast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "processSampleBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@RPSampleBufferType",
          "text": "RPSampleBufferType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/processSampleBuffer(_:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "processSampleBuffer:withType:"
        }
      ],
      "role": "symbol",
      "title": "processSampleBuffer(_:with:)",
      "type": "topic",
      "url": "/documentation/replaykit/rpbroadcastsamplehandler/processsamplebuffer(_:with:)"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPVideoSampleOrientationKey": {
      "abstract": [
        {
          "text": "The sample attachment key that describes the video orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPVideoSampleOrientationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPVideoSampleOrientationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPVideoSampleOrientationKey"
        }
      ],
      "role": "symbol",
      "title": "RPVideoSampleOrientationKey",
      "type": "topic",
      "url": "/documentation/replaykit/rpvideosampleorientationkey"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-Sample-Buffer-Clips",
      "generated": true,
      "identifiers": [
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastStarted(withSetupInfo:)",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastPaused()",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastFinished()",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastAnnotated(withApplicationInfo:)",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPApplicationInfoBundleIdentifierKey",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/processSampleBuffer(_:with:)",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPVideoSampleOrientationKey",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/finishBroadcastWithError(_:)"
      ],
      "title": "Handling Sample Buffer Clips"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "broadcastResumed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "broadcastResumed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.replaykit/documentation/ReplayKit",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-Sample-Buffer-Clips",
              "generated": true,
              "identifiers": [
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastStarted(withSetupInfo:)",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastPaused()",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastFinished()",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/broadcastAnnotated(withApplicationInfo:)",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPApplicationInfoBundleIdentifierKey",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/processSampleBuffer(_:with:)",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPVideoSampleOrientationKey",
                "doc://com.apple.replaykit/documentation/ReplayKit/RPBroadcastSampleHandler/finishBroadcastWithError(_:)"
              ],
              "title": "Handling Sample Buffer Clips"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "broadcastResumed"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPVideoSampleOrientationKey/title",
          "value": "RPVideoSampleOrientationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPVideoSampleOrientationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPVideoSampleOrientationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler/title",
          "value": "RPBroadcastSampleHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastSampleHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPBroadcastSampleHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler~1processSampleBuffer(_:with:)/title",
          "value": "processSampleBuffer:withType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler~1processSampleBuffer(_:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "processSampleBuffer:withType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPApplicationInfoBundleIdentifierKey/title",
          "value": "RPApplicationInfoBundleIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPApplicationInfoBundleIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPApplicationInfoBundleIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler~1finishBroadcastWithError(_:)/title",
          "value": "finishBroadcastWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler~1finishBroadcastWithError(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishBroadcastWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler~1broadcastPaused()/title",
          "value": "broadcastPaused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler~1broadcastPaused()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "broadcastPaused"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler~1broadcastFinished()/title",
          "value": "broadcastFinished"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler~1broadcastFinished()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "broadcastFinished"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler~1broadcastAnnotated(withApplicationInfo:)/title",
          "value": "broadcastAnnotatedWithApplicationInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler~1broadcastAnnotated(withApplicationInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "broadcastAnnotatedWithApplicationInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler~1broadcastStarted(withSetupInfo:)/title",
          "value": "broadcastStartedWithSetupInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler~1broadcastStarted(withSetupInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "broadcastStartedWithSetupInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler~1broadcastResumed()/title",
          "value": "broadcastResumed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastSampleHandler~1broadcastResumed()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "broadcastResumed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastController~1resumeBroadcast()/title",
          "value": "resumeBroadcast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPBroadcastController~1resumeBroadcast()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resumeBroadcast"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/replaykit/rpbroadcastsamplehandler/broadcastresumed()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/replaykit/rpbroadcastsamplehandler/broadcastresumed()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
