{
  "abstract": [
    {
      "text": "Key to retrieve the group’s persistent ID.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the localIdentifier property on a PHAssetCollection from the Photos framework instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyPersistentID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@ALAssetsGroupPropertyPersistentID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ALAssetsGroupPropertyPersistentID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Assets Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ALAssetsGroupPropertyPersistentID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "4.0",
        "message": "Use the localIdentifier property on a PHAssetCollection from the Photos framework instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "4.0",
        "message": "Use the localIdentifier property on a PHAssetCollection from the Photos framework instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use the localIdentifier property on a PHAssetCollection from the Photos framework instead",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "ALAssetsGroupPropertyPersistentID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ALAssetsGroupPropertyPersistentID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The corresponding value is an ",
              "type": "text"
            },
            {
              "code": "NSString",
              "type": "codeVoice"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary": {
      "abstract": [
        {
          "text": "Access the assets in a user’s media library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Assets Library",
      "type": "topic",
      "url": "/documentation/assetslibrary"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryDeletedAssetGroupsKey": {
      "abstract": [
        {
          "text": "Value is a set of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects identifying the asset groups that were deleted.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetLibraryDeletedAssetGroupsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryDeletedAssetGroupsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetLibraryDeletedAssetGroupsKey"
        }
      ],
      "role": "symbol",
      "title": "ALAssetLibraryDeletedAssetGroupsKey",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetlibrarydeletedassetgroupskey"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryInsertedAssetGroupsKey": {
      "abstract": [
        {
          "text": "Value is a set of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects identifying the assets that were inserted.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetLibraryInsertedAssetGroupsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryInsertedAssetGroupsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetLibraryInsertedAssetGroupsKey"
        }
      ],
      "role": "symbol",
      "title": "ALAssetLibraryInsertedAssetGroupsKey",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetlibraryinsertedassetgroupskey"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetGroupsKey": {
      "abstract": [
        {
          "text": "Value is a set of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects identifying the asset groups that were updated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetLibraryUpdatedAssetGroupsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetGroupsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetLibraryUpdatedAssetGroupsKey"
        }
      ],
      "role": "symbol",
      "title": "ALAssetLibraryUpdatedAssetGroupsKey",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetlibraryupdatedassetgroupskey"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetsKey": {
      "abstract": [
        {
          "text": "Value is a set of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects identifying the assets that were updated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetLibraryUpdatedAssetsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetLibraryUpdatedAssetsKey"
        }
      ],
      "role": "symbol",
      "title": "ALAssetLibraryUpdatedAssetsKey",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetlibraryupdatedassetskey"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyAssetURL": {
      "abstract": [
        {
          "text": "The key to retrieve a URL identifier for the asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyAssetURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyAssetURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyAssetURL"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyAssetURL",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertyasseturl"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDate": {
      "abstract": [
        {
          "text": "The key to retrieve the creation date of the asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyDate"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyDate",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertydate"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDuration": {
      "abstract": [
        {
          "text": "The key to retrieve the play time duration of a video asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyDuration"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyDuration",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertyduration"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyLocation": {
      "abstract": [
        {
          "text": "The key to retrieve the location information of the asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyLocation"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyLocation",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertylocation"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyOrientation": {
      "abstract": [
        {
          "text": "The key to retrieve the orientation of the asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyOrientation"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyOrientation",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertyorientation"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyRepresentations": {
      "abstract": [
        {
          "text": "The key to retrieve the representations available for a given asset (for example RAW, JPEG).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyRepresentations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyRepresentations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyRepresentations"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyRepresentations",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertyrepresentations"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyType": {
      "abstract": [
        {
          "text": "A key to retrieve the type of the asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyType"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyType",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertytype"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyURLs": {
      "abstract": [
        {
          "text": "The key to retrieve a dictionary that maps asset representations UTIs to URLs that uniquely identify the asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyURLs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyURLs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyURLs"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyURLs",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertyurls"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypePhoto": {
      "abstract": [
        {
          "text": "Specifies that the asset is a photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetTypePhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetTypePhoto"
        }
      ],
      "role": "symbol",
      "title": "ALAssetTypePhoto",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassettypephoto"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeUnknown": {
      "abstract": [
        {
          "text": "Specifies that the asset’s type cannot be determined.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetTypeUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "ALAssetTypeUnknown",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassettypeunknown"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeVideo": {
      "abstract": [
        {
          "text": "Specifies that the asset is a video.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetTypeVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetTypeVideo"
        }
      ],
      "role": "symbol",
      "title": "ALAssetTypeVideo",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassettypevideo"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyPersistentID": {
      "abstract": [
        {
          "text": "Key to retrieve the group’s persistent ID.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsGroupPropertyPersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyPersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsGroupPropertyPersistentID"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsGroupPropertyPersistentID",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetsgrouppropertypersistentid"
    },
    "doc://com.apple.documentation/documentation/foundation/nsurl": {
      "abstract": [
        {
          "text": "An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSURL"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSURL",
      "type": "topic",
      "url": "/documentation/foundation/nsurl"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryDeletedAssetGroupsKey",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryInsertedAssetGroupsKey",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetGroupsKey",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetsKey",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyAssetURL",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDate",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDuration",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyLocation",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyOrientation",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyRepresentations",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyType",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyURLs",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypePhoto",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeUnknown",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeVideo"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ALAssetsGroupPropertyPersistentID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsGroupPropertyPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryDeletedAssetGroupsKey",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryInsertedAssetGroupsKey",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetGroupsKey",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetsKey",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyAssetURL",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDate",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDuration",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyLocation",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyOrientation",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyRepresentations",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyType",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyURLs",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypePhoto",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeUnknown",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeVideo"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ALAssetsGroupPropertyPersistentID"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use the localIdentifier property on a PHAssetCollection from the Photos framework instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyAssetURL/title",
          "value": "ALAssetPropertyAssetURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyAssetURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyAssetURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyDuration/title",
          "value": "ALAssetPropertyDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyRepresentations/title",
          "value": "ALAssetPropertyRepresentations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyRepresentations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyRepresentations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyDate/title",
          "value": "ALAssetPropertyDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryDeletedAssetGroupsKey/title",
          "value": "ALAssetLibraryDeletedAssetGroupsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryDeletedAssetGroupsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetLibraryDeletedAssetGroupsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetTypeVideo/title",
          "value": "ALAssetTypeVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetTypeVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetTypeVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyOrientation/title",
          "value": "ALAssetPropertyOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetTypeUnknown/title",
          "value": "ALAssetTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetTypeUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyLocation/title",
          "value": "ALAssetPropertyLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryUpdatedAssetsKey/title",
          "value": "ALAssetLibraryUpdatedAssetsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryUpdatedAssetsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetLibraryUpdatedAssetsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyType/title",
          "value": "ALAssetPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetTypePhoto/title",
          "value": "ALAssetTypePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetTypePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetTypePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurl/abstract",
          "value": [
            {
              "text": "An object that represents the location of a resource, such as an item on a remote server or the path to a local file. ",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryUpdatedAssetGroupsKey/title",
          "value": "ALAssetLibraryUpdatedAssetGroupsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryUpdatedAssetGroupsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetLibraryUpdatedAssetGroupsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryInsertedAssetGroupsKey/title",
          "value": "ALAssetLibraryInsertedAssetGroupsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryInsertedAssetGroupsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetLibraryInsertedAssetGroupsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupPropertyPersistentID/title",
          "value": "ALAssetsGroupPropertyPersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupPropertyPersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsGroupPropertyPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyURLs/title",
          "value": "ALAssetPropertyURLs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyURLs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyURLs"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/assetslibrary/alassetsgrouppropertypersistentid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/assetslibrary/alassetsgrouppropertypersistentid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
