{
  "abstract": [
    {
      "text": "Signature for the block executed if the user does not grant access to the caller to access the data managed by the framework.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the Photos framework instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryAccessFailureBlock"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@ALAssetsLibraryAccessFailureBlock",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ALAssetsLibraryAccessFailureBlock"
      }
    ],
    "modules": [
      {
        "name": "Assets Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ALAssetsLibraryAccessFailureBlock"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "4.0",
        "message": "Use the Photos framework instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "4.0",
        "message": "Use the Photos framework instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use the Photos framework instead",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "ALAssetsLibraryAccessFailureBlock"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryAccessFailureBlock"
            },
            {
              "kind": "text",
              "text": " = ((any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The block parameter is defined as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An error object that describes why access to the library failed.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "error",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "This block type is used by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/asset(for:resultBlock:failureBlock:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/enumerateGroups(withTypes:using:failureBlock:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary": {
      "abstract": [
        {
          "text": "Access the assets in a user’s media library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Assets Library",
      "type": "topic",
      "url": "/documentation/assetslibrary"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetOrientation": {
      "abstract": [
        {
          "text": "Constants to indicate the orientation of an asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetOrientation"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetOrientation"
        }
      ],
      "role": "symbol",
      "title": "ALAssetOrientation",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetorientation"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupType": {
      "abstract": [
        {
          "text": "A bitfield to identify types of asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsGroupType"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsGroupType"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsGroupType",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetsgrouptype"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/asset(for:resultBlock:failureBlock:)": {
      "abstract": [
        {
          "text": "Invokes a given block passing as a parameter an asset identified by a specified file URL.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "resultBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ALAssetsLibraryAssetForURLResultBlock",
          "text": "ALAssetsLibraryAssetForURLResultBlock"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "failureBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ALAssetsLibraryAccessFailureBlock",
          "text": "ALAssetsLibraryAccessFailureBlock"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/asset(for:resultBlock:failureBlock:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "assetForURL:resultBlock:failureBlock:"
        }
      ],
      "role": "symbol",
      "title": "asset(for:resultBlock:failureBlock:)",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrary/asset(for:resultblock:failureblock:)"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/enumerateGroups(withTypes:using:failureBlock:)": {
      "abstract": [
        {
          "text": "Invokes a given block passing as a parameter each of the asset groups that match the given asset group type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerateGroups"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ALAssetsGroupType",
          "text": "ALAssetsGroupType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ALAssetsLibraryGroupsEnumerationResultsBlock",
          "text": "ALAssetsLibraryGroupsEnumerationResultsBlock"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "failureBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ALAssetsLibraryAccessFailureBlock",
          "text": "ALAssetsLibraryAccessFailureBlock"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/enumerateGroups(withTypes:using:failureBlock:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateGroupsWithTypes:usingBlock:failureBlock:"
        }
      ],
      "role": "symbol",
      "title": "enumerateGroups(withTypes:using:failureBlock:)",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrary/enumerategroups(withtypes:using:failureblock:)"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/writeImage(toSavedPhotosAlbum:orientation:completionBlock:)": {
      "abstract": [
        {
          "text": "Saves a given image to the Saved Photos album.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toSavedPhotosAlbum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ALAssetOrientation",
          "text": "ALAssetOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ALAssetsLibraryWriteImageCompletionBlock",
          "text": "ALAssetsLibraryWriteImageCompletionBlock"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/writeImage(toSavedPhotosAlbum:orientation:completionBlock:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeImageToSavedPhotosAlbum:orientation:completionBlock:"
        }
      ],
      "role": "symbol",
      "title": "writeImage(toSavedPhotosAlbum:orientation:completionBlock:)",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrary/writeimage(tosavedphotosalbum:orientation:completionblock:)"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/writeVideoAtPath(toSavedPhotosAlbum:completionBlock:)": {
      "abstract": [
        {
          "text": "Saves a video identified by a given URL to the Saved Photos album.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeVideoAtPath"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toSavedPhotosAlbum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "completionBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ALAssetsLibraryWriteVideoCompletionBlock",
          "text": "ALAssetsLibraryWriteVideoCompletionBlock"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/writeVideoAtPath(toSavedPhotosAlbum:completionBlock:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeVideoAtPathToSavedPhotosAlbum:completionBlock:"
        }
      ],
      "role": "symbol",
      "title": "writeVideoAtPath(toSavedPhotosAlbum:completionBlock:)",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrary/writevideoatpath(tosavedphotosalbum:completionblock:)"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryAccessFailureBlock": {
      "abstract": [
        {
          "text": "Signature for the block executed if the user does not grant access to the caller to access the data managed by the framework.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryAccessFailureBlock"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryAccessFailureBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryAccessFailureBlock"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsLibraryAccessFailureBlock",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibraryaccessfailureblock"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryAssetForURLResultBlock": {
      "abstract": [
        {
          "text": "Signature for the block executed if the user has granted access to the caller to access the data managed by the framework in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/asset(for:resultBlock:failureBlock:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryAssetForURLResultBlock"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryAssetForURLResultBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryAssetForURLResultBlock"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsLibraryAssetForURLResultBlock",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibraryassetforurlresultblock"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryChangedNotification": {
      "abstract": [
        {
          "text": "Sent when the contents of the assets library have changed from under the app that is using the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryChangedNotification"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryChangedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "ALAssetsLibraryChangedNotification",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrarychangednotification"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupResultBlock": {
      "abstract": [
        {
          "text": "Signature for the block executed if the user grants access to the caller to access the data managed by the framework..",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryGroupResultBlock"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupResultBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryGroupResultBlock"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsLibraryGroupResultBlock",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrarygroupresultblock"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupsEnumerationResultsBlock": {
      "abstract": [
        {
          "text": "Signature for the block executed when a match is found during enumeration using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/enumerateGroups(withTypes:using:failureBlock:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryGroupsEnumerationResultsBlock"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupsEnumerationResultsBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryGroupsEnumerationResultsBlock"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsLibraryGroupsEnumerationResultsBlock",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrarygroupsenumerationresultsblock"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteImageCompletionBlock": {
      "abstract": [
        {
          "text": "Signature for the block executed when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/writeImage(toSavedPhotosAlbum:orientation:completionBlock:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " completes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryWriteImageCompletionBlock"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteImageCompletionBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryWriteImageCompletionBlock"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsLibraryWriteImageCompletionBlock",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrarywriteimagecompletionblock"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteVideoCompletionBlock": {
      "abstract": [
        {
          "text": "Signature for the block executed when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/writeVideoAtPath(toSavedPhotosAlbum:completionBlock:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " completes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryWriteVideoCompletionBlock"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteVideoCompletionBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryWriteVideoCompletionBlock"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsLibraryWriteVideoCompletionBlock",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrarywritevideocompletionblock"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus": {
      "abstract": [
        {
          "text": "Constants to indicate authorization status.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "ALAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/assetslibrary/alauthorizationstatus"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-codes": {
      "abstract": [
        {
          "text": "AssetsLibrary-related error codes",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Codes",
      "type": "topic",
      "url": "/documentation/assetslibrary/error-codes"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-domain": {
      "abstract": [
        {
          "text": "Constant for the AssetsLibrary domain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-domain",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Domain",
      "type": "topic",
      "url": "/documentation/assetslibrary/error-domain"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/notification-keys": {
      "abstract": [
        {
          "text": "Keys used to get values from the user information dictionary of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryChangedNotification",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " notification.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/notification-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Notification Keys",
      "type": "topic",
      "url": "/documentation/assetslibrary/notification-keys"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/types-of-asset": {
      "abstract": [
        {
          "text": "Constants to identify types of asset.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/types-of-asset",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Types of Asset",
      "type": "topic",
      "url": "/documentation/assetslibrary/types-of-asset"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupType",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/types-of-asset",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetOrientation",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupsEnumerationResultsBlock",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryAssetForURLResultBlock",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteImageCompletionBlock",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteVideoCompletionBlock",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupResultBlock",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/notification-keys",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-domain",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-codes"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ALAssetsLibraryAccessFailureBlock"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryAccessFailureBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryAccessFailureBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupType",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/types-of-asset",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetOrientation",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupsEnumerationResultsBlock",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryAssetForURLResultBlock",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteImageCompletionBlock",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteVideoCompletionBlock",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupResultBlock",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/notification-keys",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-domain",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-codes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFv(#*$objc(cs)NSError)",
                    "text": "void (^)(NSError *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ALAssetsLibraryAccessFailureBlock"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use the Photos framework instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryAccessFailureBlock/title",
          "value": "ALAssetsLibraryAccessFailureBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryAccessFailureBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryAccessFailureBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryAccessFailureBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryAccessFailureBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1enumerateGroups(withTypes:using:failureBlock:)/title",
          "value": "enumerateGroupsWithTypes:usingBlock:failureBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1enumerateGroups(withTypes:using:failureBlock:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enumerateGroupsWithTypes:usingBlock:failureBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1writeImage(toSavedPhotosAlbum:orientation:completionBlock:)/title",
          "value": "writeImageToSavedPhotosAlbum:orientation:completionBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1writeImage(toSavedPhotosAlbum:orientation:completionBlock:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeImageToSavedPhotosAlbum:orientation:completionBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryWriteImageCompletionBlock/title",
          "value": "ALAssetsLibraryWriteImageCompletionBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryWriteImageCompletionBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryWriteImageCompletionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryWriteImageCompletionBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryWriteImageCompletionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryGroupsEnumerationResultsBlock/title",
          "value": "ALAssetsLibraryGroupsEnumerationResultsBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryGroupsEnumerationResultsBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryGroupsEnumerationResultsBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryGroupsEnumerationResultsBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryGroupsEnumerationResultsBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryAssetForURLResultBlock/title",
          "value": "ALAssetsLibraryAssetForURLResultBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryAssetForURLResultBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryAssetForURLResultBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryAssetForURLResultBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryAssetForURLResultBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1writeVideoAtPath(toSavedPhotosAlbum:completionBlock:)/title",
          "value": "writeVideoAtPathToSavedPhotosAlbum:completionBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1writeVideoAtPath(toSavedPhotosAlbum:completionBlock:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeVideoAtPathToSavedPhotosAlbum:completionBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryWriteVideoCompletionBlock/title",
          "value": "ALAssetsLibraryWriteVideoCompletionBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryWriteVideoCompletionBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryWriteVideoCompletionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryWriteVideoCompletionBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryWriteVideoCompletionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetOrientation/title",
          "value": "ALAssetOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1asset(for:resultBlock:failureBlock:)/title",
          "value": "assetForURL:resultBlock:failureBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1asset(for:resultBlock:failureBlock:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "assetForURL:resultBlock:failureBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupType/title",
          "value": "ALAssetsGroupType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsGroupType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsGroupType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus/title",
          "value": "ALAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryGroupResultBlock/title",
          "value": "ALAssetsLibraryGroupResultBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryGroupResultBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryGroupResultBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryGroupResultBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryGroupResultBlock"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/assetslibrary/alassetslibraryaccessfailureblock"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/assetslibrary/alassetslibraryaccessfailureblock"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
