{
  "abstract": [
    {
      "text": "Constants to indicate authorization status.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use PHAuthorizationStatus in the Photos framework instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ALAuthorizationStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ALAuthorizationStatus"
      }
    ],
    "modules": [
      {
        "name": "Assets Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ALAuthorizationStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "6.0",
        "message": "Use PHAuthorizationStatus in the Photos framework instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "6.0",
        "message": "Use PHAuthorizationStatus in the Photos framework instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use PHAuthorizationStatus in the Photos framework instead",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ALAuthorizationStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ALAuthorizationStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary": {
      "abstract": [
        {
          "text": "Access the assets in a user’s media library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Assets Library",
      "type": "topic",
      "url": "/documentation/assetslibrary"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetOrientation": {
      "abstract": [
        {
          "text": "Constants to indicate the orientation of an asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetOrientation"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetOrientation"
        }
      ],
      "role": "symbol",
      "title": "ALAssetOrientation",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetorientation"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupType": {
      "abstract": [
        {
          "text": "A bitfield to identify types of asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsGroupType"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsGroupType"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsGroupType",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetsgrouptype"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/asset(for:resultBlock:failureBlock:)": {
      "abstract": [
        {
          "text": "Invokes a given block passing as a parameter an asset identified by a specified file URL.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "resultBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ALAssetsLibraryAssetForURLResultBlock",
          "text": "ALAssetsLibraryAssetForURLResultBlock"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "failureBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ALAssetsLibraryAccessFailureBlock",
          "text": "ALAssetsLibraryAccessFailureBlock"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/asset(for:resultBlock:failureBlock:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "assetForURL:resultBlock:failureBlock:"
        }
      ],
      "role": "symbol",
      "title": "asset(for:resultBlock:failureBlock:)",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrary/asset(for:resultblock:failureblock:)"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/enumerateGroups(withTypes:using:failureBlock:)": {
      "abstract": [
        {
          "text": "Invokes a given block passing as a parameter each of the asset groups that match the given asset group type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerateGroups"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ALAssetsGroupType",
          "text": "ALAssetsGroupType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ALAssetsLibraryGroupsEnumerationResultsBlock",
          "text": "ALAssetsLibraryGroupsEnumerationResultsBlock"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "failureBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ALAssetsLibraryAccessFailureBlock",
          "text": "ALAssetsLibraryAccessFailureBlock"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/enumerateGroups(withTypes:using:failureBlock:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateGroupsWithTypes:usingBlock:failureBlock:"
        }
      ],
      "role": "symbol",
      "title": "enumerateGroups(withTypes:using:failureBlock:)",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrary/enumerategroups(withtypes:using:failureblock:)"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/writeImage(toSavedPhotosAlbum:orientation:completionBlock:)": {
      "abstract": [
        {
          "text": "Saves a given image to the Saved Photos album.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toSavedPhotosAlbum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ALAssetOrientation",
          "text": "ALAssetOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ALAssetsLibraryWriteImageCompletionBlock",
          "text": "ALAssetsLibraryWriteImageCompletionBlock"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/writeImage(toSavedPhotosAlbum:orientation:completionBlock:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeImageToSavedPhotosAlbum:orientation:completionBlock:"
        }
      ],
      "role": "symbol",
      "title": "writeImage(toSavedPhotosAlbum:orientation:completionBlock:)",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrary/writeimage(tosavedphotosalbum:orientation:completionblock:)"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/writeVideoAtPath(toSavedPhotosAlbum:completionBlock:)": {
      "abstract": [
        {
          "text": "Saves a video identified by a given URL to the Saved Photos album.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeVideoAtPath"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toSavedPhotosAlbum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "completionBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ALAssetsLibraryWriteVideoCompletionBlock",
          "text": "ALAssetsLibraryWriteVideoCompletionBlock"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/writeVideoAtPath(toSavedPhotosAlbum:completionBlock:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeVideoAtPathToSavedPhotosAlbum:completionBlock:"
        }
      ],
      "role": "symbol",
      "title": "writeVideoAtPath(toSavedPhotosAlbum:completionBlock:)",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrary/writevideoatpath(tosavedphotosalbum:completionblock:)"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryAccessFailureBlock": {
      "abstract": [
        {
          "text": "Signature for the block executed if the user does not grant access to the caller to access the data managed by the framework.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryAccessFailureBlock"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryAccessFailureBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryAccessFailureBlock"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsLibraryAccessFailureBlock",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibraryaccessfailureblock"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryAssetForURLResultBlock": {
      "abstract": [
        {
          "text": "Signature for the block executed if the user has granted access to the caller to access the data managed by the framework in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/asset(for:resultBlock:failureBlock:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryAssetForURLResultBlock"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryAssetForURLResultBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryAssetForURLResultBlock"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsLibraryAssetForURLResultBlock",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibraryassetforurlresultblock"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryChangedNotification": {
      "abstract": [
        {
          "text": "Sent when the contents of the assets library have changed from under the app that is using the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryChangedNotification"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryChangedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "ALAssetsLibraryChangedNotification",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrarychangednotification"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupResultBlock": {
      "abstract": [
        {
          "text": "Signature for the block executed if the user grants access to the caller to access the data managed by the framework..",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryGroupResultBlock"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupResultBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryGroupResultBlock"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsLibraryGroupResultBlock",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrarygroupresultblock"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupsEnumerationResultsBlock": {
      "abstract": [
        {
          "text": "Signature for the block executed when a match is found during enumeration using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/enumerateGroups(withTypes:using:failureBlock:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryGroupsEnumerationResultsBlock"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupsEnumerationResultsBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryGroupsEnumerationResultsBlock"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsLibraryGroupsEnumerationResultsBlock",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrarygroupsenumerationresultsblock"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteImageCompletionBlock": {
      "abstract": [
        {
          "text": "Signature for the block executed when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/writeImage(toSavedPhotosAlbum:orientation:completionBlock:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " completes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryWriteImageCompletionBlock"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteImageCompletionBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryWriteImageCompletionBlock"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsLibraryWriteImageCompletionBlock",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrarywriteimagecompletionblock"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteVideoCompletionBlock": {
      "abstract": [
        {
          "text": "Signature for the block executed when ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibrary/writeVideoAtPath(toSavedPhotosAlbum:completionBlock:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " completes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryWriteVideoCompletionBlock"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteVideoCompletionBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryWriteVideoCompletionBlock"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsLibraryWriteVideoCompletionBlock",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrarywritevideocompletionblock"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus": {
      "abstract": [
        {
          "text": "Constants to indicate authorization status.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "ALAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/assetslibrary/alauthorizationstatus"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/authorized": {
      "abstract": [
        {
          "text": "User has authorized this application to access photos data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorized"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/authorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAuthorizationStatusAuthorized"
        }
      ],
      "role": "symbol",
      "title": "ALAuthorizationStatus.authorized",
      "type": "topic",
      "url": "/documentation/assetslibrary/alauthorizationstatus/authorized"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/denied": {
      "abstract": [
        {
          "text": "User has explicitly denied this application access to photos data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAuthorizationStatusDenied"
        }
      ],
      "role": "symbol",
      "title": "ALAuthorizationStatus.denied",
      "type": "topic",
      "url": "/documentation/assetslibrary/alauthorizationstatus/denied"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/assetslibrary/alauthorizationstatus/init(rawvalue:)"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/notDetermined": {
      "abstract": [
        {
          "text": "User has not yet made a choice with regards to this application.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notDetermined"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/notDetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAuthorizationStatusNotDetermined"
        }
      ],
      "role": "symbol",
      "title": "ALAuthorizationStatus.notDetermined",
      "type": "topic",
      "url": "/documentation/assetslibrary/alauthorizationstatus/notdetermined"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/restricted": {
      "abstract": [
        {
          "text": "This application is not authorized to access photo data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restricted"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/restricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAuthorizationStatusRestricted"
        }
      ],
      "role": "symbol",
      "title": "ALAuthorizationStatus.restricted",
      "type": "topic",
      "url": "/documentation/assetslibrary/alauthorizationstatus/restricted"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-codes": {
      "abstract": [
        {
          "text": "AssetsLibrary-related error codes",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Codes",
      "type": "topic",
      "url": "/documentation/assetslibrary/error-codes"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-domain": {
      "abstract": [
        {
          "text": "Constant for the AssetsLibrary domain.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-domain",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Domain",
      "type": "topic",
      "url": "/documentation/assetslibrary/error-domain"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/notification-keys": {
      "abstract": [
        {
          "text": "Keys used to get values from the user information dictionary of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryChangedNotification",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " notification.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/notification-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Notification Keys",
      "type": "topic",
      "url": "/documentation/assetslibrary/notification-keys"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/types-of-asset": {
      "abstract": [
        {
          "text": "Constants to identify types of asset.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/types-of-asset",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Types of Asset",
      "type": "topic",
      "url": "/documentation/assetslibrary/types-of-asset"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupType",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/types-of-asset",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetOrientation",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupsEnumerationResultsBlock",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryAssetForURLResultBlock",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteImageCompletionBlock",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteVideoCompletionBlock",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryAccessFailureBlock",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupResultBlock",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/notification-keys",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-domain",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-codes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/notDetermined",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/restricted",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/denied",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/authorized"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ALAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/notDetermined",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/restricted",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/denied",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus/authorized"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupType",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/types-of-asset",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetOrientation",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupsEnumerationResultsBlock",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryAssetForURLResultBlock",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteImageCompletionBlock",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryWriteVideoCompletionBlock",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryAccessFailureBlock",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryGroupResultBlock",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/notification-keys",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-domain",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-codes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ALAuthorizationStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use PHAuthorizationStatus in the Photos framework instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus~1authorized/title",
          "value": "ALAuthorizationStatusAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus~1authorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAuthorizationStatusAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1enumerateGroups(withTypes:using:failureBlock:)/title",
          "value": "enumerateGroupsWithTypes:usingBlock:failureBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1enumerateGroups(withTypes:using:failureBlock:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enumerateGroupsWithTypes:usingBlock:failureBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus~1notDetermined/title",
          "value": "ALAuthorizationStatusNotDetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus~1notDetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAuthorizationStatusNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1writeVideoAtPath(toSavedPhotosAlbum:completionBlock:)/title",
          "value": "writeVideoAtPathToSavedPhotosAlbum:completionBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1writeVideoAtPath(toSavedPhotosAlbum:completionBlock:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeVideoAtPathToSavedPhotosAlbum:completionBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryAccessFailureBlock/title",
          "value": "ALAssetsLibraryAccessFailureBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryAccessFailureBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryAccessFailureBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryAccessFailureBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryAccessFailureBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1asset(for:resultBlock:failureBlock:)/title",
          "value": "assetForURL:resultBlock:failureBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1asset(for:resultBlock:failureBlock:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "assetForURL:resultBlock:failureBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryWriteImageCompletionBlock/title",
          "value": "ALAssetsLibraryWriteImageCompletionBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryWriteImageCompletionBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryWriteImageCompletionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryWriteImageCompletionBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryWriteImageCompletionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1writeImage(toSavedPhotosAlbum:orientation:completionBlock:)/title",
          "value": "writeImageToSavedPhotosAlbum:orientation:completionBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibrary~1writeImage(toSavedPhotosAlbum:orientation:completionBlock:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeImageToSavedPhotosAlbum:orientation:completionBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetOrientation/title",
          "value": "ALAssetOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryWriteVideoCompletionBlock/title",
          "value": "ALAssetsLibraryWriteVideoCompletionBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryWriteVideoCompletionBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryWriteVideoCompletionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryWriteVideoCompletionBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryWriteVideoCompletionBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus~1denied/title",
          "value": "ALAuthorizationStatusDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAuthorizationStatusDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryGroupResultBlock/title",
          "value": "ALAssetsLibraryGroupResultBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryGroupResultBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryGroupResultBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryGroupResultBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryGroupResultBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryAssetForURLResultBlock/title",
          "value": "ALAssetsLibraryAssetForURLResultBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryAssetForURLResultBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryAssetForURLResultBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryAssetForURLResultBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryAssetForURLResultBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus/title",
          "value": "ALAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupType/title",
          "value": "ALAssetsGroupType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsGroupType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsGroupType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryGroupsEnumerationResultsBlock/title",
          "value": "ALAssetsLibraryGroupsEnumerationResultsBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryGroupsEnumerationResultsBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryGroupsEnumerationResultsBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryGroupsEnumerationResultsBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryGroupsEnumerationResultsBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus~1restricted/title",
          "value": "ALAuthorizationStatusRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus~1restricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAuthorizationStatusRestricted"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/assetslibrary/alauthorizationstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/assetslibrary/alauthorizationstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
