{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Assets Library"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AssetsLibrary Constants"
  },
  "references": {
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary": {
      "abstract": [
        {
          "text": "Access the assets in a user’s media library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Assets Library",
      "type": "topic",
      "url": "/documentation/assetslibrary"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAsset/value(forProperty:)": {
      "abstract": [
        {
          "text": "Returns the value for a given property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAsset/value(forProperty:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueForProperty:"
        }
      ],
      "role": "symbol",
      "title": "value(forProperty:)",
      "type": "topic",
      "url": "/documentation/assetslibrary/alasset/value(forproperty:)"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryDeletedAssetGroupsKey": {
      "abstract": [
        {
          "text": "Value is a set of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects identifying the asset groups that were deleted.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetLibraryDeletedAssetGroupsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryDeletedAssetGroupsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetLibraryDeletedAssetGroupsKey"
        }
      ],
      "role": "symbol",
      "title": "ALAssetLibraryDeletedAssetGroupsKey",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetlibrarydeletedassetgroupskey"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryInsertedAssetGroupsKey": {
      "abstract": [
        {
          "text": "Value is a set of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects identifying the assets that were inserted.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetLibraryInsertedAssetGroupsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryInsertedAssetGroupsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetLibraryInsertedAssetGroupsKey"
        }
      ],
      "role": "symbol",
      "title": "ALAssetLibraryInsertedAssetGroupsKey",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetlibraryinsertedassetgroupskey"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetGroupsKey": {
      "abstract": [
        {
          "text": "Value is a set of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects identifying the asset groups that were updated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetLibraryUpdatedAssetGroupsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetGroupsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetLibraryUpdatedAssetGroupsKey"
        }
      ],
      "role": "symbol",
      "title": "ALAssetLibraryUpdatedAssetGroupsKey",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetlibraryupdatedassetgroupskey"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetsKey": {
      "abstract": [
        {
          "text": "Value is a set of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects identifying the assets that were updated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetLibraryUpdatedAssetsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetLibraryUpdatedAssetsKey"
        }
      ],
      "role": "symbol",
      "title": "ALAssetLibraryUpdatedAssetsKey",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetlibraryupdatedassetskey"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyAssetURL": {
      "abstract": [
        {
          "text": "The key to retrieve a URL identifier for the asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyAssetURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyAssetURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyAssetURL"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyAssetURL",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertyasseturl"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDate": {
      "abstract": [
        {
          "text": "The key to retrieve the creation date of the asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyDate"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyDate",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertydate"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDuration": {
      "abstract": [
        {
          "text": "The key to retrieve the play time duration of a video asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyDuration"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyDuration",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertyduration"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyLocation": {
      "abstract": [
        {
          "text": "The key to retrieve the location information of the asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyLocation"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyLocation",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertylocation"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyOrientation": {
      "abstract": [
        {
          "text": "The key to retrieve the orientation of the asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyOrientation"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyOrientation",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertyorientation"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyRepresentations": {
      "abstract": [
        {
          "text": "The key to retrieve the representations available for a given asset (for example RAW, JPEG).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyRepresentations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyRepresentations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyRepresentations"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyRepresentations",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertyrepresentations"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyType": {
      "abstract": [
        {
          "text": "A key to retrieve the type of the asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyType"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyType",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertytype"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyURLs": {
      "abstract": [
        {
          "text": "The key to retrieve a dictionary that maps asset representations UTIs to URLs that uniquely identify the asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetPropertyURLs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyURLs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetPropertyURLs"
        }
      ],
      "role": "symbol",
      "title": "ALAssetPropertyURLs",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetpropertyurls"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypePhoto": {
      "abstract": [
        {
          "text": "Specifies that the asset is a photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetTypePhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetTypePhoto"
        }
      ],
      "role": "symbol",
      "title": "ALAssetTypePhoto",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassettypephoto"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeUnknown": {
      "abstract": [
        {
          "text": "Specifies that the asset’s type cannot be determined.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetTypeUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "ALAssetTypeUnknown",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassettypeunknown"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeVideo": {
      "abstract": [
        {
          "text": "Specifies that the asset is a video.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetTypeVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetTypeVideo"
        }
      ],
      "role": "symbol",
      "title": "ALAssetTypeVideo",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassettypevideo"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyName": {
      "abstract": [
        {
          "text": "Key to retrieve the name of the group.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsGroupPropertyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsGroupPropertyName"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsGroupPropertyName",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetsgrouppropertyname"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyPersistentID": {
      "abstract": [
        {
          "text": "Key to retrieve the group’s persistent ID.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsGroupPropertyPersistentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyPersistentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsGroupPropertyPersistentID"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsGroupPropertyPersistentID",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetsgrouppropertypersistentid"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyType": {
      "abstract": [
        {
          "text": "Key to retrieve the group type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsGroupPropertyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsGroupPropertyType"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsGroupPropertyType",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetsgrouppropertytype"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyURL": {
      "abstract": [
        {
          "text": "Key to retrieve a URL that uniquely identifies the group.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsGroupPropertyURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsGroupPropertyURL"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsGroupPropertyURL",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetsgrouppropertyurl"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryChangedNotification": {
      "abstract": [
        {
          "text": "Sent when the contents of the assets library have changed from under the app that is using the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryChangedNotification"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryChangedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "ALAssetsLibraryChangedNotification",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibrarychangednotification"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryErrorDomain": {
      "abstract": [
        {
          "text": "Constant used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to distinguish errors belonging to the AssetsLibrary domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetsLibraryErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ALAssetsLibraryErrorDomain",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetslibraryerrordomain"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALErrorInvalidProperty": {
      "abstract": [
        {
          "text": "Value returned by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAsset/value(forProperty:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " if the property you tried to access is invalid.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALErrorInvalidProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALErrorInvalidProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALErrorInvalidProperty"
        }
      ],
      "role": "symbol",
      "title": "ALErrorInvalidProperty",
      "type": "topic",
      "url": "/documentation/assetslibrary/alerrorinvalidproperty"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AssetsLibrary Data Types",
      "type": "topic",
      "url": "/documentation/assetslibrary/assetslibrary-data-types"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AssetsLibrary Enumerations",
      "type": "topic",
      "url": "/documentation/assetslibrary/assetslibrary-enumerations"
    },
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/foundation/nsurl": {
      "abstract": [
        {
          "text": "An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSURL"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSURL",
      "type": "topic",
      "url": "/documentation/foundation/nsurl"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-enumerations",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryDeletedAssetGroupsKey",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryInsertedAssetGroupsKey",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetGroupsKey",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetsKey",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyAssetURL",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDate",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDuration",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyLocation",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyOrientation",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyRepresentations",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyType",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyURLs",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypePhoto",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeUnknown",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeVideo",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyName",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyPersistentID",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyType",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyURL",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryErrorDomain",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALErrorInvalidProperty"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryDeletedAssetGroupsKey",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryInsertedAssetGroupsKey",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetGroupsKey",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetLibraryUpdatedAssetsKey",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyAssetURL",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDate",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyDuration",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyLocation",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyOrientation",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyRepresentations",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyType",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetPropertyURLs",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypePhoto",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeUnknown",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetTypeVideo",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyName",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyPersistentID",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyType",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsGroupPropertyURL",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryChangedNotification",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetsLibraryErrorDomain",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALErrorInvalidProperty"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-enumerations",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetTypePhoto/title",
          "value": "ALAssetTypePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetTypePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetTypePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAsset~1value(forProperty:)/title",
          "value": "valueForProperty:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAsset~1value(forProperty:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "valueForProperty:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurl/abstract",
          "value": [
            {
              "text": "An object that represents the location of a resource, such as an item on a remote server or the path to a local file. ",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupPropertyURL/title",
          "value": "ALAssetsGroupPropertyURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupPropertyURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsGroupPropertyURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupPropertyPersistentID/title",
          "value": "ALAssetsGroupPropertyPersistentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupPropertyPersistentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsGroupPropertyPersistentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyDate/title",
          "value": "ALAssetPropertyDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryInsertedAssetGroupsKey/title",
          "value": "ALAssetLibraryInsertedAssetGroupsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryInsertedAssetGroupsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetLibraryInsertedAssetGroupsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryUpdatedAssetsKey/title",
          "value": "ALAssetLibraryUpdatedAssetsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryUpdatedAssetsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetLibraryUpdatedAssetsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyURLs/title",
          "value": "ALAssetPropertyURLs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyURLs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyURLs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyAssetURL/title",
          "value": "ALAssetPropertyAssetURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyAssetURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyAssetURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetTypeUnknown/title",
          "value": "ALAssetTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetTypeUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyDuration/title",
          "value": "ALAssetPropertyDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupPropertyName/title",
          "value": "ALAssetsGroupPropertyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupPropertyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsGroupPropertyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyOrientation/title",
          "value": "ALAssetPropertyOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryDeletedAssetGroupsKey/title",
          "value": "ALAssetLibraryDeletedAssetGroupsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryDeletedAssetGroupsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetLibraryDeletedAssetGroupsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupPropertyType/title",
          "value": "ALAssetsGroupPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsGroupPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsGroupPropertyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryUpdatedAssetGroupsKey/title",
          "value": "ALAssetLibraryUpdatedAssetGroupsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetLibraryUpdatedAssetGroupsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetLibraryUpdatedAssetGroupsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALErrorInvalidProperty/title",
          "value": "ALErrorInvalidProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALErrorInvalidProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALErrorInvalidProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryErrorDomain/title",
          "value": "ALAssetsLibraryErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetsLibraryErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetsLibraryErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyRepresentations/title",
          "value": "ALAssetPropertyRepresentations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyRepresentations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyRepresentations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetTypeVideo/title",
          "value": "ALAssetTypeVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetTypeVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetTypeVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyLocation/title",
          "value": "ALAssetPropertyLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyType/title",
          "value": "ALAssetPropertyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetPropertyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetPropertyType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/assetslibrary/assetslibrary-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/assetslibrary/assetslibrary-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
