{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Assets Library"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AssetsLibrary Enumerations"
  },
  "references": {
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary": {
      "abstract": [
        {
          "text": "Access the assets in a user’s media library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Assets Library",
      "type": "topic",
      "url": "/documentation/assetslibrary"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetOrientation": {
      "abstract": [
        {
          "text": "Constants to indicate the orientation of an asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAssetOrientation"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAssetOrientation"
        }
      ],
      "role": "symbol",
      "title": "ALAssetOrientation",
      "type": "topic",
      "url": "/documentation/assetslibrary/alassetorientation"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus": {
      "abstract": [
        {
          "text": "Constants to indicate authorization status.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ALAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ALAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "ALAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/assetslibrary/alauthorizationstatus"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AssetsLibrary Constants",
      "type": "topic",
      "url": "/documentation/assetslibrary/assetslibrary-constants"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AssetsLibrary Data Types",
      "type": "topic",
      "url": "/documentation/assetslibrary/assetslibrary-data-types"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-codes": {
      "abstract": [
        {
          "text": "AssetsLibrary-related error codes",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error Codes",
      "type": "topic",
      "url": "/documentation/assetslibrary/error-codes"
    },
    "doc://com.apple.assetslibrary/documentation/AssetsLibrary/types-of-asset": {
      "abstract": [
        {
          "text": "Constants to identify types of asset.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.assetslibrary/documentation/AssetsLibrary/types-of-asset",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Types of Asset",
      "type": "topic",
      "url": "/documentation/assetslibrary/types-of-asset"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-constants",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetOrientation",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-codes",
        "doc://com.apple.assetslibrary/documentation/AssetsLibrary/types-of-asset"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAssetOrientation",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/ALAuthorizationStatus",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/error-codes",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/types-of-asset"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-constants",
                "doc://com.apple.assetslibrary/documentation/AssetsLibrary/assetslibrary-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetOrientation/title",
          "value": "ALAssetOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAssetOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAssetOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus/title",
          "value": "ALAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.assetslibrary~1documentation~1AssetsLibrary~1ALAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ALAuthorizationStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/assetslibrary/assetslibrary-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/assetslibrary/assetslibrary-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
