{
  "abstract": [
    {
      "text": "A value that indicates the player item only supports mono and stereo layouts for audio spatialization.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats/monoAndStereo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAudioSpatializationFormats@AVAudioSpatializationFormatMonoAndStereo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "monoAndStereo"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AVAudioSpatializationFormats",
        "text": "AVAudioSpatializationFormats"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioSpatializationFormatMonoAndStereo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "monoAndStereo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "monoAndStereo"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVAudioSpatializationFormats",
              "text": "AVAudioSpatializationFormats"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats": {
      "abstract": [
        {
          "text": "A structure that defines the spatialization formats that a player item supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSpatializationFormats"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSpatializationFormats"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSpatializationFormats",
      "type": "topic",
      "url": "/documentation/avfoundation/avaudiospatializationformats"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats/AVAudioSpatializationFormatNone": {
      "abstract": [
        {
          "text": "A value that indicates the player item doesn’t support audio spatialization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioSpatializationFormatNone"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats/AVAudioSpatializationFormatNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSpatializationFormatNone",
      "type": "topic",
      "url": "/documentation/avfoundation/avaudiospatializationformats/avaudiospatializationformatnone"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats/monoAndStereo": {
      "abstract": [
        {
          "text": "A value that indicates the player item only supports mono and stereo layouts for audio spatialization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monoAndStereo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioSpatializationFormats",
          "text": "AVAudioSpatializationFormats"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats/monoAndStereo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSpatializationFormatMonoAndStereo"
        }
      ],
      "role": "symbol",
      "title": "monoAndStereo",
      "type": "topic",
      "url": "/documentation/avfoundation/avaudiospatializationformats/monoandstereo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats/monoStereoAndMultichannel": {
      "abstract": [
        {
          "text": "A value that indicates the player item supports mono, stereo, and multichannel layouts for audio spatialization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monoStereoAndMultichannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioSpatializationFormats",
          "text": "AVAudioSpatializationFormats"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats/monoStereoAndMultichannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSpatializationFormatMonoStereoAndMultichannel"
        }
      ],
      "role": "symbol",
      "title": "monoStereoAndMultichannel",
      "type": "topic",
      "url": "/documentation/avfoundation/avaudiospatializationformats/monostereoandmultichannel"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats/multichannel": {
      "abstract": [
        {
          "text": "A value that indicates the player item only supports multichannel layouts for audio spatialization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multichannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioSpatializationFormats",
          "text": "AVAudioSpatializationFormats"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats/multichannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSpatializationFormatMultichannel"
        }
      ],
      "role": "symbol",
      "title": "multichannel",
      "type": "topic",
      "url": "/documentation/avfoundation/avaudiospatializationformats/multichannel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Spatialization-Formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats/multichannel",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats/monoStereoAndMultichannel"
      ],
      "title": "Spatialization Formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioSpatializationFormatMonoAndStereo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSpatializationFormatMonoAndStereo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Spatialization-Formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats/multichannel",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats/monoStereoAndMultichannel",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSpatializationFormats/AVAudioSpatializationFormatNone"
              ],
              "title": "Spatialization Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVAudioSpatializationFormatMonoAndStereo"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAudioSpatializationFormats~1monoStereoAndMultichannel/title",
          "value": "AVAudioSpatializationFormatMonoStereoAndMultichannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAudioSpatializationFormats~1monoStereoAndMultichannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSpatializationFormatMonoStereoAndMultichannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAudioSpatializationFormats~1multichannel/title",
          "value": "AVAudioSpatializationFormatMultichannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAudioSpatializationFormats~1multichannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSpatializationFormatMultichannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAudioSpatializationFormats~1monoAndStereo/title",
          "value": "AVAudioSpatializationFormatMonoAndStereo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAudioSpatializationFormats~1monoAndStereo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSpatializationFormatMonoAndStereo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAudioSpatializationFormats/title",
          "value": "AVAudioSpatializationFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAudioSpatializationFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSpatializationFormats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAudioSpatializationFormats/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSpatializationFormats"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avaudiospatializationformats/monoandstereo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avaudiospatializationformats/monoandstereo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
