{
  "abstract": [
    {
      "text": "Tier 2 read/write textures are supported.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier/tier2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLReadWriteTextureTier@MTLReadWriteTextureTier2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tier2"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLReadWriteTextureTier2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLReadWriteTextureTier.tier2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tier2"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Read/write texture tier 2 supports the following pixel formats in addition to those supported by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier/tier1",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba32Float",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba32Uint",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba32Sint",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Float",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Uint",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Sint",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Unorm",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Uint",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Sint",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Float",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Uint",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Sint",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r8Unorm",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r8Uint",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r8Sint",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Float": {
      "abstract": [
        {
          "text": "Ordinary format with one 16-bit floating-point component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "r16Float"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatR16Float"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.r16Float",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/r16float"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Sint": {
      "abstract": [
        {
          "text": "Ordinary format with one 16-bit signed integer component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "r16Sint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Sint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatR16Sint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.r16Sint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/r16sint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Uint": {
      "abstract": [
        {
          "text": "Ordinary format with one 16-bit unsigned integer component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "r16Uint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r16Uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatR16Uint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.r16Uint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/r16uint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r8Sint": {
      "abstract": [
        {
          "text": "Ordinary format with one 8-bit signed integer component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "r8Sint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r8Sint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatR8Sint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.r8Sint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/r8sint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r8Uint": {
      "abstract": [
        {
          "text": "Ordinary format with one 8-bit unsigned integer component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "r8Uint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r8Uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatR8Uint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.r8Uint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/r8uint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r8Unorm": {
      "abstract": [
        {
          "text": "Ordinary format with one 8-bit normalized unsigned integer component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "r8Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/r8Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatR8Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.r8Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/r8unorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Float": {
      "abstract": [
        {
          "text": "Ordinary format with four 16-bit floating-point components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba16Float"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA16Float"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba16Float",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba16float"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Sint": {
      "abstract": [
        {
          "text": "Ordinary format with four 16-bit signed integer components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba16Sint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Sint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA16Sint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba16Sint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba16sint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Uint": {
      "abstract": [
        {
          "text": "Ordinary format with four 16-bit unsigned integer components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba16Uint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba16Uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA16Uint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba16Uint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba16uint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba32Float": {
      "abstract": [
        {
          "text": "Ordinary format with four 32-bit floating-point components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba32Float"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba32Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA32Float"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba32Float",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba32float"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba32Sint": {
      "abstract": [
        {
          "text": "Ordinary format with four 32-bit signed integer components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba32Sint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba32Sint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA32Sint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba32Sint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba32sint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba32Uint": {
      "abstract": [
        {
          "text": "Ordinary format with four 32-bit unsigned integer components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba32Uint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba32Uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA32Uint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba32Uint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba32uint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Sint": {
      "abstract": [
        {
          "text": "Ordinary format with four 8-bit signed integer components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba8Sint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Sint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA8Sint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba8Sint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba8sint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Uint": {
      "abstract": [
        {
          "text": "Ordinary format with four 8-bit unsigned integer components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba8Uint"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Uint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA8Uint"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba8Uint",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba8uint"
    },
    "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Unorm": {
      "abstract": [
        {
          "text": "Ordinary format with four 8-bit normalized unsigned integer components in RGBA order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rgba8Unorm"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLPixelFormat/rgba8Unorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLPixelFormatRGBA8Unorm"
        }
      ],
      "role": "symbol",
      "title": "MTLPixelFormat.rgba8Unorm",
      "type": "topic",
      "url": "/documentation/metal/mtlpixelformat/rgba8unorm"
    },
    "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier": {
      "abstract": [
        {
          "text": "The support level for read-write texture formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLReadWriteTextureTier"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLReadWriteTextureTier"
        }
      ],
      "role": "symbol",
      "title": "MTLReadWriteTextureTier",
      "type": "topic",
      "url": "/documentation/metal/mtlreadwritetexturetier"
    },
    "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier/tier1": {
      "abstract": [
        {
          "text": "Tier 1 read/write textures are supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tier1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier/tier1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLReadWriteTextureTier1"
        }
      ],
      "role": "symbol",
      "title": "MTLReadWriteTextureTier.tier1",
      "type": "topic",
      "url": "/documentation/metal/mtlreadwritetexturetier/tier1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier/tier2": {
      "abstract": [
        {
          "text": "Tier 2 read/write textures are supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tier2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier/tier2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLReadWriteTextureTier2"
        }
      ],
      "role": "symbol",
      "title": "MTLReadWriteTextureTier.tier2",
      "type": "topic",
      "url": "/documentation/metal/mtlreadwritetexturetier/tier2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier/tierNone": {
      "abstract": [
        {
          "text": "Read-write textures are not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tierNone"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier/tierNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLReadWriteTextureTierNone"
        }
      ],
      "role": "symbol",
      "title": "MTLReadWriteTextureTier.tierNone",
      "type": "topic",
      "url": "/documentation/metal/mtlreadwritetexturetier/tiernone"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier/tier1",
        "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier/tierNone"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLReadWriteTextureTier2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLReadWriteTextureTier2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier/tier1",
                "doc://com.apple.metal/documentation/Metal/MTLReadWriteTextureTier/tierNone"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLReadWriteTextureTier2"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLReadWriteTextureTier~1tier2/title",
          "value": "MTLReadWriteTextureTier2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLReadWriteTextureTier~1tier2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLReadWriteTextureTier2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba32Sint/title",
          "value": "MTLPixelFormatRGBA32Sint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba32Sint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA32Sint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Uint/title",
          "value": "MTLPixelFormatR16Uint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatR16Uint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r8Uint/title",
          "value": "MTLPixelFormatR8Uint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r8Uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatR8Uint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Uint/title",
          "value": "MTLPixelFormatRGBA8Uint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA8Uint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba32Float/title",
          "value": "MTLPixelFormatRGBA32Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba32Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA32Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Sint/title",
          "value": "MTLPixelFormatR16Sint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Sint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatR16Sint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Float/title",
          "value": "MTLPixelFormatR16Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r16Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatR16Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Sint/title",
          "value": "MTLPixelFormatRGBA8Sint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Sint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA8Sint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLReadWriteTextureTier~1tier1/title",
          "value": "MTLReadWriteTextureTier1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLReadWriteTextureTier~1tier1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLReadWriteTextureTier1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r8Sint/title",
          "value": "MTLPixelFormatR8Sint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r8Sint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatR8Sint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r8Unorm/title",
          "value": "MTLPixelFormatR8Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1r8Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatR8Unorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLReadWriteTextureTier/title",
          "value": "MTLReadWriteTextureTier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLReadWriteTextureTier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLReadWriteTextureTier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLReadWriteTextureTier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLReadWriteTextureTier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Unorm/title",
          "value": "MTLPixelFormatRGBA8Unorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba8Unorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA8Unorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Uint/title",
          "value": "MTLPixelFormatRGBA16Uint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA16Uint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLReadWriteTextureTier~1tierNone/title",
          "value": "MTLReadWriteTextureTierNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLReadWriteTextureTier~1tierNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLReadWriteTextureTierNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba32Uint/title",
          "value": "MTLPixelFormatRGBA32Uint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba32Uint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA32Uint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Sint/title",
          "value": "MTLPixelFormatRGBA16Sint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Sint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA16Sint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Float/title",
          "value": "MTLPixelFormatRGBA16Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLPixelFormat~1rgba16Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLPixelFormatRGBA16Float"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlreadwritetexturetier/tier2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlreadwritetexturetier/tier2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
