{
  "abstract": [
    {
      "text": "Decimal tab stop.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/decimalTabStop"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSAccessibilityDecimalTabStopMarkerTypeValue",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "decimalTabStop"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@NSAccessibility",
        "text": "NSAccessibility"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSAccessibilityRulerMarkerTypeValue",
        "text": "RulerMarkerTypeValue"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAccessibilityDecimalTabStopMarkerTypeValue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "decimalTabStop"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "decimalTabStop"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@NSAccessibility",
              "text": "NSAccessibility"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAccessibilityRulerMarkerTypeValue",
              "text": "RulerMarkerTypeValue"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct": {
      "abstract": [
        {
          "text": "A namespace for accessibility symbols for AppKit apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibility"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibility"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue": {
      "abstract": [
        {
          "text": "Values that describe ruler marker types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RulerMarkerTypeValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RulerMarkerTypeValue"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibility.RulerMarkerTypeValue",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/rulermarkertypevalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/centerTabStop": {
      "abstract": [
        {
          "text": "Center tab stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerTabStop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityRulerMarkerTypeValue",
          "text": "RulerMarkerTypeValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/centerTabStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityCenterTabStopMarkerTypeValue"
        }
      ],
      "role": "symbol",
      "title": "centerTabStop",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/rulermarkertypevalue/centertabstop"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/decimalTabStop": {
      "abstract": [
        {
          "text": "Decimal tab stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decimalTabStop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityRulerMarkerTypeValue",
          "text": "RulerMarkerTypeValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/decimalTabStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityDecimalTabStopMarkerTypeValue"
        }
      ],
      "role": "symbol",
      "title": "decimalTabStop",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/rulermarkertypevalue/decimaltabstop"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/firstLineIndent": {
      "abstract": [
        {
          "text": "First line indent marker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstLineIndent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityRulerMarkerTypeValue",
          "text": "RulerMarkerTypeValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/firstLineIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityFirstLineIndentMarkerTypeValue"
        }
      ],
      "role": "symbol",
      "title": "firstLineIndent",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/rulermarkertypevalue/firstlineindent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/headIndent": {
      "abstract": [
        {
          "text": "Head indent marker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headIndent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityRulerMarkerTypeValue",
          "text": "RulerMarkerTypeValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/headIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityHeadIndentMarkerTypeValue"
        }
      ],
      "role": "symbol",
      "title": "headIndent",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/rulermarkertypevalue/headindent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/leftTabStop": {
      "abstract": [
        {
          "text": "Left tab stop.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftTabStop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityRulerMarkerTypeValue",
          "text": "RulerMarkerTypeValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/leftTabStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityLeftTabStopMarkerTypeValue"
        }
      ],
      "role": "symbol",
      "title": "leftTabStop",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/rulermarkertypevalue/lefttabstop"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/rightTabStop": {
      "abstract": [
        {
          "text": "Right tab stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightTabStop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityRulerMarkerTypeValue",
          "text": "RulerMarkerTypeValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/rightTabStop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityRightTabStopMarkerTypeValue"
        }
      ],
      "role": "symbol",
      "title": "rightTabStop",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/rulermarkertypevalue/righttabstop"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/tailIndent": {
      "abstract": [
        {
          "text": "Tail indent marker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tailIndent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityRulerMarkerTypeValue",
          "text": "RulerMarkerTypeValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/tailIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityTailIndentMarkerTypeValue"
        }
      ],
      "role": "symbol",
      "title": "tailIndent",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/rulermarkertypevalue/tailindent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/unknown": {
      "abstract": [
        {
          "text": "Unknown marker type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSAccessibility",
          "text": "NSAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAccessibilityRulerMarkerTypeValue",
          "text": "RulerMarkerTypeValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityUnknownMarkerTypeValue"
        }
      ],
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibility-swift.struct/rulermarkertypevalue/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Markers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/centerTabStop",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/firstLineIndent",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/headIndent",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/leftTabStop",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/rightTabStop",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/tailIndent",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/unknown"
      ],
      "title": "Markers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSAccessibilityDecimalTabStopMarkerTypeValue"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityDecimalTabStopMarkerTypeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Markers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/centerTabStop",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/firstLineIndent",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/headIndent",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/leftTabStop",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/rightTabStop",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/tailIndent",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue/unknown"
              ],
              "title": "Markers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/RulerMarkerTypeValue",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSAccessibilityRulerMarkerTypeValue",
                    "text": "NSAccessibilityRulerMarkerTypeValue"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSAccessibilityDecimalTabStopMarkerTypeValue"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1tailIndent/title",
          "value": "NSAccessibilityTailIndentMarkerTypeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1tailIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityTailIndentMarkerTypeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1centerTabStop/title",
          "value": "NSAccessibilityCenterTabStopMarkerTypeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1centerTabStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCenterTabStopMarkerTypeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue/title",
          "value": "NSAccessibilityRulerMarkerTypeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerTypeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRulerMarkerTypeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1leftTabStop/title",
          "value": "NSAccessibilityLeftTabStopMarkerTypeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1leftTabStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityLeftTabStopMarkerTypeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1rightTabStop/title",
          "value": "NSAccessibilityRightTabStopMarkerTypeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1rightTabStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityRightTabStopMarkerTypeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1unknown/title",
          "value": "NSAccessibilityUnknownMarkerTypeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityUnknownMarkerTypeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1decimalTabStop/title",
          "value": "NSAccessibilityDecimalTabStopMarkerTypeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1decimalTabStop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityDecimalTabStopMarkerTypeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1firstLineIndent/title",
          "value": "NSAccessibilityFirstLineIndentMarkerTypeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1firstLineIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityFirstLineIndentMarkerTypeValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1headIndent/title",
          "value": "NSAccessibilityHeadIndentMarkerTypeValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1RulerMarkerTypeValue~1headIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityHeadIndentMarkerTypeValue"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibility-swift.struct/rulermarkertypevalue/decimaltabstop"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsaccessibility-swift.struct/rulermarkertypevalue/decimaltabstop"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
