{
  "abstract": [
    {
      "text": "An error that describes a failed extension manager request.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemextensions/documentation/SystemExtensions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC26OSSystemExtensionErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OSSystemExtensionError"
      }
    ],
    "modules": [
      {
        "name": "System Extensions"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OSSystemExtensionError"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "OSSystemExtensionError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OSSystemExtensionError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions": {
      "abstract": [
        {
          "text": "Install and manage user space code that extends the capabilities of macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions",
      "kind": "symbol",
      "role": "collection",
      "title": "System Extensions",
      "type": "topic",
      "url": "/documentation/systemextensions"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError": {
      "abstract": [
        {
          "text": "An error that describes a failed extension manager request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSystemExtensionError"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionError"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code": {
      "abstract": [
        {
          "text": "Error codes for system extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/authorizationRequired": {
      "abstract": [
        {
          "text": "An error code that indicates the system was unable to obtain the proper authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26OSSystemExtensionErrorCodeLeV",
          "text": "OSSystemExtensionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSSystemExtensionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/authorizationRequired",
      "kind": "symbol",
      "role": "symbol",
      "title": "authorizationRequired",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/authorizationrequired"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/codeSignatureInvalid": {
      "abstract": [
        {
          "text": "An error code that indicates the extension’s signature is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "codeSignatureInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26OSSystemExtensionErrorCodeLeV",
          "text": "OSSystemExtensionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSSystemExtensionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/codeSignatureInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "codeSignatureInvalid",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/codesignatureinvalid"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/duplicateExtensionIdentifer": {
      "abstract": [
        {
          "text": "An error code that indicates the extension identifier duplicates an existing identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duplicateExtensionIdentifer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26OSSystemExtensionErrorCodeLeV",
          "text": "OSSystemExtensionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSSystemExtensionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/duplicateExtensionIdentifer",
      "kind": "symbol",
      "role": "symbol",
      "title": "duplicateExtensionIdentifer",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/duplicateextensionidentifer"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/errorDomain": {
      "abstract": [
        {
          "text": "The domain of SystemExtension errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/errordomain"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/extensionMissingIdentifier": {
      "abstract": [
        {
          "text": "An error code that indicates the extension identifier is missing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionMissingIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26OSSystemExtensionErrorCodeLeV",
          "text": "OSSystemExtensionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSSystemExtensionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/extensionMissingIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "extensionMissingIdentifier",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/extensionmissingidentifier"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/extensionNotFound": {
      "abstract": [
        {
          "text": "An error code that indicates the manager can’t find the system extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26OSSystemExtensionErrorCodeLeV",
          "text": "OSSystemExtensionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSSystemExtensionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/extensionNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "extensionNotFound",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/extensionnotfound"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/forbiddenBySystemPolicy": {
      "abstract": [
        {
          "text": "An error code that indicates the system policy prohibits activating the system extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forbiddenBySystemPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26OSSystemExtensionErrorCodeLeV",
          "text": "OSSystemExtensionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSSystemExtensionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/forbiddenBySystemPolicy",
      "kind": "symbol",
      "role": "symbol",
      "title": "forbiddenBySystemPolicy",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/forbiddenbysystempolicy"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/missingEntitlement": {
      "abstract": [
        {
          "text": "An error code that indicates the system extension lacks a required entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingEntitlement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26OSSystemExtensionErrorCodeLeV",
          "text": "OSSystemExtensionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSSystemExtensionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/missingEntitlement",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingEntitlement",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/missingentitlement"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/requestCanceled": {
      "abstract": [
        {
          "text": "An error code that indicates the system extension manager request was canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestCanceled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26OSSystemExtensionErrorCodeLeV",
          "text": "OSSystemExtensionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSSystemExtensionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/requestCanceled",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestCanceled",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/requestcanceled"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/requestSuperseded": {
      "abstract": [
        {
          "text": "An error code that indicates the system extension request failed because the system already has a pending request for the same identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestSuperseded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26OSSystemExtensionErrorCodeLeV",
          "text": "OSSystemExtensionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSSystemExtensionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/requestSuperseded",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestSuperseded",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/requestsuperseded"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/unknown": {
      "abstract": [
        {
          "text": "An error code that indicates an unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26OSSystemExtensionErrorCodeLeV",
          "text": "OSSystemExtensionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSSystemExtensionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/unknown"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/unknownExtensionCategory": {
      "abstract": [
        {
          "text": "An error code that indicates the extension manager can’t recognize the extension’s category identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownExtensionCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26OSSystemExtensionErrorCodeLeV",
          "text": "OSSystemExtensionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSSystemExtensionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/unknownExtensionCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknownExtensionCategory",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/unknownextensioncategory"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/unsupportedParentBundleLocation": {
      "abstract": [
        {
          "text": "An error code that indicates the extension’s parent app isn’t in a valid location for activation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedParentBundleLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26OSSystemExtensionErrorCodeLeV",
          "text": "OSSystemExtensionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSSystemExtensionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/unsupportedParentBundleLocation",
      "kind": "symbol",
      "role": "symbol",
      "title": "unsupportedParentBundleLocation",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/unsupportedparentbundlelocation"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/validationFailed": {
      "abstract": [
        {
          "text": "An error code that indicates the manager can’t validate the extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC26OSSystemExtensionErrorCodeLeV",
          "text": "OSSystemExtensionError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OSSystemExtensionErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/validationFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "validationFailed",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/validationfailed"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionErrorDomain": {
      "abstract": [
        {
          "text": "The error domain identifying system extension errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionErrorDomain",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerrordomain"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-Error-Properties",
      "identifiers": [
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/errorDomain"
      ],
      "title": "Inspecting Error Properties"
    },
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/unknown",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/missingEntitlement",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/unsupportedParentBundleLocation",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/extensionNotFound",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/extensionMissingIdentifier",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/duplicateExtensionIdentifer",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/unknownExtensionCategory",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/codeSignatureInvalid",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/validationFailed",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/forbiddenBySystemPolicy",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/requestCanceled",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/requestSuperseded",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/authorizationRequired"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionErrorDomain/title",
          "value": "OSSystemExtensionErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code/title",
          "value": "OSSystemExtensionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemextensions/ossystemextensionerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
