{
  "abstract": [
    {
      "text": "The error domain identifying system extension errors.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemextensions/documentation/SystemExtensions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionErrorDomain"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@OSSystemExtensionErrorDomain",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OSSystemExtensionErrorDomain"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "System Extensions"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OSSystemExtensionErrorDomain"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "OSSystemExtensionErrorDomain"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorDomain"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions": {
      "abstract": [
        {
          "text": "Install and manage user space code that extends the capabilities of macOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions",
      "kind": "symbol",
      "role": "collection",
      "title": "System Extensions",
      "type": "topic",
      "url": "/documentation/systemextensions"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError": {
      "abstract": [
        {
          "text": "An error that describes a failed extension manager request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSystemExtensionError"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionError"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code": {
      "abstract": [
        {
          "text": "Error codes for system extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionError.Code",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerror/code"
    },
    "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionErrorDomain": {
      "abstract": [
        {
          "text": "The error domain identifying system extension errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSystemExtensionErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "OSSystemExtensionErrorDomain",
      "type": "topic",
      "url": "/documentation/systemextensions/ossystemextensionerrordomain"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError",
        "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OSSystemExtensionErrorDomain"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemextensions/documentation/SystemExtensions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemextensions/documentation/SystemExtensions/OSSystemExtensionError/Code"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSErrorDomain",
                    "text": "NSErrorDomain"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "OSSystemExtensionErrorDomain"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code/title",
          "value": "OSSystemExtensionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionErrorDomain/title",
          "value": "OSSystemExtensionErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemextensions~1documentation~1SystemExtensions~1OSSystemExtensionErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSSystemExtensionErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemextensions/ossystemextensionerrordomain"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemextensions/ossystemextensionerrordomain"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
