{
  "abstract": [
    {
      "text": "Creates an encoding result object with a signed or encrypted message, or errors if the message encoder fails to encode the message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mailkit/documentation/MailKit",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult/init(encodedMessage:signingError:encryptionError:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MEMessageEncodingResult(im)initWithEncodedMessage:signingError:encryptionError:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "encodedMessage"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MEEncodedOutgoingMessage",
        "text": "MEEncodedOutgoingMessage"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "signingError"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?, "
      },
      {
        "kind": "externalParam",
        "text": "encryptionError"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?)"
      }
    ],
    "modules": [
      {
        "name": "MailKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithEncodedMessage:signingError:encryptionError:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(encodedMessage:signingError:encryptionError:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "encodedMessage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEEncodedOutgoingMessage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MEEncodedOutgoingMessage",
              "text": "MEEncodedOutgoingMessage"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "signingError"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?, "
            },
            {
              "kind": "externalParam",
              "text": "encryptionError"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A signed or encrypted message.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "encodedMessage"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An error that occurred while signing the message.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "signingError"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An error that occurred while encrypting the message.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "encryptionError"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the message doesn’t require a digital signature or any encryption, specify ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " for the message and errors.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the message security handler does need to sign or encrypt the message, but encoding fails, specify ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " for ",
              "type": "text"
            },
            {
              "code": "encodedMessage",
              "type": "codeVoice"
            },
            {
              "text": ", and an error for one or both of the error parameters.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mailkit/documentation/MailKit": {
      "abstract": [
        {
          "text": "Secure, customize, and act on email messages that users send and receive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MailKit",
      "type": "topic",
      "url": "/documentation/mailkit"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEEncodedOutgoingMessage": {
      "abstract": [
        {
          "text": "An object that contains the signed or encrypted representation of a message’s RFC 2822 data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEEncodedOutgoingMessage"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEEncodedOutgoingMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEEncodedOutgoingMessage"
        }
      ],
      "role": "symbol",
      "title": "MEEncodedOutgoingMessage",
      "type": "topic",
      "url": "/documentation/mailkit/meencodedoutgoingmessage"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult": {
      "abstract": [
        {
          "text": "An object that contains a signed or encrypted message, or errors that indicate failure to encode the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageEncodingResult"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageEncodingResult"
        }
      ],
      "role": "symbol",
      "title": "MEMessageEncodingResult",
      "type": "topic",
      "url": "/documentation/mailkit/memessageencodingresult"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult/encodedMessage": {
      "abstract": [
        {
          "text": "A signed or encrypted message, if the message security handler needs to encode the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encodedMessage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEEncodedOutgoingMessage",
          "text": "MEEncodedOutgoingMessage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult/encodedMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encodedMessage"
        }
      ],
      "role": "symbol",
      "title": "encodedMessage",
      "type": "topic",
      "url": "/documentation/mailkit/memessageencodingresult/encodedmessage"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult/encryptionError": {
      "abstract": [
        {
          "text": "An error that occurred while the message encoder encrypted the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encryptionError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult/encryptionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encryptionError"
        }
      ],
      "role": "symbol",
      "title": "encryptionError",
      "type": "topic",
      "url": "/documentation/mailkit/memessageencodingresult/encryptionerror"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult/init(encodedMessage:signingError:encryptionError:)": {
      "abstract": [
        {
          "text": "Creates an encoding result object with a signed or encrypted message, or errors if the message encoder fails to encode the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "encodedMessage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEEncodedOutgoingMessage",
          "text": "MEEncodedOutgoingMessage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "signingError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "encryptionError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult/init(encodedMessage:signingError:encryptionError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEncodedMessage:signingError:encryptionError:"
        }
      ],
      "role": "symbol",
      "title": "init(encodedMessage:signingError:encryptionError:)",
      "type": "topic",
      "url": "/documentation/mailkit/memessageencodingresult/init(encodedmessage:signingerror:encryptionerror:)"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult/signingError": {
      "abstract": [
        {
          "text": "An error that occurred while the message encoder signed the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signingError"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult/signingError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signingError"
        }
      ],
      "role": "symbol",
      "title": "signingError",
      "type": "topic",
      "url": "/documentation/mailkit/memessageencodingresult/signingerror"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-an-Encoding-Result",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult/encodedMessage",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult/encryptionError",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult/signingError"
      ],
      "title": "Providing an Encoding Result"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithEncodedMessage:signingError:encryptionError:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEncodedMessage:signingError:encryptionError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mailkit/documentation/MailKit",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-an-Encoding-Result",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult/encodedMessage",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult/encryptionError",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageEncodingResult/signingError"
              ],
              "title": "Providing an Encoding Result"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithEncodedMessage:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEEncodedOutgoingMessage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MEEncodedOutgoingMessage",
                    "text": "MEEncodedOutgoingMessage"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "encodedMessage"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "signingError:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "signingError"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "encryptionError:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "encryptionError"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A signed or encrypted message.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "encodedMessage"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An error that occurred while signing the message.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "signingError"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An error that occurred while encrypting the message.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "encryptionError"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult/title",
          "value": "MEMessageEncodingResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageEncodingResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageEncodingResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult~1encryptionError/title",
          "value": "encryptionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult~1encryptionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "encryptionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult~1init(encodedMessage:signingError:encryptionError:)/title",
          "value": "initWithEncodedMessage:signingError:encryptionError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult~1init(encodedMessage:signingError:encryptionError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEncodedMessage:signingError:encryptionError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult~1signingError/title",
          "value": "signingError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult~1signingError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "signingError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult~1encodedMessage/title",
          "value": "encodedMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageEncodingResult~1encodedMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "encodedMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEncodedOutgoingMessage/title",
          "value": "MEEncodedOutgoingMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEncodedOutgoingMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEEncodedOutgoingMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEEncodedOutgoingMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEEncodedOutgoingMessage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mailkit/memessageencodingresult/init(encodedmessage:signingerror:encryptionerror:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mailkit/memessageencodingresult/init(encodedmessage:signingerror:encryptionerror:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
