{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTabView",
        "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabViewBorderType-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabViewBorderType-swift.enum/line"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTabViewBorderType@NSTabViewBorderTypeLine",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "line"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTabViewBorderTypeLine"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSTabView.TabViewBorderType.line"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "line"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabView": {
      "abstract": [
        {
          "text": "A multipage interface that displays one page at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTabView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTabView"
        }
      ],
      "role": "symbol",
      "title": "NSTabView",
      "type": "topic",
      "url": "/documentation/appkit/nstabview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabViewBorderType-swift.enum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TabViewBorderType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabViewBorderType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TabViewBorderType"
        }
      ],
      "role": "symbol",
      "title": "NSTabView.TabViewBorderType",
      "type": "topic",
      "url": "/documentation/appkit/nstabview/tabviewbordertype-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabViewBorderType-swift.enum/bezel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bezel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabViewBorderType-swift.enum/bezel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTabViewBorderTypeBezel"
        }
      ],
      "role": "symbol",
      "title": "NSTabView.TabViewBorderType.bezel",
      "type": "topic",
      "url": "/documentation/appkit/nstabview/tabviewbordertype-swift.enum/bezel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabViewBorderType-swift.enum/line": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "line"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabViewBorderType-swift.enum/line",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTabViewBorderTypeLine"
        }
      ],
      "role": "symbol",
      "title": "NSTabView.TabViewBorderType.line",
      "type": "topic",
      "url": "/documentation/appkit/nstabview/tabviewbordertype-swift.enum/line"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabViewBorderType-swift.enum/none": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabViewBorderType-swift.enum/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTabViewBorderTypeNone"
        }
      ],
      "role": "symbol",
      "title": "NSTabView.TabViewBorderType.none",
      "type": "topic",
      "url": "/documentation/appkit/nstabview/tabviewbordertype-swift.enum/none"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabViewBorderType-swift.enum/bezel",
        "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabViewBorderType-swift.enum/none"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTabViewBorderTypeLine"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabViewBorderTypeLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabViewBorderType-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabViewBorderType-swift.enum/bezel",
                "doc://com.apple.appkit/documentation/AppKit/NSTabView/TabViewBorderType-swift.enum/none"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTabViewBorderTypeLine"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabViewBorderType-swift.enum~1bezel/title",
          "value": "NSTabViewBorderTypeBezel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabViewBorderType-swift.enum~1bezel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabViewBorderTypeBezel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabViewBorderType-swift.enum/title",
          "value": "NSTabViewBorderType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabViewBorderType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabViewBorderType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabViewBorderType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabViewBorderType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView/title",
          "value": "NSTabView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabViewBorderType-swift.enum~1none/title",
          "value": "NSTabViewBorderTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabViewBorderType-swift.enum~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabViewBorderTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabViewBorderType-swift.enum~1line/title",
          "value": "NSTabViewBorderTypeLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTabView~1TabViewBorderType-swift.enum~1line/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTabViewBorderTypeLine"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstabview/tabviewbordertype-swift.enum/line"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstabview/tabviewbordertype-swift.enum/line"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
