{
  "abstract": [
    {
      "text": "Returns the button element for the specified key code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboardInput"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboardInput/button(forKeyCode:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GCKeyboardInput(im)buttonForKeyCode:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "button"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "forKeyCode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@GCKeyCode",
        "text": "GCKeyCode"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
        "text": "GCControllerButtonInput"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "buttonForKeyCode:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "button(forKeyCode:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "button"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "forKeyCode"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "code"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@GCKeyCode",
              "text": "GCKeyCode"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
              "text": "GCControllerButtonInput"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The code for the keyboard button element.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "code"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The keyboard button element that this profile defines for the specified key code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Alternatively, you can get a button element for a key using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile/subscript(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " notation that you inherit from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", as in ",
              "type": "text"
            },
            {
              "code": "keyboard[GCKeyUpArrow]",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput": {
      "abstract": [
        {
          "text": "A control element that represents a button touch or press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCControllerButtonInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCControllerButtonInput"
        }
      ],
      "role": "symbol",
      "title": "GCControllerButtonInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gccontrollerbuttoninput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode": {
      "abstract": [
        {
          "text": "The key codes for keys on a keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyCode"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyCode"
        }
      ],
      "role": "symbol",
      "title": "GCKeyCode",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeycode"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboardInput": {
      "abstract": [
        {
          "text": "A controller profile that uses the keyboard as the input device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCKeyboardInput"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboardInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCKeyboardInput"
        }
      ],
      "role": "symbol",
      "title": "GCKeyboardInput",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeyboardinput"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboardInput/button(forKeyCode:)": {
      "abstract": [
        {
          "text": "Returns the button element for the specified key code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "button"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forKeyCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GCKeyCode",
          "text": "GCKeyCode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
          "text": "GCControllerButtonInput"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboardInput/button(forKeyCode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonForKeyCode:"
        }
      ],
      "role": "symbol",
      "title": "button(forKeyCode:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeyboardinput/button(forkeycode:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboardInput/isAnyKeyPressed": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the user is pressing any of the keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAnyKeyPressed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboardInput/isAnyKeyPressed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "anyKeyPressed"
        }
      ],
      "role": "symbol",
      "title": "isAnyKeyPressed",
      "type": "topic",
      "url": "/documentation/gamecontroller/gckeyboardinput/isanykeypressed"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile": {
      "abstract": [
        {
          "text": "The base class for controller profiles that support physical buttons, thumbsticks, and directional pads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputProfile"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputProfile"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputProfile",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputprofile"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile/subscript(_:)": {
      "abstract": [
        {
          "text": "Returns the element that the key specifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GCControllerElement",
          "text": "GCControllerElement"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputProfile/subscript(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKeyedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputprofile/subscript(_:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/keycode-constants": {
      "abstract": [
        {
          "text": "Constants for the codes of keyboard keys.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/keycode-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keycode Constants",
      "type": "topic",
      "url": "/documentation/gamecontroller/keycode-constants"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Buttons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboardInput/isAnyKeyPressed",
        "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode",
        "doc://com.apple.gamecontroller/documentation/GameController/keycode-constants"
      ],
      "title": "Accessing Buttons"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "buttonForKeyCode:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "buttonForKeyCode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamecontroller/documentation/GameController",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboardInput"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Buttons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyboardInput/isAnyKeyPressed",
                "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode",
                "doc://com.apple.gamecontroller/documentation/GameController/keycode-constants"
              ],
              "title": "Accessing Buttons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCControllerButtonInput",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)GCControllerButtonInput",
                    "text": "GCControllerButtonInput"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "buttonForKeyCode:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCKeyCode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@GCKeyCode",
                    "text": "GCKeyCode"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "code"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The code for the keyboard button element.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "code"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The keyboard button element that this profile defines for the specified key code.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode/title",
          "value": "GCKeyCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboardInput~1button(forKeyCode:)/title",
          "value": "buttonForKeyCode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboardInput~1button(forKeyCode:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "buttonForKeyCode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/title",
          "value": "GCPhysicalInputProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCPhysicalInputProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboardInput/title",
          "value": "GCKeyboardInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboardInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyboardInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboardInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCKeyboardInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile~1subscript(_:)/title",
          "value": "objectForKeyedSubscript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCPhysicalInputProfile~1subscript(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectForKeyedSubscript:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboardInput~1isAnyKeyPressed/title",
          "value": "anyKeyPressed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCKeyboardInput~1isAnyKeyPressed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "anyKeyPressed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerButtonInput/title",
          "value": "GCControllerButtonInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerButtonInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerButtonInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCControllerButtonInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCControllerButtonInput"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gckeyboardinput/button(forkeycode:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamecontroller/gckeyboardinput/button(forkeycode:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
