{
  "abstract": [
    {
      "text": "A right-aligned caption for the message bubble.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.messages/documentation/Messages",
        "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/trailingCaption"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MSMessageTemplateLayout(py)trailingCaption",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "trailingCaption"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Messages"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "trailingCaption"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "trailingCaption"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "trailingCaption"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The trailing caption is drawn using black text and is positioned at the bottom-right corner of the message bubble, just below the image or media file. This text is right aligned and positioned on the same line as the caption. The trailing caption can wrap to three lines before being truncated. This property defaults to ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.messages/documentation/Messages": {
      "abstract": [
        {
          "text": "Create app extensions that allow users to send text, stickers, media files, and interactive messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages",
      "kind": "symbol",
      "role": "collection",
      "title": "Messages",
      "type": "topic",
      "url": "/documentation/messages"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout": {
      "abstract": [
        {
          "text": "A template-based layout for custom messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSMessageTemplateLayout"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageTemplateLayout"
        }
      ],
      "role": "symbol",
      "title": "MSMessageTemplateLayout",
      "type": "topic",
      "url": "/documentation/messages/msmessagetemplatelayout"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/caption": {
      "abstract": [
        {
          "text": "A left-aligned caption for the message bubble.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "caption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/caption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "caption"
        }
      ],
      "role": "symbol",
      "title": "caption",
      "type": "topic",
      "url": "/documentation/messages/msmessagetemplatelayout/caption"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/image": {
      "abstract": [
        {
          "text": "An image used to represent the message in the transcript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/messages/msmessagetemplatelayout/image"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/imageSubtitle": {
      "abstract": [
        {
          "text": "The subtitle for the image or media file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSubtitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/imageSubtitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSubtitle"
        }
      ],
      "role": "symbol",
      "title": "imageSubtitle",
      "type": "topic",
      "url": "/documentation/messages/msmessagetemplatelayout/imagesubtitle"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/imageTitle": {
      "abstract": [
        {
          "text": "The title for the image or media file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/imageTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageTitle"
        }
      ],
      "role": "symbol",
      "title": "imageTitle",
      "type": "topic",
      "url": "/documentation/messages/msmessagetemplatelayout/imagetitle"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/mediaFileURL": {
      "abstract": [
        {
          "text": "A media file used to represent the message in the transcript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaFileURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/mediaFileURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaFileURL"
        }
      ],
      "role": "symbol",
      "title": "mediaFileURL",
      "type": "topic",
      "url": "/documentation/messages/msmessagetemplatelayout/mediafileurl"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/subcaption": {
      "abstract": [
        {
          "text": "A left-aligned subcaption for the message bubble.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subcaption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/subcaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subcaption"
        }
      ],
      "role": "symbol",
      "title": "subcaption",
      "type": "topic",
      "url": "/documentation/messages/msmessagetemplatelayout/subcaption"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/trailingCaption": {
      "abstract": [
        {
          "text": "A right-aligned caption for the message bubble.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailingCaption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/trailingCaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trailingCaption"
        }
      ],
      "role": "symbol",
      "title": "trailingCaption",
      "type": "topic",
      "url": "/documentation/messages/msmessagetemplatelayout/trailingcaption"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/trailingSubcaption": {
      "abstract": [
        {
          "text": "A right-aligned subcaption for the message bubble.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailingSubcaption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/trailingSubcaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trailingSubcaption"
        }
      ],
      "role": "symbol",
      "title": "trailingSubcaption",
      "type": "topic",
      "url": "/documentation/messages/msmessagetemplatelayout/trailingsubcaption"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Assigning-Visual-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/image",
        "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/mediaFileURL",
        "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/imageTitle",
        "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/imageSubtitle",
        "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/caption",
        "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/subcaption",
        "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/trailingSubcaption"
      ],
      "title": "Assigning Visual Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "trailingCaption"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trailingCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.messages/documentation/Messages",
                "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Assigning-Visual-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/image",
                "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/mediaFileURL",
                "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/imageTitle",
                "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/imageSubtitle",
                "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/caption",
                "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/subcaption",
                "doc://com.apple.messages/documentation/Messages/MSMessageTemplateLayout/trailingSubcaption"
              ],
              "title": "Assigning Visual Elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "trailingCaption"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1mediaFileURL/title",
          "value": "mediaFileURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1mediaFileURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaFileURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1imageSubtitle/title",
          "value": "imageSubtitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1imageSubtitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSubtitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1subcaption/title",
          "value": "subcaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1subcaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subcaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1image/title",
          "value": "image"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "image"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout/title",
          "value": "MSMessageTemplateLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageTemplateLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageTemplateLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1trailingSubcaption/title",
          "value": "trailingSubcaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1trailingSubcaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trailingSubcaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1trailingCaption/title",
          "value": "trailingCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1trailingCaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trailingCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1caption/title",
          "value": "caption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1caption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "caption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1imageTitle/title",
          "value": "imageTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageTemplateLayout~1imageTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageTitle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/messages/msmessagetemplatelayout/trailingcaption"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/messages/msmessagetemplatelayout/trailingcaption"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
