{
  "abstract": [
    {
      "text": "Returns a 16-bit floating-point pixel value from a 32-bit floating-point pixel value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage/Interleaved16Fx4"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vImage/Interleaved16Fx4/makePixel(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Accelerate",
    "externalID": "s:10Accelerate6vImageO16Interleaved16Fx4V9makePixelys6UInt16V_A3HtSf_S3ft_tFZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "makePixel"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@Pixel_FFFF",
        "text": "Pixel_FFFF"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@Pixel_ARGB_16F",
        "text": "Pixel_ARGB_16F"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "makePixel(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "makePixel"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "source"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_FFFF",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@Pixel_FFFF",
              "text": "Pixel_FFFF"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_ARGB_16F",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@Pixel_ARGB_16F",
              "text": "Pixel_ARGB_16F"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_ARGB_16F": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_ARGB_16F"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_ARGB_16F",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_ARGB_16F"
        }
      ],
      "role": "symbol",
      "title": "Pixel_ARGB_16F",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_argb_16f"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_FFFF": {
      "abstract": [
        {
          "text": "A type for a four-channel, 32-bits-per-channel, floating-point pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_FFFF"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_FFFF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_FFFF"
        }
      ],
      "role": "symbol",
      "title": "Pixel_FFFF",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_ffff"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage": {
      "abstract": [
        {
          "text": "An enumeration that acts as a namespace for Swift overlays to vImage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage"
        }
      ],
      "role": "symbol",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/Interleaved16Fx4": {
      "abstract": [
        {
          "text": "A four-channel, 16-bit-per-channel, floating-point interleaved buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Interleaved16Fx4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/Interleaved16Fx4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Interleaved16Fx4"
        }
      ],
      "role": "symbol",
      "title": "vImage.Interleaved16Fx4",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/interleaved16fx4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/Interleaved16Fx4/makePixel(_:)": {
      "abstract": [
        {
          "text": "Returns a 16-bit floating-point pixel value from a 32-bit floating-point pixel value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makePixel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@Pixel_FFFF",
          "text": "Pixel_FFFF"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@Pixel_ARGB_16F",
          "text": "Pixel_ARGB_16F"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/Interleaved16Fx4/makePixel(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "makePixel(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/interleaved16fx4/makepixel(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_FFFF/title",
          "value": "Pixel_FFFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_FFFF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_FFFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_FFFF/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_FFFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_ARGB_16F/title",
          "value": "Pixel_ARGB_16F"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_ARGB_16F/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_ARGB_16F"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_ARGB_16F/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_ARGB_16F"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimage/interleaved16fx4/makepixel(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
