{"abstract":[{"type":"text","text":"Returns the background image to use for a given bar position and set of metrics."}],"kind":"symbol","metadata":{"title":"backgroundImage(for:barMetrics:)","platforms":[{"introducedAt":"7.0","beta":false,"deprecated":false,"unavailable":false,"name":"iOS"},{"introducedAt":"7.0","beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS"},{"introducedAt":"13.1","beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS"},{"introducedAt":"1.0","beta":false,"deprecated":false,"unavailable":false,"name":"visionOS"}],"role":"symbol","modules":[{"name":"UIKit"}],"navigatorTitle":[{"kind":"identifier","text":"backgroundImageForBarPosition:barMetrics:"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)UINavigationBar(im)backgroundImageForBarPosition:barMetrics:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarPosition","preciseIdentifier":"c:@E@UIBarPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barMetrics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarMetrics","text":"UIBarMetrics"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}]},"seeAlsoSections":[{"title":"Changing the background","anchor":"Changing-the-background","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:barMetrics:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uinavigationbar/backgroundimage(for:barmetrics:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uinavigationbar/backgroundimage(for:barmetrics:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"barPosition","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarPosition","preciseIdentifier":"c:@E@UIBarPosition","text":"UIBarPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"barMetrics","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics","preciseIdentifier":"c:@E@UIBarMetrics","text":"UIBarMetrics","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"barPosition","content":[{"inlineContent":[{"type":"text","text":"The location of the navigation bar."}],"type":"paragraph"}]},{"name":"barMetrics","content":[{"inlineContent":[{"text":"The metrics of the navigation bar.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The image to use for the specified location and metrics."}],"type":"paragraph"}],"kind":"content"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Resizable images will be stretched vertically, if necessary, for a position of ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarPosition/topAttached"},{"text":".","type":"text"}]}],"kind":"content"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:barMetrics:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:barMetrics:)","kind":"symbol","title":"backgroundImage(for:barMetrics:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundImageForBarPosition:barMetrics:"}],"abstract":[{"text":"Returns the background image to use for a given bar position and set of metrics.","type":"text"}],"url":"/documentation/uikit/uinavigationbar/backgroundimage(for:barmetrics:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundImage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIBarPosition","kind":"typeIdentifier","text":"UIBarPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barMetrics"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier","text":"UIBarMetrics"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor":{"type":"topic","title":"barTintColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barTintColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"url":"/documentation/uikit/uinavigationbar/bartintcolor","navigatorTitle":[{"text":"barTintColor","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The tint color to apply to the navigation bar background."}]},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UINavigationBar"}],"abstract":[{"type":"text","text":"Navigational controls that display in a bar along the top of the screen, usually in conjunction with a navigation controller."}],"title":"UINavigationBar","navigatorTitle":[{"kind":"identifier","text":"UINavigationBar"}],"url":"/documentation/uikit/uinavigationbar","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics":{"navigatorTitle":[{"text":"UIBarMetrics","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIBarMetrics","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uibarmetrics","title":"UIBarMetrics","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Constants to specify metrics to use for appearance."}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:)":{"kind":"symbol","title":"setBackgroundImage(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBackgroundImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier","text":"UIBarMetrics"},{"kind":"text","text":")"}],"url":"/documentation/uikit/uinavigationbar/setbackgroundimage(_:for:)","abstract":[{"type":"text","text":"Sets the background image for given bar metrics."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setBackgroundImage:forBarMetrics:"}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)":{"role":"symbol","url":"/documentation/uikit/uinavigationbar/setbackgroundimage(_:for:barmetrics:)","navigatorTitle":[{"text":"setBackgroundImage:forBarPosition:barMetrics:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setBackgroundImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIBarPosition","preciseIdentifier":"c:@E@UIBarPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"barMetrics","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIBarMetrics","preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)","abstract":[{"type":"text","text":"Sets the background image to use for a given bar position and set of metrics."}],"kind":"symbol","title":"setBackgroundImage(_:for:barMetrics:)","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIBarPosition/topAttached":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topAttached","kind":"identifier"}],"role":"symbol","title":"UIBarPosition.topAttached","url":"/documentation/uikit/uibarposition/topattached","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarPosition/topAttached","navigatorTitle":[{"text":"UIBarPositionTopAttached","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Specifies that the bar is at the top of the screen, as well as its containing view."}]},"doc://com.apple.uikit/documentation/UIKit/UIBarPosition":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIBarPosition"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIBarPosition"}],"title":"UIBarPosition","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarPosition","type":"topic","url":"/documentation/uikit/uibarposition","abstract":[{"type":"text","text":"Constants to identify the position of a bar."}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)":{"kind":"symbol","title":"backgroundImage(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarMetrics","text":"UIBarMetrics"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}],"url":"/documentation/uikit/uinavigationbar/backgroundimage(for:)","abstract":[{"type":"text","text":"Returns the background image for given bar metrics."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"backgroundImageForBarMetrics:"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"introducedAt":"7.0","unavailable":false,"deprecated":false,"name":"iOS"},{"beta":false,"introducedAt":"7.0","unavailable":false,"deprecated":false,"name":"iPadOS"},{"beta":false,"introducedAt":"13.1","unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS"},{"deprecated":false,"unavailable":false,"introducedAt":"1.0","beta":false,"name":"visionOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"backgroundImageForBarPosition:barMetrics:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"backgroundImageForBarPosition:barMetrics:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Changing the background","identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:)","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)"],"generated":true,"anchor":"Changing-the-background"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)UIImage","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"backgroundImageForBarPosition:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@UIBarPosition","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarPosition","kind":"typeIdentifier","text":"UIBarPosition"},{"kind":"text","text":") "},{"kind":"internalParam","text":"barPosition"},{"kind":"text","text":" "},{"kind":"identifier","text":"barMetrics:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@UIBarMetrics","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics","kind":"typeIdentifier","text":"UIBarMetrics"},{"kind":"text","text":") "},{"kind":"internalParam","text":"barMetrics"},{"kind":"text","text":";"}]}]}},{"path":"/primaryContentSections/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The location of the navigation bar."}]}],"name":"barPosition"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The metrics of the navigation bar.","type":"text"}]}],"name":"barMetrics"}],"kind":"parameters"}},{"op":"replace","path":"/primaryContentSections/2","value":{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The image to use for the specified location and metrics."}],"type":"paragraph"}],"kind":"content"}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:barMetrics:)/title","op":"replace","value":"backgroundImageForBarPosition:barMetrics:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:barMetrics:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"backgroundImageForBarPosition:barMetrics:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1barTintColor/title","op":"replace","value":"barTintColor"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1barTintColor/fragments","op":"replace","value":[{"kind":"identifier","text":"barTintColor"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title","op":"replace","value":"UIImage"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments","op":"replace","value":[{"kind":"identifier","text":"UIImage"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle","op":"replace","value":[{"text":"UIImage","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/title","op":"replace","value":"UINavigationBar"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/fragments","op":"replace","value":[{"text":"UINavigationBar","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/navigatorTitle","op":"replace","value":[{"text":"UINavigationBar","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics/title","op":"replace","value":"UIBarMetrics"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics/fragments","op":"replace","value":[{"text":"UIBarMetrics","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics/navigatorTitle","op":"replace","value":[{"text":"UIBarMetrics","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:)/title","op":"replace","value":"setBackgroundImage:forBarMetrics:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setBackgroundImage:forBarMetrics:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:barMetrics:)/title","op":"replace","value":"setBackgroundImage:forBarPosition:barMetrics:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:barMetrics:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBackgroundImage:forBarPosition:barMetrics:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPosition~1topAttached/title","op":"replace","value":"UIBarPositionTopAttached"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPosition~1topAttached/fragments","op":"replace","value":[{"text":"UIBarPositionTopAttached","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPosition/title","op":"replace","value":"UIBarPosition"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPosition/fragments","op":"replace","value":[{"text":"UIBarPosition","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPosition/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIBarPosition"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:)/title","op":"replace","value":"backgroundImageForBarMetrics:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"backgroundImageForBarMetrics:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}