{"seeAlsoSections":[{"title":"Building with Mac Catalyst","anchor":"Building-with-Mac-Catalyst","identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/preferredBehavioralStyle","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/currentNSToolbarSection","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/NSToolbarSection"],"generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"behavioralStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIBehavioralStyle","preciseIdentifier":"c:@E@UIBehavioralStyle","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app"]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"Use this property to determine the actual behavior style when the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/preferredBehavioralStyle"},{"type":"text","text":" is "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle/automatic"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"When the value of this property is "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle/mac"},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/AppKit/NSToolbar"},{"type":"text","text":" hosts the navigation bar’s content when you build your app with Mac Catalyst."}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"The behavioral style of the navigation bar."}],"kind":"symbol","sections":[],"variants":[{"paths":["/documentation/uikit/uinavigationbar/behavioralstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uinavigationbar/behavioralstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/behavioralStyle","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]},"metadata":{"externalID":"c:objc(cs)UINavigationBar(py)behavioralStyle","platforms":[{"introducedAt":"16.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"introducedAt":"16.0","unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"16.0","unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"1.0","unavailable":false,"beta":false,"deprecated":false,"name":"visionOS"}],"roleHeading":"Instance Property","title":"behavioralStyle","modules":[{"name":"UIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"behavioralStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIBehavioralStyle","preciseIdentifier":"c:@E@UIBehavioralStyle","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"behavioralStyle","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.documentation/documentation/AppKit/NSToolbar":{"identifier":"doc://com.apple.documentation/documentation/AppKit/NSToolbar","kind":"symbol","type":"topic","title":"NSToolbar","url":"/documentation/AppKit/NSToolbar","fragments":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSToolbar"}],"role":"symbol","abstract":[{"text":"An object that manages the space above your app’s custom content and either below or integrated with the window’s title bar.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/preferredBehavioralStyle":{"abstract":[{"type":"text","text":"The preferred behavioral style of the navigation bar."}],"navigatorTitle":[{"text":"preferredBehavioralStyle","kind":"identifier"}],"url":"/documentation/uikit/uinavigationbar/preferredbehavioralstyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredBehavioralStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIBehavioralStyle","preciseIdentifier":"c:@E@UIBehavioralStyle","kind":"typeIdentifier"}],"kind":"symbol","title":"preferredBehavioralStyle","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/preferredBehavioralStyle","type":"topic","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/behavioralStyle":{"title":"behavioralStyle","navigatorTitle":[{"kind":"identifier","text":"behavioralStyle"}],"role":"symbol","type":"topic","url":"/documentation/uikit/uinavigationbar/behavioralstyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"behavioralStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBehavioralStyle","preciseIdentifier":"c:@E@UIBehavioralStyle"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/behavioralStyle","abstract":[{"text":"The behavioral style of the navigation bar.","type":"text"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle/mac":{"abstract":[{"text":"A style that indicates that a control appears and behaves as it does in macOS.","type":"text"}],"type":"topic","title":"UIBehavioralStyle.mac","kind":"symbol","navigatorTitle":[{"text":"UIBehavioralStyleMac","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mac","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle/mac","url":"/documentation/uikit/uibehavioralstyle/mac","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UINavigationBar"}],"abstract":[{"type":"text","text":"Navigational controls that display in a bar along the top of the screen, usually in conjunction with a navigation controller."}],"title":"UINavigationBar","navigatorTitle":[{"kind":"identifier","text":"UINavigationBar"}],"url":"/documentation/uikit/uinavigationbar","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle/automatic":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automatic","kind":"identifier"}],"title":"UIBehavioralStyle.automatic","abstract":[{"text":"A style the system chooses based on the app’s targeted platform.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/uikit/uibehavioralstyle/automatic","kind":"symbol","navigatorTitle":[{"text":"UIBehavioralStyleAutomatic","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle/automatic"},"doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app":{"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app","abstract":[{"text":"Optimize your iPad app’s user experience by adopting desktop-class enhancements for multitasking with Stage Manager, document interactions, text editing, search, and more in iPadOS 16.","type":"text"}],"kind":"article","url":"/documentation/uikit/building-a-desktop-class-ipad-app","title":"Building a desktop-class iPad app","role":"article"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/currentNSToolbarSection":{"navigatorTitle":[{"text":"currentNSToolbarSection","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentNSToolbarSection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationBar","text":"UINavigationBar","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UINavigationBarNSToolbarSection","text":"NSToolbarSection","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"The toolbar section that the navigation bar is currently using.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/currentNSToolbarSection","title":"currentNSToolbarSection","url":"/documentation/uikit/uinavigationbar/currentnstoolbarsection","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIBehavioralStyle","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Constants that indicate how a control behaves in apps built with Mac Catalyst.","type":"text"}],"url":"/documentation/uikit/uibehavioralstyle","title":"UIBehavioralStyle","navigatorTitle":[{"text":"UIBehavioralStyle","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/NSToolbarSection":{"title":"UINavigationBar.NSToolbarSection","navigatorTitle":[{"kind":"identifier","text":"NSToolbarSection"}],"role":"symbol","type":"topic","url":"/documentation/uikit/uinavigationbar/nstoolbarsection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSToolbarSection"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/NSToolbarSection","abstract":[{"type":"text","text":"Constants that determine how the system hosts the navigation bar in an AppKit toolbar."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"name":"iOS","beta":false,"introducedAt":"16.0","unavailable":false},{"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"16.0","unavailable":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"16.0","unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"behavioralStyle","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"behavioralStyle"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]},"op":"replace"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"anchor":"Building-with-Mac-Catalyst","title":"Building with Mac Catalyst","identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/preferredBehavioralStyle","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/currentNSToolbarSection","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/NSToolbarSection"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle","text":"UIBehavioralStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBehavioralStyle"},{"text":" ","kind":"text"},{"text":"behavioralStyle","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSToolbar/fragments","op":"replace","value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSToolbar","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1preferredBehavioralStyle/title","op":"replace","value":"preferredBehavioralStyle"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1preferredBehavioralStyle/fragments","op":"replace","value":[{"kind":"identifier","text":"preferredBehavioralStyle"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1behavioralStyle/title","op":"replace","value":"behavioralStyle"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1behavioralStyle/fragments","op":"replace","value":[{"kind":"identifier","text":"behavioralStyle"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBehavioralStyle~1mac/title","op":"replace","value":"UIBehavioralStyleMac"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBehavioralStyle~1mac/fragments","op":"replace","value":[{"kind":"identifier","text":"UIBehavioralStyleMac"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/title","op":"replace","value":"UINavigationBar"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/fragments","op":"replace","value":[{"kind":"identifier","text":"UINavigationBar"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UINavigationBar"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBehavioralStyle~1automatic/title","op":"replace","value":"UIBehavioralStyleAutomatic"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBehavioralStyle~1automatic/fragments","op":"replace","value":[{"kind":"identifier","text":"UIBehavioralStyleAutomatic"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1currentNSToolbarSection/title","op":"replace","value":"currentNSToolbarSection"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1currentNSToolbarSection/fragments","op":"replace","value":[{"text":"currentNSToolbarSection","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBehavioralStyle/title","op":"replace","value":"UIBehavioralStyle"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBehavioralStyle/fragments","op":"replace","value":[{"kind":"identifier","text":"UIBehavioralStyle"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBehavioralStyle/navigatorTitle","op":"replace","value":[{"text":"UIBehavioralStyle","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1NSToolbarSection/title","op":"replace","value":"UINavigationBarNSToolbarSection"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1NSToolbarSection/fragments","op":"replace","value":[{"text":"UINavigationBarNSToolbarSection","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1NSToolbarSection/navigatorTitle","op":"replace","value":[{"text":"UINavigationBarNSToolbarSection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}