{"abstract":[{"text":"The toolbar section that the navigation bar is currently using.","type":"text"}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/currentNSToolbarSection","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"title":"Building with Mac Catalyst","identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/behavioralStyle","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/preferredBehavioralStyle","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/NSToolbarSection"],"anchor":"Building-with-Mac-Catalyst"}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"currentNSToolbarSection"}],"title":"currentNSToolbarSection","externalID":"c:objc(cs)UINavigationBar(py)currentNSToolbarSection","modules":[{"name":"UIKit"}],"role":"symbol","symbolKind":"property","platforms":[{"introducedAt":"16.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"introducedAt":"16.0","unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"deprecated":false,"unavailable":false,"introducedAt":"16.0","beta":false,"name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"introducedAt":"1.0","beta":false,"name":"visionOS"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentNSToolbarSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationBar","text":"UINavigationBar"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UINavigationBarNSToolbarSection","text":"NSToolbarSection"}],"roleHeading":"Instance Property"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentNSToolbarSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINavigationBar","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar","preciseIdentifier":"c:objc(cs)UINavigationBar"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"NSToolbarSection","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/NSToolbarSection","preciseIdentifier":"c:@E@UINavigationBarNSToolbarSection"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}],"kind":"declarations"},{"mentions":["doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app"],"kind":"mentions"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/uikit/uinavigationbar/currentnstoolbarsection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uinavigationbar/currentnstoolbarsection"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]},"references":{"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/behavioralStyle":{"title":"behavioralStyle","navigatorTitle":[{"kind":"identifier","text":"behavioralStyle"}],"role":"symbol","type":"topic","url":"/documentation/uikit/uinavigationbar/behavioralstyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"behavioralStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBehavioralStyle","preciseIdentifier":"c:@E@UIBehavioralStyle"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/behavioralStyle","abstract":[{"text":"The behavioral style of the navigation bar.","type":"text"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UINavigationBar"}],"abstract":[{"type":"text","text":"Navigational controls that display in a bar along the top of the screen, usually in conjunction with a navigation controller."}],"title":"UINavigationBar","navigatorTitle":[{"kind":"identifier","text":"UINavigationBar"}],"url":"/documentation/uikit/uinavigationbar","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/currentNSToolbarSection":{"navigatorTitle":[{"text":"currentNSToolbarSection","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentNSToolbarSection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationBar","text":"UINavigationBar","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UINavigationBarNSToolbarSection","text":"NSToolbarSection","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"The toolbar section that the navigation bar is currently using.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/currentNSToolbarSection","title":"currentNSToolbarSection","url":"/documentation/uikit/uinavigationbar/currentnstoolbarsection","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/NSToolbarSection":{"title":"UINavigationBar.NSToolbarSection","navigatorTitle":[{"kind":"identifier","text":"NSToolbarSection"}],"role":"symbol","type":"topic","url":"/documentation/uikit/uinavigationbar/nstoolbarsection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSToolbarSection"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/NSToolbarSection","abstract":[{"type":"text","text":"Constants that determine how the system hosts the navigation bar in an AppKit toolbar."}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/preferredBehavioralStyle":{"abstract":[{"type":"text","text":"The preferred behavioral style of the navigation bar."}],"navigatorTitle":[{"text":"preferredBehavioralStyle","kind":"identifier"}],"url":"/documentation/uikit/uinavigationbar/preferredbehavioralstyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredBehavioralStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIBehavioralStyle","preciseIdentifier":"c:@E@UIBehavioralStyle","kind":"typeIdentifier"}],"kind":"symbol","title":"preferredBehavioralStyle","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/preferredBehavioralStyle","type":"topic","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app":{"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app","abstract":[{"text":"Optimize your iPad app’s user experience by adopting desktop-class enhancements for multitasking with Stage Manager, document interactions, text editing, search, and more in iPadOS 16.","type":"text"}],"kind":"article","url":"/documentation/uikit/building-a-desktop-class-ipad-app","title":"Building a desktop-class iPad app","role":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false,"introducedAt":"16.0"},{"deprecated":false,"beta":false,"introducedAt":"16.0","unavailable":false,"name":"iPadOS"},{"deprecated":false,"beta":false,"introducedAt":"16.0","unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"beta":false,"introducedAt":"1.0","unavailable":false,"name":"visionOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"currentNSToolbarSection","path":"/metadata/title","op":"replace"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"currentNSToolbarSection"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/behavioralStyle","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/preferredBehavioralStyle","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/NSToolbarSection"],"anchor":"Building-with-Mac-Catalyst","title":"Building with Mac Catalyst"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UINavigationBarNSToolbarSection","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/NSToolbarSection","preciseIdentifier":"c:@E@UINavigationBarNSToolbarSection"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentNSToolbarSection"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"behavioralStyle","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1behavioralStyle/title"},{"op":"replace","value":[{"kind":"identifier","text":"behavioralStyle"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1behavioralStyle/fragments"},{"op":"replace","value":"UINavigationBar","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/title"},{"op":"replace","value":[{"kind":"identifier","text":"UINavigationBar"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UINavigationBar"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/navigatorTitle"},{"op":"replace","value":"currentNSToolbarSection","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1currentNSToolbarSection/title"},{"op":"replace","value":[{"kind":"identifier","text":"currentNSToolbarSection"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1currentNSToolbarSection/fragments"},{"op":"replace","value":"UINavigationBarNSToolbarSection","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1NSToolbarSection/title"},{"op":"replace","value":[{"kind":"identifier","text":"UINavigationBarNSToolbarSection"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1NSToolbarSection/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UINavigationBarNSToolbarSection"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1NSToolbarSection/navigatorTitle"},{"op":"replace","value":"preferredBehavioralStyle","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1preferredBehavioralStyle/title"},{"op":"replace","value":[{"kind":"identifier","text":"preferredBehavioralStyle"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1preferredBehavioralStyle/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}