{
  "abstract": [
    {
      "text": "Display attributes for the bar’s large title text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/largeTitleTextAttributes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UINavigationBar(py)largeTitleTextAttributes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "largeTitleTextAttributes"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSAttributedString",
        "text": "NSAttributedString"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSAttributedStringKey",
        "text": "Key"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "largeTitleTextAttributes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "largeTitleTextAttributes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "largeTitleTextAttributes"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSAttributedString",
              "text": "NSAttributedString"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAttributedStringKey",
              "text": "Key"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can specify the font, text color, text shadow color, and text shadow offset for the title in the text attributes dictionary, using the text attribute keys described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key": {
      "abstract": [
        {
          "text": "The attributes you apply to ranges of characters in an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString.Key",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar": {
      "abstract": [
        {
          "text": "Navigational controls that display in a bar along the top of the screen, usually in conjunction with a navigation controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UINavigationBar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINavigationBar"
        }
      ],
      "role": "symbol",
      "title": "UINavigationBar",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/largeTitleTextAttributes": {
      "abstract": [
        {
          "text": "Display attributes for the bar’s large title text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "largeTitleTextAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringKey",
          "text": "Key"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/largeTitleTextAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "largeTitleTextAttributes"
        }
      ],
      "role": "symbol",
      "title": "largeTitleTextAttributes",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/largetitletextattributes"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setTitleVerticalPositionAdjustment(_:for:)": {
      "abstract": [
        {
          "text": "Sets the title’s vertical position adjustment for given bar metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTitleVerticalPositionAdjustment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarMetrics",
          "text": "UIBarMetrics"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setTitleVerticalPositionAdjustment(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitleVerticalPositionAdjustment:forBarMetrics:"
        }
      ],
      "role": "symbol",
      "title": "setTitleVerticalPositionAdjustment(_:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/settitleverticalpositionadjustment(_:for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleTextAttributes": {
      "abstract": [
        {
          "text": "Display attributes for the bar’s title text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleTextAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringKey",
          "text": "Key"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleTextAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleTextAttributes"
        }
      ],
      "role": "symbol",
      "title": "titleTextAttributes",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/titletextattributes"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleVerticalPositionAdjustment(for:)": {
      "abstract": [
        {
          "text": "Returns the title’s vertical position adjustment for given bar metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleVerticalPositionAdjustment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarMetrics",
          "text": "UIBarMetrics"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleVerticalPositionAdjustment(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleVerticalPositionAdjustmentForBarMetrics:"
        }
      ],
      "role": "symbol",
      "title": "titleVerticalPositionAdjustment(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/titleverticalpositionadjustment(for:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey": {
      "abstract": [
        {
          "text": "The attributes you apply to ranges of characters in an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString.Key",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString": {
      "abstract": [
        {
          "text": "A string of text that manages data, layout, and stylistic information for ranges of characters to support rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-title",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleTextAttributes",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleVerticalPositionAdjustment(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setTitleVerticalPositionAdjustment(_:for:)"
      ],
      "title": "Configuring the title"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "largeTitleTextAttributes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "largeTitleTextAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-title",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleTextAttributes",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleVerticalPositionAdjustment(for:)",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setTitleVerticalPositionAdjustment(_:for:)"
              ],
              "title": "Configuring the title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
                    "text": "NSDictionary<NSString *,id>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "largeTitleTextAttributes"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsattributedstring~1key/title",
          "value": "NSAttributedStringKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1largeTitleTextAttributes/title",
          "value": "largeTitleTextAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1largeTitleTextAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "largeTitleTextAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSAttributedStringKey/title",
          "value": "NSAttributedStringKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1titleTextAttributes/title",
          "value": "titleTextAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1titleTextAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleTextAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setTitleVerticalPositionAdjustment(_:for:)/title",
          "value": "setTitleVerticalPositionAdjustment:forBarMetrics:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setTitleVerticalPositionAdjustment(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTitleVerticalPositionAdjustment:forBarMetrics:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/title",
          "value": "UINavigationBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINavigationBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UINavigationBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1titleVerticalPositionAdjustment(for:)/title",
          "value": "titleVerticalPositionAdjustmentForBarMetrics:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1titleVerticalPositionAdjustment(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "titleVerticalPositionAdjustmentForBarMetrics:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uinavigationbar/largetitletextattributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uinavigationbar/largetitletextattributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
