{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredBehavioralStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIBehavioralStyle","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle","kind":"typeIdentifier","text":"UIBehavioralStyle"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app"]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Use this property to specify the behavioral style for the navigation bar. If the value of the property is ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle/automatic","isActive":true,"type":"reference"},{"text":", use the ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/behavioralStyle","isActive":true,"type":"reference"},{"text":" property to determine the actual style.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The default value of this property is ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle/automatic"},{"text":". To learn more about behavioral styles, see ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle"},{"text":".","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uinavigationbar/preferredbehavioralstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uinavigationbar/preferredbehavioralstyle"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/behavioralStyle","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/currentNSToolbarSection","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/NSToolbarSection"],"anchor":"Building-with-Mac-Catalyst","title":"Building with Mac Catalyst","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]},"metadata":{"externalID":"c:objc(cs)UINavigationBar(py)preferredBehavioralStyle","title":"preferredBehavioralStyle","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"UIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredBehavioralStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIBehavioralStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBehavioralStyle"}],"platforms":[{"introducedAt":"16.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"introducedAt":"16.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"16.0","unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false},{"introducedAt":"1.0","unavailable":false,"name":"visionOS","deprecated":false,"beta":false}],"symbolKind":"property","navigatorTitle":[{"text":"preferredBehavioralStyle","kind":"identifier"}]},"abstract":[{"type":"text","text":"The preferred behavioral style of the navigation bar."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/preferredBehavioralStyle"},"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UINavigationBar"}],"abstract":[{"type":"text","text":"Navigational controls that display in a bar along the top of the screen, usually in conjunction with a navigation controller."}],"title":"UINavigationBar","navigatorTitle":[{"kind":"identifier","text":"UINavigationBar"}],"url":"/documentation/uikit/uinavigationbar","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/currentNSToolbarSection":{"navigatorTitle":[{"text":"currentNSToolbarSection","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentNSToolbarSection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationBar","text":"UINavigationBar","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UINavigationBarNSToolbarSection","text":"NSToolbarSection","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"The toolbar section that the navigation bar is currently using.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/currentNSToolbarSection","title":"currentNSToolbarSection","url":"/documentation/uikit/uinavigationbar/currentnstoolbarsection","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle/automatic":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automatic","kind":"identifier"}],"title":"UIBehavioralStyle.automatic","abstract":[{"text":"A style the system chooses based on the app’s targeted platform.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/uikit/uibehavioralstyle/automatic","kind":"symbol","navigatorTitle":[{"text":"UIBehavioralStyleAutomatic","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle/automatic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/NSToolbarSection":{"title":"UINavigationBar.NSToolbarSection","navigatorTitle":[{"kind":"identifier","text":"NSToolbarSection"}],"role":"symbol","type":"topic","url":"/documentation/uikit/uinavigationbar/nstoolbarsection","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSToolbarSection"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/NSToolbarSection","abstract":[{"type":"text","text":"Constants that determine how the system hosts the navigation bar in an AppKit toolbar."}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/behavioralStyle":{"title":"behavioralStyle","navigatorTitle":[{"kind":"identifier","text":"behavioralStyle"}],"role":"symbol","type":"topic","url":"/documentation/uikit/uinavigationbar/behavioralstyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"behavioralStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBehavioralStyle","preciseIdentifier":"c:@E@UIBehavioralStyle"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/behavioralStyle","abstract":[{"text":"The behavioral style of the navigation bar.","type":"text"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIBehavioralStyle","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Constants that indicate how a control behaves in apps built with Mac Catalyst.","type":"text"}],"url":"/documentation/uikit/uibehavioralstyle","title":"UIBehavioralStyle","navigatorTitle":[{"text":"UIBehavioralStyle","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/preferredBehavioralStyle":{"abstract":[{"type":"text","text":"The preferred behavioral style of the navigation bar."}],"navigatorTitle":[{"text":"preferredBehavioralStyle","kind":"identifier"}],"url":"/documentation/uikit/uinavigationbar/preferredbehavioralstyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredBehavioralStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIBehavioralStyle","preciseIdentifier":"c:@E@UIBehavioralStyle","kind":"typeIdentifier"}],"kind":"symbol","title":"preferredBehavioralStyle","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/preferredBehavioralStyle","type":"topic","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app":{"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app","abstract":[{"text":"Optimize your iPad app’s user experience by adopting desktop-class enhancements for multitasking with Stage Manager, document interactions, text editing, search, and more in iPadOS 16.","type":"text"}],"kind":"article","url":"/documentation/uikit/building-a-desktop-class-ipad-app","title":"Building a desktop-class iPad app","role":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"introducedAt":"16.0","deprecated":false,"name":"iOS","beta":false},{"unavailable":false,"introducedAt":"16.0","deprecated":false,"name":"iPadOS","beta":false},{"unavailable":false,"introducedAt":"16.0","deprecated":false,"name":"Mac Catalyst","beta":false},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"preferredBehavioralStyle","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"preferredBehavioralStyle"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"op":"replace","value":[{"anchor":"Building-with-Mac-Catalyst","generated":true,"title":"Building with Mac Catalyst","identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/behavioralStyle","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/currentNSToolbarSection","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/NSToolbarSection"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@E@UIBehavioralStyle","kind":"typeIdentifier","text":"UIBehavioralStyle","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBehavioralStyle"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredBehavioralStyle"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/title","op":"replace","value":"UINavigationBar"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/fragments","op":"replace","value":[{"kind":"identifier","text":"UINavigationBar"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/navigatorTitle","op":"replace","value":[{"text":"UINavigationBar","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1currentNSToolbarSection/title","op":"replace","value":"currentNSToolbarSection"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1currentNSToolbarSection/fragments","op":"replace","value":[{"text":"currentNSToolbarSection","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBehavioralStyle~1automatic/title","op":"replace","value":"UIBehavioralStyleAutomatic"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBehavioralStyle~1automatic/fragments","op":"replace","value":[{"kind":"identifier","text":"UIBehavioralStyleAutomatic"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1NSToolbarSection/title","op":"replace","value":"UINavigationBarNSToolbarSection"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1NSToolbarSection/fragments","op":"replace","value":[{"kind":"identifier","text":"UINavigationBarNSToolbarSection"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1NSToolbarSection/navigatorTitle","op":"replace","value":[{"text":"UINavigationBarNSToolbarSection","kind":"identifier"}]},{"value":"behavioralStyle","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1behavioralStyle/title"},{"value":[{"kind":"identifier","text":"behavioralStyle"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1behavioralStyle/fragments"},{"value":"UIBehavioralStyle","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBehavioralStyle/title"},{"value":[{"text":"UIBehavioralStyle","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBehavioralStyle/fragments"},{"value":[{"kind":"identifier","text":"UIBehavioralStyle"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBehavioralStyle/navigatorTitle"},{"value":"preferredBehavioralStyle","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1preferredBehavioralStyle/title"},{"value":[{"text":"preferredBehavioralStyle","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1preferredBehavioralStyle/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}