{"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Customizing the bar’s appearance","anchor":"Customizing-the-bars-appearance","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/prefersLargeTitles","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/standardAppearance","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactAppearance","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactScrollEdgeAppearance","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/isTranslucent","doc://com.apple.uikit/documentation/UIKit/uinavigationbar-legacy-customizations"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/scrollEdgeAppearance"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uinavigationbar/scrolledgeappearance"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uinavigationbar/scrolledgeappearance"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@NSCopying"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollEdgeAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBarAppearance","text":"UINavigationBarAppearance","preciseIdentifier":"c:objc(cs)UINavigationBarAppearance"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"Discussion"},{"inlineContent":[{"text":"When a navigation controller contains a navigation bar and a scroll view, part of the scroll view’s content appears underneath the navigation bar. If the edge of the scrolled content reaches that bar, UIKit applies the appearance settings in this property.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"If the value of this property is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", UIKit uses the settings found in the ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/standardAppearance","isActive":true,"type":"reference"},{"text":" property, modified to use a transparent background. If no navigation controller manages your navigation bar, UIKit ignores this property and uses the standard appearance of the navigation bar.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"When running on apps that use iOS 14 or earlier, this property applies to navigation bars with large titles. In iOS 15, this property applies to all navigation bars."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"The appearance settings for the navigation bar when the edge of scrollable content aligns with the edge of the navigation bar.","type":"text"}],"sections":[],"metadata":{"title":"scrollEdgeAppearance","modules":[{"name":"UIKit"}],"platforms":[{"beta":false,"introducedAt":"13.0","deprecated":false,"name":"iOS","unavailable":false},{"beta":false,"introducedAt":"13.0","deprecated":false,"name":"iPadOS","unavailable":false},{"beta":false,"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst","unavailable":false},{"beta":false,"introducedAt":"13.0","deprecated":false,"name":"tvOS","unavailable":false},{"beta":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","unavailable":false}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)UINavigationBar(py)scrollEdgeAppearance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollEdgeAppearance"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UINavigationBarAppearance","kind":"typeIdentifier","text":"UINavigationBarAppearance"},{"kind":"text","text":"?"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"scrollEdgeAppearance"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]},"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UINavigationBar"}],"abstract":[{"type":"text","text":"Navigational controls that display in a bar along the top of the screen, usually in conjunction with a navigation controller."}],"title":"UINavigationBar","navigatorTitle":[{"kind":"identifier","text":"UINavigationBar"}],"url":"/documentation/uikit/uinavigationbar","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/isTranslucent":{"kind":"symbol","title":"isTranslucent","abstract":[{"type":"text","text":"A Boolean value that indicates whether the navigation bar is translucent."}],"url":"/documentation/uikit/uinavigationbar/istranslucent","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/isTranslucent","type":"topic","navigatorTitle":[{"kind":"identifier","text":"translucent"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTranslucent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/standardAppearance":{"title":"standardAppearance","navigatorTitle":[{"kind":"identifier","text":"standardAppearance"}],"role":"symbol","type":"topic","url":"/documentation/uikit/uinavigationbar/standardappearance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"standardAppearance"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UINavigationBarAppearance","kind":"typeIdentifier","text":"UINavigationBarAppearance"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/standardAppearance","abstract":[{"text":"The appearance settings for a standard-height navigation bar.","type":"text"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBarAppearance":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBarAppearance","type":"topic","navigatorTitle":[{"text":"UINavigationBarAppearance","kind":"identifier"}],"abstract":[{"text":"An object for customizing the appearance of a navigation bar.","type":"text"}],"role":"symbol","kind":"symbol","title":"UINavigationBarAppearance","url":"/documentation/uikit/uinavigationbarappearance","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UINavigationBarAppearance","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/prefersLargeTitles":{"url":"/documentation/uikit/uinavigationbar/preferslargetitles","navigatorTitle":[{"text":"prefersLargeTitles","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/prefersLargeTitles","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prefersLargeTitles","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"A Boolean value that indicates whether the title displays in a large format.","type":"text"}],"title":"prefersLargeTitles","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/uinavigationbar-legacy-customizations":{"identifier":"doc://com.apple.uikit/documentation/UIKit/uinavigationbar-legacy-customizations","title":"Legacy customizations","kind":"article","type":"topic","role":"collectionGroup","abstract":[{"text":"Customize appearance information directly on the navigation bar object.","type":"text"}],"url":"/documentation/uikit/uinavigationbar-legacy-customizations"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/scrollEdgeAppearance":{"abstract":[{"text":"The appearance settings for the navigation bar when the edge of scrollable content aligns with the edge of the navigation bar.","type":"text"}],"navigatorTitle":[{"text":"scrollEdgeAppearance","kind":"identifier"}],"url":"/documentation/uikit/uinavigationbar/scrolledgeappearance","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollEdgeAppearance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationBarAppearance","text":"UINavigationBarAppearance","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"scrollEdgeAppearance","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/scrollEdgeAppearance","type":"topic","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactAppearance":{"role":"symbol","url":"/documentation/uikit/uinavigationbar/compactappearance","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"compactAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINavigationBarAppearance","preciseIdentifier":"c:objc(cs)UINavigationBarAppearance"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactAppearance","abstract":[{"text":"The appearance settings for a compact-height navigation bar.","type":"text"}],"title":"compactAppearance","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"compactAppearance"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactScrollEdgeAppearance":{"navigatorTitle":[{"text":"compactScrollEdgeAppearance","kind":"identifier"}],"role":"symbol","type":"topic","title":"compactScrollEdgeAppearance","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compactScrollEdgeAppearance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationBarAppearance","text":"UINavigationBarAppearance","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The appearance settings for a compact-height navigation bar when the edge of scrollable content aligns with the edge of the navigation bar.","type":"text"}],"url":"/documentation/uikit/uinavigationbar/compactscrolledgeappearance","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactScrollEdgeAppearance"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"introducedAt":"13.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"introducedAt":"13.0","unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1"},{"deprecated":false,"beta":false,"name":"tvOS","unavailable":false,"introducedAt":"13.0"},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"scrollEdgeAppearance","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"scrollEdgeAppearance","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationBar"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationBar/prefersLargeTitles","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/standardAppearance","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactAppearance","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactScrollEdgeAppearance","doc://com.apple.uikit/documentation/UIKit/UINavigationBar/isTranslucent","doc://com.apple.uikit/documentation/UIKit/uinavigationbar-legacy-customizations"],"title":"Customizing the bar’s appearance","generated":true,"anchor":"Customizing-the-bars-appearance"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UINavigationBarAppearance","kind":"typeIdentifier","text":"UINavigationBarAppearance","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationBarAppearance"},{"kind":"text","text":" * "},{"kind":"identifier","text":"scrollEdgeAppearance"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","value":"UINavigationBar","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/title"},{"op":"replace","value":[{"text":"UINavigationBar","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UINavigationBar"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/navigatorTitle"},{"op":"replace","value":"translucent","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1isTranslucent/title"},{"op":"replace","value":[{"text":"translucent","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1isTranslucent/fragments"},{"op":"replace","value":"standardAppearance","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1standardAppearance/title"},{"op":"replace","value":[{"text":"standardAppearance","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1standardAppearance/fragments"},{"op":"replace","value":"UINavigationBarAppearance","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBarAppearance/title"},{"op":"replace","value":[{"text":"UINavigationBarAppearance","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBarAppearance/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UINavigationBarAppearance"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBarAppearance/navigatorTitle"},{"op":"replace","value":"prefersLargeTitles","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1prefersLargeTitles/title"},{"op":"replace","value":[{"kind":"identifier","text":"prefersLargeTitles"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1prefersLargeTitles/fragments"},{"op":"replace","value":"scrollEdgeAppearance","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1scrollEdgeAppearance/title"},{"op":"replace","value":[{"kind":"identifier","text":"scrollEdgeAppearance"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1scrollEdgeAppearance/fragments"},{"op":"replace","value":"compactAppearance","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1compactAppearance/title"},{"op":"replace","value":[{"text":"compactAppearance","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1compactAppearance/fragments"},{"op":"replace","value":"compactScrollEdgeAppearance","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1compactScrollEdgeAppearance/title"},{"op":"replace","value":[{"kind":"identifier","text":"compactScrollEdgeAppearance"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1compactScrollEdgeAppearance/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}